import { type Dictionary, t } from 'intlayer';

export const registerStepContent = {
  key: 'register-step',
  content: {
    title: t({
      en: 'Create your account',
      'en-GB': 'Create your account',
      fr: 'Créez votre compte',
      es: 'Crea tu cuenta',
      de: 'Erstellen Sie Ihr Konto',
      ja: 'アカウントを作成する',
      ko: '계정을 만드세요',
      zh: '创建您的帐户',
      it: 'Crea il tuo account',
      pt: 'Crie sua conta',
      hi: 'अपना खाता बनाएं',
      ar: 'إنشاء حسابك',
      ru: 'Создайте свою учетную запись',
      tr: 'Hesabınızı oluşturun',
      pl: 'Utwórz konto',
      id: 'Buat akun Anda',
      vi: 'Tạo tài khoản của bạn',
    }),

    emailInput: {
      label: t({
        en: 'Email address',
        'en-GB': 'Email address',
        fr: 'Adresse e-mail',
        es: 'Dirección de correo electrónico',
        de: 'E-Mail-Adresse',
        ja: 'メールアドレス',
        ko: '이메일 주소',
        zh: '电子邮件地址',
        it: 'Indirizzo email',
        pt: 'Endereço de e-mail',
        hi: 'ईमेल पता',
        ar: 'عنوان البريد الإلكتروني',
        ru: 'Адрес электронной почты',
        tr: 'E-posta adresi',
        pl: 'Adres e-mail',
        id: 'Alamat email',
        vi: 'Địa chỉ email',
      }),
      placeholder: t({
        en: 'Enter e-mail address',
        'en-GB': 'Enter e-mail address',
        fr: 'Entrez votre adresse e-mail',
        es: 'Ingrese su dirección de correo electrónico',
        de: 'E-Mail-Adresse eingeben',
        ja: 'メールアドレスを入力してください',
        ko: '이메일 주소를 입력하세요',
        zh: '请输入电子邮件地址',
        it: "Inserisci l'indirizzo email",
        pt: 'Digite o endereço de e-mail',
        hi: 'ईमेल पता दर्ज करें',
        ar: 'أدخل عنوان البريد الإلكتروني',
        ru: 'Введите адрес электронной почты',
        tr: 'E-posta adresinizi girin',
        pl: 'Wprowadź adres e-mail',
        id: 'Masukkan alamat email',
        vi: 'Nhập địa chỉ email',
      }),
    },

    loginLink: {
      message: t({
        en: 'You already have an account?',
        'en-GB': 'You already have an account?',
        fr: 'Vous avez déjà un compte ?',
        es: '¿Ya tienes una cuenta?',
        de: 'Sie haben bereits ein Konto?',
        ja: 'すでにアカウントをお持ちですか？',
        ko: '계정이 이미 있습니까?',
        zh: '您已经有一个帐户了吗？',
        it: 'Hai già un account?',
        pt: 'Você já tem uma conta?',
        hi: 'क्या आपके पास पहले से एक खाता है?',
        ar: 'هل لديك حساب بالفعل؟',
        ru: 'У вас уже есть учетная запись?',
        tr: 'Zaten bir hesabınız var mı?',
        pl: 'Masz już konto?',
        id: 'Sudah punya akun?',
        vi: 'Bạn đã có tài khoản?',
      }),
      text: t({
        en: 'Log in',
        'en-GB': 'Log in',
        fr: 'Se connecter',
        es: 'Iniciar sesión',
        de: 'Einloggen',
        ja: 'ログイン',
        ko: '로그인',
        zh: '登录',
        it: 'Accedi',
        pt: 'Entrar',
        hi: 'लॉग इन करें',
        ar: 'تسجيل الدخول',
        ru: 'Войти',
        tr: 'Giriş yapın',
        pl: 'Zaloguj się',
        id: 'Log in',
        vi: 'Đăng nhập',
      }),
      ariaLabel: t({
        en: 'Click to go to login page',
        'en-GB': 'Click to go to login page',
        fr: 'Cliquez pour aller à la page de connexion',
        es: 'Haz clic para ir a la página de inicio de sesión',
        de: 'Klicken Sie, um zur Anmeldeseite zu gelangen',
        ja: 'ログインページに移動するにはクリックしてください',
        ko: '로그인 페이지로 이동하려면 클릭하세요',
        zh: '点击以转到登录页面',
        it: 'Fai clic per andare alla pagina di login',
        pt: 'Clique para ir para a página de login',
        hi: 'लॉगिन पृष्ठ पर जाने के लिए क्लिक करें',
        ar: 'انقر للانتقال إلى صفحة تسجيل الدخول',
        ru: 'Нажмите, чтобы перейти на страницу входа',
        tr: 'Giriş sayfasına gitmek için tıklayın',
        pl: 'Kliknij, aby przejść do strony logowania',
        id: 'Klik untuk menuju halaman login',
        vi: 'Nhấp để đến trang đăng nhập',
      }),
    },
  },
  title: 'Register step content',
  description:
    'Content declarations for the register step component, including form labels, placeholders, and links related to account creation.',
  tags: ['register', 'onboarding', 'form'],
} satisfies Dictionary;

export default registerStepContent;
