import { type DeclarationContent, t } from 'intlayer';

export const registerStepContent = {
  key: 'register-step',
  content: {
    title: t({
      en: 'Create your account',
      'en-GB': 'Create your account',
      fr: 'Créez votre compte',
      es: 'Crea tu cuenta',
      de: 'Erstellen Sie Ihr Konto',
      ja: 'アカウントを作成する',
      ko: '계정을 만드세요',
      zh: '创建您的帐户',
      it: 'Crea il tuo account',
      pt: 'Crie sua conta',
      hi: 'अपना खाता बनाएं',
      ar: 'إنشاء حسابك',
      ru: 'Создайте свою учетную запись',
    }),

    emailInput: {
      label: t({
        en: 'Email address',
        'en-GB': 'Email address',
        fr: 'Adresse e-mail',
        es: 'Dirección de correo electrónico',
        de: 'E-Mail-Adresse',
        ja: 'メールアドレス',
        ko: '이메일 주소',
        zh: '电子邮件地址',
        it: 'Indirizzo email',
        pt: 'Endereço de e-mail',
        hi: 'ईमेल पता',
        ar: 'عنوان البريد الإلكتروني',
        ru: 'Адрес электронной почты',
      }),
      placeholder: t({
        en: 'Enter e-mail address',
        'en-GB': 'Enter e-mail address',
        fr: 'Entrez votre adresse e-mail',
        es: 'Ingrese su dirección de correo electrónico',
        de: 'E-Mail-Adresse eingeben',
        ja: 'メールアドレスを入力してください',
        ko: '이메일 주소를 입력하세요',
        zh: '请输入电子邮件地址',
        it: "Inserisci l'indirizzo email",
        pt: 'Digite o endereço de e-mail',
        hi: 'ईमेल पता दर्ज करें',
        ar: 'أدخل عنوان البريد الإلكتروني',
        ru: 'Введите адрес электронной почты',
      }),
    },

    loginLink: {
      message: t({
        en: 'You already have an account?',
        'en-GB': 'You already have an account?',
        fr: 'Vous avez déjà un compte ?',
        es: '¿Ya tienes una cuenta?',
        de: 'Sie haben bereits ein Konto?',
        ja: 'すでにアカウントをお持ちですか？',
        ko: '계정이 이미 있습니까?',
        zh: '您已经有一个帐户了吗？',
        it: 'Hai già un account?',
        pt: 'Você já tem uma conta?',
        hi: 'क्या आपके पास पहले से एक खाता है?',
        ar: 'هل لديك حساب بالفعل؟',
        ru: 'У вас уже есть учетная запись?',
      }),
      text: t({
        en: 'Log in',
        'en-GB': 'Log in',
        fr: 'Se connecter',
        es: 'Iniciar sesión',
        de: 'Einloggen',
        ja: 'ログイン',
        ko: '로그인',
        zh: '登录',
        it: 'Accedi',
        pt: 'Entrar',
        hi: 'लॉग इन करें',
        ar: 'تسجيل الدخول',
        ru: 'Войти',
      }),
      ariaLabel: t({
        en: 'Click to go to login page',
        'en-GB': 'Click to go to login page',
        fr: 'Cliquez pour aller à la page de connexion',
        es: 'Haz clic para ir a la página de inicio de sesión',
        de: 'Klicken Sie, um zur Anmeldeseite zu gelangen',
        ja: 'ログインページに移動するにはクリックしてください',
        ko: '로그인 페이지로 이동하려면 클릭하세요',
        zh: '点击以转到登录页面',
        it: 'Fai clic per andare alla pagina di login',
        pt: 'Clique para ir para a página de login',
        hi: 'लॉगिन पृष्ठ पर जाने के लिए क्लिक करें',
        ar: 'انقر للانتقال إلى صفحة تسجيل الدخول',
        ru: 'Нажмите, чтобы перейти на страницу входа',
      }),
    },
  },
} satisfies DeclarationContent;

export default registerStepContent;
