import { type Dictionary, t } from 'intlayer';

export default {
  key: 'website-structured-data',
  content: {
    keywords: t<string[]>({
      en: [
        'translation',
        'localization',
        'multilingual',
        'Internationalization',
        'i18n',
        'Web Development',
        'Next.js',
        'JavaScript',
        'Vite',
        'React',
        'CMS',
        'Content Management System',
      ],
      fr: [
        'Traduction',
        'Localisation',
        'Multilingue',
        'SEO',
        'Internationalisation',
        'i18n',
        'Développement Web',
        'Next.js',
        'JavaScript',
        'Vite',
        'React',
        'CMS',
        'Content Management System',
      ],
      es: [
        'Traducción',
        'Localización',
        'Multilingüe',
        'SEO',
        'Internacionalización',
        'i18n',
        'Next.js',
        'Desarrollo Web',
        'JavaScript',
        'Vite',
        'React',
        'CMS',
        'Content Management System',
      ],
      'en-GB': [
        'translation',
        'localisation',
        'multilingual',
        'Internationalization',
        'i18n',
        'Web Development',
        'Next.js',
        'JavaScript',
        'Vite',
        'React',
        'CMS',
        'Content Management System',
      ],
      de: [
        'Übersetzung',
        'Lokalisierung',
        'Mehrsprachig',
        'SEO',
        'Internationalisierung',
        'i18n',
        'Webentwicklung',
        'Next.js',
        'JavaScript',
        'Vite',
        'React',
        'CMS',
        'Content-Management-System',
      ],
      it: [
        'Traduzione',
        'Localizzazione',
        'Multilingue',
        'SEO',
        'Internazionalizzazione',
        'i18n',
        'Sviluppo Web',
        'Next.js',
        'JavaScript',
        'Vite',
        'React',
        'CMS',
        'Sistema di gestione dei contenuti',
      ],
      ja: [
        '翻訳',
        'ローカリゼーション',
        '多言語',
        'SEO',
        '国際化',
        'i18n',
        'ウェブ開発',
        'Next.js',
        'JavaScript',
        'Vite',
        'React',
        'CMS',
        'コンテンツ管理システム',
      ],
      ko: [
        '번역',
        '현지화',
        '다국어',
        'SEO',
        '국제화',
        'i18n',
        '웹 개발',
        'Next.js',
        'JavaScript',
        'Vite',
        'React',
        'CMS',
        '콘텐츠 관리 시스템',
      ],
      zh: [
        '翻译',
        '本地化',
        '多语言',
        'SEO',
        '国际化',
        'i18n',
        '网页开发',
        'Next.js',
        'JavaScript',
        'Vite',
        'React',
        'CMS',
        '内容管理系统',
      ],
      pt: [
        'Tradução',
        'Localização',
        'Multilíngue',
        'SEO',
        'Internacionalização',
        'i18n',
        'Desenvolvimento Web',
        'Next.js',
        'JavaScript',
        'Vite',
        'React',
        'CMS',
        'Sistema de Gestão de Conteúdo',
      ],
      hi: [
        'अनुवाद',
        'स्थानीयकरण',
        'बहुभाषी',
        'एसईओ',
        'अंतर्राष्ट्रीयकरण',
        'i18n',
        'वेब विकास',
        'Next.js',
        'जावास्क्रिप्ट',
        'Vite',
        'React',
        'CMS',
        'सामग्री प्रबंधन प्रणाली',
      ],
      ar: [
        'ترجمة',
        'توطين',
        'متعدد اللغات',
        'SEO',
        'التدويل',
        'i18n',
        'تطوير الويب',
        'Next.js',
        'جافا سكريبت',
        'Vite',
        'React',
        'CMS',
        'نظام إدارة المحتوى',
      ],
      ru: [
        'перевод',
        'локализация',
        'многоязычный',
        'SEO',
        'интернационализация',
        'i18n',
        'веб-разработка',
        'Next.js',
        'JavaScript',
        'Vite',
        'React',
        'CMS',
        'Система управления контентом',
      ],
      tr: [
        'çeviri',
        'yerelleştirme',
        'çok dilli',
        'Uluslararasılaştırma',
        'i18n',
        'Web Geliştirme',
        'Next.js',
        'JavaScript',
        'Vite',
        'React',
        'CMS',
        'İçerik Yönetim Sistemi',
      ],
      pl: [
        'tłumaczenie',
        'lokalizacja',
        'wielojęzyczność',
        'internacjonalizacja',
        'i18n',
        'tworzenie stron internetowych',
        'Next.js',
        'JavaScript',
        'Vite',
        'React',
        'CMS',
        'system zarządzania treścią',
      ],
      id: [
        'terjemahan',
        'lokalisasi',
        'multibahasa',
        'Internasionalisasi',
        'i18n',
        'Pengembangan Web',
        'Next.js',
        'JavaScript',
        'Vite',
        'React',
        'CMS',
        'Sistem Manajemen Konten',
      ],
      vi: [
        'dịch thuật',
        'bản địa hóa',
        'đa ngôn ngữ',
        'quốc tế hóa',
        'i18n',
        'phát triển web',
        'Next.js',
        'JavaScript',
        'Vite',
        'React',
        'CMS',
        'Hệ thống quản lý nội dung',
      ],
      uk: [
        'переклад',
        'локалізація',
        'багатомовний',
        'інтернаціоналізація',
        'i18n',
        'веб-розробка',
        'Next.js',
        'JavaScript',
        'Vite',
        'React',
        'CMS',
        'система управління контентом',
      ],
    }),
  },
  title: 'Website structured data',
  description:
    'Structured data for the website including keywords related to internationalization, localization, web development, and CMS technologies for enhanced SEO.',
  tags: ['structured data', 'SEO', 'website metadata'],
} satisfies Dictionary;
