import { type Dictionary, t } from 'intlayer';

const tagListContent = {
  key: 'tag-list',
  content: {
    noTagView: {
      title: t({
        en: 'No tags',
        fr: 'Aucun tag',
        es: 'Sin tag',
        'en-GB': 'No tags',
        de: 'Kein Tag',
        ja: 'タグなし',
        ko: '태그 없음',
        zh: '没有标签',
        it: 'Nessun tag',
        pt: 'Sem tag',
        hi: 'कोई टैग नहीं',
        ar: 'لا يوجد علامات',
        ru: 'Нет тегов',
        tr: 'Etiket yok',
        pl: 'Brak tagów',
        id: 'Belum ada tag',
        vi: 'Chưa có tag nào',
        uk: 'Немає тегів',
      }),
      description: t({
        en: 'Create your first tag to indicate how AI can structure your content',
        fr: 'Créez votre premier tag pour indiquer comment l’IA peut structurer votre contenu',
        es: 'Cree su primer tag para indicar cómo la IA puede estructurar su contenido',
        'en-GB':
          'Create your first tag to indicate how AI can structure your content',
        de: 'Erstellen Sie Ihr erstes Tag, um anzugeben, wie die KI Ihren Inhalt strukturieren kann',
        ja: 'AIがコンテンツを構成する方法を示すために、最初のタグを作成してください',
        ko: 'AI가 콘텐츠를 구성하는 방법을 나타내는 첫 번째 태그를 만들어주세요',
        zh: '创建您的第一个标签，以指示 AI 如何构建您的内容',
        it: 'Crea il tuo primo tag per indicare come l’IA può strutturare il tuo contenuto',
        pt: 'Crie seu primeiro tag para indicar como a IA pode estruturar seu conteúdo',
        hi: 'अपनी सामग्री को AI कैसे संरचित कर सकती है इसे दिखाने के लिए अपना पहला टैग बनाएं',
        ar: 'أنشئ مشروعك الأول للبدء في استخدام Intlayer',
        ru: 'Создайте свой первый тег, чтобы показать, как ИИ может структурировать ваш контент',
        tr: 'İçeriğinizi yapay zekanın nasıl yapılandırabileceğini göstermek için ilk etiketinizi oluşturun',
        pl: 'Utwórz pierwszy tag, aby wskazać, jak AI może strukturyzować twoje treści',
        id: 'Buat tag pertama Anda untuk menunjukkan bagaimana AI dapat menyusun konten Anda',
        vi: 'Tạo tag đầu tiên để chỉ ra cách AI có thể cấu trúc nội dung của bạn',
        uk: 'Створіть перший тег, щоб вказати, як ШІ може структурувати ваш вміст',
      }),
    },

    selectAll: t({
      en: 'Select all tags',
      fr: 'Sélectionner tous les tags',
      es: 'Seleccionar todos los tags',
      'en-GB': 'Select all tags',
      de: 'Alle Tags auswählen',
      ja: 'すべてのタグを選択',
      ko: '모든 태그 선택',
      zh: '选择所有标签',
      it: 'Seleziona tutti i tag',
      pt: 'Selecionar todos os tags',
      hi: 'सभी टैग चुनें',
      ar: 'تحديد جميع الوسوم',
      ru: 'Выбрать все теги',
      tr: 'Tüm etiketleri seç',
      pl: 'Wybierz wszystkie tagi',
      id: 'Pilih semua tag',
      vi: 'Chọn tất cả tag',
      uk: 'Вибрати всі теги',
    }),

    selectRow: t({
      en: 'Select tag',
      fr: 'Sélectionner le tag',
      es: 'Seleccionar tag',
      'en-GB': 'Select tag',
      de: 'Tag auswählen',
      ja: 'タグを選択',
      ko: '태그 선택',
      zh: '选择标签',
      it: 'Seleziona tag',
      pt: 'Selecionar tag',
      hi: 'टैग चुनें',
      ar: 'تحديد الوسم',
      ru: 'Выбрать тег',
      tr: 'Etiketi seç',
      pl: 'Wybierz tag',
      id: 'Pilih tag',
      vi: 'Chọn tag',
      uk: 'Вибрати тег',
    }),

    deleteSelectedButton: {
      text: t({
        en: 'Delete',
        fr: 'Supprimer',
        es: 'Eliminar',
        'en-GB': 'Delete',
        de: 'Löschen',
        ja: '削除',
        ko: '삭제',
        zh: '删除',
        it: 'Elimina',
        pt: 'Excluir',
        hi: 'हटाएं',
        ar: 'حذف',
        ru: 'Удалить',
        tr: 'Sil',
        pl: 'Usuń',
        id: 'Hapus',
        vi: 'Xóa',
        uk: 'Видалити',
      }),
      label: t({
        en: 'Delete selected tags',
        fr: 'Supprimer les tags sélectionnés',
        es: 'Eliminar los tags seleccionados',
        'en-GB': 'Delete selected tags',
        de: 'Ausgewählte Tags löschen',
        ja: '選択したタグを削除',
        ko: '선택한 태그 삭제',
        zh: '删除所选标签',
        it: 'Elimina i tag selezionati',
        pt: 'Excluir tags selecionados',
        hi: 'चयनित टैग्स हटाएं',
        ar: 'حذف الوسوم المختارة',
        ru: 'Удалить выбранные теги',
        tr: 'Seçilen etiketleri sil',
        pl: 'Usuń wybrane tagi',
        id: 'Hapus tag yang dipilih',
        vi: 'Xóa các tag đã chọn',
        uk: 'Видалити вибрані теги',
      }),
    },

    searchPlaceholder: t({
      en: 'Search tags...',
      fr: 'Rechercher des tags...',
      es: 'Buscar tags...',
      'en-GB': 'Search tags...',
      de: 'Tags suchen...',
      ja: 'タグを検索...',
      ko: '태그 검색...',
      zh: '搜索标签...',
      it: 'Cerca tag...',
      pt: 'Pesquisar tags...',
      hi: 'टैग खोजें...',
      ar: 'البحث عن وسوم...',
      ru: 'Поиск тегов...',
      tr: 'Etiket ara...',
      pl: 'Szukaj tagów...',
      id: 'Cari tag...',
      vi: 'Tìm kiếm tag...',
      uk: 'Пошук тегів...',
    }),

    tableHeaders: {
      key: t({
        en: 'Key',
        fr: 'Clé',
        es: 'Clave',
        'en-GB': 'Key',
        de: 'Schlüssel',
        ja: 'キー',
        ko: '키',
        zh: '键',
        it: 'Chiave',
        pt: 'Chave',
        hi: 'कुंजी',
        ar: 'المفتاح',
        ru: 'Ключ',
        tr: 'Anahtar',
        pl: 'Klucz',
        id: 'Kunci',
        vi: 'Khóa',
        uk: 'Ключ',
      }),
      name: t({
        en: 'Name',
        fr: 'Nom',
        es: 'Nombre',
        'en-GB': 'Name',
        de: 'Name',
        ja: '名前',
        ko: '이름',
        zh: '名称',
        it: 'Nome',
        pt: 'Nome',
        hi: 'नाम',
        ar: 'الاسم',
        ru: 'Имя',
        tr: 'Ad',
        pl: 'Nazwa',
        id: 'Nama',
        vi: 'Tên',
        uk: 'Назва',
      }),
      description: t({
        en: 'Description',
        fr: 'Description',
        es: 'Descripción',
        'en-GB': 'Description',
        de: 'Beschreibung',
        ja: '説明',
        ko: '설명',
        zh: '描述',
        it: 'Descrizione',
        pt: 'Descrição',
        hi: 'विवरण',
        ar: 'الوصف',
        ru: 'Описание',
        tr: 'Açıklama',
        pl: 'Opis',
        id: 'Deskripsi',
        vi: 'Mô tả',
        uk: 'Опис',
      }),
      createdAt: t({
        en: 'Created',
        fr: 'Créé',
        es: 'Creado',
        'en-GB': 'Created',
        de: 'Erstellt',
        ja: '作成日',
        ko: '생성일',
        zh: '创建时间',
        it: 'Creato',
        pt: 'Criado',
        hi: 'बनाया गया',
        ar: 'تاريخ الإنشاء',
        ru: 'Создан',
        tr: 'Oluşturuldu',
        pl: 'Utworzono',
        id: 'Dibuat',
        vi: 'Ngày tạo',
        uk: 'Створено',
      }),
      actions: t({
        en: 'Actions',
        fr: 'Actions',
        es: 'Acciones',
        'en-GB': 'Actions',
        de: 'Aktionen',
        ja: 'アクション',
        ko: '작업',
        zh: '操作',
        it: 'Azioni',
        pt: 'Ações',
        hi: 'क्रियाएँ',
        ar: 'الإجراءات',
        ru: 'Действия',
        tr: 'İşlemler',
        pl: 'Akcje',
        id: 'Tindakan',
        vi: 'Hành động',
        uk: 'Дії',
      }),
    },

    createTagButton: {
      text: t({
        en: 'Create tag',
        fr: 'Créer un tag',
        es: 'Crear un tag',
        'en-GB': 'Create tag',
        de: 'Tag erstellen',
        ja: 'タグを作成',
        ko: '태그 만들기',
        zh: '创建标签',
        it: 'Crea tag',
        pt: 'Criar tag',
        hi: 'टैग बनाएँ',
        ar: 'إنشاء وسم',
        ru: 'Создать тег',
        tr: 'Etiket oluştur',
        pl: 'Utwórz tag',
        id: 'Buat tag',
        vi: 'Tạo tag',
        uk: 'Створити тег',
      }),
      ariaLabel: t({
        en: 'Click to create tag',
        fr: 'Cliquez pour créer un tag',
        es: 'Haga clic para crear un tag',
        'en-GB': 'Click to create tag',
        de: 'Klicken Sie, um ein Tag zu erstellen',
        ja: 'タグを作成するにはクリックしてください',
        ko: '태그를 만들려면 클릭하세요',
        zh: '点击创建标签',
        it: 'Clicca per creare il tag',
        pt: 'Clique para criar o tag',
        hi: 'टैग बनाने के लिए क्लिक करें',
        ar: 'انقر لإنشاء وسم',
        ru: 'Нажмите, чтобы создать тег',
        tr: 'Etiket oluşturmak için tıklayın',
        pl: 'Kliknij, aby utworzyć tag',
        id: 'Klik untuk membuat tag',
        vi: 'Nhấp để tạo tag',
        uk: 'Натисніть, щоб створити тег',
      }),
    },
  },
  title: 'Tag list',
  description:
    'Content declaration for displaying and managing the list of tags in the dashboard. Includes messages for empty states and actions to create new tags.',
  tags: ['dashboard', 'tag management'],
} satisfies Dictionary;

export default tagListContent;
