import { type Dictionary, t } from 'intlayer';

export const browserContent = {
  key: 'browser',
  content: {
    ariaLabel: t({
      en: 'Embedded browser',
      'en-GB': 'Embedded browser',
      fr: 'Navigateur intégré',
      es: 'Navegador integrado',
      de: 'Eingebetteter Browser',
      ja: '埋め込みブラウザ',
      ko: '임베디드 브라우저',
      zh: '嵌入式浏览器',
      it: 'Browser incorporato',
      pt: 'Navegador incorporado',
      hi: 'एम्बेडेड ब्राउज़र',
      ar: 'متصفح مدمج',
      ru: 'Встроенный браузер',
      tr: 'Gömülü tarayıcı',
      pl: 'Osadzona przeglądarka',
      id: 'Peramban tertanam',
      vi: 'Trình duyệt nhúng',
    }),
    urlLabel: t({
      en: 'URL address bar',
      'en-GB': 'URL address bar',
      fr: "Barre d'adresse URL",
      es: 'Barra de direcciones URL',
      de: 'URL-Adressleiste',
      ja: 'URLアドレスバー',
      ko: 'URL 주소 표시줄',
      zh: 'URL地址栏',
      it: 'Barra degli indirizzi URL',
      pt: 'Barra de endereços URL',
      hi: 'URL पता बार',
      ar: 'شريط عنوان URL',
      ru: 'Адресная строка URL',
      tr: 'URL adres çubuğu',
      pl: 'Pasek adresu URL',
      id: 'Bilah alamat URL',
      vi: 'Thanh địa chỉ URL',
    }),
    urlPlaceholder: 'https://example.com',
    errorMessage: t({
      en: 'Invalid URL. Try a path like "/page" or a full URL.',
      'en-GB': 'Invalid URL. Try a path like "/page" or a full URL.',
      fr: 'URL invalide. Essayez un chemin comme "/page" ou une URL complète.',
      es: 'URL no válida. Intente una ruta como "/page" o una URL completa.',
      de: 'Ungültige URL. Versuchen Sie einen Pfad wie "/page" oder eine vollständige URL.',
      ja: '無効なURL。"/page"のようなパスまたは完全なURLを試してください。',
      ko: '잘못된 URL입니다. "/page"와 같은 경로 또는 전체 URL을 시도하십시오.',
      zh: '无效的URL。尝试像"/page"这样的路径或完整的URL。',
      it: 'URL non valido. Prova un percorso come "/page" o un URL completo.',
      pt: 'URL inválido. Tente um caminho como "/page" ou uma URL completa.',
      hi: 'अमान्य URL। "/page" जैसा पथ या पूर्ण URL प्रयास करें।',
      ar: 'رابط غير صالح. جرب مسارًا مثل "/page" أو رابطًا كاملاً.',
      ru: 'Неверный URL. Попробуйте путь вроде "/page" или полный URL.',
      tr: 'Geçersiz URL. "/page" gibi bir yol veya tam URL deneyin.',
      pl: 'Nieprawidłowy adres URL. Wypróbuj ścieżkę jak "/page" lub pełny URL.',
      id: 'URL tidak valid. Coba jalur seperti "/page" atau URL lengkap.',
      vi: 'URL không hợp lệ. Thử đường dẫn như "/page" hoặc URL đầy đủ.',
    }),
    domainRestrictionError: t({
      en: 'URL must match the application domain.',
      'en-GB': 'URL must match the application domain.',
      fr: "L'URL doit correspondre au domaine de l'application.",
      es: 'La URL debe coincidir con el dominio de la aplicación.',
      de: 'Die URL muss mit der Anwendungsdomäne übereinstimmen.',
      ja: 'URLはアプリケーションドメインと一致する必要があります。',
      ko: 'URL은 애플리케이션 도메인과 일치해야 합니다.',
      zh: 'URL必须与应用程序域名匹配。',
      it: "L'URL deve corrispondere al dominio dell'applicazione.",
      pt: 'A URL deve corresponder ao domínio da aplicação.',
      hi: 'URL एप्लिकेशन डोमेन से मेल खाना चाहिए।',
      ar: 'يجب أن يتطابق الرابط مع نطاق التطبيق.',
      ru: 'URL должен соответствовать домену приложения.',
      tr: 'URL, uygulama etki alanıyla eşleşmelidir.',
      pl: 'Adres URL musi pasować do domeny aplikacji.',
      id: 'URL harus cocok dengan domain aplikasi.',
      vi: 'URL phải khớp với tên miền ứng dụng.',
    }),
    reloadButtonTitle: t({
      en: 'Reload page',
      'en-GB': 'Reload page',
      fr: 'Recharger la page',
      es: 'Recargar página',
      de: 'Seite neu laden',
      ja: 'ページを再読み込み',
      ko: '페이지 새로고침',
      zh: '重新加载页面',
      it: 'Ricarica pagina',
      pt: 'Recarregar página',
      hi: 'पृष्ठ को फिर से लोड करें',
      ar: 'إعادة تحميل الصفحة',
      ru: 'Перезагрузить страницу',
      tr: 'Sayfayı yenile',
      pl: 'Przeładuj stronę',
      id: 'Muat ulang halaman',
      vi: 'Tải lại trang',
    }),
    iframeTitle: t({
      en: 'Embedded web page',
      'en-GB': 'Embedded web page',
      fr: 'Page web intégrée',
      es: 'Página web integrada',
      de: 'Eingebettete Webseite',
      ja: '埋め込みウェブページ',
      ko: '임베디드 웹페이지',
      zh: '嵌入式网页',
      it: 'Pagina web incorporata',
      pt: 'Página web incorporada',
      hi: 'एम्बेडेड वेब पेज',
      ar: 'صفحة ويب مدمجة',
      ru: 'Встроенная веб-страница',
      tr: 'Gömülü web sayfası',
      pl: 'Osadzona strona internetowa',
      id: 'Halaman web tertanam',
      vi: 'Trang web được nhúng',
    }),
  },
  title: 'Embedded browser component',
  description:
    'Content declaration for the embedded browser UI component, including ARIA labels, URL placeholder, and error messages for displaying web pages within an iframe.',
  tags: ['UI component', 'embedded browser', 'iframe'],
} satisfies Dictionary;

export default browserContent;
