import { cond, type Dictionary, t } from 'intlayer';

export const externalsLoginButtonsContent = {
  key: 'externals-login-buttons',
  content: {
    github: {
      label: t({
        en: 'Sign in with GitHub',
        fr: 'Se connecter avec GitHub',
        es: 'Iniciar sesión con GitHub',
        de: 'Mit GitHub anmelden',
        ja: 'GitHubでサインイン',
        ko: 'GitHub로 로그인',
        zh: '使用GitHub登录',
        it: 'Accedi con GitHub',
        pt: 'Entrar com o GitHub',
        hi: 'GitHub के साथ साइनइन करें',
        ar: 'تسجيل الدخول باستخدام GitHub',
        ru: 'Войти с GitHub',
        'en-GB': 'Sign in with GitHub',
        tr: 'GitHub ile giriş yap',
        pl: 'Zaloguj się przez GitHub',
        id: 'Masuk dengan GitHub',
        vi: 'Đăng nhập bằng GitHub',
      }),
      ariaLabel: t({
        en: 'Sign in with GitHub',
        fr: 'Se connecter avec GitHub',
        es: 'Iniciar sesión con GitHub',
        de: 'Mit GitHub anmelden',
        ja: 'GitHubでサインイン',
        ko: 'GitHub로 로그인',
        zh: '使用GitHub登录',
        it: 'Accedi con GitHub',
        pt: 'Entrar com o GitHub',
        hi: 'GitHub के साथ साइनइन करें',
        ar: 'تسجيل الدخول باستخدام GitHub',
        ru: 'Войти с GitHub',
        'en-GB': 'Sign in with GitHub',
        tr: 'GitHub ile giriş yap',
        pl: 'Zaloguj się przez GitHub',
        id: 'Masuk dengan GitHub',
        vi: 'Đăng nhập bằng GitHub',
      }),
    },
    google: {
      label: t({
        en: 'Sign in with Google',
        fr: 'Se connecter avec Google',
        es: 'Iniciar sesión con Google',
        de: 'Mit Google anmelden',
        ja: 'Googleでサインイン',
        ko: 'Google로 로그인',
        zh: '使用Google登录',
        it: 'Accedi con Google',
        pt: 'Entrar com o Google',
        hi: 'Google के साथ साइनइन करें',
        ar: 'تسجيل الدخول باستخدام Google',
        ru: 'Войти с Google',
        'en-GB': 'Sign in with Google',
        tr: 'Google ile giriş yap',
        pl: 'Zaloguj się przez Google',
        id: 'Masuk dengan Google',
        vi: 'Đăng nhập bằng Google',
      }),
      ariaLabel: t({
        en: 'Sign in with Google',
        fr: 'Se connecter avec Google',
        es: 'Iniciar sesión con Google',
        de: 'Mit Google anmelden',
        ja: 'Googleでサインイン',
        ko: 'Google로 로그인',
        zh: '使用Google登录',
        it: 'Accedi con Google',
        pt: 'Entrar com o Google',
        hi: 'Google के साथ साइनइन करें',
        ar: 'تسجيل الدخول باستخدام Google',
        ru: 'Войти с Google',
        'en-GB': 'Sign in with Google',
        tr: 'Google ile giriş yap',
        pl: 'Zaloguj się przez Google',
        id: 'Masuk dengan Google',
        vi: 'Đăng nhập bằng Google',
      }),
    },
    linkedin: {
      label: t({
        en: 'Sign in with LinkedIn',
        fr: 'Se connecter avec LinkedIn',
        es: 'Iniciar sesión con LinkedIn',
        de: 'Mit LinkedIn anmelden',
        ja: 'LinkedInでサインイン',
        ko: 'LinkedIn로 로그인',
        zh: '使用LinkedIn登录',
        it: 'Accedi con LinkedIn',
        pt: 'Entrar com o LinkedIn',
        hi: 'LinkedIn के साथ साइनइन करें',
        ar: 'تسجيل الدخول باستخدام LinkedIn',
        ru: 'Войти с LinkedIn',
        'en-GB': 'Sign in with LinkedIn',
        tr: 'LinkedIn ile giriş yap',
        pl: 'Zaloguj się przez LinkedIn',
        id: 'Masuk dengan LinkedIn',
        vi: 'Đăng nhập bằng LinkedIn',
      }),
      ariaLabel: t({
        en: 'Sign in with LinkedIn',
        fr: 'Se connecter avec LinkedIn',
        es: 'Iniciar sesión con LinkedIn',
        de: 'Mit LinkedIn anmelden',
        ja: 'LinkedInでサインイン',
        ko: 'LinkedIn로 로그인',
        zh: '使用LinkedIn登录',
        it: 'Accedi con LinkedIn',
        pt: 'Entrar com o LinkedIn',
        hi: 'LinkedIn के साथ साइनइन करें',
        ar: 'تسجيل الدخول باستخدام LinkedIn',
        ru: 'Войти с LinkedIn',
        'en-GB': 'Sign in with LinkedIn',
        tr: 'LinkedIn ile giriş yap',
        pl: 'Zaloguj się przez LinkedIn',
        id: 'Masuk dengan LinkedIn',
        vi: 'Đăng nhập bằng LinkedIn',
      }),
    },
    apple: {
      label: t({
        en: 'Sign in with Apple',
        fr: 'Se connecter avec Apple',
        es: 'Iniciar sesión con Apple',
        de: 'Mit Apple anmelden',
        ja: 'Appleでサインイン',
        ko: 'Apple로 로그인',
        zh: '使用Apple登录',
        it: 'Accedi con Apple',
        pt: 'Entrar com a Apple',
        hi: 'Apple के साथ साइनइन करें',
        ar: 'تسجيل الدخول باستخدام Apple',
        ru: 'Войти с Apple',
        'en-GB': 'Sign in with Apple',
        tr: 'Apple ile giriş yap',
        pl: 'Zaloguj się przez Apple',
        id: 'Masuk dengan Apple',
        vi: 'Đăng nhập bằng Apple',
      }),
      ariaLabel: t({
        en: 'Sign in with Apple',
        fr: 'Se connecter avec Apple',
        es: 'Iniciar sesión con Apple',
        de: 'Mit Apple anmelden',
        ja: 'Appleでサインイン',
        ko: 'Apple로 로그인',
        zh: '使用Apple登录',
        it: 'Accedi con Apple',
        pt: 'Entrar com a Apple',
        hi: 'Apple के साथ साइनइन करें',
        ar: 'تسجيل الدخول باستخدام Apple',
        ru: 'Войти с Apple',
        'en-GB': 'Sign in with Apple',
        tr: 'Apple ile giriş yap',
        pl: 'Zaloguj się przez Apple',
        id: 'Masuk dengan Apple',
        vi: 'Đăng nhập bằng Apple',
      }),
    },
    bitbucket: {
      label: t({
        en: 'Sign in with Bitbucket',
        fr: 'Se connecter avec Bitbucket',
        es: 'Iniciar sesión con Bitbucket',
        de: 'Mit Bitbucket anmelden',
        ja: 'Bitbucketでサインイン',
        ko: 'Bitbucket로 로그인',
        zh: '使用Bitbucket登录',
        it: 'Accedi con Bitbucket',
        pt: 'Entrar com o Bitbucket',
        hi: 'Bitbucket के साथ साइनइन करें',
        ar: 'تسجيل الدخول باستخدام Bitbucket',
        ru: 'Войти с Bitbucket',
        'en-GB': 'Sign in with Bitbucket',
        tr: 'Bitbucket ile giriş yap',
        pl: 'Zaloguj się przez Bitbucket',
        id: 'Masuk dengan Bitbucket',
        vi: 'Đăng nhập bằng Bitbucket',
      }),
      ariaLabel: t({
        en: 'Sign in with Bitbucket',
        fr: 'Se connecter avec Bitbucket',
        es: 'Iniciar sesión con Bitbucket',
        de: 'Mit Bitbucket anmelden',
        ja: 'Bitbucketでサインイン',
        ko: 'Bitbucket로 로그인',
        zh: '使用Bitbucket登录',
        it: 'Accedi con Bitbucket',
        pt: 'Entrar com o Bitbucket',
        hi: 'Bitbucket के साथ साइनइन करें',
        ar: 'تسجيل الدخول باستخدام Bitbucket',
        ru: 'Войти с Bitbucket',
        'en-GB': 'Sign in with Bitbucket',
        tr: 'Bitbucket ile giriş yap',
        pl: 'Zaloguj się przez Bitbucket',
        id: 'Masuk dengan Bitbucket',
        vi: 'Đăng nhập bằng Bitbucket',
      }),
    },
    gitlab: {
      label: t({
        en: 'Sign in with GitLab',
        fr: 'Se connecter avec GitLab',
        es: 'Iniciar sesión con GitLab',
        de: 'Mit GitLab anmelden',
        ja: 'GitLabでサインイン',
        ko: 'GitLab로 로그인',
        zh: '使用GitLab登录',
        it: 'Accedi con GitLab',
        pt: 'Entrar com o GitLab',
        hi: 'GitLab के साथ साइनइन करें',
        ar: 'تسجيل الدخول باستخدام GitLab',
        ru: 'Войти с GitLab',
        'en-GB': 'Sign in with GitLab',
        tr: 'GitLab ile giriş yap',
        pl: 'Zaloguj się przez GitLab',
        id: 'Masuk dengan GitLab',
        vi: 'Đăng nhập bằng GitLab',
      }),
      ariaLabel: t({
        en: 'Sign in with GitLab',
        fr: 'Se connecter avec GitLab',
        es: 'Iniciar sesión con GitLab',
        de: 'Mit GitLab anmelden',
        ja: 'GitLabでサインイン',
        ko: 'GitLab로 로그인',
        zh: '使用GitLab登录',
        it: 'Accedi con GitLab',
        pt: 'Entrar com o GitLab',
        hi: 'GitLab के साथ साइनइन करें',
        ar: 'تسجيل الدخول باستخدام GitLab',
        ru: 'Войти с GitLab',
        'en-GB': 'Sign in with GitLab',
        tr: 'GitLab ile giriş yap',
        pl: 'Zaloguj się przez GitLab',
        id: 'Masuk dengan GitLab',
        vi: 'Đăng nhập bằng GitLab',
      }),
    },
    showMore: cond({
      true: t({
        en: 'Show more login options',
        fr: "Afficher plus d'options de connexion",
        es: 'Mostrar más opciones de inicio de sesión',
        de: 'Weitere Anmeldeoptionen anzeigen',
        ja: 'その他のログインオプションを表示',
        ko: '더 많은 로그인 옵션 표시',
        zh: '显示更多登录选项',
        it: 'Mostra più opzioni di accesso',
        pt: 'Mostrar mais opções de login',
        hi: 'अधिक लॉगिन विकल्प दिखाएं',
        ar: 'عرض المزيد من خيارات تسجيل الدخول',
        ru: 'Показать больше вариантов входа',
        'en-GB': 'Show more login options',
        tr: 'Daha fazla giriş seçeneği göster',
        pl: 'Pokaż więcej opcji logowania',
        id: 'Tampilkan lebih banyak opsi login',
        vi: 'Hiển thị thêm tùy chọn đăng nhập',
      }),
      false: t({
        en: 'Show less',
        fr: 'Afficher moins',
        es: 'Mostrar menos',
        de: 'Weniger anzeigen',
        ja: '表示を減らす',
        ko: '간략히 보기',
        zh: '显示较少',
        it: 'Mostra meno',
        pt: 'Mostrar menos',
        hi: 'कम दिखाएँ',
        ar: 'عرض أقل',
        ru: 'Показать меньше',
        'en-GB': 'Show less',
        tr: 'Daha az göster',
        pl: 'Pokaż mniej',
        id: 'Tampilkan lebih sedikit',
        vi: 'Thu gọn',
      }),
    }),
  },
  title: 'External login buttons',
  description:
    'Content declarations for third-party login buttons such as GitHub, Google, LinkedIn, Apple, Bitbucket, and GitLab, used in the authentication components.',
  tags: ['authentication', 'login', 'third-party providers'],
} satisfies Dictionary;

export default externalsLoginButtonsContent;
