import { type DeclarationContent, t } from 'intlayer';

const cliLoginFlowContent = {
  key: 'cli-login-flow',
  content: {
    loginTitle: t({
      en: 'Login to CLI',
      'en-GB': 'Login to CLI',
      es: 'Iniciar sesión en CLI',
      fr: 'Connexion au CLI',
      ru: 'Вход в CLI',
      ja: 'CLI にログイン',
      ko: 'CLI에 로그인',
      zh: '登录到 CLI',
      de: 'Anmeldung am CLI',
      ar: 'تسجيل الدخول إلى CLI',
      it: 'Accedi al CLI',
      pt: 'Entrar no CLI',
      hi: 'CLI में लॉगिन करें',
      tr: "CLI'ye Giriş Yap",
      pl: 'Zaloguj się do CLI',
      id: 'Masuk ke CLI',
      vi: 'Đăng nhập vào CLI',
    }),
    selectOrganization: t({
      en: 'Select Organization',
      'en-GB': 'Select Organisation',
      es: 'Seleccionar organización',
      fr: 'Sélectionner une organisation',
      ru: 'Выберите организацию',
      ja: '組織を選択',
      ko: '조직 선택',
      zh: '选择组织',
      de: 'Organisation auswählen',
      ar: 'اختر المؤسسة',
      it: 'Seleziona organizzazione',
      pt: 'Selecionar organização',
      hi: 'संगठन चुनें',
      tr: 'Organizasyon Seç',
      pl: 'Wybierz organizację',
      id: 'Pilih Organisasi',
      vi: 'Chọn tổ chức',
    }),
    selectProject: t({
      en: 'Select Project',
      'en-GB': 'Select Project',
      es: 'Seleccionar proyecto',
      fr: 'Sélectionner un projet',
      ru: 'Выберите проект',
      ja: 'プロジェクトを選択',
      ko: '프로젝트 선택',
      zh: '选择项目',
      de: 'Projekt auswählen',
      ar: 'اختر المشروع',
      it: 'Seleziona progetto',
      pt: 'Selecionar projeto',
      hi: 'परियोजना चुनें',
      tr: 'Proje Seç',
      pl: 'Wybierz projekt',
      id: 'Pilih Proyek',
      vi: 'Chọn dự án',
    }),
    selectAccessKey: t({
      en: 'Select Access Key',
      'en-GB': 'Select Access Key',
      es: 'Seleccionar clave de acceso',
      fr: "Sélectionner une clé d'accès",
      ru: 'Выберите ключ доступа',
      ja: 'アクセスキーを選択',
      ko: '액세스 키 선택',
      zh: '选择访问密钥',
      de: 'Zugriffsschlüssel auswählen',
      ar: 'اختر مفتاح الوصول',
      it: "Seleziona chiave d'accesso",
      pt: 'Selecionar chave de acesso',
      hi: 'एक्सेस कुंजी चुनें',
      tr: 'Erişim Anahtarını Seç',
      pl: 'Wybierz klucz dostępu',
      id: 'Pilih Kunci Akses',
      vi: 'Chọn khóa truy cập',
    }),
    success: {
      title: t({
        en: 'Success!',
        'en-GB': 'Success!',
        es: '¡Éxito!',
        fr: 'Succès !',
        ru: 'Успех!',
        ja: '成功しました！',
        ko: '성공!',
        zh: '成功！',
        de: 'Erfolg!',
        ar: 'نجاح!',
        it: 'Successo!',
        pt: 'Sucesso!',
        hi: 'सफलता!',
        tr: 'Başarılı!',
        pl: 'Sukces!',
        id: 'Berhasil!',
        vi: 'Thành công!',
      }),
      message: t({
        en: 'You can close this tab and return to your terminal.',
        'en-GB': 'You can close this tab and return to your terminal.',
        es: 'Puedes cerrar esta pestaña y volver a tu terminal.',
        fr: 'Vous pouvez fermer cet onglet et retourner à votre terminal.',
        ru: 'Вы можете закрыть эту вкладку и вернуться к своему терминалу.',
        ja: 'このタブを閉じてターミナルに戻ることができます。',
        ko: '이 탭을 닫고 터미널로 돌아갈 수 있습니다.',
        zh: '您可以关闭此标签页并返回到您的终端。',
        de: 'Sie können diesen Tab schließen und zu Ihrem Terminal zurückkehren.',
        ar: 'يمكنك إغلاق هذا التبويب والعودة إلى الطرفية الخاصة بك.',
        it: 'Puoi chiudere questa scheda e tornare al tuo terminale.',
        pt: 'Você pode fechar esta guia e retornar ao seu terminal.',
        hi: 'आप इस टैब को बंद करके अपने टर्मिनल पर लौट सकते हैं।',
        tr: 'Bu sekmeyi kapatıp terminalinize dönebilirsiniz.',
        pl: 'Możesz zamknąć tę kartę i wrócić do swojego terminala.',
        id: 'Anda dapat menutup tab ini dan kembali ke terminal Anda.',
        vi: 'Bạn có thể đóng tab này và quay lại terminal của mình.',
      }),
    },
  },
} satisfies DeclarationContent;

export default cliLoginFlowContent;
