import { type Dictionary, insert, t } from 'intlayer';

const projectMembersFormContent = {
  key: 'project-members-form',

  content: {
    title: t({
      en: 'Members',
      es: 'Miembros',
      fr: 'Membres',
      'en-GB': 'Members',
      de: 'Mitglieder',
      ja: 'メンバー',
      ko: '회원',
      zh: '成员',
      it: 'Membri',
      pt: 'Membros',
      hi: 'सदस्य',
      ar: 'الأعضاء',
      ru: 'Члены',
      tr: 'Üyeler',
      pl: 'Członkowie',
      id: 'Anggota',
      vi: 'Thành viên',
      uk: 'Учасники',
    }),

    membersSelect: {
      label: t({
        en: 'Select members',
        es: 'Seleccionar miembros',
        fr: 'Sélectionner des membres',
        'en-GB': 'Select members',
        de: 'Mitglieder auswählen',
        ja: 'メンバーを選択',
        ko: '구성원 선택',
        zh: '选择成员',
        it: 'Seleziona membri',
        pt: 'Selecionar membros',
        hi: 'सदस्य चुनें',
        ar: 'اختر الأعضاء',
        ru: 'Выберите членов',
        tr: 'Üyeleri seçin',
        pl: 'Wybierz członków',
        id: 'Pilih anggota',
        vi: 'Chọn thành viên',
        uk: 'Виберіть учасників',
      }),
      placeholder: t({
        en: 'Select members',
        es: 'Seleccionar miembros',
        fr: 'Sélectionner des membres',
        'en-GB': 'Select members',
        de: 'Mitglieder auswählen',
        ja: 'メンバーを選択',
        ko: '구성원 선택',
        zh: '选择成员',
        it: 'Seleziona membri',
        pt: 'Selecionar membros',
        hi: 'सदस्य चुनें',
        ar: 'اختر الأعضاء',
        ru: 'Выберите членов',
        tr: 'Üyeleri seçin',
        pl: 'Wybierz członków',
        id: 'Pilih anggota',
        vi: 'Chọn thành viên',
        uk: 'Виберіть учасників',
      }),
      description: t({
        en: 'Members can view the project.',
        es: 'Los miembros pueden ver el proyecto.',
        fr: 'Les membres peuvent voir le projet.',
        'en-GB': 'Members can view the project.',
        de: 'Mitglieder können das Projekt einsehen.',
        ja: 'メンバーはプロジェクトを表示できます。',
        ko: '회원은 프로젝트를 볼 수 있습니다.',
        zh: '成员可以查看项目。',
        it: 'I membri possono visualizzare il progetto.',
        pt: 'Os membros podem visualizar o projeto.',
        hi: 'सदस्य प्रोजेक्ट देख सकते हैं।',
        ar: 'يمكن للأعضاء عرض المشروع.',
        ru: 'Члены могут просматривать проект.',
        tr: 'Üyeler projeyi görüntüleyebilir.',
        pl: 'Członkowie mogą przeglądać projekt.',
        id: 'Anggota dapat melihat proyek.',
        vi: 'Các thành viên có thể xem dự án.',
        uk: 'Учасники можуть переглядати проєкт.',
      }),
    },

    adminsSelect: {
      label: t({
        en: 'Select admins',
        es: 'Seleccionar administradores',
        fr: 'Sélectionner des administrateurs',
        'en-GB': 'Select admins',
        de: 'Administratoren auswählen',
        ja: '管理者を選択',
        ko: '관리자 선택',
        zh: '选择管理员',
        it: 'Seleziona amministratori',
        pt: 'Selecionar administradores',
        hi: 'एडमिन चुनें',
        ar: 'اختر المديرين',
        ru: 'Выберите администраторов',
        tr: 'Yöneticileri seçin',
        pl: 'Wybierz administratorów',
        id: 'Pilih admin',
        vi: 'Chọn quản trị viên',
        uk: 'Виберіть адміністраторів',
      }),
      placeholder: t({
        en: 'Select admins',
        es: 'Seleccionar administradores',
        fr: 'Sélectionner des administrateurs',
        'en-GB': 'Select admins',
        de: 'Administratoren auswählen',
        ja: '管理者を選択',
        ko: '관리자 선택',
        zh: '选择管理员',
        it: 'Seleziona amministratori',
        pt: 'Selecionar administradores',
        hi: 'एडमिन चुनें',
        ar: 'اختر المديرين',
        ru: 'Выберите администраторов',
        tr: 'Yöneticileri seçin',
        pl: 'Wybierz administratorów',
        id: 'Pilih admin',
        vi: 'Chọn quản trị viên',
        uk: 'Виберіть адміністраторів',
      }),
      description: t({
        en: 'Admins can edit members and project settings.',
        es: 'Los administradores pueden editar miembros y configuraciones del proyecto.',
        fr: 'Les admins peuvent modifier les membres et les paramètres du projet.',
        'en-GB': 'Admins can edit members and project settings.',
        de: 'Administratoren können Mitglieder und Projekteinstellungen bearbeiten.',
        ja: '管理者はメンバーとプロジェクト設定を編集できます。',
        ko: '관리자는 구성원 및 프로젝트 설정을 수정할 수 있습니다.',
        zh: '管理员可以编辑成员和项目设置。',
        it: 'Gli amministratori possono modificare i membri e le impostazioni del progetto.',
        pt: 'Os administradores podem editar membros e configurações do projeto.',
        hi: 'व्यवस्थापक सदस्यों और प्रोजेक्ट सेटिंग्स को संपादित कर सकते हैं।',
        ar: 'يمكن للمديرين تعديل الأعضاء وإعدادات المشروع.',
        ru: 'Администраторы могут редактировать участников и настройки проекта.',
        tr: 'Yöneticiler üyeleri ve proje ayarlarını düzenleyebilir.',
        pl: 'Administratorzy mogą edytować członków i ustawienia projektu.',
        id: 'Admin dapat mengedit anggota dan pengaturan proyek.',
        vi: 'Quản trị viên có thể chỉnh sửa thành viên và cài đặt dự án.',
        uk: 'Адміністратори можуть редагувати учасників та налаштування проєкту.',
      }),
    },

    addMembersButton: {
      text: t({
        en: 'Update Members',
        es: 'Actualizar Miembros',
        fr: 'Mettre à jour les membres',
        'en-GB': 'Update Members',
        de: 'Mitglieder aktualisieren',
        ja: 'メンバーを更新',
        ko: '구성원 업데이트',
        zh: '更新成员',
        it: 'Aggiorna membri',
        pt: 'Atualizar membros',
        hi: 'सदस्यों को अपडेट करें',
        ar: 'تحديث الأعضاء',
        ru: 'Обновить членов',
        tr: 'Üyeleri güncelle',
        pl: 'Aktualizuj członków',
        id: 'Perbarui Anggota',
        vi: 'Cập nhật thành viên',
        uk: 'Оновити учасників',
      }),
      label: t({
        en: 'Update Members',
        es: 'Actualizar Miembros',
        fr: 'Mettre à jour les membres',
        'en-GB': 'Update Members',
        de: 'Mitglieder aktualisieren',
        ja: 'メンバーを更新',
        ko: '구성원 업데이트',
        zh: '更新成员',
        it: 'Aggiorna membri',
        pt: 'Atualizar membros',
        hi: 'सदस्यों को अपडेट करें',
        ar: 'تحديث الأعضاء',
        ru: 'Обновить членов',
        tr: 'Üyeleri güncelle',
        pl: 'Aktualizuj członków',
        id: 'Perbarui Anggota',
        vi: 'Cập nhật thành viên',
        uk: 'Оновити учасників',
      }),
    },

    schema: {
      requiredErrorMember: t({
        en: 'Please add at least one member to the project',
        fr: 'Veuillez ajouter au moins un membre au projet',
        es: 'Por favor, agregue al menos un miembro al proyecto',
        'en-GB': 'Please add at least one member to the project',
        de: 'Bitte fügen Sie mindestens ein Mitglied zum Projekt hinzu',
        ja: 'プロジェクトに少なくとも1人のメンバーを追加してください',
        ko: '프로젝트에 최소한 한 명의 회원을 추가하세요',
        zh: '请至少添加一名成员到项目中',
        it: 'Si prega di aggiungere almeno un membro al progetto',
        pt: 'Por favor, adicione pelo menos um membro ao projeto',
        hi: 'कृपया परियोजना में कम से कम एक सदस्य जोड़ें',
        ar: 'الرجاء إضافة عضو واحد على الأقل إلى المشروع',
        ru: 'Пожалуйста, добавьте хотя бы одного участника в проект',
        tr: 'Lütfen projeye en az bir üye ekleyin',
        pl: 'Dodaj przynajmniej jednego członka do projektu',
        id: 'Harap tambahkan setidaknya satu anggota ke proyek',
        vi: 'Vui lòng thêm ít nhất một thành viên vào dự án',
        uk: 'Будь ласка, додайте принаймні одного учасника до проєкту',
      }),

      requiredErrorAdmin: t({
        en: 'Please add at least one admin to the project',
        fr: 'Veuillez ajouter au moins un administrateur au projet',
        es: 'Por favor, agregue al menos un administrador al proyecto',
        'en-GB': 'Please add at least one admin to the project',
        de: 'Bitte fügen Sie mindestens einen Administrator zum Projekt hinzu',
        ja: 'プロジェクトに少なくとも1人の管理者を追加してください',
        ko: '프로젝트에 최소 한 명의 관리자를 추가하세요',
        zh: '请至少添加一名管理员到项目中',
        it: 'Si prega di aggiungere almeno un amministratore al progetto',
        pt: 'Por favor, adicione pelo menos um administrador ao projeto',
        hi: 'कृपया परियोजना में कम से कम एक व्यवस्थापक जोड़ें',
        ar: 'الرجاء إضافة مدير واحد على الأقل إلى المشروع',
        ru: 'Пожалуйста, добавьте хотя бы одного администратора в проект',
        tr: 'Lütfen projeye en az bir yönetici ekleyin',
        pl: 'Dodaj przynajmniej jednego administratora do projektu',
        id: 'Harap tambahkan setidaknya satu admin ke proyek',
        vi: 'Vui lòng thêm ít nhất một quản trị viên vào dự án',
        uk: 'Будь ласка, додайте принаймні одного адміністратора до проєкту',
      }),
    },

    accessControlUsername: insert(
      t({
        en: 'Access control — {{userName}}',
        fr: "Contrôle d'accès — {{userName}}",
        es: 'Control de acceso — {{userName}}',
        de: 'Zugriffskontrolle — {{userName}}',
        ja: 'アクセス制御 — {{userName}}',
        ko: '액세스 제어 — {{userName}}',
        zh: '访问控制 — {{userName}}',
        it: 'Controllo accessi — {{userName}}',
        pt: 'Controle de acesso — {{userName}}',
        hi: 'एक्सेस नियंत्रण — {{userName}}',
        ar: 'التحكم في الوصول — {{userName}}',
        ru: 'Управление доступом — {{userName}}',
        'en-GB': 'Access control — {{userName}}',
        tr: 'Erişim denetimi — {{userName}}',
        pl: 'Kontrola dostępu — {{userName}}',
        id: 'Kontrol akses — {{userName}}',
        vi: 'Kiểm soát truy cập — {{userName}}',
        uk: 'Контроль доступу — {{userName}}',
      })
    ),

    environmentAccess: t({
      en: 'Environment access',
      fr: 'Accès aux environnements',
      es: 'Acceso a entornos',
      de: 'Umgebungszugriff',
      ja: '環境アクセス',
      ko: '환경 액세스',
      zh: '环境访问',
      it: 'Accesso agli ambienti',
      pt: 'Acesso ao ambiente',
      hi: 'वातावरण पहुँच',
      ar: 'الوصول إلى البيئة',
      ru: 'Доступ к окружению',
      'en-GB': 'Environment access',
      tr: 'Ortam erişimi',
      pl: 'Dostęp do środowiska',
      id: 'Akses lingkungan',
      vi: 'Quyền truy cập môi trường',
      uk: 'Доступ до середовища',
    }),

    allEnvironments: t({
      en: 'All environments',
      fr: 'Tous les environnements',
      es: 'Todos los entornos',
      de: 'Alle Umgebungen',
      ja: 'すべての環境',
      ko: '모든 환경',
      zh: '所有环境',
      it: 'Tutti gli ambienti',
      pt: 'Todos os ambientes',
      hi: 'सभी वातावरण',
      ar: 'كل البيئات',
      ru: 'Все окружения',
      'en-GB': 'All environments',
      tr: 'Tüm ortamlar',
      pl: 'Wszystkie środowiska',
      id: 'Semua lingkungan',
      vi: 'Tất cả môi trường',
      uk: 'Всі середовища',
    }),

    restrictToSpecificEnvironments: t({
      en: 'Restrict to specific environments',
      fr: 'Limiter à des environnements spécifiques',
      es: 'Restringir a entornos específicos',
      de: 'Auf bestimmte Umgebungen beschränken',
      ja: '特定の環境に制限',
      ko: '특정 환경으로 제한',
      zh: '限制到特定环境',
      it: 'Limita agli ambienti specifici',
      pt: 'Restringir a ambientes específicos',
      hi: 'विशिष्ट वातावरणों तक सीमित करें',
      ar: 'تقييد على بيئات محددة',
      ru: 'Ограничить определёнными окружениями',
      'en-GB': 'Restrict to specific environments',
      tr: 'Belirli ortamlarla sınırla',
      pl: 'Ogranicz do określonych środowisk',
      id: 'Batasi ke lingkungan tertentu',
      vi: 'Giới hạn cho các môi trường cụ thể',
      uk: 'Обмежити конкретними середовищами',
    }),

    localeAccess: t({
      en: 'Locale access',
      fr: 'Accès aux langues',
      es: 'Acceso a idiomas',
      de: 'Sprachzugriff',
      ja: '言語アクセス',
      ko: '언어 액세스',
      zh: '语言访问',
      it: 'Accesso alle lingue',
      pt: 'Acesso a idiomas',
      hi: 'भाषा पहुँच',
      ar: 'الوصول إلى اللغات',
      ru: 'Доступ к языкам',
      'en-GB': 'Locale access',
      tr: 'Dil erişimi',
      pl: 'Dostęp do języków',
      id: 'Akses lokal',
      vi: 'Quyền truy cập ngôn ngữ',
      uk: 'Доступ до мов',
    }),

    allLocales: t({
      en: 'All locales',
      fr: 'Toutes les langues',
      es: 'Todos los idiomas',
      de: 'Alle Sprachen',
      ja: 'すべての言語',
      ko: '모든 언어',
      zh: '所有语言',
      it: 'Tutte le lingue',
      pt: 'Todos os idiomas',
      hi: 'सभी भाषाएँ',
      ar: 'كل اللغات',
      ru: 'Все языки',
      'en-GB': 'All locales',
      tr: 'Tüm diller',
      pl: 'Wszystkie języki',
      id: 'Semua lokal',
      vi: 'Tất cả ngôn ngữ',
      uk: 'Всі мови',
    }),

    restrictToSpecificLocales: t({
      en: 'Restrict to specific locales',
      fr: 'Limiter à des langues spécifiques',
      es: 'Restringir a idiomas específicos',
      de: 'Auf bestimmte Sprachen beschränken',
      ja: '特定の言語に制限',
      ko: '특정 언어로 제한',
      zh: '限制到特定语言',
      it: 'Limita alle lingue specifiche',
      pt: 'Restringir a idiomas específicos',
      hi: 'विशिष्ट भाषाओं तक सीमित करें',
      ar: 'تقييد على لغات محددة',
      ru: 'Ограничить определёнными языками',
      'en-GB': 'Restrict to specific locales',
      tr: 'Belirli dillerle sınırla',
      pl: 'Ogranicz do określonych języków',
      id: 'Batasi ke lokal tertentu',
      vi: 'Giới hạn cho các ngôn ngữ cụ thể',
      uk: 'Обмежити конкретними мовами',
    }),

    cancel: t({
      en: 'Cancel',
      fr: 'Annuler',
      es: 'Cancelar',
      de: 'Abbrechen',
      ja: 'キャンセル',
      ko: '취소',
      zh: '取消',
      it: 'Annulla',
      pt: 'Cancelar',
      hi: 'रद्द करें',
      ar: 'إلغاء',
      ru: 'Отмена',
      'en-GB': 'Cancel',
      tr: 'İptal',
      pl: 'Anuluj',
      id: 'Batal',
      vi: 'Hủy',
      uk: 'Скасувати',
    }),

    saveAccessConstraints: t({
      en: 'Save access constraints',
      fr: "Enregistrer les contraintes d'accès",
      es: 'Guardar restricciones de acceso',
      de: 'Zugriffsbeschränkungen speichern',
      ja: 'アクセス制限を保存',
      ko: '액세스 제한 저장',
      zh: '保存访问限制',
      it: 'Salva i vincoli di accesso',
      pt: 'Salvar restrições de acesso',
      hi: 'एक्सेस प्रतिबंध सहेजें',
      ar: 'حفظ قيود الوصول',
      ru: 'Сохранить ограничения доступа',
      'en-GB': 'Save access constraints',
      tr: 'Erişim kısıtlamalarını kaydet',
      pl: 'Zapisz ograniczenia dostępu',
      id: 'Simpan batasan akses',
      vi: 'Lưu ràng buộc truy cập',
      uk: 'Зберегти обмеження доступу',
    }),

    save: t({
      en: 'Save',
      fr: 'Enregistrer',
      es: 'Guardar',
      de: 'Speichern',
      ja: '保存',
      ko: '저장',
      zh: '保存',
      it: 'Salva',
      pt: 'Salvar',
      hi: 'सहेजें',
      ar: 'حفظ',
      ru: 'Сохранить',
      'en-GB': 'Save',
      tr: 'Kaydet',
      pl: 'Zapisz',
      id: 'Simpan',
      vi: 'Lưu',
      uk: 'Зберегти',
    }),

    advancedAccessControls: t({
      en: 'Advanced access controls',
      fr: "Contrôles d'accès avancés",
      es: 'Controles de acceso avanzados',
      de: 'Erweiterte Zugriffssteuerung',
      ja: '高度なアクセス制御',
      ko: '고급 액세스 제어',
      zh: '高级访问控制',
      it: 'Controlli di accesso avanzati',
      pt: 'Controles de acesso avançados',
      hi: 'उन्नत एक्सेस नियंत्रण',
      ar: 'ضوابط وصول متقدمة',
      ru: 'Расширенное управление доступом',
      'en-GB': 'Advanced access controls',
      tr: 'Gelişmiş erişim denetimleri',
      pl: 'Zaawansowane kontrole dostępu',
      id: 'Kontrol akses lanjutan',
      vi: 'Kiểm soát truy cập nâng cao',
      uk: 'Розширений контроль доступу',
    }),

    back: t({
      en: 'Back',
      fr: 'Retour',
      es: 'Volver',
      de: 'Zurück',
      ja: '戻る',
      ko: '뒤로',
      zh: '返回',
      it: 'Indietro',
      pt: 'Voltar',
      hi: 'वापस',
      ar: 'رجوع',
      ru: 'Назад',
      'en-GB': 'Back',
      tr: 'Geri',
      pl: 'Wstecz',
      id: 'Kembali',
      vi: 'Quay lại',
      uk: 'Назад',
    }),

    configureAccess: t({
      en: 'Configure access',
      fr: "Configurer l'accès",
      es: 'Configurar acceso',
      de: 'Zugriff konfigurieren',
      ja: 'アクセスを設定',
      ko: '액세스 구성',
      zh: '配置访问权限',
      it: "Configura l'accesso",
      pt: 'Configurar acesso',
      hi: 'एक्सेस कॉन्फ़िगर करें',
      ar: 'تكوين الوصول',
      ru: 'Настроить доступ',
      'en-GB': 'Configure access',
      tr: 'Erişimi yapılandır',
      pl: 'Skonfiguruj dostęp',
      id: 'Konfigurasi akses',
      vi: 'Cấu hình quyền truy cập',
      uk: 'Налаштувати доступ',
    }),
  },
  title: 'Project members form',
  description:
    'Dictionary for the project members form, including labels, descriptions, and validation messages for managing members and admins within a project.',
  tags: ['form', 'project settings', 'members management'],
} satisfies Dictionary;

export default projectMembersFormContent;
