import { type Dictionary, t } from 'intlayer';

const reviewerMissionListContent = {
  key: 'reviewer-mission-list',
  content: {
    noMissionsYet: t({
      en: 'No missions yet.',
      ru: 'Пока нет заданий.',
      ja: 'まだミッションはありません。',
      fr: 'Aucune mission pour le moment.',
      ko: '아직 미션이 없습니다.',
      zh: '尚无任务。',
      es: 'No hay misiones todavía.',
      de: 'Noch keine Missionen.',
      ar: 'لا توجد مهام بعد.',
      it: 'Ancora nessuna missione.',
      'en-GB': 'No missions yet.',
      pt: 'Nenhuma missão ainda.',
      hi: 'अभी तक कोई मिशन नहीं है।',
      tr: 'Henüz görev yok.',
      pl: 'Brak misji.',
      id: 'Belum ada misi.',
      vi: 'Chưa có nhiệm vụ nào.',
      uk: 'Поки немає завдань.',
    }),

    acceptMission: t({
      en: 'Accept mission',
      ru: 'Принять задание',
      ja: 'ミッションを受ける',
      fr: 'Accepter la mission',
      ko: '미션 수락',
      zh: '接受任务',
      es: 'Aceptar misión',
      de: 'Mission annehmen',
      ar: 'قبول المهمة',
      it: 'Accetta missione',
      'en-GB': 'Accept mission',
      pt: 'Aceitar missão',
      hi: 'मिशन स्वीकार करें',
      tr: 'Görevi kabul et',
      pl: 'Zaakceptuj misję',
      id: 'Terima misi',
      vi: 'Chấp nhận nhiệm vụ',
      uk: 'Прийняти завдання',
    }),

    accept: t({
      en: 'Accept',
      ru: 'Принять',
      ja: '承諾',
      fr: 'Accepter',
      ko: '수락',
      zh: '接受',
      es: 'Aceptar',
      de: 'Annehmen',
      ar: 'قبول',
      it: 'Accetta',
      'en-GB': 'Accept',
      pt: 'Aceitar',
      hi: 'स्वीکار करें',
      tr: 'Kabul et',
      pl: 'Zaakceptuj',
      id: 'Terima',
      vi: 'Chấp nhận',
      uk: 'Прийняти',
    }),

    declineMission: t({
      en: 'Decline mission',
      ru: 'Отклонить задание',
      ja: 'ミッションを辞退する',
      fr: 'Décliner la mission',
      ko: '미션 거절',
      zh: '拒绝任务',
      es: 'Rechazar misión',
      de: 'Mission ablehnen',
      ar: 'رفض المهمة',
      it: 'Rifiuta missione',
      'en-GB': 'Decline mission',
      pt: 'Recusar missão',
      hi: 'मिशन अस्वीकार करें',
      tr: 'Görevi reddet',
      pl: 'Odrzuć misję',
      id: 'Tolak misi',
      vi: 'Từ chối nhiệm vụ',
      uk: 'Відхилити завдання',
    }),

    decline: t({
      en: 'Decline',
      ru: 'Отклонить',
      ja: '辞退',
      fr: 'Décliner',
      ko: '거절',
      zh: '拒绝',
      es: 'Rechazar',
      de: 'Ablehnen',
      ar: 'رفض',
      it: 'Rifiuta',
      'en-GB': 'Decline',
      pt: 'Recusar',
      hi: 'अस्वीकार करें',
      tr: 'Reddet',
      pl: 'Odrzuć',
      id: 'Tolak',
      vi: 'Từ chối',
      uk: 'Відхилити',
    }),

    startMission: t({
      en: 'Start mission',
      ru: 'Начать задание',
      ja: 'ミッションを開始する',
      fr: 'Commencer la mission',
      ko: '미션 시작',
      zh: '开始任务',
      es: 'Iniciar misión',
      de: 'Mission starten',
      ar: 'بدء المهمة',
      it: 'Inizia missione',
      'en-GB': 'Start mission',
      pt: 'Iniciar missão',
      hi: 'मिशन शुरू करें',
      tr: 'Görevi başlat',
      pl: 'Rozpocznij misję',
      id: 'Mulai misi',
      vi: 'Bắt đầu nhiệm vụ',
      uk: 'Розпочати завдання',
    }),

    start: t({
      en: 'Start',
      ru: 'Начать',
      ja: '開始',
      fr: 'Démarrer',
      ko: '시작',
      zh: '开始',
      es: 'Iniciar',
      de: 'Starten',
      ar: 'بدء',
      it: 'Inizia',
      'en-GB': 'Start',
      pt: 'Iniciar',
      hi: 'शुरू करें',
      tr: 'Başlat',
      pl: 'Rozpocznij',
      id: 'Mulai',
      vi: 'Bắt đầu',
      uk: 'Розпочати',
    }),

    markMissionAsDone: t({
      en: 'Mark mission as done',
      ru: 'Отметить задание как выполненное',
      ja: 'ミッションを完了とする',
      fr: 'Marquer la mission comme terminée',
      ko: '미션을 완료로 표시',
      zh: '标记任务为已完成',
      es: 'Marcar misión como completada',
      de: 'Mission als erledigt markieren',
      ar: 'تحديد المهمة كمنتهية',
      it: 'Segna missione come completata',
      'en-GB': 'Mark mission as done',
      pt: 'Marcar missão como concluída',
      hi: 'मिशन को पूरा हुआ चिह्नित करें',
      tr: 'Görevi tamamlandı olarak işaretle',
      pl: 'Oznacz misję jako ukończoną',
      id: 'Tandai misi selesai',
      vi: 'Đánh dấu nhiệm vụ là hoàn thành',
      uk: 'Позначити завдання як виконане',
    }),

    markDone: t({
      en: 'Mark done',
      ru: 'Выполнено',
      ja: '完了とする',
      fr: 'Terminer',
      ko: '완료 표시',
      zh: '标记完成',
      es: 'Marcar hecho',
      de: 'Erledigt markieren',
      ar: 'تحديد كمنتهٍ',
      it: 'Segna completato',
      'en-GB': 'Mark done',
      pt: 'Marcar como feito',
      hi: 'पूर्ण चिह्नित करें',
      tr: 'Tamamlandı olarak işaretle',
      pl: 'Oznacz jako ukończone',
      id: 'Tandai selesai',
      vi: 'Đánh dấu hoàn thành',
      uk: 'Позначити виконаним',
    }),

    openMissionChat: t({
      en: 'Open mission chat',
      ru: 'Открыть чат задания',
      ja: 'ミッションチャットを開く',
      fr: 'Ouvrir le chat de la mission',
      ko: '미션 채팅 열기',
      zh: '打开任务聊天',
      es: 'Abrir chat de la misión',
      de: 'Missions-Chat öffnen',
      ar: 'فتح محادثة المهمة',
      it: 'Apri la chat della missione',
      'en-GB': 'Open mission chat',
      pt: 'Abrir chat da missão',
      hi: 'मिशन चैट खोलें',
      tr: 'Görev sohbetini aç',
      pl: 'Otwórz czat misji',
      id: 'Buka obrolan misi',
      vi: 'Mở trò chuyện nhiệm vụ',
      uk: 'Відкрити чат завдання',
    }),
  },
} satisfies Dictionary;

export default reviewerMissionListContent;
