import { type Dictionary, t } from 'intlayer';

const projectFormContent = {
  key: 'project-form',
  content: {
    title: t({
      en: 'Project details',
      'en-GB': 'Project details',
      fr: 'Détails du projet',
      es: 'Detalles del proyecto',
      de: 'Projektdetails',
      ja: 'プロジェクトの詳細',
      ko: '프로젝트 세부정보',
      zh: '项目详细信息',
      it: 'Dettagli del progetto',
      pt: 'Detalhes do projeto',
      hi: 'परियोजना विवरण',
      ar: 'تفاصيل المشروع',
      ru: 'Детали проекта',
      tr: 'Proje detayları',
      pl: 'Szczegóły projektu',
      id: 'Detail proyek',
      vi: 'Chi tiết dự án',
      uk: 'Деталі проєкту',
    }),
    noAdminMessage: t({
      en: 'You are not an admin of this project. Contact your administrator if you want to edit the project.',
      'en-GB':
        'You are not an admin of this project. Contact your administrator if you want to edit the project.',
      es: 'No eres un administrador de este proyecto. Contacta a tu administrador si deseas editar el proyecto.',
      fr: "Vous n'êtes pas un administrateur de ce projet. Veuillez contacter votre administrateur si vous souhaitez modifier le projet.",
      de: 'Sie sind kein Administrator dieses Projekts. Kontaktieren Sie Ihren Administrator, wenn Sie das Projekt bearbeiten möchten.',
      ja: 'このプロジェクトの管理者ではありません。プロジェクトを編集したい場合は、管理者に連絡してください。',
      ko: '이 프로젝트의 관리자가 아닙니다. 프로젝트를 편집하려면 관리자에게 문의하세요.',
      zh: '您不是此项目的管理员。如果您想编辑项目，请联系您的管理员。',
      it: 'Non sei un amministratore di questo progetto. Contatta il tuo amministratore se desideri modificare il progetto.',
      pt: 'Você não é um administrador deste projeto. Entre em contato com seu administrador se quiser editar o projeto.',
      hi: 'आप इस परियोजना के व्यवस्थापक नहीं हैं। यदि आप परियोजना को संपादित करना चाहते हैं तो अपने व्यवस्थापक से संपर्क करें।',
      ar: 'أنت لست مديرًا لهذا المشروع. اتصل بالمسؤول إذا كنت ترغب في تحرير المشروع.',
      ru: 'Вы не являетесь администратором этого проекта. Свяжитесь с администратором, если хотите редактировать проект.',
      tr: 'Bu projenin yöneticisi değilsiniz. Projeyi düzenlemek istiyorsanız yöneticinizle iletişime geçin.',
      pl: 'Nie jesteś administratorem tego projektu. Skontaktuj się z administratorem, jeśli chcesz edytować projekt.',
      id: 'Anda bukan admin proyek ini. Hubungi administrator Anda jika ingin mengedit proyek.',
      vi: 'Bạn không phải quản trị viên của dự án này. Liên hệ với quản trị viên nếu bạn muốn chỉnh sửa dự án.',
      uk: 'Ви не є адміністратором цього проєкту. Зверніться до свого адміністратора, якщо хочете редагувати проєкт.',
    }),
    nameInput: {
      label: t({
        en: 'Name of the project',
        'en-GB': 'Name of the project',
        fr: 'Nom du projet',
        es: 'Nombre del proyecto',
        de: 'Name des Projekts',
        ja: 'プロジェクトの名前',
        ko: '프로젝트 이름',
        zh: '项目名称',
        it: 'Nome del progetto',
        pt: 'Nome do projeto',
        hi: 'परियोजना का नाम',
        ar: 'اسم المشروع',
        ru: 'Название проекта',
        tr: 'Projenin adı',
        pl: 'Nazwa projektu',
        id: 'Nama proyek',
        vi: 'Tên dự án',
        uk: 'Назва проєкту',
      }),
      placeholder: t({
        en: 'Enter the name of the project',
        'en-GB': 'Enter the name of the project',
        fr: 'Entrez le nom du projet',
        es: 'Ingrese el nombre del proyecto',
        de: 'Geben Sie den Namen des Projekts ein',
        ja: 'プロジェクトの名前を入力してください',
        ko: '프로젝트 이름을 입력하세요',
        zh: '输入项目名称',
        it: 'Inserisci il nome del progetto',
        pt: 'Insira o nome do projeto',
        hi: 'परियोजना का नाम दर्ज करें',
        ar: 'أدخل اسم المشروع',
        ru: 'Введите название проекта',
        tr: 'Projenin adını girin',
        pl: 'Wprowadź nazwę projektu',
        id: 'Masukkan nama proyek',
        vi: 'Nhập tên dự án',
        uk: 'Введіть назву проєкту',
      }),
    },

    createProjectTitle: t({
      en: 'No project',
      'en-GB': 'No project',
      fr: 'Aucun projet',
      es: 'Sin proyecto',
      de: 'Kein Projekt',
      ja: 'プロジェクトなし',
      ko: '프로젝트 없음',
      zh: '没有项目',
      it: 'Nessun progetto',
      pt: 'Sem projeto',
      hi: 'कोई परियोजना नहीं',
      ar: 'لا توجد مشاريع',
      ru: 'Нет проекта',
      tr: 'Proje yok',
      pl: 'Brak projektu',
      id: 'Belum ada proyek',
      vi: 'Chưa có dự án',
      uk: 'Немає проєкту',
    }),

    createProjectDescription: t({
      en: 'Create your first project to start using Intlayer',
      'en-GB': 'Create your first project to start using Intlayer',
      fr: 'Créez votre premier projet pour commencer à utiliser Intlayer',
      es: 'Cree su primer proyecto para comenzar a usar Intlayer',
      de: 'Erstellen Sie Ihr erstes Projekt, um Intlayer zu verwenden',
      ja: 'Intlayerを使用開始するために最初のプロジェクトを作成してください',
      ko: 'Intlayer를 사용하기 시작하려면 첫 번째 프로젝트를 생성하세요',
      zh: '创建您的第一个项目以开始使用Intlayer',
      it: 'Crea il tuo primo progetto per iniziare ad utilizzare Intlayer',
      pt: 'Crie seu primeiro projeto para começar a usar o Intlayer',
      hi: 'Intlayer का उपयोग शुरू करने के लिए अपना पहला परियोजना बनाएँ',
      ar: 'أنشئ مشروعك الأول للبدء في استخدام Intlayer',
      ru: 'Создайте свой первый проект, чтобы начать использовать Intlayer',
      tr: 'Intlayer kullanmaya başlamak için ilk projenizi oluşturun',
      pl: 'Utwórz swój pierwszy projekt, aby rozpocząć korzystanie z Intlayer',
      id: 'Buat proyek pertama Anda untuk mulai menggunakan Intlayer',
      vi: 'Tạo dự án đầu tiên để bắt đầu sử dụng Intlayer',
      uk: 'Створіть свій перший проєкт, щоб почати користуватися Intlayer',
    }),

    createProjectButton: {
      text: t({
        en: 'Create project',
        'en-GB': 'Create project',
        fr: 'Créer un projet',
        es: 'Crear un proyecto',
        de: 'Projekt erstellen',
        ja: 'プロジェクトを作成',
        ko: '프로젝트 만들기',
        zh: '创建项目',
        it: 'Crea progetto',
        pt: 'Criar projeto',
        hi: 'परियोजना बनाएं',
        ar: 'إنشاء مشروع',
        ru: 'Создать проект',
        tr: 'Proje oluştur',
        pl: 'Utwórz projekt',
        id: 'Buat proyek',
        vi: 'Tạo dự án',
        uk: 'Створити проєкт',
      }),
      ariaLabel: t({
        en: 'Click to create project',
        'en-GB': 'Click to create project',
        fr: 'Cliquez pour créer un projet',
        es: 'Haga clic para crear un proyecto',
        de: 'Klicken Sie, um ein Projekt zu erstellen',
        ja: 'プロジェクトを作成するにはクリックしてください',
        ko: '프로젝트를 만들려면 클릭하세요',
        zh: '点击创建项目',
        it: 'Clicca per creare il progetto',
        pt: 'Clique para criar o projeto',
        hi: 'परियोजना बनाने के लिए क्लिक करें',
        ar: 'انقر لإنشاء مشروع',
        ru: 'Нажмите, чтобы создать проект',
        tr: 'Proje oluşturmak için tıklayın',
        pl: 'Kliknij, aby utworzyć projekt',
        id: 'Klik untuk membuat proyek',
        vi: 'Nhấp để tạo dự án',
        uk: 'Натисніть, щоб створити проєкт',
      }),
    },

    editButton: {
      text: t({
        en: 'Edit project',
        'en-GB': 'Edit project',
        fr: 'Modifier le projet',
        es: 'Editar el proyecto',
        de: 'Projekt bearbeiten',
        ja: 'プロジェクトを編集',
        ko: '프로젝트 편집',
        zh: '编辑项目',
        it: 'Modifica progetto',
        pt: 'Editar projeto',
        hi: 'परियोजना संपादित करें',
        ar: 'تعديل المشروع',
        ru: 'Редактировать проект',
        tr: 'Projeyi düzenle',
        pl: 'Edytuj projekt',
        id: 'Edit proyek',
        vi: 'Chỉnh sửa dự án',
        uk: 'Редагувати проєкт',
      }),
      ariaLabel: t({
        en: 'Click to edit',
        'en-GB': 'Click to edit',
        fr: 'Cliquez pour modifier',
        es: 'Haga clic para editar',
        de: 'Klicken Sie zum Bearbeiten',
        ja: '編集するにはクリックしてください',
        ko: '편집하려면 클릭하세요',
        zh: '点击进行编辑',
        it: 'Clicca per modificare',
        pt: 'Clique para editar',
        hi: 'संपादित करने के लिए क्लिक करें',
        ar: 'انقر للتعديل',
        ru: 'Нажмите, чтобы редактировать',
        tr: 'Düzenlemek için tıklayın',
        pl: 'Kliknij, aby edytować',
        id: 'Klik untuk mengedit',
        vi: 'Nhấp để chỉnh sửa',
        uk: 'Натисніть, щоб редагувати',
      }),
    },

    deleteProjectButton: {
      text: t({
        en: 'Delete Project',
        'en-GB': 'Delete Project',
        fr: 'Supprimer le projet',
        es: 'Eliminar el proyecto',
        de: 'Projekt löschen',
        ja: 'プロジェクトを削除',
        ko: '프로젝트 삭제',
        zh: '删除项目',
        it: 'Elimina progetto',
        pt: 'Excluir projeto',
        hi: 'परियोजना हटाएं',
        ar: 'حذف المشروع',
        ru: 'Удалить проект',
        tr: 'Projeyi sil',
        pl: 'Usuń projekt',
        id: 'Hapus proyek',
        vi: 'Xóa dự án',
        uk: 'Видалити проєкт',
      }),
      ariaLabel: t({
        en: 'Click to delete project',
        'en-GB': 'Click to delete project',
        fr: 'Cliquez pour supprimer le projet',
        es: 'Haga clic para eliminar el proyecto',
        de: 'Klicken Sie, um das Projekt zu löschen',
        ja: 'プロジェクトを削除するにはクリックしてください',
        ko: '프로젝트를 삭제하려면 클릭하세요',
        zh: '点击删除项目',
        it: 'Clicca per eliminare il progetto',
        pt: 'Clique para excluir o projeto',
        hi: 'परियोजना को हटाने के लिए क्लिक करें',
        ar: 'انقر لحذف المشروع',
        ru: 'Нажмите, чтобы удалить проект',
        tr: 'Projeyi silmek için tıklayın',
        pl: 'Kliknij, aby usunąć projekt',
        id: 'Klik untuk menghapus proyek',
        vi: 'Nhấp để xóa dự án',
        uk: 'Натисніть, щоб видалити проєкт',
      }),
    },
  },
  title: 'Project form',
  description:
    'Content related to the project form component in the dashboard. It includes UI labels, buttons, messages and descriptions to create, edit, or delete a project, including access key management.',
  tags: ['dashboard', 'project management', 'form'],
} satisfies Dictionary;

export default projectFormContent;
