import { type Dictionary, t } from 'intlayer';

const projectListContent = {
  key: 'project-list',
  content: {
    searchPlaceholder: t({
      en: 'Search for a project',
      fr: 'Rechercher un projet',
      es: 'Buscar un proyecto',
      'en-GB': 'Search for a project',
      de: 'Projekt suchen',
      ja: 'プロジェクトを検索',
      ko: '프로젝트 검색',
      zh: '搜索项目',
      it: 'Cerca un progetto',
      pt: 'Pesquisar um projeto',
      hi: 'परियोजना खोजें',
      ar: 'البحث عن مشروع',
      ru: 'Найти проект',
      tr: 'Proje ara',
      pl: 'Wyszukaj projekt',
      id: 'Cari proyek',
      vi: 'Tìm kiếm project',
    }),

    createProjectButton: {
      text: t({
        en: 'Create project',
        'en-GB': 'Create project',
        fr: 'Créer un projet',
        es: 'Crear un proyecto',
        de: 'Projekt erstellen',
        ja: 'プロジェクトを作成',
        ko: '프로젝트 만들기',
        zh: '创建项目',
        it: 'Crea progetto',
        pt: 'Criar projeto',
        hi: 'परियोजना बनाएं',
        ar: 'إنشاء مشروع',
        ru: 'Создать проект',
        tr: 'Proje oluştur',
        pl: 'Utwórz projekt',
        id: 'Buat proyek',
        vi: 'Tạo project',
      }),
      ariaLabel: t({
        en: 'Click to create project',
        'en-GB': 'Click to create project',
        fr: 'Cliquez pour créer un projet',
        es: 'Haga clic para crear un proyecto',
        de: 'Klicken Sie, um ein Projekt zu erstellen',
        ja: 'プロジェクトを作成するにはクリックしてください',
        ko: '프로젝트를 만들려면 클릭하세요',
        zh: '点击创建项目',
        it: 'Clicca per creare il progetto',
        pt: 'Clique para criar o projeto',
        hi: 'परियोजना बनाने के लिए क्लिक करें',
        ar: 'انقر لإنشاء مشروع',
        ru: 'Нажмите, чтобы создать проект',
        tr: 'Proje oluşturmak için tıklayın',
        pl: 'Kliknij, aby utworzyć projekt',
        id: 'Klik untuk membuat proyek',
        vi: 'Nhấp để tạo project',
      }),
    },

    selectButton: {
      text: t({
        en: 'Select project',
        fr: 'Sélectionner le projet',
        es: 'Seleccionar proyecto',
        'en-GB': 'Select project',
        de: 'Projekt auswählen',
        ja: 'プロジェクトを選択',
        ko: '프로젝트 선택',
        zh: '选择项目',
        it: 'Seleziona progetto',
        pt: 'Selecione o projeto',
        hi: 'परियोजना चुनें',
        ar: 'اختر المشروع',
        ru: 'Выберите проект',
        tr: 'Proje seç',
        pl: 'Wybierz projekt',
        id: 'Pilih proyek',
        vi: 'Chọn project',
      }),
      label: t({
        en: 'Click to select project',
        fr: 'Cliquez pour sélectionner le projet',
        es: 'Haga clic para seleccionar el proyecto',
        'en-GB': 'Click to select project',
        de: 'Klicken Sie, um das Projekt auszuwählen',
        ja: 'プロジェクトを選択するにはクリックしてください',
        ko: '프로젝트를 선택하려면 클릭하세요',
        zh: '点击选择项目',
        it: 'Clicca per selezionare il progetto',
        pt: 'Clique para selecionar o projeto',
        hi: 'परियोजना चुनने के लिए क्लिक करें',
        ar: 'انقر لاختيار المشروع',
        ru: 'Нажмите, чтобы выбрать проект',
        tr: 'Projeyi seçmek için tıklayın',
        pl: 'Kliknij, aby wybrać projekt',
        id: 'Klik untuk memilih proyek',
        vi: 'Nhấp để chọn project',
      }),
    },
    noProjectFound: t({
      en: 'No project found. Try clearing your filters.',
      fr: 'Aucun projet trouvé. Essayez de supprimer vos filtres.',
      es: 'No se encontró ningún proyecto. Intente borrar sus filtros.',
      'en-GB': 'No project found. Try clearing your filters.',
      de: 'Kein Projekt gefunden. Versuchen Sie, Ihre Filter zu löschen.',
      ja: 'プロジェクトが見つかりません。フィルターをクリアしてみてください。',
      ko: '프로젝트를 찾을 수 없습니다. 필터를 지워보세요.',
      zh: '找不到项目。尝试清除筛选条件。',
      it: 'Progetto non trovato. Prova a cancellare i filtri.',
      pt: 'Projeto não encontrado. Tente limpar seus filtros.',
      hi: 'परियोजना नहीं खोजी गई। अपने फ़िल्टर साफ़ करने का प्रयास करें।',
      ar: 'لم يتم العثور على مشروع. حاول مسح عوامل التصفية.',
      ru: 'Проект не найден. Попробуйте очистить фильтры.',
      tr: 'Proje bulunamadı. Filtrelerinizi temizlemeyi deneyin.',
      pl: 'Nie znaleziono żadnego projektu. Spróbuj wyczyścić filtry.',
      id: 'Tidak ada proyek yang ditemukan. Coba bersihkan filter Anda.',
      vi: 'Không tìm thấy project. Hãy thử xóa bộ lọc của bạn.',
    }),
  },
  title: 'Project list',
  description:
    'Content dictionary for the project listing section in the dashboard. Includes placeholder text, button labels, and empty state messages related to project selection and creation.',
  tags: ['dashboard', 'project management'],
} satisfies Dictionary;

export default projectListContent;
