import type { LinkGroup } from '@intlayer/design-system/footer';
import {
  External_LinkedIn,
  Website_Benchmark_NextJS_Path,
  Website_Benchmark_Path,
  Website_Benchmark_Solid_Path,
  Website_Benchmark_Svelte_Path,
  Website_Benchmark_Tanstack_Path,
  Website_Benchmark_Vue_Path,
  Website_Contributors_Path,
  Website_Doc_Environment_Astro_Path,
  Website_Doc_Environment_NextJS_Path,
  Website_Doc_Environment_Tanstack_Path,
  Website_Doc_Environment_ViteAndReact_Path,
  Website_Doc_Path,
  Website_PrivacyPolicy_Path,
  Website_TermsOfService_Path,
} from '@intlayer/design-system/routes';
import { type Dictionary, t } from 'intlayer';

type FooterContent = {
  content: LinkGroup[];
};

const footerContent = {
  key: 'footer',
  content: {
    content: [
      {
        title: 'Docs',
        links: [
          {
            href: Website_Doc_Path,
            text: t({
              en: 'Getting started',
              'en-GB': 'Getting started',
              fr: 'Commencez facilement',
              es: 'Empezando',
              de: 'Erste Schritte',
              ja: 'はじめに',
              ko: '시작하기',
              zh: '开始使用',
              it: 'Iniziare',
              pt: 'Começando',
              hi: 'आरंभ करें',
              ar: 'بدء الاستخدام',
              uk: 'Початок роботи',
              ru: 'Начало работы',
              tr: 'Başlarken',
              pl: 'Pierwsze kroki',
              id: 'Memulai',
              vi: 'Bắt đầu',
            }),
            label: t({
              en: 'See getting started documentation',
              'en-GB': 'See getting started documentation',
              fr: 'Voir la documentation de démarrage',
              es: 'Ver documentación de inicio',
              de: 'Siehe Dokumentation zum Einstieg',
              ja: '使い方のドキュメントを見る',
              ko: '시작 문서 보기',
              zh: '查看开始使用文档',
              it: 'Vedi la documentazione di avvio',
              pt: 'Veja a documentação de início',
              hi: 'आरंभ दस्तावेज़ देखें',
              ar: 'قم بمشاهدة توثيق البدء',
              uk: 'Див. документацію з початку роботи',
              ru: 'См. документацию по началу работы',
              tr: 'Başlarken belgelerine göz atın',
              pl: 'Zobacz dokumentację dotyczącą pierwszych kroków',
              id: 'Lihat dokumentasi untuk memulai',
              vi: 'Xem tài liệu hướng dẫn bắt đầu',
            }),
          },
          {
            href: Website_Doc_Environment_NextJS_Path,
            text: t({
              en: 'Intlayer with Next.js',
              'en-GB': 'Intlayer with Next.js',
              fr: 'Intlayer avec Next.js',
              es: 'Intlayer con Next.js',
              de: 'Intlayer mit Next.js',
              ja: 'IntlayerとNext.js',
              ko: 'Intlayer와 Next.js',
              zh: 'Intlayer与Next.js',
              it: 'Intlayer con Next.js',
              pt: 'Intlayer com Next.js',
              hi: 'Intlayer के साथ Next.js',
              ar: 'Intlayer مع Next.js',
              uk: 'Intlayer з Next.js',
              ru: 'Intlayer с Next.js',
              tr: 'Intlayer ile Next.js',
              pl: 'Intlayer z Next.js',
              id: 'Intlayer dengan Next.js',
              vi: 'Intlayer với Next.js',
            }),
            label: t({
              en: 'See Intlayer with Next.js documentation',
              'en-GB': 'See Intlayer with Next.js documentation',
              fr: 'Voir la documentation de Intlayer avec Next.js',
              es: 'Ver documentación de Intlayer con Next.js',
              de: 'Siehe Dokumentation zu Intlayer mit Next.js',
              ja: 'IntlayerとNext.jsのドキュメントを見る',
              ko: 'Intlayer와 Next.js 문서 보기',
              zh: '查看Intlayer与Next.js文档',
              it: 'Vedi la documentazione di Intlayer con Next.js',
              pt: 'Veja a documentação do Intlayer com Next.js',
              hi: 'Intlayer के साथ Next.js दस्तावेज़ देखें',
              ar: 'قم بمشاهدة توثيق Intlayer مع Next.js',
              uk: 'Див. документацію Intlayer з Next.js',
              ru: 'См. документацию Intlayer с Next.js',
              tr: 'Intlayer ile Next.js belgelerine göz atın',
              pl: 'Zobacz dokumentację Intlayer dla Next.js',
              id: 'Lihat dokumentasi Intlayer dengan Next.js',
              vi: 'Xem tài liệu Intlayer với Next.js',
            }),
          },
          {
            href: Website_Doc_Environment_Tanstack_Path,
            text: t({
              en: 'Intlayer with TanStack Start',
              'en-GB': 'Intlayer with TanStack Start',
              fr: 'Intlayer avec TanStack Start',
              es: 'Intlayer con TanStack Start',
              de: 'Intlayer mit TanStack Start',
              ja: 'IntlayerとTanStack Start',
              ko: 'Intlayer와 TanStack Start',
              zh: 'Intlayer与TanStack Start',
              it: 'Intlayer con TanStack Start',
              pt: 'Intlayer com TanStack Start',
              hi: 'Intlayer के साथ TanStack Start',
              ar: 'Intlayer مع TanStack Start',
              uk: 'Intlayer з TanStack Start',
              ru: 'Intlayer с TanStack Start',
              tr: 'Intlayer ile TanStack Start',
              pl: 'Intlayer z TanStack Start',
              id: 'Intlayer dengan TanStack Start',
              vi: 'Intlayer với TanStack Start',
            }),
            label: t({
              en: 'See Intlayer with TanStack Start documentation',
              'en-GB': 'See Intlayer with TanStack Start documentation',
              fr: 'Voir la documentation de Intlayer avec TanStack Start',
              es: 'Ver documentación de Intlayer con TanStack Start',
              de: 'Siehe Dokumentation zu Intlayer mit TanStack Start',
              ja: 'IntlayerとTanStack Startのドキュメントを見る',
              ko: 'Intlayer와 TanStack Start 문서 보기',
              zh: '查看Intlayer与TanStack Start文档',
              it: 'Vedi la documentazione di Intlayer con TanStack Start',
              pt: 'Veja a documentação do Intlayer com TanStack Start',
              hi: 'Intlayer के साथ TanStack Start दस्तावेज़ देखें',
              ar: 'قم بمشاهدة توثيق Intlayer مع TanStack Start',
              uk: 'Див. документацію Intlayer з TanStack Start',
              ru: 'См. документацию Intlayer с TanStack Start',
              tr: 'Intlayer ile TanStack Start belgelerine göz atın',
              pl: 'Zobacz dokumentację Intlayer dla TanStack Start',
              id: 'Lihat dokumentasi Intlayer dengan TanStack Start',
              vi: 'Xem tài liệu Intlayer với TanStack Start',
            }),
          },
          {
            href: Website_Doc_Environment_Astro_Path,
            text: t({
              en: 'Intlayer with Astro',
              'en-GB': 'Intlayer with Astro',
              fr: 'Intlayer avec Astro',
              es: 'Intlayer con Astro',
              de: 'Intlayer mit Astro',
              ja: 'IntlayerとAstro',
              ko: 'Intlayer와 Astro',
              zh: 'Intlayer与Astro',
              it: 'Intlayer con Astro',
              pt: 'Intlayer com Astro',
              hi: 'Intlayer के साथ Astro',
              ar: 'Intlayer مع Astro',
              uk: 'Intlayer з Astro',
              ru: 'Intlayer с Astro',
              tr: 'Intlayer ile Astro',
              pl: 'Intlayer z Astro',
              id: 'Intlayer dengan Astro',
              vi: 'Intlayer với Astro',
            }),
            label: t({
              en: 'See Intlayer with Astro documentation',
              'en-GB': 'See Intlayer with Astro documentation',
              fr: 'Voir la documentation de Intlayer avec Astro',
              es: 'Ver documentación de Intlayer con Astro',
              de: 'Siehe Dokumentation zu Intlayer mit Astro',
              ja: 'IntlayerとAstroのドキュメントを見る',
              ko: 'Intlayer와 Astro 문서 보기',
              zh: '查看Intlayer与Astro文档',
              it: 'Vedi la documentazione di Intlayer con Astro',
              pt: 'Veja a documentação do Intlayer com Astro',
              hi: 'Intlayer के साथ Astro दस्तावेज़ देखें',
              ar: 'قم بمشاهدة توثيق Intlayer مع Astro',
              uk: 'Див. документацію Intlayer з Astro',
              ru: 'См. документацию Intlayer с Astro',
              tr: 'Intlayer ile Astro belgelerine göz atın',
              pl: 'Zobacz dokumentację Intlayer dla Astro',
              id: 'Lihat dokumentasi Intlayer dengan Astro',
              vi: 'Xem tài liệu Intlayer với Astro',
            }),
          },
          {
            href: Website_Doc_Environment_ViteAndReact_Path,
            text: t({
              en: 'Intlayer with Vite and React',
              'en-GB': 'Intlayer with Vite and React',
              fr: 'Intlayer avec Vite et React',
              es: 'Intlayer con Vite y React',
              de: 'Intlayer mit React und Vite',
              ja: 'IntlayerとReactおよびVite',
              ko: 'Intlayer와 React 및 Vite',
              zh: 'Intlayer与React和Vite',
              it: 'Intlayer con React e Vite',
              pt: 'Intlayer com React e Vite',
              hi: 'Intlayer के साथ React और Vite',
              ar: 'Intlayer مع React و Vite',
              uk: 'Intlayer з React та Vite',
              ru: 'Intlayer с React и Vite',
              tr: 'Intlayer ile Vite ve React',
              pl: 'Intlayer z Vite i React',
              id: 'Intlayer dengan Vite dan React',
              vi: 'Intlayer với Vite và React',
            }),
            label: t({
              en: 'See Intlayer with react and vite documentation',
              'en-GB': 'See Intlayer with react and vite documentation',
              fr: 'Voir la documentation de Intlayer avec react et vite',
              es: 'Ver documentación de Intlayer con react y vite',
              de: 'Siehe Dokumentation zu Intlayer mit React und Vite',
              ja: 'IntlayerとReactおよびViteのドキュメントを見る',
              ko: 'Intlayer와 React 및 Vite 문서 보기',
              zh: '查看Intlayer与React和Vite文档',
              it: 'Vedi la documentazione di Intlayer con React e Vite',
              pt: 'Veja a documentação do Intlayer com React e Vite',
              hi: 'Intlayer के साथ React और Vite दस्तावेज़ देखें',
              ar: 'قم بمشاهدة توثيق Intlayer مع React و Vite',
              uk: 'Див. документацію Intlayer з React та Vite',
              ru: 'См. документацию Intlayer с React и Vite',
              tr: 'Intlayer ile React ve Vite belgelerine göz atın',
              pl: 'Zobacz dokumentację Intlayer dla Vite i React',
              id: 'Lihat dokumentasi Intlayer dengan Vite dan React',
              vi: 'Xem tài liệu Intlayer với React và Vite',
            }),
          },
        ],
      },
      {
        title: t({
          en: 'Benchmarks',
          'en-GB': 'Benchmarks',
          fr: 'Benchmarks',
          es: 'Benchmarks',
          de: 'Benchmarks',
          ja: 'ベンチマーク',
          ko: '벤치마크',
          zh: '基准测试',
          it: 'Benchmark',
          pt: 'Benchmarks',
          hi: 'बेंचमार्क',
          ar: 'اختبارات الأداء',
          uk: 'Бенчмарки',
          ru: 'Бенчмарки',
          tr: 'Kıyaslamalar',
          pl: 'Benchmarki',
          id: 'Benchmark',
          vi: 'Benchmark',
        }),
        links: [
          {
            href: Website_Benchmark_Path,
            text: t({
              en: 'i18n benchmark',
              'en-GB': 'i18n benchmark',
              fr: 'Benchmark i18n',
              es: 'Benchmark i18n',
              de: 'i18n-Benchmark',
              ja: 'i18n ベンチマーク',
              ko: 'i18n 벤치마크',
              zh: 'i18n 基准测试',
              it: 'Benchmark i18n',
              pt: 'Benchmark i18n',
              hi: 'i18n बेंचमार्क',
              ar: 'قياس أداء i18n',
              uk: 'Бенчмарк i18n',
              ru: 'Бенчмарк i18n',
              tr: 'i18n kıyaslaması',
              pl: 'Benchmark i18n',
              id: 'Benchmark i18n',
              vi: 'Benchmark i18n',
            }),
            label: t({
              en: 'Compare i18n libraries performance across frameworks',
              'en-GB': 'Compare i18n libraries performance across frameworks',
              fr: 'Comparer les performances des bibliothèques i18n selon les frameworks',
              es: 'Comparar el rendimiento de las bibliotecas i18n entre frameworks',
              de: 'Leistung von i18n-Bibliotheken über Frameworks hinweg vergleichen',
              ja: 'フレームワーク別に i18n ライブラリのパフォーマンスを比較する',
              ko: '프레임워크별 i18n 라이브러리 성능 비교',
              zh: '比较各框架中 i18n 库的性能',
              it: 'Confronta le prestazioni delle librerie i18n tra i framework',
              pt: 'Compare o desempenho das bibliotecas i18n entre frameworks',
              hi: 'फ़्रेमवर्क के अनुसार i18n लाइब्रेरी के प्रदर्शन की तुलना करें',
              ar: 'قارن أداء مكتبات i18n عبر أطر العمل',
              uk: 'Порівняти продуктивність i18n-бібліотек у різних фреймворках',
              ru: 'Сравнить производительность i18n-библиотек в разных фреймворках',
              tr: 'Çerçeveler arasında i18n kütüphanelerinin performansını karşılaştırın',
              pl: 'Porównaj wydajność bibliotek i18n w różnych frameworkach',
              id: 'Bandingkan performa pustaka i18n di berbagai framework',
              vi: 'So sánh hiệu năng các thư viện i18n giữa các framework',
            }),
          },
          {
            href: Website_Benchmark_NextJS_Path,
            text: t({
              en: 'Next.js benchmark',
              'en-GB': 'Next.js benchmark',
              fr: 'Benchmark Next.js',
              es: 'Benchmark de Next.js',
              de: 'Benchmark für Next.js',
              ja: 'Next.js ベンチマーク',
              ko: 'Next.js 벤치마크',
              zh: 'Next.js 基准测试',
              it: 'Benchmark Next.js',
              pt: 'Benchmark de Next.js',
              hi: 'Next.js बेंचमार्क',
              ar: 'قياس أداء Next.js',
              uk: 'Бенчмарк Next.js',
              ru: 'Бенчмарк Next.js',
              tr: 'Next.js kıyaslaması',
              pl: 'Benchmark Next.js',
              id: 'Benchmark Next.js',
              vi: 'Benchmark Next.js',
            }),
            label: t({
              en: 'See the i18n libraries benchmark for Next.js',
              'en-GB': 'See the i18n libraries benchmark for Next.js',
              fr: 'Voir le benchmark des bibliothèques i18n pour Next.js',
              es: 'Ver el benchmark de bibliotecas i18n para Next.js',
              de: 'Siehe den Benchmark der i18n-Bibliotheken für Next.js',
              ja: 'Next.js の i18n ライブラリのベンチマークを見る',
              ko: 'Next.js용 i18n 라이브러리 벤치마크 보기',
              zh: '查看 Next.js 的 i18n 库基准测试',
              it: 'Vedi il benchmark delle librerie i18n per Next.js',
              pt: 'Veja o benchmark de bibliotecas i18n para Next.js',
              hi: 'Next.js के लिए i18n लाइब्रेरी बेंचमार्क देखें',
              ar: 'اعرض قياس أداء مكتبات i18n لـ Next.js',
              uk: 'Переглянути бенчмарк i18n-бібліотек для Next.js',
              ru: 'Посмотреть бенчмарк i18n-библиотек для Next.js',
              tr: 'Next.js için i18n kütüphaneleri kıyaslamasını görüntüle',
              pl: 'Zobacz benchmark bibliotek i18n dla Next.js',
              id: 'Lihat benchmark pustaka i18n untuk Next.js',
              vi: 'Xem benchmark các thư viện i18n cho Next.js',
            }),
          },
          {
            href: Website_Benchmark_Tanstack_Path,
            text: t({
              en: 'TanStack Start benchmark',
              'en-GB': 'TanStack Start benchmark',
              fr: 'Benchmark TanStack Start',
              es: 'Benchmark de TanStack Start',
              de: 'Benchmark für TanStack Start',
              ja: 'TanStack Start ベンチマーク',
              ko: 'TanStack Start 벤치마크',
              zh: 'TanStack Start 基准测试',
              it: 'Benchmark TanStack Start',
              pt: 'Benchmark de TanStack Start',
              hi: 'TanStack Start बेंचमार्क',
              ar: 'قياس أداء TanStack Start',
              uk: 'Бенчмарк TanStack Start',
              ru: 'Бенчмарк TanStack Start',
              tr: 'TanStack Start kıyaslaması',
              pl: 'Benchmark TanStack Start',
              id: 'Benchmark TanStack Start',
              vi: 'Benchmark TanStack Start',
            }),
            label: t({
              en: 'See the i18n libraries benchmark for TanStack Start',
              'en-GB': 'See the i18n libraries benchmark for TanStack Start',
              fr: 'Voir le benchmark des bibliothèques i18n pour TanStack Start',
              es: 'Ver el benchmark de bibliotecas i18n para TanStack Start',
              de: 'Siehe den Benchmark der i18n-Bibliotheken für TanStack Start',
              ja: 'TanStack Start の i18n ライブラリのベンチマークを見る',
              ko: 'TanStack Start용 i18n 라이브러리 벤치마크 보기',
              zh: '查看 TanStack Start 的 i18n 库基准测试',
              it: 'Vedi il benchmark delle librerie i18n per TanStack Start',
              pt: 'Veja o benchmark de bibliotecas i18n para TanStack Start',
              hi: 'TanStack Start के लिए i18n लाइब्रेरी बेंचमार्क देखें',
              ar: 'اعرض قياس أداء مكتبات i18n لـ TanStack Start',
              uk: 'Переглянути бенчмарк i18n-бібліотек для TanStack Start',
              ru: 'Посмотреть бенчмарк i18n-библиотек для TanStack Start',
              tr: 'TanStack Start için i18n kütüphaneleri kıyaslamasını görüntüle',
              pl: 'Zobacz benchmark bibliotek i18n dla TanStack Start',
              id: 'Lihat benchmark pustaka i18n untuk TanStack Start',
              vi: 'Xem benchmark các thư viện i18n cho TanStack Start',
            }),
          },
          {
            href: Website_Benchmark_Vue_Path,
            text: t({
              en: 'Vue benchmark',
              'en-GB': 'Vue benchmark',
              fr: 'Benchmark Vue',
              es: 'Benchmark de Vue',
              de: 'Benchmark für Vue',
              ja: 'Vue ベンチマーク',
              ko: 'Vue 벤치마크',
              zh: 'Vue 基准测试',
              it: 'Benchmark Vue',
              pt: 'Benchmark de Vue',
              hi: 'Vue बेंचमार्क',
              ar: 'قياس أداء Vue',
              uk: 'Бенчмарк Vue',
              ru: 'Бенчмарк Vue',
              tr: 'Vue kıyaslaması',
              pl: 'Benchmark Vue',
              id: 'Benchmark Vue',
              vi: 'Benchmark Vue',
            }),
            label: t({
              en: 'See the i18n libraries benchmark for Vue',
              'en-GB': 'See the i18n libraries benchmark for Vue',
              fr: 'Voir le benchmark des bibliothèques i18n pour Vue',
              es: 'Ver el benchmark de bibliotecas i18n para Vue',
              de: 'Siehe den Benchmark der i18n-Bibliotheken für Vue',
              ja: 'Vue の i18n ライブラリのベンチマークを見る',
              ko: 'Vue용 i18n 라이브러리 벤치마크 보기',
              zh: '查看 Vue 的 i18n 库基准测试',
              it: 'Vedi il benchmark delle librerie i18n per Vue',
              pt: 'Veja o benchmark de bibliotecas i18n para Vue',
              hi: 'Vue के लिए i18n लाइब्रेरी बेंचमार्क देखें',
              ar: 'اعرض قياس أداء مكتبات i18n لـ Vue',
              uk: 'Переглянути бенчмарк i18n-бібліотек для Vue',
              ru: 'Посмотреть бенчмарк i18n-библиотек для Vue',
              tr: 'Vue için i18n kütüphaneleri kıyaslamasını görüntüle',
              pl: 'Zobacz benchmark bibliotek i18n dla Vue',
              id: 'Lihat benchmark pustaka i18n untuk Vue',
              vi: 'Xem benchmark các thư viện i18n cho Vue',
            }),
          },
          {
            href: Website_Benchmark_Svelte_Path,
            text: t({
              en: 'Svelte benchmark',
              'en-GB': 'Svelte benchmark',
              fr: 'Benchmark Svelte',
              es: 'Benchmark de Svelte',
              de: 'Benchmark für Svelte',
              ja: 'Svelte ベンチマーク',
              ko: 'Svelte 벤치마크',
              zh: 'Svelte 基准测试',
              it: 'Benchmark Svelte',
              pt: 'Benchmark de Svelte',
              hi: 'Svelte बेंचमार्क',
              ar: 'قياس أداء Svelte',
              uk: 'Бенчмарк Svelte',
              ru: 'Бенчмарк Svelte',
              tr: 'Svelte kıyaslaması',
              pl: 'Benchmark Svelte',
              id: 'Benchmark Svelte',
              vi: 'Benchmark Svelte',
            }),
            label: t({
              en: 'See the i18n libraries benchmark for Svelte',
              'en-GB': 'See the i18n libraries benchmark for Svelte',
              fr: 'Voir le benchmark des bibliothèques i18n pour Svelte',
              es: 'Ver el benchmark de bibliotecas i18n para Svelte',
              de: 'Siehe den Benchmark der i18n-Bibliotheken für Svelte',
              ja: 'Svelte の i18n ライブラリのベンチマークを見る',
              ko: 'Svelte용 i18n 라이브러리 벤치마크 보기',
              zh: '查看 Svelte 的 i18n 库基准测试',
              it: 'Vedi il benchmark delle librerie i18n per Svelte',
              pt: 'Veja o benchmark de bibliotecas i18n para Svelte',
              hi: 'Svelte के लिए i18n लाइब्रेरी बेंचमार्क देखें',
              ar: 'اعرض قياس أداء مكتبات i18n لـ Svelte',
              uk: 'Переглянути бенчмарк i18n-бібліотек для Svelte',
              ru: 'Посмотреть бенчмарк i18n-библиотек для Svelte',
              tr: 'Svelte için i18n kütüphaneleri kıyaslamasını görüntüle',
              pl: 'Zobacz benchmark bibliotek i18n dla Svelte',
              id: 'Lihat benchmark pustaka i18n untuk Svelte',
              vi: 'Xem benchmark các thư viện i18n cho Svelte',
            }),
          },
          {
            href: Website_Benchmark_Solid_Path,
            text: t({
              en: 'Solid benchmark',
              'en-GB': 'Solid benchmark',
              fr: 'Benchmark Solid',
              es: 'Benchmark de Solid',
              de: 'Benchmark für Solid',
              ja: 'Solid ベンチマーク',
              ko: 'Solid 벤치마크',
              zh: 'Solid 基准测试',
              it: 'Benchmark Solid',
              pt: 'Benchmark de Solid',
              hi: 'Solid बेंचमार्क',
              ar: 'قياس أداء Solid',
              uk: 'Бенчмарк Solid',
              ru: 'Бенчмарк Solid',
              tr: 'Solid kıyaslaması',
              pl: 'Benchmark Solid',
              id: 'Benchmark Solid',
              vi: 'Benchmark Solid',
            }),
            label: t({
              en: 'See the i18n libraries benchmark for Solid',
              'en-GB': 'See the i18n libraries benchmark for Solid',
              fr: 'Voir le benchmark des bibliothèques i18n pour Solid',
              es: 'Ver el benchmark de bibliotecas i18n para Solid',
              de: 'Siehe den Benchmark der i18n-Bibliotheken für Solid',
              ja: 'Solid の i18n ライブラリのベンチマークを見る',
              ko: 'Solid용 i18n 라이브러리 벤치마크 보기',
              zh: '查看 Solid 的 i18n 库基准测试',
              it: 'Vedi il benchmark delle librerie i18n per Solid',
              pt: 'Veja o benchmark de bibliotecas i18n para Solid',
              hi: 'Solid के लिए i18n लाइब्रेरी बेंचमार्क देखें',
              ar: 'اعرض قياس أداء مكتبات i18n لـ Solid',
              uk: 'Переглянути бенчмарк i18n-бібліотек для Solid',
              ru: 'Посмотреть бенчмарк i18n-библиотек для Solid',
              tr: 'Solid için i18n kütüphaneleri kıyaslamasını görüntüle',
              pl: 'Zobacz benchmark bibliotek i18n dla Solid',
              id: 'Lihat benchmark pustaka i18n untuk Solid',
              vi: 'Xem benchmark các thư viện i18n cho Solid',
            }),
          },
        ],
      },
      {
        title: t({
          en: 'Learn more',
          'en-GB': 'Learn more',
          fr: 'En savoir plus',
          es: 'Aprende más',
          de: 'Mehr erfahren',
          ja: 'もっと学ぶ',
          ko: '자세히 알아보기',
          zh: '了解更多',
          it: 'Scopri di più',
          pt: 'Saiba mais',
          hi: 'और जानें',
          ar: 'تعلم المزيد',
          uk: 'Дізнатися більше',
          ru: 'Узнать больше',
          tr: 'Daha fazla bilgi edin',
          pl: 'Dowiedz się więcej',
          id: 'Pelajari lebih lanjut',
          vi: 'Tìm hiểu thêm',
        }),
        links: [
          {
            href: Website_Contributors_Path,
            text: t({
              en: 'Contributors',
              'en-GB': 'Contributors',
              fr: 'Contributeurs',
              es: 'Contribuyentes',
              de: 'Mitwirkende',
              ja: '貢献者',
              ko: '기여자',
              zh: '贡献者',
              it: 'Contributori',
              pt: 'Contribuintes',
              hi: 'योगदाता',
              ar: 'مساهمون',
              uk: 'Учасники',
              ru: 'Участники',
              tr: 'Katkıda bulunanlar',
              pl: 'Współtwórcy',
              id: 'Kontributor',
              vi: 'Người đóng góp',
            }),
            label: t({
              en: 'See our contributors',
              'en-GB': 'See our contributors',
              fr: 'Voir nos contributeurs',
              es: 'Ver nuestros contribuyentes',
              de: 'Sehen Sie unsere Mitwirkenden',
              ja: '貢献者を見る',
              ko: '기여자 보기',
              zh: '查看我们的贡献者',
              it: 'Vedi i nostri contributori',
              pt: 'Ver nossos contribuintes',
              hi: 'हमारे योगदाता देखें',
              ar: 'اعرض مساهمينا',
              uk: 'Переглянути наших учасників',
              ru: 'Посмотреть наших участников',
              tr: 'Katkıda bulunanları görüntüle',
              pl: 'Zobacz naszych współtwórców',
              id: 'Lihat kontributor kami',
              vi: 'Xem những người đóng góp',
            }),
          },
          {
            href: Website_TermsOfService_Path,
            text: t({
              en: 'Terms of service',
              'en-GB': 'Terms of service',
              fr: 'Conditions de service',
              es: 'Términos de servicio',
              de: 'Nutzungsbedingungen',
              ja: 'サービス規約',
              ko: '서비스 약관',
              zh: '服务条款',
              it: 'Termini di servizio',
              pt: 'Termos de serviço',
              hi: 'सेवाओं की शर्तें',
              ar: 'شروط الخدمة',
              uk: 'Умови обслуговування',
              ru: 'Условия обслуживания',
              tr: 'Hizmet Şartları',
              pl: 'Regulamin',
              id: 'Syarat Layanan',
              vi: 'Điều khoản dịch vụ',
            }),
            label: t({
              en: 'Read our terms of service',
              'en-GB': 'Read our terms of service',
              fr: 'Lisez nos conditions de service',
              es: 'Lee nuestros términos de servicio',
              de: 'Lesen Sie unsere Nutzungsbedingungen',
              ja: 'サービス規約を読む',
              ko: '서비스 약관을 읽다',
              zh: '阅读我们的服务条款',
              it: 'Leggi i nostri termini di servizio',
              pt: 'Leia nossos termos de serviço',
              hi: 'हमारी सेवाओं की शर्तों को पढ़ें',
              ar: 'اقرأ شروط الخدمة الخاصة بنا',
              uk: 'Прочитайте наші умови обслуговування',
              ru: 'Прочтите наши условия обслуживания',
              tr: 'Hizmet şartlarımızı okuyun',
              pl: 'Przeczytaj nasz regulamin',
              id: 'Baca syarat layanan kami',
              vi: 'Đọc điều khoản dịch vụ của chúng tôi',
            }),
          },
          {
            href: Website_PrivacyPolicy_Path,
            text: t({
              en: 'Privacy Notice',
              'en-GB': 'Privacy Notice',
              fr: 'Avis de confidentialité',
              es: 'Aviso de privacidad',
              de: 'Datenschutzinformationen',
              ja: 'プライバシー通知',
              ko: '개인정보 보호 공지',
              zh: '隐私通知',
              it: 'Avviso sulla privacy',
              pt: 'Aviso de privacidade',
              hi: 'गोपनीयता अधिसूचना',
              ar: 'إشعار الخصوصية',
              uk: 'Повідомлення про конфіденційність',
              ru: 'Уведомление о конфиденциальности',
              tr: 'Gizlilik Bildirimi',
              pl: 'Polityka prywatności',
              id: 'Pemberitahuan Privasi',
              vi: 'Chính sách bảo mật',
            }),
            label: t({
              en: 'Read our privacy notice',
              'en-GB': 'Read our privacy notice',
              fr: 'Lisez notre avis de confidentialité',
              es: 'Lee nuestro aviso de privacidad',
              de: 'Lesen Sie unsere Datenschutzinformationen',
              ja: 'プライバシー通知を読む',
              ko: '개인정보 보호 공지를 읽다',
              zh: '阅读我们的隐私通知',
              it: 'Leggi il nostro avviso sulla privacy',
              pt: 'Leia nosso aviso de privacidade',
              hi: 'हमारी गोपनीयता अधिसूचना पढ़ें',
              ar: 'اقرأ إشعار الخصوصية الخاص بنا',
              uk: 'Прочитайте наше повідомлення про конфіденційність',
              ru: 'Прочтите наше уведомление о конфиденциальности',
              tr: 'Gizlilik bildirimimizi okuyun',
              pl: 'Przeczytaj naszą politykę prywatności',
              id: 'Baca pemberitahuan privasi kami',
              vi: 'Đọc chính sách bảo mật của chúng tôi',
            }),
          },
          {
            href: External_LinkedIn,
            text: 'LinkedIn',
            label: t({
              en: 'Go to our LinkedIn page',
              'en-GB': 'Go to our LinkedIn page',
              fr: 'Aller sur notre page LinkedIn',
              es: 'Ir a nuestra página de LinkedIn',
              de: 'Gehe zu unserer LinkedIn-Seite',
              ja: 'LinkedInページに移動',
              ko: '우리의 LinkedIn 페이지로 이동',
              zh: '前往我们的LinkedIn页面',
              it: 'Vai alla nostra pagina LinkedIn',
              pt: 'Vá para a nossa página do LinkedIn',
              hi: 'हमारे LinkedIn पृष्ठ पर जाएं',
              ar: 'اذهب إلى صفحة LinkedIn الخاصة بنا',
              uk: 'Перейти на нашу сторінку LinkedIn',
              ru: 'Перейти на нашу страницу LinkedIn',
              tr: 'LinkedIn sayfamıza git',
              pl: 'Przejdź na naszą stronę na LinkedIn',
              id: 'Kunjungi halaman LinkedIn kami',
              vi: 'Xem trang LinkedIn của chúng tôi',
            }),
          },
        ],
      },
    ],
  },
  title: 'Footer content',
  description:
    'Multilingual content for the website footer, including documentation links, i18n benchmarks, and informational resources such as terms of service and privacy notice.',
  tags: ['footer', 'navigation', 'documentation links', 'benchmarks', 'legal'],
} satisfies Dictionary<FooterContent>;
export default footerContent;
