import type { LinkGroup } from '@intlayer/design-system';
import { type Dictionary, t } from 'intlayer';
import { ExternalLinks, PagesRoutes } from '../../Routes';

type FooterContent = {
  content: LinkGroup[];
};

const footerContent = {
  key: 'footer',
  content: {
    content: [
      {
        title: 'Docs',
        links: [
          {
            href: PagesRoutes.Doc,
            text: t({
              en: 'Getting started',
              'en-GB': 'Getting started',
              fr: 'Commencez facilement',
              es: 'Empezando',
              de: 'Erste Schritte',
              ja: 'はじめに',
              ko: '시작하기',
              zh: '开始使用',
              it: 'Iniziare',
              pt: 'Começando',
              hi: 'आरंभ करें',
              ar: 'بدء الاستخدام',
              ru: 'Начало работы',
              tr: 'Başlarken',
              pl: 'Pierwsze kroki',
              id: 'Memulai',
              vi: 'Bắt đầu',
            }),
            label: t({
              en: 'See getting started documentation',
              'en-GB': 'See getting started documentation',
              fr: 'Voir la documentation de démarrage',
              es: 'Ver documentación de inicio',
              de: 'Siehe Dokumentation zum Einstieg',
              ja: '使い方のドキュメントを見る',
              ko: '시작 문서 보기',
              zh: '查看开始使用文档',
              it: 'Vedi la documentazione di avvio',
              pt: 'Veja a documentação de início',
              hi: 'आरंभ दस्तावेज़ देखें',
              ar: 'قم بمشاهدة توثيق البدء',
              ru: 'См. документацию по началу работы',
              tr: 'Başlarken belgelerine göz atın',
              pl: 'Zobacz dokumentację dotyczącą pierwszych kroków',
              id: 'Lihat dokumentasi untuk memulai',
              vi: 'Xem tài liệu hướng dẫn bắt đầu',
            }),
          },
          {
            href: PagesRoutes.Doc_Environment_NextJS_15,
            text: t({
              en: 'Intlayer with Next.js',
              'en-GB': 'Intlayer with Next.js',
              fr: 'Intlayer avec Next.js',
              es: 'Intlayer con Next.js',
              de: 'Intlayer mit Next.js',
              ja: 'IntlayerとNext.js',
              ko: 'Intlayer와 Next.js',
              zh: 'Intlayer与Next.js',
              it: 'Intlayer con Next.js',
              pt: 'Intlayer com Next.js',
              hi: 'Intlayer के साथ Next.js',
              ar: 'Intlayer مع Next.js',
              ru: 'Intlayer с Next.js',
              tr: 'Intlayer ile Next.js',
              pl: 'Intlayer z Next.js',
              id: 'Intlayer dengan Next.js',
              vi: 'Intlayer với Next.js',
            }),
            label: t({
              en: 'See Intlayer with Next.js documentation',
              'en-GB': 'See Intlayer with Next.js documentation',
              fr: 'Voir la documentation de Intlayer avec Next.js',
              es: 'Ver documentación de Intlayer con Next.js',
              de: 'Siehe Dokumentation zu Intlayer mit Next.js',
              ja: 'IntlayerとNext.jsのドキュメントを見る',
              ko: 'Intlayer와 Next.js 문서 보기',
              zh: '查看Intlayer与Next.js文档',
              it: 'Vedi la documentazione di Intlayer con Next.js',
              pt: 'Veja a documentação do Intlayer com Next.js',
              hi: 'Intlayer के साथ Next.js दस्तावेज़ देखें',
              ar: 'قم بمشاهدة توثيق Intlayer مع Next.js',
              ru: 'См. документацию Intlayer с Next.js',
              tr: 'Intlayer ile Next.js belgelerine göz atın',
              pl: 'Zobacz dokumentację Intlayer dla Next.js',
              id: 'Lihat dokumentasi Intlayer dengan Next.js',
              vi: 'Xem tài liệu Intlayer với Next.js',
            }),
          },

          {
            href: PagesRoutes.Doc_Environment_ViteAndReact,
            text: t({
              en: 'Intlayer with Vite and React',
              'en-GB': 'Intlayer with Vite and React',
              fr: 'Intlayer avec Vite et React',
              es: 'Intlayer con Vite y React',
              de: 'Intlayer mit React und Vite',
              ja: 'IntlayerとReactおよびVite',
              ko: 'Intlayer와 React 및 Vite',
              zh: 'Intlayer与React和Vite',
              it: 'Intlayer con React e Vite',
              pt: 'Intlayer com React e Vite',
              hi: 'Intlayer के साथ React और Vite',
              ar: 'Intlayer مع React و Vite',
              ru: 'Intlayer с React и Vite',
              tr: 'Intlayer ile Vite ve React',
              pl: 'Intlayer z Vite i React',
              id: 'Intlayer dengan Vite dan React',
              vi: 'Intlayer với Vite và React',
            }),
            label: t({
              en: 'See Intlayer with react and vite documentation',
              'en-GB': 'See Intlayer with react and vite documentation',
              fr: 'Voir la documentation de Intlayer avec react et vite',
              es: 'Ver documentación de Intlayer con react y vite',
              de: 'Siehe Dokumentation zu Intlayer mit React und Vite',
              ja: 'IntlayerとReactおよびViteのドキュメントを見る',
              ko: 'Intlayer와 React 및 Vite 문서 보기',
              zh: '查看Intlayer与React和Vite文档',
              it: 'Vedi la documentazione di Intlayer con React e Vite',
              pt: 'Veja a documentação do Intlayer com React e Vite',
              hi: 'Intlayer के साथ React और Vite दस्तावेज़ देखें',
              ar: 'قم بمشاهدة توثيق Intlayer مع React و Vite',
              ru: 'См. документацию Intlayer с React и Vite',
              tr: 'Intlayer ile React ve Vite belgelerine göz atın',
              pl: 'Zobacz dokumentację Intlayer dla Vite i React',
              id: 'Lihat dokumentasi Intlayer dengan Vite dan React',
              vi: 'Xem tài liệu Intlayer với React và Vite',
            }),
          },
          {
            href: PagesRoutes.Doc_Environment_ViteAndVue,
            text: t({
              en: 'Intlayer with vue and vite',
              'en-GB': 'Intlayer with vue and vite',
              fr: 'Intlayer avec vue et vite',
              es: 'Intlayer con vue y vite',
              de: 'Intlayer mit Vue und Vite',
              ja: 'IntlayerとVueおよびVite',
              ko: 'Intlayer와 Vue 및 Vite',
              zh: 'Intlayer与Vue和Vite',
              it: 'Intlayer con Vue e Vite',
              pt: 'Intlayer com Vue e Vite',
              hi: 'Intlayer के साथ Vue और Vite',
              ar: 'Intlayer مع Vue و Vite',
              ru: 'Intlayer с Vue и Vite',
              tr: 'Intlayer ile Vue ve Vite',
              pl: 'Intlayer z Vue i Vite',
              id: 'Intlayer dengan Vue dan Vite',
              vi: 'Intlayer với Vue và Vite',
            }),
            label: t({
              en: 'See Intlayer with vue and vite documentation',
              'en-GB': 'See Intlayer with vue and vite documentation',
              fr: 'Voir la documentation de Intlayer avec vue et vite',
              es: 'Ver documentación de Intlayer con vue y vite',
              de: 'Siehe Dokumentation zu Intlayer mit Vue und Vite',
              ja: 'IntlayerとVueおよびViteのドキュメントを見る',
              ko: 'Intlayer와 Vue 및 Vite 문서 보기',
              zh: '查看Intlayer与Vue和Vite文档',
              it: 'Vedi la documentazione di Intlayer con Vue e Vite',
              pt: 'Veja a documentação do Intlayer com Vue e Vite',
              hi: 'Intlayer के साथ Vue और Vite दस्तावेज़ दें',
              ar: 'قم بمشاهدة توثيق Intlayer مع Vue و Vite',
              ru: 'См. документацию Intlayer с Vue и Vite',
              tr: 'Intlayer ile Vue ve Vite belgelerine göz atın',
              pl: 'Zobacz dokumentację Intlayer dla Vue i Vite',
              id: 'Lihat dokumentasi Intlayer dengan Vue dan Vite',
              vi: 'Xem tài liệu Intlayer với Vue và Vite',
            }),
          },
        ],
      },
      {
        title: t({
          en: 'Examples',
          'en-GB': 'Examples',
          fr: 'Exemples',
          es: 'Ejemplos',
          de: 'Beispiele',
          ja: '例',
          ko: '예',
          zh: '示例',
          it: 'Esempi',
          pt: 'Exemplos',
          hi: 'उदाहरण',
          ar: 'أمثلة',
          ru: 'Примеры',
          tr: 'Örnekler',
          pl: 'Przykłady',
          id: 'Contoh',
          vi: 'Ví dụ',
        }),
        links: [
          {
            href: ExternalLinks.ExampleIntlayerWithNextjs,
            text: t({
              en: 'Intlayer with Next.js',
              'en-GB': 'Intlayer with Next.js',
              fr: 'Intlayer avec Next.js',
              es: 'Intlayer con Next.js',
              de: 'Intlayer mit Next.js',
              ja: 'IntlayerとNext.js',
              ko: 'Intlayer와 Next.js',
              zh: 'Intlayer与Next.js',
              it: 'Intlayer con Next.js',
              pt: 'Intlayer com Next.js',
              hi: 'Intlayer के साथ Next.js',
              ar: 'Intlayer مع Next.js',
              ru: 'Intlayer с Next.js',
              tr: 'Intlayer ile Next.js',
              pl: 'Intlayer z Next.js',
              id: 'Intlayer dengan Next.js',
              vi: 'Intlayer với Next.js',
            }),
            label: t({
              en: 'See how to set up Intlayer with Next.js',
              'en-GB': 'See how to set up Intlayer with Next.js',
              fr: 'Voir comment configurer Intlayer avec Next.js',
              es: 'Ver cómo configurar Intlayer con Next.js',
              de: 'Siehe, wie man Intlayer mit Next.js einrichtet',
              ja: 'IntlayerをNext.jsと設定する方法を見る',
              ko: 'Intlayer를 Next.js와 설정하는 방법 보기',
              zh: '查看如何设置Intlayer与Next.js',
              it: 'Vedi come configurare Intlayer con Next.js',
              pt: 'Veja como configurar o Intlayer com Next.js',
              hi: 'Intlayer को Next.js के साथ स्थापित करने का तरीका देखें',
              ar: 'قم بمشاهدة كيفية إعداد Intlayer مع Next.js',
              ru: 'См. как настроить Intlayer с Next.js',
              tr: 'Intlayer ile Next.js nasıl kurulur öğrenin',
              pl: 'Zobacz, jak skonfigurować Intlayer z Next.js',
              id: 'Lihat cara mengatur Intlayer dengan Next.js',
              vi: 'Xem cách cài đặt Intlayer với Next.js',
            }),
          },
          {
            href: ExternalLinks.ExampleIntlayerWithReactJS,
            text: t({
              en: 'Intlayer with react (CRA)',
              'en-GB': 'Intlayer with react (CRA)',
              fr: 'Intlayer avec react (CRA)',
              es: 'Intlayer con react (CRA)',
              de: 'Intlayer mit React (CRA)',
              ja: 'IntlayerとReact (CRA)',
              ko: 'Intlayer와 React (CRA)',
              zh: 'Intlayer与React (CRA)',
              it: 'Intlayer con React (CRA)',
              pt: 'Intlayer com React (CRA)',
              hi: 'Intlayer के साथ React (CRA)',
              ar: 'Intlayer مع React (CRA)',
              ru: 'Intlayer с React (CRA)',
              tr: 'Intlayer ile React (CRA)',
              pl: 'Intlayer z React (CRA)',
              id: 'Intlayer dengan react (CRA)',
              vi: 'Intlayer với React (CRA)',
            }),
            label: t({
              en: 'See how to set up Intlayer with react (CRA)',
              'en-GB': 'See how to set up Intlayer with react (CRA)',
              fr: 'Voir comment configurer Intlayer avec react (CRA)',
              es: 'Ver cómo configurar Intlayer con react (CRA)',
              de: 'Siehe, wie man Intlayer mit React (CRA) einrichtet',
              ja: 'IntlayerをReact (CRA)と設定する方法を見る',
              ko: 'Intlayer를 React (CRA)와 설정하는 방법 보기',
              zh: '查看如何设置Intlayer与React (CRA)',
              it: 'Vedi come configurare Intlayer con React (CRA)',
              pt: 'Veja como configurar o Intlayer com React (CRA)',
              hi: 'Intlayer को React (CRA) के साथ स्थापित करने का तरीका देखें',
              ar: 'قم بمشاهدة كيفية إعداد Intlayer مع React (CRA)',
              ru: 'См. как настроить Intlayer с React (CRA)',
              tr: 'Intlayer ile React (CRA) nasıl kurulur öğrenin',
              pl: 'Zobacz, jak skonfigurować Intlayer z React (CRA)',
              id: 'Lihat cara mengatur Intlayer dengan React (CRA)',
              vi: 'Xem cách cài đặt Intlayer với React (CRA)',
            }),
          },
          {
            href: ExternalLinks.ExampleIntlayerWithViteAndReact,
            text: t({
              en: 'Intlayer with Vite and React',
              'en-GB': 'Intlayer with Vite and React',
              fr: 'Intlayer avec Vite et React',
              es: 'Intlayer con Vite y React',
              de: 'Intlayer mit Vite und React',
              ja: 'IntlayerとViteおよびReact',
              ko: 'Intlayer와 Vite 및 React',
              zh: 'Intlayer与Vite和React',
              it: 'Intlayer con Vite e React',
              pt: 'Intlayer com Vite e React',
              hi: 'Intlayer के साथ Vite और React',
              ar: 'Intlayer مع Vite و React',
              ru: 'Intlayer с Vite и React',
              tr: 'Intlayer ile Vite ve React',
              pl: 'Intlayer z Vite i React',
              id: 'Intlayer dengan Vite dan React',
              vi: 'Intlayer với Vite và React',
            }),
            label: t({
              en: 'See how to set up Intlayer with Vite and React',
              'en-GB': 'See how to set up Intlayer with Vite and React',
              fr: 'Voir comment configurer Intlayer avec Vite et React',
              es: 'Ver cómo configurar Intlayer con Vite y React',
              de: 'Siehe, wie man Intlayer mit Vite und React einrichtet',
              ja: 'IntlayerをViteとReactと設定する方法を見る',
              ko: 'Intlayer를 Vite 및 React와 설정하는 방법 보기',
              zh: '查看如何设置Intlayer与Vite和React',
              it: 'Vedi come configurare Intlayer con Vite e React',
              pt: 'Veja como configurar o Intlayer com Vite e React',
              hi: 'Intlayer को Vite और React के साथ स्थापित करने का तरीका देखें',
              ar: 'قم بمشاهدة كيفية إعداد Intlayer مع Vite و React',
              ru: 'См. как настроить Intlayer с Vite и React',
              tr: 'Intlayer ile Vite ve React nasıl kurulur öğrenin',
              pl: 'Zobacz, jak skonfigurować Intlayer z Vite i React',
              id: 'Lihat cara mengatur Intlayer dengan Vite dan React',
              vi: 'Xem cách cài đặt Intlayer với Vite và React',
            }),
          },
          {
            href: ExternalLinks.ExampleIntlayerWithViteAndVue,
            text: t({
              en: 'Intlayer with Vite and Vue',
              'en-GB': 'Intlayer with Vite and Vue',
              fr: 'Intlayer avec Vite et Vue',
              es: 'Intlayer con Vite y Vue',
              de: 'Intlayer mit Vite und Vue',
              ja: 'IntlayerとViteおよびVue',
              ko: 'Intlayer와 Vite 및 Vue',
              zh: 'Intlayer与Vite和Vue',
              it: 'Intlayer con Vite e Vue',
              pt: 'Intlayer com Vite e Vue',
              hi: 'Intlayer के साथ Vite और Vue',
              ar: 'Intlayer مع Vite و Vue',
              ru: 'Intlayer с Vite и Vue',
              tr: 'Intlayer ile Vite ve Vue',
              pl: 'Intlayer z Vite i Vue',
              id: 'Intlayer dengan Vite dan Vue',
              vi: 'Intlayer với Vite và Vue',
            }),
            label: t({
              en: 'See how to set up Intlayer with Vite and Vue',
              'en-GB': 'See how to set up Intlayer with Vite and Vue',
              fr: 'Voir comment configurer Intlayer avec Vite et Vue',
              es: 'Ver cómo configurar Intlayer con Vite y Vue',
              de: 'Siehe, wie man Intlayer mit Vite und Vue einrichtet',
              ja: 'IntlayerをViteとVueと設定する方法を見る',
              ko: 'Intlayer를 Vite 및 Vue와 설정하는 방법 보기',
              zh: '查看如何设置Intlayer与Vite和Vue',
              it: 'Vedi come configurare Intlayer con Vite e Vue',
              pt: 'Veja como configurar o Intlayer com Vite e Vue',
              hi: 'Intlayer को Vite और Vue के साथ स्थापित करने का तरीका देखें',
              ar: 'قم بمشاهدة كيفية إعداد Intlayer مع Vite و Vue',
              ru: 'См. как настроить Intlayer с Vite и Vue',
              tr: 'Intlayer ile Vite ve Vue nasıl kurulur öğrenin',
              pl: 'Zobacz, jak skonfigurować Intlayer z Vite i Vue',
              id: 'Lihat cara mengatur Intlayer dengan Vite dan Vue',
              vi: 'Xem cách cài đặt Intlayer với Vite và Vue',
            }),
          },
        ],
      },
      {
        title: t({
          en: 'Learn more',
          'en-GB': 'Learn more',
          fr: 'En savoir plus',
          es: 'Aprende más',
          de: 'Mehr erfahren',
          ja: 'もっと学ぶ',
          ko: '자세히 알아보기',
          zh: '了解更多',
          it: 'Scopri di più',
          pt: 'Saiba mais',
          hi: 'और जानें',
          ar: 'تعلم المزيد',
          ru: 'Узнать больше',
          tr: 'Daha fazla bilgi edin',
          pl: 'Dowiedz się więcej',
          id: 'Pelajari lebih lanjut',
          vi: 'Tìm hiểu thêm',
        }),
        links: [
          {
            href: PagesRoutes.Contributors,
            text: t({
              en: 'Contributors',
              'en-GB': 'Contributors',
              fr: 'Contributeurs',
              es: 'Contribuyentes',
              de: 'Mitwirkende',
              ja: '貢献者',
              ko: '기여자',
              zh: '贡献者',
              it: 'Contributori',
              pt: 'Contribuintes',
              hi: 'योगदाता',
              ar: 'مساهمون',
              ru: 'Участники',
              tr: 'Katkıda bulunanlar',
              pl: 'Współtwórcy',
              id: 'Kontributor',
              vi: 'Người đóng góp',
            }),
            label: t({
              en: 'See our contributors',
              'en-GB': 'See our contributors',
              fr: 'Voir nos contributeurs',
              es: 'Ver nuestros contribuyentes',
              de: 'Sehen Sie unsere Mitwirkenden',
              ja: '貢献者を見る',
              ko: '기여자 보기',
              zh: '查看我们的贡献者',
              it: 'Vedi i nostri contributori',
              pt: 'Ver nossos contribuintes',
              hi: 'हमारे योगदाता देखें',
              ar: 'اعرض مساهمينا',
              ru: 'Посмотреть наших участников',
              tr: 'Katkıda bulunanları görüntüle',
              pl: 'Zobacz naszych współtwórców',
              id: 'Lihat kontributor kami',
              vi: 'Xem những người đóng góp',
            }),
          },
          {
            href: PagesRoutes.TermsOfService,
            text: t({
              en: 'Terms of service',
              'en-GB': 'Terms of service',
              fr: 'Conditions de service',
              es: 'Términos de servicio',
              de: 'Nutzungsbedingungen',
              ja: 'サービス規約',
              ko: '서비스 약관',
              zh: '服务条款',
              it: 'Termini di servizio',
              pt: 'Termos de serviço',
              hi: 'सेवाओं की शर्तें',
              ar: 'شروط الخدمة',
              ru: 'Условия обслуживания',
              tr: 'Hizmet Şartları',
              pl: 'Regulamin',
              id: 'Syarat Layanan',
              vi: 'Điều khoản dịch vụ',
            }),
            label: t({
              en: 'Read our terms of service',
              'en-GB': 'Read our terms of service',
              fr: 'Lisez nos conditions de service',
              es: 'Lee nuestros términos de servicio',
              de: 'Lesen Sie unsere Nutzungsbedingungen',
              ja: 'サービス規約を読む',
              ko: '서비스 약관을 읽다',
              zh: '阅读我们的服务条款',
              it: 'Leggi i nostri termini di servizio',
              pt: 'Leia nossos termos de serviço',
              hi: 'हमारी सेवाओं की शर्तों को पढ़ें',
              ar: 'اقرأ شروط الخدمة الخاصة بنا',
              ru: 'Прочтите наши условия обслуживания',
              tr: 'Hizmet şartlarımızı okuyun',
              pl: 'Przeczytaj nasz regulamin',
              id: 'Baca syarat layanan kami',
              vi: 'Đọc điều khoản dịch vụ của chúng tôi',
            }),
          },
          {
            href: PagesRoutes.PrivacyPolicy,
            text: t({
              en: 'Privacy Notice',
              'en-GB': 'Privacy Notice',
              fr: 'Avis de confidentialité',
              es: 'Aviso de privacidad',
              de: 'Datenschutzinformationen',
              ja: 'プライバシー通知',
              ko: '개인정보 보호 공지',
              zh: '隐私通知',
              it: 'Avviso sulla privacy',
              pt: 'Aviso de privacidade',
              hi: 'गोपनीयता अधिसूचना',
              ar: 'إشعار الخصوصية',
              ru: 'Уведомление о конфиденциальности',
              tr: 'Gizlilik Bildirimi',
              pl: 'Polityka prywatności',
              id: 'Pemberitahuan Privasi',
              vi: 'Chính sách bảo mật',
            }),
            label: t({
              en: 'Read our privacy notice',
              'en-GB': 'Read our privacy notice',
              fr: 'Lisez notre avis de confidentialité',
              es: 'Lee nuestro aviso de privacidad',
              de: 'Lesen Sie unsere Datenschutzinformationen',
              ja: 'プライバシー通知を読む',
              ko: '개인정보 보호 공지를 읽다',
              zh: '阅读我们的隐私通知',
              it: 'Leggi il nostro avviso sulla privacy',
              pt: 'Leia nosso aviso de privacidade',
              hi: 'हमारी गोपनीयता अधिसूचना पढ़ें',
              ar: 'اقرأ إشعار الخصوصية الخاص بنا',
              ru: 'Прочтите наше уведомление о конфиденциальности',
              tr: 'Gizlilik bildirimimizi okuyun',
              pl: 'Przeczytaj naszą politykę prywatności',
              id: 'Baca pemberitahuan privasi kami',
              vi: 'Đọc chính sách bảo mật của chúng tôi',
            }),
          },
          {
            href: ExternalLinks.LinkedIn,
            text: 'LinkedIn',
            label: t({
              en: 'Go to our LinkedIn page',
              'en-GB': 'Go to our LinkedIn page',
              fr: 'Aller sur notre page LinkedIn',
              es: 'Ir a nuestra página de LinkedIn',
              de: 'Gehe zu unserer LinkedIn-Seite',
              ja: 'LinkedInページに移動',
              ko: '우리의 LinkedIn 페이지로 이동',
              zh: '前往我们的LinkedIn页面',
              it: 'Vai alla nostra pagina LinkedIn',
              pt: 'Vá para a nossa página do LinkedIn',
              hi: 'हमारे LinkedIn पृष्ठ पर जाएं',
              ar: 'اذهب إلى صفحة LinkedIn الخاصة بنا',
              ru: 'Перейти на нашу страницу LinkedIn',
              tr: 'LinkedIn sayfamıza git',
              pl: 'Przejdź na naszą stronę na LinkedIn',
              id: 'Kunjungi halaman LinkedIn kami',
              vi: 'Xem trang LinkedIn của chúng tôi',
            }),
          },
        ],
      },
    ],
  },
  title: 'Footer content',
  description:
    'Multilingual content for the website footer, including documentation links, example projects, and informational resources such as terms of service and privacy notice.',
  tags: ['footer', 'navigation', 'documentation links', 'examples', 'legal'],
} satisfies Dictionary<FooterContent>;
export default footerContent;
