import { t, type Dictionary } from 'intlayer';

const contributionMessageContent = {
  key: 'contribution-message',
  content: {
    contribution: {
      title: t({
        en: 'Edit this doc',
        'en-GB': 'Edit this doc',
        fr: 'Modifier cette documentation',
        es: 'Editar esta documentación',
        de: 'Diese Dokumentation bearbeiten',
        ja: 'このドキュメントを編集',
        ko: '문서 수정',
        zh: '编辑此文档',
        it: 'Modifica questa documentazione',
        pt: 'Editar esta documentação',
        hi: 'इस दस्तावेज़ को संपादित करें',
        ar: 'تعديل هذه الوثيقة',
        ru: 'Изменить эту документацию',
      }),
      text: t({
        en: 'If you have an idea for improving this documentation, please feel free to contribute by submitting a pull request on GitHub.',
        'en-GB':
          'If you have an idea for improving this documentation, please feel free to contribute by submitting a pull request on GitHub.',
        fr: 'Si vous avez une idée d’amélioration pour améliorer cette documentation, n’hésitez pas à contribuer en submitant une pull request sur GitHub.',
        es: 'Si tienes una idea para mejorar esta documentación, no dudes en contribuir enviando una pull request en GitHub.',
        de: 'Wenn Sie eine Idee haben, um diese Dokumentation zu verbessern, zögern Sie bitte nicht, durch das Einreichen eines Pull-Requests auf GitHub beizutragen.',
        ja: 'このドキュメントを改善するアイデアがある場合は、GitHubでプルリクエストを送信することで自由に貢献してください。',
        ko: '이 문서를 개선할 아이디어가 있으시면 GitHub에 풀 리퀘스트를 제출하여 자유롭게 기여해 주세요.',
        zh: '如果您有改善此文档的想法，请随时通过在GitHub上提交拉取请求来贡献。',
        it: 'Se hai un’idea per migliorare questa documentazione, non esitare a contribuire inviando una pull request su GitHub.',
        pt: 'Se você tiver uma ideia para melhorar esta documentação, sinta-se à vontade para contribuir enviando uma pull request no GitHub.',
        hi: 'अगर आपके पास इस दस्तावेज़ को सुधारने के लिए कोई विचार है, तो कृपया GitHub पर एक पुल अनुरोध सबमिट करके योगदान देने में संकोच न करें।',
        ar: 'إذا كان لديك فكرة لتحسين هذه الوثيقة، فلا تتردد في المساهمة من خلال تقديم طلب سحب على GitHub.',
        ru: 'Если у вас есть идея по улучшению этой документации, не стесняйтесь внести свой вклад, подав запрос на вытягивание на GitHub.',
      }),
      button: t({
        en: 'GitHub link to the documentation',
        'en-GB': 'GitHub link to the documentation',
        fr: 'Lien GitHub de la documentation',
        es: 'Enlace de GitHub a la documentación',
        de: 'GitHub-Link zur Dokumentation',
        ja: 'ドキュメントへのGitHubリンク',
        ko: '문서에 대한 GitHub 링크',
        zh: '文档的 GitHub 链接',
        it: 'Collegamento GitHub alla documentazione',
        pt: 'Link do GitHub para a documentação',
        hi: 'दस्तावेज़ के लिए GitHub लिंक',
        ar: 'رابط GitHub للتوثيق',
        ru: 'Ссылка на документацию GitHub',
      }),
      buttonLabel: t({
        en: 'Click here to contribute',
        'en-GB': 'Click here to contribute',
        fr: 'Cliquez ici pour contribuer',
        es: 'Haga clic aquí para contribuir',
        de: 'Klicken Sie hier, um beizutragen',
        ja: '貢献するにはここをクリックしてください',
        ko: '기여하려면 여기를 클릭하세요',
        zh: '点击这里贡献',
        it: 'Clicca qui per contribuire',
        pt: 'Clique aqui para contribuir',
        hi: 'योगदान देने के लिए यहाँ क्लिक करें',
        ar: 'انقر هنا للمساهمة',
        ru: 'Нажмите здесь, чтобы внести свой вклад',
      }),
    },
  },
} satisfies Dictionary;

export default contributionMessageContent;
