import { type Dictionary, t } from 'intlayer';

const applicationTemplateMessageContent = {
  key: 'application-template-message',
  content: {
    title: t({
      ar: 'عرض قالب التطبيق على GitHub',
      de: 'Anwendungsvorlage auf GitHub ansehen',
      en: 'See the application template on GitHub',
      'en-GB': 'See the application template on GitHub',
      es: 'Ver la plantilla de aplicación en GitHub',
      fr: "Voir le modèle d'application sur GitHub",
      hi: 'GitHub पर एप्लिकेशन टेम्पलेट देखें',
      it: 'Visualizza il modello di applicazione su GitHub',
      ja: 'GitHubでアプリケーションテンプレートを見る',
      ko: 'GitHub에서 애플리케이션 템플릿 보기',
      pt: 'Ver o modelo de aplicação no GitHub',
      ru: 'Посмотреть шаблон приложения на GitHub',
      tr: "GitHub'da uygulama şablonunu görüntüle",
      zh: '在 GitHub 上查看应用程序模板',
      pl: 'Zobacz szablon aplikacji na GitHubie',
      id: 'Lihat template aplikasi di GitHub',
      vi: 'Xem mẫu ứng dụng trên GitHub',
      uk: 'Переглянути шаблон додатку на GitHub',
    }),
    description: t({
      ar: 'هذه الصفحة لديها قالب تطبيق متاح.',
      de: 'Für diese Seite ist eine Anwendungsvorlage verfügbar.',
      en: 'This page has an application template available.',
      'en-GB': 'This page has an application template available.',
      es: 'Esta página tiene una plantilla de aplicación disponible.',
      fr: "Cette page dispose d'un modèle d'application disponible.",
      hi: 'इस पृष्ठ के लिए एक एप्लिकेशन टेम्पलेट उपलब्ध है।',
      it: 'Questa pagina ha un modello di applicazione disponibile.',
      ja: 'このページにはアプリケーションテンプレートが用意されています。',
      ko: '이 페이지에는 애플리케이션 템플릿이 제공됩니다.',
      pt: 'Esta página tem um modelo de aplicação disponível.',
      ru: 'Для этой страницы доступен шаблон приложения.',
      tr: 'Bu sayfada kullanılabilir bir uygulama şablonu var.',
      zh: '此页面有可用的应用程序模板。',
      pl: 'Na tej stronie dostępny jest szablon aplikacji.',
      id: 'Halaman ini memiliki template aplikasi yang tersedia.',
      vi: 'Trang này có một mẫu ứng dụng có sẵn.',
      uk: 'На цій сторінці доступний шаблон додатку.',
    }),
    label: t({
      ar: 'عرض قالب التطبيق',
      de: 'Anwendungsvorlage ansehen',
      en: 'See the application template',
      'en-GB': 'See the application template',
      es: 'Ver la plantilla de aplicación',
      fr: "Voir le modèle d'application",
      hi: 'एप्लिकेशन टेम्पलेट देखें',
      it: 'Visualizza il modello di applicazione',
      ja: 'アプリケーションテンプレートを見る',
      ko: '애플리케이션 템플릿 보기',
      pt: 'Ver o modelo de aplicação',
      ru: 'Посмотреть шаблон приложения',
      tr: 'Uygulama şablonunu görüntüle',
      zh: '查看应用程序模板',
      pl: 'Zobacz szablon aplikacji',
      id: 'Lihat template aplikasi',
      vi: 'Xem mẫu ứng dụng',
      uk: 'Переглянути шаблон додатку',
    }),
  },
  title: 'Application template message',
  description:
    'Content related to the application template message displayed on the documentation page. It highlights and links to an available template hosted on GitHub.',
  tags: ['documentation', 'component', 'application template'],
} satisfies Dictionary;

export default applicationTemplateMessageContent;
