import { type Dictionary, t } from 'intlayer';

const reviewerDashboardPageContent = {
  key: 'reviewer-dashboard-page',
  content: {
    // Accessibility labels
    missionsAriaLabel: t({
      en: 'My translation missions',
      fr: 'Mes missions de traduction',
      es: 'Mis misiones de traducción',
      'en-GB': 'My translation missions',
      de: 'Meine Übersetzungsaufträge',
      ja: '私の翻訳ミッション',
      ko: '내 번역 미션',
      zh: '我的翻译任务',
      it: 'Le mie missioni di traduzione',
      pt: 'Minhas missões de tradução',
      hi: 'मेरे अनुवाद मिशन',
      ar: 'مهام الترجمة الخاصة بي',
      ru: 'Мои задания по переводу',
      tr: 'Çeviri görevlerim',
      pl: 'Moje misje tłumaczeniowe',
      id: 'Misi terjemahan saya',
      vi: 'Các nhiệm vụ dịch thuật của tôi',
      uk: 'Мої завдання з перекладу',
    }),
    loadingMissionsAriaLabel: t({
      en: 'Loading missions',
      fr: 'Chargement des missions',
      es: 'Cargando misiones',
      'en-GB': 'Loading missions',
      de: 'Aufträge werden geladen',
      ja: 'ミッションを読み込み中',
      ko: '미션 로딩 중',
      zh: '正在加载任务',
      it: 'Caricamento missioni',
      pt: 'Carregando missões',
      hi: 'मिशन लोड हो रहे हैं',
      ar: 'جارٍ تحميل المهام',
      ru: 'Загрузка заданий',
      tr: 'Görevler yükleniyor',
      pl: 'Wczytywanie misji',
      id: 'Memuat misi',
      vi: 'Đang tải nhiệm vụ',
      uk: 'Завантаження завдань',
    }),
    profilePreviewAriaLabel: t({
      en: 'Your public reviewer profile preview',
      fr: 'Aperçu de votre profil public de traducteur',
      es: 'Vista previa de tu perfil público de traductor',
      'en-GB': 'Your public reviewer profile preview',
      de: 'Vorschau Ihres öffentlichen Reviewer-Profils',
      ja: '公開レビュアープロフィールのプレビュー',
      ko: '공개 리뷰어 프로필 미리보기',
      zh: '您的公开审稿人资料预览',
      it: 'Anteprima del tuo profilo pubblico di revisore',
      pt: 'Pré-visualização do seu perfil público de revisor',
      hi: 'आपके सार्वजनिक समीक्षक प्रोफ़ाइल का पूर्वावलोकन',
      ar: 'معاينة ملفك الشخصي العام كمراجع',
      ru: 'Предварительный просмотр вашего публичного профиля рецензента',
      tr: 'Genel inceleyici profilinizin önizlemesi',
      pl: 'Podgląd Twojego publicznego profilu recenzenta',
      id: 'Pratinjau profil peninjau publik Anda',
      vi: 'Xem trước hồ sơ người đánh giá công khai của bạn',
      uk: 'Попередній перегляд вашого публічного профілю рецензента',
    }),

    title: t({
      en: 'Reviewer Dashboard',
      fr: 'Tableau de bord du relecteur',
      es: 'Panel del traductor',
      'en-GB': 'Reviewer Dashboard',
      de: 'Reviewer-Dashboard',
      ja: 'レビュアーダッシュボード',
      ko: '리뷰어 대시보드',
      zh: '审稿人仪表板',
      it: 'Dashboard del revisore',
      pt: 'Painel do revisor',
      hi: 'समीक्षक डैशबोर्ड',
      ar: 'لوحة تحكم المراجع',
      ru: 'Панель рецензента',
      tr: 'İnceleyici Panosu',
      pl: 'Panel recenzenta',
      id: 'Dasbor Peninjau',
      vi: 'Bảng điều khiển Người đánh giá',
      uk: 'Панель рецензента',
    }),
    notRegisteredMessage: t({
      en: 'You are not registered as a reviewer yet. Fill in the form below to start accepting translation missions.',
      fr: "Vous n'êtes pas encore inscrit en tant que traducteur. Remplissez le formulaire ci-dessous pour commencer à accepter des missions de traduction.",
      es: 'Aún no está registrado como traductor. Rellene el formulario a continuación para comenzar a aceptar misiones de traducción.',
      'en-GB':
        'You are not registered as a reviewer yet. Fill in the form below to start accepting translation missions.',
      de: 'Sie sind noch nicht als Reviewer registriert. Füllen Sie das Formular unten aus, um Übersetzungsaufträge anzunehmen.',
      ja: 'まだレビュアーとして登録されていません。以下のフォームに記入して翻訳ミッションの受付を開始してください。',
      ko: '아직 리뷰어로 등록되지 않았습니다. 아래 양식을 작성하여 번역 미션 수락을 시작하세요.',
      zh: '您尚未注册为审稿人。请填写以下表格，开始接受翻译任务。',
      it: 'Non sei ancora registrato come revisore. Compila il modulo sottostante per iniziare ad accettare missioni di traduzione.',
      pt: 'Você ainda não está registrado como revisor. Preencha o formulário abaixo para começar a aceitar missões de tradução.',
      hi: 'आप अभी तक समीक्षक के रूप में पंजीकृत नहीं हैं। अनुवाद मिशन स्वीकार करना शुरू करने के लिए नीचे दिया गया फ़ॉर्म भरें।',
      ar: 'لم تسجل بعد كمراجع. املأ النموذج أدناه لبدء قبول مهام الترجمة.',
      ru: 'Вы ещё не зарегистрированы как рецензент. Заполните форму ниже, чтобы начать принимать задания по переводу.',
      tr: 'Henüz inceleyici olarak kayıtlı değilsiniz. Çeviri görevlerini kabul etmeye başlamak için aşağıdaki formu doldurun.',
      pl: 'Nie jesteś jeszcze zarejestrowany jako recenzent. Wypełnij poniższy formularz, aby zacząć przyjmować misje tłumaczeniowe.',
      id: 'Anda belum terdaftar sebagai peninjau. Isi formulir di bawah untuk mulai menerima misi terjemahan.',
      vi: 'Bạn chưa đăng ký làm người đánh giá. Điền vào biểu mẫu bên dưới để bắt đầu nhận nhiệm vụ dịch thuật.',
      uk: 'Ви ще не зареєстровані як рецензент. Заповніть форму нижче, щоб почати приймати завдання з перекладу.',
    }),

    myMissionsTitle: t({
      en: 'My Missions',
      fr: 'Mes missions',
      es: 'Mis misiones',
      'en-GB': 'My Missions',
      de: 'Meine Missionen',
      ja: '私のミッション',
      ko: '내 미션',
      zh: '我的任务',
      it: 'Le mie missioni',
      pt: 'Minhas missões',
      hi: 'मेरे मिशन',
      ar: 'مهامي',
      ru: 'Мои задания',
      tr: 'Görevlerim',
      pl: 'Moje misje',
      id: 'Misi Saya',
      vi: 'Nhiệm vụ của tôi',
      uk: 'Мої завдання',
    }),
    profileVisibilityTitle: t({
      en: 'Profile visibility',
      fr: 'Visibilité du profil',
      es: 'Visibilidad del perfil',
      'en-GB': 'Profile visibility',
      de: 'Profilsichtbarkeit',
      ja: 'プロフィールの公開設定',
      ko: '프로필 공개 설정',
      zh: '资料可见性',
      it: 'Visibilità del profilo',
      pt: 'Visibilidade do perfil',
      hi: 'प्रोफाइल दृश्यता',
      ar: 'ظهور الملف الشخصي',
      ru: 'Видимость профиля',
      tr: 'Profil görünürlüğü',
      pl: 'Widoczność profilu',
      id: 'Visibilitas profil',
      vi: 'Khả năng hiển thị hồ sơ',
      uk: 'Видимість профілю',
    }),
    hideProfileButton: t({
      en: 'Hide profile',
      fr: 'Masquer le profil',
      es: 'Ocultar perfil',
      'en-GB': 'Hide profile',
      de: 'Profil verbergen',
      ja: 'プロフィールを非表示にする',
      ko: '프로필 숨기기',
      zh: '隐藏资料',
      it: 'Nascondi profilo',
      pt: 'Ocultar perfil',
      hi: 'प्रोफाइल छुपाएं',
      ar: 'إخفاء الملف الشخصي',
      ru: 'Скрыть профиль',
      tr: 'Profili gizle',
      pl: 'Ukryj profil',
      id: 'Sembunyikan profil',
      vi: 'Ẩn hồ sơ',
      uk: 'Сховати профіль',
    }),
    showProfileButton: t({
      en: 'Show profile',
      fr: 'Afficher le profil',
      es: 'Mostrar perfil',
      'en-GB': 'Show profile',
      de: 'Profil anzeigen',
      ja: 'プロフィールを表示する',
      ko: '프로필 표시',
      zh: '显示资料',
      it: 'Mostra profilo',
      pt: 'Mostrar perfil',
      hi: 'प्रोफाइल दिखाएं',
      ar: 'إظهار الملف الشخصي',
      ru: 'Показать профиль',
      tr: 'Profili göster',
      pl: 'Pokaż profil',
      id: 'Tampilkan profil',
      vi: 'Hiển thị hồ sơ',
      uk: 'Показати профіль',
    }),
    hiddenProfileInfo: t({
      en: 'Your profile is currently hidden from the marketplace.',
      fr: 'Votre profil est actuellement masqué de la marketplace.',
      es: 'Tu perfil está actualmente oculto en el marketplace.',
      'en-GB': 'Your profile is currently hidden from the marketplace.',
      de: 'Ihr Profil ist derzeit auf dem Marktplatz ausgeblendet.',
      ja: 'あなたのプロフィールは現在マーケットプレイスで非表示になっています。',
      ko: '프로필이 현재 마켓플레이스에서 숨겨져 있습니다.',
      zh: '您的资料目前在市场上已隐藏。',
      it: 'Il tuo profilo è attualmente nascosto dal marketplace.',
      pt: 'Seu perfil está atualmente oculto no marketplace.',
      hi: 'आपकी प्रोफाइल वर्तमान में मार्केटप्लेस से छुपी हुई है।',
      ar: 'ملفك الشخصي مخفي حاليًا من السوق.',
      ru: 'Ваш профиль в данный момент скрыт на рынке.',
      tr: 'Profiliniz şu anda pazaryerinden gizlenmiştir.',
      pl: 'Twój profil jest obecnie ukryty na rynku.',
      id: 'Profil Anda saat ini disembunyikan dari marketplace.',
      vi: 'Hồ sơ của bạn hiện đang bị ẩn khỏi thị trường.',
      uk: 'Ваш профіль наразі прихований з ринку.',
    }),
    deleteProfileButton: t({
      en: 'Delete profile',
      fr: 'Supprimer le profil',
      es: 'Eliminar perfil',
      'en-GB': 'Delete profile',
      de: 'Profil löschen',
      ja: 'プロフィールを削除する',
      ko: '프로필 삭제',
      zh: '删除资料',
      it: 'Elimina profilo',
      pt: 'Excluir perfil',
      hi: 'प्रोफाइल हटाएं',
      ar: 'حذف الملف الشخصي',
      ru: 'Удалить профиль',
      tr: 'Profili sil',
      pl: 'Usuń profil',
      id: 'Hapus profil',
      vi: 'Xóa hồ sơ',
      uk: 'Видалити профіль',
    }),
    deleteConfirmTitle: t({
      en: 'Delete your reviewer profile?',
      fr: 'Supprimer votre profil de traducteur ?',
      es: '¿Eliminar tu perfil de traductor?',
      'en-GB': 'Delete your reviewer profile?',
      de: 'Reviewer-Profil löschen?',
      ja: 'レビュアープロフィールを削除しますか？',
      ko: '리뷰어 프로필을 삭제하시겠습니까?',
      zh: '删除您的审稿人资料？',
      it: 'Eliminare il profilo revisore?',
      pt: 'Excluir seu perfil de revisor?',
      hi: 'समीक्षक प्रोफाइल हटाएं?',
      ar: 'حذف ملف المراجع الخاص بك؟',
      ru: 'Удалить профиль рецензента?',
      tr: 'Gözden geçirici profiliniz silinsin mi?',
      pl: 'Usunąć profil recenzenta?',
      id: 'Hapus profil peninjau Anda?',
      vi: 'Xóa hồ sơ người đánh giá của bạn?',
      uk: 'Видалити профіль рецензента?',
    }),
    deleteConfirmDescription: t({
      en: 'This action is permanent. Your profile, ratings and mission history will be removed from the marketplace.',
      fr: 'Cette action est permanente. Votre profil, vos évaluations et votre historique de missions seront supprimés de la marketplace.',
      es: 'Esta acción es permanente. Tu perfil, calificaciones e historial de misiones se eliminarán del marketplace.',
      'en-GB':
        'This action is permanent. Your profile, ratings and mission history will be removed from the marketplace.',
      de: 'Diese Aktion ist dauerhaft. Ihr Profil, Bewertungen und Auftragsverlauf werden aus dem Marktplatz entfernt.',
      ja: 'この操作は元に戻せません。プロフィール、評価、ミッション履歴がマーケットプレイスから削除されます。',
      ko: '이 작업은 영구적입니다. 프로필, 평점 및 미션 내역이 마켓플레이스에서 제거됩니다.',
      zh: '此操作是永久性的。您的资料、评分和任务历史记录将从市场中删除。',
      it: 'Questa azione è permanente. Il tuo profilo, le valutazioni e la cronologia delle missioni verranno rimossi dal marketplace.',
      pt: 'Esta ação é permanente. Seu perfil, avaliações e histórico de missões serão removidos do marketplace.',
      hi: 'यह कार्य स्थायी है। आपकी प्रोफाइल, रेटिंग और मिशन इतिहास मार्केटप्लेस से हटा दिए जाएंगे।',
      ar: 'هذا الإجراء دائم. ستتم إزالة ملفك الشخصي وتقييماتك وسجل مهامك من السوق.',
      ru: 'Это действие необратимо. Ваш профиль, оценки и история заданий будут удалены с рынка.',
      tr: 'Bu eylem kalıcıdır. Profiliniz, puanlarınız ve görev geçmişiniz pazaryerinden kaldırılacaktır.',
      pl: 'Ta akcja jest trwała. Twój profil, oceny i historia misji zostaną usunięte z rynku.',
      id: 'Tindakan ini bersifat permanen. Profil, penilaian, dan riwayat misi Anda akan dihapus dari marketplace.',
      vi: 'Hành động này là vĩnh viễn. Hồ sơ, xếp hạng và lịch sử nhiệm vụ của bạn sẽ bị xóa khỏi thị trường.',
      uk: 'Ця дія є незворотною. Ваш профіль, оцінки та історія завдань будуть видалені з ринку.',
    }),
    deleteConfirmButton: t({
      en: 'Yes, delete permanently',
      fr: 'Oui, supprimer définitivement',
      es: 'Sí, eliminar permanentemente',
      'en-GB': 'Yes, delete permanently',
      de: 'Ja, dauerhaft löschen',
      ja: 'はい、完全に削除する',
      ko: '예, 영구 삭제',
      zh: '是的，永久删除',
      it: 'Sì, elimina definitivamente',
      pt: 'Sim, excluir permanentemente',
      hi: 'हाँ, स्थायी रूप से हटाएं',
      ar: 'نعم، حذف نهائيًا',
      ru: 'Да, удалить навсегда',
      tr: 'Evet, kalıcı olarak sil',
      pl: 'Tak, usuń trwale',
      id: 'Ya, hapus secara permanen',
      vi: 'Có, xóa vĩnh viễn',
      uk: 'Так, видалити назавжди',
    }),
    cancelButton: t({
      en: 'Cancel',
      fr: 'Annuler',
      es: 'Cancelar',
      'en-GB': 'Cancel',
      de: 'Abbrechen',
      ja: 'キャンセル',
      ko: '취소',
      zh: '取消',
      it: 'Annulla',
      pt: 'Cancelar',
      hi: 'रद्द करें',
      ar: 'إلغاء',
      ru: 'Отмена',
      tr: 'İptal',
      pl: 'Anuluj',
      id: 'Batal',
      vi: 'Hủy',
      uk: 'Скасувати',
    }),
    pendingMessage: t({
      en: 'Your profile is under review. You will receive an email once it is approved and you appear on the marketplace.',
      fr: "Votre profil est en cours d'examen. Vous recevrez un e-mail une fois qu'il sera approuvé et que vous apparaîtrez sur la marketplace.",
      es: 'Tu perfil está siendo revisado. Recibirás un correo electrónico una vez que sea aprobado y aparezcas en el marketplace.',
      'en-GB':
        'Your profile is under review. You will receive an email once it is approved and you appear on the marketplace.',
      de: 'Ihr Profil wird überprüft. Sie erhalten eine E-Mail, sobald es genehmigt wurde und Sie auf dem Marktplatz erscheinen.',
      ja: 'プロフィールは審査中です。承認されてマーケットプレイスに掲載されると、メールでお知らせします。',
      ko: '프로필이 검토 중입니다. 승인되어 마켓플레이스에 표시되면 이메일을 받게 됩니다.',
      zh: '您的资料正在审核中。审核通过并在市场上展示后，您将收到电子邮件通知。',
      it: "Il tuo profilo è in fase di revisione. Riceverai un'email una volta approvato e visibile nel marketplace.",
      pt: 'Seu perfil está sendo revisado. Você receberá um e-mail quando for aprovado e aparecer no marketplace.',
      hi: 'आपकी प्रोफ़ाइल समीक्षाधीन है। जैसे ही यह अनुमोदित हो जाती है और आप मार्केटप्लेस पर दिखने लगते हैं, आपको एक ईमेल प्राप्त होगा।',
      ar: 'ملفك الشخصي قيد المراجعة. ستتلقى بريداً إلكترونياً بمجرد الموافقة عليه وظهورك في السوق.',
      ru: 'Ваш профиль проходит проверку. Вы получите письмо, когда он будет одобрен и появится на рынке.',
      tr: 'Profiliniz inceleniyor. Onaylandıktan ve pazaryerinde görünmeye başladıktan sonra bir e-posta alacaksınız.',
      pl: 'Twój profil jest w trakcie weryfikacji. Otrzymasz e-mail, gdy zostanie zatwierdzony i pojawi się na rynku.',
      id: 'Profil Anda sedang ditinjau. Anda akan menerima email setelah disetujui dan muncul di marketplace.',
      vi: 'Hồ sơ của bạn đang được xem xét. Bạn sẽ nhận được email khi được phê duyệt và xuất hiện trên thị trường.',
      uk: 'Ваш профіль перевіряється. Ви отримаєте електронний лист після схвалення та появи на ринку.',
    }),
  },
} satisfies Dictionary;

export default reviewerDashboardPageContent;
