import { t, type Dictionary } from 'intlayer';
import { type Metadata } from 'next';

const docContent = {
  key: 'doc-content-declaration-enumeration-metadata',
  content: {
    title: t({
      en: 'Enumeration',
      'en-GB': 'Enumeration',
      fr: 'Énumération',
      es: 'Enumeración',
      de: 'Enumeration',
      ja: '列挙',
      ko: '열거',
      zh: '枚举',
      it: 'Enumerazione',
      pt: 'Enumeração',
      hi: 'सूची',
      ar: 'التعداد',
      ru: 'Перечисление',
    }),

    description: t({
      en: 'Discover how to declare and use enumerations in your multilingual website. Follow the steps in this online documentation to set up your project in a few minutes.',
      'en-GB':
        'Discover how to declare and use enumerations in your multilingual website. Follow the steps in this online documentation to set up your project in a few minutes.',
      fr: 'Découvrez comment déclarer et utiliser des énumérations dans votre site web multilingue. Suivez les étapes de cette documentation en ligne pour configurer votre projet en quelques minutes.',
      es: 'Descubra cómo declarar y usar enumeraciones en su sitio web multilingüe. Siga los pasos de esta documentación en línea para configurar su proyecto en unos minutos.',
      de: 'Entdecken Sie, wie Sie Enumerationen in Ihrer mehrsprachigen Website deklarieren und verwenden. Befolgen Sie die Schritte in dieser Online-Dokumentation, um Ihr Projekt in wenigen Minuten einzurichten.',
      ja: '多言語ウェブサイトで列挙を宣言し使用する方法を発見してください。このオンライン文書の手順に従って、数分でプロジェクトをセットアップします。',
      ko: '다국어 웹사이트에서 열거를 선언하고 사용하는 방법을 알아보세요. 이 온라인 문서의 단계를 따라 몇 분 만에 프로젝트를 설정하세요.',
      zh: '发现如何在您的多语言网站中声明和使用枚举。按照此在线文档中的步骤，在几分钟内设置您的项目。',
      it: 'Scopri come dichiarare e utilizzare le enumerazioni nel tuo sito web multilingue. Segui i passaggi in questa documentazione online per impostare il tuo progetto in pochi minuti.',
      pt: 'Descubra como declarar e usar enumerações em seu site multilíngue. Siga os passos nesta documentação online para configurar seu projeto em poucos minutos.',
      hi: 'अपने बहुभाषी वेबसाइट में अनुक्रमों को घोषित और उपयोग करने का तरीका खोजें। अपने प्रोजेक्ट को कुछ मिनटों में सेटअप करने के लिए इस ऑनलाइन दस्तावेज़ में चरणों का पालन करें।',
      ar: 'اكتشف كيفية إعلان واستخدام التعدادات في موقعك الإلكتروني متعدد اللغات. اتبع الخطوات في هذه الوثيقة الإلكترونية لإعداد مشروعك في بضع دقائق.',
      ru: 'Узнайте, как объявлять и использовать перечисления на вашем многоязычном сайте. Следуйте шагам в этой онлайн-документации, чтобы настроить свой проект за несколько минут.',
    }),
    keywords: t({
      en: [
        'Enumeration',
        'Internationalization',
        'Documentation',
        'Intlayer',
        'Next.js',
        'JavaScript',
        'React',
      ],
      'en-GB': [
        'Enumeration',
        'Internationalization',
        'Documentation',
        'Intlayer',
        'Next.js',
        'JavaScript',
        'React',
      ],
      fr: [
        'Énumération',
        'Internationalisation',
        'Documentation',
        'Intlayer',
        'Next.js',
        'JavaScript',
        'React',
      ],
      es: [
        'Enumeración',
        'Internacionalización',
        'Documentación',
        'Intlayer',
        'Next.js',
        'JavaScript',
        'React',
      ],
      de: [
        'Enumeration',
        'Internationalisierung',
        'Dokumentation',
        'Intlayer',
        'Next.js',
        'JavaScript',
        'React',
      ],
      ja: [
        '列挙',
        '国際化',
        '文書',
        'Intlayer',
        'Next.js',
        'JavaScript',
        'React',
      ],
      ko: [
        '열거',
        '국제화',
        '문서',
        'Intlayer',
        'Next.js',
        'JavaScript',
        'React',
      ],
      zh: [
        '枚举',
        '国际化',
        '文档',
        'Intlayer',
        'Next.js',
        'JavaScript',
        'React',
      ],
      it: [
        'Enumerazione',
        'Internazionalizzazione',
        'Documentazione',
        'Intlayer',
        'Next.js',
        'JavaScript',
        'React',
      ],
      pt: [
        'Enumeração',
        'Internacionalização',
        'Documentação',
        'Intlayer',
        'Next.js',
        'JavaScript',
        'React',
      ],
      hi: [
        'सूची',
        'अंतर्राष्ट्रीयकरण',
        'डॉक्यूमेंटेशन',
        'Intlayer',
        'Next.js',
        'JavaScript',
        'React',
      ],
      ar: [
        'التعداد',
        'التدويل',
        'التوثيق',
        'Intlayer',
        'Next.js',
        'JavaScript',
        'React',
      ],
      ru: [
        'Перечисление',
        'Интернационализация',
        'Документация',
        'Intlayer',
        'Next.js',
        'JavaScript',
        'React',
      ],
    }),
  },
} satisfies Dictionary<Metadata>;

export default docContent;
