import { type Dictionary, t } from 'intlayer';

const landingPageContent = {
  key: 'landing-page',
  content: {
    landingMainTitle: t({
      en: 'Intlayer — internationalization platform',
      fr: "Intlayer — plateforme d'internationalisation",
      es: 'Intlayer — plataforma de internacionalización',
      ru: 'Intlayer — платформа интернационализации',
      ja: 'Intlayer — 国際化プラットフォーム',
      ko: 'Intlayer — 국제화 플랫폼',
      zh: 'Intlayer — 国际化平台',
      de: 'Intlayer — Internationalisierungsplattform',
      ar: 'Intlayer — منصة التدويل',
      it: 'Intlayer — piattaforma di internazionalizzazione',
      'en-GB': 'Intlayer — internationalisation platform',
      pt: 'Intlayer — plataforma de internacionalização',
      hi: 'Intlayer — अंतर्राष्ट्रीयकरण मंच',
      tr: 'Intlayer — uluslararasılaştırma platformu',
      pl: 'Intlayer — platforma internacjonalizacji',
      id: 'Intlayer — platform internasionalisasi',
      vi: 'Intlayer — nền tảng quốc tế hóa',
      uk: 'Intlayer — платформа інтернаціоналізації',
    }),
    heroSection: t({
      en: 'Hero — internationalization for developers',
      fr: "Accueil — l'internationalisation pour les développeurs",
      es: 'Inicio — internacionalización para desarrolladores',
      ru: 'Главная — интернационализация для разработчиков',
      ja: 'ヒーロー — 開発者のための国際化',
      ko: '히어로 — 개발자를 위한 국제화',
      zh: 'Hero — 开发者国际化',
      de: 'Hero — Internationalisierung für Entwickler',
      ar: 'الرئيسية — التدويل للمطورين',
      it: 'Hero — internazionalizzazione per sviluppatori',
      'en-GB': 'Hero — internationalisation for developers',
      pt: 'Hero — internacionalização para desenvolvedores',
      hi: 'हीरो — डेवलपर्स के लिए अंतर्राष्ट्रीयकरण',
      tr: 'Hero — geliştiriciler için uluslararasılaştırma',
      pl: 'Hero — internacjonalizacja dla programistów',
      id: 'Hero — internasionalisasi untuk pengembang',
      vi: 'Hero — quốc tế hóa cho nhà phát triển',
      uk: 'Головна — інтернаціоналізація для розробників',
    }),
    keyFeaturesSection: t({
      en: 'Key features',
      fr: 'Fonctionnalités clés',
      es: 'Características clave',
      ru: 'Ключевые особенности',
      ja: '主な機能',
      ko: '주요 기능',
      zh: '核心特性',
      de: 'Hauptmerkmale',
      ar: 'الميزات الرئيسية',
      it: 'Caratteristiche principali',
      'en-GB': 'Key features',
      pt: 'Principais recursos',
      hi: 'मुख्य विशेषताएं',
      tr: 'Ana özellikler',
      pl: 'Kluczowe funkcje',
      id: 'Fitur utama',
      vi: 'Các tính năng chính',
      uk: 'Ключові особливості',
    }),
    whyChooseIntlayerSection: t({
      en: 'Why choose Intlayer',
      fr: 'Pourquoi choisir Intlayer',
      es: 'Por qué elegir Intlayer',
      ru: 'Почему выбирают Intlayer',
      ja: 'なぜIntlayerを選ぶのか',
      ko: 'Intlayer를 선택해야 하는 이유',
      zh: '为什么选择 Intlayer',
      de: 'Warum Intlayer wählen',
      ar: 'لماذا تختار Intlayer',
      it: 'Perché scegliere Intlayer',
      'en-GB': 'Why choose Intlayer',
      pt: 'Por que escolher o Intlayer',
      hi: 'Intlayer क्यों चुनें',
      tr: 'Neden Intlayer',
      pl: 'Dlaczego warto wybrać Intlayer',
      id: 'Mengapa memilih Intlayer',
      vi: 'Tại sao chọn Intlayer',
      uk: 'Чому варто обрати Intlayer',
    }),
    benchmarkSection: t({
      en: 'i18n library benchmark',
      fr: 'Comparatif des bibliothèques i18n',
      es: 'Comparativa de bibliotecas i18n',
      ru: 'Сравнение библиотек i18n',
      ja: 'i18nライブラリのベンチマーク',
      ko: 'i18n 라이브러리 벤치마크',
      zh: 'i18n 库基准测试',
      de: 'i18n-Bibliotheks-Benchmark',
      ar: 'مقارنة مكتبات i18n',
      it: 'Benchmark delle librerie i18n',
      'en-GB': 'i18n library benchmark',
      pt: 'Comparativo de bibliotecas i18n',
      hi: 'i18n लाइब्रेरी बेंचमार्क',
      tr: 'i18n kütüphane karşılaştırması',
      pl: 'Benchmark bibliotek i18n',
      id: 'Tolok ukur pustaka i18n',
      vi: 'Điểm chuẩn thư viện i18n',
      uk: 'Порівняння бібліотек i18n',
    }),
    supportedLanguagesSection: t({
      en: 'Supported languages',
      fr: 'Langues prises en charge',
      es: 'Idiomas admitidos',
      ru: 'Поддерживаемые языки',
      ja: 'サポートされている言語',
      ko: '지원되는 언어',
      zh: '支持的语言',
      de: 'Unterstützte Sprachen',
      ar: 'اللغات المدعومة',
      it: 'Lingue supportate',
      'en-GB': 'Supported languages',
      pt: 'Idiomas suportados',
      hi: 'समर्थित भाषाएँ',
      tr: 'Desteklenen diller',
      pl: 'Wspierane języki',
      id: 'Bahasa yang didukung',
      vi: 'Ngôn ngữ được hỗ trợ',
      uk: 'Підтримувані мови',
    }),
    codeAuditSection: t({
      en: 'Code audit',
      fr: 'Audit de code',
      es: 'Auditoría de código',
      ru: 'Аудит кода',
      ja: 'コード監査',
      ko: '코드 감사',
      zh: '代码审计',
      de: 'Code-Audit',
      ar: 'تدقيق الكود',
      it: 'Audit del codice',
      'en-GB': 'Code audit',
      pt: 'Auditoria de código',
      hi: 'कोड ऑडिट',
      tr: 'Kod denetimi',
      pl: 'Audyt kodu',
      id: 'Audit kode',
      vi: 'Kiểm toán mã nguồn',
      uk: 'Аудит коду',
    }),
    productsSection: t({
      en: 'Products',
      fr: 'Produits',
      es: 'Productos',
      ru: 'Продукты',
      ja: '製品',
      ko: '제품',
      zh: '产品',
      de: 'Produkte',
      ar: 'المنتجات',
      it: 'Prodotti',
      'en-GB': 'Products',
      pt: 'Produtos',
      hi: 'उत्पाद',
      tr: 'Ürünler',
      pl: 'Produkty',
      id: 'Produk',
      vi: 'Sản phẩm',
      uk: 'Продукти',
    }),
    technologiesSection: t({
      en: 'Available technologies and integrations',
      fr: 'Technologies et intégrations disponibles',
      es: 'Tecnologías e integraciones disponibles',
      ru: 'Доступные технологии и интеграции',
      ja: '利用可能なテクノロジーと統合',
      ko: '사용 가능한 기술 및 통합',
      zh: '可用的技术和集成',
      de: 'Verfügbare Technologien und Integrationen',
      ar: 'التقنيات والتكاملات المتاحة',
      it: 'Tecnologie e integrazioni disponibili',
      'en-GB': 'Available technologies and integrations',
      pt: 'Tecnologias e integrações disponíveis',
      hi: 'उपलब्ध तकनीकें और एकीकरण',
      tr: 'Mevcut teknolojiler ve entegrasyonlar',
      pl: 'Dostępne technologie i integracje',
      id: 'Teknologi dan integrasi yang tersedia',
      vi: 'Các công nghệ và tích hợp có sẵn',
      uk: 'Доступні технології та інтеграції',
    }),
    liveDemoSection: t({
      en: 'Live demo',
      fr: 'Démonstration en direct',
      es: 'Demostración en vivo',
      ru: 'Демонстрация в реальном времени',
      ja: 'ライブデモ',
      ko: '라이브 데모',
      zh: '在线演示',
      de: 'Live-Demo',
      ar: 'عرض مباشر',
      it: 'Demo live',
      'en-GB': 'Live demo',
      pt: 'Demonstração ao vivo',
      hi: 'लाइव डेमो',
      tr: 'Canlı demo',
      pl: 'Demo na żywo',
      id: 'Demo langsung',
      vi: 'Bản thử nghiệm trực tiếp',
      uk: 'Демонстрація в реальному часі',
    }),
    contributorsSection: t({
      en: 'Contributors',
      fr: 'Contributeurs',
      es: 'Colaboradores',
      ru: 'Участники',
      ja: '貢献者',
      ko: '기여자',
      zh: '贡献者',
      de: 'Mitwirkende',
      ar: 'المساهمون',
      it: 'Collaboratori',
      'en-GB': 'Contributors',
      pt: 'Contribuidores',
      hi: 'योगदानकर्ता',
      tr: 'Katkıda bulunanlar',
      pl: 'Współtwórcy',
      id: 'Kontributor',
      vi: 'Người đóng góp',
      uk: 'Учасники',
    }),
    faqSection: t({
      en: 'Frequently asked questions',
      fr: 'Foire aux questions',
      es: 'Preguntas frecuentes',
      ru: 'Часто задаваемые вопросы',
      ja: 'よくある質問',
      ko: '자주 묻는 질문',
      zh: '常见问题',
      de: 'Häufig gestellte Fragen',
      ar: 'الأسئلة الشائعة',
      it: 'Domande frequenti',
      'en-GB': 'Frequently asked questions',
      pt: 'Perguntas frequentes',
      hi: 'अक्सर पूछे जाने वाले प्रश्न',
      tr: 'Sıkça sorulan sorular',
      pl: 'Często zadawane pytania',
      id: 'Pertanyaan yang sering diajukan',
      vi: 'Câu hỏi thường gặp',
      uk: 'Часті запитання',
    }),
  },
} satisfies Dictionary;

export default landingPageContent;
