import { type Dictionary, t } from 'intlayer';

const userAdminPageContent = {
  key: 'user-admin-page',
  content: {
    title: t({
      en: 'Users Management',
      fr: 'Gestion des utilisateurs',
      es: 'Gestión de usuarios',
      'en-GB': 'Users Management',
      de: 'Benutzerverwaltung',
      ja: 'ユーザー管理',
      ko: '사용자 관리',
      zh: '用户管理',
      it: 'Gestione utenti',
      pt: 'Gestão de usuários',
      hi: 'उपयोगकर्ता प्रबंधन',
      ar: 'إدارة المستخدمين',
      ru: 'Управление пользователями',
      tr: 'Kullanıcı yönetimi',
    }),
    tableHeaders: {
      name: t({
        en: 'Name',
        fr: 'Nom',
        es: 'Nombre',
        'en-GB': 'Name',
        de: 'Name',
        ja: '名前',
        ko: '이름',
        zh: '姓名',
        it: 'Nome',
        pt: 'Nome',
        hi: 'नाम',
        ar: 'الاسم',
        ru: 'Имя',
        tr: 'İsim',
      }),
      email: t({
        en: 'Email',
        fr: 'Email',
        es: 'Correo electrónico',
        'en-GB': 'Email',
        de: 'E-Mail',
        ja: 'メール',
        ko: '이메일',
        zh: '邮箱',
        it: 'Email',
        pt: 'Email',
        hi: 'ईमेल',
        ar: 'البريد الإلكتروني',
        ru: 'Электронная почта',
        tr: 'E-posta',
      }),
      role: t({
        en: 'Role',
        fr: 'Rôle',
        es: 'Rol',
        'en-GB': 'Role',
        de: 'Rolle',
        ja: '役割',
        ko: '역할',
        zh: '角色',
        it: 'Ruolo',
        pt: 'Função',
        hi: 'भूमिका',
        ar: 'الدور',
        ru: 'Роль',
        tr: 'Rol',
      }),
      status: t({
        en: 'Status',
        fr: 'Statut',
        es: 'Estado',
        'en-GB': 'Status',
        de: 'Status',
        ja: 'ステータス',
        ko: '상태',
        zh: '状态',
        it: 'Stato',
        pt: 'Status',
        hi: 'स्थिति',
        ar: 'الحالة',
        ru: 'Статус',
        tr: 'Durum',
      }),
      createdAt: t({
        en: 'Created At',
        fr: 'Créé le',
        es: 'Creado en',
        'en-GB': 'Created At',
        de: 'Erstellt am',
        ja: '作成日',
        ko: '생성일',
        zh: '创建时间',
        it: 'Creato il',
        pt: 'Criado em',
        hi: 'बनाया गया',
        ar: 'تم الإنشاء في',
        ru: 'Создано',
        tr: 'Oluşturulma',
      }),
      updatedAt: t({
        en: 'Updated At',
        fr: 'Mis à jour le',
        es: 'Actualizado en',
        'en-GB': 'Updated At',
        de: 'Aktualisiert am',
        ja: '更新日',
        ko: '업데이트 일',
        zh: '更新时间',
        it: 'Aggiornato il',
        pt: 'Atualizado em',
        hi: 'अपडेट किया गया',
        ar: 'تم التحديث في',
        ru: 'Обновлено',
        tr: 'Güncellendi',
      }),
      actions: t({
        en: 'Actions',
        fr: 'Actions',
        es: 'Acciones',
        'en-GB': 'Actions',
        de: 'Aktionen',
        ja: 'アクション',
        ko: '작업',
        zh: '操作',
        it: 'Azioni',
        pt: 'Ações',
        hi: 'कार्य',
        ar: 'الإجراءات',
        ru: 'Действия',
        tr: 'İşlemler',
      }),
    },
    statusLabels: {
      verified: t({
        en: 'Verified',
        fr: 'Vérifié',
        es: 'Verificado',
        'en-GB': 'Verified',
        de: 'Verifiziert',
        ja: '確認済み',
        ko: '확인됨',
        zh: '已验证',
        it: 'Verificato',
        pt: 'Verificado',
        hi: 'सत्यापित',
        ar: 'متحقق',
        ru: 'Подтвержден',
        tr: 'Doğrulandı',
      }),
      pending: t({
        en: 'Pending',
        fr: 'En attente',
        es: 'Pendiente',
        'en-GB': 'Pending',
        de: 'Ausstehend',
        ja: '保留中',
        ko: '대기 중',
        zh: '待处理',
        it: 'In sospeso',
        pt: 'Pendente',
        hi: 'लंबित',
        ar: 'معلق',
        ru: 'Ожидает',
        tr: 'Beklemede',
      }),
    },
    actions: {
      edit: t({
        en: 'Edit',
        fr: 'Modifier',
        es: 'Editar',
        'en-GB': 'Edit',
        de: 'Bearbeiten',
        ja: '編集',
        ko: '편집',
        zh: '编辑',
        it: 'Modifica',
        pt: 'Editar',
        hi: 'संपादित करें',
        ar: 'تعديل',
        ru: 'Редактировать',
        tr: 'Düzenle',
      }),
      delete: t({
        en: 'Delete',
        fr: 'Supprimer',
        es: 'Eliminar',
        'en-GB': 'Delete',
        de: 'Löschen',
        ja: '削除',
        ko: '삭제',
        zh: '删除',
        it: 'Elimina',
        pt: 'Excluir',
        hi: 'हटाएं',
        ar: 'حذف',
        ru: 'Удалить',
        tr: 'Sil',
      }),
      copyId: t({
        en: 'Copy id',
        fr: "Copier l'id",
        es: 'Copiar id',
        'en-GB': 'Copy id',
        de: 'Id kopieren',
        ja: 'idをコピー',
        ko: '이메일 복사',
        zh: '复制id',
        it: 'Copia id',
        pt: 'Copiar id',
        hi: 'आईडी को कॉपी करें',
        ar: 'نسخ الأيدي',
        ru: 'Копировать id',
        tr: 'Id kopyala',
      }),
    },
    noUsersMessage: t({
      en: 'No users found',
      fr: 'Aucun utilisateur trouvé',
      es: 'No se encontraron usuarios',
      'en-GB': 'No users found',
      de: 'Keine Benutzer gefunden',
      ja: 'ユーザーが見つかりません',
      ko: '사용자를 찾을 수 없습니다',
      zh: '未找到用户',
      it: 'Nessun utente trovato',
      pt: 'Nenhum usuário encontrado',
      hi: 'कोई उपयोगकर्ता नहीं मिला',
      ar: 'لم يتم العثور على مستخدمين',
      ru: 'Пользователи не найдены',
      tr: 'Kullanıcı bulunamadı',
    }),
    errorMessages: {
      loadingError: t({
        en: 'Error loading users',
        fr: 'Erreur lors du chargement des utilisateurs',
        es: 'Error al cargar usuarios',
        'en-GB': 'Error loading users',
        de: 'Fehler beim Laden der Benutzer',
        ja: 'ユーザーの読み込みエラー',
        ko: '사용자 로딩 오류',
        zh: '加载用户时出错',
        it: 'Errore nel caricamento degli utenti',
        pt: 'Erro ao carregar usuários',
        hi: 'उपयोगकर्ताओं को लोड करने में त्रुटि',
        ar: 'خطأ في تحميل المستخدمين',
        ru: 'Ошибка загрузки пользователей',
        tr: 'Kullanıcıları yükleme hatası',
      }),
    },
    successMessages: {
      idCopied: t({
        en: 'Id copied to clipboard',
        fr: 'Id copiée dans le presse-papiers',
        es: 'Id copiada al portapapeles',
        'en-GB': 'Id copied to clipboard',
        de: 'Id in die Zwischenablage kopiert',
        ja: 'idをクリップボードにコピーしました',
        ko: '이메일이 클립보드에 복사되었습니다',
        zh: 'id已复制到剪贴板',
        it: 'Id copiata negli appunti',
        pt: 'Id copiada para a área de transferência',
        hi: 'आईडी को क्लिपबोर्ड पर कॉपी कर लिया गया',
        ar: 'تم النسخ الى الحافظة',
        ru: 'Id скопирован в буфер обмена',
        tr: 'Id panoya kopyalandı',
      }),
    },
    showingResults: t({
      en: 'Showing {start} to {end} of {total} results',
      fr: 'Affichage de {start} à {end} sur {total} résultats',
      es: 'Mostrando {start} a {end} de {total} resultados',
      'en-GB': 'Showing {start} to {end} of {total} results',
      de: 'Zeige {start} bis {end} von {total} Ergebnissen',
      ja: '{total}件中{start}〜{end}件を表示',
      ko: '{total}개 결과 중 {start}~{end}개 표시',
      zh: '显示第 {start} 到 {end} 项，共 {total} 个结果',
      it: 'Mostrando {start} a {end} di {total} risultati',
      pt: 'Mostrando {start} a {end} de {total} resultados',
      hi: '{total} परिणामों में से {start} से {end} तक दिखा रहे हैं',
      ar: 'عرض {start} إلى {end} من أصل {total} نتيجة',
      ru: 'Показано {start}-{end} из {total} результатов',
      tr: '{total} sonuçtan {start}-{end} arası gösteriliyor',
    }),
    searchPlaceholder: t({
      en: 'Search users...',
      fr: 'Rechercher des utilisateurs...',
      es: 'Buscar usuarios...',
      'en-GB': 'Search users...',
      de: 'Benutzer suchen...',
      ja: 'ユーザーを検索...',
      ko: '사용자 검색...',
      zh: '搜索用户...',
      it: 'Cerca utenti...',
      pt: 'Buscar usuários...',
      hi: 'उपयोगकर्ताओं की खोज करें...',
      ar: 'البحث عن المستخدمين...',
      ru: 'Поиск пользователей...',
      tr: 'Kullanıcıları ara...',
    }),
    filterPlaceholder: t({
      en: 'Filter by organization',
      fr: 'Filtrer par organisation',
      es: 'Filtrar por organización',
      'en-GB': 'Filter by organisation',
      de: 'Nach Organisation filtern',
      ja: '組織でフィルター',
      ko: '조직별 필터',
      zh: '按组织筛选',
      it: 'Filtra per organizzazione',
      pt: 'Filtrar por organização',
      hi: 'संगठन के अनुसार फ़िल्टर करें',
      ar: 'تصفية حسب المنظمة',
      ru: 'Фильтр по организации',
      tr: 'Organizasyona göre filtrele',
    }),
    allStatuses: t({
      en: 'All organizations',
      fr: 'Toutes les organisations',
      es: 'Todas las organizaciones',
      'en-GB': 'All organisations',
      de: 'Alle Organisationen',
      ja: 'すべての組織',
      ko: '모든 조직',
      zh: '所有组织',
      it: 'Tutte le organizzazioni',
      pt: 'Todas as organizações',
      hi: 'सभी संगठन',
      ar: 'جميع المنظمات',
      ru: 'Все организации',
      tr: 'Tüm organizasyonlar',
    }),
    noData: t({
      en: 'N/A',
      fr: 'N/A',
      es: 'N/A',
      'en-GB': 'N/A',
      de: 'N/A',
      ja: 'なし',
      ko: '없음',
      zh: '无',
      it: 'N/A',
      pt: 'N/A',
      hi: 'N/A',
      ar: 'غير متوفر',
      ru: 'Н/Д',
      tr: 'Yok',
    }),
  },
} satisfies Dictionary;

export default userAdminPageContent;
