import { type Dictionary, t } from 'intlayer';

const deleteOrganizationModalContent = {
  key: 'delete-organization-modal',
  content: {
    title: t({
      ar: 'حذف المنظمة',
      de: 'Organisation löschen',
      en: 'Delete Organization',
      'en-GB': 'Delete organization',
      es: 'Eliminar organización',
      fr: 'Supprimer le Organization',
      hi: 'संगठन हटाएं',
      it: 'Elimina organizzazione',
      ja: 'オーガナイゼーションを削除',
      ko: '조직 삭제',
      pt: 'Excluir organização',
      ru: 'Удалить организацию',
      tr: 'Organizasyonu Sil',
      zh: '删除组织',
      pl: 'Usuń organizację',
    }),

    description: t({
      ar: 'هل أنت متأكد من أنك تريد حذف هذا المنظمة؟',
      de: 'Sind Sie sicher, dass Sie diese Organisation löschen möchten?',
      en: 'Are you sure you want to delete this Organization?',
      'en-GB': 'Are you sure you want to delete this organization?',
      es: '¿Está seguro de que desea eliminar esta organización?',
      fr: 'Êtes-vous sûr de vouloir supprimer ce Organization ?',
      hi: 'क्या आप इस संगठन को हटाना चाहते हैं?',
      it: 'Sei sicuro di voler eliminare questa organizzazione?',
      ja: 'このオーガナイゼーションを削除してもよろしいですか？',
      ko: '이 조직을 삭제하시겠습니까?',
      pt: 'Tem certeza de que deseja excluir esta organização?',
      ru: 'Вы уверены, что хотите удалить эту организацию?',
      tr: 'Bu Organizasyonu silmek istediğinize emin misiniz?',
      zh: '您确定要删除此组织吗？',
      pl: 'Czy na pewno chcesz usunąć tę organizację?',
    }),

    confirmButton: {
      text: t({
        en: 'Delete',
        fr: 'Supprimer',
        es: 'Eliminar',
        'en-GB': 'Delete',
        de: 'Löschen',
        ja: '削除',
        ko: '삭제',
        zh: '删除',
        it: 'Elimina',
        pt: 'Excluir',
        hi: 'हटाएं',
        ar: 'حذف',
        ru: 'Удалить',
        tr: 'Sil',
        pl: 'Usuń',
      }),
      label: t({
        en: 'Click to delete Organization',
        fr: 'Cliquez pour supprimer le Organization',
        es: 'Haga clic para eliminar la organización',
        'en-GB': 'Click to delete organization',
        de: 'Klicken Sie, um die Organisation zu löschen',
        ja: 'オーガナイゼーションを削除するにはクリックしてください',
        ko: '조직을 삭제하려면 클릭하세요',
        zh: '点击删除组织',
        it: "Clicca per eliminare l'organizzazione",
        pt: 'Clique para excluir a organização',
        hi: 'संगठन को हटाने के लिए क्लिक करें',
        ar: 'انقر لحذف المنظمة',
        ru: 'Нажмите, чтобы удалить организацию',
        tr: 'Organizasyonu silmek için tıklayın',
        pl: 'Kliknij, aby usunąć organizację',
      }),
    },

    cancelButton: {
      text: t({
        en: 'Cancel',
        fr: 'Annuler',
        es: 'Cancelar',
        'en-GB': 'Cancel',
        de: 'Abbrechen',
        ja: 'キャンセル',
        ko: '취소',
        zh: '取消',
        it: 'Annulla',
        pt: 'Cancelar',
        hi: 'रद्द करें',
        ar: 'إلغاء',
        ru: 'Отменить',
        tr: 'İptal etmek için tıklayın',
        pl: 'Anuluj',
      }),
      label: t({
        en: 'Click to cancel',
        fr: 'Cliquez pour annuler',
        es: 'Haga clic para cancelar',
        'en-GB': 'Click to cancel',
        de: 'Klicken Sie, um abzubrechen',
        ja: 'キャンセルをクリックしてください',
        ko: '취소를 클릭하세요',
        zh: '点击取消',
        it: 'Clicca per annullare',
        pt: 'Clique para cancelar',
        hi: 'रद्द करने के लिए क्लिक करें',
        ar: 'انقر لإلغاء',
        ru: 'Нажмите, чтобы отменить',
        tr: 'İptal etmek için tıklayın',
        pl: 'Kliknij, aby anulować',
      }),
    },
  },
  title: 'Delete organization modal',
  description:
    'Modal content for confirming the deletion of an organization. Includes confirmation message and action buttons with corresponding labels.',
  tags: ['modal', 'organization', 'confirmation'],
} satisfies Dictionary;

export default deleteOrganizationModalContent;
