import { t, type Dictionary } from 'intlayer';

const organizationFormContent = {
  key: 'organization-form',
  content: {
    title: t({
      en: 'Organization details',
      'en-GB': 'Organization details',
      fr: 'Détails de l’organisation',
      es: 'Detalles de la organización',
      de: 'Organisationsdetails',
      ja: '組織の詳細',
      ko: '조직 세부정보',
      zh: '组织详情',
      it: "Dettagli dell'organizzazione",
      pt: 'Detalhes da organização',
      hi: 'संगठन विवरण',
      ar: 'تفاصيل المنظمة',
      ru: 'Детали организации',
      tr: 'Organizasyon detayları',
    }),
    nameInput: {
      label: t({
        en: 'Name',
        'en-GB': 'Name',
        fr: 'Nom',
        es: 'Nombre',
        de: 'Name',
        ja: '名前',
        ko: '이름',
        zh: '名称',
        it: 'Nome',
        pt: 'Nome',
        hi: 'नाम',
        ar: 'اسم',
        ru: 'Имя',
        tr: 'İsim',
      }),
      placeholder: t({
        en: 'Enter the name of your organization',
        'en-GB': 'Enter the name of your organization',
        fr: 'Entrez le nom de votre organisation',
        es: 'Ingrese el nombre de su organización',
        de: 'Geben Sie den Namen Ihrer Organisation ein',
        ja: '組織の名前を入力してください',
        ko: '조직의 이름을 입력하세요',
        zh: '输入您的组织名称',
        it: 'Inserisci il nome della tua organizzazione',
        pt: 'Insira o nome da sua organização',
        hi: 'अपने संगठन का नाम दर्ज करें',
        ar: 'أدخل اسم منظمتك',
        ru: 'Введите название вашей организации',
        tr: 'Organizasyonunuzun adını girin',
      }),
    },

    createOrganizationTitle: t({
      en: 'No organization',
      'en-GB': 'No organization',
      fr: 'Aucune organisation',
      es: 'Sin organización',
      de: 'Keine Organisation',
      ja: '組織なし',
      ko: '조직 없음',
      zh: '没有组织',
      it: 'Nessuna organizzazione',
      pt: 'Nenhuma organização',
      hi: 'कोई संगठन नहीं',
      ar: 'لا توجد منظمة',
      ru: 'Нет организации',
      tr: 'Organizasyon yok',
    }),

    createOrganizationDescription: t({
      en: 'Create your first organization to start using Intlayer',
      'en-GB': 'Create your first organization to start using Intlayer',
      fr: 'Créez votre première organisation pour commencer à utiliser Intlayer',
      es: 'Cree su primera organización para comenzar a usar Intlayer',
      de: 'Erstellen Sie Ihre erste Organisation, um Intlayer zu verwenden',
      ja: 'Intlayerの使用を開始するために最初の組織を作成してください',
      ko: 'Intlayer 사용을 시작하려면 첫 번째 조직을 만드십시오',
      zh: '创建第一个组织以开始使用Intlayer',
      it: 'Crea la tua prima organizzazione per iniziare a utilizzare Intlayer',
      pt: 'Crie sua primeira organização para começar a usar o Intlayer',
      hi: 'Intlayer का उपयोग शुरू करने के लिए अपना पहला संगठन बनाएं',
      ar: 'قم بإنشاء منظمتك الأولى لبدء استخدام Intlayer',
      ru: 'Создайте свою первую организацию, чтобы начать использовать Intlayer',
      tr: 'Intlayer kullanmaya başlamak için ilk organizasyonunuzu oluşturun',
    }),

    createOrganizationButton: {
      text: t({
        en: 'Create organization',
        'en-GB': 'Create organization',
        fr: 'Créer une organisation',
        es: 'Crear una organización',
        de: 'Organisation erstellen',
        ja: '組織を作成',
        ko: '조직 만들기',
        zh: '创建组织',
        it: 'Crea organizzazione',
        pt: 'Criar organização',
        hi: 'संगठन बनाएँ',
        ar: 'إنشاء منظمة',
        ru: 'Создать организацию',
        tr: 'Organizasyon oluştur',
      }),
      ariaLabel: t({
        en: 'Click to create organization',
        'en-GB': 'Click to create organization',
        fr: 'Cliquez pour créer une organisation',
        es: 'Haga clic para crear una organización',
        de: 'Klicken Sie, um eine Organisation zu erstellen',
        ja: '組織を作成するにはクリックしてください',
        ko: '조직을 만들려면 클릭하세요',
        zh: '单击以创建组织',
        it: "Fai clic per creare un'organizzazione",
        pt: 'Clique para criar organização',
        hi: 'संगठन बनाने के लिए क्लिक करें',
        ar: 'انقر لإنشاء منظمة',
        ru: 'Нажмите, чтобы создать организацию',
        tr: 'Organizasyon oluşturmak için tıklayın',
      }),
    },

    editButton: {
      text: t({
        en: 'Edit organization',
        'en-GB': 'Edit organization',
        fr: "Modifier l'organisation",
        es: 'Editar la organización',
        de: 'Organisation bearbeiten',
        ja: '組織を編集',
        ko: '조직 편집',
        zh: '编辑组织',
        it: 'Modifica organizzazione',
        pt: 'Editar organização',
        hi: 'संगठन संपादित करें',
        ar: 'تحرير المنظمة',
        ru: 'Редактировать организацию',
        tr: 'Organizasyonu düzenle',
      }),
      ariaLabel: t({
        en: 'Click to edit',
        'en-GB': 'Click to edit',
        fr: 'Cliquez pour modifier',
        es: 'Haga clic para editar',
        de: 'Klicken Sie, um zu bearbeiten',
        ja: '編集するにはクリックしてください',
        ko: '편집하려면 클릭하세요',
        zh: '单击以编辑',
        it: 'Fai clic per modificare',
        pt: 'Clique para editar',
        hi: 'संपादित करने के लिए क्लिक करें',
        ar: 'انقر لتحرير',
        ru: 'Нажмите, чтобы отредактировать',
        tr: 'Düzenlemek için tıklayın',
      }),
    },

    selectButton: {
      text: t({
        en: 'Select',
        'en-GB': 'Select',
        fr: 'Sélectionner',
        es: 'Seleccionar',
        de: 'Auswählen',
        ja: '選択',
        ko: '선택',
        zh: '选择',
        it: 'Seleziona',
        pt: 'Selecionar',
        hi: 'चुनें',
        ar: 'اختر',
        ru: 'Выбрать',
        tr: 'Seç',
      }),
      ariaLabel: t({
        en: 'Click to select',
        'en-GB': 'Click to select',
        fr: 'Cliquez pour sélectionner',
        es: 'Haga clic para seleccionar',
        de: 'Klicken Sie, um auszuwählen',
        ja: '選択するにはクリックしてください',
        ko: '선택하려면 클릭하세요',
        zh: '单击以选择',
        it: 'Fai clic per selezionare',
        pt: 'Clique para selecionar',
        hi: 'चुनने के लिए क्लिक करें',
        ar: 'انقر للاختيار',
        ru: 'Нажмите, чтобы выбрать',
        tr: 'Seçmek için tıklayın',
      }),
      selected: t({
        en: 'Selected',
        'en-GB': 'Selected',
        fr: 'Sélectionné',
        es: 'Seleccionado',
        de: 'Ausgewählt',
        ja: '選択済み',
        ko: '선택됨',
        zh: '已选择',
        it: 'Selezionato',
        pt: 'Selecionado',
        hi: 'चुना हुआ',
        ar: 'محدد',
        ru: 'Выбран',
        tr: 'Seçildi',
      }),
      unselected: t({
        en: 'Select',
        'en-GB': 'Select',
        fr: 'Sélectionner',
        es: 'Seleccionar',
        de: 'Auswählen',
        ja: '選択',
        ko: '선택',
        zh: '选择',
        it: 'Seleziona',
        pt: 'Selecionar',
        hi: 'चुनें',
        ar: 'اختر',
        ru: 'Выбрать',
        tr: 'Seç',
      }),
    },
    addOrganizationButton: {
      text: t({
        en: 'Add organization',
        'en-GB': 'Add organization',
        fr: 'Ajouter une organisation',
        de: 'Organisation hinzufügen',
        es: 'Agregar organización',
        it: 'Aggiungi organizzazione',
        pt: 'Adicionar organização',
        hi: 'संगठन जोड़ें',
        ar: 'إضافة المنظمة',
        ru: 'Добавить организацию',
        ja: '組織を追加',
        ko: '조직 추가',
        zh: '添加组织',
        tr: 'Organizasyon ekle',
      }),
      ariaLabel: t({
        en: 'Click to add organization',
        'en-GB': 'Click to add organization',
        fr: 'Cliquez pour ajouter une organisation',
        de: 'Klicken Sie, um eine Organisation hinzuzufügen',
        es: 'Haga clic para agregar una organización',
        it: "Fai clic per aggiungere un'organizzazione",
        pt: 'Clique para adicionar uma organização',
        hi: 'संगठन जोड़ने के लिए क्लिक करें',
        ar: 'انقر لإضافة المنظمة',
        ru: 'Нажмите, чтобы добавить организацию',
        ja: '組織を追加するにはクリック',
        ko: '조직을 추가하려면 클릭',
        zh: '单击添加组织',
        tr: 'Organizasyon eklemek için tıklayın',
      }),
    },
    deleteOrganizationButton: {
      text: t({
        en: 'Delete Organization',
        'en-GB': 'Delete Organization',
        fr: "Supprimer l'organisation",
        es: 'Eliminar la organización',
        de: 'Organisation löschen',
        ja: '組織を削除',
        ko: '조직 삭제',
        zh: '删除组织',
        it: 'Elimina organizzazione',
        pt: 'Excluir organização',
        hi: 'संगठन हटाएं',
        ar: 'حذف المنظمة',
        ru: 'Удалить организацию',
        tr: 'Organizasyonu sil',
      }),
      ariaLabel: t({
        en: 'Click to delete organization',
        'en-GB': 'Click to delete organization',
        fr: "Cliquez pour supprimer l'organisation",
        es: 'Haga clic para eliminar la organización',
        de: 'Klicken Sie, um die Organisation zu löschen',
        ja: '組織を削除するにはクリックしてください',
        ko: '조직을 삭제하려면 클릭하세요',
        zh: '单击删除组织',
        it: "Clicca per eliminare l'organizzazione",
        pt: 'Clique para excluir a organização',
        hi: 'संगठन को हटाने के लिए क्लिक करें',
        ar: 'انقر لحذف المنظمة',
        ru: 'Нажмите, чтобы удалить организацию',
        tr: 'Organizasyonu silmek için tıklayın',
      }),
    },
  },
} satisfies Dictionary;

export default organizationFormContent;
