import { t, type Dictionary } from 'intlayer';

const signInContent = {
  key: 'sign-in',
  content: {
    forgotPasswordLink: {
      ariaLabel: t({
        en: 'Forgot your password?',
        'en-GB': 'Forgot your password?',
        fr: 'Mot de passe oublié ?',
        es: '¿Olvidaste tu contraseña?',
        de: 'Haben Sie Ihr Passwort vergessen?',
        ja: 'パスワードをお忘れですか？',
        ko: '비밀번호를 잊으셨나요?',
        zh: '忘记密码？',
        it: 'Hai dimenticato la password?',
        pt: 'Esqueceu sua senha?',
        hi: 'क्या आपने अपना पासवर्ड भुला दिया?',
        ar: 'نسيت كلمة المرور؟',
        ru: 'Забыли пароль?',
      }),
      text: t({
        en: 'Forgot password?',
        'en-GB': 'Forgot password?',
        fr: 'Mot de passe oublié ?',
        es: '¿Olvidaste tu contraseña?',
        de: 'Passwort vergessen?',
        ja: 'パスワードをお忘れですか？',
        ko: '비밀번호를 잊으셨나요?',
        zh: '忘记密码？',
        it: 'Hai dimenticato la password?',
        pt: 'Esqueceu sua senha?',
        hi: 'क्या आपने अपना पासवर्ड भुला दिया?',
        ar: 'نسيت كلمة المرور؟',
        ru: 'Забыли пароль?',
      }),
    },
    emailInput: {
      label: t({
        en: 'Email address',
        'en-GB': 'Email address',
        fr: 'Adresse e-mail',
        es: 'Dirección de correo electrónico',
        de: 'E-Mail-Adresse',
        ja: 'メールアドレス',
        ko: '이메일 주소',
        zh: '电子邮件地址',
        it: 'Indirizzo email',
        pt: 'Endereço de e-mail',
        hi: 'ईमेल पता',
        ar: 'عنوان البريد الإلكتروني',
        ru: 'Адрес электронной почты',
      }),
      placeholder: t({
        en: 'Enter e-mail address',
        'en-GB': 'Enter e-mail address',
        fr: 'Entrez votre adresse e-mail',
        es: 'Ingrese su dirección de correo electrónico',
        de: 'Geben Sie die E-Mail-Adresse ein',
        ja: 'メールアドレスを入力してください',
        ko: '이메일 주소를 입력하세요',
        zh: '请输入电子邮件地址',
        it: "Inserisci l'indirizzo email",
        pt: 'Digite o endereço de e-mail',
        hi: 'ईमेल पता दर्ज करें',
        ar: 'أدخل عنوان البريد الإلكتروني',
        ru: 'Введите адрес электронной почты',
      }),
    },
    passwordInput: {
      label: t({
        en: 'Password',
        'en-GB': 'Password',
        fr: 'Mot de passe',
        es: 'Contraseña',
        de: 'Passwort',
        ja: 'パスワード',
        ko: '비밀번호',
        zh: '密码',
        it: 'Password',
        pt: 'Senha',
        hi: 'पासवर्ड',
        ar: 'كلمة المرور',
        ru: 'Пароль',
      }),
      placeholder: t({
        en: 'Enter password',
        'en-GB': 'Enter password',
        fr: 'Entrez votre mot de passe',
        es: 'Ingrese su contraseña',
        de: 'Geben Sie das Passwort ein',
        ja: 'パスワードを入力してください',
        ko: '비밀번호를 입력하세요',
        zh: '请输入密码',
        it: 'Inserisci la password',
        pt: 'Digite a senha',
        hi: 'पासवर्ड दर्ज करें',
        ar: 'أدخل كلمة المرور',
        ru: 'Введите пароль',
      }),
    },
    rememberMeCheckbox: {
      description: t({
        en: 'Remember me on this device',
        'en-GB': 'Remember me on this device',
        fr: 'Se souvenir de moi sur cet appareil',
        es: 'Recordarme en este dispositivo',
        de: 'Mich auf diesem Gerät merken',
        ja: 'このデバイスでログイン状態を保持する',
        ko: '기기에서 로그인 상태 유지',
        zh: '记住我在这个设备上',
        it: 'Ricordami su questo dispositivo',
        pt: 'Lembrar-me neste dispositivo',
        hi: 'इस डिवाइस पर मुझे याद रखें',
        ar: 'تذكرني على هذا الجهاز',
        ru: 'Запомнить меня на этом устройстве',
      }),
    },

    loginButton: {
      text: t({
        en: 'Log in',
        'en-GB': 'Log in',
        fr: 'Se connecter',
        es: 'Iniciar sesión',
        de: 'Einloggen',
        ja: 'ログイン',
        ko: '로그인',
        zh: '登录',
        it: 'Accedi',
        pt: 'Entrar',
        hi: 'लॉग इन करें',
        ar: 'تسجيل الدخول',
        ru: 'Войти',
      }),
      ariaLabel: t({
        en: 'Click to log in',
        'en-GB': 'Click to log in',
        fr: 'Cliquez pour vous connecter',
        es: 'Haga clic para iniciar sesión',
        de: 'Klicken Sie, um sich anzumelden',
        ja: 'ログインするにはクリックしてください',
        ko: '로그인하려면 클릭하세요',
        zh: '点击登录',
        it: 'Clicca per accedere',
        pt: 'Clique para entrar',
        hi: 'लॉग इन करने के लिए क्लिक करें',
        ar: 'انقر لتسجيل الدخول',
        ru: 'Нажмите, чтобы войти',
      }),
    },
    signInButton: {
      text: t({
        en: 'Log in',
        'en-GB': 'Log in',
        fr: 'Se connecter',
        es: 'Iniciar sesión',
        de: 'Einloggen',
        ja: 'ログイン',
        ko: '로그인',
        zh: '登录',
        it: 'Accedi',
        pt: 'Entrar',
        hi: 'लॉग इन करें',
        ar: 'تسجيل الدخول',
        ru: 'Войти',
      }),
      ariaLabel: t({
        en: 'Click to log in',
        'en-GB': 'Click to log in',
        fr: 'Cliquez pour vous connecter',
        es: 'Haga clic para iniciar sesión',
        de: 'Klicken Sie, um sich anzumelden',
        ja: 'ログインするにはクリックしてください',
        ko: '로그인하려면 클릭하세요',
        zh: '点击登录',
        it: 'Clicca per accedere',
        pt: 'Clique para entrar',
        hi: 'लॉग इन करने के लिए क्लिक करें',
        ar: 'انقر لتسجيل الدخول',
        ru: 'Нажмите, чтобы войти',
      }),
    },
    signUpLink: {
      message: t({
        en: 'Don’t have an account?',
        'en-GB': 'Don’t have an account?',
        fr: 'Vous n’avez pas de compte ?',
        es: '¿No tienes una cuenta?',
        de: 'Haben Sie kein Konto?',
        ja: 'アカウントをお持ちでないですか？',
        ko: '계정이 없으신가요?',
        zh: '还没有账户？',
        it: 'Non hai un account?',
        pt: 'Você não tem uma conta?',
        hi: 'क्या आपके पास खाता नहीं है?',
        ar: 'ليس لديك حساب؟',
        ru: 'У вас нет аккаунта?',
      }),
      ariaLabel: t({
        en: 'Click to go to create an account page',
        'en-GB': 'Click to go to create an account page',
        fr: 'Cliquez pour aller à la page de création de compte',
        es: 'Haga clic para ir a la página de creación de cuenta',
        de: 'Klicken Sie, um zur Seite zur Erstellung eines Kontos zu gelangen',
        ja: 'アカウント作成ページに移動するにはクリックしてください',
        ko: '계정 생성 페이지로 이동하려면 클릭하세요',
        zh: '单击以转到创建账户页面',
        it: "Clicca per andare alla pagina di creazione dell'account",
        pt: 'Clique para ir para a página de criação de conta',
        hi: 'खाता बनाने के पृष्ठ पर जाने के लिए क्लिक करें',
        ar: 'انقر للانتقال إلى صفحة إنشاء حساب',
        ru: 'Нажмите, чтобы перейти на страницу создания аккаунта',
      }),
      text: t({
        en: 'Create an account',
        'en-GB': 'Create an account',
        fr: 'Créer un compte',
        es: 'Crear una cuenta',
        de: 'Ein Konto erstellen',
        ja: 'アカウントを作成',
        ko: '계정을 만들다',
        zh: '创建一个账户',
        it: 'Crea un account',
        pt: 'Criar uma conta',
        hi: 'एक खाता बनाएं',
        ar: 'إنشاء حساب',
        ru: 'Создать аккаунт',
      }),
    },
  },
} satisfies Dictionary;

export default signInContent;
