import { type Dictionary, t } from 'intlayer';

const reviewerMissionPageContent = {
  key: 'reviewer-mission-page',
  content: {
    // Accessibility labels
    missionDetailsAriaLabel: t({
      en: 'Mission details',
      fr: 'Détails de la mission',
      es: 'Detalles de la misión',
      'en-GB': 'Mission details',
      de: 'Auftragsdetails',
      ja: 'ミッション詳細',
      ko: '미션 상세',
      zh: '任务详情',
      it: 'Dettagli missione',
      pt: 'Detalhes da missão',
      hi: 'मिशन विवरण',
      ar: 'تفاصيل المهمة',
      ru: 'Детали задания',
      tr: 'Görev ayrıntıları',
      pl: 'Szczegóły misji',
      id: 'Detail misi',
      vi: 'Chi tiết nhiệm vụ',
      uk: 'Деталі завдання',
    }),
    statusProgressAriaLabel: t({
      en: 'Mission status progress',
      fr: 'Avancement du statut de la mission',
      es: 'Progreso del estado de la misión',
      'en-GB': 'Mission status progress',
      de: 'Auftragsstatusfortschritt',
      ja: 'ミッションのステータス進捗',
      ko: '미션 상태 진행률',
      zh: '任务状态进度',
      it: 'Avanzamento stato missione',
      pt: 'Progresso do status da missão',
      hi: 'मिशन स्थिति प्रगति',
      ar: 'تقدم حالة المهمة',
      ru: 'Прогресс статуса задания',
      tr: 'Görev durumu ilerleme',
      pl: 'Postęp statusu misji',
      id: 'Kemajuan status misi',
      vi: 'Tiến độ trạng thái nhiệm vụ',
      uk: 'Прогрес статусу завдання',
    }),
    missionSummaryAriaLabel: t({
      en: 'Mission summary',
      fr: 'Résumé de la mission',
      es: 'Resumen de la misión',
      'en-GB': 'Mission summary',
      de: 'Auftragsübersicht',
      ja: 'ミッションの概要',
      ko: '미션 요약',
      zh: '任务摘要',
      it: 'Riepilogo missione',
      pt: 'Resumo da missão',
      hi: 'मिशन सारांश',
      ar: 'ملخص المهمة',
      ru: 'Сводка задания',
      tr: 'Görev özeti',
      pl: 'Podsumowanie misji',
      id: 'Ringkasan misi',
      vi: 'Tóm tắt nhiệm vụ',
      uk: 'Зведення завдання',
    }),
    languagesAriaLabel: t({
      en: 'Languages',
      fr: 'Langues',
      es: 'Idiomas',
      'en-GB': 'Languages',
      de: 'Sprachen',
      ja: '言語',
      ko: '언어',
      zh: '语言',
      it: 'Lingue',
      pt: 'Idiomas',
      hi: 'भाषाएँ',
      ar: 'اللغات',
      ru: 'Языки',
      tr: 'Diller',
      pl: 'Języki',
      id: 'Bahasa',
      vi: 'Ngôn ngữ',
      uk: 'Мови',
    }),
    languagesToAriaLabel: t({
      en: 'to',
      fr: 'vers',
      es: 'a',
      'en-GB': 'to',
      de: 'nach',
      ja: 'から',
      ko: '→',
      zh: '→',
      it: 'a',
      pt: 'para',
      hi: 'से',
      ar: 'إلى',
      ru: 'в',
      tr: 'için',
      pl: 'do',
      id: 'ke',
      vi: 'sang',
      uk: 'до',
    }),
    reviewerActionsAriaLabel: t({
      en: 'Respond to mission request',
      fr: 'Répondre à la demande de mission',
      es: 'Responder a la solicitud de misión',
      'en-GB': 'Respond to mission request',
      de: 'Auf Auftragsanfrage reagieren',
      ja: 'ミッションリクエストに返答する',
      ko: '미션 요청에 응답하기',
      zh: '回应任务请求',
      it: 'Rispondi alla richiesta di missione',
      pt: 'Responder à solicitação de missão',
      hi: 'मिशन अनुरोध का जवाब दें',
      ar: 'الرد على طلب المهمة',
      ru: 'Ответить на запрос задания',
      tr: 'Görev isteğine yanıt ver',
      pl: 'Odpowiedz na prośbę o misję',
      id: 'Tanggapi permintaan misi',
      vi: 'Phản hồi yêu cầu nhiệm vụ',
      uk: 'Відповісти на запит завдання',
    }),
    clientActionsAriaLabel: t({
      en: 'Review translation result',
      fr: 'Vérifier le résultat de la traduction',
      es: 'Revisar el resultado de la traducción',
      'en-GB': 'Review translation result',
      de: 'Übersetzungsergebnis prüfen',
      ja: '翻訳結果を確認する',
      ko: '번역 결과 검토하기',
      zh: '审核翻译结果',
      it: 'Revisione del risultato della traduzione',
      pt: 'Revisar resultado da tradução',
      hi: 'अनुवाद परिणाम की समीक्षा करें',
      ar: 'مراجعة نتيجة الترجمة',
      ru: 'Проверить результат перевода',
      tr: 'Çeviri sonucunu incele',
      pl: 'Przejrzyj wynik tłumaczenia',
      id: 'Tinjau hasil terjemahan',
      vi: 'Xem xét kết quả dịch thuật',
      uk: 'Перевірити результат перекладу',
    }),
    reviewSectionAriaLabel: t({
      en: 'Leave a review for this mission',
      fr: 'Laisser un avis pour cette mission',
      es: 'Dejar una reseña para esta misión',
      'en-GB': 'Leave a review for this mission',
      de: 'Bewertung für diesen Auftrag abgeben',
      ja: 'このミッションにレビューを投稿する',
      ko: '이 미션에 리뷰 남기기',
      zh: '为此任务留下评价',
      it: 'Lascia una recensione per questa missione',
      pt: 'Deixar uma avaliação para esta missão',
      hi: 'इस मिशन के लिए समीक्षा छोड़ें',
      ar: 'اترك تقييماً لهذه المهمة',
      ru: 'Оставить отзыв по этому заданию',
      tr: 'Bu görev için yorum bırak',
      pl: 'Zostaw recenzję dla tej misji',
      id: 'Tinggalkan ulasan untuk misi ini',
      vi: 'Để lại đánh giá cho nhiệm vụ này',
      uk: 'Залишити відгук по цьому завданню',
    }),
    reviewCommentAriaLabel: t({
      en: 'Review comment',
      fr: "Commentaire de l'avis",
      es: 'Comentario de la reseña',
      'en-GB': 'Review comment',
      de: 'Bewertungskommentar',
      ja: 'レビューコメント',
      ko: '리뷰 댓글',
      zh: '评价评论',
      it: 'Commento della recensione',
      pt: 'Comentário da avaliação',
      hi: 'समीक्षा टिप्पणी',
      ar: 'تعليق التقييم',
      ru: 'Комментарий к отзыву',
      tr: 'Yorum değerlendirmesi',
      pl: 'Komentarz do recenzji',
      id: 'Komentar ulasan',
      vi: 'Bình luận đánh giá',
      uk: 'Коментар до відгуку',
    }),
    starRatingGroupPrefix: t({
      en: 'Star rating:',
      fr: 'Note en étoiles :',
      es: 'Calificación con estrellas:',
      'en-GB': 'Star rating:',
      de: 'Sternebewertung:',
      ja: '星評価：',
      ko: '별점:',
      zh: '星级评分：',
      it: 'Valutazione a stelle:',
      pt: 'Classificação por estrelas:',
      hi: 'स्टार रेटिंग:',
      ar: 'تقييم النجوم:',
      ru: 'Рейтинг звёзд:',
      tr: 'Yıldız puanı:',
      pl: 'Ocena gwiazdkowa:',
      id: 'Penilaian bintang:',
      vi: 'Đánh giá sao:',
      uk: 'Зірковий рейтинг:',
    }),
    starRatingGroupSuffix: t({
      en: 'out of 5',
      fr: 'sur 5',
      es: 'de 5',
      'en-GB': 'out of 5',
      de: 'von 5',
      ja: '5つ星中',
      ko: '5점 만점',
      zh: '满分 5',
      it: 'su 5',
      pt: 'de 5',
      hi: '5 में से',
      ar: 'من 5',
      ru: 'из 5',
      tr: '5 üzerinden',
      pl: 'na 5',
      id: 'dari 5',
      vi: 'trên 5',
      uk: 'з 5',
    }),
    rateStarLabel: t({
      en: 'Rate',
      fr: 'Attribuer',
      es: 'Calificar con',
      'en-GB': 'Rate',
      de: 'Bewerten mit',
      ja: '評価する',
      ko: '평가',
      zh: '评价',
      it: 'Valuta',
      pt: 'Avaliar',
      hi: 'रेट करें',
      ar: 'تقييم',
      ru: 'Оценить',
      tr: 'Puan ver',
      pl: 'Oceń',
      id: 'Nilai',
      vi: 'Đánh giá',
      uk: 'Оцінити',
    }),
    rateStarSingular: t({
      en: 'star',
      fr: 'étoile',
      es: 'estrella',
      'en-GB': 'star',
      de: 'Stern',
      ja: '星',
      ko: '별',
      zh: '星',
      it: 'stella',
      pt: 'estrela',
      hi: 'सितारा',
      ar: 'نجمة',
      ru: 'звезда',
      tr: 'yıldız',
      pl: 'gwiazdka',
      id: 'bintang',
      vi: 'sao',
      uk: 'зірка',
    }),
    rateStarPlural: t({
      en: 'stars',
      fr: 'étoiles',
      es: 'estrellas',
      'en-GB': 'stars',
      de: 'Sterne',
      ja: '星',
      ko: '별',
      zh: '星',
      it: 'stelle',
      pt: 'estrelas',
      hi: 'सितारे',
      ar: 'نجوم',
      ru: 'звёзды',
      tr: 'yıldız',
      pl: 'gwiazdki',
      id: 'bintang',
      vi: 'sao',
      uk: 'зірки',
    }),
    chatAriaLabel: t({
      en: 'Mission chat',
      fr: 'Chat de la mission',
      es: 'Chat de la misión',
      'en-GB': 'Mission chat',
      de: 'Auftrags-Chat',
      ja: 'ミッションチャット',
      ko: '미션 채팅',
      zh: '任务聊天',
      it: 'Chat della missione',
      pt: 'Chat da missão',
      hi: 'मिशन चैट',
      ar: 'محادثة المهمة',
      ru: 'Чат задания',
      tr: 'Görev sohbeti',
      pl: 'Czat misji',
      id: 'Obrolan misi',
      vi: 'Trò chuyện nhiệm vụ',
      uk: 'Чат завдання',
    }),

    missionIdLabel: t({
      en: 'Mission ID:',
      fr: 'ID de la mission :',
      es: 'ID de la misión:',
      'en-GB': 'Mission ID:',
      de: 'Auftrags-ID:',
      ja: 'ミッションID：',
      ko: '미션 ID:',
      zh: '任务 ID：',
      it: 'ID missione:',
      pt: 'ID da missão:',
      hi: 'मिशन आईडी:',
      ar: 'معرف المهمة:',
      ru: 'ID задания:',
      tr: 'Görev Kimliği:',
      pl: 'ID misji:',
      id: 'ID misi:',
      vi: 'ID nhiệm vụ:',
      uk: 'ID завдання:',
    }),
    stepCompleted: t({
      en: '(completed)',
      fr: '(terminée)',
      es: '(completado)',
      'en-GB': '(completed)',
      de: '(abgeschlossen)',
      ja: '（完了）',
      ko: '(완료)',
      zh: '（已完成）',
      it: '(completato)',
      pt: '(concluído)',
      hi: '(पूर्ण)',
      ar: '(مكتمل)',
      ru: '(выполнено)',
      tr: '(tamamlandı)',
      pl: '(ukończono)',
      id: '(selesai)',
      vi: '(hoàn thành)',
      uk: '(виконано)',
    }),
    stepCurrent: t({
      en: '(current)',
      fr: '(en cours)',
      es: '(actual)',
      'en-GB': '(current)',
      de: '(aktuell)',
      ja: '（現在）',
      ko: '(현재)',
      zh: '（当前）',
      it: '(attuale)',
      pt: '(atual)',
      hi: '(वर्तमान)',
      ar: '(الحالي)',
      ru: '(текущий)',
      tr: '(mevcut)',
      pl: '(bieżący)',
      id: '(saat ini)',
      vi: '(hiện tại)',
      uk: '(поточний)',
    }),
    languagesDtLabel: t({
      en: 'Languages',
      fr: 'Langues',
      es: 'Idiomas',
      'en-GB': 'Languages',
      de: 'Sprachen',
      ja: '言語',
      ko: '언어',
      zh: '语言',
      it: 'Lingue',
      pt: 'Idiomas',
      hi: 'भाषाएँ',
      ar: 'اللغات',
      ru: 'Языки',
      tr: 'Diller',
      pl: 'Języki',
      id: 'Bahasa',
      vi: 'Ngôn ngữ',
      uk: 'Мови',
    }),
    wordCountDtLabel: t({
      en: 'Word count',
      fr: 'Nombre de mots',
      es: 'Número de palabras',
      'en-GB': 'Word count',
      de: 'Wortanzahl',
      ja: '単語数',
      ko: '단어 수',
      zh: '字数',
      it: 'Conteggio parole',
      pt: 'Contagem de palavras',
      hi: 'शब्द गणना',
      ar: 'عدد الكلمات',
      ru: 'Количество слов',
      tr: 'Kelime sayısı',
      pl: 'Liczba słów',
      id: 'Jumlah kata',
      vi: 'Số từ',
      uk: 'Кількість слів',
    }),
    estimatedHoursDtLabel: t({
      en: 'Estimated hours',
      fr: 'Heures estimées',
      es: 'Horas estimadas',
      'en-GB': 'Estimated hours',
      de: 'Geschätzte Stunden',
      ja: '推定時間',
      ko: '예상 시간',
      zh: '预计小时数',
      it: 'Ore stimate',
      pt: 'Horas estimadas',
      hi: 'अनुमानित घंटे',
      ar: 'الساعات المقدرة',
      ru: 'Расчётное время (ч)',
      tr: 'Tahmini saatler',
      pl: 'Szacowane godziny',
      id: 'Jam yang diperkirakan',
      vi: 'Giờ ước tính',
      uk: 'Розрахункові години',
    }),
    totalPriceDtLabel: t({
      en: 'Total price',
      fr: 'Prix total',
      es: 'Precio total',
      'en-GB': 'Total price',
      de: 'Gesamtpreis',
      ja: '合計金額',
      ko: '총 가격',
      zh: '总价',
      it: 'Prezzo totale',
      pt: 'Preço total',
      hi: 'कुल मूल्य',
      ar: 'السعر الإجمالي',
      ru: 'Итоговая стоимость',
      tr: 'Toplam fiyat',
      pl: 'Łączna cena',
      id: 'Harga total',
      vi: 'Tổng giá',
      uk: 'Загальна вартість',
    }),
    notesDtLabel: t({
      en: 'Notes',
      fr: 'Notes',
      es: 'Notas',
      'en-GB': 'Notes',
      de: 'Hinweise',
      ja: 'メモ',
      ko: '메모',
      zh: '备注',
      it: 'Note',
      pt: 'Notas',
      hi: 'नोट्स',
      ar: 'ملاحظات',
      ru: 'Заметки',
      tr: 'Notlar',
      pl: 'Notatki',
      id: 'Catatan',
      vi: 'Ghi chú',
      uk: 'Нотатки',
    }),

    missionTitle: t({
      en: 'Translation Mission',
      fr: 'Mission de traduction',
      es: 'Misión de traducción',
      'en-GB': 'Translation Mission',
      de: 'Übersetzungsauftrag',
      ja: '翻訳ミッション',
      ko: '번역 미션',
      zh: '翻译任务',
      it: 'Missione di traduzione',
      pt: 'Missão de tradução',
      hi: 'अनुवाद मिशन',
      ar: 'مهمة الترجمة',
      ru: 'Задание по переводу',
      tr: 'Çeviri görevi',
      pl: 'Misja tłumaczeniowa',
      id: 'Misi terjemahan',
      vi: 'Nhiệm vụ dịch thuật',
      uk: 'Завдання з перекладу',
    }),
    missionNotFound: t({
      en: 'Mission not found.',
      fr: 'Mission introuvable.',
      es: 'Misión no encontrada.',
      'en-GB': 'Mission not found.',
      de: 'Auftrag nicht gefunden.',
      ja: 'ミッションが見つかりません。',
      ko: '미션을 찾을 수 없습니다.',
      zh: '未找到任务。',
      it: 'Missione non trovata.',
      pt: 'Missão não encontrada.',
      hi: 'मिशन नहीं मिला।',
      ar: 'المهمة غير موجودة.',
      ru: 'Задание не найдено.',
      tr: 'Görev bulunamadı.',
      pl: 'Nie znaleziono misji.',
      id: 'Misi tidak ditemukan.',
      vi: 'Không tìm thấy nhiệm vụ.',
      uk: 'Завдання не знайдено.',
    }),
    words: t({
      en: 'words',
      fr: 'mots',
      es: 'palabras',
      'en-GB': 'words',
      de: 'Wörter',
      ja: '単語',
      ko: '단어',
      zh: '字',
      it: 'parole',
      pt: 'palavras',
      hi: 'शब्द',
      ar: 'كلمات',
      ru: 'слов',
      tr: 'kelime',
      pl: 'słów',
      id: 'kata',
      vi: 'từ',
      uk: 'слів',
    }),
    hoursEstimated: t({
      en: 'hours estimated',
      fr: 'heures estimées',
      es: 'horas estimadas',
      'en-GB': 'hours estimated',
      de: 'Stunden geschätzt',
      ja: '時間（推定）',
      ko: '예상 시간',
      zh: '预计小时',
      it: 'ore stimate',
      pt: 'horas estimadas',
      hi: 'घंटे अनुमानित',
      ar: 'ساعات مقدرة',
      ru: 'часов (оценка)',
      tr: 'tahmini saat',
      pl: 'szacowane godziny',
      id: 'jam perkiraan',
      vi: 'giờ ước tính',
      uk: 'годин (оцінка)',
    }),
    accept: t({
      en: 'Accept',
      fr: 'Accepter',
      es: 'Aceptar',
      'en-GB': 'Accept',
      de: 'Annehmen',
      ja: '承諾',
      ko: '수락',
      zh: '接受',
      it: 'Accetta',
      pt: 'Aceitar',
      hi: 'स्वीकार करें',
      ar: 'قبول',
      ru: 'Принять',
      tr: 'Kabul et',
      pl: 'Akceptuj',
      id: 'Terima',
      vi: 'Chấp nhận',
      uk: 'Прийняти',
    }),
    decline: t({
      en: 'Decline',
      fr: 'Refuser',
      es: 'Rechazar',
      'en-GB': 'Decline',
      de: 'Ablehnen',
      ja: '辞退',
      ko: '거절',
      zh: '拒绝',
      it: 'Rifiuta',
      pt: 'Recusar',
      hi: 'अस्वीकार करें',
      ar: 'رفض',
      ru: 'Отклонить',
      tr: 'Reddet',
      pl: 'Odrzuć',
      id: 'Tolak',
      vi: 'Từ chối',
      uk: 'Відхилити',
    }),
    startTranslation: t({
      en: 'Start translation',
      fr: 'Démarrer la traduction',
      es: 'Iniciar traducción',
      'en-GB': 'Start translation',
      de: 'Übersetzung starten',
      ja: '翻訳を開始する',
      ko: '번역 시작',
      zh: '开始翻译',
      it: 'Avvia traduzione',
      pt: 'Iniciar tradução',
      hi: 'अनुवाद शुरू करें',
      ar: 'بدء الترجمة',
      ru: 'Начать перевод',
      tr: 'Çeviriyi başlat',
      pl: 'Rozpocznij tłumaczenie',
      id: 'Mulai terjemahan',
      vi: 'Bắt đầu dịch thuật',
      uk: 'Почати переклад',
    }),
    sendForClientReview: t({
      en: 'Send for client review',
      fr: 'Envoyer pour révision client',
      es: 'Enviar para revisión del cliente',
      'en-GB': 'Send for client review',
      de: 'Zur Kundenüberprüfung senden',
      ja: 'クライアントレビューに送る',
      ko: '클라이언트 검토를 위해 보내기',
      zh: '发送给客户审核',
      it: 'Invia per revisione cliente',
      pt: 'Enviar para revisão do cliente',
      hi: 'क्लाइंट समीक्षा के लिए भेजें',
      ar: 'إرسال لمراجعة العميل',
      ru: 'Отправить на проверку клиенту',
      tr: 'Müşteri incelemesi için gönder',
      pl: 'Wyślij do przeglądu klienta',
      id: 'Kirim untuk ditinjau klien',
      vi: 'Gửi để khách hàng xem xét',
      uk: 'Відправити на перевірку клієнту',
    }),
    approve: t({
      en: 'Approve',
      fr: 'Approuver',
      es: 'Aprobar',
      'en-GB': 'Approve',
      de: 'Genehmigen',
      ja: '承認する',
      ko: '승인',
      zh: '批准',
      it: 'Approva',
      pt: 'Aprovar',
      hi: 'अनुमोदित करें',
      ar: 'موافقة',
      ru: 'Одобрить',
      tr: 'Onayla',
      pl: 'Zatwierdź',
      id: 'Setujui',
      vi: 'Phê duyệt',
      uk: 'Схвалити',
    }),
    requestChanges: t({
      en: 'Request changes',
      fr: 'Demander des modifications',
      es: 'Solicitar cambios',
      'en-GB': 'Request changes',
      de: 'Änderungen anfordern',
      ja: '変更をリクエストする',
      ko: '변경 요청',
      zh: '请求更改',
      it: 'Richiedi modifiche',
      pt: 'Solicitar alterações',
      hi: 'परिवर्तन का अनुरोध करें',
      ar: 'طلب تغييرات',
      ru: 'Запросить изменения',
      tr: 'Değişiklik iste',
      pl: 'Poproś o zmiany',
      id: 'Minta perubahan',
      vi: 'Yêu cầu thay đổi',
      uk: 'Запросити зміни',
    }),
    leaveReview: t({
      en: 'Leave a review',
      fr: 'Laisser un avis',
      es: 'Dejar una reseña',
      'en-GB': 'Leave a review',
      de: 'Bewertung abgeben',
      ja: 'レビューを投稿する',
      ko: '리뷰 남기기',
      zh: '留下评价',
      it: 'Lascia una recensione',
      pt: 'Deixar uma avaliação',
      hi: 'समीक्षा छोड़ें',
      ar: 'اترك تقييماً',
      ru: 'Оставить отзыв',
      tr: 'Yorum bırak',
      pl: 'Zostaw recenzję',
      id: 'Tinggalkan ulasan',
      vi: 'Để lại đánh giá',
      uk: 'Залишити відгук',
    }),
    reviewPlaceholder: t({
      en: 'Share your experience...',
      fr: 'Partagez votre expérience...',
      es: 'Comparte tu experiencia...',
      'en-GB': 'Share your experience...',
      de: 'Teilen Sie Ihre Erfahrung...',
      ja: 'あなたの体験を共有してください...',
      ko: '경험을 공유해 주세요...',
      zh: '分享您的体验...',
      it: 'Condividi la tua esperienza...',
      pt: 'Compartilhe sua experiência...',
      hi: 'अपना अनुभव साझा करें...',
      ar: 'شارك تجربتك...',
      ru: 'Поделитесь своим опытом...',
      tr: 'Deneyiminizi paylaşın...',
      pl: 'Podziel się swoim doświadczeniem...',
      id: 'Bagikan pengalaman Anda...',
      vi: 'Chia sẻ trải nghiệm của bạn...',
      uk: 'Поділіться своїм досвідом...',
    }),
    submitting: t({
      en: 'Submitting...',
      fr: 'Envoi en cours...',
      es: 'Enviando...',
      'en-GB': 'Submitting...',
      de: 'Wird gesendet...',
      ja: '送信中...',
      ko: '제출 중...',
      zh: '提交中...',
      it: 'Invio in corso...',
      pt: 'Enviando...',
      hi: 'सबमिट हो रहा है...',
      ar: 'جارٍ الإرسال...',
      ru: 'Отправка...',
      tr: 'Gönderiliyor...',
      pl: 'Wysyłanie...',
      id: 'Mengirim...',
      vi: 'Đang gửi...',
      uk: 'Надсилання...',
    }),
    submitReview: t({
      en: 'Submit review',
      fr: "Envoyer l'avis",
      es: 'Enviar reseña',
      'en-GB': 'Submit review',
      de: 'Bewertung absenden',
      ja: 'レビューを送信する',
      ko: '리뷰 제출',
      zh: '提交评价',
      it: 'Invia recensione',
      pt: 'Enviar avaliação',
      hi: 'समीक्षा सबमिट करें',
      ar: 'إرسال التقييم',
      ru: 'Отправить отзыв',
      tr: 'Yorumu gönder',
      pl: 'Wyślij recenzję',
      id: 'Kirim ulasan',
      vi: 'Gửi đánh giá',
      uk: 'Надіслати відгук',
    }),
    reviewSubmitted: t({
      en: 'Review submitted. Thank you!',
      fr: 'Avis envoyé. Merci !',
      es: '¡Reseña enviada. ¡Gracias!',
      'en-GB': 'Review submitted. Thank you!',
      de: 'Bewertung eingereicht. Vielen Dank!',
      ja: 'レビューが送信されました。ありがとうございます！',
      ko: '리뷰가 제출되었습니다. 감사합니다!',
      zh: '评价已提交。谢谢！',
      it: 'Recensione inviata. Grazie!',
      pt: 'Avaliação enviada. Obrigado!',
      hi: 'समीक्षा सबमिट हो गई। धन्यवाद!',
      ar: 'تم إرسال التقييم. شكراً!',
      ru: 'Отзыв отправлен. Спасибо!',
      tr: 'Yorum gönderildi. Teşekkürler!',
      pl: 'Recenzja przesłana. Dziękujemy!',
      id: 'Ulasan dikirim. Terima kasih!',
      vi: 'Đánh giá đã được gửi. Cảm ơn!',
      uk: 'Відгук надіслано. Дякуємо!',
    }),
    chat: t({
      en: 'Chat',
      fr: 'Chat',
      es: 'Chat',
      'en-GB': 'Chat',
      de: 'Chat',
      ja: 'チャット',
      ko: '채팅',
      zh: '聊天',
      it: 'Chat',
      pt: 'Chat',
      hi: 'चैट',
      ar: 'محادثة',
      ru: 'Чат',
      tr: 'Sohbet',
      pl: 'Czat',
      id: 'Obrolan',
      vi: 'Trò chuyện',
      uk: 'Чат',
    }),
    statusPending: t({
      en: 'Pending',
      fr: 'En attente',
      es: 'Pendiente',
      'en-GB': 'Pending',
      de: 'Ausstehend',
      ja: '保留中',
      ko: '대기 중',
      zh: '待处理',
      it: 'In attesa',
      pt: 'Pendente',
      hi: 'लंबित',
      ar: 'معلق',
      ru: 'В ожидании',
      tr: 'Beklemede',
      pl: 'Oczekuje',
      id: 'Menunggu',
      vi: 'Đang chờ',
      uk: 'Очікує',
    }),
    statusAccepted: t({
      en: 'Accepted',
      fr: 'Accepté',
      es: 'Aceptado',
      'en-GB': 'Accepted',
      de: 'Angenommen',
      ja: '承諾済み',
      ko: '수락됨',
      zh: '已接受',
      it: 'Accettato',
      pt: 'Aceito',
      hi: 'स्वीकृत',
      ar: 'مقبول',
      ru: 'Принято',
      tr: 'Kabul edildi',
      pl: 'Zaakceptowano',
      id: 'Diterima',
      vi: 'Đã chấp nhận',
      uk: 'Прийнято',
    }),
    statusInProgress: t({
      en: 'In progress',
      fr: 'En cours',
      es: 'En progreso',
      'en-GB': 'In progress',
      de: 'In Bearbeitung',
      ja: '進行中',
      ko: '진행 중',
      zh: '进行中',
      it: 'In corso',
      pt: 'Em andamento',
      hi: 'प्रगति में',
      ar: 'قيد التنفيذ',
      ru: 'В процессе',
      tr: 'Devam ediyor',
      pl: 'W toku',
      id: 'Sedang berlangsung',
      vi: 'Đang tiến hành',
      uk: 'В процесі',
    }),
    statusReviewerReview: t({
      en: 'Reviewer review',
      fr: 'Révision traducteur',
      es: 'Revisión del traductor',
      'en-GB': 'Reviewer review',
      de: 'Reviewer-Prüfung',
      ja: 'レビュアー確認',
      ko: '리뷰어 검토',
      zh: '审稿人审核',
      it: 'Revisione del revisore',
      pt: 'Revisão do revisor',
      hi: 'समीक्षक की समीक्षा',
      ar: 'مراجعة المراجع',
      ru: 'Проверка рецензента',
      tr: 'İnceleyici incelemesi',
      pl: 'Przegląd recenzenta',
      id: 'Tinjauan peninjau',
      vi: 'Xem xét của người đánh giá',
      uk: 'Перевірка рецензента',
    }),
    statusClientReview: t({
      en: 'Client review',
      fr: 'Révision client',
      es: 'Revisión del cliente',
      'en-GB': 'Client review',
      de: 'Kundenprüfung',
      ja: 'クライアント確認',
      ko: '클라이언트 검토',
      zh: '客户审核',
      it: 'Revisione cliente',
      pt: 'Revisão do cliente',
      hi: 'क्लाइंट समीक्षा',
      ar: 'مراجعة العميل',
      ru: 'Проверка клиента',
      tr: 'Müşteri incelemesi',
      pl: 'Przegląd klienta',
      id: 'Tinjauan klien',
      vi: 'Xem xét của khách hàng',
      uk: 'Перевірка клієнта',
    }),
    statusCompleted: t({
      en: 'Completed',
      fr: 'Terminé',
      es: 'Completado',
      'en-GB': 'Completed',
      de: 'Abgeschlossen',
      ja: '完了',
      ko: '완료됨',
      zh: '已完成',
      it: 'Completato',
      pt: 'Concluído',
      hi: 'पूर्ण',
      ar: 'مكتمل',
      ru: 'Выполнено',
      tr: 'Tamamlandı',
      pl: 'Ukończono',
      id: 'Selesai',
      vi: 'Hoàn thành',
      uk: 'Виконано',
    }),
  },
} satisfies Dictionary;

export default reviewerMissionPageContent;
