import { type DeclarationContent, insert, t } from 'intlayer';

const cliLoginFlowContent = {
  key: 'cli-login-flow',
  content: {
    loginTitle: t({
      en: 'Login to CLI',
      'en-GB': 'Login to CLI',
      es: 'Iniciar sesión en CLI',
      fr: 'Connexion au CLI',
      ru: 'Вход в CLI',
      ja: 'CLI にログイン',
      ko: 'CLI에 로그인',
      zh: '登录到 CLI',
      de: 'Anmeldung am CLI',
      ar: 'تسجيل الدخول إلى CLI',
      it: 'Accedi al CLI',
      pt: 'Entrar no CLI',
      hi: 'CLI में लॉगिन करें',
      tr: "CLI'ye Giriş Yap",
      pl: 'Zaloguj się do CLI',
      id: 'Masuk ke CLI',
      vi: 'Đăng nhập vào CLI',
      uk: 'Увійти в CLI',
    }),

    selectOrganization: t({
      en: 'Select Organization',
      'en-GB': 'Select Organisation',
      es: 'Seleccionar organización',
      fr: 'Sélectionner une organisation',
      ru: 'Выберите организацию',
      ja: '組織を選択',
      ko: '조직 선택',
      zh: '选择组织',
      de: 'Organisation auswählen',
      ar: 'اختر المؤسسة',
      it: 'Seleziona organizzazione',
      pt: 'Selecionar organização',
      hi: 'संगठन चुनें',
      tr: 'Organizasyon Seç',
      pl: 'Wybierz organizację',
      id: 'Pilih Organisasi',
      vi: 'Chọn tổ chức',
      uk: 'Оберіть організацію',
    }),

    selectProject: t({
      en: 'Select Project',
      'en-GB': 'Select Project',
      es: 'Seleccionar proyecto',
      fr: 'Sélectionner un projet',
      ru: 'Выберите проект',
      ja: 'プロジェクトを選択',
      ko: '프로젝트 선택',
      zh: '选择项目',
      de: 'Projekt auswählen',
      ar: 'اختر المشروع',
      it: 'Seleziona progetto',
      pt: 'Selecionar projeto',
      hi: 'परियोजना चुनें',
      tr: 'Proje Seç',
      pl: 'Wybierz projekt',
      id: 'Pilih Proyek',
      vi: 'Chọn dự án',
      uk: 'Оберіть проєкт',
    }),

    context: t({
      en: 'Context',
      'en-GB': 'Context',
      es: 'Contexto',
      fr: 'Contexte',
      ru: 'Контекст',
      ja: 'コンテキスト',
      ko: '컨텍스트',
      zh: '上下文',
      de: 'Kontext',
      ar: 'السياق',
      it: 'Contesto',
      pt: 'Contexto',
      hi: 'संदर्भ',
      tr: 'Bağlam',
      pl: 'Kontekst',
      id: 'Konteks',
      vi: 'Ngữ cảnh',
      uk: 'Контекст',
    }),
    accountSelector: {
      title: t({
        en: 'Choose an account',
        'en-GB': 'Choose an account',
        fr: 'Choisir un compte',
        es: 'Elige una cuenta',
        de: 'Konto auswählen',
        ja: 'アカウントを選択',
        ko: '계정 선택',
        zh: '选择帐户',
        ru: 'Выберите аккаунт',
        ar: 'اختر حسابًا',
        it: 'Scegli un account',
        pt: 'Escolha uma conta',
        hi: 'एक खाता चुनें',
        tr: 'Bir hesap seçin',
        pl: 'Wybierz konto',
        id: 'Pilih akun',
        vi: 'Chọn một tài khoản',
        uk: 'Оберіть обліковий запис',
      }),
      description: t({
        en: 'You are already signed in on this device. Pick the account the CLI should be authenticated with.',
        'en-GB':
          'You are already signed in on this device. Pick the account the CLI should be authenticated with.',
        fr: 'Vous êtes déjà connecté sur cet appareil. Choisissez le compte avec lequel le CLI doit être authentifié.',
        es: 'Ya has iniciado sesión en este dispositivo. Elige la cuenta con la que se debe autenticar el CLI.',
        de: 'Sie sind auf diesem Gerät bereits angemeldet. Wählen Sie das Konto, mit dem die CLI authentifiziert werden soll.',
        ja: 'このデバイスではすでにサインインしています。CLI の認証に使用するアカウントを選択してください。',
        ko: '이 기기에서 이미 로그인되어 있습니다. CLI를 인증할 계정을 선택하세요.',
        zh: '您已在此设备上登录。请选择 CLI 应使用的帐户进行身份验证。',
        ru: 'Вы уже вошли в систему на этом устройстве. Выберите аккаунт, с которым должен аутентифицироваться CLI.',
        ar: 'لقد سجّلت الدخول بالفعل على هذا الجهاز. اختر الحساب الذي يجب مصادقة CLI به.',
        it: 'Hai già effettuato l’accesso su questo dispositivo. Scegli l’account con cui autenticare la CLI.',
        pt: 'Você já está conectado neste dispositivo. Escolha a conta com a qual o CLI deve ser autenticado.',
        hi: 'आप इस डिवाइस पर पहले से साइन इन हैं। वह खाता चुनें जिससे CLI को प्रमाणित किया जाना चाहिए।',
        tr: 'Bu cihazda zaten oturum açmış durumdasınız. CLI’nin kimlik doğrulaması için kullanılacak hesabı seçin.',
        pl: 'Jesteś już zalogowany na tym urządzeniu. Wybierz konto, którym ma zostać uwierzytelnione CLI.',
        id: 'Anda sudah masuk di perangkat ini. Pilih akun yang akan digunakan CLI untuk autentikasi.',
        vi: 'Bạn đã đăng nhập trên thiết bị này. Hãy chọn tài khoản mà CLI sẽ dùng để xác thực.',
        uk: 'Ви вже увійшли на цьому пристрої. Оберіть обліковий запис, з яким має автентифікуватися CLI.',
      }),
      listAriaLabel: t({
        en: 'Accounts signed in on this device',
        'en-GB': 'Accounts signed in on this device',
        fr: 'Comptes connectés sur cet appareil',
        es: 'Cuentas con sesión iniciada en este dispositivo',
        de: 'Auf diesem Gerät angemeldete Konten',
        ja: 'このデバイスでサインイン済みのアカウント',
        ko: '이 기기에 로그인된 계정',
        zh: '此设备上已登录的帐户',
        ru: 'Аккаунты, вошедшие на этом устройстве',
        ar: 'الحسابات المسجلة الدخول على هذا الجهاز',
        it: 'Account connessi su questo dispositivo',
        pt: 'Contas conectadas neste dispositivo',
        hi: 'इस डिवाइस पर साइन इन किए गए खाते',
        tr: 'Bu cihazda oturum açmış hesaplar',
        pl: 'Konta zalogowane na tym urządzeniu',
        id: 'Akun yang masuk di perangkat ini',
        vi: 'Các tài khoản đã đăng nhập trên thiết bị này',
        uk: 'Облікові записи, що увійшли на цьому пристрої',
      }),
      activeAccountAriaLabel: t({
        en: 'Selected account',
        'en-GB': 'Selected account',
        fr: 'Compte sélectionné',
        es: 'Cuenta seleccionada',
        de: 'Ausgewähltes Konto',
        ja: '選択中のアカウント',
        ko: '선택된 계정',
        zh: '已选择的帐户',
        ru: 'Выбранный аккаунт',
        ar: 'الحساب المحدد',
        it: 'Account selezionato',
        pt: 'Conta selecionada',
        hi: 'चयनित खाता',
        tr: 'Seçili hesap',
        pl: 'Wybrane konto',
        id: 'Akun terpilih',
        vi: 'Tài khoản đã chọn',
        uk: 'Обраний обліковий запис',
      }),
      switchToAriaLabel: insert(
        t({
          en: 'Switch to {{name}}',
          'en-GB': 'Switch to {{name}}',
          fr: 'Passer à {{name}}',
          es: 'Cambiar a {{name}}',
          de: 'Zu {{name}} wechseln',
          ja: '{{name}} に切り替える',
          ko: '{{name}}(으)로 전환',
          zh: '切换到 {{name}}',
          ru: 'Переключиться на {{name}}',
          ar: 'التبديل إلى {{name}}',
          it: 'Passa a {{name}}',
          pt: 'Mudar para {{name}}',
          hi: '{{name}} पर स्विच करें',
          tr: "{{name}}'a geç",
          pl: 'Przełącz na {{name}}',
          id: 'Beralih ke {{name}}',
          vi: 'Chuyển sang {{name}}',
          uk: 'Переключитись на {{name}}',
        })
      ),
      continueAs: insert(
        t({
          en: 'Continue as {{name}}',
          'en-GB': 'Continue as {{name}}',
          fr: 'Continuer en tant que {{name}}',
          es: 'Continuar como {{name}}',
          de: 'Als {{name}} fortfahren',
          ja: '{{name}} として続行',
          ko: '{{name}}(으)로 계속',
          zh: '以 {{name}} 的身份继续',
          ru: 'Продолжить как {{name}}',
          ar: 'المتابعة باسم {{name}}',
          it: 'Continua come {{name}}',
          pt: 'Continuar como {{name}}',
          hi: '{{name}} के रूप में जारी रखें',
          tr: '{{name}} olarak devam et',
          pl: 'Kontynuuj jako {{name}}',
          id: 'Lanjutkan sebagai {{name}}',
          vi: 'Tiếp tục với tư cách {{name}}',
          uk: 'Продовжити як {{name}}',
        })
      ),
      useAnotherAccount: t({
        en: 'Use another account',
        'en-GB': 'Use another account',
        fr: 'Utiliser un autre compte',
        es: 'Usar otra cuenta',
        de: 'Anderes Konto verwenden',
        ja: '別のアカウントを使用',
        ko: '다른 계정 사용',
        zh: '使用其他帐户',
        ru: 'Использовать другой аккаунт',
        ar: 'استخدام حساب آخر',
        it: 'Usa un altro account',
        pt: 'Usar outra conta',
        hi: 'किसी अन्य खाते का उपयोग करें',
        tr: 'Başka bir hesap kullan',
        pl: 'Użyj innego konta',
        id: 'Gunakan akun lain',
        vi: 'Dùng tài khoản khác',
        uk: 'Використати інший обліковий запис',
      }),
      backToAccounts: t({
        en: 'Back to my accounts',
        'en-GB': 'Back to my accounts',
        fr: 'Retour à mes comptes',
        es: 'Volver a mis cuentas',
        de: 'Zurück zu meinen Konten',
        ja: 'アカウント一覧に戻る',
        ko: '내 계정으로 돌아가기',
        zh: '返回我的帐户',
        ru: 'Назад к моим аккаунтам',
        ar: 'العودة إلى حساباتي',
        it: 'Torna ai miei account',
        pt: 'Voltar para minhas contas',
        hi: 'मेरे खातों पर वापस जाएं',
        tr: 'Hesaplarıma geri dön',
        pl: 'Wróć do moich kont',
        id: 'Kembali ke akun saya',
        vi: 'Quay lại tài khoản của tôi',
        uk: 'Назад до моїх облікових записів',
      }),
    },
    sessionAuthSelector: {
      title: t({
        en: '2-hour session token',
        'en-GB': '2-hour session token',
        fr: 'Jeton de session de 2 heures',
        es: 'Token de sesión de 2 horas',
        de: '2-Stunden-Sitzungstoken',
        ja: '2時間セッショントークン',
        ko: '2시간 세션 토큰',
        zh: '2 小时会话令牌',
        ru: '2-часовой токен сессии',
        ar: 'رمز جلسة لمدة ساعتين',
        it: 'Token di sessione di 2 ore',
        pt: 'Token de sessão de 2 horas',
        hi: '2-घंटे का सत्र टोकन',
        tr: '2 saatlik oturum anahtarı',
        pl: '2-godzinny token sesji',
        id: 'Token sesi 2 jam',
        vi: 'Token phiên 2 giờ',
        uk: '2-годинний токен сесії',
      }),
      description: t({
        en: 'A temporary token tied directly to your user account. Valid for 2 hours, no access key required.',
        'en-GB':
          'A temporary token tied directly to your user account. Valid for 2 hours, no access key required.',
        fr: "Un jeton temporaire lié directement à votre compte utilisateur. Valide pendant 2 heures, aucune clé d'accès requise.",
        es: 'Un token temporal vinculado directamente a su cuenta de usuario. Válido por 2 horas, no se requiere clave de acceso.',
        de: 'Ein temporäres Token, das direkt mit Ihrem Benutzerkonto verknüpft ist. 2 Stunden gültig, kein Zugriffsschlüssel erforderlich.',
        ja: 'ユーザーアカウントに直接紐付けられた一時的なトークンです。2時間有効で、アクセスキーは不要です。',
        ko: '사용자 계정에 직접 연결된 임시 토큰입니다. 2시간 동안 유효하며 액세스 키가 필요하지 않습니다.',
        zh: '直接绑定到您的用户帐户的临时令牌。有效期为 2 小时，无需访问密钥。',
        ru: 'Временный токен, привязанный непосредственно к вашей учетной записи. Действителен в течение 2 часов, ключ доступа не требуется.',
        ar: 'رمز مؤقت مرتبط مباشرة بحساب المستخدم الخاص بك. صالح لمدة ساعتين، لا يلزم وجود مفتاح وصول.',
        it: 'Un token temporaneo legato direttamente al tuo account utente. Valido per 2 ore, nessuna chiave di accesso richiesta.',
        pt: 'Um token temporário vinculado diretamente à sua conta de usuário. Válido por 2 horas, sem necessidade de chave de acesso.',
        hi: 'आपके उपयोगकर्ता खाते से सीधे जुड़ा एक अस्थायी टोकन। 2 घंटे के लिए मान्य, किसी एक्सेस कुंजी की आवश्यकता नहीं है।',
        tr: 'Doğrudan kullanıcı hesabınıza bağlı geçici bir anahtar. 2 saat geçerlidir, erişim anahtarı gerekmez.',
        pl: 'Tymczasowy token powiązany bezpośrednio z Twoim kontem użytkownika. Ważny przez 2 godziny, nie wymaga klucza dostępu.',
        id: 'Token sementara yang terikat langsung ke akun pengguna Anda. Berlaku selama 2 jam, tidak perlu kunci akses.',
        vi: 'Một mã thông báo tạm thời gắn trực tiếp vào tài khoản người dùng của bạn. Có hiệu lực trong 2 giờ, không cần mã truy cập.',
        uk: 'Тимчасовий токен, прив’язаний безпосередньо до вашого облікового запису користувача. Діє протягом 2 годин, ключ доступу не потрібен.',
      }),
      error: t({
        en: 'Failed to create session token. Please try again.',
        'en-GB': 'Failed to create session token. Please try again.',
        fr: 'Échec de la création du jeton de session. Veuillez réessayer.',
        es: 'Error al crear el token de sesión. Por favor, inténtelo de nuevo.',
        de: 'Sitzungstoken konnte nicht erstellt werden. Bitte versuchen Sie es erneut.',
        ja: 'セッショントークンの作成に失敗しました。もう一度お試しください。',
        ko: '세션 토큰을 생성하지 못했습니다. 다시 시도하십시오.',
        zh: '创建会话令牌失败。请再试一次。',
        ru: 'Не удалось создать токен сессии. Пожалуйста, попробуйте еще раз.',
        ar: 'فشل إنشاء رمز الجلسة. يرجى المحاولة مرة أخرى.',
        it: 'Impossibile creare il token di sessione. Riprova.',
        pt: 'Falha ao criar o token de sessão. Por favor, tente novamente.',
        hi: 'सत्र टोकन बनाने में विफल। कृपया पुन: प्रयास करें।',
        tr: 'Oturum anahtarı oluşturulamadı. Lütfen tekrar deneyin.',
        pl: 'Nie udało się utworzyć tokena sesji. Spróbuj ponownie.',
        id: 'Gagal membuat token sesi. Silakan coba lagi.',
        vi: 'Không thể tạo mã thông báo phiên. Vui lòng thử lại.',
        uk: 'Не вдалося створити токен сесії. Спробуйте ще раз.',
      }),
      buttonLabel: t({
        en: 'Generate 2h session token',
        'en-GB': 'Generate 2h session token',
        fr: 'Générer un jeton de session de 2h',
        es: 'Generar token de sesión de 2h',
        de: '2h-Sitzungstoken generieren',
        ja: '2時間セッショントークンを生成',
        ko: '2시간 세션 토큰 생성',
        zh: '生成 2 小时会话令牌',
        ru: 'Создать 2-часовой токен сессии',
        ar: 'إنشاء رمز جلسة لمدة ساعتين',
        it: 'Genera token di sessione di 2 ore',
        pt: 'Gerar token de sessão de 2h',
        hi: '2 घंटे का सत्र टोकन उत्पन्न करें',
        tr: '2 saatlik oturum anahtarı oluştur',
        pl: 'Wygeneruj 2-godzinny token sesji',
        id: 'Buat token sesi 2 jam',
        vi: 'Tạo mã thông báo phiên 2 giờ',
        uk: 'Згенерувати 2-годинний токен сесії',
      }),
      buttonText: t({
        en: 'Authenticate with session',
        'en-GB': 'Authenticate with session',
        fr: "S'authentifier avec la session",
        es: 'Autenticarse con la sesión',
        de: 'Mit Sitzung authentifizieren',
        ja: 'セッションで認証',
        ko: '세션으로 인증',
        zh: '使用会话身份验证',
        ru: 'Аутентификация через сессию',
        ar: 'المصادقة مع الجلسة',
        it: 'Autenticati con la sessione',
        pt: 'Autenticar com sessão',
        hi: 'सत्र के साथ प्रमाणित करें',
        tr: 'Oturum ile kimlik doğrula',
        pl: 'Uwierzytelnij się za pomocą sesji',
        id: 'Autentikasi dengan sesi',
        vi: 'Xác thực bằng phiên',
        uk: 'Автентифікація за допомогою сесії',
      }),
    },
  },
  title: 'CLI Login Flow',
  description:
    'Content declaration for the CLI login flow used by the Auth/CliLogin component. Provides labels and selections for logging in, choosing organization, project, and access key.',
  tags: ['cli', 'authentication', 'login', 'auth-flow'],
} satisfies DeclarationContent;

export default cliLoginFlowContent;
