import { type Dictionary, t } from 'intlayer';

const translateSectionContent = {
  key: 'translate-section',
  title: 'AI CLI Translation Section',
  description:
    'Section highlighting Intlayer CLI capabilities. Describes terminal-based automation for translating JSON dictionaries and Markdown documentation.',
  content: {
    heroTag: 'AI CLI Tool',
    heroTitle: t({
      en: 'Automate translations from your terminal.',
      'en-GB': 'Automate translations from your terminal.',
      fr: 'Automatisez les traductions depuis votre terminal.',
      es: 'Automatiza las traducciones desde tu terminal.',
      de: 'Automatisieren Sie Übersetzungen direkt im Terminal.',
      ru: 'Автоматизируйте переводы прямо из терминала.',
      ja: 'ターミナルから翻訳を自動化。',
      ko: '터미널에서 번역을 자동화하세요.',
      zh: '从终端自动化翻译。',
      ar: 'أتمتة الترجمات من المحطة الطرفية (Terminal).',
      it: 'Automatizza le traduzioni dal tuo terminale.',
      pt: 'Automatize traduções a partir do seu terminal.',
      hi: 'अपने टर्मिनल से अनुवाद स्वचालित करें।',
      tr: 'Çevirileri terminalinizden otomatikleştirin.',
      pl: 'Automatyzuj tłumaczenia ze swojego terminala.',
      id: 'Otomatisasi terjemahan dari terminal Anda.',
      vi: 'Tự động hóa dịch thuật từ terminal của bạn.',
      uk: 'Автоматизуйте переклади зі свого терміналу.',
    }),
    heroSubtitle: t({
      en: 'The CLI to audit, fill, and translate JSON & Markdown with AI.',
      'en-GB': 'The CLI to audit, fill, and translate JSON & Markdown with AI.',
      fr: "La CLI pour auditer, remplir et traduire JSON & Markdown avec l'IA.",
      es: 'La CLI para auditar, completar y traducir JSON y Markdown con IA.',
      de: 'Die CLI zum Prüfen, Füllen und Übersetzen von JSON & Markdown mit KI.',
      ru: 'CLI для аудита, заполнения и перевода JSON и Markdown с помощью ИИ.',
      ja: 'AIでJSONとMarkdownを監査、補完、翻訳するためのCLI。',
      ko: 'AI로 JSON 및 Markdown을 감사, 채우기 및 번역하는 CLI.',
      zh: '用于利用 AI 审核、填充和翻译 JSON 与 Markdown 的 CLI。',
      ar: 'واجهة سطر الأوامر (CLI) لتدقيق وملء وترجمة JSON و Markdown بالذكاء الاصطناعي.',
      it: "La CLI per controllare, riempire e tradurre JSON e Markdown con l'IA.",
      pt: 'A CLI para auditar, preencher e traduzir JSON e Markdown com IA.',
      hi: 'AI के साथ JSON और Markdown को ऑडिट, भरने और अनुवाद करने के लिए CLI।',
      tr: "AI ile JSON ve Markdown'ı denetlemek, doldurmak ve çevirmek için CLI.",
      pl: 'CLI do audytu, uzupełniania i tłumaczenia JSON i Markdown za pomocą AI.',
      id: 'CLI untuk mengaudit, mengisi, dan menerjemahkan JSON & Markdown dengan AI.',
      vi: 'CLI để kiểm tra, điền và dịch JSON & Markdown bằng AI.',
      uk: 'CLI для аудиту, заповнення та перекладу JSON і Markdown за допомогою ШІ.',
    }),
    heroDescription: t({
      en: 'Run `npx intlayer fill` to detect missing keys and generate translations using OpenAI, Claude, or local models. Keep your Git history clean and your types safe.',
      'en-GB':
        'Run `npx intlayer fill` to detect missing keys and generate translations using OpenAI, Claude, or local models. Keep your Git history clean and your types safe.',
      fr: 'Lancez `npx intlayer fill` pour détecter les clés manquantes et générer des traductions via OpenAI, Claude ou modèles locaux. Gardez un historique Git propre et des types sûrs.',
      es: 'Ejecuta `npx intlayer fill` para detectar claves faltantes y generar traducciones con OpenAI, Claude o modelos locales. Mantén tu historial Git limpio y tipos seguros.',
      de: 'Führen Sie `npx intlayer fill` aus, um fehlende Schlüssel zu erkennen und Übersetzungen mit OpenAI, Claude oder lokalen Modellen zu erstellen. Sauberer Git-Verlauf, sichere Typen.',
      ru: 'Запустите `npx intlayer fill`, чтобы найти недостающие ключи и сгенерировать переводы через OpenAI, Claude или локальные модели. Чистый Git и безопасные типы.',
      ja: '`npx intlayer fill`を実行して不足しているキーを検出し、OpenAI、Claude、またはローカルモデルを使用して翻訳を生成します。Git履歴をきれいに保ち、型安全性を維持します。',
      ko: '`npx intlayer fill`을 실행하여 누락된 키를 감지하고 OpenAI, Claude 또는 로컬 모델을 사용하여 번역을 생성하세요. Git 기록을 깨끗하게 유지하고 타입을 안전하게 보호하세요.',
      zh: '运行 `npx intlayer fill` 检测缺失的键，并使用 OpenAI、Claude 或本地模型生成翻译。保持 Git 历史整洁和类型安全。',
      ar: 'قم بتشغيل `npx intlayer fill` لاكتشاف المفاتيح المفقودة وإنشاء ترجمات باستخدام OpenAI أو Claude أو النماذج المحلية. حافظ على نظافة سجل Git وسلامة الأنواع.',
      it: 'Esegui `npx intlayer fill` per rilevare chiavi mancanti e generare traduzioni usando OpenAI, Claude o modelli locali. Mantieni pulita la cronologia Git e i tipi sicuri.',
      pt: 'Execute `npx intlayer fill` para detectar chaves ausentes e gerar traduções usando OpenAI, Claude ou modelos locais. Mantenha seu histórico Git limpo e tipos seguros.',
      hi: 'लापता कुंजियों का पता लगाने और OpenAI, Claude, या स्थानीय मॉडल का उपयोग करके अनुवाद उत्पन्न करने के लिए `npx intlayer fill` चलाएं। अपना Git इतिहास साफ रखें।',
      tr: 'Eksik anahtarları tespit etmek ve OpenAI, Claude veya yerel modelleri kullanarak çeviriler oluşturmak için `npx intlayer fill` çalıştırın. Git geçmişinizi temiz tutun.',
      pl: 'Uruchom `npx intlayer fill`, aby wykryć brakujące klucze i wygenerować tłumaczenia za pomocą OpenAI, Claude lub modeli lokalnych. Czysta historia Git i bezpieczne typy.',
      id: 'Jalankan `npx intlayer fill` untuk mendeteksi kunci yang hilang dan menghasilkan terjemahan menggunakan OpenAI, Claude, atau model lokal. Jaga riwayat Git tetap bersih.',
      vi: 'Chạy `npx intlayer fill` để phát hiện các khóa bị thiếu và tạo bản dịch bằng OpenAI, Claude hoặc các mô hình cục bộ. Giữ lịch sử Git sạch sẽ và kiểu an toàn.',
      uk: 'Запустіть `npx intlayer fill`, щоб виявити відсутні ключі та згенерувати переклади за допомогою OpenAI, Claude або локальних моделей. Зберігайте історію Git чистою.',
    }),
    primaryCta: t({
      en: 'Try the CLI',
      'en-GB': 'Try the CLI',
      fr: 'Essayer la CLI',
      es: 'Probar la CLI',
      de: 'CLI ausprobieren',
      ru: 'Попробовать CLI',
      ja: 'CLIを試す',
      ko: 'CLI 사용해보기',
      zh: '试用 CLI',
      ar: 'جرب واجهة سطر الأوامر',
      it: 'Prova la CLI',
      pt: 'Experimente a CLI',
      hi: 'CLI आज़माएं',
      tr: "CLI'ı Dene",
      pl: 'Wypróbuj CLI',
      id: 'Coba CLI',
      vi: 'Thử CLI',
      uk: 'Спробувати CLI',
    }),
  },
  tags: ['cli', 'translation', 'automation', 'json', 'markdown'],
} satisfies Dictionary;

export default translateSectionContent;
