version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 0
    # Disable Dependabot pull requests
    rebase-strategy: "disabled"
