export { default as ContentSelectorWrapper } from './ContentSelectorWrapper.vue';
export * from './configuration';
export * from './dictionariesRecord';
export * from './editedContent';
export * from './editorEnabled';
export * from './editorLocale';
export * from './focusDictionary';
export * from './installIntlayerEditor';
export * from './useCrossFrameMessageListener';
export * from './useCrossFrameState';
export * from './useEditor';
export * from './useIframeClickInterceptor';
