import { type Dictionary, t } from 'intlayer';

const mCPMessageContent = {
  key: 'mcp-message',
  content: {
    title: t({
      ar: 'أضف MCP Server إلى مساعدك الذكي',
      de: 'MCP Server zu Ihrem AI-Assistenten hinzufügen',
      en: 'Add the MCP Server to your AI Assistant',
      'en-GB': 'Add the MCP Server to your AI Assistant',
      es: 'Añadir MCP Server a tu asistente de IA',
      fr: 'Ajouter le MCP Server à votre assistant AI',
      hi: 'MCP Server को अपने AI एसिस्टेंट में जोड़ें',
      it: 'Aggiungi MCP Server al tuo assistente AI',
      ja: 'AIアシスタントにMCP Serverを追加',
      ko: 'MCP Server를 AI 어시스턴트에 추가',
      pt: 'Adicionar MCP Server ao seu assistente de IA',
      ru: 'Добавить MCP Server в ваш AI-ассистент',
      tr: 'MCP Sunucusunu AI Asistanınıza Ekleyin',
      zh: '将 MCP 服务器添加到您的 AI 助手',
    }),
    description: t({
      ar: 'بدءاً من الدمج مع خادم MCP Intlayer ، يمكن لمساعدك الذكي الاسترجاع من جميع المستندات مباشرة من ChatGPT ، DeepSeek ، Cursor ، VSCode ، إلخ.',
      de: 'Durch die Integration des Intlayer MCP-Servers in Ihren bevorzugten AI-Assistenten können Sie alle Dokumente direkt von ChatGPT, DeepSeek, Cursor, VSCode usw. abrufen.',
      en: 'By integrating the Intlayer MCP Server to your favourite AI assistant can retrieve all the doc directly from ChatGPT, DeepSeek, Cursor, VSCode, etc.',
      'en-GB':
        'By integrating the Intlayer MCP Server to your favourite AI assistant can retrieve all the doc directly from ChatGPT, DeepSeek, Cursor, VSCode, etc.',
      es: 'Al integrar el servidor MCP Intlayer a tu asistente de IA, puedes recuperar todos los documentos directamente desde ChatGPT, DeepSeek, Cursor, VSCode, etc.',
      fr: 'En intégrant le serveur MCP Intlayer à votre assistant AI, vous pouvez récupérer tous les documents directement depuis ChatGPT, DeepSeek, Cursor, VSCode, etc.',
      hi: 'अपने पसंदीदा AI एसिस्टेंट में Intlayer MCP सर्वर को एकीकृत करके आप सभी दस्तावेज़ को सीधे ChatGPT, DeepSeek, Cursor, VSCode से प्राप्त कर सकते हैं।',
      it: 'Integrando il server MCP Intlayer al tuo assistente AI, puoi recuperare tutti i documenti direttamente da ChatGPT, DeepSeek, Cursor, VSCode, ecc.',
      ja: 'Intlayer MCPサーバーを統合することで、ChatGPT、DeepSeek、Cursor、VSCodeなどから直接ドキュメントを取得できます。',
      ko: 'Intlayer MCP 서버를 통해 ChatGPT, DeepSeek, Cursor, VSCode 등에서 직접 문서를 검색할 수 있습니다.',
      pt: 'Ao integrar o servidor MCP Intlayer ao seu assistente de IA, você pode recuperar todos os documentos diretamente de ChatGPT, DeepSeek, Cursor, VSCode, etc.',
      ru: 'Интеграция сервера MCP Intlayer в ваш любимый AI-ассистент позволяет получать все документы непосредственно из ChatGPT, DeepSeek, Cursor, VSCode и т.д.',
      tr: 'Intlayer MCP Sunucusunu favori AI asistanınıza entegre ederek tüm belgeleri doğrudan ChatGPT, DeepSeek, Cursor, VSCode vb. üzerinden alabilirsiniz.',
      zh: '通过将 Intlayer MCP 服务器集成到您的 AI 助手，您可以直接从 ChatGPT、DeepSeek、Cursor、VSCode 等获取所有文档。',
    }),
    link: {
      test: t({
        en: 'See MCP Server doc',
        fr: 'Voir la documentation du serveur MCP',
        ar: 'عرض الوثائق الخاصة بالخادم MCP',
        de: 'Dokumentation des MCP-Servers ansehen',
        es: 'Ver la documentación del servidor MCP',
        it: 'Vedi la documentazione del server MCP',
        ja: 'MCPサーバーのドキュメントを表示',
        ko: 'MCP 서버 문서 보기',
        pt: 'Ver a documentação do servidor MCP',
        ru: 'Просмотр документации сервера MCP',
        'en-GB': 'See MCP Server doc',
        hi: 'MCP सर्वर दस्तावेज़ देखें',
        zh: '查看 MCP 服务器文档',
        tr: 'MCP Sunucu belgesini görüntüle',
      }),
      label: t({
        en: 'See MCP Server doc',
        fr: 'Voir la documentation du serveur MCP',
        ar: 'عرض الوثائق الخاصة بالخادم MCP',
        de: 'Dokumentation des MCP-Servers ansehen',
        es: 'Ver la documentación del servidor MCP',
        it: 'Vedi la documentazione del server MCP',
        ja: 'MCPサーバーのドキュメントを表示',
        ko: 'MCP 서버 문서 보기',
        pt: 'Ver a documentação do servidor MCP',
        ru: 'Просмотр документации сервера MCP',
        'en-GB': 'See MCP Server doc',
        hi: 'MCP सर्वर दस्तावेज़ देखें',
        zh: '查看 MCP 服务器文档',
        tr: 'MCP Sunucu belgesini görüntüle',
      }),
    },
  },
} satisfies Dictionary;

export default mCPMessageContent;
