import { type Dictionary, t } from 'intlayer';

const messageFormatterContent = {
  key: 'message-formatter-page',
  content: {
    freeBadge: t({
      en: 'Free Tool',
      'en-GB': 'Free Tool',
      fr: 'Outil Gratuit',
      es: 'Herramienta Gratuita',
      de: 'Kostenloses Tool',
      ru: 'Бесплатный инструмент',
      ja: '無料ツール',
      ko: '무료 도구',
      zh: '免费工具',
      ar: 'أداة مجانية',
      it: 'Strumento Gratuito',
      pt: 'Ferramenta Gratuita',
      hi: 'मुफ़्त उपकरण',
      tr: 'Ücretsiz Araç',
      pl: 'Darmowe narzędzie',
      id: 'Alat Gratis',
      vi: 'Công cụ miễn phí',
      uk: 'Безкоштовний інструмент',
    }),
    ecosystemBadge: t({
      en: 'Intlayer Ecosystem',
      'en-GB': 'Intlayer Ecosystem',
      fr: 'Écosystème Intlayer',
      es: 'Ecosistema Intlayer',
      de: 'Intlayer Ökosystem',
      ru: 'Экосистема Intlayer',
      ja: 'Intlayer エコシステム',
      ko: 'Intlayer 생태계',
      zh: 'Intlayer 生态系统',
      ar: 'منظومة Intlayer',
      it: 'Ecosistema Intlayer',
      pt: 'Ecossistema Intlayer',
      hi: 'Intlayer पारिस्थितिकी तंत्र',
      tr: 'Intlayer Ekosistemi',
      pl: 'Ekosystem Intlayer',
      id: 'Ekosistem Intlayer',
      vi: 'Hệ sinh thái Intlayer',
      uk: 'Екосистема Intlayer',
    }),
    githubLabel: t({
      en: 'GitHub',
      'en-GB': 'GitHub',
      fr: 'GitHub',
      es: 'GitHub',
      de: 'GitHub',
      ru: 'GitHub',
      ja: 'GitHub',
      ko: 'GitHub',
      zh: 'GitHub',
      ar: 'GitHub',
      it: 'GitHub',
      pt: 'GitHub',
      hi: 'GitHub',
      tr: 'GitHub',
      pl: 'GitHub',
      id: 'GitHub',
      vi: 'GitHub',
      uk: 'GitHub',
    }),
    icu: {
      title: t({
        en: 'ICU Message Formatter & Editor',
        'en-GB': 'ICU Message Formatter & Editor',
        fr: 'Éditeur & Formateur de Messages ICU',
        es: 'Editor y Formateador de Mensajes ICU',
        de: 'ICU-Nachrichten-Formatierer & Editor',
        ru: 'Редактор и форматировщик сообщений ICU',
        ja: 'ICU メッセージフォーマッター＆エディター',
        ko: 'ICU 메시지 포맷터 및 편집기',
        zh: 'ICU 消息格式化与编辑器',
        ar: 'محرر ومنسق رسائل ICU',
        it: 'Editor e formattatore di messaggi ICU',
        pt: 'Editor e Formatador de Mensagens ICU',
        hi: 'ICU संदेश प्रारूपक और संपादक',
        tr: 'ICU Mesaj Formatlayıcı ve Düzenleyici',
        pl: 'Edytor i formatowanie wiadomości ICU',
        id: 'Pemformat & Editor Pesan ICU',
        vi: 'Trình định dạng & Trình chỉnh sửa tin nhắn ICU',
        uk: 'Редактор та форматувальник повідомлень ICU',
      }),
      description: t({
        en: 'Build, test, and validate ICU MessageFormat strings with live preview, 100+ templates, and multi-language CLDR plural validation.',
        'en-GB':
          'Build, test, and validate ICU MessageFormat strings with live preview, 100+ templates, and multi-language CLDR plural validation.',
        fr: 'Créez, testez et validez vos chaînes ICU MessageFormat avec aperçu en direct, plus de 100 modèles et validation des pluriels CLDR multilingues.',
        es: 'Crea, prueba y valida cadenas ICU MessageFormat con vista previa en vivo, más de 100 plantillas y validación de plurales CLDR.',
        de: 'Erstellen, testen und validieren Sie ICU-MessageFormat-Zeichenfolgen mit Live-Vorschau, über 100 Vorlagen und mehrsprachiger CLDR-Pluralvalidierung.',
        ru: 'Создавайте, тестируйте и проверяйте строки ICU MessageFormat с предварительным просмотром, более чем 100 шаблонами и валидацией множественных форм CLDR.',
        ja: 'ライブプレビュー、100以上のテンプレート、多言語CLDR複数形検証を備えたICU MessageFormat文字列を作成、テスト、検証します。',
        ko: '실시간 미리보기, 100개 이상의 템플릿, 다국어 CLDR 복수형 유효성 검사를 통해 ICU MessageFormat 문자열을 빌드, 테스트 및 검증하세요.',
        zh: '使用实时预览、100+ 模板和多语言 CLDR 复数验证来构建、测试和验证 ICU MessageFormat 字符串。',
        ar: 'قم بإنشاء واختبار والتحقق من صحة سلاسل ICU MessageFormat مع معاينة حية وأكثر من 100 قالب والتحقق من صيغ الجمع في CLDR.',
        it: 'Crea, testa e valida stringhe ICU MessageFormat con anteprima dal vivo, oltre 100 modelli e convalida dei plurali CLDR multilingue.',
        pt: 'Crie, teste e valide strings ICU MessageFormat com visualização em tempo real, mais de 100 modelos e validação de plurais CLDR.',
        hi: 'लाइव पूर्वावलोकन, 100+ टेम्प्लेट और बहुभाषी CLDR बहुवचन सत्यापन के साथ ICU MessageFormat स्ट्रिंग्स बनाएं, परीक्षण करें और सत्यापित करें।',
        tr: 'Canlı önizleme, 100+ şablon ve çok dilli CLDR çoğul doğrulaması ile ICU MessageFormat dizelerini oluşturun, test edin ve doğrulayın.',
        pl: 'Twórz, testuj i weryfikuj ciągi ICU MessageFormat z podglądem na żywo, ponad 100 szablonami i walidacją liczb mnogich CLDR.',
        id: 'Buat, uji, dan validasi string ICU MessageFormat dengan pratinjau langsung, 100+ templat, dan validasi jamak CLDR multibahasa.',
        vi: 'Xây dựng, kiểm tra và xác thực chuỗi ICU MessageFormat với xem trước trực tiếp, hơn 100 mẫu và xác thực số nhiều CLDR đa ngôn ngữ.',
        uk: 'Створюйте, тестуйте та перевіряйте рядки ICU MessageFormat із попереднім переглядом, 100+ шаблонами та перевіркою форм множини CLDR.',
      }),
    },
    i18next: {
      title: t({
        en: 'i18next Message Formatter & Editor',
        'en-GB': 'i18next Message Formatter & Editor',
        fr: 'Éditeur & Formateur de Messages i18next',
        es: 'Editor y Formateador de Mensajes i18next',
        de: 'i18next-Nachrichten-Formatierer & Editor',
        ru: 'Редактор и форматировщик сообщений i18next',
        ja: 'i18next メッセージフォーマッター＆エディター',
        ko: 'i18next 메시지 포맷터 및 편집기',
        zh: 'i18next 消息格式化与编辑器',
        ar: 'محرر ومنسق رسائل i18next',
        it: 'Editor e formattatore di messaggi i18next',
        pt: 'Editor e Formatador de Mensagens i18next',
        hi: 'i18next संदेश प्रारूपक और संपादक',
        tr: 'i18next Mesaj Formatlayıcı ve Düzenleyici',
        pl: 'Edytor i formatowanie wiadomości i18next',
        id: 'Pemformat & Editor Pesan i18next',
        vi: 'Trình định dạng & Trình chỉnh sửa tin nhắn i18next',
        uk: 'Редактор та форматувальник повідомлень i18next',
      }),
      description: t({
        en: 'Format and test i18next strings with double-brace interpolation, plural suffixes (_one, _other), context keys, and nesting.',
        'en-GB':
          'Format and test i18next strings with double-brace interpolation, plural suffixes (_one, _other), context keys, and nesting.',
        fr: 'Formatez et testez vos chaînes i18next avec interpolation en doubles accolades, suffixes pluriels (_one, _other), clés de contexte et imbrications.',
        es: 'Formatea y prueba cadenas i18next con interpolación de llaves dobles, sufijos plurales (_one, _other), claves de contexto y anidamiento.',
        de: 'Formatieren und testen Sie i18next-Zeichenfolgen mit doppelter Klammerinterpolation, Pluralsuffixen (_one, _other), Kontextschlüsseln und Verschachtelung.',
        ru: 'Форматируйте и тестируйте строки i18next с двойными фигурными скобками, суффиксами множественного числа (_one, _other), контекстом и вложенностью.',
        ja: '二重中括弧の補間、複数形サフィックス（_one、_other）、コンテキストキー、ネストを使用してi18next文字列をフォーマットおよびテストします。',
        ko: '이중 중괄호 보간, 복수형 접미사(_one, _other), 컨텍스트 키 및 중첩을 사용하여 i18next 문자열을 포맷하고 테스트하세요.',
        zh: '使用双括号插值、复数后缀（_one, _other）、上下文键和嵌套来格式化和测试 i18next 字符串。',
        ar: 'قم بتنسيق واختبار سلاسل i18next باستخدام الأقواس المزدوجة ولواحق الجمع ومفاتيح السياق والتداخل.',
        it: 'Formatta e testa stringhe i18next con interpolazione a doppie parentesi graffe, suffissi plurali, chiavi di contesto e nidificazione.',
        pt: 'Formate e teste strings i18next com interpolação de chaves duplas, sufixos plurais, chaves de contexto e aninhamento.',
        hi: 'डबल-ब्रेस इंटरपोलेशन, बहुवचन प्रत्यय (_one, _other), संदर्भ कुंजियों और नेस्टिंग के साथ i18next स्ट्रिंग्स को प्रारूपित और परीक्षण करें।',
        tr: 'Çift parantez enterpolasyonu, çoğul ekler (_one, _other), bağlam anahtarları ve iç içe geçme ile i18next dizelerini biçimlendirin ve test edin.',
        pl: 'Formatuj i testuj ciągi i18next z podwójnymi klamrami, przyrostkami liczby mnogiej (_one, _other), kluczami kontekstowymi i zagnieżdżaniem.',
        id: 'Format dan uji string i18next dengan interpolasi kurung kurawal ganda, sufiks jamak, kunci konteks, dan penyarangan.',
        vi: 'Định dạng và kiểm tra chuỗi i18next với nội suy dấu ngoặc kép, hậu tố số nhiều, khóa ngữ cảnh và lồng ghép.',
        uk: 'Форматуйте та тестуйте рядки i18next з подвійними фігурними дужками, суфіксами множини, ключами контексту та вкладенням.',
      }),
    },
    vueI18n: {
      title: t({
        en: 'Vue I18n Message Formatter & Editor',
        'en-GB': 'Vue I18n Message Formatter & Editor',
        fr: 'Éditeur & Formateur de Messages Vue I18n',
        es: 'Editor y Formateador de Mensajes Vue I18n',
        de: 'Vue-I18n-Nachrichten-Formatierer & Editor',
        ru: 'Редактор и форматировщик сообщений Vue I18n',
        ja: 'Vue I18n メッセージフォーマッター＆エディター',
        ko: 'Vue I18n 메시지 포맷터 및 편집기',
        zh: 'Vue I18n 消息格式化与编辑器',
        ar: 'محرر ومنسق رسائل Vue I18n',
        it: 'Editor e formattatore di messaggi Vue I18n',
        pt: 'Editor e Formatador de Mensagens Vue I18n',
        hi: 'Vue I18n संदेश प्रारूपक और संपादक',
        tr: 'Vue I18n Mesaj Formatlayıcı ve Düzenleyici',
        pl: 'Edytor i formatowanie wiadomości Vue I18n',
        id: 'Pemformat & Editor Pesan Vue I18n',
        vi: 'Trình định dạng & Trình chỉnh sửa tin nhắn Vue I18n',
        uk: 'Редактор та форматувальник повідомлень Vue I18n',
      }),
      description: t({
        en: 'Build and test Vue I18n translation messages with pipe pluralization (0 | 1 | other), named formatting {name}, and linked messages @:key.',
        'en-GB':
          'Build and test Vue I18n translation messages with pipe pluralization (0 | 1 | other), named formatting {name}, and linked messages @:key.',
        fr: 'Créez et testez des messages Vue I18n avec pluralisation par tube (0 | 1 | autre), formatage nommé {name} et messages liés @:cle.',
        es: 'Crea y prueba mensajes de traducción de Vue I18n con pluralización por tubería (0 | 1 | otro), formato nombrado y mensajes vinculados.',
        de: 'Erstellen und testen Sie Vue-I18n-Nachrichten mit Pipe-Pluralisierung (0 | 1 | andere), benannter Formatierung {name} und verknüpften Nachrichten @:key.',
        ru: 'Создавайте и тестируйте сообщения Vue I18n с плюрализацией через вертикальную черту, именованными переменными {name} и связями @:key.',
        ja: 'パイプ複数形化（0 | 1 | その他）、名前付きフォーマット {name}、リンクされたメッセージ @:key を備えたVue I18nメッセージを作成およびテストします。',
        ko: '파이프 복수형(0 | 1 | 기타), 명명된 서식 {name}, 연결된 메시지 @:key를 사용하여 Vue I18n 메시지를 빌드하고 테스트하세요.',
        zh: '使用管道复数（0 | 1 | 其他）、命名格式化 {name} 和链接消息 @:key 构建和测试 Vue I18n 翻译消息。',
        ar: 'قم ببناء واختبار رسائل Vue I18n مع صيغ الجمع عبر الخطوط العمودية، والتنسيق المسمى {name} والرسائل المرتبطة @:key.',
        it: 'Crea e testa messaggi di traduzione Vue I18n con pluralizzazione a pipe (0 | 1 | altro), formattazione con nome e messaggi collegati.',
        pt: 'Crie e teste mensagens do Vue I18n com pluralização por barra vertical (0 | 1 | outro), formatação nomeada e mensagens vinculadas.',
        hi: 'पाइप बहुवचन (0 | 1 | अन्य), नामित प्रारूपण {name}, और लिंक किए गए संदेशों @:key के साथ Vue I18n संदेशों का निर्माण और परीक्षण करें।',
        tr: 'Boru çoğullaştırması (0 | 1 | diğer), adlandırılmış biçimlendirme {name} ve bağlantılı iletiler @:key ile Vue I18n iletileri oluşturun ve test edin.',
        pl: 'Twórz i testuj wiadomości Vue I18n z liczbą mnogą oddzielaną pionową kreską, formatowaniem nazwanym {name} i połączonymi wiadomościami @:key.',
        id: 'Buat dan uji pesan terjemahan Vue I18n dengan pluralisasi pipa (0 | 1 | other), pemformatan bernama {name}, dan pesan tertaut @:key.',
        vi: 'Xây dựng và kiểm tra tin nhắn dịch Vue I18n với số nhiều dấu gạch đứng (0 | 1 | other), định dạng có tên {name} và tin nhắn liên kết @:key.',
        uk: 'Створюйте та тестуйте повідомлення Vue I18n з плюралізацією через вертикальну риску, іменованими змінними {name} та зв’язками @:key.',
      }),
    },
    po: {
      title: t({
        en: 'GNU Gettext PO File Formatter & Editor',
        'en-GB': 'GNU Gettext PO File Formatter & Editor',
        fr: 'Éditeur & Formateur de Fichiers PO Gettext',
        es: 'Editor y Formateador de Archivos PO Gettext',
        de: 'GNU-Gettext-PO-Datei-Formatierer & Editor',
        ru: 'Редактор и форматировщик файлов PO GNU Gettext',
        ja: 'GNU Gettext PO ファイルフォーマッター＆エディター',
        ko: 'GNU Gettext PO 파일 포맷터 및 편집기',
        zh: 'GNU Gettext PO 文件格式化与编辑器',
        ar: 'محرر ومنسق ملفات GNU Gettext PO',
        it: 'Editor e formattatore di file PO GNU Gettext',
        pt: 'Editor e Formatador de Arquivos PO GNU Gettext',
        hi: 'GNU Gettext PO फ़ाइल प्रारूपक और संपादक',
        tr: 'GNU Gettext PO Dosyası Formatlayıcı ve Düzenleyici',
        pl: 'Edytor i formatowanie plików PO GNU Gettext',
        id: 'Pemformat & Editor File PO GNU Gettext',
        vi: 'Trình định dạng & Trình chỉnh sửa tệp PO GNU Gettext',
        uk: 'Редактор та форматувальник файлів PO GNU Gettext',
      }),
      description: t({
        en: 'Format, validate, and test GNU Gettext PO translation files with msgid, msgstr, msgid_plural, and printf placeholders (%s, %d).',
        'en-GB':
          'Format, validate, and test GNU Gettext PO translation files with msgid, msgstr, msgid_plural, and printf placeholders (%s, %d).',
        fr: 'Formatez, validez et testez des fichiers de traduction Gettext PO avec msgid, msgstr, msgid_plural et variables printf (%s, %d).',
        es: 'Formatea, valida y prueba archivos de traducción Gettext PO con msgid, msgstr, msgid_plural y marcadores de posición printf.',
        de: 'Formatieren, validieren und testen Sie GNU-Gettext-PO-Übersetzungsdateien mit msgid, msgstr, msgid_plural und printf-Platzhaltern.',
        ru: 'Форматируйте, проверяйте и тестируйте файлы переводов Gettext PO с msgid, msgstr, msgid_plural и заполнителями printf (%s, %d).',
        ja: 'msgid、msgstr、msgid_plural、printfプレースホルダー（%s、%d）を使用してGNU Gettext PO翻訳ファイルをフォーマット、検証、テストします。',
        ko: 'msgid, msgstr, msgid_plural 및 printf 자리 표시자(%s, %d)를 사용하여 GNU Gettext PO 번역 파일을 포맷, 검증 및 테스트하세요.',
        zh: '使用 msgid、msgstr、msgid_plural 和 printf 占位符（%s、%d）格式化、验证和测试 GNU Gettext PO 翻译文件。',
        ar: 'قم بتنسيق والتحقق من صحة واختبار ملفات ترجمة Gettext PO باستخدام msgid وmsgstr وmsgid_plural وعناصر printf (%s, %d).',
        it: 'Formatta, convalida e testa file di traduzione Gettext PO con msgid, msgstr, msgid_plural e segnaposto printf.',
        pt: 'Formate, valide e teste arquivos de tradução Gettext PO com msgid, msgstr, msgid_plural e marcadores de posição printf.',
        hi: 'msgid, msgstr, msgid_plural और printf प्लेसहोल्डर्स (%s, %d) के साथ GNU Gettext PO अनुवाद फ़ाइलों को प्रारूपित, मान्य और परीक्षण करें।',
        tr: 'Ücretsiz çevrimiçi GNU Gettext PO dosya düzenleyicisi ve mesaj biçimlendiricisi. msgid, msgstr, msgid_plural, msgctxt ve printf belirteçleri ile PO çeviri girişlerini test edin ve doğrulayın.',
        pl: 'Formatuj, weryfikuj i testuj pliki tłumaczeń Gettext PO z msgid, msgstr, msgid_plural i symbolami zastępczymi printf.',
        id: 'Format, validasi, dan uji file terjemahan Gettext PO dengan msgid, msgstr, msgid_plural, dan placeholder printf.',
        vi: 'Định dạng, xác thực và kiểm tra các tệp dịch Gettext PO với msgid, msgstr, msgid_plural và trình giữ chỗ printf.',
        uk: 'Форматуйте, перевіряйте та тестуйте файли перекладів Gettext PO з msgid, msgstr, msgid_plural та заповнювачами printf (%s, %d).',
      }),
    },
    nav: {
      toolsLabel: t({
        en: 'Switch Format Editor:',
        'en-GB': 'Switch Format Editor:',
        fr: 'Changer de formateur :',
        es: 'Cambiar de formateador:',
        de: 'Format-Editor wechseln:',
        ru: 'Сменить редактор:',
        ja: 'エディターを切り替え:',
        ko: '형식 편집기 전환:',
        zh: '切换格式编辑器：',
        ar: 'تبديل المحرر:',
        it: 'Cambia editor:',
        pt: 'Mudar de editor:',
        hi: 'प्रारूप संपादक बदलें:',
        tr: 'Format Düzenleyicisini Değiştir:',
        pl: 'Zmień edytor:',
        id: 'Ganti Editor:',
        vi: 'Chuyển đổi trình chỉnh sửa:',
        uk: 'Змінити редактор:',
      }),
      converterLink: t({
        en: 'Cross-Format Converter',
        'en-GB': 'Cross-Format Converter',
        fr: 'Convertisseur multi-formats',
        es: 'Convertidor multiformato',
        de: 'Multi-Format-Konverter',
        ru: 'Конвертер между форматами',
        ja: 'マルチフォーマットコンバーター',
        ko: '다중 형식 변환기',
        zh: '多格式转换器',
        ar: 'محول التنسيقات المتعددة',
        it: 'Convertitore multiformato',
        pt: 'Conversor multiformato',
        hi: 'मल्टी-फॉर्मेट परिवर्तक',
        tr: 'Çoklu Format Dönüştürücü',
        pl: 'Konwerter wieloformatowy',
        id: 'Pengonversi Multi-Format',
        vi: 'Trình chuyển đổi đa định dạng',
        uk: 'Багатоформатний конвертер',
      }),
    },
    categories: {
      basic: t({
        en: 'Basic',
        'en-GB': 'Basic',
        fr: 'Bases',
        es: 'Básico',
        de: 'Grundlegend',
        ru: 'Базовые',
        ja: '基本',
        ko: '기본',
        zh: '基础',
        ar: 'أساسي',
        it: 'Base',
        pt: 'Básico',
        hi: 'बुनियादी',
        tr: 'Temel',
        pl: 'Podstawowe',
        id: 'Dasar',
        vi: 'Cơ bản',
        uk: 'Базові',
      }),
      pluralization: t({
        en: 'Pluralization',
        'en-GB': 'Pluralization',
        fr: 'Pluralisation',
        es: 'Pluralización',
        de: 'Pluralisierung',
        ru: 'Множественное число',
        ja: '複数形',
        ko: '복수형',
        zh: '复数化',
        ar: 'الجمع',
        it: 'Pluralizzazione',
        pt: 'Pluralização',
        hi: 'बहुवचन',
        tr: 'Çoğullaştırma',
        pl: 'Liczba mnoga',
        id: 'Pluralisasi',
        vi: 'Số nhiều',
        uk: 'Множина',
      }),
      select: t({
        en: 'Select / Context',
        'en-GB': 'Select / Context',
        fr: 'Sélection / Contexte',
        es: 'Selección / Contexto',
        de: 'Auswahl / Kontext',
        ru: 'Выбор / Контекст',
        ja: '選択 / 文脈',
        ko: '선택 / 컨텍스트',
        zh: '选择 / 上下文',
        ar: 'اختيار / سياق',
        it: 'Selezione / Contesto',
        pt: 'Seleção / Contexto',
        hi: 'चयन / संदर्भ',
        tr: 'Seçim / Bağlam',
        pl: 'Wybór / Kontekst',
        id: 'Pilihan / Konteks',
        vi: 'Lựa chọn / Ngữ cảnh',
        uk: 'Вибір / Контекст',
      }),
      ordinal: t({
        en: 'Ordinal',
        'en-GB': 'Ordinal',
        fr: 'Ordinal',
        es: 'Ordinal',
        de: 'Ordinalzahlen',
        ru: 'Порядковые числительные',
        ja: '序数',
        ko: '서수',
        zh: '序数',
        ar: 'الأعداد الترتيبية',
        it: 'Ordinale',
        pt: 'Ordinal',
        hi: 'क्रमसूचक',
        tr: 'Sıra Sayısı',
        pl: 'Liczebniki porządkowe',
        id: 'Ordinal',
        vi: 'Số thứ tự',
        uk: 'Порядкові',
      }),
      nested: t({
        en: 'Nested',
        'en-GB': 'Nested',
        fr: 'Imbriqué',
        es: 'Anidado',
        de: 'Verschachtelt',
        ru: 'Вложенные',
        ja: 'ネスト',
        ko: '중첩',
        zh: '嵌套',
        ar: 'متداخل',
        it: 'Annidato',
        pt: 'Aninhado',
        hi: 'नेस्टेड',
        tr: 'İç İçe',
        pl: 'Zagnieżdżone',
        id: 'Tersarang',
        vi: 'Lồng nhau',
        uk: 'Вкладені',
      }),
      numbers: t({
        en: 'Numbers',
        'en-GB': 'Numbers',
        fr: 'Nombres',
        es: 'Números',
        de: 'Zahlen',
        ru: 'Числа',
        ja: '数値',
        ko: '숫자',
        zh: '数字',
        ar: 'الأرقام',
        it: 'Numeri',
        pt: 'Números',
        hi: 'संख्याएं',
        tr: 'Sayılar',
        pl: 'Liczby',
        id: 'Angka',
        vi: 'Số',
        uk: 'Числа',
      }),
      dates: t({
        en: 'Dates & Time',
        'en-GB': 'Dates & Time',
        fr: 'Dates & Heure',
        es: 'Fechas y Hora',
        de: 'Datum & Uhrzeit',
        ru: 'Даты и время',
        ja: '日付と時刻',
        ko: '날짜 및 시간',
        zh: '日期与时间',
        ar: 'التاريخ والوقت',
        it: 'Date e ora',
        pt: 'Datas e Horas',
        hi: 'दिनांक और समय',
        tr: 'Tarih ve Saat',
        pl: 'Daty i czas',
        id: 'Tanggal & Waktu',
        vi: 'Ngày & Giờ',
        uk: 'Дати та час',
      }),
      'rich-text': t({
        en: 'Rich Text',
        'en-GB': 'Rich Text',
        fr: 'Texte enrichi',
        es: 'Texto enriquecido',
        de: 'Rich Text',
        ru: 'Форматированный текст',
        ja: 'リッチテキスト',
        ko: '서식 있는 텍스트',
        zh: '富文本',
        ar: 'نص منسق',
        it: 'Testo formattato',
        pt: 'Texto formatado',
        hi: 'रिच टेक्स्ट',
        tr: 'Zengin Metin',
        pl: 'Tekst sformatowany',
        id: 'Teks Kaya',
        vi: 'Văn bản có định dạng',
        uk: 'Форматований текст',
      }),
      social: t({
        en: 'Social',
        'en-GB': 'Social',
        fr: 'Réseaux sociaux',
        es: 'Redes sociales',
        de: 'Soziales',
        ru: 'Социальные сети',
        ja: 'ソーシャル',
        ko: '소셜',
        zh: '社交',
        ar: 'التواصل الاجتماعي',
        it: 'Social',
        pt: 'Redes sociais',
        hi: 'सामाजिक',
        tr: 'Sosyal',
        pl: 'Społeczność',
        id: 'Sosial',
        vi: 'Mạng xã hội',
        uk: 'Соціальні мережі',
      }),
      ecommerce: t({
        en: 'E-commerce',
        'en-GB': 'E-commerce',
        fr: 'E-commerce',
        es: 'Comercio electrónico',
        de: 'E-Commerce',
        ru: 'Электронная коммерция',
        ja: 'Eコマース',
        ko: '전자상거래',
        zh: '电子商务',
        ar: 'التجارة الإلكترونية',
        it: 'E-commerce',
        pt: 'Comércio eletrônico',
        hi: 'ई-कॉमर्स',
        tr: 'E-ticaret',
        pl: 'E-commerce',
        id: 'E-commerce',
        vi: 'Thương mại điện tử',
        uk: 'Електронна комерція',
      }),
      forms: t({
        en: 'Forms',
        'en-GB': 'Forms',
        fr: 'Formulaires',
        es: 'Formularios',
        de: 'Formulare',
        ru: 'Формы',
        ja: 'フォーム',
        ko: '양식',
        zh: '表单',
        ar: 'النماذج',
        it: 'Moduli',
        pt: 'Formulários',
        hi: 'फ़ॉर्म',
        tr: 'Formlar',
        pl: 'Formularze',
        id: 'Formulir',
        vi: 'Biểu mẫu',
        uk: 'Форми',
      }),
      notifications: t({
        en: 'Notifications',
        'en-GB': 'Notifications',
        fr: 'Notifications',
        es: 'Notificaciones',
        de: 'Benachrichtigungen',
        ru: 'Уведомления',
        ja: '通知',
        ko: '알림',
        zh: '通知',
        ar: 'الإشعارات',
        it: 'Notifiche',
        pt: 'Notificações',
        hi: 'सूचनाएं',
        tr: 'Bildirimler',
        pl: 'Powiadomienia',
        id: 'Notifikasi',
        vi: 'Thông báo',
        uk: 'Сповіщення',
      }),
      time: t({
        en: 'Time & Duration',
        'en-GB': 'Time & Duration',
        fr: 'Durée & Temps',
        es: 'Tiempo y Duración',
        de: 'Zeit & Dauer',
        ru: 'Время и длительность',
        ja: '時間と期間',
        ko: '시간 및 기간',
        zh: '时间与时长',
        ar: 'الوقت والمدة',
        it: 'Tempo e durata',
        pt: 'Tempo e Duração',
        hi: 'समय और अवधि',
        tr: 'Zaman ve Süre',
        pl: 'Czas i trwanie',
        id: 'Waktu & Durasi',
        vi: 'Thời gian & Thời lượng',
        uk: 'Час та тривалість',
      }),
      advanced: t({
        en: 'Advanced',
        'en-GB': 'Advanced',
        fr: 'Avancé',
        es: 'Avanzado',
        de: 'Erweitert',
        ru: 'Продвинутые',
        ja: '高度な設定',
        ko: '고급',
        zh: '高级',
        ar: 'متقدم',
        it: 'Avanzato',
        pt: 'Avançado',
        hi: 'उन्नत',
        tr: 'Gelişmiş',
        pl: 'Zaawansowane',
        id: 'Lanjutan',
        vi: 'Nâng cao',
        uk: 'Розширені',
      }),
      'real-world': t({
        en: 'Real World',
        'en-GB': 'Real World',
        fr: 'Cas réels',
        es: 'Mundo real',
        de: 'Praxisbeispiele',
        ru: 'Реальные примеры',
        ja: '実践例',
        ko: '실제 사례',
        zh: '真实场景',
        ar: 'أمثلة عملية',
        it: 'Casi reali',
        pt: 'Casos reais',
        hi: 'व्यावहारिक उदाहरण',
        tr: 'Gerçek Dünya',
        pl: 'Przykłady z życia',
        id: 'Dunia Nyata',
        vi: 'Thực tế',
        uk: 'Реальні приклади',
      }),
    },
    editor: {
      editorTitle: t({
        en: 'Editor',
        'en-GB': 'Editor',
        fr: 'Éditeur',
        es: 'Editor',
        de: 'Editor',
        ru: 'Редактор',
        ja: 'エディター',
        ko: '편집기',
        zh: '编辑器',
        ar: 'محرر',
        it: 'Editor',
        pt: 'Editor',
        hi: 'संपादक',
        tr: 'Düzenleyici',
        pl: 'Edytor',
        id: 'Editor',
        vi: 'Trình chỉnh sửa',
        uk: 'Редактор',
      }),
      templatesHeader: t({
        en: 'Templates',
        'en-GB': 'Templates',
        fr: 'Modèles',
        es: 'Plantillas',
        de: 'Vorlagen',
        ru: 'Шаблоны',
        ja: 'テンプレート',
        ko: '템플릿',
        zh: '模板',
        ar: 'القوالب',
        it: 'Modelli',
        pt: 'Modelos',
        hi: 'टेम्प्लेट',
        tr: 'Şablonlar',
        pl: 'Szablony',
        id: 'Templat',
        vi: 'Mẫu',
        uk: 'Шаблони',
      }),
      clearSearch: t({
        en: 'Clear search',
        'en-GB': 'Clear search',
        fr: 'Effacer la recherche',
        es: 'Limpiar búsqueda',
        de: 'Suche löschen',
        ru: 'Очистить поиск',
        ja: '検索をクリア',
        ko: '검색 지우기',
        zh: '清除搜索',
        ar: 'مسح البحث',
        it: 'Cancella ricerca',
        pt: 'Limpar pesquisa',
        hi: 'खोज साफ़ करें',
        tr: 'Aramayı temizle',
        pl: 'Wyczyść wyszukiwanie',
        id: 'Hapus pencarian',
        vi: 'Xóa tìm kiếm',
        uk: 'Очистити пошук',
      }),
      searchPlaceholder: t({
        en: 'Search templates (e.g. plural, arabic, ranking)...',
        'en-GB': 'Search templates (e.g. plural, arabic, ranking)...',
        fr: 'Rechercher des modèles (ex. pluriel, arabe, rang)...',
        es: 'Buscar plantillas (ej. plural, árabe, ranking)...',
        de: 'Vorlagen suchen (z. B. Plural, Arabisch, Ranking)...',
        ru: 'Поиск шаблонов (например, плюрал, арабский, ранг)...',
        ja: 'テンプレートを検索（例：複数形、アラビア語、ランキングなど）...',
        ko: '템플릿 검색 (예: 복수형, 아랍어, 순위)...',
        zh: '搜索模板（如复数、阿拉伯语、排名）...',
        ar: 'البحث في القوالب (مثل الجمع، العربية، الترتيب)...',
        it: 'Cerca modelli (es. plurale, arabo, classifica)...',
        pt: 'Pesquisar modelos (ex. plural, árabe, ranking)...',
        hi: 'टेम्प्लेट खोजें (उदा. बहुवचन, अरबी, रैंकिंग)...',
        tr: 'Şablonları ara (örn. çoğul, arapça, sıralama)...',
        pl: 'Szukaj szablonów (np. liczba mnoga, arabski, ranking)...',
        id: 'Cari templat (misalnya jamak, arab, peringkat)...',
        vi: 'Tìm kiếm mẫu (ví dụ: số nhiều, tiếng Ả Rập, thứ hạng)...',
        uk: 'Пошук шаблонів (наприклад, множина, арабська, рейтинг)...',
      }),
      noTemplatesFound: t({
        en: 'No templates match your search.',
        'en-GB': 'No templates match your search.',
        fr: 'Aucun modèle ne correspond à votre recherche.',
        es: 'Ninguna plantilla coincide con tu búsqueda.',
        de: 'Keine Vorlagen entsprechen Ihrer Suche.',
        ru: 'Шаблоны не найдены.',
        ja: '該当するテンプレートが見つかりません。',
        ko: '검색과 일치하는 템플릿이 없습니다.',
        zh: '未找到匹配的模板。',
        ar: 'لا توجد قوالب تطابق بحثك.',
        it: 'Nessun modello corrisponde alla ricerca.',
        pt: 'Nenhum modelo corresponde à sua pesquisa.',
        hi: 'आपकी खोज से कोई टेम्प्लेट मेल नहीं खाता।',
        tr: 'Aramanızla eşleşen şablon bulunamadı.',
        pl: 'Brak szablonów pasujących do wyszukiwania.',
        id: 'Tidak ada templat yang cocok dengan pencarian Anda.',
        vi: 'Không có mẫu nào khớp với tìm kiếm của bạn.',
        uk: 'Шаблонів за вашим запитом не знайдено.',
      }),
      validSyntax: t({
        en: 'Valid Syntax',
        'en-GB': 'Valid Syntax',
        fr: 'Syntaxe valide',
        es: 'Sintaxis válida',
        de: 'Gültige Syntax',
        ru: 'Корректный синтаксис',
        ja: '有効な構文',
        ko: '유효한 구문',
        zh: '语法有效',
        ar: 'بناء جملة صالح',
        it: 'Sintassi valida',
        pt: 'Sintaxe válida',
        hi: 'मान्य सिंटैक्स',
        tr: 'Geçerli Sözdizimi',
        pl: 'Prawidłowa składnia',
        id: 'Sintaks Valid',
        vi: 'Cú pháp hợp lệ',
        uk: 'Правильний синтаксис',
      }),
      syntaxIssue: t({
        en: 'Syntax Issue',
        'en-GB': 'Syntax Issue',
        fr: 'Problème de syntaxe',
        es: 'Error de sintaxis',
        de: 'Syntaxfehler',
        ru: 'Ошибка синтаксиса',
        ja: '構文エラー',
        ko: '구문 오류',
        zh: '语法错误',
        ar: 'خطأ في بناء الجملة',
        it: 'Problema di sintassi',
        pt: 'Problema de sintaxe',
        hi: 'सिंटैक्स त्रुटि',
        tr: 'Sözdizimi Hatası',
        pl: 'Problem ze składnią',
        id: 'Masalah Sintaks',
        vi: 'Lỗi cú pháp',
        uk: 'Помилка синтаксису',
      }),
      syntaxErrorTitle: t({
        en: 'Syntax Validation Error:',
        'en-GB': 'Syntax Validation Error:',
        fr: 'Erreur de validation de syntaxe :',
        es: 'Error de validación de sintaxis:',
        de: 'Syntaxvalidierungsfehler:',
        ru: 'Ошибка валидации синтаксиса:',
        ja: '構文検証エラー：',
        ko: '구문 유효성 검사 오류:',
        zh: '语法验证错误：',
        ar: 'خطأ في التحقق من بناء الجملة:',
        it: 'Errore di convalida della sintassi:',
        pt: 'Erro de validação de sintaxe:',
        hi: 'सिंटैक्स सत्यापन त्रुटि:',
        tr: 'Sözdizimi Doğrulama Hatası:',
        pl: 'Błąd walidacji składni:',
        id: 'Kesalahan Validasi Sintaks:',
        vi: 'Lỗi xác thực cú pháp:',
        uk: 'Помилка перевірки синтаксису:',
      }),
      undoLabel: t({
        en: 'Undo',
        'en-GB': 'Undo',
        fr: 'Annuler',
        es: 'Deshacer',
        de: 'Rückgängig',
        ru: 'Отменить',
        ja: '元に戻す',
        ko: '실행 취소',
        zh: '撤销',
        ar: 'تراجع',
        it: 'Annulla',
        pt: 'Desfazer',
        hi: 'पूर्ववत करें',
        tr: 'Geri al',
        pl: 'Cofnij',
        id: 'Urungkan',
        vi: 'Hoàn tác',
        uk: 'Скасувати',
      }),
      redoLabel: t({
        en: 'Redo',
        'en-GB': 'Redo',
        fr: 'Rétablir',
        es: 'Rehacer',
        de: 'Wiederholen',
        ru: 'Повторить',
        ja: 'やり直す',
        ko: '다시 실행',
        zh: '重做',
        ar: 'إعادة',
        it: 'Ripeti',
        pt: 'Refazer',
        hi: 'फिर से करें',
        tr: 'Yinele',
        pl: 'Ponów',
        id: 'Ulangi',
        vi: 'Làm lại',
        uk: 'Повторити',
      }),
      insertLabel: t({
        en: 'Insert',
        'en-GB': 'Insert',
        fr: 'Insérer',
        es: 'Insertar',
        de: 'Einfügen',
        ru: 'Вставить',
        ja: '挿入',
        ko: '삽입',
        zh: '插入',
        ar: 'إدراج',
        it: 'Inserisci',
        pt: 'Inserir',
        hi: 'सम्मिलित करें',
        tr: 'Ekle',
        pl: 'Wstaw',
        id: 'Sisipkan',
        vi: 'Chèn',
        uk: 'Вставити',
      }),
      quickInsertSnippets: t({
        en: 'Quick Insert Snippets',
        'en-GB': 'Quick Insert Snippets',
        fr: 'Extraits à insertion rapide',
        es: 'Fragmentos de inserción rápida',
        de: 'Schnell-Einfüge-Snippets',
        ru: 'Быстрые фрагменты',
        ja: 'クイック挿入スニペット',
        ko: '빠른 삽입 스니펫',
        zh: '快捷插入代码片段',
        ar: 'مقتطفات الإدراج السريع',
        it: 'Snippet di inserimento rapido',
        pt: 'Trechos de inserção rápida',
        hi: 'त्वरित सम्मिलित स्निपेट',
        tr: 'Hızlı Ekleme Kod Parçacıkları',
        pl: 'Szybkie wstawianie fragmentów',
        id: 'Cuplikan Penyisipan Cepat',
        vi: 'Đoạn mã chèn nhanh',
        uk: 'Швидкі фрагменти коду',
      }),
      copyString: t({
        en: 'Copy string',
        'en-GB': 'Copy string',
        fr: 'Copier la chaîne',
        es: 'Copiar cadena',
        de: 'Zeichenfolge kopieren',
        ru: 'Скопировать строку',
        ja: '文字列をコピー',
        ko: '문자열 복사',
        zh: '复制字符串',
        ar: 'نسخ النص',
        it: 'Copia stringa',
        pt: 'Copiar string',
        hi: 'स्ट्रिंग कॉपी करें',
        tr: 'Dizeyi kopyala',
        pl: 'Kopiuj ciąg',
        id: 'Salin string',
        vi: 'Sao chép chuỗi',
        uk: 'Копіювати рядок',
      }),
      clearText: t({
        en: 'Clear text',
        'en-GB': 'Clear text',
        fr: 'Effacer le texte',
        es: 'Limpiar texto',
        de: 'Text löschen',
        ru: 'Очистить текст',
        ja: 'テキストをクリア',
        ko: '텍스트 지우기',
        zh: '清空文本',
        ar: 'مسح النص',
        it: 'Cancella testo',
        pt: 'Limpar texto',
        hi: 'टेक्स्ट साफ़ करें',
        tr: 'Metni temizle',
        pl: 'Wyczyść tekst',
        id: 'Hapus teks',
        vi: 'Xóa văn bản',
        uk: 'Очистити текст',
      }),
      editorPlaceholder: t({
        en: 'Type or paste your message format string here...',
        'en-GB': 'Type or paste your message format string here...',
        fr: 'Saisissez ou collez votre chaîne de formatage ici...',
        es: 'Escribe o pega tu cadena de formato aquí...',
        de: 'Geben Sie hier Ihre Formatzeichenfolge ein oder fügen Sie sie ein...',
        ru: 'Введите или вставьте вашу строку формата здесь...',
        ja: 'メッセージ形式の文字列をここに入力または貼り付け...',
        ko: '여기에 메시지 형식 문자열을 입력하거나 붙여넣으세요...',
        zh: '在此输入或粘贴您的消息格式字符串...',
        ar: 'اكتب أو الصق نص التنسيق هنا...',
        it: 'Digita o incolla qui la tua stringa di formato...',
        pt: 'Digite ou cole sua string de formato aqui...',
        hi: 'यहाँ अपना संदेश प्रारूप स्ट्रिंग टाइप करें या चिपकाएँ...',
        tr: 'Mesaj formatı dizenizi buraya yazın veya yapıştırın...',
        pl: 'Wpisz lub wklej tutaj ciąg formatu wiadomości...',
        id: 'Ketik atau tempel string format pesan Anda di sini...',
        vi: 'Nhập hoặc dán chuỗi định dạng tin nhắn của bạn vào đây...',
        uk: 'Введіть або вставте рядок формату повідомлення тут...',
      }),
      characters: t({
        en: 'characters',
        'en-GB': 'characters',
        fr: 'caractères',
        es: 'caracteres',
        de: 'Zeichen',
        ru: 'символов',
        ja: '文字',
        ko: '자',
        zh: '字符',
        ar: 'أحرف',
        it: 'caratteri',
        pt: 'caracteres',
        hi: 'वर्ण',
        tr: 'karakter',
        pl: 'znaków',
        id: 'karakter',
        vi: 'ký tự',
        uk: 'символів',
      }),
      lines: t({
        en: 'lines',
        'en-GB': 'lines',
        fr: 'lignes',
        es: 'líneas',
        de: 'Zeilen',
        ru: 'строк',
        ja: '行',
        ko: '줄',
        zh: '行',
        ar: 'أسطر',
        it: 'righe',
        pt: 'linhas',
        hi: 'पंक्तियाँ',
        tr: 'satır',
        pl: 'wierszy',
        id: 'baris',
        vi: 'dòng',
        uk: 'рядків',
      }),
      testVariablesTitle: t({
        en: 'Test Variables & Live Preview',
        'en-GB': 'Test Variables & Live Preview',
        fr: 'Variables de test & Aperçu en direct',
        es: 'Variables de prueba y vista previa en vivo',
        de: 'Testvariablen & Live-Vorschau',
        ru: 'Тестовые переменные и предпросмотр',
        ja: 'テスト変数とライブプレビュー',
        ko: '테스트 변수 및 실시간 미리보기',
        zh: '测试变量与实时预览',
        ar: 'متغيرات الاختبار والمعاينة المباشرة',
        it: 'Variabili di test e anteprima dal vivo',
        pt: 'Variáveis de teste e visualização ao vivo',
        hi: 'परीक्षण चर और लाइव पूर्वावलोकन',
        tr: 'Test Değişkenleri ve Canlı Önizleme',
        pl: 'Zmienne testowe i podgląd na żywo',
        id: 'Variabel Uji & Pratinjau Langsung',
        vi: 'Biến kiểm tra & Xem trước trực tiếp',
        uk: 'Тестові змінні та попередній перегляд',
      }),
      testVariablesDescription: t({
        en: 'Adjust variables and switch languages to verify CLDR plural rules',
        'en-GB':
          'Adjust variables and switch languages to verify CLDR plural rules',
        fr: 'Modifiez les variables et changez de langue pour vérifier les règles CLDR',
        es: 'Ajusta variables y cambia de idioma para verificar reglas CLDR',
        de: 'Passen Sie Variablen an und wechseln Sie Sprachen, um CLDR-Regeln zu prüfen',
        ru: 'Изменяйте переменные и переключайте языки для проверки правил CLDR',
        ja: '変数を調整し言語を切り替えてCLDR複数形ルールを確認します',
        ko: '변수를 조정하고 언어를 전환하여 CLDR 복수형 규칙을 확인하세요',
        zh: '调整变量并切换语言以验证 CLDR 复数规则',
        ar: 'قم بضبط المتغيرات وتبديل اللغات للتحقق من قواعد جمع CLDR',
        it: 'Regola le variabili e cambia lingua per verificare le regole CLDR',
        pt: 'Ajuste variáveis e mude de idioma para verificar regras CLDR',
        hi: 'CLDR बहुवचन नियमों को सत्यापित करने के लिए चर समायोजित करें और भाषा बदलें',
        tr: 'CLDR çoğul kurallarını doğrulamak için değişkenleri ayarlayın ve dilleri değiştirin',
        pl: 'Dostosuj zmienne i zmień język, aby zweryfikować reguły CLDR',
        id: 'Sesuaikan variabel dan ganti bahasa untuk memverifikasi aturan CLDR',
        vi: 'Điều chỉnh các biến và chuyển đổi ngôn ngữ để xác minh quy tắc CLDR',
        uk: 'Налаштуйте змінні та змініть мову для перевірки правил CLDR',
      }),
      localeLabel: t({
        en: 'Locale:',
        'en-GB': 'Locale:',
        fr: 'Langue :',
        es: 'Idioma:',
        de: 'Sprache:',
        ru: 'Язык:',
        ja: '言語:',
        ko: '로케일:',
        zh: '语言环境：',
        ar: 'اللغة:',
        it: 'Lingua:',
        pt: 'Idioma:',
        hi: 'भाषा:',
        tr: 'Yerel Ayar:',
        pl: 'Język:',
        id: 'Lokal:',
        vi: 'Ngôn ngữ:',
        uk: 'Мова:',
      }),
      noVariablesDetected: t({
        en: 'No variables detected in message string.',
        'en-GB': 'No variables detected in message string.',
        fr: 'Aucune variable détectée dans la chaîne.',
        es: 'No se detectaron variables en la cadena.',
        de: 'Keine Variablen in der Zeichenfolge erkannt.',
        ru: 'В строке не обнаружено переменных.',
        ja: 'メッセージ文字列に変数は検出されませんでした。',
        ko: '메시지 문자열에서 변수가 감지되지 않았습니다.',
        zh: '在消息字符串中未检测到变量。',
        ar: 'لم يتم اكتشاف أي متغيرات في السلسلة.',
        it: 'Nessuna variabile rilevata nella stringa.',
        pt: 'Nenhuma variável detectada na string.',
        hi: 'संदेश स्ट्रिंग में कोई चर नहीं मिला।',
        tr: 'Mesaj dizisinde değişken algılanmadı.',
        pl: 'Nie wykryto zmiennych w ciągu wiadomości.',
        id: 'Tidak ada variabel yang terdeteksi dalam pesan.',
        vi: 'Không có biến nào được phát hiện trong chuỗi tin nhắn.',
        uk: 'У рядку повідомлення не виявлено змінних.',
      }),
      renderedOutput: t({
        en: 'Rendered Output',
        'en-GB': 'Rendered Output',
        fr: 'Résultat généré',
        es: 'Resultado generado',
        de: 'Gerenderte Ausgabe',
        ru: 'Результат',
        ja: '出力結果',
        ko: '렌더링된 출력',
        zh: '渲染输出',
        ar: 'النتيجة المخرجة',
        it: 'Risultato generato',
        pt: 'Resultado gerado',
        hi: 'रेंडर किया गया आउटपुट',
        tr: 'Oluşturulan Çıktı',
        pl: 'Wygenerowany wynik',
        id: 'Hasil Render',
        vi: 'Kết quả hiển thị',
        uk: 'Отриманий результат',
      }),
      enterMessagePrompt: t({
        en: 'Enter a message format string above to preview output.',
        'en-GB': 'Enter a message format string above to preview output.',
        fr: 'Saisissez une chaîne de formatage ci-dessus pour prévisualiser le résultat.',
        es: 'Introduce una cadena de formato arriba para previsualizar el resultado.',
        de: 'Geben Sie oben eine Formatzeichenfolge ein, um die Ausgabe anzuzeigen.',
        ru: 'Введите строку формата выше для предварительного просмотра.',
        ja: 'プレビューを表示するには上部にフォーマット文字列を入力してください。',
        ko: '출력을 미리 보려면 위에 메시지 형식 문자열을 입력하세요.',
        zh: '在上方输入消息格式字符串以预览输出。',
        ar: 'أدخل نص التنسيق أعلاه لمعاينة النتيجة.',
        it: 'Inserisci una stringa di formato sopra per visualizzare l’anteprima.',
        pt: 'Insira uma string de formato acima para pré-visualizar a saída.',
        hi: 'आउटपुट का पूर्वावलोकन करने के लिए ऊपर एक संदेश प्रारूप स्ट्रिंग दर्ज करें।',
        tr: 'Çıktıyı önizlemek için yukarıya bir mesaj formatı dizesi girin.',
        pl: 'Wpisz ciąg formatu wiadomości powyżej, aby zobaczyć podgląd.',
        id: 'Masukkan string format pesan di atas untuk melihat pratinjau.',
        vi: 'Nhập chuỗi định dạng tin nhắn ở trên để xem trước kết quả.',
        uk: 'Введіть рядок формату повідомлення вище для попереднього перегляду.',
      }),
      exportTitle: t({
        en: 'Export to Intlayer Type-Safe Declaration',
        'en-GB': 'Export to Intlayer Type-Safe Declaration',
        fr: 'Exporter vers une déclaration typée Intlayer',
        es: 'Exportar a declaración con tipos seguros de Intlayer',
        de: 'In typsichere Intlayer-Deklaration exportieren',
        ru: 'Экспорт в типизированную декларацию Intlayer',
        ja: 'Intlayer の型安全な宣言にエクスポート',
        ko: 'Intlayer 타입 안전 선언으로 내보내기',
        zh: '导出为 Intlayer 类型安全声明',
        ar: 'التصدير إلى تصريح Intlayer الآمن من حيث الأنواع',
        it: 'Esporta nella dichiarazione sicura per i tipi di Intlayer',
        pt: 'Exportar para declaração com segurança de tipos do Intlayer',
        hi: 'Intlayer टाइप-सुरक्षित घोषणा में निर्यात करें',
        tr: 'Intlayer Tür Güvenli Bildirimine Aktar',
        pl: 'Eksportuj do deklaracji Intlayer z kontrolą typów',
        id: 'Ekspor ke Deklarasi Tipe Aman Intlayer',
        vi: 'Xuất sang khai báo an toàn kiểu của Intlayer',
        uk: 'Експортувати в типізовану декларацію Intlayer',
      }),
      exportDescription: t({
        en: 'Intlayer validates translations at compile-time with full TypeScript autocomplete.',
        'en-GB':
          'Intlayer validates translations at compile-time with full TypeScript autocomplete.',
        fr: 'Intlayer valide les traductions à la compilation avec autocomplétion TypeScript complète.',
        es: 'Intlayer valida las traducciones en compilación con autocompletado TypeScript completo.',
        de: 'Intlayer validiert Übersetzungen zur Kompilierzeit mit vollständiger TypeScript-Autovervollständigung.',
        ru: 'Intlayer проверяет переводы во время компиляции с полной автоподстановкой TypeScript.',
        ja: 'Intlayerは完全なTypeScript自動補完によりコンパイル時に翻訳を検証します。',
        ko: 'Intlayer는 완벽한 TypeScript 자동 완성을 통해 컴파일 타임에 번역을 검증합니다.',
        zh: 'Intlayer 在编译时通过完整的 TypeScript 自动补全来验证翻译。',
        ar: 'يتحقق Intlayer من صحة الترجمات في وقت التجميع مع الإكمال التلقائي الكامل في TypeScript.',
        it: 'Intlayer convalida le traduzioni in fase di compilazione con completamento automatico TypeScript completo.',
        pt: 'O Intlayer valida traduções em tempo de compilação com autocompletar TypeScript completo.',
        hi: 'Intlayer पूर्ण TypeScript स्वतः पूर्णता के साथ संकलन समय पर अनुवादों को मान्य करता है।',
        tr: 'Intlayer, tam TypeScript otomatik tamamlama ile derleme zamanında çevirileri doğrular.',
        pl: 'Intlayer sprawdza poprawność tłumaczeń w czasie kompilacji z pełnym autouzupełnianiem TypeScript.',
        id: 'Intlayer memvalidasi terjemahan saat kompilasi dengan pelengkapan otomatis TypeScript lengkap.',
        vi: 'Intlayer xác thực bản dịch tại thời điểm biên dịch với tính năng tự động hoàn thành TypeScript đầy đủ.',
        uk: 'Intlayer перевіряє переклади під час компіляції з повним автодоповненням TypeScript.',
      }),
      copyIntlayerCode: t({
        en: 'Copy Intlayer Code',
        'en-GB': 'Copy Intlayer Code',
        fr: 'Copier le code Intlayer',
        es: 'Copiar código Intlayer',
        de: 'Intlayer-Code kopieren',
        ru: 'Скопировать код Intlayer',
        ja: 'Intlayer コードをコピー',
        ko: 'Intlayer 코드 복사',
        zh: '复制 Intlayer 代码',
        ar: 'نسخ كود Intlayer',
        it: 'Copia codice Intlayer',
        pt: 'Copiar código Intlayer',
        hi: 'Intlayer कोड कॉपी करें',
        tr: 'Intlayer Kodunu Kopyala',
        pl: 'Kopiuj kod Intlayer',
        id: 'Salin Kode Intlayer',
        vi: 'Sao chép mã Intlayer',
        uk: 'Копіювати код Intlayer',
      }),
    },
    cheatSheet: {
      subtitle: t({
        en: "Quick syntax rules and how each pattern maps to Intlayer's type-safe declarations",
        'en-GB':
          "Quick syntax rules and how each pattern maps to Intlayer's type-safe declarations",
        fr: 'Règles de syntaxe rapides et équivalences typées avec Intlayer',
        es: 'Reglas de sintaxis rápidas y cómo cada patrón se asigna a Intlayer',
        de: 'Schnelle Syntaxregeln und wie jedes Muster auf typsichere Intlayer-Deklarationen abbildet',
        ru: 'Быстрые правила синтаксиса и их соответствие декларациям Intlayer',
        ja: '構文ルールとIntlayerの型安全な宣言へのマッピング一覧',
        ko: '빠른 구문 규칙 및 각 패턴이 Intlayer의 타입 안전 선언에 매핑되는 방법',
        zh: '快速语法规则以及每个模式如何映射到 Intlayer 的类型安全声明',
        ar: 'قواعد بناء الجملة السريعة وكيفية تعيين كل نمط لتصريحات Intlayer',
        it: 'Regole sintattiche rapide e corrispondenze tipizzate con Intlayer',
        pt: 'Regras de sintaxe rápidas e como cada padrão mapeia para o Intlayer',
        hi: 'त्वरित सिंटैक्स नियम और प्रत्येक पैटर्न Intlayer घोषणाओं में कैसे मैप होता है',
        tr: 'Hızlı sözdizimi kuralları ve her kalıbın Intlayer bildirimlerine nasıl eşlendiği',
        pl: 'Szybkie reguły składni i mapowanie wzorców na deklaracje Intlayer',
        id: 'Aturan sintaks cepat dan pemetaan pola ke deklarasi Intlayer',
        vi: 'Quy tắc cú pháp nhanh và cách mỗi mẫu ánh xạ tới khai báo Intlayer',
        uk: 'Швидкі правила синтаксису та відповідність деклараціям Intlayer',
      }),
      featureHeader: t({
        en: 'Feature',
        'en-GB': 'Feature',
        fr: 'Fonctionnalité',
        es: 'Característica',
        de: 'Funktion',
        ru: 'Функция',
        ja: '機能',
        ko: '기능',
        zh: '功能',
        ar: 'الميزة',
        it: 'Funzionalità',
        pt: 'Recurso',
        hi: 'सुविधा',
        tr: 'Özellik',
        pl: 'Funkcja',
        id: 'Fitur',
        vi: 'Tính năng',
        uk: 'Функція',
      }),
      syntaxHeader: t({
        en: 'Syntax',
        'en-GB': 'Syntax',
        fr: 'Syntaxe',
        es: 'Sintaxis',
        de: 'Syntax',
        ru: 'Синтаксис',
        ja: '構文',
        ko: '구문',
        zh: '语法',
        ar: 'بناء الجملة',
        it: 'Sintassi',
        pt: 'Sintaxe',
        hi: 'सिंटैक्स',
        tr: 'Sözdizimi',
        pl: 'Składnia',
        id: 'Sintaks',
        vi: 'Cú pháp',
        uk: 'Синтаксис',
      }),
      exampleHeader: t({
        en: 'Example',
        'en-GB': 'Example',
        fr: 'Exemple',
        es: 'Ejemplo',
        de: 'Beispiel',
        ru: 'Пример',
        ja: '例',
        ko: '예시',
        zh: '示例',
        ar: 'مثال',
        it: 'Esempio',
        pt: 'Exemplo',
        hi: 'उदाहरण',
        tr: 'Örnek',
        pl: 'Przykład',
        id: 'Contoh',
        vi: 'Ví dụ',
        uk: 'Приклад',
      }),
      notesHeader: t({
        en: 'Notes',
        'en-GB': 'Notes',
        fr: 'Remarques',
        es: 'Notas',
        de: 'Hinweise',
        ru: 'Примечания',
        ja: '備考',
        ko: '참고',
        zh: '备注',
        ar: 'ملاحظات',
        it: 'Note',
        pt: 'Notas',
        hi: 'टिप्पणियाँ',
        tr: 'Notlar',
        pl: 'Uwagi',
        id: 'Catatan',
        vi: 'Ghi chú',
        uk: 'Примітки',
      }),
      intlayerEquivalentHeader: t({
        en: 'Intlayer Equivalent',
        'en-GB': 'Intlayer Equivalent',
        fr: 'Équivalent Intlayer',
        es: 'Equivalente en Intlayer',
        de: 'Intlayer-Äquivalent',
        ru: 'Эквивалент в Intlayer',
        ja: 'Intlayer での同等表現',
        ko: 'Intlayer 동등 표현',
        zh: 'Intlayer 等效写法',
        ar: 'المكافئ في Intlayer',
        it: 'Equivalente Intlayer',
        pt: 'Equivalente no Intlayer',
        hi: 'Intlayer समकक्ष',
        tr: 'Intlayer Eşdeğeri',
        pl: 'Odpowiednik w Intlayer',
        id: 'Setara Intlayer',
        vi: 'Tương đương trong Intlayer',
        uk: 'Еквівалент в Intlayer',
      }),
      compilerTip: t({
        en: 'Intlayer compiler-driven architecture replaces complex runtime message parsing with compile-time type-safety and automated extraction.',
        'en-GB':
          'Intlayer compiler-driven architecture replaces complex runtime message parsing with compile-time type-safety and automated extraction.',
        fr: 'L’architecture pilotée par compilateur d’Intlayer remplace l’analyse complexe au runtime par la sécurité des types à la compilation.',
        es: 'La arquitectura basada en compilador de Intlayer reemplaza el análisis complejo en tiempo de ejecución con seguridad de tipos en compilación.',
        de: 'Die compilergesteuerte Architektur von Intlayer ersetzt komplexes Laufzeit-Parsing durch Typsicherheit zur Kompilierzeit.',
        ru: 'Архитектура Intlayer на основе компилятора заменяет сложный парсинг во время выполнения статической проверкой типов при компиляции.',
        ja: 'Intlayerのコンパイラ駆動アーキテクチャは、複雑な実行時パースをコンパイル時の型安全性と自動抽出に置き換えます。',
        ko: 'Intlayer의 컴파일러 기반 아키텍처는 복잡한 런타임 구문 분석을 컴파일 타임 타입 안전성과 자동 추출로 대체합니다.',
        zh: 'Intlayer 基于编译器的架构用编译时类型安全和自动化提取取代了复杂的运行时消息解析。',
        ar: 'تستبدل بنية Intlayer المدفوعة بالمترجم التحليل المعقد في وقت التشغيل بأمان الأنواع في وقت التجميع والاستخراج الآلي.',
        it: 'L’architettura basata su compilatore di Intlayer sostituisce il parsing a runtime con la sicurezza dei tipi in fase di compilazione.',
        pt: 'A arquitetura orientada por compilador do Intlayer substitui a análise em tempo de execução pela segurança de tipos na compilação.',
        hi: 'Intlayer की कंपाइलर-चालित वास्तुकला जटिल रनटाइम पार्सिंग को कंपाइल-टाइम टाइप सुरक्षा के साथ बदल देती है।',
        tr: 'Intlayer derleyici odaklı mimarisi, karmaşık çalışma zamanı ayrıştırmasını derleme zamanı tür güvenliği ile değiştirir.',
        pl: 'Architektura Intlayer oparta na kompilatorze zastępuje złożone parsowanie w czasie wykonywania bezpieczeństwem typów w czasie kompilacji.',
        id: 'Arsitektur berbasis kompilator Intlayer menggantikan penguraian pesan runtime yang rumit dengan keamanan tipe waktu kompilasi.',
        vi: 'Kiến trúc dựa trên trình biên dịch của Intlayer thay thế việc phân tích cú pháp trong thời gian chạy bằng tính an toàn kiểu tại thời điểm biên dịch.',
        uk: 'Архітектура Intlayer на основі компілятора замінює складний парсинг під час виконання перевіркою типів під час компіляції.',
      }),
    },
    cta: {
      title: t({
        en: 'Never Worry About Complex Syntax Again',
        'en-GB': 'Never Worry About Complex Syntax Again',
        fr: 'Ne vous souciez plus jamais des syntaxes complexes',
        es: 'Olvídate de las sintaxis complejas para siempre',
        de: 'Machen Sie sich nie wieder Gedanken über komplexe Syntax',
        ru: 'Забудьте о сложных синтаксических ошибках навсегда',
        ja: '複雑な構文に悩まされることはもうありません',
        ko: '복잡한 구문에 대해 더 이상 걱정하지 마세요',
        zh: '无需再为复杂的语法烦恼',
        ar: 'لا تقلق أبدًا بشأن بناء الجمل المعقدة مرة أخرى',
        it: 'Non preoccuparti mai più di sintassi complesse',
        pt: 'Nunca mais se preocupe com sintaxes complexas',
        hi: 'जटिल सिंटैक्स के बारे में कभी चिंता न करें',
        tr: 'Artık Karmaşık Sözdizimi Konusunda Endişelenmeyin',
        pl: 'Nigdy więcej nie martw się skomplikowaną składnią',
        id: 'Tidak Perlu Khawatir Lagi tentang Sintaks yang Rumit',
        vi: 'Không còn phải lo lắng về cú pháp phức tạp nữa',
        uk: 'Більше ніколи не турбуйтеся про складний синтаксис',
      }),
      description: t({
        en: 'Intlayer turns internationalization into a joyful developer experience with compile-time type-safety, automatic component extraction, and seamless CMS integration.',
        'en-GB':
          'Intlayer turns internationalization into a joyful developer experience with compile-time type-safety, automatic component extraction, and seamless CMS integration.',
        fr: 'Intlayer transforme l’internationalisation en une expérience de développement fluide avec sécurité des types à la compilation, extraction automatique et CMS intégré.',
        es: 'Intlayer transforma la internacionalización en una experiencia fluida con seguridad de tipos en compilación, extracción automática y CMS integrado.',
        de: 'Intlayer verwandelt die Internationalisierung mit Typsicherheit zur Kompilierzeit, automatischer Komponentenextraktion und nahtloser CMS-Integration in ein Vergnügen.',
        ru: 'Intlayer превращает интернационализацию в удобный процесс благодаря статической типизации во время компиляции, авто-извлечению и встроенной CMS.',
        ja: 'Intlayerは、コンパイル時の型安全性、自動コンポーネント抽出、シームレスなCMS統合により、国際化を快適な開発体験に変えます。',
        ko: 'Intlayer는 컴파일 타임 타입 안정성, 자동 컴포넌트 추출 및 완벽한 CMS 통합을 통해 국제화를 즐거운 개발 경험으로 바꿉니다.',
        zh: 'Intlayer 通过编译时类型安全、自动组件提取和无缝 CMS 集成，让国际化成为愉悦的开发体验。',
        ar: 'يحوّل Intlayer التدويل إلى تجربة ممتعة للمطورين من خلال أمان الأنواع وقت الترجمة والاستخراج التلقائي للمكونات والتكامل السلس مع CMS.',
        it: 'Intlayer trasforma l’internazionalizzazione in un’esperienza di sviluppo piacevole con sicurezza dei tipi in fase di compilazione, estrazione automatica e CMS integrato.',
        pt: 'O Intlayer transforma a internacionalização em uma experiência agradável com segurança de tipos em tempo de compilação, extração automática e CMS integrado.',
        hi: 'Intlayer कंपाइल-टाइम टाइप सुरक्षा, स्वचालित घटक निष्कर्षण और सहज CMS एकीकरण के साथ अंतर्राष्ट्रीयकरण को एक सुखद डेवलपर अनुभव बनाता है।',
        tr: 'Intlayer, derleme zamanı tür güvenliği, otomatik bileşen çıkarma ve sorunsuz CMS entegrasyonu ile yerelleştirmeyi keyifli bir geliştirici deneyimine dönüştürür.',
        pl: 'Intlayer zmienia internacjonalizację w przyjemne doświadczenie programistyczne dzięki bezpieczeństwu typów w czasie kompilacji, automatycznej ekstrakcji i integracji z CMS.',
        id: 'Intlayer mengubah internasionalisasi menjadi pengalaman pengembang yang menyenangkan dengan keamanan tipe waktu kompilasi, ekstraksi komponen otomatis, dan integrasi CMS yang mulus.',
        vi: 'Intlayer biến quốc tế hóa thành trải nghiệm phát triển thú vị với tính an toàn kiểu tại thời điểm biên dịch, tự động trích xuất thành phần và tích hợp CMS liền mạch.',
        uk: 'Intlayer перетворює інтернаціоналізацію на приємний досвід розробки завдяки типізації під час компіляції, автоматичному вилученню та інтеграції з CMS.',
      }),
      button: t({
        en: 'Explore Intlayer Documentation',
        'en-GB': 'Explore Intlayer Documentation',
        fr: 'Découvrir la documentation Intlayer',
        es: 'Explorar la documentación de Intlayer',
        de: 'Intlayer-Dokumentation erkunden',
        ru: 'Изучить документацию Intlayer',
        ja: 'Intlayer のドキュメントを見る',
        ko: 'Intlayer 문서 탐색',
        zh: '探索 Intlayer 文档',
        ar: 'استكشف وثائق Intlayer',
        it: 'Esplora la documentazione di Intlayer',
        pt: 'Explorar a documentação do Intlayer',
        hi: 'Intlayer दस्तावेज़ देखें',
        tr: 'Intlayer Belgelerini Keşfedin',
        pl: 'Odkryj dokumentację Intlayer',
        id: 'Jelajahi Dokumentasi Intlayer',
        vi: 'Khám phá tài liệu Intlayer',
        uk: 'Ознайомитися з документацією Intlayer',
      }),
    },
  },
} satisfies Dictionary;

export default messageFormatterContent;
