import { type Dictionary, t } from 'intlayer';

const demoSectionContent = {
  key: 'demo-section',
  content: {
    title: t({
      ar: 'جرب العرض التوضيحي المباشر',
      de: 'Versuchen Sie die Live-Demo',
      en: 'Try the live demo',
      'en-GB': 'Try the live demo',
      es: 'Prueba la demo en vivo',
      fr: 'Essayez la démo en direct',
      hi: 'लाइव डेमो का प्रयास करें',
      it: 'Prova la demo dal vivo',
      ja: 'ライブデモを試す',
      ko: '라이브 데모를 사용해 보세요',
      pt: 'Experimente a demonstração ao vivo',
      ru: 'Попробуйте демонстрацию в реальном времени',
      tr: 'Canlı demoyu deneyin',
      zh: '试用实时演示',
      pl: 'Wypróbuj demo na żywo',
      id: 'Coba demo langsung',
      vi: 'Thử bản demo trực tiếp',
      uk: 'Спробуйте живу демонстрацію',
    }),
    demoSwitchSelector: {
      nextjs: t({
        en: 'Next.js',
        'en-GB': 'Next.js',
        fr: 'Next.js',
        es: 'Next.js',
        de: 'Next.js',
        ja: 'Next.js',
        ko: 'Next.js',
        zh: 'Next.js',
        it: 'Next.js',
        pt: 'Next.js',
        hi: 'Next.js',
        ar: 'Next.js',
        ru: 'Next.js',
        tr: 'Next.js',
        pl: 'Next.js',
        id: 'Next.js',
        vi: 'Next.js',
        uk: 'Next.js',
      }),
      tanstack: t({
        en: 'Tanstack Start',
        'en-GB': 'Tanstack Start',
        fr: 'Tanstack Start',
        es: 'Tanstack Start',
        de: 'Tanstack Start',
        ja: 'Tanstack Start',
        ko: 'Tanstack Start',
        zh: 'Tanstack Start',
        it: 'Tanstack Start',
        pt: 'Tanstack Start',
        hi: 'Tanstack Start',
        ar: 'Tanstack Start',
        ru: 'Tanstack Start',
        tr: 'Tanstack Start',
        pl: 'Tanstack Start',
        id: 'Tanstack Start',
        vi: 'Tanstack Start',
        uk: 'Tanstack Start',
      }),
      astro: t({
        en: 'Astro',
        'en-GB': 'Astro',
        fr: 'Astro',
        es: 'Astro',
        de: 'Astro',
        ja: 'Astro',
        ko: 'Astro',
        zh: 'Astro',
        it: 'Astro',
        pt: 'Astro',
        hi: 'Astro',
        ar: 'Astro',
        ru: 'Astro',
        tr: 'Astro',
        pl: 'Astro',
        id: 'Astro',
        vi: 'Astro',
        uk: 'Astro',
      }),
      nuxt: t({
        en: 'Nuxt',
        'en-GB': 'Nuxt',
        fr: 'Nuxt',
        es: 'Nuxt',
        de: 'Nuxt',
        ja: 'Nuxt',
        ko: 'Nuxt',
        zh: 'Nuxt',
        it: 'Nuxt',
        pt: 'Nuxt',
        hi: 'Nuxt',
        ar: 'Nuxt',
        ru: 'Nuxt',
        tr: 'Nuxt',
        pl: 'Nuxt',
        id: 'Nuxt',
        vi: 'Nuxt',
        uk: 'Nuxt',
      }),
      svelte: t({
        en: 'Svelte',
        'en-GB': 'Svelte',
        fr: 'Svelte',
        es: 'Svelte',
        de: 'Svelte',
        ja: 'Svelte',
        ko: 'Svelte',
        zh: 'Svelte',
        it: 'Svelte',
        pt: 'Svelte',
        hi: 'Svelte',
        ar: 'Svelte',
        ru: 'Svelte',
        tr: 'Svelte',
        pl: 'Svelte',
        id: 'Svelte',
        vi: 'Svelte',
        uk: 'Svelte',
      }),
    },
  },
  title: 'Demo section',
  description:
    'Content related to the demo section of the landing page, including titles and options to try the demo via Next.js, Tanstack, Astro, Nuxt or Svelte templates.',
  tags: ['landing page', 'demo section'],
} satisfies Dictionary;

export default demoSectionContent;
