import { type Dictionary, t } from 'intlayer';

const comingSoonContent = {
  key: 'cms-landing-coming-soon',
  title: 'CMS landing page coming soon section content',
  description:
    'Content declarations for the CMS landing page coming soon section.',
  content: {
    comingSoonTitle: t({
      en: 'Coming soon',
      'en-GB': 'Coming soon',
      fr: 'Bientôt disponible',
      es: 'Próximamente',
      de: 'Demnächst verfügbar',
      ru: 'Скоро',
      ja: '近日公開',
      ko: '곧 출시',
      zh: '即将推出',
      ar: 'قريباً',
      it: 'Prossimamente',
      pt: 'Em breve',
      hi: 'जल्द ही आ रहा है',
      tr: 'Yakında',
      pl: 'Wkrótce',
      id: 'Segera hadir',
      vi: 'Sắp ra mắt',
    }),
    comingSoonFeatures: [
      {
        id: 'auto-translate',
        icon: 'sparkles',
        title: t({
          en: 'AI auto-translation',
          'en-GB': 'AI auto-translation',
          fr: 'Traduction automatique IA',
          es: 'Traducción automática con IA',
          de: 'KI-Auto-Übersetzung',
          ru: 'Автоматический перевод с ИИ',
          ja: 'AI自動翻訳',
          ko: 'AI 자동 번역',
          zh: 'AI自动翻译',
          ar: 'ترجمة تلقائية بالذكاء الاصطناعي',
          it: 'Traduzione automatica con IA',
          pt: 'Tradução automática com IA',
          hi: 'AI स्वचालित अनुवाद',
          tr: 'AI otomatik çeviri',
          pl: 'Automatyczne tłumaczenie AI',
          id: 'Terjemahan otomatis AI',
          vi: 'Dịch tự động bằng AI',
        }),
        description: t({
          en: 'Push content in one language, get AI-powered translations instantly, like Reddit does with posts.',
          'en-GB':
            'Push content in one language, get AI-powered translations instantly, like Reddit does with posts.',
          fr: "Poussez du contenu dans une langue, obtenez des traductions alimentées par l'IA instantanément, comme Reddit le fait avec ses posts.",
          es: 'Sube contenido en un idioma, obtén traducciones con IA al instante, como Reddit hace con sus publicaciones.',
          de: 'Content in einer Sprache pushen, sofort KI-gestützte Übersetzungen erhalten, wie Reddit es mit Posts macht.',
          ru: 'Отправьте контент на одном языке, мгновенно получите переводы на основе ИИ, как Reddit делает с постами.',
          ja: '1つの言語でコンテンツをプッシュすると、Redditが投稿で行うように、AIによる翻訳を即座に取得できます。',
          ko: '한 언어로 콘텐츠를 푸시하면 Reddit이 게시물에서 하는 것처럼 AI 기반 번역을 즉시 받을 수 있습니다.',
          zh: '用一种语言推送内容，立即获得AI驱动的翻译，就像Reddit对帖子所做的那样。',
          ar: 'ادفع المحتوى بلغة واحدة، واحصل على ترجمات مدعومة بالذكاء الاصطناعي على الفور، كما يفعل Reddit مع المنشورات.',
          it: "Invia contenuti in una lingua, ottieni traduzioni alimentate dall'IA istantaneamente, come fa Reddit con i post.",
          pt: 'Envie conteúdo em um idioma, obtenha traduções alimentadas por IA instantaneamente, como o Reddit faz com as postagens.',
          hi: 'एक भाषा में सामग्री पुश करें, Reddit जैसे पोस्ट के साथ तुरंत AI-संचालित अनुवाद प्राप्त करें।',
          tr: "İçeriği bir dilde gönderin, Reddit'in gönderilerle yaptığı gibi anında AI destekli çeviriler alın.",
          pl: 'Wyślij treść w jednym języku, natychmiast otrzymaj tłumaczenia wspierane przez AI, tak jak Reddit robi to z postami.',
          id: 'Dorong konten dalam satu bahasa, dapatkan terjemahan bertenaga AI secara instan, seperti yang dilakukan Reddit dengan postingan.',
          vi: 'Đẩy nội dung bằng một ngôn ngữ, nhận bản dịch do AI hỗ trợ ngay lập tức, giống như Reddit làm với bài đăng.',
        }),
        badge: t({
          en: 'WIP',
          'en-GB': 'WIP',
          fr: 'En cours',
          es: 'En desarrollo',
          de: 'In Arbeit',
          ru: 'В работе',
          ja: '作業中',
          ko: '작업 중',
          zh: '进行中',
          ar: 'قيد العمل',
          it: 'In lavorazione',
          pt: 'Em desenvolvimento',
          hi: 'कार्य प्रगति में',
          tr: 'Yapım aşamasında',
          pl: 'W trakcie',
          id: 'Sedang dikerjakan',
          vi: 'Đang phát triển',
        }),
      },
      {
        id: 'self-hosted',
        icon: 'building',
        title: t({
          en: 'Self-hosted option',
          'en-GB': 'Self-hosted option',
          fr: 'Option auto-hébergée',
          es: 'Opción auto-hospedada',
          de: 'Self-hosted Option',
          ru: 'Опция самохостинга',
          ja: 'セルフホスティングオプション',
          ko: '자체 호스팅 옵션',
          zh: '自托管选项',
          ar: 'خيار الاستضافة الذاتية',
          it: 'Opzione self-hosted',
          pt: 'Opção de auto-hospedagem',
          hi: 'सेल्फ-होस्टेड विकल्प',
          tr: 'Kendi barındırma seçeneği',
          pl: 'Opcja self-hosted',
          id: 'Opsi self-hosted',
          vi: 'Tùy chọn tự lưu trữ',
        }),
        description: t({
          en: 'Run Intlayer CMS on your own infrastructure when compliance or control requires it.',
          'en-GB':
            'Run Intlayer CMS on your own infrastructure when compliance or control requires it.',
          fr: "Exécutez Intlayer CMS sur votre propre infrastructure lorsque la conformité ou le contrôle l'exigent.",
          es: 'Ejecuta Intlayer CMS en tu propia infraestructura cuando la conformidad o el control lo requieran.',
          de: 'Intlayer CMS auf eigener Infrastruktur betreiben, wenn Compliance oder Kontrolle es erfordern.',
          ru: 'Запускайте Intlayer CMS на собственной инфраструктуре, когда этого требуют соответствие или контроль.',
          ja: 'コンプライアンスや制御が必要な場合、独自のインフラストラクチャでIntlayer CMSを実行します。',
          ko: '규정 준수 또는 제어가 필요한 경우 자체 인프라에서 Intlayer CMS를 실행하세요.',
          zh: '当合规性或控制需要时，在您自己的基础设施上运行 Intlayer CMS。',
          ar: 'قم بتشغيل Intlayer CMS على البنية التحتية الخاصة بك عندما تتطلب الامتثال أو التحكم.',
          it: 'Esegui Intlayer CMS sulla tua infrastruttura quando la conformità o il controllo lo richiedono.',
          pt: 'Execute o Intlayer CMS em sua própria infraestrutura quando a conformidade ou o controle exigirem.',
          hi: 'जब अनुपालन या नियंत्रण की आवश्यकता हो तो अपने स्वयं के बुनियादी ढांचे पर Intlayer CMS चलाएं।',
          tr: "Uyumluluk veya kontrol gerektirdiğinde kendi altyapınızda Intlayer CMS'i çalıştırın.",
          pl: 'Uruchom Intlayer CMS na własnej infrastrukturze, gdy wymaga tego zgodność lub kontrola.',
          id: 'Jalankan Intlayer CMS di infrastruktur Anda sendiri ketika kepatuhan atau kontrol memerlukannya.',
          vi: 'Chạy Intlayer CMS trên cơ sở hạ tầng của riêng bạn khi tuân thủ hoặc kiểm soát yêu cầu.',
        }),
        badge: t({
          en: 'WIP',
          'en-GB': 'WIP',
          fr: 'En cours',
          es: 'En desarrollo',
          de: 'In Arbeit',
          ru: 'В работе',
          ja: '作業中',
          ko: '작업 중',
          zh: '进行中',
          ar: 'قيد العمل',
          it: 'In lavorazione',
          pt: 'Em desenvolvimento',
          hi: 'कार्य प्रगति में',
          tr: 'Yapım aşamasında',
          pl: 'W trakcie',
          id: 'Sedang dikerjakan',
          vi: 'Đang phát triển',
        }),
      },
      {
        id: 'webhooks',
        icon: 'webhook',
        title: t({
          en: 'CI/CD webhooks',
          'en-GB': 'CI/CD webhooks',
          fr: 'Webhooks CI/CD',
          es: 'Webhooks CI/CD',
          de: 'CI/CD Webhooks',
          ru: 'CI/CD вебхуки',
          ja: 'CI/CD Webhook',
          ko: 'CI/CD 웹훅',
          zh: 'CI/CD Webhook',
          ar: 'Webhooks CI/CD',
          it: 'Webhook CI/CD',
          pt: 'Webhooks CI/CD',
          hi: 'CI/CD वेबहुक',
          tr: "CI/CD webhook'ları",
          pl: 'Webhooki CI/CD',
          id: 'Webhook CI/CD',
          vi: 'Webhook CI/CD',
        }),
        description: t({
          en: 'Trigger rebuilds automatically when content changes. Integrate with Vercel, Netlify, GitHub Actions, and more.',
          'en-GB':
            'Trigger rebuilds automatically when content changes. Integrate with Vercel, Netlify, GitHub Actions, and more.',
          fr: 'Déclenchez des reconstructions automatiquement lorsque le contenu change. Intégrez avec Vercel, Netlify, GitHub Actions, et plus.',
          es: 'Activa reconstrucciones automáticamente cuando el contenido cambia. Integra con Vercel, Netlify, GitHub Actions, y más.',
          de: 'Rebuilds automatisch auslösen, wenn sich Content ändert. Integration mit Vercel, Netlify, GitHub Actions und mehr.',
          ru: 'Автоматически запускайте пересборку при изменении контента. Интегрируйтесь с Vercel, Netlify, GitHub Actions и другими.',
          ja: 'コンテンツが変更されたときに自動的に再ビルドをトリガーします。Vercel、Netlify、GitHub Actionsなどと統合。',
          ko: '콘텐츠가 변경되면 자동으로 재빌드를 트리거합니다. Vercel, Netlify, GitHub Actions 등과 통합.',
          zh: '内容更改时自动触发重建。与Vercel、Netlify、GitHub Actions等集成。',
          ar: 'قم بتشغيل إعادة البناء تلقائياً عند تغيير المحتوى. التكامل مع Vercel و Netlify و GitHub Actions والمزيد.',
          it: 'Attiva automaticamente le ricompilazioni quando il contenuto cambia. Integra con Vercel, Netlify, GitHub Actions e altro ancora.',
          pt: 'Dispare reconstruções automaticamente quando o conteúdo muda. Integre com Vercel, Netlify, GitHub Actions e mais.',
          hi: 'सामग्री बदलने पर स्वचालित रूप से पुनर्निर्माण ट्रिगर करें। Vercel, Netlify, GitHub Actions और अधिक के साथ एकीकृत करें।',
          tr: 'İçerik değiştiğinde otomatik olarak yeniden derlemeleri tetikleyin. Vercel, Netlify, GitHub Actions ve daha fazlasıyla entegre edin.',
          pl: 'Automatycznie wyzwalaj przebudowy, gdy treść się zmienia. Integruj z Vercel, Netlify, GitHub Actions i więcej.',
          id: 'Picu pembangunan ulang secara otomatis saat konten berubah. Integrasikan dengan Vercel, Netlify, GitHub Actions, dan lainnya.',
          vi: 'Tự động kích hoạt rebuild khi nội dung thay đổi. Tích hợp với Vercel, Netlify, GitHub Actions và hơn thế nữa.',
        }),
        badge: t({
          en: 'WIP',
          'en-GB': 'WIP',
          fr: 'En cours',
          es: 'En desarrollo',
          de: 'In Arbeit',
          ru: 'В работе',
          ja: '作業中',
          ko: '작업 중',
          zh: '进行中',
          ar: 'قيد العمل',
          it: 'In lavorazione',
          pt: 'Em desenvolvimento',
          hi: 'कार्य प्रगति में',
          tr: 'Yapım aşamasında',
          pl: 'W trakcie',
          id: 'Sedang dikerjakan',
          vi: 'Đang phát triển',
        }),
      },
    ],
  },
} satisfies Dictionary;

export default comingSoonContent;
