import { type Dictionary, t } from 'intlayer';

const finalCtaContent = {
  key: 'cms-landing-final-cta',
  title: 'CMS landing page final CTA section content',
  description:
    'Content declarations for the CMS landing page final CTA section.',
  content: {
    finalCtaTitle: t({
      en: 'Ready to unify your content workflow?',
      'en-GB': 'Ready to unify your content workflow?',
      fr: 'Prêt à unifier votre workflow de contenu ?',
      es: '¿Listo para unificar tu flujo de contenido?',
      de: 'Bereit, Ihren Content-Workflow zu vereinheitlichen?',
      ru: 'Готовы объединить рабочий процесс контента?',
      ja: 'コンテンツワークフローを統合する準備はできていますか？',
      ko: '콘텐츠 워크플로우를 통합할 준비가 되셨나요?',
      zh: '准备好统一您的内容工作流程了吗？',
      ar: 'هل أنت مستعد لتوحيد سير عمل المحتوى الخاص بك؟',
      it: 'Pronto a unificare il tuo flusso di lavoro dei contenuti?',
      pt: 'Pronto para unificar seu fluxo de trabalho de conteúdo?',
      hi: 'अपने सामग्री वर्कफ़्लो को एकीकृत करने के लिए तैयार हैं?',
      tr: 'İçerik iş akışınızı birleştirmeye hazır mısınız?',
      pl: 'Gotowy do ujednolicenia przepływu pracy z treścią?',
      id: 'Siap menyatukan alur kerja konten Anda?',
      vi: 'Sẵn sàng thống nhất quy trình làm việc nội dung của bạn?',
    }),
    finalCtaDescription: t({
      en: 'Start for free. Scale as you grow. No credit card required.',
      'en-GB': 'Start for free. Scale as you grow. No credit card required.',
      fr: 'Commencez gratuitement. Évoluez selon vos besoins. Aucune carte de crédit requise.',
      es: 'Empieza gratis. Escala según crezcas. Sin tarjeta de crédito.',
      de: 'Kostenlos starten. Skalieren Sie mit Ihrem Wachstum. Keine Kreditkarte erforderlich.',
      ru: 'Начните бесплатно. Масштабируйтесь по мере роста. Кредитная карта не требуется.',
      ja: '無料で始めましょう。成長に合わせてスケール。クレジットカード不要。',
      ko: '무료로 시작하세요. 성장에 따라 확장하세요. 신용카드 불필요.',
      zh: '免费开始。随着您的成长而扩展。无需信用卡。',
      ar: 'ابدأ مجاناً. قم بالتوسع مع نموك. لا حاجة لبطاقة ائتمان.',
      it: 'Inizia gratuitamente. Scala man mano che cresci. Nessuna carta di credito richiesta.',
      pt: 'Comece grátis. Escale conforme cresce. Sem cartão de crédito necessário.',
      hi: 'मुफ्त में शुरू करें। जैसे-जैसे आप बढ़ें, स्केल करें। क्रेडिट कार्ड की आवश्यकता नहीं।',
      tr: 'Ücretsiz başlayın. Büyüdükçe ölçeklendirin. Kredi kartı gerekmez.',
      pl: 'Zacznij za darmo. Skaluj się wraz ze wzrostem. Karta kredytowa nie jest wymagana.',
      id: 'Mulai gratis. Skala saat Anda tumbuh. Tidak perlu kartu kredit.',
      vi: 'Bắt đầu miễn phí. Mở rộng khi bạn phát triển. Không cần thẻ tín dụng.',
    }),
    finalCtaPrimary: t({
      en: 'Get started free',
      'en-GB': 'Get started free',
      fr: 'Commencer gratuitement',
      es: 'Empezar gratis',
      de: 'Kostenlos starten',
      ru: 'Начать бесплатно',
      ja: '無料で始める',
      ko: '무료로 시작하기',
      zh: '免费开始',
      ar: 'ابدأ مجاناً',
      it: 'Inizia gratuitamente',
      pt: 'Comece grátis',
      hi: 'मुफ्त में शुरू करें',
      tr: 'Ücretsiz başla',
      pl: 'Zacznij za darmo',
      id: 'Mulai gratis',
      vi: 'Bắt đầu miễn phí',
    }),
    finalCtaSecondary: t({
      en: 'View pricing',
      'en-GB': 'View pricing',
      fr: 'Voir les tarifs',
      es: 'Ver precios',
      de: 'Preise ansehen',
      ru: 'Посмотреть цены',
      ja: '価格を見る',
      ko: '가격 보기',
      zh: '查看价格',
      ar: 'عرض الأسعار',
      it: 'Visualizza i prezzi',
      pt: 'Ver preços',
      hi: 'मूल्य देखें',
      tr: 'Fiyatları görüntüle',
      pl: 'Zobacz ceny',
      id: 'Lihat harga',
      vi: 'Xem giá',
    }),
  },
} satisfies Dictionary;

export default finalCtaContent;
