import { type Dictionary, t } from 'intlayer';

const totpFormContent = {
  key: 'totp-form',
  content: {
    codeLabel: t({
      en: 'Code',
      'en-GB': 'Code',
      fr: 'Code',
      es: 'Código',
      de: 'Code',
      ja: 'コード',
      ko: '코드',
      zh: '代码',
      it: 'Codice',
      pt: 'Código',
      hi: 'कोड',
      ar: 'رمز',
      ru: 'Код',
      tr: 'Kod',
      pl: 'Kod',
      id: 'Kode',
      vi: 'Mã',
      uk: 'Код',
    }),
    codePlaceholder: t({
      en: 'Enter 6-digit code',
      'en-GB': 'Enter 6-digit code',
      fr: 'Entrez le code à 6 chiffres',
      es: 'Ingrese código de 6 dígitos',
      de: 'Geben Sie den 6-stelligen Code ein',
      ja: '6桁のコードを入力してください',
      ko: '6자리 코드를 입력하세요',
      zh: '输入6位数代码',
      it: 'Inserisci codice a 6 cifre',
      pt: 'Digite o código de 6 dígitos',
      hi: '6 अंकों का कोड दर्ज करें',
      ar: 'أدخل رمز مكون من 6 أرقام',
      ru: 'Введите 6-значный код',
      tr: '6 haneli kodu girin',
      pl: 'Wprowadź 6-cyfrowy kod',
      id: 'Masukkan kode 6 digit',
      vi: 'Nhập mã 6 chữ số',
      uk: 'Введіть 6-значний код',
    }),
    verifyButton: t({
      en: 'Verify',
      'en-GB': 'Verify',
      fr: 'Vérifier',
      es: 'Verificar',
      de: 'Überprüfen',
      ja: '確認',
      ko: '확인',
      zh: '验证',
      it: 'Verifica',
      pt: 'Verificar',
      hi: 'सत्यापित करें',
      ar: 'تحقق',
      ru: 'Проверить',
      tr: 'Doğrula',
      pl: 'Zweryfikuj',
      id: 'Verifikasi',
      vi: 'Xác minh',
      uk: 'Підтвердити',
    }),
  },
  title: 'TOTP form',
  description:
    'Strings for the Time-based One-Time Password (TOTP) verification form, including code label, code input placeholder, and verify button text.',
  tags: ['auth', 'totp', 'form', 'two-factor'],
} satisfies Dictionary;

export default totpFormContent;
