import { type Dictionary, t } from 'intlayer';

const contributorSectionContent = {
  key: 'contributor-section',
  content: {
    title: t({
      en: 'Built by the Community',
      'en-GB': 'Built by the Community',
      fr: 'Construit par la communauté',
      es: 'Construido por la comunidad',
      de: 'Von der Community gebaut',
      it: 'Costruito dalla comunità',
      pt: 'Construído pela comunidade',
      ru: 'Создано сообществом',
      ja: 'コミュニティによって構築',
      ko: '커뮤니티에 의해 구축됨',
      zh: '由社区构建',
      hi: 'समुदाय द्वारा निर्मित',
      tr: 'Topluluk tarafından oluşturuldu',
      ar: 'بناه المجتمع',
      pl: 'Zbudowane przez społeczność',
      id: 'Dibangun oleh Komunitas',
      vi: 'Được xây dựng bởi Cộng đồng',
    }),
    subtitle: t({
      en: 'Meet the amazing contributors who make Intlayer possible.',
      'en-GB': 'Meet the amazing contributors who make Intlayer possible',
      fr: 'Rencontrez les contributeurs incroyables qui rendent Intlayer possible. Vous voulez etre le prochain ? Rejoignez nous sur Discord.',
      es: 'Conoce a los increíbles colaboradores que hacen posible Intlayer',
      de: 'Lernen Sie die erstaunlichen Mitwirkenden kennen, die Intlayer möglich machen',
      it: 'Incontra gli straordinari contributori che rendono possibile Intlayer',
      pt: 'Conheça os incríveis colaboradores que tornam o Intlayer possível',
      ru: 'Познакомьтесь с удивительными участниками, которые делают Intlayer возможным',
      ja: 'Intlayerを可能にする素晴らしい貢献者に会おう',
      ko: 'Intlayer를 가능하게 하는 놀라운 기여자들을 만나보세요',
      zh: '认识让Intlayer成为可能的了不起的贡献者',
      hi: 'Intlayer को संभव बनाने वाले अद्भुत योगदानकर्ताओं से मिलें',
      tr: "Intlayer'ı mümkün kılan harika katkıda bulunanlarla tanışın",
      ar: 'تعرف على المساهمين المذهلين الذين يجعلون Intlayer ممكنًا',
      pl: 'Poznaj niesamowitych współtwórców, którzy umożliwiają Intlayer',
      id: 'Temui kontributor luar biasa yang membuat Intlayer mungkin',
      vi: 'Gặp gỡ những người đóng góp tuyệt vời làm cho Intlayer trở nên khả thi',
    }),
    seeAllLink: t({
      en: 'See all contributors',
      'en-GB': 'See all contributors',
      fr: 'Voir tous les contributeurs',
      es: 'Ver todos los colaboradores',
      de: 'Alle Mitwirkenden anzeigen',
      it: 'Vedi tutti i contributori',
      pt: 'Ver todos os colaboradores',
      ru: 'Посмотреть всех участников',
      ja: 'すべての貢献者を見る',
      ko: '모든 기여자 보기',
      zh: '查看所有贡献者',
      hi: 'सभी योगदानकर्ताओं को देखें',
      tr: 'Tüm katkıda bulunanları gör',
      ar: 'انظر جميع المساهمين',
      pl: 'Zobacz wszystkich współtwórców',
      id: 'Lihat semua kontributor',
      vi: 'Xem tất cả người đóng góp',
    }),
    discordLinkLabel: t({
      en: 'Join us',
      'en-GB': 'Join us',
      fr: 'Rejoignez-nous',
      es: 'Únete a nosotros',
      de: 'Tritt uns bei',
      it: 'Unisciti a noi',
      pt: 'Junte-se a nós',
      ru: 'Присоединяйтесь к нам',
      ja: '参加する',
      ko: '합류하세요',
      zh: '加入我们',
      hi: 'हमसे जुड़ें',
      tr: 'Bize katılın',
      ar: 'انضم إلينا',
      pl: 'Dołącz do nas',
      id: 'Bergabunglah dengan kami',
      vi: 'Tham gia với chúng tôi',
    }),
  },
  title: 'Contributor section content',
  description:
    'Content declarations for the landing page contributor section. Includes labels, headings, and call-to-actions related to the contributors.',
  tags: ['landing page', 'contributors', 'section content'],
} satisfies Dictionary;

export default contributorSectionContent;
