/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Char123LocaleChar125RouteRouteImport } from './routes/{-$locale}/route'
import { Route as ApiOgRouteImport } from './routes/api/og'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125SplatRouteImport } from './routes/{-$locale}/$'
import { Route as Char123LocaleChar125ReviewerIdRouteImport } from './routes/{-$locale}/$reviewerId'
import { Route as Char123LocaleChar125404RouteImport } from './routes/{-$locale}/404'
import { Route as Char123LocaleChar125DashboardIndexRouteImport } from './routes/{-$locale}/dashboard/index'
import { Route as Char123LocaleChar125FindReviewerIndexRouteImport } from './routes/{-$locale}/find-reviewer/index'
import { Route as Char123LocaleChar125FindReviewerReviewerIdRouteImport } from './routes/{-$locale}/find-reviewer/$reviewerId'
import { Route as Char123LocaleChar125DashboardMissionMissionIdRouteImport } from './routes/{-$locale}/dashboard/mission.$missionId'
import { Route as Char123LocaleChar125FindReviewerDashboardIndexRouteImport } from './routes/{-$locale}/find-reviewer/dashboard/index'
import { Route as Char123LocaleChar125FindReviewerDashboardMissionMissionIdRouteImport } from './routes/{-$locale}/find-reviewer/dashboard/mission.$missionId'

const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: '/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125SplatRoute =
  Char123LocaleChar125SplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ReviewerIdRoute =
  Char123LocaleChar125ReviewerIdRouteImport.update({
    id: '/$reviewerId',
    path: '/$reviewerId',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125404Route = Char123LocaleChar125404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => Char123LocaleChar125RouteRoute,
} as any)
const Char123LocaleChar125DashboardIndexRoute =
  Char123LocaleChar125DashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125FindReviewerIndexRoute =
  Char123LocaleChar125FindReviewerIndexRouteImport.update({
    id: '/find-reviewer/',
    path: '/find-reviewer/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125FindReviewerReviewerIdRoute =
  Char123LocaleChar125FindReviewerReviewerIdRouteImport.update({
    id: '/find-reviewer/$reviewerId',
    path: '/find-reviewer/$reviewerId',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125DashboardMissionMissionIdRoute =
  Char123LocaleChar125DashboardMissionMissionIdRouteImport.update({
    id: '/dashboard/mission/$missionId',
    path: '/dashboard/mission/$missionId',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125FindReviewerDashboardIndexRoute =
  Char123LocaleChar125FindReviewerDashboardIndexRouteImport.update({
    id: '/find-reviewer/dashboard/',
    path: '/find-reviewer/dashboard/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125FindReviewerDashboardMissionMissionIdRoute =
  Char123LocaleChar125FindReviewerDashboardMissionMissionIdRouteImport.update({
    id: '/find-reviewer/dashboard/mission/$missionId',
    path: '/find-reviewer/dashboard/mission/$missionId',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/healthz': typeof HealthzRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/og': typeof ApiOgRoute
  '/{-$locale}/$': typeof Char123LocaleChar125SplatRoute
  '/{-$locale}/$reviewerId': typeof Char123LocaleChar125ReviewerIdRoute
  '/{-$locale}/404': typeof Char123LocaleChar125404Route
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/find-reviewer/$reviewerId': typeof Char123LocaleChar125FindReviewerReviewerIdRoute
  '/{-$locale}/dashboard/': typeof Char123LocaleChar125DashboardIndexRoute
  '/{-$locale}/find-reviewer/': typeof Char123LocaleChar125FindReviewerIndexRoute
  '/{-$locale}/dashboard/mission/$missionId': typeof Char123LocaleChar125DashboardMissionMissionIdRoute
  '/{-$locale}/find-reviewer/dashboard/': typeof Char123LocaleChar125FindReviewerDashboardIndexRoute
  '/{-$locale}/find-reviewer/dashboard/mission/$missionId': typeof Char123LocaleChar125FindReviewerDashboardMissionMissionIdRoute
}
export interface FileRoutesByTo {
  '/healthz': typeof HealthzRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/og': typeof ApiOgRoute
  '/{-$locale}/$': typeof Char123LocaleChar125SplatRoute
  '/{-$locale}/$reviewerId': typeof Char123LocaleChar125ReviewerIdRoute
  '/{-$locale}/404': typeof Char123LocaleChar125404Route
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/find-reviewer/$reviewerId': typeof Char123LocaleChar125FindReviewerReviewerIdRoute
  '/{-$locale}/dashboard': typeof Char123LocaleChar125DashboardIndexRoute
  '/{-$locale}/find-reviewer': typeof Char123LocaleChar125FindReviewerIndexRoute
  '/{-$locale}/dashboard/mission/$missionId': typeof Char123LocaleChar125DashboardMissionMissionIdRoute
  '/{-$locale}/find-reviewer/dashboard': typeof Char123LocaleChar125FindReviewerDashboardIndexRoute
  '/{-$locale}/find-reviewer/dashboard/mission/$missionId': typeof Char123LocaleChar125FindReviewerDashboardMissionMissionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/healthz': typeof HealthzRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/og': typeof ApiOgRoute
  '/{-$locale}/$': typeof Char123LocaleChar125SplatRoute
  '/{-$locale}/$reviewerId': typeof Char123LocaleChar125ReviewerIdRoute
  '/{-$locale}/404': typeof Char123LocaleChar125404Route
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/find-reviewer/$reviewerId': typeof Char123LocaleChar125FindReviewerReviewerIdRoute
  '/{-$locale}/dashboard/': typeof Char123LocaleChar125DashboardIndexRoute
  '/{-$locale}/find-reviewer/': typeof Char123LocaleChar125FindReviewerIndexRoute
  '/{-$locale}/dashboard/mission/$missionId': typeof Char123LocaleChar125DashboardMissionMissionIdRoute
  '/{-$locale}/find-reviewer/dashboard/': typeof Char123LocaleChar125FindReviewerDashboardIndexRoute
  '/{-$locale}/find-reviewer/dashboard/mission/$missionId': typeof Char123LocaleChar125FindReviewerDashboardMissionMissionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/healthz'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/og'
    | '/{-$locale}/$'
    | '/{-$locale}/$reviewerId'
    | '/{-$locale}/404'
    | '/{-$locale}/'
    | '/{-$locale}/find-reviewer/$reviewerId'
    | '/{-$locale}/dashboard/'
    | '/{-$locale}/find-reviewer/'
    | '/{-$locale}/dashboard/mission/$missionId'
    | '/{-$locale}/find-reviewer/dashboard/'
    | '/{-$locale}/find-reviewer/dashboard/mission/$missionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/healthz'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/og'
    | '/{-$locale}/$'
    | '/{-$locale}/$reviewerId'
    | '/{-$locale}/404'
    | '/{-$locale}'
    | '/{-$locale}/find-reviewer/$reviewerId'
    | '/{-$locale}/dashboard'
    | '/{-$locale}/find-reviewer'
    | '/{-$locale}/dashboard/mission/$missionId'
    | '/{-$locale}/find-reviewer/dashboard'
    | '/{-$locale}/find-reviewer/dashboard/mission/$missionId'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/healthz'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/og'
    | '/{-$locale}/$'
    | '/{-$locale}/$reviewerId'
    | '/{-$locale}/404'
    | '/{-$locale}/'
    | '/{-$locale}/find-reviewer/$reviewerId'
    | '/{-$locale}/dashboard/'
    | '/{-$locale}/find-reviewer/'
    | '/{-$locale}/dashboard/mission/$missionId'
    | '/{-$locale}/find-reviewer/dashboard/'
    | '/{-$locale}/find-reviewer/dashboard/mission/$missionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren
  HealthzRoute: typeof HealthzRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiOgRoute: typeof ApiOgRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/$': {
      id: '/{-$locale}/$'
      path: '/$'
      fullPath: '/{-$locale}/$'
      preLoaderRoute: typeof Char123LocaleChar125SplatRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/$reviewerId': {
      id: '/{-$locale}/$reviewerId'
      path: '/$reviewerId'
      fullPath: '/{-$locale}/$reviewerId'
      preLoaderRoute: typeof Char123LocaleChar125ReviewerIdRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/404': {
      id: '/{-$locale}/404'
      path: '/404'
      fullPath: '/{-$locale}/404'
      preLoaderRoute: typeof Char123LocaleChar125404RouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/dashboard/': {
      id: '/{-$locale}/dashboard/'
      path: '/dashboard'
      fullPath: '/{-$locale}/dashboard/'
      preLoaderRoute: typeof Char123LocaleChar125DashboardIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/find-reviewer/': {
      id: '/{-$locale}/find-reviewer/'
      path: '/find-reviewer'
      fullPath: '/{-$locale}/find-reviewer/'
      preLoaderRoute: typeof Char123LocaleChar125FindReviewerIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/find-reviewer/$reviewerId': {
      id: '/{-$locale}/find-reviewer/$reviewerId'
      path: '/find-reviewer/$reviewerId'
      fullPath: '/{-$locale}/find-reviewer/$reviewerId'
      preLoaderRoute: typeof Char123LocaleChar125FindReviewerReviewerIdRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/dashboard/mission/$missionId': {
      id: '/{-$locale}/dashboard/mission/$missionId'
      path: '/dashboard/mission/$missionId'
      fullPath: '/{-$locale}/dashboard/mission/$missionId'
      preLoaderRoute: typeof Char123LocaleChar125DashboardMissionMissionIdRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/find-reviewer/dashboard/': {
      id: '/{-$locale}/find-reviewer/dashboard/'
      path: '/find-reviewer/dashboard'
      fullPath: '/{-$locale}/find-reviewer/dashboard/'
      preLoaderRoute: typeof Char123LocaleChar125FindReviewerDashboardIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/find-reviewer/dashboard/mission/$missionId': {
      id: '/{-$locale}/find-reviewer/dashboard/mission/$missionId'
      path: '/find-reviewer/dashboard/mission/$missionId'
      fullPath: '/{-$locale}/find-reviewer/dashboard/mission/$missionId'
      preLoaderRoute: typeof Char123LocaleChar125FindReviewerDashboardMissionMissionIdRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
  }
}

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125SplatRoute: typeof Char123LocaleChar125SplatRoute
  Char123LocaleChar125ReviewerIdRoute: typeof Char123LocaleChar125ReviewerIdRoute
  Char123LocaleChar125404Route: typeof Char123LocaleChar125404Route
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
  Char123LocaleChar125FindReviewerReviewerIdRoute: typeof Char123LocaleChar125FindReviewerReviewerIdRoute
  Char123LocaleChar125DashboardIndexRoute: typeof Char123LocaleChar125DashboardIndexRoute
  Char123LocaleChar125FindReviewerIndexRoute: typeof Char123LocaleChar125FindReviewerIndexRoute
  Char123LocaleChar125DashboardMissionMissionIdRoute: typeof Char123LocaleChar125DashboardMissionMissionIdRoute
  Char123LocaleChar125FindReviewerDashboardIndexRoute: typeof Char123LocaleChar125FindReviewerDashboardIndexRoute
  Char123LocaleChar125FindReviewerDashboardMissionMissionIdRoute: typeof Char123LocaleChar125FindReviewerDashboardMissionMissionIdRoute
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125SplatRoute: Char123LocaleChar125SplatRoute,
    Char123LocaleChar125ReviewerIdRoute: Char123LocaleChar125ReviewerIdRoute,
    Char123LocaleChar125404Route: Char123LocaleChar125404Route,
    Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
    Char123LocaleChar125FindReviewerReviewerIdRoute:
      Char123LocaleChar125FindReviewerReviewerIdRoute,
    Char123LocaleChar125DashboardIndexRoute:
      Char123LocaleChar125DashboardIndexRoute,
    Char123LocaleChar125FindReviewerIndexRoute:
      Char123LocaleChar125FindReviewerIndexRoute,
    Char123LocaleChar125DashboardMissionMissionIdRoute:
      Char123LocaleChar125DashboardMissionMissionIdRoute,
    Char123LocaleChar125FindReviewerDashboardIndexRoute:
      Char123LocaleChar125FindReviewerDashboardIndexRoute,
    Char123LocaleChar125FindReviewerDashboardMissionMissionIdRoute:
      Char123LocaleChar125FindReviewerDashboardMissionMissionIdRoute,
  }

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
  HealthzRoute: HealthzRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiOgRoute: ApiOgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
