import {
  type DocKey,
  getDocMetadata as getDocMetadataCore,
} from '@intlayer/docs';
import { type Dictionary, localeRecord, t } from 'intlayer';

const getDocMetadata = (doc: DocKey) =>
  t(localeRecord(async ({ locale }) => await getDocMetadataCore(doc, locale)));

const docDataContent: Dictionary = {
  key: 'doc-data',
  fill: false,
  content: {
    why: {
      title: t({
        en: 'Why Intlayer ?',
        'en-GB': 'Why Intlayer ?',
        fr: 'Pourquoi Intlayer ?',
        es: '¿Por qué Intlayer?',
        de: 'Warum Intlayer?',
        it: 'Perché Intlayer?',
        ja: 'なぜIntlayer？',
        ko: 'Intlayer의 이점',
        zh: '为什么Intlayer？',
        pt: 'Por que Intlayer?',
        hi: 'Intlayer का क्यों लाभ',
        ar: 'لماذا Intlayer؟',
        ru: 'Почему Intlayer?',
        tr: 'Neden Intlayer?',
        pl: 'Dlaczego Intlayer?',
        id: 'Mengapa Intlayer?',
        vi: 'Tại sao Intlayer?',
      }),
      default: getDocMetadata('./docs/en/interest_of_intlayer.md'),
    },
    'get-started': {
      title: t({
        en: 'Get Started',
        'en-GB': 'Get Started',
        fr: 'Commencer',
        es: 'Empezar',
        de: 'Anfangen',
        it: 'Iniziare',
        ja: '始める',
        ko: '시작하기',
        zh: '开始',
        pt: 'Começar',
        hi: 'शुरू करें',
        ar: 'ابدأ',
        ru: 'Начать',
        tr: 'Başla',
        pl: 'Zacząć',
        id: 'Mulai',
        vi: 'Bắt đầu',
      }),
      default: getDocMetadata('./docs/en/introduction.md'),
    },
    roadmap: {
      title: t({
        en: 'Roadmap',
        'en-GB': 'Roadmap',
        fr: 'Feuille de route',
        es: 'Hoja de ruta',
        de: 'Roadmap',
        it: 'Roadmap',
        ja: 'ロードマップ',
        ko: '로드맵',
        zh: '路线图',
        pt: 'Roteiro',
        hi: 'रोडमैप',
        ar: 'خريطة الطريق',
        ru: 'Дорожная карта',
        tr: 'Yol Haritası',
        pl: 'Roadmap',
        id: 'Roadmap',
        vi: 'Roadmap',
      }),
      default: getDocMetadata('./docs/en/roadmap.md'),
    },
    concept: {
      title: t({
        en: 'Concept',
        'en-GB': 'Concept',
        fr: 'Concept',
        es: 'Concepto',
        de: 'Konzept',
        it: 'Concetto',
        ja: 'コンセプト',
        ko: '개념',
        zh: '概念',
        pt: 'Conceito',
        hi: 'अवधारणा',
        ar: 'مفهوم',
        ru: 'Концепция',
        tr: 'Kavram',
        pl: 'Koncepcja',
        id: 'Konsep',
        vi: 'Khái niệm',
      }),
      subSections: {
        'how-works-intlayer': {
          title: t({
            en: 'How Intlayer Works',
            'en-GB': 'How Intlayer Works',
            fr: 'Comment Intlayer fonctionne',
            es: 'Cómo funciona Intlayer',
            de: 'Wie Intlayer funktioniert',
            it: 'Come funziona Intlayer',
            ja: 'Intlayerの仕組み',
            ko: 'Intlayer 작동 방식',
            zh: 'Intlayer如何工作',
            pt: 'Como o Intlayer funciona',
            hi: 'Intlayer कैसे काम करता है',
            ar: 'كيف يعمل Intlayer',
            ru: 'Как работает Intlayer',
            tr: 'Intlayer Nasıl Çalışır',
            pl: 'Jak działa Intlayer',
            id: 'Bagaimana Intlayer bekerja',
            vi: 'Intlayer làm việc như thế nào',
          }),
          default: getDocMetadata('./docs/en/how_works_intlayer.md'),
        },
        configuration: {
          title: t({
            en: 'Configuration',
            'en-GB': 'Configuration',
            fr: 'Configuration',
            es: 'Configuración',
            de: 'Konfiguration',
            it: 'Configurazione',
            ja: '設定',
            ko: '구성',
            zh: '配置',
            pt: 'Configuração',
            hi: 'कॉन्फ़िगरेशन',
            ar: 'التكوين',
            ru: 'Конфигурация',
            tr: 'Yapılandırma',
            pl: 'Konfiguracja',
            id: 'Konfigurasi',
            vi: 'Cấu hình',
          }),
          default: getDocMetadata('./docs/en/configuration.md'),
        },
        cli: {
          title: 'CLI',
          default: getDocMetadata('./docs/en/cli/index.md'),
        },
        editor: {
          title: t({
            en: 'Visual Editor',
            'en-GB': 'Visual Editor',
            fr: 'Éditeur visuel',
            es: 'Editor visual',
            de: 'Visueller Editor',
            it: 'Editor visuale',
            ja: 'ビジュアルエディター',
            ko: '비주얼 편집기',
            zh: '可视化编辑器',
            pt: 'Editor visual',
            hi: 'विज़ुअल एडिटर',
            ar: 'المحرر المرئي',
            ru: 'Визуальный редактор',
            tr: 'Görsel Editör',
            pl: 'Edytor wizualny',
            id: 'Editor visual',
            vi: 'Editor visual',
          }),

          default: getDocMetadata('./docs/en/intlayer_visual_editor.md'),
        },
        cms: {
          title: 'CMS',
          default: getDocMetadata('./docs/en/intlayer_CMS.md'),
        },
        'ci-cd': {
          title: t({
            en: 'CI/CD Integration',
            'en-GB': 'CI/CD Integration',
            fr: 'Intégration CI/CD',
            es: 'Integración CI/CD',
            de: 'CI/CD-Integration',
            it: 'Integrazione CI/CD',
            ja: 'CI/CD統合',
            ko: 'CI/CD 통합',
            zh: 'CI/CD集成',
            pt: 'Integração CI/CD',
            hi: 'CI/CD एकीकरण',
            ar: 'تكامل CI/CD',
            ru: 'Интеграция CI/CD',
            tr: 'CI/CD Entegrasyonu',
            pl: 'Integracja CI/CD',
            id: 'Integrasi CI/CD',
            vi: 'Tích hợp CI/CD',
          }),
          default: getDocMetadata('./docs/en/CI_CD.md'),
        },
        content: {
          title: t({
            en: 'Content Declaration',
            'en-GB': 'Content Declaration',
            fr: 'Déclaration de contenu',
            es: 'Declaración de contenido',
            de: 'Inhaltsdeklaration',
            it: 'Dichiarazione dei contenuti',
            ja: 'コンテンツ宣言',
            ko: '콘텐츠 선언',
            zh: '内容声明',
            pt: 'Declaração de conteúdo',
            hi: 'सामग्री घोषणा',
            ar: 'إعلان المحتوى',
            ru: 'Объявление контента',
            tr: 'İçerik Beyanı',
            pl: 'Deklaracja zawartości',
            id: 'Deklarasi konten',
            vi: 'Khai báo nội dung',
          }),
          default: getDocMetadata('./docs/en/dictionary/content_file.md'),
          subSections: {
            translation: {
              title: t({
                en: 'Translation',
                'en-GB': 'Translation',
                fr: 'Traduction',
                es: 'Traducción',
                de: 'Übersetzung',
                it: 'Traduzione',
                ja: '翻訳',
                ko: '번역',
                zh: '翻译',
                pt: 'Tradução',
                hi: 'अनुवाद',
                ar: 'ترجمة',
                ru: 'Перевод',
                tr: 'Çeviri',
                pl: 'Tłumaczenie',
                id: 'Terjemahan',
                vi: 'Dịch',
              }),
              default: getDocMetadata('./docs/en/dictionary/translation.md'),
            },
            enumeration: {
              title: t({
                en: 'Enumeration',
                'en-GB': 'Enumeration',
                fr: 'Énumération',
                es: 'Enumeración',
                de: 'Aufzählung',
                it: 'Enumerazione',
                ja: '列挙',
                ko: '열거',
                zh: '枚举',
                pt: 'Enumeração',
                hi: 'गणना',
                ar: 'تعداد',
                ru: 'Перечисление',
                tr: 'Numaralandırma',
                pl: 'Wyliczenie',
                id: 'Penumeraan',
                vi: 'Liệt kê',
              }),
              default: getDocMetadata('./docs/en/dictionary/enumeration.md'),
            },
            condition: {
              title: t({
                en: 'Condition',
                'en-GB': 'Condition',
                fr: 'Condition',
                es: 'Condición',
                de: 'Bedingung',
                it: 'Condizione',
                ja: '条件',
                ko: '조건',
                zh: '条件',
                pt: 'Condição',
                hi: 'शर्त',
                ar: 'شرط',
                ru: 'Условие',
                tr: 'Koşul',
                pl: 'Warunek',
                id: 'Kondisi',
                vi: 'Điều kiện',
              }),
              default: getDocMetadata('./docs/en/dictionary/condition.md'),
            },
            gender: {
              title: t({
                en: 'Gender',
                'en-GB': 'Gender',
                fr: 'Genre',
                es: 'Género',
                de: 'Geschlecht',
                it: 'Genere',
                ja: '性別',
                ko: '성별',
                zh: '性别',
                pt: 'Gênero',
                hi: 'लिंग',
                ar: 'جنس',
                ru: 'Пол',
                tr: 'Cinsiyet',
                pl: 'Płeć',
                id: 'Jenis kelamin',
                vi: 'Giới tính',
              }),
              default: getDocMetadata('./docs/en/dictionary/gender.md'),
            },
            insertion: {
              title: t({
                en: 'Insertion',
                'en-GB': 'Insertion',
                fr: 'Insertion',
                es: 'Inserción',
                de: 'Einfügung',
                it: 'Inserimento',
                ja: '挿入',
                ko: '삽입',
                zh: '插入',
                pt: 'Inserção',
                hi: 'सम्मिलन',
                ar: 'إدراج',
                ru: 'Вставка',
                tr: 'Ekleme',
                pl: 'Wstawienie',
                id: 'Penambahan',
                vi: 'Chèn',
              }),
              default: getDocMetadata('./docs/en/dictionary/insertion.md'),
            },
            file: {
              title: t({
                en: 'File',
                'en-GB': 'File',
                fr: 'Fichier',
                es: 'Archivo',
                de: 'Datei',
                it: 'File',
                ja: 'ファイル',
                ko: '파일',
                zh: '文件',
                pt: 'Arquivo',
                hi: 'फ़ाइल',
                ar: 'ملف',
                ru: 'Файл',
                tr: 'Dosya',
                pl: 'Plik',
                id: 'Berkas',
                vi: 'Tệp',
              }),
              default: getDocMetadata('./docs/en/dictionary/file.md'),
            },
            nesting: {
              title: t({
                en: 'Nesting',
                'en-GB': 'Nesting',
                fr: 'Imbrication',
                es: 'Anidación',
                de: 'Verschachtelung',
                it: 'Annidamento',
                ja: 'ネスティング',
                ko: '중첩',
                zh: '嵌套',
                pt: 'Aninhamento',
                hi: 'नेस्टिंग',
                ar: 'تداخل',
                ru: 'Вложенность',
                tr: 'İç İçe Geçme',
                pl: 'Zagnieżdżanie',
                id: 'Nesting',
                vi: 'Nesting',
              }),
              default: getDocMetadata('./docs/en/dictionary/nesting.md'),
            },
            markdown: {
              title: 'Markdown',
              default: getDocMetadata('./docs/en/dictionary/markdown.md'),
            },
            'function-fetching': {
              title: t({
                en: 'Function Fetching',
                'en-GB': 'Function Fetching',
                fr: 'Récupération de fonction',
                es: 'Obtención de función',
                de: 'Funktionsabruf',
                it: 'Recupero funzione',
                ja: '関数取得',
                ko: '함수 가져오기',
                zh: '函数获取',
                pt: 'Busca de função',
                hi: 'फ़ंक्शन फेचिंग',
                ar: 'جلب الوظيفة',
                ru: 'Получение функции',
                tr: 'Fonksiyon Getirme',
                pl: 'Pobieranie funkcji',
                id: 'Pengambilan fungsi',
                vi: 'Lấy hàm',
              }),
              default: getDocMetadata(
                './docs/en/dictionary/function_fetching.md'
              ),
            },
          },
        },
        'per-locale-file': {
          title: t({
            en: 'Per Locale File',
            'en-GB': 'Per Locale File',
            fr: 'Fichier par locale',
            es: 'Archivo por locale',
            de: 'Datei pro Locale',
            it: 'File per locale',
            ja: 'ロケールごとのファイル',
            ko: '로케일별 파일',
            zh: '每个语言环境的文件',
            pt: 'Arquivo por locale',
            hi: 'प्रति लोकेल फ़ाइल',
            ar: 'ملف لكل لغة',
            ru: 'Файл для каждой локали',
            tr: 'Yerel Dosya',
            pl: 'Plik dla każdej lokalizacji',
            id: 'File untuk setiap lokal',
            vi: 'File cho mỗi ngôn ngữ',
          }),
          default: getDocMetadata('./docs/en/per_locale_file.md'),
        },
        'auto-fill': {
          title: t({
            en: 'Auto Fill',
            'en-GB': 'Auto Fill',
            fr: 'Remplissage automatique',
            es: 'Autocompletado',
            de: 'Automatisches Ausfüllen',
            it: 'Compilazione automatica',
            ja: '自動入力',
            ko: '자동 채우기',
            zh: '自动填充',
            pt: 'Preenchimento automático',
            hi: 'स्वतः भरण',
            ar: 'الملء التلقائي',
            ru: 'Автозаполнение',
            tr: 'Otomatik Doldurma',
            pl: 'Automatyczne wypełnianie',
            id: 'Pengisian otomatis',
            vi: 'Tự động điền',
          }),
          default: getDocMetadata('./docs/en/autoFill.md'),
        },
        testing: {
          title: t({
            en: 'Testing',
            fr: 'Tests',
            es: 'Pruebas',
            'en-GB': 'Testing',
            de: 'Testen',
            it: 'Test',
            ja: 'テスト',
            ko: '테스트',
            zh: '测试',
            pt: 'Testes',
            hi: 'परीक्षण',
            ar: 'اختبار',
            ru: 'Тестирование',
            tr: 'Test',
            pl: 'Testowanie',
            id: 'Pengujian',
            vi: 'Kiểm tra',
          }),
          default: getDocMetadata('./docs/en/testing.md'),
        },
      },
    },
    environment: {
      title: t({
        en: 'Environment',
        fr: 'Environnement',
        es: 'Entornos',
        'en-GB': 'Environment',
        de: 'Umwelt',
        ja: '環境',
        ko: '환경',
        zh: '环境',
        it: 'Ambiente',
        pt: 'Ambiente',
        hi: 'पर्यावरण',
        ar: 'بيئة',
        ru: 'Окружающая среда',
        tr: 'Ortam',
        pl: 'Środowisko',
        id: 'Lingkungan',
        vi: 'Môi trường',
      }),
      subSections: {
        nextjs: {
          title: 'Next.js',
          default: getDocMetadata('./docs/en/intlayer_with_nextjs_16.md'),
          subSections: {
            15: {
              title: 'Next.js 15',
              default: getDocMetadata('./docs/en/intlayer_with_nextjs_15.md'),
            },
            14: {
              title: t({
                en: 'Next.js 14 and App Router',
                fr: 'Next.js 14 et App Router',
                es: 'Next.js 14 y App Router',
                'en-GB': 'Next.js 14 and App Router',
                de: 'Next.js 14 und App Router',
                ja: 'Next.js 14とApp Router',
                ko: 'Next.js 14 및 앱 라우터',
                zh: 'Next.js 14和应用路由器',
                it: 'Next.js 14 e App Router',
                pt: 'Next.js 14 e App Router',
                hi: 'Next.js 14 और ऐप राउटर',
                ar: 'Next.js 14 وموجه التطبيق',
                ru: 'Next.js 14 и App Router',
                tr: 'Next.js 14 ve Uygulama Yönlendirici',
                pl: 'Next.js 14 i App Router',
                id: 'Next.js 14 dan App Router',
                vi: 'Next.js 14 và App Router',
              }),
              default: getDocMetadata('./docs/en/intlayer_with_nextjs_14.md'),
            },
            'next-with-Page-Router': {
              title: t({
                en: 'Next.js and Page Router',
                fr: 'Next.js et Page Router',
                es: 'Next.js y Page Router',
                'en-GB': 'Next.js and Page Router',
                de: 'Next.js und Page Router',
                ja: 'Next.jsとページルーター',
                ko: 'Next.js 및 페이지 라우터',
                zh: 'Next.js和页面路由器',
                it: 'Next.js e Page Router',
                pt: 'Next.js e Page Router',
                hi: 'Next.js और पेज राउटर',
                ar: 'Next.js وموجه الصفحة',
                ru: 'Next.js и Page Router',
                tr: 'Next.js ve Sayfa Yönlendirici',
                pl: 'Next.js dan Page Router',
                id: 'Next.js dan Page Router',
                vi: 'Next.js và Page Router',
              }),
              default: getDocMetadata(
                './docs/en/intlayer_with_nextjs_page_router.md'
              ),
            },
          },
        },

        'vite-and-react': {
          title: t({
            en: 'Vite and React',
            fr: 'Vite et React',
            es: 'Vite y React',
            'en-GB': 'Vite and React',
            de: 'Vite und React',
            ja: 'ViteおよびReact',
            ko: 'Vite 및 React',
            zh: 'Vite和React',
            it: 'Vite e React',
            pt: 'Vite e React',
            hi: 'Vite और React',
            ar: 'Vite و React',
            ru: 'Vite и React',
            tr: 'Vite ve React',
            pl: 'Vite dan React',
            id: 'Vite dan React',
            vi: 'Vite và React',
          }),
          default: getDocMetadata('./docs/en/intlayer_with_vite+react.md'),
          subSections: {
            'react-router-v7': {
              title: 'React Router v7',
              default: getDocMetadata(
                './docs/en/intlayer_with_react_router_v7.md'
              ),
            },
          },
        },
        'tanstack-start': {
          title: 'Tanstack Start',
          default: getDocMetadata('./docs/en/intlayer_with_tanstack.md'),
        },
        astro: {
          title: 'Astro',
          default: getDocMetadata('./docs/en/intlayer_with_astro.md'),
        },
        'create-react-app': {
          title: 'React CRA',
          default: getDocMetadata(
            './docs/en/intlayer_with_create_react_app.md'
          ),
        },
        'vite-and-vue': {
          title: t({
            en: 'Vite and Vue',
            fr: 'Vite et Vue',
            es: 'Vite y Vue',
            'en-GB': 'Vite and Vue',
            de: 'Vite und Vue',
            ja: 'ViteおよびVue',
            ko: 'Vite 및 Vue',
            zh: 'Vite和Vue',
            it: 'Vite e Vue',
            pt: 'Vite e Vue',
            hi: 'Vite और Vue',
            ar: 'Vite و Vue',
            ru: 'Vite и Vue',
            tr: 'Vite ve Vue',
            pl: 'Vite dan Vue',
            id: 'Vite dan Vue',
            vi: 'Vite và Vue',
          }),
          default: getDocMetadata('./docs/en/intlayer_with_vite+vue.md'),
        },
        'nuxt-and-vue': {
          title: t({
            en: 'Nuxt and Vue',
            fr: 'Nuxt et Vue',
            es: 'Nuxt y Vue',
            'en-GB': 'Nuxt and Vue',
            de: 'Nuxt und Vue',
            ja: 'NuxtおよびVue',
            ko: 'Nuxt 및 Vue',
            zh: 'Nuxt和Vue',
            it: 'Nuxt e Vue',
            pt: 'Nuxt e Vue',
            hi: 'Nuxt और Vue',
            ar: 'Nuxt و Vue',
            ru: 'Nuxt и Vue',
            tr: 'Nuxt ve Vue',
            pl: 'Nuxt dan Vue',
            id: 'Nuxt dan Vue',
            vi: 'Nuxt và Vue',
          }),
          default: getDocMetadata('./docs/en/intlayer_with_nuxt.md'),
        },
        'vite-and-solid': {
          title: t({
            en: 'Vite and Solid',
            fr: 'Vite et Solid',
            es: 'Vite y Solid',
            'en-GB': 'Vite and Solid',
            de: 'Vite und Solid',
            ja: 'ViteおよびSolid',
            ko: 'Vite 및 Solid',
            zh: 'Vite和Solid',
            it: 'Vite e Solid',
            pt: 'Vite e Solid',
            hi: 'Vite और Solid',
            ar: 'Vite و Solid',
            ru: 'Vite и Solid',
            tr: 'Vite ve Solid',
            pl: 'Vite dan Solid',
            id: 'Vite dan Solid',
            vi: 'Vite và Solid',
          }),
          default: getDocMetadata('./docs/en/intlayer_with_vite+solid.md'),
        },
        'vite-and-svelte': {
          title: t({
            en: 'Vite and Svelte',
            fr: 'Vite et Svelte',
            es: 'Vite y Svelte',
            'en-GB': 'Vite and Svelte',
            de: 'Vite und Svelte',
            ja: 'ViteおよびSvelte',
            ko: 'Vite 및 Svelte',
            zh: 'Vite和Svelte',
            it: 'Vite e Svelte',
            pt: 'Vite e Svelte',
            hi: 'Vite और Svelte',
            ar: 'Vite و Svelte',
            ru: 'Vite и Svelte',
            tr: 'Vite ve Svelte',
            pl: 'Vite dan Svelte',
            id: 'Vite dan Svelte',
            vi: 'Vite và Svelte',
          }),
          default: getDocMetadata('./docs/en/intlayer_with_vite+svelte.md'),
          subSections: {
            'vite-and-svelte-kit': {
              title: 'SvelteKit',
              default: getDocMetadata('./docs/en/intlayer_with_svelte_kit.md'),
            },
          },
        },
        'vite-and-preact': {
          title: t({
            en: 'Vite and Preact',
            fr: 'Vite et Preact',
            es: 'Vite y Preact',
            'en-GB': 'Vite and Preact',
            de: 'Vite und Preact',
            ja: 'ViteおよびPreact',
            ko: 'Vite 및 Preact',
            zh: 'Vite和Preact',
            it: 'Vite e Preact',
            pt: 'Vite e Preact',
            hi: 'Vite और Preact',
            ar: 'Vite و Preact',
            ru: 'Vite и Preact',
            tr: 'Vite ve Preact',
            pl: 'Vite dan Preact',
            id: 'Vite dan Preact',
            vi: 'Vite và Preact',
          }),
          default: getDocMetadata('./docs/en/intlayer_with_vite+preact.md'),
        },
        angular: {
          title: 'Angular',
          default: getDocMetadata('./docs/en/intlayer_with_angular.md'),
        },
        'react-native-and-expo': {
          title: t({
            en: 'React Native and Expo',
            fr: 'React Native et Expo',
            es: 'React Native y Expo',
            'en-GB': 'React Native and Expo',
            de: 'React Native und Expo',
            ja: 'React NativeとExpo',
            ko: 'React Native 및 Expo',
            zh: 'React Native和Expo',
            it: 'React Native e Expo',
            pt: 'React Native e Expo',
            hi: 'React Native और Expo',
            ar: 'React Native و Expo',
            ru: 'React Native и Expo',
            tr: 'React Native ve Expo',
            pl: 'React Native dan Expo',
            id: 'React Native dan Expo',
            vi: 'React Native và Expo',
          }),
          default: getDocMetadata(
            './docs/en/intlayer_with_react_native+expo.md'
          ),
        },
        'lynx-and-react': {
          title: t({
            en: 'Lynx and React',
            fr: 'Lynx et React',
            es: 'Lynx y React',
            'en-GB': 'Lynx and React',
            de: 'Lynx und React',
            ja: 'LynxおよびReact',
            ko: 'Lynx 및 React',
            zh: 'Lynx和React',
            it: 'Lynx e React',
            pt: 'Lynx e React',
            hi: 'Lynx और React',
            ar: 'Lynx و React',
            ru: 'Lynx и React',
            tr: 'Lynx ve React',
            pl: 'Lynx dan React',
            id: 'Lynx dan React',
            vi: 'Lynx và React',
          }),
          default: getDocMetadata('./docs/en/intlayer_with_lynx+react.md'),
        },
        express: {
          title: 'Express.js',
          default: getDocMetadata('./docs/en/intlayer_with_express.md'),
        },
        nest: {
          title: 'NestJS',
          default: getDocMetadata('./docs/en/intlayer_with_nestjs.md'),
        },
      },
    },
    plugins: {
      title: 'Plugins',
      subSections: {
        syncJSON: {
          title: 'syncJSON',
          default: getDocMetadata('./docs/en/plugins/sync-json.md'),
        },
      },
    },

    'vs-code-extension': {
      title: t({
        en: 'VS Code Extension',
        fr: 'Extension VS Code',
        es: 'Extensión VS Code',
        'en-GB': 'VS Code Extension',
        de: 'VS Code-Erweiterung',
        ja: 'VS Code拡張機能',
        ko: 'VS Code 확장 기능',
        zh: 'VS Code扩展',
        it: 'Estensione VS Code',
        pt: 'Extensão VS Code',
        ru: 'Расширение VS Code',
        ar: 'امتداد VS Code',
        hi: 'VS Code एक्सटेंशन',
        tr: 'VS Code Uzantısı',
        pl: 'Rozszerzenie VS Code',
        id: 'Ekstensi VS Code',
        vi: 'Mở rộng VS Code',
      }),
      default: getDocMetadata('./docs/en/vs_code_extension.md'),
    },
    'mcp-server': {
      title: t({
        en: 'MCP Server',
        fr: 'Serveur MCP',
        es: 'Servidor MCP',
        'en-GB': 'MCP Server',
        de: 'MCP-Server',
        ja: 'MCPサーバー',
        ko: 'MCP 서버',
        zh: 'MCP服务器',
        it: 'Server MCP',
        pt: 'Servidor MCP',
        hi: 'इंटलेयर MCP सर्वर',
        ar: 'خادم MCP',
        ru: 'Сервер MCP',
        tr: 'MCP Sunucusu',
        pl: 'Serwer MCP',
        id: 'Server MCP',
        vi: 'MCP Server',
      }),
      default: getDocMetadata('./docs/en/mcp_server.md'),
    },
  },
} satisfies Dictionary;

export default docDataContent;
