import { t, type Dictionary } from 'intlayer';

const docDataContent = {
  key: 'doc-data',
  content: {
    'get-started': {
      title: t({
        en: 'Get Started',
        'en-GB': 'Get Started',
        fr: 'Commencer',
        es: 'Empezar',
        de: 'Anfangen',
        it: 'Iniziare',
        ja: '始める',
        ko: '시작하기',
        zh: '开始',
        pt: 'Começar',
        hi: 'शुरू करें',
        ar: 'ابدأ',
        ru: 'Начать',
      }),
    },
    roadmap: {
      title: t({
        en: 'Roadmap',
        'en-GB': 'Roadmap',
        fr: 'Feuille de route',
        es: 'Hoja de ruta',
        de: 'Roadmap',
        it: 'Roadmap',
        ja: 'ロードマップ',
        ko: '로드맵',
        zh: '路线图',
        pt: 'Roteiro',
        hi: 'रोडमैप',
        ar: 'خريطة الطريق',
        ru: 'Дорожная карта',
      }),
    },
    concept: {
      title: t({
        en: 'Concept',
        'en-GB': 'Concept',
        fr: 'Concept',
        es: 'Concepto',
        de: 'Konzept',
        it: 'Concetto',
        ja: 'コンセプト',
        ko: '개념',
        zh: '概念',
        pt: 'Conceito',
        hi: 'अवधारणा',
        ar: 'مفهوم',
        ru: 'Концепция',
      }),
      subSections: {
        'how-works-intlayer': {
          title: t({
            en: 'How Intlayer Works',
            'en-GB': 'How Intlayer Works',
            fr: 'Comment Intlayer fonctionne',
            es: 'Cómo funciona Intlayer',
            de: 'Wie Intlayer funktioniert',
            it: 'Come funziona Intlayer',
            ja: 'Intlayerの仕組み',
            ko: 'Intlayer 작동 방식',
            zh: 'Intlayer如何工作',
            pt: 'Como o Intlayer funciona',
            hi: 'Intlayer कैसे काम करता है',
            ar: 'كيف يعمل Intlayer',
            ru: 'Как работает Intlayer',
          }),
        },
        configuration: {
          title: t({
            en: 'Configuration',
            'en-GB': 'Configuration',
            fr: 'Configuration',
            es: 'Configuración',
            de: 'Konfiguration',
            it: 'Configurazione',
            ja: '設定',
            ko: '구성',
            zh: '配置',
            pt: 'Configuração',
            hi: 'कॉन्फ़िगरेशन',
            ar: 'التكوين',
            ru: 'Конфигурация',
          }),
        },
        interest: {
          title: t({
            en: 'Interest of Intlayer',
            'en-GB': 'Interest of Intlayer',
            fr: 'Intérêt de Intlayer',
            es: 'Interés de Intlayer',
            de: 'Vorteile von Intlayer',
            it: 'Interesse di Intlayer',
            ja: 'Intlayerの利点',
            ko: 'Intlayer의 이점',
            zh: 'Intlayer的优势',
            pt: 'Interesse do Intlayer',
            hi: 'Intlayer का लाभ',
            ar: 'مزايا Intlayer',
            ru: 'Преимущества Intlayer',
          }),
        },
        cli: {
          title: 'CLI',
        },
        editor: {
          title: t({
            en: 'Visual Editor',
            'en-GB': 'Visual Editor',
            fr: 'Éditeur visuel',
            es: 'Editor visual',
            de: 'Visueller Editor',
            it: 'Editor visuale',
            ja: 'ビジュアルエディター',
            ko: '비주얼 편집기',
            zh: '可视化编辑器',
            pt: 'Editor visual',
            hi: 'विज़ुअल एडिटर',
            ar: 'المحرر المرئي',
            ru: 'Визуальный редактор',
          }),
        },
        cms: {
          title: 'CMS',
        },
        'ci-cd': {
          title: t({
            en: 'CI/CD Integration',
            'en-GB': 'CI/CD Integration',
            fr: 'Intégration CI/CD',
            es: 'Integración CI/CD',
            de: 'CI/CD-Integration',
            it: 'Integrazione CI/CD',
            ja: 'CI/CD統合',
            ko: 'CI/CD 통합',
            zh: 'CI/CD集成',
            pt: 'Integração CI/CD',
            hi: 'CI/CD एकीकरण',
            ar: 'تكامل CI/CD',
            ru: 'Интеграция CI/CD',
          }),
        },
        content: {
          title: t({
            en: 'Content Declaration',
            'en-GB': 'Content Declaration',
            fr: 'Déclaration de contenu',
            es: 'Declaración de contenido',
            de: 'Inhaltsdeklaration',
            it: 'Dichiarazione dei contenuti',
            ja: 'コンテンツ宣言',
            ko: '콘텐츠 선언',
            zh: '内容声明',
            pt: 'Declaração de conteúdo',
            hi: 'सामग्री घोषणा',
            ar: 'إعلان المحتوى',
            ru: 'Объявление контента',
          }),
          subsections: {
            translation: {
              title: t({
                en: 'Translation',
                'en-GB': 'Translation',
                fr: 'Traduction',
                es: 'Traducción',
                de: 'Übersetzung',
                it: 'Traduzione',
                ja: '翻訳',
                ko: '번역',
                zh: '翻译',
                pt: 'Tradução',
                hi: 'अनुवाद',
                ar: 'ترجمة',
                ru: 'Перевод',
              }),
            },
            enumeration: {
              title: t({
                en: 'Enumeration',
                'en-GB': 'Enumeration',
                fr: 'Énumération',
                es: 'Enumeración',
                de: 'Aufzählung',
                it: 'Enumerazione',
                ja: '列挙',
                ko: '열거',
                zh: '枚举',
                pt: 'Enumeração',
                hi: 'गणना',
                ar: 'تعداد',
                ru: 'Перечисление',
              }),
            },
            condition: {
              title: t({
                en: 'Condition',
                'en-GB': 'Condition',
                fr: 'Condition',
                es: 'Condición',
                de: 'Bedingung',
                it: 'Condizione',
                ja: '条件',
                ko: '조건',
                zh: '条件',
                pt: 'Condição',
                hi: 'शर्त',
                ar: 'شرط',
                ru: 'Условие',
              }),
            },
            insertion: {
              title: t({
                en: 'Insertion',
                'en-GB': 'Insertion',
                fr: 'Insertion',
                es: 'Inserción',
                de: 'Einfügung',
                it: 'Inserimento',
                ja: '挿入',
                ko: '삽입',
                zh: '插入',
                pt: 'Inserção',
                hi: 'सम्मिलन',
                ar: 'إدراج',
                ru: 'Вставка',
              }),
            },
            file: {
              title: t({
                en: 'File',
                'en-GB': 'File',
                fr: 'Fichier',
                es: 'Archivo',
                de: 'Datei',
                it: 'File',
                ja: 'ファイル',
                ko: '파일',
                zh: '文件',
                pt: 'Arquivo',
                hi: 'फ़ाइल',
                ar: 'ملف',
                ru: 'Файл',
              }),
            },
            nesting: {
              title: t({
                en: 'Nesting',
                'en-GB': 'Nesting',
                fr: 'Imbrication',
                es: 'Anidación',
                de: 'Verschachtelung',
                it: 'Annidamento',
                ja: 'ネスティング',
                ko: '중첩',
                zh: '嵌套',
                pt: 'Aninhamento',
                hi: 'नेस्टिंग',
                ar: 'تداخل',
                ru: 'Вложенность',
              }),
            },
            markdown: {
              title: 'Markdown',
            },
            'function-fetching': {
              title: t({
                en: 'Function Fetching',
                'en-GB': 'Function Fetching',
                fr: 'Récupération de fonction',
                es: 'Obtención de función',
                de: 'Funktionsabruf',
                it: 'Recupero funzione',
                ja: '関数取得',
                ko: '함수 가져오기',
                zh: '函数获取',
                pt: 'Busca de função',
                hi: 'फ़ंक्शन फेचिंग',
                ar: 'جلب الوظيفة',
                ru: 'Получение функции',
              }),
            },
          },
        },
        'per-locale-file': {
          title: t({
            en: 'Per Locale File',
            'en-GB': 'Per Locale File',
            fr: 'Fichier par locale',
            es: 'Archivo por locale',
            de: 'Datei pro Locale',
            it: 'File per locale',
            ja: 'ロケールごとのファイル',
            ko: '로케일별 파일',
            zh: '每个语言环境的文件',
            pt: 'Arquivo por locale',
            hi: 'प्रति लोकेल फ़ाइल',
            ar: 'ملف لكل لغة',
            ru: 'Файл для каждой локали',
          }),
        },
        'auto-fill': {
          title: t({
            en: 'Auto Fill',
            'en-GB': 'Auto Fill',
            fr: 'Remplissage automatique',
            es: 'Autocompletado',
            de: 'Automatisches Ausfüllen',
            it: 'Compilazione automatica',
            ja: '自動入力',
            ko: '자동 채우기',
            zh: '自动填充',
            pt: 'Preenchimento automático',
            hi: 'स्वतः भरण',
            ar: 'الملء التلقائي',
            ru: 'Автозаполнение',
          }),
        },
      },
    },
    environment: {
      title: t({
        en: 'Environment',
        fr: 'Environnement',
        es: 'Entornos',
        'en-GB': 'Environment',
        de: 'Umwelt',
        ja: '環境',
        ko: '환경',
        zh: '环境',
        it: 'Ambiente',
        pt: 'Ambiente',
        hi: 'पर्यावरण',
        ar: 'بيئة',
        ru: 'Окружающая среда',
      }),
      subSections: {
        nextjs: {
          title: t({
            en: 'Intlayer with Next.js',
            fr: 'Intlayer avec Next.js',
            es: 'Intlayer con Next.js',
            'en-GB': 'Intlayer with Next.js',
            de: 'Intlayer mit Next.js',
            ja: 'IntlayerとNext.js',
            ko: 'Intlayer와 Next.js',
            zh: 'Intlayer与Next.js',
            it: 'Intlayer con Next.js',
            pt: 'Intlayer com Next.js',
            hi: 'Intlayer के साथ Next.js',
            ar: 'Intlayer مع Next.js',
            ru: 'Intlayer с Next.js',
          }),
          subSections: {
            14: {
              title: t({
                en: 'Next.js 14 and App Router',
                fr: 'Next.js 14 et App Router',
                es: 'Next.js 14 y App Router',
                'en-GB': 'Next.js 14 and App Router',
                de: 'Next.js 14 und App Router',
                ja: 'Next.js 14とApp Router',
                ko: 'Next.js 14 및 앱 라우터',
                zh: 'Next.js 14和应用路由器',
                it: 'Next.js 14 e App Router',
                pt: 'Next.js 14 e App Router',
                hi: 'Next.js 14 और ऐप राउटर',
                ar: 'Next.js 14 وموجه التطبيق',
                ru: 'Next.js 14 и App Router',
              }),
            },
            'next-with-Page-Router': {
              title: t({
                en: 'Next.js and Page Router',
                fr: 'Next.js et Page Router',
                es: 'Next.js y Page Router',
                'en-GB': 'Next.js and Page Router',
                de: 'Next.js und Page Router',
                ja: 'Next.jsとページルーター',
                ko: 'Next.js 및 페이지 라우터',
                zh: 'Next.js和页面路由器',
                it: 'Next.js e Page Router',
                pt: 'Next.js e Page Router',
                hi: 'Next.js और पेज राउटर',
                ar: 'Next.js وموجه الصفحة',
                ru: 'Next.js и Page Router',
              }),
            },
          },
        },
        'create-react-app': {
          title: t({
            en: 'Intlayer with React CRA',
            fr: 'Intlayer avec React CRA',
            es: 'Intlayer con React CRA',
            'en-GB': 'Intlayer with React CRA',
            de: 'Intlayer mit React CRA',
            ja: 'IntlayerとReact CRA',
            ko: 'Intlayer와 React CRA',
            zh: 'Intlayer与React CRA',
            it: 'Intlayer con React CRA',
            pt: 'Intlayer com React CRA',
            hi: 'Intlayer के साथ React CRA',
            ar: 'Intlayer مع React CRA',
            ru: 'Intlayer с React CRA',
          }),
        },
        'vite-and-react': {
          title: t({
            en: 'Intlayer with Vite and React',
            fr: 'Intlayer avec Vite et React',
            es: 'Intlayer con Vite y React',
            'en-GB': 'Intlayer with Vite and React',
            de: 'Intlayer mit Vite und React',
            ja: 'IntlayerとViteおよびReact',
            ko: 'Intlayer와 Vite 및 React',
            zh: 'Intlayer与Vite和React',
            it: 'Intlayer con Vite e React',
            pt: 'Intlayer com Vite e React',
            hi: 'Intlayer के साथ Vite और React',
            ar: 'Intlayer مع Vite و React',
            ru: 'Intlayer с Vite и React',
          }),
        },
        'vite-and-vue': {
          title: t({
            en: 'Intlayer with Vite and Vue',
            fr: 'Intlayer avec Vite et Vue',
            es: 'Intlayer con Vite y Vue',
            'en-GB': 'Intlayer with Vite and Vue',
            de: 'Intlayer mit Vite und Vue',
            ja: 'IntlayerとViteおよびVue',
            ko: 'Intlayer와 Vite 및 Vue',
            zh: 'Intlayer与Vite和Vue',
            it: 'Intlayer con Vite e Vue',
            pt: 'Intlayer com Vite e Vue',
            hi: 'Intlayer के साथ Vite और Vue',
            ar: 'Intlayer مع Vite و Vue',
            ru: 'Intlayer с Vite и Vue',
          }),
        },
        'vite-and-solid': {
          title: t({
            en: 'Intlayer with Vite and Solid',
            fr: 'Intlayer avec Vite et Solid',
            es: 'Intlayer con Vite y Solid',
            'en-GB': 'Intlayer with Vite and Solid',
            de: 'Intlayer mit Vite und Solid',
            ja: 'IntlayerとViteおよびSolid',
            ko: 'Intlayer와 Vite 및 Solid',
            zh: 'Intlayer与Vite和Solid',
            it: 'Intlayer con Vite e Solid',
            pt: 'Intlayer com Vite e Solid',
            hi: 'Intlayer के साथ Vite और Solid',
            ar: 'Intlayer مع Vite و Solid',
            ru: 'Intlayer с Vite и Solid',
          }),
        },
        'vite-and-svelte': {
          title: t({
            en: 'Intlayer with Vite and Svelte',
            fr: 'Intlayer avec Vite et Svelte',
            es: 'Intlayer con Vite y Svelte',
            'en-GB': 'Intlayer with Vite and Svelte',
            de: 'Intlayer mit Vite und Svelte',
            ja: 'IntlayerとViteおよびSvelte',
            ko: 'Intlayer와 Vite 및 Svelte',
            zh: 'Intlayer与Vite和Svelte',
            it: 'Intlayer con Vite e Svelte',
            pt: 'Intlayer com Vite e Svelte',
            hi: 'Intlayer के साथ Vite और Svelte',
            ar: 'Intlayer مع Vite و Svelte',
            ru: 'Intlayer с Vite и Svelte',
          }),
        },
        'vite-and-preact': {
          title: t({
            en: 'Intlayer with Vite and Preact',
            fr: 'Intlayer avec Vite et Preact',
            es: 'Intlayer con Vite y Preact',
            'en-GB': 'Intlayer with Vite and Preact',
            de: 'Intlayer mit Vite und Preact',
            ja: 'IntlayerとViteおよびPreact',
            ko: 'Intlayer와 Vite 및 Preact',
            zh: 'Intlayer与Vite和Preact',
            it: 'Intlayer con Vite e Preact',
            pt: 'Intlayer com Vite e Preact',
            hi: 'Intlayer के साथ Vite और Preact',
            ar: 'Intlayer مع Vite و Preact',
            ru: 'Intlayer с Vite и Preact',
          }),
        },
        angular: {
          title: t({
            en: 'Intlayer with Angular',
            fr: 'Intlayer avec Angular',
            es: 'Intlayer con Angular',
            'en-GB': 'Intlayer with Angular',
            de: 'Intlayer mit Angular',
            ja: 'IntlayerとAngular',
            ko: 'Intlayer와 Angular',
            zh: 'Intlayer与Angular',
            it: 'Intlayer con Angular',
            pt: 'Intlayer com Angular',
            hi: 'Intlayer के साथ Angular',
            ar: 'Intlayer مع Angular',
            ru: 'Intlayer с Angular',
          }),
        },
        'react-native-and-expo': {
          title: t({
            en: 'Intlayer with React Native and Expo',
            fr: 'Intlayer avec React Native et Expo',
            es: 'Intlayer con React Native y Expo',
            'en-GB': 'Intlayer with React Native and Expo',
            de: 'Intlayer mit React Native und Expo',
            ja: 'IntlayerとReact NativeとExpo',
            ko: 'Intlayer와 React Native 및 Expo',
            zh: 'Intlayer与React Native和Expo',
            it: 'Intlayer con React Native e Expo',
            pt: 'Intlayer com React Native e Expo',
            hi: 'Intlayer के साथ React Native और Expo',
            ar: 'Intlayer مع React Native و Expo',
            ru: 'Intlayer с React Native и Expo',
          }),
        },
        'lynx-and-react': {
          title: t({
            en: 'Intlayer with Lynx and React',
            fr: 'Intlayer avec Lynx et React',
            es: 'Intlayer con Lynx y React',
            'en-GB': 'Intlayer with Lynx and React',
            de: 'Intlayer mit Lynx und React',
            ja: 'IntlayerとLynxおよびReact',
            ko: 'Intlayer와 Lynx 및 React',
            zh: 'Intlayer与Lynx和React',
            it: 'Intlayer con Lynx e React',
            pt: 'Intlayer com Lynx e React',
            hi: 'Intlayer के साथ Lynx और React',
            ar: 'Intlayer مع Lynx و React',
            ru: 'Intlayer с Lynx и React',
          }),
        },
        express: {
          title: t({
            en: 'Intlayer with Express',
            fr: 'Intlayer avec Express',
            es: 'Intlayer con Express',
            'en-GB': 'Intlayer with Express',
            de: 'Intlayer mit Express',
            ja: 'IntlayerとExpress',
            ko: 'Intlayer와 Express',
            zh: 'Intlayer与Express',
            it: 'Intlayer con Express',
            pt: 'Intlayer com Express',
            hi: 'Intlayer के साथ Express',
            ar: 'Intlayer مع Express',
            ru: 'Intlayer с Express',
          }),
        },
      },
    },
    packages: {
      title: t({
        en: 'Packages',
        fr: 'Paquets',
        es: 'Paquetes',
        'en-GB': 'Packages',
        de: 'Pakete',
        ja: 'パッケージ',
        ko: '패키지',
        zh: '包',
        it: 'Pacchetti',
        pt: 'Pacotes',
        hi: 'पैकेज',
        ar: 'الحزم',
        ru: 'Пакеты',
      }),
      subSections: {
        intlayer: {
          title: 'intlayer',
          subSections: {
            getConfiguration: {
              title: 'getConfiguration',
            },
            getEnumeration: {
              title: 'getEnumeration',
            },
            getHTMLTextDir: {
              title: 'getHTMLTextDir',
            },
            getLocaleLang: {
              title: 'getLocaleLang',
            },
            getLocaleName: {
              title: 'getLocaleName',
            },
            getLocalizedUrl: {
              title: 'getLocalizedUrl',
            },
            getMultilingualUrls: {
              title: 'getMultilingualUrls',
            },
            getPathWithoutLocale: {
              title: 'getPathWithoutLocale',
            },
            getTranslation: {
              title: 'getTranslation',
            },
            removeLocaleFromUrl: {
              title: 'removeLocaleFromUrl',
            },
          },
        },
        'express-intlayer': {
          title: 'express-intlayer',
          subSections: {
            t: {
              title: 't',
            },
          },
        },
        'react-intlayer': {
          title: 'react-intlayer',
          subSections: {
            t: {
              title: 't',
            },
            useIntlayer: {
              title: 'useIntlayer',
            },
            useIntlayerAsync: {
              title: 'useIntlayerAsync',
            },
            useDictionary: {
              title: 'useDictionary',
            },
            useLocale: {
              title: 'useLocale',
            },
          },
        },
        'next-intlayer': {
          title: 'next-intlayer',
          subSections: {
            t: {
              title: 't',
            },
            useIntlayer: {
              title: 'useIntlayer',
            },
            useIntlayerAsync: {
              title: 'useIntlayerAsync',
            },
            useDictionary: {
              title: 'useDictionary',
            },
            useLocale: {
              title: 'useLocale',
            },
          },
        },
        'vite-intlayer': {
          title: 'vite-intlayer',
        },
        'vue-intlayer': {
          title: 'vue-intlayer',
        },
        'solid-intlayer': {
          title: 'solid-intlayer',
        },
        'svelte-intlayer': {
          title: 'svelte-intlayer',
        },
        'preact-intlayer': {
          title: 'preact-intlayer',
        },
        'angular-intlayer': {
          title: 'angular-intlayer',
        },
        'lynx-intlayer': {
          title: 'lynx-intlayer',
        },
        'react-native-intlayer': {
          title: 'react-native-intlayer',
        },
        'react-scripts-intlayer': {
          title: 'react-scripts-intlayer',
        },
      },
    },
    'vs-code-extension': {
      title: t({
        en: 'VS Code Extension',
        fr: 'Extension VS Code',
        es: 'Extensión VS Code',
        'en-GB': 'VS Code Extension',
        de: 'VS Code-Erweiterung',
        ja: 'VS Code拡張機能',
        ko: 'VS Code 확장 기능',
        zh: 'VS Code扩展',
        it: 'Estensione VS Code',
        pt: 'Extensão VS Code',
        ru: 'Расширение VS Code',
        ar: 'امتداد VS Code',
        hi: 'VS Code एक्सटेंशन',
      }),
    },
    mcp_server: {
      title: t({
        en: 'Intlayer MCP Server',
        fr: 'Serveur MCP Intlayer',
        es: 'Servidor MCP Intlayer',
        'en-GB': 'Intlayer MCP Server',
        de: 'Intlayer MCP-Server',
        ja: 'Intlayer MCPサーバー',
        ko: 'Intlayer MCP 서버',
        zh: 'Intlayer MCP服务器',
        it: 'Server MCP Intlayer',
        pt: 'Servidor MCP Intlayer',
        hi: 'इंटलेयर MCP सर्वर',
        ar: 'خادم MCP Intlayer',
        ru: 'Сервер MCP Intlayer',
      }),
    },
    blog: {
      title: t({
        en: 'Blog',
        fr: 'Blog',
        es: 'Blog',
        'en-GB': 'Blog',
        de: 'Blog',
        ja: 'ブログ',
        ko: '블로그',
        zh: '博客',
        it: 'Blog',
        pt: 'Blog',
        hi: 'ब्लॉग',
        ar: 'مدونة',
        ru: 'Блог',
      }),
      subSections: {
        i18next: {
          title: t({
            en: 'Intlayer and i18next',
            fr: 'Intlayer et i18next',
            es: 'Intlayer y i18next',
            'en-GB': 'Intlayer and i18next',
            de: 'Intlayer und i18next',
            ja: 'Intlayerとi18next',
            ko: 'Intlayer와 i18next',
            zh: 'Intlayer和i18next',
            it: 'Intlayer e i18next',
            pt: 'Intlayer e i18next',
            hi: 'Intlayer और i18next',
            ar: 'Intlayer و i18next',
            ru: 'Intlayer и i18next',
          }),
        },
      },
    },
  },
} satisfies Dictionary;

export default docDataContent;
