import { type Dictionary, t } from 'intlayer';

const docNavTitlesContent = {
  key: 'doc-nav-list',
  content: {
    collapseButton: {
      label: t({
        en: 'Collapse',
        fr: 'Réduire',
        es: 'Colapsar',
        'en-GB': 'Collapse',
        de: 'Zuklappen',
        ja: '折りたたむ',
        ko: '접기',
        zh: '折叠',
        it: 'Comprimi',
        pt: 'Recolher',
        hi: 'संकुचित करें',
        ar: 'اطوي التوسيع',
        ru: 'Свернуть',
        tr: 'Daralt',
        pl: 'Zwiń',
        id: 'Ciutkan',
        vi: 'Thu gọn',
        uk: 'Згорнути',
      }),
    },
    blogButton: {
      label: t({
        en: 'Go to blog',
        fr: 'Aller à la blog',
        es: 'Ir a la blog',
        'en-GB': 'Go to blog',
        de: 'Gehe zur Blog',
        ja: 'ブログへ行く',
        ko: '블로그로 이동',
        zh: '转到博客',
        it: 'Vai al blog',
        pt: 'Ir para o blog',
        hi: 'ब्लॉग पर जाएं',
        ar: 'اذهب إلى المدونة',
        ru: 'Перейти к блогу',
        tr: 'Bloga git',
        pl: 'Przejdź do bloga',
        id: 'Kunjungi blog',
        vi: 'Đi tới blog',
        uk: 'Перейти до блогу',
      }),
      text: t({
        en: 'Blog',
        fr: 'Blog',
        es: 'Blog',
        'en-GB': 'Blog',
        de: 'Blog',
        ja: 'ブログ',
        ko: '블로그',
        zh: '博客',
        it: 'Blog',
        pt: 'Blog',
        hi: 'ब्लॉग',
        ar: 'مدونة',
        ru: 'Блог',
        tr: 'Blog',
        pl: 'Blog',
        id: 'Blog',
        vi: 'Blog',
        uk: 'Блог',
      }),
    },
    chatBotButton: {
      text: t({
        en: 'Ask a question',
        fr: 'Poser une question',
        es: 'Preguntar una pregunta',
        'en-GB': 'Ask a question',
        de: 'Frage stellen',
        ja: '質問をする',
        ko: '질문 발표',
        zh: '问问题',
        it: 'Fai una domanda',
        pt: 'Faça uma pergunta',
        hi: 'प्रश्न करें',
        ar: 'طرح سؤال',
        ru: 'Задать вопрос',
        tr: 'Bir soru sor',
        pl: 'Zadaj pytanie',
        id: 'Ajukan pertanyaan',
        vi: 'Đặt câu hỏi',
        uk: 'Задати питання',
      }),
      label: t({
        en: 'Click to go to the AI powered smart documentation chatbot',
        fr: 'Cliquez pour accéder au chatbot IA intelligent',
        es: 'Haga clic para acceder al chatbot inteligente de documentación inteligente',
        'en-GB': 'Click to go to the AI powered smart documentation chatbot',
        de: 'Klicken Sie, um auf den intelligenten Chatbot für intelligente Dokumentation zuzugreifen',
        ja: 'AI チャットボットにアクセスするにはクリックしてください',
        ko: 'AI 채팅 봇으로 접근하려면 클릭하세요',
        zh: '点击访问 AI 智能文档聊天机器人',
        it: 'Clicca per accedere al chatbot intelligente per la documentazione intelligente',
        pt: 'Clique para acessar o chatbot inteligente de documentação inteligente',
        hi: 'क्लिक करें केंद्रित सामग्री चैटबॉट पर जाएं',
        ar: 'انقر للدخول إلى الدردشة الذكية للوثائق الذكية',
        ru: 'Нажмите, чтобы перейти к интеллектуальному чат-боту для умной документации',
        tr: 'Yapay zeka destekli akıllı dokümantasyon sohbet botuna gitmek için tıklayın',
        pl: 'Kliknij, aby przejść do inteligentnego chatbota dokumentacji napędzanego sztuczną inteligencją',
        id: 'Klik untuk membuka chatbot dokumentasi cerdas bertenaga AI',
        vi: 'Nhấp để truy cập chatbot thông minh hỗ trợ tài liệu, hoạt động bằng trí tuệ nhân tạo',
        uk: 'Натисніть, щоб перейти до інтелектуального чат-бота документації на базі штучного інтелекту.',
      }),
    },
  },
  title: 'Documentation navigation list',
  description:
    'Content declaration for the documentation navigation list component, including labels for buttons like collapse, blog access, and chatbot interaction.',
  tags: ['documentation', 'navigation', 'component'],
} satisfies Dictionary;

export default docNavTitlesContent;
