import { type Dictionary, t } from 'intlayer';

const valuePropsContent = {
  key: 'cms-landing-value-props',
  title: 'CMS Landing Page — Value Propositions',
  description:
    'Content declaration for the CMS landing page value propositions section, including the section title and a list of value propositions (id, icon, title, description).',
  content: {
    valuePropsTitle: t({
      en: 'Why teams choose Intlayer CMS',
      'en-GB': 'Why teams choose Intlayer CMS',
      fr: 'Pourquoi les équipes choisissent Intlayer CMS',
      es: 'Por qué los equipos eligen Intlayer CMS',
      de: 'Warum Teams Intlayer CMS wählen',
      ru: 'Почему команды выбирают Intlayer CMS',
      ja: 'チームがIntlayer CMSを選ぶ理由',
      ko: '팀이 Intlayer CMS를 선택하는 이유',
      zh: '为什么团队选择 Intlayer CMS',
      ar: 'لماذا تختار الفرق Intlayer CMS',
      it: 'Perché i team scelgono Intlayer CMS',
      pt: 'Por que as equipes escolhem Intlayer CMS',
      hi: 'टीमें Intlayer CMS क्यों चुनती हैं',
      tr: "Ekipler neden Intlayer CMS'i seçiyor",
      pl: 'Dlaczego zespoły wybierają Intlayer CMS',
      id: 'Mengapa tim memilih Intlayer CMS',
      vi: 'Tại sao các nhóm chọn Intlayer CMS',
      uk: 'Чому команди обирають Intlayer CMS',
    }),
    valueProps: [
      {
        id: 'code-first',
        icon: 'code',
        title: t({
          en: 'Code-first, not code-only',
          'en-GB': 'Code-first, not code-only',
          fr: 'Code-first, pas code-only',
          es: 'Code-first, no solo código',
          de: 'Code-first, nicht nur Code',
          ru: 'Code-first, а не только код',
          ja: 'コードファースト、コードのみではない',
          ko: '코드 우선, 코드만이 아님',
          zh: '代码优先，不仅仅是代码',
          ar: 'الكود أولاً، وليس الكود فقط',
          it: 'Code-first, non solo codice',
          pt: 'Code-first, não apenas código',
          hi: 'कोड-फर्स्ट, केवल कोड नहीं',
          tr: 'Kod öncelikli, sadece kod değil',
          pl: 'Code-first, nie tylko kod',
          id: 'Code-first, bukan hanya kode',
          vi: 'Code-first, không chỉ là code',
          uk: 'Код перш за все — не лише код',
        }),
        description: t({
          en: 'Content lives in your repo as source of truth. The CMS syncs and extends, never replaces.',
          'en-GB':
            'Content lives in your repo as source of truth. The CMS syncs and extends, never replaces.',
          fr: 'Le contenu vit dans votre repo comme source de vérité. Le CMS synchronise et étend, ne remplace jamais.',
          es: 'El contenido vive en tu repo como fuente de verdad. El CMS sincroniza y extiende, nunca reemplaza.',
          de: 'Inhalte leben in Ihrem Repo als Single Source of Truth. Das CMS synchronisiert und erweitert, ersetzt nie.',
          ru: 'Контент живет в вашем репозитории как источник истины. CMS синхронизирует и расширяет, никогда не заменяет.',
          ja: 'コンテンツは真実の源としてリポジトリに存在します。CMSは同期し拡張しますが、置き換えることはありません。',
          ko: '콘텐츠는 단일 정보 소스로 저장소에 존재합니다. CMS는 동기화하고 확장하지만 절대 대체하지 않습니다.',
          zh: '内容作为事实来源存在于您的仓库中。CMS同步和扩展，从不替换。',
          ar: 'المحتوى يعيش في مستودعك كمصدر للحقيقة. CMS يزامن ويمتد، لا يستبدل أبداً.',
          it: 'Il contenuto vive nel tuo repository come fonte di verità. Il CMS sincronizza ed estende, non sostituisce mai.',
          pt: 'O conteúdo vive no seu repositório como fonte da verdade. O CMS sincroniza e estende, nunca substitui.',
          hi: 'सामग्री आपके रेपो में सत्य के स्रोत के रूप में रहती है। CMS सिंक करता है और विस्तार करता है, कभी प्रतिस्थापित नहीं करता।',
          tr: 'İçerik, gerçeğin kaynağı olarak deponuzda yaşar. CMS senkronize eder ve genişletir, asla değiştirmez.',
          pl: 'Treść żyje w Twoim repozytorium jako źródło prawdy. CMS synchronizuje i rozszerza, nigdy nie zastępuje.',
          id: 'Konten hidup di repo Anda sebagai sumber kebenaran. CMS menyinkronkan dan memperluas, tidak pernah mengganti.',
          vi: 'Nội dung sống trong repo của bạn như nguồn sự thật. CMS đồng bộ và mở rộng, không bao giờ thay thế.',
          uk: 'Контент зберігається у вашому репозиторії як єдине джерело правди. CMS синхронізує та розширює його, але ніколи не замінює.',
        }),
      },
      {
        id: 'no-plugins',
        icon: 'puzzle',
        title: t({
          en: 'Zero plugins, zero surprise costs',
          'en-GB': 'Zero plugins, zero surprise costs',
          fr: 'Zéro plugins, zéro coûts surprises',
          es: 'Cero plugins, cero costos sorpresa',
          de: 'Keine Plugins, keine versteckten Kosten',
          ru: 'Ноль плагинов, ноль неожиданных затрат',
          ja: 'プラグインゼロ、予期しないコストゼロ',
          ko: '플러그인 제로, 예상치 못한 비용 제로',
          zh: '零插件，零意外成本',
          ar: 'صفر إضافات، صفر تكاليف مفاجئة',
          it: 'Zero plugin, zero costi a sorpresa',
          pt: 'Zero plugins, zero custos surpresa',
          hi: 'शून्य प्लगइन, शून्य आश्चर्यजनक लागत',
          tr: 'Sıfır eklenti, sıfır sürpriz maliyet',
          pl: 'Zero wtyczek, zero niespodziewanych kosztów',
          id: 'Nol plugin, nol biaya mengejutkan',
          vi: 'Không plugin, không chi phí bất ngờ',
          uk: 'Жодних плагінів, жодних несподіваних витрат',
        }),
        description: t({
          en: 'Multilingual content management is built-in. No add-ons needed for localization, versioning, or collaboration.',
          'en-GB':
            'Multilingual content management is built-in. No add-ons needed for localization, versioning, or collaboration.',
          fr: 'La gestion de contenu multilingue est intégrée. Pas de modules complémentaires nécessaires pour la localisation, le versioning ou la collaboration.',
          es: 'La gestión de contenido multilingüe está integrada. Sin complementos necesarios para localización, versionado o colaboración.',
          de: 'Mehrsprachiges Content-Management ist integriert. Keine Add-ons für Lokalisierung, Versionierung oder Zusammenarbeit nötig.',
          ru: 'Многоязычное управление контентом встроено. Не нужны дополнения для локализации, версионирования или сотрудничества.',
          ja: '多言語コンテンツ管理が組み込まれています。ローカライゼーション、バージョン管理、またはコラボレーションにアドオンは不要です。',
          ko: '다국어 콘텐츠 관리가 내장되어 있습니다. 현지화, 버전 관리 또는 협업을 위한 추가 기능이 필요하지 않습니다.',
          zh: '多语言内容管理是内置的。本地化、版本控制或协作不需要附加组件。',
          ar: 'إدارة المحتوى متعدد اللغات مدمجة. لا حاجة لإضافات للتوطين أو إدارة الإصدارات أو التعاون.',
          it: 'La gestione dei contenuti multilingue è integrata. Non sono necessari componenti aggiuntivi per la localizzazione, il versioning o la collaborazione.',
          pt: 'O gerenciamento de conteúdo multilíngue está integrado. Nenhum complemento necessário para localização, versionamento ou colaboração.',
          hi: 'बहुभाषी सामग्री प्रबंधन अंतर्निहित है। स्थानीयकरण, संस्करण नियंत्रण या सहयोग के लिए ऐड-ऑन की आवश्यकता नहीं है।',
          tr: 'Çok dilli içerik yönetimi yerleşiktir. Yerelleştirme, sürüm oluşturma veya işbirliği için eklenti gerekmez.',
          pl: 'Wielojęzyczne zarządzanie treścią jest wbudowane. Nie są potrzebne dodatki do lokalizacji, wersjonowania lub współpracy.',
          id: 'Manajemen konten multibahasa sudah terpasang. Tidak perlu add-on untuk lokalisasi, versioning, atau kolaborasi.',
          vi: 'Quản lý nội dung đa ngôn ngữ được tích hợp sẵn. Không cần tiện ích bổ sung cho bản địa hóa, phiên bản hoặc cộng tác.',
          uk: 'Підтримка багатомовного управління контентом вбудована. Немає потреби в додаткових модулях для локалізації, версіювання чи спільної роботи.',
        }),
      },
      {
        id: 'ship-faster',
        icon: 'rocket',
        title: t({
          en: 'Ship content 10× faster',
          'en-GB': 'Ship content 10× faster',
          fr: 'Publiez du contenu 10× plus vite',
          es: 'Publica contenido 10× más rápido',
          de: 'Content 10× schneller veröffentlichen',
          ru: 'Публикуйте контент в 10 раз быстрее',
          ja: 'コンテンツを10倍速く配信',
          ko: '콘텐츠를 10배 더 빠르게 배송',
          zh: '内容发布速度提高10倍',
          ar: 'انشر المحتوى أسرع بـ 10 مرات',
          it: 'Pubblica contenuti 10× più velocemente',
          pt: 'Publique conteúdo 10× mais rápido',
          hi: 'सामग्री 10× तेजी से शिप करें',
          tr: 'İçeriği 10× daha hızlı gönderin',
          pl: 'Publikuj treść 10× szybciej',
          id: 'Kirim konten 10× lebih cepat',
          vi: 'Gửi nội dung nhanh hơn 10 lần',
          uk: 'Публікуйте контент у 10 разів швидше',
        }),
        description: t({
          en: 'Live sync pushes changes instantly. No rebuild required. Update copy in production while users browse.',
          'en-GB':
            'Live sync pushes changes instantly. No rebuild required. Update copy in production while users browse.',
          fr: 'La synchronisation en direct pousse les changements instantanément. Aucune reconstruction requise. Mettez à jour le contenu en production pendant que les utilisateurs naviguent.',
          es: 'La sincronización en vivo envía cambios al instante. Sin reconstrucción necesaria. Actualiza el contenido en producción mientras los usuarios navegan.',
          de: 'Live-Sync pusht Änderungen sofort. Kein Rebuild erforderlich. Aktualisieren Sie Inhalte in der Produktion, während Benutzer browsen.',
          ru: 'Живая синхронизация мгновенно отправляет изменения. Пересборка не требуется. Обновляйте контент в продакшене, пока пользователи просматривают.',
          ja: 'ライブ同期が変更を即座にプッシュします。再ビルドは不要です。ユーザーが閲覧している間、本番環境でコンテンツを更新します。',
          ko: '라이브 동기화가 변경 사항을 즉시 푸시합니다. 재빌드가 필요하지 않습니다. 사용자가 탐색하는 동안 프로덕션에서 콘텐츠를 업데이트합니다.',
          zh: '实时同步立即推送更改。无需重建。在用户浏览时更新生产中的内容。',
          ar: 'المزامنة المباشرة تدفع التغييرات على الفور. لا حاجة لإعادة البناء. قم بتحديث المحتوى في الإنتاج أثناء تصفح المستخدمين.',
          it: 'La sincronizzazione live invia le modifiche istantaneamente. Nessuna ricompilazione richiesta. Aggiorna il contenuto in produzione mentre gli utenti navigano.',
          pt: 'A sincronização ao vivo envia alterações instantaneamente. Nenhuma reconstrução necessária. Atualize o conteúdo em produção enquanto os usuários navegam.',
          hi: 'लाइव सिंक परिवर्तनों को तुरंत पुश करता है। पुनर्निर्माण की आवश्यकता नहीं है। उपयोगकर्ता ब्राउज़ करते समय प्रोडक्शन में कॉपी अपडेट करें।',
          tr: 'Canlı senkronizasyon değişiklikleri anında gönderir. Yeniden derleme gerekmez. Kullanıcılar gezinirken üretimde içeriği güncelleyin.',
          pl: 'Synchronizacja na żywo natychmiast wysyła zmiany. Nie jest wymagana przebudowa. Aktualizuj treść w produkcji, gdy użytkownicy przeglądają.',
          id: 'Sinkronisasi langsung mendorong perubahan secara instan. Tidak perlu rebuild. Perbarui konten di produksi saat pengguna menjelajah.',
          vi: 'Đồng bộ trực tiếp đẩy thay đổi ngay lập tức. Không cần rebuild. Cập nhật nội dung trong sản xuất khi người dùng duyệt.',
          uk: 'Жива синхронізація миттєво застосовує зміни. Перебудова не потрібна. Оновлюйте тексти у робочому середовищі, поки користувачі переглядають сайт.',
        }),
      },
    ],
  },
  tags: ['cms', 'landing-page', 'value-propositions'],
} satisfies Dictionary;

export default valuePropsContent;
