import { type Dictionary, insert, md, t } from 'intlayer';

export const environmentsFormContent = {
  key: 'environments-form',
  content: {
    title: t({
      en: 'Environments',
      'en-GB': 'Environments',
      fr: 'Environnements',
      es: 'Entornos',
      de: 'Umgebungen',
      ja: '環境',
      ko: '환경',
      zh: '环境',
      it: 'Ambienti',
      pt: 'Ambientes',
      hi: 'परिवेश',
      ar: 'البيئات',
      ru: 'Среды',
      tr: 'Ortamlar',
      pl: 'Środowiska',
      id: 'Lingkungan',
      vi: 'Môi trường',
      uk: 'Середовища',
    }),

    addButton: {
      text: t({
        en: 'Add',
        'en-GB': 'Add',
        fr: 'Ajouter',
        es: 'Agregar',
        de: 'Hinzufügen',
        ja: '追加',
        ko: '추가',
        zh: '添加',
        it: 'Aggiungi',
        pt: 'Adicionar',
        hi: 'जोड़ें',
        ar: 'إضافة',
        ru: 'Добавить',
        tr: 'Ekle',
        pl: 'Dodaj',
        id: 'Tambah',
        vi: 'Thêm',
        uk: 'Додати',
      }),
      label: t({
        en: 'Add environment',
        'en-GB': 'Add environment',
        fr: 'Ajouter un environnement',
        es: 'Agregar entorno',
        de: 'Umgebung hinzufügen',
        ja: '環境を追加',
        ko: '환경 추가',
        zh: '添加环境',
        it: 'Aggiungi ambiente',
        pt: 'Adicionar ambiente',
        hi: 'परिवेश जोड़ें',
        ar: 'إضافة بيئة',
        ru: 'Добавить среду',
        tr: 'Ortam ekle',
        pl: 'Dodaj środowisko',
        id: 'Tambah lingkungan',
        vi: 'Thêm môi trường',
        uk: 'Додати середовище',
      }),
    },

    emptyState: {
      description: t({
        en: 'No environments yet.',
        'en-GB': 'No environments yet.',
        fr: "Aucun environnement pour l'instant.",
        es: 'Aún no hay entornos.',
        de: 'Noch keine Umgebungen.',
        ja: 'まだ環境がありません。',
        ko: '아직 환경이 없습니다.',
        zh: '暂无环境。',
        it: 'Nessun ambiente ancora.',
        pt: 'Ainda sem ambientes.',
        hi: 'अभी तक कोई परिवेश नहीं।',
        ar: 'لا توجد بيئات بعد.',
        ru: 'Пока нет сред.',
        tr: 'Henüz ortam yok.',
        pl: 'Brak środowisk.',
        id: 'Belum ada lingkungan.',
        vi: 'Chưa có môi trường nào.',
        uk: 'Поки немає середовищ.',
      }),
      hint: t({
        en: 'Environments let you manage separate configs and content for production, staging, development, etc.',
        'en-GB':
          'Environments let you manage separate configs and content for production, staging, development, etc.',
        fr: 'Les environnements vous permettent de gérer des configurations et du contenu séparés pour la production, le staging, le développement, etc.',
        es: 'Los entornos le permiten gestionar configuraciones y contenido separados para producción, staging, desarrollo, etc.',
        de: 'Umgebungen ermöglichen es Ihnen, separate Konfigurationen und Inhalte für Produktion, Staging, Entwicklung usw. zu verwalten.',
        ja: '環境を使用すると、本番、ステージング、開発などの個別の設定とコンテンツを管理できます。',
        ko: '환경을 통해 프로덕션, 스테이징, 개발 등에 대한 별도의 구성 및 콘텐츠를 관리할 수 있습니다.',
        zh: '环境让您可以为生产、暂存、开发等管理单独의 配置 and 内容。',
        it: 'Gli ambienti consentono di gestire configurazioni e contenuti separati per produzione, staging, sviluppo, ecc.',
        pt: 'Os ambientes permitem gerenciar configurações e conteúdo separados para produção, staging, desenvolvimento, etc.',
        hi: 'परिवेश आपको उत्पादन, स्टेजिंग, विकास आदि के लिए अलग कॉन्फ़िगरेशन और सामग्री प्रबंधित करने देते हैं।',
        ar: 'تتيح لك البيئات إدارة إعدادات ومحتوى منفصلة للإنتاج والتدريج والتطوير وما إلى ذلك.',
        ru: 'Среды позволяют управлять отдельными конфигурациями и контентом для продакшена, стейджинга, разработки и т.д.',
        tr: 'Ortamlar, üretim, hazırlık, geliştirme vb. için ayrı yapılandırma ve içerikleri yönetmenizi sağlar.',
        pl: 'Środowiska umożliwiają zarządzanie oddzielnymi konfiguracjami i treściami dla produkcji, stagingu, programowania itp.',
        id: 'Lingkungan memungkinkan Anda mengelola konfigurasi dan konten terpisah untuk produksi, staging, pengembangan, dll.',
        vi: 'Môi trường cho phép bạn quản lý các cấu hình và nội dung riêng biệt cho sản xuất, dàn dựng, phát triển, v.v.',
        uk: 'Середовища дозволяють управляти окремими конфігураціями та вмістом для виробництва, стейджингу, розробки тощо.',
      }),
      createFirstButton: t({
        en: 'Create first environment',
        'en-GB': 'Create first environment',
        fr: 'Créer le premier environnement',
        es: 'Crear primer entorno',
        de: 'Erste Umgebung erstellen',
        ja: '最初の環境を作成',
        ko: '첫 번째 환경 만들기',
        zh: '创建第一个环境',
        it: 'Crea il primo ambiente',
        pt: 'Criar primeiro ambiente',
        hi: 'पहला परिवेश बनाएं',
        ar: 'إنشاء البيئة الأولى',
        ru: 'Создать первую среду',
        tr: 'İlk ortamı oluştur',
        pl: 'Utwórz pierwsze środowisko',
        id: 'Buat lingkungan pertama',
        vi: 'Tạo môi trường đầu tiên',
        uk: 'Створити перше середовище',
      }),
    },

    newEnvPlaceholder: t({
      en: 'e.g. development, staging',
      'en-GB': 'e.g. development, staging',
      fr: 'ex. développement, staging',
      es: 'ej. desarrollo, staging',
      de: 'z.B. Entwicklung, Staging',
      ja: '例: development, staging',
      ko: '예: development, staging',
      zh: '例如 development、staging',
      it: 'es. sviluppo, staging',
      pt: 'ex. desenvolvimento, staging',
      hi: 'उदा. development, staging',
      ar: 'مثل: development, staging',
      ru: 'напр. development, staging',
      tr: 'örn. development, staging',
      pl: 'np. development, staging',
      id: 'mis. development, staging',
      vi: 'vd. development, staging',
      uk: 'напр. development, staging',
    }),

    createButton: t({
      en: 'Create',
      'en-GB': 'Create',
      fr: 'Créer',
      es: 'Crear',
      de: 'Erstellen',
      ja: '作成',
      ko: '생성',
      zh: '创建',
      it: 'Crea',
      pt: 'Criar',
      hi: 'बनाएं',
      ar: 'إنشاء',
      ru: 'Создать',
      tr: 'Oluştur',
      pl: 'Utwórz',
      id: 'Buat',
      vi: 'Tạo',
      uk: 'Створити',
    }),

    defaultBadge: t({
      en: 'default',
      'en-GB': 'default',
      fr: 'défaut',
      es: 'predeterminado',
      de: 'Standard',
      ja: 'デフォルト',
      ko: '기본',
      zh: '默认',
      it: 'predefinito',
      pt: 'padrão',
      hi: 'डिफ़ॉल्ट',
      ar: 'افتراضي',
      ru: 'по умолчанию',
      tr: 'varsayılan',
      pl: 'domyślny',
      id: 'default',
      vi: 'mặc định',
      uk: 'за замовчуванням',
    }),

    switchButton: insert(
      t({
        en: 'Switch to {{name}}',
        'en-GB': 'Switch to {{name}}',
        fr: 'Selectionner {{name}}',
        es: 'Cambiar a {{name}}',
        de: 'Zu {{name}} wechseln',
        ja: '{{name}} に切り替え',
        ko: '{{name}}(으)로 전환',
        zh: '切换到 {{name}}',
        it: 'Passa a {{name}}',
        pt: 'Mudar para {{name}}',
        hi: '{{name}} पर स्विच करें',
        ar: 'تبديل إلى {{name}}',
        ru: 'Переключить на {{name}}',
        tr: '{{name}} ortamına geç',
        pl: 'Przełącz na {{name}}',
        id: 'Beralih ke {{name}}',
        vi: 'Chuyển sang {{name}}',
        uk: 'Переключитися на {{name}}',
      })
    ),

    migrateModal: {
      migrateContentButton: t({
        en: 'Migrate content',
        'en-GB': 'Migrate content',
        fr: 'Migrer le contenu',
        es: 'Migrar contenido',
        de: 'Inhalt migrieren',
        ja: 'コンテンツを移行',
        ko: '콘텐츠 마이그레이션',
        zh: '迁移内容',
        it: 'Migra contenuto',
        pt: 'Migrar conteúdo',
        hi: 'सामग्री माइग्रेट करें',
        ar: 'ترحيل المحتوى',
        ru: 'Мигрировать контент',
        tr: 'İçeriği taşı',
        pl: 'Migruj zawartość',
        id: 'Migrasi konten',
        vi: 'Di chuyển nội dung',
        uk: 'Мігрувати вміст',
      }),
      sourceLabel: t({
        en: 'Source',
        fr: 'Source',
        es: 'Origen',
        de: 'Quelle',
        ja: '移行元',
        ko: '소스',
        zh: '源',
        it: 'Origine',
        pt: 'Origem',
        hi: 'स्रोत',
        ar: 'المصدر',
        ru: 'Источник',
        tr: 'Kaynak',
        pl: 'Źródło',
        id: 'Sumber',
        vi: 'Nguồn',
        uk: 'Джерело',
        'en-GB': 'Source',
      }),
      targetLabel: t({
        en: 'Target',
        fr: 'Cible',
        es: 'Destino',
        de: 'Ziel',
        ja: '移行先',
        ko: '대상',
        zh: '目标',
        it: 'Destinazione',
        pt: 'Destino',
        hi: 'लक्ष्य',
        ar: 'الهدف',
        ru: 'Цель',
        tr: 'Hedef',
        pl: 'Cel',
        id: 'Target',
        vi: 'Đích',
        uk: 'Ціль',
        'en-GB': 'Target',
      }),
      selectSourcePlaceholder: t({
        en: 'Select source environment',
        fr: "Sélectionner l'environnement source",
        es: 'Seleccionar entorno de origen',
        de: 'Quellumgebung auswählen',
        ja: '移行元の環境を選択',
        ko: '소스 환경 선택',
        zh: '选择源环境',
        it: "Seleziona l'ambiente di origine",
        pt: 'Selecionar ambiente de origine',
        hi: 'स्रोत परिवेश चुनें',
        ar: 'حدد البيئة المصدر',
        ru: 'Выберите исходную среду',
        tr: 'Kaynak ortamı seçin',
        pl: 'Wybierz środowisko źródłowe',
        id: 'Pilih lingkungan sumber',
        vi: 'Chọn môi trường nguồn',
        uk: 'Виберіть вихідне середовище',
        'en-GB': 'Select source environment',
      }),
      selectTargetPlaceholder: t({
        en: 'Select target environment',
        'en-GB': 'Select target environment',
        fr: "Sélectionner l'environnement cible",
        es: 'Seleccionar entorno de destino',
        de: 'Zielumgebung auswählen',
        ja: 'ターゲット環境を選択',
        ko: '대상 환경 선택',
        zh: '选择目标环境',
        it: "Seleziona l'ambiente di destinazione",
        pt: 'Selecionar ambiente de destino',
        hi: 'लक्ष्य परिवेश चुनें',
        ar: 'حدد البيئة المستهدفة',
        ru: 'Выберите целевую среду',
        tr: 'Hedef ortamı seçin',
        pl: 'Wybierz środowisko docelowe',
        id: 'Pilih lingkungan target',
        vi: 'Chọn môi trường đích',
        uk: 'Виберіть цільове середовище',
      }),
      title: t({
        en: 'Migrate',
        'en-GB': 'Migrate',
        fr: 'Migrer',
        es: 'Migrar',
        de: 'Migrieren',
        ja: '移行',
        ko: '마이그레이션',
        zh: '迁移',
        it: 'Migra',
        pt: 'Migrar',
        hi: 'माइग्रेट करें',
        ar: 'ترحيل',
        ru: 'Мигрировать',
        tr: 'Taşı',
        pl: 'Migruj',
        id: 'Migrasi',
        vi: 'Di chuyển',
        uk: 'Мігрувати',
      }),
      migrateContent: t({
        en: 'Migrate dictionary content',
        'en-GB': 'Migrate dictionary content',
        fr: 'Migrer le contenu du dictionnaire',
        es: 'Migrar contenido del diccionario',
        de: 'Wörterbuchinhalt migrieren',
        ja: '辞書コンテンツを移行',
        ko: '사전 콘텐츠 마이그레이션',
        zh: '迁移字典内容',
        it: 'Migra il contenuto del dizionario',
        pt: 'Migrar conteúdo do dicionário',
        hi: 'शब्दकोश सामग्री माइग्रेट करें',
        ar: 'ترحيل محتوى القاموس',
        ru: 'Мигрировать содержимое словаря',
        tr: 'Sözlük içeriğini taşı',
        pl: 'Migruj zawartość słownika',
        id: 'Migrasi konten kamus',
        vi: 'Di chuyển nội dung từ điển',
        uk: 'Мігрувати вміст словника',
      }),
      migrateConfig: t({
        en: 'Migrate configuration',
        'en-GB': 'Migrate configuration',
        fr: 'Migrer la configuration',
        es: 'Migrar configuración',
        de: 'Konfiguration migrieren',
        ja: '設定を移行',
        ko: '구성 마이그레이션',
        zh: '迁移配置',
        it: 'Migra la configurazione',
        pt: 'Migrar configuração',
        hi: 'कॉन्फ़िगरेशन माइग्रेट करें',
        ar: 'ترحيل التكوين',
        ru: 'Мигрировать конфигурацию',
        tr: 'Yapılandırmayı taşı',
        pl: 'Migruj konfigurację',
        id: 'Migrasi konfigurasi',
        vi: 'Di chuyển cấu hình',
        uk: 'Мігрувати конфігурацію',
      }),
      strategyLabel: t({
        en: 'If content already exists in',
        'en-GB': 'If content already exists in',
        fr: 'Si le contenu existe déjà dans',
        es: 'Si el contenido ya existe en',
        de: 'Wenn Inhalt bereits vorhanden ist in',
        ja: 'コンテンツが既に存在する場合',
        ko: '콘텐츠가 이미 존재하는 경우',
        zh: '如果内容已存在于',
        it: 'Se il contenuto esiste già in',
        pt: 'Se o conteúdo já existir em',
        hi: 'यदि सामग्री पहले से मौजूद है',
        ar: 'إذا كان المحتوى موجوداً بالفعل في',
        ru: 'Если контент уже существует в',
        tr: 'İçerik zaten mevcutsa',
        pl: 'Jeśli treść już istnieje w',
        id: 'Jika konten sudah ada di',
        vi: 'Nếu nội dung đã tồn tại trong',
        uk: 'Якщо вміст вже існує в',
      }),
      fillMissing: t({
        en: 'Fill missing only (skip existing)',
        'en-GB': 'Fill missing only (skip existing)',
        fr: 'Remplir uniquement les manquants (ignorer les existants)',
        es: 'Rellenar solo los faltantes (omitir existentes)',
        de: 'Nur fehlende auffüllen (vorhandene überspringen)',
        ja: '不足分のみ補完（既存はスキップ）',
        ko: '누락된 것만 채우기 (기존 건너뛰기)',
        zh: '仅填充缺失（跳过现有）',
        it: 'Riempi solo i mancanti (salta esistenti)',
        pt: 'Preencher apenas os ausentes (pular existentes)',
        hi: 'केवल लापता भरें (मौजूदा छोड़ें)',
        ar: 'ملء المفقودة فقط (تخطي الموجودة)',
        ru: 'Заполнить только отсутствующее (пропустить существующее)',
        tr: 'Sadece eksikleri doldur (mevcutları atla)',
        pl: 'Uzupełnij tylko brakujące (pomiń istniejące)',
        id: 'Isi yang hilang saja (lewati yang ada)',
        vi: 'Chỉ điền phần thiếu (bỏ qua phần đã có)',
        uk: 'Заповнити лише відсутнє (пропустити наявне)',
      }),
      overwrite: t({
        en: 'Overwrite all',
        'en-GB': 'Overwrite all',
        fr: 'Tout écraser',
        es: 'Sobrescribir todo',
        de: 'Alles überschreiben',
        ja: 'すべて上書き',
        ko: '모두 덮어쓰기',
        zh: '全部覆盖',
        it: 'Sovrascrivi tutto',
        pt: 'Sobrescrever tudo',
        hi: 'सभी को ओवरराइट करें',
        ar: 'الكتابة فوق الكل',
        ru: 'Перезаписать всё',
        tr: 'Hepsinin üzerine yaz',
        pl: 'Nadpisz wszystko',
        id: 'Timpa semua',
        vi: 'Ghi đè tất cả',
        uk: 'Перезаписати все',
      }),
      cancelButton: t({
        en: 'Cancel',
        'en-GB': 'Cancel',
        fr: 'Annuler',
        es: 'Cancelar',
        de: 'Abbrechen',
        ja: 'キャンセル',
        ko: '취소',
        zh: '取消',
        it: 'Annulla',
        pt: 'Cancelar',
        hi: 'रद्द करें',
        ar: 'إلغاء',
        ru: 'Отмена',
        tr: 'İptal',
        pl: 'Anuluj',
        id: 'Batal',
        vi: 'Hủy',
        uk: 'Скасувати',
      }),
      runButton: t({
        en: 'Migrate',
        'en-GB': 'Migrate',
        fr: 'Migrer',
        es: 'Migrar',
        de: 'Migrieren',
        ja: '移行する',
        ko: '마이그레이션 실행',
        zh: '迁移',
        it: 'Migra',
        pt: 'Migrar',
        hi: 'माइग्रेट करें',
        ar: 'ترحيل',
        ru: 'Запустить',
        tr: 'Taşı',
        pl: 'Migruj',
        id: 'Migrasi',
        vi: 'Di chuyển',
        uk: 'Мігрувати',
      }),
    },

    migrateFrom: insert(
      t({
        en: 'Migrate content from {{name}}',
        'en-GB': 'Migrate content from {{name}}',
        fr: 'Migrer le contenu de {{name}}',
        es: 'Migrar contenido de {{name}}',
        de: 'Inhalt von {{name}} migrieren',
        ja: '{{name}} からコンテンツを移行',
        ko: '{{name}}에서 콘텐츠 마이그레이션',
        zh: '从 {{name}} 迁移内容',
        it: 'Migra contenuto da {{name}}',
        pt: 'Migrar conteúdo de {{name}}',
        hi: '{{name}} से सामग्री माइग्रेट करें',
        ar: 'ترحيل المحتوى من {{name}}',
        ru: 'Миграция контента из {{name}}',
        tr: '{{name}} ortamından içeriği taşı',
        pl: 'Migruj zawartość z {{name}}',
        id: 'Migrasi konten dari {{name}}',
        vi: 'Di chuyển nội dung từ {{name}}',
        uk: 'Мігрувати вміст з {{name}}',
      })
    ),

    productionError: t({
      en: '"Production" is the default environment and cannot be added.',
      'en-GB': '"Production" is the default environment and cannot be added.',
      fr: '"Production" est l\'environnement par défaut et ne peut pas être ajouté.',
      es: '"Production" es el entorno predeterminado y no se puede agregar.',
      de: '"Production" ist die Standardumgebung und kann nicht hinzugefügt werden.',
      ja: '「Production」はデフォルトの環境であるため追加できません。',
      ko: '"Production"은 기본 환경이므로 추가할 수 없습니다.',
      zh: '“Production” 是默认环境，无法添加。',
      it: '"Production" è l\'ambiente predefinito e non può essere aggiunto.',
      pt: '"Production" é o ambiente padrão e não pode ser adicionado.',
      hi: '"Production" डिफ़ॉल्ट परिवेश है और इसे जोड़ा नहीं जा सकता।',
      ar: '"Production" هي البيئة الافتراضية ولا يمكن إضافتها.',
      ru: '«Production» — это среда по умолчанию, её нельзя добавить.',
      tr: '"Production" varsayılan ortamdır ve eklenemez.',
      pl: '„Production” to środowisko domyślne i nie można go dodać.',
      id: '"Production" adalah lingkungan default and tidak dapat ditambahkan.',
      vi: '"Production" là môi trường mặc định và không thể thêm vào.',
      uk: '«Production» — це середовище за замовчуванням, його не можна додати.',
    }),

    uniqueError: t({
      en: 'This environment already exists.',
      'en-GB': 'This environment already exists.',
      fr: 'Cet environnement existe déjà.',
      es: 'Este entorno ya existe.',
      de: 'Diese Umgebung existiert bereits.',
      ja: 'この環境は既に存在します。',
      ko: '이 환경은 이미 존재합니다.',
      zh: '此环境已存在。',
      it: 'Questo ambiente esiste già.',
      pt: 'Este ambiente já existe.',
      hi: 'यह परिवेश पहले से मौजूद है।',
      ar: 'هذه البيئة موجودة بالفعل.',
      ru: 'Эта среда уже существует.',
      tr: 'Bu ortam zaten mevcut.',
      pl: 'To środowisko już istnieje.',
      id: 'Lingkungan ini sudah ada.',
      vi: 'Môi trường này đã tồn tại.',
      uk: 'Це середовище вже існує.',
    }),

    resolutionNote: t({
      en: 'Note: In your codebase, the environment will have to match a .env.{env}.locale -> .env.{env} -> .env resolution.',
      'en-GB':
        'Note: In your codebase, the environment will have to match a .env.{env}.locale -> .env.{env} -> .env resolution.',
      fr: "Note : Dans votre base de code, l'environnement devra correspondre à une résolution .env.{env}.locale -> .env.{env} -> .env.",
      es: 'Nota: En su base de código, el entorno tendrá que coincidir con una resolución .env.{env}.locale -> .env.{env} -> .env.',
      de: 'Hinweis: In Ihrer Codebasis muss die Umgebung mit einer Auflösung .env.{env}.locale -> .env.{env} -> .env übereinstimmen.',
      ja: '注意：コードベースでは、環境は .env.{env}.locale -> .env.{env} -> .env の解決ルールに一致する必要があります。',
      ko: '참고: 코드베이스에서 환경은 .env.{env}.locale -> .env.{env} -> .env 해상도 규칙과 일치해야 합니다.',
      zh: '注意：在您的代码库中，环境必须与 .env.{env}.locale -> .env.{env} -> .env 解析规则相匹配。',
      it: "Nota: Nella tua base di codice, l'ambiente dovrà corrispondere a una risoluzione .env.{env}.locale -> .env.{env} -> .env.",
      pt: 'Nota: Em sua base de código, o ambiente terá que corresponder a uma resolução .env.{env}.locale -> .env.{env} -> .env.',
      hi: 'नोट: आपके कोडबेस में, परिवेश को .env.{env}.locale -> .env.{env} -> .env रिज़ॉल्यूशन से मेल खाना होगा।',
      ar: 'ملاحظة: في قاعدة الكود الخاصة بك، يجب أن تتوافق البيئة مع دقة .env.{env}.locale -> .env.{env} -> .env.',
      ru: 'Примечание: В вашей кодовой базе среда должна соответствовать разрешению .env.{env}.locale -> .env.{env} -> .env.',
      tr: 'Not: Kod tabanınızda ortamın bir .env.{env}.locale -> .env.{env} -> .env çözünürlüğü ile eşleşmesi gerekir.',
      pl: 'Uwaga: w bazie kodu środowisko musi odpowiadać rozpoznawaniu nazw .env.{env}.locale -> .env.{env} -> .env.',
      id: 'Catatan: Di basis kode Anda, lingkungan harus cocok dengan resolusi .env.{env}.locale -> .env.{env} -> .env.',
      vi: 'Lưu ý: Trong cơ sở mã của bạn, môi trường sẽ phải khớp với độ phân giải .env.{env}.locale -> .env.{env} -> .env.',
      uk: 'Примітка: У вашій кодовій базі середовище має відповідати роздільній здатності .env.{env}.locale -> .env.{env} -> .env.',
    }),

    cannotCreateAnEnvironmentNamed: t({
      en: 'Cannot create an environment named "production" — it is the built-in default.',
      'en-GB':
        'Cannot create an environment named "production" — it is the built-in default.',
      fr: 'Impossible de créer un environnement nommé "production" — c\'est la valeur par défaut intégrée.',
      es: 'No se puede crear un entorno llamado "production" — es el valor predeterminado incorporado.',
      de: 'Eine Umgebung mit dem Namen "production" kann nicht erstellt werden — dies ist der integrierte Standard.',
      ja: '「production」という名前の環境は作成できません。これは組み込みのデフォルトです。',
      ko: '이름이 "production"인 환경은 만들 수 없습니다. 기본 내장 환경입니다.',
      zh: '无法创建名为 "production" 的环境 — 这是内置的默认环境。',
      it: 'Impossibile creare un ambiente denominato "production" — è l\'impostazione predefinita integrata.',
      pt: 'Não é possível criar um ambiente chamado "production" — é o padrão integrado.',
      hi: 'नाम "production" वाला परिवेश नहीं बनाया जा सकता — यह अंतर्निहित डिफ़ॉल्ट है।',
      ar: 'لا يمكن إنشاء بيئة باسم "production" — إنها القيمة الافتراضية المدمجة.',
      ru: 'Невозможно создать среду с именем «production» — это встроенное значение по умолчанию.',
      tr: '"production" adında bir ortam oluşturulamaz — bu yerleşik varsayılandır.',
      pl: 'Nie można utworzyć środowiska o nazwie „production” — jest to wbudowane domyślne środowisko.',
      id: 'Tidak dapat membuat lingkungan bernama "production" — ini adalah bawaan default.',
      vi: 'Không thể tạo môi trường có tên "production" — đó là mặc định tích hợp.',
      uk: 'Неможливо створити середовище з назвою «production» — це вбудоване значення за замовчуванням.',
    }),

    anEnvironmentNamedTrimmedAlready: insert(
      t({
        en: 'An environment named "{{trimmed}}" already exists.',
        'en-GB': 'An environment named "{{trimmed}}" already exists.',
        fr: 'Un environnement nommé "{{trimmed}}" existe déjà.',
        es: 'Ya existe un entorno llamado "{{trimmed}}".',
        de: 'Eine Umgebung namens "{{trimmed}}" existiert bereits.',
        ja: '「{{trimmed}}」という名前の環境は既に存在します。',
        ko: '이름이 "{{trimmed}}"인 환경이 이미 존재합니다.',
        zh: '名为 "{{trimmed}}" 的环境已存在。',
        it: 'Un ambiente denominato "{{trimmed}}" esiste già.',
        pt: 'Um ambiente chamado "{{trimmed}}" já existe.',
        hi: '“{{trimmed}}” नाम का परिवेश पहले से मौजूद है।',
        ar: 'توجد بيئة باسم "{{trimmed}}" بالفعل.',
        ru: 'Среда с именем «{{trimmed}}» уже существует.',
        tr: '“{{trimmed}}” adında bir ortam zaten mevcut.',
        pl: 'Środowisko o nazwie „{{trimmed}}” już istnieje.',
        id: 'Lingkungan bernama "{{trimmed}}" sudah ada.',
        vi: 'Môi trường có tên "{{trimmed}}" đã tồn tại.',
        uk: 'Середовище з назвою «{{trimmed}}» вже існує.',
      })
    ),

    builtIn: t({
      en: 'built-in',
      'en-GB': 'built-in',
      fr: 'intégré',
      es: 'incorporado',
      de: 'integriert',
      ja: '組み込み',
      ko: '내장됨',
      zh: '内置',
      it: 'integrato',
      pt: 'incorporado',
      hi: 'अंतर्निहित',
      ar: 'مدمج',
      ru: 'встроенный',
      tr: 'yerleşik',
      pl: 'wbudowany',
      id: 'bawaan',
      vi: 'tích hợp',
      uk: 'вбудований',
    }),

    deleteName: insert(
      t({
        en: 'Delete {{name}}',
        'en-GB': 'Delete {{name}}',
        fr: 'Supprimer {{name}}',
        es: 'Eliminar {{name}}',
        de: '{{name}} löschen',
        ja: '{{name}} を削除',
        ko: '{{name}} 삭제',
        zh: '删除 {{name}}',
        it: 'Elimina {{name}}',
        pt: 'Excluir {{name}}',
        hi: '{{name}} हटाएं',
        ar: 'حذف {{name}}',
        ru: 'Удалить {{name}}',
        tr: '{{name}} ortamını sil',
        pl: 'Usuń {{name}}',
        id: 'Hapus {{name}}',
        vi: 'Xóa {{name}}',
        uk: 'Видалити {{name}}',
      })
    ),

    from: t({
      en: 'From',
      'en-GB': 'From',
      fr: 'Depuis',
      es: 'Desde',
      de: 'Von',
      ja: '移行元',
      ko: '출발지',
      zh: '从',
      it: 'Da',
      pt: 'De',
      hi: 'से',
      ar: 'من',
      ru: 'Из',
      tr: 'Kaynak',
      pl: 'Z',
      id: 'Dari',
      vi: 'Từ',
      uk: 'З',
    }),

    to: t({
      en: 'To',
      'en-GB': 'To',
      fr: 'Vers',
      es: 'A',
      de: 'Nach',
      ja: '移行先',
      ko: '목적지',
      zh: '至',
      it: 'A',
      pt: 'Para',
      hi: 'तक',
      ar: 'إلى',
      ru: 'В',
      tr: 'Hedef',
      pl: 'Do',
      id: 'Ke',
      vi: 'Đến',
      uk: 'До',
    }),

    dictionaryContent: t({
      en: 'Dictionary content',
      'en-GB': 'Dictionary content',
      fr: 'Contenu du dictionnaire',
      es: 'Contenido del diccionario',
      de: 'Wörterbuchinhalt',
      ja: '辞書コンテンツ',
      ko: '사전 콘텐츠',
      zh: '字典内容',
      it: 'Contenuto del dizionario',
      pt: 'Conteúdo do dicionário',
      hi: 'शब्दकोश सामग्री',
      ar: 'محتوى القاموس',
      ru: 'Содержимое словаря',
      tr: 'Sözlük içeriği',
      pl: 'Zawartość słownika',
      id: 'Konten kamus',
      vi: 'Nội dung từ điển',
      uk: 'Вміст словника',
    }),

    configuration: t({
      en: 'Configuration',
      'en-GB': 'Configuration',
      fr: 'Configuration',
      es: 'Configuración',
      de: 'Konfiguration',
      ja: '設定',
      ko: '구성',
      zh: '配置',
      it: 'Configurazione',
      pt: 'Configuração',
      hi: 'कॉन्फ़िगरेशन',
      ar: 'التكوين',
      ru: 'Конфигурация',
      tr: 'Yapılandırma',
      pl: 'Konfiguracja',
      id: 'Konfigurasi',
      vi: 'Cấu hình',
      uk: 'Конфігурація',
    }),

    copiesAllDictionariesFrom: t({
      en: 'Copies all dictionaries from',
      'en-GB': 'Copies all dictionaries from',
      fr: 'Copie tous les dictionnaires de',
      es: 'Copia todos los diccionarios de',
      de: 'Kopiert alle Wörterbücher von',
      ja: 'すべての辞書を以下からコピーします：',
      ko: '다음에서 모든 사전 복사:',
      zh: '复制所有字典自',
      it: 'Copia tutti i dizionari da',
      pt: 'Copia todos os dicionários de',
      hi: 'सभी शब्दकोशों को यहाँ से कॉपी करता है',
      ar: 'ينسخ جميع القواميس من',
      ru: 'Копирует все словари из',
      tr: 'Tüm sözlükleri şuradan kopyalar:',
      pl: 'Kopiuje wszystkie słowniki z',
      id: 'Menyalin semua kamus dari',
      vi: 'Sao chép tất cả từ điển từ',
      uk: 'Копіює всі словники з',
    }),

    runMigration: t({
      en: 'Run migration',
      'en-GB': 'Run migration',
      fr: 'Lancer la migration',
      es: 'Ejecutar migración',
      de: 'Migration ausführen',
      ja: 'マイグレーションを実行',
      ko: '마이그레이션 실행',
      zh: '运行迁移',
      it: 'Esegui migrazione',
      pt: 'Executar migração',
      hi: 'माइग्रेशन चलाएं',
      ar: 'تشغيل الترحيل',
      ru: 'Запустить миграцию',
      tr: 'Taşımayı çalıştır',
      pl: 'Uruchom migrację',
      id: 'Jalankan migrasi',
      vi: 'Chạy di chuyển',
      uk: 'Запустити міграцію',
    }),

    matches: md(
      t({
        en: 'Matches `.env.{name}.local` and `.env.{name}` when using the CLI with `--env {name}`.',
        'en-GB':
          'Matches `.env.{name}.local` and `.env.{name}` when using the CLI with `--env {name}`.',
        fr: "Correspond à `.env.{name}.local` et `.env.{name}` lors de l'utilisation de la CLI avec `--env {name}`.",
        es: 'Coincide con `.env.{name}.local` y `.env.{name}` al usar la CLI con `--env {name}`.',
        de: 'Entspricht `.env.{name}.local` und `.env.{name}` bei Verwendung der CLI mit `--env {name}`.',
        ja: 'CLIで `--env {name}` を使用する場合、`.env.{name}.local` および `.env.{name}` と一致します。',
        ko: 'CLI에서 `--env {name}`을 사용할 때 `.env.{name}.local` 및 `.env.{name}`과 일치합니다.',
        zh: '在使用 CLI 时搭配 `--env {name}`，将匹配 `.env.{name}.local` 和 `.env.{name}`。',
        it: 'Corrisponde a `.env.{name}.local` e `.env.{name}` quando si usa la CLI con `--env {name}`.',
        pt: 'Corresponde a `.env.{name}.local` e `.env.{name}` ao usar a CLI com `--env {name}`.',
        hi: 'जब सीएलआई का उपयोग `--env {name}` के साथ किया जाता है, तो यह `.env.{name}.local` और `.env.{name}` से मेल खाता है।',
        ar: 'يطابق `.env.{name}.local` و `.env.{name}` عند استخدام CLI مع `--env {name}`.',
        ru: 'Соответствует `.env.{name}.local` и `.env.{name}` при использовании CLI с `--env {name}`.',
        tr: "CLI'yi `--env {name}` ile kullanırken `.env.{name}.local` ve `.env.{name}` ile eşleşir.",
        pl: 'Pasuje do `.env.{name}.local` i `.env.{name}` podczas używania CLI z `--env {name}`.',
        id: 'Cocok dengan `.env.{name}.local` dan `.env.{name}` saat menggunakan CLI dengan `--env {name}`.',
        vi: 'Khớp với `.env.{name}.local` và `.env.{name}` khi sử dụng CLI với `--env {name}`.',
        uk: 'Відповідає `.env.{name}.local` та `.env.{name}` при використанні CLI з `--env {name}`.',
      })
    ),

    migrateContentBetweenEnvironments: t({
      en: 'Migrate content between environments',
      'en-GB': 'Migrate content between environments',
      fr: 'Migrer le contenu entre les environnements',
      es: 'Migrar contenido entre entornos',
      de: 'Inhalte zwischen Umgebungen migrieren',
      ja: '環境間でコンテンツを移行する',
      ko: '환경 간 콘텐츠 마이그레이션',
      zh: '在环境之间迁移内容',
      it: 'Migra il contenuto tra gli ambienti',
      pt: 'Migrar conteúdo entre ambientes',
      hi: 'परिवेशों के बीच सामग्री माइग्रेट करें',
      ar: 'ترحيل المحتوى بين البيئات',
      ru: 'Миграция контента между средами',
      tr: 'Ortamlar arasında içerik taşı',
      pl: 'Migruj zawartość między środowiskami',
      id: 'Migrasi konten antar lingkungan',
      vi: 'Di chuyển nội dung giữa các môi trường',
      uk: 'Мігрувати вміст між середовищами',
    }),
  },
  title: 'Environments form',
  description: 'Content for the project environments management form.',
  tags: ['form', 'environments', 'project'],
} satisfies Dictionary;

export default environmentsFormContent;
