import { type Dictionary, t } from 'intlayer';

export enum Plans {
  Free = 'free',
  Premium = 'premium',
  Enterprise = 'enterprise',
  Lifetime = 'lifetime',
  Custom = 'custom',
}

export enum Period {
  Monthly = 'monthly',
  Yearly = 'yearly',
  Lifetime = 'lifetime',
}

export type PricingInfo = {
  title: string;
  badge?: string;
  description: string;
  priceId?: string;
  checkPoint: string[];
  callToAction: {
    label: string;
    text: string;
  };
  priceLabel?: string;
};

export const planDetails = {
  free: {
    title: t({
      en: 'Free',
      fr: 'Gratuit',
      es: 'Gratis',
      'en-GB': 'Free',
      de: 'Kostenlos',
      ja: '無料',
      ko: '무료',
      zh: '免费',
      it: 'Gratuito',
      pt: 'Grátis',
      hi: 'मुफ्त',
      ar: 'مجاني',
      ru: 'Бесплатный',
      tr: 'Ücretsiz',
      pl: 'Darmowy',
      id: 'Gratis',
      vi: 'Miễn phí',
      uk: 'Безкоштовний',
    }),
    description: t({
      en: 'Ideal for individuals looking to activate the visual editor on their application. Edit content directly with the AI interface and get a feel for Intlayer’s capabilities.',
      fr: 'Idéal pour les personnes qui cherchent à activer l’éditeur visuel sur leur application. Modifiez le contenu directement avec l’interface AI et obtenez un aperçu des capacités de Intlayer.',
      es: 'Ideal para personas que buscan activar el editor visual en su aplicación. Edite el contenido directamente con la interfaz AI y obtenga una sensación de las capacidades de Intlayer.',
      'en-GB':
        'Ideal for individuals looking to activate the visual editor on their application. Edit content directly with the AI interface and get a feel for Intlayer’s capabilities.',
      de: 'Ideal für Einzelpersonen, die den visuellen Editor in ihrer Anwendung aktivieren möchten. Bearbeiten Sie Inhalte direkt mit der KI-Oberfläche und bekommen Sie ein Gefühl für die Möglichkeiten von Intlayer.',
      ja: 'アプリケーションでビジュアルエディタを有効にしようとする個人に最適です。 AIインターフェイスで直接コンテンツを編集し、Intlayerの機能を体感してください。',
      ko: '애플리케이션에서 비주얼 편집기를 활성화하려는 개인에게 적합합니다. AI 인터페이스로 직접 콘텐츠를 편집하고 Intlayer의 기능을 느껴보세요.',
      zh: '适合希望在其应用程序上激活可视化编辑器的个人。 直接使用AI界面编辑内容，并感受Intlayer的能力。',
      it: 'Ideale per individui che cercano di attivare l’editor visivo nella propria applicazione. Modifica i contenuti direttamente con l’interfaccia AI e fatti un’idea delle potenzialità di Intlayer.',
      pt: 'Ideal para pessoas que desejam ativar o editor visual em seu aplicativo. Edite o conteúdo diretamente com a interface de IA e tenha uma ideia das capacidades do Intlayer.',
      hi: 'व्यक्तियों के लिए आदर्श जो अपने एप्लिकेशन पर दृश्य संपादक को सक्रिय करना चाहते हैं। AI इंटरफ़ेस के साथ सीधे सामग्री संपादित करें और Intlayer की क्षमताओं का अनुभव करें。',
      ar: 'مثالي للأفراد الذين يتطلعون إلى تفعيل محرر الصور في تطبيقهم. قم بتحرير المحتوى مباشرةً من خلال واجهة الذكاء الاصطناعي واحصل على إحساس بإمكانيات Intlayer.',
      ru: 'Идеально подходит для людей, которые хотят активировать визуальный редактор в своем приложении. Редактируйте контент напрямую с помощью интерфейса ИИ и узнайте о возможностях Intlayer.',
      tr: 'Uygulamanızda görsel düzenleyiciyi etkinleştirmek isteyen bireyler için idealdir. İçeriği AI arayüzü ile doğrudan düzenleyin ve Intlayer’ın yeteneklerini hissedin.',
      pl: 'Idealny dla osób, które chcą aktywować edytor wizualny w swojej aplikacji. Edytuj treści bezpośrednio za pomocą interfejsu AI i poznaj możliwości Intlayera.',
      id: 'Ideal untuk individu yang ingin mengaktifkan editor visual di aplikasi mereka. Sunting konten langsung melalui antarmuka AI dan rasakan kemampuan Intlayer.',
      vi: 'Lý tưởng cho cá nhân muốn kích hoạt trình chỉnh sửa trực quan trên ứng dụng của họ. Chỉnh sửa nội dung trực tiếp bằng giao diện AI và trải nghiệm khả năng của Intlayer.',
      uk: 'Ідеально підходить для окремих користувачів, які хочуть активувати візуальний редактор у своєму застосунку. Редагуйте контент безпосередньо через інтерфейс ШІ та оцініть можливості Intlayer.',
    }),
    checkPoint: t({
      en: [
        'Access to all Intlayer packages',
        'Unlimited usage of the visual editor',
        'Unlimited distant dictionaries',
        '100 Mb of storage',
        '2 projects',
        '2 organization users',
      ],
      fr: [
        'Accès à tous les packages Intlayer',
        'Utilisation illimitée de l’éditeur visuel',
        'Dictionnaires distants illimités',
        '100 Mo de stockage',
        '2 projets',
        '2 utilisateurs d’organisation',
      ],
      es: [
        'Acceso a todos los paquetes de Intlayer',
        'Uso ilimitado del editor visual',
        'Diccionarios distantes ilimitados',
        '100 Mb de almacenamiento',
        '2 proyectos',
        '2 usuarios de organización',
      ],
      'en-GB': [
        'Access to all Intlayer packages',
        'Unlimited usage of the visual editor',
        'Unlimited distant dictionaries',
        '100 Mb of storage',
        '2 projects',
        '2 organization users',
      ],
      de: [
        'Zugriff auf alle Intlayer-Pakete',
        'Unbegrenzte Nutzung des visuellen Editors',
        'Unbegrenzte entfernte Wörterbücher',
        '100 MB Speicher',
        '2 Projekte',
        '2 Organisationsbenutzer',
      ],
      ja: [
        'すべてのIntlayerパッケージにアクセス',
        'ビジュアルエディタの無制限使用',
        '無制限の遠隔辞書',
        '100 MBのストレージ',
        '2プロジェクト',
        '2組織ユーザー',
      ],
      ko: [
        '모든 Intlayer 패키지에 액세스',
        '비주얼 편집기를 무제한으로 사용',
        '무제한 원격 사전',
        '100MB의 저장 공간',
        '2 프로젝트',
        '2 조직 사용자',
      ],
      zh: [
        '访问所有Intlayer程序包',
        '无限使用可视化编辑器',
        '无限远程字典',
        '100MB存储',
        '2个项目',
        '2个组织用户',
      ],
      it: [
        'Accesso a tutti i pacchetti Intlayer',
        'Utilizzo illimitato dell’editor visivo',
        'Dizionari remoti illimitati',
        '100 Mb di spazio di archiviazione',
        '2 progetti',
        '2 utenti dell’organizzazione',
      ],
      pt: [
        'Acesso a todos os pacotes Intlayer',
        'Uso ilimitado do editor visual',
        'Dicionários remotos ilimitados',
        '100 Mb de armazenamento',
        '2 projetos',
        '2 usuários da organização',
      ],
      hi: [
        'सभी Intlayer पैकेजों तक पहुँच',
        'दृश्य संपादक का असीमित उपयोग',
        'असीमित दूरस्थ शब्दकोश',
        '100 एमबी भंडारण',
        '2 प्रोजेक्ट',
        '2 संगठन उपयोगकर्ता',
      ],
      ar: [
        'الوصول إلى جميع حزم Intlayer',
        'استخدام غير محدود للمحرر المرئي',
        'قواميس بعيدة غير محدودة',
        '100 ميغابايت من التخزين',
        'مشروعين',
        'مستخدمين اثنين للمنظمة',
      ],
      ru: [
        'Доступ ко всем пакетам Intlayer',
        'Неограниченное использование визуального редактора',
        'Неограниченные удаленные словари',
        '100 Мб памяти',
        '2 проекта',
        '2 пользователя организации',
      ],
      tr: [
        'Tüm Intlayer paketlerine erişim',
        'Görsel düzenleyicinin sınırsız kullanımı',
        'Sınırsız uzak sözlükler',
        '100 Mb depolama',
        '2 proje',
        '2 organizasyon kullanıcısı',
      ],
      pl: [
        'Dostęp do wszystkich pakietów Intlayer',
        'Nieograniczone korzystanie z edytora wizualnego',
        'Nieograniczone zdalne słowniki',
        '100 MB pamięci',
        '2 projekty',
        '2 użytkowników organizacji',
      ],
      id: [
        'Akses ke semua paket Intlayer',
        'Penggunaan editor visual tanpa batas',
        'Kamus jarak jauh tanpa batas',
        '100 MB penyimpanan',
        '2 proyek',
        '2 pengguna organisasi',
      ],
      vi: [
        'Truy cập tất cả các gói Intlayer',
        'Sử dụng trình chỉnh sửa trực quan không giới hạn',
        'Từ điển từ xa không giới hạn',
        '100 MB dung lượng lưu trữ',
        '2 dự án',
        '2 người dùng tổ chức',
      ],
      uk: [
        'Доступ до всіх пакетів Intlayer',
        'Необмежене використання візуального редактора',
        'Необмежені віддалені словники',
        '100 МБ сховища',
        '2 проекти',
        '2 користувачі організації',
      ],
    }),
    callToAction: {
      label: t({
        en: 'Try it for free',
        fr: 'Essayez gratuitement',
        es: 'Pruébalo gratuitamente',
        'en-GB': 'Try it for free',
        de: 'Probieren Sie es kostenlos aus',
        ja: '無料で試す',
        ko: '무료로 시도해 보세요',
        zh: '免费试用',
        it: 'Provalo gratuitamente',
        pt: 'Experimente grátis',
        hi: 'यह मुफ्त में आजमाएँ',
        ar: 'جربه مجاناً',
        ru: 'Попробуйте бесплатно',
        tr: 'Ücretsiz deneyin',
        pl: 'Wypróbuj za darmo',
        id: 'Coba gratis',
        vi: 'Dùng thử miễn phí',
        uk: 'Спробувати безкоштовно',
      }),
      text: t({
        en: 'Try it for free',
        fr: 'Essayez gratuitement',
        es: 'Pruébalo gratuitamente',
        'en-GB': 'Try it for free',
        de: 'Probieren Sie es kostenlos aus',
        ja: '無料で試す',
        ko: '무료로 시도해 보세요',
        zh: '免费试用',
        it: 'Provalo gratuitamente',
        pt: 'Experimente grátis',
        hi: 'यह मुफ्त में आजमाएँ',
        ar: 'جربه مجاناً',
        ru: 'Попробуйте бесплатно',
        tr: 'Ücretsiz deneyin',
        pl: 'Wypróbuj za darmo',
        id: 'Coba gratis',
        vi: 'Dùng thử miễn phí',
        uk: 'Спробувати безкоштовно',
      }),
    },
  },
  premium: {
    title: t({
      en: 'Premium',
      fr: 'Premium',
      es: 'Premium',
      'en-GB': 'Premium',
      de: 'Premium',
      ja: 'プレミアム',
      ko: '프리미엄',
      zh: '高级',
      it: 'Premio',
      pt: 'Premium',
      hi: 'प्रीमियम',
      ar: 'متميز',
      ru: 'Премиум',
      tr: 'Premium',
      pl: 'Premium',
      id: 'Premium',
      vi: 'Premium',
      uk: 'Преміум',
    }),
    description: t({
      en: 'Designed for small to medium teams needing more flexibility. Includes AI content generation, up to 10 projects, and 20 organization users.',
      fr: 'Conçu pour les équipes petites à moyennes nécessitant plus de flexibilité. Comprend la génération de contenu IA, jusqu’à 10 projets et 20 utilisateurs d’organisation.',
      es: 'Diseñado para equipos pequeños a medianos que necesitan más flexibilidad. Incluye generación de contenido IA, hasta 10 proyectos y 20 usuarios de la organización.',
      'en-GB':
        'Designed for small to medium teams needing more flexibility. Includes AI content generation, up to 10 projects, and 20 organization users.',
      de: 'Entwickelt für kleine bis mittlere Teams, die mehr Flexibilität benötigen. Beinhaltet KI-Inhaltsgenerierung, bis zu 10 Projekte und 20 Organisationsbenutzer.',
      ja: '中小規模のチーム向けに設計されています。 10までのプロジェクトと20の組織ユーザーのAIコンテンツ生成を含みます。',
      ko: '더 많은 유연성이 필요한 중소 규모 팀을 위해 설계되었습니다. 최대 10개의 프로젝트와 20명의 조직 사용자와 함께하는 AI 콘텐츠 생성이 포함되어 있습니다.',
      zh: '针对需要更多灵活性的中小型团队而设计。 包括AI内容生成、最多10个项目和20个组织用户。',
      it: 'Progettato per team piccoli e medi che necessitano di maggiore flessibilità. Include generazione di contenuti AI, fino a 10 progetti e 20 utenti dell’organizzazione.',
      pt: 'Projetado para equipes pequenas a médias que precisam de mais flexibilidade. Inclui geração de conteúdo de IA, até 10 projetos e 20 usuários da organização.',
      hi: 'छोटे से मध्यम दलों के लिए डिज़ाइन किया गया जो अधिक लचीलापन चाहते हैं। इसमें AI सामग्री निर्माण, 10 तक परियोजनाएँ और 20 संगठन उपयोगकर्ता शामिल हैं।',
      ar: 'مصمم للفرق الصغيرة والمتوسطة التي تحتاج إلى مزيد من المرونة. يتضمن إنشاء محتوى مدفوع بالذكاء الاصطناعي، يصل إلى 10 مشاريع، و20 مستخدمًا للمنظمة.',
      ru: 'Разработан для небольших и средних команд, которым требуется больше гибкости. Включает генерацию контента на основе ИИ, до 10 проектов и 20 пользовательских организаций.',
      tr: 'Daha fazla esneklik gerektiren küçük ve orta ölçekli ekipler için tasarlanmıştır. AI içerik oluşturma, 10 projeye kadar ve 20 organizasyon kullanıcısı içerir.',
      pl: 'Przeznaczony dla małych i średnich zespołów potrzebujących większej elastyczności. Zawiera generowanie treści wspomagane przez AI, do 10 projektów i 20 użytkowników organizacji.',
      id: 'Dirancang untuk tim kecil hingga menengah yang membutuhkan fleksibilitas lebih. Termasuk pembuatan konten berbasis AI, hingga 10 proyek, dan 20 pengguna organisasi.',
      vi: 'Được thiết kế cho các đội nhỏ tới vừa cần nhiều tính linh hoạt hơn. Bao gồm tạo nội dung bằng AI, tối đa 10 dự án và 20 người dùng tổ chức.',
      uk: 'Призначений для малих та середніх команд, яким потрібна більша гнучкість. Включає генерацію контенту на базі ШІ, до 10 проектів та 20 користувачів організації.',
    }),
    checkPoint: t({
      en: [
        'Access to all Intlayer packages',
        'Unlimited usage of the visual editor',
        'Unlimited distant dictionaries',
        '500 Mb of storage',
        '10 projects',
        '20 organization users',
        'AI powered content generation',
        'Premium support',
      ],
      fr: [
        'Accès à tous les packages Intlayer',
        'Utilisation illimitée de l’éditeur visuel',
        'Dictionnaires distants illimités',
        '500 Mo de stockage',
        '10 projets',
        '20 utilisateurs d’organisation',
        'Génération de contenu IA',
        'Support premium',
      ],
      es: [
        'Acceso a todos los paquetes de Intlayer',
        'Uso ilimitado del editor visual',
        'Diccionarios distantes ilimitados',
        '500 Mb de almacenamiento',
        '10 proyectos',
        '20 usuarios de la organización',
        'Generación de contenido IA',
        'Soporte premium',
      ],
      'en-GB': [
        'Access to all Intlayer packages',
        'Unlimited usage of the visual editor',
        'Unlimited distant dictionaries',
        '500 Mb of storage',
        '10 projects',
        '20 organization users',
        'AI powered content generation',
        'Premium support',
      ],
      de: [
        'Zugriff auf alle Intlayer-Pakete',
        'Unbegrenzte Nutzung des visuellen Editors',
        'Unbegrenzte entfernte Wörterbücher',
        '500 MB Speicher',
        '10 Projekte',
        '20 Organisationsbenutzer',
        'KI-gestützte Inhaltsgenerierung',
        'Premium-Support',
      ],
      ja: [
        'すべてのIntlayerパッケージにアクセス',
        'ビジュアルエディタの無制限使用',
        '無制限の遠隔辞書',
        '500 MBのストレージ',
        '10プロジェクト',
        '20組織ユーザー',
        'AI駆動のコンテンツ生成',
        'プレミアムサポート',
      ],
      ko: [
        '모든 Intlayer 패키지에 액세스',
        '비주얼 편집기를 무제한으로 사용',
        '무제한 원격 사전',
        '500MB의 저장 공간',
        '10 프로젝트',
        '20 조직 사용자',
        'AI 기반 콘텐츠 생성',
        '프리미엄 지원',
      ],
      zh: [
        '访问所有Intlayer程序包',
        '无限使用可视化编辑器',
        '无限远程字典',
        '500MB存储',
        '10个项目',
        '20个组织用户',
        'AI驱动的内容生成',
        '专业支持',
      ],
      it: [
        'Accesso a tutti i pacchetti Intlayer',
        'Utilizzo illimitato dell’editor visivo',
        'Dizionari remoti illimitati',
        '500 Mb di spazio di archiviazione',
        '10 progetti',
        '20 utenti dell’organizzazione',
        'Generazione di contenuti AI',
        'Supporto premium',
      ],
      pt: [
        'Acesso a todos os pacotes Intlayer',
        'Uso ilimitado do editor visual',
        'Dicionários remotos ilimitados',
        '500 Mb de armazenamento',
        '10 projetos',
        '20 usuários da organização',
        'Geração de conteúdo de IA',
        'Suporte premium',
      ],
      hi: [
        'सभी Intlayer पैकेजों तक पहुँच',
        'दृश्य संपादक का असीमित उपयोग',
        'असीमित दूरस्थ शब्दकोश',
        '500MB भंडारण',
        '10 परियोजनाएँ',
        '20 संगठन उपयोगकर्ता',
        'AI द्वारा संचालित सामग्री निर्माण',
        'प्रीमियम समर्थन',
      ],
      ar: [
        'الوصول إلى جميع حزم Intlayer',
        'استخدام غير محدود للمحرر المرئي',
        'قواميس بعيدة غير محدودة',
        '500 ميغابايت من التخزين',
        '10 مشاريع',
        '20 مستخدم منظمة',
        'إنشاء محتوى مدفوع بالذكاء الاصطناعي',
        'دعم متميز',
      ],
      ru: [
        'Доступ ко всем пакетам Intlayer',
        'Неограниченное использование визуального редактора',
        'Неограниченные удаленные словари',
        '500 Мб памяти',
        '10 проектов',
        '20 пользователей организации',
        'Генерация контента с поддержкой ИИ',
        'Премиум поддержка',
      ],
      tr: [
        'Tüm Intlayer paketlerine erişim',
        'Görsel düzenleyicinin sınırsız kullanımı',
        'Sınırsız uzak sözlükler',
        '500 Mb depolama',
        '10 proje',
        '20 organizasyon kullanıcısı',
        'AI destekli içerik oluşturma',
        'Premium destek',
      ],
      pl: [
        'Dostęp do wszystkich pakietów Intlayer',
        'Nieograniczone korzystanie z edytora wizualnego',
        'Nieograniczone zdalne słowniki',
        '500 MB pamięci',
        '10 projektów',
        '20 użytkowników organizacji',
        'Generowanie treści wspomagane przez AI',
        'Wsparcie Premium',
      ],
      id: [
        'Akses ke semua paket Intlayer',
        'Penggunaan editor visual tanpa batas',
        'Kamus jarak jauh tanpa batas',
        '500 MB penyimpanan',
        '10 proyek',
        '20 pengguna organisasi',
        'Pembuatan konten didukung AI',
        'Dukungan premium',
      ],
      vi: [
        'Truy cập tất cả các gói Intlayer',
        'Sử dụng trình chỉnh sửa trực quan không giới hạn',
        'Từ điển từ xa không giới hạn',
        '500 MB dung lượng lưu trữ',
        '10 dự án',
        '20 người dùng tổ chức',
        'Tạo nội dung bằng AI',
        'Hỗ trợ Premium',
      ],
      uk: [
        'Доступ до всіх пакетів Intlayer',
        'Необмежене використання візуального редактора',
        'Необмежені віддалені словники',
        '500 МБ сховища',
        '10 проектів',
        '20 користувачів організації',
        'Генерація контенту на базі ШІ',
        'Преміальна підтримка',
      ],
    }),
  },
  enterprise: {
    title: t({
      en: 'Enterprise',
      fr: 'Entreprise',
      es: 'Empresa',
      'en-GB': 'Enterprise',
      de: 'Unternehmen',
      ja: 'エンタープライズ',
      ko: '기업',
      zh: '企业',
      it: 'Enterprise',
      pt: 'Empresarial',
      hi: 'एंटरप्राइज',
      ar: 'مؤسسة',
      ru: 'Корпоративный',
      tr: 'Kurumsal',
      pl: 'Enterprise',
      id: 'Enterprise',
      vi: 'Enterprise',
      uk: 'Корпоративний',
    }),
    description: t({
      en: 'Built for larger teams requiring advanced tools. Get unlimited projects, AI-powered SEO, and content generation with unlimited users.',
      fr: 'Conçu pour les grandes équipes nécessitant des outils avancés. Profitez de projets illimités, SEO IA, et génération de contenu avec utilisateurs illimités.',
      es: 'Diseñado para equipos grandes que requieren herramientas avanzadas. Obtén proyectos ilimitados, SEO IA, y generación de contenido con usuarios ilimitados.',
      'en-GB':
        'Built for larger teams requiring advanced tools. Get unlimited projects, AI-powered SEO, and content generation with unlimited users.',
      de: 'Für größere Teams, die fortschrittliche Tools benötigen. Erhalten Sie unbegrenzte Projekte, KI-unterstützte SEO und Inhaltsgenerierung mit unbegrenzten Benutzern.',
      ja: '高度なツールを必要とする大規模なチーム向けに構築されています。 無制限のプロジェクト、AI対応のSEO、無制限のユーザーを持つコンテンツ生成を取得します。',
      ko: '고급 도구가 필요한 대규모 팀을 위해 구축되었습니다. 무제한 프로젝트, AI 기반 SEO 및 무제한 사용자가 포함된 콘텐츠 생성을 받습니다.',
      zh: '专为需要先进工具的大型团队构建。 获取无限项目、AI支持的SEO和具有无限用户的内容生成。',
      it: 'Creato per team numerosi che richiedono strumenti avanzati. Ottieni progetti illimitati, SEO potenziato dall’IA e generazione di contenuti con utenti illimitati.',
      pt: 'Construído para equipes maiores que precisam de ferramentas avançadas. Obtenha projetos ilimitados, SEO movido por IA e geração de conteúdo com usuários ilimitados.',
      hi: 'उन्नत उपकरणों की आवश्यकता वाले बड़े टीमों के लिए निर्मित। असीमित परियोजनाएँ, एआई-समर्थित एसईओ और असीमित उपयोगकर्ताओं के साथ सामग्री निर्माण प्राप्त करें।',
      ar: 'بناءً للفرق الكبيرة التي تتطلب أدوات متقدمة. احصل على مشاريع غير محدودة ، وتحسين محركات البحث المعتمد على الذكاء الاصطناعي ، وإنشاء محتوى مع مستخدمين غير محدودين.',
      ru: 'Создано для крупных команд, которым требуются современные инструменты. Получите неограниченное количество проектов, SEO с поддержкой ИИ и создание контента с неограниченным числом пользователей.',
      tr: 'Daha büyük ekipler için tasarlanmıştır ve gelişmiş araçlar gerektirir. Sınırsız projeler, AI destekli SEO ve sınırsız kullanıcı ile içerik oluşturma elde edin.',
      pl: 'Stworzony dla większych zespołów wymagających zaawansowanych narzędzi. Oferuje nieograniczone projekty, optymalizację SEO wspomaganą przez AI oraz generowanie treści dla nieograniczonej liczby użytkowników.',
      id: 'Dirancang untuk tim besar yang membutuhkan alat lanjutan. Dapatkan proyek tanpa batas, SEO bertenaga AI, dan pembuatan konten dengan pengguna tanpa batas.',
      vi: 'Dành cho các nhóm lớn cần công cụ nâng cao. Có dự án không giới hạn, AI powered SEO và AI powered content generation với số lượng người dùng không giới hạn.',
      uk: 'Створено для більших команд, які потребують розширених інструментів. Отримайте необмежену кількість проєктів, SEO на основі ШІ та генерацію контенту з необмеженою кількістю користувачів.',
    }),
    checkPoint: t({
      en: [
        'Access to all Intlayer packages',
        'Unlimited usage of the visual editor',
        'Unlimited distant dictionaries',
        '2+ Gb of storage',
        'Unlimited projects',
        'Unlimited organization users',
        'AI powered content generation',
        'AI powered SEO optimization',
        'Hot reloading for client and server side content',
        'Premium support',
      ],
      fr: [
        'Accès à tous les packages Intlayer',
        'Utilisation illimitée de l’éditeur visuel',
        'Dictionnaires distants illimités',
        '2+ Go de stockage',
        'Projets illimités',
        'Utilisateurs d’organisation illimités',
        'Génération de contenu IA',
        'Optimisation SEO IA',
        'Rechargement à chaud du contenu côté client et serveur',
        'Support premium',
      ],
      es: [
        'Acceso a todos los paquetes de Intlayer',
        'Uso ilimitado del editor visual',
        'Diccionarios distantes ilimitados',
        '2+ Gb de almacenamiento',
        'Proyectos ilimitados',
        'Usuarios de la organización ilimitados',
        'Generación de contenido IA',
        'Optimización SEO IA',
        'Recarga rápida por el contenido del lado del cliente y servidor',
        'Soporte premium',
      ],
      'en-GB': [
        'Access to all Intlayer packages',
        'Unlimited usage of the visual editor',
        'Unlimited distant dictionaries',
        '2+ Gb of storage',
        'Unlimited projects',
        'Unlimited organization users',
        'AI powered content generation',
        'AI powered SEO optimization',
        'Hot reloading for client and server side content',
        'Premium support',
      ],
      de: [
        'Zugriff auf alle Intlayer-Pakete',
        'Unbegrenzte Nutzung des visuellen Editors',
        'Unbegrenzte entfernte Wörterbücher',
        '2+ GB Speicher',
        'Unbegrenzt Projekte',
        'Unbegrenzte Benutzer für Organisationen',
        'KI-gestützte Inhaltsgenerierung',
        'Optimierung von SEO mit KI',
        'Hot Reloading für Client- und Serverseitige Inhalte',
        'Premium-Support',
      ],
      ja: [
        'すべてのIntlayerパッケージにアクセス',
        'ビジュアルエディタの無制限使用',
        '無制限の遠隔辞書',
        '2+ Gbのストレージ',
        '無制限のプロジェクト',
        '無制限の組織ユーザー',
        'AIによるコンテンツ生成',
        'AIによるSEO最適化',
        'クライアントとサーバーサイドのホットリローディング',
        'プレミアムサポート',
      ],
      ko: [
        '모든 Intlayer 패키지에 액세스',
        '비주얼 편집기를 무제한으로 사용',
        '무제한 원격 사전',
        '2+GB의 저장 공간',
        '무제한 프로젝트',
        '무제한 조직 사용자',
        'AI 기반 콘텐츠 생성',
        'AI 기반 SEO 최적화',
        '클라이언트와 서버 사이드 핫 로드',
        '프리미엄 지원',
      ],
      zh: [
        '访问所有Intlayer程序包',
        '无限使用可视化编辑器',
        '无限远程字典',
        '2+ GB存储',
        '无限项目',
        '无限组织用户',
        'AI驱动的内容生成',
        'AI驱动的SEO优化',
        '客户端和服务端的热重载',
        '专业支持',
      ],
      it: [
        'Accesso a tutti i pacchetti Intlayer',
        'Utilizzo illimitato dell’editor visivo',
        'Dizionari remoti illimitati',
        '2+ GB di spazio di archiviazione',
        'Progetti illimitati',
        'Utenti illimitati per l’organizzazione',
        'Generazione di contenuti AI',
        'Ottimizzazione SEO basata su AI',
        'Aggiornamento rapido per il contenuto lato client e server',
        'Supporto premium',
      ],
      pt: [
        'Acesso a todos os pacotes Intlayer',
        'Uso ilimitado do editor visual',
        'Dicionários remotos ilimitados',
        '2+ GB de armazenamento',
        'Projetos ilimitados',
        'Usuários ilimitados da organização',
        'Geração de conteúdo com IA',
        'Otimização de SEO com IA',
        'Recarregamento rápido para o conteúdo do lado do cliente e servidor',
        'Suporte premium',
      ],
      hi: [
        'सभी Intlayer पैकेजों तक पहुँच',
        'दृश्य संपादक का असीमित उपयोग',
        'असीमित दूरस्थ शब्दकोश',
        '2+ जीबी संग्रहण',
        'असीमित परियोजनाएँ',
        'असीमित संगठन उपयोगकर्ता',
        'AI द्वारा संचालित सामग्री निर्माण',
        'AI द्वारा संचालित SEO ऑप्टिमाइजेशन',
        'क्लाइंट और सर्वर साइड के लिए हॉट रीलोड',
        'प्रीमियम समर्थन',
      ],
      ar: [
        'الوصول إلى جميع حزم Intlayer',
        'استخدام غير محدود للمحرر المرئي',
        'قواميس بعيدة غير محدودة',
        '2+ غيغابايت من التخزين',
        'مشاريع غير محدودة',
        'مستخدمون غير محدودون للمنظمة',
        'إنشاء محتوى مدعوم بالذكاء الاصطناعي',
        'تحسين محركات البحث المدعوم بالذكاء الاصطناعي',
        'التحديث السريع للمحتوى على الجانب العميل والجانب الخادم',
        'دعم متميز',
      ],
      ru: [
        'Доступ ко всем пакетам Intlayer',
        'Неограниченное использование визуального редактора',
        'Неограниченные удаленные словари',
        '2+ Гб хранилища',
        'Неограниченное количество проектов',
        'Неограниченное количество пользователей организации',
        'Генерация контента с поддержкой ИИ',
        'Оптимизация SEO с поддержкой ИИ',
        'Быстрое обновление для контента на клиенте и сервере',
        'Премиум поддержка',
      ],
      tr: [
        'Tüm Intlayer paketlerine erişim',
        'Görsel düzenleyicinin sınırsız kullanımı',
        'Sınırsız uzak sözlükler',
        '2+ Gb depolama',
        'Sınırsız projeler',
        'Sınırsız organizasyon kullanıcıları',
        'AI destekli içerik oluşturma',
        'AI destekli SEO optimizasyonu',
        'İstemci ve sunucu tarafı içerik için sıcak yeniden yükleme',
        'Premium destek',
      ],
      pl: [
        null,
        null,
        'Nieograniczone zdalne słowniki',
        'Ponad 2 GB miejsca',
        'Nieograniczona liczba projektów',
        'Nieograniczona liczba użytkowników organizacji',
        'Generowanie treści wspomagane przez AI',
        'Optymalizacja SEO wspomagana przez AI',
        'Hot reloading dla treści po stronie klienta i serwera',
        'Wsparcie premium',
      ],
      id: [
        'Akses ke semua paket Intlayer',
        'Penggunaan editor visual tanpa batas',
        'Kamus jarak jauh tanpa batas',
        'Penyimpanan lebih dari 2 GB',
        'Proyek tanpa batas',
        'Pengguna organisasi tanpa batas',
        'Pembuatan konten bertenaga AI',
        'Optimisasi SEO bertenaga AI',
        'Hot reloading untuk konten sisi klien dan server',
        'Dukungan premium',
      ],
      vi: [
        'Truy cập tất cả các gói Intlayer',
        'Sử dụng visual editor không giới hạn',
        'Sử dụng distant dictionaries không giới hạn',
        'Trên 2 GB dung lượng lưu trữ',
        'Dự án không giới hạn',
        'Số người dùng tổ chức không giới hạn',
        'AI powered content generation',
        'AI powered SEO optimization',
        'Hot reloading cho nội dung phía client và server',
        'Hỗ trợ Premium',
      ],
      uk: [
        'Доступ до всіх пакетів Intlayer',
        'Необмежене використання візуального редактора',
        'Необмежені віддалені словники',
        'Понад 2 ГБ сховища',
        'Необмежена кількість проєктів',
        'Необмежена кількість користувачів організації',
        'Генерація контенту на основі ШІ',
        'SEO-оптимізація на основі ШІ',
        'Гаряче перезавантаження контенту на стороні клієнта й сервера',
        'Преміум-підтримка',
      ],
    }),
  },
  lifetime: {
    title: t({
      en: 'Lifetime',
      fr: 'À vie',
      es: 'De por vida',
      'en-GB': 'Lifetime',
      de: 'Lebenslang',
      ja: 'ライフタイム',
      ko: '평생',
      zh: '终身',
      it: 'A vita',
      pt: 'Vitalício',
      hi: 'आजीवन',
      ar: 'مدى الحياة',
      ru: 'Пожизненно',
      tr: 'Ömür Boyu',
      pl: 'Dożywotni',
      id: 'Seumur Hidup',
      vi: 'Trọn đời',
      uk: 'Довічний',
    }),
    badge: t({
      en: 'Limited time offer',
      fr: 'Offre limitée',
      es: 'Oferta por tiempo limitado',
      'en-GB': 'Limited time offer',
      de: 'Zeitlich begrenztes Angebot',
      ja: '期間限定オファー',
      ko: '한정 기간 제공',
      zh: '限时优惠',
      it: 'Offerta a tempo limitato',
      pt: 'Oferta por tempo limitado',
      hi: 'सीमित समय की पेशकश',
      ar: 'عرض لفترة محدودة',
      ru: 'Ограниченное предложение',
      tr: 'Sınırlı süreli teklif',
      pl: 'Oferta ograniczona czasowo',
      id: 'Penawaran terbatas',
      vi: 'Ưu đãi có thời hạn',
      uk: 'Обмежена пропозиція',
    }),
    description: t({
      en: 'Limited time offer: pay once, use forever. Includes everything in the Enterprise plan with no recurring fees.',
      fr: 'Offre limitée dans le temps : payez une fois, utilisez à vie. Inclut tout ce que contient le plan Entreprise sans frais récurrents.',
      es: 'Oferta por tiempo limitado: paga una vez, úsalo para siempre. Incluye todo lo del plan Empresa sin pagos recurrentes.',
      'en-GB':
        'Limited time offer: pay once, use forever. Includes everything in the Enterprise plan with no recurring fees.',
      de: 'Zeitlich begrenztes Angebot: einmal bezahlen, lebenslang nutzen. Beinhaltet alle Funktionen des Enterprise-Plans ohne wiederkehrende Gebühren.',
      ja: '期間限定オファー：一度の支払いで永久に利用可能。エンタープライズプランのすべての機能を、定期費用なしで利用できます。',
      ko: '한정 기간 제공: 한 번만 결제하고 평생 사용하세요. 정기 결제 없이 엔터프라이즈 플랜의 모든 기능을 포함합니다.',
      zh: '限时优惠：一次付款，永久使用。包含企业版的所有功能，无需定期付费。',
      it: 'Offerta a tempo limitato: paghi una volta, usi per sempre. Include tutto il piano Enterprise senza costi ricorrenti.',
      pt: 'Oferta por tempo limitado: pague uma vez, use para sempre. Inclui tudo do plano Empresarial sem mensalidades.',
      hi: 'सीमित समय की पेशकश: एक बार भुगतान करें, हमेशा उपयोग करें। एंटरप्राइज़ प्लान की सभी सुविधाएँ बिना किसी आवर्ती शुल्क के शामिल हैं।',
      ar: 'عرض لفترة محدودة: ادفع مرة واحدة، واستخدمه إلى الأبد. يشمل كل ما في خطة الشركات بدون رسوم متكررة.',
      ru: 'Ограниченное по времени предложение: оплатите один раз — пользуйтесь всю жизнь. Включает всё из корпоративного плана без повторяющихся платежей.',
      tr: 'Sınırlı süreli teklif: bir kez ödeyin, ömür boyu kullanın. Kurumsal planın tüm özelliklerini tekrarlayan ödeme olmadan içerir.',
      pl: 'Oferta ograniczona czasowo: zapłać raz, korzystaj na zawsze. Zawiera wszystko z planu Enterprise bez opłat cyklicznych.',
      id: 'Penawaran terbatas: bayar sekali, gunakan selamanya. Termasuk semua fitur paket Enterprise tanpa biaya berlangganan.',
      vi: 'Ưu đãi có thời hạn: thanh toán một lần, dùng trọn đời. Bao gồm mọi thứ trong gói Enterprise mà không có phí định kỳ.',
      uk: 'Обмежена в часі пропозиція: оплатіть один раз — користуйтеся назавжди. Включає все з Enterprise без періодичних платежів.',
    }),
    checkPoint: t({
      en: [
        'One-time payment, lifetime access',
        'Access to all Intlayer packages',
        'Unlimited usage of the visual editor',
        'Unlimited distant dictionaries',
        '2+ Gb of storage',
        'Unlimited projects',
        'Unlimited organization users',
        'AI powered content generation',
        'AI powered SEO optimization',
        'Hot reloading for client and server side content',
        'Premium support',
      ],
      fr: [
        'Paiement unique, accès à vie',
        'Accès à tous les packages Intlayer',
        'Utilisation illimitée de l’éditeur visuel',
        'Dictionnaires distants illimités',
        '2+ Go de stockage',
        'Projets illimités',
        'Utilisateurs d’organisation illimités',
        'Génération de contenu IA',
        'Optimisation SEO IA',
        'Rechargement à chaud du contenu côté client et serveur',
        'Support premium',
      ],
      es: [
        'Pago único, acceso de por vida',
        'Acceso a todos los paquetes de Intlayer',
        'Uso ilimitado del editor visual',
        'Diccionarios distantes ilimitados',
        '2+ Gb de almacenamiento',
        'Proyectos ilimitados',
        'Usuarios de la organización ilimitados',
        'Generación de contenido IA',
        'Optimización SEO IA',
        'Recarga rápida por el contenido del lado del cliente y servidor',
        'Soporte premium',
      ],
      'en-GB': [
        'One-time payment, lifetime access',
        'Access to all Intlayer packages',
        'Unlimited usage of the visual editor',
        'Unlimited distant dictionaries',
        '2+ Gb of storage',
        'Unlimited projects',
        'Unlimited organization users',
        'AI powered content generation',
        'AI powered SEO optimization',
        'Hot reloading for client and server side content',
        'Premium support',
      ],
      de: [
        'Einmalige Zahlung, lebenslanger Zugriff',
        'Zugriff auf alle Intlayer-Pakete',
        'Unbegrenzte Nutzung des visuellen Editors',
        'Unbegrenzte entfernte Wörterbücher',
        '2+ GB Speicher',
        'Unbegrenzt Projekte',
        'Unbegrenzte Benutzer für Organisationen',
        'KI-gestützte Inhaltsgenerierung',
        'KI-gestützte SEO-Optimierung',
        'Hot Reloading für Client- und serverseitige Inhalte',
        'Premium-Support',
      ],
      ja: [
        '一括払い、永久アクセス',
        'すべてのIntlayerパッケージにアクセス',
        'ビジュアルエディタの無制限使用',
        '無制限の遠隔辞書',
        '2+ GBのストレージ',
        '無制限のプロジェクト',
        '無制限の組織ユーザー',
        'AIによるコンテンツ生成',
        'AIによるSEO最適化',
        'クライアントとサーバーサイドのホットリローディング',
        'プレミアムサポート',
      ],
      ko: [
        '한 번 결제, 평생 사용',
        '모든 Intlayer 패키지에 액세스',
        '비주얼 편집기 무제한 사용',
        '무제한 원격 사전',
        '2+GB의 저장 공간',
        '무제한 프로젝트',
        '무제한 조직 사용자',
        'AI 기반 콘텐츠 생성',
        'AI 기반 SEO 최적화',
        '클라이언트 및 서버 사이드 핫 리로드',
        '프리미엄 지원',
      ],
      zh: [
        '一次付款，终身使用',
        '访问所有Intlayer程序包',
        '无限使用可视化编辑器',
        '无限远程字典',
        '2+ GB存储',
        '无限项目',
        '无限组织用户',
        'AI驱动的内容生成',
        'AI驱动的SEO优化',
        '客户端和服务端的热重载',
        '专业支持',
      ],
      it: [
        'Pagamento unico, accesso a vita',
        'Accesso a tutti i pacchetti Intlayer',
        'Utilizzo illimitato dell’editor visivo',
        'Dizionari remoti illimitati',
        '2+ GB di spazio di archiviazione',
        'Progetti illimitati',
        'Utenti illimitati per l’organizzazione',
        'Generazione di contenuti AI',
        'Ottimizzazione SEO basata su AI',
        'Aggiornamento rapido per il contenuto lato client e server',
        'Supporto premium',
      ],
      pt: [
        'Pagamento único, acesso vitalício',
        'Acesso a todos os pacotes Intlayer',
        'Uso ilimitado do editor visual',
        'Dicionários remotos ilimitados',
        '2+ GB de armazenamento',
        'Projetos ilimitados',
        'Usuários ilimitados da organização',
        'Geração de conteúdo com IA',
        'Otimização de SEO com IA',
        'Recarregamento rápido para conteúdo do lado do cliente e servidor',
        'Suporte premium',
      ],
      hi: [
        'एक बार भुगतान, आजीवन उपयोग',
        'सभी Intlayer पैकेजों तक पहुँच',
        'दृश्य संपादक का असीमित उपयोग',
        'असीमित दूरस्थ शब्दकोश',
        '2+ जीबी संग्रहण',
        'असीमित परियोजनाएँ',
        'असीमित संगठन उपयोगकर्ता',
        'AI द्वारा संचालित सामग्री निर्माण',
        'AI द्वारा संचालित SEO ऑप्टिमाइजेशन',
        'क्लाइंट और सर्वर साइड के लिए हॉट रीलोड',
        'प्रीमियम समर्थन',
      ],
      ar: [
        'دفعة واحدة، وصول مدى الحياة',
        'الوصول إلى جميع حزم Intlayer',
        'استخدام غير محدود للمحرر المرئي',
        'قواميس بعيدة غير محدودة',
        '2+ غيغابايت من التخزين',
        'مشاريع غير محدودة',
        'مستخدمون غير محدودون للمنظمة',
        'إنشاء محتوى مدعوم بالذكاء الاصطناعي',
        'تحسين محركات البحث المدعوم بالذكاء الاصطناعي',
        'التحديث السريع للمحتوى من الجانب العميل والجانب الخادم',
        'دعم متميز',
      ],
      ru: [
        'Единоразовый платёж, пожизненный доступ',
        'Доступ ко всем пакетам Intlayer',
        'Неограниченное использование визуального редактора',
        'Неограниченные удалённые словари',
        '2+ Гб хранилища',
        'Неограниченное количество проектов',
        'Неограниченное количество пользователей организации',
        'Генерация контента с поддержкой ИИ',
        'Оптимизация SEO с поддержкой ИИ',
        'Быстрое обновление для контента на клиенте и сервере',
        'Премиум поддержка',
      ],
      tr: [
        'Tek seferlik ödeme, ömür boyu erişim',
        'Tüm Intlayer paketlerine erişim',
        'Görsel düzenleyicinin sınırsız kullanımı',
        'Sınırsız uzak sözlükler',
        '2+ Gb depolama',
        'Sınırsız projeler',
        'Sınırsız organizasyon kullanıcıları',
        'AI destekli içerik oluşturma',
        'AI destekli SEO optimizasyonu',
        'İstemci ve sunucu tarafı içerik için sıcak yeniden yükleme',
        'Premium destek',
      ],
      pl: [
        'Jednorazowa płatność, dożywotni dostęp',
        'Dostęp do wszystkich pakietów Intlayer',
        'Nieograniczone korzystanie z edytora wizualnego',
        'Nieograniczone zdalne słowniki',
        'Ponad 2 GB miejsca',
        'Nieograniczona liczba projektów',
        'Nieograniczona liczba użytkowników organizacji',
        'Generowanie treści wspomagane przez AI',
        'Optymalizacja SEO wspomagana przez AI',
        'Hot reloading dla treści po stronie klienta i serwera',
        'Wsparcie premium',
      ],
      id: [
        'Bayar sekali, akses seumur hidup',
        'Akses ke semua paket Intlayer',
        'Penggunaan editor visual tanpa batas',
        'Kamus jarak jauh tanpa batas',
        'Penyimpanan lebih dari 2 GB',
        'Proyek tanpa batas',
        'Pengguna organisasi tanpa batas',
        'Pembuatan konten bertenaga AI',
        'Optimisasi SEO bertenaga AI',
        'Hot reloading untuk konten sisi klien dan server',
        'Dukungan premium',
      ],
      vi: [
        'Thanh toán một lần, dùng trọn đời',
        'Truy cập tất cả các gói Intlayer',
        'Sử dụng visual editor không giới hạn',
        'Sử dụng distant dictionaries không giới hạn',
        'Trên 2 GB dung lượng lưu trữ',
        'Dự án không giới hạn',
        'Số người dùng tổ chức không giới hạn',
        'Tạo nội dung bằng AI',
        'Tối ưu SEO bằng AI',
        'Hot reloading cho nội dung phía client và server',
        'Hỗ trợ Premium',
      ],
      uk: [
        'Одноразова оплата, довічний доступ',
        'Доступ до всіх пакетів Intlayer',
        'Необмежене використання візуального редактора',
        'Необмежені віддалені словники',
        'Понад 2 ГБ сховища',
        'Необмежена кількість проєктів',
        'Необмежена кількість користувачів організації',
        'Генерація контенту на основі ШІ',
        'SEO-оптимізація на основі ШІ',
        'Гаряче перезавантаження контенту на стороні клієнта й сервера',
        'Преміум-підтримка',
      ],
    }),
  },
  custom: {
    title: t({
      en: 'Custom',
      fr: 'Sur mesure',
      es: 'Personalizado',
      'en-GB': 'Custom',
      de: 'Benutzerdefiniert',
      ja: 'カスタム',
      ko: '커스텀',
      zh: '自定义',
      it: 'Personalizzato',
      pt: 'Personalizado',
      hi: 'कस्टम',
      ar: 'مخصص',
      ru: 'Индивидуальный',
      tr: 'Özel',
      pl: 'Niestandardowy',
      id: 'Kustom',
      vi: 'Tùy chỉnh',
      uk: 'Індивідуальний',
    }),
    description: t({
      en: 'Tailored implementation for your organization. Can include self-hosting and custom setup.',
      fr: 'Mise en œuvre sur mesure pour votre organisation. Peut inclure l’auto-hébergement et une configuration personnalisée.',
      es: 'Implementación a medida para su organización. Puede incluir autohospedaje y configuración personalizada.',
      'en-GB':
        'Tailored implementation for your organization. Can include self-hosting and custom setup.',
      de: 'Maßgeschneiderte Implementierung für Ihr Unternehmen. Kann Self-Hosting und benutzerdefiniertes Setup beinhalten.',
      ja: '組織に合わせたオーダーメイドの導入。セルフホスティングやカスタムセットアップも可能です。',
      ko: '조직에 맞춘 맞춤형 구현. 셀프 호스팅 및 맞춤형 설정이 포함될 수 있습니다.',
      zh: '为您的组织量身定制的实施。可以包括自托管和自定义设置。',
      it: 'Implementazione su misura per la tua organizzazione. Può includere l’auto-hosting e la configurazione personalizzata.',
      pt: 'Implementação personalizada para a sua organização. Pode incluir auto-hospedagem e configuração personalizada.',
      hi: 'आपके संगठन के लिए अनुकूलित कार्यान्वयन। इसमें स्व-होस्टिंग और कस्टम सेटअप शामिल हो सकते हैं।',
      ar: 'تنفيذ مخصص لمؤسستك. يمكن أن يشمل الاستضافة الذاتية والإعداد المخصص.',
      ru: 'Индивидуальное внедрение для вашей организации. Может включать селф-хостинг и индивидуальную настройку.',
      tr: 'Kuruluşunuz için özel uygulama. Kendi kendine barındırma ve özel kurulum içerebilir.',
      pl: 'Wdrożenie szyte na miarę dla Twojej organizacji. Może obejmować własny hosting i niestandardową konfigurację.',
      id: 'Implementasi yang disesuaikan untuk organisasi Anda. Dapat mencakup hosting mandiri dan pengaturan khusus.',
      vi: 'Triển khai tùy chỉnh cho tổ chức của bạn. Có thể bao gồm tự lưu trữ và thiết lập tùy chỉnh.',
      uk: 'Індивідуальне впровадження для вашої організації. Може включати self-hosting та індивідуальне налаштування.',
    }),
    checkPoint: t({
      en: [
        'Self-hosting options',
        'Access to all Intlayer packages',
        'Unlimited usage of the visual editor',
        'Unlimited distant dictionaries',
        'Custom setup & integration',
        'Dedicated support',
        'Tailored features',
        'Unlimited projects',
        'Unlimited users',
      ],
      fr: [
        'Options d’auto-hébergement',
        'Accès à tous les packages Intlayer',
        'Utilisation illimitée de l’éditeur visuel',
        'Dictionnaires distants illimités',
        'Configuration et intégration sur mesure',
        'Support dédié',
        'Fonctionnalités adaptées',
        'Projets illimités',
        'Utilisateurs illimités',
      ],
      es: [
        'Opciones de autohospedaje',
        'Acceso a todos los paquetes de Intlayer',
        'Uso ilimitado del editor visual',
        'Diccionarios distantes ilimitados',
        'Configuración e integración a medida',
        'Soporte dedicado',
        'Funcionalidades adaptadas',
        'Proyectos ilimitados',
        'Usuarios ilimitados',
      ],
      'en-GB': [
        'Self-hosting options',
        'Access to all Intlayer packages',
        'Unlimited usage of the visual editor',
        'Unlimited distant dictionaries',
        'Custom setup & integration',
        'Dedicated support',
        'Tailored features',
        'Unlimited projects',
        'Unlimited users',
      ],
      de: [
        'Self-Hosting-Optionen',
        'Zugriff auf alle Intlayer-Pakete',
        'Unbegrenzte Nutzung des visuellen Editors',
        'Unbegrenzte entfernte Wörterbücher',
        'Benutzerdefiniertes Setup & Integration',
        'Engagierter Support',
        'Maßgeschneiderte Funktionen',
        'Unbegrenzte Projekte',
        'Unbegrenzte Benutzer',
      ],
      ja: [
        'セルフホスティングオプション',
        'すべてのIntlayerパッケージへのアクセス',
        'ビジュアルエディターの無制限利用',
        '無制限のリモート辞書',
        'カスタムセットアップと統合',
        '専用サポート',
        'オーダーメイド機能',
        '無制限のプロジェクト',
        '無制限のユーザー',
      ],
      ko: [
        '셀프 호스팅 옵션',
        '모든 Intlayer 패키지에 대한 액세스',
        '비주얼 에디터 무제한 사용',
        '무제한 원격 사전',
        '맞춤형 설정 및 통합',
        '전담 지원',
        '맞춤형 기능',
        '무제한 프로젝트',
        '무제한 사용자',
      ],
      zh: [
        '自托管选项',
        '访问所有 Intlayer 包',
        '无限使用可视化编辑器',
        '无限远程字典',
        '自定义设置与集成',
        '专属支持',
        '量身定制的功能',
        '无限项目',
        '无限用户',
      ],
      it: [
        'Opzioni di auto-hosting',
        'Accesso a tutti i pacchetti Intlayer',
        'Uso illimitato dell’editor visivo',
        'Dizionari remoti illimitati',
        'Configurazione e integrazione su misura',
        'Supporto dedicato',
        'Funzionalità personalizzate',
        'Progetti illimitati',
        'Utenti illimitati',
      ],
      pt: [
        'Opções de auto-hospedagem',
        'Acesso a todos os pacotes Intlayer',
        'Uso ilimitado do editor visual',
        'Dicionários remotos ilimitados',
        'Configuração e integração personalizada',
        'Suporte dedicado',
        'Funcionalidades personalizadas',
        'Projetos ilimitados',
        'Usuários ilimitados',
      ],
      hi: [
        'स्व-होस्टिंग विकल्प',
        'सभी Intlayer पैकेज तक पहुंच',
        'विज़ुअल एडिटर का असीमित उपयोग',
        'असीमित दूरस्थ शब्दकोश',
        'कस्टम सेटअप और एकीकरण',
        'समर्पित समर्थन',
        'अनुकूलित सुविधाएँ',
        'असीमित परियोजनाएँ',
        'असीमित उपयोगकर्ता',
      ],
      ar: [
        'خيارات الاستضافة الذاتية',
        'الوصول إلى جميع حزم Intlayer',
        'استخدام غير محدود للمحرر المرئي',
        'قواميس بعيدة غير محدودة',
        'إعداد وتكامل مخصص',
        'دعم مخصص',
        'ميزات مصممة خصيصًا',
        'مشاريع غير محدودة',
        'مستخدمون غير محدودون',
      ],
      ru: [
        'Варианты селф-хостинга',
        'Доступ ко всем пакетам Intlayer',
        'Неограниченное использование визуального редактора',
        'Неограниченные удаленные словари',
        'Индивидуальная настройка и интеграция',
        'Выделенная поддержка',
        'Специальные функции',
        'Неограниченное количество проектов',
        'Неограниченное количество пользователей',
      ],
      tr: [
        'Kendi kendine barındırma seçenekleri',
        'Tüm Intlayer paketlerine erişim',
        'Görsel düzenleyicinin sınırsız kullanımı',
        'Sınırsız uzak sözlükler',
        'Özel kurulum ve entegrasyon',
        'Özel destek',
        'Özel özellikler',
        'Sınırsız projeler',
        'Sınırsız kullanıcılar',
      ],
      pl: [
        'Opcje własnego hostingu',
        'Dostęp do wszystkich pakietów Intlayer',
        'Nieograniczone korzystanie z edytora wizualnego',
        'Nieograniczone słowniki zdalne',
        'Niestandardowa konfiguracja i integracja',
        'Dedykowane wsparcie',
        'Funkcje szyte na miarę',
        'Nieograniczona liczba projektów',
        'Nieograniczona liczba użytkowników',
      ],
      id: [
        'Opsi hosting mandiri',
        'Akses ke semua paket Intlayer',
        'Penggunaan editor visual tanpa batas',
        'Kamus jarak jauh tanpa batas',
        'Pengaturan & integrasi khusus',
        'Dukungan khusus',
        'Fitur yang disesuaikan',
        'Proyek tanpa batas',
        'Pengguna tanpa batas',
      ],
      vi: [
        'Tùy chọn tự lưu trữ',
        'Truy cập tất cả các gói Intlayer',
        'Sử dụng không giới hạn trình chỉnh sửa trực quan',
        'Từ điển từ xa không giới hạn',
        'Thiết lập & tích hợp tùy chỉnh',
        'Hỗ trợ tận tình',
        'Tính năng tùy chỉnh',
        'Dự án không giới hạn',
        'Người dùng không giới hạn',
      ],
      uk: [
        'Варіанти self-hosting',
        'Доступ до всіх пакетів Intlayer',
        'Необмежене використання візуального редактора',
        'Необмежені віддалені словники',
        'Індивідуальна настройка та інтеграція',
        'Виділена підтримка',
        'Спеціальні функції',
        'Необмежена кількість проєктів',
        'Необмежена кількість користувачів',
      ],
    }),
    callToAction: {
      label: t({
        en: 'Chat with an expert',
        fr: 'Discuter avec un expert',
        es: 'Hablar con un experto',
        'en-GB': 'Chat with an expert',
        de: 'Mit einem Experten chatten',
        ja: 'エキスパートに相談する',
        ko: '전문가와 상담하기',
        zh: '与专家对话',
        it: 'Parla con un esperto',
        pt: 'Falar com um especialista',
        hi: 'किसी विशेषज्ञ से बात करें',
        ar: 'تحدث مع خبير',
        ru: 'Поговорить с экспертом',
        tr: 'Bir uzmanla sohbet edin',
        pl: 'Porozmawiaj z ekspertem',
        id: 'Ngobrol dengan pakar',
        vi: 'Trò chuyện với chuyên gia',
        uk: 'Поспілкуватися з експертом',
      }),
      text: t({
        en: 'Chat with an expert',
        fr: 'Discuter avec un expert',
        es: 'Hablar con un experto',
        'en-GB': 'Chat with an expert',
        de: 'Mit einem Experten chatten',
        ja: 'エキスパートに相談する',
        ko: '전문가와 상담하기',
        zh: '与专家对话',
        it: 'Parla con un esperto',
        pt: 'Falar com um especialista',
        hi: 'किसी विशेषज्ञ से बात करें',
        ar: 'تحدث مع خبير',
        ru: 'Поговорить с экспертом',
        tr: 'Bir uzmanla sohbet edin',
        pl: 'Porozmawiaj z ekspertem',
        id: 'Ngobrol dengan pakar',
        vi: 'Trò chuyện với chuyên gia',
        uk: 'Поспілкуватися з експертом',
      }),
    },
    priceLabel: t({
      en: 'Contact us',
      fr: 'Contactez-nous',
      es: 'Contáctenos',
      'en-GB': 'Contact us',
      de: 'Kontaktieren Sie uns',
      ja: 'お問い合わせ',
      ko: '문의하기',
      zh: '联系我们',
      it: 'Contattaci',
      pt: 'Contate-nos',
      hi: 'हमसे संपर्क करें',
      ar: 'اتصل بنا',
      ru: 'Свяжитесь с нами',
      tr: 'Bize ulaşın',
      pl: 'Skontaktuj się z nami',
      id: 'Hubungi kami',
      vi: 'Liên hệ với chúng tôi',
      uk: 'Зв’яжіться з нами',
    }),
  },
} satisfies Dictionary<Record<Plans, Partial<PricingInfo>>>['content'];

const pricing = {
  monthly: {
    free: planDetails.free,
    premium: {
      ...planDetails.premium,
      priceId: import.meta.env.VITE_STRIPE_PREMIUM_MONTHLY_PRICE_ID!,
      callToAction: {
        label: t({
          en: 'Get started',
          fr: 'Commencer',
          es: 'Comenzar',
          'en-GB': 'Get started',
          de: 'Loslegen',
          ja: '始める',
          ko: '시작하기',
          zh: '开始',
          it: 'Inizia',
          pt: 'Começar',
          hi: 'शुरू करें',
          ar: 'ابدأ',
          ru: 'Начать',
          tr: 'Başla',
          pl: 'Rozpocznij',
          id: 'Mulai sekarang',
          vi: 'Bắt đầu',
          uk: 'Почати',
        }),
        text: t({
          en: 'Get started',
          fr: 'Commencer',
          es: 'Comenzar',
          'en-GB': 'Get started',
          de: 'Loslegen',
          ja: '始める',
          ko: '시작하기',
          zh: '开始',
          it: 'Inizia',
          pt: 'Começar',
          hi: 'शुरू करें',
          ar: 'ابدأ',
          ru: 'Начать',
          tr: 'Başla',
          pl: 'Rozpocznij',
          id: 'Mulai sekarang',
          vi: 'Bắt đầu',
          uk: 'Почати',
        }),
      },
    },
    enterprise: {
      ...planDetails.enterprise,
      priceId: import.meta.env.VITE_STRIPE_ENTERPRISE_MONTHLY_PRICE_ID!,
      callToAction: {
        label: t({
          en: 'Get started',
          fr: 'Commencer',
          es: 'Comenzar',
          'en-GB': 'Get started',
          de: 'Loslegen',
          ja: '始める',
          ko: '시작하기',
          zh: '开始',
          it: 'Inizia',
          pt: 'Começar',
          hi: 'शुरू करें',
          ar: 'ابدأ',
          ru: 'Начать',
          tr: 'Başla',
          pl: 'Rozpocznij',
          id: 'Mulai sekarang',
          vi: 'Bắt đầu',
          uk: 'Почати',
        }),
        text: t({
          en: 'Get started',
          fr: 'Commencer',
          es: 'Comenzar',
          'en-GB': 'Get started',
          de: 'Loslegen',
          ja: '始める',
          ko: '시작하기',
          zh: '开始',
          it: 'Inizia',
          pt: 'Começar',
          hi: 'शुरू करें',
          ar: 'ابدأ',
          ru: 'Начать',
          tr: 'Başla',
          pl: 'Rozpocznij',
          id: 'Mulai sekarang',
          vi: 'Bắt đầu',
          uk: 'Почати',
        }),
      },
    },
    custom: planDetails.custom,
  },
  yearly: {
    free: planDetails.free,

    premium: {
      ...planDetails.premium,
      priceId: import.meta.env.VITE_STRIPE_PREMIUM_YEARLY_PRICE_ID!,
      badge: t({
        en: 'Save up to 20% annually',
        fr: "Économisez jusqu'à 20% par an",
        es: 'Ahorra hasta un 20% anualmente',
        'en-GB': 'Save up to 20% annually',
        de: 'Sparen Sie bis zu 20% jährlich',
        ja: '年間最大20%節約',
        ko: '연간 최대 20% 절약',
        zh: '每年最多节省20%',
        it: 'Risparmia fino al 20% annualmente',
        pt: 'Economize até 20% anualmente',
        hi: 'सालाना 20% तक बचाएं',
        ar: 'وفر ما يصل إلى 20% سنويًا',
        ru: 'Экономьте до 20% в год',
        tr: "Yıllık %20'ye kadar tasarruf edin",
        pl: 'Oszczędzaj do 20% rocznie',
        id: 'Hemat hingga 20% per tahun',
        vi: 'Tiết kiệm đến 20% hàng năm',
        uk: 'Заощаджуйте до 20% щорічно',
      }),
      callToAction: {
        label: t({
          en: 'Get started',
          fr: 'Commencer',
          es: 'Comenzar',
          'en-GB': 'Get started',
          de: 'Loslegen',
          ja: '始める',
          ko: '시작하기',
          zh: '开始',
          it: 'Inizia',
          pt: 'Começar',
          hi: 'शुरू करें',
          ar: 'ابدأ',
          ru: 'Начать',
          tr: 'Başla',
          pl: 'Rozpocznij',
          id: 'Mulai sekarang',
          vi: 'Bắt đầu',
          uk: 'Почати',
        }),
        text: t({
          en: 'Get started',
          fr: 'Commencer',
          es: 'Comenzar',
          'en-GB': 'Get started',
          de: 'Loslegen',
          ja: '始める',
          ko: '시작하기',
          zh: '开始',
          it: 'Inizia',
          pt: 'Começar',
          hi: 'शुरू करें',
          ar: 'ابدأ',
          ru: 'Начать',
          tr: 'Başla',
          pl: 'Rozpocznij',
          id: 'Mulai sekarang',
          vi: 'Bắt đầu',
          uk: 'Почати',
        }),
      },
    },
    enterprise: {
      ...planDetails.enterprise,
      priceId: import.meta.env.VITE_STRIPE_ENTERPRISE_YEARLY_PRICE_ID!,
      badge: t({
        en: 'Save up to 20% annually',
        fr: "Économisez jusqu'à 20% par an",
        es: 'Ahorra hasta un 20% anualmente',
        'en-GB': 'Save up to 20% annually',
        de: 'Sparen Sie bis zu 20% jährlich',
        ja: '年間最大20%節約',
        ko: '연간 최대 20% 절약',
        zh: '每年最多节省20%',
        it: 'Risparmia fino al 20% annualmente',
        pt: 'Economize até 20% anualmente',
        hi: 'सालाना 20% तक बचाएं',
        ar: 'وفر ما يصل إلى 20% سنويًا',
        ru: 'Экономьте до 20% в год',
        tr: "Yıllık %20'ye kadar tasarruf edin",
        pl: 'Oszczędzaj do 20% rocznie',
        id: 'Hemat hingga 20% per tahun',
        vi: 'Tiết kiệm đến 20% hàng năm',
        uk: 'Заощаджуйте до 20% щорічно',
      }),
      callToAction: {
        label: t({
          en: 'Get started',
          fr: 'Commencer',
          es: 'Comenzar',
          'en-GB': 'Get started',
          de: 'Loslegen',
          ja: '始める',
          ko: '시작하기',
          zh: '开始',
          it: 'Inizia',
          pt: 'Começar',
          hi: 'शुरू करें',
          ar: 'ابدأ',
          ru: 'Начать',
          tr: 'Başla',
          pl: 'Rozpocznij',
          id: 'Mulai',
          vi: 'Bắt đầu',
          uk: 'Розпочати',
        }),
        text: t({
          en: 'Get started',
          fr: 'Commencer',
          es: 'Comenzar',
          'en-GB': 'Get started',
          de: 'Loslegen',
          ja: '始める',
          ko: '시작하기',
          zh: '开始',
          it: 'Inizia',
          pt: 'Começar',
          hi: 'शुरू करें',
          ar: 'ابدأ',
          ru: 'Начать',
          tr: 'Başla',
          pl: 'Rozpocznij',
          id: 'Mulai',
          vi: 'Bắt đầu',
          uk: 'Розпочати',
        }),
      },
    },
    custom: planDetails.custom,
  },
  lifetime: {
    free: planDetails.free,
    lifetime: {
      ...planDetails.lifetime,
      priceId: import.meta.env.VITE_STRIPE_ONE_TIME_PAYMENT_PRICE_ID!,
      callToAction: {
        label: t({
          en: 'Get lifetime access',
          fr: 'Obtenir l’accès à vie',
          es: 'Obtener acceso de por vida',
          'en-GB': 'Get lifetime access',
          de: 'Lebenslangen Zugriff erhalten',
          ja: 'ライフタイムアクセスを取得',
          ko: '평생 액세스 받기',
          zh: '获取终身访问权',
          it: 'Ottieni accesso a vita',
          pt: 'Obter acesso vitalício',
          hi: 'आजीवन एक्सेस प्राप्त करें',
          ar: 'احصل على وصول مدى الحياة',
          ru: 'Получить пожизненный доступ',
          tr: 'Ömür boyu erişim al',
          pl: 'Uzyskaj dożywotni dostęp',
          id: 'Dapatkan akses seumur hidup',
          vi: 'Nhận quyền truy cập trọn đời',
          uk: 'Отримати довічний доступ',
        }),
        text: t({
          en: 'Get lifetime access',
          fr: 'Obtenir l’accès à vie',
          es: 'Obtener acceso de por vida',
          'en-GB': 'Get lifetime access',
          de: 'Lebenslangen Zugriff erhalten',
          ja: 'ライフタイムアクセスを取得',
          ko: '평생 액세스 받기',
          zh: '获取终身访问权',
          it: 'Ottieni accesso a vita',
          pt: 'Obter acesso vitalício',
          hi: 'आजीवन एक्सेस प्राप्त करें',
          ar: 'احصل على وصول مدى الحياة',
          ru: 'Получить пожизненный доступ',
          tr: 'Ömür boyu erişim al',
          pl: 'Uzyskaj dożywotni dostęp',
          id: 'Dapatkan akses seumur hidup',
          vi: 'Nhận quyền truy cập trọn đời',
          uk: 'Отримати довічний доступ',
        }),
      },
    },
    custom: planDetails.custom,
  },
} satisfies Dictionary<
  Record<Period, Partial<Record<Plans, PricingInfo>>>
>['content'];

const pricingContent = {
  key: 'pricing',
  content: {
    title: t({
      en: 'Pricing CMS',
      fr: 'Tarification CMS',
      es: 'Precios CMS',
      'en-GB': 'Pricing CMS',
      de: 'Preise CMS',
      ja: '価格 CMS',
      ko: '가격 CMS',
      zh: '价格 CMS',
      it: 'Prezzi CMS',
      pt: 'Preços CMS',
      hi: 'मूल्य निर्धारण CMS',
      ar: 'سعر CMS',
      ru: 'Цены CMS',
      tr: 'Fiyatlandırma CMS',
      pl: 'Cennik CMS',
      id: 'Harga CMS',
      vi: 'Bảng giá CMS',
      uk: 'Ціни для CMS',
    }),
    description: t({
      fr: "Intlayer est avant tout une suite d'outil gratuit et open source. Le pricing associée s'applique uniquement à l'utilisation du CMS, de l'éditeur visuel et des outils d'IA associés. (Note: Il est aussi possible de self hoster le CMS en clonant le dépôt GitHub.)",
      en: 'Intlayer is primarily a free and open-source suite of tools. The associated pricing applies only to the use of the CMS, the visual editor, and the associated AI tools. (Note: It is also possible to self-host the CMS by cloning the GitHub repository.)',
      es: 'Intlayer es ante todo un conjunto de herramientas gratuitas y de código abierto. Los precios asociados se aplican únicamente al uso del CMS, el editor visual y las herramientas de IA asociadas. (Nota: También es posible alojar el CMS por cuenta propia clonando el repositorio de GitHub.)',
      'en-GB':
        'Intlayer is primarily a free and open-source suite of tools. The associated pricing applies only to the use of the CMS, the visual editor, and the associated AI tools. (Note: It is also possible to self-host the CMS by cloning the GitHub repository.)',
      de: 'Intlayer ist in erster Linie eine kostenlose und Open-Source-Tool-Suite. Die zugehörige Preisgestaltung gilt nur für die Nutzung des CMS, des visuellen Editors und der damit verbundenen KI-Tools. (Hinweis: Es ist auch möglich, das CMS selbst zu hosten, indem das GitHub-Repository geklont wird.)',
      ja: 'Intlayerは主に無料でオープンソースのツールスイートです。関連する料金はCMS、ビジュアルエディタ、および関連するAIツールの使用にのみ適用されます。（注：GitHubリポジトリをクローンしてCMSを自己ホストすることも可能です。）',
      ko: 'Intlayer는 주로 무료 오픈 소스 도구 모음입니다. 관련된 가격은 CMS, 비주얼 편집기 및 관련 AI 도구 사용에만 적용됩니다. (참고: GitHub 리포지토리를 클론하여 CMS를 자체 호스팅하는 것도 가능합니다.)',
      zh: 'Intlayer 主要是一套免费且开源的工具套件。相关定价仅适用于CMS、可视化编辑器以及相关的AI工具的使用。（注意：也可以通过克隆GitHub存储库来自行托管CMS。）',
      it: "Intlayer è principalmente una suite di strumenti gratuita e open source. La tariffazione associata si applica solo all'uso del CMS, dell'editor visuale e degli strumenti IA associati. (Nota: è anche possibile auto-ospitare il CMS clonando il repository GitHub.)",
      pt: 'O Intlayer é principalmente um conjunto de ferramentas gratuito e de código aberto. A precificação associada aplica-se apenas ao uso do CMS, do editor visual e das ferramentas de IA associadas. (Nota: também é possível auto-hospedar o CMS clonando o repositório do GitHub.)',
      hi: 'Intlayer मुख्य रूप से एक मुफ्त और ओपन-सोर्स टूल सूट है। संबंधित मूल्य निर्धारण केवल CMS, दृश्य संपादक और संबंधित AI उपकरणों के उपयोग पर लागू होता है। (नोट: GitHub रिपॉजिटरी को क्लोन करके CMS को स्वयं होस्ट करना भी संभव है।)',
      ar: 'إن Intlayer هو في المقام الأول مجموعة أدوات مجانية ومفتوحة المصدر. يتم تطبيق التسعير المرتبط فقط لاستخدام CMS، والمحرر المرئي، وأدوات الذكاء الاصطناعي المرتبطة. (ملاحظة: من الممكن أيضًا استضافة CMS بنفسك عن طريق استنساخ مستودع GitHub.)',
      ru: 'Intlayer - это, прежде всего, набор бесплатных и открытых инструментов. Сопутствующая цена применяется только к использованию CMS, визуального редактора и связанных инструментов ИИ. (Примечание: также возможно саморазмещение CMS с помощью клонирования репозитория на GitHub.)',
      tr: "Intlayer öncelikle ücretsiz ve açık kaynaklı bir araç setidir. İlgili fiyatlandırma yalnızca CMS, görsel düzenleyici ve ilgili AI araçlarının kullanımı için geçerlidir. (Not: GitHub deposunu klonlayarak CMS'yi kendi kendinize barındırmak da mümkündür.)",
      pl: 'Intlayer to przede wszystkim darmowy i otwartoźródłowy zestaw narzędzi. Powiązane opłaty dotyczą wyłącznie korzystania z CMS, edytora wizualnego oraz powiązanych narzędzi AI. (Uwaga: możliwe jest również samodzielne hostowanie CMS przez sklonowanie repozytorium na GitHubie.)',
      id: 'Intlayer terutama merupakan rangkaian alat yang bersifat gratis dan sumber terbuka. Harga yang terkait hanya berlaku untuk penggunaan CMS, editor visual, dan alat AI terkait. (Catatan: Anda juga dapat meng-host sendiri CMS dengan mengkloning repositori GitHub.)',
      vi: 'Intlayer chủ yếu là một bộ công cụ mã nguồn mở và miễn phí. Bảng giá này chỉ áp dụng cho việc sử dụng CMS, trình chỉnh sửa trực quan và các công cụ AI liên quan. (Lưu ý: Bạn cũng có thể tự lưu trữ CMS bằng cách sao chép kho lưu trữ GitHub.)',
      uk: "Intlayer насамперед є безкоштовним та відкритим набором інструментів. Пов'язана плата стосується лише використання CMS, візуального редактора та пов'язаних інструментів ШІ. (Примітка: також можливо самостійно розгорнути CMS, склонивши репозиторій на GitHub.)",
    }),
    pricing,
    period: {
      monthly: t({
        en: 'Monthly',
        fr: 'Mensuel',
        es: 'Mensual',
        'en-GB': 'Monthly',
        de: 'Monatlich',
        ja: '毎月',
        ko: '매달',
        zh: '每月',
        it: 'Mensile',
        pt: 'Mensal',
        hi: 'मासिक',
        ar: 'شهريًا',
        ru: 'Ежемесячно',
        tr: 'Aylık',
        pl: 'Miesięcznie',
        id: 'Bulanan',
        vi: 'Hàng tháng',
        uk: 'Щомісячно',
      }),

      yearly: t({
        en: 'Monthly',
        fr: 'Mensuel',
        es: 'Mensual',
        'en-GB': 'Monthly',
        de: 'Monatlich',
        ja: '毎月',
        ko: '매달',
        zh: '每月',
        it: 'Mensile',
        pt: 'Mensal',
        hi: 'मासिक',
        ar: 'شهريًا',
        ru: 'Ежемесячно',
        tr: 'Aylık',
        pl: 'Miesięcznie',
        id: 'Bulanan',
        vi: 'Hàng tháng',
        uk: 'Щомісячно',
      }),

      lifetime: t({
        en: 'Lifetime',
        fr: 'À vie',
        es: 'De por vida',
        'en-GB': 'Lifetime',
        de: 'Lebenslang',
        ja: 'ライフタイム',
        ko: '평생',
        zh: '终身',
        it: 'A vita',
        pt: 'Vitalício',
        hi: 'आजीवन',
        ar: 'مدى الحياة',
        ru: 'Пожизненно',
        tr: 'Ömür Boyu',
        pl: 'Dożywotni',
        id: 'Seumur Hidup',
        vi: 'Trọn đời',
        uk: 'Довічний',
      }),
    },
    priceFrequency: {
      monthly: t({
        en: 'Monthly',
        fr: 'Mensuel',
        es: 'Mensual',
        'en-GB': 'Monthly',
        de: 'Monatlich',
        ja: '毎月',
        ko: '매달',
        zh: '每月',
        it: 'Mensile',
        pt: 'Mensal',
        hi: 'मासिक',
        ar: 'شهريًا',
        ru: 'Ежемесячно',
        tr: 'Aylık',
        pl: 'Miesięcznie',
        id: 'Bulanan',
        vi: 'Hàng tháng',
        uk: 'Щомісячно',
      }),
      yearly: t({
        en: 'Monthly',
        fr: 'Mensuel',
        es: 'Mensual',
        'en-GB': 'Monthly',
        de: 'Monatlich',
        ja: '毎月',
        ko: '매달',
        zh: '每月',
        it: 'Mensile',
        pt: 'Mensal',
        hi: 'मासिक',
        ar: 'شهريًا',
        ru: 'Ежемесячно',
        tr: 'Aylık',
        pl: 'Miesięcznie',
        id: 'Bulanan',
        vi: 'Hàng tháng',
        uk: 'Щомісячно',
      }),
      lifetime: t({
        en: 'one-time',
        fr: 'paiement unique',
        es: 'pago único',
        'en-GB': 'one-time',
        de: 'einmalig',
        ja: '一回払い',
        ko: '일회성',
        zh: '一次性',
        it: 'una tantum',
        pt: 'pagamento único',
        hi: 'एकमुश्त',
        ar: 'دفعة واحدة',
        ru: 'единовременно',
        tr: 'tek seferlik',
        pl: 'jednorazowo',
        id: 'sekali bayar',
        vi: 'một lần',
        uk: 'одноразово',
      }),
    },
    comparisonTable: {
      title: t({
        en: 'Compare Plans',
        'en-GB': 'Compare Plans',
        fr: 'Comparer les plans',
        es: 'Comparar planes',
        de: 'Pläne vergleichen',
        ja: 'プランを比較',
        ko: '플랜 비교',
        zh: '比较方案',
        it: 'Confronta piani',
        pt: 'Comparar planos',
        hi: 'योजनाओं की तुलना करें',
        ar: 'مقارنة الخطط',
        ru: 'Сравнить планы',
        tr: 'Planları karşılaştır',
        pl: 'Porównaj plany',
        id: 'Bandingkan paket',
        vi: 'So sánh gói',
        uk: 'Порівняти плани',
      }),
      categories: {
        core: t({
          en: 'Core Features',
          'en-GB': 'Core Features',
          fr: 'Fonctionnalités principales',
          es: 'Características principales',
          de: 'Kernfunktionen',
          ja: 'コア機能',
          ko: '핵심 기능',
          zh: '核心功能',
          it: 'Funzionalità principali',
          pt: 'Recursos principais',
          hi: 'मुख्य विशेषताएँ',
          ar: 'الميزات الأساسية',
          ru: 'Основные функции',
          tr: 'Temel Özellikler',
          pl: 'Podstawowe funkcje',
          id: 'Fitur utama',
          vi: 'Tính năng cốt lõi',
          uk: 'Основні функції',
        }),
        limits: t({
          en: 'Limits',
          'en-GB': 'Limits',
          fr: 'Limites',
          es: 'Límites',
          de: 'Grenzen',
          ja: '制限',
          ko: '제한',
          zh: '限制',
          it: 'Limiti',
          pt: 'Limites',
          hi: 'सीमाएँ',
          ar: 'الحدود',
          ru: 'Ограничения',
          tr: 'Sınırlar',
          pl: 'Limity',
          id: 'Batas',
          vi: 'Giới hạn',
          uk: 'Обмеження',
        }),
        ai: t({
          en: 'AI Features',
          'en-GB': 'AI Features',
          fr: 'Fonctionnalités IA',
          es: 'Características de IA',
          de: 'KI-Funktionen',
          ja: 'AI機能',
          ko: 'AI 기능',
          zh: 'AI功能',
          it: 'Funzionalità AI',
          pt: 'Recursos de IA',
          hi: 'AI विशेषताएँ',
          ar: 'ميزات الذكاء الاصطناعي',
          ru: 'Функции ИИ',
          tr: 'Yapay Zeka Özellikleri',
          pl: 'Funkcje AI',
          id: 'Fitur AI',
          vi: 'Tính năng AI',
          uk: 'Функції ШІ',
        }),
        support: t({
          en: 'Support',
          'en-GB': 'Support',
          fr: 'Support',
          es: 'Soporte',
          de: 'Support',
          ja: 'サポート',
          ko: '지원',
          zh: '支持',
          it: 'Supporto',
          pt: 'Suporte',
          hi: 'सहायता',
          ar: 'الدعم',
          ru: 'Поддержка',
          tr: 'Destek',
          pl: 'Wsparcie',
          id: 'Dukungan',
          vi: 'Hỗ trợ',
          uk: 'Підтримка',
        }),
      },
      features: {
        visualEditor: t({
          en: 'Visual Editor',
          'en-GB': 'Visual Editor',
          fr: 'Éditeur visuel',
          es: 'Editor visual',
          de: 'Visueller Editor',
          ja: 'ビジュアルエディタ',
          ko: '비주얼 에디터',
          zh: '可视化编辑器',
          it: 'Editor visivo',
          pt: 'Editor visual',
          hi: 'विज़ुअल एडिटर',
          ar: 'المحرر المرئي',
          ru: 'Визуальный редактор',
          tr: 'Görsel Düzenleyici',
          pl: 'Edytor wizualny',
          id: 'Editor visual',
          vi: 'Trình chỉnh sửa trực quan',
          uk: 'Візуальний редактор',
        }),
        distantDictionaries: t({
          en: 'Distant Dictionaries',
          'en-GB': 'Distant Dictionaries',
          fr: 'Dictionnaires distants',
          es: 'Diccionarios distantes',
          de: 'Entfernte Wörterbücher',
          ja: '遠隔辞書',
          ko: '원격 사전',
          zh: '远程字典',
          it: 'Dizionari remoti',
          pt: 'Dicionários remotos',
          hi: 'दूरस्थ शब्दकोश',
          ar: 'القواميس البعيدة',
          ru: 'Удалённые словари',
          tr: 'Uzak Sözlükler',
          pl: 'Zdalne słowniki',
          id: 'Kamus jarak jauh',
          vi: 'Từ điển từ xa',
          uk: 'Віддалені словники',
        }),
        hotReloading: t({
          en: 'Hot Reloading',
          'en-GB': 'Hot Reloading',
          fr: 'Rechargement à chaud',
          es: 'Recarga en caliente',
          de: 'Hot Reloading',
          ja: 'ホットリローディング',
          ko: '핫 리로딩',
          zh: '热重载',
          it: 'Aggiornamento dinamico',
          pt: 'Recarga automática',
          hi: 'हॉट रीलोडिंग',
          ar: 'إعادة التحميل الفوري',
          ru: 'Горячая перезагрузка',
          tr: 'Anında Yenileme',
          pl: 'Gorące ładowanie',
          id: 'Hot reloading',
          vi: 'Tải lại nóng',
          uk: 'Гаряче перезавантаження',
        }),
        storage: t({
          en: 'Storage',
          'en-GB': 'Storage',
          fr: 'Stockage',
          es: 'Almacenamiento',
          de: 'Speicher',
          ja: 'ストレージ',
          ko: '스토리지',
          zh: '存储',
          it: 'Spazio di archiviazione',
          pt: 'Armazenamento',
          hi: 'भंडारण',
          ar: 'التخزين',
          ru: 'Хранилище',
          tr: 'Depolama',
          pl: 'Przechowywanie',
          id: 'Penyimpanan',
          vi: 'Lưu trữ',
          uk: 'Сховище',
        }),
        projects: t({
          en: 'Projects',
          'en-GB': 'Projects',
          fr: 'Projets',
          es: 'Proyectos',
          de: 'Projekte',
          ja: 'プロジェクト',
          ko: '프로젝트',
          zh: '项目',
          it: 'Progetti',
          pt: 'Projetos',
          hi: 'परियोजनाएँ',
          ar: 'المشاريع',
          ru: 'Проекты',
          tr: 'Projeler',
          pl: 'Projekty',
          id: 'Proyek',
          vi: 'Dự án',
          uk: 'Проєкти',
        }),
        users: t({
          en: 'Organization Users',
          'en-GB': 'Organisation Users',
          fr: "Utilisateurs de l'organisation",
          es: 'Usuarios de la organización',
          de: 'Organisationsbenutzer',
          ja: '組織ユーザー',
          ko: '조직 사용자',
          zh: '组织用户',
          it: "Utenti dell'organizzazione",
          pt: 'Usuários da organização',
          hi: 'संगठन उपयोगकर्ता',
          ar: 'مستخدمو المنظمة',
          ru: 'Пользователи организации',
          tr: 'Organizasyon Kullanıcıları',
          pl: 'Użytkownicy organizacji',
          id: 'Pengguna organisasi',
          vi: 'Người dùng tổ chức',
          uk: 'Користувачі організації',
        }),
        aiContentGeneration: t({
          en: 'AI Content Generation',
          'en-GB': 'AI Content Generation',
          fr: 'Génération de contenu IA',
          es: 'Generación de contenido IA',
          de: 'KI-Inhaltsgenerierung',
          ja: 'AIコンテンツ生成',
          ko: 'AI 콘텐츠 생성',
          zh: 'AI内容生成',
          it: 'Generazione di contenuti AI',
          pt: 'Geração de conteúdo com IA',
          hi: 'AI सामग्री निर्माण',
          ar: 'إنشاء محتوى بالذكاء الاصطناعي',
          ru: 'Генерация контента с ИИ',
          tr: 'AI İçerik Üretimi',
          pl: 'Generowanie treści AI',
          id: 'Pembuatan konten AI',
          vi: 'Tạo nội dung bằng AI',
          uk: 'Генерація контенту ШІ',
        }),
        aiSeoOptimization: t({
          en: 'AI SEO Optimization',
          'en-GB': 'AI SEO Optimisation',
          fr: 'Optimisation SEO IA',
          es: 'Optimización SEO IA',
          de: 'KI-SEO-Optimierung',
          ja: 'AI SEO最適化',
          ko: 'AI SEO 최적화',
          zh: 'AI SEO优化',
          it: 'Ottimizzazione SEO AI',
          pt: 'Otimização SEO com IA',
          hi: 'AI SEO ऑप्टिमाइज़ेशन',
          ar: 'تحسين SEO بالذكاء الاصطناعي',
          ru: 'SEO-оптимизация с ИИ',
          tr: 'AI SEO Optimizasyonu',
          pl: 'Optymalizacja SEO AI',
          id: 'Optimisasi SEO AI',
          vi: 'Tối ưu SEO bằng AI',
          uk: 'SEO-оптимізація ШІ',
        }),
        premiumSupport: t({
          en: 'Premium Support',
          'en-GB': 'Premium Support',
          fr: 'Support premium',
          es: 'Soporte premium',
          de: 'Premium-Support',
          ja: 'プレミアムサポート',
          ko: '프리미엄 지원',
          zh: '专业支持',
          it: 'Supporto premium',
          pt: 'Suporte premium',
          hi: 'प्रीमियम समर्थन',
          ar: 'الدعم المتميز',
          ru: 'Премиум поддержка',
          tr: 'Premium Destek',
          pl: 'Wsparcie premium',
          id: 'Dukungan premium',
          vi: 'Hỗ trợ Premium',
          uk: 'Преміум-підтримка',
        }),
        oneTimePayment: t({
          en: 'One-time Payment',
          'en-GB': 'One-time Payment',
          fr: 'Paiement unique',
          es: 'Pago único',
          de: 'Einmalige Zahlung',
          ja: '一括払い',
          ko: '일회성 결제',
          zh: '一次性付款',
          it: 'Pagamento unico',
          pt: 'Pagamento único',
          hi: 'एकमुश्त भुगतान',
          ar: 'دفع لمرة واحدة',
          ru: 'Единовременный платёж',
          tr: 'Tek seferlik ödeme',
          pl: 'Jednorazowa płatność',
          id: 'Pembayaran sekali',
          vi: 'Thanh toán một lần',
          uk: 'Одноразовий платіж',
        }),
        unlimited: t({
          en: 'Unlimited',
          'en-GB': 'Unlimited',
          fr: 'Illimité',
          es: 'Ilimitado',
          de: 'Unbegrenzt',
          ja: '無制限',
          ko: '무제한',
          zh: '无限',
          it: 'Illimitato',
          pt: 'Ilimitado',
          hi: 'असीमित',
          ar: 'غير محدود',
          ru: 'Безлимитно',
          tr: 'Sınırsız',
          pl: 'Nieograniczone',
          id: 'Tidak terbatas',
          vi: 'Không giới hạn',
          uk: 'Необмежено',
        }),
      },
      planNames: {
        free: planDetails.free.title,
        premium: planDetails.premium.title,
        enterprise: planDetails.enterprise.title,
        lifetime: planDetails.lifetime.title,
      },
    },
  },
  title: 'Pricing plans for CMS',
  description:
    "Content declaration defining the pricing plans for Intlayer's CMS, including Free, Premium, and Enterprise tiers. It outlines the features, limits, and structure of monthly and yearly subscriptions, along with AI capabilities and user/project quotas.",
  tags: [
    'pricing',
    'cms',
    'subscription plans',
    'visual editor',
    'ai features',
  ],
};

export default pricingContent;
