import { type Dictionary, t } from 'intlayer';

const twoFactorFormContent = {
  key: 'two-factor-form',
  content: {
    title: t({
      en: 'Two-Factor Authentication',
      fr: 'Authentification à deux facteurs',
      es: 'Autenticación de dos factores',
      de: 'Zwei-Faktor-Authentifizierung',
      ja: '二要素認証',
      ko: '2단계 인증',
      zh: '双因素认证',
      it: 'Autenticazione a due fattori',
      pt: 'Autenticação de dois fatores',
      hi: 'दो-कारक प्रमाणीकरण',
      ar: 'المصادقة الثنائية',
      ru: 'Двухфакторная аутентификация',
      'en-GB': 'Two-Factor Authentication',
      tr: 'İki Faktörlü Kimlik Doğrulama',
      pl: 'Uwierzytelnianie dwuskładnikowe',
      id: 'Autentikasi Dua Faktor',
      vi: 'Xác thực hai yếu tố',
    }),
    description: t({
      en: 'Add an extra layer of security to your account by enabling two-factor authentication.',
      fr: "Ajoutez une couche de sécurité supplémentaire à votre compte en activant l'authentification à deux facteurs.",
      es: 'Agregue una capa adicional de seguridad a su cuenta habilitando la autenticación de dos factores.',
      de: 'Fügen Sie Ihrem Konto eine zusätzliche Sicherheitsebene hinzu, indem Sie die Zwei-Faktor-Authentifizierung aktivieren.',
      ja: '二要素認証を有効にして、アカウントにセキュリティレイヤーを追加します。',
      ko: '2단계 인증을 활성화하여 계정에 추가 보안 계층을 추가하세요.',
      zh: '通过启用双因素认证为您的帐户添加额外的安全层。',
      it: "Aggiungi un ulteriore livello di sicurezza al tuo account abilitando l'autenticazione a due fattori.",
      pt: 'Adicione uma camada extra de segurança à sua conta ativando a autenticação de dois fatores.',
      hi: 'दो-कारक प्रमाणीकरण सक्षम करके अपने खाते में सुरक्षा की एक अतिरिक्त परत जोड़ें।',
      ar: 'أضف طبقة إضافية من الأمان إلى حسابك عن طريق تمكين المصادقة الثنائية.',
      ru: 'Добавьте дополнительный уровень безопасности к вашей учетной записи, включив двухфакторную аутентификацию.',
      'en-GB':
        'Add an extra layer of security to your account by enabling two-factor authentication.',
      tr: 'İki faktörlü kimlik doğrulamayı etkinleştirerek hesabınıza ekstra bir güvenlik katmanı ekleyin.',
      pl: 'Dodaj dodatkową warstwę zabezpieczeń do swojego konta, włączając uwierzytelnianie dwuskładnikowe.',
      id: 'Tambahkan lapisan keamanan ekstra ke akun Anda dengan mengaktifkan autentikasi dua faktor.',
      vi: 'Thêm một lớp bảo mật bổ sung cho tài khoản của bạn bằng cách bật xác thực hai yếu tố.',
    }),
    enabledStatus: t({
      en: 'Two-factor authentication is enabled',
      fr: "L'authentification à deux facteurs est activée",
      es: 'La autenticación de dos factores está habilitada',
      de: 'Zwei-Faktor-Authentifizierung ist aktiviert',
      ja: '二要素認証が有効です',
      ko: '2단계 인증이 활성화되었습니다',
      zh: '双因素认证已启用',
      it: "L'autenticazione a due fattori è abilitata",
      pt: 'A autenticação de dois fatores está ativada',
      hi: 'दो-कारक प्रमाणीकरण सक्षम है',
      ar: 'المصادقة الثنائية مفعلة',
      ru: 'Двухфакторная аутентификация включена',
      'en-GB': 'Two-factor authentication is enabled',
      tr: 'İki faktörlü kimlik doğrulama etkin',
      pl: 'Uwierzytelnianie dwuskładnikowe jest włączone',
      id: 'Autentikasi dua faktor diaktifkan',
      vi: 'Xác thực hai yếu tố đã được bật',
    }),
    disabledStatus: t({
      en: 'Two-factor authentication is disabled',
      fr: "L'authentification à deux facteurs est désactivée",
      es: 'La autenticación de dos factores está deshabilitada',
      de: 'Zwei-Faktor-Authentifizierung ist deaktiviert',
      ja: '二要素認証が無効です',
      ko: '2단계 인증이 비활성화되었습니다',
      zh: '双因素认证已禁用',
      it: "L'autenticazione a due fattori è disabilitata",
      pt: 'A autenticação de dois fatores está desativada',
      hi: 'दो-कारक प्रमाणीकरण अक्षम है',
      ar: 'المصادقة الثنائية معطلة',
      ru: 'Двухфакторная аутентификация отключена',
      'en-GB': 'Two-factor authentication is disabled',
      tr: 'İki faktörlü kimlik doğrulama devre dışı',
      pl: 'Uwierzytelnianie dwuskładnikowe jest wyłączone',
      id: 'Autentikasi dua faktor dinonaktifkan',
      vi: 'Xác thực hai yếu tố đã bị tắt',
    }),
    enableButton: {
      text: t({
        en: 'Enable two-factor authentication',
        fr: "Activer l'authentification à deux facteurs",
        es: 'Habilitar autenticación de dos factores',
        de: 'Zwei-Faktor-Authentifizierung aktivieren',
        ja: '二要素認証を有効にする',
        ko: '2단계 인증 활성화',
        zh: '启用双因素认证',
        it: 'Abilita autenticazione a due fattori',
        pt: 'Ativar autenticação de dois fatores',
        hi: 'दो-कारक प्रमाणीकरण सक्षम करें',
        ar: 'تمكين المصادقة الثنائية',
        ru: 'Включить двухфакторную аутентификацию',
        'en-GB': 'Enable two-factor authentication',
        tr: 'İki faktörlü kimlik doğrulamayı etkinleştir',
        pl: 'Włącz uwierzytelnianie dwuskładnikowe',
        id: 'Aktifkan autentikasi dua faktor',
        vi: 'Bật xác thực hai yếu tố',
      }),
      ariaLabel: t({
        en: 'Click to enable two-factor authentication',
        fr: "Cliquez pour activer l'authentification à deux facteurs",
        es: 'Haz clic para habilitar la autenticación de dos factores',
        de: 'Klicken Sie, um die Zwei-Faktor-Authentifizierung zu aktivieren',
        ja: '二要素認証を有効にするにはクリックしてください',
        ko: '2단계 인증을 활성화하려면 클릭하세요',
        zh: '单击以启用双因素认证',
        it: "Clicca per abilitare l'autenticazione a due fattori",
        pt: 'Clique para ativar a autenticação de dois fatores',
        hi: 'दो-कारक प्रमाणीकरण सक्षम करने के लिए क्लिक करें',
        ar: 'انقر لتمكين المصادقة الثنائية',
        ru: 'Нажмите, чтобы включить двухфакторную аутентификацию',
        'en-GB': 'Click to enable two-factor authentication',
        tr: 'İki faktörlü kimlik doğrulamayı etkinleştirmek için tıklayın',
        pl: 'Kliknij, aby włączyć uwierzytelnianie dwuskładnikowe',
        id: 'Klik untuk mengaktifkan autentikasi dua faktor',
        vi: 'Nhấp để bật xác thực hai yếu tố',
      }),
    },
    disableButton: {
      text: t({
        en: 'Disable two-factor authentication',
        fr: "Désactiver l'authentification à deux facteurs",
        es: 'Deshabilitar autenticación de dos factores',
        de: 'Zwei-Faktor-Authentifizierung deaktivieren',
        ja: '二要素認証を無効にする',
        ko: '2단계 인증 비활성화',
        zh: '禁用双因素认证',
        it: 'Disabilita autenticazione a due fattori',
        pt: 'Desativar autenticação de dois fatores',
        hi: 'दो-कारक प्रमाणीकरण अक्षम करें',
        ar: 'تعطيل المصادقة الثنائية',
        ru: 'Отключить двухфакторную аутентификацию',
        'en-GB': 'Disable two-factor authentication',
        tr: 'İki faktörlü kimlik doğrulamayı devre dışı bırak',
        pl: 'Wyłącz uwierzytelnianie dwuskładnikowe',
        id: 'Nonaktifkan autentikasi dua faktor',
        vi: 'Tắt xác thực hai yếu tố',
      }),
      ariaLabel: t({
        en: 'Click to disable two-factor authentication',
        fr: "Cliquez pour désactiver l'authentification à deux facteurs",
        es: 'Haz clic para deshabilitar la autenticación de dos factores',
        de: 'Klicken Sie, um die Zwei-Faktor-Authentifizierung zu deaktivieren',
        ja: '二要素認証を無効にするにはクリックしてください',
        ko: '2단계 인증을 비활성화하려면 클릭하세요',
        zh: '单击以禁用双因素认证',
        it: "Clicca per disabilitare l'autenticazione a due fattori",
        pt: 'Clique para desativar a autenticação de dois fatores',
        hi: 'दो-कारक प्रमाणीकरण अक्षम करने के लिए क्लिक करें',
        ar: 'انقر لتعطيل المصادقة الثنائية',
        ru: 'Нажмите, чтобы отключить двухфакторную аутентификацию',
        'en-GB': 'Click to disable two-factor authentication',
        tr: 'İki faktörlü kimlik doğrulamayı devre dışı bırakmak için tıklayın',
        pl: 'Kliknij, aby wyłączyć uwierzytelnianie dwuskładnikowe',
        id: 'Klik untuk menonaktifkan autentikasi dua faktor',
        vi: 'Nhấp để tắt xác thực hai yếu tố',
      }),
    },
  },
  title: 'Two-factor authentication form',
  description:
    'Content declaration for the two-factor authentication form, including labels, descriptions, status messages, and button texts for managing 2FA settings.',
  tags: ['authentication', 'security', '2FA', 'form'],
} satisfies Dictionary;

export default twoFactorFormContent;
