import { type Dictionary, t } from 'intlayer';

const localizationAnalyzerContent = {
  key: 'localization-analyzer',
  content: {
    title: t({
      en: 'Analyze Your Website’s Global Localization Score',
      fr: 'Analysez le score de localisation de votre site web',
      es: 'Analice el puntaje de localización global de su sitio web',
      de: 'Analysieren Sie den globalen Lokalisierungs-Score Ihrer Website',
      ja: 'ウェブサイトのグローバルなローカリゼーションスコアを分析します',
      zh: '分析您网站的全球本地化评分',
      ru: 'Проанализируйте общий рейтинг локализации вашего сайта',
      ko: '웹사이트의 글로벌 현지화 점수를 분석하세요',
      it: 'Analizza il punteggio di localizzazione globale del tuo sito web',
      pt: 'Analise a pontuação global de localização do seu site',
      hi: 'अपनी वेबसाइट के ग्लोबल स्थानीयकरण स्कोर का विश्लेषण करें',
      tr: 'Web sitenizin küresel yerelleştirme puanını analiz edin',
      pl: 'Przeanalizuj globalny wynik lokalizacji swojej strony internetowej',
      id: 'Analisis skor lokalisasi global situs web Anda',
      vi: 'Phân tích điểm số bản địa hóa toàn cầu của trang web của bạn',
      ar: 'حلل درجة التوطين العالمية لموقعك',
    }),
    description: t({
      en: 'Quickly and for free, evaluate the localization quality of your website. Analyze principal multilingual elements to get a comprehensive score and actionable insights for improving your reach.',
      fr: "Évaluez gratuitement et rapidement la qualité de la localisation de votre site Web. Analysez les principaux éléments multilingues pour obtenir un score complet et des informations exploitables afin d'améliorer votre portée.",
      es: 'Evalúe gratis y rápidamente la calidad de la localización de su sitio web. Analice los principales elementos multilingües para obtener una puntuación integral y consejos prácticos para mejorar su alcance.',
      de: 'Bewerten Sie kostenlos und schnell die Lokalisierungsqualität Ihrer Website. Analysieren Sie die wichtigsten mehrsprachigen Elemente, um eine umfassende Bewertung und umsetzbare Erkenntnisse zur Verbesserung Ihrer Reichweite zu erhalten.',
      ja: 'ウェブサイトのローカリゼーション品質を無料かつ迅速に評価します。多言語要素を分析して、包括的なスコアとリーチを改善するための実用的な洞察を得ましょう。',
      zh: '快速且免费评估您网站的本地化质量。分析主要多语言元素，获得全面评分和可行见解，从而提升您的覆盖范围。',
      ru: 'Быстро и бесплатно оцените качество локализации вашего сайта. Проанализируйте основные многоязычные элементы, чтобы получить комплексную оценку и практические рекомендации по расширению охвата.',
      ko: '웹사이트의 현지화 품질을 무료로 빠르게 평가하세요. 주요 다국어 요소를 분석해 종합 점수와 영향력 향상을 위한 실행 가능한 인사이트를 얻으세요.',
      it: 'Valuta gratuitamente e rapidamente la qualità della localizzazione del tuo sito. Analizza i principali elementi multilingue per ottenere un punteggio completo e informazioni utili per ampliare la tua portata.',
      pt: 'Avalie gratuitamente e rapidamente a qualidade da localização do seu site. Analise os principais elementos multilíngues para obter uma pontuação abrangente e insights acionáveis para melhorar seu alcance.',
      hi: 'अपनी वेबसाइट की स्थानीयकरण गुणवत्ता का त्वरित और निःशुल्क मूल्यांकन करें। मुख्य बहुभाषी तत्वों का विश्लेषण कर व्यापक स्कोर और पहुँच बढ़ाने के लिए व्यवहारिक सुझाव प्राप्त करें।',
      tr: 'Web sitenizin yerelleştirme kalitesini hızlı ve ücretsiz bir şekilde değerlendirin. Ana çok dilli öğeleri analiz ederek kapsamlı bir puan ve erişiminizi artıracak içgörüler elde edin.',
      pl: 'Szybko i bezpłatnie oceń jakość lokalizacji swojej strony internetowej. Przeanalizuj kluczowe elementy wielojęzyczne, aby uzyskać kompleksową ocenę i praktyczne wskazówki na temat zwiększania zasięgu.',
      id: 'Evaluasi kualitas lokalisasi situs web Anda dengan cepat dan gratis. Analisis elemen multibahasa utama untuk mendapatkan skor komprehensif dan wawasan yang dapat ditindaklanjuti guna meningkatkan jangkauan Anda.',
      vi: 'Đánh giá nhanh và miễn phí chất lượng bản địa hóa của trang web của bạn. Phân tích các yếu tố đa ngôn ngữ chính để nhận điểm số tổng thể và thông tin hữu ích nhằm nâng cao phạm vi tiếp cận.',
      ar: 'قيّم بسرعة وبالمجان جودة التوطين لموقعك الإلكتروني. حلّل العناصر الرئيسية متعددة اللغات للحصول على درجة شاملة ورؤى قابلة للتنفيذ لتحسين وصولك.',
    }),
    steps: t({
      en: [
        'Fetching and parsing HTML...',
        'Analyzing linguistic structure...',
        'Checking hreflang and metadata...',
        'Detecting language selector...',
        'Analyzing SEO multilanguage...',
        'Calculating localization score...',
      ],
      fr: [
        'Récupération et analyse du HTML...',
        'Analyse de la structure linguistique...',
        'Vérification des hreflang et des métadonnées...',
        'Détection du sélecteur de langue...',
        'Analyse du SEO multilingue...',
        'Calcul du score de localisation...',
      ],
      es: [
        'Recuperando y analizando HTML...',
        'Analizando estructura lingüística...',
        'Verificando hreflang y metadatos...',
        'Detectando selector de idioma...',
        'Analizando SEO multilingüe...',
        'Calculando puntuación de localización...',
      ],
      de: [
        'HTML abrufen und parsen...',
        'Analyse der sprachlichen Struktur...',
        'Überprüfung von Hreflang und Metadaten...',
        'Erkennen des Sprachselectors...',
        'Analyse des mehrsprachigen SEO...',
        'Berechnung des Lokalisierungs-Scores...',
      ],
      ja: [
        'HTMLを取得して解析中...',
        '言語構造を分析中...',
        'hreflangとメタデータをチェック中...',
        '言語セレクターを検出中...',
        '多言語SEOを分析中...',
        'ローカリゼーションスコアを計算中...',
      ],
      zh: [
        '获取并解析HTML...',
        '分析语言结构...',
        '检查hreflang和元数据...',
        '检测语言选择器...',
        '分析多语言SEO...',
        '计算本地化评分...',
      ],
      ru: [
        'Получение и разбор HTML...',
        'Анализ языковой структуры...',
        'Проверка hreflang и метаданных...',
        'Обнаружение переключателя языка...',
        'Анализ многоязычного SEO...',
        'Вычисление рейтинга локализации...',
      ],
      ko: [
        'HTML 가져오기 및 파싱 중...',
        '언어 구조 분석 중...',
        'hreflang 및 메타데이터 확인 중...',
        '언어 선택기 감지 중...',
        '다국어 SEO 분석 중...',
        '현지화 점수 계산 중...',
      ],
      it: [
        'Recupero e analisi del codice HTML...',
        'Analisi della struttura linguistica...',
        'Verifica di hreflang e metadati...',
        'Rilevamento del selettore lingua...',
        'Analisi della SEO multilingue...',
        'Calcolo del punteggio di localizzazione...',
      ],
      pt: [
        'Buscando e analisando HTML...',
        'Analisando estrutura linguística...',
        'Verificando hreflang e metadados...',
        'Detectando seletor de idioma...',
        'Analisando SEO multilíngue...',
        'Calculando pontuação de localização...',
      ],
      hi: [
        'HTML प्राप्त कर रहे हैं और विश्लेषण कर रहे हैं...',
        'भाषाई संरचना का विश्लेषण हो रहा है...',
        'hreflang और मेटाडेटा की जांच हो रही है...',
        'भाषा चयनकर्ता का पता लगाया जा रहा है...',
        'बहुभाषी SEO का विश्लेषण हो रहा है...',
        'स्थानीयकरण स्कोर की गणना हो रही है...',
      ],
      tr: [
        'HTML alınıyor ve ayrıştırılıyor...',
        'Dil yapısı analiz ediliyor...',
        'hreflang ve meta veriler kontrol ediliyor...',
        'Dil seçici algılanıyor...',
        'SEO çok dillilik analizi yapılıyor...',
        'Yerelleştirme puanı hesaplanıyor...',
      ],
      pl: [
        'Pobieranie i analizowanie HTML...',
        'Analiza struktury językowej...',
        'Sprawdzanie hreflang i metadanych...',
        'Wykrywanie selektora języka...',
        'Analiza wielojęzycznego SEO...',
        'Obliczanie wyniku lokalizacji...',
      ],
      id: [
        'Mengambil dan mengurai HTML...',
        'Menganalisis struktur linguistik...',
        'Memeriksa hreflang dan metadata...',
        'Mendeteksi pemilih bahasa...',
        'Menganalisis SEO multibahasa...',
        'Menghitung skor lokalisasi...',
      ],
      vi: [
        'Đang lấy và phân tích HTML...',
        'Đang phân tích cấu trúc ngôn ngữ...',
        'Đang kiểm tra hreflang và metadata...',
        'Đang phát hiện bộ chọn ngôn ngữ...',
        'Đang phân tích SEO đa ngôn ngữ...',
        'Đang tính điểm bản địa hóa...',
      ],
      ar: [
        'جلب وتحليل HTML...',
        'تحليل البنية اللغوية...',
        'التحقق من hreflang والبيانات الوصفية...',
        'اكتشاف محدد اللغة...',
        'تحليل تحسين محركات البحث متعدد اللغات...',
        'حساب درجة التوطين...',
      ],
    }),
    error: t({
      en: 'Unable to analyze site.',
      fr: 'Impossible d’analyser le site.',
      es: 'No se puede analizar el sitio.',
      de: 'Website konnte nicht analysiert werden.',
      ja: 'サイトを解析できません。',
      zh: '无法分析网站。',
      ru: 'Не удалось проанализировать сайт.',
      ko: '사이트를 분석할 수 없습니다.',
      it: 'Impossibile analizzare il sito.',
      pt: 'Não foi possível analisar o site.',
      hi: 'साइट का विश्लेषण करने में असमर्थ।',
      tr: 'Site analiz edilemiyor.',
      pl: 'Nie można przeanalizować strony.',
      id: 'Tidak dapat menganalisis situs.',
      vi: 'Không thể phân tích trang web.',
      ar: 'يتعذر تحليل الموقع.',
    }),
  },
  title: 'Localization Analyzer texts',
  description:
    'Localized labels, steps and error messages for the LocalizationAnalyzer component.',
  tags: ['localization', 'analyzer', 'score', 'i18n'],
} satisfies Dictionary;

export default localizationAnalyzerContent;
