import { type Dictionary, t } from 'intlayer';

const localizationAnalyzerContent = {
  key: 'localization-analyzer',
  content: {
    title: t({
      en: 'Analyze Your Website’s Global Localization Score',
      fr: 'Analysez le score de localisation de votre site web',
      es: 'Analice el puntaje de localización global de su sitio web',
      de: 'Analysieren Sie den globalen Lokalisierungs-Score Ihrer Website',
      ja: 'ウェブサイトのグローバルなローカリゼーションスコアを分析します',
      zh: '分析您网站的全球本地化评分',
      ru: 'Проанализируйте общий рейтинг локализации вашего сайта',
      ko: '웹사이트의 글로벌 현지화 점수를 분석하세요',
      it: 'Analizza il punteggio di localizzazione globale del tuo sito web',
      pt: 'Analise a pontuação global de localização do seu site',
      hi: 'अपनी वेबसाइट के ग्लोबल स्थानीयकरण स्कोर का विश्लेषण करें',
      tr: 'Web sitenizin küresel yerelleştirme puanını analiz edin',
      pl: 'Przeanalizuj globalny wynik lokalizacji swojej strony internetowej',
      id: 'Analisis skor lokalisasi global situs web Anda',
      vi: 'Phân tích điểm số bản địa hóa toàn cầu của trang web của bạn',
      ar: 'حلل درجة التوطين العالمية لموقعك',
    }),
    description: t({
      en: 'Quickly and for free, evaluate the localization quality of your website. Analyze principal multilingual elements to get a comprehensive score and actionable insights for improving your reach.',
      fr: "Évaluez gratuitement et rapidement la qualité de la localisation de votre site Web. Analysez les principaux éléments multilingues pour obtenir un score complet et des informations exploitables afin d'améliorer votre portée.",
      es: 'Evalúe gratis y rápidamente la calidad de la localización de su sitio web. Analice los principales elementos multilingües para obtener una puntuación integral y consejos prácticos para mejorar su alcance.',
      de: 'Bewerten Sie kostenlos und schnell die Lokalisierungsqualität Ihrer Website. Analysieren Sie die wichtigsten mehrsprachigen Elemente, um eine umfassende Bewertung und umsetzbare Erkenntnisse zur Verbesserung Ihrer Reichweite zu erhalten.',
      ja: 'ウェブサイトのローカリゼーション品質を無料かつ迅速に評価します。多言語要素を分析して、包括的なスコアとリーチを改善するための実用的な洞察を得ましょう。',
      zh: '快速且免费评估您网站的本地化质量。分析主要多语言元素，获得全面评分和可行见解，从而提升您的覆盖范围。',
      ru: 'Быстро и бесплатно оцените качество локализации вашего сайта. Проанализируйте основные многоязычные элементы, чтобы получить комплексную оценку и практические рекомендации по расширению охвата.',
      ko: '웹사이트의 현지화 품질을 무료로 빠르게 평가하세요. 주요 다국어 요소를 분석해 종합 점수와 영향력 향상을 위한 실행 가능한 인사이트를 얻으세요.',
      it: 'Valuta gratuitamente e rapidamente la qualità della localizzazione del tuo sito. Analizza i principali elementi multilingue per ottenere un punteggio completo e informazioni utili per ampliare la tua portata.',
      pt: 'Avalie gratuitamente e rapidamente a qualidade da localização do seu site. Analise os principais elementos multilíngues para obter uma pontuação abrangente e insights acionáveis para melhorar seu alcance.',
      hi: 'अपनी वेबसाइट की स्थानीयकरण गुणवत्ता का त्वरित और निःशुल्क मूल्यांकन करें। मुख्य बहुभाषी तत्वों का विश्लेषण कर व्यापक स्कोर और पहुँच बढ़ाने के लिए व्यवहारिक सुझाव प्राप्त करें।',
      tr: 'Web sitenizin yerelleştirme kalitesini hızlı ve ücretsiz bir şekilde değerlendirin. Ana çok dilli öğeleri analiz ederek kapsamlı bir puan ve erişiminizi artıracak içgörüler elde edin.',
      pl: 'Szybko i bezpłatnie oceń jakość lokalizacji swojej strony internetowej. Przeanalizuj kluczowe elementy wielojęzyczne, aby uzyskać kompleksową ocenę i praktyczne wskazówki na temat zwiększania zasięgu.',
      id: 'Evaluasi kualitas lokalisasi situs web Anda dengan cepat dan gratis. Analisis elemen multibahasa utama untuk mendapatkan skor komprehensif dan wawasan yang dapat ditindaklanjuti guna meningkatkan jangkauan Anda.',
      vi: 'Đánh giá nhanh và miễn phí chất lượng bản địa hóa của trang web của bạn. Phân tích các yếu tố đa ngôn ngữ chính để nhận điểm số tổng thể và thông tin hữu ích nhằm nâng cao phạm vi tiếp cận.',
      ar: 'قيّم بسرعة وبالمجان جودة التوطين لموقعك الإلكتروني. حلّل العناصر الرئيسية متعددة اللغات للحصول على درجة شاملة ورؤى قابلة للتنفيذ لتحسين وصولك.',
    }),
    error: t({
      en: 'Unable to analyze site.',
      fr: 'Impossible d’analyser le site.',
      es: 'No se puede analizar el sitio.',
      de: 'Website konnte nicht analysiert werden.',
      ja: 'サイトを解析できません。',
      zh: '无法分析网站。',
      ru: 'Не удалось проанализировать сайт.',
      ko: '사이트를 분석할 수 없습니다.',
      it: 'Impossibile analizzare il sito.',
      pt: 'Não foi possível analisar o site.',
      hi: 'साइट का विश्लेषण करने में असमर्थ।',
      tr: 'Site analiz edilemiyor.',
      pl: 'Nie można przeanalizować strony.',
      id: 'Tidak dapat menganalisis situs.',
      vi: 'Không thể phân tích trang web.',
      ar: 'يتعذر تحليل الموقع.',
    }),
  },
  title: 'Localization Analyzer texts',
  description:
    'Localized labels, steps and error messages for the LocalizationAnalyzer component.',
  tags: ['localization', 'analyzer', 'score', 'i18n'],
} satisfies Dictionary;

export default localizationAnalyzerContent;
