import { type Dictionary, t } from 'intlayer';

const recursiveAuditResultsContent = {
  key: 'recursive-audit-results',
  content: {
    title: t({
      en: 'Full Site Audit Progress',
      fr: "Progression de l'audit complet du site",
      es: 'Progreso de la auditoría completa del sitio',
      de: 'Fortschritt der vollständigen Website-Prüfung',
      ja: 'サイト全体の監査進捗',
      zh: '全站审核进度',
      ru: 'Прогресс полного аудита сайта',
      ko: '전체 사이트 감사 진행 상황',
      it: "Avanzamento dell'audit completo del sito",
      pt: 'Progresso da auditoria completa do site',
      hi: 'पूर्ण साइट ऑडिट प्रगति',
      tr: 'Tam Site Denetim İlerlemesi',
      pl: 'Postęp pełnego audytu strony',
      id: 'Kemajuan Audit Situs Penuh',
      vi: 'Tiến trình kiểm tra toàn bộ trang web',
      ar: 'تقدم التدقيق الكامل للموقع',
      'en-GB': 'Full Site Audit Progress',
      uk: 'Прогрес повного аудиту сайту',
    }),
    progressLabel: t({
      en: 'Progress',
      fr: 'Progression',
      es: 'Progreso',
      de: 'Fortschritt',
      ja: '進捗',
      zh: '进度',
      ru: 'Прогресс',
      ko: '진행 상황',
      it: 'Avanzamento',
      pt: 'Progresso',
      hi: 'प्रगति',
      tr: 'İlerleme',
      pl: 'Postęp',
      id: 'Kemajuan',
      vi: 'Tiến trình',
      ar: 'التقدم',
      'en-GB': 'Progress',
      uk: 'Прогрес',
    }),
    pagesAudited: t({
      en: 'pages audited',
      fr: 'pages auditées',
      es: 'páginas auditadas',
      de: 'Seiten geprüft',
      ja: 'ページ監査済み',
      zh: '页已审核',
      ru: 'страниц проверено',
      ko: '페이지 감사됨',
      it: 'pagine verificate',
      pt: 'páginas auditadas',
      hi: 'पृष्ठ ऑडिट किए गए',
      tr: 'sayfa denetlendi',
      pl: 'stron poddanych audytowi',
      id: 'halaman diaudit',
      vi: 'trang đã kiểm tra',
      ar: 'صفحة تم تدقيقها',
      'en-GB': 'pages audited',
      uk: 'сторінок перевірено',
    }),
    resumeButton: t({
      en: 'Resume',
      fr: 'Reprendre',
      es: 'Reanudar',
      de: 'Fortsetzen',
      ja: '再開',
      zh: '继续',
      ru: 'Возобновить',
      ko: '재개',
      it: 'Riprendi',
      pt: 'Retomar',
      hi: 'फिर शुरू करें',
      tr: 'Devam Et',
      pl: 'Wznów',
      id: 'Lanjutkan',
      vi: 'Tiếp tục',
      ar: 'استئناف',
      'en-GB': 'Resume',
      uk: 'Відновити',
    }),
    pauseButton: t({
      en: 'Pause',
      fr: 'Pause',
      es: 'Pausar',
      de: 'Pausieren',
      ja: '一時停止',
      zh: '暂停',
      ru: 'Пауза',
      ko: '일시 중지',
      it: 'Pausa',
      pt: 'Pausar',
      hi: 'रोकें',
      tr: 'Duraklat',
      pl: 'Wstrzymaj',
      id: 'Jeda',
      vi: 'Tạm dừng',
      ar: 'إيقاف مؤقت',
      'en-GB': 'Pause',
      uk: 'Пауза',
    }),
    stopButton: t({
      en: 'Stop',
      fr: 'Arrêter',
      es: 'Detener',
      de: 'Stopp',
      ja: '停止',
      zh: '停止',
      ru: 'Остановить',
      ko: '정지',
      it: 'Ferma',
      pt: 'Parar',
      hi: 'रोकें',
      tr: 'Durdur',
      pl: 'Zatrzymaj',
      id: 'Hentikan',
      vi: 'Dừng',
      ar: 'إيقاف',
      'en-GB': 'Stop',
      uk: 'Зупинити',
    }),
    columnUrl: t({
      en: 'URL',
      fr: 'URL',
      es: 'URL',
      de: 'URL',
      ja: 'URL',
      zh: 'URL',
      ru: 'URL',
      ko: 'URL',
      it: 'URL',
      pt: 'URL',
      hi: 'URL',
      tr: 'URL',
      pl: 'URL',
      id: 'URL',
      vi: 'URL',
      ar: 'URL',
      'en-GB': 'URL',
      uk: 'URL',
    }),
    columnStatus: t({
      en: 'Status',
      fr: 'Statut',
      es: 'Estado',
      de: 'Status',
      ja: 'ステータス',
      zh: '状态',
      ru: 'Статус',
      ko: '상태',
      it: 'Stato',
      pt: 'Status',
      hi: 'स्थिति',
      tr: 'Durum',
      pl: 'Status',
      id: 'Status',
      vi: 'Trạng thái',
      ar: 'الحالة',
      'en-GB': 'Status',
      uk: 'Статус',
    }),
    columnScore: t({
      en: 'Score',
      fr: 'Score',
      es: 'Puntuación',
      de: 'Bewertung',
      ja: 'スコア',
      zh: '评分',
      ru: 'Оценка',
      ko: '점수',
      it: 'Punteggio',
      pt: 'Pontuação',
      hi: 'स्कोर',
      tr: 'Puan',
      pl: 'Wynik',
      id: 'Skor',
      vi: 'Điểm',
      ar: 'النتيجة',
      'en-GB': 'Score',
      uk: 'Оцінка',
    }),
  },

  title: 'Recursive Audit Results texts',
  description: 'Localized labels for the RecursiveAuditResults component.',
  tags: ['audit', 'recursive', 'results'],
} satisfies Dictionary;

export default recursiveAuditResultsContent;
