import { type Dictionary, t } from 'intlayer';

const adminSidebarContent = {
  key: 'admin-sidebar',
  content: {
    navigation: {
      dashboard: {
        label: t({
          en: 'Go to dashboard',
          fr: 'Aller au tableau de bord',
          es: 'Ir al tablero',
          'en-GB': 'Go to dashboard',
          de: 'Zum Dashboard gehen',
          ja: 'ダッシュボードに移動',
          ko: '대시보드로 이동',
          zh: '转到仪表板',
          it: 'Vai alla dashboard',
          pt: 'Ir para o painel',
          hi: 'डैशबोर्ड पर जाएं',
          ar: 'اذهب إلى لوحة القيادة',
          ru: 'Перейти на прибортную панель',
          tr: 'Dashboarde git',
          pl: 'Przejdź do pulpitu',
          id: 'Buka dashboard',
          vi: 'Đi tới bảng điều khiển',
          uk: 'Перейти до панелі керування',
        }),
        title: t({
          en: 'Dashboard',
          fr: 'Tableau de bord',
          es: 'Tablero',
          'en-GB': 'Dashboard',
          de: 'Armaturenbrett',
          ja: 'ダッシュボード',
          ko: '대시보드',
          zh: '仪表板',
          it: 'Dashboard',
          pt: 'Painel',
          hi: 'डैशबोर्ड',
          ar: 'لوحة القيادة',
          ru: 'Приборная панель',
          tr: 'Dashboard',
          pl: 'Pulpit',
          id: 'Dashboard',
          vi: 'Bảng điều khiển',
          uk: 'Панель керування',
        }),
      },
      management: {
        label: t({
          en: 'Management section',
          fr: 'Section de gestion',
          es: 'Sección de gestión',
          'en-GB': 'Management section',
          de: 'Verwaltungsbereich',
          ja: '管理セクション',
          ko: '관리 섹션',
          zh: '管理部分',
          it: 'Sezione di gestione',
          pt: 'Seção de gerenciamento',
          hi: 'प्रबंधन अनुभाग',
          ar: 'قسم الإدارة',
          ru: 'Раздел управления',
          tr: 'Yönetim bölümü',
          pl: 'Sekcja zarządzania',
          id: 'Bagian manajemen',
          vi: 'Mục quản lý',
          uk: 'Розділ керування',
        }),
        title: t({
          en: 'Management',
          fr: 'Gestion',
          es: 'Gestión',
          'en-GB': 'Management',
          de: 'Verwaltung',
          ja: '管理',
          ko: '관리',
          zh: '管理',
          it: 'Gestione',
          pt: 'Gerenciamento',
          hi: 'प्रबंधन',
          ar: 'الإدارة',
          ru: 'Управление',
          tr: 'Yönetim',
          pl: 'Zarządzanie',
          id: 'Manajemen',
          vi: 'Quản lý',
          uk: 'Керування',
        }),
        organizations: {
          label: t({
            en: 'Manage organizations',
            fr: 'Gérer les organisations',
            es: 'Gestionar organizaciones',
            'en-GB': 'Manage organizations',
            de: 'Organisationen verwalten',
            ja: '組織を管理',
            ko: '조직 관리',
            zh: '管理组织',
            it: 'Gestisci organizzazioni',
            pt: 'Gerenciar organizações',
            hi: 'संगठनों का प्रबंधन',
            ar: 'إدارة المنظمات',
            ru: 'Управление организациями',
            tr: 'Organizasyonları yönet',
            pl: 'Zarządzaj organizacjami',
            id: 'Kelola organisasi',
            vi: 'Quản lý tổ chức',
            uk: 'Керувати організаціями',
          }),
          title: t({
            en: 'Organizations',
            fr: 'Organisations',
            es: 'Organizaciones',
            'en-GB': 'Organisations',
            de: 'Organisationen',
            ja: '組織',
            ko: '조직',
            zh: '组织',
            it: 'Organizzazioni',
            pt: 'Organizações',
            hi: 'संगठन',
            ar: 'المنظمات',
            ru: 'Организации',
            tr: 'Organizasyonlar',
            pl: 'Organizacje',
            id: 'Organisasi',
            vi: 'Tổ chức',
            uk: 'Організації',
          }),
        },
        projects: {
          label: t({
            en: 'Manage projects',
            fr: 'Gérer les projets',
            es: 'Gestionar proyectos',
            'en-GB': 'Manage projects',
            de: 'Projekte verwalten',
            ja: 'プロジェクトを管理',
            ko: '프로젝트 관리',
            zh: '管理项目',
            it: 'Gestisci progetti',
            pt: 'Gerenciar projetos',
            hi: 'परियोजनाओं का प्रबंधन',
            ar: 'إدارة المشاريع',
            ru: 'Управление проектами',
            tr: 'Projeleri yönet',
            pl: 'Zarządzaj projektami',
            id: 'Kelola proyek',
            vi: 'Quản lý dự án',
            uk: 'Керувати проєктами',
          }),
          title: t({
            en: 'Projects',
            fr: 'Projets',
            es: 'Proyectos',
            'en-GB': 'Projects',
            de: 'Projekte',
            ja: 'プロジェクト',
            ko: '프로젝트',
            zh: '项目',
            it: 'Progetti',
            pt: 'Projetos',
            hi: 'परियोजनाएं',
            ar: 'المشاريع',
            ru: 'Проекты',
            tr: 'Projeler',
            pl: 'Projekty',
            id: 'Proyek',
            vi: 'Dự án',
            uk: 'Проєкти',
          }),
        },
        users: {
          label: t({
            en: 'Manage users',
            fr: 'Gérer les utilisateurs',
            es: 'Gestionar usuarios',
            'en-GB': 'Manage users',
            de: 'Benutzer verwalten',
            ja: 'ユーザーを管理',
            ko: '사용자 관리',
            zh: '管理用户',
            it: 'Gestisci utenti',
            pt: 'Gerenciar usuários',
            hi: 'उपयोगकर्ताओं का प्रबंधन',
            ar: 'إدارة المستخدمين',
            ru: 'Управление пользователями',
            tr: 'Kullanıcıları yönet',
            pl: 'Zarządzaj użytkownikami',
            id: 'Kelola pengguna',
            vi: 'Quản lý người dùng',
            uk: 'Керувати користувачами',
          }),
          title: t({
            en: 'Users',
            fr: 'Utilisateurs',
            es: 'Usuarios',
            'en-GB': 'Users',
            de: 'Benutzer',
            ja: 'ユーザー',
            ko: '사용자',
            zh: '用户',
            it: 'Utenti',
            pt: 'Usuários',
            hi: 'उपयोगकर्ता',
            ar: 'المستخدمون',
            ru: 'Пользователи',
            tr: 'Kullanıcılar',
            pl: 'Użytkownicy',
            id: 'Pengguna',
            vi: 'Người dùng',
            uk: 'Користувачі',
          }),
        },
        discussions: {
          label: t({
            en: 'Manage discussions',
            fr: 'Gérer les discussions',
            es: 'Gestionar discusiones',
            'en-GB': 'Manage discussions',
            de: 'Diskussionen verwalten',
            ja: 'ディスカッションを管理',
            ko: '토론 관리',
            zh: '管理讨论',
            it: 'Gestisci discussioni',
            pt: 'Gerenciar discussões',
            hi: 'चर्चा प्रबंधन',
            ar: 'إدارة المناقشات',
            ru: 'Управление обсуждениями',
            tr: 'Tartışma yönetimi',
            pl: 'Zarządzaj dyskusjami',
            id: 'Kelola diskusi',
            vi: 'Quản lý thảo luận',
            uk: 'Керувати обговореннями',
          }),
          title: t({
            en: 'Discussions',
            fr: 'Discussions',
            es: 'Discusiones',
            'en-GB': 'Discussions',
            de: 'Diskussionen',
            ja: 'ディスカッション',
            ko: '토론',
            zh: '讨论',
            it: 'Discussioni',
            pt: 'Discussões',
            hi: 'चर्चा',
            ar: 'المناقشات',
            ru: 'Обсуждения',
            tr: 'Tartışmalar',
            pl: 'Dyskusje',
            id: 'Diskusi',
            vi: 'Thảo luận',
            uk: 'Обговорення',
          }),
        },
        affiliate: {
          label: t({
            en: 'Manage affiliate program',
            fr: "Gérer le programme d'affiliation",
            es: 'Gestionar programa de afiliados',
            ru: 'Управление партнёрской программой',
            ja: 'アフィリエイトプログラムを管理',
            ko: '제휴 프로그램 관리',
            zh: '管理联盟计划',
            de: 'Affiliate-Programm verwalten',
            ar: 'إدارة برنامج التسويق بالعمولة',
            it: 'Gestisci il programma di affiliazione',
            'en-GB': 'Manage affiliate program',
            pt: 'Gerenciar programa de afiliados',
            hi: 'अफिलिएट कार्यक्रम प्रबंधित करें',
            tr: 'Ortaklık programını yönet',
            pl: 'Zarządzaj programem partnerskim',
            id: 'Kelola program afiliasi',
            vi: 'Quản lý chương trình liên kết',
            uk: 'Керувати партнерською програмою',
          }),
          title: t({
            en: 'Affiliate',
            fr: 'Affiliation',
            es: 'Afiliados',
            ru: 'Партнёр',
            ja: 'アフィリエイト',
            ko: '제휴',
            zh: '推广合伙人',
            de: 'Affiliate',
            ar: 'شريك تسويق',
            it: 'Affiliazione',
            'en-GB': 'Affiliate',
            pt: 'Afiliado',
            hi: 'अफिलिएट',
            tr: 'Ortaklık',
            pl: 'Partner',
            id: 'Afiliasi',
            vi: 'Đối tác liên kết',
            uk: 'Партнерська програма',
          }),
        },
        promoCodes: {
          label: t({
            en: 'Manage promo codes',
            fr: 'Gérer les codes promotionnels',
            es: 'Gestionar códigos promocionales',
            ru: 'Управление промокодами',
            ja: 'プロモーションコードを管理',
            ko: '프로모션 코드 관리',
            zh: '管理促销代码',
            de: 'Promo-Codes verwalten',
            ar: 'إدارة الرموز الترويجية',
            it: 'Gestisci i codici promozionali',
            'en-GB': 'Manage promo codes',
            pt: 'Gerenciar códigos promocionais',
            hi: 'प्रोमो कोड प्रबंधित करें',
            tr: 'Promosyon kodlarını yönet',
            pl: 'Zarządzaj kodami promocyjnymi',
            id: 'Kelola kode promo',
            vi: 'Quản lý mã khuyến mãi',
            uk: 'Керувати промокодами',
          }),
          title: t({
            en: 'Promo Codes',
            fr: 'Codes Promo',
            es: 'Códigos Promo',
            ru: 'Промокоды',
            ja: 'プロモコード',
            ko: '프로모션 코드',
            zh: '促销代码',
            de: 'Promo-Codes',
            ar: 'الرموز الترويجية',
            it: 'Codici Promo',
            'en-GB': 'Promo Codes',
            pt: 'Códigos Promo',
            hi: 'प्रोमो कोड',
            tr: 'Promosyon Kodları',
            pl: 'Kody Promocyjne',
            id: 'Kode Promo',
            vi: 'Mã Khuyến Mãi',
            uk: 'Промокоди',
          }),
        },
        reviewers: {
          label: t({
            en: 'Manage reviewers',
            fr: 'Gérer les traducteurs',
            es: 'Gestionar traductores',
            ru: 'Управление рецензентами',
            ja: 'レビュアーを管理',
            ko: '검토자 관리',
            zh: '管理评审人员',
            de: 'Rezensenten verwalten',
            ar: 'إدارة المراجعين',
            it: 'Gestisci i revisori',
            'en-GB': 'Manage reviewers',
            pt: 'Gerenciar revisores',
            hi: 'समीक्षकों का प्रबंधन करें',
            tr: 'İnceleyicileri yönet',
            pl: 'Zarządzaj recenzentami',
            id: 'Kelola pengulas',
            vi: 'Quản lý người đánh giá',
            uk: 'Керувати рецензентами',
          }),
          title: t({
            en: 'Reviewers',
            fr: 'Traducteurs',
            es: 'Traductores',
            ru: 'Рецензенты',
            ja: 'レビュアー',
            ko: '검토자',
            zh: '评审人员',
            de: 'Rezensenten',
            ar: 'المراجعون',
            it: 'Revisori',
            'en-GB': 'Reviewers',
            pt: 'Revisores',
            hi: 'समीक्षक',
            tr: 'İnceleyiciler',
            pl: 'Recenzenci',
            id: 'Pengulas',
            vi: 'Người đánh giá',
            uk: 'Рецензенти',
          }),
        },
      },
    },
    adminSectionNavigation: t({
      en: 'Admin section navigation',
      fr: 'Navigation de la section administration',
      es: 'Navegación de la sección de administración',
      ru: 'Навигация по разделу администратора',
      ja: '管理セクションのナビゲーション',
      ko: '관리자 섹션 탐색',
      zh: '管理员部分导航',
      de: 'Navigation des Admin-Bereichs',
      ar: 'التنقل في قسم الإدارة',
      it: 'Navigazione sezione amministratore',
      'en-GB': 'Admin section navigation',
      pt: 'Navegação da seção de administração',
      hi: 'प्रशासन अनुभाग का नेविगेशन',
      tr: 'Yönetici bölümü navigasyonu',
      pl: 'Nawigacja sekcji administracyjnej',
      id: 'Navigasi bagian admin',
      vi: 'Điều hướng phần quản trị',
      uk: 'Навігація розділу адміністратора',
    }),
  },
  title: 'Admin sidebar navigation',
  description:
    'Content declaration for the admin sidebar navigation, includes labels and titles for dashboard access and management sections such as organizations, projects, users, and discussions.',
  tags: ['admin panel', 'sidebar navigation', 'dashboard'],
} satisfies Dictionary;

export default adminSidebarContent;
