import { type Dictionary, t } from 'intlayer';

const projectConfigDetailsContent = {
  key: 'project-config-detail',
  content: {
    title: t({
      en: 'Project configuration',
      'en-GB': 'Project configuration',
      fr: 'Configuration du projet',
      es: 'Configuración del proyecto',
      de: 'Projektkonfiguration',
      ja: 'プロジェクトの構成',
      ko: '프로젝트 구성',
      zh: '项目配置',
      it: 'Configurazione del progetto',
      pt: 'Configuração do projeto',
      hi: 'प्रोजेक्ट कॉन्फ़िगरेशन',
      ar: 'تكوين المشروع',
      ru: 'Конфигурация проекта',
      tr: 'Proje yapılandırması',
      pl: 'Konfiguracja projektu',
      id: 'Konfigurasi proyek',
      vi: 'Cấu hình dự án',
      uk: 'Конфігурація проєкту',
    }),
    i18nSection: {
      title: t({
        en: 'Internationalization',
        'en-GB': 'Internationalization',
        fr: 'Internationalisation',
        es: 'Internacionalización',
        de: 'Internationalisierung',
        ja: '国際化',
        ko: '국제화',
        zh: '国际化',
        it: 'Internazionalizzazione',
        pt: 'Internacionalização',
        hi: 'अनेक्षांश',
        ar: 'التدويل الدولي',
        ru: 'Интернационализация',
        tr: 'Uluslararasılaştırma',
        pl: 'Internacjonalizacja',
        id: 'Internasionalisasi',
        vi: 'Quốc tế hóa (i18n)',
        uk: 'Інтернаціоналізація',
      }),
      localeListTitle: t({
        en: 'Available locales',
        'en-GB': 'Available locales',
        fr: 'Locales disponibles',
        es: 'Locales disponibles',
        de: 'Verfügbare Lokalisierungen',
        ja: '利用可能なロケール',
        ko: '사용 가능한 로케일',
        zh: '可用的地区',
        it: 'Localizzazioni disponibili',
        pt: 'Localizações disponíveis',
        hi: 'उपलब्ध स्थान',
        ar: 'المواقع المتاحة',
        ru: 'Доступные локализации',
        tr: 'Mevcut yereller',
        pl: 'Dostępne lokalizacje',
        id: 'Daftar locale yang tersedia',
        vi: 'Các locale khả dụng',
        uk: 'Доступні локалі',
      }),
      defaultLocaleTitle: t({
        en: 'Default locale',
        'en-GB': 'Default locale',
        fr: 'Locale par défaut',
        es: 'Locale predeterminada',
        de: 'Standard-Lokalisierung',
        ja: 'デフォルトのロケール',
        ko: '기본 로케일',
        zh: '默认地区',
        it: 'Localizzazione predefinita',
        pt: 'Localização padrão',
        hi: 'डिफ़ॉल्ट स्थान',
        ar: 'الموقع الافتراضي',
        ru: 'Локализация по умолчанию',
        tr: 'Varsayılan yerel',
        pl: 'Domyślna lokalizacja',
        id: 'Locale default',
        vi: 'Locale mặc định',
        uk: 'Локаль за замовчуванням',
      }),
    },

    editorSection: {
      title: t({
        en: 'Editor',
        'en-GB': 'Editor',
        fr: 'Éditeur',
        es: 'Editor',
        de: 'Editor',
        ja: 'エディタ',
        ko: '편집기',
        zh: '编辑器',
        it: 'Editor',
        pt: 'Editor',
        hi: 'संपादक',
        ar: 'المحرر',
        ru: 'Редактор',
        tr: 'Editör',
        pl: 'Edytor',
        id: 'Editor',
        vi: 'Editor',
        uk: 'Редактор',
      }),
      applicationURL: {
        title: t({
          en: 'Application URL',
          'en-GB': 'Application URL',
          fr: "URL de l'application",
          es: 'URL de la aplicación',
          de: 'Anwendungs-URL',
          ja: 'アプリケーション URL',
          ko: '애플리케이션 URL',
          zh: '应用程序 URL',
          it: "URL dell'applicazione",
          pt: 'URL do aplicativo',
          hi: 'एप्लीकेशन URL',
          ar: 'عنوان URL التطبيق',
          ru: 'URL-адрес приложения',
          tr: "Uygulama URL'si",
          pl: 'URL aplikacji',
          id: 'URL Aplikasi',
          vi: 'URL ứng dụng',
          uk: 'URL застосунку',
        }),
        label: t({
          en: "Click to navigate to the application's URL",
          'en-GB': "Click to navigate to the application's URL",
          fr: "Cliquez pour accéder à l'URL de l'application",
          es: 'Haga clic para navegar a la URL de la aplicación',
          de: 'Klicken Sie hier, um zur Anwendungs-URL zu navigieren',
          ja: 'アプリケーション URL に移動するにはクリックしてください',
          ko: '애플리케이션 URL으로 이동하려면 클릭하세요',
          zh: '点击查看应用程序的 URL',
          it: "Clicca per andare all'URL dell'applicazione",
          pt: 'Clique para acessar a URL do aplicativo',
          hi: 'एप्लीकेशन URL पर जाने के लिए क्लिक करें',
          ar: 'انقر للانتقال إلى عنوان URL التطبيق',
          ru: 'Нажмите, чтобы перейти к URL-адресу приложения',
          tr: "Uygulamanın URL'sine gitmek için tıklayın",
          pl: 'Kliknij, aby przejść do adresu URL aplikacji',
          id: 'Klik untuk membuka URL aplikasi',
          vi: 'Nhấp để điều hướng đến URL của ứng dụng',
          uk: 'Натисніть, щоб перейти за URL застосунку',
        }),
      },
      cmsURL: {
        title: t({
          en: 'CMS URL',
          'en-GB': 'CMS URL',
          fr: 'URL du CMS',
          es: 'URL del CMS',
          de: 'CMS-URL',
          ja: 'CMS URL',
          ko: 'CMS URL',
          zh: 'CMS URL',
          it: 'URL del CMS',
          pt: 'URL do CMS',
          hi: 'CMS URL',
          ar: 'عنوان URL للمحرك المرئي',
          ru: 'URL-адрес CMS',
          tr: 'CMS URL',
          pl: 'URL CMS',
          id: 'URL CMS',
          vi: 'URL CMS',
          uk: 'URL CMS',
        }),
        label: t({
          en: 'Click to navigate to the CMS URL',
          'en-GB': 'Click to navigate to the CMS URL',
          fr: "Cliquez pour accéder à l'URL du CMS",
          es: 'Haga clic para navegar a la URL del CMS',
          de: 'Klicken Sie hier, um zur CMS-URL zu navigieren',
          ja: 'CMS URLに移動するにはクリックしてください',
          ko: 'CMS URL로 이동하려면 클릭하세요',
          zh: '点击查看CMS URL',
          it: "Clicca per andare all'URL del CMS",
          pt: 'Clique para acessar a URL do CMS',
          hi: 'क्लिक करें के लिए CMS URL पर जाएं',
          ar: 'انقر للانتقال إلى عنوان URL للمحرك المرئي',
          ru: 'Нажмите, чтобы перейти к URL-адресу CMS',
          tr: "CMS URL'ine gitmek için tıklayın",
          pl: 'Kliknij, aby przejść do adresu URL CMS',
          id: 'Klik untuk membuka URL CMS',
          vi: 'Nhấp để điều hướng đến URL của CMS',
          uk: 'Натисніть, щоб перейти за URL CMS',
        }),
      },
    },

    aiSection: {
      title: t({
        en: 'AI Configuration',
        'en-GB': 'AI Configuration',
        fr: "Configuration de l'IA",
        es: 'Configuración de IA',
        de: 'KI-Konfiguration',
        ja: 'AI設定',
        ko: 'AI 구성',
        zh: 'AI 配置',
        it: 'Configurazione IA',
        pt: 'Configuração de IA',
        hi: 'AI कॉन्फ़िगरेशन',
        ar: 'تكوين الذكاء الاصطناعي',
        ru: 'Настройка ИИ',
        tr: 'AI Yapılandırması',
        pl: 'Konfiguracja AI',
        id: 'Konfigurasi AI',
        vi: 'Cấu hình AI',
        uk: 'Налаштування ШІ',
      }),
      provider: {
        title: t({
          en: 'AI Provider',
          'en-GB': 'AI Provider',
          fr: "Fournisseur d'IA",
          es: 'Proveedor de IA',
          de: 'KI-Anbieter',
          ja: 'AIプロバイダー',
          ko: 'AI 제공자',
          zh: 'AI 提供商',
          it: 'Provider IA',
          pt: 'Provedor de IA',
          hi: 'AI प्रदाता',
          ar: 'مزود الذكاء الاصطناعي',
          ru: 'Поставщик ИИ',
          tr: 'AI Sağlayıcı',
          pl: 'Dostawca AI',
          id: 'Penyedia AI',
          vi: 'Nhà cung cấp AI',
          uk: 'Провайдер ШІ',
        }),
      },
      model: {
        title: t({
          en: 'AI Model',
          'en-GB': 'AI Model',
          fr: "Modèle d'IA",
          es: 'Modelo de IA',
          de: 'KI-Modell',
          ja: 'AIモデル',
          ko: 'AI 모델',
          zh: 'AI 模型',
          it: 'Modello IA',
          pt: 'Modelo de IA',
          hi: 'AI मॉडल',
          ar: 'نموذج الذكاء الاصطناعي',
          ru: 'Модель ИИ',
          tr: 'AI Modeli',
          pl: 'Model AI',
          id: 'Model AI',
          vi: 'Mô hình AI',
          uk: 'Модель ШІ',
        }),
      },
      apiKey: {
        title: t({
          en: 'API Key',
          'en-GB': 'API Key',
          fr: "Clé d'API",
          es: 'Clave de API',
          de: 'API-Schlüssel',
          ja: 'APIキー',
          ko: 'API 키',
          zh: 'API 密钥',
          it: 'Chiave API',
          pt: 'Chave de API',
          hi: 'API कुंजी',
          ar: 'مفتاح API',
          ru: 'API ключ',
          tr: 'API Anahtarı',
          pl: 'Klucz API',
          id: 'Kunci API',
          vi: 'Khóa API',
          uk: 'API-ключ',
        }),
        configured: t({
          en: 'Configured',
          'en-GB': 'Configured',
          fr: 'Configuré',
          es: 'Configurado',
          de: 'Konfiguriert',
          ja: '設定済み',
          ko: '구성됨',
          zh: '已配置',
          it: 'Configurato',
          pt: 'Configurado',
          hi: 'कॉन्फ़िगर किया गया',
          ar: 'تم التكوين',
          ru: 'Настроено',
          tr: 'Yapılandırıldı',
          pl: 'Skonfigurowano',
          id: 'Dikonfigurasi',
          vi: 'Đã cấu hình',
          uk: 'Налаштовано',
        }),
        notConfigured: t({
          en: 'Not configured',
          'en-GB': 'Not configured',
          fr: 'Non configuré',
          es: 'No configurado',
          de: 'Nicht konfiguriert',
          ja: '未設定',
          ko: '구성되지 않음',
          zh: '未配置',
          it: 'Non configurato',
          pt: 'Não configurado',
          hi: 'कॉन्फ़िगर नहीं किया गया',
          ar: 'غير مكون',
          ru: 'Не настроено',
          tr: 'Yapılandırılmadı',
          pl: 'Nie skonfigurowano',
          id: 'Tidak dikonfigurasi',
          vi: 'Chưa cấu hình',
          uk: 'Не налаштовано',
        }),
      },
      applicationContext: {
        title: t({
          en: 'Application Context',
          'en-GB': 'Application Context',
          fr: "Contexte de l'application",
          es: 'Contexto de la aplicación',
          de: 'Anwendungskontext',
          ja: 'アプリケーションコンテキスト',
          ko: '애플리케이션 컨텍스트',
          zh: '应用程序上下文',
          it: "Contesto dell'applicazione",
          pt: 'Contexto da aplicação',
          hi: 'एप्लिकेशन संदर्भ',
          ar: 'سياق التطبيق',
          ru: 'Контекст приложения',
          tr: 'Uygulama Bağlamı',
          pl: 'Kontekst aplikacji',
          id: 'Konteks Aplikasi',
          vi: 'Ngữ cảnh ứng dụng',
          uk: 'Контекст застосунку',
        }),
      },
    },

    noConfig: {
      message: t({
        en: 'No configuration pushed. Please push your configuration first using the CLI.',
        'en-GB':
          'No configuration pushed. Please push your configuration first using the CLI.',
        fr: "Aucune configuration poussée. Veuillez d'abord pousser votre configuration à l'aide de la CLI.",
        es: 'No hay configuración empujada. Por favor, empuje su configuración primero utilizando la CLI.',
        de: 'Keine Konfiguration hochgeladen. Bitte laden Sie zuerst Ihre Konfiguration über die CLI hoch.',
        ja: 'コンフィグレーションがプッシュされていません。CLIを使用して、最初にコンフィグレーションをプッシュしてください。',
        ko: '설정이 푸시되지 않았습니다. 먼저 CLI를 사용하여 설정을 푸시하세요.',
        zh: '未推送配置。请先使用CLI推送配置。',
        it: 'Nessuna configurazione caricata. Caricare prima la configurazione utilizzando la CLI.',
        pt: 'Nenhuma configuração enviada. Por favor, envie sua configuração primeiro usando a CLI.',
        hi: 'कोई विन्यास पुश्पित नहीं है। कृपया पहले CLI का उपयोग करें से अपने विन्यास पुश्पित करें।',
        ar: 'لا تم تحميل التكوين. يرجى تحميل التكوين الخاص بك أولاً باستخدام CLI.',
        ru: 'Не загружена конфигурация. Пожалуйста, сначала загрузите конфигурацию с помощью CLI.',
        tr: 'Yapılandırma yüklenmedi. Lütfen önce CLI kullanarak yapılandırmanızı yükleyin.',
        pl: 'Nie przesłano konfiguracji. Najpierw wyślij konfigurację za pomocą CLI.',
        id: 'Belum ada konfigurasi yang dipush. Silakan push konfigurasi Anda terlebih dahulu menggunakan CLI.',
        vi: 'Chưa có cấu hình được đẩy. Vui lòng đẩy cấu hình của bạn trước bằng CLI.',
        uk: 'Конфігурацію не надіслано. Будь ласка, спочатку надішліть конфігурацію за допомогою CLI.',
      }),
    },
    updateConfig: {
      message: t({
        en: 'You can update your configuration using the CLI.',
        'en-GB': 'You can update your configuration using the CLI.',
        fr: 'Vous pouvez mettre à jour votre configuration en utilisant la CLI.',
        es: 'Puede actualizar su configuración utilizando la CLI.',
        de: 'Sie können Ihre Konfiguration mit der CLI aktualisieren.',
        ja: 'CLI を使用して、構成を更新できます。',
        ko: 'CLI를 사용하여 구성을 업데이트할 수 있습니다.',
        zh: '您可以使用 CLI 更新您的配置。',
        it: 'È possibile aggiornare la configurazione utilizzando la CLI.',
        pt: 'Você pode atualizar sua configuração usando a CLI.',
        hi: 'आप CLI के साथ अपनी विन्यास को अद्यतन कर सकते हैं।',
        ar: 'يمكنك تحديث تكوينك باستخدام CLI.',
        ru: 'Вы можете обновить конфигурацию с помощью CLI.',
        tr: 'Yapılandırmanızı CLI kullanarak güncelleyebilirsiniz',
        pl: 'Możesz zaktualizować konfigurację za pomocą CLI.',
        id: 'Anda dapat memperbarui konfigurasi Anda menggunakan CLI.',
        vi: 'Bạn có thể cập nhật cấu hình bằng CLI.',
        uk: 'Ви можете оновити конфігурацію за допомогою CLI.',
      }),
    },
    pushConfigDocLink: {
      text: t({
        en: 'See how to push your configuration',
        'en-GB': 'See how to push your configuration',
        fr: 'Voir comment pousser votre configuration',
        es: 'Ver cómo empujar su configuración',
        de: 'Siehe, wie Sie Ihre Konfiguration hochladen',
        ja: 'コンフィグレーションをプッシュする方法を見る',
        ko: '설정을 푸시하는 방법을 보십시오',
        zh: '查看如何推送您的配置',
        it: 'Vedi come caricare la tua configurazione',
        pt: 'Veja como enviar sua configuração',
        hi: 'अपनी विन्यास कैसे पुश करें देखें',
        ar: 'شاهد كيفية تحميل التكوين الخاص بك',
        ru: 'Посмотрите, как загрузить вашу конфигурацию',
        tr: 'Yapılandırmanızı nasıl göndereceğinizi görün',
        pl: 'Zobacz, jak przesłać konfigurację',
        id: 'Lihat cara mempush konfigurasi Anda',
        vi: 'Xem cách đẩy cấu hình',
        uk: 'Дізнайтеся, як надіслати конфігурацію',
      }),
      label: t({
        en: 'Click to go to the related documentation',
        'en-GB': 'Click to go to the related documentation',
        fr: 'Cliquez pour accéder à la documentation associée',
        es: 'Haga clic para ir a la documentación relacionada',
        de: 'Klicken Sie hier, um zur zugehörigen Dokumentation zu gelangen',
        ja: '関連ドキュメントに移動するにはクリックしてください',
        ko: '관련 문서로 이동하려면 클릭하세요',
        zh: '点击查看相关文档',
        it: 'Clicca per andare alla documentazione correlata',
        pt: 'Clique para acessar a documentação relacionada',
        hi: 'संबंधित दस्तावेज़ीकरण पर जाने के लिए क्लिक करें',
        ar: 'انقر للانتقال إلى الوثائق ذات الصلة',
        ru: 'Нажмите, чтобы перейти к соответствующей документации',
        tr: 'İlgili belgelere gitmek için tıklayın',
        pl: 'Kliknij, aby przejść do powiązanej dokumentacji',
        id: 'Klik untuk membuka dokumentasi terkait',
        vi: 'Nhấp để đến tài liệu liên quan',
        uk: 'Натисніть, щоб перейти до відповідної документації',
      }),
    },
  },
  title: 'Project configuration details',
  description:
    'Content declaration for the project configuration section in the dashboard. Includes titles and messages related to internationalization settings, editor URLs, and configuration status.',
  tags: ['dashboard', 'project settings', 'configuration'],
} satisfies Dictionary;

export default projectConfigDetailsContent;
