import { type Dictionary, t } from 'intlayer';

const configEditionFormContent = {
  key: 'config-edition-form',
  content: {
    title: t({
      en: 'Edit Configuration',
      'en-GB': 'Edit Configuration',
      fr: 'Modifier la configuration',
      es: 'Editar configuración',
      de: 'Konfiguration bearbeiten',
      ja: '設定を編集',
      ko: '구성 편집',
      zh: '编辑配置',
      it: 'Modifica configurazione',
      pt: 'Editar configuração',
      hi: 'कॉन्फ़िगरेशन संपादित करें',
      ar: 'تعديل التكوين',
      ru: 'Редактировать конфигурацию',
      tr: 'Yapılandırmayı düzenle',
      pl: 'Edytuj konfigurację',
      id: 'Edit Konfigurasi',
      vi: 'Chỉnh sửa cấu hình',
      uk: 'Редагувати конфігурацію',
    }),
    i18nSection: {
      title: t({
        en: 'Internationalization',
        'en-GB': 'Internationalization',
        fr: 'Internationalisation',
        es: 'Internacionalización',
        de: 'Internationalisierung',
        ja: '国際化',
        ko: '국제화',
        zh: '国际化',
        it: 'Internazionalizzazione',
        pt: 'Internacionalização',
        hi: 'अनेक्षांश',
        ar: 'التدويل الدولي',
        ru: 'Интернационализация',
        tr: 'Uluslararasılaştırma',
        pl: 'Internacjonalizacja',
        id: 'Internasionalisasi',
        vi: 'Quốc tế hóa (i18n)',
        uk: 'Інтернаціоналізація',
      }),
      localesInput: {
        label: t({
          en: 'Locales',
          'en-GB': 'Locales',
          fr: 'Locales',
          es: 'Idiomas',
          de: 'Sprachen',
          ja: 'ロケール',
          ko: '로케일',
          zh: '语言环境',
          it: 'Lingue',
          pt: 'Idiomas',
          hi: 'स्थान',
          ar: 'المواقع',
          ru: 'Локали',
          tr: 'Diller',
          pl: 'Lokalizacje',
          id: 'Locale',
          vi: 'Locale',
          uk: 'Локалі',
        }),
        placeholder: t({
          en: 'Select locales...',
          'en-GB': 'Select locales...',
          fr: 'Sélectionner les locales...',
          es: 'Seleccionar idiomas...',
          de: 'Sprachen auswählen...',
          ja: 'ロケールを選択...',
          ko: '로케일 선택...',
          zh: '选择语言环境...',
          it: 'Seleziona le lingue...',
          pt: 'Selecionar idiomas...',
          hi: 'स्थान चुनें...',
          ar: 'اختر المواقع...',
          ru: 'Выберите локали...',
          tr: 'Dilleri seçin...',
          pl: 'Wybierz lokalizacje...',
          id: 'Pilih locale...',
          vi: 'Chọn locale...',
          uk: 'Виберіть локалі...',
        }),
        description: t({
          en: 'Select the locales available for your application',
          'en-GB': 'Select the locales available for your application',
          fr: 'Sélectionnez les locales disponibles pour votre application',
          es: 'Seleccione los idiomas disponibles para su aplicación',
          de: 'Wählen Sie die verfügbaren Sprachen für Ihre Anwendung',
          ja: 'アプリケーションで利用可能なロケールを選択してください',
          ko: '애플리케이션에 사용 가능한 로케일을 선택하세요',
          zh: '选择应用程序可用的语言环境',
          it: "Seleziona le lingue disponibili per l'applicazione",
          pt: 'Selecione os idiomas disponíveis para seu aplicativo',
          hi: 'अपने एप्लिकेशन के लिए उपलब्ध स्थान चुनें',
          ar: 'حدد المواقع المتاحة لتطبيقك',
          ru: 'Выберите локали, доступные для вашего приложения',
          tr: 'Uygulamanız için mevcut dilleri seçin',
          pl: 'Wybierz lokalizacje dostępne dla aplikacji',
          id: 'Pilih locale yang tersedia untuk aplikasi Anda',
          vi: 'Chọn các locale có sẵn cho ứng dụng của bạn',
          uk: 'Виберіть локалі, доступні у вашому застосунку',
        }),
      },
      defaultLocaleInput: {
        label: t({
          en: 'Default Locale',
          'en-GB': 'Default Locale',
          fr: 'Locale par défaut',
          es: 'Idioma predeterminado',
          de: 'Standardsprache',
          ja: 'デフォルトロケール',
          ko: '기본 로케일',
          zh: '默认语言环境',
          it: 'Lingua predefinita',
          pt: 'Idioma padrão',
          hi: 'डिफ़ॉल्ट स्थान',
          ar: 'الموقع الافتراضي',
          ru: 'Локаль по умолчанию',
          tr: 'Varsayılan dil',
          pl: 'Domyślna lokalizacja',
          id: 'Locale Default',
          vi: 'Locale mặc định',
          uk: 'Локаль за замовчуванням',
        }),
        placeholder: t({
          en: 'Select default locale...',
          'en-GB': 'Select default locale...',
          fr: 'Sélectionner la locale par défaut...',
          es: 'Seleccionar idioma predeterminado...',
          de: 'Standardsprache auswählen...',
          ja: 'デフォルトロケールを選択...',
          ko: '기본 로케일 선택...',
          zh: '选择默认语言环境...',
          it: 'Seleziona la lingua predefinita...',
          pt: 'Selecionar idioma padrão...',
          hi: 'डिफ़ॉल्ट स्थान चुनें...',
          ar: 'اختر الموقع الافتراضي...',
          ru: 'Выберите локаль по умолчанию...',
          tr: 'Varsayılan dili seçin...',
          pl: 'Wybierz domyślną lokalizację...',
          id: 'Pilih locale default...',
          vi: 'Chọn locale mặc định...',
          uk: 'Виберіть локаль за замовчуванням...',
        }),
        description: t({
          en: 'The default locale used when no locale is specified',
          'en-GB': 'The default locale used when no locale is specified',
          fr: "La locale par défaut utilisée lorsqu'aucune locale n'est spécifiée",
          es: 'El idioma predeterminado utilizado cuando no se especifica ningún idioma',
          de: 'Die Standardsprache, die verwendet wird, wenn keine Sprache angegeben ist',
          ja: 'ロケールが指定されていない場合に使用されるデフォルトのロケール',
          ko: '로케일이 지정되지 않은 경우 사용되는 기본 로케일',
          zh: '未指定语言环境时使用的默认语言环境',
          it: 'La lingua predefinita utilizzata quando non è specificata alcuna lingua',
          pt: 'O idioma padrão usado quando nenhum idioma é especificado',
          hi: 'जब कोई स्थान निर्दिष्ट नहीं है तो उपयोग किया जाने वाला डिफ़ॉल्ट स्थान',
          ar: 'الموقع الافتراضي المستخدم عندما لا يتم تحديد موقع',
          ru: 'Локаль по умолчанию, используемая когда локаль не указана',
          tr: 'Dil belirtilmediğinde kullanılan varsayılan dil',
          pl: 'Domyślna lokalizacja używana gdy nie określono lokalizacji',
          id: 'Locale default yang digunakan saat tidak ada locale yang ditentukan',
          vi: 'Locale mặc định được sử dụng khi không có locale nào được chỉ định',
          uk: 'Локаль, яка використовується за замовчуванням, якщо не вказано іншу',
        }),
      },
    },
    editorSection: {
      title: t({
        en: 'Editor',
        'en-GB': 'Editor',
        fr: 'Éditeur',
        es: 'Editor',
        de: 'Editor',
        ja: 'エディタ',
        ko: '편집기',
        zh: '编辑器',
        it: 'Editor',
        pt: 'Editor',
        hi: 'संपादक',
        ar: 'المحرر',
        ru: 'Редактор',
        tr: 'Editör',
        pl: 'Edytor',
        id: 'Editor',
        vi: 'Editor',
        uk: 'Редактор',
      }),
      applicationURLInput: {
        label: t({
          en: 'Application URL',
          'en-GB': 'Application URL',
          fr: "URL de l'application",
          es: 'URL de la aplicación',
          de: 'Anwendungs-URL',
          ja: 'アプリケーション URL',
          ko: '애플리케이션 URL',
          zh: '应用程序 URL',
          it: "URL dell'applicazione",
          pt: 'URL do aplicativo',
          hi: 'एप्लीकेशन URL',
          ar: 'عنوان URL التطبيق',
          ru: 'URL-адрес приложения',
          tr: "Uygulama URL'si",
          pl: 'URL aplikacji',
          id: 'URL Aplikasi',
          vi: 'URL ứng dụng',
          uk: 'URL додатку',
        }),
        placeholder: t({
          en: 'https://your-app.com',
          'en-GB': 'https://your-app.com',
          fr: 'https://votre-app.com',
          es: 'https://tu-app.com',
          de: 'https://ihre-app.com',
          ja: 'https://your-app.com',
          ko: 'https://your-app.com',
          zh: 'https://your-app.com',
          it: 'https://tua-app.com',
          pt: 'https://seu-app.com',
          hi: 'https://your-app.com',
          ar: 'https://your-app.com',
          ru: 'https://your-app.com',
          tr: 'https://uygulamaniz.com',
          pl: 'https://twoja-aplikacja.com',
          id: 'https://aplikasi-anda.com',
          vi: 'https://ung-dung-cua-ban.com',
          uk: 'https://your-app.com',
        }),
        description: t({
          en: 'The URL where your application is hosted',
          'en-GB': 'The URL where your application is hosted',
          fr: 'URL où votre application est hébergée',
          es: 'La URL donde está alojada su aplicación',
          de: 'Die URL, unter der Ihre Anwendung gehostet wird',
          ja: 'アプリケーションがホストされている URL',
          ko: '애플리케이션이 호스팅되는 URL',
          zh: '应用程序托管的 URL',
          it: "L'URL in cui è ospitata la tua applicazione",
          pt: 'A URL onde seu aplicativo está hospedado',
          hi: 'जहां आपका एप्लिकेशन होस्ट किया गया है वह URL',
          ar: 'عنوان URL حيث يتم استضافة تطبيقك',
          ru: 'URL-адрес, где размещено ваше приложение',
          tr: 'Uygulamanızın barındırıldığı URL',
          pl: 'Adres URL, pod którym hostowana jest aplikacja',
          id: 'URL tempat aplikasi Anda dihosting',
          vi: 'URL nơi ứng dụng của bạn được lưu trữ',
          uk: 'URL, за яким розміщено ваш додаток',
        }),
      },
      cmsURLInput: {
        label: t({
          en: 'CMS URL',
          'en-GB': 'CMS URL',
          fr: 'URL du CMS',
          es: 'URL del CMS',
          de: 'CMS-URL',
          ja: 'CMS URL',
          ko: 'CMS URL',
          zh: 'CMS URL',
          it: 'URL del CMS',
          pt: 'URL do CMS',
          hi: 'CMS URL',
          ar: 'عنوان URL للمحرك المرئي',
          ru: 'URL-адрес CMS',
          tr: 'CMS URL',
          pl: 'URL CMS',
          id: 'URL CMS',
          vi: 'URL CMS',
          uk: 'URL CMS',
        }),
        placeholder: t({
          en: 'https://intlayer.org',
          'en-GB': 'https://intlayer.org',
          fr: 'https://intlayer.org',
          es: 'https://intlayer.org',
          de: 'https://intlayer.org',
          ja: 'https://intlayer.org',
          ko: 'https://intlayer.org',
          zh: 'https://intlayer.org',
          it: 'https://intlayer.org',
          pt: 'https://intlayer.org',
          hi: 'https://intlayer.org',
          ar: 'https://intlayer.org',
          ru: 'https://intlayer.org',
          tr: 'https://intlayer.org',
          pl: 'https://intlayer.org',
          id: 'https://intlayer.org',
          vi: 'https://intlayer.org',
          uk: 'https://intlayer.org',
        }),
        description: t({
          en: 'The URL of the Intlayer CMS',
          'en-GB': 'The URL of the Intlayer CMS',
          fr: "L'URL du CMS Intlayer",
          es: 'La URL del CMS de Intlayer',
          de: 'Die URL des Intlayer CMS',
          ja: 'Intlayer CMS の URL',
          ko: 'Intlayer CMS의 URL',
          zh: 'Intlayer CMS 的 URL',
          it: "L'URL del CMS Intlayer",
          pt: 'A URL do CMS Intlayer',
          hi: 'Intlayer CMS का URL',
          ar: 'عنوان URL لـ Intlayer CMS',
          ru: 'URL-адрес Intlayer CMS',
          tr: 'Intlayer CMS URL adresi',
          pl: 'Adres URL Intlayer CMS',
          id: 'URL Intlayer CMS',
          vi: 'URL của Intlayer CMS',
          uk: 'URL CMS Intlayer',
        }),
      },
    },
    aiSection: {
      title: t({
        en: 'AI Configuration',
        'en-GB': 'AI Configuration',
        fr: "Configuration de l'IA",
        es: 'Configuración de IA',
        de: 'KI-Konfiguration',
        ja: 'AI設定',
        ko: 'AI 구성',
        zh: 'AI 配置',
        it: 'Configurazione IA',
        pt: 'Configuração de IA',
        hi: 'AI कॉन्फ़िगरेशन',
        ar: 'تكوين الذكاء الاصطناعي',
        ru: 'Настройка ИИ',
        tr: 'AI Yapılandırması',
        pl: 'Konfiguracja AI',
        id: 'Konfigurasi AI',
        vi: 'Cấu hình AI',
        uk: 'Налаштування ШІ',
      }),
      providerInput: {
        label: t({
          en: 'AI Provider',
          'en-GB': 'AI Provider',
          fr: "Fournisseur d'IA",
          es: 'Proveedor de IA',
          de: 'KI-Anbieter',
          ja: 'AIプロバイダー',
          ko: 'AI 제공자',
          zh: 'AI 提供商',
          it: 'Provider IA',
          pt: 'Provedor de IA',
          hi: 'AI प्रदाता',
          ar: 'مزود الذكاء الاصطناعي',
          ru: 'Поставщик ИИ',
          tr: 'AI Sağlayıcı',
          pl: 'Dostawca AI',
          id: 'Penyedia AI',
          vi: 'Nhà cung cấp AI',
          uk: 'Провайдер ШІ',
        }),
        placeholder: t({
          en: 'Select AI provider...',
          'en-GB': 'Select AI provider...',
          fr: "Sélectionner le fournisseur d'IA...",
          es: 'Seleccionar proveedor de IA...',
          de: 'KI-Anbieter auswählen...',
          ja: 'AIプロバイダーを選択...',
          ko: 'AI 제공자 선택...',
          zh: '选择AI提供商...',
          it: 'Seleziona provider IA...',
          pt: 'Selecionar provedor de IA...',
          hi: 'AI प्रदाता चुनें...',
          ar: 'اختر مزود الذكاء الاصطناعي...',
          ru: 'Выберите поставщика ИИ...',
          tr: 'AI sağlayıcı seçin...',
          pl: 'Wybierz dostawcę AI...',
          id: 'Pilih penyedia AI...',
          vi: 'Chọn nhà cung cấp AI...',
          uk: 'Виберіть провайдера ШІ...',
        }),
        description: t({
          en: 'The AI provider to use for translations and content generation',
          'en-GB':
            'The AI provider to use for translations and content generation',
          fr: "Le fournisseur d'IA à utiliser pour les traductions et la génération de contenu",
          es: 'El proveedor de IA a usar para traducciones y generación de contenido',
          de: 'Der KI-Anbieter für Übersetzungen und Inhaltsgenerierung',
          ja: '翻訳とコンテンツ生成に使用するAIプロバイダー',
          ko: '번역 및 콘텐츠 생성에 사용할 AI 제공자',
          zh: '用于翻译和内容生成的AI提供商',
          it: 'Il provider IA da utilizzare per traduzioni e generazione di contenuti',
          pt: 'O provedor de IA para traduções e geração de conteúdo',
          hi: 'अनुवाद और सामग्री उत्पादन के लिए AI प्रदाता',
          ar: 'مزود الذكاء الاصطناعي للترجمات وتوليد المحتوى',
          ru: 'Поставщик ИИ для переводов и генерации контента',
          tr: 'Çeviriler ve içerik üretimi için AI sağlayıcı',
          pl: 'Dostawca AI do tłumaczeń i generowania treści',
          id: 'Penyedia AI untuk terjemahan dan pembuatan konten',
          vi: 'Nhà cung cấp AI cho dịch thuật và tạo nội dung',
          uk: 'Провайдер ШІ для перекладів та генерації контенту',
        }),
      },
      modelInput: {
        label: t({
          en: 'AI Model',
          'en-GB': 'AI Model',
          fr: "Modèle d'IA",
          es: 'Modelo de IA',
          de: 'KI-Modell',
          ja: 'AIモデル',
          ko: 'AI 모델',
          zh: 'AI 模型',
          it: 'Modello IA',
          pt: 'Modelo de IA',
          hi: 'AI मॉडल',
          ar: 'نموذج الذكاء الاصطناعي',
          ru: 'Модель ИИ',
          tr: 'AI Modeli',
          pl: 'Model AI',
          id: 'Model AI',
          vi: 'Mô hình AI',
          uk: 'Модель ШІ',
        }),
        placeholder: t({
          en: 'gpt-4o-2024-11-20',
          'en-GB': 'gpt-4o-2024-11-20',
          fr: 'gpt-4o-2024-11-20',
          es: 'gpt-4o-2024-11-20',
          de: 'gpt-4o-2024-11-20',
          ja: 'gpt-4o-2024-11-20',
          ko: 'gpt-4o-2024-11-20',
          zh: 'gpt-4o-2024-11-20',
          it: 'gpt-4o-2024-11-20',
          pt: 'gpt-4o-2024-11-20',
          hi: 'gpt-4o-2024-11-20',
          ar: 'gpt-4o-2024-11-20',
          ru: 'gpt-4o-2024-11-20',
          tr: 'gpt-4o-2024-11-20',
          pl: 'gpt-4o-2024-11-20',
          id: 'gpt-4o-2024-11-20',
          vi: 'gpt-4o-2024-11-20',
          uk: 'gpt-4o-2024-11-20',
        }),
        description: t({
          en: 'The specific AI model to use',
          'en-GB': 'The specific AI model to use',
          fr: "Le modèle d'IA spécifique à utiliser",
          es: 'El modelo de IA específico a usar',
          de: 'Das spezifische KI-Modell',
          ja: '使用する特定のAIモデル',
          ko: '사용할 특정 AI 모델',
          zh: '要使用的特定AI模型',
          it: 'Il modello IA specifico da utilizzare',
          pt: 'O modelo de IA específico a usar',
          hi: 'उपयोग करने के लिए विशिष्ट AI मॉडल',
          ar: 'نموذج الذكاء الاصطناعي المحدد',
          ru: 'Конкретная модель ИИ',
          tr: 'Kullanılacak belirli AI modeli',
          pl: 'Konkretny model AI do użycia',
          id: 'Model AI spesifik yang akan digunakan',
          vi: 'Mô hình AI cụ thể để sử dụng',
          uk: 'Конкретна модель ШІ для використання',
        }),
      },
      temperatureInput: {
        label: t({
          en: 'Temperature',
          'en-GB': 'Temperature',
          fr: 'Température',
          es: 'Temperatura',
          de: 'Temperatur',
          ja: '温度',
          ko: '온도',
          zh: '温度',
          it: 'Temperatura',
          pt: 'Temperatura',
          hi: 'तापमान',
          ar: 'درجة الحرارة',
          ru: 'Температура',
          tr: 'Sıcaklık',
          pl: 'Temperatura',
          id: 'Temperatur',
          vi: 'Nhiệt độ',
          uk: 'Температура',
        }),
        placeholder: t({
          en: '0.1',
          'en-GB': '0.1',
          fr: '0.1',
          es: '0.1',
          de: '0.1',
          ja: '0.1',
          ko: '0.1',
          zh: '0.1',
          it: '0.1',
          pt: '0.1',
          hi: '0.1',
          ar: '0.1',
          ru: '0.1',
          tr: '0.1',
          pl: '0.1',
          id: '0.1',
          vi: '0.1',
          uk: '0.1',
        }),
        description: t({
          en: 'Controls randomness (0-2). Lower = more focused, higher = more creative',
          'en-GB':
            'Controls randomness (0-2). Lower = more focused, higher = more creative',
          fr: "Contrôle l'aléatoire (0-2). Plus bas = plus focalisé, plus haut = plus créatif",
          es: 'Controla la aleatoriedad (0-2). Menor = más enfocado, mayor = más creativo',
          de: 'Steuert Zufälligkeit (0-2). Niedriger = fokussierter, höher = kreativer',
          ja: 'ランダム性を制御 (0-2)。低い = より集中、高い = より創造的',
          ko: '무작위성 제어 (0-2). 낮음 = 더 집중, 높음 = 더 창의적',
          zh: '控制随机性 (0-2)。较低 = 更专注，较高 = 更有创意',
          it: 'Controlla la casualità (0-2). Più basso = più focalizzato, più alto = più creativo',
          pt: 'Controla aleatoriedade (0-2). Menor = mais focado, maior = mais criativo',
          hi: 'यादृच्छिकता को नियंत्रित करता है (0-2)। कम = अधिक केंद्रित, अधिक = अधिक रचनात्मक',
          ar: 'يتحكم في العشوائية (0-2). أقل = أكثر تركيزًا، أعلى = أكثر إبداعًا',
          ru: 'Контролирует случайность (0-2). Ниже = более сфокусировано, выше = более креативно',
          tr: 'Rastgeleliği kontrol eder (0-2). Düşük = daha odaklı, yüksek = daha yaratıcı',
          pl: 'Kontroluje losowość (0-2). Niższy = bardziej skupiony, wyższy = bardziej kreatywny',
          id: 'Mengontrol keacakan (0-2). Lebih rendah = lebih fokus, lebih tinggi = lebih kreatif',
          vi: 'Kiểm soát độ ngẫu nhiên (0-2). Thấp hơn = tập trung hơn, cao hơn = sáng tạo hơn',
          uk: 'Керує випадковістю (0–2). Нижчі значення = більш сфокусовано, вищі = більш креативно',
        }),
      },
      apiKeyInput: {
        label: t({
          en: 'API Key',
          'en-GB': 'API Key',
          fr: "Clé d'API",
          es: 'Clave de API',
          de: 'API-Schlüssel',
          ja: 'APIキー',
          ko: 'API 키',
          zh: 'API 密钥',
          it: 'Chiave API',
          pt: 'Chave de API',
          hi: 'API कुंजी',
          ar: 'مفتاح API',
          ru: 'API ключ',
          tr: 'API Anahtarı',
          pl: 'Klucz API',
          id: 'Kunci API',
          vi: 'Khóa API',
          uk: 'API ключ',
        }),
        placeholder: t({
          en: 'sk-...',
          'en-GB': 'sk-...',
          fr: 'sk-...',
          es: 'sk-...',
          de: 'sk-...',
          ja: 'sk-...',
          ko: 'sk-...',
          zh: 'sk-...',
          it: 'sk-...',
          pt: 'sk-...',
          hi: 'sk-...',
          ar: 'sk-...',
          ru: 'sk-...',
          tr: 'sk-...',
          pl: 'sk-...',
          id: 'sk-...',
          vi: 'sk-...',
          uk: 'sk-...',
        }),
        description: t({
          en: 'Your AI provider API key for authentication',
          'en-GB': 'Your AI provider API key for authentication',
          fr: "Votre clé API du fournisseur d'IA pour l'authentification",
          es: 'Su clave de API del proveedor de IA para autenticación',
          de: 'Ihr KI-Anbieter API-Schlüssel zur Authentifizierung',
          ja: '認証用のAIプロバイダーAPIキー',
          ko: '인증을 위한 AI 제공자 API 키',
          zh: '用于身份验证的AI提供商API密钥',
          it: "La tua chiave API del provider IA per l'autenticazione",
          pt: 'Sua chave de API do provedor de IA para autenticação',
          hi: 'प्रमाणीकरण के लिए आपकी AI प्रदाता API कुंजी',
          ar: 'مفتاح API الخاص بمزود الذكاء الاصطناعي للمصادقة',
          ru: 'Ваш API ключ провайдера ИИ для аутентификации',
          tr: 'Kimlik doğrulama için AI sağlayıcı API anahtarınız',
          pl: 'Twój klucz API dostawcy AI do uwierzytelniania',
          id: 'Kunci API penyedia AI Anda untuk autentikasi',
          vi: 'Khóa API nhà cung cấp AI của bạn để xác thực',
          uk: 'API-ключ вашого провайдера ШІ для автентифікації',
        }),
      },
      applicationContextInput: {
        label: t({
          en: 'Application Context',
          'en-GB': 'Application Context',
          fr: "Contexte de l'application",
          es: 'Contexto de la aplicación',
          de: 'Anwendungskontext',
          ja: 'アプリケーションコンテキスト',
          ko: '애플리케이션 컨텍스트',
          zh: '应用程序上下文',
          it: "Contesto dell'applicazione",
          pt: 'Contexto da aplicação',
          hi: 'एप्लिकेशन संदर्भ',
          ar: 'سياق التطبيق',
          ru: 'Контекст приложения',
          tr: 'Uygulama Bağlamı',
          pl: 'Kontekst aplikacji',
          id: 'Konteks Aplikasi',
          vi: 'Ngữ cảnh ứng dụng',
          uk: 'Контекст застосунку',
        }),
        placeholder: t({
          en: 'This is a website for a company that sells products online.',
          'en-GB':
            'This is a website for a company that sells products online.',
          fr: 'Ceci est un site web pour une entreprise qui vend des produits en ligne.',
          es: 'Este es un sitio web para una empresa que vende productos en línea.',
          de: 'Dies ist eine Website für ein Unternehmen, das Produkte online verkauft.',
          ja: 'これはオンラインで製品を販売する会社のウェブサイトです。',
          ko: '이것은 온라인으로 제품을 판매하는 회사의 웹사이트입니다.',
          zh: '这是一个在线销售产品的公司网站。',
          it: "Questo è un sito web per un'azienda che vende prodotti online.",
          pt: 'Este é um site para uma empresa que vende produtos online.',
          hi: 'यह एक वेबसाइट है जो ऑनलाइन उत्पाद बेचती है।',
          ar: 'هذا موقع ويب لشركة تبيع منتجات عبر الإنترنت.',
          ru: 'Это веб-сайт для компании, которая продает товары онлайн.',
          tr: 'Bu, çevrimiçi ürün satan bir şirket için bir web sitesidir.',
          pl: 'To jest strona internetowa dla firmy sprzedającej produkty online.',
          id: 'Ini adalah situs web untuk perusahaan yang menjual produk secara online.',
          vi: 'Đây là trang web cho một công ty bán sản phẩm trực tuyến.',
          uk: 'Це вебсайт компанії, яка продає товари онлайн.',
        }),
        description: t({
          en: 'Describe your application to help AI generate better translations',
          'en-GB':
            'Describe your application to help AI generate better translations',
          fr: "Décrivez votre application pour aider l'IA à générer de meilleures traductions",
          es: 'Describe tu aplicación para ayudar a la IA a generar mejores traducciones',
          de: 'Beschreiben Sie Ihre Anwendung, um der KI zu helfen, bessere Übersetzungen zu generieren',
          ja: 'AIがより良い翻訳を生成できるようにアプリケーションを説明してください',
          ko: 'AI가 더 나은 번역을 생성하도록 애플리케이션을 설명하세요',
          zh: '描述您的应用程序以帮助AI生成更好的翻译',
          it: "Descrivi la tua applicazione per aiutare l'IA a generare traduzioni migliori",
          pt: 'Descreva sua aplicação para ajudar a IA a gerar melhores traduções',
          hi: 'बेहतर अनुवाद उत्पन्न करने में AI की मदद के लिए अपने एप्लिकेशन का वर्णन करें',
          ar: 'صف تطبيقك لمساعدة الذكاء الاصطناعي على إنشاء ترجمات أفضل',
          ru: 'Опишите ваше приложение, чтобы помочь ИИ генерировать лучшие переводы',
          tr: "AI'ın daha iyi çeviriler üretmesine yardımcı olmak için uygulamanızı açıklayın",
          pl: 'Opisz swoją aplikację, aby pomóc AI generować lepsze tłumaczenia',
          id: 'Jelaskan aplikasi Anda untuk membantu AI menghasilkan terjemahan yang lebih baik',
          vi: 'Mô tả ứng dụng của bạn để giúp AI tạo bản dịch tốt hơn',
          uk: 'Опишіть ваш застосунок, щоб ШІ міг генерувати точніші переклади',
        }),
      },
    },
    saveButton: {
      text: t({
        en: 'Save Configuration',
        'en-GB': 'Save Configuration',
        fr: 'Enregistrer la configuration',
        es: 'Guardar configuración',
        de: 'Konfiguration speichern',
        ja: '設定を保存',
        ko: '구성 저장',
        zh: '保存配置',
        it: 'Salva configurazione',
        pt: 'Salvar configuração',
        hi: 'कॉन्फ़िगरेशन सहेजें',
        ar: 'حفظ التكوين',
        ru: 'Сохранить конфигурацию',
        tr: 'Yapılandırmayı kaydet',
        pl: 'Zapisz konfigurację',
        id: 'Simpan Konfigurasi',
        vi: 'Lưu cấu hình',
        uk: 'Зберегти конфігурацію',
      }),
      ariaLabel: t({
        en: 'Click to save the configuration',
        'en-GB': 'Click to save the configuration',
        fr: 'Cliquez pour enregistrer la configuration',
        es: 'Haga clic para guardar la configuración',
        de: 'Klicken Sie hier, um die Konfiguration zu speichern',
        ja: '設定を保存するにはクリックしてください',
        ko: '구성을 저장하려면 클릭하세요',
        zh: '点击保存配置',
        it: 'Clicca per salvare la configurazione',
        pt: 'Clique para salvar a configuração',
        hi: 'कॉन्फ़िगरेशन सहेजने के लिए क्लिक करें',
        ar: 'انقر لحفظ التكوين',
        ru: 'Нажмите, чтобы сохранить конфигурацию',
        tr: 'Yapılandırmayı kaydetmek için tıklayın',
        pl: 'Kliknij, aby zapisać konfigurację',
        id: 'Klik untuk menyimpan konfigurasi',
        vi: 'Nhấp để lưu cấu hình',
        uk: 'Натисніть, щоб зберегти конфігурацію',
      }),
    },
    cancelButton: {
      text: t({
        en: 'Cancel',
        'en-GB': 'Cancel',
        fr: 'Annuler',
        es: 'Cancelar',
        de: 'Abbrechen',
        ja: 'キャンセル',
        ko: '취소',
        zh: '取消',
        it: 'Annulla',
        pt: 'Cancelar',
        hi: 'रद्द करें',
        ar: 'إلغاء',
        ru: 'Отмена',
        tr: 'İptal',
        pl: 'Anuluj',
        id: 'Batal',
        vi: 'Hủy',
        uk: 'Скасувати',
      }),
      ariaLabel: t({
        en: 'Click to cancel and close the modal',
        'en-GB': 'Click to cancel and close the modal',
        fr: 'Cliquez pour annuler et fermer la fenêtre',
        es: 'Haga clic para cancelar y cerrar el modal',
        de: 'Klicken Sie hier, um abzubrechen und das Modal zu schließen',
        ja: 'キャンセルしてモーダルを閉じるにはクリックしてください',
        ko: '취소하고 모달을 닫으려면 클릭하세요',
        zh: '点击取消并关闭模态框',
        it: 'Clicca per annullare e chiudere la finestra',
        pt: 'Clique para cancelar e fechar o modal',
        hi: 'रद्द करने और मॉडल बंद करने के लिए क्लिक करें',
        ar: 'انقر للإلغاء وإغلاق النافذة',
        ru: 'Нажмите, чтобы отменить и закрыть модальное окно',
        tr: "İptal etmek ve modal'ı kapatmak için tıklayın",
        pl: 'Kliknij, aby anulować i zamknąć okno modalne',
        id: 'Klik untuk membatalkan dan menutup modal',
        vi: 'Nhấp để hủy và đóng modal',
        uk: 'Натисніть, щоб скасувати та закрити модальне вікно',
      }),
    },
    editButton: {
      ariaLabel: t({
        en: 'Click to edit the configuration',
        'en-GB': 'Click to edit the configuration',
        fr: 'Cliquez pour modifier la configuration',
        es: 'Haga clic para editar la configuración',
        de: 'Klicken Sie hier, um die Konfiguration zu bearbeiten',
        ja: '設定を編集するにはクリックしてください',
        ko: '구성을 편집하려면 클릭하세요',
        zh: '点击编辑配置',
        it: 'Clicca per modificare la configurazione',
        pt: 'Clique para editar a configuração',
        hi: 'कॉन्फ़िगरेशन संपादित करने के लिए क्लिक करें',
        ar: 'انقر لتعديل التكوين',
        ru: 'Нажмите, чтобы редактировать конфигурацию',
        tr: 'Yapılandırmayı düzenlemek için tıklayın',
        pl: 'Kliknij, aby edytować konfigurację',
        id: 'Klik untuk mengedit konfigurasi',
        vi: 'Nhấp để chỉnh sửa cấu hình',
        uk: 'Натисніть, щоб редагувати конфігурацію',
      }),
    },
  },
  title: 'Config edition form content',
  description:
    'Content declaration for the project configuration edition form.',
  tags: ['dashboard', 'form', 'config', 'edit'],
} satisfies Dictionary;

export default configEditionFormContent;
