import { t, type Dictionary } from 'intlayer';

const availableTechnoContent = {
  key: 'available-techno-section',
  content: {
    availableOn: t({
      en: 'Available on',
      'en-GB': 'Available on',
      fr: 'Disponible sur',
      es: 'Disponible en',
      de: 'Verfügbar auf',
      ja: '利用可能',
      ko: '사용 가능',
      zh: '可用',
      it: 'Disponibile su',
      pt: 'Disponível em',
      hi: 'उपलब्ध है',
      ar: 'متاح على',
      ru: 'Доступно на',
      tr: 'Mevcut',
    }),
    commingSoon: t({
      en: 'Comming soon',
      'en-GB': 'Comming soon',
      fr: 'Bientôt disponible',
      es: 'Próximamente disponible',
      de: 'Demnächst verfügbar',
      ja: 'まもなく利用可能',
      ko: '곧 사용 가능',
      zh: '即将可用',
      it: 'Disponibile presto',
      pt: 'Disponível em breve',
      hi: 'जल्द उपलब्ध है',
      ar: 'قريبا متاح على',
      ru: 'Скоро доступно',
      tr: 'Çok yakında',
    }),
    icons: {
      react: {
        label: t({
          en: 'Go to ReactJS official website',
          'en-GB': 'Go to ReactJS official website',
          fr: 'Aller sur le site officiel de ReactJS',
          es: 'Ir al sitio web oficial de ReactJS',
          de: 'Zur offiziellen ReactJS-Website gehen',
          ja: 'ReactJS公式ウェブサイトに行く',
          ko: 'ReactJS 공식 웹사이트로 이동',
          zh: '前往 ReactJS 官方网站',
          it: 'Vai al sito ufficiale di ReactJS',
          pt: 'Ir para o site oficial do ReactJS',
          hi: 'ReactJS की आधिकारिक वेबसाइट पर जाएं',
          ar: 'اذهب إلى الموقع الرسمي لـ ReactJS',
          ru: 'Перейти на официальный сайт ReactJS',
          tr: 'ReactJS resmi web sitesine git',
        }),
      },
      nextjs: {
        label: t({
          en: 'Go to NextJS official website',
          'en-GB': 'Go to NextJS official website',
          fr: 'Aller sur le site officiel de NextJS',
          es: 'Ir al sitio web oficial de NextJS',
          de: 'Zur offiziellen NextJS-Website gehen',
          ja: 'NextJS公式ウェブサイトに行く',
          ko: 'NextJS 공식 웹사이트로 이동',
          zh: '前往 NextJS 官方网站',
          it: 'Vai al sito ufficiale di NextJS',
          pt: 'Ir para o site oficial do NextJS',
          hi: 'NextJS की आधिकारिक वेबसाइट पर जाएं',
          ar: 'اذهب إلى الموقع الرسمي لـ NextJS',
          ru: 'Перейти на официальный сайт NextJS',
          tr: 'NextJS resmi web sitesine git',
        }),
      },
      vite: {
        label: t({
          en: 'Go to ViteJS official website',
          'en-GB': 'Go to ViteJS official website',
          fr: 'Aller sur le site officiel de ViteJS',
          es: 'Ir al sitio web oficial de ViteJS',
          de: 'Zur offiziellen ViteJS-Website gehen',
          ja: 'ViteJS公式ウェブサイトに行く',
          ko: 'ViteJS 공식 웹사이트로 이동',
          zh: '前往 ViteJS 官方网站',
          it: 'Vai al sito ufficiale di ViteJS',
          pt: 'Ir para o site oficial do ViteJS',
          hi: 'ViteJS की आधिकारिक वेबसाइट पर जाएं',
          ar: 'اذهب إلى الموقع الرسمي لـ ViteJS',
          ru: 'Перейти на официальный сайт ViteJS',
          tr: 'ViteJS resmi web sitesine git',
        }),
      },
      vue: {
        label: t({
          en: 'Go to VueJS official website',
          'en-GB': 'Go to VueJS official website',
          fr: 'Aller sur le site officiel de VueJS',
          es: 'Ir al sitio web oficial de VueJS',
          de: 'Zur offiziellen VueJS-Website gehen',
          ja: 'VueJS公式ウェブサイトに行く',
          ko: 'VueJS 공식 웹사이트로 이동',
          zh: '前往 VueJS 官方网站',
          it: 'Vai al sito ufficiale di VueJS',
          pt: 'Ir para o site oficial do VueJS',
          hi: 'VueJS की आधिकारिक वेबसाइट पर जाएं',
          ar: 'اذهب إلى الموقع الرسمي لـ VueJS',
          ru: 'Перейти на официальный сайт VueJS',
          tr: 'VueJS resmi web sitesine git',
        }),
      },
      nuxt: {
        label: t({
          en: 'Go to NuxtJS official website',
          'en-GB': 'Go to NuxtJS official website',
          fr: 'Aller sur le site officiel de NuxtJS',
          es: 'Ir al sitio web oficial de NuxtJS',
          de: 'Zur offiziellen NuxtJS-Website gehen',
          ja: 'NuxtJS公式ウェブサイトに行く',
          ko: 'NuxtJS 공식 웹사이트로 이동',
          zh: '前往 NuxtJS 官方网站',
          it: 'Vai al sito ufficiale di NuxtJS',
          pt: 'Ir para o site oficial do NuxtJS',
          hi: 'NuxtJS की आधिकारिक वेबसाइट पर जाएं',
          ar: 'اذهب إلى الموقع الرسمي لـ NuxtJS',
          ru: 'Перейти на официальный сайт NuxtJS',
          tr: 'NuxtJS resmi web sitesine git',
        }),
      },
      angular: {
        label: t({
          en: 'Go to AngularJS official website',
          'en-GB': 'Go to AngularJS official website',
          fr: 'Aller sur le site officiel d’AngularJS',
          es: 'Ir al sitio web oficial de AngularJS',
          de: 'Zur offiziellen AngularJS-Website gehen',
          ja: 'AngularJS公式ウェブサイトに行く',
          ko: 'AngularJS 공식 웹사이트로 이동',
          zh: '前往 AngularJS 官方网站',
          it: 'Vai al sito ufficiale di AngularJS',
          pt: 'Ir para o site oficial do AngularJS',
          hi: 'AngularJS की आधिकारिक वेबसाइट पर जाएं',
          ar: 'اذهب إلى الموقع الرسمي لـ AngularJS',
          ru: 'Перейти на официальный сайт AngularJS',
          tr: 'AngularJS resmi web sitesine git',
        }),
      },
      preact: {
        label: t({
          en: 'Go to Preact official website',
          'en-GB': 'Go to Preact official website',
          fr: 'Aller sur le site officiel de Preact',
          es: 'Ir al sitio web oficial de Preact',
          de: 'Zur offiziellen Preact-Website gehen',
          ja: 'Preact公式ウェブサイトに行く',
          ko: 'Preact 공식 웹사이트로 이동',
          zh: '前往 Preact 官方网站',
          it: 'Vai al sito ufficiale di Preact',
          pt: 'Ir para o site oficial do Preact',
          hi: 'Preact की आधिकारिक वेबसाइट पर जाएं',
          ar: 'اذهب إلى الموقع الرسمي لـ Preact',
          ru: 'Перейти на официальный сайт Preact',
          tr: 'Preact resmi web sitesine git',
        }),
      },
      solid: {
        label: t({
          en: 'Go to SolidJS official website',
          'en-GB': 'Go to SolidJS official website',
          fr: 'Aller sur le site officiel de SolidJS',
          es: 'Ir al sitio web oficial de SolidJS',
          de: 'Zur offiziellen SolidJS-Website gehen',
          ja: 'SolidJS公式ウェブサイトに行く',
          ko: 'SolidJS 공식 웹사이트로 이동',
          zh: '前往 SolidJS 官方网站',
          it: 'Vai al sito ufficiale di SolidJS',
          pt: 'Ir para o site oficial do SolidJS',
          hi: 'SolidJS की आधिकारिक वेबसाइट पर जाएं',
          ar: 'اذهب إلى الموقع الرسمي لـ SolidJS',
          ru: 'Перейти на официальный сайт SolidJS',
          tr: 'SolidJS resmi web sitesine git',
        }),
      },
      svelte: {
        label: t({
          en: 'Go to Svelte official website',
          'en-GB': 'Go to Svelte official website',
          fr: 'Aller sur le site officiel de Svelte',
          es: 'Ir al sitio web oficial de Svelte',
          de: 'Zur offiziellen Svelte-Website gehen',
          ja: 'Svelte公式ウェブサイトに行く',
          ko: 'Svelte 공식 웹사이트로 이동',
          zh: '前往 Svelte 官方网站',
          it: 'Vai al sito ufficiale di Svelte',
          pt: 'Ir para o site oficial do Svelte',
          hi: 'Svelte की आधिकारिक वेबसाइट पर जाएं',
          ar: 'اذهب إلى الموقع الرسمي لـ Svelte',
          ru: 'Перейти на официальный сайт Svelte',
          tr: 'Svelte resmi web sitesine git',
        }),
      },
    },
  },
} satisfies Dictionary;

export default availableTechnoContent;
