import { type Dictionary, t } from 'intlayer';

const configEditionFormContent = {
  key: 'config-edition-form',
  content: {
    title: t({
      en: 'Edit Configuration',
      'en-GB': 'Edit Configuration',
      fr: 'Modifier la configuration',
      es: 'Editar configuración',
      de: 'Konfiguration bearbeiten',
      ja: '設定を編集',
      ko: '구성 편집',
      zh: '编辑配置',
      it: 'Modifica configurazione',
      pt: 'Editar configuração',
      hi: 'कॉन्फ़िगरेशन संपादित करें',
      ar: 'تعديل التكوين',
      ru: 'Редактировать конфигурацию',
      tr: 'Yapılandırmayı düzenle',
      pl: 'Edytuj konfigurację',
      id: 'Edit Konfigurasi',
      vi: 'Chỉnh sửa cấu hình',
    }),
    i18nSection: {
      title: t({
        en: 'Internationalization',
        'en-GB': 'Internationalization',
        fr: 'Internationalisation',
        es: 'Internacionalización',
        de: 'Internationalisierung',
        ja: '国際化',
        ko: '국제화',
        zh: '国际化',
        it: 'Internazionalizzazione',
        pt: 'Internacionalização',
        hi: 'अनेक्षांश',
        ar: 'التدويل الدولي',
        ru: 'Интернационализация',
        tr: 'Uluslararasılaştırma',
        pl: 'Internacjonalizacja',
        id: 'Internasionalisasi',
        vi: 'Quốc tế hóa (i18n)',
      }),
      localesInput: {
        label: t({
          en: 'Locales',
          'en-GB': 'Locales',
          fr: 'Locales',
          es: 'Idiomas',
          de: 'Sprachen',
          ja: 'ロケール',
          ko: '로케일',
          zh: '语言环境',
          it: 'Lingue',
          pt: 'Idiomas',
          hi: 'स्थान',
          ar: 'المواقع',
          ru: 'Локали',
          tr: 'Diller',
          pl: 'Lokalizacje',
          id: 'Locale',
          vi: 'Locale',
        }),
        placeholder: t({
          en: 'Select locales...',
          'en-GB': 'Select locales...',
          fr: 'Sélectionner les locales...',
          es: 'Seleccionar idiomas...',
          de: 'Sprachen auswählen...',
          ja: 'ロケールを選択...',
          ko: '로케일 선택...',
          zh: '选择语言环境...',
          it: 'Seleziona le lingue...',
          pt: 'Selecionar idiomas...',
          hi: 'स्थान चुनें...',
          ar: 'اختر المواقع...',
          ru: 'Выберите локали...',
          tr: 'Dilleri seçin...',
          pl: 'Wybierz lokalizacje...',
          id: 'Pilih locale...',
          vi: 'Chọn locale...',
        }),
        description: t({
          en: 'Select the locales available for your application',
          'en-GB': 'Select the locales available for your application',
          fr: 'Sélectionnez les locales disponibles pour votre application',
          es: 'Seleccione los idiomas disponibles para su aplicación',
          de: 'Wählen Sie die verfügbaren Sprachen für Ihre Anwendung',
          ja: 'アプリケーションで利用可能なロケールを選択してください',
          ko: '애플리케이션에 사용 가능한 로케일을 선택하세요',
          zh: '选择应用程序可用的语言环境',
          it: "Seleziona le lingue disponibili per l'applicazione",
          pt: 'Selecione os idiomas disponíveis para seu aplicativo',
          hi: 'अपने एप्लिकेशन के लिए उपलब्ध स्थान चुनें',
          ar: 'حدد المواقع المتاحة لتطبيقك',
          ru: 'Выберите локали, доступные для вашего приложения',
          tr: 'Uygulamanız için mevcut dilleri seçin',
          pl: 'Wybierz lokalizacje dostępne dla aplikacji',
          id: 'Pilih locale yang tersedia untuk aplikasi Anda',
          vi: 'Chọn các locale có sẵn cho ứng dụng của bạn',
        }),
      },
      defaultLocaleInput: {
        label: t({
          en: 'Default Locale',
          'en-GB': 'Default Locale',
          fr: 'Locale par défaut',
          es: 'Idioma predeterminado',
          de: 'Standardsprache',
          ja: 'デフォルトロケール',
          ko: '기본 로케일',
          zh: '默认语言环境',
          it: 'Lingua predefinita',
          pt: 'Idioma padrão',
          hi: 'डिफ़ॉल्ट स्थान',
          ar: 'الموقع الافتراضي',
          ru: 'Локаль по умолчанию',
          tr: 'Varsayılan dil',
          pl: 'Domyślna lokalizacja',
          id: 'Locale Default',
          vi: 'Locale mặc định',
        }),
        placeholder: t({
          en: 'Select default locale...',
          'en-GB': 'Select default locale...',
          fr: 'Sélectionner la locale par défaut...',
          es: 'Seleccionar idioma predeterminado...',
          de: 'Standardsprache auswählen...',
          ja: 'デフォルトロケールを選択...',
          ko: '기본 로케일 선택...',
          zh: '选择默认语言环境...',
          it: 'Seleziona la lingua predefinita...',
          pt: 'Selecionar idioma padrão...',
          hi: 'डिफ़ॉल्ट स्थान चुनें...',
          ar: 'اختر الموقع الافتراضي...',
          ru: 'Выберите локаль по умолчанию...',
          tr: 'Varsayılan dili seçin...',
          pl: 'Wybierz domyślną lokalizację...',
          id: 'Pilih locale default...',
          vi: 'Chọn locale mặc định...',
        }),
        description: t({
          en: 'The default locale used when no locale is specified',
          'en-GB': 'The default locale used when no locale is specified',
          fr: "La locale par défaut utilisée lorsqu'aucune locale n'est spécifiée",
          es: 'El idioma predeterminado utilizado cuando no se especifica ningún idioma',
          de: 'Die Standardsprache, die verwendet wird, wenn keine Sprache angegeben ist',
          ja: 'ロケールが指定されていない場合に使用されるデフォルトのロケール',
          ko: '로케일이 지정되지 않은 경우 사용되는 기본 로케일',
          zh: '未指定语言环境时使用的默认语言环境',
          it: 'La lingua predefinita utilizzata quando non è specificata alcuna lingua',
          pt: 'O idioma padrão usado quando nenhum idioma é especificado',
          hi: 'जब कोई स्थान निर्दिष्ट नहीं है तो उपयोग किया जाने वाला डिफ़ॉल्ट स्थान',
          ar: 'الموقع الافتراضي المستخدم عندما لا يتم تحديد موقع',
          ru: 'Локаль по умолчанию, используемая когда локаль не указана',
          tr: 'Dil belirtilmediğinde kullanılan varsayılan dil',
          pl: 'Domyślna lokalizacja używana gdy nie określono lokalizacji',
          id: 'Locale default yang digunakan saat tidak ada locale yang ditentukan',
          vi: 'Locale mặc định được sử dụng khi không có locale nào được chỉ định',
        }),
      },
    },
    editorSection: {
      title: t({
        en: 'Editor',
        'en-GB': 'Editor',
        fr: 'Éditeur',
        es: 'Editor',
        de: 'Editor',
        ja: 'エディタ',
        ko: '편집기',
        zh: '编辑器',
        it: 'Editor',
        pt: 'Editor',
        hi: 'संपादक',
        ar: 'المحرر',
        ru: 'Редактор',
        tr: 'Editör',
        pl: 'Edytor',
        id: 'Editor',
        vi: 'Editor',
      }),
      applicationURLInput: {
        label: t({
          en: 'Application URL',
          'en-GB': 'Application URL',
          fr: "URL de l'application",
          es: 'URL de la aplicación',
          de: 'Anwendungs-URL',
          ja: 'アプリケーション URL',
          ko: '애플리케이션 URL',
          zh: '应用程序 URL',
          it: "URL dell'applicazione",
          pt: 'URL do aplicativo',
          hi: 'एप्लीकेशन URL',
          ar: 'عنوان URL التطبيق',
          ru: 'URL-адрес приложения',
          tr: "Uygulama URL'si",
          pl: 'URL aplikacji',
          id: 'URL Aplikasi',
          vi: 'URL ứng dụng',
        }),
        placeholder: t({
          en: 'https://your-app.com',
          'en-GB': 'https://your-app.com',
          fr: 'https://votre-app.com',
          es: 'https://tu-app.com',
          de: 'https://ihre-app.com',
          ja: 'https://your-app.com',
          ko: 'https://your-app.com',
          zh: 'https://your-app.com',
          it: 'https://tua-app.com',
          pt: 'https://seu-app.com',
          hi: 'https://your-app.com',
          ar: 'https://your-app.com',
          ru: 'https://your-app.com',
          tr: 'https://uygulamaniz.com',
          pl: 'https://twoja-aplikacja.com',
          id: 'https://aplikasi-anda.com',
          vi: 'https://ung-dung-cua-ban.com',
        }),
        description: t({
          en: 'The URL where your application is hosted',
          'en-GB': 'The URL where your application is hosted',
          fr: 'URL où votre application est hébergée',
          es: 'La URL donde está alojada su aplicación',
          de: 'Die URL, unter der Ihre Anwendung gehostet wird',
          ja: 'アプリケーションがホストされている URL',
          ko: '애플리케이션이 호스팅되는 URL',
          zh: '应用程序托管的 URL',
          it: "L'URL in cui è ospitata la tua applicazione",
          pt: 'A URL onde seu aplicativo está hospedado',
          hi: 'जहां आपका एप्लिकेशन होस्ट किया गया है वह URL',
          ar: 'عنوان URL حيث يتم استضافة تطبيقك',
          ru: 'URL-адрес, где размещено ваше приложение',
          tr: 'Uygulamanızın barındırıldığı URL',
          pl: 'Adres URL, pod którym hostowana jest aplikacja',
          id: 'URL tempat aplikasi Anda dihosting',
          vi: 'URL nơi ứng dụng của bạn được lưu trữ',
        }),
      },
      cmsURLInput: {
        label: t({
          en: 'CMS URL',
          'en-GB': 'CMS URL',
          fr: 'URL du CMS',
          es: 'URL del CMS',
          de: 'CMS-URL',
          ja: 'CMS URL',
          ko: 'CMS URL',
          zh: 'CMS URL',
          it: 'URL del CMS',
          pt: 'URL do CMS',
          hi: 'CMS URL',
          ar: 'عنوان URL للمحرك المرئي',
          ru: 'URL-адрес CMS',
          tr: 'CMS URL',
          pl: 'URL CMS',
          id: 'URL CMS',
          vi: 'URL CMS',
        }),
        placeholder: t({
          en: 'https://intlayer.org',
          'en-GB': 'https://intlayer.org',
          fr: 'https://intlayer.org',
          es: 'https://intlayer.org',
          de: 'https://intlayer.org',
          ja: 'https://intlayer.org',
          ko: 'https://intlayer.org',
          zh: 'https://intlayer.org',
          it: 'https://intlayer.org',
          pt: 'https://intlayer.org',
          hi: 'https://intlayer.org',
          ar: 'https://intlayer.org',
          ru: 'https://intlayer.org',
          tr: 'https://intlayer.org',
          pl: 'https://intlayer.org',
          id: 'https://intlayer.org',
          vi: 'https://intlayer.org',
        }),
        description: t({
          en: 'The URL of the Intlayer CMS',
          'en-GB': 'The URL of the Intlayer CMS',
          fr: "L'URL du CMS Intlayer",
          es: 'La URL del CMS de Intlayer',
          de: 'Die URL des Intlayer CMS',
          ja: 'Intlayer CMS の URL',
          ko: 'Intlayer CMS의 URL',
          zh: 'Intlayer CMS 的 URL',
          it: "L'URL del CMS Intlayer",
          pt: 'A URL do CMS Intlayer',
          hi: 'Intlayer CMS का URL',
          ar: 'عنوان URL لـ Intlayer CMS',
          ru: 'URL-адрес Intlayer CMS',
          tr: 'Intlayer CMS URL adresi',
          pl: 'Adres URL Intlayer CMS',
          id: 'URL Intlayer CMS',
          vi: 'URL của Intlayer CMS',
        }),
      },
    },
    saveButton: {
      text: t({
        en: 'Save Configuration',
        'en-GB': 'Save Configuration',
        fr: 'Enregistrer la configuration',
        es: 'Guardar configuración',
        de: 'Konfiguration speichern',
        ja: '設定を保存',
        ko: '구성 저장',
        zh: '保存配置',
        it: 'Salva configurazione',
        pt: 'Salvar configuração',
        hi: 'कॉन्फ़िगरेशन सहेजें',
        ar: 'حفظ التكوين',
        ru: 'Сохранить конфигурацию',
        tr: 'Yapılandırmayı kaydet',
        pl: 'Zapisz konfigurację',
        id: 'Simpan Konfigurasi',
        vi: 'Lưu cấu hình',
      }),
      ariaLabel: t({
        en: 'Click to save the configuration',
        'en-GB': 'Click to save the configuration',
        fr: 'Cliquez pour enregistrer la configuration',
        es: 'Haga clic para guardar la configuración',
        de: 'Klicken Sie hier, um die Konfiguration zu speichern',
        ja: '設定を保存するにはクリックしてください',
        ko: '구성을 저장하려면 클릭하세요',
        zh: '点击保存配置',
        it: 'Clicca per salvare la configurazione',
        pt: 'Clique para salvar a configuração',
        hi: 'कॉन्फ़िगरेशन सहेजने के लिए क्लिक करें',
        ar: 'انقر لحفظ التكوين',
        ru: 'Нажмите, чтобы сохранить конфигурацию',
        tr: 'Yapılandırmayı kaydetmek için tıklayın',
        pl: 'Kliknij, aby zapisać konfigurację',
        id: 'Klik untuk menyimpan konfigurasi',
        vi: 'Nhấp để lưu cấu hình',
      }),
    },
    cancelButton: {
      text: t({
        en: 'Cancel',
        'en-GB': 'Cancel',
        fr: 'Annuler',
        es: 'Cancelar',
        de: 'Abbrechen',
        ja: 'キャンセル',
        ko: '취소',
        zh: '取消',
        it: 'Annulla',
        pt: 'Cancelar',
        hi: 'रद्द करें',
        ar: 'إلغاء',
        ru: 'Отмена',
        tr: 'İptal',
        pl: 'Anuluj',
        id: 'Batal',
        vi: 'Hủy',
      }),
      ariaLabel: t({
        en: 'Click to cancel and close the modal',
        'en-GB': 'Click to cancel and close the modal',
        fr: 'Cliquez pour annuler et fermer la fenêtre',
        es: 'Haga clic para cancelar y cerrar el modal',
        de: 'Klicken Sie hier, um abzubrechen und das Modal zu schließen',
        ja: 'キャンセルしてモーダルを閉じるにはクリックしてください',
        ko: '취소하고 모달을 닫으려면 클릭하세요',
        zh: '点击取消并关闭模态框',
        it: 'Clicca per annullare e chiudere la finestra',
        pt: 'Clique para cancelar e fechar o modal',
        hi: 'रद्द करने और मॉडल बंद करने के लिए क्लिक करें',
        ar: 'انقر للإلغاء وإغلاق النافذة',
        ru: 'Нажмите, чтобы отменить и закрыть модальное окно',
        tr: "İptal etmek ve modal'ı kapatmak için tıklayın",
        pl: 'Kliknij, aby anulować i zamknąć okno modalne',
        id: 'Klik untuk membatalkan dan menutup modal',
        vi: 'Nhấp để hủy và đóng modal',
      }),
    },
    editButton: {
      ariaLabel: t({
        en: 'Click to edit the configuration',
        'en-GB': 'Click to edit the configuration',
        fr: 'Cliquez pour modifier la configuration',
        es: 'Haga clic para editar la configuración',
        de: 'Klicken Sie hier, um die Konfiguration zu bearbeiten',
        ja: '設定を編集するにはクリックしてください',
        ko: '구성을 편집하려면 클릭하세요',
        zh: '点击编辑配置',
        it: 'Clicca per modificare la configurazione',
        pt: 'Clique para editar a configuração',
        hi: 'कॉन्फ़िगरेशन संपादित करने के लिए क्लिक करें',
        ar: 'انقر لتعديل التكوين',
        ru: 'Нажмите, чтобы редактировать конфигурацию',
        tr: 'Yapılandırmayı düzenlemek için tıklayın',
        pl: 'Kliknij, aby edytować konfigurację',
        id: 'Klik untuk mengedit konfigurasi',
        vi: 'Nhấp để chỉnh sửa cấu hình',
      }),
    },
  },
  title: 'Config edition form content',
  description:
    'Content declaration for the project configuration edition form.',
  tags: ['dashboard', 'form', 'config', 'edit'],
} satisfies Dictionary;

export default configEditionFormContent;
