/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Char123LocaleChar125RouteRouteImport } from './routes/{-$locale}/route'
import { Route as Char123LocaleChar125OtherRouteImport } from './routes/{-$locale}/_other'
import { Route as Char123LocaleChar125DashboardRouteImport } from './routes/{-$locale}/_dashboard'
import { Route as Char123LocaleChar125404RouteImport } from './routes/{-$locale}/404'
import { Route as Char123LocaleChar125SplatRouteImport } from './routes/{-$locale}/$'
import { Route as Char123LocaleChar125DashboardIndexRouteImport } from './routes/{-$locale}/_dashboard/index'
import { Route as Char123LocaleChar125OtherPricingRouteImport } from './routes/{-$locale}/_other/pricing'
import { Route as Char123LocaleChar125OtherOnboardingRouteImport } from './routes/{-$locale}/_other/onboarding'
import { Route as Char123LocaleChar125DashboardProjectsRouteImport } from './routes/{-$locale}/_dashboard/projects'
import { Route as Char123LocaleChar125DashboardProfileRouteImport } from './routes/{-$locale}/_dashboard/profile'
import { Route as Char123LocaleChar125DashboardOrganizationRouteImport } from './routes/{-$locale}/_dashboard/organization'
import { Route as Char123LocaleChar125DashboardEditorRouteImport } from './routes/{-$locale}/_dashboard/_editor'
import { Route as Char123LocaleChar125DashboardAdminRouteImport } from './routes/{-$locale}/_dashboard/_admin'
import { Route as Char123LocaleChar125OtherAuthCliLoginRouteImport } from './routes/{-$locale}/_other/auth/cli-login'
import { Route as Char123LocaleChar125OtherAuthNotAuthenticatedRouteImport } from './routes/{-$locale}/_other/auth/_not-authenticated'
import { Route as Char123LocaleChar125OtherAuthAuthenticatedRouteImport } from './routes/{-$locale}/_other/auth/_authenticated'
import { Route as Char123LocaleChar125DashboardEditorTagsRouteImport } from './routes/{-$locale}/_dashboard/_editor/tags'
import { Route as Char123LocaleChar125DashboardAdminAdminRouteImport } from './routes/{-$locale}/_dashboard/_admin/admin'
import { Route as Char123LocaleChar125OtherAuthPasswordResetRouteImport } from './routes/{-$locale}/_other/auth/password/reset'
import { Route as Char123LocaleChar125OtherAuthPasswordAskResetRouteImport } from './routes/{-$locale}/_other/auth/password/ask-reset'
import { Route as Char123LocaleChar125OtherAuthPasswordLayoutRouteImport } from './routes/{-$locale}/_other/auth/password/_layout'
import { Route as Char123LocaleChar125OtherAuthNotAuthenticatedRegisterRouteImport } from './routes/{-$locale}/_other/auth/_not-authenticated/register'
import { Route as Char123LocaleChar125OtherAuthNotAuthenticatedLoginRouteImport } from './routes/{-$locale}/_other/auth/_not-authenticated/login'
import { Route as Char123LocaleChar125OtherAuthNotAuthenticated2faRouteImport } from './routes/{-$locale}/_other/auth/_not-authenticated/2fa'
import { Route as Char123LocaleChar125DashboardEditorTagsTagKeyRouteImport } from './routes/{-$locale}/_dashboard/_editor/tags.$tagKey'
import { Route as Char123LocaleChar125DashboardEditorContentTranslateRouteImport } from './routes/{-$locale}/_dashboard/_editor/_content/translate'
import { Route as Char123LocaleChar125DashboardEditorContentEditorRouteImport } from './routes/{-$locale}/_dashboard/_editor/_content/editor'
import { Route as Char123LocaleChar125DashboardEditorContentDictionaryRouteImport } from './routes/{-$locale}/_dashboard/_editor/_content/dictionary'
import { Route as Char123LocaleChar125DashboardAdminAdminUsersRouteImport } from './routes/{-$locale}/_dashboard/_admin/admin.users'
import { Route as Char123LocaleChar125DashboardAdminAdminProjectsRouteImport } from './routes/{-$locale}/_dashboard/_admin/admin.projects'
import { Route as Char123LocaleChar125DashboardAdminAdminOrganizationsRouteImport } from './routes/{-$locale}/_dashboard/_admin/admin.organizations'
import { Route as Char123LocaleChar125DashboardAdminAdminDiscussionsRouteImport } from './routes/{-$locale}/_dashboard/_admin/admin.discussions'
import { Route as Char123LocaleChar125OtherAuthAuthenticatedPasswordChangeRouteImport } from './routes/{-$locale}/_other/auth/_authenticated/password.change'
import { Route as Char123LocaleChar125DashboardEditorContentDictionaryDictionaryKeyRouteImport } from './routes/{-$locale}/_dashboard/_editor/_content/dictionary.$dictionaryKey'
import { Route as Char123LocaleChar125DashboardAdminAdminUsersIdRouteImport } from './routes/{-$locale}/_dashboard/_admin/admin.users.$id'
import { Route as Char123LocaleChar125DashboardAdminAdminProjectsIdRouteImport } from './routes/{-$locale}/_dashboard/_admin/admin.projects.$id'
import { Route as Char123LocaleChar125DashboardAdminAdminOrganizationsIdRouteImport } from './routes/{-$locale}/_dashboard/_admin/admin.organizations.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: '/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125OtherRoute =
  Char123LocaleChar125OtherRouteImport.update({
    id: '/_other',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125DashboardRoute =
  Char123LocaleChar125DashboardRouteImport.update({
    id: '/_dashboard',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125404Route = Char123LocaleChar125404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => Char123LocaleChar125RouteRoute,
} as any)
const Char123LocaleChar125SplatRoute =
  Char123LocaleChar125SplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125DashboardIndexRoute =
  Char123LocaleChar125DashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125DashboardRoute,
  } as any)
const Char123LocaleChar125OtherPricingRoute =
  Char123LocaleChar125OtherPricingRouteImport.update({
    id: '/pricing',
    path: '/pricing',
    getParentRoute: () => Char123LocaleChar125OtherRoute,
  } as any)
const Char123LocaleChar125OtherOnboardingRoute =
  Char123LocaleChar125OtherOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => Char123LocaleChar125OtherRoute,
  } as any)
const Char123LocaleChar125DashboardProjectsRoute =
  Char123LocaleChar125DashboardProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => Char123LocaleChar125DashboardRoute,
  } as any)
const Char123LocaleChar125DashboardProfileRoute =
  Char123LocaleChar125DashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => Char123LocaleChar125DashboardRoute,
  } as any)
const Char123LocaleChar125DashboardOrganizationRoute =
  Char123LocaleChar125DashboardOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => Char123LocaleChar125DashboardRoute,
  } as any)
const Char123LocaleChar125DashboardEditorRoute =
  Char123LocaleChar125DashboardEditorRouteImport.update({
    id: '/_editor',
    getParentRoute: () => Char123LocaleChar125DashboardRoute,
  } as any)
const Char123LocaleChar125DashboardAdminRoute =
  Char123LocaleChar125DashboardAdminRouteImport.update({
    id: '/_admin',
    getParentRoute: () => Char123LocaleChar125DashboardRoute,
  } as any)
const Char123LocaleChar125OtherAuthCliLoginRoute =
  Char123LocaleChar125OtherAuthCliLoginRouteImport.update({
    id: '/auth/cli-login',
    path: '/auth/cli-login',
    getParentRoute: () => Char123LocaleChar125OtherRoute,
  } as any)
const Char123LocaleChar125OtherAuthNotAuthenticatedRoute =
  Char123LocaleChar125OtherAuthNotAuthenticatedRouteImport.update({
    id: '/auth/_not-authenticated',
    path: '/auth',
    getParentRoute: () => Char123LocaleChar125OtherRoute,
  } as any)
const Char123LocaleChar125OtherAuthAuthenticatedRoute =
  Char123LocaleChar125OtherAuthAuthenticatedRouteImport.update({
    id: '/auth/_authenticated',
    path: '/auth',
    getParentRoute: () => Char123LocaleChar125OtherRoute,
  } as any)
const Char123LocaleChar125DashboardEditorTagsRoute =
  Char123LocaleChar125DashboardEditorTagsRouteImport.update({
    id: '/tags',
    path: '/tags',
    getParentRoute: () => Char123LocaleChar125DashboardEditorRoute,
  } as any)
const Char123LocaleChar125DashboardAdminAdminRoute =
  Char123LocaleChar125DashboardAdminAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => Char123LocaleChar125DashboardAdminRoute,
  } as any)
const Char123LocaleChar125OtherAuthPasswordResetRoute =
  Char123LocaleChar125OtherAuthPasswordResetRouteImport.update({
    id: '/auth/password/reset',
    path: '/auth/password/reset',
    getParentRoute: () => Char123LocaleChar125OtherRoute,
  } as any)
const Char123LocaleChar125OtherAuthPasswordAskResetRoute =
  Char123LocaleChar125OtherAuthPasswordAskResetRouteImport.update({
    id: '/auth/password/ask-reset',
    path: '/auth/password/ask-reset',
    getParentRoute: () => Char123LocaleChar125OtherRoute,
  } as any)
const Char123LocaleChar125OtherAuthPasswordLayoutRoute =
  Char123LocaleChar125OtherAuthPasswordLayoutRouteImport.update({
    id: '/auth/password/_layout',
    path: '/auth/password',
    getParentRoute: () => Char123LocaleChar125OtherRoute,
  } as any)
const Char123LocaleChar125OtherAuthNotAuthenticatedRegisterRoute =
  Char123LocaleChar125OtherAuthNotAuthenticatedRegisterRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => Char123LocaleChar125OtherAuthNotAuthenticatedRoute,
  } as any)
const Char123LocaleChar125OtherAuthNotAuthenticatedLoginRoute =
  Char123LocaleChar125OtherAuthNotAuthenticatedLoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => Char123LocaleChar125OtherAuthNotAuthenticatedRoute,
  } as any)
const Char123LocaleChar125OtherAuthNotAuthenticated2faRoute =
  Char123LocaleChar125OtherAuthNotAuthenticated2faRouteImport.update({
    id: '/2fa',
    path: '/2fa',
    getParentRoute: () => Char123LocaleChar125OtherAuthNotAuthenticatedRoute,
  } as any)
const Char123LocaleChar125DashboardEditorTagsTagKeyRoute =
  Char123LocaleChar125DashboardEditorTagsTagKeyRouteImport.update({
    id: '/$tagKey',
    path: '/$tagKey',
    getParentRoute: () => Char123LocaleChar125DashboardEditorTagsRoute,
  } as any)
const Char123LocaleChar125DashboardEditorContentTranslateRoute =
  Char123LocaleChar125DashboardEditorContentTranslateRouteImport.update({
    id: '/_content/translate',
    path: '/translate',
    getParentRoute: () => Char123LocaleChar125DashboardEditorRoute,
  } as any)
const Char123LocaleChar125DashboardEditorContentEditorRoute =
  Char123LocaleChar125DashboardEditorContentEditorRouteImport.update({
    id: '/_content/editor',
    path: '/editor',
    getParentRoute: () => Char123LocaleChar125DashboardEditorRoute,
  } as any)
const Char123LocaleChar125DashboardEditorContentDictionaryRoute =
  Char123LocaleChar125DashboardEditorContentDictionaryRouteImport.update({
    id: '/_content/dictionary',
    path: '/dictionary',
    getParentRoute: () => Char123LocaleChar125DashboardEditorRoute,
  } as any)
const Char123LocaleChar125DashboardAdminAdminUsersRoute =
  Char123LocaleChar125DashboardAdminAdminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => Char123LocaleChar125DashboardAdminAdminRoute,
  } as any)
const Char123LocaleChar125DashboardAdminAdminProjectsRoute =
  Char123LocaleChar125DashboardAdminAdminProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => Char123LocaleChar125DashboardAdminAdminRoute,
  } as any)
const Char123LocaleChar125DashboardAdminAdminOrganizationsRoute =
  Char123LocaleChar125DashboardAdminAdminOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => Char123LocaleChar125DashboardAdminAdminRoute,
  } as any)
const Char123LocaleChar125DashboardAdminAdminDiscussionsRoute =
  Char123LocaleChar125DashboardAdminAdminDiscussionsRouteImport.update({
    id: '/discussions',
    path: '/discussions',
    getParentRoute: () => Char123LocaleChar125DashboardAdminAdminRoute,
  } as any)
const Char123LocaleChar125OtherAuthAuthenticatedPasswordChangeRoute =
  Char123LocaleChar125OtherAuthAuthenticatedPasswordChangeRouteImport.update({
    id: '/password/change',
    path: '/password/change',
    getParentRoute: () => Char123LocaleChar125OtherAuthAuthenticatedRoute,
  } as any)
const Char123LocaleChar125DashboardEditorContentDictionaryDictionaryKeyRoute =
  Char123LocaleChar125DashboardEditorContentDictionaryDictionaryKeyRouteImport.update(
    {
      id: '/$dictionaryKey',
      path: '/$dictionaryKey',
      getParentRoute: () =>
        Char123LocaleChar125DashboardEditorContentDictionaryRoute,
    } as any,
  )
const Char123LocaleChar125DashboardAdminAdminUsersIdRoute =
  Char123LocaleChar125DashboardAdminAdminUsersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => Char123LocaleChar125DashboardAdminAdminUsersRoute,
  } as any)
const Char123LocaleChar125DashboardAdminAdminProjectsIdRoute =
  Char123LocaleChar125DashboardAdminAdminProjectsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => Char123LocaleChar125DashboardAdminAdminProjectsRoute,
  } as any)
const Char123LocaleChar125DashboardAdminAdminOrganizationsIdRoute =
  Char123LocaleChar125DashboardAdminAdminOrganizationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () =>
      Char123LocaleChar125DashboardAdminAdminOrganizationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125DashboardEditorRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}/$': typeof Char123LocaleChar125SplatRoute
  '/{-$locale}/404': typeof Char123LocaleChar125404Route
  '/{-$locale}/organization': typeof Char123LocaleChar125DashboardOrganizationRoute
  '/{-$locale}/profile': typeof Char123LocaleChar125DashboardProfileRoute
  '/{-$locale}/projects': typeof Char123LocaleChar125DashboardProjectsRoute
  '/{-$locale}/onboarding': typeof Char123LocaleChar125OtherOnboardingRoute
  '/{-$locale}/pricing': typeof Char123LocaleChar125OtherPricingRoute
  '/{-$locale}/': typeof Char123LocaleChar125DashboardIndexRoute
  '/{-$locale}/admin': typeof Char123LocaleChar125DashboardAdminAdminRouteWithChildren
  '/{-$locale}/tags': typeof Char123LocaleChar125DashboardEditorTagsRouteWithChildren
  '/{-$locale}/auth': typeof Char123LocaleChar125OtherAuthNotAuthenticatedRouteWithChildren
  '/{-$locale}/auth/cli-login': typeof Char123LocaleChar125OtherAuthCliLoginRoute
  '/{-$locale}/admin/discussions': typeof Char123LocaleChar125DashboardAdminAdminDiscussionsRoute
  '/{-$locale}/admin/organizations': typeof Char123LocaleChar125DashboardAdminAdminOrganizationsRouteWithChildren
  '/{-$locale}/admin/projects': typeof Char123LocaleChar125DashboardAdminAdminProjectsRouteWithChildren
  '/{-$locale}/admin/users': typeof Char123LocaleChar125DashboardAdminAdminUsersRouteWithChildren
  '/{-$locale}/dictionary': typeof Char123LocaleChar125DashboardEditorContentDictionaryRouteWithChildren
  '/{-$locale}/editor': typeof Char123LocaleChar125DashboardEditorContentEditorRoute
  '/{-$locale}/translate': typeof Char123LocaleChar125DashboardEditorContentTranslateRoute
  '/{-$locale}/tags/$tagKey': typeof Char123LocaleChar125DashboardEditorTagsTagKeyRoute
  '/{-$locale}/auth/2fa': typeof Char123LocaleChar125OtherAuthNotAuthenticated2faRoute
  '/{-$locale}/auth/login': typeof Char123LocaleChar125OtherAuthNotAuthenticatedLoginRoute
  '/{-$locale}/auth/register': typeof Char123LocaleChar125OtherAuthNotAuthenticatedRegisterRoute
  '/{-$locale}/auth/password': typeof Char123LocaleChar125OtherAuthPasswordLayoutRoute
  '/{-$locale}/auth/password/ask-reset': typeof Char123LocaleChar125OtherAuthPasswordAskResetRoute
  '/{-$locale}/auth/password/reset': typeof Char123LocaleChar125OtherAuthPasswordResetRoute
  '/{-$locale}/admin/organizations/$id': typeof Char123LocaleChar125DashboardAdminAdminOrganizationsIdRoute
  '/{-$locale}/admin/projects/$id': typeof Char123LocaleChar125DashboardAdminAdminProjectsIdRoute
  '/{-$locale}/admin/users/$id': typeof Char123LocaleChar125DashboardAdminAdminUsersIdRoute
  '/{-$locale}/dictionary/$dictionaryKey': typeof Char123LocaleChar125DashboardEditorContentDictionaryDictionaryKeyRoute
  '/{-$locale}/auth/password/change': typeof Char123LocaleChar125OtherAuthAuthenticatedPasswordChangeRoute
}
export interface FileRoutesByTo {
  '/{-$locale}': typeof Char123LocaleChar125DashboardIndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}/$': typeof Char123LocaleChar125SplatRoute
  '/{-$locale}/404': typeof Char123LocaleChar125404Route
  '/{-$locale}/organization': typeof Char123LocaleChar125DashboardOrganizationRoute
  '/{-$locale}/profile': typeof Char123LocaleChar125DashboardProfileRoute
  '/{-$locale}/projects': typeof Char123LocaleChar125DashboardProjectsRoute
  '/{-$locale}/onboarding': typeof Char123LocaleChar125OtherOnboardingRoute
  '/{-$locale}/pricing': typeof Char123LocaleChar125OtherPricingRoute
  '/{-$locale}/admin': typeof Char123LocaleChar125DashboardAdminAdminRouteWithChildren
  '/{-$locale}/tags': typeof Char123LocaleChar125DashboardEditorTagsRouteWithChildren
  '/{-$locale}/auth': typeof Char123LocaleChar125OtherAuthNotAuthenticatedRouteWithChildren
  '/{-$locale}/auth/cli-login': typeof Char123LocaleChar125OtherAuthCliLoginRoute
  '/{-$locale}/admin/discussions': typeof Char123LocaleChar125DashboardAdminAdminDiscussionsRoute
  '/{-$locale}/admin/organizations': typeof Char123LocaleChar125DashboardAdminAdminOrganizationsRouteWithChildren
  '/{-$locale}/admin/projects': typeof Char123LocaleChar125DashboardAdminAdminProjectsRouteWithChildren
  '/{-$locale}/admin/users': typeof Char123LocaleChar125DashboardAdminAdminUsersRouteWithChildren
  '/{-$locale}/dictionary': typeof Char123LocaleChar125DashboardEditorContentDictionaryRouteWithChildren
  '/{-$locale}/editor': typeof Char123LocaleChar125DashboardEditorContentEditorRoute
  '/{-$locale}/translate': typeof Char123LocaleChar125DashboardEditorContentTranslateRoute
  '/{-$locale}/tags/$tagKey': typeof Char123LocaleChar125DashboardEditorTagsTagKeyRoute
  '/{-$locale}/auth/2fa': typeof Char123LocaleChar125OtherAuthNotAuthenticated2faRoute
  '/{-$locale}/auth/login': typeof Char123LocaleChar125OtherAuthNotAuthenticatedLoginRoute
  '/{-$locale}/auth/register': typeof Char123LocaleChar125OtherAuthNotAuthenticatedRegisterRoute
  '/{-$locale}/auth/password': typeof Char123LocaleChar125OtherAuthPasswordLayoutRoute
  '/{-$locale}/auth/password/ask-reset': typeof Char123LocaleChar125OtherAuthPasswordAskResetRoute
  '/{-$locale}/auth/password/reset': typeof Char123LocaleChar125OtherAuthPasswordResetRoute
  '/{-$locale}/admin/organizations/$id': typeof Char123LocaleChar125DashboardAdminAdminOrganizationsIdRoute
  '/{-$locale}/admin/projects/$id': typeof Char123LocaleChar125DashboardAdminAdminProjectsIdRoute
  '/{-$locale}/admin/users/$id': typeof Char123LocaleChar125DashboardAdminAdminUsersIdRoute
  '/{-$locale}/dictionary/$dictionaryKey': typeof Char123LocaleChar125DashboardEditorContentDictionaryDictionaryKeyRoute
  '/{-$locale}/auth/password/change': typeof Char123LocaleChar125OtherAuthAuthenticatedPasswordChangeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}/$': typeof Char123LocaleChar125SplatRoute
  '/{-$locale}/404': typeof Char123LocaleChar125404Route
  '/{-$locale}/_dashboard': typeof Char123LocaleChar125DashboardRouteWithChildren
  '/{-$locale}/_other': typeof Char123LocaleChar125OtherRouteWithChildren
  '/{-$locale}/_dashboard/_admin': typeof Char123LocaleChar125DashboardAdminRouteWithChildren
  '/{-$locale}/_dashboard/_editor': typeof Char123LocaleChar125DashboardEditorRouteWithChildren
  '/{-$locale}/_dashboard/organization': typeof Char123LocaleChar125DashboardOrganizationRoute
  '/{-$locale}/_dashboard/profile': typeof Char123LocaleChar125DashboardProfileRoute
  '/{-$locale}/_dashboard/projects': typeof Char123LocaleChar125DashboardProjectsRoute
  '/{-$locale}/_other/onboarding': typeof Char123LocaleChar125OtherOnboardingRoute
  '/{-$locale}/_other/pricing': typeof Char123LocaleChar125OtherPricingRoute
  '/{-$locale}/_dashboard/': typeof Char123LocaleChar125DashboardIndexRoute
  '/{-$locale}/_dashboard/_admin/admin': typeof Char123LocaleChar125DashboardAdminAdminRouteWithChildren
  '/{-$locale}/_dashboard/_editor/tags': typeof Char123LocaleChar125DashboardEditorTagsRouteWithChildren
  '/{-$locale}/_other/auth/_authenticated': typeof Char123LocaleChar125OtherAuthAuthenticatedRouteWithChildren
  '/{-$locale}/_other/auth/_not-authenticated': typeof Char123LocaleChar125OtherAuthNotAuthenticatedRouteWithChildren
  '/{-$locale}/_other/auth/cli-login': typeof Char123LocaleChar125OtherAuthCliLoginRoute
  '/{-$locale}/_dashboard/_admin/admin/discussions': typeof Char123LocaleChar125DashboardAdminAdminDiscussionsRoute
  '/{-$locale}/_dashboard/_admin/admin/organizations': typeof Char123LocaleChar125DashboardAdminAdminOrganizationsRouteWithChildren
  '/{-$locale}/_dashboard/_admin/admin/projects': typeof Char123LocaleChar125DashboardAdminAdminProjectsRouteWithChildren
  '/{-$locale}/_dashboard/_admin/admin/users': typeof Char123LocaleChar125DashboardAdminAdminUsersRouteWithChildren
  '/{-$locale}/_dashboard/_editor/_content/dictionary': typeof Char123LocaleChar125DashboardEditorContentDictionaryRouteWithChildren
  '/{-$locale}/_dashboard/_editor/_content/editor': typeof Char123LocaleChar125DashboardEditorContentEditorRoute
  '/{-$locale}/_dashboard/_editor/_content/translate': typeof Char123LocaleChar125DashboardEditorContentTranslateRoute
  '/{-$locale}/_dashboard/_editor/tags/$tagKey': typeof Char123LocaleChar125DashboardEditorTagsTagKeyRoute
  '/{-$locale}/_other/auth/_not-authenticated/2fa': typeof Char123LocaleChar125OtherAuthNotAuthenticated2faRoute
  '/{-$locale}/_other/auth/_not-authenticated/login': typeof Char123LocaleChar125OtherAuthNotAuthenticatedLoginRoute
  '/{-$locale}/_other/auth/_not-authenticated/register': typeof Char123LocaleChar125OtherAuthNotAuthenticatedRegisterRoute
  '/{-$locale}/_other/auth/password/_layout': typeof Char123LocaleChar125OtherAuthPasswordLayoutRoute
  '/{-$locale}/_other/auth/password/ask-reset': typeof Char123LocaleChar125OtherAuthPasswordAskResetRoute
  '/{-$locale}/_other/auth/password/reset': typeof Char123LocaleChar125OtherAuthPasswordResetRoute
  '/{-$locale}/_dashboard/_admin/admin/organizations/$id': typeof Char123LocaleChar125DashboardAdminAdminOrganizationsIdRoute
  '/{-$locale}/_dashboard/_admin/admin/projects/$id': typeof Char123LocaleChar125DashboardAdminAdminProjectsIdRoute
  '/{-$locale}/_dashboard/_admin/admin/users/$id': typeof Char123LocaleChar125DashboardAdminAdminUsersIdRoute
  '/{-$locale}/_dashboard/_editor/_content/dictionary/$dictionaryKey': typeof Char123LocaleChar125DashboardEditorContentDictionaryDictionaryKeyRoute
  '/{-$locale}/_other/auth/_authenticated/password/change': typeof Char123LocaleChar125OtherAuthAuthenticatedPasswordChangeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/sitemap.xml'
    | '/{-$locale}/$'
    | '/{-$locale}/404'
    | '/{-$locale}/organization'
    | '/{-$locale}/profile'
    | '/{-$locale}/projects'
    | '/{-$locale}/onboarding'
    | '/{-$locale}/pricing'
    | '/{-$locale}/'
    | '/{-$locale}/admin'
    | '/{-$locale}/tags'
    | '/{-$locale}/auth'
    | '/{-$locale}/auth/cli-login'
    | '/{-$locale}/admin/discussions'
    | '/{-$locale}/admin/organizations'
    | '/{-$locale}/admin/projects'
    | '/{-$locale}/admin/users'
    | '/{-$locale}/dictionary'
    | '/{-$locale}/editor'
    | '/{-$locale}/translate'
    | '/{-$locale}/tags/$tagKey'
    | '/{-$locale}/auth/2fa'
    | '/{-$locale}/auth/login'
    | '/{-$locale}/auth/register'
    | '/{-$locale}/auth/password'
    | '/{-$locale}/auth/password/ask-reset'
    | '/{-$locale}/auth/password/reset'
    | '/{-$locale}/admin/organizations/$id'
    | '/{-$locale}/admin/projects/$id'
    | '/{-$locale}/admin/users/$id'
    | '/{-$locale}/dictionary/$dictionaryKey'
    | '/{-$locale}/auth/password/change'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$locale}'
    | '/sitemap.xml'
    | '/{-$locale}/$'
    | '/{-$locale}/404'
    | '/{-$locale}/organization'
    | '/{-$locale}/profile'
    | '/{-$locale}/projects'
    | '/{-$locale}/onboarding'
    | '/{-$locale}/pricing'
    | '/{-$locale}/admin'
    | '/{-$locale}/tags'
    | '/{-$locale}/auth'
    | '/{-$locale}/auth/cli-login'
    | '/{-$locale}/admin/discussions'
    | '/{-$locale}/admin/organizations'
    | '/{-$locale}/admin/projects'
    | '/{-$locale}/admin/users'
    | '/{-$locale}/dictionary'
    | '/{-$locale}/editor'
    | '/{-$locale}/translate'
    | '/{-$locale}/tags/$tagKey'
    | '/{-$locale}/auth/2fa'
    | '/{-$locale}/auth/login'
    | '/{-$locale}/auth/register'
    | '/{-$locale}/auth/password'
    | '/{-$locale}/auth/password/ask-reset'
    | '/{-$locale}/auth/password/reset'
    | '/{-$locale}/admin/organizations/$id'
    | '/{-$locale}/admin/projects/$id'
    | '/{-$locale}/admin/users/$id'
    | '/{-$locale}/dictionary/$dictionaryKey'
    | '/{-$locale}/auth/password/change'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/sitemap.xml'
    | '/{-$locale}/$'
    | '/{-$locale}/404'
    | '/{-$locale}/_dashboard'
    | '/{-$locale}/_other'
    | '/{-$locale}/_dashboard/_admin'
    | '/{-$locale}/_dashboard/_editor'
    | '/{-$locale}/_dashboard/organization'
    | '/{-$locale}/_dashboard/profile'
    | '/{-$locale}/_dashboard/projects'
    | '/{-$locale}/_other/onboarding'
    | '/{-$locale}/_other/pricing'
    | '/{-$locale}/_dashboard/'
    | '/{-$locale}/_dashboard/_admin/admin'
    | '/{-$locale}/_dashboard/_editor/tags'
    | '/{-$locale}/_other/auth/_authenticated'
    | '/{-$locale}/_other/auth/_not-authenticated'
    | '/{-$locale}/_other/auth/cli-login'
    | '/{-$locale}/_dashboard/_admin/admin/discussions'
    | '/{-$locale}/_dashboard/_admin/admin/organizations'
    | '/{-$locale}/_dashboard/_admin/admin/projects'
    | '/{-$locale}/_dashboard/_admin/admin/users'
    | '/{-$locale}/_dashboard/_editor/_content/dictionary'
    | '/{-$locale}/_dashboard/_editor/_content/editor'
    | '/{-$locale}/_dashboard/_editor/_content/translate'
    | '/{-$locale}/_dashboard/_editor/tags/$tagKey'
    | '/{-$locale}/_other/auth/_not-authenticated/2fa'
    | '/{-$locale}/_other/auth/_not-authenticated/login'
    | '/{-$locale}/_other/auth/_not-authenticated/register'
    | '/{-$locale}/_other/auth/password/_layout'
    | '/{-$locale}/_other/auth/password/ask-reset'
    | '/{-$locale}/_other/auth/password/reset'
    | '/{-$locale}/_dashboard/_admin/admin/organizations/$id'
    | '/{-$locale}/_dashboard/_admin/admin/projects/$id'
    | '/{-$locale}/_dashboard/_admin/admin/users/$id'
    | '/{-$locale}/_dashboard/_editor/_content/dictionary/$dictionaryKey'
    | '/{-$locale}/_other/auth/_authenticated/password/change'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/_other': {
      id: '/{-$locale}/_other'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125OtherRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/_dashboard': {
      id: '/{-$locale}/_dashboard'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125DashboardRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/404': {
      id: '/{-$locale}/404'
      path: '/404'
      fullPath: '/{-$locale}/404'
      preLoaderRoute: typeof Char123LocaleChar125404RouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/$': {
      id: '/{-$locale}/$'
      path: '/$'
      fullPath: '/{-$locale}/$'
      preLoaderRoute: typeof Char123LocaleChar125SplatRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/_dashboard/': {
      id: '/{-$locale}/_dashboard/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125DashboardIndexRouteImport
      parentRoute: typeof Char123LocaleChar125DashboardRoute
    }
    '/{-$locale}/_other/pricing': {
      id: '/{-$locale}/_other/pricing'
      path: '/pricing'
      fullPath: '/{-$locale}/pricing'
      preLoaderRoute: typeof Char123LocaleChar125OtherPricingRouteImport
      parentRoute: typeof Char123LocaleChar125OtherRoute
    }
    '/{-$locale}/_other/onboarding': {
      id: '/{-$locale}/_other/onboarding'
      path: '/onboarding'
      fullPath: '/{-$locale}/onboarding'
      preLoaderRoute: typeof Char123LocaleChar125OtherOnboardingRouteImport
      parentRoute: typeof Char123LocaleChar125OtherRoute
    }
    '/{-$locale}/_dashboard/projects': {
      id: '/{-$locale}/_dashboard/projects'
      path: '/projects'
      fullPath: '/{-$locale}/projects'
      preLoaderRoute: typeof Char123LocaleChar125DashboardProjectsRouteImport
      parentRoute: typeof Char123LocaleChar125DashboardRoute
    }
    '/{-$locale}/_dashboard/profile': {
      id: '/{-$locale}/_dashboard/profile'
      path: '/profile'
      fullPath: '/{-$locale}/profile'
      preLoaderRoute: typeof Char123LocaleChar125DashboardProfileRouteImport
      parentRoute: typeof Char123LocaleChar125DashboardRoute
    }
    '/{-$locale}/_dashboard/organization': {
      id: '/{-$locale}/_dashboard/organization'
      path: '/organization'
      fullPath: '/{-$locale}/organization'
      preLoaderRoute: typeof Char123LocaleChar125DashboardOrganizationRouteImport
      parentRoute: typeof Char123LocaleChar125DashboardRoute
    }
    '/{-$locale}/_dashboard/_editor': {
      id: '/{-$locale}/_dashboard/_editor'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125DashboardEditorRouteImport
      parentRoute: typeof Char123LocaleChar125DashboardRoute
    }
    '/{-$locale}/_dashboard/_admin': {
      id: '/{-$locale}/_dashboard/_admin'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125DashboardAdminRouteImport
      parentRoute: typeof Char123LocaleChar125DashboardRoute
    }
    '/{-$locale}/_other/auth/cli-login': {
      id: '/{-$locale}/_other/auth/cli-login'
      path: '/auth/cli-login'
      fullPath: '/{-$locale}/auth/cli-login'
      preLoaderRoute: typeof Char123LocaleChar125OtherAuthCliLoginRouteImport
      parentRoute: typeof Char123LocaleChar125OtherRoute
    }
    '/{-$locale}/_other/auth/_not-authenticated': {
      id: '/{-$locale}/_other/auth/_not-authenticated'
      path: '/auth'
      fullPath: '/{-$locale}/auth'
      preLoaderRoute: typeof Char123LocaleChar125OtherAuthNotAuthenticatedRouteImport
      parentRoute: typeof Char123LocaleChar125OtherRoute
    }
    '/{-$locale}/_other/auth/_authenticated': {
      id: '/{-$locale}/_other/auth/_authenticated'
      path: '/auth'
      fullPath: '/{-$locale}/auth'
      preLoaderRoute: typeof Char123LocaleChar125OtherAuthAuthenticatedRouteImport
      parentRoute: typeof Char123LocaleChar125OtherRoute
    }
    '/{-$locale}/_dashboard/_editor/tags': {
      id: '/{-$locale}/_dashboard/_editor/tags'
      path: '/tags'
      fullPath: '/{-$locale}/tags'
      preLoaderRoute: typeof Char123LocaleChar125DashboardEditorTagsRouteImport
      parentRoute: typeof Char123LocaleChar125DashboardEditorRoute
    }
    '/{-$locale}/_dashboard/_admin/admin': {
      id: '/{-$locale}/_dashboard/_admin/admin'
      path: '/admin'
      fullPath: '/{-$locale}/admin'
      preLoaderRoute: typeof Char123LocaleChar125DashboardAdminAdminRouteImport
      parentRoute: typeof Char123LocaleChar125DashboardAdminRoute
    }
    '/{-$locale}/_other/auth/password/reset': {
      id: '/{-$locale}/_other/auth/password/reset'
      path: '/auth/password/reset'
      fullPath: '/{-$locale}/auth/password/reset'
      preLoaderRoute: typeof Char123LocaleChar125OtherAuthPasswordResetRouteImport
      parentRoute: typeof Char123LocaleChar125OtherRoute
    }
    '/{-$locale}/_other/auth/password/ask-reset': {
      id: '/{-$locale}/_other/auth/password/ask-reset'
      path: '/auth/password/ask-reset'
      fullPath: '/{-$locale}/auth/password/ask-reset'
      preLoaderRoute: typeof Char123LocaleChar125OtherAuthPasswordAskResetRouteImport
      parentRoute: typeof Char123LocaleChar125OtherRoute
    }
    '/{-$locale}/_other/auth/password/_layout': {
      id: '/{-$locale}/_other/auth/password/_layout'
      path: '/auth/password'
      fullPath: '/{-$locale}/auth/password'
      preLoaderRoute: typeof Char123LocaleChar125OtherAuthPasswordLayoutRouteImport
      parentRoute: typeof Char123LocaleChar125OtherRoute
    }
    '/{-$locale}/_other/auth/_not-authenticated/register': {
      id: '/{-$locale}/_other/auth/_not-authenticated/register'
      path: '/register'
      fullPath: '/{-$locale}/auth/register'
      preLoaderRoute: typeof Char123LocaleChar125OtherAuthNotAuthenticatedRegisterRouteImport
      parentRoute: typeof Char123LocaleChar125OtherAuthNotAuthenticatedRoute
    }
    '/{-$locale}/_other/auth/_not-authenticated/login': {
      id: '/{-$locale}/_other/auth/_not-authenticated/login'
      path: '/login'
      fullPath: '/{-$locale}/auth/login'
      preLoaderRoute: typeof Char123LocaleChar125OtherAuthNotAuthenticatedLoginRouteImport
      parentRoute: typeof Char123LocaleChar125OtherAuthNotAuthenticatedRoute
    }
    '/{-$locale}/_other/auth/_not-authenticated/2fa': {
      id: '/{-$locale}/_other/auth/_not-authenticated/2fa'
      path: '/2fa'
      fullPath: '/{-$locale}/auth/2fa'
      preLoaderRoute: typeof Char123LocaleChar125OtherAuthNotAuthenticated2faRouteImport
      parentRoute: typeof Char123LocaleChar125OtherAuthNotAuthenticatedRoute
    }
    '/{-$locale}/_dashboard/_editor/tags/$tagKey': {
      id: '/{-$locale}/_dashboard/_editor/tags/$tagKey'
      path: '/$tagKey'
      fullPath: '/{-$locale}/tags/$tagKey'
      preLoaderRoute: typeof Char123LocaleChar125DashboardEditorTagsTagKeyRouteImport
      parentRoute: typeof Char123LocaleChar125DashboardEditorTagsRoute
    }
    '/{-$locale}/_dashboard/_editor/_content/translate': {
      id: '/{-$locale}/_dashboard/_editor/_content/translate'
      path: '/translate'
      fullPath: '/{-$locale}/translate'
      preLoaderRoute: typeof Char123LocaleChar125DashboardEditorContentTranslateRouteImport
      parentRoute: typeof Char123LocaleChar125DashboardEditorRoute
    }
    '/{-$locale}/_dashboard/_editor/_content/editor': {
      id: '/{-$locale}/_dashboard/_editor/_content/editor'
      path: '/editor'
      fullPath: '/{-$locale}/editor'
      preLoaderRoute: typeof Char123LocaleChar125DashboardEditorContentEditorRouteImport
      parentRoute: typeof Char123LocaleChar125DashboardEditorRoute
    }
    '/{-$locale}/_dashboard/_editor/_content/dictionary': {
      id: '/{-$locale}/_dashboard/_editor/_content/dictionary'
      path: '/dictionary'
      fullPath: '/{-$locale}/dictionary'
      preLoaderRoute: typeof Char123LocaleChar125DashboardEditorContentDictionaryRouteImport
      parentRoute: typeof Char123LocaleChar125DashboardEditorRoute
    }
    '/{-$locale}/_dashboard/_admin/admin/users': {
      id: '/{-$locale}/_dashboard/_admin/admin/users'
      path: '/users'
      fullPath: '/{-$locale}/admin/users'
      preLoaderRoute: typeof Char123LocaleChar125DashboardAdminAdminUsersRouteImport
      parentRoute: typeof Char123LocaleChar125DashboardAdminAdminRoute
    }
    '/{-$locale}/_dashboard/_admin/admin/projects': {
      id: '/{-$locale}/_dashboard/_admin/admin/projects'
      path: '/projects'
      fullPath: '/{-$locale}/admin/projects'
      preLoaderRoute: typeof Char123LocaleChar125DashboardAdminAdminProjectsRouteImport
      parentRoute: typeof Char123LocaleChar125DashboardAdminAdminRoute
    }
    '/{-$locale}/_dashboard/_admin/admin/organizations': {
      id: '/{-$locale}/_dashboard/_admin/admin/organizations'
      path: '/organizations'
      fullPath: '/{-$locale}/admin/organizations'
      preLoaderRoute: typeof Char123LocaleChar125DashboardAdminAdminOrganizationsRouteImport
      parentRoute: typeof Char123LocaleChar125DashboardAdminAdminRoute
    }
    '/{-$locale}/_dashboard/_admin/admin/discussions': {
      id: '/{-$locale}/_dashboard/_admin/admin/discussions'
      path: '/discussions'
      fullPath: '/{-$locale}/admin/discussions'
      preLoaderRoute: typeof Char123LocaleChar125DashboardAdminAdminDiscussionsRouteImport
      parentRoute: typeof Char123LocaleChar125DashboardAdminAdminRoute
    }
    '/{-$locale}/_other/auth/_authenticated/password/change': {
      id: '/{-$locale}/_other/auth/_authenticated/password/change'
      path: '/password/change'
      fullPath: '/{-$locale}/auth/password/change'
      preLoaderRoute: typeof Char123LocaleChar125OtherAuthAuthenticatedPasswordChangeRouteImport
      parentRoute: typeof Char123LocaleChar125OtherAuthAuthenticatedRoute
    }
    '/{-$locale}/_dashboard/_editor/_content/dictionary/$dictionaryKey': {
      id: '/{-$locale}/_dashboard/_editor/_content/dictionary/$dictionaryKey'
      path: '/$dictionaryKey'
      fullPath: '/{-$locale}/dictionary/$dictionaryKey'
      preLoaderRoute: typeof Char123LocaleChar125DashboardEditorContentDictionaryDictionaryKeyRouteImport
      parentRoute: typeof Char123LocaleChar125DashboardEditorContentDictionaryRoute
    }
    '/{-$locale}/_dashboard/_admin/admin/users/$id': {
      id: '/{-$locale}/_dashboard/_admin/admin/users/$id'
      path: '/$id'
      fullPath: '/{-$locale}/admin/users/$id'
      preLoaderRoute: typeof Char123LocaleChar125DashboardAdminAdminUsersIdRouteImport
      parentRoute: typeof Char123LocaleChar125DashboardAdminAdminUsersRoute
    }
    '/{-$locale}/_dashboard/_admin/admin/projects/$id': {
      id: '/{-$locale}/_dashboard/_admin/admin/projects/$id'
      path: '/$id'
      fullPath: '/{-$locale}/admin/projects/$id'
      preLoaderRoute: typeof Char123LocaleChar125DashboardAdminAdminProjectsIdRouteImport
      parentRoute: typeof Char123LocaleChar125DashboardAdminAdminProjectsRoute
    }
    '/{-$locale}/_dashboard/_admin/admin/organizations/$id': {
      id: '/{-$locale}/_dashboard/_admin/admin/organizations/$id'
      path: '/$id'
      fullPath: '/{-$locale}/admin/organizations/$id'
      preLoaderRoute: typeof Char123LocaleChar125DashboardAdminAdminOrganizationsIdRouteImport
      parentRoute: typeof Char123LocaleChar125DashboardAdminAdminOrganizationsRoute
    }
  }
}

interface Char123LocaleChar125DashboardAdminAdminOrganizationsRouteChildren {
  Char123LocaleChar125DashboardAdminAdminOrganizationsIdRoute: typeof Char123LocaleChar125DashboardAdminAdminOrganizationsIdRoute
}

const Char123LocaleChar125DashboardAdminAdminOrganizationsRouteChildren: Char123LocaleChar125DashboardAdminAdminOrganizationsRouteChildren =
  {
    Char123LocaleChar125DashboardAdminAdminOrganizationsIdRoute:
      Char123LocaleChar125DashboardAdminAdminOrganizationsIdRoute,
  }

const Char123LocaleChar125DashboardAdminAdminOrganizationsRouteWithChildren =
  Char123LocaleChar125DashboardAdminAdminOrganizationsRoute._addFileChildren(
    Char123LocaleChar125DashboardAdminAdminOrganizationsRouteChildren,
  )

interface Char123LocaleChar125DashboardAdminAdminProjectsRouteChildren {
  Char123LocaleChar125DashboardAdminAdminProjectsIdRoute: typeof Char123LocaleChar125DashboardAdminAdminProjectsIdRoute
}

const Char123LocaleChar125DashboardAdminAdminProjectsRouteChildren: Char123LocaleChar125DashboardAdminAdminProjectsRouteChildren =
  {
    Char123LocaleChar125DashboardAdminAdminProjectsIdRoute:
      Char123LocaleChar125DashboardAdminAdminProjectsIdRoute,
  }

const Char123LocaleChar125DashboardAdminAdminProjectsRouteWithChildren =
  Char123LocaleChar125DashboardAdminAdminProjectsRoute._addFileChildren(
    Char123LocaleChar125DashboardAdminAdminProjectsRouteChildren,
  )

interface Char123LocaleChar125DashboardAdminAdminUsersRouteChildren {
  Char123LocaleChar125DashboardAdminAdminUsersIdRoute: typeof Char123LocaleChar125DashboardAdminAdminUsersIdRoute
}

const Char123LocaleChar125DashboardAdminAdminUsersRouteChildren: Char123LocaleChar125DashboardAdminAdminUsersRouteChildren =
  {
    Char123LocaleChar125DashboardAdminAdminUsersIdRoute:
      Char123LocaleChar125DashboardAdminAdminUsersIdRoute,
  }

const Char123LocaleChar125DashboardAdminAdminUsersRouteWithChildren =
  Char123LocaleChar125DashboardAdminAdminUsersRoute._addFileChildren(
    Char123LocaleChar125DashboardAdminAdminUsersRouteChildren,
  )

interface Char123LocaleChar125DashboardAdminAdminRouteChildren {
  Char123LocaleChar125DashboardAdminAdminDiscussionsRoute: typeof Char123LocaleChar125DashboardAdminAdminDiscussionsRoute
  Char123LocaleChar125DashboardAdminAdminOrganizationsRoute: typeof Char123LocaleChar125DashboardAdminAdminOrganizationsRouteWithChildren
  Char123LocaleChar125DashboardAdminAdminProjectsRoute: typeof Char123LocaleChar125DashboardAdminAdminProjectsRouteWithChildren
  Char123LocaleChar125DashboardAdminAdminUsersRoute: typeof Char123LocaleChar125DashboardAdminAdminUsersRouteWithChildren
}

const Char123LocaleChar125DashboardAdminAdminRouteChildren: Char123LocaleChar125DashboardAdminAdminRouteChildren =
  {
    Char123LocaleChar125DashboardAdminAdminDiscussionsRoute:
      Char123LocaleChar125DashboardAdminAdminDiscussionsRoute,
    Char123LocaleChar125DashboardAdminAdminOrganizationsRoute:
      Char123LocaleChar125DashboardAdminAdminOrganizationsRouteWithChildren,
    Char123LocaleChar125DashboardAdminAdminProjectsRoute:
      Char123LocaleChar125DashboardAdminAdminProjectsRouteWithChildren,
    Char123LocaleChar125DashboardAdminAdminUsersRoute:
      Char123LocaleChar125DashboardAdminAdminUsersRouteWithChildren,
  }

const Char123LocaleChar125DashboardAdminAdminRouteWithChildren =
  Char123LocaleChar125DashboardAdminAdminRoute._addFileChildren(
    Char123LocaleChar125DashboardAdminAdminRouteChildren,
  )

interface Char123LocaleChar125DashboardAdminRouteChildren {
  Char123LocaleChar125DashboardAdminAdminRoute: typeof Char123LocaleChar125DashboardAdminAdminRouteWithChildren
}

const Char123LocaleChar125DashboardAdminRouteChildren: Char123LocaleChar125DashboardAdminRouteChildren =
  {
    Char123LocaleChar125DashboardAdminAdminRoute:
      Char123LocaleChar125DashboardAdminAdminRouteWithChildren,
  }

const Char123LocaleChar125DashboardAdminRouteWithChildren =
  Char123LocaleChar125DashboardAdminRoute._addFileChildren(
    Char123LocaleChar125DashboardAdminRouteChildren,
  )

interface Char123LocaleChar125DashboardEditorTagsRouteChildren {
  Char123LocaleChar125DashboardEditorTagsTagKeyRoute: typeof Char123LocaleChar125DashboardEditorTagsTagKeyRoute
}

const Char123LocaleChar125DashboardEditorTagsRouteChildren: Char123LocaleChar125DashboardEditorTagsRouteChildren =
  {
    Char123LocaleChar125DashboardEditorTagsTagKeyRoute:
      Char123LocaleChar125DashboardEditorTagsTagKeyRoute,
  }

const Char123LocaleChar125DashboardEditorTagsRouteWithChildren =
  Char123LocaleChar125DashboardEditorTagsRoute._addFileChildren(
    Char123LocaleChar125DashboardEditorTagsRouteChildren,
  )

interface Char123LocaleChar125DashboardEditorContentDictionaryRouteChildren {
  Char123LocaleChar125DashboardEditorContentDictionaryDictionaryKeyRoute: typeof Char123LocaleChar125DashboardEditorContentDictionaryDictionaryKeyRoute
}

const Char123LocaleChar125DashboardEditorContentDictionaryRouteChildren: Char123LocaleChar125DashboardEditorContentDictionaryRouteChildren =
  {
    Char123LocaleChar125DashboardEditorContentDictionaryDictionaryKeyRoute:
      Char123LocaleChar125DashboardEditorContentDictionaryDictionaryKeyRoute,
  }

const Char123LocaleChar125DashboardEditorContentDictionaryRouteWithChildren =
  Char123LocaleChar125DashboardEditorContentDictionaryRoute._addFileChildren(
    Char123LocaleChar125DashboardEditorContentDictionaryRouteChildren,
  )

interface Char123LocaleChar125DashboardEditorRouteChildren {
  Char123LocaleChar125DashboardEditorTagsRoute: typeof Char123LocaleChar125DashboardEditorTagsRouteWithChildren
  Char123LocaleChar125DashboardEditorContentDictionaryRoute: typeof Char123LocaleChar125DashboardEditorContentDictionaryRouteWithChildren
  Char123LocaleChar125DashboardEditorContentEditorRoute: typeof Char123LocaleChar125DashboardEditorContentEditorRoute
  Char123LocaleChar125DashboardEditorContentTranslateRoute: typeof Char123LocaleChar125DashboardEditorContentTranslateRoute
}

const Char123LocaleChar125DashboardEditorRouteChildren: Char123LocaleChar125DashboardEditorRouteChildren =
  {
    Char123LocaleChar125DashboardEditorTagsRoute:
      Char123LocaleChar125DashboardEditorTagsRouteWithChildren,
    Char123LocaleChar125DashboardEditorContentDictionaryRoute:
      Char123LocaleChar125DashboardEditorContentDictionaryRouteWithChildren,
    Char123LocaleChar125DashboardEditorContentEditorRoute:
      Char123LocaleChar125DashboardEditorContentEditorRoute,
    Char123LocaleChar125DashboardEditorContentTranslateRoute:
      Char123LocaleChar125DashboardEditorContentTranslateRoute,
  }

const Char123LocaleChar125DashboardEditorRouteWithChildren =
  Char123LocaleChar125DashboardEditorRoute._addFileChildren(
    Char123LocaleChar125DashboardEditorRouteChildren,
  )

interface Char123LocaleChar125DashboardRouteChildren {
  Char123LocaleChar125DashboardAdminRoute: typeof Char123LocaleChar125DashboardAdminRouteWithChildren
  Char123LocaleChar125DashboardEditorRoute: typeof Char123LocaleChar125DashboardEditorRouteWithChildren
  Char123LocaleChar125DashboardOrganizationRoute: typeof Char123LocaleChar125DashboardOrganizationRoute
  Char123LocaleChar125DashboardProfileRoute: typeof Char123LocaleChar125DashboardProfileRoute
  Char123LocaleChar125DashboardProjectsRoute: typeof Char123LocaleChar125DashboardProjectsRoute
  Char123LocaleChar125DashboardIndexRoute: typeof Char123LocaleChar125DashboardIndexRoute
}

const Char123LocaleChar125DashboardRouteChildren: Char123LocaleChar125DashboardRouteChildren =
  {
    Char123LocaleChar125DashboardAdminRoute:
      Char123LocaleChar125DashboardAdminRouteWithChildren,
    Char123LocaleChar125DashboardEditorRoute:
      Char123LocaleChar125DashboardEditorRouteWithChildren,
    Char123LocaleChar125DashboardOrganizationRoute:
      Char123LocaleChar125DashboardOrganizationRoute,
    Char123LocaleChar125DashboardProfileRoute:
      Char123LocaleChar125DashboardProfileRoute,
    Char123LocaleChar125DashboardProjectsRoute:
      Char123LocaleChar125DashboardProjectsRoute,
    Char123LocaleChar125DashboardIndexRoute:
      Char123LocaleChar125DashboardIndexRoute,
  }

const Char123LocaleChar125DashboardRouteWithChildren =
  Char123LocaleChar125DashboardRoute._addFileChildren(
    Char123LocaleChar125DashboardRouteChildren,
  )

interface Char123LocaleChar125OtherAuthAuthenticatedRouteChildren {
  Char123LocaleChar125OtherAuthAuthenticatedPasswordChangeRoute: typeof Char123LocaleChar125OtherAuthAuthenticatedPasswordChangeRoute
}

const Char123LocaleChar125OtherAuthAuthenticatedRouteChildren: Char123LocaleChar125OtherAuthAuthenticatedRouteChildren =
  {
    Char123LocaleChar125OtherAuthAuthenticatedPasswordChangeRoute:
      Char123LocaleChar125OtherAuthAuthenticatedPasswordChangeRoute,
  }

const Char123LocaleChar125OtherAuthAuthenticatedRouteWithChildren =
  Char123LocaleChar125OtherAuthAuthenticatedRoute._addFileChildren(
    Char123LocaleChar125OtherAuthAuthenticatedRouteChildren,
  )

interface Char123LocaleChar125OtherAuthNotAuthenticatedRouteChildren {
  Char123LocaleChar125OtherAuthNotAuthenticated2faRoute: typeof Char123LocaleChar125OtherAuthNotAuthenticated2faRoute
  Char123LocaleChar125OtherAuthNotAuthenticatedLoginRoute: typeof Char123LocaleChar125OtherAuthNotAuthenticatedLoginRoute
  Char123LocaleChar125OtherAuthNotAuthenticatedRegisterRoute: typeof Char123LocaleChar125OtherAuthNotAuthenticatedRegisterRoute
}

const Char123LocaleChar125OtherAuthNotAuthenticatedRouteChildren: Char123LocaleChar125OtherAuthNotAuthenticatedRouteChildren =
  {
    Char123LocaleChar125OtherAuthNotAuthenticated2faRoute:
      Char123LocaleChar125OtherAuthNotAuthenticated2faRoute,
    Char123LocaleChar125OtherAuthNotAuthenticatedLoginRoute:
      Char123LocaleChar125OtherAuthNotAuthenticatedLoginRoute,
    Char123LocaleChar125OtherAuthNotAuthenticatedRegisterRoute:
      Char123LocaleChar125OtherAuthNotAuthenticatedRegisterRoute,
  }

const Char123LocaleChar125OtherAuthNotAuthenticatedRouteWithChildren =
  Char123LocaleChar125OtherAuthNotAuthenticatedRoute._addFileChildren(
    Char123LocaleChar125OtherAuthNotAuthenticatedRouteChildren,
  )

interface Char123LocaleChar125OtherRouteChildren {
  Char123LocaleChar125OtherOnboardingRoute: typeof Char123LocaleChar125OtherOnboardingRoute
  Char123LocaleChar125OtherPricingRoute: typeof Char123LocaleChar125OtherPricingRoute
  Char123LocaleChar125OtherAuthAuthenticatedRoute: typeof Char123LocaleChar125OtherAuthAuthenticatedRouteWithChildren
  Char123LocaleChar125OtherAuthNotAuthenticatedRoute: typeof Char123LocaleChar125OtherAuthNotAuthenticatedRouteWithChildren
  Char123LocaleChar125OtherAuthCliLoginRoute: typeof Char123LocaleChar125OtherAuthCliLoginRoute
  Char123LocaleChar125OtherAuthPasswordLayoutRoute: typeof Char123LocaleChar125OtherAuthPasswordLayoutRoute
  Char123LocaleChar125OtherAuthPasswordAskResetRoute: typeof Char123LocaleChar125OtherAuthPasswordAskResetRoute
  Char123LocaleChar125OtherAuthPasswordResetRoute: typeof Char123LocaleChar125OtherAuthPasswordResetRoute
}

const Char123LocaleChar125OtherRouteChildren: Char123LocaleChar125OtherRouteChildren =
  {
    Char123LocaleChar125OtherOnboardingRoute:
      Char123LocaleChar125OtherOnboardingRoute,
    Char123LocaleChar125OtherPricingRoute:
      Char123LocaleChar125OtherPricingRoute,
    Char123LocaleChar125OtherAuthAuthenticatedRoute:
      Char123LocaleChar125OtherAuthAuthenticatedRouteWithChildren,
    Char123LocaleChar125OtherAuthNotAuthenticatedRoute:
      Char123LocaleChar125OtherAuthNotAuthenticatedRouteWithChildren,
    Char123LocaleChar125OtherAuthCliLoginRoute:
      Char123LocaleChar125OtherAuthCliLoginRoute,
    Char123LocaleChar125OtherAuthPasswordLayoutRoute:
      Char123LocaleChar125OtherAuthPasswordLayoutRoute,
    Char123LocaleChar125OtherAuthPasswordAskResetRoute:
      Char123LocaleChar125OtherAuthPasswordAskResetRoute,
    Char123LocaleChar125OtherAuthPasswordResetRoute:
      Char123LocaleChar125OtherAuthPasswordResetRoute,
  }

const Char123LocaleChar125OtherRouteWithChildren =
  Char123LocaleChar125OtherRoute._addFileChildren(
    Char123LocaleChar125OtherRouteChildren,
  )

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125SplatRoute: typeof Char123LocaleChar125SplatRoute
  Char123LocaleChar125404Route: typeof Char123LocaleChar125404Route
  Char123LocaleChar125DashboardRoute: typeof Char123LocaleChar125DashboardRouteWithChildren
  Char123LocaleChar125OtherRoute: typeof Char123LocaleChar125OtherRouteWithChildren
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125SplatRoute: Char123LocaleChar125SplatRoute,
    Char123LocaleChar125404Route: Char123LocaleChar125404Route,
    Char123LocaleChar125DashboardRoute:
      Char123LocaleChar125DashboardRouteWithChildren,
    Char123LocaleChar125OtherRoute: Char123LocaleChar125OtherRouteWithChildren,
  }

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
