import { type Dictionary, enu, insert, t } from 'intlayer';

const githubRepositoryLinkContent = {
  key: 'github-repository-link',
  content: {
    authentication: {
      failed: t({
        en: 'GitHub authentication failed:',
        'en-GB': 'GitHub authentication failed:',
        ru: 'Ошибка аутентификации GitHub:',
        ja: 'GitHub認証に失敗しました:',
        fr: "Échec de l'authentification GitHub :",
        ko: 'GitHub 인증 실패:',
        zh: 'GitHub 身份验证失败：',
        es: 'Error de autenticación de GitHub:',
        de: 'GitHub-Authentifizierung fehlgeschlagen:',
        ar: 'فشل المصادقة على GitHub:',
        it: 'Autenticazione GitHub non riuscita:',
        pt: 'Falha na autenticação do GitHub:',
        hi: 'GitHub प्रमाणीकरण विफल:',
        tr: 'GitHub kimlik doğrulaması başarısız:',
        pl: 'Uwierzytelnianie GitHub nie powiodło się:',
        id: 'Autentikasi GitHub gagal:',
        vi: 'Xác thực GitHub thất bại:',
      }),
      clientIdNotConfigured: t({
        en: 'GitHub Client ID is not configured',
        'en-GB': 'GitHub Client ID is not configured',
        ru: 'GitHub Client ID не настроен',
        ja: 'GitHub Client IDが設定されていません',
        fr: "L'ID client GitHub n'est pas configuré",
        ko: 'GitHub Client ID가 구성되지 않았습니다',
        zh: '未配置 GitHub Client ID',
        es: 'El ID de cliente de GitHub no está configurado',
        de: 'GitHub Client-ID ist nicht konfiguriert',
        ar: 'معرف عميل GitHub غير مُكوّن',
        it: "L'ID client di GitHub non è configurato",
        pt: 'O ID do cliente do GitHub não está configurado',
        hi: 'GitHub Client ID कॉन्फ़िगर नहीं है',
        tr: 'GitHub Client ID yapılandırılmamış',
        pl: 'GitHub Client ID nie jest skonfigurowany',
        id: 'ID Klien GitHub tidak dikonfigurasi',
        vi: 'ID khách hàng GitHub chưa được cấu hình',
      }),
    },
    repository: {
      connectTitle: t({
        en: 'Connect GitHub Repository',
        'en-GB': 'Connect GitHub Repository',
        ru: 'Подключить репозиторий GitHub',
        ja: 'GitHubリポジトリを接続',
        fr: 'Connecter le dépôt GitHub',
        ko: 'GitHub 저장소 연결',
        zh: '连接 GitHub 仓库',
        es: 'Conectar repositorio de GitHub',
        de: 'GitHub-Repository verbinden',
        ar: 'ربط مستودع GitHub',
        it: 'Connetti repository GitHub',
        pt: 'Conectar repositório do GitHub',
        hi: 'GitHub रिपॉजिटरी कनेक्ट करें',
        tr: 'GitHub Deposu Bağla',
        pl: 'Połącz repozytorium GitHub',
        id: 'Hubungkan Repositori GitHub',
        vi: 'Kết nối kho lưu trữ GitHub',
      }),
      connectDescription: t({
        en: 'Connect your GitHub repository to access codebase files and set up Intlayer configuration.',
        'en-GB':
          'Connect your GitHub repository to access codebase files and set up Intlayer configuration.',
        ru: 'Подключите репозиторий GitHub для доступа к файлам кодовой базы и настройки конфигурации Intlayer.',
        ja: 'GitHubリポジトリを接続して、コードベースファイルにアクセスし、Intlayer設定を行います。',
        fr: 'Connectez votre dépôt GitHub pour accéder aux fichiers du code source et configurer Intlayer.',
        ko: 'GitHub 저장소를 연결하여 코드베이스 파일에 액세스하고 Intlayer 구성을 설정합니다.',
        zh: '连接您的 GitHub 仓库以访问代码库文件并设置 Intlayer 配置。',
        es: 'Conecta tu repositorio de GitHub para acceder a los archivos del código fuente y configurar Intlayer.',
        de: 'Verbinden Sie Ihr GitHub-Repository, um auf Codebasis-Dateien zuzugreifen und die Intlayer-Konfiguration einzurichten.',
        ar: 'قم بربط مستودع GitHub الخاص بك للوصول إلى ملفات قاعدة الكود وإعداد تكوين Intlayer.',
        it: 'Connetti il tuo repository GitHub per accedere ai file della codebase e configurare Intlayer.',
        pt: 'Conecte seu repositório do GitHub para acessar arquivos da base de código e configurar o Intlayer.',
        hi: 'कोडबेस फ़ाइलों तक पहुंचने और Intlayer कॉन्फ़िगरेशन सेट करने के लिए अपने GitHub रिपॉजिटरी को कनेक्ट करें।',
        tr: 'Kod tabanı dosyalarına erişmek ve Intlayer yapılandırmasını ayarlamak için GitHub deponuzu bağlayın.',
        pl: 'Połącz swoje repozytorium GitHub, aby uzyskać dostęp do plików bazy kodu i skonfigurować Intlayer.',
        id: 'Hubungkan repositori GitHub Anda untuk mengakses file codebase dan mengatur konfigurasi Intlayer.',
        vi: 'Kết nối kho lưu trữ GitHub của bạn để truy cập các tệp codebase và thiết lập cấu hình Intlayer.',
      }),
      projectsFound: insert(
        enu({
          1: t({
            en: '{{count}} project found',
            'en-GB': '{{count}} project found',
            ru: 'найден {{count}} проект',
            ja: '{{count}} プロジェクトが見つかりました',
            fr: '{{count}} projet trouvé',
            ko: '{{count}}개 프로젝트 발견',
            zh: '找到 {{count}} 个项目',
            es: '{{count}} proyecto encontrado',
            de: '{{count}} Projekt gefunden',
            ar: 'تم العثور على {{count}} مشروع',
            it: '{{count}} progetto trovato',
            pt: '{{count}} projeto encontrado',
            hi: '{{count}} प्रोजेक्ट मिले',
            tr: '{{count}} proje bulundu',
            pl: 'znaleziono {{count}} projekt',
            id: '{{count}} proyek ditemukan',
            vi: '{{count}} dự án được tìm thấy',
          }),
          '>1': t({
            en: '{{count}} projects found',
            'en-GB': '{{count}} projects found',
            ru: 'найдено {{count}} проектов',
            ja: '{{count}} プロジェクトが見つかりました',
            fr: '{{count}} projets trouvés',
            ko: '{{count}}개 프로젝트 발견',
            zh: '找到 {{count}} 个项目',
            es: '{{count}} proyectos encontrados',
            de: '{{count}} Projekte gefunden',
            ar: 'تم العثور على {{count}} مشاريع',
            it: '{{count}} progetti trovati',
            pt: '{{count}} projetos encontrados',
            hi: '{{count}} प्रोजेक्ट मिले',
            tr: '{{count}} proje bulundu',
            pl: 'znaleziono {{count}} projektów',
            id: '{{count}} proyek ditemukan',
            vi: '{{count}} dự án được tìm thấy',
          }),
        })
      ),
      load: t({
        en: 'Load Repositories',
        'en-GB': 'Load Repositories',
        ru: 'Загрузить репозитории',
        ja: 'リポジトリを読み込む',
        fr: 'Charger les dépôts',
        ko: '저장소 로드',
        zh: '加载仓库',
        es: 'Cargar repositorios',
        de: 'Repositorys laden',
        ar: 'تحميل المستودعات',
        it: 'Carica repository',
        pt: 'Carregar repositórios',
        hi: 'रिपॉजिटरी लोड करें',
        tr: 'Depoları Yükle',
        pl: 'Załaduj repozytoria',
        id: 'Muat Repositori',
        vi: 'Tải kho lưu trữ',
      }),
      select: t({
        en: 'Select a repository',
        'en-GB': 'Select a repository',
        ru: 'Выберите репозиторий',
        ja: 'リポジトリを選択',
        fr: 'Sélectionner un dépôt',
        ko: '저장소 선택',
        zh: '选择一个仓库',
        es: 'Seleccionar un repositorio',
        de: 'Repository auswählen',
        ar: 'اختر مستودعًا',
        it: 'Seleziona un repository',
        pt: 'Selecionar um repositório',
        hi: 'एक रिपॉजिटरी चुनें',
        tr: 'Bir depo seçin',
        pl: 'Wybierz repozytorium',
        id: 'Pilih repositori',
        vi: 'Chọn một kho lưu trữ',
      }),
      loading: t({
        en: 'Loading repositories...',
        'en-GB': 'Loading repositories...',
        ru: 'Загрузка репозиториев...',
        ja: 'リポジトリを読み込み中...',
        fr: 'Chargement des dépôts...',
        ko: '저장소 로드 중...',
        zh: '正在加载仓库...',
        es: 'Cargando repositorios...',
        de: 'Repositorys werden geladen...',
        ar: 'جارٍ تحميل المستودعات...',
        it: 'Caricamento repository...',
        pt: 'Carregando repositórios...',
        hi: 'रिपॉजिटरी लोड हो रही हैं...',
        tr: 'Depolar yükleniyor...',
        pl: 'Ładowanie repozytoriów...',
        id: 'Memuat repositori...',
        vi: 'Đang tải kho lưu trữ...',
      }),
    },
    status: {
      checking: t({
        en: 'Checking for intlayer.config.ts...',
        'en-GB': 'Checking for intlayer.config.ts...',
        ru: 'Проверка наличия intlayer.config.ts...',
        ja: 'intlayer.config.tsを確認中...',
        fr: 'Vérification de intlayer.config.ts...',
        ko: 'intlayer.config.ts 확인 중...',
        zh: '正在检查 intlayer.config.ts...',
        es: 'Verificando intlayer.config.ts...',
        de: 'Suche nach intlayer.config.ts...',
        ar: 'جارٍ التحقق من intlayer.config.ts...',
        it: 'Verifica di intlayer.config.ts...',
        pt: 'Verificando intlayer.config.ts...',
        hi: 'intlayer.config.ts की जांच की जा रही है...',
        tr: 'intlayer.config.ts kontrol ediliyor...',
        pl: 'Sprawdzanie intlayer.config.ts...',
        id: 'Memeriksa intlayer.config.ts...',
        vi: 'Đang kiểm tra intlayer.config.ts...',
      }),
      configFound: t({
        en: 'intlayer.config.ts found',
        'en-GB': 'intlayer.config.ts found',
        ru: 'intlayer.config.ts найден',
        ja: 'intlayer.config.tsが見つかりました',
        fr: 'intlayer.config.ts trouvé',
        ko: 'intlayer.config.ts 찾음',
        zh: '找到 intlayer.config.ts',
        es: 'intlayer.config.ts encontrado',
        de: 'intlayer.config.ts gefunden',
        ar: 'تم العثور على intlayer.config.ts',
        it: 'intlayer.config.ts trovato',
        pt: 'intlayer.config.ts encontrado',
        hi: 'intlayer.config.ts मिल गया',
        tr: 'intlayer.config.ts bulundu',
        pl: 'Znaleziono intlayer.config.ts',
        id: 'intlayer.config.ts ditemukan',
        vi: 'Đã tìm thấy intlayer.config.ts',
      }),
      configNotFound: t({
        en: 'intlayer.config.ts not found',
        'en-GB': 'intlayer.config.ts not found',
        ru: 'intlayer.config.ts не найден',
        ja: 'intlayer.config.tsが見つかりません',
        fr: 'intlayer.config.ts introuvable',
        ko: 'intlayer.config.ts를 찾을 수 없음',
        zh: '未找到 intlayer.config.ts',
        es: 'intlayer.config.ts no encontrado',
        de: 'intlayer.config.ts nicht gefunden',
        ar: 'لم يتم العثور على intlayer.config.ts',
        it: 'intlayer.config.ts non trovato',
        pt: 'intlayer.config.ts não encontrado',
        hi: 'intlayer.config.ts नहीं मिला',
        tr: 'intlayer.config.ts bulunamadı',
        pl: 'Nie znaleziono intlayer.config.ts',
        id: 'intlayer.config.ts tidak ditemukan',
        vi: 'Không tìm thấy intlayer.config.ts',
      }),
      connectedTo: t({
        en: 'Connected to',
        'en-GB': 'Connected to',
        ru: 'Подключено к',
        ja: '接続先:',
        fr: 'Connecté à',
        ko: '연결됨:',
        zh: '已连接到',
        es: 'Conectado a',
        de: 'Verbunden mit',
        ar: 'متصل بـ',
        it: 'Connesso a',
        pt: 'Conectado a',
        hi: 'से जुड़ा हुआ',
        tr: 'Bağlandı:',
        pl: 'Połączono z',
        id: 'Terhubung ke',
        vi: 'Đã kết nối với',
      }),
    },
    actions: {
      connect: t({
        en: 'Connect GitHub',
        'en-GB': 'Connect GitHub',
        ru: 'Подключить GitHub',
        ja: 'GitHubを接続',
        fr: 'Connecter GitHub',
        ko: 'GitHub 연결',
        zh: '连接 GitHub',
        es: 'Conectar GitHub',
        de: 'GitHub verbinden',
        ar: 'ربط GitHub',
        it: 'Connetti GitHub',
        pt: 'Conectar GitHub',
        hi: 'GitHub कनेक्ट करें',
        tr: 'GitHub Bağla',
        pl: 'Połącz GitHub',
        id: 'Hubungkan GitHub',
        vi: 'Kết nối GitHub',
      }),
      cancel: t({
        en: 'Cancel',
        'en-GB': 'Cancel',
        ru: 'Отмена',
        ja: 'キャンセル',
        fr: 'Annuler',
        ko: '취소',
        zh: '取消',
        es: 'Cancelar',
        de: 'Abbrechen',
        ar: 'إلغاء',
        it: 'Annulla',
        pt: 'Cancelar',
        hi: 'रद्द करें',
        tr: 'İptal',
        pl: 'Anuluj',
        id: 'Batal',
        vi: 'Hủy',
      }),
      useThisFile: t({
        en: 'Use this configuration',
        'en-GB': 'Use this configuration',
        ru: 'Использовать эту конфигурацию',
        ja: 'この設定を使用',
        fr: 'Utiliser cette configuration',
        ko: '이 구성 사용',
        zh: '使用此配置',
        es: 'Usar esta configuración',
        de: 'Diese Konfiguration verwenden',
        ar: 'استخدم هذا التكوين',
        it: 'Usa questa configurazione',
        pt: 'Usar esta configuração',
        hi: 'इस कॉन्फ़िगरेशन का उपयोग करें',
        tr: 'Bu yapılandırmayı kullan',
        pl: 'Użyj tej konfiguracji',
        id: 'Gunakan konfigurasi ini',
        vi: 'Sử dụng cấu hình này',
      }),
      disconnect: t({
        en: 'Disconnect',
        'en-GB': 'Disconnect',
        ru: 'Отключить',
        ja: '切断',
        fr: 'Déconnecter',
        ko: '연결 해제',
        zh: '断开连接',
        es: 'Desconectar',
        de: 'Trennen',
        ar: 'قطع الاتصال',
        it: 'Disconnetti',
        pt: 'Desconectar',
        hi: 'डिस्कनेक्ट करें',
        tr: 'Bağlantıyı Kes',
        pl: 'Rozłącz',
        id: 'Putuskan koneksi',
        vi: 'Ngắt kết nối',
      }),
      loadConfig: t({
        en: 'View Configuration',
        'en-GB': 'View Configuration',
        ru: 'Просмотр конфигурации',
        ja: '設定を表示',
        fr: 'Voir la configuration',
        ko: '구성 보기',
        zh: '查看配置',
        es: 'Ver configuración',
        de: 'Konfiguration anzeigen',
        ar: 'عرض التكوين',
        it: 'Visualizza configurazione',
        pt: 'Ver configuração',
        hi: 'कॉन्फ़िगरेशन देखें',
        tr: 'Yapılandırmayı Görüntüle',
        pl: 'Wyświetl konfigurację',
        id: 'Lihat Konfigurasi',
        vi: 'Xem cấu hình',
      }),
      import: t({
        en: 'Import',
        'en-GB': 'Import',
        ru: 'Импорт',
        ja: 'インポート',
        fr: 'Importer',
        ko: '가져오기',
        zh: '导入',
        es: 'Importar',
        de: 'Importieren',
        ar: 'استيراد',
        it: 'Importa',
        pt: 'Importar',
        hi: 'आयात करें',
        tr: 'İçe Aktar',
        pl: 'Importuj',
        id: 'Impor',
        vi: 'Nhập khẩu',
      }),
    },
    modal: {
      confirmTitle: t({
        en: 'Confirm Configuration',
        'en-GB': 'Confirm Configuration',
        ru: 'Подтвердить конфигурацию',
        ja: '設定を確認',
        fr: 'Confirmer la configuration',
        ko: '구성 확인',
        zh: '确认配置',
        es: 'Confirmar configuración',
        de: 'Konfiguration bestätigen',
        ar: 'تأكيد التكوين',
        it: 'Conferma configurazione',
        pt: 'Confirmar configuração',
        hi: 'कॉन्फ़िगरेशन की पुष्टि करें',
        tr: 'Yapılandırmayı Onayla',
        pl: 'Potwierdź konfigurację',
        id: 'Konfirmasi Konfigurasi',
        vi: 'Xác nhận cấu hình',
      }),
      selectConfigTitle: t({
        en: 'Select Configuration File',
        'en-GB': 'Select Configuration File',
        ru: 'Выберите файл конфигурации',
        ja: '設定ファイルを選択',
        fr: 'Sélectionner le fichier de configuration',
        ko: '구성 파일 선택',
        zh: '选择配置文件',
        es: 'Seleccionar archivo de configuración',
        de: 'Konfigurationsdatei auswählen',
        ar: 'اختر ملف التكوين',
        it: 'Seleziona file di configurazione',
        pt: 'Selecionar arquivo de configuração',
        hi: 'कॉन्फ़िगरेशन फ़ाइल चुनें',
        tr: 'Yapılandırma Dosyası Seç',
        pl: 'Wybierz plik konfiguracyjny',
        id: 'Pilih File Konfigurasi',
        vi: 'Chọn tệp cấu hình',
      }),
      selectConfigDescription: t({
        en: 'Multiple Intlayer configuration files were detected in',
        'en-GB': 'Multiple Intlayer configuration files were detected in',
        ru: 'Обнаружено несколько файлов конфигурации Intlayer в',
        ja: '複数のIntlayer設定ファイルが検出されました',
        fr: 'Plusieurs fichiers de configuration Intlayer ont été détectés dans',
        ko: '여러 개의 Intlayer 구성 파일이 감지되었습니다',
        zh: '检测到多个 Intlayer 配置文件',
        es: 'Se detectaron varios archivos de configuración de Intlayer en',
        de: 'Mehrere Intlayer-Konfigurationsdateien wurden erkannt in',
        ar: 'تم اكتشاف عدة ملفات تكوين Intlayer في',
        it: 'Sono stati rilevati più file di configurazione Intlayer in',
        pt: 'Vários arquivos de configuração do Intlayer foram detectados em',
        hi: 'कई Intlayer कॉन्फ़िगरेशन फ़ाइलें पाई गईं',
        tr: 'Birden fazla Intlayer yapılandırma dosyası tespit edildi',
        pl: 'Wykryto wiele plików konfiguracyjnych Intlayer w',
        id: 'Beberapa file konfigurasi Intlayer terdeteksi di',
        vi: 'Nhiều tệp cấu hình Intlayer đã được phát hiện trong',
      }),
      selectConfigDescriptionEnd: t({
        en: '. Please select the one you want to use for this project.',
        'en-GB': '. Please select the one you want to use for this project.',
        ru: '. Пожалуйста, выберите тот, который вы хотите использовать для этого проекта.',
        ja: '。このプロジェクトで使用するものを選択してください。',
        fr: '. Veuillez sélectionner celui que vous souhaitez utiliser pour ce projet.',
        ko: '. 이 프로젝트에 사용할 파일을 선택하세요.',
        zh: '。请选择要用于此项目的文件。',
        es: '. Por favor, selecciona el que quieres usar para este proyecto.',
        de: '. Bitte wählen Sie die aus, die Sie für dieses Projekt verwenden möchten.',
        ar: '. يرجى اختيار الملف الذي تريد استخدامه لهذا المشروع.',
        it: '. Seleziona quello che vuoi utilizzare per questo progetto.',
        pt: '. Por favor, selecione o que deseja usar para este projeto.',
        hi: '। कृपया इस प्रोजेक्ट के लिए उपयोग करने के लिए एक चुनें।',
        tr: '. Lütfen bu proje için kullanmak istediğinizi seçin.',
        pl: '. Proszę wybrać ten, którego chcesz użyć w tym projekcie.',
        id: '. Silakan pilih yang ingin Anda gunakan untuk proyek ini.',
        vi: '. Vui lòng chọn tệp bạn muốn sử dụng cho dự án này.',
      }),
      viewConfigTitle: t({
        en: 'Configuration',
        'en-GB': 'Configuration',
        ru: 'Конфигурация',
        ja: '設定',
        fr: 'Configuration',
        ko: '구성',
        zh: '配置',
        es: 'Configuración',
        de: 'Konfiguration',
        ar: 'التكوين',
        it: 'Configurazione',
        pt: 'Configuração',
        hi: 'कॉन्फ़िगरेशन',
        tr: 'Yapılandırma',
        pl: 'Konfiguracja',
        id: 'Konfigurasi',
        vi: 'Cấu hình',
      }),
      failedToLoad: t({
        en: 'Failed to load content',
        'en-GB': 'Failed to load content',
        ru: 'Не удалось загрузить содержимое',
        ja: 'コンテンツの読み込みに失敗しました',
        fr: 'Échec du chargement du contenu',
        ko: '콘텐츠를 불러오지 못했습니다',
        zh: '加载内容失败',
        es: 'Error al cargar el contenido',
        de: 'Inhalt konnte nicht geladen werden',
        ar: 'فشل تحميل المحتوى',
        it: 'Impossibile caricare il contenuto',
        pt: 'Falha ao carregar o conteúdo',
        hi: 'सामग्री लोड करने में विफल',
        tr: 'İçerik yüklenemedi',
        pl: 'Nie udało się załadować zawartości',
        id: 'Gagal memuat konten',
        vi: 'Không thể tải nội dung',
      }),
      back: t({
        en: 'Back',
        'en-GB': 'Back',
        ru: 'Назад',
        ja: '戻る',
        fr: 'Retour',
        ko: '뒤로',
        zh: '返回',
        es: 'Atrás',
        de: 'Zurück',
        ar: 'رجوع',
        it: 'Indietro',
        pt: 'Voltar',
        hi: 'वापस',
        tr: 'Geri',
        pl: 'Wstecz',
        id: 'Kembali',
        vi: 'Quay lại',
      }),
      close: t({
        en: 'Close',
        'en-GB': 'Close',
        ru: 'Закрыть',
        ja: '閉じる',
        fr: 'Fermer',
        ko: '닫기',
        zh: '关闭',
        es: 'Cerrar',
        de: 'Schließen',
        ar: 'إغلاق',
        it: 'Chiudi',
        pt: 'Fechar',
        hi: 'बंद करें',
        tr: 'Kapat',
        pl: 'Zamknij',
        id: 'Tutup',
        vi: 'Đóng',
      }),
    },
    labels: {
      branch: t({
        en: 'Branch:',
        'en-GB': 'Branch:',
        ru: 'Ветка:',
        ja: 'ブランチ:',
        fr: 'Branche :',
        ko: '브랜치:',
        zh: '分支：',
        es: 'Rama:',
        de: 'Branch:',
        ar: 'الفرع:',
        it: 'Ramo:',
        pt: 'Ramificação:',
        hi: 'शाखा:',
        tr: 'Dal:',
        pl: 'Gałąź:',
        id: 'Cabang:',
        vi: 'Nhánh:',
      }),
    },
  },
} satisfies Dictionary;

export default githubRepositoryLinkContent;
