import { type Dictionary, t } from 'intlayer';

const auditSectionContent = {
  key: 'audit-section',
  content: {
    title: t({
      en: 'Test your multilingual setup',
      ru: 'Проверьте свою многоязычную настройку',
      ja: '多言語設定をテストしましょう',
      fr: 'Testez votre configuration multilingue',
      ko: '다국어 설정을 테스트하세요',
      zh: '测试您的多语言设置',
      es: 'Pruebe su configuración multilingüe',
      de: 'Testen Sie Ihre mehrsprachige Einrichtung',
      ar: 'اختبر إعدادات التعدد اللغوي الخاصة بك',
      it: 'Verifica la tua configurazione multilingue',
      'en-GB': 'Test your multilingual setup',
      pt: 'Teste sua configuração multilingue',
      hi: 'अपनी बहुभाषी सेटअप का परीक्षण करें',
      tr: 'Çok dilli kurulumunuzu test edin',
      pl: 'Przetestuj swoją konfigurację wielojęzyczną',
      id: 'Uji pengaturan multibahasa Anda',
      vi: 'Kiểm tra cài đặt đa ngôn ngữ của bạn',
    }),
    placeholder: t({
      en: 'Enter a domain or website',
      ru: 'Введите домен или веб-сайт',
      ja: 'ドメインまたはウェブサイトを入力',
      fr: 'Entrez un domaine ou un site web',
      ko: '도메인 또는 웹사이트를 입력하세요',
      zh: '输入域名或网站',
      es: 'Introduce un dominio o sitio web',
      de: 'Geben Sie eine Domain oder Website ein',
      ar: 'أدخل نطاقًا أو موقعًا إلكترونيًا',
      it: 'Inserisci un dominio o sito web',
      'en-GB': 'Enter a domain or website',
      pt: 'Digite um domínio ou site',
      hi: 'डोमेन या वेबसाइट दर्ज करें',
      tr: 'Bir alan adı veya web sitesi girin',
      pl: 'Wpisz domenę lub stronę internetową',
      id: 'Masukkan domain atau situs web',
      vi: 'Nhập tên miền hoặc trang web',
    }),
    submitLabel: t({
      en: 'Submit audit',
      ru: 'Отправить аудит',
      ja: '監査を送信',
      fr: 'Lancer l’audit',
      ko: '감사 제출',
      zh: '提交审核',
      es: 'Enviar auditoría',
      de: 'Audit einreichen',
      ar: 'إرسال التدقيق',
      it: 'Invia audit',
      'en-GB': 'Submit audit',
      pt: 'Enviar auditoria',
      hi: 'ऑडिट सबमिट करें',
      tr: 'Denetimi gönder',
      pl: 'Prześlij audyt',
      id: 'Kirim audit',
      vi: 'Gửi kiểm tra',
    }),
  },
  title: 'Audit section',
  description:
    'Dictionary for the audit section on the landing page that lets users submit a domain for audit.',
  tags: ['landing page', 'audit', 'multilingual'],
} satisfies Dictionary;

export default auditSectionContent;
