import { type Dictionary, t } from 'intlayer';

const reviewerFiltersContent = {
  key: 'reviewer-filters',
  content: {
    filters: t({
      en: 'Filters',
      fr: 'Filtres',
      es: 'Filtros',
      'en-GB': 'Filters',
      de: 'Filter',
      ja: 'フィルター',
      ko: '필터',
      zh: '筛选',
      it: 'Filtri',
      pt: 'Filtros',
      hi: 'फ़िल्टर',
      ar: 'تصفية',
      ru: 'Фильтры',
      tr: 'Filtreler',
      pl: 'Filtry',
      id: 'Filter',
      vi: 'Bộ lọc',
      uk: 'Фільтри',
    }),

    sourceLanguage: t({
      en: 'Source language',
      fr: 'Langue source',
      es: 'Idioma de origen',
      'en-GB': 'Source language',
      de: 'Quellsprache',
      ja: 'ソース言語',
      ko: '원본 언어',
      zh: '源语言',
      it: 'Lingua sorgente',
      pt: 'Idioma de origem',
      hi: 'स्रोत भाषा',
      ar: 'اللغة المصدر',
      ru: 'Исходный язык',
      tr: 'Kaynak dil',
      pl: 'Język źródłowy',
      id: 'Bahasa sumber',
      vi: 'Ngôn ngữ nguồn',
      uk: 'Мова джерела',
    }),

    targetLanguage: t({
      en: 'Target language',
      fr: 'Langue cible',
      es: 'Idioma de destino',
      'en-GB': 'Target language',
      de: 'Zielsprache',
      ja: 'ターゲット言語',
      ko: '대상 언어',
      zh: '目标语言',
      it: 'Lingua di destinazione',
      pt: 'Idioma de destino',
      hi: 'लक्ष्य भाषा',
      ar: 'اللغة الهدف',
      ru: 'Целевой язык',
      tr: 'Hedef dil',
      pl: 'Język docelowy',
      id: 'Bahasa target',
      vi: 'Ngôn ngữ đích',
      uk: 'Цільова мова',
    }),

    minRating: t({
      en: 'Min rating',
      fr: 'Note minimale',
      es: 'Calificación mínima',
      'en-GB': 'Min rating',
      de: 'Mindestbewertung',
      ja: '最低評価',
      ko: '최소 평점',
      zh: '最低评分',
      it: 'Valutazione minima',
      pt: 'Avaliação mínima',
      hi: 'न्यूनतम रेटिंग',
      ar: 'الحد الأدنى للتقييم',
      ru: 'Мин. рейтинг',
      tr: 'Min. puan',
      pl: 'Min. ocena',
      id: 'Penilaian minimum',
      vi: 'Đánh giá tối thiểu',
      uk: 'Мін. рейтинг',
    }),

    any: t({
      en: 'Any',
      fr: 'Tous',
      es: 'Cualquiera',
      'en-GB': 'Any',
      de: 'Beliebig',
      ja: 'すべて',
      ko: '모두',
      zh: '任意',
      it: 'Qualsiasi',
      pt: 'Qualquer',
      hi: 'कोई भी',
      ar: 'أي',
      ru: 'Любой',
      tr: 'Herhangi biri',
      pl: 'Dowolna',
      id: 'Apa saja',
      vi: 'Bất kỳ',
      uk: 'Будь-який',
    }),

    priceRange: t({
      en: 'Price range / hr ($)',
      fr: 'Fourchette de prix / h ($)',
      es: 'Rango de precio / h ($)',
      'en-GB': 'Price range / hr ($)',
      de: 'Preisspanne / Std. ($)',
      ja: '料金範囲 / 時間 ($)',
      ko: '가격 범위 / 시간 ($)',
      zh: '价格区间 / 小时 ($)',
      it: 'Fascia di prezzo / ora ($)',
      pt: 'Faixa de preço / h ($)',
      hi: 'मूल्य सीमा / घंटा ($)',
      ar: 'نطاق السعر / ساعة ($)',
      ru: 'Диапазон цен / ч ($)',
      tr: 'Fiyat aralığı / sa ($)',
      pl: 'Zakres cen / godz. ($)',
      id: 'Rentang harga / jam ($)',
      vi: 'Khoảng giá / giờ ($)',
      uk: 'Діапазон цін / год ($)',
    }),

    clearFilters: t({
      en: 'Clear filters',
      fr: 'Effacer les filtres',
      es: 'Limpiar filtros',
      'en-GB': 'Clear filters',
      de: 'Filter zurücksetzen',
      ja: 'フィルターをクリア',
      ko: '필터 초기화',
      zh: '清除筛选',
      it: 'Cancella filtri',
      pt: 'Limpar filtros',
      hi: 'फ़िल्टर साफ़ करें',
      ar: 'مسح الفلاتر',
      ru: 'Сбросить фильтры',
      tr: 'Filtreleri temizle',
      pl: 'Wyczyść filtry',
      id: 'Hapus filter',
      vi: 'Xóa bộ lọc',
      uk: 'Скинути фільтри',
    }),

    egEn: t({
      en: 'e.g. en',
      fr: 'ex. en',
      es: 'por ej. en',
      'en-GB': 'e.g. en',
      de: 'z.B. en',
      ja: '例：en',
      ko: '예: en',
      zh: '例如 en',
      it: 'es. en',
      pt: 'ex. en',
      hi: 'जैसे en',
      ar: 'مثال: en',
      ru: 'напр. en',
      tr: 'örn. en',
      pl: 'np. en',
      id: 'mis. en',
      vi: 'vd. en',
      uk: 'напр. en',
    }),

    egFr: t({
      en: 'e.g. fr',
      fr: 'ex. fr',
      es: 'por ej. fr',
      'en-GB': 'e.g. fr',
      de: 'z.B. fr',
      ja: '例：fr',
      ko: '예: fr',
      zh: '例如 fr',
      it: 'es. fr',
      pt: 'ex. fr',
      hi: 'जैसे fr',
      ar: 'مثال: fr',
      ru: 'напр. fr',
      tr: 'örn. fr',
      pl: 'np. fr',
      id: 'mis. fr',
      vi: 'vd. fr',
      uk: 'напр. fr',
    }),

    fourPlusStars: t({
      en: '4+ stars',
      fr: '4+ étoiles',
      es: '4+ estrellas',
      'en-GB': '4+ stars',
      de: '4+ Sterne',
      ja: '4つ星以上',
      ko: '4점 이상',
      zh: '4星及以上',
      it: '4+ stelle',
      pt: '4+ estrelas',
      hi: '4+ सितारे',
      ar: '4+ نجوم',
      ru: '4+ звёзды',
      tr: '4+ yıldız',
      pl: '4+ gwiazdki',
      id: '4+ bintang',
      vi: '4+ sao',
      uk: '4+ зірки',
    }),

    fourPointFivePlusStars: t({
      en: '4.5+ stars',
      fr: '4.5+ étoiles',
      es: '4.5+ estrellas',
      'en-GB': '4.5+ stars',
      de: '4,5+ Sterne',
      ja: '4.5つ星以上',
      ko: '4.5점 이상',
      zh: '4.5星及以上',
      it: '4,5+ stelle',
      pt: '4,5+ estrelas',
      hi: '4.5+ सितारे',
      ar: '4.5+ نجوم',
      ru: '4,5+ звёзды',
      tr: '4,5+ yıldız',
      pl: '4,5+ gwiazdki',
      id: '4,5+ bintang',
      vi: '4,5+ sao',
      uk: '4,5+ зірки',
    }),

    filterReviewers: t({
      en: 'Filter reviewers',
      fr: 'Filtrer les traducteurs',
      es: 'Filtrar traductores',
      'en-GB': 'Filter reviewers',
      de: 'Reviewer filtern',
      ja: 'レビュアーをフィルター',
      ko: '리뷰어 필터링',
      zh: '筛选审稿人',
      it: 'Filtra revisori',
      pt: 'Filtrar revisores',
      hi: 'समीक्षकों को फ़िल्टर करें',
      ar: 'تصفية المراجعين',
      ru: 'Фильтровать рецензентов',
      tr: 'İnceleyicileri filtrele',
      pl: 'Filtruj recenzentów',
      id: 'Filter peninjau',
      vi: 'Lọc người đánh giá',
      uk: 'Фільтрувати рецензентів',
    }),

    categories: t({
      en: 'Categories',
      fr: 'Catégories',
      es: 'Categorías',
      'en-GB': 'Categories',
      de: 'Kategorien',
      ja: 'カテゴリー',
      ko: '카테고리',
      zh: '类别',
      it: 'Categorie',
      pt: 'Categorias',
      hi: 'श्रेणियाँ',
      ar: 'الفئات',
      ru: 'Категории',
      tr: 'Kategoriler',
      pl: 'Kategorie',
      id: 'Kategori',
      vi: 'Danh mục',
      uk: 'Категорії',
    }),

    categoryLabels: {
      copywriter: t({
        en: 'Copywriter',
        fr: 'Rédacteur',
        es: 'Redactor',
        'en-GB': 'Copywriter',
        de: 'Texter',
        ja: 'コピーライター',
        ko: '카피라이터',
        zh: '文案撰写',
        it: 'Copywriter',
        pt: 'Redator',
        hi: 'कॉपीराइटर',
        ar: 'كاتب إعلاني',
        ru: 'Копирайтер',
        tr: 'Metin yazarı',
        pl: 'Copywriter',
        id: 'Penulis konten',
        vi: 'Người viết nội dung',
        uk: 'Копірайтер',
      }),
      translator: t({
        en: 'Translator',
        fr: 'Traducteur',
        es: 'Traductor',
        'en-GB': 'Translator',
        de: 'Übersetzer',
        ja: '翻訳者',
        ko: '번역가',
        zh: '翻译员',
        it: 'Traduttore',
        pt: 'Tradutor',
        hi: 'अनुवादक',
        ar: 'مترجم',
        ru: 'Переводчик',
        tr: 'Çevirmen',
        pl: 'Tłumacz',
        id: 'Penerjemah',
        vi: 'Dịch giả',
        uk: 'Перекладач',
      }),
      proofreader: t({
        en: 'Proofreader',
        fr: 'Correcteur',
        es: 'Corrector',
        'en-GB': 'Proofreader',
        de: 'Korrektor',
        ja: '校正者',
        ko: '교정자',
        zh: '校对员',
        it: 'Revisore',
        pt: 'Revisor',
        hi: 'प्रूफरीडर',
        ar: 'مدقق لغوي',
        ru: 'Корректор',
        tr: 'Düzeltmen',
        pl: 'Korektor',
        id: 'Pemeriksa teks',
        vi: 'Người hiệu đính',
        uk: 'Коректор',
      }),
      technical_writer: t({
        en: 'Technical writer',
        fr: 'Rédacteur technique',
        es: 'Escritor técnico',
        'en-GB': 'Technical writer',
        de: 'Technischer Redakteur',
        ja: 'テクニカルライター',
        ko: '기술 문서 작성자',
        zh: '技术写作',
        it: 'Scrittore tecnico',
        pt: 'Redator técnico',
        hi: 'तकनीकी लेखक',
        ar: 'كاتب تقني',
        ru: 'Технический писатель',
        tr: 'Teknik yazar',
        pl: 'Pisarz techniczny',
        id: 'Penulis teknis',
        vi: 'Người viết kỹ thuật',
        uk: 'Технічний письменник',
      }),
      marketing: t({
        en: 'Marketing',
        fr: 'Marketing',
        es: 'Marketing',
        'en-GB': 'Marketing',
        de: 'Marketing',
        ja: 'マーケティング',
        ko: '마케팅',
        zh: '营销',
        it: 'Marketing',
        pt: 'Marketing',
        hi: 'मार्केटिंग',
        ar: 'تسويق',
        ru: 'Маркетинг',
        tr: 'Pazarlama',
        pl: 'Marketing',
        id: 'Pemasaran',
        vi: 'Tiếp thị',
        uk: 'Маркетинг',
      }),
      seo: 'SEO',
      content_reviewer: t({
        en: 'Content reviewer',
        fr: 'Relecteur de contenu',
        es: 'Revisor de contenido',
        'en-GB': 'Content reviewer',
        de: 'Content-Prüfer',
        ja: 'コンテンツレビュアー',
        ko: '콘텐츠 검토자',
        zh: '内容审核员',
        it: 'Revisore di contenuti',
        pt: 'Revisor de conteúdo',
        hi: 'सामग्री समीक्षक',
        ar: 'مراجع المحتوى',
        ru: 'Рецензент контента',
        tr: 'İçerik denetçisi',
        pl: 'Recenzent treści',
        id: 'Peninjau konten',
        vi: 'Người đánh giá nội dung',
        uk: 'Рецензент контенту',
      }),
    },
  },
} satisfies Dictionary;

export default reviewerFiltersContent;
