import { t, type DeclarationContent } from 'intlayer';
import { type Metadata } from 'next';

const docContent = {
  key: 'doc-useIntlayerAsync-react-intlayer-metadata',
  content: {
    title: t({
      en: 'useIntlayerAsync Hook Documentation | react-intlayer',
      'en-GB': 'useIntlayerAsync Hook Documentation | react-intlayer',
      fr: 'Documentation du hook useIntlayerAsync | react-intlayer',
      es: 'Documentación del hook useIntlayerAsync | react-intlayer',
      de: 'Dokumentation des useIntlayerAsync Hooks | react-intlayer',
      ja: 'useIntlayerAsyncフックのドキュメント | react-intlayer',
      ko: 'useIntlayerAsync 훅 설명서 | react-intlayer',
      zh: 'useIntlayerAsync钩子文档 | react-intlayer',
      it: 'Documentazione del hook useIntlayerAsync | react-intlayer',
      pt: 'Documentação do hook useIntlayerAsync | react-intlayer',
      hi: 'useIntlayerAsync हुक दस्तावेज | react-intlayer',
      ar: 'وثائق خطاف useIntlayerAsync | react-intlayer',
      ru: 'Документация по хуку useIntlayerAsync | react-intlayer',
    }),

    description: t({
      en: 'See how to use the useIntlayerAsync hook for next-intlayer package',
      'en-GB':
        'See how to use the useIntlayerAsync hook for next-intlayer package',
      fr: 'Découvrez comment utiliser le hook useIntlayerAsync pour le package next-intlayer',
      es: 'Descubre cómo usar el hook useIntlayerAsync para el paquete next-intlayer',
      de: 'Erfahren Sie, wie Sie den useIntlayerAsync-Hook für das next-intlayer-Paket verwenden',
      ja: 'next-intlayerパッケージのuseIntlayerAsyncフックの使用方法を確認してください',
      ko: 'next-intlayer 패키지에 대한 useIntlayerAsync 훅 사용 방법을 확인하세요',
      zh: '查看如何为next-intlayer包使用useIntlayerAsync钩子',
      it: 'Scopri come utilizzare il hook useIntlayerAsync per il pacchetto next-intlayer',
      pt: 'Veja como usar o hook useIntlayerAsync para o pacote next-intlayer',
      hi: 'next-intlayer पैकेज के लिए useIntlayerAsync हुक का उपयोग कैसे करें यह देखें',
      ar: 'انظر كيف تستخدم خطاف useIntlayerAsync لحزمة next-intlayer',
      ru: 'Узнайте, как использовать хук useIntlayerAsync для пакета next-intlayer',
    }),

    keywords: t({
      en: [
        'useIntlayerAsync',
        'dictionary',
        'key',
        'Intlayer',
        'Internationalization',
        'Documentation',
        'Next.js',
        'JavaScript',
        'React',
      ],
      'en-GB': [
        'useIntlayerAsync',
        'dictionary',
        'key',
        'Intlayer',
        'Internationalization',
        'Documentation',
        'Next.js',
        'JavaScript',
        'React',
      ],
      fr: [
        'useIntlayerAsync',
        'dictionnaire',
        'clé',
        'Intlayer',
        'Internationalisation',
        'Documentation',
        'Next.js',
        'JavaScript',
        'React',
      ],
      es: [
        'useIntlayerAsync',
        'diccionario',
        'clave',
        'Intlayer',
        'Internacionalización',
        'Documentación',
        'Next.js',
        'JavaScript',
        'React',
      ],
      de: [
        'useIntlayerAsync',
        'Wörterbuch',
        'Schlüssel',
        'Intlayer',
        'Internationalisierung',
        'Dokumentation',
        'Next.js',
        'JavaScript',
        'React',
      ],
      ja: [
        'useIntlayerAsync',
        '辞書',
        'キー',
        'Intlayer',
        '国際化',
        'ドキュメンテーション',
        'Next.js',
        'JavaScript',
        'React',
      ],
      ko: [
        'useIntlayerAsync',
        '사전',
        '키',
        'Intlayer',
        '국제화',
        '문서',
        'Next.js',
        'JavaScript',
        'React',
      ],
      zh: [
        'useIntlayerAsync',
        '字典',
        '键',
        'Intlayer',
        '国际化',
        '文档',
        'Next.js',
        'JavaScript',
        'React',
      ],
      it: [
        'useIntlayerAsync',
        'dizionario',
        'chiave',
        'Intlayer',
        'Internazionalizzazione',
        'Documentazione',
        'Next.js',
        'JavaScript',
        'React',
      ],
      pt: [
        'useIntlayerAsync',
        'dicionário',
        'chave',
        'Intlayer',
        'Internacionalização',
        'Documentação',
        'Next.js',
        'JavaScript',
        'React',
      ],
      hi: [
        'useIntlayerAsync',
        'शब्दकोश',
        'चाबी',
        'Intlayer',
        'अंतर्राष्ट्रीयकरण',
        'दस्तावेज़',
        'Next.js',
        'JavaScript',
        'React',
      ],
      ar: [
        'useIntlayerAsync',
        'قاموس',
        'مفتاح',
        'Intlayer',
        'الدولية',
        'التوثيق',
        'Next.js',
        'JavaScript',
        'React',
      ],
      ru: [
        'useIntlayerAsync',
        'словарь',
        'ключ',
        'Intlayer',
        'Интернационализация',
        'Документация',
        'Next.js',
        'JavaScript',
        'React',
      ],
    }),
  },
} satisfies DeclarationContent<Metadata>;

export default docContent;
