import { type Dictionary, t } from 'intlayer';

const mailerSettingsContent = {
  key: 'mailer-settings',
  content: {
    title: t({
      en: 'Email Configuration',
      'en-GB': 'Email Configuration',
      fr: 'Configuration des emails',
      es: 'Configuración de correo',
      de: 'E-Mail-Konfiguration',
      ja: 'メール設定',
      ko: '이메일 구성',
      zh: '电子邮件配置',
      it: 'Configurazione email',
      pt: 'Configuração de email',
      tr: 'E-posta Yapılandırması',
      ru: 'Настройка электронной почты',
      ar: 'إعدادات البريد الإلكتروني',
      hi: 'ईमेल कॉन्फ़िगरेशन',
      pl: 'Konfiguracja e-mail',
      id: 'Konfigurasi Email',
      vi: 'Cấu hình email',
      uk: 'Налаштування електронної пошти',
    }),

    description: t({
      en: 'Send organization emails (invitations, notifications) through your own provider instead of the default Intlayer mailer.',
      'en-GB':
        'Send organisation emails (invitations, notifications) through your own provider instead of the default Intlayer mailer.',
      fr: "Envoyez les emails de l'organisation (invitations, notifications) via votre propre fournisseur plutôt que le service par défaut d'Intlayer.",
      es: 'Envíe los correos de la organización (invitaciones, notificaciones) a través de su propio proveedor en lugar del servicio predeterminado de Intlayer.',
      de: 'Senden Sie Organisations-E-Mails (Einladungen, Benachrichtigungen) über Ihren eigenen Anbieter statt über den Standard-Mailer von Intlayer.',
      ja: '組織のメール（招待、通知）を、Intlayerの既定のメーラーではなく独自のプロバイダー経由で送信します。',
      ko: '조직 이메일(초대, 알림)을 기본 Intlayer 메일러 대신 자체 공급자를 통해 보냅니다.',
      zh: '通过您自己的提供商而非默认的 Intlayer 邮件服务发送组织电子邮件（邀请、通知）。',
      it: "Invia le email dell'organizzazione (inviti, notifiche) tramite il tuo provider invece del mailer predefinito di Intlayer.",
      pt: 'Envie os emails da organização (convites, notificações) através do seu próprio provedor em vez do mailer padrão do Intlayer.',
      tr: 'Kuruluş e-postalarını (davetler, bildirimler) varsayılan Intlayer posta hizmeti yerine kendi sağlayıcınız üzerinden gönderin.',
      ru: 'Отправляйте письма организации (приглашения, уведомления) через собственного провайдера вместо стандартного почтового сервиса Intlayer.',
      ar: 'أرسل رسائل المنظمة (الدعوات والإشعارات) عبر مزوّدك الخاص بدلاً من خدمة البريد الافتراضية في Intlayer.',
      hi: 'संगठन के ईमेल (आमंत्रण, सूचनाएं) डिफ़ॉल्ट Intlayer मेलर के बजाय अपने स्वयं के प्रदाता के माध्यम से भेजें।',
      pl: 'Wysyłaj e-maile organizacji (zaproszenia, powiadomienia) przez własnego dostawcę zamiast domyślnego mailera Intlayer.',
      id: 'Kirim email organisasi (undangan, notifikasi) melalui penyedia Anda sendiri alih-alih mailer bawaan Intlayer.',
      vi: 'Gửi email của tổ chức (lời mời, thông báo) qua nhà cung cấp của riêng bạn thay vì trình gửi thư mặc định của Intlayer.',
      uk: 'Надсилайте листи організації (запрошення, сповіщення) через власного провайдера замість стандартного поштового сервісу Intlayer.',
    }),

    enabledLabel: t({
      en: 'Use a custom mailer',
      'en-GB': 'Use a custom mailer',
      fr: 'Utiliser un service de messagerie personnalisé',
      es: 'Usar un servicio de correo personalizado',
      de: 'Eigenen Mailer verwenden',
      ja: 'カスタムメーラーを使用する',
      ko: '사용자 지정 메일러 사용',
      zh: '使用自定义邮件服务',
      it: 'Usa un mailer personalizzato',
      pt: 'Usar um mailer personalizado',
      tr: 'Özel bir posta hizmeti kullan',
      ru: 'Использовать собственный почтовый сервис',
      ar: 'استخدام خدمة بريد مخصصة',
      hi: 'कस्टम मेलर का उपयोग करें',
      pl: 'Użyj własnego mailera',
      id: 'Gunakan mailer khusus',
      vi: 'Sử dụng trình gửi thư tùy chỉnh',
      uk: 'Використовувати власний поштовий сервіс',
    }),

    providerTypeLabel: t({
      en: 'Provider',
      'en-GB': 'Provider',
      fr: 'Fournisseur',
      es: 'Proveedor',
      de: 'Anbieter',
      ja: 'プロバイダー',
      ko: '공급자',
      zh: '提供商',
      it: 'Provider',
      pt: 'Provedor',
      tr: 'Sağlayıcı',
      ru: 'Провайдер',
      ar: 'المزوّد',
      hi: 'प्रदाता',
      pl: 'Dostawca',
      id: 'Penyedia',
      vi: 'Nhà cung cấp',
      uk: 'Провайдер',
    }),

    providerTypeOptions: {
      resend: 'Resend',
      smtp: 'SMTP',
    },

    fromNameLabel: t({
      en: 'Sender name',
      'en-GB': 'Sender name',
      fr: "Nom de l'expéditeur",
      es: 'Nombre del remitente',
      de: 'Absendername',
      ja: '送信者名',
      ko: '보낸 사람 이름',
      zh: '发件人名称',
      it: 'Nome del mittente',
      pt: 'Nome do remetente',
      tr: 'Gönderen adı',
      ru: 'Имя отправителя',
      ar: 'اسم المُرسِل',
      hi: 'प्रेषक का नाम',
      pl: 'Nazwa nadawcy',
      id: 'Nama pengirim',
      vi: 'Tên người gửi',
      uk: 'Ім’я відправника',
    }),

    fromNamePlaceholder: 'Acme',

    fromEmailLabel: t({
      en: 'Sender email',
      'en-GB': 'Sender email',
      fr: "Email de l'expéditeur",
      es: 'Correo del remitente',
      de: 'Absender-E-Mail',
      ja: '送信者メールアドレス',
      ko: '보낸 사람 이메일',
      zh: '发件人电子邮件',
      it: 'Email del mittente',
      pt: 'Email do remetente',
      tr: 'Gönderen e-postası',
      ru: 'Email отправителя',
      ar: 'البريد الإلكتروني للمُرسِل',
      hi: 'प्रेषक का ईमेल',
      pl: 'E-mail nadawcy',
      id: 'Email pengirim',
      vi: 'Email người gửi',
      uk: 'Email відправника',
    }),

    fromEmailPlaceholder: 'no-reply@acme.com',

    resendConfig: {
      title: t({
        en: 'Resend Configuration',
        'en-GB': 'Resend Configuration',
        fr: 'Configuration Resend',
        es: 'Configuración de Resend',
        de: 'Resend-Konfiguration',
        ja: 'Resend 設定',
        ko: 'Resend 구성',
        zh: 'Resend 配置',
        it: 'Configurazione Resend',
        pt: 'Configuração do Resend',
        tr: 'Resend Yapılandırması',
        ru: 'Настройка Resend',
        ar: 'إعدادات Resend',
        hi: 'Resend कॉन्फ़िगरेशन',
        pl: 'Konfiguracja Resend',
        id: 'Konfigurasi Resend',
        vi: 'Cấu hình Resend',
        uk: 'Налаштування Resend',
      }),
      apiKeyLabel: t({
        en: 'API Key',
        'en-GB': 'API Key',
        fr: 'Clé API',
        es: 'Clave API',
        de: 'API-Schlüssel',
        ja: 'APIキー',
        ko: 'API 키',
        zh: 'API 密钥',
        it: 'Chiave API',
        pt: 'Chave de API',
        tr: 'API Anahtarı',
        ru: 'API-ключ',
        ar: 'مفتاح API',
        hi: 'API कुंजी',
        pl: 'Klucz API',
        id: 'Kunci API',
        vi: 'Khóa API',
        uk: 'API-ключ',
      }),
      apiKeyPlaceholder: 're_xxxxxxxxxxxxxxxx',
    },

    smtpConfig: {
      title: t({
        en: 'SMTP Configuration',
        'en-GB': 'SMTP Configuration',
        fr: 'Configuration SMTP',
        es: 'Configuración SMTP',
        de: 'SMTP-Konfiguration',
        ja: 'SMTP 設定',
        ko: 'SMTP 구성',
        zh: 'SMTP 配置',
        it: 'Configurazione SMTP',
        pt: 'Configuração SMTP',
        tr: 'SMTP Yapılandırması',
        ru: 'Настройка SMTP',
        ar: 'إعدادات SMTP',
        hi: 'SMTP कॉन्फ़िगरेशन',
        pl: 'Konfiguracja SMTP',
        id: 'Konfigurasi SMTP',
        vi: 'Cấu hình SMTP',
        uk: 'Налаштування SMTP',
      }),
      hostLabel: t({
        en: 'Host',
        'en-GB': 'Host',
        fr: 'Hôte',
        es: 'Host',
        de: 'Host',
        ja: 'ホスト',
        ko: '호스트',
        zh: '主机',
        it: 'Host',
        pt: 'Host',
        tr: 'Sunucu',
        ru: 'Хост',
        ar: 'المضيف',
        hi: 'होस्ट',
        pl: 'Host',
        id: 'Host',
        vi: 'Máy chủ',
        uk: 'Хост',
      }),
      hostPlaceholder: 'smtp.acme.com',
      portLabel: t({
        en: 'Port',
        'en-GB': 'Port',
        fr: 'Port',
        es: 'Puerto',
        de: 'Port',
        ja: 'ポート',
        ko: '포트',
        zh: '端口',
        it: 'Porta',
        pt: 'Porta',
        tr: 'Bağlantı Noktası',
        ru: 'Порт',
        ar: 'المنفذ',
        hi: 'पोर्ट',
        pl: 'Port',
        id: 'Porta',
        vi: 'Cổng',
        uk: 'Порт',
      }),
      secureLabel: t({
        en: 'Use TLS (implicit, usually port 465)',
        'en-GB': 'Use TLS (implicit, usually port 465)',
        fr: 'Utiliser TLS (implicite, généralement port 465)',
        es: 'Usar TLS (implícito, normalmente puerto 465)',
        de: 'TLS verwenden (implizit, üblicherweise Port 465)',
        ja: 'TLS を使用（暗黙的、通常はポート 465）',
        ko: 'TLS 사용 (암시적, 일반적으로 포트 465)',
        zh: '使用 TLS（隐式，通常为端口 465）',
        it: 'Usa TLS (implicito, di solito porta 465)',
        pt: 'Usar TLS (implícito, geralmente porta 465)',
        tr: 'TLS kullan (örtük, genellikle 465 bağlantı noktası)',
        ru: 'Использовать TLS (неявный, обычно порт 465)',
        ar: 'استخدام TLS (ضمني، عادةً المنفذ 465)',
        hi: 'TLS का उपयोग करें (अंतर्निहित, आमतौर पर पोर्ट 465)',
        pl: 'Użyj TLS (niejawny, zwykle port 465)',
        id: 'Gunakan TLS (implisit, biasanya porta 465)',
        vi: 'Sử dụng TLS (ngầm định, thường là cổng 465)',
        uk: 'Використовувати TLS (неявний, зазвичай порт 465)',
      }),
      userLabel: t({
        en: 'Username',
        'en-GB': 'Username',
        fr: "Nom d'utilisateur",
        es: 'Nombre de usuario',
        de: 'Benutzername',
        ja: 'ユーザー名',
        ko: '사용자 이름',
        zh: '用户名',
        it: 'Nome utente',
        pt: 'Nome de usuário',
        tr: 'Kullanıcı adı',
        ru: 'Имя пользователя',
        ar: 'اسم المستخدم',
        hi: 'उपयोगकर्ता नाम',
        pl: 'Nazwa użytkownika',
        id: 'Nama pengguna',
        vi: 'Tên người dùng',
        uk: 'Ім’я користувача',
      }),
      userPlaceholder: 'apikey',
      passwordLabel: t({
        en: 'Password',
        'en-GB': 'Password',
        fr: 'Mot de passe',
        es: 'Contraseña',
        de: 'Passwort',
        ja: 'パスワード',
        ko: '비밀번호',
        zh: '密码',
        it: 'Password',
        pt: 'Senha',
        tr: 'Parola',
        ru: 'Пароль',
        ar: 'كلمة المرور',
        hi: 'पासवर्ड',
        pl: 'Hasło',
        id: 'Kata sandi',
        vi: 'Mật khẩu',
        uk: 'Пароль',
      }),
    },

    secretConfiguredPlaceholder: t({
      en: 'Configured — leave blank to keep unchanged',
      'en-GB': 'Configured — leave blank to keep unchanged',
      fr: 'Configuré — laissez vide pour ne pas modifier',
      es: 'Configurado — deje en blanco para no cambiarlo',
      de: 'Konfiguriert — leer lassen, um es beizubehalten',
      ja: '設定済み — 変更しない場合は空欄のままにします',
      ko: '구성됨 — 변경하지 않으려면 비워 두세요',
      zh: '已配置 — 留空则保持不变',
      it: 'Configurato — lascia vuoto per non modificarlo',
      pt: 'Configurado — deixe em branco para manter',
      tr: 'Yapılandırıldı — değiştirmemek için boş bırakın',
      ru: 'Настроено — оставьте пустым, чтобы не менять',
      ar: 'مُهيأ — اتركه فارغًا للإبقاء عليه دون تغيير',
      hi: 'कॉन्फ़िगर किया गया — अपरिवर्तित रखने के लिए खाली छोड़ें',
      pl: 'Skonfigurowano — pozostaw puste, aby nie zmieniać',
      id: 'Terkonfigurasi — biarkan kosong untuk mempertahankan',
      vi: 'Đã cấu hình — để trống để giữ nguyên',
      uk: 'Налаштовано — залиште порожнім, щоб не змінювати',
    }),

    fromEmailInvalid: t({
      en: 'A valid sender email is required',
      'en-GB': 'A valid sender email is required',
      fr: "Un email d'expéditeur valide est requis",
      es: 'Se requiere un correo de remitente válido',
      de: 'Eine gültige Absender-E-Mail ist erforderlich',
      ja: '有効な送信者メールアドレスが必要です',
      ko: '유효한 보낸 사람 이메일이 필요합니다',
      zh: '需要有效的发件人电子邮件',
      it: 'È richiesta un’email del mittente valida',
      pt: 'É necessário um email de remetente válido',
      tr: 'Geçerli bir gönderen e-postası gerekli',
      ru: 'Требуется действительный email отправителя',
      ar: 'مطلوب بريد إلكتروني صالح للمُرسِل',
      hi: 'एक मान्य प्रेषक ईमेल आवश्यक है',
      pl: 'Wymagany jest prawidłowy e-mail nadawcy',
      id: 'Email pengirim yang valid diperlukan',
      vi: 'Cần có email người gửi hợp lệ',
      uk: 'Потрібен дійсний email відправника',
    }),

    apiKeyRequired: t({
      en: 'A Resend API key is required',
      'en-GB': 'A Resend API key is required',
      fr: 'Une clé API Resend est requise',
      es: 'Se requiere una clave API de Resend',
      de: 'Ein Resend-API-Schlüssel ist erforderlich',
      ja: 'Resend APIキーが必要です',
      ko: 'Resend API 키가 필요합니다',
      zh: '需要 Resend API 密钥',
      it: 'È richiesta una chiave API Resend',
      pt: 'É necessária uma chave de API do Resend',
      tr: 'Resend API anahtarı gerekli',
      ru: 'Требуется API-ключ Resend',
      ar: 'مطلوب مفتاح API لـ Resend',
      hi: 'एक Resend API कुंजी आवश्यक है',
      pl: 'Wymagany jest klucz API Resend',
      id: 'Kunci API Resend diperlukan',
      vi: 'Cần có khóa API Resend',
      uk: 'Потрібен API-ключ Resend',
    }),

    smtpHostRequired: t({
      en: 'An SMTP host is required',
      'en-GB': 'An SMTP host is required',
      fr: 'Un hôte SMTP est requis',
      es: 'Se requiere un host SMTP',
      de: 'Ein SMTP-Host ist erforderlich',
      ja: 'SMTPホストが必要です',
      ko: 'SMTP 호스트가 필요합니다',
      zh: '需要 SMTP 主机',
      it: 'È richiesto un host SMTP',
      pt: 'É necessário um host SMTP',
      tr: 'Bir SMTP sunucusu gerekli',
      ru: 'Требуется SMTP-хост',
      ar: 'مطلوب مضيف SMTP',
      hi: 'एक SMTP होस्ट आवश्यक है',
      pl: 'Wymagany jest host SMTP',
      id: 'Host SMTP diperlukan',
      vi: 'Cần có máy chủ SMTP',
      uk: 'Потрібен SMTP-хост',
    }),

    saveButton: {
      text: t({
        en: 'Save Email Configuration',
        'en-GB': 'Save Email Configuration',
        fr: 'Enregistrer la configuration des emails',
        es: 'Guardar configuración de correo',
        de: 'E-Mail-Konfiguration speichern',
        ja: 'メール設定を保存',
        ko: '이메일 구성 저장',
        zh: '保存电子邮件配置',
        it: 'Salva configurazione email',
        pt: 'Salvar configuração de email',
        tr: 'E-posta Yapılandırmasını Kaydet',
        ru: 'Сохранить настройку почты',
        ar: 'حفظ إعدادات البريد الإلكتروني',
        hi: 'ईमेल कॉन्फ़िगरेशन सहेजें',
        pl: 'Zapisz konfigurację e-mail',
        id: 'Simpan Konfigurasi Email',
        vi: 'Lưu cấu hình email',
        uk: 'Зберегти налаштування пошти',
      }),
      ariaLabel: t({
        en: 'Click to save email configuration',
        'en-GB': 'Click to save email configuration',
        fr: 'Cliquez pour enregistrer la configuration des emails',
        es: 'Haga clic para guardar la configuración de correo',
        de: 'Klicken Sie, um die E-Mail-Konfiguration zu speichern',
        ja: 'メール設定を保存するにはクリックしてください',
        ko: '이메일 구성을 저장하려면 클릭하세요',
        zh: '单击以保存电子邮件配置',
        it: 'Fai clic per salvare la configurazione email',
        pt: 'Clique para salvar a configuração de email',
        tr: 'E-posta yapılandırmasını kaydetmek için tıklayın',
        ru: 'Нажмите, чтобы сохранить настройку почты',
        ar: 'انقر لحفظ إعدادات البريد الإلكتروني',
        hi: 'ईमेल कॉन्फ़िगरेशन सहेजने के लिए क्लिक करें',
        pl: 'Kliknij, aby zapisać konfigurację e-mail',
        id: 'Klik untuk menyimpan konfigurasi email',
        vi: 'Nhấp để lưu cấu hình email',
        uk: 'Натисніть, щоб зберегти налаштування пошти',
      }),
    },
  },
  title: 'Mailer Settings',
  description:
    'Content declaration for the per-organization mailer settings form. Includes labels, placeholders and validation messages for Resend and SMTP configuration.',
  tags: ['dashboard', 'mailer', 'email', 'organization'],
} satisfies Dictionary;

export default mailerSettingsContent;
