import { t, type DeclarationContent } from 'intlayer';
import { type Metadata } from 'next';

const docContent = {
  key: 'doc-visual-editor-metadata',
  content: {
    title: t({
      en: 'Intlayer Visual Editor | Edit your content using a visual editor',
      'en-GB':
        'Intlayer Visual Editor | Edit your content using a visual editor',
      fr: 'Éditeur Visual Intlayer | Modifiez votre contenu en utilisant un éditeur visuel',
      es: 'Editor Visual Intlayer | Edita tu contenido utilizando un editor visual',
      de: 'Intlayer Visual Editor | Bearbeiten Sie Ihren Inhalt mit einem visuellen Editor',
      ja: 'Intlayerビジュアルエディター | ビジュアルエディターを使用してコンテンツを編集します',
      ko: 'Intlayer 비주얼 편집기 | 비주얼 편집기를 사용하여 콘텐츠를 편집합니다',
      zh: 'Intlayer 可视编辑器 | 使用可视编辑器编辑您的内容',
      it: 'Editor Visual Intlayer | Modifica il tuo contenuto utilizzando un editor visuale',
      pt: 'Editor Visual Intlayer | Edite seu conteúdo usando um editor visual',
      hi: 'Intlayer वीजियो संपादक | वीजियो संपादक का उपयोग करके अपने कंटेंट को संपादित करें',
      ar: 'محرر المرئي لِانتلاير | تحرير محتوىك باستخدام محرر المرئي',
      ru: 'Intlayer визуальный редактор | Изменяйте свой контент, используя визуальный редактор',
    }),

    description: t({
      en: 'Discover how to use the Intlayer Editor to manage your multilingual website. Follow the steps in this online documentation to set up your project in a few minutes.',
      'en-GB':
        'Discover how to use the Intlayer Editor to manage your multilingual website. Follow the steps in this online documentation to set up your project in a few minutes.',
      fr: "Découvrez comment utiliser l'Éditeur Intlayer pour gérer votre site web multilingue. Suivez les étapes de cette documentation en ligne pour configurer votre projet en quelques minutes.",
      es: 'Descubra cómo usar el Editor Intlayer para gestionar su sitio web multilingüe. Siga los pasos de esta documentación en línea para configurar su proyecto en unos minutos.',
      de: 'Erfahren Sie, wie Sie den Intlayer-Editor zur Verwaltung Ihrer mehrsprachigen Website nutzen können. Befolgen Sie die Schritte in dieser Online-Dokumentation, um Ihr Projekt in wenigen Minuten einzurichten.',
      ja: 'Intlayerエディターを使用して多言語ウェブサイトを管理する方法を発見してください。このオンラインドキュメントの手順に従って、数分でプロジェクトを設定することができます。',
      ko: 'Intlayer 편집기를 사용하여 다국어 웹사이트를 관리하는 방법을 알아보세요. 이 온라인 문서의 단계를 따라 몇 분 만에 프로젝트를 설정하세요.',
      zh: '发现如何使用Intlayer编辑器来管理您的多语言网站。遵循本在线文档中的步骤，在几分钟内设置您的项目。',
      it: 'Scopri come utilizzare l’Editor Intlayer per gestire il tuo sito web multilingue. Segui i passi in questa documentazione online per configurare il tuo progetto in pochi minuti.',
      pt: 'Descubra como usar o Editor Intlayer para gerenciar seu site multilíngue. Siga os passos nesta documentação online para configurar seu projeto em poucos minutos.',
      hi: 'Intlayer संपादक का उपयोग करके अपने बहुभाषी वेबसाइट का प्रबंधन करने का तरीका जानें। अपने प्रोजेक्ट को कुछ ही मिनटों में सेट करने के लिए इस ऑनलाइन दस्तावेज़ में दिए गए चरणों का पालन करें।',
      ar: 'اكتشف كيفية استخدام محرر Intlayer لإدارة موقعك الإلكتروني متعدد اللغات. اتبع الخطوات في هذه الوثيقة عبر الإنترنت لإعداد مشروعك في بضع دقائق.',
      ru: 'Узнайте, как использовать редактор Intlayer для управления вашим многоязычным веб-сайтом. Следуйте шагам в этой онлайн-документации, чтобы настроить ваш проект за несколько минут.',
    }),

    keywords: t({
      en: [
        'Editor',
        'Internationalization',
        'Documentation',
        'Intlayer',
        'Next.js',
        'JavaScript',
        'React',
      ],
      'en-GB': [
        'Editor',
        'Internationalization',
        'Documentation',
        'Intlayer',
        'Next.js',
        'JavaScript',
        'React',
      ],
      fr: [
        'Éditeur',
        'Internationalisation',
        'Documentation',
        'Intlayer',
        'Next.js',
        'JavaScript',
        'React',
      ],
      es: [
        'Editor',
        'Internacionalización',
        'Documentación',
        'Intlayer',
        'Next.js',
        'JavaScript',
        'React',
      ],
      de: [
        'Editor',
        'Internationalisierung',
        'Dokumentation',
        'Intlayer',
        'Next.js',
        'JavaScript',
        'React',
      ],
      ja: [
        'エディター',
        '国際化',
        'ドキュメント',
        'Intlayer',
        'Next.js',
        'JavaScript',
        'React',
      ],
      ko: [
        '편집자',
        '국제화',
        '문서',
        'Intlayer',
        'Next.js',
        'JavaScript',
        'React',
      ],
      zh: [
        '编辑器',
        '国际化',
        '文档',
        'Intlayer',
        'Next.js',
        'JavaScript',
        'React',
      ],
      it: [
        'Editor',
        'Internazionalizzazione',
        'Documentazione',
        'Intlayer',
        'Next.js',
        'JavaScript',
        'React',
      ],
      pt: [
        'Editor',
        'Internacionalização',
        'Documentação',
        'Intlayer',
        'Next.js',
        'JavaScript',
        'React',
      ],
      hi: [
        'संपादक',
        'अंतर्राष्ट्रीयकरण',
        'प्रलेखन',
        'Intlayer',
        'Next.js',
        'JavaScript',
        'React',
      ],
      ar: [
        'محرر',
        'تدويل',
        'وثائق',
        'Intlayer',
        'Next.js',
        'JavaScript',
        'React',
      ],
      ru: [
        'Редактор',
        'Интернационализация',
        'Документация',
        'Intlayer',
        'Next.js',
        'JavaScript',
        'React',
      ],
    }),
  },
} satisfies DeclarationContent<Metadata>;

export default docContent;
