import { t, type Dictionary } from 'intlayer';

export const changePasswordContent = {
  key: 'change-password-schema',
  content: {
    currentPasswordInput: {
      label: t({
        en: 'Current password',
        fr: 'Mot de passe actuel',
        es: 'Contraseña actual',
        de: 'Aktuelles Passwort',
        ja: '現在のパスワード',
        ko: '현재 비밀번호',
        zh: '当前密码',
        it: 'Password attuale',
        pt: 'Senha atual',
        hi: 'वर्तमान पासवर्ड',
        ar: 'كلمة المرور الحالية',
        ru: 'Текущий пароль',
        'en-GB': 'Current password',
      }),
      placeholder: t({
        en: 'Enter actual password',
        fr: 'Entrez votre mot de passe actuel',
        es: 'Ingresa tu contraseña actual',
        de: 'Geben Sie das aktuelle Passwort ein',
        ja: '現在のパスワードを入力してください',
        ko: '현재 비밀번호를 입력하세요',
        zh: '输入当前密码',
        it: 'Inserisci la password attuale',
        pt: 'Digite a senha atual',
        hi: 'वर्तमान पासवर्ड दर्ज करें',
        ar: 'أدخل كلمة المرور الحالية',
        ru: 'Введите текущий пароль',
        'en-GB': 'Enter actual password',
      }),
    },
    newPasswordInput: {
      label: t({
        en: 'New password',
        fr: 'Nouveau mot de passe',
        es: 'Nueva contraseña',
        de: 'Neues Passwort',
        ja: '新しいパスワード',
        ko: '새 비밀번호',
        zh: '新密码',
        it: 'Nuova password',
        pt: 'Nova senha',
        hi: 'नया पासवर्ड',
        ar: 'كلمة المرور الجديدة',
        ru: 'Новый пароль',
        'en-GB': 'New password',
      }),
      placeholder: t({
        en: 'Enter new password',
        fr: 'Entrez votre nouveau mot de passe',
        es: 'Ingresa tu nueva contraseña',
        de: 'Geben Sie das neue Passwort ein',
        ja: '新しいパスワードを入力してください',
        ko: '새 비밀번호를 입력하세요',
        zh: '输入新密码',
        it: 'Inserisci la nuova password',
        pt: 'Digite a nova senha',
        hi: 'नया पासवर्ड दर्ज करें',
        ar: 'أدخل كلمة المرور الجديدة',
        ru: 'Введите новый пароль',
        'en-GB': 'Enter new password',
      }),
    },
    confirmPasswordInput: {
      label: t({
        en: 'Confirm new password',
        fr: 'Confirmez le nouveau mot de passe',
        es: 'Confirma tu nueva contraseña',
        de: 'Bestätigen Sie das neue Passwort',
        ja: '新しいパスワードを確認してください',
        ko: '새 비밀번호를 확인하세요',
        zh: '确认新密码',
        it: 'Conferma la nuova password',
        pt: 'Confirme a nova senha',
        hi: 'नए पासवर्ड की पुष्टि करें',
        ar: 'تأكيد كلمة المرور الجديدة',
        ru: 'Подтвердите новый пароль',
        'en-GB': 'Confirm new password',
      }),
      placeholder: t({
        en: 'Confirm new password',
        fr: 'Confirmez votre nouveau mot de passe',
        es: 'Confirma tu nueva contraseña',
        de: 'Bestätigen Sie das neue Passwort',
        ja: '新しいパスワードを確認してください',
        ko: '새 비밀번호를 확인하세요',
        zh: '确认新密码',
        it: 'Conferma la nuova password',
        pt: 'Confirme a nova senha',
        hi: 'नए पासवर्ड की पुष्टि करें',
        ar: 'تأكيد كلمة المرور الجديدة',
        ru: 'Подтвердите новый пароль',
        'en-GB': 'Confirm new password',
      }),
    },
    changePasswordButton: {
      text: t({
        en: 'Change password',
        fr: 'Changer le mot de passe',
        es: 'Cambiar la contraseña',
        de: 'Passwort ändern',
        ja: 'パスワードを変更',
        ko: '비밀번호 변경',
        zh: '更改密码',
        it: 'Cambia password',
        pt: 'Alterar senha',
        hi: 'पासवर्ड बदलें',
        ar: 'تغيير كلمة المرور',
        ru: 'Сменить пароль',
        'en-GB': 'Change password',
      }),
      ariaLabel: t({
        en: 'Click to change password',
        fr: 'Cliquez pour changer le mot de passe',
        es: 'Haz clic para cambiar la contraseña',
        de: 'Klicken Sie, um das Passwort zu ändern',
        ja: 'パスワードを変更するにはクリックしてください',
        ko: '비밀번호를 변경하려면 클릭하세요',
        zh: '单击以更改密码',
        it: 'Clicca per cambiare la password',
        pt: 'Clique para alterar a senha',
        hi: 'पासवर्ड बदलने के लिए क्लिक करें',
        ar: 'انقر لتغيير كلمة المرور',
        ru: 'Нажмите, чтобы изменить пароль',
        'en-GB': 'Click to change password',
      }),
    },
    backToHomeButton: {
      text: t({
        en: 'Back to home page',
        fr: 'Retour à la page d’accueil',
        es: 'Volver a la página de inicio',
        de: 'Zurück zur Startseite',
        ja: 'ホームページに戻る',
        ko: '홈페이지로 돌아가기',
        zh: '返回主页',
        it: 'Torna alla home page',
        pt: 'Voltar para a página inicial',
        hi: 'होम पृष्ठ पर वापस जाएं',
        ar: 'العودة إلى الصفحة الرئيسية',
        ru: 'Вернуться на главную страницу',
        'en-GB': 'Back to home page',
      }),
      ariaLabel: t({
        en: 'Click to go back to the home page',
        fr: 'Cliquez pour revenir à la page d’accueil',
        es: 'Haz clic para volver a la página de inicio',
        de: 'Klicken Sie, um zur Startseite zurückzukehren',
        ja: 'ホームページに戻るにはクリックしてください',
        ko: '홈페이지로 돌아가려면 클릭하세요',
        zh: '单击以返回主页',
        it: 'Clicca per tornare alla home page',
        pt: 'Clique para voltar para a página inicial',
        hi: 'होम पृष्ठ पर वापस जाने के लिए क्लिक करें',
        ar: 'انقر للعودة إلى الصفحة الرئيسية',
        ru: 'Нажмите, чтобы вернуться на главную страницу',
        'en-GB': 'Click to go back to the home page',
      }),
    },
  },
} satisfies Dictionary;
