import { type Dictionary, t } from 'intlayer';

export default {
  key: 'organization-structured-data',
  content: {
    slogan: t({
      en: 'Ship multilingual apps faster',
      fr: 'Déployez des applications multilingues plus rapidement',
      es: 'Envía aplicaciones multilingües más rápido',
      'en-GB': 'Ship multilingual apps faster',
      de: 'Erstellen Sie mehrsprachige Apps schneller',
      it: 'Distribuisci app multilingue più velocemente',
      ja: '多言語アプリをより速く公開',
      ko: '다국어 앱을 더 빠르게 출시하세요',
      zh: '更快地交付多语言应用程序',
      pt: 'Envie aplicativos multilíngues mais rápido',
      hi: 'बहुभाषी ऐप्स तेज़ी से शिप करें',
      ar: 'أطلق تطبيقات متعددة اللغات بشكل أسرع',
      ru: 'Развертывайте многоязычные приложения быстрее',
      tr: 'Çok dilli uygulamaları daha hızlı yayınlayın',
      pl: 'Szybciej dostarczaj aplikacje wielojęzyczne',
      id: 'Kirim aplikasi multibahasa lebih cepat',
      vi: 'Giao các ứng dụng đa ngôn ngữ nhanh hơn',
      uk: 'Розгортайте багатомовні додатки швидше',
    }),
    knowsAbout: t<string[]>({
      en: [
        'internationalization',
        'localization',
        'translation management',
        'i18n',
        'l10n',
        'multilingual SEO',
        'software localization',
        'Next.js',
        'React',
        'TypeScript',
      ],
      fr: [
        'internationalisation',
        'localisation',
        'gestion des traductions',
        'i18n',
        'l10n',
        'SEO multilingue',
        'localisation de logiciels',
        'Next.js',
        'React',
        'TypeScript',
      ],
      es: [
        'internacionalización',
        'localización',
        'gestión de traducciones',
        'i18n',
        'l10n',
        'SEO multilingüe',
        'localización de software',
        'Next.js',
        'React',
        'TypeScript',
      ],
      'en-GB': [
        'internationalization',
        'localization',
        'translation management',
        'i18n',
        'l10n',
        'multilingual SEO',
        'software localization',
        'Next.js',
        'React',
        'TypeScript',
      ],
      de: [
        'Internationalisierung',
        'Lokalisierung',
        'Übersetzungsmanagement',
        'i18n',
        'l10n',
        'mehrsprachiges SEO',
        'Software-Lokalisierung',
        'Next.js',
        'React',
        'TypeScript',
      ],
      it: [
        'internazionalizzazione',
        'localizzazione',
        'gestione delle traduzioni',
        'i18n',
        'l10n',
        'SEO multilingue',
        'localizzazione del software',
        'Next.js',
        'React',
        'TypeScript',
      ],
      ja: [
        '国際化',
        'ローカリゼーション',
        '翻訳管理',
        'i18n',
        'l10n',
        '多言語SEO',
        'ソフトウェアローカリゼーション',
        'Next.js',
        'React',
        'TypeScript',
      ],
      ko: [
        '국제화',
        '현지화',
        '번역 관리',
        'i18n',
        'l10n',
        '다국어 SEO',
        '소프트웨어 현지화',
        'Next.js',
        'React',
        'TypeScript',
      ],
      zh: [
        '国际化',
        '本地化',
        '翻译管理',
        'i18n',
        'l10n',
        '多语言 SEO',
        '软件本地化',
        'Next.js',
        'React',
        'TypeScript',
      ],
      pt: [
        'internacionalização',
        'localização',
        'gestão de traduções',
        'i18n',
        'l10n',
        'SEO multilíngue',
        'localização de software',
        'Next.js',
        'React',
        'TypeScript',
      ],
      hi: [
        'अंतर्राष्ट्रीयकरण',
        'स्थानीयकरण',
        'अनुवाद प्रबंधन',
        'i18n',
        'l10n',
        'बहुभाषी एसईओ',
        'सॉफ्टवेयर स्थानीयकरण',
        'Next.js',
        'React',
        'TypeScript',
      ],
      ar: [
        'التدويل',
        'التوطين',
        'إدارة الترجمة',
        'i18n',
        'l10n',
        'SEO متعدد اللغات',
        'توطين البرمجيات',
        'Next.js',
        'React',
        'TypeScript',
      ],
      ru: [
        'интернационализация',
        'локализация',
        'управление переводами',
        'i18n',
        'l10n',
        'многоязычный SEO',
        'локализация программного обеспечения',
        'Next.js',
        'React',
        'TypeScript',
      ],
      tr: [
        'uluslararasılaştırma',
        'yerelleştirme',
        'çeviri yönetimi',
        'i18n',
        'l10n',
        'çok dilli SEO',
        'yazılım yerelleştirme',
        'Next.js',
        'React',
        'TypeScript',
      ],
      pl: [
        'internacjonalizacja',
        'lokalizacja',
        'zarządzanie tłumaczeniami',
        'i18n',
        'l10n',
        'wielojęzyczne SEO',
        'lokalizacja oprogramowania',
        'Next.js',
        'React',
        'TypeScript',
      ],
      id: [
        'internasionalisasi',
        'lokalisasi',
        'manajemen terjemahan',
        'i18n',
        'l10n',
        'SEO multibahasa',
        'lokalisasi perangkat lunak',
        'Next.js',
        'React',
        'TypeScript',
      ],
      vi: [
        'quốc tế hóa',
        'bản địa hóa',
        'quản lý dịch thuật',
        'i18n',
        'l10n',
        'SEO đa ngôn ngữ',
        'bản địa hóa phần mềm',
        'Next.js',
        'React',
        'TypeScript',
      ],
      uk: [
        'інтернаціоналізація',
        'локалізація',
        'управління перекладами',
        'i18n',
        'l10n',
        'багатомовний SEO',
        'локалізація програмного забезпечення',
        'Next.js',
        'React',
        'TypeScript',
      ],
    }),
  },
  title: 'Organization structured data',
  description:
    'Structured data for the organization, including slogan and relevant keywords. Helps search engines understand the organization effectively.',
  tags: ['structured data', 'SEO', 'organization'],
} satisfies Dictionary;
