import { type Dictionary, t } from 'intlayer';

const organizationsAdminPageContent = {
  key: 'organization-admin-page',
  content: {
    title: t({
      en: 'Organizations Management',
      fr: 'Gestion des organisations',
      es: 'Gestión de organizaciones',
      'en-GB': 'Organisations Management',
      de: 'Organisationsverwaltung',
      ja: '組織管理',
      ko: '조직 관리',
      zh: '组织管理',
      it: 'Gestione organizzazioni',
      pt: 'Gestão de organizações',
      hi: 'संगठन प्रबंधन',
      ar: 'إدارة المنظمات',
      ru: 'Управление организациями',
      tr: 'Organizasyon yönetimi',
      pl: 'Zarządzanie organizacjami',
    }),
    tableHeaders: {
      name: t({
        en: 'Name',
        fr: 'Nom',
        es: 'Nombre',
        'en-GB': 'Name',
        de: 'Name',
        ja: '名前',
        ko: '이름',
        zh: '名称',
        it: 'Nome',
        pt: 'Nome',
        hi: 'नाम',
        ar: 'الاسم',
        ru: 'Имя',
        tr: 'İsim',
        pl: 'Nazwa',
      }),
      id: 'ID',
      createdAt: t({
        en: 'Created At',
        fr: 'Créé le',
        es: 'Creado en',
        'en-GB': 'Created At',
        de: 'Erstellt am',
        ja: '作成日',
        ko: '생성일',
        zh: '创建时间',
        it: 'Creato il',
        pt: 'Criado em',
        hi: 'बनाया गया',
        ar: 'تم الإنشاء في',
        ru: 'Создано',
        tr: 'Oluşturulma',
        pl: 'Data utworzenia',
      }),
      updatedAt: t({
        en: 'Updated At',
        fr: 'Mis à jour le',
        es: 'Actualizado en',
        'en-GB': 'Updated At',
        de: 'Aktualisiert am',
        ja: '更新日',
        ko: '업데이트일',
        zh: '更新时间',
        it: 'Aggiornato il',
        pt: 'Atualizado em',
        hi: 'अपडेट किया गया',
        ar: 'تم التحديث في',
        ru: 'Обновлено',
        tr: 'Güncellendi',
        pl: 'Data aktualizacji',
      }),
    },
    noData: t({
      en: 'N/A',
      fr: 'N/A',
      es: 'N/A',
      'en-GB': 'N/A',
      de: 'N/A',
      ja: 'なし',
      ko: '없음',
      zh: '无',
      it: 'N/A',
      pt: 'N/A',
      hi: 'N/A',
      ar: 'غير متوفر',
      ru: 'Н/Д',
      tr: 'Yok',
      pl: 'Brak danych',
    }),
    errorMessages: {
      loadingError: t({
        en: 'Error loading organizations',
        fr: 'Erreur lors du chargement des organisations',
        es: 'Error al cargar organizaciones',
        'en-GB': 'Error loading organisations',
        de: 'Fehler beim Laden der Organisationen',
        ja: '組織の読み込みエラー',
        ko: '조직 로딩 오류',
        zh: '加载组织时出错',
        it: 'Errore nel caricamento delle organizzazioni',
        pt: 'Erro ao carregar organizações',
        hi: 'संगठनों को लोड करने में त्रुटि',
        ar: 'خطأ في تحميل المنظمات',
        ru: 'Ошибка загрузки организаций',
        tr: 'Organizasyonlar yüklenirken hata oluştu',
        pl: 'Błąd podczas ładowania organizacji',
      }),
    },
    searchPlaceholder: t({
      en: 'Search organizations...',
      fr: 'Rechercher des organisations...',
      es: 'Buscar organizaciones...',
      'en-GB': 'Search organisations...',
      de: 'Organisationen suchen...',
      ja: '組織を検索...',
      ko: '조직 검색...',
      zh: '搜索组织...',
      it: 'Cerca organizzazioni...',
      pt: 'Buscar organizações...',
      hi: 'संगठनों की खोज करें...',
      ar: 'ابحث عن المنظمات...',
      ru: 'Поиск организаций...',
      tr: 'Organizasyonları ara...',
      pl: 'Szukaj organizacji...',
    }),
    noOrganizationFound: t({
      en: 'Organization not found',
      fr: 'Organisation non trouvée',
      es: 'Organización no encontrada',
      'en-GB': 'Organization not found',
      de: 'Organisation nicht gefunden',
      ja: '組織が見つかりません',
      ko: '조직을 찾을 수 없습니다',
      zh: '找不到组织',
      it: 'Organizzazione non trovata',
      pt: 'Organização não encontrada',
      hi: 'संगठन नहीं खोजा गया',
      ar: 'المنظمة غير موجودة',
      ru: 'Организация не найдена',
      tr: 'Organizasyon bulunamadı',
      pl: 'Nie znaleziono organizacji',
    }),
  },
  title: 'Organization admin page',
  description:
    'Content declarations for the organization administration page, including table headers, search placeholder, error messages, and no data state.',
  tags: ['admin page', 'organizations', 'dashboard'],
} satisfies Dictionary;

export default organizationsAdminPageContent;
