import { cond, type Dictionary, t } from 'intlayer';

const cliRepositoryFlowContent = {
  key: 'cli-repository-flow',
  content: {
    signInTitle: t({
      en: 'Sign in to set up your repository',
      'en-GB': 'Sign in to set up your repository',
      es: 'Inicia sesión para configurar tu repositorio',
      fr: 'Connectez-vous pour configurer votre dépôt',
      ru: 'Войдите, чтобы настроить репозиторий',
      ja: 'リポジトリを設定するにはサインインしてください',
      ko: '저장소를 설정하려면 로그인하세요',
      zh: '登录以设置您的仓库',
      de: 'Melden Sie sich an, um Ihr Repository einzurichten',
      ar: 'سجّل الدخول لإعداد مستودعك',
      it: 'Accedi per configurare il tuo repository',
      pt: 'Entre para configurar seu repositório',
      hi: 'अपनी रिपॉजिटरी सेट करने के लिए साइन इन करें',
      tr: 'Deponuzu kurmak için giriş yapın',
      pl: 'Zaloguj się, aby skonfigurować repozytorium',
      id: 'Masuk untuk menyiapkan repositori Anda',
      vi: 'Đăng nhập để thiết lập kho mã của bạn',
      uk: 'Увійдіть, щоб налаштувати репозиторій',
    }),
    title: t({
      en: 'Connect your repository',
      'en-GB': 'Connect your repository',
      es: 'Conecta tu repositorio',
      fr: 'Connectez votre dépôt',
      ru: 'Подключите репозиторий',
      ja: 'リポジトリを接続',
      ko: '저장소 연결',
      zh: '连接您的仓库',
      de: 'Repository verbinden',
      ar: 'اربط مستودعك',
      it: 'Collega il tuo repository',
      pt: 'Conecte seu repositório',
      hi: 'अपनी रिपॉजिटरी कनेक्ट करें',
      tr: 'Deponuzu bağlayın',
      pl: 'Połącz swoje repozytorium',
      id: 'Hubungkan repositori Anda',
      vi: 'Kết nối kho mã của bạn',
      uk: 'Підключіть репозиторій',
    }),
    description: t({
      en: 'Link the git repository of this project so CMS edits can be committed back to your codebase and builds can be triggered.',
      'en-GB':
        'Link the git repository of this project so CMS edits can be committed back to your codebase and builds can be triggered.',
      es: 'Vincula el repositorio git de este proyecto para que las ediciones del CMS se confirmen en tu código y se puedan lanzar compilaciones.',
      fr: 'Liez le dépôt git de ce projet pour que les modifications du CMS soient commitées dans votre code et que les builds puissent être déclenchés.',
      ru: 'Свяжите git-репозиторий проекта, чтобы изменения из CMS коммитились в код, а сборки запускались автоматически.',
      ja: 'このプロジェクトの git リポジトリを連携すると、CMS での編集をコードにコミットし、ビルドをトリガーできます。',
      ko: '이 프로젝트의 git 저장소를 연결하면 CMS 편집 내용을 코드베이스에 커밋하고 빌드를 트리거할 수 있습니다.',
      zh: '关联此项目的 git 仓库，即可将 CMS 中的修改提交回代码库并触发构建。',
      de: 'Verknüpfen Sie das Git-Repository dieses Projekts, damit CMS-Änderungen in Ihren Code committet und Builds ausgelöst werden können.',
      ar: 'اربط مستودع git لهذا المشروع حتى تُرسل تعديلات CMS إلى قاعدة الشيفرة ويمكن تشغيل عمليات البناء.',
      it: 'Collega il repository git di questo progetto per eseguire il commit delle modifiche del CMS nel codice e avviare le build.',
      pt: 'Vincule o repositório git deste projeto para que as edições do CMS sejam enviadas ao seu código e as builds possam ser disparadas.',
      hi: 'इस प्रोजेक्ट की git रिपॉजिटरी लिंक करें ताकि CMS के बदलाव आपके कोड में कमिट हों और बिल्ड ट्रिगर हो सकें।',
      tr: 'CMS düzenlemelerinin kod tabanınıza commit edilmesi ve derlemelerin tetiklenebilmesi için bu projenin git deposunu bağlayın.',
      pl: 'Połącz repozytorium git tego projektu, aby zmiany z CMS trafiały do kodu, a buildy mogły być uruchamiane.',
      id: 'Tautkan repositori git proyek ini agar perubahan di CMS dapat di-commit ke kode Anda dan build dapat dipicu.',
      vi: 'Liên kết kho git của dự án này để các chỉnh sửa trong CMS được commit vào mã nguồn và có thể kích hoạt build.',
      uk: 'Підключіть git-репозиторій проєкту, щоб зміни з CMS комітилися в код, а збірки запускалися.',
    }),
    detectedTitle: t({
      en: 'Detected from your local git remote',
      'en-GB': 'Detected from your local git remote',
      es: 'Detectado desde tu remoto git local',
      fr: 'Détecté depuis votre remote git local',
      ru: 'Обнаружено по локальному git remote',
      ja: 'ローカルの git リモートから検出',
      ko: '로컬 git 원격에서 감지됨',
      zh: '从本地 git 远程仓库检测到',
      de: 'Aus Ihrem lokalen Git-Remote erkannt',
      ar: 'تم اكتشافه من مستودع git البعيد المحلي',
      it: 'Rilevato dal tuo remote git locale',
      pt: 'Detectado a partir do seu remoto git local',
      hi: 'आपके स्थानीय git रिमोट से पहचाना गया',
      tr: 'Yerel git uzak deponuzdan algılandı',
      pl: 'Wykryto na podstawie lokalnego zdalnego repozytorium git',
      id: 'Terdeteksi dari remote git lokal Anda',
      vi: 'Phát hiện từ git remote cục bộ của bạn',
      uk: 'Виявлено з локального git remote',
    }),
    branch: t({
      en: 'Branch',
      'en-GB': 'Branch',
      es: 'Rama',
      fr: 'Branche',
      ru: 'Ветка',
      ja: 'ブランチ',
      ko: '브랜치',
      zh: '分支',
      de: 'Branch',
      ar: 'الفرع',
      it: 'Branch',
      pt: 'Branch',
      hi: 'ब्रांच',
      tr: 'Dal',
      pl: 'Gałąź',
      id: 'Branch',
      vi: 'Nhánh',
      uk: 'Гілка',
    }),
    configFile: t({
      en: 'Configuration file',
      'en-GB': 'Configuration file',
      es: 'Archivo de configuración',
      fr: 'Fichier de configuration',
      ru: 'Файл конфигурации',
      ja: '設定ファイル',
      ko: '구성 파일',
      zh: '配置文件',
      de: 'Konfigurationsdatei',
      ar: 'ملف الإعدادات',
      it: 'File di configurazione',
      pt: 'Arquivo de configuração',
      hi: 'कॉन्फ़िगरेशन फ़ाइल',
      tr: 'Yapılandırma dosyası',
      pl: 'Plik konfiguracyjny',
      id: 'File konfigurasi',
      vi: 'Tệp cấu hình',
      uk: 'Файл конфігурації',
    }),
    finish: cond({
      true: t({
        en: 'Finish',
        'en-GB': 'Finish',
        es: 'Finalizar',
        fr: 'Terminer',
        ru: 'Завершить',
        ja: '完了',
        ko: '완료',
        zh: '完成',
        de: 'Abschließen',
        ar: 'إنهاء',
        it: 'Fine',
        pt: 'Concluir',
        hi: 'समाप्त करें',
        tr: 'Bitir',
        pl: 'Zakończ',
        id: 'Selesai',
        vi: 'Hoàn tất',
        uk: 'Завершити',
      }),
      false: t({
        en: 'Skip for now',
        'en-GB': 'Skip for now',
        es: 'Omitir por ahora',
        fr: 'Passer pour le moment',
        ru: 'Пропустить',
        ja: '今はスキップ',
        ko: '지금은 건너뛰기',
        zh: '暂时跳过',
        de: 'Vorerst überspringen',
        ar: 'تخطَّ الآن',
        it: 'Salta per ora',
        pt: 'Pular por enquanto',
        hi: 'अभी छोड़ें',
        tr: 'Şimdilik atla',
        pl: 'Pomiń na razie',
        id: 'Lewati untuk saat ini',
        vi: 'Bỏ qua lúc này',
        uk: 'Пропустити зараз',
      }),
    }),
  },
  title: 'CLI repository flow',
  description:
    'Content declaration for the CLI repository setup page opened by `intlayer init repository`: connect the git repository of the CMS project and its build settings, then return to the terminal.',
  tags: ['cli', 'repository', 'git', 'build settings'],
} satisfies Dictionary;

export default cliRepositoryFlowContent;
