import { type Dictionary, t } from 'intlayer';

const backupCodeTabContent = {
  key: 'backup-code-tab',
  content: {
    codeLabel: t({
      en: 'Backup Code',
      'en-GB': 'Backup Code',
      fr: 'Code de secours',
      es: 'Código de respaldo',
      de: 'Backup-Code',
      ja: 'バックアップコード',
      ko: '백업 코드',
      zh: '备份代码',
      it: 'Codice di backup',
      pt: 'Código de backup',
      hi: 'बैकअप कोड',
      ar: 'رمز النسخ الاحتياطي',
      ru: 'Резервный код',
      tr: 'Yedekleme Kodu',
      pl: 'Kod zapasowy',
      id: 'Kode Cadangan',
      vi: 'Mã dự phòng',
    }),
    codePlaceholder: t({
      en: 'Enter your backup code',
      'en-GB': 'Enter your backup code',
      fr: 'Entrez votre code de secours',
      es: 'Ingrese su código de respaldo',
      de: 'Geben Sie Ihren Backup-Code ein',
      ja: 'バックアップコードを入力してください',
      ko: '백업 코드를 입력하세요',
      zh: '输入您的备份代码',
      it: 'Inserisci il tuo codice di backup',
      pt: 'Digite seu código de backup',
      hi: 'अपना बैकअप कोड दर्ज करें',
      ar: 'أدخل رمز النسخ الاحتياطي الخاص بك',
      ru: 'Введите ваш резервный код',
      tr: 'Yedekleme kodunuzu girin',
      pl: 'Wprowadź kod zapasowy',
      id: 'Masukkan kode cadangan Anda',
      vi: 'Nhập mã dự phòng của bạn',
    }),
    verifyButton: t({
      en: 'Verify',
      'en-GB': 'Verify',
      fr: 'Vérifier',
      es: 'Verificar',
      de: 'Überprüfen',
      ja: '確認',
      ko: '확인',
      zh: '验证',
      it: 'Verifica',
      pt: 'Verificar',
      hi: 'सत्यापित करें',
      ar: 'تحقق',
      ru: 'Проверить',
      tr: 'Doğrula',
      pl: 'Zweryfikuj',
      id: 'Verifikasi',
      vi: 'Xác minh',
    }),
  },
} satisfies Dictionary;

export default backupCodeTabContent;
