import { type Dictionary, insert, t } from 'intlayer';

const applicationNotRunningViewContent = {
  key: 'application-not-running-view',
  content: {
    connectionError: insert(
      t({
        ar: 'فشل الاتصال بـ {{applicationUrl}}. يرجى التأكد من تشغيل تطبيقك. (الخطأ: {{error}})',
        de: 'Verbindung zu {{applicationUrl}} fehlgeschlagen. Stellen Sie sicher, dass Ihre Anwendung läuft. (Fehler: {{error}})',
        en: 'Failed to connect to {{applicationUrl}}. Please ensure your application is running. (Error: {{error}})',
        'en-GB':
          'Failed to connect to {{applicationUrl}}. Please ensure your application is running. (Error: {{error}})',
        es: 'Error al conectar con {{applicationUrl}}. Asegúrese de que su aplicación se esté ejecutando. (Error: {{error}})',
        fr: "Impossible de se connecter à {{applicationUrl}}. Veuillez vous assurer que votre application est en cours d'exécution. (Erreur : {{error}})",
        hi: '{{applicationUrl}} से कनेक्ट करने में विफल। कृपया सुनिश्चित करें कि आपका एप्लिकेशन चल रहा है। (त्रुटि: {{error}})',
        it: 'Connessione a {{applicationUrl}} fallita. Assicurati che la tua applicazione sia in esecuzione. (Errore: {{error}})',
        ja: '{{applicationUrl}} への接続に失敗しました。アプリケーションが実行されていることを確認してください。(エラー: {{error}})',
        ko: '{{applicationUrl}}에 연결하지 못했습니다. 애플리케이션이 실행 중인지 확인하십시오. (오류: {{error}})',
        pt: 'Falha ao conectar a {{applicationUrl}}. Certifique-se de que sua aplicação está em execução. (Erro: {{error}})',
        ru: 'Не удалось подключиться к {{applicationUrl}}. Убедитесь, что ваше приложение запущено. (Ошибка: {{error}})',
        tr: '{{applicationUrl}} adresine bağlanılamadı. Lütfen uygulamanızın çalıştığından emin olun. (Hata: {{error}})',
        zh: '连接 {{applicationUrl}} 失败。请确保您的应用程序 server 正在运行。(错误: {{error}})',
        pl: 'Nie udało się połączyć z {{applicationUrl}}. Upewnij się, że Twoja aplikacja jest uruchomiona. (Błąd: {{error}})',
        id: 'Gagal terhubung ke {{applicationUrl}}. Pastikan aplikasi Anda sedang berjalan. (Error: {{error}})',
        vi: 'Không thể kết nối với {{applicationUrl}}. Vui lòng đảm bảo ứng dụng của bạn đang chạy. (Lỗi: {{error}})',
        uk: 'Не вдалося підключитися до {{applicationUrl}}. Переконайтеся, що ваша програма запущена. (Помилка: {{error}})',
      })
    ),
    fetchError: insert(
      t({
        ar: 'فشل جلب تطبيق العميل. حالة الاستجابة: {{status}} {{statusText}}',
        de: 'Abrufen der Client-Anwendung fehlgeschlagen. Antwortstatus: {{status}} {{statusText}}',
        en: 'Failed to fetch client application. Response status: {{status}} {{statusText}}',
        'en-GB':
          'Failed to fetch client application. Response status: {{status}} {{statusText}}',
        es: 'Error al obtener la aplicação cliente. Estado de la resposta: {{status}} {{statusText}}',
        fr: 'Échec de la récupération de l’application client. Statut de la réponse : {{status}} {{statusText}}',
        hi: 'क्लाइंट एप्लिकेशन प्राप्त करने में विफल। प्रतिक्रिया स्थिति: {{status}} {{statusText}}',
        it: 'Impossibile recuperare l’applicazione client. Stato della risposta: {{status}} {{statusText}}',
        ja: 'クライアントアプリケーションの取得に失敗しました。レスポンスステータス: {{status}} {{statusText}}',
        ko: '클라이언트 애플리케이션을 가져오지 못했습니다. 응답 상태: {{status}} {{statusText}}',
        pt: 'Falha ao buscar a aplicação cliente. Status da resposta: {{status}} {{statusText}}',
        ru: 'Не удалось загрузить клиентское приложение. Статус ответа: {{status}} {{statusText}}',
        tr: 'İmci uygulaması alınamadı. Yanıt durumu: {{status}} {{statusText}}',
        zh: '获取客户端应用程序失败。响应状态: {{status}} {{statusText}}',
        pl: 'Nie udało się pobrać aplikacji klienckiej. Status odpowiedzi: {{status}} {{statusText}}',
        id: 'Gagal mengambil aplikasi klien. Status respons: {{status}} {{statusText}}',
        vi: 'Không thể tải ứng dụng khách. Trạng thái phản hồi: {{status}} {{statusText}}',
        uk: 'Не вдалося завантажити клієнтський додаток. Статус відповіді: {{status}} {{statusText}}',
      })
    ),
    title: t({
      ar: 'التطبيق غير متاح',
      de: 'Ihre Anwendung ist nicht zugänglich',
      en: 'Your application is not accessible',
      'en-GB': 'Your application is not accessible',
      es: 'Tu aplicación no está accesible',
      fr: "Votre application n'est pas accessible",
      hi: 'आपका एप्लिकेशन पहुंच नहीं है',
      it: 'La tua applicazione non è accessibile',
      ja: 'あなたのアプリケーションはアクセスできません',
      ko: '당신의 앱은 접근할 수 없습니다.',
      pt: 'Sua aplicação não está acessível',
      ru: 'Ваше приложение не доступно',
      tr: 'Uygulamanız erişilebilir değil',
      zh: '您的应用程序无法访问',
      pl: 'Twoja aplikacja jest niedostępna',
      id: 'Aplikasi Anda tidak dapat diakses',
      vi: 'Ứng dụng của bạn không thể truy cập được',
      uk: 'Ваш додаток недоступний',
    }),
    description: t({
      ar: 'لاستخدام محرك المحتوى، يجب عليك التأكد من أن التطبيق يعمل.',
      de: 'Um den CMS zu verwenden, müssen Sie sicherstellen, dass die Anwendung läuft.',
      en: 'To use the CMS, you need to ensure that the application is running.',
      'en-GB':
        'To use the CMS, you need to ensure that the application is running.',
      es: 'Para usar el CMS, debe asegurarse de que la aplicación esté en ejecución.',
      fr: 'Pour utiliser le CMS, vous devez vous assurer que l’application est en cours d’exécution.',
      hi: 'CMS का उपयोग करने के लिए, आपको यह सुनिश्चित करना होगा कि एप्लिकेशन चल रहा है।',
      it: 'Per utilizzare il CMS, è necessario assicurarsi che l’applicazione sia in esecuzione.',
      ja: 'CMS を使用するには、アプリケーションが実行されていることを確認する必要があります。',
      ko: 'CMS를 사용하려면 앱이 실행되고 있는지 확인해야 합니다.',
      pt: 'Para usar o CMS, você precisa garantir que a aplicação esteja em execução.',
      ru: 'Чтобы использовать CMS, вам необходимо убедиться, что приложение работает.',
      tr: "CMS'yi kullanmak için uygulamanın çalıştığından emin olmanız gerekir.",
      zh: '要使用 CMS，您需要确保应用程序正在运行。',
      pl: 'Aby korzystać z CMS, upewnij się, że aplikacja jest uruchomiona.',
      id: 'Untuk menggunakan CMS, pastikan aplikasi sedang berjalan.',
      vi: 'Để sử dụng CMS, bạn cần đảm bảo ứng dụng đang chạy.',
      uk: 'Щоб використовувати CMS, переконайтеся, що додаток працює.',
    }),
    urlLabel: t({
      ar: 'رابط تطبيق العميل:',
      de: 'URL der Client-Anwendung:',
      en: 'Client Application URL:',
      'en-GB': 'Client Application URL:',
      es: 'URL de la aplicación cliente:',
      fr: 'URL de l’application client :',
      hi: 'क्लाइंट एप्लिकेशन यूआरएल:',
      it: 'URL dell’applicazione client:',
      ja: 'クライアントアプリケーションのURL:',
      ko: '클라이언트 애플리케이션 URL:',
      pt: 'URL da aplicação cliente:',
      ru: 'URL клиентского приложения:',
      tr: 'İstemci Uygulama URL’si:',
      zh: '客户端应用程序 URL:',
      pl: 'URL aplikacji klienckiej:',
      id: 'URL aplikasi klien:',
      vi: 'URL ứng dụng khách:',
      uk: 'URL клієнтського додатка:',
    }),
    urlLinkLabel: t({
      ar: 'رابط التطبيق',
      de: 'Anwendungs-URL',
      en: 'Application URL',
      'en-GB': 'Application URL',
      es: 'URL de la aplicación',
      fr: "URL de l'application",
      hi: 'एप्लिकेशन यूआरएल',
      it: "URL dell'applicazione",
      ja: 'アプリケーションURL',
      ko: '애플리케이션 URL',
      pt: 'URL da aplicação',
      ru: 'URL приложения',
      tr: "Uygulama URL'si",
      zh: '应用程序 URL',
      pl: 'URL aplikacji',
      id: 'URL aplikasi',
      vi: 'URL ứng dụng',
      uk: 'URL додатка',
    }),
    tipsTitle: t({
      ar: 'نصائح:',
      de: 'Tipps:',
      en: 'Tips:',
      'en-GB': 'Tips:',
      es: 'Consejos:',
      fr: 'Conseils :',
      hi: 'सुझाव:',
      it: 'Suggerimenti:',
      ja: 'ヒント:',
      ko: '팁:',
      pt: 'Dicas:',
      ru: 'Советы:',
      tr: 'İpuçları:',
      zh: '提示:',
      pl: 'Wskazówki:',
      id: 'Tips:',
      vi: 'Gợi ý:',
      uk: 'Поради:',
    }),
    tips: insert(
      t({
        en: [
          'Ensure the `editor.cmsUrl` configuration field is set to `{{editorUrl}}`.',
          'Ensure the `editor.applicationUrl` configuration field is set to `{{applicationUrl}}`.',
          "Ensure the CSP ('Content-Security-Policy') header does not block the editor's iframe (Required: `frame-ancestors` and `connect-src`). Check the console (F12) for more details.",
        ],
        'en-GB': [
          'Ensure the `editor.cmsUrl` configuration field is set to `{{editorUrl}}`.',
          'Ensure the `editor.applicationUrl` configuration field is set to `{{applicationUrl}}`.',
          "Ensure the CSP ('Content-Security-Policy') header does not block the editor's iframe (Required: `frame-ancestors` and `connect-src`). Check the console (F12) for more details.",
        ],
        fr: [
          'Assurez-vous que le champ de configuration `editor.cmsUrl` est défini sur `{{editorUrl}}`.',
          'Assurez-vous que le champ de configuration `editor.applicationUrl` est défini sur `{{applicationUrl}}`.',
          "Assurez-vous que l'en-tête CSP ('Content-Security-Policy') ne bloque pas l'iframe de l'éditeur (Requis : `frame-ancestors` et `connect-src`). Vérifiez la console (F12) pour plus de détails.",
        ],
        es: [
          'Asegúrese de que el campo de configuración `editor.cmsUrl` esté establecido en `{{editorUrl}}`.',
          'Asegúrese de que el campo de configuración `editor.applicationUrl` esté establecido en `{{applicationUrl}}`.',
          "Asegúrese de que el encabezado CSP ('Content-Security-Policy') no bloquee el iframe del editor (Requerido: `frame-ancestors` y `connect-src`). Verifique la consola (F12) para más detalles.",
        ],
        de: [
          'Stellen Sie sicher, dass das Konfigurationsfeld `editor.cmsUrl` auf `{{editorUrl}}` gesetzt ist.',
          'Stellen Sie sicher, dass das Konfigurationsfeld `editor.applicationUrl` auf `{{applicationUrl}}` gesetzt ist.',
          "Stellen Sie sicher, dass der CSP-Header ('Content-Security-Policy') das Iframe des Editors nicht blockiert (Erforderlich: `frame-ancestors` und `connect-src`). Überprüfen Sie die Konsole (F12) für weitere Details.",
        ],
        it: [
          'Assicurati che il campo di configurazione `editor.cmsUrl` sia impostato su `{{editorUrl}}`.',
          'Assicurati che il campo di configurazione `editor.applicationUrl` sia impostato su `{{applicationUrl}}`.',
          "Assicurati che l'intestazione CSP ('Content-Security-Policy') non blocchi l'iframe dell'editor (Richiesto: `frame-ancestors` e `connect-src`). Controlla la console (F12) per maggiori dettagli.",
        ],
        ja: [
          '`editor.cmsUrl`設定フィールドが`{{editorUrl}}`に設定されていることを確認してください。',
          '`editor.applicationUrl`設定フィールドが`{{applicationUrl}}`に設定されていることを確認してください。',
          "CSP（'Content-Security-Policy'）ヘッダーがエディターのiframeをブロックしていないことを確認してください（必須：`frame-ancestors`および`connect-src`）。詳細はコンソール（F12）を確認してください。",
        ],
        ko: [
          '`editor.cmsUrl` 설정 필드가 `{{editorUrl}}`로 설정되어 있는지 확인하세요.',
          '`editor.applicationUrl` 설정 필드가 `{{applicationUrl}}`로 설정되어 있는지 확인하세요.',
          "CSP('Content-Security-Policy') 헤더가 에디터의 iframe을 차단하지 않는지 확인하세요(필수: `frame-ancestors` 및 `connect-src`). 자세한 내용은 콘솔(F12)을 확인하세요.",
        ],
        zh: [
          '确保 `editor.cmsUrl` 配置字段设置为 `{{editorUrl}}`。',
          '确保 `editor.applicationUrl` 配置字段设置为 `{{applicationUrl}}`。',
          "确保 CSP（'Content-Security-Policy'）标头不会阻止编辑器的 iframe（必需：`frame-ancestors` 和 `connect-src`）。查看控制台（F12）以获取更多详细信息。",
        ],
        pt: [
          'Certifique-se de que o campo de configuração `editor.cmsUrl` esteja definido como `{{editorUrl}}`.',
          'Certifique-se de que o campo de configuração `editor.applicationUrl` esteja definido como `{{applicationUrl}}`.',
          "Certifique-se de que o cabeçalho CSP ('Content-Security-Policy') não bloqueie o iframe do editor (Obrigatório: `frame-ancestors` e `connect-src`). Verifique a console (F12) para mais detalhes.",
        ],
        ru: [
          'Убедитесь, что поле конфигурации `editor.cmsUrl` установлено на `{{editorUrl}}`.',
          'Убедитесь, что поле конфигурации `editor.applicationUrl` установлено на `{{applicationUrl}}`.',
          "Убедитесь, что заголовок CSP ('Content-Security-Policy') не блокирует iframe редактора (Требуется: `frame-ancestors` и `connect-src`). Проверьте консоль (F12) для получения дополнительных сведений.",
        ],
        ar: [
          'تأكد من تعيين حقل التكوين `editor.cmsUrl` إلى `{{editorUrl}}`.',
          'تأكد من تعيين حقل التكوين `editor.applicationUrl` إلى `{{applicationUrl}}`.',
          "تأكد من أن ترويسة CSP ('Content-Security-Policy') لا تحظر إطار iframe الخاص بالمحرر (مطلوب: `frame-ancestors` و `connect-src`). تحقق من وحدة التحكم (F12) لمزيد من التفاصيل.",
        ],
        hi: [
          'सुनिश्चित करें कि `editor.cmsUrl` कॉन्फ़िगरेशन फ़ील्ड `{{editorUrl}}` पर सेट है।',
          'सुनिश्चित करें कि `editor.applicationUrl` कॉन्फ़िगरेशन फ़ील्ड `{{applicationUrl}}` पर सेट है।',
          "सुनिश्चित करें कि CSP ('Content-Security-Policy') हेडर संपादक के iframe को ब्लॉक नहीं करता है (आवश्यक: `frame-ancestors` और `connect-src`)। अधिक जानकारी के लिए कंसोल (F12) की जांच करें।",
        ],
        tr: [
          '`editor.cmsUrl` yapılandırma alanının `{{editorUrl}}` olarak ayarlandığından emin olun.',
          '`editor.applicationUrl` yapılandırma alanının `{{applicationUrl}}` olarak ayarlandığından emin olun.',
          "CSP ('Content-Security-Policy') başlığının düzenleyicinin iframe'ini engellemediğinden emin olun (Gerekli: `frame-ancestors` ve `connect-src`). Daha fazla detay için konsolu (F12) kontrol edin.",
        ],
        pl: [
          'Upewnij się, że pole konfiguracji `editor.cmsUrl` jest ustawione na `{{editorUrl}}`.',
          'Upewnij się, że pole konfiguracji `editor.applicationUrl` jest ustawione na `{{applicationUrl}}`.',
          "Upewnij się, że nagłówek CSP ('Content-Security-Policy') nie blokuje ramki iframe edytora (Wymagane: `frame-ancestors` i `connect-src`). Sprawdź konsolę (F12), aby uzyskać więcej szczegółów.",
        ],
        id: [
          'Pastikan bidang konfigurasi `editor.cmsUrl` diatur ke `{{editorUrl}}`.',
          'Pastikan bidang konfigurasi `editor.applicationUrl` diatur ke `{{applicationUrl}}`.',
          "Pastikan header CSP ('Content-Security-Policy') tidak memblokir iframe editor (Diperlukan: `frame-ancestors` dan `connect-src`). Periksa konsol (F12) untuk detail lebih lanjut.",
        ],
        vi: [
          'Đảm bảo trường cấu hình `editor.cmsUrl` được đặt thành `{{editorUrl}}`.',
          'Đảm bảo trường cấu hình `editor.applicationUrl` được đặt thành `{{applicationUrl}}`.',
          "Đảm bảo tiêu đề CSP ('Content-Security-Policy') không chặn iframe của trình chỉnh sửa (Bắt buộc: `frame-ancestors` và `connect-src`). Kiểm tra bảng điều khiển (F12) để biết thêm chi tiết.",
        ],
        uk: [
          'Переконайтеся, що поле конфігурації `editor.cmsUrl` встановлено на `{{editorUrl}}`.',
          'Переконайтеся, що поле конфігурації `editor.applicationUrl` встановлено на `{{applicationUrl}}`.',
          "Переконайтеся, що заголовок CSP ('Content-Security-Policy') не блокує iframe редактора (Потрібно: `frame-ancestors` та `connect-src`). Перевірте консоль (F12) для отримання додаткової інформації.",
        ],
      })
    ),
    documentationLink: {
      label: t({
        en: 'Click to go to the CMS documentation',
        'en-GB': 'Click to go to the CMS documentation',
        fr: 'Cliquez ici pour accéder à la documentation du CMS',
        es: 'Haga clic aquí para acceder a la documentación del CMS',
        de: 'Klicken Sie hier, um die CMS-Dokumentation zu besuchen',
        ja: 'CMS ドキュメントに移動するには、ここをクリックしてください',
        ko: 'CMS 문서로 이동하려면 여기를 클릭하십시오.',
        zh: '点击此处访问 CMS 文档',
        pt: 'Clique aqui para acessar a documentação do CMS',
        ru: 'Нажмите, чтобы перейти к документации CMS',
        ar: 'انقر هنا للوصول إلى وثائق محرك المحتوى',
        hi: 'क्या आप CMS के डॉक्यूमेंट पर जाना चाहते हैं?',
        it: 'Fai clic qui per accedere alla documentazione del CMS',
        tr: 'CMS belgelerine gitmek için tıklayın',
        pl: 'Kliknij, aby przejść do dokumentacji CMS',
        id: 'Klik untuk membuka dokumentasi CMS',
        vi: 'Nhấp để xem tài liệu CMS',
        uk: 'Натисніть, щоб перейти до документації CMS',
      }),
      text: t({
        en: 'See how to configure the CMS',
        'en-GB': 'See how to configure the CMS',
        fr: 'Voir comment configurer le CMS',
        de: 'Siehe, wie man den CMS konfiguriert',
        ar: 'انظر كيفية تكوين محرك المحتوى',
        hi: 'CMS को कॉन्फ़िगर करने के बारे में देखें',
        it: 'Vedi come configurare il CMS',
        ja: 'CMSの設定方法を見る',
        ru: 'Смотрите, как настроить CMS',
        es: 'Vea cómo configurar el CMS',
        pt: 'Veja como configurar o CMS',
        ko: 'CMS 설정 방법을 보십시오',
        zh: '查看如何配置CMS',
        tr: "CMS'yi nasıl yapılandıracağınızı görün",
        pl: 'Zobacz, jak skonfigurować CMS',
        id: 'Lihat cara mengonfigurasi CMS',
        vi: 'Xem cách cấu hình CMS',
        uk: 'Дізнайтеся, як налаштувати CMS',
      }),
    },
  },
  title: 'Application not running view',
  description:
    'UI content shown when the connected application is not accessible. Provides guidance to properly configure the CMS connection, including local and remote setup instructions, and CSP header requirements.',
  tags: ['error state', 'CMS setup', 'application connection'],
} satisfies Dictionary;

export default applicationNotRunningViewContent;
