import { type Dictionary, insert, t } from 'intlayer';

const dashboardSidebarContent = {
  key: 'dashboard-sidebar',
  content: {
    collapseButton: {
      text: t({
        en: 'Collapse',
        fr: 'Réduire',
        es: 'Colapsar',
        'en-GB': 'Collapse',
        de: 'Zuklappen',
        ja: '折りたたむ',
        ko: '사이드바 접기',
        zh: '折叠侧边栏',
        it: 'Comprimi',
        pt: 'Recolher',
        hi: 'संकुचित करें',
        ar: 'اطوي',
        ru: 'Свернуть',
        tr: 'Daralt',
        pl: 'Zwiń',
        id: 'Sembunyikan',
        vi: 'Thu gọn',
        uk: 'Згорнути',
      }),
      label: t({
        en: 'Collapse sidebar',
        fr: 'Réduire la barre latérale',
        es: 'Colapsar barra lateral',
        'en-GB': 'Collapse sidebar',
        de: 'Seitenleiste zuklappen',
        ja: 'サイドバーを折りたたむ',
        ko: '사이드바 접기',
        zh: '折叠侧边栏',
        it: 'Comprimi barra laterale',
        pt: 'Recolher barra lateral',
        hi: 'साइडबार संकुचित करें',
        ar: 'اطوي الشريط الجانبي',
        ru: 'Свернуть боковую панель',
        tr: 'Kenar çubuğunu daralt',
        pl: 'Zwiń pasek boczny',
        id: 'Sembunyikan sidebar',
        vi: 'Thu gọn thanh bên',
        uk: 'Згорнути бічну панель',
      }),
    },

    navigation: {
      editor: {
        label: t({
          en: 'Go to Intlayer visual editor',
          'en-GB': 'Go to Intlayer visual editor',
          fr: "Aller sur l'éditeur visuel Intlayer",
          es: 'Ir al editor visual de Intlayer',
          de: 'Gehen Sie zum Intlayer-Visual-Editor',
          ja: 'Intlayer ビジュアルエディタに行く',
          ko: 'Intlayer 비주얼 편집기로 이동',
          zh: '转到 Intlayer 可视化编辑器',
          it: "Vai all'editor visivo di Intlayer",
          pt: 'Ir para o editor visual do Intlayer',
          hi: 'Intlayer विज़ुअल एडिटर पर जाएं',
          ar: 'اذهب إلى المحرر المرئي لـ Intlayer',
          ru: 'Перейти к визуальному редактору Intlayer',
          tr: 'Intlayer görsel düzenleyicisine git',
          pl: 'Przejdź do wizualnego edytora Intlayer',
          id: 'Buka Intlayer visual editor',
          vi: 'Mở trình chỉnh sửa trực quan Intlayer',
          uk: 'Перейти до візуального редактора Intlayer',
        }),
        title: t({
          en: 'Editor',
          'en-GB': 'Editor',
          fr: 'Éditeur',
          es: 'Editor',
          de: 'Editor',
          ja: 'エディタ',
          ko: '편집기',
          zh: '编辑器',
          it: 'Editor',
          pt: 'Editor',
          hi: 'संपादक',
          ar: 'محرر',
          ru: 'Редактор',
          tr: 'Editör',
          pl: 'Edytor',
          id: 'Editor',
          vi: 'Trình chỉnh sửa',
          uk: 'Редактор',
        }),
      },
      translate: {
        label: t({
          en: 'Go to translate dashboard',
          'en-GB': 'Go to translate dashboard',
          fr: 'Aller sur le tableau de bord de traduction',
          es: 'Ir al tablero de traducción',
          de: 'Gehen Sie zum Übersetzungs-Dashboard',
          ja: '翻訳ダッシュボードに行く',
          ko: '번역 대시보드로 이동',
          zh: '转到翻译仪表板',
          it: 'Vai alla dashboard di traduzione',
          pt: 'Ir para o painel de tradução',
          hi: 'अनुवाद डैशबोर्ड पर जाएं',
          ar: 'اذهب إلى لوحة معلومات الترجمة',
          ru: 'Перейти к панели управления переводом',
          tr: "Çeviri Dashboard'ına git",
          pl: 'Przejdź do panelu tłumaczeń',
          id: 'Buka dashboard Translate',
          vi: 'Đi tới bảng điều khiển dịch thuật',
          uk: 'Перейти до панелі перекладів',
        }),
        title: t({
          en: 'Translate',
          'en-GB': 'Translate',
          fr: 'Traduire',
          es: 'Traducir',
          de: 'Übersetzen',
          ja: '翻訳',
          ko: '번역',
          zh: '翻译',
          it: 'Traduci',
          pt: 'Traduzir',
          hi: 'अनुवाद',
          ar: 'ترجمة',
          ru: 'Перевод',
          tr: 'Çevir',
          pl: 'Tłumacz',
          id: 'Translate',
          vi: 'Dịch',
          uk: 'Переклад',
        }),
      },
      dictionaries: {
        label: t({
          en: 'Go to dictionaries dashboard',
          'en-GB': 'Go to dictionaries dashboard',
          fr: 'Aller sur le tableau de bord des dictionnaires',
          es: 'Ir al tablero de diccionarios',
          de: 'Gehen Sie zum Wörterbuch-Dashboard',
          ja: '辞書ダッシュボードに行く',
          ko: '사전 대시보드로 이동',
          zh: '转到字典仪表板',
          it: 'Vai alla dashboard dei dizionari',
          pt: 'Ir para o painel de dicionários',
          hi: 'शब्दकोश डैशबोर्ड पर जाएं',
          ar: 'اذهب إلى لوحة معلومات القواميس',
          ru: 'Перейти к панели управления словарями',
          tr: "Sözlük Dashboard'ına git",
          pl: 'Przejdź do panelu słowników',
          id: 'Buka dashboard Dictionaries',
          vi: 'Đi tới bảng điều khiển từ điển',
          uk: 'Перейти до панелі словників',
        }),
        title: t({
          en: 'Dictionaries',
          'en-GB': 'Dictionaries',
          fr: 'Dictionnaires',
          es: 'Diccionarios',
          de: 'Wörterbücher',
          ja: '辞書',
          ko: '사전',
          zh: '字典',
          it: 'Dizionari',
          pt: 'Dicionários',
          hi: 'शब्दकोश',
          ar: 'قواميس',
          ru: 'Словари',
          tr: 'Sözlükler',
          pl: 'Słowniki',
          id: 'Dictionaries',
          vi: 'Từ điển',
          uk: 'Словники',
        }),
      },
      content: {
        label: t({
          en: 'Go to content dashboard',
          'en-GB': 'Go to content dashboard',
          fr: 'Aller sur le tableau de bord de contenu',
          es: 'Ir al tablero de contenido',
          de: 'Gehen Sie zum Inhaltsdashboard',
          ja: 'コンテンツダッシュボードに行く',
          ko: '콘텐츠 대시보드로 이동',
          zh: '转到内容仪表板',
          it: 'Vai alla dashboard dei contenuti',
          pt: 'Ir para o painel de conteúdo',
          hi: 'सामग्री डैशबोर्ड पर जाएं',
          ar: 'اذهب إلى لوحة معلومات المحتوى',
          ru: 'Перейти к панели управления контентом',
          tr: "İçerik Dashboard'ına git",
          pl: 'Przejdź do panelu zawartości',
          id: 'Buka dashboard Content',
          vi: 'Đi tới bảng điều khiển nội dung',
          uk: 'Перейти до панелі вмісту',
        }),
        title: t({
          en: 'Content',
          'en-GB': 'Content',
          fr: 'Contenu',
          es: 'Contenido',
          de: 'Inhalt',
          ja: 'コンテンツ',
          ko: '콘텐츠',
          zh: '内容',
          it: 'Contenuto',
          pt: 'Conteúdo',
          hi: 'सामग्री',
          ar: 'محتوى',
          ru: 'Содержание',
          tr: 'İçerik',
          pl: 'Zawartość',
          id: 'Content',
          vi: 'Nội dung',
          uk: 'Вміст',
        }),
      },
      tags: {
        label: t({
          en: 'Go to tags dashboard',
          'en-GB': 'Go to tags dashboard',
          fr: 'Aller sur le tableau de bord des tags',
          es: 'Ir al tablero de etiquetas',
          de: 'Gehen Sie zum Tags-Dashboard',
          ja: 'タグダッシュボードに行く',
          ko: '태그 대시보드로 이동',
          zh: '转到标签仪表板',
          it: 'Vai alla dashboard dei tag',
          pt: 'Ir para o painel de tags',
          hi: 'टैग डैशबोर्ड पर जाएं',
          ar: 'اذهب إلى لوحة معلومات الوسوم',
          ru: 'Перейти к панели управления тегами',
          tr: "Etiket Dashboard'ına git",
          pl: 'Przejdź do panelu tagów',
          id: 'Buka dashboard Tags',
          vi: 'Đi tới bảng điều khiển thẻ',
          uk: 'Перейти до панелі тегів',
        }),
        title: t({
          en: 'Tags',
          'en-GB': 'Tags',
          fr: 'Tags',
          es: 'Etiquetas',
          de: 'Tags',
          ja: 'タグ',
          ko: '태그',
          zh: '标签',
          it: 'Tag',
          pt: 'Tags',
          hi: 'टैग',
          ar: 'وسوم',
          ru: 'Теги',
          tr: 'Etiketler',
          pl: 'Tagi',
          id: 'Tags',
          vi: 'Thẻ',
          uk: 'Теги',
        }),
      },
      scanner: {
        label: t({
          en: 'Go to i18n SEO Scanner',
          'en-GB': 'Go to i18n SEO Scanner',
          fr: 'Aller sur le Scanner i18n SEO',
          es: 'Ir al Escáner i18n SEO',
          de: 'Zum i18n SEO Scanner gehen',
          ja: 'i18n SEOスキャナーに移動',
          ko: 'i18n SEO 스캐너로 이동',
          zh: '转到 i18n SEO 扫描仪',
          it: 'Vai allo Scanner i18n SEO',
          pt: 'Ir para o Scanner i18n SEO',
          hi: 'i18n SEO स्कैनर पर जाएं',
          ar: 'اذهب إلى ماسح i18n SEO',
          ru: 'Перейти к сканеру i18n SEO',
          tr: 'i18n SEO Tarayıcıya git',
          pl: 'Przejdź do Skanera i18n SEO',
          id: 'Buka Pemindai i18n SEO',
          vi: 'Đi tới Trình quét i18n SEO',
          uk: 'Перейти до сканера i18n SEO',
        }),
        title: t({
          en: 'Scanner',
          'en-GB': 'Scanner',
          fr: 'Scanner',
          es: 'Escáner',
          de: 'Scanner',
          ja: 'スキャナー',
          ko: '스캐너',
          zh: '扫描仪',
          it: 'Scanner',
          pt: 'Scanner',
          hi: 'स्कैनर',
          ar: 'ماسح',
          ru: 'Сканер',
          tr: 'Tarayıcı',
          pl: 'Skaner',
          id: 'Pemindai',
          vi: 'Trình quét',
          uk: 'Сканер',
        }),
      },
      ide: {
        label: t({
          en: 'Go to IDE',
          'en-GB': 'Go to IDE',
          fr: "Aller sur l'IDE",
          es: 'Ir al IDE',
          de: 'Gehen Sie zum IDE',
          ja: 'IDEに移動',
          ko: 'IDE로 이동',
          zh: '转到 IDE',
          it: "Vai all'IDE",
          pt: 'Ir para o IDE',
          hi: 'IDE पर जाएं',
          ar: 'اذهب إلى IDE',
          ru: 'Перейти к IDE',
          tr: "IDE'ye git",
          pl: 'Przejdź do IDE',
          id: 'Buka IDE',
          vi: 'Đi tới IDE',
          uk: 'Перейти до IDE',
        }),
        title: 'IDE',
      },
      projects: {
        label: t({
          en: 'Go to projects dashboard',
          'en-GB': 'Go to projects dashboard',
          fr: 'Aller sur le tableau de bord des projets',
          es: 'Ir al tablero de proyectos',
          de: 'Gehen Sie zum Projekt-Dashboard',
          ja: 'プロジェクトダッシュボードに行く',
          ko: '프로젝트 대시보드로 이동',
          zh: '转到项目仪表板',
          it: 'Vai alla dashboard dei progetti',
          pt: 'Ir para o painel de projetos',
          hi: 'परियोजना डैशबोर्ड पर जाएं',
          ar: 'اذهب إلى لوحة معلومات المشاريع',
          ru: 'Перейти к панели управления проектами',
          tr: "Proje Dashboard'ına git",
          pl: 'Przejdź do panelu projektów',
          id: 'Buka dashboard Projects',
          vi: 'Đi tới bảng điều khiển dự án',
          uk: 'Перейти до панелі проєктів',
        }),
        title: t({
          en: 'Projects',
          'en-GB': 'Projects',
          fr: 'Projets',
          es: 'Proyectos',
          de: 'Projekte',
          ja: 'プロジェクト',
          ko: '프로젝트',
          zh: '项目',
          it: 'Progetti',
          pt: 'Projetos',
          hi: 'परियोजनाएँ',
          ar: 'مشاريع',
          ru: 'Проекты',
          tr: 'Projeler',
          pl: 'Projekty',
          id: 'Projects',
          vi: 'Dự án',
          uk: 'Проєкти',
        }),
      },
      organization: {
        label: t({
          en: 'Go to organization dashboard',
          'en-GB': 'Go to organization dashboard',
          fr: "Aller sur le tableau de bord de l'organisation",
          es: 'Ir al tablero de organización',
          de: 'Gehen Sie zum Organisationsdashboard',
          ja: '組織のダッシュボードに行く',
          ko: '조직 대시보드로 이동',
          zh: '转到组织仪表板',
          it: "Vai alla dashboard dell'organizzazione",
          pt: 'Ir para o painel de organização',
          hi: 'संगठन डैशबोर्ड पर जाएं',
          ar: 'اذهب إلى لوحة معلومات المؤسسة',
          ru: 'Перейти к панели управления организацией',
          tr: "Organizasyon Dashboard'ına git",
          pl: 'Przejdź do panelu organizacji',
          id: 'Buka dashboard Organization',
          vi: 'Đi tới bảng điều khiển tổ chức',
          uk: 'Перейти до панелі організації',
        }),
        title: t({
          en: 'Organization',
          'en-GB': 'Organization',
          fr: 'Organisation',
          es: 'Organización',
          de: 'Organisation',
          ja: '組織',
          ko: '조직',
          zh: '组织',
          it: 'Organizzazione',
          pt: 'Organização',
          hi: 'संगठन',
          ar: 'تنظيم',
          ru: 'Организация',
          tr: 'Organizasyon',
          pl: 'Organizacja',
          id: 'Organization',
          vi: 'Tổ chức',
          uk: 'Організація',
        }),
      },
      admin: {
        label: t({
          en: 'Go to admin panel',
          'en-GB': 'Go to admin panel',
          fr: "Aller sur le panneau d'administration",
          es: 'Ir al panel de administración',
          de: 'Gehen Sie zum Admin-Panel',
          ja: '管理パネルに行く',
          ko: '관리자 패널로 이동',
          zh: '转到管理面板',
          it: 'Vai al pannello di amministrazione',
          pt: 'Ir para o painel de administração',
          hi: 'एडमिन पैनल पर जाएं',
          ar: 'اذهب إلى لوحة الإدارة',
          ru: 'Перейти к панели администратора',
          tr: 'Admin paneline git',
          pl: 'Przejdź do panelu administratora',
          id: 'Buka panel Admin',
          vi: 'Đi tới bảng quản trị',
          uk: 'Перейти до панелі адміністратора',
        }),
        title: t({
          en: 'Admin',
          'en-GB': 'Admin',
          fr: 'Administration',
          es: 'Administración',
          de: 'Administration',
          ja: '管理',
          ko: '관리자',
          zh: '管理',
          it: 'Amministrazione',
          pt: 'Administração',
          hi: 'एडमिन',
          ar: 'إدارة',
          ru: 'Администрирование',
          tr: 'Yönetim',
          pl: 'Administracja',
          id: 'Admin',
          vi: 'Quản trị',
          uk: 'Адміністрування',
        }),
      },
      project: {
        title: t({
          en: 'Project',
          'en-GB': 'Project',
          fr: 'Projet',
          es: 'Proyecto',
          de: 'Projekt',
          ja: 'プロジェクト',
          ko: '프로젝트',
          zh: '项目',
          it: 'Progetto',
          pt: 'Projeto',
          hi: 'परियोजना',
          ar: 'مشروع',
          ru: 'Проект',
          tr: 'Proje',
          pl: 'Projekt',
          id: 'Proyek',
          vi: 'Dự án',
          uk: 'Проєкт',
        }),
      },
      logout: {
        text: t({
          en: 'Logout',
          fr: 'Se déconnecter',
          es: 'Cerrar sesión',
          'en-GB': 'Logout',
          de: 'Abmelden',
          ja: 'ログアウト',
          ko: '로그아웃',
          zh: '登出',
          it: 'Disconnettersi',
          pt: 'Sair',
          hi: 'लॉग आउट',
          ar: 'تسجيل الخروج',
          ru: 'Выйти',
          tr: 'Çıkış Yap',
          pl: 'Wyloguj się',
          id: 'Keluar',
          vi: 'Đăng xuất',
          uk: 'Вийти',
        }),
        label: t({
          en: 'Click to logout',
          fr: 'Cliquez pour vous déconnecter',
          es: 'Haga clic para cerrar sesión',
          'en-GB': 'Click to logout',
          de: 'Klicken Sie, um sich abzumelden',
          ja: 'ログアウトするにはクリックしてください',
          ko: '로그아웃하려면 클릭하세요',
          zh: '点击登出',
          it: 'Clicca per disconnetterti',
          pt: 'Clique para sair',
          hi: 'लॉग आउट करने के लिए क्लिक करें',
          ar: 'انقر لتسجيل الخروج',
          ru: 'Нажмите, чтобы выйти',
          tr: 'Çıkış yapmak için tıklayın',
          pl: 'Kliknij, aby się wylogować',
          id: 'Klik untuk keluar',
          vi: 'Nhấp để đăng xuất',
          uk: 'Натисніть, щоб вийти',
        }),
      },
      viewProfile: {
        text: t({
          en: 'View Profile',
          fr: 'Voir le profil',
          es: 'Ver perfil',
          'en-GB': 'View Profile',
          de: 'Profil anzeigen',
          ja: 'プロフィールを表示',
          ko: '프로필 보기',
          zh: '查看个人资料',
          it: 'Visualizza profilo',
          pt: 'Visualizar perfil',
          hi: 'प्रोफ़ाइल देखें',
          ar: 'عرض الملف الشخصي',
          ru: 'Посмотреть профиль',
          tr: 'Profili Görüntüle',
          pl: 'Pokaż profil',
          id: 'Lihat Profil',
          vi: 'Xem hồ sơ',
          uk: 'Переглянути профіль',
        }),
        label: t({
          en: 'Click to view your profile',
          fr: 'Cliquez pour voir votre profil',
          es: 'Haga clic para ver su perfil',
          'en-GB': 'Click to view your profile',
          de: 'Klicken Sie, um Ihr Profil anzuzeigen',
          ja: 'プロフィールを表示するにはクリックしてください',
          ko: '프로필을 보려면 클릭하세요',
          zh: '点击查看您的个人资料',
          it: 'Clicca per visualizzare il tuo profilo',
          pt: 'Clique para visualizar seu perfil',
          hi: 'अपनी प्रोफ़ाइल देखने के लिए क्लिक करें',
          ar: 'انقر لعرض ملفك الشخصي',
          ru: 'Нажмите, чтобы посмотреть свой профиль',
          tr: 'Profilinizi görüntülemek için tıklayın',
          pl: 'Kliknij, aby zobaczyć swój profil',
          id: 'Klik untuk melihat profil Anda',
          vi: 'Nhấp để xem hồ sơ của bạn',
          uk: 'Натисніть, щоб переглянути свій профіль',
        }),
      },
    },

    reviewerMarketplace: {
      text: t({
        en: 'Book a reviewer',
        'en-GB': 'Book a reviewer',
        fr: 'Trouver un traducteur',
        es: 'Encontrar un traductor',
        de: 'Übersetzer finden',
        ja: '翻訳者を見つける',
        ko: '번역가 찾기',
        zh: '找翻译',
        it: 'Trova un traduttore',
        pt: 'Encontrar um tradutor',
        hi: 'अनुवादक खोजें',
        ar: 'ابحث عن مترجم',
        ru: 'Найти переводчика',
        tr: 'Çevirmen bul',
        pl: 'Znajdź tłumacza',
        id: 'Cari Penerjemah',
        vi: 'Tìm dịch giả',
        uk: 'Знайти перекладача',
      }),
      label: t({
        en: 'Open Reviewer Marketplace in a new tab',
        'en-GB': 'Open Reviewer Marketplace in a new tab',
        fr: 'Ouvrir le marché des traducteurs dans un nouvel onglet',
        es: 'Abrir el mercado de traductores en una nueva pestaña',
        de: 'Übersetzer-Marktplatz in neuem Tab öffnen',
        ja: '翻訳者マーケットプレイスを新しいタブで開く',
        ko: '번역가 마켓플레이스를 새 탭에서 열기',
        zh: '在新标签页中打开翻译员市场',
        it: 'Apri il mercato dei traduttori in una nuova scheda',
        pt: 'Abrir o mercado de tradutores numa nova aba',
        hi: 'नए टैब में अनुवादक बाज़ार खोलें',
        ar: 'افتح سوق المترجمين في علامة تبويب جديدة',
        ru: 'Открыть рынок переводчиков в новой вкладке',
        tr: 'Çevirmen Pazarını yeni sekmede aç',
        pl: 'Otwórz rynek tłumaczy w nowej karcie',
        id: 'Buka Pasar Penerjemah di tab baru',
        vi: 'Mở Chợ dịch giả trong tab mới',
        uk: 'Відкрити ринок перекладачів у новій вкладці',
      }),
      description: t({
        en: 'Intlayer helps you review your AI-generated content with native speakers, marketing experts, copywriters, and certified reviewers.',
        'en-GB':
          'Intlayer helps you review your AI-generated content with native speakers, marketing experts, copywriters, and certified reviewers.',
        fr: "Intlayer vous aide à réviser votre contenu généré par l'IA avec des locuteurs natifs, des experts en marketing, des concepteurs-rédacteurs et des traducteurs certifiés.",
        es: 'Intlayer le ayuda a revisar su contenido generado por IA con hablantes nativos, expertos en marketing, redactores y traductores certificados.',
        de: 'Intlayer hilft Ihnen dabei, Ihre KI-generierten Inhalte mit Muttersprachlern, Marketingexperten, Werbetextern und zertifizierten Übersetzern zu überprüfen.',
        ja: 'Intlayerは、ネイティブスピーカー、マーケティングの専門家、コピーライター、認定翻訳者と一緒にAI生成コンテンツをレビューするのに役立ちます。',
        ko: 'Intlayer는 원어민, 마케팅 전문가, 카피라이터 및 공인 번역가와 함께 AI 생성 콘텐츠를 검토할 수 있도록 지원합니다.',
        zh: 'Intlayer 帮助您与母语人士、营销专家、文案撰稿人和认证翻译员一起审查 AI 生成的内容。',
        it: "Intlayer ti aiuta a revisionare i tuoi contenuti generati dall'intelligenza artificiale con madrelingua, esperti di marketing, copywriter e traduttori certificati.",
        pt: 'O Intlayer ajuda você a revisar seu conteúdo gerado por IA com falantes nativos, especialistas em marketing, redatores e tradutores certificados.',
        hi: 'Intlayer आपको देशी वक्ताओं, मार्केटिंग विशेषज्ञों, कॉपीराइटर और प्रमाणित अनुवादकों के साथ आपके AI-जनित सामग्री की समीक्षा करने में मदद करता है।',
        ar: 'تساعدك Intlayer في مراجعة المحتوى الذي تم إنشاؤه بواسطة الذكاء الاصطناعي مع متحدثين أصليين وخبراء تسويق ومؤلفين ومترجمين معتمدين.',
        ru: 'Intlayer помогает вам проверять контент, созданный ИИ, с носителями языка, экспертами по маркетингу, копирайтерами и сертифицированными переводчиками.',
        tr: 'Intlayer, yapay zeka tarafından oluşturulan içeriğinizi anadili olan kişiler, pazarlama uzmanları, reklam yazarları ve sertifikalı çevirmenlerle incelemenize yardımcı olur.',
        pl: 'Intlayer pomaga w recenzowaniu treści wygenerowanych przez sztuczną inteligencję we współpracy z native speakerami, ekspertami ds. marketingu, copywriterami i certyfikowanymi tłumaczami.',
        id: 'Intlayer membantu Anda meninjau konten yang dihasilkan AI dengan penutur asli, pakar pemasaran, copywriter, dan penerjemah bersertifikat.',
        vi: 'Intlayer giúp bạn xem xét nội dung do AI tạo ra với người bản ngữ, chuyên gia tiếp thị, copywriter và biên dịch viên được chứng nhận.',
        uk: 'Intlayer допомагає вам перевіряти контент, створений штучним інтелектом, за допомогою носіїв мови, експертів з маркетингу, копірайтерів та сертифікованих перекладачів.',
      }),
    },

    goToProfile: t({
      en: 'Go to profile',
      fr: 'Voir le profil',
      es: 'Ver perfil',
      'en-GB': 'View Profile',
      de: 'Profil anzeigen',
      ja: 'プロフィールを表示',
      ko: '프로필 보기',
      zh: '查看个人资料',
      it: 'Visualizza profilo',
      pt: 'Visualizar perfil',
      hi: 'प्रोफ़ाइल देखें',
      ar: 'عرض الملف الشخصي',
      ru: 'Посмотреть профиль',
      tr: 'Profili Görüntüle',
      pl: 'Pokaż profil',
      id: 'Lihat Profil',
      vi: 'Xem hồ sơ',
      uk: 'Переглянути профіль',
    }),

    dashboardNavigation: t({
      en: 'Dashboard navigation',
      fr: 'Navigation du tableau de bord',
      es: 'Navegación del tablero',
      ru: 'Навигация по панели управления',
      ja: 'ダッシュボードのナビゲーション',
      ko: '대시보드 탐색',
      zh: '仪表板导航',
      de: 'Dashboard-Navigation',
      ar: 'التنقل في لوحة التحكم',
      it: 'Navigazione della dashboard',
      'en-GB': 'Dashboard navigation',
      pt: 'Navegação do painel',
      hi: 'डैशबोर्ड नेविगेशन',
      tr: 'Kontrol Paneli Gezintisi',
      pl: 'Nawigacja pulpitu',
      id: 'Navigasi dasbor',
      vi: 'Điều hướng bảng điều khiển',
      uk: 'Навігація панелі керування',
    }),

    sidebarNavigation: t({
      en: 'Sidebar navigation',
      fr: 'Navigation latérale',
      es: 'Navegación lateral',
      ru: 'Боковая навигация',
      ja: 'サイドバーのナビゲーション',
      ko: '사이드바 탐색',
      zh: '侧边栏导航',
      de: 'Seitenleisten-Navigation',
      ar: 'التنقل في الشريط الجانبي',
      it: 'Navigazione della barra laterale',
      'en-GB': 'Sidebar navigation',
      pt: 'Navegação da barra lateral',
      hi: 'साइडबार नेविगेशन',
      tr: 'Kenar Çubuğu Gezintisi',
      pl: 'Nawigacja boczna',
      id: 'Navigasi bilah samping',
      vi: 'Điều hướng thanh bên',
      uk: 'Навігація бічної панелі',
    }),

    environment: t({
      en: 'Environment',
      fr: 'Environnement',
      es: 'Entorno',
      ru: 'Окружение',
      ja: '環境',
      ko: '환경',
      zh: '环境',
      de: 'Umgebung',
      ar: 'البيئة',
      it: 'Ambiente',
      'en-GB': 'Environment',
      pt: 'Ambiente',
      hi: 'परिवेश',
      tr: 'Ortam',
      pl: 'Środowisko',
      id: 'Lingkungan',
      vi: 'Môi trường',
      uk: 'Середовище',
    }),

    defaultEnv: t({
      en: 'default',
      fr: 'par défaut',
      es: 'predeterminado',
      ru: 'по умолчанию',
      ja: 'デフォルト',
      ko: '기본',
      zh: '默认',
      de: 'Standard',
      ar: 'افتراضي',
      it: 'predefinito',
      'en-GB': 'default',
      pt: 'padrão',
      hi: 'डिफ़ॉल्ट',
      tr: 'varsayılan',
      pl: 'domyślny',
      id: 'bawaan',
      vi: 'mặc định',
      uk: 'за замовчуванням',
    }),

    switchToName: insert(
      t({
        en: 'Switch to {{name}}',
        fr: 'Passer à {{name}}',
        es: 'Cambiar a {{name}}',
        ru: 'Переключиться на {{name}}',
        ja: '{{name}} に切り替える',
        ko: '{{name}}(으)로 전환',
        zh: '切换到 {{name}}',
        de: 'Zu {{name}} wechseln',
        ar: 'التبديل إلى {{name}}',
        it: 'Passa a {{name}}',
        'en-GB': 'Switch to {{name}}',
        pt: 'Mudar para {{name}}',
        hi: '{{name}} पर स्विच करें',
        tr: "{{name}}'a geç",
        pl: 'Przełącz na {{name}}',
        id: 'Beralih ke {{name}}',
        vi: 'Chuyển sang {{name}}',
        uk: 'Переключитись на {{name}}',
      })
    ),
  },
  title: 'Dashboard sidebar navigation',
  description:
    'Content declaration for the dashboard sidebar navigation, includes labels and titles for dashboard access and navigation sections.',
  tags: ['dashboard', 'sidebar', 'navigation'],
} satisfies Dictionary;

export default dashboardSidebarContent;
