import { type Dictionary, t } from 'intlayer';

const ssoSettingsContent = {
  key: 'sso-settings',
  content: {
    title: t({
      en: 'SSO Configuration',
      'en-GB': 'SSO Configuration',
      fr: 'Configuration SSO',
      es: 'Configuración SSO',
      de: 'SSO-Konfiguration',
      ja: 'SSO設定',
      ko: 'SSO 구성',
      zh: 'SSO 配置',
      it: 'Configurazione SSO',
      pt: 'Configuração SSO',
    }),
    description: t({
      en: 'Configure Single Sign-On for your organization to allow members to sign in with their corporate identity provider.',
      'en-GB':
        'Configure Single Sign-On for your organisation to allow members to sign in with their corporate identity provider.',
      fr: "Configurez l'authentification unique pour votre organisation afin de permettre aux membres de se connecter avec leur fournisseur d'identité d'entreprise.",
      es: 'Configure el inicio de sesión único para su organización para permitir que los miembros inicien sesión con su proveedor de identidad corporativo.',
      de: 'Konfigurieren Sie Single Sign-On für Ihre Organisation, damit Mitglieder sich mit ihrem Unternehmensidentitätsanbieter anmelden können.',
      ja: '組織のシングルサインオンを設定して、メンバーが企業のIDプロバイダーでサインインできるようにします。',
      ko: '조직의 Single Sign-On을 구성하여 구성원이 기업 ID 공급자로 로그인할 수 있도록 합니다.',
      zh: '为您的组织配置单点登录，以便成员可以使用其企业身份提供商登录。',
      it: 'Configura il Single Sign-On per la tua organizzazione per consentire ai membri di accedere con il loro provider di identità aziendale.',
      pt: 'Configure o Single Sign-On para sua organização para permitir que os membros façam login com seu provedor de identidade corporativo.',
    }),
    enabledLabel: t({
      en: 'Enable SSO',
      'en-GB': 'Enable SSO',
      fr: 'Activer SSO',
      es: 'Habilitar SSO',
      de: 'SSO aktivieren',
      ja: 'SSOを有効にする',
      ko: 'SSO 활성화',
      zh: '启用 SSO',
      it: 'Abilita SSO',
      pt: 'Habilitar SSO',
    }),
    providerTypeLabel: t({
      en: 'Provider Type',
      'en-GB': 'Provider Type',
      fr: 'Type de fournisseur',
      es: 'Tipo de proveedor',
      de: 'Anbietertyp',
      ja: 'プロバイダータイプ',
      ko: '공급자 유형',
      zh: '提供商类型',
      it: 'Tipo di provider',
      pt: 'Tipo de provedor',
    }),
    providerTypeOptions: {
      saml: t({
        en: 'SAML 2.0',
        'en-GB': 'SAML 2.0',
        fr: 'SAML 2.0',
        es: 'SAML 2.0',
        de: 'SAML 2.0',
        ja: 'SAML 2.0',
        ko: 'SAML 2.0',
        zh: 'SAML 2.0',
        it: 'SAML 2.0',
        pt: 'SAML 2.0',
      }),
      oidc: t({
        en: 'OpenID Connect (OIDC)',
        'en-GB': 'OpenID Connect (OIDC)',
        fr: 'OpenID Connect (OIDC)',
        es: 'OpenID Connect (OIDC)',
        de: 'OpenID Connect (OIDC)',
        ja: 'OpenID Connect (OIDC)',
        ko: 'OpenID Connect (OIDC)',
        zh: 'OpenID Connect (OIDC)',
        it: 'OpenID Connect (OIDC)',
        pt: 'OpenID Connect (OIDC)',
      }),
    },
    domainsLabel: t({
      en: 'Email Domains',
      'en-GB': 'Email Domains',
      fr: 'Domaines email',
      es: 'Dominios de correo',
      de: 'E-Mail-Domains',
      ja: 'メールドメイン',
      ko: '이메일 도메인',
      zh: '电子邮件域',
      it: 'Domini email',
      pt: 'Domínios de email',
    }),
    domainsPlaceholder: t({
      en: 'e.g., company.com (comma separated)',
      'en-GB': 'e.g., company.com (comma separated)',
      fr: 'ex: entreprise.com (séparés par des virgules)',
      es: 'ej: empresa.com (separados por comas)',
      de: 'z.B. firma.de (kommagetrennt)',
      ja: '例: company.com（カンマ区切り）',
      ko: '예: company.com (쉼표로 구분)',
      zh: '例如：company.com（逗号分隔）',
      it: 'es: azienda.com (separati da virgola)',
      pt: 'ex: empresa.com (separados por vírgula)',
    }),
    domainsDescription: t({
      en: 'Users with email addresses from these domains will be required to use SSO.',
      'en-GB':
        'Users with email addresses from these domains will be required to use SSO.',
      fr: 'Les utilisateurs avec des adresses email de ces domaines devront utiliser SSO.',
      es: 'Los usuarios con direcciones de correo de estos dominios deberán usar SSO.',
      de: 'Benutzer mit E-Mail-Adressen aus diesen Domains müssen SSO verwenden.',
      ja: 'これらのドメインのメールアドレスを持つユーザーはSSOを使用する必要があります。',
      ko: '이 도메인의 이메일 주소를 가진 사용자는 SSO를 사용해야 합니다.',
      zh: '来自这些域的电子邮件地址的用户将被要求使用SSO。',
      it: 'Gli utenti con indirizzi email da questi domini dovranno utilizzare SSO.',
      pt: 'Usuários com endereços de email desses domínios serão obrigados a usar SSO.',
    }),
    samlConfig: {
      title: t({
        en: 'SAML Configuration',
        'en-GB': 'SAML Configuration',
        fr: 'Configuration SAML',
        es: 'Configuración SAML',
        de: 'SAML-Konfiguration',
        ja: 'SAML設定',
        ko: 'SAML 구성',
        zh: 'SAML 配置',
        it: 'Configurazione SAML',
        pt: 'Configuração SAML',
      }),
      idpEntityIdLabel: t({
        en: 'IdP Entity ID',
        'en-GB': 'IdP Entity ID',
        fr: "ID d'entité IdP",
        es: 'ID de entidad IdP',
        de: 'IdP Entity ID',
        ja: 'IdP エンティティ ID',
        ko: 'IdP 엔티티 ID',
        zh: 'IdP 实体 ID',
        it: 'ID entità IdP',
        pt: 'ID da entidade IdP',
      }),
      idpEntityIdPlaceholder: t({
        en: 'https://idp.example.com/entity-id',
        'en-GB': 'https://idp.example.com/entity-id',
        fr: 'https://idp.exemple.com/entity-id',
        es: 'https://idp.ejemplo.com/entity-id',
        de: 'https://idp.beispiel.de/entity-id',
        ja: 'https://idp.example.com/entity-id',
        ko: 'https://idp.example.com/entity-id',
        zh: 'https://idp.example.com/entity-id',
        it: 'https://idp.esempio.com/entity-id',
        pt: 'https://idp.exemplo.com/entity-id',
      }),
      idpSSOUrlLabel: t({
        en: 'IdP SSO URL',
        'en-GB': 'IdP SSO URL',
        fr: 'URL SSO IdP',
        es: 'URL SSO IdP',
        de: 'IdP SSO URL',
        ja: 'IdP SSO URL',
        ko: 'IdP SSO URL',
        zh: 'IdP SSO URL',
        it: 'URL SSO IdP',
        pt: 'URL SSO IdP',
      }),
      idpSSOUrlPlaceholder: t({
        en: 'https://idp.example.com/sso',
        'en-GB': 'https://idp.example.com/sso',
        fr: 'https://idp.exemple.com/sso',
        es: 'https://idp.ejemplo.com/sso',
        de: 'https://idp.beispiel.de/sso',
        ja: 'https://idp.example.com/sso',
        ko: 'https://idp.example.com/sso',
        zh: 'https://idp.example.com/sso',
        it: 'https://idp.esempio.com/sso',
        pt: 'https://idp.exemplo.com/sso',
      }),
      idpCertificateLabel: t({
        en: 'IdP Certificate (PEM)',
        'en-GB': 'IdP Certificate (PEM)',
        fr: 'Certificat IdP (PEM)',
        es: 'Certificado IdP (PEM)',
        de: 'IdP-Zertifikat (PEM)',
        ja: 'IdP 証明書 (PEM)',
        ko: 'IdP 인증서 (PEM)',
        zh: 'IdP 证书 (PEM)',
        it: 'Certificato IdP (PEM)',
        pt: 'Certificado IdP (PEM)',
      }),
      idpCertificatePlaceholder: t({
        en: 'Paste your IdP certificate here...',
        'en-GB': 'Paste your IdP certificate here...',
        fr: 'Collez votre certificat IdP ici...',
        es: 'Pegue su certificado IdP aquí...',
        de: 'Fügen Sie Ihr IdP-Zertifikat hier ein...',
        ja: 'IdP証明書をここに貼り付けてください...',
        ko: 'IdP 인증서를 여기에 붙여넣으세요...',
        zh: '在此处粘贴您的IdP证书...',
        it: 'Incolla il tuo certificato IdP qui...',
        pt: 'Cole seu certificado IdP aqui...',
      }),
    },
    oidcConfig: {
      title: t({
        en: 'OIDC Configuration',
        'en-GB': 'OIDC Configuration',
        fr: 'Configuration OIDC',
        es: 'Configuración OIDC',
        de: 'OIDC-Konfiguration',
        ja: 'OIDC設定',
        ko: 'OIDC 구성',
        zh: 'OIDC 配置',
        it: 'Configurazione OIDC',
        pt: 'Configuração OIDC',
      }),
      issuerLabel: t({
        en: 'Issuer URL',
        'en-GB': 'Issuer URL',
        fr: "URL de l'émetteur",
        es: 'URL del emisor',
        de: 'Aussteller-URL',
        ja: '発行者 URL',
        ko: '발급자 URL',
        zh: '发行者 URL',
        it: 'URL emittente',
        pt: 'URL do emissor',
      }),
      issuerPlaceholder: t({
        en: 'https://accounts.google.com',
        'en-GB': 'https://accounts.google.com',
        fr: 'https://accounts.google.com',
        es: 'https://accounts.google.com',
        de: 'https://accounts.google.com',
        ja: 'https://accounts.google.com',
        ko: 'https://accounts.google.com',
        zh: 'https://accounts.google.com',
        it: 'https://accounts.google.com',
        pt: 'https://accounts.google.com',
      }),
      clientIdLabel: t({
        en: 'Client ID',
        'en-GB': 'Client ID',
        fr: 'ID client',
        es: 'ID de cliente',
        de: 'Client-ID',
        ja: 'クライアント ID',
        ko: '클라이언트 ID',
        zh: '客户端 ID',
        it: 'ID client',
        pt: 'ID do cliente',
      }),
      clientIdPlaceholder: t({
        en: 'Your OAuth2 client ID',
        'en-GB': 'Your OAuth2 client ID',
        fr: 'Votre ID client OAuth2',
        es: 'Su ID de cliente OAuth2',
        de: 'Ihre OAuth2-Client-ID',
        ja: 'OAuth2クライアントID',
        ko: 'OAuth2 클라이언트 ID',
        zh: '您的 OAuth2 客户端 ID',
        it: 'Il tuo ID client OAuth2',
        pt: 'Seu ID do cliente OAuth2',
      }),
      clientSecretLabel: t({
        en: 'Client Secret',
        'en-GB': 'Client Secret',
        fr: 'Secret client',
        es: 'Secreto de cliente',
        de: 'Client-Secret',
        ja: 'クライアントシークレット',
        ko: '클라이언트 시크릿',
        zh: '客户端密钥',
        it: 'Segreto client',
        pt: 'Segredo do cliente',
      }),
      clientSecretPlaceholder: t({
        en: 'Your OAuth2 client secret',
        'en-GB': 'Your OAuth2 client secret',
        fr: 'Votre secret client OAuth2',
        es: 'Su secreto de cliente OAuth2',
        de: 'Ihr OAuth2-Client-Secret',
        ja: 'OAuth2クライアントシークレット',
        ko: 'OAuth2 클라이언트 시크릿',
        zh: '您的 OAuth2 客户端密钥',
        it: 'Il tuo segreto client OAuth2',
        pt: 'Seu segredo do cliente OAuth2',
      }),
    },
    advancedSettings: {
      title: t({
        en: 'Advanced Settings',
        'en-GB': 'Advanced Settings',
        fr: 'Paramètres avancés',
        es: 'Configuración avanzada',
        de: 'Erweiterte Einstellungen',
        ja: '詳細設定',
        ko: '고급 설정',
        zh: '高级设置',
        it: 'Impostazioni avanzate',
        pt: 'Configurações avançadas',
      }),
      enforceSSOLabel: t({
        en: 'Enforce SSO',
        'en-GB': 'Enforce SSO',
        fr: 'Forcer SSO',
        es: 'Forzar SSO',
        de: 'SSO erzwingen',
        ja: 'SSOを強制',
        ko: 'SSO 강제',
        zh: '强制 SSO',
        it: 'Forza SSO',
        pt: 'Forçar SSO',
      }),
      enforceSSODescription: t({
        en: 'Require all users in this organization to use SSO',
        'en-GB': 'Require all users in this organisation to use SSO',
        fr: 'Obliger tous les utilisateurs de cette organisation à utiliser SSO',
        es: 'Requerir que todos los usuarios de esta organización usen SSO',
        de: 'Alle Benutzer in dieser Organisation müssen SSO verwenden',
        ja: 'この組織のすべてのユーザーにSSOの使用を要求する',
        ko: '이 조직의 모든 사용자가 SSO를 사용하도록 요구',
        zh: '要求此组织中的所有用户使用SSO',
        it: 'Richiedi a tutti gli utenti di questa organizzazione di utilizzare SSO',
        pt: 'Exigir que todos os usuários nesta organização usem SSO',
      }),
      allowPasswordLoginLabel: t({
        en: 'Allow Password Login',
        'en-GB': 'Allow Password Login',
        fr: 'Autoriser la connexion par mot de passe',
        es: 'Permitir inicio de sesión con contraseña',
        de: 'Passwort-Anmeldung erlauben',
        ja: 'パスワードログインを許可',
        ko: '비밀번호 로그인 허용',
        zh: '允许密码登录',
        it: 'Consenti login con password',
        pt: 'Permitir login com senha',
      }),
      allowPasswordLoginDescription: t({
        en: 'Allow users to bypass SSO and log in with email/password',
        'en-GB': 'Allow users to bypass SSO and log in with email/password',
        fr: 'Permettre aux utilisateurs de contourner SSO et de se connecter avec email/mot de passe',
        es: 'Permitir a los usuarios omitir SSO e iniciar sesión con email/contraseña',
        de: 'Benutzern erlauben, SSO zu umgehen und sich mit E-Mail/Passwort anzumelden',
        ja: 'ユーザーがSSOをバイパスしてメール/パスワードでログインすることを許可',
        ko: '사용자가 SSO를 우회하고 이메일/비밀번호로 로그인하도록 허용',
        zh: '允许用户绕过SSO并使用电子邮件/密码登录',
        it: 'Consenti agli utenti di bypassare SSO e accedere con email/password',
        pt: 'Permitir que os usuários ignorem o SSO e façam login com email/senha',
      }),
    },
    saveButton: {
      text: t({
        en: 'Save SSO Configuration',
        'en-GB': 'Save SSO Configuration',
        fr: 'Enregistrer la configuration SSO',
        es: 'Guardar configuración SSO',
        de: 'SSO-Konfiguration speichern',
        ja: 'SSO設定を保存',
        ko: 'SSO 구성 저장',
        zh: '保存 SSO 配置',
        it: 'Salva configurazione SSO',
        pt: 'Salvar configuração SSO',
      }),
      ariaLabel: t({
        en: 'Click to save SSO configuration',
        'en-GB': 'Click to save SSO configuration',
        fr: 'Cliquez pour enregistrer la configuration SSO',
        es: 'Haga clic para guardar la configuración SSO',
        de: 'Klicken Sie, um die SSO-Konfiguration zu speichern',
        ja: 'SSO設定を保存するにはクリックしてください',
        ko: 'SSO 구성을 저장하려면 클릭하세요',
        zh: '单击以保存SSO配置',
        it: 'Fai clic per salvare la configurazione SSO',
        pt: 'Clique para salvar a configuração SSO',
      }),
    },
  },
  title: 'SSO Settings',
  description:
    'Content declaration for the SSO settings form in the organization dashboard. Includes labels, placeholders, and descriptions for SAML and OIDC configuration.',
  tags: ['dashboard', 'sso', 'authentication', 'organization'],
} satisfies Dictionary;

export default ssoSettingsContent;
