export enum PagesRoutes {
  Home = '/',
  Demo = '/demo',
  NotFound = '/404',

  Doc = '/doc',
  Doc_GetStarted = '/doc/get_started',
  Doc_HowWorksIntlayer = '/doc/concept/how_works_intlayer',
  Doc_Configuration = '/doc/concept/configuration',
  Doc_Interest = '/doc/concept/interest_of_intlayer',
  Doc_IntlayerEditor = '/doc/concept/intlayer_editor',
  Doc_CLI = '/doc/concept/intlayer_cli',
  Doc_IntlayerWithI18next = '/doc/concept/intlayer_with_i18next',
  Doc_ContentDeclaration = '/doc/concept/content_declaration',
  Doc_ContentDeclaration_Translation = '/doc/concept/content_declaration/translation',
  Doc_ContentDeclaration_Enumeration = '/doc/concept/content_declaration/enumeration',
  Doc_ContentDeclaration_FunctionFetching = '/doc/concept/content_declaration/function_fetching',
  Doc_ContentDeclaration_NestedId = '/doc/concept/content_declaration/nested_id',
  Doc_Environment_NextJS = '/doc/environment/intlayer_with_nextjs',
  Doc_Environment_CRA = '/doc/environment/intlayer_with_create_react_app',
  Doc_Environment_ViteAndReact = '/doc/environment/intlayer_with_vite_and_react',
  Doc_Intlayer_with_I18next = '/doc/blog/intlayer_with_i18next',

  PrivacyPolicy = '/privacy_notice',
  TermsOfService = '/terms_of_service',
}

export enum ExternalLinks {
  Github = 'https://github.com/aypineau/intlayer',
  LinkedIn = 'https://www.linkedin.com/company/intlayerorg/',
  ExampleIntlayerWithNextjs = 'https://github.com/aypineau/intlayer/tree/3c64451e85648f8a354a54d84216a27b68f4cb2d/examples/nextjs-app',
  ExampleIntlayerWithReactJS = 'https://github.com/aypineau/intlayer/tree/3c64451e85648f8a354a54d84216a27b68f4cb2d/examples/react-app',
  ExampleIntlayerWithViteAndReact = 'https://github.com/aypineau/intlayer/tree/3c64451e85648f8a354a54d84216a27b68f4cb2d/examples/vite-app',
}

export enum GithubRoutes {
  Introduction = 'https://github.com/aypineau/intlayer/blob/main/docs/docs/introduction_en.md',
  HowWorksIntlayer = 'https://github.com/aypineau/intlayer/blob/main/docs/docs/how_works_intlayer_en.md',
  Configuration = 'https://github.com/aypineau/intlayer/blob/main/docs/docs/configuration_en.md',
  InterestOfIntlayer = 'https://github.com/aypineau/intlayer/blob/main/docs/docs/interest_of_intlayer_en.md',
  IntlayerCLI = 'https://github.com/aypineau/intlayer/blob/main/docs/docs/intlayer_cli_en.md',
  IntlayerEditor = 'https://github.com/aypineau/intlayer/blob/main/docs/docs/intlayer_editor_en.md',
  IntlayerWithNextJS = 'https://github.com/aypineau/intlayer/blob/main/docs/docs/intlayer_with_nextjs_en.md',
  IntlayerWithReactCRA = 'https://github.com/aypineau/intlayer/blob/main/docs/docs/intlayer_with_create_react_app_en.md',
  IntlayerWithViteReact = 'https://github.com/aypineau/intlayer/blob/main/docs/docs/intlayer_with_vite+react_en.md',
  IntlayerWithI18next = 'https://github.com/aypineau/intlayer/blob/main/docs/docs/intlayer_with_i18next_en.md',
  ContentDeclaration_GetStarted = 'https://github.com/aypineau/intlayer/blob/main/docs/docs/content_declaration/get_started_en.md',
  ContentDeclaration_ContentExtentionCustomization = 'https://github.com/aypineau/intlayer/blob/main/docs/docs/content_declaration/content_extention_customization_en.md',
  ContentDeclaration_Enumeration = 'https://github.com/aypineau/intlayer/blob/main/docs/docs/content_declaration/enumeration_en.md',
  ContentDeclaration_FunctionFetching = 'https://github.com/aypineau/intlayer/blob/main/docs/docs/content_declaration/function_fetching_en.md',
  ContentDeclaration_NestedId = 'https://github.com/aypineau/intlayer/blob/main/docs/docs/content_declaration/nested_id_en.md',
  ContentDeclaration_Translation = 'https://github.com/aypineau/intlayer/blob/main/docs/docs/content_declaration/translation_en.md',
  PrivacyPolicy = 'https://github.com/aypineau/intlayer/blob/main/docs/docs/privacy_notice_en.md',
  TermsOfService = 'https://github.com/aypineau/intlayer/blob/main/docs/docs/terms_of_service_en.md',
}
