/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthDotmdRouteImport } from './routes/auth[.]md'
import { Route as FeedDotxmlRouteImport } from './routes/feed[.]xml'
import { Route as PostsDotjsonRouteImport } from './routes/posts[.]json'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Char123LocaleChar125RouteRouteImport } from './routes/{-$locale}/route'
import { Route as DotwellKnownAiCatalogDotjsonRouteImport } from './routes/[.]well-known/ai-catalog[.]json'
import { Route as DotwellKnownApiCatalogRouteImport } from './routes/[.]well-known/api-catalog'
import { Route as DotwellKnownOauthProtectedResourceRouteImport } from './routes/[.]well-known/oauth-protected-resource'
import { Route as ApiBaiduPushRouteImport } from './routes/api/baidu-push'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125SplatRouteImport } from './routes/{-$locale}/$'
import { Route as Char123LocaleChar125DocsRouteRouteImport } from './routes/{-$locale}/_docs/route'
import { Route as Char123LocaleChar125PlaygroundRouteRouteImport } from './routes/{-$locale}/_playground/route'
import { Route as Char123LocaleChar125CmsRouteImport } from './routes/{-$locale}/cms'
import { Route as Char123LocaleChar125ContributorsRouteImport } from './routes/{-$locale}/contributors'
import { Route as Char123LocaleChar125DemoRouteImport } from './routes/{-$locale}/demo'
import { Route as Char123LocaleChar125I18nMessageConverterRouteImport } from './routes/{-$locale}/i18n-message-converter'
import { Route as Char123LocaleChar125I18nSeoScannerRouteImport } from './routes/{-$locale}/i18n-seo-scanner'
import { Route as Char123LocaleChar125MarkdownRouteImport } from './routes/{-$locale}/markdown'
import { Route as Char123LocaleChar125TmsRouteImport } from './routes/{-$locale}/tms'
import { Route as Char123LocaleChar125TranslateRouteImport } from './routes/{-$locale}/translate'
import { Route as DotwellKnownAgentSkillsIndexDotjsonRouteImport } from './routes/[.]well-known/agent-skills/index[.]json'
import { Route as DotwellKnownMcpServerCardDotjsonRouteImport } from './routes/[.]well-known/mcp/server-card[.]json'
import { Route as ApiProxyAhrefsAnalyticsRouteImport } from './routes/api/proxy/ahrefs-analytics'
import { Route as Char123LocaleChar125DocsPrivacyNoticeRouteImport } from './routes/{-$locale}/_docs/privacy-notice'
import { Route as Char123LocaleChar125DocsPrivacyNoticeDotmdRouteImport } from './routes/{-$locale}/_docs/privacy-notice[.]md'
import { Route as Char123LocaleChar125DocsTermsOfServiceRouteImport } from './routes/{-$locale}/_docs/terms-of-service'
import { Route as Char123LocaleChar125DocsTermsOfServiceDotmdRouteImport } from './routes/{-$locale}/_docs/terms-of-service[.]md'
import { Route as Char123LocaleChar125PlaygroundPlaygroundRouteImport } from './routes/{-$locale}/_playground/playground'
import { Route as DotwellKnownAgentSkillsSkillSKILLDotmdRouteImport } from './routes/[.]well-known/agent-skills/$skill/SKILL[.]md'
import { Route as Char123LocaleChar125DocsBlogIndexRouteImport } from './routes/{-$locale}/_docs/blog/index'
import { Route as Char123LocaleChar125DocsBlogSplatRouteImport } from './routes/{-$locale}/_docs/blog/$'
import { Route as Char123LocaleChar125DocsBlogSearchRouteImport } from './routes/{-$locale}/_docs/blog/search'
import { Route as Char123LocaleChar125DocsDocSplatRouteImport } from './routes/{-$locale}/_docs/doc/$'
import { Route as Char123LocaleChar125DocsDocChatRouteImport } from './routes/{-$locale}/_docs/doc/chat'
import { Route as Char123LocaleChar125DocsDocSearchRouteImport } from './routes/{-$locale}/_docs/doc/search'
import { Route as Char123LocaleChar125DocsFrequentQuestionsIndexRouteImport } from './routes/{-$locale}/_docs/frequent-questions/index'
import { Route as Char123LocaleChar125DocsFrequentQuestionsSplatRouteImport } from './routes/{-$locale}/_docs/frequent-questions/$'
import { Route as Char123LocaleChar125BlogRawSplatRouteImport } from './routes/{-$locale}/blog/raw/$'
import { Route as Char123LocaleChar125DocRawSplatRouteImport } from './routes/{-$locale}/doc/raw/$'
import { Route as Char123LocaleChar125FrequentQuestionsRawSplatRouteImport } from './routes/{-$locale}/frequent-questions/raw/$'

const AuthDotmdRoute = AuthDotmdRouteImport.update({
  id: '/auth.md',
  path: '/auth.md',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedDotxmlRoute = FeedDotxmlRouteImport.update({
  id: '/feed.xml',
  path: '/feed.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsDotjsonRoute = PostsDotjsonRouteImport.update({
  id: '/posts.json',
  path: '/posts.json',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: '/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownAiCatalogDotjsonRoute =
  DotwellKnownAiCatalogDotjsonRouteImport.update({
    id: '/.well-known/ai-catalog.json',
    path: '/.well-known/ai-catalog.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownApiCatalogRoute = DotwellKnownApiCatalogRouteImport.update({
  id: '/.well-known/api-catalog',
  path: '/.well-known/api-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOauthProtectedResourceRoute =
  DotwellKnownOauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBaiduPushRoute = ApiBaiduPushRouteImport.update({
  id: '/api/baidu-push',
  path: '/api/baidu-push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125SplatRoute =
  Char123LocaleChar125SplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125DocsRouteRoute =
  Char123LocaleChar125DocsRouteRouteImport.update({
    id: '/_docs',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125PlaygroundRouteRoute =
  Char123LocaleChar125PlaygroundRouteRouteImport.update({
    id: '/_playground',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125CmsRoute = Char123LocaleChar125CmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => Char123LocaleChar125RouteRoute,
} as any)
const Char123LocaleChar125ContributorsRoute =
  Char123LocaleChar125ContributorsRouteImport.update({
    id: '/contributors',
    path: '/contributors',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125DemoRoute =
  Char123LocaleChar125DemoRouteImport.update({
    id: '/demo',
    path: '/demo',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125I18nMessageConverterRoute =
  Char123LocaleChar125I18nMessageConverterRouteImport.update({
    id: '/i18n-message-converter',
    path: '/i18n-message-converter',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125I18nSeoScannerRoute =
  Char123LocaleChar125I18nSeoScannerRouteImport.update({
    id: '/i18n-seo-scanner',
    path: '/i18n-seo-scanner',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125MarkdownRoute =
  Char123LocaleChar125MarkdownRouteImport.update({
    id: '/markdown',
    path: '/markdown',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125TmsRoute = Char123LocaleChar125TmsRouteImport.update({
  id: '/tms',
  path: '/tms',
  getParentRoute: () => Char123LocaleChar125RouteRoute,
} as any)
const Char123LocaleChar125TranslateRoute =
  Char123LocaleChar125TranslateRouteImport.update({
    id: '/translate',
    path: '/translate',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const DotwellKnownAgentSkillsIndexDotjsonRoute =
  DotwellKnownAgentSkillsIndexDotjsonRouteImport.update({
    id: '/.well-known/agent-skills/index.json',
    path: '/.well-known/agent-skills/index.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownMcpServerCardDotjsonRoute =
  DotwellKnownMcpServerCardDotjsonRouteImport.update({
    id: '/.well-known/mcp/server-card.json',
    path: '/.well-known/mcp/server-card.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProxyAhrefsAnalyticsRoute = ApiProxyAhrefsAnalyticsRouteImport.update({
  id: '/api/proxy/ahrefs-analytics',
  path: '/api/proxy/ahrefs-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125DocsPrivacyNoticeRoute =
  Char123LocaleChar125DocsPrivacyNoticeRouteImport.update({
    id: '/privacy-notice',
    path: '/privacy-notice',
    getParentRoute: () => Char123LocaleChar125DocsRouteRoute,
  } as any)
const Char123LocaleChar125DocsPrivacyNoticeDotmdRoute =
  Char123LocaleChar125DocsPrivacyNoticeDotmdRouteImport.update({
    id: '/privacy-notice.md',
    path: '/privacy-notice.md',
    getParentRoute: () => Char123LocaleChar125DocsRouteRoute,
  } as any)
const Char123LocaleChar125DocsTermsOfServiceRoute =
  Char123LocaleChar125DocsTermsOfServiceRouteImport.update({
    id: '/terms-of-service',
    path: '/terms-of-service',
    getParentRoute: () => Char123LocaleChar125DocsRouteRoute,
  } as any)
const Char123LocaleChar125DocsTermsOfServiceDotmdRoute =
  Char123LocaleChar125DocsTermsOfServiceDotmdRouteImport.update({
    id: '/terms-of-service.md',
    path: '/terms-of-service.md',
    getParentRoute: () => Char123LocaleChar125DocsRouteRoute,
  } as any)
const Char123LocaleChar125PlaygroundPlaygroundRoute =
  Char123LocaleChar125PlaygroundPlaygroundRouteImport.update({
    id: '/playground',
    path: '/playground',
    getParentRoute: () => Char123LocaleChar125PlaygroundRouteRoute,
  } as any)
const DotwellKnownAgentSkillsSkillSKILLDotmdRoute =
  DotwellKnownAgentSkillsSkillSKILLDotmdRouteImport.update({
    id: '/.well-known/agent-skills/$skill/SKILL.md',
    path: '/.well-known/agent-skills/$skill/SKILL.md',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125DocsBlogIndexRoute =
  Char123LocaleChar125DocsBlogIndexRouteImport.update({
    id: '/blog/',
    path: '/blog/',
    getParentRoute: () => Char123LocaleChar125DocsRouteRoute,
  } as any)
const Char123LocaleChar125DocsBlogSplatRoute =
  Char123LocaleChar125DocsBlogSplatRouteImport.update({
    id: '/blog/$',
    path: '/blog/$',
    getParentRoute: () => Char123LocaleChar125DocsRouteRoute,
  } as any)
const Char123LocaleChar125DocsBlogSearchRoute =
  Char123LocaleChar125DocsBlogSearchRouteImport.update({
    id: '/blog/search',
    path: '/blog/search',
    getParentRoute: () => Char123LocaleChar125DocsRouteRoute,
  } as any)
const Char123LocaleChar125DocsDocSplatRoute =
  Char123LocaleChar125DocsDocSplatRouteImport.update({
    id: '/doc/$',
    path: '/doc/$',
    getParentRoute: () => Char123LocaleChar125DocsRouteRoute,
  } as any)
const Char123LocaleChar125DocsDocChatRoute =
  Char123LocaleChar125DocsDocChatRouteImport.update({
    id: '/doc/chat',
    path: '/doc/chat',
    getParentRoute: () => Char123LocaleChar125DocsRouteRoute,
  } as any)
const Char123LocaleChar125DocsDocSearchRoute =
  Char123LocaleChar125DocsDocSearchRouteImport.update({
    id: '/doc/search',
    path: '/doc/search',
    getParentRoute: () => Char123LocaleChar125DocsRouteRoute,
  } as any)
const Char123LocaleChar125DocsFrequentQuestionsIndexRoute =
  Char123LocaleChar125DocsFrequentQuestionsIndexRouteImport.update({
    id: '/frequent-questions/',
    path: '/frequent-questions/',
    getParentRoute: () => Char123LocaleChar125DocsRouteRoute,
  } as any)
const Char123LocaleChar125DocsFrequentQuestionsSplatRoute =
  Char123LocaleChar125DocsFrequentQuestionsSplatRouteImport.update({
    id: '/frequent-questions/$',
    path: '/frequent-questions/$',
    getParentRoute: () => Char123LocaleChar125DocsRouteRoute,
  } as any)
const Char123LocaleChar125BlogRawSplatRoute =
  Char123LocaleChar125BlogRawSplatRouteImport.update({
    id: '/blog/raw/$',
    path: '/blog/raw/$',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125DocRawSplatRoute =
  Char123LocaleChar125DocRawSplatRouteImport.update({
    id: '/doc/raw/$',
    path: '/doc/raw/$',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125FrequentQuestionsRawSplatRoute =
  Char123LocaleChar125FrequentQuestionsRawSplatRouteImport.update({
    id: '/frequent-questions/raw/$',
    path: '/frequent-questions/raw/$',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/auth.md': typeof AuthDotmdRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/posts.json': typeof PostsDotjsonRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/ai-catalog.json': typeof DotwellKnownAiCatalogDotjsonRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/api/baidu-push': typeof ApiBaiduPushRoute
  '/api/health': typeof ApiHealthRoute
  '/{-$locale}/$': typeof Char123LocaleChar125SplatRoute
  '/{-$locale}/cms': typeof Char123LocaleChar125CmsRoute
  '/{-$locale}/contributors': typeof Char123LocaleChar125ContributorsRoute
  '/{-$locale}/demo': typeof Char123LocaleChar125DemoRoute
  '/{-$locale}/i18n-message-converter': typeof Char123LocaleChar125I18nMessageConverterRoute
  '/{-$locale}/i18n-seo-scanner': typeof Char123LocaleChar125I18nSeoScannerRoute
  '/{-$locale}/markdown': typeof Char123LocaleChar125MarkdownRoute
  '/{-$locale}/tms': typeof Char123LocaleChar125TmsRoute
  '/{-$locale}/translate': typeof Char123LocaleChar125TranslateRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/.well-known/agent-skills/index.json': typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  '/.well-known/mcp/server-card.json': typeof DotwellKnownMcpServerCardDotjsonRoute
  '/api/proxy/ahrefs-analytics': typeof ApiProxyAhrefsAnalyticsRoute
  '/{-$locale}/privacy-notice': typeof Char123LocaleChar125DocsPrivacyNoticeRoute
  '/{-$locale}/privacy-notice.md': typeof Char123LocaleChar125DocsPrivacyNoticeDotmdRoute
  '/{-$locale}/terms-of-service': typeof Char123LocaleChar125DocsTermsOfServiceRoute
  '/{-$locale}/terms-of-service.md': typeof Char123LocaleChar125DocsTermsOfServiceDotmdRoute
  '/{-$locale}/playground': typeof Char123LocaleChar125PlaygroundPlaygroundRoute
  '/.well-known/agent-skills/$skill/SKILL.md': typeof DotwellKnownAgentSkillsSkillSKILLDotmdRoute
  '/{-$locale}/blog/$': typeof Char123LocaleChar125DocsBlogSplatRoute
  '/{-$locale}/blog/search': typeof Char123LocaleChar125DocsBlogSearchRoute
  '/{-$locale}/doc/$': typeof Char123LocaleChar125DocsDocSplatRoute
  '/{-$locale}/doc/chat': typeof Char123LocaleChar125DocsDocChatRoute
  '/{-$locale}/doc/search': typeof Char123LocaleChar125DocsDocSearchRoute
  '/{-$locale}/frequent-questions/$': typeof Char123LocaleChar125DocsFrequentQuestionsSplatRoute
  '/{-$locale}/blog/raw/$': typeof Char123LocaleChar125BlogRawSplatRoute
  '/{-$locale}/doc/raw/$': typeof Char123LocaleChar125DocRawSplatRoute
  '/{-$locale}/frequent-questions/raw/$': typeof Char123LocaleChar125FrequentQuestionsRawSplatRoute
  '/{-$locale}/blog/': typeof Char123LocaleChar125DocsBlogIndexRoute
  '/{-$locale}/frequent-questions/': typeof Char123LocaleChar125DocsFrequentQuestionsIndexRoute
}
export interface FileRoutesByTo {
  '/auth.md': typeof AuthDotmdRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/posts.json': typeof PostsDotjsonRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/.well-known/ai-catalog.json': typeof DotwellKnownAiCatalogDotjsonRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/api/baidu-push': typeof ApiBaiduPushRoute
  '/api/health': typeof ApiHealthRoute
  '/{-$locale}/$': typeof Char123LocaleChar125SplatRoute
  '/{-$locale}/cms': typeof Char123LocaleChar125CmsRoute
  '/{-$locale}/contributors': typeof Char123LocaleChar125ContributorsRoute
  '/{-$locale}/demo': typeof Char123LocaleChar125DemoRoute
  '/{-$locale}/i18n-message-converter': typeof Char123LocaleChar125I18nMessageConverterRoute
  '/{-$locale}/i18n-seo-scanner': typeof Char123LocaleChar125I18nSeoScannerRoute
  '/{-$locale}/markdown': typeof Char123LocaleChar125MarkdownRoute
  '/{-$locale}/tms': typeof Char123LocaleChar125TmsRoute
  '/{-$locale}/translate': typeof Char123LocaleChar125TranslateRoute
  '/.well-known/agent-skills/index.json': typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  '/.well-known/mcp/server-card.json': typeof DotwellKnownMcpServerCardDotjsonRoute
  '/api/proxy/ahrefs-analytics': typeof ApiProxyAhrefsAnalyticsRoute
  '/{-$locale}/privacy-notice': typeof Char123LocaleChar125DocsPrivacyNoticeRoute
  '/{-$locale}/privacy-notice.md': typeof Char123LocaleChar125DocsPrivacyNoticeDotmdRoute
  '/{-$locale}/terms-of-service': typeof Char123LocaleChar125DocsTermsOfServiceRoute
  '/{-$locale}/terms-of-service.md': typeof Char123LocaleChar125DocsTermsOfServiceDotmdRoute
  '/{-$locale}/playground': typeof Char123LocaleChar125PlaygroundPlaygroundRoute
  '/.well-known/agent-skills/$skill/SKILL.md': typeof DotwellKnownAgentSkillsSkillSKILLDotmdRoute
  '/{-$locale}/blog/$': typeof Char123LocaleChar125DocsBlogSplatRoute
  '/{-$locale}/blog/search': typeof Char123LocaleChar125DocsBlogSearchRoute
  '/{-$locale}/doc/$': typeof Char123LocaleChar125DocsDocSplatRoute
  '/{-$locale}/doc/chat': typeof Char123LocaleChar125DocsDocChatRoute
  '/{-$locale}/doc/search': typeof Char123LocaleChar125DocsDocSearchRoute
  '/{-$locale}/frequent-questions/$': typeof Char123LocaleChar125DocsFrequentQuestionsSplatRoute
  '/{-$locale}/blog/raw/$': typeof Char123LocaleChar125BlogRawSplatRoute
  '/{-$locale}/doc/raw/$': typeof Char123LocaleChar125DocRawSplatRoute
  '/{-$locale}/frequent-questions/raw/$': typeof Char123LocaleChar125FrequentQuestionsRawSplatRoute
  '/{-$locale}/blog': typeof Char123LocaleChar125DocsBlogIndexRoute
  '/{-$locale}/frequent-questions': typeof Char123LocaleChar125DocsFrequentQuestionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/auth.md': typeof AuthDotmdRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/posts.json': typeof PostsDotjsonRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}/_docs': typeof Char123LocaleChar125DocsRouteRouteWithChildren
  '/{-$locale}/_playground': typeof Char123LocaleChar125PlaygroundRouteRouteWithChildren
  '/.well-known/ai-catalog.json': typeof DotwellKnownAiCatalogDotjsonRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/api/baidu-push': typeof ApiBaiduPushRoute
  '/api/health': typeof ApiHealthRoute
  '/{-$locale}/$': typeof Char123LocaleChar125SplatRoute
  '/{-$locale}/cms': typeof Char123LocaleChar125CmsRoute
  '/{-$locale}/contributors': typeof Char123LocaleChar125ContributorsRoute
  '/{-$locale}/demo': typeof Char123LocaleChar125DemoRoute
  '/{-$locale}/i18n-message-converter': typeof Char123LocaleChar125I18nMessageConverterRoute
  '/{-$locale}/i18n-seo-scanner': typeof Char123LocaleChar125I18nSeoScannerRoute
  '/{-$locale}/markdown': typeof Char123LocaleChar125MarkdownRoute
  '/{-$locale}/tms': typeof Char123LocaleChar125TmsRoute
  '/{-$locale}/translate': typeof Char123LocaleChar125TranslateRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/.well-known/agent-skills/index.json': typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  '/.well-known/mcp/server-card.json': typeof DotwellKnownMcpServerCardDotjsonRoute
  '/api/proxy/ahrefs-analytics': typeof ApiProxyAhrefsAnalyticsRoute
  '/{-$locale}/_docs/privacy-notice': typeof Char123LocaleChar125DocsPrivacyNoticeRoute
  '/{-$locale}/_docs/privacy-notice.md': typeof Char123LocaleChar125DocsPrivacyNoticeDotmdRoute
  '/{-$locale}/_docs/terms-of-service': typeof Char123LocaleChar125DocsTermsOfServiceRoute
  '/{-$locale}/_docs/terms-of-service.md': typeof Char123LocaleChar125DocsTermsOfServiceDotmdRoute
  '/{-$locale}/_playground/playground': typeof Char123LocaleChar125PlaygroundPlaygroundRoute
  '/.well-known/agent-skills/$skill/SKILL.md': typeof DotwellKnownAgentSkillsSkillSKILLDotmdRoute
  '/{-$locale}/_docs/blog/$': typeof Char123LocaleChar125DocsBlogSplatRoute
  '/{-$locale}/_docs/blog/search': typeof Char123LocaleChar125DocsBlogSearchRoute
  '/{-$locale}/_docs/doc/$': typeof Char123LocaleChar125DocsDocSplatRoute
  '/{-$locale}/_docs/doc/chat': typeof Char123LocaleChar125DocsDocChatRoute
  '/{-$locale}/_docs/doc/search': typeof Char123LocaleChar125DocsDocSearchRoute
  '/{-$locale}/_docs/frequent-questions/$': typeof Char123LocaleChar125DocsFrequentQuestionsSplatRoute
  '/{-$locale}/blog/raw/$': typeof Char123LocaleChar125BlogRawSplatRoute
  '/{-$locale}/doc/raw/$': typeof Char123LocaleChar125DocRawSplatRoute
  '/{-$locale}/frequent-questions/raw/$': typeof Char123LocaleChar125FrequentQuestionsRawSplatRoute
  '/{-$locale}/_docs/blog/': typeof Char123LocaleChar125DocsBlogIndexRoute
  '/{-$locale}/_docs/frequent-questions/': typeof Char123LocaleChar125DocsFrequentQuestionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/auth.md'
    | '/feed.xml'
    | '/posts.json'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/.well-known/ai-catalog.json'
    | '/.well-known/api-catalog'
    | '/.well-known/oauth-protected-resource'
    | '/api/baidu-push'
    | '/api/health'
    | '/{-$locale}/$'
    | '/{-$locale}/cms'
    | '/{-$locale}/contributors'
    | '/{-$locale}/demo'
    | '/{-$locale}/i18n-message-converter'
    | '/{-$locale}/i18n-seo-scanner'
    | '/{-$locale}/markdown'
    | '/{-$locale}/tms'
    | '/{-$locale}/translate'
    | '/{-$locale}/'
    | '/.well-known/agent-skills/index.json'
    | '/.well-known/mcp/server-card.json'
    | '/api/proxy/ahrefs-analytics'
    | '/{-$locale}/privacy-notice'
    | '/{-$locale}/privacy-notice.md'
    | '/{-$locale}/terms-of-service'
    | '/{-$locale}/terms-of-service.md'
    | '/{-$locale}/playground'
    | '/.well-known/agent-skills/$skill/SKILL.md'
    | '/{-$locale}/blog/$'
    | '/{-$locale}/blog/search'
    | '/{-$locale}/doc/$'
    | '/{-$locale}/doc/chat'
    | '/{-$locale}/doc/search'
    | '/{-$locale}/frequent-questions/$'
    | '/{-$locale}/blog/raw/$'
    | '/{-$locale}/doc/raw/$'
    | '/{-$locale}/frequent-questions/raw/$'
    | '/{-$locale}/blog/'
    | '/{-$locale}/frequent-questions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth.md'
    | '/feed.xml'
    | '/posts.json'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/{-$locale}'
    | '/.well-known/ai-catalog.json'
    | '/.well-known/api-catalog'
    | '/.well-known/oauth-protected-resource'
    | '/api/baidu-push'
    | '/api/health'
    | '/{-$locale}/$'
    | '/{-$locale}/cms'
    | '/{-$locale}/contributors'
    | '/{-$locale}/demo'
    | '/{-$locale}/i18n-message-converter'
    | '/{-$locale}/i18n-seo-scanner'
    | '/{-$locale}/markdown'
    | '/{-$locale}/tms'
    | '/{-$locale}/translate'
    | '/.well-known/agent-skills/index.json'
    | '/.well-known/mcp/server-card.json'
    | '/api/proxy/ahrefs-analytics'
    | '/{-$locale}/privacy-notice'
    | '/{-$locale}/privacy-notice.md'
    | '/{-$locale}/terms-of-service'
    | '/{-$locale}/terms-of-service.md'
    | '/{-$locale}/playground'
    | '/.well-known/agent-skills/$skill/SKILL.md'
    | '/{-$locale}/blog/$'
    | '/{-$locale}/blog/search'
    | '/{-$locale}/doc/$'
    | '/{-$locale}/doc/chat'
    | '/{-$locale}/doc/search'
    | '/{-$locale}/frequent-questions/$'
    | '/{-$locale}/blog/raw/$'
    | '/{-$locale}/doc/raw/$'
    | '/{-$locale}/frequent-questions/raw/$'
    | '/{-$locale}/blog'
    | '/{-$locale}/frequent-questions'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/auth.md'
    | '/feed.xml'
    | '/posts.json'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/{-$locale}/_docs'
    | '/{-$locale}/_playground'
    | '/.well-known/ai-catalog.json'
    | '/.well-known/api-catalog'
    | '/.well-known/oauth-protected-resource'
    | '/api/baidu-push'
    | '/api/health'
    | '/{-$locale}/$'
    | '/{-$locale}/cms'
    | '/{-$locale}/contributors'
    | '/{-$locale}/demo'
    | '/{-$locale}/i18n-message-converter'
    | '/{-$locale}/i18n-seo-scanner'
    | '/{-$locale}/markdown'
    | '/{-$locale}/tms'
    | '/{-$locale}/translate'
    | '/{-$locale}/'
    | '/.well-known/agent-skills/index.json'
    | '/.well-known/mcp/server-card.json'
    | '/api/proxy/ahrefs-analytics'
    | '/{-$locale}/_docs/privacy-notice'
    | '/{-$locale}/_docs/privacy-notice.md'
    | '/{-$locale}/_docs/terms-of-service'
    | '/{-$locale}/_docs/terms-of-service.md'
    | '/{-$locale}/_playground/playground'
    | '/.well-known/agent-skills/$skill/SKILL.md'
    | '/{-$locale}/_docs/blog/$'
    | '/{-$locale}/_docs/blog/search'
    | '/{-$locale}/_docs/doc/$'
    | '/{-$locale}/_docs/doc/chat'
    | '/{-$locale}/_docs/doc/search'
    | '/{-$locale}/_docs/frequent-questions/$'
    | '/{-$locale}/blog/raw/$'
    | '/{-$locale}/doc/raw/$'
    | '/{-$locale}/frequent-questions/raw/$'
    | '/{-$locale}/_docs/blog/'
    | '/{-$locale}/_docs/frequent-questions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren
  AuthDotmdRoute: typeof AuthDotmdRoute
  FeedDotxmlRoute: typeof FeedDotxmlRoute
  PostsDotjsonRoute: typeof PostsDotjsonRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DotwellKnownAiCatalogDotjsonRoute: typeof DotwellKnownAiCatalogDotjsonRoute
  DotwellKnownApiCatalogRoute: typeof DotwellKnownApiCatalogRoute
  DotwellKnownOauthProtectedResourceRoute: typeof DotwellKnownOauthProtectedResourceRoute
  ApiBaiduPushRoute: typeof ApiBaiduPushRoute
  ApiHealthRoute: typeof ApiHealthRoute
  DotwellKnownAgentSkillsIndexDotjsonRoute: typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  DotwellKnownMcpServerCardDotjsonRoute: typeof DotwellKnownMcpServerCardDotjsonRoute
  ApiProxyAhrefsAnalyticsRoute: typeof ApiProxyAhrefsAnalyticsRoute
  DotwellKnownAgentSkillsSkillSKILLDotmdRoute: typeof DotwellKnownAgentSkillsSkillSKILLDotmdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth.md': {
      id: '/auth.md'
      path: '/auth.md'
      fullPath: '/auth.md'
      preLoaderRoute: typeof AuthDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed.xml': {
      id: '/feed.xml'
      path: '/feed.xml'
      fullPath: '/feed.xml'
      preLoaderRoute: typeof FeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts.json': {
      id: '/posts.json'
      path: '/posts.json'
      fullPath: '/posts.json'
      preLoaderRoute: typeof PostsDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/ai-catalog.json': {
      id: '/.well-known/ai-catalog.json'
      path: '/.well-known/ai-catalog.json'
      fullPath: '/.well-known/ai-catalog.json'
      preLoaderRoute: typeof DotwellKnownAiCatalogDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/api-catalog': {
      id: '/.well-known/api-catalog'
      path: '/.well-known/api-catalog'
      fullPath: '/.well-known/api-catalog'
      preLoaderRoute: typeof DotwellKnownApiCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/baidu-push': {
      id: '/api/baidu-push'
      path: '/api/baidu-push'
      fullPath: '/api/baidu-push'
      preLoaderRoute: typeof ApiBaiduPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/$': {
      id: '/{-$locale}/$'
      path: '/$'
      fullPath: '/{-$locale}/$'
      preLoaderRoute: typeof Char123LocaleChar125SplatRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/_docs': {
      id: '/{-$locale}/_docs'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125DocsRouteRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/_playground': {
      id: '/{-$locale}/_playground'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125PlaygroundRouteRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/cms': {
      id: '/{-$locale}/cms'
      path: '/cms'
      fullPath: '/{-$locale}/cms'
      preLoaderRoute: typeof Char123LocaleChar125CmsRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/contributors': {
      id: '/{-$locale}/contributors'
      path: '/contributors'
      fullPath: '/{-$locale}/contributors'
      preLoaderRoute: typeof Char123LocaleChar125ContributorsRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/demo': {
      id: '/{-$locale}/demo'
      path: '/demo'
      fullPath: '/{-$locale}/demo'
      preLoaderRoute: typeof Char123LocaleChar125DemoRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/i18n-message-converter': {
      id: '/{-$locale}/i18n-message-converter'
      path: '/i18n-message-converter'
      fullPath: '/{-$locale}/i18n-message-converter'
      preLoaderRoute: typeof Char123LocaleChar125I18nMessageConverterRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/i18n-seo-scanner': {
      id: '/{-$locale}/i18n-seo-scanner'
      path: '/i18n-seo-scanner'
      fullPath: '/{-$locale}/i18n-seo-scanner'
      preLoaderRoute: typeof Char123LocaleChar125I18nSeoScannerRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/markdown': {
      id: '/{-$locale}/markdown'
      path: '/markdown'
      fullPath: '/{-$locale}/markdown'
      preLoaderRoute: typeof Char123LocaleChar125MarkdownRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/tms': {
      id: '/{-$locale}/tms'
      path: '/tms'
      fullPath: '/{-$locale}/tms'
      preLoaderRoute: typeof Char123LocaleChar125TmsRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/translate': {
      id: '/{-$locale}/translate'
      path: '/translate'
      fullPath: '/{-$locale}/translate'
      preLoaderRoute: typeof Char123LocaleChar125TranslateRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/.well-known/agent-skills/index.json': {
      id: '/.well-known/agent-skills/index.json'
      path: '/.well-known/agent-skills/index.json'
      fullPath: '/.well-known/agent-skills/index.json'
      preLoaderRoute: typeof DotwellKnownAgentSkillsIndexDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/mcp/server-card.json': {
      id: '/.well-known/mcp/server-card.json'
      path: '/.well-known/mcp/server-card.json'
      fullPath: '/.well-known/mcp/server-card.json'
      preLoaderRoute: typeof DotwellKnownMcpServerCardDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy/ahrefs-analytics': {
      id: '/api/proxy/ahrefs-analytics'
      path: '/api/proxy/ahrefs-analytics'
      fullPath: '/api/proxy/ahrefs-analytics'
      preLoaderRoute: typeof ApiProxyAhrefsAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/_docs/privacy-notice': {
      id: '/{-$locale}/_docs/privacy-notice'
      path: '/privacy-notice'
      fullPath: '/{-$locale}/privacy-notice'
      preLoaderRoute: typeof Char123LocaleChar125DocsPrivacyNoticeRouteImport
      parentRoute: typeof Char123LocaleChar125DocsRouteRoute
    }
    '/{-$locale}/_docs/privacy-notice.md': {
      id: '/{-$locale}/_docs/privacy-notice.md'
      path: '/privacy-notice.md'
      fullPath: '/{-$locale}/privacy-notice.md'
      preLoaderRoute: typeof Char123LocaleChar125DocsPrivacyNoticeDotmdRouteImport
      parentRoute: typeof Char123LocaleChar125DocsRouteRoute
    }
    '/{-$locale}/_docs/terms-of-service': {
      id: '/{-$locale}/_docs/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/{-$locale}/terms-of-service'
      preLoaderRoute: typeof Char123LocaleChar125DocsTermsOfServiceRouteImport
      parentRoute: typeof Char123LocaleChar125DocsRouteRoute
    }
    '/{-$locale}/_docs/terms-of-service.md': {
      id: '/{-$locale}/_docs/terms-of-service.md'
      path: '/terms-of-service.md'
      fullPath: '/{-$locale}/terms-of-service.md'
      preLoaderRoute: typeof Char123LocaleChar125DocsTermsOfServiceDotmdRouteImport
      parentRoute: typeof Char123LocaleChar125DocsRouteRoute
    }
    '/{-$locale}/_playground/playground': {
      id: '/{-$locale}/_playground/playground'
      path: '/playground'
      fullPath: '/{-$locale}/playground'
      preLoaderRoute: typeof Char123LocaleChar125PlaygroundPlaygroundRouteImport
      parentRoute: typeof Char123LocaleChar125PlaygroundRouteRoute
    }
    '/.well-known/agent-skills/$skill/SKILL.md': {
      id: '/.well-known/agent-skills/$skill/SKILL.md'
      path: '/.well-known/agent-skills/$skill/SKILL.md'
      fullPath: '/.well-known/agent-skills/$skill/SKILL.md'
      preLoaderRoute: typeof DotwellKnownAgentSkillsSkillSKILLDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/_docs/blog/': {
      id: '/{-$locale}/_docs/blog/'
      path: '/blog'
      fullPath: '/{-$locale}/blog/'
      preLoaderRoute: typeof Char123LocaleChar125DocsBlogIndexRouteImport
      parentRoute: typeof Char123LocaleChar125DocsRouteRoute
    }
    '/{-$locale}/_docs/blog/$': {
      id: '/{-$locale}/_docs/blog/$'
      path: '/blog/$'
      fullPath: '/{-$locale}/blog/$'
      preLoaderRoute: typeof Char123LocaleChar125DocsBlogSplatRouteImport
      parentRoute: typeof Char123LocaleChar125DocsRouteRoute
    }
    '/{-$locale}/_docs/blog/search': {
      id: '/{-$locale}/_docs/blog/search'
      path: '/blog/search'
      fullPath: '/{-$locale}/blog/search'
      preLoaderRoute: typeof Char123LocaleChar125DocsBlogSearchRouteImport
      parentRoute: typeof Char123LocaleChar125DocsRouteRoute
    }
    '/{-$locale}/_docs/doc/$': {
      id: '/{-$locale}/_docs/doc/$'
      path: '/doc/$'
      fullPath: '/{-$locale}/doc/$'
      preLoaderRoute: typeof Char123LocaleChar125DocsDocSplatRouteImport
      parentRoute: typeof Char123LocaleChar125DocsRouteRoute
    }
    '/{-$locale}/_docs/doc/chat': {
      id: '/{-$locale}/_docs/doc/chat'
      path: '/doc/chat'
      fullPath: '/{-$locale}/doc/chat'
      preLoaderRoute: typeof Char123LocaleChar125DocsDocChatRouteImport
      parentRoute: typeof Char123LocaleChar125DocsRouteRoute
    }
    '/{-$locale}/_docs/doc/search': {
      id: '/{-$locale}/_docs/doc/search'
      path: '/doc/search'
      fullPath: '/{-$locale}/doc/search'
      preLoaderRoute: typeof Char123LocaleChar125DocsDocSearchRouteImport
      parentRoute: typeof Char123LocaleChar125DocsRouteRoute
    }
    '/{-$locale}/_docs/frequent-questions/': {
      id: '/{-$locale}/_docs/frequent-questions/'
      path: '/frequent-questions'
      fullPath: '/{-$locale}/frequent-questions/'
      preLoaderRoute: typeof Char123LocaleChar125DocsFrequentQuestionsIndexRouteImport
      parentRoute: typeof Char123LocaleChar125DocsRouteRoute
    }
    '/{-$locale}/_docs/frequent-questions/$': {
      id: '/{-$locale}/_docs/frequent-questions/$'
      path: '/frequent-questions/$'
      fullPath: '/{-$locale}/frequent-questions/$'
      preLoaderRoute: typeof Char123LocaleChar125DocsFrequentQuestionsSplatRouteImport
      parentRoute: typeof Char123LocaleChar125DocsRouteRoute
    }
    '/{-$locale}/blog/raw/$': {
      id: '/{-$locale}/blog/raw/$'
      path: '/blog/raw/$'
      fullPath: '/{-$locale}/blog/raw/$'
      preLoaderRoute: typeof Char123LocaleChar125BlogRawSplatRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/doc/raw/$': {
      id: '/{-$locale}/doc/raw/$'
      path: '/doc/raw/$'
      fullPath: '/{-$locale}/doc/raw/$'
      preLoaderRoute: typeof Char123LocaleChar125DocRawSplatRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/frequent-questions/raw/$': {
      id: '/{-$locale}/frequent-questions/raw/$'
      path: '/frequent-questions/raw/$'
      fullPath: '/{-$locale}/frequent-questions/raw/$'
      preLoaderRoute: typeof Char123LocaleChar125FrequentQuestionsRawSplatRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
  }
}

interface Char123LocaleChar125DocsRouteRouteChildren {
  Char123LocaleChar125DocsPrivacyNoticeRoute: typeof Char123LocaleChar125DocsPrivacyNoticeRoute
  Char123LocaleChar125DocsPrivacyNoticeDotmdRoute: typeof Char123LocaleChar125DocsPrivacyNoticeDotmdRoute
  Char123LocaleChar125DocsTermsOfServiceRoute: typeof Char123LocaleChar125DocsTermsOfServiceRoute
  Char123LocaleChar125DocsTermsOfServiceDotmdRoute: typeof Char123LocaleChar125DocsTermsOfServiceDotmdRoute
  Char123LocaleChar125DocsBlogSplatRoute: typeof Char123LocaleChar125DocsBlogSplatRoute
  Char123LocaleChar125DocsBlogSearchRoute: typeof Char123LocaleChar125DocsBlogSearchRoute
  Char123LocaleChar125DocsDocSplatRoute: typeof Char123LocaleChar125DocsDocSplatRoute
  Char123LocaleChar125DocsDocChatRoute: typeof Char123LocaleChar125DocsDocChatRoute
  Char123LocaleChar125DocsDocSearchRoute: typeof Char123LocaleChar125DocsDocSearchRoute
  Char123LocaleChar125DocsFrequentQuestionsSplatRoute: typeof Char123LocaleChar125DocsFrequentQuestionsSplatRoute
  Char123LocaleChar125DocsBlogIndexRoute: typeof Char123LocaleChar125DocsBlogIndexRoute
  Char123LocaleChar125DocsFrequentQuestionsIndexRoute: typeof Char123LocaleChar125DocsFrequentQuestionsIndexRoute
}

const Char123LocaleChar125DocsRouteRouteChildren: Char123LocaleChar125DocsRouteRouteChildren =
  {
    Char123LocaleChar125DocsPrivacyNoticeRoute:
      Char123LocaleChar125DocsPrivacyNoticeRoute,
    Char123LocaleChar125DocsPrivacyNoticeDotmdRoute:
      Char123LocaleChar125DocsPrivacyNoticeDotmdRoute,
    Char123LocaleChar125DocsTermsOfServiceRoute:
      Char123LocaleChar125DocsTermsOfServiceRoute,
    Char123LocaleChar125DocsTermsOfServiceDotmdRoute:
      Char123LocaleChar125DocsTermsOfServiceDotmdRoute,
    Char123LocaleChar125DocsBlogSplatRoute:
      Char123LocaleChar125DocsBlogSplatRoute,
    Char123LocaleChar125DocsBlogSearchRoute:
      Char123LocaleChar125DocsBlogSearchRoute,
    Char123LocaleChar125DocsDocSplatRoute:
      Char123LocaleChar125DocsDocSplatRoute,
    Char123LocaleChar125DocsDocChatRoute: Char123LocaleChar125DocsDocChatRoute,
    Char123LocaleChar125DocsDocSearchRoute:
      Char123LocaleChar125DocsDocSearchRoute,
    Char123LocaleChar125DocsFrequentQuestionsSplatRoute:
      Char123LocaleChar125DocsFrequentQuestionsSplatRoute,
    Char123LocaleChar125DocsBlogIndexRoute:
      Char123LocaleChar125DocsBlogIndexRoute,
    Char123LocaleChar125DocsFrequentQuestionsIndexRoute:
      Char123LocaleChar125DocsFrequentQuestionsIndexRoute,
  }

const Char123LocaleChar125DocsRouteRouteWithChildren =
  Char123LocaleChar125DocsRouteRoute._addFileChildren(
    Char123LocaleChar125DocsRouteRouteChildren,
  )

interface Char123LocaleChar125PlaygroundRouteRouteChildren {
  Char123LocaleChar125PlaygroundPlaygroundRoute: typeof Char123LocaleChar125PlaygroundPlaygroundRoute
}

const Char123LocaleChar125PlaygroundRouteRouteChildren: Char123LocaleChar125PlaygroundRouteRouteChildren =
  {
    Char123LocaleChar125PlaygroundPlaygroundRoute:
      Char123LocaleChar125PlaygroundPlaygroundRoute,
  }

const Char123LocaleChar125PlaygroundRouteRouteWithChildren =
  Char123LocaleChar125PlaygroundRouteRoute._addFileChildren(
    Char123LocaleChar125PlaygroundRouteRouteChildren,
  )

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125DocsRouteRoute: typeof Char123LocaleChar125DocsRouteRouteWithChildren
  Char123LocaleChar125PlaygroundRouteRoute: typeof Char123LocaleChar125PlaygroundRouteRouteWithChildren
  Char123LocaleChar125SplatRoute: typeof Char123LocaleChar125SplatRoute
  Char123LocaleChar125CmsRoute: typeof Char123LocaleChar125CmsRoute
  Char123LocaleChar125ContributorsRoute: typeof Char123LocaleChar125ContributorsRoute
  Char123LocaleChar125DemoRoute: typeof Char123LocaleChar125DemoRoute
  Char123LocaleChar125I18nMessageConverterRoute: typeof Char123LocaleChar125I18nMessageConverterRoute
  Char123LocaleChar125I18nSeoScannerRoute: typeof Char123LocaleChar125I18nSeoScannerRoute
  Char123LocaleChar125MarkdownRoute: typeof Char123LocaleChar125MarkdownRoute
  Char123LocaleChar125TmsRoute: typeof Char123LocaleChar125TmsRoute
  Char123LocaleChar125TranslateRoute: typeof Char123LocaleChar125TranslateRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
  Char123LocaleChar125BlogRawSplatRoute: typeof Char123LocaleChar125BlogRawSplatRoute
  Char123LocaleChar125DocRawSplatRoute: typeof Char123LocaleChar125DocRawSplatRoute
  Char123LocaleChar125FrequentQuestionsRawSplatRoute: typeof Char123LocaleChar125FrequentQuestionsRawSplatRoute
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125DocsRouteRoute:
      Char123LocaleChar125DocsRouteRouteWithChildren,
    Char123LocaleChar125PlaygroundRouteRoute:
      Char123LocaleChar125PlaygroundRouteRouteWithChildren,
    Char123LocaleChar125SplatRoute: Char123LocaleChar125SplatRoute,
    Char123LocaleChar125CmsRoute: Char123LocaleChar125CmsRoute,
    Char123LocaleChar125ContributorsRoute:
      Char123LocaleChar125ContributorsRoute,
    Char123LocaleChar125DemoRoute: Char123LocaleChar125DemoRoute,
    Char123LocaleChar125I18nMessageConverterRoute:
      Char123LocaleChar125I18nMessageConverterRoute,
    Char123LocaleChar125I18nSeoScannerRoute:
      Char123LocaleChar125I18nSeoScannerRoute,
    Char123LocaleChar125MarkdownRoute: Char123LocaleChar125MarkdownRoute,
    Char123LocaleChar125TmsRoute: Char123LocaleChar125TmsRoute,
    Char123LocaleChar125TranslateRoute: Char123LocaleChar125TranslateRoute,
    Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
    Char123LocaleChar125BlogRawSplatRoute:
      Char123LocaleChar125BlogRawSplatRoute,
    Char123LocaleChar125DocRawSplatRoute: Char123LocaleChar125DocRawSplatRoute,
    Char123LocaleChar125FrequentQuestionsRawSplatRoute:
      Char123LocaleChar125FrequentQuestionsRawSplatRoute,
  }

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
  AuthDotmdRoute: AuthDotmdRoute,
  FeedDotxmlRoute: FeedDotxmlRoute,
  PostsDotjsonRoute: PostsDotjsonRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DotwellKnownAiCatalogDotjsonRoute: DotwellKnownAiCatalogDotjsonRoute,
  DotwellKnownApiCatalogRoute: DotwellKnownApiCatalogRoute,
  DotwellKnownOauthProtectedResourceRoute:
    DotwellKnownOauthProtectedResourceRoute,
  ApiBaiduPushRoute: ApiBaiduPushRoute,
  ApiHealthRoute: ApiHealthRoute,
  DotwellKnownAgentSkillsIndexDotjsonRoute:
    DotwellKnownAgentSkillsIndexDotjsonRoute,
  DotwellKnownMcpServerCardDotjsonRoute: DotwellKnownMcpServerCardDotjsonRoute,
  ApiProxyAhrefsAnalyticsRoute: ApiProxyAhrefsAnalyticsRoute,
  DotwellKnownAgentSkillsSkillSKILLDotmdRoute:
    DotwellKnownAgentSkillsSkillSKILLDotmdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
