export enum PagesRoutes {
  Home = '/',
  Demo = '/demo',
  NotFound = '/404',

  Dashboard = '/dashboard',
  Dashboard_Content = '/dashboard/content',
  Dashboard_Projects = '/dashboard/projects',
  Dashboard_Organization = '/dashboard/organization',
  Dashboard_Profile = '/dashboard/profile',

  Doc = '/doc',
  Doc_Search = '/doc/search',
  Doc_GetStarted = '/doc/get-started',
  Doc_HowWorksIntlayer = '/doc/concept/how-works-intlayer',
  Doc_Configuration = '/doc/concept/configuration',
  Doc_Interest = '/doc/concept/interest',
  Doc_IntlayerEditor = '/doc/concept/editor',
  Doc_CLI = '/doc/concept/cli',
  Doc_ContentDeclaration = '/doc/concept/content',
  Doc_ContentDeclaration_Translation = '/doc/concept/content/translation',
  Doc_ContentDeclaration_Enumeration = '/doc/concept/content/enumeration',
  Doc_ContentDeclaration_FunctionFetching = '/doc/concept/content/function-fetching',
  Doc_Environment_NextJS_15 = '/doc/environment/nextjs',
  Doc_Environment_NextJS_14 = '/doc/environment/nextjs/14',
  Doc_Intlayer_with_NextJS_using_Page_Router = '/doc/environment/nextjs/next-with-Page-Router',
  Doc_Environment_CRA = '/doc/environment/create-react-app',
  Doc_Environment_ViteAndReact = '/doc/environment/vite-and-react',
  Doc_Environment_Express = '/doc/environment/express',
  Doc_Intlayer_with_I18next = '/doc/blog/i18next',
  'Doc_Packages_express-intlayer_t' = '/doc/packages/express-intlayer/t',
  'Doc_Packages_react-intlayer_t' = '/doc/packages/react-intlayer/t',
  'Doc_Packages_react-intlayer_useIntlayer' = '/doc/packages/react-intlayer/useIntlayer',
  'Doc_Packages_react-intlayer_useDictionary' = '/doc/packages/react-intlayer/useDictionary',
  'Doc_Packages_react-intlayer_useLocale' = '/doc/packages/react-intlayer/useLocale',
  'Doc_Packages_next-intlayer_t' = '/doc/packages/next-intlayer/t',
  'Doc_Packages_next-intlayer_useIntlayer' = '/doc/packages/next-intlayer/useIntlayer',
  'Doc_Packages_next-intlayer_useDictionary' = '/doc/packages/next-intlayer/useDictionary',
  'Doc_Packages_next-intlayer_useLocale' = '/doc/packages/next-intlayer/useLocale',

  PrivacyPolicy = '/privacy-notice',
  TermsOfService = '/terms-of-service',

  Pricing = '/pricing',

  Onboarding = '/onboarding',
  Onboarding_Flow = '/onboarding/{{step}}/{{plan}}/{{period}}',

  Auth_SignIn = '/auth/login',
  Auth_SignUp = '/auth/register',
  Auth_ResetPassword = '/auth/password/reset',
  Auth_ChangePassword = '/auth/password/change',
}

export enum ExternalLinks {
  Github = 'https://github.com/aymericzip/intlayer',
  LinkedIn = 'https://www.linkedin.com/company/intlayerorg/',
  ExampleIntlayerWithNextjs = 'https://github.com/aymericzip/intlayer/tree/3c64451e85648f8a354a54d84216a27b68f4cb2d/examples/nextjs-app',
  ExampleIntlayerWithReactJS = 'https://github.com/aymericzip/intlayer/tree/3c64451e85648f8a354a54d84216a27b68f4cb2d/examples/react-app',
  ExampleIntlayerWithViteAndReact = 'https://github.com/aymericzip/intlayer/tree/3c64451e85648f8a354a54d84216a27b68f4cb2d/examples/vite-app',
}

export enum GithubRoutes {
  Introduction = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/introduction_en.md',
  HowWorksIntlayer = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/how_works_intlayer_en.md',
  Configuration = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/configuration_en.md',
  InterestOfIntlayer = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/interest_of_intlayer_en.md',
  IntlayerCLI = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/intlayer_cli_en.md',
  IntlayerEditor = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/intlayer_editor_en.md',
  IntlayerWithNextJS15 = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/intlayer_with_nextjs_15_en.md',
  IntlayerWithNextJS14 = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/intlayer_with_nextjs_14_en.md',
  IntlayerWithNextJSUsingPageRouter = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/intlayer_with_nextjs_page_router_en.md',
  IntlayerWithReactCRA = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/intlayer_with_create_react_app_en.md',
  IntlayerWithViteReact = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/intlayer_with_vite+react_en.md',
  IntlayerWithI18next = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/intlayer_with_i18next_en.md',
  IntlayerWithExpress = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/intlayer_with_express_en.md',
  ContentDeclaration_GetStarted = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/content/get_started_en.md',
  ContentDeclaration_ContentExtensionCustomization = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/content/content_extention_customization_en.md',
  ContentDeclaration_Enumeration = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/content/enumeration_en.md',
  ContentDeclaration_FunctionFetching = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/content/function_fetching_en.md',
  ContentDeclaration_NestedId = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/content/nested_id_en.md',
  ContentDeclaration_Translation = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/content/translation_en.md',
  'Packages_express-intlayer_t' = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/packages/express-intlayer/t_en.md',
  'Packages_react-intlayer_t' = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/packages/react-intlayer/t_en.md',
  'Packages_react-intlayer_useIntlayer' = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/packages/react-intlayer/useIntlayer_en.md',
  'Packages_react-intlayer_useDictionary' = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/packages/react-intlayer/useDictionary_en.md',
  'Packages_react-intlayer_useLocale' = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/packages/react-intlayer/useLocale_en.md',
  'Packages_next-intlayer_t' = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/packages/next-intlayer/t_en.md',
  'Packages_next-intlayer_useIntlayer' = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/packages/next-intlayer/useIntlayer_en.md',
  'Packages_next-intlayer_useDictionary' = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/packages/next-intlayer/useDictionary_en.md',
  'Packages_next-intlayer_useLocale' = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/packages/next-intlayer/useLocale_en.md',
  PrivacyPolicy = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/privacy_notice_en.md',
  TermsOfService = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/terms_of_service_en.md',
}
