export enum PagesRoutes {
  Home = '/',
  Demo = '/demo',
  NotFound = '/404',

  Dashboard = '/dashboard',
  Dashboard_Content = '/dashboard/content',
  Dashboard_Projects = '/dashboard/projects',
  Dashboard_Organization = '/dashboard/organization',
  Dashboard_Profile = '/dashboard/profile',

  Doc = '/doc',
  Doc_GetStarted = '/doc/get-started',
  Doc_HowWorksIntlayer = '/doc/concept/how-works-intlayer',
  Doc_Configuration = '/doc/concept/configuration',
  Doc_Interest = '/doc/concept/interest',
  Doc_IntlayerEditor = '/doc/concept/editor',
  Doc_CLI = '/doc/concept/cli',
  Doc_ContentDeclaration = '/doc/concept/content',
  Doc_ContentDeclaration_Translation = '/doc/concept/content/translation',
  Doc_ContentDeclaration_Enumeration = '/doc/concept/content/enumeration',
  Doc_ContentDeclaration_FunctionFetching = '/doc/concept/content/function-fetching',
  Doc_ContentDeclaration_NestedId = '/doc/concept/content/nested-id',
  Doc_Environment_NextJS = '/doc/environment/nextjs',
  Doc_Environment_CRA = '/doc/environment/create-react-app',
  Doc_Environment_ViteAndReact = '/doc/environment/vite-and-react',
  Doc_Environment_Express = '/doc/environment/express',
  Doc_Intlayer_with_I18next = '/doc/blog/i18next',

  PrivacyPolicy = '/privacy_notice',
  TermsOfService = '/terms_of_service',

  Pricing = '/pricing',

  Onboarding = '/onboarding',
  Onboarding_VerifyEmail = '/onboarding/verify_email',
  Onboarding_Registration = '/onboarding/registration',
  Onboarding_Password = '/onboarding/password',
  Onboarding_SetupOrganization = '/onboarding/setup_organization',
  Onboarding_Payment = '/onboarding/payment',

  Auth_SignIn = '/auth/login',
  Auth_SignUp = '/auth/register',
  Auth_ResetPassword = '/auth/password/reset',
  Auth_ChangePassword = '/auth/password/change',
}

export enum ExternalLinks {
  Github = 'https://github.com/aymericzip/intlayer',
  LinkedIn = 'https://www.linkedin.com/company/intlayerorg/',
  ExampleIntlayerWithNextjs = 'https://github.com/aymericzip/intlayer/tree/3c64451e85648f8a354a54d84216a27b68f4cb2d/examples/nextjs-app',
  ExampleIntlayerWithReactJS = 'https://github.com/aymericzip/intlayer/tree/3c64451e85648f8a354a54d84216a27b68f4cb2d/examples/react-app',
  ExampleIntlayerWithViteAndReact = 'https://github.com/aymericzip/intlayer/tree/3c64451e85648f8a354a54d84216a27b68f4cb2d/examples/vite-app',
}

export enum GithubRoutes {
  Introduction = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/introduction_en.md',
  HowWorksIntlayer = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/how_works_intlayer_en.md',
  Configuration = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/configuration_en.md',
  InterestOfIntlayer = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/interest_of_intlayer_en.md',
  IntlayerCLI = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/intlayer_cli_en.md',
  IntlayerEditor = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/intlayer_editor_en.md',
  IntlayerWithNextJS = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/intlayer_with_nextjs_en.md',
  IntlayerWithReactCRA = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/intlayer_with_create_react_app_en.md',
  IntlayerWithViteReact = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/intlayer_with_vite+react_en.md',
  IntlayerWithI18next = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/intlayer_with_i18next_en.md',
  IntlayerWithExpress = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/intlayer_with_express_en.md',
  ContentDeclaration_GetStarted = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/content/get_started_en.md',
  ContentDeclaration_ContentExtentionCustomization = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/content/content_extention_customization_en.md',
  ContentDeclaration_Enumeration = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/content/enumeration_en.md',
  ContentDeclaration_FunctionFetching = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/content/function_fetching_en.md',
  ContentDeclaration_NestedId = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/content/nested_id_en.md',
  ContentDeclaration_Translation = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/content/translation_en.md',
  PrivacyPolicy = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/privacy_notice_en.md',
  TermsOfService = 'https://github.com/aymericzip/intlayer/blob/main/docs/docs/terms_of_service_en.md',
}
