import { type Dictionary, t } from 'intlayer';

const affiliateInvitationPageContent = {
  key: 'affiliate-invitation-page',
  content: {
    invitationNotFound: t({
      en: 'Invitation not found',
      ru: 'Приглашение не найдено',
      ja: '招待状が見つかりません',
      fr: 'Invitation introuvable',
      ko: '초대장을 찾을 수 없습니다',
      zh: '未找到邀请',
      es: 'Invitación no encontrada',
      de: 'Einladung nicht gefunden',
      ar: 'الدعوة غير موجودة',
      it: 'Invito non trovato',
      'en-GB': 'Invitation not found',
      pt: 'Convite não encontrado',
      hi: 'निमंत्रण नहीं मिला',
      tr: 'Davetiye bulunamadı',
      pl: 'Nie znaleziono zaproszenia',
      id: 'Undangan tidak ditemukan',
      vi: 'Không tìm thấy lời mời',
      uk: 'Запрошення не знайдено',
    }),

    thisInvitationLinkIsInvalid: t({
      en: 'This invitation link is invalid or has expired. Please contact us if you believe this is a mistake.',
      ru: 'Эта ссылка-приглашение недействительна или срок ее действия истек. Пожалуйста, свяжитесь с нами, если вы считаете, что это ошибка.',
      ja: 'この招待リンクは無効であるか、期限切れです。これが間違いであると思われる場合は、お問い合わせください。',
      fr: "Ce lien d'invitation est invalide ou a expiré. Veuillez nous contacter si vous pensez qu'il s'agit d'une erreur.",
      ko: '이 초대 링크가 유효하지 않거나 만료되었습니다. 실수라고 생각되시면 저희에게 연락해 주세요.',
      zh: '此邀请链接无效或已过期。如果您认为这是错误，请与我们联系。',
      es: 'Este enlace de invitación es inválido o ha caducado. Por favor contáctenos si cree que esto es un error.',
      de: 'Dieser Einladungslink ist ungültig oder abgelaufen. Bitte kontaktieren Sie uns, wenn Sie glauben, dass dies ein Fehler ist.',
      ar: 'رابط الدعوة هذا غير صالح أو انتهت صلاحيته. يرجى الاتصال بنا إذا كنت تعتقد أن هذا خطأ.',
      it: 'Questo link di invito non è valido o è scaduto. Ti preghiamo di contattarci se ritieni che si tratti di un errore.',
      'en-GB':
        'This invitation link is invalid or has expired. Please contact us if you believe this is a mistake.',
      pt: 'Este link de convite é inválido ou expirou. Entre em contato conosco se achar que isso é um erro.',
      hi: 'यह आमंत्रण लिंक अमान्य है या समाप्त हो गया है। यदि आपको लगता है कि यह कोई गलती है तो कृपया हमसे संपर्क करें।',
      tr: 'Bu davet bağlantısı geçersiz veya süresi dolmuş. Bunun bir hata olduğunu düşünüyorsanız lütfen bizimle iletişime geçin.',
      pl: 'Ten link z zaproszeniem jest nieważny lub wygasł. Skontaktuj się z nami, jeśli uważasz, że to błąd.',
      id: 'Tautan undangan ini tidak valid atau telah kedaluwarsa. Silakan hubungi kami jika Anda yakin ini adalah kesalahan.',
      vi: 'Liên kết lời mời này không hợp lệ hoặc đã hết hạn. Vui lòng liên hệ với chúng tôi nếu bạn cho rằng đây là sự nhầm lẫn.',
      uk: "Це посилання-запрошення недійсне або термін його дії минув. Будь ласка, зв'яжіться з нами, якщо ви вважаєте, що це помилка.",
    }),

    invitationAlreadyAccepted: t({
      en: 'Invitation already accepted',
      ru: 'Приглашение уже принято',
      ja: '招待状はすでに承認されています',
      fr: 'Invitation déjà acceptée',
      ko: '초대장이 이미 수락되었습니다',
      zh: '邀请已被接受',
      es: 'Invitación ya aceptada',
      de: 'Einladung bereits angenommen',
      ar: 'تم قبول الدعوة بالفعل',
      it: 'Invito già accettato',
      'en-GB': 'Invitation already accepted',
      pt: 'Convite já aceito',
      hi: 'निमंत्रण पहले ही स्वीकार कर लिया गया है',
      tr: 'Davetiye zaten kabul edildi',
      pl: 'Zaproszenie zostało już zaakceptowane',
      id: 'Undangan sudah diterima',
      vi: 'Lời mời đã được chấp nhận',
      uk: 'Запрошення вже прийнято',
    }),

    thisInvitationHasAlreadyBeen: t({
      en: 'This invitation has already been used. Log in to access your affiliate dashboard.',
      ru: 'Это приглашение уже было использовано. Войдите в систему, чтобы получить доступ к панели партнера.',
      ja: 'この招待状はすでに使用されています。ログインしてアフィリエイトダッシュボードにアクセスしてください。',
      fr: "Cette invitation a déjà été utilisée. Connectez-vous pour accéder à votre tableau de bord d'affiliation.",
      ko: '이 초대장은 이미 사용되었습니다. 제휴 대시보드에 액세스하려면 로그인하세요.',
      zh: '该邀请已被使用。登录即可访问您的会员仪表板。',
      es: 'Esta invitación ya ha sido utilizada. Inicie sesión para acceder a su panel de afiliado.',
      de: 'Diese Einladung wurde bereits verwendet. Melden Sie sich an, um auf Ihr Affiliate-Dashboard zuzugreifen.',
      ar: 'تم استخدام هذه الدعوة بالفعل. سجل الدخول للوصول إلى لوحة معلومات الشريك الخاصة بك.',
      it: 'Questo invito è già stato utilizzato. Accedi per visualizzare la tua dashboard affiliato.',
      'en-GB':
        'This invitation has already been used. Log in to access your affiliate dashboard.',
      pt: 'Este convite já foi usado. Faça login para acessar seu painel de afiliado.',
      hi: 'इस आमंत्रण का पहले ही उपयोग किया जा चुका है। अपने सहयोगी डैशबोर्ड तक पहुंचने के लिए लॉग इन करें।',
      tr: 'Bu davetiye zaten kullanılmış. Ortaklık kontrol panelinize erişmek için giriş yapın.',
      pl: 'To zaproszenie zostało już użyte. Zaloguj się, aby uzyskać dostęp do panelu partnerskiego.',
      id: 'Undangan ini sudah digunakan. Masuk untuk mengakses dasbor afiliasi Anda.',
      vi: 'Lời mời này đã được sử dụng. Đăng nhập để truy cập trang tổng quan đại lý của bạn.',
      uk: 'Це запрошення вже було використано. Увійдіть, щоб отримати доступ до панелі партнера.',
    }),

    invitationExpired: t({
      en: 'Invitation expired',
      ru: 'Приглашение истекло',
      ja: '招待状の有効期限が切れました',
      fr: 'Invitation expirée',
      ko: '초대장이 만료되었습니다',
      zh: '邀请已过期',
      es: 'Invitación caducada',
      de: 'Einladung abgelaufen',
      ar: 'انتهت صلاحية الدعوة',
      it: 'Invito scaduto',
      'en-GB': 'Invitation expired',
      pt: 'O convite expirou',
      hi: 'निमंत्रण की समय सीमा समाप्त',
      tr: 'Davetiyenin süresi doldu',
      pl: 'Zaproszenie wygasło',
      id: 'Undangan kedaluwarsa',
      vi: 'Lời mời đã hết hạn',
      uk: 'Термін дії запрошення минув',
    }),

    thisInvitationLinkHasExpired: t({
      en: 'This invitation link has expired. Please ask for a new invitation.',
      ru: 'Срок действия этой ссылки-приглашения истек. Пожалуйста, попросите новое приглашение.',
      ja: 'この招待リンクの有効期限が切れました。新しい招待状をリクエストしてください。',
      fr: "Ce lien d'invitation a expiré. Veuillez demander une nouvelle invitation.",
      ko: '이 초대 링크가 만료되었습니다. 새 초대장을 요청해 주세요.',
      zh: '此邀请链接已过期。请申请新的邀请。',
      es: 'Este enlace de invitación ha caducado. Por favor solicite una nueva invitación.',
      de: 'Dieser Einladungslink ist abgelaufen. Bitte fordern Sie eine neue Einladung an.',
      ar: 'انتهت صلاحية رابط الدعوة هذا. يرجى طلب دعوة جديدة.',
      it: 'Questo link di invito è scaduto. Ti preghiamo di richiedere un nuovo invito.',
      'en-GB':
        'This invitation link has expired. Please ask for a new invitation.',
      pt: 'Este link de convite expirou. Por favor, peça um novo convite.',
      hi: 'इस आमंत्रण लिंक की समय सीमा समाप्त हो गई है। कृपया नए आमंत्रण के लिए पूछें।',
      tr: 'Bu davet bağlantısının süresi doldu. Lütfen yeni bir davetiye isteyin.',
      pl: 'Ten link z zaproszeniem wygasł. Poproś o nowe zaproszenie.',
      id: 'Tautan undangan ini telah kedaluwarsa. Silakan minta undangan baru.',
      vi: 'Liên kết lời mời này đã hết hạn. Vui lòng yêu cầu một lời mời mới.',
      uk: 'Термін дії цього посилання-запрошення минув. Будь ласка, попросіть нове запрошення.',
    }),

    welcomeToTheAffiliateProgram: t({
      en: 'Welcome to the Affiliate Program!',
      ru: 'Добро пожаловать в партнерскую программу!',
      ja: 'アフィリエイトプログラムへようこそ！',
      fr: "Bienvenue dans le programme d'affiliation !",
      ko: '제휴 프로그램에 오신 것을 환영합니다!',
      zh: '欢迎加入联盟计划！',
      es: '¡Bienvenido al Programa de Afiliados!',
      de: 'Willkommen im Affiliate-Programm!',
      ar: 'مرحبًا بك في برنامج الشركاء التابعين!',
      it: 'Benvenuto nel programma di affiliazione!',
      'en-GB': 'Welcome to the Affiliate Program!',
      pt: 'Bem-vindo ao Programa de Afiliados!',
      hi: 'सहबद्ध कार्यक्रम में आपका स्वागत है!',
      tr: 'Ortaklık Programına Hoş Geldiniz!',
      pl: 'Witamy w programie partnerskim!',
      id: 'Selamat datang di Program Afiliasi!',
      vi: 'Chào mừng bạn đến với Chương trình Tiếp thị liên kết!',
      uk: 'Ласкаво просимо до партнерської програми!',
    }),

    completeTheSetupBelowTo: t({
      en: 'Complete the setup below to activate your affiliate account and start earning commissions.',
      ru: 'Завершите настройку ниже, чтобы активировать свой партнерский аккаунт и начать зарабатывать комиссионные.',
      ja: '以下の設定を完了してアフィリエイトアカウントを有効にし、コミッションの獲得を開始してください。',
      fr: "Complétez la configuration ci-dessous pour activer votre compte d'affiliation et commencer à gagner des commissions.",
      ko: '제휴 계정을 활성화하고 수수료를 받기 시작하려면 아래 설정을 완료하세요.',
      zh: '完成以下设置以激活您的会员帐户并开始赚取佣金。',
      es: 'Complete la configuración a continuación para activar su cuenta de afiliado y comenzar a ganar comisiones.',
      de: 'Schließen Sie die Einrichtung unten ab, um Ihr Affiliate-Konto zu aktivieren und Provisionen zu verdienen.',
      ar: 'أكمل الإعداد أدناه لتنشيط حساب الشريك الخاص بك والبدء في كسب العمولات.',
      it: 'Completa la configurazione qui sotto per attivare il tuo account affiliato e iniziare a guadagnare commissioni.',
      'en-GB':
        'Complete the setup below to activate your affiliate account and start earning commissions.',
      pt: 'Conclua a configuração abaixo para ativar sua conta de afiliado e começar a ganhar comissões.',
      hi: 'अपने सहयोगी खाते को सक्रिय करने और कमीशन अर्जित करना शुरू करने के लिए नीचे दिए गए सेटअप को पूरा करें।',
      tr: 'Ortaklık hesabınızı etkinleştirmek ve komisyon kazanmaya başlamak için aşağıdaki kurulumu tamamlayın.',
      pl: 'Zakończ konfigurację poniżej, aby aktywować swoje konto partnerskie i zacząć zarabiać prowizje.',
      id: 'Selesaikan pengaturan di bawah ini untuk mengaktifkan akun afiliasi Anda dan mulai mendapatkan komisi.',
      vi: 'Hoàn tất quá trình thiết lập bên dưới để kích hoạt tài khoản liên kết của bạn và bắt đầu kiếm tiền hoa hồng.',
      uk: 'Завершіть налаштування нижче, щоб активувати свій партнерський обліковий запис і почати заробляти комісійні.',
    }),

    affiliateProgramInvitation: t({
      en: 'Affiliate Program Invitation',
      ru: 'Приглашение в партнерскую программу',
      ja: 'アフィリエイトプログラムへの招待',
      fr: "Invitation au programme d'affiliation",
      ko: '제휴 프로그램 초대',
      zh: '会员计划邀请函',
      es: 'Invitación al Programa de Afiliados',
      de: 'Einladung zum Affiliate-Programm',
      ar: 'دعوة لبرنامج الشركاء التابعين',
      it: 'Invito al programma di affiliazione',
      'en-GB': 'Affiliate Program Invitation',
      pt: 'Convite para o Programa de Afiliados',
      hi: 'सहबद्ध कार्यक्रम आमंत्रण',
      tr: 'Ortaklık Programı Davetiyesi',
      pl: 'Zaproszenie do programu partnerskiego',
      id: 'Undangan Program Afiliasi',
      vi: 'Lời mời tham gia Chương trình Tiếp thị liên kết',
      uk: 'Запрошення до партнерської програми',
    }),

    youveBeenInvitedToJoin: t({
      en: "You've been invited to join the Intlayer Affiliate Program. Earn a commission for every subscription you refer.",
      ru: 'Вас пригласили присоединиться к партнерской программе Intlayer. Зарабатывайте комиссионные за каждую рекомендованную вами подписку.',
      ja: 'Intlayer アフィリエイト プログラムに参加するよう招待されました。紹介したサブスクリプションごとにコミッションを獲得できます。',
      fr: "Vous avez été invité à rejoindre le programme d'affiliation Intlayer. Gagnez une commission pour chaque abonnement que vous parrainez.",
      ko: 'Intlayer 제휴 프로그램에 초대되었습니다. 귀하가 추천한 구독마다 수수료를 받으세요.',
      zh: '您被邀请加入 Intlayer 联盟计划。每次推荐订阅即可赚取佣金。',
      es: 'Ha sido invitado a unirse al programa de afiliados de Intlayer. Gane una comisión por cada suscripción que recomiende.',
      de: 'Sie wurden eingeladen, dem Intlayer Affiliate-Programm beizutreten. Verdienen Sie eine Provision für jedes Abonnement, das Sie empfehlen.',
      ar: 'لقد تمت دعوتك للانضمام إلى برنامج الشركاء التابعين لـ Intlayer. اكسب عمولة على كل اشتراك تحيله.',
      it: 'Sei stato invitato a unirti al programma di affiliazione Intlayer. Guadagna una commissione per ogni abbonamento che segnali.',
      'en-GB':
        "You've been invited to join the Intlayer Affiliate Program. Earn a commission for every subscription you refer.",
      pt: 'Você foi convidado a participar do Programa de Afiliados da Intlayer. Ganhe uma comissão por cada assinatura que você indicar.',
      hi: 'आपको Intlayer सहयोगी कार्यक्रम में शामिल होने के लिए आमंत्रित किया गया है। आपके द्वारा संदर्भित प्रत्येक सदस्यता के लिए कमीशन अर्जित करें।',
      tr: 'Intlayer Ortaklık Programına katılmaya davet edildiniz. Yönlendirdiğiniz her abonelik için bir komisyon kazanın.',
      pl: 'Zostałeś zaproszony do dołączenia do programu partnerskiego Intlayer. Zarabiaj prowizję za każdą poleconą subskrypcję.',
      id: 'Anda telah diundang untuk bergabung dengan Program Afiliasi Intlayer. Dapatkan komisi untuk setiap langganan yang Anda referensikan.',
      vi: 'Bạn đã được mời tham gia Chương trình Tiếp thị liên kết Intlayer. Kiếm hoa hồng cho mỗi đăng ký mà bạn giới thiệu.',
      uk: 'Вас запросили приєднатися до партнерської програми Intlayer. Заробляйте комісію за кожну підписку, яку ви рекомендуєте.',
    }),

    commission: t({
      en: 'Commission',
      ru: 'Комиссия',
      ja: 'コミッション',
      fr: 'Commission',
      ko: '수수료',
      zh: '佣金',
      es: 'Comisión',
      de: 'Provision',
      ar: 'عمولة',
      it: 'Commissione',
      'en-GB': 'Commission',
      pt: 'Comissão',
      hi: 'कमीशन',
      tr: 'Komisyon',
      pl: 'Prowizja',
      id: 'Komisi',
      vi: 'Hoa hồng',
      uk: 'Комісія',
    }),

    invitationExpires: t({
      en: 'Invitation expires',
      ru: 'Приглашение истекает',
      ja: '招待状の有効期限',
      fr: "L'invitation expire",
      ko: '초대장 만료일',
      zh: '邀请到期',
      es: 'La invitación expira',
      de: 'Einladung läuft ab',
      ar: 'تنتهي صلاحية الدعوة',
      it: "L'invito scade",
      'en-GB': 'Invitation expires',
      pt: 'O convite expira',
      hi: 'निमंत्रण की समय सीमा समाप्त होती है',
      tr: 'Davetiyenin süresi doluyor',
      pl: 'Zaproszenie wygasa',
      id: 'Undangan kedaluwarsa',
      vi: 'Lời mời hết hạn',
      uk: 'Термін дії запрошення закінчується',
    }),

    failedToAcceptInvitationPlease: t({
      en: 'Failed to accept invitation. Please try again.',
      ru: 'Не удалось принять приглашение. Пожалуйста, попробуйте еще раз.',
      ja: '招待を承諾できませんでした。もう一度お試しください。',
      fr: "Échec de l'acceptation de l'invitation. Veuillez réessayer.",
      ko: '초대를 수락하지 못했습니다. 다시 시도해 주세요.',
      zh: '未能接受邀请。请重试。',
      es: 'No se pudo aceptar la invitación. Por favor inténtalo de nuevo.',
      de: 'Einladung konnte nicht angenommen werden. Bitte versuchen Sie es erneut.',
      ar: 'فشل في قبول الدعوة. يرجى المحاولة مرة أخرى.',
      it: "Impossibile accettare l'invito. Riprova.",
      'en-GB': 'Failed to accept invitation. Please try again.',
      pt: 'Falha ao aceitar o convite. Por favor, tente novamente.',
      hi: 'निमंत्रण स्वीकार करने में विफल। कृपया पुनः प्रयास करें।',
      tr: 'Davetiye kabul edilemedi. Lütfen tekrar deneyin.',
      pl: 'Nie udało się zaakceptować zaproszenia. Spróbuj ponownie.',
      id: 'Gagal menerima undangan. Silakan coba lagi.',
      vi: 'Không thể chấp nhận lời mời. Vui lòng thử lại.',
      uk: 'Не вдалося прийняти запрошення. Будь ласка, спробуйте ще раз.',
    }),

    accepting: t({
      en: 'Accepting…',
      ru: 'Принятие…',
      ja: '承認中…',
      fr: 'Acceptation…',
      ko: '수락 중…',
      zh: '接受中…',
      es: 'Aceptando…',
      de: 'Akzeptieren…',
      ar: 'جارٍ القبول…',
      it: 'Accettazione…',
      'en-GB': 'Accepting…',
      pt: 'Aceitando…',
      hi: 'स्वीकार किया जा रहा है…',
      tr: 'Kabul ediliyor…',
      pl: 'Akceptowanie…',
      id: 'Menerima…',
      vi: 'Đang chấp nhận…',
      uk: 'Прийняття…',
    }),

    acceptInvitation: t({
      en: 'Accept Invitation',
      ru: 'Принять приглашение',
      ja: '招待を承諾する',
      fr: "Accepter l'invitation",
      ko: '초대 수락',
      zh: '接受邀请',
      es: 'Aceptar invitación',
      de: 'Einladung annehmen',
      ar: 'قبول الدعوة',
      it: 'Accetta invito',
      'en-GB': 'Accept Invitation',
      pt: 'Aceitar convite',
      hi: 'निमंत्रण स्वीकार करें',
      tr: 'Davetiyeyi Kabul Et',
      pl: 'Akceptuj zaproszenie',
      id: 'Terima Undangan',
      vi: 'Chấp nhận lời mời',
      uk: 'Прийняти запрошення',
    }),
    country: t({
      en: 'Country',
      ru: 'Страна',
      ja: '国',
      fr: 'Pays',
      ko: '국가',
      zh: '国家',
      es: 'País',
      de: 'Land',
      ar: 'البلد',
      it: 'Paese',
      'en-GB': 'Country',
      pt: 'País',
      hi: 'देश',
      tr: 'Ülke',
      pl: 'Kraj',
      id: 'Negara',
      vi: 'Quốc gia',
      uk: 'Країна',
    }),

    selectYourCountry: t({
      en: 'Select your country…',
      ru: 'Выберите вашу страну…',
      ja: '国を選択してください…',
      fr: 'Sélectionnez votre pays…',
      ko: '국가를 선택하세요…',
      zh: '选择您的国家…',
      es: 'Seleccione su país…',
      de: 'Wählen Sie Ihr Land…',
      ar: 'اختر بلدك…',
      it: 'Seleziona il tuo paese…',
      'en-GB': 'Select your country…',
      pt: 'Selecione seu país…',
      hi: 'अपना देश चुनें…',
      tr: 'Ülkenizi seçin…',
      pl: 'Wybierz swój kraj…',
      id: 'Pilih negara Anda…',
      vi: 'Chọn quốc gia của bạn…',
      uk: 'Виберіть свою країну…',
    }),

    acceptInvitationLabel: t({
      en: 'Accept the invitation to join the affiliate program',
      ru: 'Принять приглашение присоединиться к партнерской программе',
      ja: 'アフィリエイトプログラムへの参加招待を承諾する',
      fr: "Accepter l'invitation à rejoindre le programme d'affiliation",
      ko: '제휴 프로그램 가입 초대 수락',
      zh: '接受加入联盟计划的邀请',
      es: 'Aceptar la invitación para unirse al programa de afiliados',
      de: 'Die Einladung zur Teilnahme am Affiliate-Programm annehmen',
      ar: 'قبول الدعوة للانضمام إلى برنامج الشركاء التابعين',
      it: "Accetta l'invito a unirsi al programma di affiliazione",
      'en-GB': 'Accept the invitation to join the affiliate program',
      pt: 'Aceitar o convite para participar do programa de afiliados',
      hi: 'सहबद्ध कार्यक्रम में शामिल होने का निमंत्रण स्वीकार करें',
      tr: 'Ortaklık programına katılma davetini kabul et',
      pl: 'Zaakceptuj zaproszenie do dołączenia do programu partnerskiego',
      id: 'Terima undangan untuk bergabung dengan program afiliasi',
      vi: 'Chấp nhận lời mời tham gia chương trình tiếp thị liên kết',
      uk: 'Прийняти запрошення приєднатися до партнерської програми',
    }),
  },
} satisfies Dictionary;

export default affiliateInvitationPageContent;
