import { type Dictionary, t } from 'intlayer';

const dashboardSidebarContent = {
  key: 'dashboard-sidebar',
  content: {
    collapseButton: {
      label: t({
        en: 'Collapse sidebar',
        fr: 'Réduire la barre latérale',
        es: 'Colapsar barra lateral',
        'en-GB': 'Collapse sidebar',
        de: 'Seitenleiste zuklappen',
        ja: 'サイドバーを折りたたむ',
        ko: '사이드바 접기',
        zh: '折叠侧边栏',
        it: 'Comprimi barra laterale',
        pt: 'Recolher barra lateral',
        hi: 'साइडबार संकुचित करें',
        ar: 'اطوي الشريط الجانبي',
        ru: 'Свернуть боковую панель',
        tr: 'Kenar çubuğunu daralt',
        pl: 'Zwiń pasek boczny',
        id: 'Sembunyikan sidebar',
        vi: 'Thu gọn thanh bên',
      }),
    },

    navigation: {
      editor: {
        label: t({
          en: 'Go to Intlayer visual editor',
          'en-GB': 'Go to Intlayer visual editor',
          fr: "Aller sur l'éditeur visuel Intlayer",
          es: 'Ir al editor visual de Intlayer',
          de: 'Gehen Sie zum Intlayer-Visual-Editor',
          ja: 'Intlayer ビジュアルエディタに行く',
          ko: 'Intlayer 비주얼 편집기로 이동',
          zh: '转到 Intlayer 可视化编辑器',
          it: 'Vai alla editor visuale di Intlayer',
          pt: 'Ir para o editor visual do Intlayer',
          hi: 'Intlayer व्हिडिओ एडिटर पर जाएं',
          ar: 'اذهب إلى محرر الفيديو لـ Intlayer',
          ru: 'Перейти к визуальному редактору Intlayer',
          tr: 'Intlayer görsel düzenleyicisine git',
          pl: 'Przejdź do wizualnego edytora Intlayer',
          id: 'Buka Intlayer visual editor',
          vi: 'Mở trình chỉnh sửa trực quan Intlayer',
        }),
        title: t({
          en: 'Editor',
          'en-GB': 'Editor',
          fr: 'Éditeur',
          es: 'Editor',
          de: 'Editor',
          ja: 'エディタ',
          ko: '편집기',
          zh: '编辑器',
          it: 'Editor',
          pt: 'Editor',
          hi: 'संपादक',
          ar: 'محرر',
          ru: 'Редактор',
          tr: 'Editör',
          pl: 'Edytor',
          id: 'Editor',
          vi: 'Trình chỉnh sửa',
        }),
      },
      content: {
        label: t({
          en: 'Go to content dashboard',
          'en-GB': 'Go to content dashboard',
          fr: 'Aller sur le tableau de bord de contenu',
          es: 'Ir al tablero de contenido',
          de: 'Gehen Sie zum Inhaltsdashboard',
          ja: 'コンテンツダッシュボードに行く',
          ko: '콘텐츠 대시보드로 이동',
          zh: '转到内容仪表板',
          it: 'Vai alla dashboard dei contenuti',
          pt: 'Ir para o painel de conteúdo',
          hi: 'सामग्री डैशबोर्ड पर जाएं',
          ar: 'اذهب إلى لوحة معلومات المحتوى',
          ru: 'Перейти к панели управления контентом',
          tr: "İçerik Dashboard'ına git",
          pl: 'Przejdź do panelu zawartości',
          id: 'Buka dashboard Content',
          vi: 'Đi tới bảng điều khiển nội dung',
        }),
        title: t({
          en: 'Content',
          'en-GB': 'Content',
          fr: 'Contenu',
          es: 'Contenido',
          de: 'Inhalt',
          ja: 'コンテンツ',
          ko: '콘텐츠',
          zh: '内容',
          it: 'Contenuto',
          pt: 'Conteúdo',
          hi: 'सामग्री',
          ar: 'محتوى',
          ru: 'Содержание',
          tr: 'İçerik',
          pl: 'Zawartość',
          id: 'Content',
          vi: 'Nội dung',
        }),
      },
      tags: {
        label: t({
          en: 'Go to tags dashboard',
          'en-GB': 'Go to tags dashboard',
          fr: 'Aller sur le tableau de bord des tags',
          es: 'Ir al tablero de etiquetas',
          de: 'Gehen Sie zum Tags-Dashboard',
          ja: 'タグダッシュボードに行く',
          ko: '태그 대시보드로 이동',
          zh: '转到标签仪表板',
          it: 'Vai alla dashboard dei tag',
          pt: 'Ir para o painel de tags',
          hi: 'टैग डैशबोर्ड पर जाएं',
          ar: 'اذهب إلى لوحة معلومات الوسوم',
          ru: 'Перейти к панели управления тегами',
          tr: "Etiket Dashboard'ına git",
          pl: 'Przejdź do panelu tagów',
          id: 'Buka dashboard Tags',
          vi: 'Đi tới bảng điều khiển thẻ',
        }),
        title: t({
          en: 'Tags',
          'en-GB': 'Tags',
          fr: 'Tags',
          es: 'Etiquetas',
          de: 'Tags',
          ja: 'タグ',
          ko: '태그',
          zh: '标签',
          it: 'Tag',
          pt: 'Tags',
          hi: 'टैग',
          ar: 'وسوم',
          ru: 'Теги',
          tr: 'Etiketler',
          pl: 'Tagi',
          id: 'Tags',
          vi: 'Thẻ',
        }),
      },
      projects: {
        label: t({
          en: 'Go to projects dashboard',
          'en-GB': 'Go to projects dashboard',
          fr: 'Aller sur le tableau de bord des projets',
          es: 'Ir al tablero de proyectos',
          de: 'Gehen Sie zum Projekt-Dashboard',
          ja: 'プロジェクトダッシュボードに行く',
          ko: '프로젝트 대시보드로 이동',
          zh: '转到项目仪表板',
          it: 'Vai alla dashboard dei progetti',
          pt: 'Ir para o painel de projetos',
          hi: 'परियोजना डैशबोर्ड पर जाएं',
          ar: 'اذهب إلى لوحة معلومات المشاريع',
          ru: 'Перейти к панели управления проектами',
          tr: "Proje Dashboard'ına git",
          pl: 'Przejdź do panelu projektów',
          id: 'Buka dashboard Projects',
          vi: 'Đi tới bảng điều khiển dự án',
        }),
        title: t({
          en: 'Projects',
          'en-GB': 'Projects',
          fr: 'Projets',
          es: 'Proyectos',
          de: 'Projekte',
          ja: 'プロジェクト',
          ko: '프로젝트',
          zh: '项目',
          it: 'Progetti',
          pt: 'Projetos',
          hi: 'परियोजनाएँ',
          ar: 'مشاريع',
          ru: 'Проекты',
          tr: 'Projeler',
          pl: 'Projekty',
          id: 'Projects',
          vi: 'Dự án',
        }),
      },
      organization: {
        label: t({
          en: 'Go to organization dashboard',
          'en-GB': 'Go to organization dashboard',
          fr: "Aller sur le tableau de bord de l'organisation",
          es: 'Ir al tablero de organización',
          de: 'Gehen Sie zum Organisationsdashboard',
          ja: '組織のダッシュボードに行く',
          ko: '조직 대시보드로 이동',
          zh: '转到组织仪表板',
          it: "Vai alla dashboard dell'organizzazione",
          pt: 'Ir para o painel de organização',
          hi: 'संगठन डैशबोर्ड पर जाएं',
          ar: 'اذهب إلى لوحة معلومات المؤسسة',
          ru: 'Перейти к панели управления организацией',
          tr: "Organizasyon Dashboard'ına git",
          pl: 'Przejdź do panelu organizacji',
          id: 'Buka dashboard Organization',
          vi: 'Đi tới bảng điều khiển tổ chức',
        }),
        title: t({
          en: 'Organization',
          'en-GB': 'Organization',
          fr: 'Organisation',
          es: 'Organización',
          de: 'Organisation',
          ja: '組織',
          ko: '조직',
          zh: '组织',
          it: 'Organizzazione',
          pt: 'Organização',
          hi: 'संगठन',
          ar: 'تنظيم',
          ru: 'Организация',
          tr: 'Organizasyon',
          pl: 'Organizacja',
          id: 'Organization',
          vi: 'Tổ chức',
        }),
      },
      profile: {
        label: t({
          en: 'Go to profile dashboard',
          'en-GB': 'Go to profile dashboard',
          fr: 'Aller sur le tableau de bord du profil',
          es: 'Ir al tablero de perfil',
          de: 'Gehen Sie zum Profil-Dashboard',
          ja: 'プロフィールダッシュボードに行く',
          ko: '프로필 대시보드로 이동',
          zh: '转到个人资料仪表板',
          it: 'Vai alla dashboard del profilo',
          pt: 'Ir para o painel de perfil',
          hi: 'प्रोफ़ाइल डैशबोर्ड पर जाएं',
          ar: 'اذهب إلى لوحة معلومات الملف الشخصي',
          ru: 'Перейти к панели управления профилем',
          tr: "Profil Dashboard'ına git",
          pl: 'Przejdź do panelu profilu',
          id: 'Buka dashboard Profile',
          vi: 'Đi tới bảng điều khiển hồ sơ',
        }),
        title: t({
          en: 'Profile',
          'en-GB': 'Profile',
          fr: 'Profil',
          es: 'Perfil',
          de: 'Profil',
          ja: 'プロフィール',
          ko: '프로필',
          zh: '个人资料',
          it: 'Profilo',
          pt: 'Perfil',
          hi: 'प्रोफ़ाइल',
          ar: 'الملف الشخصي',
          ru: 'Профиль',
          tr: 'Profil',
          pl: 'Profil',
          id: 'Profile',
          vi: 'Hồ sơ',
        }),
      },
      admin: {
        label: t({
          en: 'Go to admin dashboard',
          'en-GB': 'Go to admin dashboard',
          fr: 'Aller sur le tableau de bord admin',
          es: 'Ir al tablero de admin',
          de: 'Gehen Sie zum Admin-Dashboard',
          ja: '管理者ダッシュボードに行く',
          ko: '관리자 대시보드로 이동',
          zh: '转到管理员仪表板',
          it: 'Vai alla dashboard admin',
          pt: 'Ir para o painel de admin',
          hi: '管理者ダッシュボードに行く',
          ar: 'اذهب إلى لوحة معلومات المشرف',
          ru: 'Перейти к панели управления администратором',
          tr: "Admin Dashboard'ına git",
          pl: 'Przejdź do panelu administracyjnego',
          id: 'Buka dashboard Admin',
          vi: 'Đi tới bảng điều khiển quản trị',
        }),
        title: t({
          en: 'Admin',
          'en-GB': 'Admin',
          fr: 'Admin',
          es: 'Admin',
          de: 'Admin',
          ja: '管理者',
          ko: '관리자',
          zh: '管理员',
          it: 'Admin',
          pt: 'Admin',
          hi: '管理者',
          ar: 'مشرف',
          ru: 'Администратор',
          tr: 'Admin',
          pl: 'Administracja',
          id: 'Admin',
          vi: 'Quản trị',
        }),
      },
    },
  },
  title: 'Dashboard sidebar navigation',
  description:
    'Content declaration for the dashboard sidebar navigation, includes labels and titles for dashboard access and navigation sections.',
  tags: ['dashboard', 'sidebar', 'navigation'],
} satisfies Dictionary;

export default dashboardSidebarContent;
