import { type Dictionary, t } from 'intlayer';

const projectFocusContent = {
  key: 'project-focus',
  content: {
    projectNotFound: {
      title: t({
        en: 'Project Not Found',
        'en-GB': 'Project Not Found',
        fr: 'Projet non trouvé',
        es: 'Proyecto no encontrado',
        de: 'Projekt nicht gefunden',
        ja: 'プロジェクトが見つかりません',
        ko: '프로젝트를 찾을 수 없음',
        zh: '未找到项目',
        it: 'Progetto non trovato',
        pt: 'Projeto não encontrado',
        hi: 'परियोजना नहीं मिली',
        ar: 'لم يتم العثور على المشروع',
        uk: 'Проект не знайдено',
        ru: 'Проект не найден',
        tr: 'Proje Bulunamadı',
        pl: 'Nie znaleziono projektu',
        id: 'Proyek Tidak Ditemukan',
        vi: 'Không tìm thấy dự án',
      }),
      description: t({
        en: 'The project you are looking for does not exist or has been removed.',
        'en-GB':
          'The project you are looking for does not exist or has been removed.',
        fr: "Le projet que vous recherchez n'existe pas ou a été supprimé.",
        es: 'El proyecto que buscas no existe o ha sido eliminado.',
        de: 'Das gesuchte Projekt existiert nicht oder wurde entfernt.',
        ja: 'お探しのプロジェクトは存在しないか、削除されました。',
        ko: '찾으시는 프로젝트가 존재하지 않거나 삭제되었습니다.',
        zh: '您寻找的项目不存在或已被删除。',
        it: 'Il progetto che stai cercando non esiste o è stato rimosso.',
        pt: 'O projeto que você está procurando não existe ou foi removido.',
        hi: 'आप जिस परियोजना की तलाश कर रहे हैं वह मौजूद नहीं है या उसे हटा दिया गया है।',
        ar: 'المشروع الذي تبحث عنه غير موجود أو تمت إزالته.',
        uk: 'Проект, який ви шукаєте, не існує або був видалений.',
        ru: 'Проект, который вы ищете, не существует или был удален.',
        tr: 'Aradığınız proje mevcut değil veya kaldırılmış.',
        pl: 'Projekt, którego szukasz, nie istnieje lub został usunięty.',
        id: 'Proyek yang Anda cari tidak ada atau telah dihapus.',
        vi: 'Dự án bạn đang tìm kiếm không tồn tại hoặc đã bị xóa.',
      }),
      backToGallery: t({
        en: 'Back to Gallery',
        'en-GB': 'Back to Gallery',
        fr: 'Retour à la galerie',
        es: 'Volver a la galería',
        de: 'Zurück zur Galerie',
        ja: 'ギャラリーに戻る',
        ko: '갤러리로 돌아가기',
        zh: '回到图库',
        it: 'Torna alla galleria',
        pt: 'Voltar para a Galeria',
        hi: 'गैलरी पर वापस जाएं',
        ar: 'العودة إلى المعرض',
        uk: 'Назад до галереї',
        ru: 'Назад в галерею',
        tr: 'Galeriye Dön',
        pl: 'Powrót do galerii',
        id: 'Kembali ke Galeri',
        vi: 'Quay lại bộ sưu tập',
      }),
    },
    backToShowcase: t({
      en: 'Back to Showcase Gallery',
      'en-GB': 'Back to Showcase Gallery',
      fr: 'Retour à la galerie Showcase',
      es: 'Volver a la galería de Showcase',
      de: 'Zurück zur Showcase-Galerie',
      ja: 'ショーケースギャラリーに戻る',
      ko: '쇼케이스 갤러리로 돌아가기',
      zh: '回到展示图库',
      it: 'Torna alla galleria Showcase',
      pt: 'Voltar para a Galeria Showcase',
      hi: 'शोकेस गैलरी पर वापस जाएं',
      ar: 'العودة إلى معرض المواقع',
      uk: 'Назад до вітрини',
      ru: 'Назад в галерею',
      tr: 'Vitrin Galerisine Dön',
      pl: 'Powrót do galerii projektów',
      id: 'Kembali ke Galeri Showcase',
      vi: 'Quay lại Showcase',
    }),
    na: t({
      en: 'N/A',
      'en-GB': 'N/A',
      fr: 'N/A',
      es: 'N/A',
      de: 'N/V',
      ja: 'N/A',
      ko: '해당 없음',
      zh: '不适用',
      it: 'N/D',
      pt: 'N/A',
      hi: 'उपलब्ध नहीं',
      ar: 'غير متوفر',
      uk: 'Н/Д',
      ru: 'Н/Д',
      tr: 'YOK',
      pl: 'N/A',
      id: 'N/A',
      vi: 'N/A',
    }),
  },
} satisfies Dictionary;

export default projectFocusContent;
