import { type Dictionary, t } from 'intlayer';

const projectMoreProjectsContent = {
  key: 'project-more-projects',
  content: {
    moreProjects: t({
      en: 'More Projects',
      'en-GB': 'More Projects',
      fr: 'Plus de projets',
      es: 'Más proyectos',
      de: 'Weitere Projekte',
      ja: '他のプロジェクト',
      ko: '다른 프로젝트',
      zh: '更多项目',
      it: 'Altri progetti',
      pt: 'Mais projetos',
      hi: 'और परियोजनाएं',
      ar: 'مشاريع أخرى',
      uk: 'Більше проектів',
      ru: 'Другие проекты',
      tr: 'Daha Fazla Proje',
      pl: 'Więcej projektów',
      id: 'Proyek Lainnya',
      vi: 'Thêm dự án',
    }),
    moreProjectsDescription: t({
      en: 'Explore other projects that use Intlayer for their internationalization.',
      'en-GB':
        'Explore other projects that use Intlayer for their internationalisation.',
      fr: "Découvrez d'autres projets qui utilisent Intlayer pour leur internationalisation.",
      es: 'Explore otros proyectos que utilizan Intlayer para su internacionalización.',
      de: 'Entdecken Sie weitere Projekte, die Intlayer für ihre Internationalisierung nutzen.',
      ja: '国際化にIntlayerを使用した他のプロジェクトを探索する。',
      ko: '국제화를 위해 Intlayer를 사용하는 다른 프로젝트를 탐색하십시오.',
      zh: '探索其他使用 Intlayer 进行国际化的项目。',
      it: 'Esplora altri progetti che utilizzano Intlayer per la loro internazionalizzazione.',
      pt: 'Explore outros projetos que utilizam o Intlayer para sua internacionalização.',
      hi: 'उन अन्य परियोजनाओं का अन्वेषण करें जो अपने अंतर्राष्ट्रीयकरण के लिए Intlayer का उपयोग करती हैं।',
      ar: 'استكشف المشاريع الأخرى التي تستخدم Intlayer لتدويلها.',
      uk: 'Досліджуйте інші проекти, які використовують Intlayer для інтернаціоналізації.',
      ru: 'Ознакомьтесь с другими проектами, использующими Intlayer для интернационализации.',
      tr: 'Uluslararasılaştırma için Intlayer kullanan diğer projeleri keşfedin.',
      pl: 'Poznaj inne projekty, które wykorzystują Intlayer do swojej internacjonalizacji.',
      id: 'Jelajahi proyek lain yang menggunakan Intlayer untuk internasionalisasinya.',
      vi: 'Khám phá các dự án khác sử dụng Intlayer để quốc tế hóa.',
    }),
    noProjectsFound: t({
      en: 'No more projects found',
      'en-GB': 'No more projects found',
      fr: 'Plus aucun projet trouvé',
      es: 'No se encontraron más proyectos',
      de: 'Keine weiteren Projekte gefunden',
      ja: '他のプロジェクトが見つかりませんでした',
      ko: '다른 프로젝트를 찾을 수 없습니다',
      zh: '未找到更多项目',
      it: 'Nessun altro progetto trovato',
      pt: 'Nenhum outro projeto encontrado',
      hi: 'कोई और परियोजनाएं नहीं मिलीं',
      ar: 'لم يتم العثور على مشاريع أخرى',
      uk: 'Більше проектів не знайдено',
      ru: 'Больше проектов не найдено',
      tr: 'Daha fazla proje bulunamadı',
      pl: 'Nie znaleziono więcej projektów',
      id: 'Tidak ada proyek lain ditemukan',
      vi: 'Không tìm thấy thêm dự án nào',
    }),
  },
} satisfies Dictionary;

export default projectMoreProjectsContent;
