export enum MessageKey {
  INTLAYER_EDITOR_ENABLED = 'INTLAYER_EDITOR_ENABLED',
  INTLAYER_URL_CHANGE = 'INTLAYER_URL_CHANGE',
  INTLAYER_FOCUSED_CONTENT_CHANGED = 'INTLAYER_FOCUSED_CONTENT_CHANGED',
  INTLAYER_DICTIONARIES_RECORD_CHANGED = 'INTLAYER_DICTIONARIES_RECORD_CHANGED',
  INTLAYER_EDITED_CONTENT_CHANGED = 'INTLAYER_EDITED_CONTENT_CHANGED',
}
