import { t, type Dictionary } from 'intlayer';

const deleteProjectModalContent = {
  key: 'delete-project-modal',
  content: {
    title: t({
      en: 'Delete Project',
      fr: 'Supprimer le Project',
      es: 'Eliminar proyecto',
      'en-GB': 'Delete Project',
      de: 'Projekt löschen',
      ja: 'プロジェクトを削除',
      ko: '프로젝트 삭제',
      zh: '删除项目',
      it: 'Elimina progetto',
      pt: 'Excluir projeto',
      hi: 'प्रोजेक्ट हटाएं',
      ar: 'حذف المشروع',
      ru: 'Удалить проект',
    }),

    description: t({
      en: 'Are you sure you want to delete this Project?',
      fr: 'Êtes-vous sûr de vouloir supprimer ce Project ?',
      es: '¿Está seguro de que desea eliminar este proyecto?',
      'en-GB': 'Are you sure you want to delete this project?',
      de: 'Sind Sie sicher, dass Sie dieses Projekt löschen möchten?',
      ja: 'このプロジェクトを削除してもよろしいですか？',
      ko: '이 프로젝트를 삭제하시겠습니까?',
      zh: '您确定要删除此项目吗？',
      it: 'Sei sicuro di voler eliminare questo progetto?',
      pt: 'Tem certeza de que deseja excluir este projeto?',
      hi: 'क्या आप इस प्रोजेक्ट को हटाना चाहते हैं?',
      ar: 'هل أنت متأكد من أنك تريد حذف هذا المشروع؟',
      ru: 'Вы уверены, что хотите удалить этот проект?',
    }),

    confirmButton: {
      text: t({
        en: 'Delete',
        fr: 'Supprimer',
        es: 'Eliminar',
        'en-GB': 'Delete',
        de: 'Löschen',
        ja: '削除',
        ko: '삭제',
        zh: '删除',
        it: 'Elimina',
        pt: 'Excluir',
        hi: 'हटाएं',
        ar: 'حذف',
        ru: 'Удалить',
      }),
      label: t({
        en: 'Click to delete Project',
        fr: 'Cliquez pour supprimer le Project',
        es: 'Haga clic para eliminar el proyecto',
        'en-GB': 'Click to delete Project',
        de: 'Klicken Sie, um das Projekt zu löschen',
        ja: 'プロジェクトを削除するにはクリックしてください',
        ko: '프로젝트를 삭제하려면 클릭하세요',
        zh: '点击删除项目',
        it: 'Clicca per eliminare il progetto',
        pt: 'Clique para excluir o projeto',
        hi: 'प्रोजेक्ट को हटाने के लिए क्लिक करें',
        ar: 'انقر لحذف المشروع',
        ru: 'Нажмите, чтобы удалить проект',
      }),
    },

    cancelButton: {
      text: t({
        en: 'Cancel',
        fr: 'Annuler',
        es: 'Cancelar',
        'en-GB': 'Cancel',
        de: 'Abbrechen',
        ja: 'キャンセル',
        ko: '취소',
        zh: '取消',
        it: 'Annulla',
        pt: 'Cancelar',
        hi: 'रद्द करें',
        ar: 'إلغاء',
        ru: 'Отменить',
      }),
      label: t({
        en: 'Click to cancel',
        fr: 'Cliquez pour annuler',
        es: 'Haga clic para cancelar',
        'en-GB': 'Click to cancel',
        de: 'Klicken Sie, um abzubrechen',
        ja: 'キャンセルをクリックしてください',
        ko: '취소를 클릭하세요',
        zh: '点击取消',
        it: 'Clicca per annullare',
        pt: 'Clique para cancelar',
        hi: 'रद्द करने के लिए क्लिक करें',
        ar: 'انقر لإلغاء',
        ru: 'Нажмите, чтобы отменить',
      }),
    },
  },
} satisfies Dictionary;

export default deleteProjectModalContent;
