import { type Dictionary, t } from 'intlayer';

const blogCommentSectionContent = {
  key: 'blog-comment-section',
  fill: true,
  importMode: 'dynamic',
  content: {
    failedToSubmitComment: t({
      en: 'Failed to submit comment',
      'en-GB': 'Failed to submit comment',
      fr: 'Échec de la soumission du commentaire',
      es: 'Error al enviar el comentario',
      de: 'Kommentar konnte nicht gesendet werden',
      ja: 'コメントの送信に失敗しました',
      ko: '댓글을 제출하지 못했습니다',
      zh: '提交评论失败',
      it: 'Impossibile inviare il commento',
      pt: 'Falha ao enviar o comentário',
      hi: 'टिप्पणी सबमिट करने में विफल',
      ar: 'فشل في إرسال التعليق',
      ru: 'Не удалось отправить комментарий',
      tr: 'Yorum gönderilemedi',
      pl: 'Nie udało się przesłać komentarza',
      id: 'Gagal mengirim komentar',
      vi: 'Gửi bình luận thất bại',
      uk: 'Не вдалося надіслати коментар',
    }),

    failedToSubmitYourComment: t({
      en: 'Failed to submit your comment. Please try again.',
      'en-GB': 'Failed to submit your comment. Please try again.',
      fr: 'Échec de la soumission de votre commentaire. Veuillez réessayer.',
      es: 'Error al enviar su comentario. Por favor, inténtelo de nuevo.',
      de: 'Ihr Kommentar konnte nicht gesendet werden. Bitte versuchen Sie es erneut.',
      ja: 'コメントの送信に失敗しました。もう一度お試しください。',
      ko: '댓글을 제출하지 못했습니다. 다시 시도해 주세요.',
      zh: '提交您的评论失败。请重试。',
      it: 'Impossibile inviare il tuo commento. Per favore riprova.',
      pt: 'Falha ao enviar o seu comentário. Por favor, tente novamente.',
      hi: 'आपकी टिप्पणी सबमिट करने में विफल। कृपया पुनः प्रयास करें।',
      ar: 'فشل في إرسال تعليقك. يرجى المحاولة مرة أخرى.',
      ru: 'Не удалось отправить ваш комментарий. Пожалуйста, попробуйте еще раз.',
      tr: 'Yorumunuz gönderilemedi. Lütfen tekrar deneyin.',
      pl: 'Nie udało się przesłać Twojego komentarza. Spróbuj ponownie.',
      id: 'Gagal mengirim komentar Anda. Silakan coba lagi.',
      vi: 'Gửi bình luận của bạn thất bại. Vui lòng thử lại.',
      uk: 'Не вдалося надіслати ваш коментар. Будь ласка, спробуйте ще раз.',
    }),

    comments: t({
      en: 'Comments',
      'en-GB': 'Comments',
      fr: 'Commentaires',
      es: 'Comentarios',
      de: 'Kommentare',
      ja: 'コメント',
      ko: '댓글',
      zh: '评论',
      it: 'Commenti',
      pt: 'Comentários',
      hi: 'टिप्पणियाँ',
      ar: 'التعليقات',
      ru: 'Комментарии',
      tr: 'Yorumlar',
      pl: 'Komentarze',
      id: 'Komentar',
      vi: 'Bình luận',
      uk: 'Коментарі',
    }),

    noCommentsYetBeThe: t({
      en: 'No comments yet. Be the first to share your thoughts.',
      'en-GB': 'No comments yet. Be the first to share your thoughts.',
      fr: 'Aucun commentaire pour le moment. Soyez le premier à partager vos pensées.',
      es: 'Aún no hay comentarios. Sé el primero en compartir tus pensamientos.',
      de: 'Noch keine Kommentare. Seien Sie der Erste, der seine Gedanken teilt.',
      ja: 'まだコメントはありません。最初のコメントを共有しましょう。',
      ko: '아직 댓글이 없습니다. 첫 번째로 의견을 나눠보세요.',
      zh: '暂无评论。成为第一个分享您想法的人吧。',
      it: 'Ancora nessun commento. Sii il primo a condividere i tuoi pensieri.',
      pt: 'Ainda sem comentários. Seja o primeiro a compartilhar seus pensamentos.',
      hi: 'अभी तक कोई टिप्पणी नहीं। अपने विचार साझा करने वाले पहले व्यक्ति बनें।',
      ar: 'لا توجد تعليقات بعد. كن أول من يشارك أفكاره.',
      ru: 'Пока нет комментариев. Будьте первым, кто поделится своими мыслями.',
      tr: 'Henüz yorum yok. Düşüncelerinizi paylaşan ilk kişi olun.',
      pl: 'Nie ma jeszcze komentarzy. Bądź pierwszą osobą, która podzieli się swoimi przemyśleniami.',
      id: 'Belum ada komentar. Jadilah yang pertama membagikan pemikiran Anda.',
      vi: 'Chưa có bình luận nào. Hãy là người đầu tiên chia sẻ suy nghĩ của bạn.',
      uk: 'Поки що немає коментарів. Будьте першим, хто поділиться своїми думками.',
    }),

    yourCommentHasBeenSubmitted: t({
      en: 'Your comment has been submitted and is awaiting moderation.',
      'en-GB': 'Your comment has been submitted and is awaiting moderation.',
      fr: 'Votre commentaire a été soumis et est en attente de modération.',
      es: 'Su comentario ha sido enviado y está en espera de moderación.',
      de: 'Ihr Kommentar wurde gesendet und wartet auf die Moderation.',
      ja: 'コメントが送信され、現在承認待ちです。',
      ko: '댓글이 제출되었으며 검토 대기 중입니다.',
      zh: '您的评论已提交并正在等待审核。',
      it: 'Il tuo commento è stato inviato ed è in attesa di moderazione.',
      pt: 'O seu comentário foi enviado e está a aguardar moderação.',
      hi: 'आपकी टिप्पणी सबमिट कर दी गई है और मॉडरेशन की प्रतीक्षा कर रही है।',
      ar: 'تم إرسال تعليقك وهو في انتظار المراجعة.',
      ru: 'Ваш комментарий отправлен и ожидает модерации.',
      tr: 'Yorumunuz gönderildi ve moderasyon bekliyor.',
      pl: 'Twój komentarz został przesłany i oczekuje na moderację.',
      id: 'Komentar Anda telah dikirim dan sedang menunggu moderasi.',
      vi: 'Bình luận của bạn đã được gửi và đang chờ kiểm duyệt.',
      uk: 'Ваш коментар надіслано і він очікує на модерацію.',
    }),

    addAComment: t({
      en: 'Add a comment →',
      'en-GB': 'Add a comment →',
      fr: 'Ajouter un commentaire →',
      es: 'Añadir un comentario →',
      de: 'Einen Kommentar hinzufügen →',
      ja: 'コメントを追加 →',
      ko: '댓글 추가 →',
      zh: '添加评论 →',
      it: 'Aggiungi un commento →',
      pt: 'Adicionar um comentário →',
      hi: 'एक टिप्पणी जोड़ें →',
      ar: 'أضف تعليقًا →',
      ru: 'Добавить комментарий →',
      tr: 'Yorum ekle →',
      pl: 'Dodaj komentarz →',
      id: 'Tambahkan komentar →',
      vi: 'Thêm bình luận →',
      uk: 'Додати коментар →',
    }),

    name: t({
      en: 'Name',
      'en-GB': 'Name',
      fr: 'Nom',
      es: 'Nombre',
      de: 'Name',
      ja: '名前',
      ko: '이름',
      zh: '姓名',
      it: 'Nome',
      pt: 'Nome',
      hi: 'नाम',
      ar: 'الاسم',
      ru: 'Имя',
      tr: 'İsim',
      pl: 'Imię',
      id: 'Nama',
      vi: 'Tên',
      uk: 'Імʼя',
    }),

    yourName: t({
      en: 'Your name',
      'en-GB': 'Your name',
      fr: 'Votre nom',
      es: 'Tu nombre',
      de: 'Ihr Name',
      ja: 'お名前',
      ko: '당신의 이름',
      zh: '您的姓名',
      it: 'Il tuo nome',
      pt: 'Seu nome',
      hi: 'आपका नाम',
      ar: 'اسمك',
      ru: 'Ваше имя',
      tr: 'Adınız',
      pl: 'Twoje imię',
      id: 'Nama Anda',
      vi: 'Tên của bạn',
      uk: 'Ваше імʼя',
    }),

    email: t({
      en: 'Email',
      'en-GB': 'Email',
      fr: 'Email',
      es: 'Correo electrónico',
      de: 'E-Mail',
      ja: 'メール',
      ko: '이메일',
      zh: '电子邮件',
      it: 'Email',
      pt: 'Email',
      hi: 'ईमेल',
      ar: 'البريد الإلكتروني',
      ru: 'Электронная почта',
      tr: 'E-posta',
      pl: 'E-mail',
      id: 'Email',
      vi: 'Email',
      uk: 'Електронна пошта',
    }),

    comment: t({
      en: 'Comment',
      'en-GB': 'Comment',
      fr: 'Commentaire',
      es: 'Comentario',
      de: 'Kommentar',
      ja: 'コメント',
      ko: '댓글',
      zh: '评论',
      it: 'Commento',
      pt: 'Comentário',
      hi: 'टिप्पणी',
      ar: 'تعليق',
      ru: 'Комментарий',
      tr: 'Yorum',
      pl: 'Komentarz',
      id: 'Komentar',
      vi: 'Bình luận',
      uk: 'Коментар',
    }),

    shareYourThoughts: t({
      en: 'Share your thoughts…',
      'en-GB': 'Share your thoughts…',
      fr: 'Partagez vos pensées…',
      es: 'Comparte tus pensamientos…',
      de: 'Teile deine Gedanken…',
      ja: 'あなたの考えを共有してください…',
      ko: '당신의 생각을 공유해 주세요…',
      zh: '分享您的想法…',
      it: 'Condividi i tuoi pensieri…',
      pt: 'Compartilhe seus pensamentos…',
      hi: 'अपने विचार साझा करें…',
      ar: 'شاركنا أفكارك…',
      ru: 'Поделитесь своими мыслями…',
      tr: 'Düşüncelerinizi paylaşın…',
      pl: 'Podziel się swoimi myślami…',
      id: 'Bagikan pemikiran Anda…',
      vi: 'Chia sẻ suy nghĩ của bạn…',
      uk: 'Поділіться своїми думками…',
    }),

    submitting: t({
      en: 'Submitting…',
      'en-GB': 'Submitting…',
      fr: 'Soumission…',
      es: 'Enviando…',
      de: 'Wird gesendet…',
      ja: '送信中…',
      ko: '제출 중…',
      zh: '提交中…',
      it: 'Invio in corso…',
      pt: 'A enviar…',
      hi: 'सबमिट कर रहा है…',
      ar: 'جاري الإرسال…',
      ru: 'Отправка…',
      tr: 'Gönderiliyor…',
      pl: 'Przesyłanie…',
      id: 'Mengirim…',
      vi: 'Đang gửi…',
      uk: 'Надсилання…',
    }),

    submitComment: t({
      en: 'Submit comment',
      'en-GB': 'Submit comment',
      fr: 'Soumettre le commentaire',
      es: 'Enviar comentario',
      de: 'Kommentar senden',
      ja: 'コメントを送信',
      ko: '댓글 제출',
      zh: '提交评论',
      it: 'Invia commento',
      pt: 'Enviar comentário',
      hi: 'टिप्पणी सबमिट करें',
      ar: 'إرسال التعليق',
      ru: 'Отправить комментарий',
      tr: 'Yorum gönder',
      pl: 'Prześlij komentarz',
      id: 'Kirim komentar',
      vi: 'Gửi bình luận',
      uk: 'Надіслати коментар',
    }),

    cancel: t({
      en: 'Cancel',
      'en-GB': 'Cancel',
      fr: 'Annuler',
      es: 'Cancelar',
      de: 'Abbrechen',
      ja: 'キャンセル',
      ko: '취소',
      zh: '取消',
      it: 'Annulla',
      pt: 'Cancelar',
      hi: 'रद्द करें',
      ar: 'إلغاء',
      ru: 'Отмена',
      tr: 'İptal',
      pl: 'Anuluj',
      id: 'Batal',
      vi: 'Hủy',
      uk: 'Скасувати',
    }),

    commentsAreModeratedAndWill: t({
      en: 'Comments are moderated and will appear after approval.',
      'en-GB': 'Comments are moderated and will appear after approval.',
      fr: 'Les commentaires sont modérés et apparaîtront après approbation.',
      es: 'Los comentarios están moderados y aparecerán después de su aprobación.',
      de: 'Kommentare werden moderiert und nach Genehmigung angezeigt.',
      ja: 'コメントはモデレーションされ、承認後に表示されます。',
      ko: '댓글은 검토 후 승인되면 표시됩니다.',
      zh: '评论将受到审核，并在批准后显示。',
      it: "I commenti sono moderati e appariranno dopo l'approvazione.",
      pt: 'Os comentários são moderados e aparecerão após aprovação.',
      hi: 'टिप्पणियों को मॉडरेट किया जाता है और अनुमोदन के बाद दिखाई देंगी।',
      ar: 'التعليقات تخضع للمراجعة وستظهر بعد الموافقة عليها.',
      ru: 'Комментарии модерируются и появятся после одобрения.',
      tr: 'Yorumlar denetlenmektedir ve onaylandıktan sonra görünecektir.',
      pl: 'Komentarze są moderowane i pojawią się po zatwierdzeniu.',
      id: 'Komentar dimoderasi dan akan muncul setelah disetujui.',
      vi: 'Bình luận được kiểm duyệt và sẽ xuất hiện sau khi được phê duyệt.',
      uk: 'Коментарі модеруються і зʼявляться після схвалення.',
    }),
  },
} satisfies Dictionary;

export default blogCommentSectionContent;
