import { type Dictionary, t } from 'intlayer';

const ssoSettingsContent = {
  key: 'sso-settings',
  content: {
    title: t({
      en: 'SSO Configuration',
      'en-GB': 'SSO Configuration',
      fr: 'Configuration SSO',
      es: 'Configuración SSO',
      de: 'SSO-Konfiguration',
      ja: 'SSO設定',
      ko: 'SSO 구성',
      zh: 'SSO 配置',
      it: 'Configurazione SSO',
      pt: 'Configuração SSO',
      tr: 'SSO Yapılandırması',
      ru: 'Настройка SSO',
      ar: 'تكوين SSO',
      hi: 'SSO कॉन्फ़िगरेशन',
      pl: 'Konfiguracja SSO',
      id: 'Konfigurasi SSO',
      vi: 'Cấu hình SSO',
      uk: 'Налаштування SSO',
    }),
    description: t({
      en: 'Configure Single Sign-On for your organization to allow members to sign in with their corporate identity provider.',
      'en-GB':
        'Configure Single Sign-On for your organisation to allow members to sign in with their corporate identity provider.',
      fr: "Configurez l'authentification unique pour votre organisation afin de permettre aux membres de se connecter avec leur fournisseur d'identité d'entreprise.",
      es: 'Configure el inicio de sesión único para su organización para permitir que los miembros inicien sesión con su proveedor de identidad corporativo.',
      de: 'Konfigurieren Sie Single Sign-On für Ihre Organisation, damit Mitglieder sich mit ihrem Unternehmensidentitätsanbieter anmelden können.',
      ja: '組織のシングルサインオンを設定して、メンバーが企業のIDプロバイダーでサインインできるようにします。',
      ko: '조직의 Single Sign-On을 구성하여 구성원이 기업 ID 공급자로 로그인할 수 있도록 합니다.',
      zh: '为您的组织配置单点登录，以便成员可以使用其企业身份提供商登录。',
      it: 'Configura il Single Sign-On per la tua organizzazione per consentire ai membri di accedere con il loro provider di identità aziendale.',
      pt: 'Configure o Single Sign-On para sua organização para permitir que os membros façam login com seu provedor de identidade corporativo.',
      tr: 'Kurumsal kimlik sağlayıcıları ile oturum açmayı sağlamak için organizasyonunuzda Tek Oturum Açma (SSO) yapılandırmasını tamamlayın.',
      ru: 'Настройте Single Sign-On для вашей организации, чтобы разрешить членам входить с помощью корпоративного провайдера идентификации.',
      ar: 'قم بتكوين تسجيل الدخول الموحد لمنظمتك للسماح للأعضاء بتسجيل الدخول باستخدام موفر الهوية المؤسسية الخاص بهم.',
      hi: 'अपने संगठन के लिए सिंगल साइन-ऑन कॉन्फ़िगर करें ताकि सदस्य अपने कॉर्पोरेट पहचान प्रदाता के साथ साइन इन कर सकें।',
      pl: 'Skonfiguruj Single Sign-On dla swojej organizacji, aby umożliwić członkom logowanie się za pomocą ich korporacyjnego dostawcy tożsamości.',
      id: 'Konfigurasikan Single Sign-On untuk organisasi Anda agar anggota dapat masuk dengan penyedia identitas perusahaan mereka.',
      vi: 'Cấu hình Single Sign-On cho tổ chức của bạn để cho phép thành viên đăng nhập bằng nhà cung cấp danh tính doanh nghiệp của họ.',
      uk: 'Налаштуйте єдиний вхід (SSO) для вашої організації, щоб учасники могли входити за допомогою корпоративного провайдера автентифікації.',
    }),
    enabledLabel: t({
      en: 'Enable SSO',
      'en-GB': 'Enable SSO',
      fr: 'Activer SSO',
      es: 'Habilitar SSO',
      de: 'SSO aktivieren',
      ja: 'SSOを有効にする',
      ko: 'SSO 활성화',
      zh: '启用 SSO',
      it: 'Abilita SSO',
      pt: 'Habilitar SSO',
      tr: "SSO'yu Etkinleştir",
      ru: 'Включить SSO',
      ar: 'تفعيل SSO',
      hi: 'SSO सक्षम करें',
      pl: 'Włącz SSO',
      id: 'Aktifkan SSO',
      vi: 'Bật SSO',
      uk: 'Увімкнути SSO',
    }),
    providerTypeLabel: t({
      en: 'Provider Type',
      'en-GB': 'Provider Type',
      fr: 'Type de fournisseur',
      es: 'Tipo de proveedor',
      de: 'Anbietertyp',
      ja: 'プロバイダータイプ',
      ko: '공급자 유형',
      zh: '提供商类型',
      it: 'Tipo di provider',
      pt: 'Tipo de provedor',
      tr: 'Sağlayıcı Türü',
      ru: 'Тип провайдера',
      ar: 'نوع الموفر',
      hi: 'प्रदाता प्रकार',
      pl: 'Typ dostawcy',
      id: 'Jenis Penyedia',
      vi: 'Loại nhà cung cấp',
      uk: 'Тип провайдера',
    }),
    providerTypeOptions: {
      saml: 'SAML 2.0',
      oidc: 'OpenID Connect (OIDC)',
    },
    domainsLabel: t({
      en: 'Email Domains',
      'en-GB': 'Email Domains',
      fr: 'Domaines email',
      es: 'Dominios de correo',
      de: 'E-Mail-Domains',
      ja: 'メールドメイン',
      ko: '이메일 도메인',
      zh: '电子邮件域',
      it: 'Domini email',
      pt: 'Domínios de email',
      tr: 'E-posta Alan Adları',
      ru: 'Домены электронной почты',
      ar: 'نطاقات البريد الإلكتروني',
      hi: 'ईमेल डोमेन',
      pl: 'Domeny e-mail',
      id: 'Domain Email',
      vi: 'Miền email',
      uk: 'Домени електронної пошти',
    }),
    domainsPlaceholder: t({
      en: 'e.g., company.com (comma separated)',
      'en-GB': 'e.g., company.com (comma separated)',
      fr: 'ex: entreprise.com (séparés par des virgules)',
      es: 'ej: empresa.com (separados por comas)',
      de: 'z.B. firma.de (kommagetrennt)',
      ja: '例: company.com（カンマ区切り）',
      ko: '예: company.com (쉼표로 구분)',
      zh: '例如：company.com（逗号分隔）',
      it: 'es: azienda.com (separati da virgola)',
      pt: 'ex: empresa.com (separados por vírgula)',
      tr: 'örn: company.com (virgülle ayrılmış)',
      ru: 'например: company.com (разделено запятыми)',
      ar: 'مثال: company.com (مفصولة بفواصل)',
      hi: 'उदाहरण: company.com (अल्पविराम से अलग)',
      pl: 'np. company.com (oddzielone przecinkami)',
      id: 'misalnya: company.com (dipisahkan dengan koma)',
      vi: 'ví dụ: company.com (phân cách bằng dấu phẩy)',
      uk: 'наприклад company.com (через кому)',
    }),
    domainsDescription: t({
      en: 'Users with email addresses from these domains will be required to use SSO.',
      'en-GB':
        'Users with email addresses from these domains will be required to use SSO.',
      fr: 'Les utilisateurs avec des adresses email de ces domaines devront utiliser SSO.',
      es: 'Los usuarios con direcciones de correo de estos dominios deberán usar SSO.',
      de: 'Benutzer mit E-Mail-Adressen aus diesen Domains müssen SSO verwenden.',
      ja: 'これらのドメインのメールアドレスを持つユーザーはSSOを使用する必要があります。',
      ko: '이 도메인의 이메일 주소를 가진 사용자는 SSO를 사용해야 합니다.',
      zh: '来自这些域的电子邮件地址的用户将被要求使用SSO。',
      it: 'Gli utenti con indirizzi email da questi domini dovranno utilizzare SSO.',
      pt: 'Usuários com endereços de email desses domínios serão obrigados a usar SSO.',
      tr: 'Bu alan adlarından e-posta adreslerine sahip kullanıcıların SSO kullanması gerekecektir.',
      ru: 'Пользователи с адресами электронной почты из этих доменов должны будут использовать SSO.',
      ar: 'سيُطلب من المستخدمين الذين لديهم عناوين بريد إلكتروني من هذه النطاقات استخدام SSO.',
      hi: 'इन डोमेन से ईमेल पते वाले उपयोगकर्ताओं को SSO का उपयोग करना होगा।',
      pl: 'Użytkownicy z adresami e-mail z tych domen będą musieli używać SSO.',
      id: 'Pengguna dengan alamat email dari domain ini akan diwajibkan menggunakan SSO.',
      vi: 'Người dùng có địa chỉ email từ các miền này sẽ được yêu cầu sử dụng SSO.',
      uk: 'Користувачі з адресами електронної пошти в цих доменах повинні будуть використовувати SSO.',
    }),
    samlConfig: {
      title: t({
        en: 'SAML Configuration',
        'en-GB': 'SAML Configuration',
        fr: 'Configuration SAML',
        es: 'Configuración SAML',
        de: 'SAML-Konfiguration',
        ja: 'SAML設定',
        ko: 'SAML 구성',
        zh: 'SAML 配置',
        it: 'Configurazione SAML',
        pt: 'Configuração SAML',
        tr: 'SAML Yapılandırması',
        ru: 'Настройка SAML',
        ar: 'تكوين SAML',
        hi: 'SAML कॉन्फ़िगरेशन',
        pl: 'Konfiguracja SAML',
        id: 'Konfigurasi SAML',
        vi: 'Cấu hình SAML',
        uk: 'Налаштування SAML',
      }),
      idpEntityIdLabel: t({
        en: 'IdP Entity ID',
        'en-GB': 'IdP Entity ID',
        fr: "ID d'entité IdP",
        es: 'ID de entidad IdP',
        de: 'IdP Entity ID',
        ja: 'IdP エンティティ ID',
        ko: 'IdP 엔티티 ID',
        zh: 'IdP 实体 ID',
        it: 'ID entità IdP',
        pt: 'ID da entidade IdP',
        tr: 'IdP Varlık Kimliği',
        ru: 'ID сущности IdP',
        ar: 'معرف كيان IdP',
        hi: 'IdP इकाई ID',
        pl: 'Identyfikator jednostki IdP',
        id: 'ID Entitas IdP',
        vi: 'ID thực thể IdP',
        uk: 'Ідентифікатор сутності IdP',
      }),
      idpEntityIdPlaceholder: 'https://idp.example.com/entity-id',
      idpSSOUrlLabel: t({
        en: 'IdP SSO URL',
        'en-GB': 'IdP SSO URL',
        fr: 'URL SSO IdP',
        es: 'URL SSO IdP',
        de: 'IdP SSO URL',
        ja: 'IdP SSO URL',
        ko: 'IdP SSO URL',
        zh: 'IdP SSO URL',
        it: 'URL SSO IdP',
        pt: 'URL SSO IdP',
        tr: 'IdP SSO URL',
        ru: 'URL SSO IdP',
        ar: 'رابط SSO IdP',
        hi: 'IdP SSO URL',
        pl: 'URL SSO IdP',
        id: 'URL SSO IdP',
        vi: 'URL SSO IdP',
        uk: 'URL SSO IdP',
      }),
      idpSSOUrlPlaceholder: 'https://idp.example.com/sso',
      idpCertificateLabel: t({
        en: 'IdP Certificate (PEM)',
        'en-GB': 'IdP Certificate (PEM)',
        fr: 'Certificat IdP (PEM)',
        es: 'Certificado IdP (PEM)',
        de: 'IdP-Zertifikat (PEM)',
        ja: 'IdP 証明書 (PEM)',
        ko: 'IdP 인증서 (PEM)',
        zh: 'IdP 证书 (PEM)',
        it: 'Certificato IdP (PEM)',
        pt: 'Certificado IdP (PEM)',
        tr: 'IdP Sertifikası (PEM)',
        ru: 'Сертификат IdP (PEM)',
        ar: 'شهادة IdP (PEM)',
        hi: 'IdP प्रमाणपत्र (PEM)',
        pl: 'Certyfikat IdP (PEM)',
        id: 'Sertifikat IdP (PEM)',
        vi: 'Chứng chỉ IdP (PEM)',
        uk: 'Сертифікат IdP (PEM)',
      }),
      idpCertificatePlaceholder: t({
        en: 'Paste your IdP certificate here...',
        'en-GB': 'Paste your IdP certificate here...',
        fr: 'Collez votre certificat IdP ici...',
        es: 'Pegue su certificado IdP aquí...',
        de: 'Fügen Sie Ihr IdP-Zertifikat hier ein...',
        ja: 'IdP証明書をここに貼り付けてください...',
        ko: 'IdP 인증서를 여기에 붙여넣으세요...',
        zh: '在此处粘贴您的IdP证书...',
        it: 'Incolla il tuo certificato IdP qui...',
        pt: 'Cole seu certificado IdP aqui...',
        tr: 'IdP sertifikanızı buraya yapıştırın...',
        ru: 'Вставьте сертификат IdP сюда...',
        ar: 'الصق شهادة IdP الخاصة بك هنا...',
        hi: 'अपना IdP प्रमाणपत्र यहाँ चिपकाएँ...',
        pl: 'Wklej tutaj swój certyfikat IdP...',
        id: 'Tempelkan sertifikat IdP Anda di sini...',
        vi: 'Dán chứng chỉ IdP của bạn vào đây...',
        uk: 'Вставте сертифікат IdP тут...',
      }),
    },
    oidcConfig: {
      title: t({
        en: 'OIDC Configuration',
        'en-GB': 'OIDC Configuration',
        fr: 'Configuration OIDC',
        es: 'Configuración OIDC',
        de: 'OIDC-Konfiguration',
        ja: 'OIDC設定',
        ko: 'OIDC 구성',
        zh: 'OIDC 配置',
        it: 'Configurazione OIDC',
        pt: 'Configuração OIDC',
        tr: 'OIDC Yapılandırması',
        ru: 'Настройка OIDC',
        ar: 'تكوين OIDC',
        hi: 'OIDC कॉन्फ़िगरेशन',
        pl: 'Konfiguracja OIDC',
        id: 'Konfigurasi OIDC',
        vi: 'Cấu hình OIDC',
        uk: 'Налаштування OIDC',
      }),
      issuerLabel: t({
        en: 'Issuer URL',
        'en-GB': 'Issuer URL',
        fr: "URL de l'émetteur",
        es: 'URL del emisor',
        de: 'Aussteller-URL',
        ja: '発行者 URL',
        ko: '발급자 URL',
        zh: '发行者 URL',
        it: 'URL emittente',
        pt: 'URL do emissor',
        tr: 'Yayıncı URL',
        ru: 'URL издателя',
        ar: 'رابط المُصدر',
        hi: 'जारीकर्ता URL',
        pl: 'URL wystawcy',
        id: 'URL Penerbit',
        vi: 'URL nhà phát hành',
        uk: 'URL видавця',
      }),
      issuerPlaceholder: 'https://idp.example.com/sso',
      clientIdLabel: t({
        en: 'Client ID',
        'en-GB': 'Client ID',
        fr: 'ID client',
        es: 'ID de cliente',
        de: 'Client-ID',
        ja: 'クライアント ID',
        ko: '클라이언트 ID',
        zh: '客户端 ID',
        it: 'ID client',
        pt: 'ID do cliente',
        tr: 'İstemci Kimliği',
        ru: 'ID клиента',
        ar: 'معرف العميل',
        hi: 'क्लाइंट ID',
        pl: 'Identyfikator klienta',
        id: 'ID Klien',
        vi: 'ID khách hàng',
        uk: 'ID клієнта',
      }),
      clientIdPlaceholder: t({
        en: 'Your OAuth2 client ID',
        'en-GB': 'Your OAuth2 client ID',
        fr: 'Votre ID client OAuth2',
        es: 'Su ID de cliente OAuth2',
        de: 'Ihre OAuth2-Client-ID',
        ja: 'OAuth2クライアントID',
        ko: 'OAuth2 클라이언트 ID',
        zh: '您的 OAuth2 客户端 ID',
        it: 'Il tuo ID client OAuth2',
        pt: 'Seu ID do cliente OAuth2',
        tr: 'OAuth2 istemci kimliğiniz',
        ru: 'Ваш ID клиента OAuth2',
        ar: 'معرف عميل OAuth2 الخاص بك',
        hi: 'आपका OAuth2 क्लाइंट ID',
        pl: 'Twój identyfikator klienta OAuth2',
        id: 'ID Klien OAuth2 Anda',
        vi: 'ID khách hàng OAuth2 của bạn',
        uk: 'Ваш ID клієнта OAuth2',
      }),
      clientSecretLabel: t({
        en: 'Client Secret',
        'en-GB': 'Client Secret',
        fr: 'Secret client',
        es: 'Secreto de cliente',
        de: 'Client-Secret',
        ja: 'クライアントシークレット',
        ko: '클라이언트 시크릿',
        zh: '客户端密钥',
        it: 'Segreto client',
        pt: 'Segredo do cliente',
        tr: 'İstemci Gizliliği',
        ru: 'Секрет клиента',
        ar: 'سر العميل',
        hi: 'क्लाइंट सीक्रेट',
        pl: 'Klucz tajny klienta',
        id: 'Rahasia Klien',
        vi: 'Bí mật khách hàng',
        uk: 'Секрет клієнта',
      }),
      clientSecretPlaceholder: t({
        en: 'Your OAuth2 client secret',
        'en-GB': 'Your OAuth2 client secret',
        fr: 'Votre secret client OAuth2',
        es: 'Su secreto de cliente OAuth2',
        de: 'Ihr OAuth2-Client-Secret',
        ja: 'OAuth2クライアントシークレット',
        ko: 'OAuth2 클라이언트 시크릿',
        zh: '您的 OAuth2 客户端密钥',
        it: 'Il tuo segreto client OAuth2',
        pt: 'Seu segredo do cliente OAuth2',
        tr: 'OAuth2 istemci gizliliğiniz',
        ru: 'Ваш секрет клиента OAuth2',
        ar: 'سر عميل OAuth2 الخاص بك',
        hi: 'आपका OAuth2 क्लाइंट सीक्रेट',
        pl: 'Twój klucz tajny klienta OAuth2',
        id: 'Rahasia Klien OAuth2 Anda',
        vi: 'Bí mật khách hàng OAuth2 của bạn',
        uk: 'Ваш секрет клієнта OAuth2',
      }),
    },
    advancedSettings: {
      title: t({
        en: 'Advanced Settings',
        'en-GB': 'Advanced Settings',
        fr: 'Paramètres avancés',
        es: 'Configuración avanzada',
        de: 'Erweiterte Einstellungen',
        ja: '詳細設定',
        ko: '고급 설정',
        zh: '高级设置',
        it: 'Impostazioni avanzate',
        pt: 'Configurações avançadas',
        tr: 'Gelişmiş Ayarlar',
        ru: 'Расширенные настройки',
        ar: 'الإعدادات المتقدمة',
        hi: 'उन्नत सेटिंग्स',
        pl: 'Zaawansowane ustawienia',
        id: 'Pengaturan Lanjutan',
        vi: 'Cài đặt nâng cao',
        uk: 'Додаткові налаштування',
      }),
      enforceSSOLabel: t({
        en: 'Enforce SSO',
        'en-GB': 'Enforce SSO',
        fr: 'Forcer SSO',
        es: 'Forzar SSO',
        de: 'SSO erzwingen',
        ja: 'SSOを強制',
        ko: 'SSO 강제',
        zh: '强制 SSO',
        it: 'Forza SSO',
        pt: 'Forçar SSO',
        tr: "SSO'yu Zorunlu Kıl",
        ru: 'Принудительно использовать SSO',
        ar: 'فرض SSO',
        hi: 'SSO लागू करें',
        pl: 'Wymuś SSO',
        id: 'Paksa SSO',
        vi: 'Bắt buộc SSO',
        uk: 'Примусове використання SSO',
      }),
      enforceSSODescription: t({
        en: 'Require all users in this organization to use SSO',
        'en-GB': 'Require all users in this organisation to use SSO',
        fr: 'Obliger tous les utilisateurs de cette organisation à utiliser SSO',
        es: 'Requerir que todos los usuarios de esta organización usen SSO',
        de: 'Alle Benutzer in dieser Organisation müssen SSO verwenden',
        ja: 'この組織のすべてのユーザーにSSOの使用を要求する',
        ko: '이 조직의 모든 사용자가 SSO를 사용하도록 요구',
        zh: '要求此组织中的所有用户使用SSO',
        it: 'Richiedi a tutti gli utenti di questa organizzazione di utilizzare SSO',
        pt: 'Exigir que todos os usuários nesta organização usem SSO',
        tr: 'Bu organizasyondaki tüm kullanıcıların SSO kullanmasını zorunlu kıl',
        ru: 'Требовать от всех пользователей этой организации использовать SSO',
        ar: 'تطلب من جميع المستخدمين في هذه المنظمة استخدام SSO',
        hi: 'इस संगठन के सभी उपयोगकर्ताओं को SSO का उपयोग करने के लिए आवश्यक करें',
        pl: 'Wymagaj, aby wszyscy użytkownicy w tej organizacji używali SSO',
        id: 'Wajibkan semua pengguna di organisasi ini untuk menggunakan SSO',
        vi: 'Yêu cầu tất cả người dùng trong tổ chức này sử dụng SSO',
        uk: 'Вимагати від усіх користувачів цієї організації використання SSO',
      }),
      allowPasswordLoginLabel: t({
        en: 'Allow Password Login',
        'en-GB': 'Allow Password Login',
        fr: 'Autoriser la connexion par mot de passe',
        es: 'Permitir inicio de sesión con contraseña',
        de: 'Passwort-Anmeldung erlauben',
        ja: 'パスワードログインを許可',
        ko: '비밀번호 로그인 허용',
        zh: '允许密码登录',
        it: 'Consenti login con password',
        pt: 'Permitir login com senha',
        tr: 'Şifre ile Girişe İzin Ver',
        ru: 'Разрешить вход по паролю',
        ar: 'السماح بتسجيل الدخول بكلمة المرور',
        hi: 'पासवर्ड लॉगिन की अनुमति दें',
        pl: 'Zezwól na logowanie hasłem',
        id: 'Izinkan Login dengan Kata Sandi',
        vi: 'Cho phép đăng nhập bằng mật khẩu',
        uk: 'Дозволити вхід за паролем',
      }),
      allowPasswordLoginDescription: t({
        en: 'Allow users to bypass SSO and log in with email/password',
        'en-GB': 'Allow users to bypass SSO and log in with email/password',
        fr: 'Permettre aux utilisateurs de contourner SSO et de se connecter avec email/mot de passe',
        es: 'Permitir a los usuarios omitir SSO e iniciar sesión con email/contraseña',
        de: 'Benutzern erlauben, SSO zu umgehen und sich mit E-Mail/Passwort anzumelden',
        ja: 'ユーザーがSSOをバイパスしてメール/パスワードでログインすることを許可',
        ko: '사용자가 SSO를 우회하고 이메일/비밀번호로 로그인하도록 허용',
        zh: '允许用户绕过SSO并使用电子邮件/密码登录',
        it: 'Consenti agli utenti di bypassare SSO e accedere con email/password',
        pt: 'Permitir que os usuários ignorem o SSO e façam login com email/senha',
        tr: "Kullanıcıların SSO'yu atlayıp e-posta/şifre ile giriş yapmasına izin ver",
        ru: 'Разрешить пользователям обходить SSO и входить с помощью email/пароля',
        ar: 'السماح للمستخدمين بتجاوز SSO وتسجيل الدخول بالبريد الإلكتروني/كلمة المرور',
        hi: 'उपयोगकर्ताओं को SSO को बायपास करने और ईमेल/पासवर्ड के साथ लॉग इन करने की अनुमति दें',
        pl: 'Zezwól użytkownikom na pominięcie SSO i logowanie się za pomocą e-maila/hasła',
        id: 'Izinkan pengguna untuk melewati SSO dan masuk dengan email/kata sandi',
        vi: 'Cho phép người dùng bỏ qua SSO và đăng nhập bằng email/mật khẩu',
        uk: 'Дозволити користувачам обійти SSO і входити за допомогою електронної пошти та пароля',
      }),
    },
    saveButton: {
      text: t({
        en: 'Save SSO Configuration',
        'en-GB': 'Save SSO Configuration',
        fr: 'Enregistrer la configuration SSO',
        es: 'Guardar configuración SSO',
        de: 'SSO-Konfiguration speichern',
        ja: 'SSO設定を保存',
        ko: 'SSO 구성 저장',
        zh: '保存 SSO 配置',
        it: 'Salva configurazione SSO',
        pt: 'Salvar configuração SSO',
        tr: 'SSO Yapılandırmasını Kaydet',
        ru: 'Сохранить настройку SSO',
        ar: 'حفظ تكوين SSO',
        hi: 'SSO कॉन्फ़िगरेशन सहेजें',
        pl: 'Zapisz konfigurację SSO',
        id: 'Simpan Konfigurasi SSO',
        vi: 'Lưu cấu hình SSO',
        uk: 'Зберегти налаштування SSO',
      }),
      ariaLabel: t({
        en: 'Click to save SSO configuration',
        'en-GB': 'Click to save SSO configuration',
        fr: 'Cliquez pour enregistrer la configuration SSO',
        es: 'Haga clic para guardar la configuración SSO',
        de: 'Klicken Sie, um die SSO-Konfiguration zu speichern',
        ja: 'SSO設定を保存するにはクリックしてください',
        ko: 'SSO 구성을 저장하려면 클릭하세요',
        zh: '单击以保存SSO配置',
        it: 'Fai clic per salvare la configurazione SSO',
        pt: 'Clique para salvar a configuração SSO',
        tr: 'SSO yapılandırmasını kaydetmek için tıklayın',
        ru: 'Нажмите, чтобы сохранить настройку SSO',
        ar: 'انقر لحفظ تكوين SSO',
        hi: 'SSO कॉन्फ़िगरेशन सहेजने के लिए क्लिक करें',
        pl: 'Kliknij, aby zapisać konfigurację SSO',
        id: 'Klik untuk menyimpan konfigurasi SSO',
        vi: 'Nhấp để lưu cấu hình SSO',
        uk: 'Натисніть, щоб зберегти налаштування SSO',
      }),
    },
  },
  title: 'SSO Settings',
  description:
    'Content declaration for the SSO settings form in the organization dashboard. Includes labels, placeholders, and descriptions for SAML and OIDC configuration.',
  tags: ['dashboard', 'sso', 'authentication', 'organization'],
} satisfies Dictionary;

export default ssoSettingsContent;
