import { type Dictionary, t } from 'intlayer';

const comparisonSectionContent = {
  key: 'comparison-section',
  title: 'Comparison section (TMS Landing)',
  description:
    'Comparison section content for the TMS landing page comparing Intlayer with Crowdin/Lokalise across integration, AI translation, pricing model, and developer experience.',
  content: {
    comparisonTitle: t({
      en: 'Why developers switch to Intlayer',
      'en-GB': 'Why developers switch to Intlayer',
      fr: 'Pourquoi les développeurs passent à Intlayer',
      es: 'Por qué los desarrolladores cambian a Intlayer',
      de: 'Warum Entwickler zu Intlayer wechseln',
      ru: 'Почему разработчики переходят на Intlayer',
      ja: '開発者がIntlayerに切り替える理由',
      ko: '개발자가 Intlayer로 전환하는 이유',
      zh: '为什么开发者选择Intlayer',
      ar: 'لماذا ينتقل المطورون إلى Intlayer',
      it: 'Perché gli sviluppatori passano a Intlayer',
      pt: 'Por que desenvolvedores mudam para Intlayer',
      hi: 'डेवलपर Intlayer पर क्यों स्विच करते हैं',
      tr: "Geliştiriciler neden Intlayer'a geçiyor",
      pl: 'Dlaczego deweloperzy przechodzą na Intlayer',
      id: 'Mengapa pengembang beralih ke Intlayer',
      vi: 'Tại sao nhà phát triển chuyển sang Intlayer',
      uk: 'Чому розробники переходять на Intlayer',
    }),
    comparisonHeaders: {
      feature: t({
        en: 'Feature',
        'en-GB': 'Feature',
        fr: 'Fonctionnalité',
        es: 'Característica',
        de: 'Funktion',
        ru: 'Функция',
        ja: '機能',
        ko: '기능',
        zh: '功能',
        ar: 'الميزة',
        it: 'Funzionalità',
        pt: 'Recurso',
        hi: 'सुविधा',
        tr: 'Özellik',
        pl: 'Funkcja',
        id: 'Fitur',
        vi: 'Tính năng',
        uk: 'Функція',
      }),
      intlayer: 'Intlayer',
      others: 'Crowdin / Lokalise',
    },
    comparisonRows: [
      {
        feature: t({
          en: 'Integration',
          'en-GB': 'Integration',
          fr: 'Intégration',
          es: 'Integración',
          de: 'Integration',
          ru: 'Интеграция',
          ja: '統合',
          ko: '통합',
          zh: '集成',
          ar: 'التكامل',
          it: 'Integrazione',
          pt: 'Integração',
          hi: 'एकीकरण',
          tr: 'Entegrasyon',
          pl: 'Integracja',
          id: 'Integrasi',
          vi: 'Tích hợp',
          uk: 'Інтеграція',
        }),
        intlayer: t({
          en: 'Native (Code-first)',
          'en-GB': 'Native (Code-first)',
          fr: 'Natif (Code-first)',
          es: 'Nativo (Code-first)',
          de: 'Nativ (Code-first)',
          ru: 'Нативный (Code-first)',
          ja: 'ネイティブ（コードファースト）',
          ko: '네이티브 (코드 우선)',
          zh: '原生（代码优先）',
          ar: 'أصلي (Code-first)',
          it: 'Nativo (Code-first)',
          pt: 'Nativo (Code-first)',
          hi: 'नेटिव (कोड-फर्स्ट)',
          tr: 'Yerel (Kod-öncelikli)',
          pl: 'Natywny (Code-first)',
          id: 'Native (Code-first)',
          vi: 'Gốc (Code-first)',
          uk: 'Нативна (орієнтована на код)',
        }),
        others: t({
          en: 'File-based (JSON/XML)',
          'en-GB': 'File-based (JSON/XML)',
          fr: 'Basé sur fichiers',
          es: 'Basado en archivos',
          de: 'Dateibasiert',
          ru: 'На основе файлов (JSON/XML)',
          ja: 'ファイルベース（JSON/XML）',
          ko: '파일 기반 (JSON/XML)',
          zh: '基于文件（JSON/XML）',
          ar: 'قائم على الملفات (JSON/XML)',
          it: 'Basato su file (JSON/XML)',
          pt: 'Baseado em arquivos (JSON/XML)',
          hi: 'फ़ाइल-आधारित (JSON/XML)',
          tr: 'Dosya tabanlı (JSON/XML)',
          pl: 'Oparte na plikach (JSON/XML)',
          id: 'Berbasis file (JSON/XML)',
          vi: 'Dựa trên tệp (JSON/XML)',
          uk: 'Файлова (JSON/XML)',
        }),
      },
      {
        feature: t({
          en: 'AI Translation',
          'en-GB': 'AI Translation',
          fr: 'Traduction IA',
          es: 'Traducción IA',
          de: 'KI-Übersetzung',
          ru: 'ИИ-перевод',
          ja: 'AI翻訳',
          ko: 'AI 번역',
          zh: 'AI翻译',
          ar: 'ترجمة بالذكاء الاصطناعي',
          it: 'Traduzione IA',
          pt: 'Tradução por IA',
          hi: 'AI अनुवाद',
          tr: 'AI Çevirisi',
          pl: 'Tłumaczenie AI',
          id: 'Terjemahan AI',
          vi: 'Dịch bằng AI',
          uk: 'Переклад на базі ШІ',
        }),
        intlayer: t({
          en: 'Native & Context-aware',
          'en-GB': 'Native & Context-aware',
          fr: 'Natif & Contextuel',
          es: 'Nativo y Contextual',
          de: 'Nativ & Kontextbezogen',
          ru: 'Нативный и контекстно-зависимый',
          ja: 'ネイティブ＆コンテキスト対応',
          ko: '네이티브 및 컨텍스트 인식',
          zh: '原生且上下文感知',
          ar: 'أصلي وواعي بالسياق',
          it: 'Nativo e consapevole del contesto',
          pt: 'Nativo e consciente do contexto',
          hi: 'नेटिव और संदर्भ-जागरूक',
          tr: 'Yerel ve bağlam bilinçli',
          pl: 'Natywny i świadomy kontekstu',
          id: 'Native & Context-aware',
          vi: 'Gốc và nhận biết ngữ cảnh',
          uk: 'Нативний і чутливий до контексту',
        }),
        others: t({
          en: 'Paid add-on / Generic',
          'en-GB': 'Paid add-on / Generic',
          fr: 'Add-on payant / Générique',
          es: 'Add-on pago / Genérico',
          de: 'Kostenpflichtiges Add-on',
          ru: 'Платный дополнение / Общий',
          ja: '有料アドオン/汎用',
          ko: '유료 애드온 / 일반',
          zh: '付费插件/通用',
          ar: 'إضافة مدفوعة / عامة',
          it: 'Add-on a pagamento / Generico',
          pt: 'Complemento pago / Genérico',
          hi: 'भुगतान एड-ऑन / सामान्य',
          tr: 'Ücretli eklenti / Genel',
          pl: 'Płatny dodatek / Ogólny',
          id: 'Add-on berbayar / Generik',
          vi: 'Tiện ích trả phí / Chung',
          uk: 'Платне доповнення / Універсальний',
        }),
      },
      {
        feature: t({
          en: 'Pricing Model',
          'en-GB': 'Pricing Model',
          fr: 'Modèle de prix',
          es: 'Modelo de precios',
          de: 'Preismodell',
          ru: 'Модель ценообразования',
          ja: '価格モデル',
          ko: '가격 모델',
          zh: '定价模式',
          ar: 'نموذج التسعير',
          it: 'Modello di prezzo',
          pt: 'Modelo de preços',
          hi: 'मूल्य निर्धारण मॉडल',
          tr: 'Fiyatlandırma Modeli',
          pl: 'Model cenowy',
          id: 'Model Harga',
          vi: 'Mô hình định giá',
          uk: 'Модель ціноутворення',
        }),
        intlayer: t({
          en: 'Free / Flat rate',
          'en-GB': 'Free / Flat rate',
          fr: 'Gratuit / Forfaitaire',
          es: 'Gratis / Tarifa plana',
          de: 'Kostenlos / Pauschale',
          ru: 'Бесплатно / Фиксированная ставка',
          ja: '無料/定額',
          ko: '무료 / 정액제',
          zh: '免费/固定费率',
          ar: 'مجاني / سعر ثابت',
          it: 'Gratuito / Tariffa fissa',
          pt: 'Grátis / Taxa fixa',
          hi: 'मुफ्त / सपाट दर',
          tr: 'Ücretsiz / Sabit fiyat',
          pl: 'Darmowe / Stawka ryczałtowa',
          id: 'Gratis / Tarif tetap',
          vi: 'Miễn phí / Giá cố định',
          uk: 'Безкоштовно / Фіксована ціна',
        }),
        others: t({
          en: 'Per word / Per seat',
          'en-GB': 'Per word / Per seat',
          fr: 'Par mot / Par siège',
          es: 'Por palabra / usuario',
          de: 'Pro Wort / Nutzer',
          ru: 'За слово / За место',
          ja: '単語あたり/座席あたり',
          ko: '단어당 / 좌석당',
          zh: '按字/按席位',
          ar: 'لكل كلمة / لكل مقعد',
          it: 'Per parola / Per posto',
          pt: 'Por palavra / Por assento',
          hi: 'प्रति शब्द / प्रति सीट',
          tr: 'Kelime başına / Koltuk başına',
          pl: 'Za słowo / Za miejsce',
          id: 'Per kata / Per kursi',
          vi: 'Theo từ / Theo chỗ ngồi',
          uk: 'За слово / За користувача',
        }),
      },
      {
        feature: t({
          en: 'DX',
          'en-GB': 'DX',
          fr: 'DX',
          es: 'DX',
          de: 'DX',
          ru: 'DX',
          ja: 'DX',
          ko: 'DX',
          zh: 'DX',
          ar: 'DX',
          it: 'DX',
          pt: 'DX',
          hi: 'DX',
          tr: 'DX',
          pl: 'DX',
          id: 'DX',
          vi: 'DX',
          uk: 'DX (досвід розробника)',
        }),
        intlayer: t({
          en: 'Type-safe Dictionaries',
          'en-GB': 'Type-safe Dictionaries',
          fr: 'Dictionnaires Type-safe',
          es: 'Diccionarios Type-safe',
          de: 'Typsichere Wörterbücher',
          ru: 'Типобезопасные словари',
          ja: '型安全な辞書',
          ko: '타입 안전 사전',
          zh: '类型安全字典',
          ar: 'قواميس آمنة النوع',
          it: 'Dizionari Type-safe',
          pt: 'Dicionários Type-safe',
          hi: 'टाइप-सुरक्षित शब्दकोश',
          tr: 'Tip güvenli Sözlükler',
          pl: 'Słowniki Type-safe',
          id: 'Kamus Type-safe',
          vi: 'Từ điển Type-safe',
          uk: 'Типобезпечні словники',
        }),
        others: t({
          en: 'String keys (Error prone)',
          'en-GB': 'String keys (Error prone)',
          fr: 'Clés de chaîne (Erreurs)',
          es: 'Claves de texto',
          de: 'String-Keys',
          ru: 'Строковые ключи (Склонны к ошибкам)',
          ja: '文字列キー（エラーが発生しやすい）',
          ko: '문자열 키 (오류 발생 가능)',
          zh: '字符串键（易出错）',
          ar: 'مفاتيح نصية (عرضة للأخطاء)',
          it: 'Chiavi stringa (Propense agli errori)',
          pt: 'Chaves de string (Propenso a erros)',
          hi: 'स्ट्रिंग कुंजी (त्रुटि-प्रवण)',
          tr: 'String anahtarları (Hata eğilimli)',
          pl: 'Klucze stringowe (Podatne na błędy)',
          id: 'Kunci string (Rentan kesalahan)',
          vi: 'Khóa chuỗi (Dễ lỗi)',
          uk: 'Рядкові ключі (схильні до помилок)',
        }),
      },
    ],
  },
  tags: ['comparison', 'tms-landing', 'landing-section'],
} satisfies Dictionary;

export default comparisonSectionContent;
