import { type Dictionary, t } from 'intlayer';

const heroSectionContent = {
  key: 'hero-section',
  title: 'TMS Landing Hero Section',
  description:
    'Hero section content for the TMS landing page, including the tagline, headline, subheadline, description, primary and secondary CTAs, and screenshot alt text.',
  content: {
    heroTag: 'Intlayer TMS',
    heroTitle: t({
      en: 'Stop paying per word. Automate with AI.',
      'en-GB': 'Stop paying per word. Automate with AI.',
      fr: "Arrêtez de payer au mot. Automatisez avec l'IA.",
      es: 'Deja de pagar por palabra. Automatiza con IA.',
      de: 'Hören Sie auf, pro Wort zu zahlen. Automatisieren Sie mit KI.',
      ru: 'Перестаньте платить за слово. Автоматизируйте с помощью ИИ.',
      ja: '単語ごとの支払いをやめましょう。AIで自動化します。',
      ko: '단어당 비용 지불을 중단하세요. AI로 자동화하세요.',
      zh: '停止按字付费。使用AI自动化。',
      ar: 'توقف عن الدفع لكل كلمة. أتمتة باستخدام الذكاء الاصطناعي.',
      it: "Smetti di pagare per parola. Automatizza con l'IA.",
      pt: 'Pare de pagar por palavra. Automatize com IA.',
      hi: 'शब्द के अनुसार भुगतान करना बंद करें। AI के साथ स्वचालित करें।',
      tr: 'Kelime başına ödeme yapmayı bırakın. AI ile otomatikleştirin.',
      pl: 'Przestań płacić za słowo. Automatyzuj za pomocą AI.',
      id: 'Berhenti membayar per kata. Otomatiskan dengan AI.',
      vi: 'Ngừng trả tiền theo từ. Tự động hóa bằng AI.',
      uk: 'Припиніть платити за слово. Автоматизуйте за допомогою ШІ.',
    }),
    heroSubtitle: t({
      en: 'The open-source alternative to Crowdin & Lokalise. Built for modern developer workflows.',
      'en-GB':
        'The open-source alternative to Crowdin & Lokalise. Built for modern developer workflows.',
      fr: "L'alternative open-source à Crowdin & Lokalise. Conçu pour les workflows de développement modernes.",
      es: 'La alternativa de código abierto a Crowdin y Lokalise. Creado para flujos de trabajo modernos.',
      de: 'Die Open-Source-Alternative zu Crowdin & Lokalise. Gebaut für moderne Entwickler-Workflows.',
      ru: 'Открытая альтернатива Crowdin и Lokalise. Создана для современных рабочих процессов разработчиков.',
      ja: 'CrowdinとLokaliseのオープンソース代替品。モダンな開発者ワークフロー向けに構築。',
      ko: 'Crowdin 및 Lokalise의 오픈소스 대안. 현대적인 개발자 워크플로우를 위해 구축되었습니다.',
      zh: 'Crowdin和Lokalise的开源替代方案。专为现代开发者工作流程而构建。',
      ar: 'البديل مفتوح المصدر لـ Crowdin و Lokalise. مبني لسير عمل المطورين الحديث.',
      it: "L'alternativa open-source a Crowdin e Lokalise. Costruita per flussi di lavoro moderni per sviluppatori.",
      pt: 'A alternativa open-source ao Crowdin e Lokalise. Construído para fluxos de trabalho modernos de desenvolvedores.',
      hi: 'Crowdin और Lokalise का ओपन-सोर्स विकल्प। आधुनिक डेवलपर वर्कफ़्लो के लिए निर्मित।',
      tr: "Crowdin ve Lokalise'nin açık kaynak alternatifi. Modern geliştirici iş akışları için oluşturuldu.",
      pl: 'Alternatywa open-source dla Crowdin i Lokalise. Zbudowana dla nowoczesnych przepływów pracy deweloperów.',
      id: 'Alternatif open-source untuk Crowdin & Lokalise. Dibangun untuk alur kerja pengembang modern.',
      vi: 'Giải pháp mã nguồn mở thay thế cho Crowdin & Lokalise. Được xây dựng cho quy trình làm việc của nhà phát triển hiện đại.',
      uk: 'Відкрите програмне забезпечення — альтернатива Crowdin і Lokalise. Створено для сучасних робочих процесів розробників.',
    }),
    heroDescription: t({
      en: 'Manage translations directly in your code or via the visual editor. Leverage AI to translate instantly. collaborate with your team without seat limits.',
      'en-GB':
        'Manage translations directly in your code or via the visual editor. Leverage AI to translate instantly. Collaborate with your team without seat limits.',
      fr: "Gérez les traductions directement dans votre code ou via l'éditeur visuel. Utilisez l'IA pour traduire instantanément. Collaborez avec votre équipe sans limite de sièges.",
      es: 'Gestiona traducciones directamente en tu código o vía editor visual. Usa IA para traducir al instante. Colabora con tu equipo sin límites de usuarios.',
      de: 'Verwalten Sie Übersetzungen direkt in Ihrem Code oder über den visuellen Editor. Nutzen Sie KI für sofortige Übersetzungen. Arbeiten Sie ohne Platzbegrenzung im Team.',
      ru: 'Управляйте переводами прямо в коде или через визуальный редактор. Используйте ИИ для мгновенного перевода. Сотрудничайте с командой без ограничений по местам.',
      ja: 'コード内またはビジュアルエディターで翻訳を直接管理。AIを活用して即座に翻訳。座席制限なしでチームと協力。',
      ko: '코드 또는 시각적 편집기에서 직접 번역을 관리하세요. AI를 활용하여 즉시 번역하세요. 좌석 제한 없이 팀과 협업하세요.',
      zh: '直接在代码中或通过可视化编辑器管理翻译。利用AI即时翻译。与团队协作，无席位限制。',
      ar: 'إدارة الترجمات مباشرة في الكود أو عبر المحرر المرئي. استفد من الذكاء الاصطناعي للترجمة الفورية. تعاون مع فريقك دون حدود المقاعد.',
      it: "Gestisci le traduzioni direttamente nel tuo codice o tramite l'editor visivo. Sfrutta l'IA per tradurre istantaneamente. Collabora con il tuo team senza limiti di posti.",
      pt: 'Gerencie traduções diretamente no seu código ou via editor visual. Aproveite a IA para traduzir instantaneamente. Colabore com sua equipe sem limites de assentos.',
      hi: 'अपने कोड में या दृश्य संपादक के माध्यम से सीधे अनुवाद प्रबंधित करें। तुरंत अनुवाद करने के लिए AI का लाभ उठाएं। सीट सीमा के बिना अपनी टीम के साथ सहयोग करें।',
      tr: "Çevirileri doğrudan kodunuzda veya görsel düzenleyici aracılığıyla yönetin. Anında çeviri için AI'dan yararlanın. Koltuk sınırı olmadan ekibinizle işbirliği yapın.",
      pl: 'Zarządzaj tłumaczeniami bezpośrednio w kodzie lub za pomocą edytora wizualnego. Wykorzystaj AI do natychmiastowego tłumaczenia. Współpracuj z zespołem bez limitów miejsc.',
      id: 'Kelola terjemahan langsung di kode Anda atau melalui editor visual. Manfaatkan AI untuk menerjemahkan secara instan. Berkolaborasi dengan tim Anda tanpa batas kursi.',
      vi: 'Quản lý bản dịch trực tiếp trong mã của bạn hoặc qua trình chỉnh sửa trực quan. Tận dụng AI để dịch ngay lập tức. Cộng tác với nhóm của bạn mà không giới hạn chỗ ngồi.',
      uk: 'Керуйте перекладами прямо в коді або через візуальний редактор. Використовуйте ШІ для миттєвого перекладу. Співпрацюйте з командою без обмежень на кількість користувачів.',
    }),
    primaryCta: t({
      en: 'Start for free',
      'en-GB': 'Start for free',
      fr: 'Commencer gratuitement',
      es: 'Empieza gratis',
      de: 'Kostenlos starten',
      ru: 'Начать бесплатно',
      ja: '無料で始める',
      ko: '무료로 시작하기',
      zh: '免费开始',
      ar: 'ابدأ مجاناً',
      it: 'Inizia gratuitamente',
      pt: 'Comece grátis',
      hi: 'मुफ्त में शुरू करें',
      tr: 'Ücretsiz başla',
      pl: 'Zacznij za darmo',
      id: 'Mulai gratis',
      vi: 'Bắt đầu miễn phí',
      uk: 'Почати безкоштовно',
    }),
    secondaryCta: t({
      en: 'Compare features',
      'en-GB': 'Compare features',
      fr: 'Comparer les fonctionnalités',
      es: 'Comparar características',
      de: 'Funktionen vergleichen',
      ru: 'Сравнить функции',
      ja: '機能を比較',
      ko: '기능 비교',
      zh: '比较功能',
      ar: 'مقارنة الميزات',
      it: 'Confronta le funzionalità',
      pt: 'Comparar recursos',
      hi: 'सुविधाओं की तुलना करें',
      tr: 'Özellikleri karşılaştır',
      pl: 'Porównaj funkcje',
      id: 'Bandingkan fitur',
      vi: 'So sánh tính năng',
      uk: 'Порівняти функції',
    }),
    screenshotAlt: t({
      en: 'Intlayer TMS - Translation management interface',
      'en-GB': 'Intlayer TMS - Translation management interface',
      fr: 'Intlayer TMS - Interface de gestion de traduction',
      es: 'Intlayer TMS - Interfaz de gestión de traducción',
      de: 'Intlayer TMS - Übersetzungsverwaltungsoberfläche',
      ru: 'Intlayer TMS - Интерфейс управления переводами',
      ja: 'Intlayer TMS - 翻訳管理インターフェース',
      ko: 'Intlayer TMS - 번역 관리 인터페이스',
      zh: 'Intlayer TMS - 翻译管理界面',
      ar: 'Intlayer TMS - واجهة إدارة الترجمة',
      it: 'Intlayer TMS - Interfaccia di gestione traduzioni',
      pt: 'Intlayer TMS - Interface de gerenciamento de tradução',
      hi: 'Intlayer TMS - अनुवाद प्रबंधन इंटरफ़ेस',
      tr: 'Intlayer TMS - Çeviri yönetim arayüzü',
      pl: 'Intlayer TMS - Interfejs zarządzania tłumaczeniami',
      id: 'Intlayer TMS - Antarmuka manajemen terjemahan',
      vi: 'Intlayer TMS - Giao diện quản lý bản dịch',
      uk: 'Intlayer TMS — інтерфейс управління перекладами',
    }),
  },
  tags: ['hero section', 'landing page', 'tms', 'component', 'marketing'],
} satisfies Dictionary;

export default heroSectionContent;
