import { type Dictionary, t } from 'intlayer';

const comparisonSectionContent = {
  key: 'comparison-section-markdown',
  title: 'Markdown Landing Comparison Section',
  description:
    'Capability matrix opposing the Intlayer Markdown engine to markdown-to-jsx, marked, remark / rehype and @mdx-js on MDX, typing, framework coverage, SSR, configuration, frontmatter, dependencies and bundle cost.',
  content: {
    comparisonTitle: t({
      en: 'One engine instead of a shopping list',
      'en-GB': 'One engine instead of a shopping list',
      fr: 'Un seul moteur au lieu d’une liste de courses',
      es: 'Un solo motor en lugar de una lista de la compra',
      de: 'Eine Engine statt einer Einkaufsliste',
      ru: 'Один движок вместо списка покупок',
      ja: '選定リストではなく、ひとつのエンジン',
      ko: '고를 목록 대신 하나의 엔진',
      zh: '一个引擎，而不是一张选型清单',
      ar: 'محرك واحد بدل قائمة اختيارات',
      it: 'Un solo motore invece di una lista della spesa',
      pt: 'Um motor em vez de uma lista de compras',
      hi: 'चुनने की सूची के बजाय एक ही इंजन',
      tr: 'Bir alışveriş listesi yerine tek bir motor',
      pl: 'Jeden silnik zamiast listy zakupów',
      id: 'Satu mesin, bukan daftar belanja',
      vi: 'Một bộ máy thay vì một danh sách lựa chọn',
      uk: 'Один рушій замість списку покупок',
    }),
    comparisonDescription: t({
      en: 'Every project ends with the same chore: weigh markdown-to-jsx against marked, remark and MDX, wire the winner in, then discover it does not do MDX, that its types are loose, or that its plugin chain breaks on the client. Intlayer makes that choice for you.',
      'en-GB':
        'Every project ends with the same chore: weigh markdown-to-jsx against marked, remark and MDX, wire the winner in, then discover it does not do MDX, that its types are loose, or that its plugin chain breaks on the client. Intlayer makes that choice for you.',
      fr: "Chaque projet finit par la même corvée : peser markdown-to-jsx contre marked, remark et MDX, brancher le gagnant, puis découvrir qu'il ne gère pas MDX, que son typage est approximatif ou que sa chaîne de plugins casse côté client. Intlayer fait ce choix pour vous.",
      es: 'Todo proyecto acaba con la misma tarea: comparar markdown-to-jsx con marked, remark y MDX, integrar al ganador y descubrir que no soporta MDX, que sus tipos son laxos o que su cadena de plugins se rompe en el cliente. Intlayer toma esa decisión por ti.',
      de: 'Jedes Projekt endet mit derselben Pflichtübung: markdown-to-jsx gegen marked, remark und MDX abwägen, den Sieger einbinden und dann feststellen, dass er kein MDX kann, seine Typen ungenau sind oder seine Plugin-Kette auf dem Client bricht. Intlayer trifft diese Wahl für Sie.',
      ru: 'Каждый проект заканчивается одной и той же рутиной: взвесить markdown-to-jsx против marked, remark и MDX, подключить победителя и обнаружить, что он не умеет MDX, что его типы неточны или что цепочка плагинов ломается на клиенте. Intlayer делает этот выбор за вас.',
      ja: 'どのプロジェクトでも同じ作業が待っています。markdown-to-jsx、marked、remark、MDXを比べ、選んだものを組み込み、MDX非対応だったり型が甘かったり、プラグインの連鎖がクライアントで壊れたりすることに気づく。Intlayerはその選択を代わりに済ませます。',
      ko: '모든 프로젝트는 같은 잡일로 끝납니다. markdown-to-jsx와 marked, remark, MDX를 저울질하고 승자를 연결한 뒤, MDX를 지원하지 않거나 타입이 허술하거나 플러그인 체인이 클라이언트에서 깨진다는 걸 알게 되죠. Intlayer가 그 선택을 대신합니다.',
      zh: '每个项目都要做同一件苦差事：在 markdown-to-jsx、marked、remark 和 MDX 之间权衡，接入选中的那个，然后发现它不支持 MDX、类型很松散，或者插件链在客户端崩掉。Intlayer 替你做出这个选择。',
      ar: 'ينتهي كل مشروع بالمهمة نفسها: الموازنة بين markdown-to-jsx وmarked وremark وMDX، ثم ربط الفائز واكتشاف أنه لا يدعم MDX أو أن أنواعه فضفاضة أو أن سلسلة إضافاته تنهار على العميل. يتولى Intlayer هذا الاختيار عنك.',
      it: 'Ogni progetto finisce con la stessa incombenza: soppesare markdown-to-jsx contro marked, remark e MDX, integrare il vincitore e scoprire che non supporta MDX, che i tipi sono approssimativi o che la catena di plugin si rompe sul client. Intlayer sceglie al posto tuo.',
      pt: 'Todo projeto termina com a mesma tarefa: pesar markdown-to-jsx contra marked, remark e MDX, integrar o vencedor e descobrir que ele não faz MDX, que os tipos são frouxos ou que a cadeia de plugins quebra no cliente. O Intlayer faz essa escolha por você.',
      hi: 'हर प्रोजेक्ट एक ही काम पर आकर रुकता है: markdown-to-jsx, marked, remark और MDX को तौलो, विजेता को जोड़ो, और फिर पता चले कि वह MDX नहीं करता, उसके टाइप ढीले हैं, या उसकी प्लगइन चेन क्लाइंट पर टूट जाती है। Intlayer यह चुनाव आपके लिए कर देता है।',
      tr: "Her proje aynı angaryayla biter: markdown-to-jsx'i marked, remark ve MDX ile tartıp kazananı projeye bağlarsınız, ardından MDX'i desteklemediğini, tiplerinin gevşek olduğunu ya da eklenti zincirinin istemcide bozulduğunu keşfedersiniz. Intlayer bu seçimi sizin yerinize yapar.",
      pl: 'Każdy projekt kończy się tym samym obowiązkiem: porównać markdown-to-jsx z marked, remark i MDX, podłączyć zwycięzcę, a potem odkryć, że nie obsługuje MDX, że typy są nieprecyzyjne albo że łańcuch wtyczek psuje się po stronie klienta. Intlayer dokonuje tego wyboru za Ciebie.',
      id: 'Setiap proyek berakhir dengan tugas yang sama: menimbang markdown-to-jsx dengan marked, remark, dan MDX, memasang pemenangnya, lalu sadar bahwa ia tidak mendukung MDX, tipenya longgar, atau rantai plugin-nya rusak di sisi klien. Intlayer membuat pilihan itu untuk Anda.',
      vi: 'Dự án nào cũng kết thúc bằng cùng một việc vặt: cân nhắc markdown-to-jsx với marked, remark và MDX, gắn thứ được chọn vào, rồi phát hiện nó không hỗ trợ MDX, kiểu dữ liệu lỏng lẻo, hoặc chuỗi plugin hỏng ở phía client. Intlayer chọn giúp bạn.',
      uk: 'Кожен проєкт завершується однією й тією ж рутиною: зважити markdown-to-jsx проти marked, remark і MDX, під’єднати переможця, а потім виявити, що він не вміє MDX, що його типи неточні або що ланцюжок плагінів ламається на клієнті. Intlayer робить цей вибір за вас.',
    }),
    featureHeader: t({
      en: 'Capability',
      'en-GB': 'Capability',
      fr: 'Capacité',
      es: 'Capacidad',
      de: 'Fähigkeit',
      ru: 'Возможность',
      ja: '機能',
      ko: '기능',
      zh: '能力',
      ar: 'القدرة',
      it: 'Capacità',
      pt: 'Capacidade',
      hi: 'क्षमता',
      tr: 'Yetenek',
      pl: 'Możliwość',
      id: 'Kemampuan',
      vi: 'Khả năng',
      uk: 'Можливість',
    }),
    legend: {
      supported: t({
        en: 'Supported',
        'en-GB': 'Supported',
        fr: 'Pris en charge',
        es: 'Compatible',
        de: 'Unterstützt',
        ru: 'Поддерживается',
        ja: '対応',
        ko: '지원',
        zh: '支持',
        ar: 'مدعوم',
        it: 'Supportato',
        pt: 'Suportado',
        hi: 'समर्थित',
        tr: 'Destekleniyor',
        pl: 'Obsługiwane',
        id: 'Didukung',
        vi: 'Được hỗ trợ',
        uk: 'Підтримується',
      }),
      partial: t({
        en: 'Partial, or through extra packages',
        'en-GB': 'Partial, or through extra packages',
        fr: 'Partiel, ou via des paquets supplémentaires',
        es: 'Parcial, o mediante paquetes adicionales',
        de: 'Teilweise oder über zusätzliche Pakete',
        ru: 'Частично или через дополнительные пакеты',
        ja: '部分的、または追加パッケージ経由',
        ko: '부분 지원 또는 추가 패키지 필요',
        zh: '部分支持，或需额外的包',
        ar: 'جزئي، أو عبر حزم إضافية',
        it: 'Parziale, o tramite pacchetti aggiuntivi',
        pt: 'Parcial, ou por meio de pacotes extras',
        hi: 'आंशिक, या अतिरिक्त पैकेज के ज़रिए',
        tr: 'Kısmi ya da ek paketlerle',
        pl: 'Częściowo lub przez dodatkowe pakiety',
        id: 'Sebagian, atau lewat paket tambahan',
        vi: 'Một phần, hoặc qua gói bổ sung',
        uk: 'Частково або через додаткові пакети',
      }),
      notSupported: t({
        en: 'Not supported',
        'en-GB': 'Not supported',
        fr: 'Non pris en charge',
        es: 'No compatible',
        de: 'Nicht unterstützt',
        ru: 'Не поддерживается',
        ja: '非対応',
        ko: '미지원',
        zh: '不支持',
        ar: 'غير مدعوم',
        it: 'Non supportato',
        pt: 'Sem suporte',
        hi: 'असमर्थित',
        tr: 'Desteklenmiyor',
        pl: 'Nieobsługiwane',
        id: 'Tidak didukung',
        vi: 'Không hỗ trợ',
        uk: 'Не підтримується',
      }),
    },
    rows: [
      {
        id: 'mdx',
        feature: t({
          en: 'MDX components',
          'en-GB': 'MDX components',
          fr: 'Composants MDX',
          es: 'Componentes MDX',
          de: 'MDX-Komponenten',
          ru: 'MDX-компоненты',
          ja: 'MDXコンポーネント',
          ko: 'MDX 컴포넌트',
          zh: 'MDX 组件',
          ar: 'مكوّنات MDX',
          it: 'Componenti MDX',
          pt: 'Componentes MDX',
          hi: 'MDX कंपोनेंट',
          tr: 'MDX bileşenleri',
          pl: 'Komponenty MDX',
          id: 'Komponen MDX',
          vi: 'Thành phần MDX',
          uk: 'MDX-компоненти',
        }),
      },
      {
        id: 'typing',
        feature: t({
          en: 'Type-safe nodes and overrides',
          'en-GB': 'Type-safe nodes and overrides',
          fr: 'Nœuds et surcharges typés',
          es: 'Nodos y sobrescrituras tipados',
          de: 'Typsichere Nodes und Overrides',
          ru: 'Типобезопасные узлы и переопределения',
          ja: '型安全なノードとオーバーライド',
          ko: '타입 안전한 노드와 오버라이드',
          zh: '类型安全的节点与覆盖项',
          ar: 'عقد وتجاوزات آمنة الأنواع',
          it: 'Nodi e override type-safe',
          pt: 'Nós e sobrescritas com tipos seguros',
          hi: 'टाइप-सुरक्षित नोड और ओवरराइड',
          tr: 'Tip güvenli düğümler ve geçersiz kılmalar',
          pl: 'Bezpieczne typowo węzły i nadpisania',
          id: 'Node dan override yang aman tipe',
          vi: 'Node và override an toàn kiểu',
          uk: 'Типобезпечні вузли та перевизначення',
        }),
      },
      {
        id: 'react',
        feature: t({
          en: 'React and Next.js output',
          'en-GB': 'React and Next.js output',
          fr: 'Sortie React et Next.js',
          es: 'Salida para React y Next.js',
          de: 'Ausgabe für React und Next.js',
          ru: 'Вывод для React и Next.js',
          ja: 'ReactとNext.js向けの出力',
          ko: 'React 및 Next.js 출력',
          zh: 'React 与 Next.js 输出',
          ar: 'مخرجات لـ React وNext.js',
          it: 'Output per React e Next.js',
          pt: 'Saída para React e Next.js',
          hi: 'React और Next.js आउटपुट',
          tr: 'React ve Next.js çıktısı',
          pl: 'Wyjście dla React i Next.js',
          id: 'Keluaran React dan Next.js',
          vi: 'Đầu ra React và Next.js',
          uk: 'Вивід для React і Next.js',
        }),
      },
      {
        id: 'frameworks',
        feature: t({
          en: 'Vue, Svelte, Solid, Preact, Angular',
          'en-GB': 'Vue, Svelte, Solid, Preact, Angular',
          fr: 'Vue, Svelte, Solid, Preact, Angular',
          es: 'Vue, Svelte, Solid, Preact, Angular',
          de: 'Vue, Svelte, Solid, Preact, Angular',
          ru: 'Vue, Svelte, Solid, Preact, Angular',
          ja: 'Vue、Svelte、Solid、Preact、Angular',
          ko: 'Vue, Svelte, Solid, Preact, Angular',
          zh: 'Vue、Svelte、Solid、Preact、Angular',
          ar: 'Vue وSvelte وSolid وPreact وAngular',
          it: 'Vue, Svelte, Solid, Preact, Angular',
          pt: 'Vue, Svelte, Solid, Preact, Angular',
          hi: 'Vue, Svelte, Solid, Preact, Angular',
          tr: 'Vue, Svelte, Solid, Preact, Angular',
          pl: 'Vue, Svelte, Solid, Preact, Angular',
          id: 'Vue, Svelte, Solid, Preact, Angular',
          vi: 'Vue, Svelte, Solid, Preact, Angular',
          uk: 'Vue, Svelte, Solid, Preact, Angular',
        }),
      },
      {
        id: 'ssr',
        feature: t({
          en: 'Server parse, client render, no re-parse',
          'en-GB': 'Server parse, client render, no re-parse',
          fr: 'Analyse serveur, rendu client, sans ré-analyse',
          es: 'Análisis en servidor, render en cliente, sin reanálisis',
          de: 'Server parst, Client rendert, kein erneutes Parsen',
          ru: 'Разбор на сервере, рендеринг на клиенте, без повторного разбора',
          ja: 'サーバーで解析、クライアントで描画、再解析なし',
          ko: '서버 파싱, 클라이언트 렌더링, 재파싱 없음',
          zh: '服务端解析，客户端渲染，无需重新解析',
          ar: 'تحليل على الخادم وعرض على العميل بلا إعادة تحليل',
          it: 'Parsing sul server, rendering sul client, senza ri-parsing',
          pt: 'Análise no servidor, render no cliente, sem reanálise',
          hi: 'सर्वर पर पार्स, क्लाइंट पर रेंडर, दोबारा पार्स नहीं',
          tr: 'Sunucuda ayrıştırma, istemcide işleme, yeniden ayrıştırma yok',
          pl: 'Parsowanie na serwerze, render na kliencie, bez ponownego parsowania',
          id: 'Urai di server, render di klien, tanpa penguraian ulang',
          vi: 'Phân tích ở máy chủ, kết xuất ở client, không phân tích lại',
          uk: 'Розбір на сервері, рендеринг на клієнті, без повторного розбору',
        }),
      },
      {
        id: 'config',
        feature: t({
          en: 'Configured without a plugin chain',
          'en-GB': 'Configured without a plugin chain',
          fr: 'Configuré sans chaîne de plugins',
          es: 'Configurable sin cadena de plugins',
          de: 'Konfiguration ohne Plugin-Kette',
          ru: 'Настройка без цепочки плагинов',
          ja: 'プラグインの連鎖なしで設定',
          ko: '플러그인 체인 없이 설정',
          zh: '无需插件链即可配置',
          ar: 'إعداد بلا سلسلة إضافات',
          it: 'Configurabile senza catena di plugin',
          pt: 'Configurado sem cadeia de plugins',
          hi: 'बिना प्लगइन चेन के कॉन्फ़िगर',
          tr: 'Eklenti zinciri olmadan yapılandırma',
          pl: 'Konfiguracja bez łańcucha wtyczek',
          id: 'Dikonfigurasi tanpa rantai plugin',
          vi: 'Cấu hình không cần chuỗi plugin',
          uk: 'Налаштування без ланцюжка плагінів',
        }),
      },
      {
        id: 'frontmatter',
        feature: t({
          en: 'Typed frontmatter metadata',
          'en-GB': 'Typed frontmatter metadata',
          fr: 'Métadonnées de frontmatter typées',
          es: 'Metadatos de frontmatter tipados',
          de: 'Typisierte Frontmatter-Metadaten',
          ru: 'Типизированные метаданные frontmatter',
          ja: '型付きのフロントマターメタデータ',
          ko: '타입이 지정된 프론트매터 메타데이터',
          zh: '带类型的 frontmatter 元数据',
          ar: 'بيانات frontmatter وصفية مُنمَّطة',
          it: 'Metadati frontmatter tipizzati',
          pt: 'Metadados de frontmatter tipados',
          hi: 'टाइप्ड frontmatter मेटाडेटा',
          tr: 'Tipli frontmatter meta verileri',
          pl: 'Typowane metadane frontmatter',
          id: 'Metadata frontmatter bertipe',
          vi: 'Siêu dữ liệu frontmatter có kiểu',
          uk: 'Типізовані метадані frontmatter',
        }),
      },
      {
        id: 'dependencies',
        feature: t({
          en: 'Zero runtime dependencies',
          'en-GB': 'Zero runtime dependencies',
          fr: "Zéro dépendance d'exécution",
          es: 'Cero dependencias en tiempo de ejecución',
          de: 'Keine Laufzeitabhängigkeiten',
          ru: 'Ноль зависимостей во время выполнения',
          ja: '実行時依存関係ゼロ',
          ko: '런타임 의존성 제로',
          zh: '零运行时依赖',
          ar: 'صفر تبعيات وقت التشغيل',
          it: 'Zero dipendenze a runtime',
          pt: 'Zero dependências de runtime',
          hi: 'शून्य रनटाइम निर्भरता',
          tr: 'Sıfır çalışma zamanı bağımlılığı',
          pl: 'Zero zależności w czasie działania',
          id: 'Nol dependensi runtime',
          vi: 'Không phụ thuộc lúc chạy',
          uk: 'Нуль залежностей під час виконання',
        }),
      },
      {
        id: 'purge',
        feature: t({
          en: 'Removed from the bundle when unused',
          'en-GB': 'Removed from the bundle when unused',
          fr: 'Retiré du bundle si inutilisé',
          es: 'Eliminado del bundle si no se usa',
          de: 'Aus dem Bundle entfernt, wenn ungenutzt',
          ru: 'Удаляется из бандла, если не используется',
          ja: '未使用ならバンドルから削除',
          ko: '미사용 시 번들에서 제거',
          zh: '未使用时从打包结果中移除',
          ar: 'يُزال من الحزمة عند عدم الاستخدام',
          it: 'Rimosso dal bundle se non usato',
          pt: 'Removido do bundle quando não usado',
          hi: 'अप्रयुक्त होने पर बंडल से हटाया गया',
          tr: 'Kullanılmadığında paketten kaldırılır',
          pl: 'Usuwany z bundla, gdy nieużywany',
          id: 'Dihapus dari bundel bila tidak dipakai',
          vi: 'Bị loại khỏi bundle khi không dùng',
          uk: 'Вилучається з бандла, якщо не використовується',
        }),
      },
    ],
    notes: {
      pluginChain: t({
        en: 'remark and rehype can do most of it, but through a plugin chain you assemble yourself — and one that does not always behave the same in the browser as on the server.',
        'en-GB':
          'remark and rehype can do most of it, but through a plugin chain you assemble yourself — and one that does not always behave the same in the browser as on the server.',
        fr: "remark et rehype savent faire l'essentiel, mais via une chaîne de plugins que vous assemblez vous-même, et qui ne se comporte pas toujours pareil dans le navigateur et sur le serveur.",
        es: 'remark y rehype pueden hacer casi todo, pero mediante una cadena de plugins que tú mismo ensamblas y que no siempre se comporta igual en el navegador que en el servidor.',
        de: 'remark und rehype können das meiste davon — aber über eine Plugin-Kette, die Sie selbst zusammenstellen und die sich im Browser nicht immer wie auf dem Server verhält.',
        ru: 'remark и rehype умеют почти всё это, но через цепочку плагинов, которую вы собираете сами и которая в браузере ведёт себя не всегда так же, как на сервере.',
        ja: 'remarkとrehypeはその大半をこなせますが、自分で組み立てるプラグインの連鎖を通してであり、ブラウザとサーバーで挙動が同じとは限りません。',
        ko: 'remark와 rehype는 대부분을 해내지만, 직접 조립해야 하는 플러그인 체인을 거치며 브라우저와 서버에서 늘 같게 동작하지도 않습니다.',
        zh: 'remark 和 rehype 大多能做到，但要靠你自己拼装的插件链，而它在浏览器和服务端的行为并不总是一致。',
        ar: 'يستطيع remark وrehype فعل معظم ذلك، لكن عبر سلسلة إضافات تجمّعها بنفسك، ولا تتصرف دائماً في المتصفح كما تتصرف على الخادم.',
        it: 'remark e rehype sanno fare quasi tutto, ma attraverso una catena di plugin che assembli tu e che non si comporta sempre allo stesso modo nel browser e sul server.',
        pt: 'remark e rehype dão conta da maior parte, mas por meio de uma cadeia de plugins que você mesmo monta — e que nem sempre se comporta igual no navegador e no servidor.',
        hi: 'remark और rehype अधिकांश काम कर सकते हैं, पर उस प्लगइन चेन के ज़रिए जिसे आप स्वयं जोड़ते हैं, और जो ब्राउज़र तथा सर्वर पर हमेशा एक जैसा व्यवहार नहीं करती।',
        tr: 'remark ve rehype bunun çoğunu yapabilir; ama kendinizin kurduğu ve tarayıcıda sunucudakiyle her zaman aynı davranmayan bir eklenti zinciri üzerinden.',
        pl: 'remark i rehype potrafią większość z tego, ale przez łańcuch wtyczek, który sam składasz — i który w przeglądarce nie zawsze zachowuje się tak jak na serwerze.',
        id: 'remark dan rehype bisa melakukan sebagian besarnya, tetapi lewat rantai plugin yang Anda rakit sendiri — dan yang tidak selalu berperilaku sama di peramban seperti di server.',
        vi: 'remark và rehype làm được phần lớn, nhưng qua một chuỗi plugin bạn tự lắp ráp — và nó không phải lúc nào cũng hoạt động giống nhau ở trình duyệt và máy chủ.',
        uk: 'remark і rehype здатні на більшість цього, але через ланцюжок плагінів, який ви збираєте самі і який у браузері не завжди поводиться так само, як на сервері.',
      }),
      frameworks: t({
        en: 'markdown-to-jsx renders React only, and marked hands you an HTML string. For Vue, Svelte, Solid or Angular there is no equivalent to reach for.',
        'en-GB':
          'markdown-to-jsx renders React only, and marked hands you an HTML string. For Vue, Svelte, Solid or Angular there is no equivalent to reach for.',
        fr: "markdown-to-jsx ne rend que du React, et marked vous renvoie une chaîne HTML. Pour Vue, Svelte, Solid ou Angular, il n'existe pas d'équivalent vers lequel se tourner.",
        es: 'markdown-to-jsx solo renderiza React y marked te devuelve una cadena HTML. Para Vue, Svelte, Solid o Angular no hay un equivalente al que recurrir.',
        de: 'markdown-to-jsx rendert nur React, und marked liefert Ihnen einen HTML-String. Für Vue, Svelte, Solid oder Angular gibt es kein Pendant, auf das man zurückgreifen könnte.',
        ru: 'markdown-to-jsx рендерит только React, а marked отдаёт строку HTML. Для Vue, Svelte, Solid или Angular аналога попросту нет.',
        ja: 'markdown-to-jsxはReactしか描画せず、markedはHTML文字列を返すだけです。Vue、Svelte、Solid、Angularに手を伸ばせる同等品はありません。',
        ko: 'markdown-to-jsx는 React만 렌더링하고, marked는 HTML 문자열을 돌려줍니다. Vue, Svelte, Solid, Angular에는 손에 잡히는 대안이 없습니다.',
        zh: 'markdown-to-jsx 只渲染 React，marked 只给你一段 HTML 字符串。对 Vue、Svelte、Solid 或 Angular 来说，根本没有可用的对应方案。',
        ar: 'يعرض markdown-to-jsx لـ React فقط، ويعطيك marked سلسلة HTML. أما Vue وSvelte وSolid وAngular فلا يوجد لها بديل مكافئ.',
        it: 'markdown-to-jsx renderizza solo React e marked ti restituisce una stringa HTML. Per Vue, Svelte, Solid o Angular non esiste un equivalente a cui rivolgersi.',
        pt: 'markdown-to-jsx só renderiza React e o marked devolve uma string HTML. Para Vue, Svelte, Solid ou Angular não há equivalente a que recorrer.',
        hi: 'markdown-to-jsx सिर्फ़ React रेंडर करता है और marked आपको HTML स्ट्रिंग थमा देता है। Vue, Svelte, Solid या Angular के लिए कोई समकक्ष विकल्प ही नहीं है।',
        tr: 'markdown-to-jsx yalnızca React işler, marked ise size bir HTML dizesi verir. Vue, Svelte, Solid veya Angular için başvurabileceğiniz bir muadil yok.',
        pl: 'markdown-to-jsx renderuje tylko React, a marked zwraca ciąg HTML. Dla Vue, Svelte, Solid czy Angulara nie ma odpowiednika, po który można sięgnąć.',
        id: 'markdown-to-jsx hanya merender React, dan marked memberi Anda string HTML. Untuk Vue, Svelte, Solid, atau Angular tidak ada padanan yang bisa dipakai.',
        vi: 'markdown-to-jsx chỉ kết xuất React, còn marked trả về một chuỗi HTML. Với Vue, Svelte, Solid hay Angular thì không có lựa chọn tương đương nào.',
        uk: 'markdown-to-jsx рендерить лише React, а marked віддає рядок HTML. Для Vue, Svelte, Solid чи Angular просто немає рівноцінного варіанта.',
      }),
      frontmatter: t({
        en: 'None of them hands you typed frontmatter: you stack a content layer on top, or parse the metadata yourself.',
        'en-GB':
          'None of them hands you typed frontmatter: you stack a content layer on top, or parse the metadata yourself.',
        fr: 'Aucun ne vous donne un frontmatter typé : vous empilez une couche de contenu par-dessus, ou vous analysez les métadonnées vous-même.',
        es: 'Ninguno te da un frontmatter tipado: apilas una capa de contenido encima o analizas los metadatos tú mismo.',
        de: 'Keines davon liefert Ihnen typisiertes Frontmatter: Sie setzen eine Content-Schicht obendrauf oder parsen die Metadaten selbst.',
        ru: 'Ни один из них не даёт типизированный frontmatter: вы надстраиваете слой контента или разбираете метаданные сами.',
        ja: 'いずれも型付きのフロントマターは渡してくれません。コンテンツレイヤーを重ねるか、自分でメタデータを解析することになります。',
        ko: '어느 것도 타입이 지정된 프론트매터를 주지 않습니다. 콘텐츠 레이어를 얹거나 메타데이터를 직접 파싱해야 합니다.',
        zh: '它们都不会给你带类型的 frontmatter：你要么再叠一层内容层，要么自己解析元数据。',
        ar: 'لا يمنحك أيٌّ منها frontmatter مُنمَّطاً: إما أن تضيف طبقة محتوى فوقه، أو تحلل البيانات الوصفية بنفسك.',
        it: 'Nessuno di essi ti dà un frontmatter tipizzato: o impili un content layer sopra, o analizzi i metadati da solo.',
        pt: 'Nenhum deles entrega um frontmatter tipado: você empilha uma camada de conteúdo por cima ou analisa os metadados por conta própria.',
        hi: 'इनमें से कोई भी टाइप्ड frontmatter नहीं देता: या तो आप ऊपर एक कंटेंट लेयर चढ़ाते हैं, या मेटाडेटा खुद पार्स करते हैं।',
        tr: 'Hiçbiri size tipli frontmatter vermez: ya üstüne bir içerik katmanı eklersiniz ya da meta verileri kendiniz ayrıştırırsınız.',
        pl: 'Żaden z nich nie daje typowanego frontmattera: albo dokładasz warstwę treści, albo sam parsujesz metadane.',
        id: 'Tak satu pun memberi Anda frontmatter bertipe: Anda menumpuk content layer di atasnya, atau mengurai metadatanya sendiri.',
        vi: 'Không cái nào trao cho bạn frontmatter có kiểu: bạn phải chồng thêm một content layer, hoặc tự phân tích siêu dữ liệu.',
        uk: 'Жоден із них не дає типізованого frontmatter: ви або надбудовуєте шар контенту, або розбираєте метадані самотужки.',
      }),
    },
  },
} satisfies Dictionary;

export default comparisonSectionContent;
