import { type Dictionary, t } from 'intlayer';

const finalCtaSectionContent = {
  key: 'final-cta-section-markdown',
  title: 'Markdown Landing Final CTA Section',
  description:
    'Closing call-to-action of the Markdown landing page, pointing to the Markdown documentation.',
  content: {
    finalCtaTitle: t({
      en: 'Stop choosing a Markdown renderer',
      'en-GB': 'Stop choosing a Markdown renderer',
      fr: 'Arrêtez de choisir un moteur Markdown',
      es: 'Deja de elegir un renderizador de Markdown',
      de: 'Hören Sie auf, einen Markdown-Renderer auszuwählen',
      ru: 'Перестаньте выбирать рендерер Markdown',
      ja: 'Markdownレンダラー選びは終わりにしましょう',
      ko: 'Markdown 렌더러 고르는 일은 그만',
      zh: '不用再挑 Markdown 渲染器了',
      ar: 'كفى اختياراً لمحرك عرض Markdown',
      it: 'Smetti di scegliere un renderer Markdown',
      pt: 'Pare de escolher um renderizador de Markdown',
      hi: 'Markdown रेंडरर चुनना बंद करें',
      tr: 'Markdown renderer seçmeyi bırakın',
      pl: 'Przestań wybierać renderer Markdown',
      id: 'Berhenti memilih renderer Markdown',
      vi: 'Ngừng chọn trình kết xuất Markdown',
      uk: 'Припиніть обирати рендерер Markdown',
    }),
    finalCtaDescription: t({
      en: 'It is already in Intlayer: dependency free, MDX capable, SSR ready, typed end to end, and gone from your bundle when you do not use it.',
      'en-GB':
        'It is already in Intlayer: dependency free, MDX capable, SSR ready, typed end to end, and gone from your bundle when you do not use it.',
      fr: "Il est déjà dans Intlayer : sans dépendance, compatible MDX, prêt pour le SSR, typé de bout en bout, et absent de votre bundle si vous ne l'utilisez pas.",
      es: 'Ya está en Intlayer: sin dependencias, con MDX, listo para SSR, tipado de extremo a extremo y fuera de tu bundle si no lo usas.',
      de: 'Er steckt schon in Intlayer: ohne Abhängigkeiten, MDX-fähig, SSR-bereit, durchgehend typisiert — und aus Ihrem Bundle verschwunden, wenn Sie ihn nicht nutzen.',
      ru: 'Он уже в Intlayer: без зависимостей, с MDX, готов к SSR, типизирован от начала до конца и исчезает из бандла, если не используется.',
      ja: 'すでにIntlayerに入っています。依存関係なし、MDX対応、SSR対応、端から端まで型付き。使わなければバンドルから消えます。',
      ko: '이미 Intlayer 안에 있습니다. 의존성 없이 MDX를 지원하고 SSR에 대비되어 있으며 처음부터 끝까지 타입이 지정되고, 쓰지 않으면 번들에서 사라집니다.',
      zh: '它已经在 Intlayer 里了：零依赖、支持 MDX、面向 SSR、端到端类型化，不用时还会从打包结果中消失。',
      ar: 'إنه موجود في Intlayer أصلاً: بلا تبعيات، يدعم MDX، جاهز لـ SSR، مُنمَّط من الطرف إلى الطرف، ويختفي من حزمتك إن لم تستخدمه.',
      it: 'È già in Intlayer: senza dipendenze, compatibile MDX, pronto per l’SSR, tipizzato end to end e assente dal bundle se non lo usi.',
      pt: 'Ele já está no Intlayer: sem dependências, com MDX, pronto para SSR, tipado de ponta a ponta e fora do seu bundle quando você não usa.',
      hi: 'यह पहले से Intlayer में है: बिना निर्भरता, MDX सक्षम, SSR के लिए तैयार, आद्योपांत टाइप्ड, और इस्तेमाल न होने पर बंडल से गायब।',
      tr: "Zaten Intlayer'ın içinde: bağımlılıksız, MDX destekli, SSR'a hazır, uçtan uca tipli ve kullanmadığınızda paketinizden kayboluyor.",
      pl: 'Jest już w Intlayerze: bez zależności, z MDX, gotowy na SSR, typowany od początku do końca i znikający z bundla, gdy go nie używasz.',
      id: 'Sudah ada di dalam Intlayer: tanpa dependensi, mendukung MDX, siap SSR, bertipe menyeluruh, dan hilang dari bundel saat tidak dipakai.',
      vi: 'Nó đã có sẵn trong Intlayer: không phụ thuộc, hỗ trợ MDX, sẵn sàng SSR, có kiểu từ đầu đến cuối và biến mất khỏi bundle khi bạn không dùng.',
      uk: 'Він уже в Intlayer: без залежностей, із MDX, готовий до SSR, типізований наскрізно й зникає з бандла, якщо ви його не використовуєте.',
    }),
    finalCtaButton: t({
      en: 'Read the Markdown guide',
      'en-GB': 'Read the Markdown guide',
      fr: 'Lire le guide Markdown',
      es: 'Leer la guía de Markdown',
      de: 'Markdown-Leitfaden lesen',
      ru: 'Читать руководство по Markdown',
      ja: 'Markdownガイドを読む',
      ko: 'Markdown 가이드 읽기',
      zh: '阅读 Markdown 指南',
      ar: 'اقرأ دليل Markdown',
      it: 'Leggi la guida Markdown',
      pt: 'Ler o guia de Markdown',
      hi: 'Markdown गाइड पढ़ें',
      tr: 'Markdown kılavuzunu oku',
      pl: 'Przeczytaj przewodnik po Markdown',
      id: 'Baca panduan Markdown',
      vi: 'Đọc hướng dẫn Markdown',
      uk: 'Читати посібник з Markdown',
    }),
  },
} satisfies Dictionary;

export default finalCtaSectionContent;
