import { type Dictionary, t } from 'intlayer';

const frameworksSectionContent = {
  key: 'frameworks-section-markdown',
  title: 'Markdown Landing Frameworks Section',
  description:
    'Cross-framework section of the Markdown landing page: the same Markdown node renders as JSX, a VNode or an HTML string depending on the framework.',
  content: {
    title: t({
      en: 'The same node, in every framework',
      'en-GB': 'The same node, in every framework',
      fr: 'Le même nœud, dans chaque framework',
      es: 'El mismo nodo, en todos los frameworks',
      de: 'Derselbe Node, in jedem Framework',
      ru: 'Один и тот же узел в каждом фреймворке',
      ja: '同じノードを、あらゆるフレームワークで',
      ko: '같은 노드를 모든 프레임워크에서',
      zh: '同一个节点，适用于每个框架',
      ar: 'العقدة نفسها في كل إطار عمل',
      it: 'Lo stesso nodo, in ogni framework',
      pt: 'O mesmo nó, em todos os frameworks',
      hi: 'वही नोड, हर फ्रेमवर्क में',
      tr: 'Aynı düğüm, her frameworkte',
      pl: 'Ten sam węzeł w każdym frameworku',
      id: 'Node yang sama, di setiap framework',
      vi: 'Cùng một node, trong mọi framework',
      uk: 'Той самий вузол у кожному фреймворку',
    }),
    description: t({
      en: 'A Markdown node is turned into the native output of the framework it lands in — JSX, a VNode, or an HTML string. Svelte, Solid and Angular are first-class, not afterthoughts.',
      'en-GB':
        'A Markdown node is turned into the native output of the framework it lands in — JSX, a VNode, or an HTML string. Svelte, Solid and Angular are first-class, not afterthoughts.',
      fr: "Un nœud Markdown devient la sortie native du framework qui l'accueille : JSX, VNode ou chaîne HTML. Svelte, Solid et Angular sont traités comme des cibles de premier plan, pas comme des ajouts tardifs.",
      es: 'Un nodo Markdown se convierte en la salida nativa del framework en el que aterriza: JSX, un VNode o una cadena HTML. Svelte, Solid y Angular son ciudadanos de primera clase, no añadidos tardíos.',
      de: 'Ein Markdown-Node wird in die native Ausgabe des jeweiligen Frameworks überführt — JSX, ein VNode oder ein HTML-String. Svelte, Solid und Angular sind vollwertig unterstützt, kein Nachgedanke.',
      ru: 'Узел Markdown превращается в нативный вывод того фреймворка, в котором оказался: JSX, VNode или строку HTML. Svelte, Solid и Angular поддержаны полноценно, а не по остаточному принципу.',
      ja: 'Markdownノードは、置かれたフレームワークのネイティブな出力（JSX、VNode、HTML文字列）に変換されます。Svelte、Solid、Angularも後付けではなく一級市民です。',
      ko: 'Markdown 노드는 놓인 프레임워크의 네이티브 출력, 즉 JSX나 VNode 또는 HTML 문자열로 변환됩니다. Svelte, Solid, Angular도 뒤늦은 추가가 아니라 일급 대상입니다.',
      zh: 'Markdown 节点会转换成所在框架的原生输出——JSX、VNode 或 HTML 字符串。Svelte、Solid 和 Angular 都是一等公民，而非事后补丁。',
      ar: 'تتحول عقدة Markdown إلى المخرجات الأصلية للإطار الذي تعمل فيه: JSX أو VNode أو سلسلة HTML. وSvelte وSolid وAngular مدعومة بالدرجة الأولى لا كإضافات لاحقة.',
      it: 'Un nodo Markdown diventa l’output nativo del framework in cui si trova: JSX, un VNode o una stringa HTML. Svelte, Solid e Angular sono di prima classe, non ripensamenti.',
      pt: 'Um nó Markdown vira a saída nativa do framework em que está — JSX, um VNode ou uma string HTML. Svelte, Solid e Angular são de primeira classe, não remendos.',
      hi: 'Markdown नोड उस फ्रेमवर्क के नेटिव आउटपुट में बदल जाता है जहाँ वह चलता है — JSX, VNode या HTML स्ट्रिंग। Svelte, Solid और Angular पहली श्रेणी में हैं, बाद की सोच नहीं।',
      tr: 'Bir Markdown düğümü, bulunduğu frameworkün doğal çıktısına dönüşür: JSX, VNode ya da HTML dizesi. Svelte, Solid ve Angular sonradan eklenmiş değil, birinci sınıf hedeflerdir.',
      pl: 'Węzeł Markdown zamienia się w natywne wyjście frameworka, w którym się znajduje — JSX, VNode albo ciąg HTML. Svelte, Solid i Angular są pełnoprawne, a nie doklejone na końcu.',
      id: 'Node Markdown diubah menjadi keluaran native framework tempatnya berada — JSX, VNode, atau string HTML. Svelte, Solid, dan Angular adalah warga kelas satu, bukan tambahan belakangan.',
      vi: 'Một node Markdown được chuyển thành đầu ra native của framework nơi nó chạy — JSX, VNode hay chuỗi HTML. Svelte, Solid và Angular là công dân hạng nhất, không phải phần thêm vào sau.',
      uk: 'Вузол Markdown перетворюється на нативний вивід того фреймворка, в якому опинився: JSX, VNode або рядок HTML. Svelte, Solid і Angular підтримані повноцінно, а не як додаток.',
    }),
    outputLabel: t({
      en: 'Renders as',
      'en-GB': 'Renders as',
      fr: 'Rendu en',
      es: 'Se renderiza como',
      de: 'Rendert als',
      ru: 'Рендерится как',
      ja: '出力形式',
      ko: '렌더링 형태',
      zh: '渲染为',
      ar: 'يُعرض بصيغة',
      it: 'Renderizza come',
      pt: 'Renderiza como',
      hi: 'इस रूप में रेंडर',
      tr: 'Şu olarak işlenir',
      pl: 'Renderuje jako',
      id: 'Dirender sebagai',
      vi: 'Kết xuất thành',
      uk: 'Рендериться як',
    }),
  },
} satisfies Dictionary;

export default frameworksSectionContent;
