import { type Dictionary, t } from 'intlayer';

const heroSectionContent = {
  key: 'hero-section-markdown',
  title: 'Markdown Landing Hero Section',
  description:
    'Hero section content for the Markdown landing page, including the pills, headline, description, both call-to-actions, and the code preview card.',
  content: {
    pills: {
      zeroDependency: t({
        en: 'Zero dependency',
        'en-GB': 'Zero dependency',
        fr: 'Zéro dépendance',
        es: 'Cero dependencias',
        de: 'Keine Abhängigkeiten',
        ru: 'Без зависимостей',
        ja: '依存関係ゼロ',
        ko: '의존성 제로',
        zh: '零依赖',
        ar: 'بدون تبعيات',
        it: 'Zero dipendenze',
        pt: 'Zero dependências',
        hi: 'शून्य निर्भरता',
        tr: 'Sıfır bağımlılık',
        pl: 'Zero zależności',
        id: 'Tanpa dependensi',
        vi: 'Không phụ thuộc',
        uk: 'Без залежностей',
      }),
      mdx: t({
        en: 'MDX ready',
        'en-GB': 'MDX ready',
        fr: 'Compatible MDX',
        es: 'Compatible con MDX',
        de: 'MDX-fähig',
        ru: 'Поддержка MDX',
        ja: 'MDX対応',
        ko: 'MDX 지원',
        zh: '支持 MDX',
        ar: 'جاهز لـ MDX',
        it: 'Pronto per MDX',
        pt: 'Pronto para MDX',
        hi: 'MDX समर्थित',
        tr: 'MDX hazır',
        pl: 'Gotowe na MDX',
        id: 'Siap MDX',
        vi: 'Hỗ trợ MDX',
        uk: 'Підтримка MDX',
      }),
      ssr: t({
        en: 'Built for SSR',
        'en-GB': 'Built for SSR',
        fr: 'Conçu pour le SSR',
        es: 'Diseñado para SSR',
        de: 'Für SSR gebaut',
        ru: 'Создан для SSR',
        ja: 'SSR向け設計',
        ko: 'SSR를 위한 설계',
        zh: '为 SSR 而生',
        ar: 'مصمم لـ SSR',
        it: 'Pensato per SSR',
        pt: 'Feito para SSR',
        hi: 'SSR के लिए निर्मित',
        tr: 'SSR için tasarlandı',
        pl: 'Stworzone dla SSR',
        id: 'Dibuat untuk SSR',
        vi: 'Được xây dựng cho SSR',
        uk: 'Створено для SSR',
      }),
      crossFramework: t({
        en: 'Cross-framework',
        'en-GB': 'Cross-framework',
        fr: 'Multi-frameworks',
        es: 'Multiframework',
        de: 'Framework-übergreifend',
        ru: 'Для всех фреймворков',
        ja: 'クロスフレームワーク',
        ko: '크로스 프레임워크',
        zh: '跨框架',
        ar: 'متعدد الأطر',
        it: 'Multi-framework',
        pt: 'Multiframework',
        hi: 'क्रॉस-फ्रेमवर्क',
        tr: 'Çapraz framework',
        pl: 'Wieloframeworkowe',
        id: 'Lintas framework',
        vi: 'Đa framework',
        uk: 'Для різних фреймворків',
      }),
    },
    title: t({
      en: 'Markdown that renders 5× faster.',
      'en-GB': 'Markdown that renders 5× faster.',
      fr: 'Du Markdown rendu 5× plus vite.',
      es: 'Markdown que se renderiza 5× más rápido.',
      de: 'Markdown, das 5× schneller rendert.',
      ru: 'Markdown, который рендерится в 5 раз быстрее.',
      ja: '5倍速く描画されるMarkdown。',
      ko: '5배 더 빠르게 렌더링되는 Markdown.',
      zh: '渲染速度快 5 倍的 Markdown。',
      ar: 'Markdown يُعرض أسرع بـ 5 مرات.',
      it: 'Markdown che renderizza 5× più veloce.',
      pt: 'Markdown que renderiza 5× mais rápido.',
      hi: 'Markdown जो 5× तेज़ रेंडर होता है।',
      tr: '5× daha hızlı işlenen Markdown.',
      pl: 'Markdown renderowany 5× szybciej.',
      id: 'Markdown yang dirender 5× lebih cepat.',
      vi: 'Markdown hiển thị nhanh hơn 5×.',
      uk: 'Markdown, що рендериться в 5 разів швидше.',
    }),
    description: t({
      en: 'Intlayer ships its own Markdown engine. No dependency, MDX included, parsed on the server, and rendered natively in React, Next.js, Vue, Svelte, Solid, Preact and Angular. You never have to pick a renderer again.',
      'en-GB':
        'Intlayer ships its own Markdown engine. No dependency, MDX included, parsed on the server, and rendered natively in React, Next.js, Vue, Svelte, Solid, Preact and Angular. You never have to pick a renderer again.',
      fr: "Intlayer embarque son propre moteur Markdown. Sans dépendance, MDX inclus, analysé côté serveur et rendu nativement dans React, Next.js, Vue, Svelte, Solid, Preact et Angular. Vous n'avez plus jamais à choisir un moteur de rendu.",
      es: 'Intlayer incluye su propio motor Markdown. Sin dependencias, con MDX, analizado en el servidor y renderizado de forma nativa en React, Next.js, Vue, Svelte, Solid, Preact y Angular. Nunca más tendrás que elegir un renderizador.',
      de: 'Intlayer bringt seine eigene Markdown-Engine mit. Ohne Abhängigkeiten, inklusive MDX, auf dem Server geparst und nativ in React, Next.js, Vue, Svelte, Solid, Preact und Angular gerendert. Sie müssen nie wieder einen Renderer auswählen.',
      ru: 'Intlayer поставляется с собственным движком Markdown. Без зависимостей, с MDX, разбор на сервере и нативный рендеринг в React, Next.js, Vue, Svelte, Solid, Preact и Angular. Вам больше не нужно выбирать рендерер.',
      ja: 'IntlayerはMarkdownエンジンを内蔵しています。依存関係なし、MDX対応、サーバー側で解析し、React、Next.js、Vue、Svelte、Solid、Preact、Angularでネイティブに描画します。もうレンダラーを選ぶ必要はありません。',
      ko: 'Intlayer는 자체 Markdown 엔진을 제공합니다. 의존성 없이 MDX를 지원하고, 서버에서 파싱하며, React, Next.js, Vue, Svelte, Solid, Preact, Angular에서 네이티브로 렌더링합니다. 더 이상 렌더러를 고를 필요가 없습니다.',
      zh: 'Intlayer 内置了自己的 Markdown 引擎。零依赖、支持 MDX、在服务端解析，并在 React、Next.js、Vue、Svelte、Solid、Preact 和 Angular 中原生渲染。你再也不用挑选渲染器了。',
      ar: 'يأتي Intlayer بمحرك Markdown خاص به. بدون تبعيات، مع دعم MDX، يُحلَّل على الخادم ويُعرض أصلياً في React وNext.js وVue وSvelte وSolid وPreact وAngular. لن تحتاج إلى اختيار محرك عرض بعد الآن.',
      it: 'Intlayer include il proprio motore Markdown. Nessuna dipendenza, MDX incluso, analizzato sul server e renderizzato nativamente in React, Next.js, Vue, Svelte, Solid, Preact e Angular. Non dovrai più scegliere un renderer.',
      pt: 'O Intlayer traz o seu próprio motor Markdown. Sem dependências, com MDX, analisado no servidor e renderizado nativamente em React, Next.js, Vue, Svelte, Solid, Preact e Angular. Você nunca mais precisa escolher um renderizador.',
      hi: 'Intlayer अपना खुद का Markdown इंजन देता है। कोई निर्भरता नहीं, MDX शामिल, सर्वर पर पार्स और React, Next.js, Vue, Svelte, Solid, Preact तथा Angular में नेटिव रेंडरिंग। अब आपको रेंडरर चुनने की ज़रूरत नहीं।',
      tr: "Intlayer kendi Markdown motorunu içerir. Bağımlılık yok, MDX dahil, sunucuda ayrıştırılır ve React, Next.js, Vue, Svelte, Solid, Preact ile Angular'da doğal olarak işlenir. Artık bir renderer seçmenize gerek yok.",
      pl: 'Intlayer dostarcza własny silnik Markdown. Bez zależności, z MDX, parsowany na serwerze i renderowany natywnie w React, Next.js, Vue, Svelte, Solid, Preact i Angular. Nigdy więcej nie musisz wybierać renderera.',
      id: 'Intlayer hadir dengan mesin Markdown-nya sendiri. Tanpa dependensi, mendukung MDX, diurai di server, dan dirender secara native di React, Next.js, Vue, Svelte, Solid, Preact, dan Angular. Anda tidak perlu lagi memilih renderer.',
      vi: 'Intlayer đi kèm bộ máy Markdown riêng. Không phụ thuộc, hỗ trợ MDX, phân tích trên máy chủ và hiển thị native trong React, Next.js, Vue, Svelte, Solid, Preact và Angular. Bạn không còn phải chọn trình kết xuất nữa.',
      uk: 'Intlayer постачається з власним рушієм Markdown. Без залежностей, із MDX, розбір на сервері та нативний рендеринг у React, Next.js, Vue, Svelte, Solid, Preact і Angular. Вам більше не потрібно обирати рендерер.',
    }),
    readTheDocs: t({
      en: 'Read the documentation',
      'en-GB': 'Read the documentation',
      fr: 'Lire la documentation',
      es: 'Leer la documentación',
      de: 'Dokumentation lesen',
      ru: 'Читать документацию',
      ja: 'ドキュメントを読む',
      ko: '문서 읽기',
      zh: '阅读文档',
      ar: 'اقرأ الوثائق',
      it: 'Leggi la documentazione',
      pt: 'Ler a documentação',
      hi: 'दस्तावेज़ पढ़ें',
      tr: 'Belgeleri oku',
      pl: 'Przeczytaj dokumentację',
      id: 'Baca dokumentasi',
      vi: 'Đọc tài liệu',
      uk: 'Читати документацію',
    }),
    seeBenchmark: t({
      en: 'See the numbers',
      'en-GB': 'See the numbers',
      fr: 'Voir les chiffres',
      es: 'Ver las cifras',
      de: 'Zahlen ansehen',
      ru: 'Посмотреть цифры',
      ja: '数値を見る',
      ko: '수치 보기',
      zh: '查看数据',
      ar: 'اطّلع على الأرقام',
      it: 'Vedi i numeri',
      pt: 'Ver os números',
      hi: 'आँकड़े देखें',
      tr: 'Rakamları gör',
      pl: 'Zobacz liczby',
      id: 'Lihat angkanya',
      vi: 'Xem các con số',
      uk: 'Переглянути цифри',
    }),
    card: {
      switchSelector: {
        multilingual: t({
          en: 'Multilingual',
          'en-GB': 'Multilingual',
          fr: 'Multilingue',
          es: 'Multilingüe',
          de: 'Mehrsprachig',
          ru: 'Многоязычный',
          ja: '多言語',
          ko: '다국어',
          zh: '多语言',
          ar: 'متعدد اللغات',
          it: 'Multilingue',
          pt: 'Multilíngue',
          hi: 'बहुभाषी',
          tr: 'Çok dilli',
          pl: 'Wielojęzyczny',
          id: 'Multibahasa',
          vi: 'Đa ngôn ngữ',
          uk: 'Багатомовний',
        }),
        monolingual: t({
          en: 'Monolingual',
          'en-GB': 'Monolingual',
          fr: 'Monolingue',
          es: 'Monolingüe',
          de: 'Einsprachig',
          ru: 'Одноязычный',
          ja: '単一言語',
          ko: '단일 언어',
          zh: '单语言',
          ar: 'أحادي اللغة',
          it: 'Monolingue',
          pt: 'Monolíngue',
          hi: 'एकभाषी',
          tr: 'Tek dilli',
          pl: 'Jednojęzyczny',
          id: 'Monobahasa',
          vi: 'Đơn ngôn ngữ',
          uk: 'Одномовний',
        }),
        contentFile: t({
          en: '.content file',
          'en-GB': '.content file',
          fr: 'Fichier .content',
          es: 'Archivo .content',
          de: '.content-Datei',
          ru: 'Файл .content',
          ja: '.contentファイル',
          ko: '.content 파일',
          zh: '.content 文件',
          ar: 'ملف .content',
          it: 'File .content',
          pt: 'Arquivo .content',
          hi: '.content फ़ाइल',
          tr: '.content dosyası',
          pl: 'Plik .content',
          id: 'Berkas .content',
          vi: 'Tệp .content',
          uk: 'Файл .content',
        }),
      },
      multilingual: {
        codeBlockTitle: 'markdown-file.en.content.md',
        code: `---
key: my-markdown-content
description: My content
locale: en
---

# My content

Here an example of markdown content`,
        description: t({
          en: 'The locale front-matter field defines the locale of the content. It is optional. If not provided, Intlayer will use the default locale, which is also used as fallback locale if no translation is available for a specific locale.',
          'en-GB':
            'The locale front-matter field defines the locale of the content. It is optional. If not provided, Intlayer will use the default locale, which is also used as fallback locale if no translation is available for a specific locale.',
          fr: 'Le champ de front-matter locale définit la langue du contenu. Il est optionnel. S’il n’est pas renseigné, Intlayer utilisera la langue par défaut, également utilisée comme langue de repli si aucune traduction n’est disponible pour une langue spécifique.',
          es: 'El campo de frontmatter locale define el idioma del contenido. Es opcional. Si no se proporciona, Intlayer usará el idioma predeterminado, que también se usa como idioma de reserva si no hay traducción disponible para un idioma específico.',
          de: 'Das Frontmatter-Feld locale definiert das Gebietsschema des Inhalts. Es ist optional. Falls nicht angegeben, verwendet Intlayer das Standard-Gebietsschema, das auch als Fallback dient, falls keine Übersetzung vorhanden ist.',
          ru: 'Поле frontmatter locale определяет локаль контента. Оно необязательно. Если оно не указано, Intlayer использует локаль по умолчанию, которая также служит запасной, если перевод отсутствует.',
          ja: 'front-matterのlocaleフィールドはコンテンツのロケールを定義します。省略可能です。指定しない場合、Intlayerはデフォルトロケールを使用し、翻訳がない場合のフォールバックとしても機能します。',
          ko: 'front-matter의 locale 필드는 콘텐츠의 로캘을 정의합니다. 선택 사항이며, 지정하지 않으면 Intlayer는 기본 로캘을 사용하고 번역이 없을 때의 대체 로캘로도 작동합니다.',
          zh: 'front-matter 中的 locale 字段用于定义内容的语言。它是可选的。若未提供，Intlayer 将使用默认语言，若特定语言没有可用翻译，它也将用作后备语言。',
          ar: 'يحدد حقل frontmatter locale لغة المحتوى. وهو اختياري. إذا لم يُحدد، سيستخدم Intlayer اللغة الافتراضية، والتي تُستخدم أيضاً كلغة احتياطية إذا لم تتوفر ترجمة للغة معينة.',
          it: 'Il campo frontmatter locale definisce la lingua del contenuto. È opzionale. Se non fornito, Intlayer userà la lingua predefinita, usata anche come fallback se non è disponibile una traduzione.',
          pt: 'O campo de frontmatter locale define o idioma do conteúdo. É opcional. Se não for fornecido, o Intlayer usará o idioma padrão, que também é usado como reserva caso não haja tradução disponível.',
          hi: 'front-matter फ़ील्ड locale सामग्री का लोकेल तय करता है। यह वैकल्पिक है। यदि नहीं दिया गया, तो Intlayer डिफ़ॉल्ट लोकेल का उपयोग करेगा, जो अनुवाद न होने पर फ़ॉलबैक भी बनता है।',
          tr: 'front-matter locale alanı içeriğin dilini belirler. İsteğe bağlıdır. Sağlanmazsa Intlayer, belirli bir dil için çeviri bulunmadığında geri dönüş olarak da kullanılan varsayılan dili kullanır.',
          pl: 'Pole frontmatter locale definiuje język treści. Jest opcjonalne. Jeśli nie zostanie podane, Intlayer użyje domyślnego języka, który służy również jako język zapasowy w przypadku braku tłumaczenia.',
          id: 'Bidang front-matter locale menentukan bahasa konten. Bersifat opsional. Jika tidak disediakan, Intlayer akan menggunakan bahasa default, yang juga menjadi fallback jika tidak ada terjemahan.',
          vi: 'Trường front-matter locale xác định ngôn ngữ của nội dung. Trường này là tùy chọn. Nếu không cung cấp, Intlayer sẽ dùng ngôn ngữ mặc định, đồng thời là ngôn ngữ dự phòng nếu chưa có bản dịch.',
          uk: 'Поле frontmatter locale визначає мову вмісту. Воно необов’язкове. Якщо не вказано, Intlayer використає мову за замовчуванням, яка також слугує запасною, якщо переклад відсутній.',
        }),
        fileStructureTitle: t({
          en: 'Example of file structure:',
          'en-GB': 'Example of file structure:',
          fr: 'Exemple d’arborescence :',
          es: 'Ejemplo de estructura de archivos:',
          de: 'Beispiel für Dateistruktur:',
          ru: 'Пример структуры файлов:',
          ja: 'ファイル構造の例：',
          ko: '파일 구조 예시:',
          zh: '文件结构示例：',
          ar: 'مثال على بنية الملفات:',
          it: 'Esempio di struttura file:',
          pt: 'Exemplo de estrutura de arquivos:',
          hi: 'फ़ाइल संरचना का उदाहरण:',
          tr: 'Dosya yapısı örneği:',
          pl: 'Przykład struktury plików:',
          id: 'Contoh struktur berkas:',
          vi: 'Ví dụ về cấu trúc tệp:',
          uk: 'Приклад структури файлів:',
        }),
        fileStructure: `content
├── markdown-file.en.content.md
├── markdown-file.fr.content.md
└── markdown-file.es.content.md`,
      },
      monolingual: {
        codeBlockTitle: 'markdown-file.content.md',
        code: `---
key: my-markdown-content
description: My content
---

# My content

Here an example of markdown content`,
        description: t({
          en: 'When the locale front-matter field is omitted, Intlayer uses your configured default locale. You can maintain your entire content in a single markdown file without locale identifiers.',
          'en-GB':
            'When the locale front-matter field is omitted, Intlayer uses your configured default locale. You can maintain your entire content in a single markdown file without locale identifiers.',
          fr: 'Lorsque le champ de front-matter locale est omis, Intlayer utilise votre langue par défaut configurée. Vous pouvez conserver tout votre contenu dans un fichier markdown unique sans préfixe de langue.',
          es: 'Cuando se omite el campo locale de frontmatter, Intlayer usa el idioma predeterminado configurado. Puedes mantener todo tu contenido en un solo archivo markdown sin prefijos de idioma.',
          de: 'Wird das Frontmatter-Feld locale weggelassen, verwendet Intlayer Ihr konfiguriertes Standard-Gebietsschema. Sie können alle Inhalte in einer einzigen Markdown-Datei ohne Sprachpräfixe verwalten.',
          ru: 'Если поле frontmatter locale опущено, Intlayer использует настроенную локаль по умолчанию. Вы можете хранить контент в одном файле markdown без языковых префиксов.',
          ja: 'front-matterのlocaleフィールドを省略すると、Intlayerは設定されたデフォルトロケールを使用します。言語プレフィックスなしで単一のMarkdownファイルにコンテンツをまとめられます。',
          ko: 'front-matter의 locale 필드를 생략하면 Intlayer는 설정된 기본 로캘을 사용합니다. 언어 접두사 없이 단일 Markdown 파일로 모든 콘텐츠를 유지할 수 있습니다.',
          zh: '当省略 front-matter 中的 locale 字段时，Intlayer 将使用配置的默认语言。无需语言前缀即可在单个 Markdown 文件中管理全部内容。',
          ar: 'عند إغفال حقل frontmatter locale، يستخدم Intlayer لغتك الافتراضية المحددة. يمكنك الاحتفاظ بكافة محتوياتك في ملف markdown واحد دون بادئات لغوية.',
          it: 'Quando il campo frontmatter locale viene omesso, Intlayer usa la lingua predefinita configurata. Puoi mantenere tutti i contenuti in un unico file markdown senza prefissi di lingua.',
          pt: 'Quando o campo de frontmatter locale é omitido, o Intlayer usa o idioma padrão configurado. Você pode manter todo o seu conteúdo em um único arquivo markdown sem prefixos de idioma.',
          hi: 'जब front-matter फ़ील्ड locale छोड़ दिया जाता है, तो Intlayer आपके कॉन्फ़िगर किए गए डिफ़ॉल्ट लोकेल का उपयोग करता है। आप बिना किसी भाषा उपसर्ग के एक ही Markdown फ़ाइल में सामग्री रख सकते हैं।',
          tr: 'front-matter locale alanı atlandığında Intlayer yapılandırılmış varsayılan dilinizi kullanır. Tüm içeriğinizi dil önekleri olmadan tek bir markdown dosyasında tutabilirsiniz.',
          pl: 'Gdy pole frontmatter locale zostanie pominięte, Intlayer użyje skonfigurowanego języka domyślnego. Możesz przechowywać całą treść w jednym pliku markdown bez prefiksów językowych.',
          id: 'Saat bidang front-matter locale dihilangkan, Intlayer menggunakan bahasa default yang Anda konfigurasikan. Anda dapat menyimpan seluruh konten dalam satu berkas markdown tanpa prefiks bahasa.',
          vi: 'Khi bỏ qua trường front-matter locale, Intlayer sẽ sử dụng ngôn ngữ mặc định đã cấu hình. Bạn có thể lưu trữ toàn bộ nội dung trong một tệp markdown duy nhất mà không cần tiền tố ngôn ngữ.',
          uk: 'Якщо поле frontmatter locale пропущено, Intlayer використовує налаштовану мову за замовчуванням. Ви можете зберігати весь вміст в одному файлі markdown без префіксів мови.',
        }),
        fileStructureTitle: t({
          en: 'Example of file structure:',
          'en-GB': 'Example of file structure:',
          fr: 'Exemple d’arborescence :',
          es: 'Ejemplo de estructura de archivos:',
          de: 'Beispiel für Dateistruktur:',
          ru: 'Пример структуры файлов:',
          ja: 'ファイル構造の例：',
          ko: '파일 구조 예시:',
          zh: '文件结构示例：',
          ar: 'مثال على بنية الملفات:',
          it: 'Esempio di struttura file:',
          pt: 'Exemplo de estructura de archivos:',
          hi: 'फ़ाइल संरचना का उदाहरण:',
          tr: 'Dosya yapısı örneği:',
          pl: 'Przykład struktury plików:',
          id: 'Contoh struktur berkas:',
          vi: 'Ví dụ về cấu trúc tệp:',
          uk: 'Приклад структури файлів:',
        }),
        fileStructure: `content
└── markdown-file.content.md`,
      },
      contentFile: {
        codeBlockTitle: 'article.content.ts',
        code: `import { md, file, t, type Dictionary } from 'intlayer';

export default {
  key: 'article',
  content: {
    body: t({
      en: md(file('./article.en.md')),
      fr: md(file('./article.fr.md')),
    }),
  },
} satisfies Dictionary;`,
        description: t({
          en: 'Declare Markdown directly inside a TypeScript, ESM, or JSON dictionary using the md() and file() functions, pairing translations with full type safety.',
          'en-GB':
            'Declare Markdown directly inside a TypeScript, ESM, or JSON dictionary using the md() and file() functions, pairing translations with full type safety.',
          fr: 'Déclarez du Markdown directement dans un dictionnaire TypeScript, ESM ou JSON à l’aide des fonctions md() et file(), pour des traductions typées et flexibles.',
          es: 'Declara Markdown directamente en un diccionario TypeScript, ESM o JSON usando las funciones md() y file(), combinando traducciones con seguridad de tipos.',
          de: 'Deklarieren Sie Markdown direkt in einem TypeScript-, ESM- oder JSON-Wörterbuch mit den Funktionen md() und file(), kombiniert mit vollständiger Typsicherheit.',
          ru: 'Объявляйте Markdown прямо в словаре TypeScript, ESM или JSON с помощью функций md() и file(), сочетая переводы с полной типобезопасностью.',
          ja: 'md()とfile()関数を使ってTypeScript、ESM、またはJSONディクショナリ内でMarkdownを直接宣言し、型安全に翻訳を統合できます。',
          ko: 'md()와 file() 함수를 사용하여 TypeScript, ESM 또는 JSON 딕셔너리 내부에서 Markdown을 직접 선언하고 완벽한 타입 안전성과 함께 번역을 구성할 수 있습니다.',
          zh: '在 TypeScript、ESM 或 JSON 词典中直接使用 md() 和 file() 函数声明 Markdown，兼顾翻译与完整的类型安全性。',
          ar: 'صرّح عن Markdown مباشرة داخل قاموس TypeScript أو ESM أو JSON باستخدام الدالتين md() وfile()، لربط الترجمات بأمان نوعي كامل.',
          it: 'Dichiara Markdown direttamente in un dizionario TypeScript, ESM o JSON tramite le funzioni md() e file(), associando le traduzioni con completa type-safety.',
          pt: 'Declare Markdown diretamente em um dicionário TypeScript, ESM ou JSON usando as funções md() e file(), combinando traduções com total segurança de tipos.',
          hi: 'md() और file() फ़ंक्शन का उपयोग करके TypeScript, ESM या JSON डिक्शनरी में सीधे Markdown घोषित करें और पूर्ण टाइप सुरक्षा के साथ अनुवाद जोड़ें।',
          tr: 'md() ve file() fonksiyonlarını kullanarak doğrudan TypeScript, ESM veya JSON sözlüğü içinde Markdown tanımlayın ve tam tip güvenliğiyle çevirileri eşleştirin.',
          pl: 'Deklaruj Markdown bezpośrednio w słowniku TypeScript, ESM lub JSON za pomocą funkcji md() i file(), łącząc tłumaczenia z pełnym bezpieczeństwem typów.',
          id: 'Deklarasikan Markdown langsung di dalam kamus TypeScript, ESM, atau JSON menggunakan fungsi md() dan file(), menggabungkan terjemahan dengan keamanan tipe penuh.',
          vi: 'Khai báo Markdown trực tiếp trong từ điển TypeScript, ESM hoặc JSON bằng các hàm md() và file(), kết hợp bản dịch với độ an toàn kiểu hoàn chỉnh.',
          uk: 'Оголошуйте Markdown безпосередньо у словнику TypeScript, ESM або JSON за допомогою функцій md() та file(), поєднуючи переклади з повною типобезпекою.',
        }),
        fileStructureTitle: t({
          en: 'Example of file structure:',
          'en-GB': 'Example of file structure:',
          fr: 'Exemple d’arborescence :',
          es: 'Ejemplo de estructura de archivos:',
          de: 'Beispiel für Dateistruktur:',
          ru: 'Пример структуры файлов:',
          ja: 'ファイル構造の例：',
          ko: '파일 구조 예시:',
          zh: '文件结构示例：',
          ar: 'مثال على بنية الملفات:',
          it: 'Esempio di struttura file:',
          pt: 'Exemplo de estructura de archivos:',
          hi: 'फ़ाइल संरचना का उदाहरण:',
          tr: 'Dosya yapısı örneği:',
          pl: 'Przykład struktury plików:',
          id: 'Contoh struktur berkas:',
          vi: 'Ví dụ về cấu trúc tệp:',
          uk: 'Приклад структури файлів:',
        }),
        fileStructure: `content
├── article.content.ts
├── article.en.md
└── article.fr.md`,
      },
      codeBlockTitle: 'markdown-file.en.content.md',
      code: `---
key: my-markdown-content
description: My content
locale: en
---

# My content

Here an example of markdown content`,
      features: {
        zeroDependency: t({
          en: 'No dependency',
          'en-GB': 'No dependency',
          fr: 'Aucune dépendance',
          es: 'Sin dependencias',
          de: 'Keine Abhängigkeit',
          ru: 'Без зависимостей',
          ja: '依存関係なし',
          ko: '의존성 없음',
          zh: '无依赖',
          ar: 'بدون تبعيات',
          it: 'Nessuna dipendenza',
          pt: 'Sem dependências',
          hi: 'कोई निर्भरता नहीं',
          tr: 'Bağımlılık yok',
          pl: 'Bez zależności',
          id: 'Tanpa dependensi',
          vi: 'Không phụ thuộc',
          uk: 'Без залежностей',
        }),
        mdxComponents: t({
          en: 'MDX components',
          'en-GB': 'MDX components',
          fr: 'Composants MDX',
          es: 'Componentes MDX',
          de: 'MDX-Komponenten',
          ru: 'MDX-компоненты',
          ja: 'MDXコンポーネント',
          ko: 'MDX 컴포넌트',
          zh: 'MDX 组件',
          ar: 'مكوّنات MDX',
          it: 'Componenti MDX',
          pt: 'Componentes MDX',
          hi: 'MDX कंपोनेंट',
          tr: 'MDX bileşenleri',
          pl: 'Komponenty MDX',
          id: 'Komponen MDX',
          vi: 'Thành phần MDX',
          uk: 'MDX-компоненти',
        }),
        typedFrontmatter: t({
          en: 'Typed frontmatter',
          'en-GB': 'Typed frontmatter',
          fr: 'Frontmatter typé',
          es: 'Frontmatter tipado',
          de: 'Typisiertes Frontmatter',
          ru: 'Типизированный frontmatter',
          ja: '型付きフロントマター',
          ko: '타입이 지정된 프론트매터',
          zh: '带类型的 frontmatter',
          ar: 'frontmatter مُنمَّط',
          it: 'Frontmatter tipizzato',
          pt: 'Frontmatter tipado',
          hi: 'टाइप्ड frontmatter',
          tr: 'Tip güvenli frontmatter',
          pl: 'Typowany frontmatter',
          id: 'Frontmatter bertipe',
          vi: 'Frontmatter có kiểu',
          uk: 'Типізований frontmatter',
        }),
        treeShaken: t({
          en: 'Purged when unused',
          'en-GB': 'Purged when unused',
          fr: 'Purgé si inutilisé',
          es: 'Eliminado si no se usa',
          de: 'Entfernt, wenn ungenutzt',
          ru: 'Удаляется, если не используется',
          ja: '未使用なら削除',
          ko: '미사용 시 제거',
          zh: '未使用时被移除',
          ar: 'يُزال عند عدم الاستخدام',
          it: 'Rimosso se non usato',
          pt: 'Removido se não usado',
          hi: 'अप्रयुक्त होने पर हटाया गया',
          tr: 'Kullanılmazsa kaldırılır',
          pl: 'Usuwany, gdy nieużywany',
          id: 'Dihapus jika tidak dipakai',
          vi: 'Loại bỏ khi không dùng',
          uk: 'Вилучається, якщо не використовується',
        }),
      },
    },
  },
} satisfies Dictionary;

export default heroSectionContent;
