import { type Dictionary, t } from 'intlayer';

const translateDashboardContent = {
  key: 'translate-dashboard',
  content: {
    searchPlaceholder: t({
      ar: 'قاموس 검색',
      de: 'Wörterbuch suchen',
      en: 'Search for a dictionary',
      'en-GB': 'Search for a dictionary',
      es: 'Buscar un diccionario',
      fr: 'Rechercher un dictionnaire',
      hi: 'शब्दकोश खोजें',
      it: 'Cerca un dizionario',
      ja: '辞書を検索',
      ko: '사전 검색',
      pt: 'Pesquisar um dicionário',
      ru: 'Найти словарь',
      tr: 'Sözlük arama',
      zh: '搜索字典',
      pl: 'Wyszukaj słownik',
      id: 'Cari kamus',
      vi: 'Tìm kiếm từ điển',
      uk: 'Шукати словник',
    }),

    noDictionaries: t({
      en: 'No dictionaries found',
      fr: 'Aucun dictionnaire trouvé',
      es: 'No se encontraron diccionarios',
      'en-GB': 'No dictionaries found',
      de: 'Keine Wörterbücher gefunden',
      ja: '辞書が見つかりませんでした',
      ko: '사전을 찾을 수 없습니다',
      zh: '未找到字典',
      it: 'Nessun dizionario trovato',
      pt: 'Nenhum dicionário encontrado',
      hi: 'कोई शब्दकोश नहीं मिला',
      ar: 'لم يتم العثور على قواميس',
      ru: 'Словари не найдены',
      tr: 'Sözlük bulunamadı',
      pl: 'Nie znaleziono słowników',
      id: 'Tidak ada kamus yang ditemukan',
      vi: 'Không tìm thấy từ điển',
      uk: 'Словників не знайдено',
    }),

    scrollToTop: t({
      en: 'Scroll to top',
      fr: 'Faire défiler vers le haut',
      es: 'Desplazar hacia arriba',
      'en-GB': 'Scroll to top',
      de: 'Nach oben scrollen',
      ar: 'التمرير للأعلى',
      hi: 'स्क्रॉल करें ऊपर',
      it: "Scorri verso l'alto",
      ja: '上にスクロール',
      ko: '위로 스크롤',
      pt: 'Deslocar para cima',
      ru: 'Прокрутить вверх',
      tr: 'Yukarı kaydır',
      zh: '向上滚动',
      pl: 'Przewiń w górę',
      id: 'Scroll ke atas',
      vi: 'Cuộn lên trên',
      uk: 'Прокрутити вгору',
    }),
  },
  tags: ['dashboard', 'translate', 'dictionary'],
} satisfies Dictionary;

export default translateDashboardContent;
