import { type Dictionary, enu, insert, t } from 'intlayer';

const translateDashboardContent = {
  key: 'translate-dashboard',
  content: {
    searchPlaceholder: t({
      ar: 'قاموس 검색',
      de: 'Wörterbuch suchen',
      en: 'Search for a dictionary',
      'en-GB': 'Search for a dictionary',
      es: 'Buscar un diccionario',
      fr: 'Rechercher un dictionnaire',
      hi: 'शब्दकोश खोजें',
      it: 'Cerca un dizionario',
      ja: '辞書を検索',
      ko: '사전 검색',
      pt: 'Pesquisar um dicionário',
      ru: 'Найти словарь',
      tr: 'Sözlük arama',
      zh: '搜索字典',
      pl: 'Wyszukaj słownik',
      id: 'Cari kamus',
      vi: 'Tìm kiếm từ điển',
      uk: 'Шукати словник',
    }),

    noDictionaries: t({
      en: 'No dictionaries found',
      fr: 'Aucun dictionnaire trouvé',
      es: 'No se encontraron diccionarios',
      'en-GB': 'No dictionaries found',
      de: 'Keine Wörterbücher gefunden',
      ja: '辞書が見つかりませんでした',
      ko: '사전을 찾을 수 없습니다',
      zh: '未找到字典',
      it: 'Nessun dizionario trovato',
      pt: 'Nenhum dicionário encontrado',
      hi: 'कोई शब्दकोश नहीं मिला',
      ar: 'لم يتم العثور على قواميس',
      ru: 'Словари не найдены',
      tr: 'Sözlük bulunamadı',
      pl: 'Nie znaleziono słowników',
      id: 'Tidak ada kamus yang ditemukan',
      vi: 'Không tìm thấy từ điển',
      uk: 'Словників не знайдено',
    }),

    scrollToTop: t({
      en: 'Scroll to top',
      fr: 'Faire défiler vers le haut',
      es: 'Desplazar hacia arriba',
      'en-GB': 'Scroll to top',
      de: 'Nach oben scrollen',
      ar: 'التمرير للأعلى',
      hi: 'स्क्रॉल करें ऊपर',
      it: "Scorri verso l'alto",
      ja: '上にスクロール',
      ko: '위로 스크롤',
      pt: 'Deslocar para cima',
      ru: 'Прокрутить вверх',
      tr: 'Yukarı kaydır',
      zh: '向上滚动',
      pl: 'Przewiń w górę',
      id: 'Scroll ke atas',
      vi: 'Cuộn lên trên',
      uk: 'Прокрутити вгору',
    }),

    addTranslation: t({
      en: 'Add a translation',
      fr: 'Ajouter une traduction',
      es: 'Añadir una traducción',
      'en-GB': 'Add a translation',
      de: 'Übersetzung hinzufügen',
      ar: 'إضافة ترجمة',
      hi: 'अनुवाद जोड़ें',
      it: 'Aggiungi una traduzione',
      ja: '翻訳を追加',
      ko: '번역 추가',
      pt: 'Adicionar uma tradução',
      ru: 'Добавить перевод',
      tr: 'Çeviri ekle',
      zh: '添加翻译',
      pl: 'Dodaj tłumaczenie',
      id: 'Tambah terjemahan',
      vi: 'Thêm bản dịch',
      uk: 'Додати переклад',
    }),

    saveAllButton: {
      text: t({
        en: 'Save all',
        'en-GB': 'Save all',
        fr: 'Tout enregistrer',
        es: 'Guardar todo',
        ar: 'حفظ الكل',
        de: 'Alles speichern',
        hi: 'सभी सहेजें',
        it: 'Salva tutto',
        ja: 'すべて保存',
        ko: '모두 저장',
        pt: 'Salvar tudo',
        ru: 'Сохранить все',
        tr: 'Hepsini kaydet',
        zh: '全部保存',
        pl: 'Zapisz wszystko',
        id: 'Simpan semua',
        vi: 'Lưu tất cả',
        uk: 'Зберегти все',
      }),
      label: {
        value: t({
          en: 'Save all dictionaries',
          'en-GB': 'Save all dictionaries',
          fr: 'Enregistrer tous les dictionnaires',
          es: 'Guardar todos los diccionarios',
          ar: 'حفظ جميع القواميس',
          de: 'Alle Wörterbücher speichern',
          hi: 'सभी शब्दकोश सहेजें',
          it: 'Salva tutti i dizionari',
          ja: 'すべての辞書を保存',
          ko: '모든 사전 저장',
          pt: 'Salvar todos os dicionários',
          ru: 'Сохранить все словари',
          tr: 'Tüm sözlükleri kaydet',
          zh: '保存所有词典',
          pl: 'Zapisz wszystkie słowniki',
          id: 'Simpan semua kamus',
          vi: 'Lưu tất cả từ điển',
          uk: 'Зберегти всі словники',
        }),
      },
    },

    restoreAllButton: {
      text: t({
        en: 'Restore all',
        'en-GB': 'Restore all',
        fr: 'Tout restaurer',
        es: 'Restaurar todo',
        ar: 'استعادة الكل',
        de: 'Alles wiederherstellen',
        hi: 'सभी पुनर्स्थापित करें',
        it: 'Ripristina tutto',
        ja: 'すべて復元',
        ko: '모두 복원',
        pt: 'Restaurar tudo',
        ru: 'Восстановить все',
        tr: 'Hepsini geri yükle',
        zh: '全部恢复',
        pl: 'Przywróć wszystko',
        id: 'Pulihkan semua',
        vi: 'Khôi phục tất cả',
        uk: 'Відновити все',
      }),
      label: {
        value: t({
          en: 'Restore all dictionaries',
          'en-GB': 'Restore all dictionaries',
          fr: 'Restaurer tous les dictionnaires',
          es: 'Restaurar todos los diccionarios',
          ar: 'استعادة جميع القواميس',
          de: 'Alle Wörterbücher wiederherstellen',
          hi: 'सभी शब्दकोश पुनर्स्थापित करें',
          it: 'Ripristina tutti i dizionari',
          ja: 'すべての辞書を復元',
          ko: '모든 사전 복원',
          pt: 'Restaurar todos os dicionários',
          ru: 'Восстановить все словари',
          tr: 'Tüm sözlükleri geri yükle',
          zh: '恢复所有词典',
          pl: 'Przywróć wszystkie słowniki',
          id: 'Pulihkan semua kamus',
          vi: 'Khôi phục tất cả từ điển',
          uk: 'Відновити всі словники',
        }),
      },
    },

    saveDictionaryButton: {
      label: {
        value: t({
          en: 'Save dictionary',
          'en-GB': 'Save dictionary',
          fr: 'Enregistrer le dictionnaire',
          es: 'Guardar diccionario',
          ar: 'حفظ القاموس',
          de: 'Wörterbuch speichern',
          hi: 'शब्दकोश सहेजें',
          it: 'Salva dizionario',
          ja: '辞書を保存',
          ko: '사전 저장',
          pt: 'Salvar dicionário',
          ru: 'Сохранить словарь',
          tr: 'Sözlüğü kaydet',
          zh: '保存词典',
          pl: 'Zapisz słownik',
          id: 'Simpan kamus',
          vi: 'Lưu từ điển',
          uk: 'Зберегти словник',
        }),
      },
    },

    restoreDictionaryButton: {
      label: {
        value: t({
          en: 'Restore dictionary',
          'en-GB': 'Restore dictionary',
          fr: 'Restaurer le dictionnaire',
          es: 'Restaurar diccionario',
          ar: 'استعادة القاموس',
          de: 'Wörterbuch wiederherstellen',
          hi: 'शब्दकोश पुनर्स्थापित करें',
          it: 'Ripristina dizionario',
          ja: '辞書の復元',
          ko: '사전 복원',
          pt: 'Restaurar dicionário',
          ru: 'Восстановить словарь',
          tr: 'Sözlüğü geri yükle',
          zh: '恢复词典',
          pl: 'Przywróć słownik',
          id: 'Pulihkan kamus',
          vi: 'Khôi phục từ điển',
          uk: 'Відновити словник',
        }),
      },
    },

    modifiedCount: insert(
      t({
        en: '{{count}} dictionaries modified',
        'en-GB': '{{count}} dictionaries modified',
        fr: '{{count}} dictionnaires modifiés',
        es: '{{count}} diccionarios modificados',
        ar: '{{count}} قواميس معدلة',
        de: '{{count}} geänderte Wörterbücher',
        hi: '{{count}} संशोधित शब्दकोश',
        it: '{{count}} dizionari modificati',
        ja: '{{count}} 個の変更された辞書',
        ko: '{{count}}개의 수정된 사전',
        pt: '{{count}} dicionários modificados',
        ru: '{{count}} измененных словаря',
        tr: '{{count}} değiştirilmiş sözlük',
        zh: '{{count}} 个已修改的词典',
        pl: '{{count}} zmodyfikowanych słowników',
        id: '{{count}} kamus yang dimodifikasi',
        vi: '{{count}} từ điển đã sửa đổi',
        uk: '{{count}} змінених словників',
      })
    ),
  },
  tags: ['dashboard', 'translate', 'dictionary'],
} satisfies Dictionary;

export default translateDashboardContent;
