import { PagesRoutes } from '@/Routes';
import { t, type Dictionary } from 'intlayer';

const actionButtonContent = {
  key: 'landing-section-action-button',
  content: {
    primaryBtn: {
      label: t({
        en: 'Go to getting started documentation',
        'en-GB': 'Go to getting started documentation',
        fr: 'Accéder à la documentation de démarrage',
        es: 'Ir a la documentación de inicio',
        de: 'Gehe zur Einstieg Dokumentation',
        ja: 'はじめに関するドキュメントへ行く',
        ko: '시작 문서로 이동',
        zh: '前往入门文档',
        it: 'Vai alla documentazione per iniziare',
        pt: 'Ir para a documentação de introdução',
        hi: 'प्रारंभिक दस्तावेज़ पर जाएं',
        ar: 'اذهب إلى وثيقة البداية',
        ru: 'Перейти к документации по началу',
        tr: 'Başlarken belgelerine git',
      }),
      content: t({
        en: 'Get Started',
        'en-GB': 'Get Started',
        fr: 'Commencer',
        es: 'Empezar',
        de: 'Loslegen',
        ja: '始める',
        ko: '시작하다',
        zh: '开始',
        it: 'Iniziare',
        pt: 'Começar',
        hi: 'शुरू करें',
        ar: 'ابدأ',
        ru: 'Начать',
        tr: 'Başla',
      }),
      url: PagesRoutes.Doc,
    },
    secondaryBtn: {
      label: t({
        en: 'Go to the interest of intlayer documentation',
        'en-GB': 'Go to the interest of intlayer documentation',
        fr: "Accéder à la documentation sur l'intérêt d'intlayer",
        es: 'Ir a la documentación del interés de intlayer',
        de: 'Gehe zur Interessendokumentation von intlayer',
        ja: 'Intlayerの利点に関するドキュメントへ行く',
        ko: 'intlayer 문서의 이점으로 이동',
        zh: '查看intlayer文档的益处',
        it: "Vai alla documentazione sull'interesse di intlayer",
        pt: 'Ir para a documentação sobre o interesse do intlayer',
        hi: 'intlayer दस्तावेज़ के लाभ पर जाएं',
        ar: 'اذهب إلى وثيقة أهمية intlayer',
        ru: 'Перейти к документации о преимуществах intlayer',
        tr: 'intlayer belgelerinin faydalarına git',
      }),
      content: t({
        en: 'Why Intlayer?',
        'en-GB': 'Why Intlayer?',
        fr: 'Pourquoi Intlayer ?',
        es: '¿Por qué Intlayer?',
        de: 'Warum Intlayer?',
        ja: 'なぜIntlayerか？',
        ko: '왜 Intlayer인가?',
        zh: '为什么选择Intlayer？',
        it: 'Perché Intlayer?',
        pt: 'Por que Intlayer?',
        hi: 'इंटलेयर क्यों?',
        ar: 'لماذا Intlayer؟',
        ru: 'Почему Intlayer?',
        tr: 'Neden Intlayer?',
      }),
      url: PagesRoutes.Doc_Why,
    },
  },
} satisfies Dictionary;

export default actionButtonContent;
