import { t, type Dictionary } from 'intlayer';

const landingSectionContent = {
  key: 'landing-section',
  content: {
    whatsNew: t({
      en: "What's new",
      'en-GB': "What's new",
      fr: 'Quoi de neuf',
      es: 'Novedades',
      de: 'Was gibt es Neues',
      ja: '新着情報',
      ko: '새로운 소식',
      zh: '最新消息',
      it: 'Novità',
      pt: 'Novidades',
      hi: 'नया क्या है',
      ar: 'ما الجديد',
      ru: 'Что нового',
    }),
    version: t({
      en: 'Just shipped  ',
      'en-GB': 'Just shipped  ',
      fr: '  vient de sortir',
      es: 'Recién lanzado  ',
      de: 'Gerade   veröffentlicht',
      ja: ' をリリースしました',
      ko: '  출시',
      zh: '刚刚发布  ',
      it: 'Appena rilasciato  ',
      pt: 'Acabamos de lançar a  ',
      hi: 'अभी   शिप किया गया',
      ar: 'تم شحن   للتو',
      ru: 'Только что выпустили  ',
    }),
    title: t({
      en: 'Per-Component i18n - Speed up your development process',
      'en-GB': 'Per-Component i18n - Speed up your development process',
      fr: 'i18n par composant - Accélérez votre processus de développement',
      es: 'i18n por componente - Acelera tu proceso de desarrollo',
      de: 'i18n pro Komponente - Beschleunigen Sie Ihr Entwicklungsprozess',
      ja: 'コンポーネントごとのi18n - 開発プロセスを加速',
      ko: '컴포넌트별 i18n - 개발 프로세스 가속화',
      zh: '组件级i18n - 加速开发过程',
      it: 'i18n per componente - Accelera il tuo processo di sviluppo',
      pt: 'i18n por componente - Acelera o seu processo de desenvolvimento',
      hi: 'घड़ा को कंपोनेंट आई 18 एन - डेवलपमेंट प्रोसेस को त्वरित करें',
      ar: 'i18n بالمكون - تسريع عملية التطوير',
      ru: 'i18n по компоненту - Ускорение процесса разработки',
    }),
    subheading: t({
      en: 'Type-Safe. Use AI. Edit Visually.',
      'en-GB': 'Type-Safe. Use AI. Edit Visually.',
      fr: "Sécurisé. Utilisez l'IA. Éditez visuellement.",
      es: 'Seguro de tipos. Use IA. Edite visualmente.',
      de: 'Typsicher. KI nutzen. Visuell bearbeiten.',
      ja: '型安全。AIを使用。視覚的に編集。',
      ko: '타입 안전. AI 사용. 시각적 편집.',
      zh: '类型安全。使用AI。可视化编辑。',
      it: "Type-Safe. Usa l'IA. Modifica visivamente.",
      pt: 'Type-Safe. Use IA. Edite visualmente.',
      hi: 'टाइप-सेफ। AI का उपयोग करें। विजुअली एडिट करें।',
      ar: 'آمن الأنواع. استخدم الذكاء الاصطناعي. حرر بصريًا.',
      ru: 'Типобезопасный. Используйте ИИ. Редактируйте визуально.',
    }),
    description: t({
      en: 'Intlayer gives SaaS teams an AI-assisted, developer-first workflow for localization and content with zero vendor lock-in. Intlayer is an open source project, any contributor is highly valued',
      'en-GB':
        'Intlayer gives SaaS teams an AI-assisted, developer-first workflow for localization and content with zero vendor lock-in. Intlayer is an open source project, any contributor is highly valued',
      fr: 'Intlayer offre aux équipes SaaS un flux de travail assisté par IA et axé sur les développeurs pour la localisation et le contenu, sans dépendance vis-à-vis d’un fournisseur. Intlayer est un projet open source, et toute contribution est très appréciée.',
      es: 'Intlayer proporciona a los equipos de SaaS un flujo de trabajo de localización y contenido asistido por IA y centrado en el desarrollador, sin dependencia de proveedores. Intlayer es un proyecto de código abierto, y cualquier contribución es muy valorada.',
      de: 'Intlayer bietet SaaS-Teams einen KI-gestützten, entwicklerorientierten Workflow für Lokalisierung und Inhalte ohne Anbieterbindung. Intlayer ist ein Open-Source-Projekt, und jeder Beitrag wird sehr geschätzt.',
      ja: 'Intlayerは、SaaSチームに、ベンダーロックインのない、AI支援の開発者第一のローカリゼーションおよびコンテンツワークフローを提供します。Intlayerはオープンソースプロジェクトであり、どんな貢献者も高く評価されます。',
      ko: 'Intlayer는 SaaS 팀에게 공급업체 종속성이 없는 AI 지원 개발자 우선 현지화 및 콘텐츠 워크플로를 제공합니다. Intlayer는 오픈 소스 프로젝트이며 모든 기여자는 높이 평가됩니다.',
      zh: 'Intlayer为SaaS团队提供了一个AI辅助、开发者优先的本地化和内容工作流程，无供应商锁定。Intlayer是一个开源项目，非常欢迎任何贡献者。',
      it: 'Intlayer offre ai team SaaS un flusso di lavoro per la localizzazione e i contenuti assistito da IA e incentrato sugli sviluppatori, senza vincoli con i fornitori. Intlayer è un progetto open source e ogni contributo è molto apprezzato.',
      pt: 'O Intlayer oferece às equipes de SaaS um fluxo de trabalho de localização e conteúdo assistido por IA e focado no desenvolvedor, sem dependência de fornecedor. O Intlayer é um projeto de código aberto, e qualquer contribuidor é muito valorizado.',
      hi: 'इंटलेयर सास टीमों को शून्य वेंडर लॉक-इन के साथ स्थानीयकरण और सामग्री के लिए एआई-सहायता प्राप्त, डेवलपर-प्रथम वर्कफ़्लो देता है। इंटलेयर एक ओपन सोर्स प्रोजेक्ट है, किसी भी योगदानकर्ता का बहुत महत्व है।',
      ar: 'يمنح Intlayer فرق SaaS سير عمل مدعوم بالذكاء الاصطناعي وموجه للمطورين للترجمة والمحتوى دون أي ارتباط بمورد معين. Intlayer هو مشروع مفتوح المصدر، ويتم تقدير أي مساهم بشكل كبير.',
      ru: 'Intlayer предоставляет командам SaaS рабочий процесс локализации и контента с поддержкой ИИ, ориентированный на разработчиков, без привязки к поставщику. Intlayer — это проект с открытым исходным кодом, и любой вклад высоко ценится.',
    }),

    availableFor: t({
      en: 'Available for',
      'en-GB': 'Available for',
      fr: 'Disponible pour',
      es: 'Disponible para',
      de: 'Verfügbar für',
      ja: '利用可能',
      ko: '사용 가능',
      zh: '适用于',
      it: 'Disponibile per',
      pt: 'Disponível para',
      hi: 'केवल इसके लिए उपलब्ध',
      ar: 'متاح ل',
      ru: 'Доступно для',
    }),
    supportButton: t({
      en: 'Support the project',
      'en-GB': 'Support the project',
      fr: 'Soutenir le projet',
      es: 'Apoyar el proyecto',
      de: 'Das Projekt unterstützen',
      ja: 'プロジェクトをサポート',
      ko: '프로젝트 지원',
      zh: '支持项目',
      it: 'Sostenere il progetto',
      pt: 'Apoiar o projeto',
      hi: 'परियोजना का समर्थन करें',
      ar: 'دعم المشروع',
      ru: 'Поддержать проект',
    }),
    getStartedButton: t({
      en: 'Get started',
      'en-GB': 'Get started',
      fr: 'Commencer',
      es: 'Empezar',
      de: 'Loslegen',
      ja: '始める',
      ko: '시작하기',
      zh: '开始',
      it: 'Iniziare',
      pt: 'Começar',
      hi: 'शुरू हो जाओ',
      ar: 'البدء',
      ru: 'Начать',
    }),
  },
} satisfies Dictionary;

export default landingSectionContent;
