import { type Dictionary, t } from 'intlayer';

const landingSectionContent = {
  key: 'landing-section',
  content: {
    whatsNew: t({
      ar: 'ما الجديد',
      de: 'Was gibt es Neues',
      en: "What's new",
      'en-GB': "What's new",
      es: 'Novedades',
      fr: 'Actualités ',
      hi: 'नया क्या है',
      it: 'Novità',
      ja: '新着情報',
      ko: '새로운 소식',
      pt: 'Novidades',
      ru: 'Что нового',
      tr: 'Neler Yeni',
      zh: '最新消息',
    }),
    whatsNewLabel: t({
      ar: 'اذهب إلى صفحة التحديثات',
      de: 'Zur Seite der Updates gehen',
      en: 'Go to the updates page',
      'en-GB': 'Go to the updates page',
      es: 'Ir a la página de actualizaciones',
      fr: 'Aller à la page des mises à jour',
      hi: 'अपडेट पृष्ठ पर जाएं',
      it: 'Vai alla pagina delle aggiornamenti',
      ja: '更新ページに行く',
      ko: '업데이트 페이지로 이동',
      pt: 'Ir para a página de atualizações',
      ru: 'Перейти на страницу обновлений',
      tr: 'Güncellemeler sayfasına git',
      zh: '前往更新页面',
    }),
    version: t({
      ar: 'تم شحن   للتو',
      de: 'Gerade   veröffentlicht',
      en: 'Just shipped  ',
      'en-GB': 'Just shipped  ',
      es: 'Recién lanzado  ',
      fr: ' Publiée récemment  ',
      hi: 'अभी   शिप किया गया',
      it: 'Appena rilasciato  ',
      ja: ' をリリースしました',
      ko: '  출시',
      pt: 'Acabamos de lançar a  ',
      ru: 'Только что выпустили  ',
      tr: 'Az önce yayınlandı  ',
      zh: '刚刚发布  ',
    }),
    title: t({
      ar: 'i18n بالمكون - تسريع عملية التطوير',
      de: 'i18n pro Komponente - Beschleunigen Sie Ihr Entwicklungsprozess',
      en: 'Per-Component i18n - Speed up your development process',
      'en-GB': 'Per-Component i18n - Speed up your development process',
      es: 'i18n por componente - Acelera tu proceso de desarrollo',
      fr: 'Accélérez votre processus de développement (i18n par composant)',
      hi: 'घड़ा को कंपोनेंट आई 18 एन - डेवलपमेंट प्रोसेस को त्वरित करें',
      it: 'i18n per componente - Accelera il tuo processo di sviluppo',
      ja: 'コンポーネントごとのi18n - 開発プロセスを加速',
      ko: '컴포넌트별 i18n - 개발 프로세스 가속화',
      pt: 'i18n por componente - Acelera o seu processo de desenvolvimento',
      ru: 'i18n по компоненту - Ускорение процесса разработки',
      tr: 'Bileşen Başına i18n - Geliştirme Sürecinizi Hızlandırın',
      zh: '组件级i18n - 加速开发过程',
    }),
    subheading: t({
      ar: 'آمن الأنواع. ترجم بالذكاء الاصطناعي. حرر بصريًا.',
      de: 'Type-Safe. Mit KI übersetzen. Visuell bearbeiten.',
      en: 'Type-Safe. Translate with AI. Edit Visually.',
      'en-GB': 'Type-Safe. Translate with AI. Edit Visually.',
      es: 'Type-Safe. Traduce con IA. Edita visualmente.',
      fr: "Type-Safe. Traduisez avec l'IA. Éditez visuellement.",
      hi: 'टाइप-सेफ। AI से अनुवाद करें। विजुअली एडिट करें।',
      it: "Type-Safe. Traduci con l'IA. Modifica visivamente.",
      ja: '型安全。AIで翻訳。視覚的に編集。',
      ko: '타입 안전. AI로 번역. 시각적으로 편집.',
      pt: 'Type-Safe. Traduza com IA. Edite visualmente.',
      ru: 'Типобезопасный. Переводите с ИИ. Редактируйте визуально.',
      tr: 'Type-Safe. Yapay Zeka ile Çeviri. Görsel Olarak Düzenle.',
      zh: '类型安全。AI翻译。可视化编辑。',
    }),
    description: t({
      ar: 'يوفر Intlayer لفريقك سير عمل يركز على المطور للتدويل وإدارة المحتوى، مما يضمن بقاء كودك قابلاً للصيانة وقابلاً للتطوير. يعمل كنظام إدارة محتوى موجه للمكونات وهو مفتوح المصدر بالكامل. كل مساهمة مقدرة بصدق.',
      de: 'Definieren Sie Übersetzungen neben Komponenten mit vollständiger Typsicherheit. Laden Sie bei Bedarf Redakteure über ein optionales CMS ein. Jeder Beitrag wird aufrichtig geschätzt.',
      en: 'Define translations next to components, with full type safety.Invite editors through an optional CMS when needed. Every contribution genuinely appreciated.',
      'en-GB':
        'Define translations next to components, with full type safety.Invite editors through an optional CMS when needed. Every contribution genuinely appreciated.',
      es: 'Define traducciones junto a los componentes, con una seguridad de tipo completa. Invita a los editores a través de un CMS opcional cuando sea necesario. Cada contribución es genuinamente apreciada.',
      fr: 'Définissez les traductions au niveau des composants, avec typage strict. Invitez des éditeurs via un CMS optionnel si besoin. Chaque contribution est appréciée.',
      hi: 'Intlayer आपकी टीम को अंतर्राष्ट्रीयकरण और सामग्री प्रबंधन के लिए डेवलपर-प्रथम वर्कफ़्लो प्रदान करता है, यह सुनिश्चित करते हुए कि आपका कोड रखरखाव योग्य और स्केलेबल बना रहे। यह एक कंपोनेंट-उन्मुख CMS के रूप में कार्य करता है और पूरी तरह से ओपन सोर्स है। हर योगदान का सच्चे दिल से आभार।',
      it: "Intlayer fornisce al tuo team un flusso di lavoro orientato allo sviluppatore per l'internazionalizzazione e la gestione dei contenuti, garantendo che il tuo codice rimanga manutenibile e scalabile. Funziona come un CMS orientato ai componenti ed è completamente open source. Ogni contributo è sinceramente apprezzato.",
      ja: 'コンポーネントの隣に翻訳を定義し、完全な型安全性を確保します。必要に応じてオプションのCMSを通じて編集者を招待します。すべての貢献に心から感謝します。',
      ko: '구성 요소 옆에 번역을 정의하고 완전한 유형 안전성을 보장합니다. 필요에 따라 선택적 CMS를 통해 편집자를 초대합니다. 모든 기여에 진심으로 감사드립니다.',
      pt: 'Intlayer fornece à sua equipe um fluxo de trabalho focado no desenvolvedor para internacionalização e gerenciamento de conteúdo, garantindo que seu código permaneça manutenível e escalável. Funciona como um CMS orientado a componentes e é totalmente open source. Cada contribuição é genuinamente apreciada.',
      ru: 'Intlayer предоставляет вашей команде ориентированный на разработчиков рабочий процесс для интернационализации и управления контентом, обеспечивая поддерживаемость и масштабируемость вашего кода. Он работает как компонентно-ориентированная CMS и полностью открыт. Каждый вклад искренне ценится.',
      tr: 'Intlayer, ekibinize uluslararasılaştırma ve içerik yönetimi için geliştirici odaklı bir iş akışı sağlar ve kodunuzun sürdürülebilir ve ölçeklenebilir kalmasını sağlar. Bileşen odaklı bir CMS olarak çalışır ve tamamen açık kaynaktır. Her katkı gerçekten takdir edilmektedir.',
      zh: 'Intlayer为您的团队提供以开发者为先的国际化和内容管理工作流程，确保您的代码保持可维护性和可扩展性。它作为面向组件的CMS运作，并且完全开源。真诚感谢每一份贡献。',
    }),

    availableFor: t({
      ar: 'متاح ل',
      de: 'Verfügbar für',
      en: 'Available for',
      'en-GB': 'Available for',
      es: 'Disponible para',
      fr: 'Disponible pour',
      hi: 'केवल इसके लिए उपलब्ध',
      it: 'Disponibile per',
      ja: '利用可能',
      ko: '사용 가능',
      pt: 'Disponível para',
      ru: 'Доступно для',
      tr: 'Şunun için mevcut',
      zh: '适用于',
    }),
    supportButton: t({
      ar: 'دعم المشروع',
      de: 'Das Projekt unterstützen',
      en: 'Support the project',
      'en-GB': 'Support the project',
      es: 'Apoyar el proyecto',
      fr: 'Soutenir le projet',
      hi: 'परियोजना का समर्थन करें',
      it: 'Sostenere il progetto',
      ja: 'プロジェクトをサポート',
      ko: '프로젝트 지원',
      pt: 'Apoiar o projeto',
      ru: 'Поддержать проект',
      tr: 'Projeyi destekle',
      zh: '支持项目',
    }),
    getStartedButton: t({
      ar: 'البدء',
      de: 'Loslegen',
      en: 'Get started',
      'en-GB': 'Get started',
      es: 'Empezar',
      fr: 'Commencer',
      hi: 'शुरू हो जाओ',
      it: 'Iniziare',
      ja: '始める',
      ko: '시작하기',
      pt: 'Começar',
      ru: 'Начать',
      tr: 'Başlayın',
      zh: '开始',
    }),
  },
} satisfies Dictionary;

export default landingSectionContent;
