import { t, type Dictionary } from 'intlayer';

const landingSectionContent = {
  key: 'landing-section',
  content: {
    whatsNew: t({
      en: "What's new",
      'en-GB': "What's new",
      fr: 'Quoi de neuf',
      es: 'Novedades',
      de: 'Was gibt es Neues',
      ja: '新着情報',
      ko: '새로운 소식',
      zh: '最新消息',
      it: 'Novità',
      pt: 'Novidades',
      hi: 'नया क्या है',
      ar: 'ما الجديد',
      ru: 'Что нового',
    }),
    version: t({
      en: 'Just shipped  ',
      'en-GB': 'Just shipped  ',
      fr: '  vient de sortir',
      es: 'Recién lanzado  ',
      de: 'Gerade   veröffentlicht',
      ja: ' をリリースしました',
      ko: '  출시',
      zh: '刚刚发布  ',
      it: 'Appena rilasciato  ',
      pt: 'Acabamos de lançar a  ',
      hi: 'अभी   शिप किया गया',
      ar: 'تم شحن   للتو',
      ru: 'Только что выпустили  ',
    }),
    title: t({
      en: 'Translate Your SaaS in Minutes, Not Weeks',
      'en-GB': 'Translate Your SaaS in Minutes, Not Weeks',
      fr: 'Traduisez votre SaaS en quelques minutes, pas en semaines',
      es: 'Traduzca su SaaS en minutos, no en semanas',
      de: 'Übersetzen Sie Ihre SaaS in Minuten, nicht in Wochen',
      ja: '数週間ではなく数分でSaaSを翻訳',
      ko: '몇 주가 아닌 몇 분 만에 SaaS 번역',
      zh: '在几分钟内翻译您的SaaS，而不是几周',
      it: 'Traduci il tuo SaaS in pochi minuti, non in settimane',
      pt: 'Traduza seu SaaS em minutos, não em semanas',
      hi: 'अपने SaaS को हफ्तों में नहीं, मिनटों में अनुवाद करें',
      ar: 'ترجم SaaS الخاص بك في دقائق وليس في أسابيع',
      ru: 'Переведите свой SaaS за минуты, а не за недели',
    }),
    subheading: t({
      en: 'Use AI. Edit visually. Push global. All for free.',
      'en-GB': 'Use AI. Edit visually. Push global. All for free.',
      fr: 'Utilisez l’IA. Éditez visuellement. Diffusez mondialement. Tout cela gratuitement.',
      es: 'Usa la IA. Edita visualmente. Lanza a nivel mundial. Todo gratis.',
      de: 'KI nutzen. Visuell bearbeiten. Global veröffentlichen. Alles kostenlos.',
      ja: 'AIを使用。視覚的に編集。グローバルに展開。すべて無料。',
      ko: 'AI 사용. 시각적으로 편집. 전 세계에 출시. 모두 무료.',
      zh: '使用AI。可视化编辑。全球发布。完全免费。',
      it: 'Usa l’IA. Modifica visivamente. Pubblica a livello globale. Tutto gratuitamente.',
      pt: 'Use IA. Edite visualmente. Lance globalmente. Tudo de graça.',
      hi: 'एआई का प्रयोग करें। विज़ुअली संपादित करें। वैश्विक रूप से पुश करें। सब कुछ मुफ्त।',
      ar: 'استخدم الذكاء الاصطناعي. قم بالتحرير بصريًا. انشر عالميًا. كل ذلك مجانًا.',
      ru: 'Используйте ИИ. Редактируйте визуально. Публикуйте глобально. Все бесплатно.',
    }),
    description: t({
      en: 'Intlayer gives SaaS teams an AI-assisted, developer-first workflow for localization and content with zero vendor lock-in. Intlayer is an open source project, any contributor is highly valued',
      'en-GB':
        'Intlayer gives SaaS teams an AI-assisted, developer-first workflow for localization and content with zero vendor lock-in. Intlayer is an open source project, any contributor is highly valued',
      fr: 'Intlayer offre aux équipes SaaS un flux de travail assisté par IA et axé sur les développeurs pour la localisation et le contenu, sans dépendance vis-à-vis d’un fournisseur. Intlayer est un projet open source, et toute contribution est très appréciée.',
      es: 'Intlayer proporciona a los equipos de SaaS un flujo de trabajo de localización y contenido asistido por IA y centrado en el desarrollador, sin dependencia de proveedores. Intlayer es un proyecto de código abierto, y cualquier contribución es muy valorada.',
      de: 'Intlayer bietet SaaS-Teams einen KI-gestützten, entwicklerorientierten Workflow für Lokalisierung und Inhalte ohne Anbieterbindung. Intlayer ist ein Open-Source-Projekt, und jeder Beitrag wird sehr geschätzt.',
      ja: 'Intlayerは、SaaSチームに、ベンダーロックインのない、AI支援の開発者第一のローカリゼーションおよびコンテンツワークフローを提供します。Intlayerはオープンソースプロジェクトであり、どんな貢献者も高く評価されます。',
      ko: 'Intlayer는 SaaS 팀에게 공급업체 종속성이 없는 AI 지원 개발자 우선 현지화 및 콘텐츠 워크플로를 제공합니다. Intlayer는 오픈 소스 프로젝트이며 모든 기여자는 높이 평가됩니다.',
      zh: 'Intlayer为SaaS团队提供了一个AI辅助、开发者优先的本地化和内容工作流程，无供应商锁定。Intlayer是一个开源项目，非常欢迎任何贡献者。',
      it: 'Intlayer offre ai team SaaS un flusso di lavoro per la localizzazione e i contenuti assistito da IA e incentrato sugli sviluppatori, senza vincoli con i fornitori. Intlayer è un progetto open source e ogni contributo è molto apprezzato.',
      pt: 'O Intlayer oferece às equipes de SaaS um fluxo de trabalho de localização e conteúdo assistido por IA e focado no desenvolvedor, sem dependência de fornecedor. O Intlayer é um projeto de código aberto, e qualquer contribuidor é muito valorizado.',
      hi: 'इंटलेयर सास टीमों को शून्य वेंडर लॉक-इन के साथ स्थानीयकरण और सामग्री के लिए एआई-सहायता प्राप्त, डेवलपर-प्रथम वर्कफ़्लो देता है। इंटलेयर एक ओपन सोर्स प्रोजेक्ट है, किसी भी योगदानकर्ता का बहुत महत्व है।',
      ar: 'يمنح Intlayer فرق SaaS سير عمل مدعوم بالذكاء الاصطناعي وموجه للمطورين للترجمة والمحتوى دون أي ارتباط بمورد معين. Intlayer هو مشروع مفتوح المصدر، ويتم تقدير أي مساهم بشكل كبير.',
      ru: 'Intlayer предоставляет командам SaaS рабочий процесс локализации и контента с поддержкой ИИ, ориентированный на разработчиков, без привязки к поставщику. Intlayer — это проект с открытым исходным кодом, и любой вклад высоко ценится.',
    }),

    availableFor: t({
      en: 'Available for',
      'en-GB': 'Available for',
      fr: 'Disponible pour',
      es: 'Disponible para',
      de: 'Verfügbar für',
      ja: '利用可能',
      ko: '사용 가능',
      zh: '适用于',
      it: 'Disponibile per',
      pt: 'Disponível para',
      hi: 'केवल इसके लिए उपलब्ध',
      ar: 'متاح ل',
      ru: 'Доступно для',
    }),
    supportButton: t({
      en: 'Support the project',
      'en-GB': 'Support the project',
      fr: 'Soutenir le projet',
      es: 'Apoyar el proyecto',
      de: 'Das Projekt unterstützen',
      ja: 'プロジェクトをサポート',
      ko: '프로젝트 지원',
      zh: '支持项目',
      it: 'Sostenere il progetto',
      pt: 'Apoiar o projeto',
      hi: 'परियोजना का समर्थन करें',
      ar: 'دعم المشروع',
      ru: 'Поддержать проект',
    }),
    getStartedButton: t({
      en: 'Get started',
      'en-GB': 'Get started',
      fr: 'Commencer',
      es: 'Empezar',
      de: 'Loslegen',
      ja: '始める',
      ko: '시작하기',
      zh: '开始',
      it: 'Iniziare',
      pt: 'Começar',
      hi: 'शुरू हो जाओ',
      ar: 'البدء',
      ru: 'Начать',
    }),
  },
} satisfies Dictionary;

export default landingSectionContent;
