import { type Dictionary, t } from 'intlayer';

const affiliateAdminDetailPageContent = {
  key: 'affiliate-admin-detail-page',
  content: {
    affiliateDetailTitle: t({
      en: 'Affiliate Detail',
      ru: 'Детали партнера',
      ja: 'アフィリエイト詳細',
      fr: "Détails de l'affilié",
      ko: '제휴사 세부 정보',
      zh: '附属机构详情',
      es: 'Detalle del afiliado',
      de: 'Affiliate-Details',
      ar: 'تفاصيل الشريك',
      it: 'Dettagli affiliato',
      'en-GB': 'Affiliate Detail',
      pt: 'Detalhes do afiliado',
      hi: 'सहयोगी विवरण',
      tr: 'Ortak Detayı',
      pl: 'Szczegóły partnera',
      id: 'Detail Afiliasi',
      vi: 'Chi tiết đại lý',
      uk: 'Деталі партнера',
    }),
    affiliateNotFound: t({
      en: 'Affiliate not found.',
      ru: 'Партнер не найден.',
      ja: 'アフィリエイトが見つかりません。',
      fr: 'Affilié introuvable.',
      ko: '제휴사를 찾을 수 없습니다.',
      zh: '未找到附属机构。',
      es: 'Afiliado no encontrado.',
      de: 'Affiliate nicht gefunden.',
      ar: 'الشريك غير موجود.',
      it: 'Affiliato non trovato.',
      'en-GB': 'Affiliate not found.',
      pt: 'Afiliado não encontrado.',
      hi: 'सहयोगी नहीं मिला।',
      tr: 'Ortak bulunamadı.',
      pl: 'Nie znaleziono partnera.',
      id: 'Afiliasi tidak ditemukan.',
      vi: 'Không tìm thấy đại lý.',
      uk: 'Партнера не знайдено.',
    }),
    id: t({
      en: 'ID',
      ru: 'ID',
      ja: 'ID',
      fr: 'ID',
      ko: 'ID',
      zh: 'ID',
      es: 'ID',
      de: 'ID',
      ar: 'معرف',
      it: 'ID',
      'en-GB': 'ID',
      pt: 'ID',
      hi: 'आईडी',
      tr: 'Kimlik',
      pl: 'ID',
      id: 'ID',
      vi: 'ID',
      uk: 'ID',
    }),
    referralCode: t({
      en: 'Referral Code',
      ru: 'Реферальный код',
      ja: '紹介コード',
      fr: 'Code de parrainage',
      ko: '추천 코드',
      zh: '推荐代码',
      es: 'Código de referencia',
      de: 'Empfehlungscode',
      ar: 'رمز الإحالة',
      it: 'Codice di riferimento',
      'en-GB': 'Referral Code',
      pt: 'Código de indicação',
      hi: 'रेफरल कोड',
      tr: 'Referans Kodu',
      pl: 'Kod polecający',
      id: 'Kode Rujukan',
      vi: 'Mã giới thiệu',
      uk: 'Реферальний код',
    }),
    status: t({
      en: 'Status',
      ru: 'Статус',
      ja: 'ステータス',
      fr: 'Statut',
      ko: '상태',
      zh: '状态',
      es: 'Estado',
      de: 'Status',
      ar: 'الحالة',
      it: 'Stato',
      'en-GB': 'Status',
      pt: 'Status',
      hi: 'स्थिति',
      tr: 'Durum',
      pl: 'Status',
      id: 'Status',
      vi: 'Trạng thái',
      uk: 'Статус',
    }),
    commissionRate: t({
      en: 'Commission Rate',
      ru: 'Ставка комиссии',
      ja: 'コミッション率',
      fr: 'Taux de commission',
      ko: '수수료율',
      zh: '佣金率',
      es: 'Tasa de comisión',
      de: 'Provisionssatz',
      ar: 'نسبة العمولة',
      it: 'Tasso di commissione',
      'en-GB': 'Commission Rate',
      pt: 'Taxa de comissão',
      hi: 'कमीशन दर',
      tr: 'Komisyon Oranı',
      pl: 'Stawka prowizji',
      id: 'Tingkat Komisi',
      vi: 'Tỷ lệ hoa hồng',
      uk: 'Ставка комісії',
    }),
    commissionType: t({
      en: 'Commission Type',
      ru: 'Тип комиссии',
      ja: 'コミッションタイプ',
      fr: 'Type de commission',
      ko: '수수료 유형',
      zh: '佣金类型',
      es: 'Tipo de comisión',
      de: 'Provisionstyp',
      ar: 'نوع العمولة',
      it: 'Tipo di commissione',
      'en-GB': 'Commission Type',
      pt: 'Tipo de comissão',
      hi: 'कमीशन का प्रकार',
      tr: 'Komisyon Türü',
      pl: 'Typ prowizji',
      id: 'Jenis Komisi',
      vi: 'Loại hoa hồng',
      uk: 'Тип комісії',
    }),
    stripeAccount: t({
      en: 'Stripe Account',
      ru: 'Аккаунт Stripe',
      ja: 'Stripeアカウント',
      fr: 'Compte Stripe',
      ko: 'Stripe 계정',
      zh: 'Stripe账户',
      es: 'Cuenta de Stripe',
      de: 'Stripe-Konto',
      ar: 'حساب Stripe',
      it: 'Account Stripe',
      'en-GB': 'Stripe Account',
      pt: 'Conta Stripe',
      hi: 'Stripe खाता',
      tr: 'Stripe Hesabı',
      pl: 'Konto Stripe',
      id: 'Akun Stripe',
      vi: 'Tài khoản Stripe',
      uk: 'Акаунт Stripe',
    }),
    created: t({
      en: 'Created',
      ru: 'Создано',
      ja: '作成日',
      fr: 'Créé',
      ko: '생성됨',
      zh: '已创建',
      es: 'Creado',
      de: 'Erstellt',
      ar: 'تم الإنشاء',
      it: 'Creato',
      'en-GB': 'Created',
      pt: 'Criado',
      hi: 'बनाया गया',
      tr: 'Oluşturuldu',
      pl: 'Utworzono',
      id: 'Dibuat',
      vi: 'Đã tạo',
      uk: 'Створено',
    }),
    updated: t({
      en: 'Updated',
      ru: 'Обновлено',
      ja: '更新日',
      fr: 'Mis à jour',
      ko: '업데이트됨',
      zh: '已更新',
      es: 'Actualizado',
      de: 'Aktualisiert',
      ar: 'تم التحديث',
      it: 'Aggiornato',
      'en-GB': 'Updated',
      pt: 'Atualizado',
      hi: 'अपडेट किया गया',
      tr: 'Güncellendi',
      pl: 'Zaktualizowano',
      id: 'Diperbarui',
      vi: 'Đã cập nhật',
      uk: 'Оновлено',
    }),
    userProfile: t({
      en: 'User Profile',
      ru: 'Профиль пользователя',
      ja: 'ユーザープロフィール',
      fr: 'Profil utilisateur',
      ko: '사용자 프로필',
      zh: '用户资料',
      es: 'Perfil de usuario',
      de: 'Benutzerprofil',
      ar: 'ملف المستخدم',
      it: 'Profilo utente',
      'en-GB': 'User Profile',
      pt: 'Perfil do usuário',
      hi: 'उपयोगकर्ता प्रोफ़ाइल',
      tr: 'Kullanıcı Profili',
      pl: 'Profil użytkownika',
      id: 'Profil Pengguna',
      vi: 'Hồ sơ người dùng',
      uk: 'Профіль користувача',
    }),
    viewUserProfile: t({
      en: 'View user profile →',
      ru: 'Профиль пользователя →',
      ja: 'ユーザープロフィールを表示 →',
      fr: 'Voir le profil utilisateur →',
      ko: '사용자 프로필 보기 →',
      zh: '查看用户资料 →',
      es: 'Ver perfil de usuario →',
      de: 'Benutzerprofil anzeigen →',
      ar: 'عرض ملف المستخدم →',
      it: 'Visualizza profilo utente →',
      'en-GB': 'View user profile →',
      pt: 'Ver perfil do usuário →',
      hi: 'उपयोगकर्ता प्रोफ़ाइल देखें →',
      tr: 'Kullanıcı profilini görüntüle →',
      pl: 'Zobacz profil użytkownika →',
      id: 'Lihat profil pengguna →',
      vi: 'Xem hồ sơ người dùng →',
      uk: 'Переглянути профіль користувача →',
    }),
    enable: t({
      en: 'Enable affiliate',
      ru: 'Активировать партнёра',
      ja: 'アフィリエイトを有効化',
      fr: "Activer l'affilié",
      ko: '제휴사 활성화',
      zh: '启用附属机构',
      es: 'Activar afiliado',
      de: 'Affiliate aktivieren',
      ar: 'تفعيل الشريك',
      it: "Attiva l'affiliato",
      'en-GB': 'Enable affiliate',
      pt: 'Ativar afiliado',
      hi: 'सहयोगी सक्षम करें',
      tr: 'Ortağı etkinleştir',
      pl: 'Aktywuj partnera',
      id: 'Aktifkan afiliasi',
      vi: 'Kích hoạt đại lý',
      uk: 'Активувати партнера',
    }),
    suspend: t({
      en: 'Suspend affiliate',
      ru: 'Приостановить партнёра',
      ja: 'アフィリエイトを停止',
      fr: "Suspendre l'affilié",
      ko: '제휴사 정지',
      zh: '暂停附属机构',
      es: 'Suspender afiliado',
      de: 'Affiliate sperren',
      ar: 'تعليق الشريك',
      it: "Sospendi l'affiliato",
      'en-GB': 'Suspend affiliate',
      pt: 'Suspender afiliado',
      hi: 'सहयोगी निलंबित करें',
      tr: 'Ortağı askıya al',
      pl: 'Zawieś partnera',
      id: 'Tangguhkan afiliasi',
      vi: 'Tạm ngưng đại lý',
      uk: 'Призупинити партнера',
    }),
  },
} satisfies Dictionary;

export default affiliateAdminDetailPageContent;
