import { type Dictionary, t } from 'intlayer';

const planContent = {
  key: 'organization-plan',
  content: {
    title: t({
      en: 'Plan',
      fr: 'Plan',
      es: 'Plan',
      'en-GB': 'Plan',
      de: 'Plan',
      ja: 'プラン',
      ko: '플랜',
      zh: '计划',
      it: 'Piano',
      pt: 'Plano',
      hi: 'प्लान',
      ar: 'الخطة',
      ru: 'План',
      tr: 'Plan',
      pl: 'Plan',
      id: 'Paket',
      vi: 'Gói',
    }),

    upgradeButton: {
      text: t({
        en: 'Upgrade',
        fr: 'Mettre à niveau',
        es: 'Mejorar',
        'en-GB': 'Upgrade',
        de: 'Upgrade',
        ja: 'アップグレード',
        ko: '업그레이드',
        zh: '升级',
        it: 'Aggiorna',
        pt: 'Atualizar',
        hi: 'अपग्रेड',
        ar: 'ترقية',
        ru: 'Обновить',
        tr: 'Yükselt',
        pl: 'Uaktualnij',
        id: 'Tingkatkan',
        vi: 'Nâng cấp',
      }),
      label: t({
        en: 'Click to upgrade',
        fr: 'Cliquez pour mettre à niveau',
        es: 'Haz clic para mejorar',
        'en-GB': 'Click to upgrade',
        de: 'Klicken Sie, um zu aktualisieren',
        ja: 'アップグレードをクリック',
        ko: '업그레이드를 클릭하세요',
        zh: '点击升级',
        it: 'Clicca per aggiornare',
        pt: 'Clique para atualizar',
        hi: 'अपग्रेड करने के लिए क्लिक करें',
        ar: 'انقر لترقية',
        ru: 'Нажмите, чтобы обновить',
        tr: 'Yükseltmek için tıklayın',
        pl: 'Kliknij, aby uaktualnić plan',
        id: 'Klik untuk meningkatkan',
        vi: 'Nhấn để nâng cấp',
      }),
    },

    renewButton: {
      text: t({
        en: 'Renew plan',
        fr: 'Renouveler le plan',
        es: 'Renovar plan',
        'en-GB': 'Renew plan',
        de: 'Plan erneuern',
        ja: 'プランを更新',
        ko: '계획 업그레이드',
        zh: '续订计划',
        it: 'Rinnova piano',
        pt: 'Renovar plano',
        hi: 'प्रोजेक्ट रीनोवर्ड करें',
        ar: 'إعادة ترقية الخطة',
        ru: 'Продлить план',
        tr: 'Planı yenile',
        pl: 'Odnów plan',
        id: 'Perpanjang paket',
        vi: 'Gia hạn gói',
      }),
      label: t({
        en: 'Click to renew plan',
        fr: 'Cliquez pour renouveler le plan',
        es: 'Haz clic para renovar el plan',
        'en-GB': 'Click to renew plan',
        de: 'Klicken Sie, um das Plan zu erneuern',
        ja: 'プランを更新するにはクリックしてください',
        ko: '계획을 업그레이드하려면 클릭하세요',
        zh: '点击续订计划',
        it: 'Clicca per rinnovare il piano',
        pt: 'Clique para renovar o plano',
        hi: 'प्रोजेक्ट रीनोवर्ड करने के लिए क्लिक करें',
        ar: 'انقر لإعادة ترقية الخطة',
        ru: 'Нажмите, чтобы продлить план',
        tr: 'Planı yenilemek için tıklayın',
        pl: 'Kliknij, aby odnowić plan',
        id: 'Klik untuk memperpanjang paket',
        vi: 'Nhấn để gia hạn gói',
      }),
    },

    cancelButton: {
      text: t({
        en: 'Cancel plan',
        fr: 'Annuler le plan',
        es: 'Cancelar plan',
        'en-GB': 'Cancel plan',
        de: 'Plan stornieren',
        ja: 'プランをキャンセル',
        ko: '계획 취소',
        zh: '取消计划',
        it: 'Annulla piano',
        pt: 'Cancelar plano',
        hi: 'प्लान रद्द करें',
        ar: 'إلغاء الخطة',
        ru: 'Отменить план',
        tr: 'Planı iptal et',
        pl: 'Anuluj plan',
        id: 'Batalkan langganan',
        vi: 'Hủy gói',
      }),
      label: t({
        en: 'Click to cancel plan',
        fr: 'Cliquez pour annuler le plan',
        es: 'Haz clic para cancelar el plan',
        'en-GB': 'Click to cancel plan',
        de: 'Klicken Sie, um den Plan zu stornieren',
        ja: 'プランをキャンセルするにはクリックしてください',
        ko: '계획을 취소하려면 클릭하세요',
        zh: '点击取消计划',
        it: 'Clicca per annullare il piano',
        pt: 'Clique para cancelar o plano',
        hi: 'प्लान रद्द करने के लिए क्लिक करें',
        ar: 'انقر لإلغاء الخطة',
        ru: 'Нажмите, чтобы отменить план',
        tr: 'Planı iptal etmek için tıklayın',
        pl: 'Kliknij, aby anulować plan',
        id: 'Klik untuk membatalkan langganan',
        vi: 'Nhấn để hủy gói',
      }),
    },

    cancelModal: {
      title: t({
        en: 'Are you sure you want to cancel your subscription?',
        fr: 'Êtes-vous sûr de vouloir annuler votre abonnement ?',
        es: '¿Está seguro de que desea cancelar su suscripción?',
        'en-GB': 'Are you sure you want to cancel your subscription?',
        de: 'Sind Sie sicher, dass Sie Ihr Abonnement stornieren möchten?',
        ja: 'サブスクリプションをキャンセルしてもよろしいですか？',
        ko: '구독을 취소하시겠습니까?',
        zh: '您确定要取消您的订阅吗？',
        it: 'Sei sicuro di voler annullare la tua sottoscrizione?',
        pt: 'Tem certeza de que deseja cancelar o seu plano?',
        hi: 'क्या आप अपने सदस्यता रद्द करना चाहते हैं?',
        ar: 'هل أنت متأكد من أنك ترغب في إلغاء اشتراكك؟',
        ru: 'Вы уверены, что хотите отменить подписку?',
        tr: 'Aboneliğinizi iptal etmek istediğinizden emin misiniz?',
        pl: 'Czy na pewno chcesz anulować subskrypcję?',
        id: 'Apakah Anda yakin ingin membatalkan langganan Anda?',
        vi: 'Bạn có chắc chắn muốn hủy đăng ký của mình không?',
      }),

      message: t({
        en: 'This action CANNOT be undone. This will permanently cancel your subscription. Your other organization members will also loose access to the organization and access to premium features will be disabled. If you’d like to use it in the future, you will need to create it again.',
        fr: "Cette action est IRRÉVERSIBLE. Cela annulera votre abonnement. Les autres membres de votre organisation seront également perdus de l'accès à l'organisation et à toutes les fonctionnalités premium. Si vous souhaitez l'utiliser à l'avenir, vous devrez la créer à nouveau.",
        es: 'Esta acción NO SE PUEDE deshacer. Esto cancelará permanentemente su suscripción. Los otros miembros de su organización también perderán el acceso a la organización y las funcionalidades premium de acceso se desactivarán. Si desea usarla en el futuro, deberá crearla nuevamente.',
        'en-GB':
          'This action CANNOT be undone. This will permanently cancel your subscription. Your other organization members will also loose access to the organization and access to premium features will be disabled. If you’d like to use it in the future, you will need to create it again.',
        de: 'Diese Aktion KANN NICHT rückgängig gemacht werden. Dies wird Ihr Abonnement dauerhaft stornieren. Ihre anderen Organisationsteilnehmer verlieren ebenfalls den Zugriff auf die Organisation und der Zugriff auf Premium-Funktionen wird deaktiviert. Wenn Sie es in Zukunft verwenden möchten, müssen Sie es erneut erstellen.',
        ja: 'この操作は取り消すことができません。これにより、サブスクリプションが永久にキャンセルされます。他の組織メンバーも組織へのアクセスを失い、プレミアム機能へのアクセスが無効になります。将来使用する場合は、再度作成する必要があります。',
        ko: '이 작업은 취소할 수 없습니다. 이 작업은 구독을 영구적으로 취소합니다. 다른 조직 구성원도 조직에 대한 액세스를 잃게되며 프리미엄 기능에 대한 액세스가 비활성화됩니다. 나중에 사용하려면 다시 만들어야합니다.',
        zh: '此操作无法撤消。这将永久取消您的订阅。您的其他组织成员也将失去对组织的访问权限，并且对高级功能的访问权限将被禁用。如果您希望将来使用它，则需要重新创建它。',
        it: "Questa azione NON PUÒ essere annullata. Questo cancellerà permanentemente la tua sottoscrizione. Anche gli altri membri dell'organizzazione perderanno l'accesso all'organizzazione e l'accesso alle funzionalità premium verrà disabilitato. Se desideri utilizzarlo in futuro, dovrai crearlo nuovamente.",
        pt: 'Esta ação NÃO PODE ser desfeita. Isso cancelará permanentemente sua assinatura. Os outros membros da sua organização também perderão o acesso à organização e o acesso a recursos premium será desativado. Se desejar usá-lo no futuro, será necessário criá-lo novamente.',
        hi: 'यह कार्रवाई पूर्ववत नहीं की जा सकती। यह आपकी सदस्यता को स्थायी रूप से रद्द करेगा। आपके अन्य संगठन सदस्य भी संगठन तक पहुंच खो देंगे और प्रीमियम सुविधाओं तक पहुंच अक्षम हो जाएगी। यदि आप इसे भविष्य में उपयोग करना चाहते हैं, तो आपको इसे फिर से बनाना होगा।',
        ar: 'هذا الإجراء لا يمكن التراجع عنه. سيتم إلغاء اشتراكك بشكل دائم. سيفقد أعضاء المنظمة الآخرون أيضًا الوصول إلى المنظمة وسيتم تعطيل الوصول إلى الميزات المميزة. إذا كنت ترغب في استخدامه في المستقبل ، فيجب عليك إعادة إنشائه.',
        ru: 'Это действие НЕЛЬЗЯ отменить. Это навсегда отменит вашу подписку. Ваши другие члены организации также потеряют доступ к организации, и доступ к премиальным функциям будет отключен. Если вы хотите использовать его в будущем, вам нужно будет создать его снова.',
        tr: 'Bu işlem geri alınamaz. Bu, aboneliğinizi kalıcı olarak iptal edecektir. Diğer organizasyon üyeleriniz de organizasyona erişimi kaybedecek ve premium özelliklere erişim devre dışı bırakılacaktır. Gelecekte kullanmak isterseniz, yeniden oluşturmanız gerekecektir.',
        pl: 'Ta akcja NIE MOŻE zostać cofnięta. To spowoduje trwałe anulowanie Twojej subskrypcji. Pozostali członkowie organizacji również stracą dostęp do organizacji, a dostęp do funkcji premium zostanie wyłączony. Jeśli w przyszłości będziesz chciał(a) z niej skorzystać, będziesz musiał(a) utworzyć ją ponownie.',
        id: 'Tindakan ini TIDAK DAPAT dibatalkan. Ini akan secara permanen membatalkan langganan Anda. Anggota organisasi lainnya juga akan kehilangan akses ke organisasi dan akses ke fitur premium akan dinonaktifkan. Jika Anda ingin menggunakannya di masa depan, Anda harus membuatnya lagi.',
        vi: 'Hành động này KHÔNG THỂ hoàn tác. Thao tác này sẽ hủy vĩnh viễn đăng ký của bạn. Các thành viên khác trong tổ chức của bạn cũng sẽ mất quyền truy cập vào tổ chức và quyền truy cập các tính năng cao cấp sẽ bị vô hiệu hóa. Nếu bạn muốn sử dụng lại trong tương lai, bạn sẽ cần phải tạo lại tổ chức.',
      }),

      buttonLabel: t({
        en: 'Cancel my subscription',
        fr: 'Annuler mon abonnement',
        es: 'Cancelar mi suscripción',
        'en-GB': 'Cancel my subscription',
        de: 'Meinen Abonnement stornieren',
        ja: 'サブスクリプションをキャンセル',
        ko: '구독 취소',
        zh: '取消我的订阅',
        it: 'Annulla la mia sottoscrizione',
        pt: 'Cancelar minha assinatura',
        hi: 'मेरी सदस्यता रद्द करें',
        ar: 'إلغاء اشتراكي',
        ru: 'Отменить мою подписку',
        tr: 'Aboneliğimi iptal et',
        pl: 'Anuluj moją subskrypcję',
        id: 'Batalkan langganan saya',
        vi: 'Hủy đăng ký của tôi',
      }),

      confirmText: t({
        en: 'I understand, cancel my subscription',
        fr: 'Je comprends, annuler mon abonnement',
        es: 'Entiendo, cancelar mi suscripción',
        'en-GB': 'I understand, cancel my subscription',
        de: 'Ich verstehe, meinen Abonnement stornieren',
        ja: '理解しました。サブスクリプションをキャンセルします',
        ko: '이해하고 구독을 취소합니다',
        zh: '我明白了，取消我的订阅',
        it: 'Capisco, annulla la mia sottoscrizione',
        pt: 'Eu entendo, cancelo minha assinatura',
        hi: 'मैं समझ सकता हूं, मेरी सदस्यता रद्द करें',
        ar: 'أفهم، إلغاء اشتراكي',
        ru: 'Я понимаю, отменить мою подписку',
        tr: 'Anlıyorum, aboneliğimi iptal et',
        pl: 'Rozumiem, anuluj moją subskrypcję',
        id: 'Saya mengerti, batalkan langganan saya',
        vi: 'Tôi hiểu, hủy đăng ký của tôi',
      }),
    },
  },
  title: 'Organization plan',
  description:
    'Content declaration related to the subscription plan management within an organization. Includes UI text for upgrading, renewing, and canceling plans, as well as confirmation modals.',
  tags: ['organization', 'subscription', 'dashboard'],
} satisfies Dictionary;

export default planContent;
