import { GithubRoutes, PagesRoutes } from '@/Routes';
import { DocData } from '@components/DocPage/types';
import { Dictionary, t } from 'intlayer';

const docContent = {
  key: 'doc-nuxt-intlayer-metadata',
  content: {
    docName: 'package__nuxt-intlayer',
    url: PagesRoutes['Doc_Packages_nuxt-intlayer'],
    githubUrl: GithubRoutes['Packages_nuxt-intlayer'],
    createdAt: '2025-06-18',
    updatedAt: '2025-06-18',
    title: t({
      en: 'Package Documentation | nuxt-intlayer',
      'en-GB': 'Package Documentation | nuxt-intlayer',
      fr: 'Documentation du package | nuxt-intlayer',
      es: 'Documentación del paquete | nuxt-intlayer',
      de: 'Paketdokumentation | nuxt-intlayer',
      ja: 'パッケージドキュメント | nuxt-intlayer',
      ko: '패키지 문서 | nuxt-intlayer',
      zh: '包文档 | nuxt-intlayer',
      it: 'Documentazione del pacchetto | nuxt-intlayer',
      pt: 'Documentação do pacote | nuxt-intlayer',
      hi: 'पैकेज के डॉक्यूमेंटेशन | nuxt-intlayer',
      ar: 'وثائق حزمة | nuxt-intlayer',
      ru: 'Документация пакета | nuxt-intlayer',
    }),

    description: t({
      en: 'See how to use the nuxt-intlayer package',
      'en-GB': 'See how to use the nuxt-intlayer package',
      fr: 'Découvrez comment utiliser le package nuxt-intlayer',
      es: 'Descubre cómo usar el paquete nuxt-intlayer',
      de: 'Erfahren Sie, wie Sie das nuxt-intlayer-Paket verwenden',
      ja: 'nuxt-intlayerパッケージの使用方法を確認してください',
      ko: 'nuxt-intlayer 패키지 사용 방법을 확인하세요',
      zh: '查看如何使用 nuxt-intlayer 软件包',
      it: 'Scopri come utilizzare il pacchetto nuxt-intlayer',
      pt: 'Veja como usar o pacote nuxt-intlayer',
      hi: 'nuxt-intlayer पैकेज का उपयोग कैसे करें',
      ar: 'انظر كيف تستخدم حزمة nuxt-intlayer',
      ru: 'Узнайте, как использовать пакет nuxt-intlayer',
    }),

    keywords: t({
      en: [
        'Intlayer',
        'nuxt-intlayer',
        'Internationalization',
        'Documentation',
        'JavaScript',
        'Nuxt',
      ],
      'en-GB': [
        'Intlayer',
        'nuxt-intlayer',
        'Internationalization',
        'Documentation',
        'JavaScript',
        'Nuxt',
      ],
      fr: [
        'Intlayer',
        'nuxt-intlayer',
        'Internationalisation',
        'Documentation',
        'JavaScript',
        'Nuxt',
      ],
      es: [
        'Intlayer',
        'nuxt-intlayer',
        'Internacionalización',
        'Documentación',
        'JavaScript',
        'Nuxt',
      ],
      de: [
        'Intlayer',
        'nuxt-intlayer',
        'Internationalisierung',
        'Dokumentation',
        'JavaScript',
        'Nuxt',
      ],
      ja: [
        'Intlayer',
        'nuxt-intlayer',
        '国際化',
        'ドキュメント',
        'JavaScript',
        'Nuxt',
      ],
      ko: ['Intlayer', 'nuxt-intlayer', '국제화', '문서', 'JavaScript', 'Nuxt'],
      zh: ['Intlayer', 'nuxt-intlayer', '国际化', '文档', 'JavaScript', 'Nuxt'],
      it: [
        'Intlayer',
        'nuxt-intlayer',
        'internazionalizzazione',
        'documentazione',
        'JavaScript',
        'Nuxt',
      ],
      pt: [
        'Intlayer',
        'nuxt-intlayer',
        'internacionalização',
        'documentação',
        'JavaScript',
        'Nuxt',
      ],
      hi: [
        'Intlayer',
        'nuxt-intlayer',
        'अंतर्राष्ट्रीयकरण',
        'प्रलेखन',
        'JavaScript',
        'Nuxt',
      ],
      ar: [
        'Intlayer',
        'nuxt-intlayer',
        'الدولية',
        'المستندات',
        'JavaScript',
        'Nuxt',
      ],
      ru: [
        'Intlayer',
        'nuxt-intlayer',
        'интернационализация',
        'документация',
        'JavaScript',
        'Nuxt',
      ],
    }),
  },
} satisfies Dictionary<DocData>;

export default docContent;
