import { t, type Dictionary } from 'intlayer';

const codeContent = {
  key: 'code',
  content: {
    title: t({
      en: 'Copy code',
      es: 'Copiar código',
      pt: 'Copiar código',
      fr: 'Copier le code',
      de: 'Code kopieren',
      it: 'Copiare il codice',
      ja: 'コードをコピー',
      ko: '코드 복사',
      zh: '复制代码',
      hi: 'कोड कॉपी करें',
      'en-GB': 'Copy code',
      ru: 'Копировать код',
      ar: 'نسخ الكود',
    }),
    description: t({
      en: 'Copy the code to the clipboard',
      es: 'Copiar el código al portapapeles',
      pt: 'Copiar o código para a área de transferência',
      fr: 'Copier le code dans le presse-papiers',
      de: 'Kopieren Sie den Code in die Zwischenablage',
      it: 'Copiare il codice nella clipboard',
      ja: 'コードをクリップボードにコピー',
      ko: '코드를 클립보드에 복사',
      zh: '复制代码到剪贴板',
      hi: 'कोड को क्लिपबोर्ड पर कॉपी करें',
      'en-GB': 'Copy the code to the clipboard',
      ru: 'Копировать код в буфер обмена',
      ar: 'نسخ الكود إلى الحافظة',
    }),
    show: t({
      en: 'Show more',
      fr: 'Afficher plus',
      es: 'Mostrar más',
      'en-GB': 'Show more',
      de: 'Mehr anzeigen',
      ja: 'もっと見る',
      ko: '더 보기',
      zh: '显示更多',
      it: 'Mostra di più',
      pt: 'Mostrar mais',
      hi: 'और दिखाएँ',
      ar: 'عرض المزيد',
      ru: 'Показать больше',
    }),
    hide: t({
      en: 'Show less',
      fr: 'Afficher moins',
      es: 'Mostrar menos',
      'en-GB': 'Show less',
      de: 'Weniger anzeigen',
      ja: '表示を減らす',
      ko: '간략히 보기',
      zh: '显示较少',
      it: 'Mostra meno',
      pt: 'Mostrar menos',
      hi: 'कम दिखाएँ',
      ar: 'عرض أقل',
      ru: 'Показать меньше',
    }),
  },
} satisfies Dictionary;

export default codeContent;
