import { GithubRoutes, PagesRoutes } from '@/Routes';
import { DocData } from '@components/DocPage/types';
import { Dictionary, t } from 'intlayer';

const docContent = {
  key: 'doc-getHTMLTextDir-intlayer-metadata',
  content: {
    docName: 'package__intlayer__getHTMLTextDir',
    url: PagesRoutes['Doc_Packages_intlayer_getHTMLTextDir'],
    githubUrl: GithubRoutes['Packages_intlayer_getHTMLTextDir'],
    createdAt: '2024-08-11',
    updatedAt: '2024-08-11',
    title: t({
      en: 'getHTMLTextDir Function Documentation | intlayer',
      'en-GB': 'getHTMLTextDir Function Documentation | intlayer',
      fr: 'Documentation de la fonction getHTMLTextDir | intlayer',
      es: 'Documentación de la función getHTMLTextDir | intlayer',
      de: 'Dokumentation der t-Funktion | intlayer',
      ja: 't関数のドキュメント | intlayer',
      ko: 'getHTMLTextDir 함수 문서 | intlayer',
      zh: 't函数文档 | intlayer',
      it: 'Documentazione della funzione getHTMLTextDir | intlayer',
      pt: 'Documentação da função getHTMLTextDir | intlayer',
      hi: 'getHTMLTextDir फ़ंक्शन प्रलेखन | intlayer',
      ar: 'وثائق دالة getHTMLTextDir | intlayer',
      ru: 'Документация функции getHTMLTextDir | intlayer',
    }),

    description: t({
      en: 'See how to use the getHTMLTextDir function for intlayer package',
      'en-GB':
        'See how to use the getHTMLTextDir function for intlayer package',
      fr: 'Découvrez commengetHTMLTextDir utiliser la fonction getHTMLTextDir pour le package intlayer',
      es: 'Descubre cómo usar la función getHTMLTextDir para el paquete intlayer',
      de: 'Erfahren Sie, wie Sie die t-Funktion für das intlayer-PakegetHTMLTextDir verwenden',
      ja: 'intlayerパッケージのt関数の使用方法を確認してください',
      ko: 'intlayer 패키지의 getHTMLTextDir 함수 사용 방법을 확인하세요',
      zh: '查看如何使用 intlayer 软件包的 getHTMLTextDir 函数',
      it: 'Scopri come utilizzare la funzione getHTMLTextDir per il pacchetto intlayer',
      pt: 'Veja como usar a função getHTMLTextDir para o pacote intlayer',
      hi: 'intlayer पैकेज के लिए getHTMLTextDir फ़ंक्शन का उपयोग कैसे करें, यह जानें',
      ar: 'انظر كيف تستخدم دالة getHTMLTextDir لحزمة intlayer',
      ru: 'Узнайте, как использовать функцию getHTMLTextDir для пакета intlayer',
    }),

    keywords: t({
      en: [
        'getHTMLTextDir',
        'translation',
        'Intlayer',
        'intlayer',
        'Internationalization',
        'Documentation',
        'Next.js',
        'JavaScript',
        'React',
      ],
      'en-GB': [
        'getHTMLTextDir',
        'translation',
        'Intlayer',
        'intlayer',
        'Internationalization',
        'Documentation',
        'Next.js',
        'JavaScript',
        'React',
      ],
      fr: [
        'getHTMLTextDir',
        'traduction',
        'Intlayer',
        'intlayer',
        'Internationalisation',
        'Documentation',
        'Next.js',
        'JavaScript',
        'React',
      ],
      es: [
        'getHTMLTextDir',
        'traducción',
        'Intlayer',
        'intlayer',
        'Internacionalización',
        'Documentación',
        'Next.js',
        'JavaScript',
        'React',
      ],
      de: [
        'getHTMLTextDir',
        'Übersetzung',
        'Intlayer',
        'intlayer',
        'Internationalisierung',
        'Dokumentation',
        'Next.js',
        'JavaScript',
        'React',
      ],
      ja: [
        'getHTMLTextDir',
        '翻訳',
        'Intlayer',
        'intlayer',
        '国際化',
        'ドキュメント',
        'Next.js',
        'JavaScript',
        'React',
      ],
      ko: [
        'getHTMLTextDir',
        '번역',
        'Intlayer',
        'intlayer',
        '국제화',
        '문서',
        'Next.js',
        'JavaScript',
        'React',
      ],
      zh: [
        'getHTMLTextDir',
        '翻译',
        'Intlayer',
        'intlayer',
        '国际化',
        '文档',
        'Next.js',
        'JavaScript',
        'React',
      ],
      it: [
        'getHTMLTextDir',
        'traduzione',
        'Intlayer',
        'intlayer',
        'internazionalizzazione',
        'documentazione',
        'Next.js',
        'JavaScript',
        'React',
      ],
      pt: [
        'getHTMLTextDir',
        'tradução',
        'Intlayer',
        'intlayer',
        'internacionalização',
        'documentação',
        'Next.js',
        'JavaScript',
        'React',
      ],
      hi: [
        'getHTMLTextDir',
        'अनुवाद',
        'Intlayer',
        'intlayer',
        'अंतर्राष्ट्रीयकरण',
        'प्रलेखन',
        'Next.js',
        'JavaScript',
        'React',
      ],
      ar: [
        'getHTMLTextDir',
        'ترجمة',
        'Intlayer',
        'intlayer',
        'الدولية',
        'المستندات',
        'Next.js',
        'JavaScript',
        'React',
      ],
      ru: [
        'getHTMLTextDir',
        'перевод',
        'Intlayer',
        'intlayer',
        'интернационализация',
        'документация',
        'Next.js',
        'JavaScript',
        'React',
      ],
    }),
  },
} satisfies Dictionary<DocData>;

export default docContent;
