import { GithubRoutes, PagesRoutes } from '@/Routes';
import { DocData } from '@components/DocPage/types';
import { Dictionary, t } from 'intlayer';

const docContent = {
  key: 'doc-intlayer-metadata',
  content: {
    docName: 'package__intlayer',
    url: PagesRoutes['Doc_Packages_intlayer'],
    githubUrl: GithubRoutes['Packages_intlayer'],
    createdAt: '2024-08-11',
    updatedAt: '2024-08-11',
    title: t({
      en: 'Package Documentation | intlayer',
      'en-GB': 'Package Documentation | intlayer',
      fr: 'Documentation du package | intlayer',
      es: 'Documentación del paquete | intlayer',
      de: 'Paketdokumentation | intlayer',
      ja: 'パッケージドキュメント | intlayer',
      ko: '패키지 문서 | intlayer',
      zh: '包文档 | intlayer',
      it: 'Documentazione del pacchetto | intlayer',
      pt: 'Documentação do pacote | intlayer',
      hi: 'पैकेज के डॉक्यूमेंटेशन | intlayer',
      ar: 'وثائق حزمة | intlayer',
      ru: 'Документация пакета | intlayer',
    }),

    description: t({
      en: 'See how to use the intlayer package',
      'en-GB': 'See how to use the intlayer package',
      fr: 'Découvrez comment utiliser le package intlayer',
      es: 'Descubre cómo usar el paquete intlayer',
      de: 'Erfahren Sie, wie Sie das intlayer-Paket verwenden',
      ja: 'intlayerパッケージの使用方法を確認してください',
      ko: 'intlayer 패키지 사용 방법을 확인하세요',
      zh: '查看如何使用 intlayer 软件包',
      it: 'Scopri come utilizzare il pacchetto intlayer',
      pt: 'Veja como usar o pacote intlayer',
      hi: 'intlayer पैकेज का उपयोग कैसे करें',
      ar: 'انظر كيف تستخدم حزمة intlayer',
      ru: 'Узнайте, как использовать пакет intlayer',
    }),

    keywords: t({
      en: [
        'Intlayer',
        'intlayer',
        'Internationalization',
        'Documentation',
        'Next.js',
        'JavaScript',
        'React',
      ],
      'en-GB': [
        'Intlayer',
        'intlayer',
        'Internationalization',
        'Documentation',
        'Next.js',
        'JavaScript',
        'React',
      ],
      fr: [
        'Intlayer',
        'intlayer',
        'Internationalisation',
        'Documentation',
        'Next.js',
        'JavaScript',
        'React',
      ],
      es: [
        'Intlayer',
        'intlayer',
        'Internacionalización',
        'Documentación',
        'Next.js',
        'JavaScript',
        'React',
      ],
      de: [
        'Intlayer',
        'intlayer',
        'Internationalisierung',
        'Dokumentation',
        'Next.js',
        'JavaScript',
        'React',
      ],
      ja: [
        'Intlayer',
        'intlayer',
        '国際化',
        'ドキュメント',
        'Next.js',
        'JavaScript',
        'React',
      ],
      ko: [
        'Intlayer',
        'intlayer',
        '국제화',
        '문서',
        'Next.js',
        'JavaScript',
        'React',
      ],
      zh: [
        'Intlayer',
        'intlayer',
        '国际化',
        '文档',
        'Next.js',
        'JavaScript',
        'React',
      ],
      it: [
        'Intlayer',
        'intlayer',
        'internazionalizzazione',
        'documentazione',
        'Next.js',
        'JavaScript',
        'React',
      ],
      pt: [
        'Intlayer',
        'intlayer',
        'internacionalização',
        'documentação',
        'Next.js',
        'JavaScript',
        'React',
      ],
      hi: [
        'Intlayer',
        'intlayer',
        'अंतर्राष्ट्रीयकरण',
        'प्रलेखन',
        'Next.js',
        'JavaScript',
        'React',
      ],
      ar: [
        'Intlayer',
        'intlayer',
        'الدولية',
        'المستندات',
        'Next.js',
        'JavaScript',
        'React',
      ],
      ru: [
        'Intlayer',
        'intlayer',
        'интернационализация',
        'документация',
        'Next.js',
        'JavaScript',
        'React',
      ],
    }),
  },
} satisfies Dictionary<DocData>;

export default docContent;
