import { type Dictionary, insert, t } from 'intlayer';

export const frameConnectionErrorContent = {
  key: 'frame-connection-error',
  content: {
    title: t({
      en: 'The application could not be displayed',
      'en-GB': 'The application could not be displayed',
      fr: "L'application n'a pas pu être affichée",
      es: 'No se pudo mostrar la aplicación',
      de: 'Die Anwendung konnte nicht angezeigt werden',
      ja: 'アプリケーションを表示できませんでした',
      ko: '애플리케이션을 표시할 수 없습니다',
      zh: '无法显示应用程序',
      it: "Impossibile visualizzare l'applicazione",
      pt: 'Não foi possível exibir a aplicação',
      hi: 'एप्लिकेशन प्रदर्शित नहीं किया जा सका',
      ar: 'تعذر عرض التطبيق',
      ru: 'Не удалось отобразить приложение',
      tr: 'Uygulama görüntülenemedi',
      pl: 'Nie można wyświetlić aplikacji',
      id: 'Aplikasi tidak dapat ditampilkan',
      vi: 'Không thể hiển thị ứng dụng',
      uk: 'Не вдалося відобразити застосунок',
    }),
    description: insert(
      t({
        en: '{{applicationUrl}} did not connect to the editor. Check that:',
        'en-GB':
          '{{applicationUrl}} did not connect to the editor. Check that:',
        fr: "{{applicationUrl}} ne s'est pas connectée à l'éditeur. Vérifiez que :",
        es: '{{applicationUrl}} no se conectó al editor. Compruebe que:',
        de: '{{applicationUrl}} hat sich nicht mit dem Editor verbunden. Prüfen Sie, dass:',
        ja: '{{applicationUrl}} がエディターに接続しませんでした。次の点を確認してください：',
        ko: '{{applicationUrl}}이(가) 에디터에 연결되지 않았습니다. 다음을 확인하세요:',
        zh: '{{applicationUrl}} 未连接到编辑器。请检查：',
        it: "{{applicationUrl}} non si è connessa all'editor. Verifica che:",
        pt: '{{applicationUrl}} não se conectou ao editor. Verifique se:',
        hi: '{{applicationUrl}} एडिटर से कनेक्ट नहीं हुआ। जाँचें कि:',
        ar: 'لم يتصل {{applicationUrl}} بالمحرر. تحقق من أن:',
        ru: '{{applicationUrl}} не подключилось к редактору. Убедитесь, что:',
        tr: '{{applicationUrl}} düzenleyiciye bağlanmadı. Şunları kontrol edin:',
        pl: '{{applicationUrl}} nie połączyła się z edytorem. Sprawdź, czy:',
        id: '{{applicationUrl}} tidak terhubung ke editor. Pastikan bahwa:',
        vi: '{{applicationUrl}} không kết nối với trình chỉnh sửa. Hãy kiểm tra rằng:',
        uk: '{{applicationUrl}} не підключився до редактора. Переконайтеся, що:',
      })
    ),
    framingCause: insert(
      t({
        en: 'its Content-Security-Policy `frame-ancestors` directive (or `X-Frame-Options` header) allows {{editorOrigin}}',
        'en-GB':
          'its Content-Security-Policy `frame-ancestors` directive (or `X-Frame-Options` header) allows {{editorOrigin}}',
        fr: 'sa directive Content-Security-Policy `frame-ancestors` (ou son en-tête `X-Frame-Options`) autorise {{editorOrigin}}',
        es: 'su directiva Content-Security-Policy `frame-ancestors` (o la cabecera `X-Frame-Options`) permite {{editorOrigin}}',
        de: 'seine Content-Security-Policy-Direktive `frame-ancestors` (oder der Header `X-Frame-Options`) {{editorOrigin}} erlaubt',
        ja: 'Content-Security-Policy の `frame-ancestors` ディレクティブ（または `X-Frame-Options` ヘッダー）が {{editorOrigin}} を許可している',
        ko: 'Content-Security-Policy의 `frame-ancestors` 지시어(또는 `X-Frame-Options` 헤더)가 {{editorOrigin}}을(를) 허용하는지',
        zh: '其 Content-Security-Policy 的 `frame-ancestors` 指令（或 `X-Frame-Options` 头）允许 {{editorOrigin}}',
        it: 'la sua direttiva Content-Security-Policy `frame-ancestors` (o l’header `X-Frame-Options`) consente {{editorOrigin}}',
        pt: 'sua diretiva Content-Security-Policy `frame-ancestors` (ou o cabeçalho `X-Frame-Options`) permite {{editorOrigin}}',
        hi: 'इसका Content-Security-Policy `frame-ancestors` निर्देश (या `X-Frame-Options` हेडर) {{editorOrigin}} को अनुमति देता है',
        ar: 'توجيه `frame-ancestors` في Content-Security-Policy (أو ترويسة `X-Frame-Options`) يسمح بـ {{editorOrigin}}',
        ru: 'его директива Content-Security-Policy `frame-ancestors` (или заголовок `X-Frame-Options`) разрешает {{editorOrigin}}',
        tr: 'Content-Security-Policy `frame-ancestors` yönergesi (veya `X-Frame-Options` başlığı) {{editorOrigin}} adresine izin veriyor',
        pl: 'jej dyrektywa Content-Security-Policy `frame-ancestors` (lub nagłówek `X-Frame-Options`) zezwala na {{editorOrigin}}',
        id: 'direktif Content-Security-Policy `frame-ancestors` (atau header `X-Frame-Options`) mengizinkan {{editorOrigin}}',
        vi: 'chỉ thị Content-Security-Policy `frame-ancestors` (hoặc header `X-Frame-Options`) cho phép {{editorOrigin}}',
        uk: 'його директива Content-Security-Policy `frame-ancestors` (або заголовок `X-Frame-Options`) дозволяє {{editorOrigin}}',
      })
    ),
    editorEnabledCause: t({
      en: 'the visual editor is enabled in its Intlayer configuration (`editor.enabled`)',
      'en-GB':
        'the visual editor is enabled in its Intlayer configuration (`editor.enabled`)',
      fr: "l'éditeur visuel est activé dans sa configuration Intlayer (`editor.enabled`)",
      es: 'el editor visual está activado en su configuración de Intlayer (`editor.enabled`)',
      de: 'der visuelle Editor in der Intlayer-Konfiguration aktiviert ist (`editor.enabled`)',
      ja: 'Intlayer 設定でビジュアルエディターが有効になっている（`editor.enabled`）',
      ko: 'Intlayer 설정에서 비주얼 에디터가 활성화되어 있는지 (`editor.enabled`)',
      zh: '其 Intlayer 配置中已启用可视化编辑器（`editor.enabled`）',
      it: "l'editor visuale è abilitato nella sua configurazione Intlayer (`editor.enabled`)",
      pt: 'o editor visual está ativado na configuração do Intlayer (`editor.enabled`)',
      hi: 'इसके Intlayer कॉन्फ़िगरेशन में विज़ुअल एडिटर सक्षम है (`editor.enabled`)',
      ar: 'المحرر المرئي مفعّل في إعدادات Intlayer الخاصة به (`editor.enabled`)',
      ru: 'визуальный редактор включён в его конфигурации Intlayer (`editor.enabled`)',
      tr: 'görsel düzenleyici Intlayer yapılandırmasında etkin (`editor.enabled`)',
      pl: 'edytor wizualny jest włączony w jej konfiguracji Intlayer (`editor.enabled`)',
      id: 'editor visual diaktifkan dalam konfigurasi Intlayer-nya (`editor.enabled`)',
      vi: 'trình chỉnh sửa trực quan được bật trong cấu hình Intlayer (`editor.enabled`)',
      uk: 'візуальний редактор увімкнено в його конфігурації Intlayer (`editor.enabled`)',
    }),
    editorDisabledDescription: insert(
      t({
        en: 'The visual editor is disabled in the Intlayer configuration of {{applicationUrl}}.',
        'en-GB':
          'The visual editor is disabled in the Intlayer configuration of {{applicationUrl}}.',
        fr: "L'éditeur visuel est désactivé dans la configuration Intlayer de {{applicationUrl}}.",
        es: 'El editor visual está desactivado en la configuración de Intlayer de {{applicationUrl}}.',
        de: 'Der visuelle Editor ist in der Intlayer-Konfiguration von {{applicationUrl}} deaktiviert.',
        ja: '{{applicationUrl}} の Intlayer 設定でビジュアルエディターが無効になっています。',
        ko: '{{applicationUrl}}의 Intlayer 설정에서 비주얼 에디터가 비활성화되어 있습니다.',
        zh: '{{applicationUrl}} 的 Intlayer 配置中已禁用可视化编辑器。',
        it: "L'editor visuale è disabilitato nella configurazione Intlayer di {{applicationUrl}}.",
        pt: 'O editor visual está desativado na configuração do Intlayer de {{applicationUrl}}.',
        hi: '{{applicationUrl}} के Intlayer कॉन्फ़िगरेशन में विज़ुअल एडिटर अक्षम है।',
        ar: 'المحرر المرئي معطّل في إعدادات Intlayer الخاصة بـ {{applicationUrl}}.',
        ru: 'Визуальный редактор отключён в конфигурации Intlayer приложения {{applicationUrl}}.',
        tr: '{{applicationUrl}} için Intlayer yapılandırmasında görsel düzenleyici devre dışı.',
        pl: 'Edytor wizualny jest wyłączony w konfiguracji Intlayer aplikacji {{applicationUrl}}.',
        id: 'Editor visual dinonaktifkan dalam konfigurasi Intlayer {{applicationUrl}}.',
        vi: 'Trình chỉnh sửa trực quan bị tắt trong cấu hình Intlayer của {{applicationUrl}}.',
        uk: 'Візуальний редактор вимкнено в конфігурації Intlayer застосунку {{applicationUrl}}.',
      })
    ),
    editorDisabledHint: t({
      en: 'Set `editor.enabled: true` in its Intlayer configuration file, then restart the application.',
      'en-GB':
        'Set `editor.enabled: true` in its Intlayer configuration file, then restart the application.',
      fr: "Définissez `editor.enabled: true` dans son fichier de configuration Intlayer, puis redémarrez l'application.",
      es: 'Establezca `editor.enabled: true` en su archivo de configuración de Intlayer y reinicie la aplicación.',
      de: 'Setzen Sie `editor.enabled: true` in der Intlayer-Konfigurationsdatei und starten Sie die Anwendung neu.',
      ja: 'Intlayer 設定ファイルで `editor.enabled: true` を設定し、アプリケーションを再起動してください。',
      ko: 'Intlayer 설정 파일에서 `editor.enabled: true`로 설정한 후 애플리케이션을 다시 시작하세요.',
      zh: '在其 Intlayer 配置文件中设置 `editor.enabled: true`，然后重启应用程序。',
      it: "Imposta `editor.enabled: true` nel file di configurazione Intlayer, quindi riavvia l'applicazione.",
      pt: 'Defina `editor.enabled: true` no arquivo de configuração do Intlayer e reinicie a aplicação.',
      hi: 'इसकी Intlayer कॉन्फ़िगरेशन फ़ाइल में `editor.enabled: true` सेट करें, फिर एप्लिकेशन को पुनः आरंभ करें।',
      ar: 'اضبط `editor.enabled: true` في ملف إعدادات Intlayer، ثم أعد تشغيل التطبيق.',
      ru: 'Укажите `editor.enabled: true` в файле конфигурации Intlayer и перезапустите приложение.',
      tr: 'Intlayer yapılandırma dosyasında `editor.enabled: true` ayarlayın, ardından uygulamayı yeniden başlatın.',
      pl: 'Ustaw `editor.enabled: true` w pliku konfiguracji Intlayer, a następnie uruchom ponownie aplikację.',
      id: 'Atur `editor.enabled: true` di file konfigurasi Intlayer-nya, lalu mulai ulang aplikasi.',
      vi: 'Đặt `editor.enabled: true` trong tệp cấu hình Intlayer, rồi khởi động lại ứng dụng.',
      uk: 'Укажіть `editor.enabled: true` у файлі конфігурації Intlayer, а потім перезапустіть застосунок.',
    }),
    providerCause: t({
      en: 'the page renders the Intlayer provider of your framework',
      'en-GB': 'the page renders the Intlayer provider of your framework',
      fr: 'la page affiche le provider Intlayer de votre framework',
      es: 'la página renderiza el provider de Intlayer de su framework',
      de: 'die Seite den Intlayer-Provider Ihres Frameworks rendert',
      ja: 'ページがフレームワークの Intlayer プロバイダーをレンダリングしている',
      ko: '페이지가 프레임워크의 Intlayer 프로바이더를 렌더링하는지',
      zh: '页面渲染了您框架的 Intlayer provider',
      it: 'la pagina renderizza il provider Intlayer del tuo framework',
      pt: 'a página renderiza o provider Intlayer do seu framework',
      hi: 'पेज आपके फ़्रेमवर्क का Intlayer provider रेंडर करता है',
      ar: 'الصفحة تعرض موفّر Intlayer الخاص بإطار العمل لديك',
      ru: 'страница рендерит провайдер Intlayer вашего фреймворка',
      tr: 'sayfa, çatınızın Intlayer sağlayıcısını oluşturuyor',
      pl: 'strona renderuje provider Intlayer Twojego frameworka',
      id: 'halaman merender provider Intlayer dari framework Anda',
      vi: 'trang có hiển thị provider Intlayer của framework bạn dùng',
      uk: 'сторінка рендерить провайдер Intlayer вашого фреймворку',
    }),
    retry: t({
      en: 'Retry',
      'en-GB': 'Retry',
      fr: 'Réessayer',
      es: 'Reintentar',
      de: 'Erneut versuchen',
      ja: '再試行',
      ko: '다시 시도',
      zh: '重试',
      it: 'Riprova',
      pt: 'Tentar novamente',
      hi: 'पुनः प्रयास करें',
      ar: 'إعادة المحاولة',
      ru: 'Повторить',
      tr: 'Tekrar dene',
      pl: 'Spróbuj ponownie',
      id: 'Coba lagi',
      vi: 'Thử lại',
      uk: 'Повторити',
    }),
    dismiss: t({
      en: 'Show the page anyway',
      'en-GB': 'Show the page anyway',
      fr: 'Afficher la page quand même',
      es: 'Mostrar la página de todos modos',
      de: 'Seite trotzdem anzeigen',
      ja: 'それでもページを表示',
      ko: '그래도 페이지 표시',
      zh: '仍然显示页面',
      it: 'Mostra comunque la pagina',
      pt: 'Mostrar a página mesmo assim',
      hi: 'फिर भी पेज दिखाएँ',
      ar: 'عرض الصفحة على أي حال',
      ru: 'Всё равно показать страницу',
      tr: 'Sayfayı yine de göster',
      pl: 'Pokaż stronę mimo to',
      id: 'Tetap tampilkan halaman',
      vi: 'Vẫn hiển thị trang',
      uk: 'Все одно показати сторінку',
    }),
  },
  title: 'Frame connection error',
  description:
    'Overlay shown when the application framed by the visual editor never connects to it.',
} satisfies Dictionary;

export default frameConnectionErrorContent;
