import { type Dictionary, t } from 'intlayer';

const markdownEditorContent = {
  key: 'markdown-editor',
  content: {
    noResults: t({
      en: 'No results',
      'en-GB': 'No results',
      fr: 'Aucun résultat',
      es: 'Sin resultados',
      ru: 'Нет результатов',
      ja: '結果がありません',
      ko: '결과 없음',
      zh: '没有结果',
      de: 'Keine Ergebnisse',
      ar: 'لا توجد نتائج',
      it: 'Nessun risultato',
      pt: 'Sem resultados',
      hi: 'कोई परिणाम नहीं',
      tr: 'Sonuç yok',
      pl: 'Brak wyników',
      id: 'Tidak ada hasil',
      vi: 'Không có kết quả',
      uk: 'Немає результатів',
    }),
    text: t({
      en: 'Text',
      'en-GB': 'Text',
      fr: 'Texte',
      es: 'Texto',
      ru: 'Текст',
      ja: 'テキスト',
      ko: '텍스트',
      zh: '文本',
      de: 'Text',
      ar: 'نص',
      it: 'Testo',
      pt: 'Texto',
      hi: 'पाठ',
      tr: 'Metin',
      pl: 'Tekst',
      id: 'Teks',
      vi: 'Văn bản',
      uk: 'Текст',
    }),
    textDesc: t({
      en: 'Just start typing with plain text.',
      'en-GB': 'Just start typing with plain text.',
      fr: 'Commencez à taper du texte brut.',
      es: 'Comience a escribir con texto sin formato.',
      ru: 'Просто начните вводить обычный текст.',
      ja: 'プレーンテキストで入力を開始します。',
      ko: '일반 텍스트로 입력을 시작하세요.',
      zh: '只需开始输入纯文本。',
      de: 'Beginnen Sie einfach mit der Eingabe von normalem Text.',
      ar: 'ما عليك سوى البدء في الكتابة بنص عادي.',
      it: 'Inizia a scrivere con testo semplice.',
      pt: 'Basta começar a digitar com texto simples.',
      hi: 'सादे पाठ के साथ लिखना शुरू करें।',
      tr: 'Sadece düz metinle yazmaya başlayın.',
      pl: 'Po prostu zacznij pisać zwykłym tekstem.',
      id: 'Mulai mengetik dengan teks biasa.',
      vi: 'Chỉ cần bắt đầu nhập bằng văn bản thuần túy.',
      uk: 'Просто почніть вводити звичайний текст.',
    }),
    todoList: t({
      en: 'To-do List',
      'en-GB': 'To-do List',
      fr: 'Liste de tâches',
      es: 'Lista de tareas',
      ru: 'Список задач',
      ja: 'ToDo リスト',
      ko: '할 일 목록',
      zh: '待办事项列表',
      de: 'ToDo-Liste',
      ar: 'قائمة المهام',
      it: 'Lista cose da fare',
      pt: 'Lista de tarefas',
      hi: 'कार्य सूची',
      tr: 'Yapılacaklar listesi',
      pl: 'Lista zadań',
      id: 'Daftar Tugas',
      vi: 'Danh sách việc cần làm',
      uk: 'Список справ',
    }),
    todoListDesc: t({
      en: 'Track tasks with a to-do list.',
      'en-GB': 'Track tasks with a to-do list.',
      fr: 'Suivez vos tâches avec une liste de choses à faire.',
      es: 'Realice un seguimiento de las tareas con una lista de tareas pendientes.',
      ru: 'Отслеживайте задачи с помощью списка дел.',
      ja: 'ToDo リストでタスクを追跡します。',
      ko: '할 일 목록으로 작업을 추적하세요.',
      zh: '使用待办事项列表跟踪任务。',
      de: 'Verfolgen Sie Aufgaben mit einer ToDo-Liste.',
      ar: 'تتبع المهام باستخدام قائمة المهام.',
      it: 'Traccia le attività con una lista di cose da fare.',
      pt: 'Acompanhe as tarefas com uma lista de tarefas.',
      hi: 'एक कार्य सूची के साथ कार्यों को ट्रैक करें।',
      tr: 'Yapılacaklar listesi ile görevleri takip edin.',
      pl: 'Śledź zadania za pomocą listy zadań.',
      id: 'Lacak tugas dengan daftar tugas.',
      vi: 'Theo dõi nhiệm vụ bằng danh sách việc cần làm.',
      uk: 'Відстежуйте завдання за допомогою списку справ.',
    }),
    heading1: t({
      en: 'Heading 1',
      'en-GB': 'Heading 1',
      fr: 'Titre 1',
      es: 'Título 1',
      ru: 'Заголовок 1',
      ja: '見出し 1',
      ko: '제목 1',
      zh: '标题 1',
      de: 'Überschrift 1',
      ar: 'العنوان 1',
      it: 'Intestazione 1',
      pt: 'Título 1',
      hi: 'शीर्षक 1',
      tr: 'Başlık 1',
      pl: 'Nagłówek 1',
      id: 'Heading 1',
      vi: 'Tiêu đề 1',
      uk: 'Заголовок 1',
    }),
    heading1Desc: t({
      en: 'Big section heading.',
      'en-GB': 'Big section heading.',
      fr: 'Grand titre de section.',
      es: 'Título de sección grande.',
      ru: 'Крупный заголовок раздела.',
      ja: '大見出し。',
      ko: '큰 섹션 제목.',
      zh: '大部门标题。',
      de: 'Große Abschnittsüberschrift.',
      ar: 'عنوان قسم كبير.',
      it: 'Intestazione di sezione grande.',
      pt: 'Título de seção grande.',
      hi: 'बड़ा अनुभाग शीर्षक।',
      tr: 'Büyük bölüm başlığı.',
      pl: 'Duży nagłówek sekcji.',
      id: 'Heading bagian besar.',
      vi: 'Tiêu đề phần lớn.',
      uk: 'Великий заголовок розділу.',
    }),
    heading2: t({
      en: 'Heading 2',
      'en-GB': 'Heading 2',
      fr: 'Titre 2',
      es: 'Título 2',
      ru: 'Заголовок 2',
      ja: '見出し 2',
      ko: '제목 2',
      zh: '标题 2',
      de: 'Überschrift 2',
      ar: 'العنوان 2',
      it: 'Intestazione 2',
      pt: 'Título 2',
      hi: 'शीर्षक 2',
      tr: 'Başlık 2',
      pl: 'Nagłówek 2',
      id: 'Heading 2',
      vi: 'Tiêu đề 2',
      uk: 'Заголовок 2',
    }),
    heading2Desc: t({
      en: 'Medium section heading.',
      'en-GB': 'Medium section heading.',
      fr: 'Titre de section moyen.',
      es: 'Título de sección mediano.',
      ru: 'Средний заголовок раздела.',
      ja: '中見出し。',
      ko: '중간 섹션 제목.',
      zh: '中等部门标题。',
      de: 'Mittlere Abschnittsüberschrift.',
      ar: 'عنوان قسم متوسط.',
      it: 'Intestazione di sezione media.',
      pt: 'Título de seção médio.',
      hi: 'मध्यम अनुभाग शीर्षक।',
      tr: 'Orta bölüm başlığı.',
      pl: 'Średni nagłówek sekcji.',
      id: 'Heading bagian sedang.',
      vi: 'Tiêu đề phần trung bình.',
      uk: 'Середній заголовок розділу.',
    }),
    heading3: t({
      en: 'Heading 3',
      'en-GB': 'Heading 3',
      fr: 'Titre 3',
      es: 'Título 3',
      ru: 'Заголовок 3',
      ja: '見出し 3',
      ko: '제목 3',
      zh: '标题 3',
      de: 'Überschrift 3',
      ar: 'العنوان 3',
      it: 'Intestazione 3',
      pt: 'Título 3',
      hi: 'शीर्षक 3',
      tr: 'Başlık 3',
      pl: 'Nagłówek 3',
      id: 'Heading 3',
      vi: 'Tiêu đề 3',
      uk: 'Заголовок 3',
    }),
    heading3Desc: t({
      en: 'Small section heading.',
      'en-GB': 'Small section heading.',
      fr: 'Petit titre de section.',
      es: 'Título de sección pequeño.',
      ru: 'Мелкий заголовок раздела.',
      ja: '小見出し。',
      ko: '작은 섹션 제목.',
      zh: '小部门标题。',
      de: 'Kleine Abschnittsüberschrift.',
      ar: 'عنوان قسم صغير.',
      it: 'Intestazione di sezione piccola.',
      pt: 'Título de seção pequeno.',
      hi: 'छोटा अनुभाग शीर्षक।',
      tr: 'Küçük bölüm başlığı.',
      pl: 'Mały nagłówek sekcji.',
      id: 'Heading bagian kecil.',
      vi: 'Tiêu đề phần nhỏ.',
      uk: 'Малий заголовок розділу.',
    }),
    bulletList: t({
      en: 'Bullet List',
      'en-GB': 'Bullet List',
      fr: 'Liste à puces',
      es: 'Lista con viñetas',
      ru: 'Маркированный список',
      ja: '箇条書きリスト',
      ko: '글머리 기호 목록',
      zh: '无序列表',
      de: 'Aufzählungsliste',
      ar: 'قائمة نقطية',
      it: 'Elenco puntato',
      pt: 'Lista de marcadores',
      hi: 'बुलेट सूची',
      tr: 'Madde işaretli liste',
      pl: 'Lista punktowana',
      id: 'Daftar Simbol',
      vi: 'Danh sách dấu đầu dòng',
      uk: 'Маркований список',
    }),
    bulletListDesc: t({
      en: 'Create a simple bullet list.',
      'en-GB': 'Create a simple bullet list.',
      fr: 'Créez une liste à puces simple.',
      es: 'Cree una lista con viñetas simple.',
      ru: 'Создайте простой маркированный список.',
      ja: '簡単な箇条書きリストを作成します。',
      ko: '간단한 글머리 기호 목록을 만듭니다.',
      zh: '创建简单的无序列表。',
      de: 'Erstellen Sie eine einfache Aufzählungsliste.',
      ar: 'إنشاء قائمة نقطية بسيطة.',
      it: 'Crea un semplice elenco puntato.',
      pt: 'Crie uma lista de marcadores simples.',
      hi: 'एक सरल बुलेट सूची बनाएं।',
      tr: 'Basit bir madde işaretli liste oluşturun.',
      pl: 'Utwórz prostą listę punktowaną.',
      id: 'Buat daftar simbol sederhana.',
      vi: 'Tạo danh sách dấu đầu dòng đơn giản.',
      uk: 'Створіть простий маркований список.',
    }),
    numberedList: t({
      en: 'Numbered List',
      'en-GB': 'Numbered List',
      fr: 'Liste numérotée',
      es: 'Lista numerada',
      ru: 'Нумерованный список',
      ja: '番号付きリスト',
      ko: '번호 매기기 목록',
      zh: '有序列表',
      de: 'Nummerierte Liste',
      ar: 'قائمة مرقمة',
      it: 'Elenco numerato',
      pt: 'Lista numerada',
      hi: 'क्रमबद्ध सूची',
      tr: 'Numaralı liste',
      pl: 'Lista numerowana',
      id: 'Daftar Bernomor',
      vi: 'Danh sách đánh số',
      uk: 'Нумерований список',
    }),
    numberedListDesc: t({
      en: 'Create a list with numbering.',
      'en-GB': 'Create a list with numbering.',
      fr: 'Créez une liste avec numérotation.',
      es: 'Cree una lista con numeración.',
      ru: 'Создайте список с нумерацией.',
      ja: '番号付きのリストを作成します。',
      ko: '번호가 매겨진 목록을 만듭니다.',
      zh: '创建带数字编号的列表。',
      de: 'Erstellen Sie eine nummerierte Liste.',
      ar: 'إنشاء قائمة بأرقام.',
      it: 'Crea un elenco numerato.',
      pt: 'Crie uma lista numerada.',
      hi: 'नंबरिंग के साथ एक सूची बनाएं।',
      tr: 'Numaralı bir liste oluşturun.',
      pl: 'Utwórz listę z numeracją.',
      id: 'Buat daftar dengan nomor.',
      vi: 'Tạo danh sách có đánh số.',
      uk: 'Створіть список із нумерацією.',
    }),
    quote: t({
      en: 'Quote',
      'en-GB': 'Quote',
      fr: 'Citation',
      es: 'Cita',
      ru: 'Цитата',
      ja: '引用',
      ko: '인용구',
      zh: '引用',
      de: 'Zitat',
      ar: 'اقتباس',
      it: 'Citazione',
      pt: 'Citação',
      hi: 'उद्धरण',
      tr: 'Alıntı',
      pl: 'Cytat',
      id: 'Kutipan',
      vi: 'Trích dẫn',
      uk: 'Цитата',
    }),
    quoteDesc: t({
      en: 'Capture a quote.',
      'en-GB': 'Capture a quote.',
      fr: 'Ajouter une citation.',
      es: 'Añadir una cita.',
      ru: 'Добавить цитату.',
      ja: '引用を追加します。',
      ko: '인용구를 추가합니다.',
      zh: '添加引用。',
      de: 'Erfassen Sie ein Zitat.',
      ar: 'إضافة اقتباس.',
      it: 'Inserisci una citazione.',
      pt: 'Adicione uma citação.',
      hi: 'एक उद्धरण जोड़ें।',
      tr: 'Bir alıntı ekleyin.',
      pl: 'Utwórz cytat.',
      id: 'Buat kutipan.',
      vi: 'Thêm một trích dẫn.',
      uk: 'Додайте цитату.',
    }),
    code: t({
      en: 'Code',
      'en-GB': 'Code',
      fr: 'Code',
      es: 'Código',
      ru: 'Код',
      ja: 'コード',
      ko: '코드',
      zh: '代码',
      de: 'Code',
      ar: 'رمز',
      it: 'Codice',
      pt: 'Código',
      hi: 'कोड',
      tr: 'Kod',
      pl: 'Kod',
      id: 'Kode',
      vi: 'Mã code',
      uk: 'Код',
    }),
    codeDesc: t({
      en: 'Capture a code snippet.',
      'en-GB': 'Capture a code snippet.',
      fr: 'Ajouter un extrait de code.',
      es: 'Añadir un fragmento de código.',
      ru: 'Добавить фрагмент кода.',
      ja: 'コードスニペットを追加します。',
      ko: '코드 스니펫을 추가합니다.',
      zh: '添加代码段。',
      de: 'Erfassen Sie ein Code-Snippet.',
      ar: 'إضافة مقتطف كود.',
      it: 'Inserisci un frammento di codice.',
      pt: 'Adicione um fragmento de código.',
      hi: 'एक कोड स्निपेट जोड़ें।',
      tr: 'Bir kod parçacığı ekleyin.',
      pl: 'Utwórz fragment kodu.',
      id: 'Buat cuplikan kode.',
      vi: 'Thêm một đoạn mã.',
      uk: 'Додайте фрагмент коду.',
    }),
    image: t({
      en: 'Image',
      'en-GB': 'Image',
      fr: 'Image',
      es: 'Imagen',
      ru: 'Изображение',
      ja: '画像',
      ko: '이미지',
      zh: '图片',
      de: 'Bild',
      ar: 'صورة',
      it: 'Immagine',
      pt: 'Imagem',
      hi: 'चित्र',
      tr: 'Resim',
      pl: 'Obraz',
      id: 'Gambar',
      vi: 'Hình ảnh',
      uk: 'Зображення',
    }),
    imageDesc: t({
      en: 'Upload an image from your computer.',
      'en-GB': 'Upload an image from your computer.',
      fr: 'Téléchargez une image depuis votre ordinateur.',
      es: 'Suba una imagen desde su ordenador.',
      ru: 'Загрузите изображение с компьютера.',
      ja: 'コンピューターから画像をアップロードします。',
      ko: '컴퓨터에서 이미지를 업로드합니다.',
      zh: '从电脑上传图片。',
      de: 'Laden Sie ein Bild von Ihrem Computer hoch.',
      ar: 'تحميل صورة من جهاز الكمبيوتر الخاص بك.',
      it: "Carica un'immagine dal tuo computer.",
      pt: 'Carregue uma imagem do seu computador.',
      hi: 'अपने कंप्यूटर से एक छवि अपलोड करें।',
      tr: 'Bilgisayarınızdan bir resim yükleyin.',
      pl: 'Prześlij obraz z komputera.',
      id: 'Unggah gambar dari komputer Anda.',
      vi: 'Tải lên một hình ảnh từ máy tính của bạn.',
      uk: 'Завантажте зображення з комп’ютера.',
    }),
    youtube: t({
      en: 'Youtube',
      'en-GB': 'Youtube',
      fr: 'Youtube',
      es: 'Youtube',
      ru: 'Youtube',
      ja: 'Youtube',
      ko: 'Youtube',
      zh: 'Youtube',
      de: 'Youtube',
      ar: 'يوتيوب',
      it: 'Youtube',
      pt: 'Youtube',
      hi: 'यूट्यूब',
      tr: 'Youtube',
      pl: 'Youtube',
      id: 'Youtube',
      vi: 'Youtube',
      uk: 'Youtube',
    }),
    youtubeDesc: t({
      en: 'Embed a Youtube video.',
      'en-GB': 'Embed a Youtube video.',
      fr: 'Intégrez une vidéo Youtube.',
      es: 'Inserte un video de Youtube.',
      ru: 'Встроить видео с Youtube.',
      ja: 'Youtube 動画を埋め込みます。',
      ko: 'Youtube 동영상을 삽입합니다.',
      zh: '嵌入 Youtube 视频。',
      de: 'Betten Sie ein Youtube-Video ein.',
      ar: 'تضمين فيديو يوتيوب.',
      it: 'Incorpora un video di Youtube.',
      pt: 'Incorpore um vídeo do Youtube.',
      hi: 'एक यूट्यूब वीडियो एम्बेड करें।',
      tr: 'Bir Youtube videosu gömün.',
      pl: 'Osadź wideo z Youtube.',
      id: 'Sematkan video Youtube.',
      vi: 'Nhúng video Youtube.',
      uk: 'Вставте відео з Youtube.',
    }),
    youtubePrompt: t({
      en: 'Please enter Youtube Video Link',
      'en-GB': 'Please enter Youtube Video Link',
      fr: 'Veuillez saisir le lien de la vidéo Youtube',
      es: 'Por favor, introduzca el enlace del video de Youtube',
      ru: 'Пожалуйста, введите ссылку на видео Youtube',
      ja: 'Youtube 動画のリンクを入力してください',
      ko: 'Youtube 동영상 링크를 입력하세요',
      zh: '请输入 Youtube 视频链接',
      de: 'Bitte geben Sie den Youtube-Videolink ein',
      ar: 'يرجى إدخال رابط فيديو يوتيوب',
      it: 'Inserisci il link del video di Youtube',
      pt: 'Por favor, insira o link do vídeo do Youtube',
      hi: 'कृपया यूट्यूब वीडियो लिंक दर्ज करें',
      tr: 'Lütfen Youtube Video Bağlantısını girin',
      pl: 'Wprowadź link do wideo na Youtube',
      id: 'Silakan masukkan Tautan Video Youtube',
      vi: 'Vui lòng nhập liên kết video Youtube',
      uk: 'Будь ласка, введіть посилання на відео Youtube',
    }),
    youtubeError: t({
      en: 'Please enter a correct Youtube Video Link',
      'en-GB': 'Please enter a correct Youtube Video Link',
      fr: 'Veuillez saisir un lien de vidéo Youtube correct',
      es: 'Por favor, introduzca un enlace de video de Youtube correcto',
      ru: 'Пожалуйста, введите корректную ссылку на видео Youtube',
      ja: '正しい Youtube 動画のリンクを入力してください',
      ko: '올바른 Youtube 동영상 링크를 입력하세요',
      zh: '请输入正确的 Youtube 视频链接',
      de: 'Bitte geben Sie einen korrekten Youtube-Videolink ein',
      ar: 'يرجى إدخال رابط فيديو يوتيوب صحيح',
      it: 'Inserisci un link corretto del video di Youtube',
      pt: 'Por favor, insira um link correto do vídeo do Youtube',
      hi: 'कृपया सही यूट्यूब वीडियो लिंक दर्ज करें',
      tr: 'Lütfen doğru bir Youtube Video Bağlantısı girin',
      pl: 'Wprowadź poprawny link do wideo na Youtube',
      id: 'Silakan masukkan Tautan Video Youtube yang benar',
      vi: 'Vui lòng nhập liên kết video Youtube chính xác',
      uk: 'Будь ласка, введіть правильне посилання на відео Youtube',
    }),
    multiple: t({
      en: 'Multiple',
      'en-GB': 'Multiple',
      fr: 'Multiple',
      es: 'Múltiple',
      ru: 'Несколько',
      ja: '複数',
      ko: '다중',
      zh: '多个',
      de: 'Mehrere',
      ar: 'متعدد',
      it: 'Molteplici',
      pt: 'Múltiplo',
      hi: 'एकाधिक',
      tr: 'Birden çok',
      pl: 'Wielokrotny',
      id: 'Beberapa',
      vi: 'Nhiều',
      uk: 'Кілька',
    }),
    bold: t({
      en: 'bold',
      'en-GB': 'bold',
      fr: 'gras',
      es: 'negrita',
      ru: 'жирный',
      ja: '太字',
      ko: '굵게',
      zh: '加粗',
      de: 'fett',
      ar: 'عريض',
      it: 'grassetto',
      pt: 'negrito',
      hi: 'बोल्ड',
      tr: 'kalın',
      pl: 'pogrubienie',
      id: 'tebal',
      vi: 'in đậm',
      uk: 'жирний',
    }),
    italic: t({
      en: 'italic',
      'en-GB': 'italic',
      fr: 'italique',
      es: 'cursiva',
      ru: 'курсив',
      ja: '斜体',
      ko: '기울임꼴',
      zh: '斜体',
      de: 'kursiv',
      ar: 'مائل',
      it: 'corsivo',
      pt: 'itálico',
      hi: 'तिरछा',
      tr: 'italik',
      pl: 'kursywa',
      id: 'miring',
      vi: 'in nghiêng',
      uk: 'курсив',
    }),
    underline: t({
      en: 'underline',
      'en-GB': 'underline',
      fr: 'souligné',
      es: 'subrayado',
      ru: 'подчеркнутый',
      ja: '下線',
      ko: '밑줄',
      zh: '下划线',
      de: 'unterstrichen',
      ar: 'تحته خط',
      it: 'sottolineato',
      pt: 'sublinhado',
      hi: 'रेखांकित',
      tr: 'altı çizili',
      pl: 'podkreślenie',
      id: 'garis bawah',
      vi: 'gạch chân',
      uk: 'підкреслений',
    }),
    strike: t({
      en: 'strike',
      'en-GB': 'strike',
      fr: 'barré',
      es: 'tachado',
      ru: 'зачеркнутый',
      ja: '打ち消し線',
      ko: '취소선',
      zh: '删除线',
      de: 'durchgestrichen',
      ar: 'مشطوب',
      it: 'barrato',
      pt: 'tachado',
      hi: 'स्ट्राइक',
      tr: 'üstü çizili',
      pl: 'przekreślenie',
      id: 'coret',
      vi: 'gạch ngang',
      uk: 'закреслений',
    }),
    colorHeading: t({
      en: 'Color',
      'en-GB': 'Color',
      fr: 'Couleur',
      es: 'Color',
      ru: 'Цвет',
      ja: '色',
      ko: '색상',
      zh: '颜色',
      de: 'Farbe',
      ar: 'لون',
      it: 'Colore',
      pt: 'Cor',
      hi: 'रंग',
      tr: 'Renk',
      pl: 'Kolor',
      id: 'Warna',
      vi: 'Màu sắc',
      uk: 'Колір',
    }),
    highlightHeading: t({
      en: 'Highlight',
      'en-GB': 'Highlight',
      fr: 'Surlignage',
      es: 'Resaltado',
      ru: 'Выделение',
      ja: 'ハイライト',
      ko: '강조',
      zh: '高亮',
      de: 'Hervorhebung',
      ar: 'تمييز',
      it: 'Evidenziato',
      pt: 'Destaque',
      hi: 'हाइलाइट',
      tr: 'Vurgu',
      pl: 'Wyróżnienie',
      id: 'Sorotan',
      vi: 'Tô sáng',
      uk: 'Виділення',
    }),
    colorDefault: t({
      en: 'Default',
      'en-GB': 'Default',
      fr: 'Par défaut',
      es: 'Por defecto',
      ru: 'По умолчанию',
      ja: 'デフォルト',
      ko: '기본값',
      zh: '默认',
      de: 'Standard',
      ar: 'افتراضي',
      it: 'Predefinito',
      pt: 'Padrão',
      hi: 'डिफ़ॉल्ट',
      tr: 'Varsayılan',
      pl: 'Domyślny',
      id: 'Bawaan',
      vi: 'Mặc định',
      uk: 'За замовчуванням',
    }),
    colorPrimary: t({
      en: 'Primary',
      'en-GB': 'Primary',
      fr: 'Primaire',
      es: 'Primario',
      ru: 'Первичный',
      ja: 'プライマリ',
      ko: '기본',
      zh: '主要',
      de: 'Primär',
      ar: 'أساسي',
      it: 'Primario',
      pt: 'Primário',
      hi: 'प्राथमिक',
      tr: 'Birincil',
      pl: 'Podstawowy',
      id: 'Utama',
      vi: 'Chủ đạo',
      uk: 'Основний',
    }),
    colorSecondary: t({
      en: 'Secondary',
      'en-GB': 'Secondary',
      fr: 'Secondaire',
      es: 'Secundario',
      ru: 'Вторичный',
      ja: 'セカンダリ',
      ko: '보조',
      zh: '次要',
      de: 'Sekundär',
      ar: 'ثانوي',
      it: 'Secondario',
      pt: 'Secundário',
      hi: 'द्वितीयक',
      tr: 'İkincil',
      pl: 'Drugorzędny',
      id: 'Sekunder',
      vi: 'Phụ',
      uk: 'Другорядний',
    }),
    colorSuccess: t({
      en: 'Success',
      'en-GB': 'Success',
      fr: 'Succès',
      es: 'Éxito',
      ru: 'Успех',
      ja: '成功',
      ko: '성공',
      zh: '成功',
      de: 'Erfolg',
      ar: 'نجاح',
      it: 'Successo',
      pt: 'Sucesso',
      hi: 'सफलता',
      tr: 'Başarılı',
      pl: 'Sukces',
      id: 'Sukses',
      vi: 'Thành công',
      uk: 'Успіх',
    }),
    colorWarning: t({
      en: 'Warning',
      'en-GB': 'Warning',
      fr: 'Avertissement',
      es: 'Advertencia',
      ru: 'Предупреждение',
      ja: '警告',
      ko: '경고',
      zh: '警告',
      de: 'Warnung',
      ar: 'تحذير',
      it: 'Avvertimento',
      pt: 'Aviso',
      hi: 'चेतावनी',
      tr: 'Uyarı',
      pl: 'Ostrzeżenie',
      id: 'Peringatan',
      vi: 'Cảnh báo',
      uk: 'Попередження',
    }),
    colorError: t({
      en: 'Error',
      'en-GB': 'Error',
      fr: 'Erreur',
      es: 'Error',
      ru: 'Ошибка',
      ja: 'エラー',
      ko: '오류',
      zh: '错误',
      de: 'Fehler',
      ar: 'خطأ',
      it: 'Errore',
      pt: 'Erro',
      hi: 'त्रुटि',
      tr: 'Hata',
      pl: 'Błąd',
      id: 'Kesalahan',
      vi: 'Lỗi',
      uk: 'Помилка',
    }),
    colorNeutral: t({
      en: 'Neutral',
      'en-GB': 'Neutral',
      fr: 'Neutre',
      es: 'Neutro',
      ru: 'Нейтральный',
      ja: 'ニュートラル',
      ko: '중립',
      zh: '中性',
      de: 'Neutral',
      ar: 'محايد',
      it: 'Neutro',
      pt: 'Neutro',
      hi: 'तटस्थ',
      tr: 'Nötr',
      pl: 'Neutralny',
      id: 'Netral',
      vi: 'Trung tính',
      uk: 'Нейтральний',
    }),
    link: t({
      en: 'Link',
      'en-GB': 'Link',
      fr: 'Lien',
      es: 'Enlace',
      ru: 'Ссылка',
      ja: 'リンク',
      ko: '링크',
      zh: '链接',
      de: 'Link',
      ar: 'رابط',
      it: 'Link',
      pt: 'Link',
      hi: 'लिंक',
      tr: 'Bağlantı',
      pl: 'Link',
      id: 'Tautan',
      vi: 'Liên kết',
      uk: 'Посилання',
    }),
    linkPlaceholder: t({
      en: 'Paste a link',
      'en-GB': 'Paste a link',
      fr: 'Coller un lien',
      es: 'Pegar un enlace',
      ru: 'Вставьте ссылку',
      ja: 'リンクを貼り付け',
      ko: '링크 붙여넣기',
      zh: '粘贴链接',
      de: 'Link einfügen',
      ar: 'الصق رابطًا',
      it: 'Incolla un link',
      pt: 'Cole um link',
      hi: 'लिंक पेस्ट करें',
      tr: 'Bağlantı yapıştırın',
      pl: 'Wklej link',
      id: 'Tempel tautan',
      vi: 'Dán liên kết',
      uk: 'Вставте посилання',
    }),
    removeLink: t({
      en: 'Remove link',
      'en-GB': 'Remove link',
      fr: 'Supprimer le lien',
      es: 'Eliminar enlace',
      ru: 'Удалить ссылку',
      ja: 'リンクを削除',
      ko: '링크 제거',
      zh: '移除链接',
      de: 'Link entfernen',
      ar: 'إزالة الرابط',
      it: 'Rimuovi link',
      pt: 'Remover link',
      hi: 'लिंक हटाएं',
      tr: 'Bağlantıyı kaldır',
      pl: 'Usuń link',
      id: 'Hapus tautan',
      vi: 'Xóa liên kết',
      uk: 'Видалити посилання',
    }),
    applyLink: t({
      en: 'Apply link',
      'en-GB': 'Apply link',
      fr: 'Appliquer le lien',
      es: 'Aplicar enlace',
      ru: 'Применить ссылку',
      ja: 'リンクを適用',
      ko: '링크 적용',
      zh: '应用链接',
      de: 'Link anwenden',
      ar: 'تطبيق الرابط',
      it: 'Applica link',
      pt: 'Aplicar link',
      hi: 'लिंक लागू करें',
      tr: 'Bağlantıyı uygula',
      pl: 'Zastosuj link',
      id: 'Terapkan tautan',
      vi: 'Áp dụng liên kết',
      uk: 'Застосувати посилання',
    }),
    askAI: t({
      en: 'Ask AI',
      'en-GB': 'Ask AI',
      fr: "Demander à l'IA",
      es: 'Preguntar a la IA',
      ru: 'Спросить ИИ',
      ja: 'AI に質問',
      ko: 'AI에 질문',
      zh: '询问 AI',
      de: 'KI fragen',
      ar: 'اسأل الذكاء الاصطناعي',
      it: "Chiedi all'IA",
      pt: 'Perguntar à IA',
      hi: 'एआई से पूछें',
      tr: 'Yapay Zekaya Sor',
      pl: 'Zapytaj AI',
      id: 'Tanya AI',
      vi: 'Hỏi AI',
      uk: 'Запитати ШІ',
    }),
    replaceSelection: t({
      en: 'Replace selection',
      'en-GB': 'Replace selection',
      fr: 'Remplacer la sélection',
      es: 'Reemplazar selección',
      ru: 'Заменить выделенное',
      ja: '選択範囲を置換',
      ko: '선택 항목 바꾸기',
      zh: '替换选择',
      de: 'Auswahl ersetzen',
      ar: 'استبدال التحديد',
      it: 'Sostituisci selezione',
      pt: 'Substituir seleção',
      hi: 'चयन बदलें',
      tr: 'Seçimi değiştir',
      pl: 'Zastąp zaznaczenie',
      id: 'Ganti pilihan',
      vi: 'Thay thế lựa chọn',
      uk: 'Замінити виділене',
    }),
    insertBelow: t({
      en: 'Insert below',
      'en-GB': 'Insert below',
      fr: 'Insérer en dessous',
      es: 'Insertar debajo',
      ru: 'Вставить ниже',
      ja: '下に挿入',
      ko: '아래에 삽입',
      zh: '插在下方',
      de: 'Unten einfügen',
      ar: 'إدراج أدناه',
      it: 'Inserisci sotto',
      pt: 'Inserir abaixo',
      hi: 'नीचे डालें',
      tr: 'Altına ekle',
      pl: 'Wstaw poniżej',
      id: 'Sisipkan di bawah',
      vi: 'Chèn vào bên dưới',
      uk: 'Вставити нижче',
    }),
    discard: t({
      en: 'Discard',
      'en-GB': 'Discard',
      fr: 'Abandonner',
      es: 'Descartar',
      ru: 'Отклонить',
      ja: '破棄',
      ko: '삭제',
      zh: '丢弃',
      de: 'Verwerfen',
      ar: 'تجاهل',
      it: 'Scarta',
      pt: 'Descartar',
      hi: 'खारिज करें',
      tr: 'Vazgeç',
      pl: 'Odrzuć',
      id: 'Buang',
      vi: 'Hủy bỏ',
      uk: 'Відхилити',
    }),
    aiError: t({
      en: 'AI error',
      'en-GB': 'AI error',
      fr: "Erreur de l'IA",
      es: 'Error de la IA',
      ru: 'Ошибка ИИ',
      ja: 'AI エラー',
      ko: 'AI 오류',
      zh: 'AI 错误',
      de: 'KI-Fehler',
      ar: 'خطأ الذكاء الاصطناعي',
      it: 'Errore IA',
      pt: 'Erro da IA',
      hi: 'एआई त्रुटि',
      tr: 'Yapay Zeka Hatası',
      pl: 'Błąd AI',
      id: 'Kesalahan AI',
      vi: 'Lỗi AI',
      uk: 'Помилка ШІ',
    }),
    aiThinking: t({
      en: 'AI is thinking',
      'en-GB': 'AI is thinking',
      fr: "L'IA réfléchit",
      es: 'La IA está pensando',
      ru: 'ИИ думает',
      ja: 'AI が考えています',
      ko: 'AI가 생각 중입니다',
      zh: 'AI 正在思考',
      de: 'KI denkt nach',
      ar: 'الذكاء الاصطناعي يفكر',
      it: "L'IA sta pensando",
      pt: 'A IA está pensando',
      hi: 'एआई सोच रहा है',
      tr: 'Yapay Zeka düşünüyor',
      pl: 'AI myśli',
      id: 'AI sedang berpikir',
      vi: 'AI đang suy nghĩ',
      uk: 'ШІ думає',
    }),
    tellAI: t({
      en: 'Tell AI what to do next',
      'en-GB': 'Tell AI what to do next',
      fr: "Dites à l'IA quoi faire ensuite",
      es: 'Dígale a la IA qué hacer a continuación',
      ru: 'Скажите ИИ, что делать дальше',
      ja: '次に何をすべきか AI に指示してください',
      ko: 'AI에게 다음에 해야 할 일을 지시하세요',
      zh: '告诉 AI 下一步该做什么',
      de: 'Sagen Sie der KI, was sie als nächstes tun soll',
      ar: 'أخبر الذكاء الاصطناعي بما يجب فعله بعد ذلك',
      it: "Di' all'IA cosa fare dopo",
      pt: 'Diga à IA o que fazer a seguir',
      hi: 'एआई को बताएं कि आगे क्या करना है',
      tr: 'Yapay Zekaya bir sonraki adımı söyleyin',
      pl: 'Powiedz AI, co robić dalej',
      id: 'Beri tahu AI apa yang harus dilakukan selanjutnya',
      vi: 'Cho AI biết cần làm gì tiếp theo',
      uk: 'Скажіть ШІ, що робити далі',
    }),
    askAIToEdit: t({
      en: 'Ask AI to edit or generate...',
      'en-GB': 'Ask AI to edit or generate...',
      fr: "Demander à l'IA de modifier ou de générer...",
      es: 'Preguntar a la IA para editar o generar...',
      ru: 'Попросите ИИ изменить или создать...',
      ja: 'AI に編集または生成を依頼...',
      ko: 'AI에게 편집 또는 생성을 요청하세요...',
      zh: '请求 AI 进行编辑或生成...',
      de: 'Bitten Sie die KI zu bearbeiten oder zu generieren...',
      ar: 'طلب تعديل أو إنشاء من الذكاء الاصطناعي...',
      it: "Chiedi all'IA di modificare o generare...",
      pt: 'Peça à IA para editar ou gerar...',
      hi: 'एआई को संपादित या जनरेट करने के लिए कहें...',
      tr: 'Yapay Zekadan düzenlemesini veya oluşturmasını isteyin...',
      pl: 'Poproś AI o edycję lub wygenerowanie...',
      id: 'Minta AI untuk mengedit atau membuat...',
      vi: 'Yêu cầu AI chỉnh sửa hoặc tạo...',
      uk: 'Попросіть ШІ редагувати або створити...',
    }),
    send: t({
      en: 'Send',
      'en-GB': 'Send',
      fr: 'Envoyer',
      es: 'Enviar',
      ru: 'Отправить',
      ja: '送信',
      ko: '전송',
      zh: '发送',
      de: 'Senden',
      ar: 'إرسال',
      it: 'Invia',
      pt: 'Enviar',
      hi: 'भेजें',
      tr: 'Gönder',
      pl: 'Wyślij',
      id: 'Kirim',
      vi: 'Gửi',
      uk: 'Надіслати',
    }),
    editHeading: t({
      en: 'Edit or review selection',
      'en-GB': 'Edit or review selection',
      fr: 'Modifier ou réviser la sélection',
      es: 'Editar o revisar la selección',
      ru: 'Редактировать или проверить выделенное',
      ja: '選択範囲の編集または確認',
      ko: '선택 영역 편집 또는 검토',
      zh: '编辑或审查选择',
      de: 'Auswahl bearbeiten oder überprüfen',
      ar: 'تعديل أو مراجعة التحديد',
      it: 'Modifica o rivedi la selezione',
      pt: 'Editar ou revisar a seleção',
      hi: 'चयन संपादित करें या समीक्षा करें',
      tr: 'Seçimi düzenleyin veya inceleyin',
      pl: 'Edytuj lub przejrzyj zaznaczenie',
      id: 'Edit atau tinjau pilihan',
      vi: 'Chỉnh sửa hoặc đánh giá lựa chọn',
      uk: 'Редагувати або переглянути виділене',
    }),
    improveWriting: t({
      en: 'Improve writing',
      'en-GB': 'Improve writing',
      fr: "Améliorer l'écriture",
      es: 'Mejorar la escritura',
      ru: 'Улучшить текст',
      ja: '文章を改善',
      ko: '작성 글 개선',
      zh: '改善写作',
      de: 'Schreiben verbessern',
      ar: 'تحسين الكتابة',
      it: 'Migliora la scrittura',
      pt: 'Melhorar a escrita',
      hi: 'लेखन में सुधार करें',
      tr: 'Yazımı geliştir',
      pl: 'Popraw styl',
      id: 'Tingkatkan penulisan',
      vi: 'Cải thiện cách viết',
      uk: 'Покращити текст',
    }),
    fixGrammar: t({
      en: 'Fix grammar',
      'en-GB': 'Fix grammar',
      fr: 'Corriger la grammaire',
      es: 'Corregir la gramática',
      ru: 'Исправить грамматику',
      ja: '文法を修正',
      ko: '문법 교정',
      zh: '纠正语法',
      de: 'Grammatik korrigieren',
      ar: 'تصحيح القواعد',
      it: 'Correggi la grammatica',
      pt: 'Corrigir gramática',
      hi: 'व्याकरण ठीक करें',
      tr: 'Dilbilgisini düzelt',
      pl: 'Popraw gramatykę',
      id: 'Perbaiki tata bahasa',
      vi: 'Sửa ngữ pháp',
      uk: 'Виправити граматику',
    }),
    makeShorter: t({
      en: 'Make shorter',
      'en-GB': 'Make shorter',
      fr: 'Rendre plus court',
      es: 'Hacer más corto',
      ru: 'Сделать короче',
      ja: '短縮する',
      ko: '더 짧게',
      zh: '缩短',
      de: 'Kürzen',
      ar: 'جعله أقصر',
      it: 'Rendi più corto',
      pt: 'Tornar mais curto',
      hi: 'छोटा करें',
      tr: 'Kısalt',
      pl: 'Skróć',
      id: 'Perpendek',
      vi: 'Làm ngắn lại',
      uk: 'Зробити коротшим',
    }),
    makeLonger: t({
      en: 'Make longer',
      'en-GB': 'Make longer',
      fr: 'Rendre plus long',
      es: 'Hacer más largo',
      ru: 'Сделать длиннее',
      ja: '詳細にする',
      ko: '더 길게',
      zh: '拉长',
      de: 'Verlängern',
      ar: 'جعله أطول',
      it: 'Rendi più lungo',
      pt: 'Tornar mais longo',
      hi: 'बड़ा करें',
      tr: 'Uzat',
      pl: 'Wydłuż',
      id: 'Perpanjang',
      vi: 'Làm dài ra',
      uk: 'Зробити довшим',
    }),
    moreHeading: t({
      en: 'Use AI to do more',
      'en-GB': 'Use AI to do more',
      fr: "Utiliser l'IA pour en faire plus",
      es: 'Usar la IA para hacer más',
      ru: 'Сделать больше с помощью ИИ',
      ja: 'AI でさらに行う',
      ko: 'AI로 추가 작업 수행',
      zh: '利用 AI 做更多',
      de: 'Verwenden Sie KI, um mehr zu tun',
      ar: 'استخدم الذكاء الاصطناعي لعمل المزيد',
      it: "Usa l'IA per fare di più",
      pt: 'Usar IA para fazer mais',
      hi: 'एआई का अधिक उपयोग करें',
      tr: 'Yapay Zeka ile daha fazlasını yapın',
      pl: 'Użyj AI, aby zrobić więcej',
      id: 'Gunakan AI untuk melakukan lebih banyak',
      vi: 'Sử dụng AI để làm nhiều hơn',
      uk: 'Використовуйте ШІ, щоб зробити більше',
    }),
    continueWriting: t({
      en: 'Continue writing',
      'en-GB': 'Continue writing',
      fr: 'Continuer à écrire',
      es: 'Continuar escribiendo',
      ru: 'Продолжить писать',
      ja: '執筆を継続',
      ko: '이어 쓰기',
      zh: '继续写作',
      de: 'Weiter schreiben',
      ar: 'مواصلة الكتابة',
      it: 'Continua a scrivere',
      pt: 'Continuar a escrever',
      hi: 'लिखना जारी रखें',
      tr: 'Yazmaya devam et',
      pl: 'Kontynuuj pisanie',
      id: 'Lanjutkan menulis',
      vi: 'Tiếp tục viết',
      uk: 'Продовжити писати',
    }),
  },
  title: 'Markdown Editor',
  description:
    'Content strings used for the Markdown Editor component, including slash command suggestions, color selectors, link selectors, and AI generation tools.',
  tags: ['markdown', 'editor', 'component'],
} satisfies Dictionary;

export default markdownEditorContent;
