import { type Dictionary, t } from 'intlayer';

type WhyToChoseIntlayerContent = {
  title: string;
  content: {
    title: string;
    description: string;
    iconKey: string;
  }[];
};

const whyToChoseIntlayerContent = {
  key: 'why-to-chose-intlayer-section',
  content: {
    title: t({
      en: 'Why to chose Inlyayer?',
      'en-GB': 'Why to chose Inlyayer?',
      fr: 'Pourquoi choisir Intlayer ?',
      es: '¿Por qué elegir Intlayer?',
      de: 'Warum Intlayer wählen?',
      ja: 'Intlayerを選ぶ理由は？',
      ko: 'Intlayer를 선택하는 이유는 무엇입니까?',
      zh: '为什么选择Intlayer？',
      it: 'Perché scegliere Intlayer?',
      pt: 'Por que escolher o Intlayer?',
      hi: 'Intlayer को क्यों चुनें?',
      ar: 'لماذا تختار Intlayer؟',
      ru: 'Почему стоит выбрать Intlayer?',
      tr: "Neden Intlayer'ı seçmelisiniz?",
    }),
    content: [
      {
        title: t({
          en: 'Free and Open Source',
          'en-GB': 'Free and Open Source',
          es: 'Gratis y de Código Abierto',
          fr: 'Gratuit et Open Source',
          de: 'Kostenlos und Open Source',
          ja: '無料でオープンソース',
          ko: '무료 및 오픈 소스',
          zh: '免费和开源',
          it: 'Gratuito e Open Source',
          pt: 'Grátis e Código Aberto',
          hi: 'नि:शुल्क और ओपन सोर्स',
          ar: 'مجاني ومفتوح المصدر',
          ru: 'Бесплатно и с открытым исходным кодом',
          tr: 'Ücretsiz ve Açık Kaynak',
        }),
        description: t({
          en: 'Intlayer is free and open source, allowing you to use it for free and contribute to suit your needs.',
          'en-GB':
            'Intlayer is free and open source, allowing you to use it for free and contribute to suit your needs.',
          es: 'Intlayer es gratuito y de código abierto, lo que le permite usarlo gratuitamente y contribuir a adaptarse a sus necesidades.',
          fr: "Intlayer est gratuit et open source, vous permettant de l'utiliser gratuitement et de contribuer à son bon fonctionnement.",
          de: 'Intlayer ist kostenlos und Open Source, wodurch Sie es kostenlos nutzen und anpassen können.',
          ja: 'Intlayerは無料でオープンソースであり、無料で使用し、ニーズに合わせて貢献することができます。',
          ko: 'Intlayer는 무료이자 오픈소스이며, 무료로 사용하고 필요한 대로 기여할 수 있습니다.',
          zh: 'Intlayer是免费的开源软件，允许你免费使用并做出适合你需求的贡献。',
          it: 'Intlayer è gratuito e open source, permettendoti di usarlo gratuitamente e contribuire per adattarlo alle tue esigenze.',
          pt: 'O Intlayer é gratuito e de código aberto, permitindo que você o use gratuitamente e contribua para atendê-lo às suas necessidades.',
          hi: 'Intlayer नि:शुल्क और ओपन-सोर्स है, जिससे आप इसे मुफ्त में उपयोग कर सकते हैं और अपनी आवश्यकताओं के अनुसार योगदान कर सकते हैं।',
          ar: 'Intlayer مجاني ومفتوح المصدر، مما يتيح لك استخدامه مجانًا والمساهمة وفقًا لاحتياجاتك.',
          ru: 'Intlayer бесплатен и с открытым исходным кодом, что позволяет вам использовать его бесплатно и вносить изменения по мере необходимости.',
          tr: 'Intlayer ücretsiz ve açık kaynaklıdır, böylece ücretsiz kullanabilir ve ihtiyaçlarınıza göre katkıda bulunabilirsiniz.',
        }),
        iconKey: 'free',
      },
      {
        title: t({
          en: 'JavaScript-Powered Content Management',
          'en-GB': 'JavaScript-Powered Content Management',
          es: 'Gestión de Contenido Impulsada por JavaScript',
          fr: 'Gestion de Contenu Propulsée par JavaScript',
          de: 'JavaScript-gestützte Inhaltsverwaltung',
          ja: 'JavaScriptによるコンテンツ管理',
          ko: 'JavaScript 기반의 콘텐츠 관리',
          zh: '基于JavaScript的内容管理',
          it: 'Gestione dei contenuti potenziata da JavaScript',
          pt: 'Gerenciamento de Conteúdo Impulsionado por JavaScript',
          hi: 'JavaScript संचालित सामग्री प्रबंधन',
          ar: 'إدارة المحتوى المدعومة من JavaScript',
          ru: 'Управление контентом на базе JavaScript',
          tr: 'JavaScript Destekli İçerik Yönetimi',
        }),
        description: t({
          en: 'Harness the flexibility of JavaScript to define and manage your content efficiently.',
          'en-GB':
            'Harness the flexibility of JavaScript to define and manage your content efficiently.',
          es: 'Aprovecha la flexibilidad de JavaScript para definir y gestionar tu contenido eficientemente.',
          fr: 'Exploitez la flexibilité de JavaScript pour définir et gérer votre contenu efficacement.',
          de: 'Nutzen Sie die Flexibilität von JavaScript, um Ihren Inhalt effizient zu definieren und zu verwalten.',
          ja: 'JavaScriptの柔軟性を活用して、コンテンツを効率的に定義し管理できます。',
          ko: 'JavaScript의 유연성을 활용하여 콘텐츠를 효율적으로 정의하고 관리하십시오.',
          zh: '利用JavaScript的灵活性高效地定义和管理您的内容。',
          it: 'Sfrutta la flessibilità di JavaScript per definire e gestire i tuoi contenuti in modo efficiente.',
          pt: 'Aproveite a flexibilidade do JavaScript para definir e gerenciar seu conteúdo de forma eficiente.',
          hi: 'JavaScript की लचीलापन का लाभ उठाकर, अपनी सामग्री को प्रभावी ढंग से परिभाषित और प्रबंधित करें।',
          ar: 'استفد من مرونة JavaScript لتعريف وإدارة المحتوى الخاص بك بكفاءة.',
          ru: 'Используйте гибкость JavaScript, чтобы эффективно определять и управлять своим контентом.',
          tr: "JavaScript'in esnekliğini kullanarak içeriğinizi verimli bir şekilde tanımlayın ve yönetin.",
        }),
        iconKey: 'code',
      },
      {
        title: t({
          en: 'Type-Safe Environment',
          'en-GB': 'Type-Safe Environment',
          es: 'Type-Safe Entorno',
          fr: 'Type-Safe Environnement',
          de: 'Typsicher Umgebung',
          ja: 'タイプセーフ環境',
          ko: '타입 안전한 환경',
          zh: '类型安全环境',
          it: 'Ambiente Type-Safe',
          pt: 'Ambiente Type-Safe',
          hi: 'टाइप-सुरक्षित वातावरण',
          ar: 'بيئة آمنة من نوعها',
          ru: 'Типобезопасная среда',
          tr: 'Tip Güvenli Ortam',
        }),
        description: t({
          en: 'Leverage TypeScript to ensure all your content definitions are precise and error-free.',
          'en-GB':
            'Leverage TypeScript to ensure all your content definitions are precise and error-free.',
          es: 'Utiliza TypeScript para asegurar que todas tus definiciones de contenido sean precisas y sin errores.',
          fr: "Utilisez TypeScript pour garantir que toutes vos définitions de contenu soient précises et exemptes d'erreurs.",
          de: 'Nutzen Sie TypeScript, um sicherzustellen, dass alle Ihre Inhaltsdefinitionen präzise und fehlerfrei sind.',
          ja: 'TypeScriptを活用して、すべてのコンテンツ定義が正確でエラーがないことを保証します。',
          ko: 'TypeScript를 활용하여 모든 콘텐츠 정의가 정확하고 오류가 없도록 합니다.',
          zh: '利用TypeScript确保您所有的内容定义都是准确且没有错误的。',
          it: 'Sfrutta TypeScript per garantire che tutte le tue definizioni di contenuto siano precise e prive di errori.',
          pt: 'Aproveite o TypeScript para garantir que todas as suas definições de conteúdo sejam precisas e sem erros.',
          hi: 'TypeScript का लाभ उठाएं ताकि आपकी सभी सामग्री परिभाषाएँ सटीक और त्रुटि-मुक्त हों।',
          ar: 'استفد من TypeScript لضمان دقة جميع تعريفات المحتوى الخاصة بك وخلوها من الأخطاء.',
          ru: 'Используйте TypeScript, чтобы гарантировать, что все ваши определения контента точны и свободны от ошибок.',
          tr: "TypeScript'i kullanarak tüm içerik tanımlarınızın kesin ve hatasız olmasını sağlayın.",
        }),
        iconKey: 'type',
      },
      {
        title: t({
          en: 'Declaration at the component level',
          'en-GB': 'Declaration at the component level',
          es: 'Declaración a nivel de componente',
          fr: 'Declaration au niveau du component',
          de: 'Deklaration auf Komponentenebene',
          ja: 'コンポーネントレベルでの宣言',
          ko: '구성 요소 수준에서의 선언',
          zh: '组件级别的声明',
          it: 'Dichiarazione a livello di componente',
          pt: 'Declaração no nível do componente',
          hi: 'घटक स्तर पर घोषणा',
          ar: 'إعلان على مستوى المكون',
          ru: 'Декларация на уровне компонента',
          tr: 'Bileşen düzeyinde beyan',
        }),
        description: t({
          en: 'Keep your translations close to their respective components, enhancing maintainability and clarity.',
          'en-GB':
            'Keep your translations close to their respective components, enhancing maintainability and clarity.',
          es: 'Mantén tus traducciones cerca de sus respectivos componentes, mejorando la mantenibilidad y claridad.',
          fr: 'Gardez vos traductions proches de leurs composants respectifs, améliorant la maintenabilité et la clarté.',
          de: 'Halten Sie Ihre Übersetzungen in der Nähe ihrer jeweiligen Komponenten, um die Wartbarkeit und Klarheit zu verbessern.',
          ja: '翻訳をそれぞれのコンポーネントの近くに保ち、保守性と明瞭性を高めます。',
          ko: '번역을 각 구성 요소의 가까운 곳에 두어 유지 관리성과 명확성을 향상시킵니다.',
          zh: '将翻译保留在各自组件附近，从而提高可维护性和清晰度。',
          it: 'Mantieni le tue traduzioni vicino ai rispettivi componenti, migliorando la manutenibilità e la chiarezza.',
          pt: 'Mantenha suas traduções perto de seus respectivos componentes, melhorando a manutenibilidade e a clareza.',
          hi: 'अपनी अनुवादों को उनके संबंधित घटकों के करीब रखें, जिससे रखरखाव और स्पष्टता में सुधार होता है।',
          ar: 'احتفظ بترجمتك بالقرب من مكوناتها الخاصة، مما يعزز القابلية للصيانة والوضوح.',
          ru: 'Держите переводы рядом с соответствующими компонентами, улучшая поддерживаемость и ясность.',
          tr: 'Çevirilerinizi ilgili bileşenlerine yakın tutarak sürdürülebilirliği ve netliği artırın.',
        }),
        iconKey: 'file-tree',
      },
      {
        title: t({
          en: 'Simplified Setup',
          'en-GB': 'Simplified Setup',
          es: 'Configuración Simplificada',
          fr: 'Configuration Simplifiée',
          de: 'Vereinfachte Einrichtung',
          ja: '簡素化されたセットアップ',
          ko: '단순화된 설정',
          zh: '简化的设置',
          it: 'Configurazione Semplificata',
          pt: 'Configuração Simplificada',
          hi: 'सरल सेटअप',
          ar: 'إعداد مبسط',
          ru: 'Упрощенный процесс настройки',
          tr: 'Basitleştirilmiş Kurulum',
        }),
        description: t({
          en: 'Get up and running quickly with minimal configuration, especially optimized for Next.js projects.',
          'en-GB':
            'Get up and running quickly with minimal configuration, especially optimized for Next.js projects.',
          es: 'Ponte en marcha rápidamente con una configuración mínima, especialmente optimizado para proyectos Next.js.',
          fr: 'Mettez-vous en route rapidement avec une configuration minimale, spécialement optimisée pour les projets Next.js.',
          de: 'Fangen Sie schnell an und laufen Sie mit minimaler Konfiguration, die speziell für Next.js-Projekte optimiert ist.',
          ja: '最小限の設定で迅速に立ち上がり、特にNext.jsプロジェクトに最適化されています。',
          ko: '최소한의 구성으로 빠르게 시작하고 운영하십시오. 특히 Next.js 프로젝트에 최적화되어 있습니다.',
          zh: '快速启动并运行，配置最小，特别为Next.js项目进行了优化。',
          it: 'Avvia rapidamente con configurazione minima, ottimizzata soprattutto per progetti Next.js.',
          pt: 'Comece a funcionar rapidamente com configuração mínima, especialmente otimizada para projetos Next.js.',
          hi: 'न्यूनतम कॉन्फ़िगरेशन के साथ जल्दी सेटअप करें, विशेष रूप से Next.js परियोजनाओं के लिए अनुकूलित।',
          ar: 'ابدأ بسرعة مع الحد الأدنى من التكوين، مع تحسين خاص لمشاريع Next.js.',
          ru: 'Быстро начните работу с минимальной настройкой, особенно оптимизированной для проектов Next.js.',
          tr: 'Özellikle Next.js projeleri için optimize edilmiş, minimum yapılandırma ile hızlıca başlayın.',
        }),
        iconKey: 'timer',
      },
      {
        title: t({
          en: 'Integrated CMS',
          'en-GB': 'Integrated CMS',
          es: 'CMS Integrado',
          fr: 'CMS Intégré',
          de: 'Integriertes CMS',
          ja: '統合CMS',
          ko: '통합된 CMS',
          zh: '集成CMS',
          it: 'CMS Integrato',
          pt: 'CMS Integrado',
          hi: 'एकीकृत CMS',
          ar: 'CMS متكامل',
          ru: 'Интегрированная CMS',
          tr: 'Entegre CMS',
        }),
        description: t({
          en: 'Edit your content on your website with an integrated CMS directly on your website. Boost content generation thanks to AI.',
          'en-GB':
            'Edit your content on your website with an integrated CMS directly on your website. Boost content generation thanks to AI.',
          es: 'Edite sus contenidos con un CMS directamente integrado en su sitio web. Aumente la generación de contenido gracias a la IA.',
          fr: "Editez vos contenus à l'aide un CMS directement intégré à votre site. Boostez la generation de contenu grâce à l'IA.",
          de: 'Bearbeiten Sie Ihre Inhalte auf Ihrer Website mit einem direkt integrierten CMS. Steigern Sie die Inhaltserstellung dank KI.',
          ja: 'ウェブサイト上で直接統合CMSを使用して、コンテンツを編集します。AIを活用してコンテンツ生成を強化します。',
          ko: '웹사이트에서 직접 통합된 CMS로 콘텐츠를 편집하세요. AI 덕분에 콘텐츠 생성을 향상시키십시오.',
          zh: '通过网站上集成的CMS直接编辑网站上的内容。依靠AI推动内容生成。',
          it: "Modifica i tuoi contenuti sul tuo sito web con un CMS integrato direttamente sul tuo sito. Aumenta la generazione di contenuti grazie all'IA.",
          pt: 'Edite seu conteúdo em seu site com um CMS integrado diretamente em seu site. Aumente a geração de conteúdo graças à IA.',
          hi: 'अपनी वेबसाइट पर एकीकृत CMS के साथ अपने सामग्री को संपादित करें। AI के माध्यम से सामग्री निर्माण को बढ़ावा दें।',
          ar: 'قم بتحرير المحتوى الخاص بك على موقع الويب الخاص بك باستخدام نظام إدارة المحتوى المتكامل مباشرة على موقع الويب الخاص بك. عزز إنتاج المحتوى بفضل الذكاء الاصطناعي.',
          ru: 'Редактируйте свой контент на своем сайте с помощью интегрированной CMS непосредственно на вашем сайте. Ускорьте создание контента благодаря ИИ.',
          tr: 'Entegre CMS ile web sitenizdeki içeriğinizi doğrudan web sitenizde düzenleyin. Yapay zeka sayesinde içerik üretimini artırın.',
        }),
        iconKey: 'cms',
      },
    ],
  },
} satisfies Dictionary<WhyToChoseIntlayerContent>;

export default whyToChoseIntlayerContent;
