import { type Dictionary, t } from 'intlayer';

const adminBreadcrumbContent = {
  key: 'admin-breadcrumb',
  content: {
    home: t({
      en: 'Dashboard',
      fr: 'Tableau de bord',
      es: 'Panel de control',
      'en-GB': 'Dashboard',
      de: 'Dashboard',
      ja: 'ダッシュボード',
      ko: '대시보드',
      zh: '仪表板',
      it: 'Dashboard',
      pt: 'Painel',
      hi: 'डैशबोर्ड',
      ar: 'لوحة التحكم',
      ru: 'Панель управления',
      tr: 'Kontrol Paneli',
    }),
    users: t({
      en: 'Users',
      fr: 'Utilisateurs',
      es: 'Usuarios',
      'en-GB': 'Users',
      de: 'Benutzer',
      ja: 'ユーザー',
      ko: '사용자',
      zh: '用户',
      it: 'Utenti',
      pt: 'Usuários',
      hi: 'उपयोगकर्ता',
      ar: 'المستخدمون',
      ru: 'Пользователи',
      tr: 'Kullanıcılar',
    }),
    organizations: t({
      en: 'Organizations',
      fr: 'Organisations',
      es: 'Organizaciones',
      'en-GB': 'Organisations',
      de: 'Organisationen',
      ja: '組織',
      ko: '조직',
      zh: '组织',
      it: 'Organizzazioni',
      pt: 'Organizações',
      hi: 'संगठन',
      ar: 'المنظمات',
      ru: 'Организации',
      tr: 'Kuruluşlar',
    }),
    projects: t({
      en: 'Projects',
      fr: 'Projets',
      es: 'Proyectos',
      'en-GB': 'Projects',
      de: 'Projekte',
      ja: 'プロジェクト',
      ko: '프로젝트',
      zh: '项目',
      it: 'Progetti',
      pt: 'Projetos',
      hi: 'परियोजनाएं',
      ar: 'المشاريع',
      ru: 'Проекты',
      tr: 'Projeler',
    }),
    dashboard: t({
      en: 'Dashboard',
      fr: 'Tableau de bord',
      es: 'Panel de control',
      'en-GB': 'Dashboard',
      de: 'Dashboard',
      ja: 'ダッシュボード',
      ko: '대시보드',
      zh: '仪表板',
      it: 'Dashboard',
      pt: 'Painel',
      hi: 'डैशबोर्ड',
      ar: 'لوحة التحكم',
      ru: 'Панель управления',
      tr: 'Kontrol Paneli',
    }),
    userDetail: t({
      en: 'User Details',
      fr: 'Détails utilisateur',
      es: 'Detalles del usuario',
      'en-GB': 'User Details',
      de: 'Benutzerdetails',
      ja: 'ユーザー詳細',
      ko: '사용자 세부정보',
      zh: '用户详情',
      it: 'Dettagli utente',
      pt: 'Detalhes do usuário',
      hi: 'उपयोगकर्ता विवरण',
      ar: 'تفاصيل المستخدم',
      ru: 'Детали пользователя',
      tr: 'Kullanıcı Detayları',
    }),
  },
} satisfies Dictionary;

export default adminBreadcrumbContent;
