/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index';
import { Route as Char123LocaleChar125RouteRouteImport } from './routes/{-$locale}/route';
import { Route as ApiBaiduPushRouteImport } from './routes/api/baidu-push';
import { Route as ApiHealthRouteImport } from './routes/api/health';
import { Route as FeedDotxmlRouteImport } from './routes/feed[.]xml';
import { Route as PostsDotjsonRouteImport } from './routes/posts[.]json';
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt';
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml';

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any);
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any);
const PostsDotjsonRoute = PostsDotjsonRouteImport.update({
  id: '/posts.json',
  path: '/posts.json',
  getParentRoute: () => rootRouteImport,
} as any);
const FeedDotxmlRoute = FeedDotxmlRouteImport.update({
  id: '/feed.xml',
  path: '/feed.xml',
  getParentRoute: () => rootRouteImport,
} as any);
const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: '/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any);
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any);
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiBaiduPushRoute = ApiBaiduPushRouteImport.update({
  id: '/api/baidu-push',
  path: '/api/baidu-push',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren;
  '/feed.xml': typeof FeedDotxmlRoute;
  '/posts.json': typeof PostsDotjsonRoute;
  '/robots.txt': typeof RobotsDottxtRoute;
  '/sitemap.xml': typeof SitemapDotxmlRoute;
  '/api/baidu-push': typeof ApiBaiduPushRoute;
  '/api/health': typeof ApiHealthRoute;
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute;
}
export interface FileRoutesByTo {
  '/feed.xml': typeof FeedDotxmlRoute;
  '/posts.json': typeof PostsDotjsonRoute;
  '/robots.txt': typeof RobotsDottxtRoute;
  '/sitemap.xml': typeof SitemapDotxmlRoute;
  '/api/baidu-push': typeof ApiBaiduPushRoute;
  '/api/health': typeof ApiHealthRoute;
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren;
  '/feed.xml': typeof FeedDotxmlRoute;
  '/posts.json': typeof PostsDotjsonRoute;
  '/robots.txt': typeof RobotsDottxtRoute;
  '/sitemap.xml': typeof SitemapDotxmlRoute;
  '/api/baidu-push': typeof ApiBaiduPushRoute;
  '/api/health': typeof ApiHealthRoute;
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/{-$locale}'
    | '/feed.xml'
    | '/posts.json'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/baidu-push'
    | '/api/health'
    | '/{-$locale}/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/feed.xml'
    | '/posts.json'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/baidu-push'
    | '/api/health'
    | '/{-$locale}';
  id:
    | '__root__'
    | '/{-$locale}'
    | '/feed.xml'
    | '/posts.json'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/baidu-push'
    | '/api/health'
    | '/{-$locale}/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren;
  FeedDotxmlRoute: typeof FeedDotxmlRoute;
  PostsDotjsonRoute: typeof PostsDotjsonRoute;
  RobotsDottxtRoute: typeof RobotsDottxtRoute;
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute;
  ApiBaiduPushRoute: typeof ApiBaiduPushRoute;
  ApiHealthRoute: typeof ApiHealthRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml';
      path: '/sitemap.xml';
      fullPath: '/sitemap.xml';
      preLoaderRoute: typeof SitemapDotxmlRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/robots.txt': {
      id: '/robots.txt';
      path: '/robots.txt';
      fullPath: '/robots.txt';
      preLoaderRoute: typeof RobotsDottxtRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/posts.json': {
      id: '/posts.json';
      path: '/posts.json';
      fullPath: '/posts.json';
      preLoaderRoute: typeof PostsDotjsonRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/feed.xml': {
      id: '/feed.xml';
      path: '/feed.xml';
      fullPath: '/feed.xml';
      preLoaderRoute: typeof FeedDotxmlRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/{-$locale}': {
      id: '/{-$locale}';
      path: '/{-$locale}';
      fullPath: '/{-$locale}';
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/{-$locale}/': {
      id: '/{-$locale}/';
      path: '/';
      fullPath: '/{-$locale}/';
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport;
      parentRoute: typeof Char123LocaleChar125RouteRoute;
    };
    '/api/health': {
      id: '/api/health';
      path: '/api/health';
      fullPath: '/api/health';
      preLoaderRoute: typeof ApiHealthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/baidu-push': {
      id: '/api/baidu-push';
      path: '/api/baidu-push';
      fullPath: '/api/baidu-push';
      preLoaderRoute: typeof ApiBaiduPushRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute;
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
  };

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren
  );

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
  FeedDotxmlRoute: FeedDotxmlRoute,
  PostsDotjsonRoute: PostsDotjsonRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiBaiduPushRoute: ApiBaiduPushRoute,
  ApiHealthRoute: ApiHealthRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { createStart } from '@tanstack/react-start';
import type { getRouter } from './router.tsx';

declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
