import { type Dictionary, t } from 'intlayer';

const passkeyItemContent = {
  key: 'passkey-item',
  content: {
    createdAt: t({
      en: 'Created',
      'en-GB': 'Created',
      fr: 'Créée le',
      es: 'Creada el',
      de: 'Erstellt am',
      ja: '作成日',
      ko: '생성됨',
      zh: '创建于',
      it: 'Creato il',
      pt: 'Criado em',
      hi: 'सृजित',
      ar: 'تم الإنشاء في',
      ru: 'Создано',
      tr: 'Oluşturuldu',
      pl: 'Utworzono',
      id: 'Dibuat',
      vi: 'Được tạo',
    }),
    deletePasskeyButton: {
      text: t({
        en: 'Delete',
        'en-GB': 'Delete',
        fr: 'Supprimer',
        es: 'Eliminar',
        de: 'Löschen',
        ja: '削除',
        ko: '삭제',
        zh: '删除',
        it: 'Elimina',
        pt: 'Excluir',
        hi: 'हटाएं',
        ar: 'حذف',
        ru: 'Удалить',
        tr: 'Sil',
        pl: 'Usuń',
        id: 'Hapus',
        vi: 'Xóa',
      }),
      ariaLabel: t({
        en: 'Click to delete the passkey',
        'en-GB': 'Click to delete the passkey',
        fr: 'Cliquez pour supprimer la clé',
        es: 'Haga clic para eliminar la llave',
        de: 'Klicken Sie, um den Passkey zu löschen',
        ja: 'パスキーを削除するにはクリックしてください',
        ko: '패스키를 삭제하려면 클릭하세요',
        zh: '点击删除通行密钥',
        it: 'Clicca per eliminare la passkey',
        pt: 'Clique para excluir a chave',
        hi: 'पासकी हटाने के लिए क्लिक करें',
        ar: 'انقر لحذف مفتاح المرور',
        ru: 'Нажмите, чтобы удалить ключ доступа',
        tr: 'Parolasız giriş anahtarını silmek için tıklayın',
        pl: 'Kliknij, aby usunąć klucz dostępu',
        id: 'Klik untuk menghapus kunci sandi',
        vi: 'Nhấp để xóa khóa truy cập',
      }),
    },
    confirmDelete: t({
      en: 'Confirm',
      'en-GB': 'Confirm',
      fr: 'Confirmer',
      es: 'Confirmar',
      de: 'Bestätigen',
      ja: '確認',
      ko: '확인',
      zh: '确认',
      it: 'Conferma',
      pt: 'Confirmar',
      hi: 'पुष्टि करें',
      ar: 'تأكيد',
      ru: 'Подтвердить',
      tr: 'Onayla',
      pl: 'Potwierdź',
      id: 'Konfirmasi',
      vi: 'Xác nhận',
    }),
    cancelButton: t({
      en: 'Cancel',
      'en-GB': 'Cancel',
      fr: 'Annuler',
      es: 'Cancelar',
      de: 'Abbrechen',
      ja: 'キャンセル',
      ko: '취소',
      zh: '取消',
      it: 'Annulla',
      pt: 'Cancelar',
      hi: 'रद्द करें',
      ar: 'إلغاء',
      ru: 'Отмена',
      tr: 'İptal',
      pl: 'Anuluj',
      id: 'Batal',
      vi: 'Hủy',
    }),
  },
} satisfies Dictionary;

export default passkeyItemContent;
