import { type Dictionary, t } from 'intlayer';

const passkeyManagementContent = {
  key: 'passkey-management',
  content: {
    description: t({
      en: 'Manage your passkeys for secure, passwordless authentication.',
      'en-GB': 'Manage your passkeys for secure, passwordless authentication.',
      fr: 'Gérez vos clés de sécurité pour une authentification sécurisée sans mot de passe.',
      es: 'Administre sus llaves de acceso para una autenticación segura sin contraseña.',
      de: 'Verwalten Sie Ihre Passkeys für eine sichere, passwortlose Authentifizierung.',
      ja: '安全でパスワード不要の認証のためにパスキーを管理します。',
      ko: '안전하고 비밀번호 없는 인증을 위해 패스키를 관리합니다.',
      zh: '管理您的通行密钥，实现安全、无密码的身份验证。',
      it: "Gestisci le tue passkey per un'autenticazione sicura senza password.",
      pt: 'Gerencie suas chaves de acesso para uma autenticação segura e sem senha.',
      hi: 'सुरक्षित, पासवर्ड-रहित प्रमाणीकरण के लिए अपनी पासकी प्रबंधित करें।',
      ar: 'قم بإدارة مفاتيح المرور الخاصة بك للمصادقة الآمنة بدون كلمة مرور.',
      ru: 'Управляйте своими ключами доступа для безопасной аутентификации без пароля.',
      tr: "Güvenli, şifresiz kimlik doğrulama için Passkey'lerinizi yönetin.",
      pl: 'Zarządzaj kluczami dostępu dla bezpiecznego, bezhasłowego uwierzytelniania.',
      id: 'Kelola kunci sandi Anda untuk otentikasi yang aman dan tanpa kata sandi.',
      vi: 'Quản lý khóa truy cập của bạn cho xác thực an toàn, không mật khẩu.',
    }),
    noPasskeysTitle: t({
      en: 'No passkeys yet',
      'en-GB': 'No passkeys yet',
      fr: 'Aucune clé de sécurité',
      es: 'No hay llaves de acceso todavía',
      de: 'Noch keine Passkeys',
      ja: 'パスキーがありません',
      ko: '아직 패스키 없음',
      zh: '暂无通行密钥',
      it: 'Nessuna passkey presente',
      pt: 'Ainda não há chaves de acesso',
      hi: 'अभी कोई पासकी नहीं है',
      ar: 'لا توجد مفاتيح مرور بعد',
      ru: 'Ключи доступа отсутствуют',
      tr: 'Henüz parolasız giriş anahtarı yok',
      pl: 'Brak kluczy dostępu',
      id: 'Belum ada kunci sandi',
      vi: 'Chưa có khóa truy cập',
    }),
    noPasskeysDescription: t({
      en: 'Add your first passkey for secure, passwordless authentication.',
      'en-GB':
        'Add your first passkey for secure, passwordless authentication.',
      fr: 'Ajoutez votre première clé de sécurité pour une authentification sécurisée sans mot de passe.',
      es: 'Agregue su primera llave de acceso para una autenticación segura sin contraseña.',
      de: 'Fügen Sie Ihren ersten Passkey für eine sichere, passwortlose Authentifizierung hinzu.',
      ja: '安全でパスワード不要の認証のために最初のパスキーを追加しましょう。',
      ko: '안전하고 비밀번호 없는 인증을 위해 첫 패스키를 추가하세요.',
      zh: '添加您的第一个通行密钥，实现安全、无密码的身份验证。',
      it: "Aggiungi la tua prima passkey per un'autenticazione sicura senza password.",
      pt: 'Adicione sua primeira chave de acesso para uma autenticação segura e sem senha.',
      hi: 'सुरक्षित, पासवर्ड-रहित प्रमाणीकरण के लिए अपनी पहली पासकी जोड़ें।',
      ar: 'أضف أول مفتاح مرور خاص بك للمصادقة الآمنة بدون كلمة مرور.',
      ru: 'Добавьте свой первый ключ доступа для безопасной аутентификации без пароля.',
      tr: 'Güvenli, şifresiz kimlik doğrulama için ilk Passkey’inizi ekleyin.',
      pl: 'Dodaj swój pierwszy klucz dostępu dla bezpiecznego, bezhasłowego uwierzytelniania.',
      id: 'Tambahkan kunci sandi pertama Anda untuk otentikasi yang aman dan tanpa kata sandi.',
      vi: 'Thêm khóa truy cập đầu tiên để xác thực an toàn, không mật khẩu.',
    }),
    addPasskeyButton: t({
      en: 'New Passkey',
      'en-GB': 'New Passkey',
      fr: 'Nouvelle clé',
      es: 'Nueva llave',
      de: 'Neuer Passkey',
      ja: '新しいパスキー',
      ko: '새 패스키',
      zh: '新建通行密钥',
      it: 'Nuova passkey',
      pt: 'Nova chave de acesso',
      hi: 'नई पासकी',
      ar: 'مفتاح مرور جديد',
      ru: 'Добавить ключ',
      tr: 'Yeni Parolasız Giriş',
      pl: 'Nowy klucz dostępu',
      id: 'Kunci Sandi Baru',
      vi: 'Khóa truy cập mới',
    }),
    deletePasskeyButton: {
      text: t({
        en: 'Delete',
        'en-GB': 'Delete',
        fr: 'Supprimer',
        es: 'Eliminar',
        de: 'Löschen',
        ja: '削除',
        ko: '삭제',
        zh: '删除',
        it: 'Elimina',
        pt: 'Excluir',
        hi: 'हटाएं',
        ar: 'حذف',
        ru: 'Удалить',
        tr: 'Sil',
        pl: 'Usuń',
        id: 'Hapus',
        vi: 'Xóa',
      }),
      ariaLabel: t({
        en: 'Click to delete the passkey',
        'en-GB': 'Click to delete the passkey',
        fr: 'Cliquez pour supprimer la clé',
        es: 'Haga clic para eliminar la llave',
        de: 'Klicken Sie, um den Passkey zu löschen',
        ja: 'パスキーを削除するにはクリックしてください',
        ko: '패스키를 삭제하려면 클릭하세요',
        zh: '点击删除通行密钥',
        it: 'Clicca per eliminare la passkey',
        pt: 'Clique para excluir a chave',
        hi: 'पासकी हटाने के लिए क्लिक करें',
        ar: 'انقر لحذف مفتاح المرور',
        ru: 'Нажмите, чтобы удалить ключ доступа',
        tr: 'Parolasız giriş anahtarını silmek için tıklayın',
        pl: 'Kliknij, aby usunąć klucz dostępu',
        id: 'Klik untuk menghapus kunci sandi',
        vi: 'Nhấp để xóa khóa truy cập',
      }),
    },
  },
} satisfies Dictionary;

export default passkeyManagementContent;
