import { GithubRoutes, PagesRoutes } from '@/Routes';
import { DocData } from '@components/DocPage/types';
import { Dictionary, t } from 'intlayer';

const docContent = {
  key: 'doc-react-native-intlayer-metadata',
  content: {
    docName: 'package__react-native-intlayer',
    url: PagesRoutes['Doc_Packages_react-native-intlayer'],
    githubUrl: GithubRoutes['Packages_react-native-intlayer'],
    createdAt: '2025-03-13',
    updatedAt: '2025-03-13',
    title: t({
      en: 'Package Documentation | react-native-intlayer',
      'en-GB': 'Package Documentation | react-native-intlayer',
      fr: 'Documentation du package | react-native-intlayer',
      es: 'Documentación del paquete | react-native-intlayer',
      de: 'Paketdokumentation | react-native-intlayer',
      ja: 'パッケージドキュメント | react-native-intlayer',
      ko: '패키지 문서 | react-native-intlayer',
      zh: '包文档 | react-native-intlayer',
      it: 'Documentazione del pacchetto | react-native-intlayer',
      pt: 'Documentação do pacote | react-native-intlayer',
      hi: 'पैकेज के डॉक्यूमेंटेशन | react-native-intlayer',
      ar: 'وثائق حزمة | react-native-intlayer',
      ru: 'Документация пакета | react-native-intlayer',
    }),

    description: t({
      en: 'See how to use the react-native-intlayer package',
      'en-GB': 'See how to use the react-native-intlayer package',
      fr: 'Découvrez comment utiliser le package react-native-intlayer',
      es: 'Descubre cómo usar el paquete react-native-intlayer',
      de: 'Erfahren Sie, wie Sie das react-native-intlayer-Paket verwenden',
      ja: 'react-native-intlayerパッケージの使用方法を確認してください',
      ko: 'react-native-intlayer 패키지 사용 방법을 확인하세요',
      zh: '查看如何使用 react-native-intlayer 软件包',
      it: 'Scopri come utilizzare il pacchetto react-native-intlayer',
      pt: 'Veja como usar o pacote react-native-intlayer',
      hi: 'react-native-intlayer पैकेज का उपयोग कैसे करें',
      ar: 'انظر كيف تستخدم حزمة react-native-intlayer',
      ru: 'Узнайте, как использовать пакет react-native-intlayer',
    }),

    keywords: t({
      en: [
        'Intlayer',
        'React Native',
        'react-native-intlayer',
        'Internationalization',
        'Documentation',
        'Next.js',
        'JavaScript',
        'React',
      ],
      'en-GB': [
        'Intlayer',
        'React Native',
        'react-native-intlayer',
        'Internationalization',
        'Documentation',
        'Next.js',
        'JavaScript',
        'React',
      ],
      fr: [
        'Intlayer',
        'React Native',
        'react-native-intlayer',
        'Internationalisation',
        'Documentation',
        'Next.js',
        'JavaScript',
        'React',
      ],
      es: [
        'Intlayer',
        'React Native',
        'react-native-intlayer',
        'Internacionalización',
        'Documentación',
        'Next.js',
        'JavaScript',
        'React',
      ],
      de: [
        'Intlayer',
        'React Native',
        'react-native-intlayer',
        'Internationalisierung',
        'Dokumentation',
        'Next.js',
        'JavaScript',
        'React',
      ],
      ja: [
        'Intlayer',
        'React Native',
        'react-native-intlayer',
        '国際化',
        'ドキュメント',
        'Next.js',
        'JavaScript',
        'React',
      ],
      ko: [
        'Intlayer',
        'React Native',
        'react-native-intlayer',
        '국제화',
        '문서',
        'Next.js',
        'JavaScript',
        'React',
      ],
      zh: [
        'Intlayer',
        'React Native',
        'react-native-intlayer',
        '国际化',
        '文档',
        'Next.js',
        'JavaScript',
        'React',
      ],
      it: [
        'Intlayer',
        'React Native',
        'react-native-intlayer',
        'internazionalizzazione',
        'documentazione',
        'Next.js',
        'JavaScript',
        'React',
      ],
      pt: [
        'Intlayer',
        'React Native',
        'react-native-intlayer',
        'internacionalização',
        'documentação',
        'Next.js',
        'JavaScript',
        'React',
      ],
      hi: [
        'Intlayer',
        'React Native',
        'react-native-intlayer',
        'अंतर्राष्ट्रीयकरण',
        'प्रलेखन',
        'Next.js',
        'JavaScript',
        'React',
      ],
      ar: [
        'Intlayer',
        'React Native',
        'react-native-intlayer',
        'الدولية',
        'المستندات',
        'Next.js',
        'JavaScript',
        'React',
      ],
      ru: [
        'Intlayer',
        'React Native',
        'react-native-intlayer',
        'интернационализация',
        'документация',
        'Next.js',
        'JavaScript',
        'React',
      ],
    }),
  },
} satisfies Dictionary<DocData>;

export default docContent;
