import { type Dictionary, t } from 'intlayer';

const dashboardNavbarContent = {
  key: 'dashboard-navbar',
  content: {
    organizationTrigger: {
      label: t({
        en: 'Click to select an organization',
        fr: 'Cliquez pour sélectionner une organisation',
        es: 'Haga clic para seleccionar una organización',
        'en-GB': 'Click to select an organization',
        de: 'Klicken Sie, um eine Organisation auszuwählen',
        ja: '組織を選択するにはクリックしてください',
        ko: '조직 선택을 클릭하세요',
        zh: '点击选择一个组织',
        it: "Clicca per selezionare un'organizzazione",
        pt: 'Clique para selecionar uma organização',
        hi: 'संस्थान का चयन करने के लिए क्लिक करें',
        ar: 'انقر لاختيار منظمة',
        ru: 'Нажмите, чтобы выбрать организацию',
        tr: 'Bir organizasyon seçmek için tıklayın',
        pl: 'Kliknij, aby wybrać organizację',
        id: 'Klik untuk memilih organisasi',
        vi: 'Nhấp để chọn tổ chức',
      }),
    },
    selectOrganizationInstruction: t({
      ar: 'اختر منظمة',
      de: 'Organisation auswählen',
      en: 'Select organization',
      'en-GB': 'Select organization',
      es: 'Seleccionar una organización',
      fr: 'Sélectionner une organisation',
      hi: 'संस्थान चुनें',
      it: "Seleziona un'organizzazione",
      ja: '組織を選択',
      ko: '조직 선택',
      pt: 'Selecionar organização',
      ru: 'Выберите организацию',
      tr: 'Organizasyon seç',
      zh: '选择组织',
      pl: 'Wybierz organizację',
      id: 'Pilih organisasi',
      vi: 'Chọn tổ chức',
    }),

    noOtherOrganizations: t({
      ar: 'لا توجد منظمات أخرى',
      de: 'Keine anderen Organisationen',
      en: 'No other organizations',
      'en-GB': 'No other organizations',
      es: 'Sin otras organizaciones',
      fr: 'Aucune autre organisation',
      hi: 'कोई अन्य संगठन नहीं',
      it: "Nessun'altra organizzazione",
      ja: '他の組織はありません',
      ko: '다른 조직이 없습니다',
      pt: 'Sem outras organizações',
      ru: 'Нет других организаций',
      tr: 'Başka organizasyon yok',
      zh: '没有其他组织',
      pl: 'Brak innych organizacji',
      id: 'Tidak ada organisasi lain',
      vi: 'Không có tổ chức nào khác',
    }),
    organizationLogout: {
      text: t({
        en: 'Exit organization context',
        fr: 'Quitter le contexte organisation',
        es: 'Salir del contexto de la organización',
        'en-GB': 'Exit organization context',
        de: 'Organisationskontext verlassen',
        ja: '組織コンテキストを終了',
        ko: '조직 컨텍스트 종료',
        zh: '退出组织上下文',
        it: 'Esci dal contesto organizzazione',
        pt: 'Sair do contexto da organização',
        hi: 'संस्थान संदर्भ से बाहर निकलें',
        ar: 'الخروج من سياق المنظمة',
        ru: 'Выйти из контекста организации',
        tr: 'Organizasyon bağlamından çık',
        pl: 'Wyjdź z kontekstu organizacji',
        id: 'Keluar dari konteks organisasi',
        vi: 'Thoát khỏi ngữ cảnh tổ chức',
      }),
      label: t({
        en: 'Click to exit organization context',
        fr: 'Cliquez pour quitter le contexte organisation',
        es: 'Haga clic para salir del contexto de la organización',
        'en-GB': 'Click to exit organization context',
        de: 'Klicken Sie, um den Organisationskontext zu verlassen',
        ja: '組織コンテキストを終了するにはクリックしてください',
        ko: '조직 컨텍스트를 종료하려면 클릭하세요',
        zh: '点击退出组织上下文',
        it: 'Clicca per uscire dal contesto organizzazione',
        pt: 'Clique para sair do contexto da organização',
        hi: 'संस्थान संदर्भ से बाहर निकलने के लिए क्लिक करें',
        ar: 'انقر للخروج من سياق المنظمة',
        ru: 'Нажмите, чтобы выйти из контекста организации',
        tr: 'Organizasyon bağlamından çıkmak için tıklayın',
        pl: 'Kliknij, aby wyjść z kontekstu organizacji',
        id: 'Klik untuk keluar dari konteks organisasi',
        vi: 'Nhấp để thoát khỏi ngữ cảnh tổ chức',
      }),
    },
    createNewOrganization: {
      text: t({
        en: 'Create new organization',
        fr: 'Créer une nouvelle organisation',
        es: 'Crear una nueva organización',
        'en-GB': 'Create new organization',
        de: 'Neue Organisation erstellen',
        ja: '新しい組織を作成',
        ko: '새 조직 만들기',
        zh: '创建新的组织',
        it: 'Crea nuova organizzazione',
        pt: 'Criar nova organização',
        hi: 'नए संगठन का निर्माण करें',
        ar: 'إنشاء منظمة جديدة',
        ru: 'Создать новую организацию',
        tr: 'Yeni organizasyon oluştur',
        pl: 'Utwórz nową organizację',
        id: 'Buat organisasi baru',
        vi: 'Tạo tổ chức mới',
      }),
      label: t({
        en: 'Click to create a new organization',
        fr: 'Cliquez pour créer une nouvelle organisation',
        es: 'Haga clic para crear una nueva organización',
        'en-GB': 'Click to create a new organization',
        de: 'Klicken Sie, um eine neue Organisation zu erstellen',
        ja: '新しい組織を作成するにはクリックしてください',
        ko: '새 조직을 만들려면 클릭하세요',
        zh: '点击创建新的组织',
        it: 'Clicca per creare una nuova organizzazione',
        pt: 'Clique para criar uma nova organização',
        hi: 'नए संगठन का निर्माण करने के लिए क्लिक करें',
        ar: 'انقر لإنشاء منظمة جديدة',
        ru: 'Нажмите, чтобы создать новую организацию',
        tr: 'Yeni organizasyon oluşturmak için tıklayın',
        pl: 'Kliknij, aby utworzyć nową organizację',
        id: 'Klik untuk membuat organisasi baru',
        vi: 'Nhấp để tạo tổ chức mới',
      }),
    },

    projectTrigger: {
      label: t({
        en: 'Click to select a project',
        fr: 'Cliquez pour sélectionner un projet',
        es: 'Haga clic para seleccionar un proyecto',
        'en-GB': 'Click to select a project',
        de: 'Klicken Sie, um ein Projekt auszuwählen',
        ja: 'プロジェクトを選択するにはクリックしてください',
        ko: '프로젝트 선택을 클릭하세요',
        zh: '点击选择一个项目',
        it: 'Clicca per selezionare un progetto',
        pt: 'Clique para selecionar um projeto',
        hi: 'परियोजना का चयन करने के लिए क्लिक करें',
        ar: 'انقر لاختيار مشروع',
        ru: 'Нажмите, чтобы выбрать проект',
        tr: 'Bir proje seçmek için tıklayın',
        pl: 'Kliknij, aby wybrać projekt',
        id: 'Klik untuk memilih proyek',
        vi: 'Nhấp để chọn dự án',
      }),
    },
    selectProjectInstruction: t({
      ar: 'اختر مشروعًا',
      de: 'Projekt auswählen',
      en: 'Select project',
      'en-GB': 'Select project',
      es: 'Seleccionar un proyecto',
      fr: 'Sélectionner un projet',
      hi: 'परियोजना चुनें',
      it: 'Seleziona un progetto',
      ja: 'プロジェクトを選択',
      ko: '프로젝트 선택',
      pt: 'Selecionar projeto',
      ru: 'Выберите проект',
      tr: 'Proje seç',
      zh: '选择项目',
      pl: 'Wybierz projekt',
      id: 'Pilih proyek',
      vi: 'Chọn dự án',
    }),

    noOtherProjects: t({
      ar: 'لا توجد مشاريع أخرى',
      de: 'Keine anderen Projekte',
      en: 'No other projects',
      'en-GB': 'No other projects',
      es: 'Sin otros proyectos',
      fr: 'Aucun autre projet',
      hi: 'कोई अन्य प्रोजेक्ट नहीं',
      it: 'Nessun altro progetto',
      ja: '他のプロジェクトはありません',
      ko: '다른 프로젝트가 없습니다',
      pt: 'Sem outros projetos',
      ru: 'Нет других проектов',
      tr: 'Başka proje yok',
      zh: '没有其他项目',
      pl: 'Brak innych projektów',
      id: 'Tidak ada proyek lain',
      vi: 'Không có dự án nào khác',
    }),
    projectLogout: {
      text: t({
        en: 'Exit project context',
        'en-GB': 'Exit project context',
        fr: 'Quitter le contexte du projet',
        es: 'Salir del contexto del proyecto',
        de: 'Projektkontext verlassen',
        ja: 'プロジェクトのコンテキストを終了',
        ko: '프로젝트 컨텍스트 종료',
        zh: '退出项目上下文',
        it: 'Esci dal contesto del progetto',
        pt: 'Sair do contexto do projeto',
        hi: 'परियोजना संदर्भ से बाहर निकलें',
        ar: 'الخروج من سياق المشروع',
        ru: 'Выйти из контекста проекта',
        tr: 'Proje bağlamından çık',
        pl: 'Opuść kontekst projektu',
        id: 'Keluar dari konteks proyek',
        vi: 'Thoát khỏi ngữ cảnh dự án',
      }),
      label: t({
        en: 'Click to log out from project',
        fr: 'Cliquez pour se déconnecter du projet',
        es: 'Haga clic para cerrar sesión del proyecto',
        'en-GB': 'Click to log out from project',
        de: 'Klicken Sie, um sich vom Projekt abzumelden',
        ja: 'プロジェクトからログアウトするにはクリックしてください',
        ko: '프로젝트에서 로그아웃하려면 클릭하세요',
        zh: '点击从项目注销',
        it: 'Clicca per disconnetterti dal progetto',
        pt: 'Clique para sair do projeto',
        hi: 'परियोजना से लॉगआउट करने के लिए क्लिक करें',
        ar: 'انقر لتسجيل الخروج من المشروع',
        ru: 'Нажмите, чтобы выйти из проекта',
        tr: 'Projeden çıkış yapmak için tıklayın',
        pl: 'Kliknij, aby wylogować się z projektu',
        id: 'Klik untuk keluar dari proyek',
        vi: 'Nhấp để đăng xuất khỏi dự án',
      }),
    },
    createNewProject: {
      text: t({
        en: 'Create new project',
        fr: 'Créer un nouveau projet',
        es: 'Crear un nuevo proyecto',
        'en-GB': 'Create new project',
        de: 'Neues Projekt erstellen',
        ja: '新しいプロジェクトを作成',
        ko: '새 프로젝트 만들기',
        zh: '创建新的项目',
        it: 'Crea nuovo progetto',
        pt: 'Criar novo projeto',
        hi: 'नए प्रोजेक्ट का निर्माण करें',
        ar: 'إنشاء مشروع جديد',
        ru: 'Создать новый проект',
        tr: 'Yeni proje oluştur',
        pl: 'Utwórz nowy projekt',
        id: 'Buat proyek baru',
        vi: 'Tạo dự án mới',
      }),
      label: t({
        en: 'Click to create a new project',
        fr: 'Cliquez pour créer un nouveau projet',
        es: 'Haga clic para crear un nuevo proyecto',
        'en-GB': 'Click to create a new project',
        de: 'Klicken Sie, um ein neues Projekt zu erstellen',
        ja: '新しいプロジェクトを作成するにはクリックしてください',
        ko: '새 프로젝트를 만들려면 클릭하세요',
        zh: '点击创建新的项目',
        it: 'Clicca per creare un nuovo progetto',
        pt: 'Clique para criar um novo projeto',
        hi: 'नए प्रोजेक्ट का निर्माण करने के लिए क्लिक करें',
        ar: 'انقر لإنشاء مشروع جديد',
        ru: 'Нажмите, чтобы создать новый проект',
        tr: 'Yeni proje oluşturmak için tıklayın',
        pl: 'Kliknij, aby utworzyć nowy projekt',
        id: 'Klik untuk membuat proyek baru',
        vi: 'Nhấp để tạo dự án mới',
      }),
    },
  },
  title: 'Dashboard navbar',
  description:
    'Content declarations for the dashboard navigation bar, including labels and instructions for selecting or creating organizations and projects.',
  tags: [
    'dashboard',
    'navbar',
    'navigation',
    'organization',
    'project management',
  ],
} satisfies Dictionary;

export default dashboardNavbarContent;
