import { t, type Dictionary } from 'intlayer';

const dashboardNavbarContent = {
  key: 'dashboard-navbar',
  content: {
    organizationTrigger: {
      label: t({
        en: 'Click to select an organization',
        fr: 'Cliquez pour sélectionner une organisation',
        es: 'Haga clic para seleccionar una organización',
        'en-GB': 'Click to select an organization',
        de: 'Klicken Sie, um eine Organisation auszuwählen',
        ja: '組織を選択するにはクリックしてください',
        ko: '조직 선택을 클릭하세요',
        zh: '点击选择一个组织',
        it: "Clicca per selezionare un'organizzazione",
        pt: 'Clique para selecionar uma organização',
        hi: 'संस्थान का चयन करने के लिए क्लिक करें',
        ar: 'انقر لاختيار منظمة',
        ru: 'Нажмите, чтобы выбрать организацию',
        tr: 'Bir organizasyon seçmek için tıklayın',
      }),
    },
    selectOrganizationInstruction: t({
      en: 'Select organization',
      fr: 'Sélectionner une organisation',
      es: 'Seleccionar una organización',
      'en-GB': 'Select organization',
      de: 'Organisation auswählen',
      ja: '組織を選択',
      ko: '조직 선택',
      zh: '选择组织',
      it: "Seleziona un'organizzazione",
      pt: 'Selecionar organização',
      hi: 'संस्थान चुनें',
      ar: 'اختر منظمة',
      ru: 'Выберите организацию',
      tr: 'Organizasyon seç',
    }),

    noOtherOrganizations: t({
      en: 'No other organizations',
      fr: 'Aucune autre organisation',
      es: 'Sin otras organizaciones',
      'en-GB': 'No other organizations',
      de: 'Keine anderen Organisationen',
      ja: '他の組織はありません',
      ko: '다른 조직이 없습니다',
      zh: '没有其他组织',
      it: "Nessun'altra organizzazione",
      pt: 'Sem outras organizações',
      hi: 'कोई अन्य संगठन नहीं',
      ar: 'لا توجد منظمات أخرى',
      ru: 'Нет других организаций',
      tr: 'Başka organizasyon yok',
    }),
    organizationLogout: {
      text: t({
        en: 'Log out from organization',
        fr: "Se déconnecter de l'organisation",
        es: 'Cerrar sesión de la organización',
        'en-GB': 'Log out from organization',
        de: 'Von der Organisation abmelden',
        ja: '組織からログアウト',
        ko: '조직에서 로그아웃',
        zh: '从组织注销',
        it: "Disconnetti dall'organizzazione",
        pt: 'Sair da organização',
        hi: 'सगाई से लॉगआउट करें',
        ar: 'تسجيل الخروج من المنظمة',
        ru: 'Выйти из организации',
        tr: 'Organizasyondan çıkış yap',
      }),
      label: t({
        en: 'Click to log out from organization',
        fr: "Cliquez pour se déconnecter de l'organisation",
        es: 'Haga clic para cerrar sesión de la organización',
        'en-GB': 'Click to log out from organization',
        de: 'Klicken Sie, um sich von der Organisation abzumelden',
        ja: '組織からログアウトするにはクリックしてください',
        ko: '조직에서 로그아웃하려면 클릭하세요',
        zh: '点击从组织注销',
        it: "Clicca per disconnetterti dall'organizzazione",
        pt: 'Clique para sair da organização',
        hi: 'संस्थान से लॉगआउट करने के लिए क्लिक करें',
        ar: 'انقر لتسجيل الخروج من المنظمة',
        ru: 'Нажмите, чтобы выйти из организации',
        tr: 'Organizasyondan çıkış yapmak için tıklayın',
      }),
    },
    createNewOrganization: {
      text: t({
        en: 'Create new organization',
        fr: 'Créer une nouvelle organisation',
        es: 'Crear una nueva organización',
        'en-GB': 'Create new organization',
        de: 'Neue Organisation erstellen',
        ja: '新しい組織を作成',
        ko: '새 조직 만들기',
        zh: '创建新的组织',
        it: 'Crea nuova organizzazione',
        pt: 'Criar nova organização',
        hi: 'नए संगठन का निर्माण करें',
        ar: 'إنشاء منظمة جديدة',
        ru: 'Создать новую организацию',
        tr: 'Yeni organizasyon oluştur',
      }),
      label: t({
        en: 'Click to create a new organization',
        fr: 'Cliquez pour créer une nouvelle organisation',
        es: 'Haga clic para crear una nueva organización',
        'en-GB': 'Click to create a new organization',
        de: 'Klicken Sie, um eine neue Organisation zu erstellen',
        ja: '新しい組織を作成するにはクリックしてください',
        ko: '새 조직을 만들려면 클릭하세요',
        zh: '点击创建新的组织',
        it: 'Clicca per creare una nuova organizzazione',
        pt: 'Clique para criar uma nova organização',
        hi: 'नए संगठन का निर्माण करने के लिए क्लिक करें',
        ar: 'انقر لإنشاء منظمة جديدة',
        ru: 'Нажмите, чтобы создать новую организацию',
        tr: 'Yeni organizasyon oluşturmak için tıklayın',
      }),
    },

    projectTrigger: {
      label: t({
        en: 'Click to select a project',
        fr: 'Cliquez pour sélectionner un projet',
        es: 'Haga clic para seleccionar un proyecto',
        'en-GB': 'Click to select a project',
        de: 'Klicken Sie, um ein Projekt auszuwählen',
        ja: 'プロジェクトを選択するにはクリックしてください',
        ko: '프로젝트 선택을 클릭하세요',
        zh: '点击选择一个项目',
        it: 'Clicca per selezionare un progetto',
        pt: 'Clique para selecionar um projeto',
        hi: 'परियोजना का चयन करने के लिए क्लिक करें',
        ar: 'انقر لاختيار مشروع',
        ru: 'Нажмите, чтобы выбрать проект',
        tr: 'Bir proje seçmek için tıklayın',
      }),
    },
    selectProjectInstruction: t({
      en: 'Select project',
      fr: 'Sélectionner un projet',
      es: 'Seleccionar un proyecto',
      'en-GB': 'Select project',
      de: 'Projekt auswählen',
      ja: 'プロジェクトを選択',
      ko: '프로젝트 선택',
      zh: '选择项目',
      it: 'Seleziona un progetto',
      pt: 'Selecionar projeto',
      hi: 'परियोजना चुनें',
      ar: 'اختر مشروعًا',
      ru: 'Выберите проект',
      tr: 'Proje seç',
    }),

    noOtherProjects: t({
      en: 'No other projects',
      fr: 'Aucun autre projet',
      es: 'Sin otros proyectos',
      'en-GB': 'No other projects',
      de: 'Keine anderen Projekte',
      ja: '他のプロジェクトはありません',
      ko: '다른 프로젝트가 없습니다',
      zh: '没有其他项目',
      it: 'Nessun altro progetto',
      pt: 'Sem outros projetos',
      hi: 'कोई अन्य प्रोजेक्ट नहीं',
      ar: 'لا توجد مشاريع أخرى',
      ru: 'Нет других проектов',
      tr: 'Başka proje yok',
    }),
    projectLogout: {
      text: t({
        en: 'Log out from project',
        fr: 'Se déconnecter du projet',
        es: 'Cerrar sesión del proyecto',
        'en-GB': 'Log out from project',
        de: 'Vom Projekt abmelden',
        ja: 'プロジェクトからログアウト',
        ko: '프로젝트에서 로그아웃',
        zh: '从项目注销',
        it: 'Disconnetti dal progetto',
        pt: 'Sair do projeto',
        hi: 'परियोजना से लॉगआउट करें',
        ar: 'تسجيل الخروج من المشروع',
        ru: 'Выйти из проекта',
        tr: 'Projeden çıkış yap',
      }),
      label: t({
        en: 'Click to log out from project',
        fr: 'Cliquez pour se déconnecter du projet',
        es: 'Haga clic para cerrar sesión del proyecto',
        'en-GB': 'Click to log out from project',
        de: 'Klicken Sie, um sich vom Projekt abzumelden',
        ja: 'プロジェクトからログアウトするにはクリックしてください',
        ko: '프로젝트에서 로그아웃하려면 클릭하세요',
        zh: '点击从项目注销',
        it: 'Clicca per disconnetterti dal progetto',
        pt: 'Clique para sair do projeto',
        hi: 'परियोजना से लॉगआउट करने के लिए क्लिक करें',
        ar: 'انقر لتسجيل الخروج من المشروع',
        ru: 'Нажмите, чтобы выйти из проекта',
        tr: 'Projeden çıkış yapmak için tıklayın',
      }),
    },
    createNewProject: {
      text: t({
        en: 'Create new project',
        fr: 'Créer un nouveau projet',
        es: 'Crear un nuevo proyecto',
        'en-GB': 'Create new project',
        de: 'Neues Projekt erstellen',
        ja: '新しいプロジェクトを作成',
        ko: '새 프로젝트 만들기',
        zh: '创建新的项目',
        it: 'Crea nuovo progetto',
        pt: 'Criar novo projeto',
        hi: 'नए प्रोजेक्ट का निर्माण करें',
        ar: 'إنشاء مشروع جديد',
        ru: 'Создать новый проект',
        tr: 'Yeni proje oluştur',
      }),
      label: t({
        en: 'Click to create a new project',
        fr: 'Cliquez pour créer un nouveau projet',
        es: 'Haga clic para crear un nuevo proyecto',
        'en-GB': 'Click to create a new project',
        de: 'Klicken Sie, um ein neues Projekt zu erstellen',
        ja: '新しいプロジェクトを作成するにはクリックしてください',
        ko: '새 프로젝트를 만들려면 클릭하세요',
        zh: '点击创建新的项目',
        it: 'Clicca per creare un nuovo progetto',
        pt: 'Clique para criar um novo projeto',
        hi: 'नए प्रोजेक्ट का निर्माण करने के लिए क्लिक करें',
        ar: 'انقر لإنشاء مشروع جديد',
        ru: 'Нажмите, чтобы создать новый проект',
        tr: 'Yeni proje oluşturmak için tıklayın',
      }),
    },
  },
} satisfies Dictionary;

export default dashboardNavbarContent;
