import { t, type Dictionary } from 'intlayer';

export const paymentStepContent = {
  key: 'payment-step',
  content: {
    title: t({
      en: 'Payment',
      'en-GB': 'Payment',
      fr: 'Paiement',
      es: 'Pago',
      de: 'Zahlung',
      ja: '支払い',
      ko: '지불',
      zh: '付款',
      it: 'Pagamento',
      pt: 'Pagamento',
      hi: 'भुगतान',
      ar: 'الدفع',
      ru: 'Платеж',
    }),
    paymentDetails: {
      title: t({
        en: 'Payment Details',
        'en-GB': 'Payment Details',
        fr: 'Détails du paiement',
        es: 'Detalles del pago',
        de: 'Zahlungsdetails',
        ja: '支払いの詳細',
        ko: '결제 세부정보',
        zh: '付款详情',
        it: 'Dettagli di pagamento',
        pt: 'Detalhes do pagamento',
        hi: 'भुगतान विवरण',
        ar: 'تفاصيل الدفع',
        ru: 'Детали платежа',
      }),
    },
    youReOrganizationIsAlreadySubscribed: {
      title: t({
        en: 'Your organization is already subscribed',
        'en-GB': 'Your organization is already subscribed',
        fr: 'Votre organisation est déjà abonnée',
        es: 'Su organización ya está suscrita',
        de: 'Ihre Organisation ist bereits abonniert',
        ja: 'あなたの組織はすでに購読されています',
        ko: '귀하의 조직은 이미 구독되었습니다',
        zh: '您的组织已订阅',
        it: 'La tua organizzazione è già abbonata',
        pt: 'Sua organização já está inscrita',
        hi: 'आपका संगठन पहले से ही सब्सक्राइब है',
        ar: 'منظمتك مشترك بها بالفعل',
        ru: 'Ваша организация уже подписана',
      }),
    },
    incorrectProductMessage: t({
      en: 'The current picked product is not valid. Please select a valid product.',
      'en-GB':
        'The current picked product is not valid. Please select a valid product.',
      fr: "Le produit actuellement sélectionné n'est pas valide. Veuillez sélectionner un produit valide.",
      es: 'El producto actualmente seleccionado no es válido. Por favor, seleccione un producto válido.',
      de: 'Das aktuell ausgewählte Produkt ist ungültig. Bitte wählen Sie ein gültiges Produkt aus.',
      ja: '現在選択されている製品は無効です。有効な製品を選択してください。',
      ko: '현재 선택된 제품이 유효하지 않습니다. 유효한 제품을 선택하십시오.',
      zh: '当前选择的产品无效。请选择有效的产品。',
      it: 'Il prodotto attualmente selezionato non è valido. Si prega di selezionare un prodotto valido.',
      pt: 'O produto atualmente selecionado não é válido. Selecione um produto válido.',
      hi: 'वर्तमान में चुना गया उत्पाद मान्य नहीं है। कृपया एक मान्य उत्पाद चुनें।',
      ar: 'المنتج المحدد حاليا غير صالح. يرجى اختيار منتج صالح.',
      ru: 'Текущий выбранный продукт недействителен. Пожалуйста, выберите действительный продукт.',
    }),
    pickANewProductButton: {
      text: t({
        en: 'Pick a new product',
        'en-GB': 'Pick a new product',
        fr: 'Choisissez un nouveau produit',
        es: 'Elija un nuevo producto',
        de: 'Wählen Sie ein neues Produkt',
        ja: '新しい製品を選択',
        ko: '새 제품 선택',
        zh: '选择新产品',
        it: 'Scegli un nuovo prodotto',
        pt: 'Escolha um novo produto',
        hi: 'नया उत्पाद चुनें',
        ar: 'اختر منتجًا جديدًا',
        ru: 'Выберите новый продукт',
      }),
      label: t({
        en: 'Pick a new product',
        'en-GB': 'Pick a new product',
        fr: 'Choisissez un nouveau produit',
        es: 'Elija un nuevo producto',
        de: 'Wählen Sie ein neues Produkt',
        ja: '新しい製品を選択',
        ko: '새 제품 선택',
        zh: '选择新产品',
        it: 'Scegli un nuovo prodotto',
        pt: 'Escolha um novo produto',
        hi: 'नया उत्पाद चुनें',
        ar: 'اختر منتجًا جديدًا',
        ru: 'Выберите новый продукт',
      }),
    },
  },
} satisfies Dictionary;

export default paymentStepContent;
