import { type Dictionary, t } from 'intlayer';

const chatFormSectionContent = {
  key: 'chat-form-section',
  content: {
    textArea: {
      label: t({
        de: 'Stellen Sie Ihre Frage an unsere KI-gestützte Smart-Dokumentation',
        zh: '向我们基于 AI 的智能文档提问',
        ko: '저희의 AI 기반 스마트 문서에 질문해 주세요',
        ja: 'AI搭載のスマートドキュメントに質問してください',
        en: 'Ask your question to our AI-Powered Smart Documentation',
        'en-GB': 'Ask your question to our AI-Powered Smart Documentation',
        fr: 'Posez votre question à notre documentation intelligente',
        es: 'Pregúntale a nuestra documentación inteligente',
        it: 'Fai una domanda alla nostra documentazione intelligente',
        pt: 'Faça uma pergunta para nossa documentação inteligente',
        hi: 'हमारे एआई-पॉयटेड स्मार्ट दस्तावेज़ के लिए अपनी प्रश्न करें',
        ar: 'طرح سؤالك لدردشة الوثائق الخاصة بنا AI',
        ru: 'Спросите нашу умную документацию',
        tr: 'Yapay Zeka Destekli Akıllı Belgelerimize sorunuzu sorun',
        pl: 'Zadaj pytanie naszej inteligentnej dokumentacji wspieranej przez AI',
        id: 'Ajukan pertanyaan Anda kepada Dokumentasi Cerdas bertenaga AI kami',
        vi: 'Đặt câu hỏi cho Tài liệu Thông minh do AI hỗ trợ',
        uk: 'Задайте своє запитання нашій інтелектуальній документації на базі ШІ',
      }),
      placeholder: t({
        de: 'Stellen Sie mir irgendwas...',
        zh: '问我任何事情...',
        ko: '무엇을 물어보세요...',
        ja: '私たちに何か質問してください...',
        en: 'Ask me anything...',
        'en-GB': 'Ask me anything...',
        fr: 'Posez-moi n’importe quoi...',
        es: 'Pregúntame cualquier cosa...',
        it: 'Fai qualcosa...',
        pt: 'Faça algo...',
        hi: 'कुछ प्रश्न करें...',
        ar: 'طرح شيئا...',
        ru: 'Спросите меня что-нибудь...',
        tr: 'Bana bir şey sor...',
        pl: 'Zapytaj mnie o cokolwiek...',
        id: 'Tanyakan apa saja...',
        vi: 'Hãy hỏi tôi bất cứ điều gì...',
        uk: 'Запитайте мене про що завгодно...',
      }),
    },
    sendQuestionButton: {
      label: t({
        de: 'Klicken Sie, um die Frage zu senden',
        zh: '点击发送问题',
        ko: '질문을 보내려면 클릭하세요',
        ja: '質問を送信するにはクリックしてください',
        en: 'Click to send question',
        'en-GB': 'Click to send question',
        fr: 'Cliquez pour envoyer la question',
        es: 'Haga clic para enviar la pregunta',
        it: 'Clicca per inviare la domanda',
        pt: 'Clique para enviar a pergunta',
        hi: 'प्रश्न भेजने के लिए क्लिक करें',
        ar: 'انقر لإرسال السؤال',
        ru: 'Нажмите, чтобы отправить вопрос',
        tr: 'Soruyu göndermek için tıklayın',
        pl: 'Kliknij, aby wysłać pytanie',
        id: 'Klik untuk mengirim pertanyaan',
        vi: 'Nhấn để gửi câu hỏi',
        uk: 'Натисніть, щоб надіслати запит',
      }),
    },
    clearButton: {
      label: t({
        de: 'Klicken Sie, um zu löschen',
        zh: '点击清除',
        ko: '지우려면 클릭하세요',
        ja: 'クリアするにはクリックしてください',
        en: 'Click to clear',
        'en-GB': 'Click to clear',
        fr: 'Cliquez pour effacer',
        es: 'Haga clic para borrar',
        it: 'Clicca per cancellare',
        pt: 'Clique para limpar',
        hi: 'साफ़ करने के लिए क्लिक करें',
        ar: 'انقر لمسح',
        ru: 'Нажмите, чтобы очистить',
        tr: 'Temizlemek için tıklayın',
        pl: 'Kliknij, aby wyczyścić',
        id: 'Klik untuk mengosongkan',
        vi: 'Nhấn để xóa',
        uk: 'Натисніть, щоб очистити',
      }),
    },
  },
  title: 'Chat form section',
  description:
    'Content declaration for the chat form section of the AI-powered documentation assistant, including labels and placeholders for user interaction.',
  tags: ['chat interface', 'documentation assistant', 'form section'],
} satisfies Dictionary;

export default chatFormSectionContent;
