import { HttpStatusCodes } from '@utils/httpStatusCodes';
import type { ErrorCode } from './errorCodes.types';

/**
 * Affiliate-related error codes.
 */
export const affiliateErrors = {
  AFFILIATE_ALREADY_EXISTS: {
    title: {
      en: 'Affiliate already exists',
      'en-GB': 'Affiliate already exists',
      fr: 'Affilié déjà existant',
      es: 'Afiliado ya existe',
      ru: 'Аффилиат уже существует',
      ja: 'アフィリエイトはすでに存在します',
      ko: '제휴사가 이미 존재합니다',
      zh: '联盟会员已存在',
      de: 'Affiliate existiert bereits',
      ar: 'المسوق بالعمولة موجود بالفعل',
      it: "L'affiliato esiste già",
      pt: 'O afiliado já existe',
      hi: 'संबद्ध पहले से मौजूद है',
      tr: 'Ortak zaten mevcut',
      pl: 'Partner już istnieje',
      id: 'Afiliasi sudah ada',
      vi: 'Liên kết đã tồn tại',
      uk: 'Афілійований партнер вже існує',
    },
    message: {
      en: 'This user is already registered as an affiliate.',
      'en-GB': 'This user is already registered as an affiliate.',
      fr: "Cet utilisateur est déjà enregistré en tant qu'affilié.",
      es: 'Este usuario ya está registrado como afiliado.',
      ru: 'Этот пользователь уже зарегистрирован как партнер.',
      ja: 'このユーザーはすでにアフィリエイトとして登録されています。',
      ko: '이 사용자는 이미 제휴사로 등록되어 있습니다.',
      zh: '该用户已注册为联盟会员。',
      de: 'Dieser Benutzer ist bereits als Affiliate registriert.',
      ar: 'هذا المستخدم مسجل بالفعل كمسوق بالعمولة.',
      it: 'Questo utente è già registrato come affiliato.',
      pt: 'Este utilizador já está registado como afiliado.',
      hi: 'यह उपयोगकर्ता पहले से संबद्ध के रूप में पंजीकृत है।',
      tr: 'Bu kullanıcı zaten ortak olarak kayıtlı.',
      pl: 'Ten użytkownik jest już zarejestrowany jako partner.',
      id: 'Pengguna ini sudah terdaftar sebagai afiliasi.',
      vi: 'Người dùng này đã được đăng ký là đối tác liên kết.',
      uk: 'Цей користувач вже зареєстрований як партнер.',
    },
    statusCode: HttpStatusCodes.CONFLICT_409,
  },
  AFFILIATE_NOT_FOUND: {
    title: {
      en: 'Affiliate not found',
      'en-GB': 'Affiliate not found',
      fr: 'Affilié non trouvé',
      es: 'Afiliado no encontrado',
      ru: 'Аффилиат не найден',
      ja: 'アフィリエイトが見つかりません',
      ko: '제휴사를 찾을 수 없습니다',
      zh: '未找到联盟会员',
      de: 'Affiliate nicht gefunden',
      ar: 'المسوق بالعمولة غير موجود',
      it: 'Affiliato non trovato',
      pt: 'Afiliado não encontrado',
      hi: 'संबद्ध नहीं मिला',
      tr: 'Ortak bulunamadı',
      pl: 'Nie znaleziono partnera',
      id: 'Afiliasi tidak ditemukan',
      vi: 'Không tìm thấy đối tác liên kết',
      uk: 'Партнера не знайдено',
    },
    message: {
      en: 'No affiliate account found for this user.',
      'en-GB': 'No affiliate account found for this user.',
      fr: 'Aucun compte affilié trouvé pour cet utilisateur.',
      es: 'No se encontró ninguna cuenta de afiliado para este usuario.',
      ru: 'Для этого пользователя не найден партнерский аккаунт.',
      ja: 'このユーザーのアフィリエイトアカウントが見つかりません。',
      ko: '이 사용자의 제휴 계정을 찾을 수 없습니다.',
      zh: '未找到该用户的联盟账户。',
      de: 'Für diesen Benutzer wurde kein Affiliate-Konto gefunden.',
      ar: 'لم يتم العثور على حساب مسوق بالعمولة لهذا المستخدم.',
      it: 'Nessun account affiliato trovato per questo utente.',
      pt: 'Nenhuma conta de afiliado encontrada para este utilizador.',
      hi: 'इस उपयोगकर्ता के लिए कोई संबद्ध खाता नहीं मिला।',
      tr: 'Bu kullanıcı için ortak hesabı bulunamadı.',
      pl: 'Nie znaleziono konta partnera dla tego użytkownika.',
      id: 'Tidak ada akun afiliasi ditemukan untuk pengguna ini.',
      vi: 'Không tìm thấy tài khoản liên kết cho người dùng này.',
      uk: 'Партнерський акаунт для цього користувача не знайдено.',
    },
    statusCode: HttpStatusCodes.NOT_FOUND_404,
  },
  AFFILIATE_INVITATION_NOT_FOUND: {
    title: {
      en: 'Invitation not found',
      'en-GB': 'Invitation not found',
      fr: 'Invitation introuvable',
      es: 'Invitación no encontrada',
      ru: 'Приглашение не найдено',
      ja: '招待が見つかりません',
      ko: '초대를 찾을 수 없습니다',
      zh: '未找到邀请',
      de: 'Einladung nicht gefunden',
      ar: 'لم يتم العثور على الدعوة',
      it: 'Invito non trovato',
      pt: 'Convite não encontrado',
      hi: 'आमंत्रण नहीं मिला',
      tr: 'Davet bulunamadı',
      pl: 'Nie znaleziono zaproszenia',
      id: 'Undangan tidak ditemukan',
      vi: 'Không tìm thấy lời mời',
      uk: 'Запрошення не знайдено',
    },
    message: {
      en: 'This invitation link is invalid or has expired.',
      'en-GB': 'This invitation link is invalid or has expired.',
      fr: "Ce lien d'invitation est invalide ou a expiré.",
      es: 'Este enlace de invitación no es válido o ha caducado.',
      ru: 'Эта ссылка приглашения недействительна или истекла.',
      ja: 'この招待リンクは無効または期限切れです。',
      ko: '이 초대 링크는 유효하지 않거나 만료되었습니다.',
      zh: '此邀请链接无效或已过期。',
      de: 'Dieser Einladungslink ist ungültig oder abgelaufen.',
      ar: 'رابط الدعوة هذا غير صالح أو انتهت صلاحيته.',
      it: 'Questo link di invito non è valido o è scaduto.',
      pt: 'Este link de convite é inválido ou expirou.',
      hi: 'यह आमंत्रण लिंक अमान्य है या समाप्त हो गया है।',
      tr: 'Bu davet bağlantısı geçersiz veya süresi dolmuş.',
      pl: 'Ten link zaproszenia jest nieprawidłowy lub wygasł.',
      id: 'Tautan undangan ini tidak valid atau telah kedaluwarsa.',
      vi: 'Liên kết mời này không hợp lệ hoặc đã hết hạn.',
      uk: 'Це посилання запрошення недійсне або закінчилося.',
    },
    statusCode: HttpStatusCodes.NOT_FOUND_404,
  },
  AFFILIATE_INVITATION_ALREADY_USED: {
    title: {
      en: 'Invitation already used',
      'en-GB': 'Invitation already used',
      fr: 'Invitation déjà utilisée',
      es: 'Invitación ya utilizada',
      ru: 'Приглашение уже использовано',
      ja: '招待はすでに使用されています',
      ko: '초대가 이미 사용되었습니다',
      zh: '邀请已被使用',
      de: 'Einladung bereits verwendet',
      ar: 'تم استخدام الدعوة بالفعل',
      it: 'Invito già utilizzato',
      pt: 'Convite já utilizado',
      hi: 'आमंत्रण पहले ही उपयोग किया जा चुका है',
      tr: 'Davet zaten kullanılmış',
      pl: 'Zaproszenie zostało już użyte',
      id: 'Undangan sudah digunakan',
      vi: 'Lời mời đã được sử dụng',
      uk: 'Запрошення вже використано',
    },
    message: {
      en: 'This invitation has already been accepted or has expired.',
      'en-GB': 'This invitation has already been accepted or has expired.',
      fr: 'Cette invitation a déjà été acceptée ou a expiré.',
      es: 'Esta invitación ya ha sido aceptada o ha caducado.',
      ru: 'Это приглашение уже принято или истекло.',
      ja: 'この招待はすでに承認されたか期限切れです。',
      ko: '이 초대는 이미 수락되었거나 만료되었습니다.',
      zh: '此邀请已被接受或已过期。',
      de: 'Diese Einladung wurde bereits angenommen oder ist abgelaufen.',
      ar: 'تم قبول هذه الدعوة بالفعل أو انتهت صلاحيتها.',
      it: 'Questo invito è già stato accettato o è scaduto.',
      pt: 'Este convite já foi aceite ou expirou.',
      hi: 'यह आमंत्रण पहले ही स्वीकार किया जा चुका है या समाप्त हो गया है।',
      tr: 'Bu davet zaten kabul edilmiş veya süresi dolmuş.',
      pl: 'To zaproszenie zostało już zaakceptowane lub wygasło.',
      id: 'Undangan ini sudah diterima atau kedaluwarsa.',
      vi: 'Lời mời này đã được chấp nhận hoặc đã hết hạn.',
      uk: 'Це запрошення вже прийнято або закінчилося.',
    },
    statusCode: HttpStatusCodes.CONFLICT_409,
  },
  AFFILIATE_INVITATION_EMAIL_MISMATCH: {
    title: {
      en: 'Invitation email mismatch',
      'en-GB': 'Invitation email mismatch',
      fr: "L'e-mail de l'invitation ne correspond pas",
      es: 'El correo de la invitación no coincide',
      ru: 'Электронная почта приглашения не совпадает',
      ja: '招待メールが一致しません',
      ko: '초대 이메일이 일치하지 않습니다',
      zh: '邀请电子邮件不匹配',
      de: 'E-Mail der Einladung stimmt nicht überein',
      ar: 'البريد الإلكتروني للدعوة غير متطابق',
      it: "L'e-mail dell'invito non corrisponde",
      pt: 'O e-mail do convite não corresponde',
      hi: 'आमंत्रण ईमेल मेल नहीं खाता',
      tr: 'Davet e-postası eşleşmiyor',
      pl: 'Adres e-mail zaproszenia nie zgadza się',
      id: 'Email undangan tidak cocok',
      vi: 'Email lời mời không khớp',
      uk: 'Електронна пошта запрошення не збігається',
    },
    message: {
      en: 'This invitation was sent to a different email address. Sign in with the invited account to accept it.',
      'en-GB':
        'This invitation was sent to a different email address. Sign in with the invited account to accept it.',
      fr: "Cette invitation a été envoyée à une autre adresse e-mail. Connectez-vous avec le compte invité pour l'accepter.",
      es: 'Esta invitación se envió a una dirección de correo diferente. Inicie sesión con la cuenta invitada para aceptarla.',
      ru: 'Это приглашение было отправлено на другой адрес электронной почты. Войдите в приглашённую учётную запись, чтобы принять его.',
      ja: 'この招待は別のメールアドレスに送信されました。招待されたアカウントでサインインして承認してください。',
      ko: '이 초대는 다른 이메일 주소로 전송되었습니다. 초대된 계정으로 로그인하여 수락하세요.',
      zh: '此邀请已发送至其他电子邮件地址。请使用被邀请的帐户登录以接受。',
      de: 'Diese Einladung wurde an eine andere E-Mail-Adresse gesendet. Melden Sie sich mit dem eingeladenen Konto an, um sie anzunehmen.',
      ar: 'تم إرسال هذه الدعوة إلى عنوان بريد إلكتروني مختلف. سجّل الدخول بالحساب المدعو لقبولها.',
      it: "Questo invito è stato inviato a un altro indirizzo e-mail. Accedi con l'account invitato per accettarlo.",
      pt: 'Este convite foi enviado para um endereço de e-mail diferente. Inicie sessão com a conta convidada para o aceitar.',
      hi: 'यह आमंत्रण किसी अन्य ईमेल पते पर भेजा गया था। इसे स्वीकार करने के लिए आमंत्रित खाते से साइन इन करें।',
      tr: 'Bu davet farklı bir e-posta adresine gönderildi. Kabul etmek için davet edilen hesapla giriş yapın.',
      pl: 'To zaproszenie zostało wysłane na inny adres e-mail. Zaloguj się na zaproszone konto, aby je zaakceptować.',
      id: 'Undangan ini dikirim ke alamat email yang berbeda. Masuk dengan akun yang diundang untuk menerimanya.',
      vi: 'Lời mời này đã được gửi đến một địa chỉ email khác. Đăng nhập bằng tài khoản được mời để chấp nhận.',
      uk: 'Це запрошення було надіслано на іншу електронну адресу. Увійдіть до запрошеного облікового запису, щоб прийняти його.',
    },
    statusCode: HttpStatusCodes.FORBIDDEN_403,
  },
  AFFILIATE_CODE_GENERATION_FAILED: {
    title: {
      en: 'Referral code generation failed',
      'en-GB': 'Referral code generation failed',
      fr: 'Échec de la génération du code de parrainage',
      es: 'Error al generar el código de referido',
      ru: 'Ошибка генерации реферального кода',
      ja: '紹介コードの生成に失敗しました',
      ko: '추천 코드 생성 실패',
      zh: '推荐码生成失败',
      de: 'Generierung des Empfehlungscodes fehlgeschlagen',
      ar: 'فشل إنشاء رمز الإحالة',
      it: 'Generazione del codice di riferimento fallita',
      pt: 'Falha na geração do código de referência',
      hi: 'रेफरल कोड जनरेशन विफल',
      tr: 'Referans kodu oluşturma başarısız',
      pl: 'Generowanie kodu polecenia nie powiodło się',
      id: 'Pembuatan kode referral gagal',
      vi: 'Tạo mã giới thiệu thất bại',
      uk: 'Помилка генерації реферального коду',
    },
    message: {
      en: 'Failed to generate a unique referral code. Please try again.',
      'en-GB': 'Failed to generate a unique referral code. Please try again.',
      fr: 'Impossible de générer un code de parrainage unique. Veuillez réessayer.',
      es: 'No se pudo generar un código de referido único. Inténtelo de nuevo.',
      ru: 'Не удалось сгенерировать уникальный реферальный код. Попробуйте снова.',
      ja: 'ユニークな紹介コードの生成に失敗しました。再試行してください。',
      ko: '고유 추천 코드 생성에 실패했습니다. 다시 시도하십시오.',
      zh: '无法生成唯一的推荐码。请重试。',
      de: 'Es konnte kein eindeutiger Empfehlungscode generiert werden. Bitte versuchen Sie es erneut.',
      ar: 'فشل في إنشاء رمز إحالة فريد. يرجى المحاولة مرة أخرى.',
      it: 'Impossibile generare un codice di riferimento univoco. Riprovare.',
      pt: 'Falha ao gerar um código de referência único. Por favor, tente novamente.',
      hi: 'एक अद्वितीय रेफरल कोड उत्पन्न करने में विफल। कृपया पुनः प्रयास करें।',
      tr: 'Benzersiz bir referans kodu oluşturulamadı. Lütfen tekrar deneyin.',
      pl: 'Nie udało się wygenerować unikalnego kodu polecenia. Spróbuj ponownie.',
      id: 'Gagal menghasilkan kode referral unik. Silakan coba lagi.',
      vi: 'Không thể tạo mã giới thiệu duy nhất. Vui lòng thử lại.',
      uk: 'Не вдалося згенерувати унікальний реферальний код. Будь ласка, спробуйте ще раз.',
    },
    statusCode: HttpStatusCodes.INTERNAL_SERVER_ERROR_500,
  },
  PROMO_CODE_NOT_FOUND: {
    title: {
      en: 'Promo code not found',
      'en-GB': 'Promo code not found',
      fr: 'Code promo introuvable',
      es: 'Código promocional no encontrado',
      ru: 'Промо-код не найден',
      ja: 'プロモコードが見つかりません',
      ko: '프로모 코드를 찾을 수 없습니다',
      zh: '未找到促销码',
      de: 'Aktionscode nicht gefunden',
      ar: 'رمز العرض الترويجي غير موجود',
      it: 'Codice promozionale non trovato',
      pt: 'Código promocional não encontrado',
      hi: 'प्रोमो कोड नहीं मिला',
      tr: 'Promosyon kodu bulunamadı',
      pl: 'Kod promocyjny nie znaleziony',
      id: 'Kode promo tidak ditemukan',
      vi: 'Không tìm thấy mã khuyến mãi',
      uk: 'Промо-код не знайдено',
    },
    message: {
      en: 'The requested promo code does not exist.',
      'en-GB': 'The requested promo code does not exist.',
      fr: "Le code promo demandé n'existe pas.",
      es: 'El código promocional solicitado no existe.',
      ru: 'Запрошенный промо-код не существует.',
      ja: 'リクエストされたプロモコードは存在しません。',
      ko: '요청한 프로모 코드가 존재하지 않습니다.',
      zh: '请求的促销码不存在。',
      de: 'Der angeforderte Aktionscode existiert nicht.',
      ar: 'رمز العرض الترويجي المطلوب غير موجود.',
      it: 'Il codice promozionale richiesto non esiste.',
      pt: 'O código promocional solicitado não existe.',
      hi: 'अनुरोधित प्रोमो कोड मौजूद नहीं है।',
      tr: 'İstenen promosyon kodu mevcut değil.',
      pl: 'Żądany kod promocyjny nie istnieje.',
      id: 'Kode promo yang diminta tidak ada.',
      vi: 'Mã khuyến mãi được yêu cầu không tồn tại.',
      uk: 'Запитаний промо-код не існує.',
    },
    statusCode: HttpStatusCodes.NOT_FOUND_404,
  },
} satisfies Record<string, ErrorCode>;
