import { HttpStatusCodes } from '@utils/httpStatusCodes';
import type { ErrorCode } from './errorCodes.types';

/**
 * Auth-related error codes.
 */
export const authErrors = {
  JWT_TOKEN_CREATION_FAILED_USER: {
    title: {
      en: 'JWT Token Creation Failed',
      fr: 'Echec de la création du jeton JWT',
      es: 'Error al crear el token JWT',
    },
    message: {
      en: 'JWT token creation failed for user.',
      fr: "Echec de la création du jeton JWT pour l'utilisateur.",
      es: 'Error al crear el token JWT para el usuario.',
    },
    statusCode: HttpStatusCodes.INTERNAL_SERVER_ERROR_500,
  },
  JWT_TOKEN_CREATION_FAILED_ORGANIZATION: {
    title: {
      en: 'JWT Token Creation Failed',
      fr: 'Echec de la création du jeton JWT',
      es: 'Error al crear el token JWT',
    },
    message: {
      en: 'JWT token creation failed for organization.',
      fr: "Echec de la création du jeton JWT pour l'organisation.",
      es: 'Error al crear el token JWT para la organización.',
    },
    statusCode: HttpStatusCodes.INTERNAL_SERVER_ERROR_500,
  },
  JWT_TOKEN_CREATION_FAILED_PROJECT: {
    title: {
      en: 'JWT Token Creation Failed',
      fr: 'Echec de la création du jeton JWT',
      es: 'Error al crear el token JWT',
    },
    message: {
      en: 'JWT token creation failed for project.',
      fr: 'Echec de la création du jeton JWT pour le projet.',
      es: 'Error al crear el token JWT para el proyecto.',
    },
    statusCode: HttpStatusCodes.INTERNAL_SERVER_ERROR_500,
  },
  JWT_TOKEN_ORGANIZATION_MISMATCH_PROJECT: {
    title: {
      en: 'Organization Mismatch',
      fr: 'Organisation non correspondante',
      es: 'Organización no coincidente',
    },
    message: {
      en: 'The specified organization does not match the organization of the project.',
      fr: "L'organisation spécifiée ne correspond pas à l'organisation du projet.",
      es: 'La organización especificada no coincide con la organización del proyecto.',
    },
    statusCode: HttpStatusCodes.UNAUTHORIZED_401,
  },
  ACCESS_KEY_NOT_FOUND: {
    title: {
      en: 'Access Key Not Found',
      'en-GB': 'Access Key Not Found',
      fr: "Clé d'accès non trouvée",
      es: 'Clave de acceso no encontrada',
      ru: 'Ключ доступа не найден',
      ja: 'アクセスキーが見つかりません',
      ko: '액세스 키를 찾을 수 없습니다',
      zh: '未找到访问密钥',
      de: 'Zugriffsschlüssel nicht gefunden',
      ar: 'مفتاح الوصول غير موجود',
      it: 'Chiave di accesso non trovata',
      pt: 'Chave de acesso não encontrada',
      hi: 'एक्सेस कुंजी नहीं मिली',
      tr: 'Erişim anahtarı bulunamadı',
      pl: 'Nie znaleziono klucza dostępu',
      id: 'Kunci Akses Tidak Ditemukan',
      vi: 'Không tìm thấy khóa truy cập',
      uk: 'Ключ доступу не знайдено',
    },
    message: {
      en: 'The specified access key could not be found.',
      'en-GB': 'The specified access key could not be found.',
      fr: "La clé d'accès spécifiée est introuvable.",
      es: 'La clave de acceso especificada no se pudo encontrar.',
      ru: 'Указанный ключ доступа не удалось найти.',
      ja: '指定されたアクセスキーが見つかりませんでした。',
      ko: '지정된 액세스 키를 찾을 수 없습니다.',
      zh: '找不到指定的访问密钥。',
      de: 'Der angegebene Zugriffsschlüssel konnte nicht gefunden werden.',
      ar: 'لم يتم العثور على مفتاح الوصول المحدد.',
      it: 'Impossibile trovare la chiave di accesso specificata.',
      pt: 'A chave de acesso especificada não pôde ser encontrada.',
      hi: 'निर्दिष्ट एक्सेस कुंजी नहीं मिली।',
      tr: 'Belirtilen erişim anahtarı bulunamadı.',
      pl: 'Określony klucz dostępu nie został znaleziony.',
      id: 'Kunci akses yang ditentukan tidak dapat ditemukan.',
      vi: 'Không thể tìm thấy khóa truy cập đã chỉ định.',
      uk: 'Вказаний ключ доступу не знайдено.',
    },
    statusCode: HttpStatusCodes.NOT_FOUND_404,
  },
  ACCESS_KEY_CREATION_FAILED: {
    title: {
      en: 'Access Key Creation Failed',
      'en-GB': 'Access Key Creation Failed',
      fr: "Échec de la création de la clé d'accès",
      es: 'Error al crear la clave de acceso',
      ru: 'Ошибка создания ключа доступа',
      ja: 'アクセスキーの作成に失敗しました',
      ko: '액세스 키 생성 실패',
      zh: '访问密钥创建失败',
      de: 'Zugriffsschlüsselerstellung fehlgeschlagen',
      ar: 'فشل إنشاء مفتاح الوصول',
      it: 'Creazione chiave di accesso fallita',
      pt: 'Falha na criação da chave de acceso',
      hi: 'एक्सेस कुंजी निर्माण विफल रहा',
      tr: 'Erişim anahtarı oluşturma başarısız',
      pl: 'Tworzenie klucza dostępu nie powiodło się',
      id: 'Pembuatan Kunci Akses Gagal',
      vi: 'Tạo khóa truy cập thất bại',
      uk: 'Помилка створення ключа доступу',
    },
    message: {
      en: 'Failed to create a new access key for the project.',
      'en-GB': 'Failed to create a new access key for the project.',
      fr: "La création d'une nouvelle clé d'accès pour le projet a échoué.",
      es: 'No se pudo crear una nueva clave de acceso para el proyecto.',
      ru: 'Не удалось создать новый ключ доступа для проекта.',
      ja: 'プロジェクトの新しいアクセスキーの作成に失敗しました。',
      ko: '프로젝트에 대한 새 액세스 키를 생성하지 못했습니다.',
      zh: '无法为项目创建新的访问密钥。',
      de: 'Ein neuer Zugriffsschlüssel für das Projekt konnte nicht erstellt werden.',
      ar: 'فشل في إنشاء مفتاح وصول جديد للمشروع.',
      it: 'Impossibile creare una nuova chiave di accesso per il progetto.',
      pt: 'Falha ao criar uma nova chave de acesso para o projeto.',
      hi: 'परियोजना के लिए एक नई एक्सेस कुंजी बनाने में विफल।',
      tr: 'Proje için yeni bir erişim anahtarı oluşturulamadı.',
      pl: 'Nie udało się utworzyć nowego klucza dostępu dla projektu.',
      id: 'Gagal membuat kunci akses baru untuk proyek tersebut.',
      vi: 'Không thể tạo khóa truy cập mới cho dự án.',
      uk: 'Не вдалося створити новий ключ доступу для проекту.',
    },
    statusCode: HttpStatusCodes.INTERNAL_SERVER_ERROR_500,
  },
  ACCESS_KEY_DELETION_FAILED: {
    title: {
      en: 'Access Key Deletion Failed',
      'en-GB': 'Access Key Deletion Failed',
      fr: "Échec de la suppression de la clé d'accès",
      es: 'Error al eliminar la clave de acceso',
      ru: 'Ошибка удаления ключа доступа',
      ja: 'アクセスキーの削除に失敗しました',
      ko: '액세스 키 삭제 실패',
      zh: '访问密钥删除失败',
      de: 'Zugriffsschlüssellöschung fehlgeschlagen',
      ar: 'فشل حذف مفتاح الوصول',
      it: 'Eliminazione chiave di accesso fallita',
      pt: 'Falha na exclusão da chave de acesso',
      hi: 'एक्सेस कुंजी हटाना विफल रहा',
      tr: 'Erişim anahtarı silme başarısız',
      pl: 'Usuwanie klucza dostępu nie powiodło się',
      id: 'Penghapusan Kunci Akses Gagal',
      vi: 'Xóa khóa truy cập thất bại',
      uk: 'Помилка видалення ключа доступу',
    },
    message: {
      en: 'Failed to delete the specified access key.',
      'en-GB': 'Failed to delete the specified access key.',
      fr: "La suppression de la clé d'accès a échoué.",
      es: 'No se pudo eliminar la clave de acceso especificada.',
      ru: 'Не удалось удалить указанный ключ доступа.',
      ja: '指定されたアクセスキーの削除に失敗しました。',
      ko: '지정된 액세스 키를 삭제하지 못했습니다.',
      zh: '无法删除指定的访问密钥。',
      de: 'Der angegebene Zugriffsschlüssel konnte nicht gelöscht werden.',
      ar: 'فشل في حذف مفتاح الوصول المحدد.',
      it: 'Impossibile eliminare la chiave di accesso specificata.',
      pt: 'Falha ao excluir a chave de acesso especificada.',
      hi: 'निर्दिष्ट एक्सेस कुंजी को हटाने में विफल।',
      tr: 'Belirtilen erişim anahtarı silinemedi.',
      pl: 'Nie udało się usunąć określonego klucza dostępu.',
      id: 'Gagal menghapus kunci akses yang ditentukan.',
      vi: 'Không thể xóa khóa truy cập đã chỉ định.',
      uk: 'Не вдалося видалити вказаний ключ доступу.',
    },
    statusCode: HttpStatusCodes.INTERNAL_SERVER_ERROR_500,
  },
  ACCESS_KEY_UPDATE_FAILED: {
    title: {
      en: 'Access Key Update Failed',
      'en-GB': 'Access Key Update Failed',
      fr: "Échec de la mise à jour de la clé d'accès",
      es: 'Error al actualizar la clave de acceso',
      ru: 'Ошибка обновления ключа доступа',
      ja: 'アクセスキーの更新に失敗しました',
      ko: '액세스 키 업데이트 실패',
      zh: '访问密钥更新失败',
      de: 'Zugriffsschlüsselaktualisierung fehlgeschlagen',
      ar: 'فشل تحديث مفتاح الوصول',
      it: 'Aggiornamento chiave di accesso fallito',
      pt: 'Falha na atualização da chave de acesso',
      hi: 'एक्सेस कुंजी अपडेट विफल रहा',
      tr: 'Erişim anahtarı güncelleme başarısız',
      pl: 'Aktualizacja klucza dostępu nie powiodła się',
      id: 'Pembaruan Kunci Akses Gagal',
      vi: 'Cập nhật khóa truy cập thất bại',
      uk: 'Помилка оновлення ключа доступу',
    },
    message: {
      en: 'Failed to update the specified access key.',
      'en-GB': 'Failed to update the specified access key.',
      fr: "La mise à jour de la clé d'accès a échoué.",
      es: 'No se pudo actualizar la clave de acceso especificada.',
      ru: 'Не удалось обновить указанный ключ доступа.',
      ja: '指定されたアクセスキーの更新に失敗しました。',
      ko: '지정된 액세스 키를 업데이트하지 못했습니다.',
      zh: '无法更新指定的访问密钥。',
      de: 'Der angegebene Zugriffsschlüssel konnte nicht aktualisiert werden.',
      ar: 'فشل في تحديث مفتاح الوصول المحدد.',
      it: 'Impossibile aggiornare la chiave di accesso specificata.',
      pt: 'Falha ao atualizar a chave de acesso especificada.',
      hi: 'निर्दिष्ट एक्सेस कुंजी को अपडेट करने में विफल।',
      tr: 'Belirtilen erişim anahtarı güncellenemedi.',
      pl: 'Nie udało się zaktualizować określonego klucza dostępu.',
      id: 'Gagal memperbarui kunci akses yang ditentukan.',
      vi: 'Không thể cập nhật khóa truy cập đã chỉ định.',
      uk: 'Не вдалося оновити вказаний ключ доступу.',
    },
    statusCode: HttpStatusCodes.INTERNAL_SERVER_ERROR_500,
  },
  ACCESS_KEY_INVALID: {
    title: {
      en: 'Invalid Access Key',
      'en-GB': 'Invalid Access Key',
      fr: "Clé d'accès invalide",
      es: 'Clave de acceso no válida',
      ru: 'Недопустимый ключ доступа',
      ja: '無効なアクセスキー',
      ko: '유효하지 않은 액세스 키',
      zh: '访问密钥无效',
      de: 'Ungültiger Zugriffsschlüssel',
      ar: 'مفتاح الوصول غير صالح',
      it: 'Chiave di accesso non valida',
      pt: 'Chave de acesso inválida',
      hi: 'अमान्य एक्सेस कुंजी',
      tr: 'Geçersiz erişim anahtarı',
      pl: 'Nieprawidłowy klucz dostępu',
      id: 'Kunci Akses Tidak Valid',
      vi: 'Khóa truy cập không hợp lệ',
      uk: 'Неприпустимий ключ доступу',
    },
    message: {
      en: 'The provided access key is invalid or expired.',
      'en-GB': 'The provided access key is invalid or expired.',
      fr: "La clé d'accès fournie est invalide ou expirée.",
      es: 'La clave de acceso proporcionada no es válida o ha expirado.',
      ru: 'Предоставленный ключ доступа недействителен или истек.',
      ja: '提供されたアクセスキーが無効であるか、期限が切れています。',
      ko: '제공된 액세스 키가 유효하지 않거나 만료되었습니다.',
      zh: '提供的访问密钥无效或已过期。',
      de: 'Der angegebene Zugriffsschlüssel ist ungültig oder abgelaufen.',
      ar: 'مفتاح الوصول المقدم غير صالح أو منتهي الصلاحية.',
      it: 'La chiave di accesso fornita non è valida o è scaduta.',
      pt: 'A chave de acesso fornecida é inválida ou expirou.',
      hi: 'प्रदान की गई एक्सेस कुंजी अमान्य है या उसकी अवधि समाप्त हो गई है।',
      tr: 'Sağlanan erişim anahtarı geçersiz veya süresi dolmuş.',
      pl: 'Podany klucz dostępu jest nieprawidłowy lub wygasł.',
      id: 'Kunci akses yang diberikan tidak valid atau kedaluwarsa.',
      vi: 'Khóa truy cập được cung cấp không hợp lệ hoặc đã hết hạn.',
      uk: 'Наданий ключ доступу неприпустимий або термін його дії закінчився.',
    },
    statusCode: HttpStatusCodes.UNAUTHORIZED_401,
  },
  LOGIN_FAILED: {
    title: {
      en: 'Login Failed',
      'en-GB': 'Login Failed',
      fr: 'Échec de la connexion',
      es: 'Error al iniciar sesión',
      ru: 'Ошибка входа',
      ja: 'ログインに失敗しました',
      ko: '로그인 실패',
      zh: '登录失败',
      de: 'Anmeldung fehlgeschlagen',
      ar: 'فشل تسجيل الدخول',
      it: 'Accesso fallito',
      pt: 'Falha no login',
      hi: 'लॉगिन विफल',
      tr: 'Giriş başarısız',
      pl: 'Logowanie nie powiodło się',
      id: 'Login Gagal',
      vi: 'Đăng nhập thất bại',
      uk: 'Помилка входу',
    },
    message: {
      en: 'The email or password provided is incorrect.',
      'en-GB': 'The email or password provided is incorrect.',
      fr: "L'email ou le mot de passe fourni est incorrect.",
      es: 'El correo electrónico o la contraseña proporcionada es incorrecta.',
      ru: 'Указанный email или пароль неверны.',
      ja: '提供されたメールアドレスまたはパスワードが正しくありません。',
      ko: '제공된 이메일 또는 비밀번호가 올바르지 않습니다.',
      zh: '提供的电子邮件或密码不正确。',
      de: 'Die angegebene E-Mail oder das Passwort ist falsch.',
      ar: 'البريد الإلكتروني أو كلمة المرور المقدمة غير صحيحة.',
      it: 'L’email o la password fornite non sono corrette.',
      pt: 'O e-mail ou a senha fornecidos estão incorretos.',
      hi: 'प्रदान किया गया ईमेल या पासवर्ड गलत है।',
      tr: 'Sağlanan e-posta veya şifre yanlış.',
      pl: 'Podany e-mail lub hasło są nieprawidłowe.',
      id: 'Email atau kata sandi yang diberikan salah.',
      vi: 'Email hoặc mật khẩu được cung cấp không chính xác.',
      uk: 'Наданий email або пароль невірні.',
    },
    statusCode: HttpStatusCodes.BAD_REQUEST_400,
  },
  AUTH_ERROR: {
    title: {
      en: 'Authentication Error',
      'en-GB': 'Authentication Error',
      fr: "Erreur d'authentification",
      es: 'Error de autenticación',
      ru: 'Ошибка аутентификации',
      ja: '認証エラー',
      ko: '인증 오류',
      zh: '身份验证错误',
      de: 'Authentifizierungsfehler',
      ar: 'خطأ في المصادقة',
      it: 'Errore di autenticazione',
      pt: 'Erro de autenticação',
      hi: 'प्रमाणीकरण त्रुटि',
      tr: 'Kimlik doğrulama hatası',
      pl: 'Błąd uwierzytelniania',
      id: 'Kesalahan Autentikasi',
      vi: 'Lỗi xác thực',
      uk: 'Помилка автентифікації',
    },
    message: {
      en: 'Authentication fail because access token is invalid.',
      'en-GB': 'Authentication failed because the access token is invalid.',
      fr: "L'authentification a échoué car le jeton d'accès est invalide.",
      es: 'La autenticación falló porque el token de acceso es inválido.',
      ru: 'Аутентификация не удалась, так как токен доступа недействителен.',
      ja: 'アクセストークンが無効なため、認証に失敗しました。',
      ko: '액세스 토큰이 유효하지 않아 인증에 실패했습니다.',
      zh: '由于访问令牌无效，身份验证失败。',
      de: 'Authentifizierung fehlgeschlagen, da das Zugriffstoken ungültig ist.',
      ar: 'فشلت المصادقة لأن رمز الوصول غير صالح.',
      it: 'Autenticazione fallita perché il token di accesso non è valido.',
      pt: 'A autenticação falhou porque o token de acesso é inválido.',
      hi: 'प्रमाणीकरण विफल रहा क्योंकि एक्सेस टोकन अमान्य है।',
      tr: 'Erişim belirteci geçersiz olduğu için kimlik doğrulaması başarısız oldu.',
      pl: 'Uwierzytelnianie nie powiodło się, ponieważ token dostępu jest nieprawidłowy.',
      id: 'Autentikasi gagal karena token akses tidak valid.',
      vi: 'Xác thực thất bại vì mã thông báo truy cập không hợp lệ.',
      uk: 'Помилка автентифікації, оскільки токен доступу неприпустимий.',
    },
    statusCode: HttpStatusCodes.UNAUTHORIZED_401,
  },
  TOO_MANY_CONNECTIONS: {
    title: {
      en: 'Too many connections',
      'en-GB': 'Too many connections',
      fr: 'Trop de connexions',
      es: 'Demasiadas conexiones',
      ru: 'Слишком много подключений',
      ja: '接続が多すぎます',
      ko: '접속자가 너무 많습니다',
      zh: '连接过多',
      de: 'Zu viele Verbindungen',
      ar: 'عدد كبير جدا من الاتصالات',
      it: 'Troppe connessioni',
      pt: 'Muitas conexões',
      hi: 'बहुत अधिक कनेक्शन',
      tr: 'Çok fazla bağlantı',
      pl: 'Zbyt wiele połączeń',
      id: 'Terlalu Banyak Koneksi',
      vi: 'Quá nhiều kết nối',
      uk: 'Занадто багато з’єднань',
    },
    message: {
      en: 'Too many connections. Please try again later.',
      'en-GB': 'Too many connections. Please try again later.',
      fr: 'Trop de connexions. Veuillez réessayer plus tard.',
      es: 'Demasiadas conexiones. Por favor, inténtelo de nuevo más tarde.',
      ru: 'Слишком много подключений. Пожалуйста, попробуйте позже.',
      ja: '接続が多すぎます。後でもう一度お試しください。',
      ko: '접속자가 너무 많습니다. 나중에 다시 시도하십시오.',
      zh: '连接过多。请稍后再试。',
      de: 'Zu viele Verbindungen. Bitte versuchen Sie es später erneut.',
      ar: 'عدد كبير جدا من الاتصالات. يرجى المحاولة مرة أخرى في وقت لاحق.',
      it: 'Troppe connessioni. Riprova più tardi.',
      pt: 'Muitas conexões. Por favor, tente novamente mais tarde.',
      hi: 'बहुत अधिक कनेक्शन। कृपया बाद में पुनः प्रयास करें।',
      tr: 'Çok fazla bağlantı. Lütfen daha sonra tekrar deneyiniz.',
      pl: 'Zbyt wiele połączeń. Proszę spróbować później.',
      id: 'Terlalu banyak koneksi. Harap coba lagi nanti.',
      vi: 'Quá nhiều kết nối. Vui lòng thử lại sau.',
      uk: 'Занадто багато з’єднань. Будь ласка, спробуйте пізніше.',
    },
    statusCode: HttpStatusCodes.CONFLICT_409,
  },
  INVALID_USER_ID: {
    title: {
      en: 'Invalid User ID',
      'en-GB': 'Invalid User ID',
      fr: 'Identifiant utilisateur non valide',
      es: 'Identificador de usuario no válido',
      ru: 'Недопустимый ID пользователя',
      ja: '無効なユーザーID',
      ko: '유효하지 않은 사용자 ID',
      zh: '用户 ID 无效',
      de: 'Ungültige Benutzer-ID',
      ar: 'معرف مستخدم غير صالح',
      it: 'ID utente non valido',
      pt: 'ID de usuário inválido',
      hi: 'अमान्य उपयोगकर्ता आईडी',
      tr: 'Geçersiz kullanıcı ID',
      pl: 'Nieprawidłowy identyfikator użytkownika',
      id: 'ID Pengguna Tidak Valid',
      vi: 'Mã người dùng không hợp lệ',
      uk: 'Неприпустимий ID користувача',
    },
    message: {
      en: 'The provided user ID is invalid.',
      'en-GB': 'The provided user ID is invalid.',
      fr: "L'identifiant utilisateur fourni n'est pas valide.",
      es: 'El identificador de usuario proporcionado no es válido.',
      ru: 'Предоставленный ID пользователя недопустим.',
      ja: '提供されたユーザーIDが無効です。',
      ko: '제공된 사용자 ID가 유효하지 않습니다.',
      zh: '提供的用户 ID 无效。',
      de: 'Die angegebene Benutzer-ID ist ungültig.',
      ar: 'معرف المستخدم المقدم غير صالح.',
      it: 'L’ID utente fornito non è valido.',
      pt: 'O ID de usuário fornecido é inválido.',
      hi: 'प्रदान की गई उपयोगकर्ता आईडी अमान्य है।',
      tr: 'Sağlanan kullanıcı ID geçersiz.',
      pl: 'Podany identyfikator użytkownika jest nieprawidłowy.',
      id: 'ID pengguna yang diberikan tidak valid.',
      vi: 'Mã người dùng được cung cấp không hợp lệ.',
      uk: 'Наданий ID користувача неприпустимий.',
    },
    statusCode: HttpStatusCodes.BAD_REQUEST_400,
  },
  EMAIL_NOT_PROVIDED: {
    title: {
      en: 'Email Not Provided',
      'en-GB': 'Email Not Provided',
      fr: 'Email non fourni',
      es: 'Email no proporcionado',
      ru: 'Email не предоставлен',
      ja: 'メールアドレスが提供されていません',
      ko: '이메일이 제공되지 않았습니다',
      zh: '未提供电子邮件',
      de: 'E-Mail nicht angegeben',
      ar: 'البريد الإلكتروني غير متوفر',
      it: 'Email non fornita',
      pt: 'E-mail não fornecido',
      hi: 'ईमेल प्रदान नहीं किया गया',
      tr: 'E-posta sağlanmadı',
      pl: 'Nie podano adresu e-mail',
      id: 'Email Tidak Disediakan',
      vi: 'Email không được cung cấp',
      uk: 'Email не надано',
    },
    message: {
      en: 'Email not provided.',
      'en-GB': 'Email not provided.',
      fr: 'Email non fourni.',
      es: 'Email no proporcionado.',
      ru: 'Email не предоставлен.',
      ja: 'メールアドレスが提供されていません。',
      ko: '이메일이 제공되지 않았습니다.',
      zh: '未提供电子邮件。',
      de: 'E-Mail wurde nicht angegeben.',
      ar: 'لم يتم توفير البريد الإلكتروني.',
      it: 'Email non fornita.',
      pt: 'E-mail não fornecido.',
      hi: 'ईमेल प्रदान नहीं किया गया।',
      tr: 'E-posta sağlanmadı.',
      pl: 'Nie podano adresu e-mail.',
      id: 'Email tidak disediakan.',
      vi: 'Email không được cung cấp.',
      uk: 'Email не надано.',
    },
    statusCode: HttpStatusCodes.BAD_REQUEST_400,
  },
  SECRET_NOT_PROVIDED: {
    title: {
      en: 'Secret Not Provided',
      'en-GB': 'Secret Not Provided',
      fr: 'Secret non fourni',
      es: 'Secreto no proporcionado',
      ru: 'Секрет не предоставлен',
      ja: 'シークレットが提供されていません',
      ko: '비밀이 제공되지 않았습니다',
      zh: '未提供密钥',
      de: 'Geheimnis nicht angegeben',
      ar: 'السر غير متوفر',
      it: 'Segreto non fornito',
      pt: 'Segredo não fornecido',
      hi: 'गुप्त प्रदान नहीं किया गया',
      tr: 'Gizli anahtar sağlanmadı',
      pl: 'Nie podano klucza tajnego',
      id: 'Rahasia Tidak Disediakan',
      vi: 'Bí mật không được cung cấp',
      uk: 'Секрет не надано',
    },
    message: {
      en: 'Secret not provided.',
      'en-GB': 'Secret not provided.',
      fr: 'Secret non fourni.',
      es: 'Secreto no proporcionado.',
      ru: 'Секрет не предоставлен.',
      ja: 'シークレットが提供されていません。',
      ko: '비밀이 제공되지 않았습니다.',
      zh: '未提供密钥。',
      de: 'Geheimnis wurde nicht angegeben.',
      ar: 'لم يتم توفير السر.',
      it: 'Segreto non fornito.',
      pt: 'Segredo não fornecido.',
      hi: 'गुप्त प्रदान नहीं किया गया।',
      tr: 'Gizli anahtar sağlanmadı.',
      pl: 'Nie podano klucza tajnego.',
      id: 'Rahasia tidak disediakan.',
      vi: 'Bí mật không được cung cấp.',
      uk: 'Секрет не надано.',
    },
    statusCode: HttpStatusCodes.BAD_REQUEST_400,
  },
  SESSION_NOT_FOUND: {
    title: {
      en: 'Session Not Found',
      'en-GB': 'Session Not Found',
      fr: 'Session non trouvée',
      es: 'Sesión no encontrada',
      ru: 'Сессия не найдена',
      ja: 'セッションが見つかりません',
      ko: '세션을 찾을 수 없습니다',
      zh: '未找到会话',
      de: 'Sitzung nicht gefunden',
      ar: 'الجلسة غير موجودة',
      it: 'Sessione non trovata',
      pt: 'Sessão não encontrada',
      hi: 'सत्र नहीं मिला',
      tr: 'Oturum bulunamadı',
      pl: 'Nie znaleziono sesji',
      id: 'Sesi Tidak Ditemukan',
      vi: 'Không tìm thấy phiên',
      uk: 'Сесія не знайдена',
    },
    message: {
      en: 'The session was not found.',
      'en-GB': 'The session was not found.',
      fr: "La session n'a pas été trouvée.",
      es: 'La sesión no se ha encontrado.',
      ru: 'Сессия не была найдена.',
      ja: 'セッションが見つかりませんでした。',
      ko: '세션을 찾을 수 없습니다.',
      zh: '未找到会话。',
      de: 'Die Sitzung wurde nicht gefunden.',
      ar: 'لم يتم العثور على الجلسة.',
      it: 'La sessione non è stata trovata.',
      pt: 'A sessão não foi encontrada.',
      hi: 'सत्र नहीं मिला।',
      tr: 'Oturum bulunamadı.',
      pl: 'Sesja nie została znaleziona.',
      id: 'Sesi tidak ditemukan.',
      vi: 'Phiên không được tìm thấy.',
      uk: 'Сесію не було знайдено.',
    },
    statusCode: HttpStatusCodes.NOT_FOUND_404,
  },
  CLIENT_ID_NOT_FOUND: {
    title: {
      en: 'Client ID Not Found',
      'en-GB': 'Client ID Not Found',
      fr: 'Identifiant client non trouvé',
      es: 'Identificador de cliente no encontrado',
      ru: 'ID клиента не найден',
      ja: 'クライアントIDが見つかりません',
      ko: '클라이언트 ID를 찾을 수 없습니다',
      zh: '未找到客户端 ID',
      de: 'Client-ID nicht gefunden',
      ar: 'معرف العميل غير موجود',
      it: 'ID client non trovato',
      pt: 'ID do cliente não encontrado',
      hi: 'क्लाइंट आईडी नहीं मिला',
      tr: 'İstemci ID bulunamadı',
      pl: 'Nie znaleziono identyfikatora klienta',
      id: 'ID Klien Tidak Ditemukan',
      vi: 'Không tìm thấy mã định danh khách hàng',
      uk: 'ID клієнта не знайдено',
    },
    message: {
      en: 'The client ID was not found.',
      'en-GB': 'The client ID was not found.',
      fr: "L'identifiant client n'a pas été trouvé.",
      es: 'El identificador de cliente no se ha encontrado.',
      ru: 'ID клиента не был найден.',
      ja: 'クライアントIDが見つかりませんでした。',
      ko: '클라이언트 ID를 찾을 수 없습니다.',
      zh: '未找到客户端 ID。',
      de: 'Die Client-ID wurde nicht gefunden.',
      ar: 'لم يتم العثور على معرف العميل.',
      it: 'L’ID del client non è stato trovato.',
      pt: 'O ID do cliente não foi encontrado.',
      hi: 'क्लाइंट आईडी नहीं मिला।',
      tr: 'İstemci ID bulunamadı.',
      pl: 'Identyfikator klienta nie został znaleziony.',
      id: 'ID klien tidak ditemukan.',
      vi: 'Mã định danh khách hàng không được tìm thấy.',
      uk: 'ID клієнта не було знайдено.',
    },
    statusCode: HttpStatusCodes.NOT_FOUND_404,
  },
  SESSION_NOT_DEFINED: {
    title: {
      en: 'Session not defined',
      'en-GB': 'Session not defined',
      fr: 'Session non définie',
      es: 'Sesión no definida',
      ru: 'Сессия не определена',
      ja: 'セッションが定義されていません',
      ko: '세션이 정의되지 않았습니다',
      zh: '会话未定义',
      de: 'Sitzung nicht definiert',
      ar: 'الجلسة غير محددة',
      it: 'Sessione non definita',
      pt: 'Sessão não definida',
      hi: 'सत्र परिभाषित नहीं है',
      tr: 'Oturum tanımlanmadı',
      pl: 'Sesja nie została zdefiniowana',
      id: 'Sesi Tidak Didefinisikan',
      vi: 'Phiên không được xác định',
      uk: 'Сесію не визначено',
    },
    message: {
      en: 'The session is not defined.',
      'en-GB': 'The session is not defined.',
      fr: "La session n'est pas définie.",
      es: 'La sesión no está definida.',
      ru: 'Сессия не определена.',
      ja: 'セッションが定義されていません。',
      ko: '세션이 정의되지 않았습니다.',
      zh: '会话未定义。',
      de: 'Die Sitzung ist nicht definiert.',
      ar: 'الجلسة غير محددة.',
      it: 'La sessione non è definita.',
      pt: 'A sessão não está definida.',
      hi: 'सत्र परिभाषित नहीं है।',
      tr: 'Oturum tanımlanmadı.',
      pl: 'Sesja nie została zdefiniowana.',
      id: 'Sesi tidak didefinisikan.',
      vi: 'Phiên không được xác định.',
      uk: 'Сесію не визначено.',
    },
    statusCode: HttpStatusCodes.BAD_REQUEST_400,
  },
  INVALID_OAUTH_GRANT_TYPE: {
    title: {
      en: 'Invalid OAuth grant type',
      'en-GB': 'Invalid OAuth grant type',
      fr: 'Type de grant OAuth invalide',
      es: 'Tipo de concesión OAuth no válido',
      ru: 'Недопустимый тип авторизации OAuth',
      ja: '無効なOAuthグラントタイプ',
      ko: '유효하지 않은 OAuth 권한 부여 유형',
      zh: 'OAuth 授权类型无效',
      de: 'Ungültiger OAuth-Grant-Typ',
      ar: 'نوع منح OAuth غير صالح',
      it: 'Tipo di autorizzazione OAuth non valido',
      pt: 'Tipo de concessão OAuth inválido',
      hi: 'अमान्य OAuth अनुदान प्रकार',
      tr: 'Geçersiz OAuth yetki türü',
      pl: 'Nieprawidłowy typ uprawnień OAuth',
      id: 'Jenis Hibah OAuth Tidak Valid',
      vi: 'Loại cấp phép OAuth không hợp lệ',
      uk: 'Неприпустимий тип авторизації OAuth',
    },
    message: {
      en: 'The grant type is invalid.',
      'en-GB': 'The grant type is invalid.',
      fr: 'Le type de grant est invalide.',
      es: 'El tipo de concesión es no válido.',
      ru: 'Тип авторизации недействителен.',
      ja: 'グラントタイプが無効です。',
      ko: '권한 부여 유형이 유효하지 않습니다.',
      zh: '授权类型无效。',
      de: 'Der Grant-Typ ist ungültig.',
      ar: 'نوع المنح غير صالح.',
      it: 'Il tipo di autorizzazione non è valido.',
      pt: 'O tipo de concessão é inválido.',
      hi: 'अनुदान प्रकार अमान्य है।',
      tr: 'Yetki türü geçersiz.',
      pl: 'Typ uprawnień jest nieprawidłowy.',
      id: 'Jenis hibah tidak valid.',
      vi: 'Loại cấp phép không hợp lệ.',
      uk: 'Тип авторизації неприпустимий.',
    },
    statusCode: HttpStatusCodes.BAD_REQUEST_400,
  },
  INVALID_OAUTH_CLIENT: {
    title: {
      en: 'Invalid OAuth client',
      'en-GB': 'Invalid OAuth client',
      fr: 'Client OAuth invalide',
      es: 'Cliente OAuth no válido',
      ru: 'Недопустимый клиент OAuth',
      ja: '無効なOAuthクライアント',
      ko: '유효하지 않은 OAuth 클라이언트',
      zh: 'OAuth 客户端无效',
      de: 'Ungültiger OAuth-Client',
      ar: 'عميل OAuth غير صالح',
      it: 'Client OAuth non valido',
      pt: 'Cliente OAuth inválido',
      hi: 'अमान्य OAuth क्लाइंट',
      tr: 'Geçersiz OAuth istemcisi',
      pl: 'Nieprawidłowy klient OAuth',
      id: 'Klien OAuth Tidak Valid',
      vi: 'Máy khách OAuth không hợp lệ',
      uk: 'Неприпустимий клієнт OAuth',
    },
    message: {
      en: 'The client is invalid.',
      'en-GB': 'The client is invalid.',
      fr: 'Le client est invalide.',
      es: 'El cliente es no válido.',
      ru: 'Клиент недействителен.',
      ja: 'クライアントが無効です。',
      ko: '클라이언트가 유효하지 않습니다.',
      zh: '客户端无效。',
      de: 'Der Client ist ungültig.',
      ar: 'العميل غير صالح.',
      it: 'Il client non è valido.',
      pt: 'O cliente é inválido.',
      hi: 'क्लाइंट अमान्य है।',
      tr: 'İstemci geçersiz.',
      pl: 'Klient jest nieprawidłowy.',
      id: 'Klien tidak valid.',
      vi: 'Máy khách không hợp lệ.',
      uk: 'Клієнт неприпустимий.',
    },
    statusCode: HttpStatusCodes.BAD_REQUEST_400,
  },
  INVALID_ACCESS_TOKEN: {
    title: {
      en: 'Invalid access token',
      'en-GB': 'Invalid access token',
      fr: "Jeton d'accès invalide",
      es: 'Token de acceso no válido',
      ru: 'Недопустимый токен доступа',
      ja: 'アクセストークンが無効です',
      ko: '유효하지 않은 액세스 토큰',
      zh: '访问令牌无效',
      de: 'Ungültiger Zugriffstoken',
      ar: 'رمز وصول غير صالح',
      it: 'Token di accesso non valido',
      pt: 'Token de acesso inválido',
      hi: 'अमान्य एक्सेस टोकन',
      tr: 'Geçersiz erişim anahtarı',
      pl: 'Nieprawidłowy token dostępu',
      id: 'Token Akses Tidak Valid',
      vi: 'Mã truy cập không hợp lệ',
      uk: 'Неприпустимий токен доступу',
    },
    message: {
      en: 'The access token is invalid.',
      'en-GB': 'The access token is invalid.',
      fr: "Le jeton d'accès est invalide.",
      es: 'El token de acceso es no válido.',
      ru: 'Токен доступа недействителен.',
      ja: 'アクセストークンが無効です。',
      ko: '액세스 토큰이 유효하지 않습니다.',
      zh: '访问令牌无效。',
      de: 'Der Zugriffstoken ist ungültig.',
      ar: 'رمز الوصول غير صالح.',
      it: 'Il token di accesso non è valido.',
      pt: 'O token de acesso é inválido.',
      hi: 'एक्सेस टोकन अमान्य है।',
      tr: 'Erişim anahtarı geçersiz.',
      pl: 'Token dostępu jest nieprawidłowy.',
      id: 'Token akses tidak valid.',
      vi: 'Mã truy cập không hợp lệ.',
      uk: 'Токен доступу неприпустимий.',
    },
    statusCode: HttpStatusCodes.BAD_REQUEST_400,
  },
  EXPIRED_ACCESS_TOKEN: {
    title: {
      en: 'Expired access token',
      'en-GB': 'Expired access token',
      fr: "Jeton d'accès expiré",
      es: 'Token de acceso expirado',
      ru: 'Истек срок действия токена доступа',
      ja: 'アクセストークンの期限が切れました',
      ko: '액세스 토큰 만료',
      zh: '访问令牌已过期',
      de: 'Zugriffstoken abgelaufen',
      ar: 'انتهت صلاحية رمز الوصول',
      it: 'Token di accesso scaduto',
      pt: 'Token de acesso expirado',
      hi: 'एक्सेस टोकन समाप्त हो गया है',
      tr: 'Erişim anahtarının süresi doldu',
      pl: 'Token dostępu wygasł',
      id: 'Token Akses Kedaluwarsa',
      vi: 'Mã truy cập đã hết hạn',
      uk: 'Термін дії токена доступу закінчився',
    },
    message: {
      en: 'The access token has expired.',
      'en-GB': 'The access token has expired.',
      fr: "Le jeton d'accès a expiré.",
      es: 'El token de acceso ha expirado.',
      ru: 'Срок действия токена доступа истек.',
      ja: 'アクセストークンの期限が切れました。',
      ko: '액세스 토큰이 만료되었습니다.',
      zh: '访问令牌已过期。',
      de: 'Der Zugriffstoken ist abgelaufen.',
      ar: 'انتهت صلاحية رمز الوصول.',
      it: 'Il token di accesso è scaduto.',
      pt: 'O token de acesso expirou.',
      hi: 'एक्सेस टोकन समाप्त हो गया है।',
      tr: 'Erişim anahtarının süresi doldu.',
      pl: 'Token dostępu wygasł.',
      id: 'Token akses telah kedaluwarsa.',
      vi: 'Mã truy cập đã hết hạn.',
      uk: 'Термін дії токена доступу закінчився.',
    },
    statusCode: HttpStatusCodes.BAD_REQUEST_400,
  },
  PERMISSION_DENIED: {
    title: {
      en: 'Permission Denied',
      'en-GB': 'Permission Denied',
      fr: 'Permission refusée',
      es: 'Permiso denegado',
      ru: 'Доступ запрещен',
      ja: 'アクセス許可がありません',
      ko: '권한 거부됨',
      zh: '权限被拒绝',
      de: 'Berechtigung verweigert',
      ar: 'تم رفض الإذن',
      it: 'Permesso negato',
      pt: 'Permissão negada',
      hi: 'अनुमति अस्वीकार कर दी गई',
      tr: 'İzin reddedildi',
      pl: 'Odmowa uprawnień',
      id: 'Izin Ditolak',
      vi: 'Quyền truy cập bị từ chối',
      uk: 'Доступ заборонено',
    },
    message: {
      en: 'You do not have permission to access this resource.',
      'en-GB': 'You do not have permission to access this resource.',
      fr: "Vous n'avez pas les permissions nécessaires pour accéder à cette ressource.",
      es: 'No tienes permisos para acceder a este recurso.',
      ru: 'У вас нет прав для доступа к этому ресурсу.',
      ja: 'このリソースにアクセスする権限がありません。',
      ko: '이 리소스에 액세스할 권한이 없습니다.',
      zh: '您没有访问此资源的权限。',
      de: 'Sie haben keine Berechtigung, auf diese Ressource zuzugreifen.',
      ar: 'ليس لديك إذن للوصول إلى هذا المورد.',
      it: 'Non hai il permesso di accedere a questa risorsa.',
      pt: 'Você não tem permissão para acessar este recurso.',
      hi: 'आपके पास इस संसाधन तक पहुँचने की अनुमति नहीं है।',
      tr: 'Bu kaynağa erişim izniniz yok.',
      pl: 'Nie masz uprawnień do dostępu do tego zasobu.',
      id: 'Anda tidak memiliki izin untuk mengakses sumber daya ini.',
      vi: 'Bạn không có quyền truy cập vào tài nguyên này.',
      uk: 'У вас немає прав для доступу до цього ресурсу.',
    },
    statusCode: HttpStatusCodes.FORBIDDEN_403,
  },
} satisfies Record<string, ErrorCode>;
