import { HttpStatusCodes } from '@utils/httpStatusCodes';
import type { ErrorCode } from './errorCodes.types';

/**
 * Billing-related error codes.
 */
export const billingErrors = {
  PLAN_NOT_FOUND: {
    title: {
      en: 'Plan Not Found',
      'en-GB': 'Plan Not Found',
      fr: 'Plan non trouvé',
      es: 'Plan no encontrado',
      ru: 'План не найден',
      ja: 'プランが見つかりません',
      ko: '요금제를 찾을 수 없습니다',
      zh: '未找到计划',
      de: 'Plan nicht gefunden',
      ar: 'الخطة غير موجودة',
      it: 'Piano non trovato',
      pt: 'Plano não encontrado',
      hi: 'योजना नहीं मिली',
      tr: 'Plan bulunamadı',
      pl: 'Nie znaleziono planu',
      id: 'Paket Tidak Ditemukan',
      vi: 'Không tìm thấy gói',
      uk: 'План не знайдено',
    },
    message: {
      en: 'Plan not found',
      'en-GB': 'Plan not found',
      fr: 'Plan non trouvé',
      es: 'Plan no encontrado',
      ru: 'План не найден.',
      ja: 'プランが見つかりませんでした。',
      ko: '요금제를 찾을 수 없습니다.',
      zh: '未找到计划。',
      de: 'Plan wurde nicht gefunden.',
      ar: 'لم يتم العثور على الخطة.',
      it: 'Piano non trovato.',
      pt: 'Plano não encontrado.',
      hi: 'योजना नहीं मिली।',
      tr: 'Plan bulunamadı.',
      pl: 'Nie znaleziono planu.',
      id: 'Paket tidak ditemukan.',
      vi: 'Không tìm thấy gói.',
      uk: 'План не знайдено.',
    },
    statusCode: HttpStatusCodes.NOT_FOUND_404,
  },
  MULTIPLE_PLANS_FOUND: {
    title: {
      en: 'Multiple Plans Found',
      'en-GB': 'Multiple Plans Found',
      fr: 'Plusieurs plans trouvés',
      es: 'Múltiples planes encontrados',
      ru: 'Найдено несколько планов',
      ja: '複数のプランが見つかりました',
      ko: '여러 요금제가 발견되었습니다',
      zh: '找到多个计划',
      de: 'Mehrere Pläne gefunden',
      ar: 'تم العثور على خطط متعددة',
      it: 'Trovati più piani',
      pt: 'Múltiplos planos encontrados',
      hi: 'एकाधिक योजनाएं मिलीं',
      tr: 'Birden fazla plan bulundu',
      pl: 'Znaleziono wiele planów',
      id: 'Beberapa Paket Ditemukan',
      vi: 'Tìm thấy nhiều gói',
      uk: 'Знайдено кілька планів',
    },
    message: {
      en: 'Multiple plans found for the provided information.',
      'en-GB': 'Multiple plans found for the provided information.',
      fr: "Plusieurs plans trouvés pour l'information fournie.",
      es: 'Múltiples planes encontrados para la información proporcionada.',
      ru: 'Для предоставленной информации найдено несколько планов.',
      ja: '提供された情報に対して複数のプランが見つかりました。',
      ko: '제공된 정보에 대해 여러 요금제가 발견되었습니다.',
      zh: '根据提供的信息找到多个计划。',
      de: 'Für die bereitgestellten Informationen wurden mehrere Pläne gefunden.',
      ar: 'تم العثور على خطط متعددة للمعلومات المقدمة.',
      it: 'Trovati più piani per le informazioni fornite.',
      pt: 'Múltiplos planos encontrados para as informações fornecidas.',
      hi: 'प्रदान की गई जानकारी के लिए एकाधिक योजनाएं मिलीं।',
      tr: 'Sağlanan bilgiler için birden fazla plan bulundu.',
      pl: 'Znaleziono wiele planów dla podanych informacji.',
      id: 'Beberapa paket ditemukan untuk informasi yang diberikan.',
      vi: 'Tìm thấy nhiều gói cho thông tin được cung cấp.',
      uk: 'Для наданої інформації знайдено кілька планів.',
    },
    statusCode: HttpStatusCodes.BAD_REQUEST_400,
  },
  PLAN_USER_LIMIT_REACHED: {
    title: {
      en: 'Plan User Limit Reached',
      'en-GB': 'Plan User Limit Reached',
      fr: 'Limite de participants atteinte',
      es: 'Límite de participantes alcanzado',
      ru: 'Достигнут лимит пользователей плана',
      ja: 'プランのユーザー制限に達しました',
      ko: '요금제 사용자 제한에 도달했습니다',
      zh: '已达到计划用户限制',
      de: 'Nutzerlimit des Plans erreicht',
      ar: 'تم الوصول إلى الحد الأقصى لمستخدمي الخطة',
      it: 'Limite utenti del piano raggiunto',
      pt: 'Limite de usuários do plano atingido',
      hi: 'योजना उपयोगकर्ता सीमा समाप्त हो गई है',
      tr: 'Plan kullanıcı sınırına ulaşıldı',
      pl: 'Osiągnięto limit użytkowników planu',
      id: 'Batas Pengguna Paket Tercapai',
      vi: 'Đã đạt giới hạn người dùng của gói',
      uk: 'Досягнуто ліміту користувачів плану',
    },
    message: {
      en: 'The plan has reached its user limit. Please upgrade to add more users.',
      'en-GB':
        'The plan has reached its user limit. Please upgrade to add more users.',
      fr: 'Le plan a atteint sa limite de participants. Veuillez passer à un forfait supérieur pour ajouter plus de membres.',
      es: 'El plan ha alcanzado su límite de participantes. Por favor, actualice su plan para agregar más usuarios.',
      ru: 'План достиг лимита пользователей. Пожалуйста, обновите план, чтобы добавить больше пользователей.',
      ja: 'プランのユーザー制限に達しました。ユーザーを追加するにはアップグレードしてください।',
      ko: '요금제의 사용자 제한에 도달했습니다. 더 많은 사용자를 추가하려면 업그레이드하십시오.',
      zh: '该计划已达到用户限制। 请升级以添加更多用户।',
      de: 'Der Plan hat sein Nutzerlimit erreicht. Bitte führen Sie ein Upgrade durch, um weitere Nutzer hinzuzufügen.',
      ar: 'وصلت الخطة إلى الحد الأقصى للمستخدمين. يرجى الترقية لإضافة المزيد من المستخدمين.',
      it: 'Il piano ha raggiunto il limite di utenti. Effettua l’upgrade per aggiungere altri utenti.',
      pt: 'O plano atingiu o limite de usuários. Por favor, faça um upgrade para adicionar mais usuários.',
      hi: 'योजना अपने उपयोगकर्ता सीमा तक पहुँच गई है। कृपया अधिक उपयोगकर्ताओं को जोड़ने के लिए अपग्रेड करें।',
      tr: 'Plan kullanıcı sınırına ulaştı. Daha fazla kullanıcı eklemek için lütfen yükseltin.',
      pl: 'Plan osiągnął limit użytkowników. Zaktualizuj plan, aby dodać więcej użytkowników.',
      id: 'Paket telah mencapai batas pengguna. Harap tingkatkan untuk menambah lebih banyak pengguna.',
      vi: 'Gói đã đạt đến giới hạn người dùng. Vui lòng nâng cấp để thêm nhiều người dùng hơn.',
      uk: 'План досяг ліміту користувачів. Будь ласка, оновіть план, щоб додати більше користувачів.',
    },
    statusCode: HttpStatusCodes.UNAUTHORIZED_401,
  },
  PLAN_PROJECT_LIMIT_REACHED: {
    title: {
      en: 'Plan Project Limit Reached',
      'en-GB': 'Plan Project Limit Reached',
      fr: 'Limite de projets atteinte',
      es: 'Límite de proyectos alcanzado',
      ru: 'Достигнут лимит проектов плана',
      ja: 'プランのプロジェクト制限に達しました',
      ko: '요금제 프로젝트 제한에 도달했습니다',
      zh: '已达到计划项目限制',
      de: 'Projektlimit des Plans erreicht',
      ar: 'تم الوصول إلى الحد الأقصى لمشاريع الخطة',
      it: 'Limite progetti del piano raggiunto',
      pt: 'Limite de projetos do plano atingido',
      hi: 'योजना परियोजना सीमा समाप्त हो गई है',
      tr: 'Plan proje sınırına ulaşıldı',
      pl: 'Osiągnięto limit projektów planu',
      id: 'Batas Proyek Paket Tercapai',
      vi: 'Đã đạt giới hạn dự án của gói',
      uk: 'Досягнуто ліміту проектів плану',
    },
    message: {
      en: 'The plan has reached its project limit. Please upgrade to add more projects.',
      'en-GB':
        'The plan has reached its project limit. Please upgrade to add more projects.',
      fr: 'Le plan a atteint sa limite de projets. Veuillez passer à un forfait supérieur pour ajouter plus de projets.',
      es: 'El plan ha alcanzado su límite de proyectos. Por favor, actualice su plan para agregar más proyectos.',
      ru: 'План достиг лимита проектов. Пожалуйста, обновите план, чтобы добавить больше проектов.',
      ja: 'プランのプロジェクト制限に達しました。プロジェクトを追加するにはアップグレードしてください।',
      ko: '요금제의 프로젝트 제한에 도달했습니다. 더 많은 프로젝트를 추가하려면 업그레이드하십시오.',
      zh: '该计划已达到项目限制। 请升级以添加更多项目।',
      de: 'Der Plan hat sein Projektlimit erreicht. Bitte führen Sie ein Upgrade durch, um weitere Projekte hinzuzufügen.',
      ar: 'وصلت الخطة إلى الحد الأقصى للمشاريع. يرجى الترقية لإضافة المزيد من المشاريع.',
      it: 'Il piano ha raggiunto il limite di progetti. Effettua l’upgrade per aggiungere altri progetti.',
      pt: 'O plano atingiu o limite de projetos. Por favor, faça um upgrade para adicionar mais projetos.',
      hi: 'योजना अपने परियोजना सीमा तक पहुँच गई है। कृपया अधिक परियोजनाओं को जोड़ने के लिए अपग्रेड करें।',
      tr: 'Plan proje sınırına ulaştı. Daha fazla proje eklemek için lütfen yükseltin.',
      pl: 'Plan osiągnął limit projektów. Zaktualizuj plan, aby dodać więcej projektów.',
      id: 'Paket telah mencapai batas proyek. Harap tingkatkan untuk menambah lebih banyak proyek.',
      vi: 'Gói đã đạt đến giới hạn dự án. Vui lòng nâng cấp để thêm nhiều dự án hơn.',
      uk: 'План досяг ліміту проектів. Будь ласка, оновіть план, щоб додати більше проектів.',
    },
    statusCode: HttpStatusCodes.UNAUTHORIZED_401,
  },

  SUBSCRIPTION_CREATION_FAILED: {
    title: {
      en: 'Subscription Creation Failed',
      'en-GB': 'Subscription Creation Failed',
      fr: 'Échec de la création de la souscription',
      es: 'Error al crear la suscripción',
      ru: 'Ошибка создания подписки',
      ja: 'サブスクリプションの作成に失敗しました',
      ko: '구독 생성 실패',
      zh: '订阅创建失败',
      de: 'Abonnementerstellung fehlgeschlagen',
      ar: 'فشل إنشاء الاشتراك',
      it: 'Creazione abbonamento fallita',
      pt: 'Falha na criação da assinatura',
      hi: 'सदस्यता निर्माण विफल रहा',
      tr: 'Abonelik oluşturma başarısız',
      pl: 'Tworzenie subskrypcji nie powiodło się',
      id: 'Pembuatan Langganan Gagal',
      vi: 'Tạo gói đăng ký thất bại',
      uk: 'Помилка створення підписки',
    },
    message: {
      en: 'Failed to create the specified subscription.',
      'en-GB': 'Failed to create the specified subscription.',
      fr: 'La création de la souscription a échoué.',
      es: 'No se pudo crear la suscripción especificada.',
      ru: 'Не удалось создать указанную подписку.',
      ja: '指定されたサブスクリプションの作成に失敗しました。',
      ko: '지정된 구독을 생성하지 못했습니다.',
      zh: '无法创建指定的订阅。',
      de: 'Das angegebene Abonnement konnte nicht erstellt werden.',
      ar: 'فشل في إنشاء الاشتراك المحدد.',
      it: 'Impossibile creare l’abbonamento specificato.',
      pt: 'Falha ao criar a assinatura especificada.',
      hi: 'निर्दिष्ट सदस्यता बनाने में विफल।',
      tr: 'Belirtilen abonelik oluşturulamadı.',
      pl: 'Nie udało się utworzyć określonej subskrypcji.',
      id: 'Gagal membuat langganan yang ditentukan.',
      vi: 'Không thể tạo gói đăng ký đã chỉ định.',
      uk: 'Не вдалося створити вказану підписку.',
    },
    statusCode: HttpStatusCodes.INTERNAL_SERVER_ERROR_500,
  },

  CALLBACK_URL_NOT_VALID: {
    title: {
      en: 'Callback URL not valid',
      'en-GB': 'Callback URL not valid',
      fr: 'URL de rappel non valide',
      es: 'URL de devolución no válida',
      ru: 'Недопустимый URL обратного вызова',
      ja: 'コールバックURLが無効です',
      ko: '콜백 URL이 유효하지 않습니다',
      zh: '回调 URL 无效',
      de: 'Callback-URL ungültig',
      ar: 'عنوان URL لرد الاتصال غير صالح',
      it: 'URL di callback non valido',
      pt: 'URL de retorno inválida',
      hi: 'कॉलबैक URL मान्य नहीं है',
      tr: 'Geri arama URL’si geçerli değil',
      pl: 'Nieprawidłowy adres URL wywołania zwrotnego',
      id: 'URL Callback Tidak Valid',
      vi: 'URL gọi lại không hợp lệ',
      uk: 'Неприпустимий URL зворотного виклику',
    },
    message: {
      en: 'The callback URL is not valid.',
      'en-GB': 'The callback URL is not valid.',
      fr: 'L’URL de rappel n’est pas valide.',
      es: 'La URL de devolución no es válida.',
      ru: 'URL обратного вызова недопустим.',
      ja: 'コールバックURLが無効です。',
      ko: '콜백 URL이 유효하지 않습니다.',
      zh: '回调 URL 无效。',
      de: 'Die Callback-URL ist ungültig.',
      ar: 'عنوان URL لرد الاتصال غير صالح.',
      it: 'L’URL di callback non è valido.',
      pt: 'A URL de retorno não é válida.',
      hi: 'कॉलबैक URL मान्य नहीं है।',
      tr: 'Geri arama URL’si geçerli değil.',
      pl: 'Adres URL wywołania zwrotnego jest nieprawidłowy.',
      id: 'URL callback tidak valid.',
      vi: 'URL gọi lại không hợp lệ.',
      uk: 'URL зворотного виклику неприпустимий.',
    },
    statusCode: HttpStatusCodes.BAD_REQUEST_400,
  },
  STRIPE_SUBSCRIPTION_NO_CUSTOMER: {
    title: {
      en: 'No customer found',
      'en-GB': 'No customer found',
      fr: 'Aucun client trouvé',
      es: 'No se encontró el cliente',
      ru: 'Клиент не найден',
      ja: '顧客が見つかりません',
      ko: '고객을 찾을 수 없습니다',
      zh: '未找到客户',
      de: 'Kein Kunde gefunden',
      ar: 'لم يتم العثور على عميل',
      it: 'Nessun cliente trovato',
      pt: 'Nenhum cliente encontrado',
      hi: 'कोई ग्राहक नहीं मिला',
      tr: 'Müşteri bulunamadı',
      pl: 'Nie znaleziono klienta',
      id: 'Tidak Ada Pelanggan Ditemukan',
      vi: 'Không tìm thấy khách hàng',
      uk: 'Клієнта не знайдено',
    },
    message: {
      en: 'No customer found for the provided subscription.',
      'en-GB': 'No customer found for the provided subscription.',
      fr: "Aucun client n'a été trouvé pour l'abonnement fourni.",
      es: 'No se encontró ningún cliente para la suscripción proporcionada.',
      ru: 'Для предоставленной подписки клиент не найден.',
      ja: '提供されたサブスクリプションに対して顧客が見つかりませんでした。',
      ko: '제공된 구독에 대해 고객을 찾을 수 없습니다.',
      zh: '根据提供的订阅未找到客户。',
      de: 'Für das bereitgestellte Abonnement wurde kein Kunde gefunden.',
      ar: 'لم يتم العثور على عميل للاشتراك المقدم.',
      it: 'Nessun cliente trovato per l’abbonamento fornito.',
      pt: 'Nenhum cliente encontrado para a assinatura fornecida.',
      hi: 'प्रदान की गई सदस्यता के लिए कोई ग्राहक नहीं मिला।',
      tr: 'Sağlanan abonelik için müşteri bulunamadı.',
      pl: 'Nie znaleziono klienta dla podanej subskrypcji.',
      id: 'Tidak ada pelanggan ditemukan untuk langganan yang diberikan.',
      vi: 'Không tìm thấy khách hàng cho gói đăng ký được cung cấp.',
      uk: 'Для наданої підписки клієнта не знайдено.',
    },
    statusCode: HttpStatusCodes.INTERNAL_SERVER_ERROR_500,
  },
  NO_SUBSCRIPTION_ID_PROVIDED: {
    title: {
      en: 'No subscription ID provided',
      'en-GB': 'No subscription ID provided',
      fr: "Aucun ID d'abonnement fourni",
      es: 'No se proporcionó ningún ID de suscripción',
      ru: 'ID подписки не предоставлен',
      ja: 'サブスクリプションIDが提供されていません',
      ko: '구독 ID가 제공되지 않았습니다',
      zh: '未提供订阅 ID',
      de: 'Keine Abonnements-ID angegeben',
      ar: 'لم يتم توفير معرف الاشتراك',
      it: 'Nessun ID abbonamento fornito',
      pt: 'Nenhum ID de assinatura fornecido',
      hi: 'कोई सदस्यता आईडी प्रदान नहीं की गई',
      tr: 'Abonelik ID sağlanmadı',
      pl: 'Nie podano identyfikatora subskrypcji',
      id: 'ID Langganan Tidak Disediakan',
      vi: 'Không có mã định danh đăng ký nào được cung cấp',
      uk: 'ID підписки не надано',
    },
    message: {
      en: 'No subscription ID provided.',
      'en-GB': 'No subscription ID provided.',
      fr: "Aucun ID d'abonnement n'a été fourni.",
      es: 'No se proporcionó ningún ID de suscripción.',
      ru: 'ID подписки не был предоставлен.',
      ja: 'サブスクリプションIDが提供されませんでした。',
      ko: '구독 ID가 제공되지 않았습니다.',
      zh: '未提供订阅 ID。',
      de: 'Es wurde keine Abonnements-ID angegeben.',
      ar: 'لم يتم توفير معرف الاشتراك.',
      it: 'Nessun ID abbonamento fornito.',
      pt: 'Nenhum ID de assinatura foi fornecido.',
      hi: 'कोई सदस्यता आईडी प्रदान नहीं की गई।',
      tr: 'Abonelik ID sağlanmadı.',
      pl: 'Nie podano identyfikatora subskrypcji.',
      id: 'ID langganan tidak disediakan.',
      vi: 'Không có mã định danh đăng ký nào được cung cấp.',
      uk: 'ID підписки не було надано.',
    },
    statusCode: HttpStatusCodes.BAD_REQUEST_400,
  },
  CANNOT_CANCEL_SUBSCRIPTION: {
    title: {
      en: 'Cannot cancel subscription',
      'en-GB': 'Cannot cancel subscription',
      fr: "Impossible d'annuler l'abonnement",
      es: 'No se puede cancelar la suscripción',
      ru: 'Не удается отменить подписку',
      ja: 'サブスクリプションをキャンセルできません',
      ko: '구독을 취소할 수 없습니다',
      zh: '无法取消订阅',
      de: 'Abonnement kann nicht gekündigt werden',
      ar: 'لا يمكن إلغاء الاشتراك',
      it: 'Impossibile annullare l’abbonamento',
      pt: 'Não é possível cancelar a assinatura',
      hi: 'सदस्यता रद्द नहीं की जा सकती',
      tr: 'Abonelik iptal edilemiyor',
      pl: 'Nie można anulować subskrypcji',
      id: 'Tidak Dapat Membatalkan Langganan',
      vi: 'Không thể hủy gói đăng ký',
      uk: 'Не вдається скасувати підписку',
    },
    message: {
      en: 'Cannot cancel subscription.',
      'en-GB': 'Cannot cancel subscription.',
      fr: "Impossible d'annuler l'abonnement.",
      es: 'No se puede cancelar la suscripción.',
      ru: 'Не удается отменить подписку.',
      ja: 'サブスクリプションをキャンセルできません。',
      ko: '구독을 취소할 수 없습니다.',
      zh: '无法取消订阅。',
      de: 'Abonnement kann nicht gekündigt werden.',
      ar: 'لا يمكن إلغاء الاشتراك.',
      it: 'Impossibile annullare l’abbonamento.',
      pt: 'Não é possível cancelar a assinatura.',
      hi: 'सदस्यता रद्द नहीं की जा सकती।',
      tr: 'Abonelik iptal edilemiyor.',
      pl: 'Nie można anulować subskrypcji.',
      id: 'Tidak dapat membatalkan langganan.',
      vi: 'Không thể hủy gói đăng ký.',
      uk: 'Не вдається скасувати підписку.',
    },
    statusCode: HttpStatusCodes.INTERNAL_SERVER_ERROR_500,
  },
  ALREADY_SUBSCRIBED: {
    title: {
      en: 'Already Subscribed',
      'en-GB': 'Already Subscribed',
      fr: 'Déjà abonné',
      es: 'Ya suscrito',
      ru: 'Уже подписан',
      ja: 'すでに購読しています',
      ko: '이미 구독 중입니다',
      zh: '已订阅',
      de: 'Bereits abonniert',
      ar: 'مشترك بالفعل',
      it: 'Già abbonato',
      pt: 'Já é assinante',
      hi: 'पहले से ही सब्सक्राइब किया हुआ है',
      tr: 'Zaten abone olundu',
      pl: 'Już subskrybujesz',
      id: 'Sudah Berlangganan',
      vi: 'Đã đăng ký',
      uk: 'Вже підписаний',
    },
    message: {
      en: 'You are already subscribed to this plan.',
      'en-GB': 'You are already subscribed to this plan.',
      fr: 'Vous êtes déjà abonné à ce plan.',
      es: 'Ya estás suscrito a este plan.',
      ru: 'Вы уже подписаны на этот план.',
      ja: 'すでにこのプランを購読しています。',
      ko: '이미 이 요금제를 구독 중입니다.',
      zh: '您已经订阅了此计划。',
      de: 'Sie haben diesen Plan bereits abonniert.',
      ar: 'أنت مشترك بالفعل في هذه الخطة.',
      it: 'Sei già abbonato a questo piano.',
      pt: 'Você já está inscrito neste plano.',
      hi: 'आप पहले से ही इस योजना की सदस्यता ले चुके हैं।',
      tr: 'Bu plana zaten abonesiniz.',
      pl: 'Już subskrybujesz ten plan.',
      id: 'Anda sudah berlangganan paket ini.',
      vi: 'Bạn đã đăng ký gói này rồi.',
      uk: 'Ви вже підписані на цей план.',
    },
    statusCode: HttpStatusCodes.BAD_REQUEST_400,
  },
  SESSION_CREATION_FAILED: {
    title: {
      en: 'Session Creation Failed',
      'en-GB': 'Session Creation Failed',
      fr: 'Échec de la création de la session',
      es: 'Error al crear la sesión',
      ru: 'Ошибка создания сессии',
      ja: 'セッションの作成に失敗しました',
      ko: '세션 생성 실패',
      zh: '会话创建失败',
      de: 'Sitzungserstellung fehlgeschlagen',
      ar: 'فشل إنشاء الجلسة',
      it: 'Creazione sessione fallita',
      pt: 'Falha na criação da sessão',
      hi: 'सत्र निर्माण विफल रहा',
      tr: 'Oturum oluşturma başarısız',
      pl: 'Tworzenie sesji nie powiodło się',
      id: 'Pembuatan Sesi Gagal',
      vi: 'Tạo phiên thất bại',
      uk: 'Помилка створення сесії',
    },
    message: {
      en: 'Failed to create the specified session.',
      'en-GB': 'Failed to create the specified session.',
      fr: 'La création de la session a échoué.',
      es: 'No se pudo crear la sesión especificada.',
      ru: 'Не удалось создать указанную сессию.',
      ja: '指定されたセッションの作成に失敗しました。',
      ko: '지정된 세션을 생성하지 못했습니다.',
      zh: '无法创建指定的会话。',
      de: 'Die angegebene Sitzung konnte nicht erstellt werden.',
      ar: 'فشل في إنشاء الجلسة المحددة.',
      it: 'Impossibile creare la sessione specificata.',
      pt: 'Falha ao criar a sessão especificada.',
      hi: 'निर्दिष्ट सत्र बनाने में विफल।',
      tr: 'Belirtilen oturum oluşturulamadı.',
      pl: 'Nie udało się utworzyć określonej sesji.',
      id: 'Gagal membuat sesi yang ditentukan.',
      vi: 'Không thể tạo phiên đã chỉ định.',
      uk: 'Не вдалося створити вказану сесію.',
    },
    statusCode: HttpStatusCodes.INTERNAL_SERVER_ERROR_500,
  },
  SETUP_INTENT_CREATION_FAILED: {
    title: {
      en: 'Setup Intent Creation Failed',
      'en-GB': 'Setup Intent Creation Failed',
      fr: "Échec de la création de l'intention de configuration",
      es: 'Error al crear la intención de configuración',
      ru: 'Ошибка создания намерения настройки',
      ja: 'セットアップインテントの作成に失敗しました',
      ko: '설정 의도 생성 실패',
      zh: '设置意图创建失败',
      de: 'Setup-Intent-Erstellung fehlgeschlagen',
      ar: 'فشل إنشاء نية الإعداد',
      it: 'Creazione Setup Intent fallita',
      pt: 'Falha na creazione del Setup Intent',
      hi: 'सेटअप इंटेंट निर्माण विफल रहा',
      tr: 'Kurulum amacı oluşturma başarısız',
      pl: 'Tworzenie zamiaru konfiguracji nie powiodło się',
      id: 'Pembuatan Setup Intent Gagal',
      vi: 'Tạo ý định thiết lập thất bại',
      uk: 'Помилка створення наміру налаштування',
    },
    message: {
      en: 'Failed to create the setup intent.',
      'en-GB': 'Failed to create the setup intent.',
      fr: "Échec de la création de l'intention de configuration.",
      es: 'Error al crear la intención de configuración.',
      ru: 'Не удалось создать намерение настройки.',
      ja: 'セットアップインテントの作成に失敗しました。',
      ko: '설정 의도를 생성하지 못했습니다.',
      zh: '无法创建设置意图。',
      de: 'Der Setup-Intent konnte nicht erstellt werden.',
      ar: 'فشل في إنشاء نية الإعداد.',
      it: 'Impossibile creare il setup intent.',
      pt: 'Falha ao criar o setup intent.',
      hi: 'सेटअप इंटेंट बनाने में विफल।',
      tr: 'Kurulum amacı oluşturulamadı.',
      pl: 'Nie udało się utworzyć zamiaru konfiguracji.',
      id: 'Gagal membuat setup intent.',
      vi: 'Không thể tạo ý định thiết lập.',
      uk: 'Не вдалося створити намір налаштування.',
    },
    statusCode: HttpStatusCodes.INTERNAL_SERVER_ERROR_500,
  },
} satisfies Record<string, ErrorCode>;
