import { HttpStatusCodes } from '@utils/httpStatusCodes';
import type { ErrorCode } from './errorCodes.types';

/**
 * Git-related error codes.
 */
export const gitErrors = {
  GITHUB_FETCH_USER_DATA_FAILED: {
    title: {
      en: 'GitHub Fetch User Data Failed',
      'en-GB': 'GitHub Fetch User Data Failed',
      fr: 'Échec de la récupération des données utilisateur de GitHub',
      es: 'Error al obtener datos del usuario de GitHub',
      ru: 'Ошибка получения данных пользователя GitHub',
      ja: 'GitHubユーザーデータの取得に失敗しました',
      ko: 'GitHub 사용자 데이터 가져오기 실패',
      zh: '从 GitHub 获取用户数据失败',
      de: 'GitHub-Benutzerdaten konnten nicht abgerufen werden',
      ar: 'فشل جلب بيانات المستخدم من GitHub',
      it: 'Recupero dati utente da GitHub fallito',
      pt: 'Falha ao buscar dados do usuário no GitHub',
      hi: 'GitHub से उपयोगकर्ता डेटा प्राप्त करने में विफल',
      tr: 'GitHub kullanıcı verileri alınamadı',
      pl: 'Nie udało się pobrać danych użytkownika z GitHub',
      id: 'Gagal Mengambil Data Pengguna GitHub',
      vi: 'Lấy dữ liệu người dùng từ GitHub thất bại',
      uk: 'Помилка отримання даних користувача GitHub',
    },
    message: {
      en: 'Failed to fetch user data from GitHub.',
      'en-GB': 'Failed to fetch user data from GitHub.',
      fr: 'Échec de la récupération des données utilisateur de GitHub.',
      es: 'Error al obtener datos del usuario de GitHub.',
      ru: 'Не удалось получить данные пользователя из GitHub.',
      ja: 'GitHubからユーザーデータを取得できませんでした。',
      ko: 'GitHub에서 사용자 데이터를 가져오지 못했습니다.',
      zh: '从 GitHub 获取用户数据失败。',
      de: 'Benutzerdaten konnten nicht von GitHub abgerufen werden.',
      ar: 'فشل في جلب بيانات المستخدم من GitHub.',
      it: 'Impossibile recuperare i dati dell’utente da GitHub.',
      pt: 'Falha ao buscar dados do usuário no GitHub.',
      hi: 'GitHub से उपयोगकर्ता डेटा प्राप्त करने में विफल।',
      tr: 'GitHub’dan kullanıcı verileri alınamadı.',
      pl: 'Nie udało się pobrać danych użytkownika z GitHub.',
      id: 'Gagal mengambil data pengguna dari GitHub.',
      vi: 'Không thể lấy dữ liệu người dùng từ GitHub.',
      uk: 'Не вдалося отримати дані користувача з GitHub.',
    },
    statusCode: HttpStatusCodes.INTERNAL_SERVER_ERROR_500,
  },
  GIT_HUB_FETCH_USER_EMAIL_FAILED: {
    title: {
      en: 'GitHub Fetch User Email Failed',
      'en-GB': 'GitHub Fetch User Email Failed',
      fr: "Échec de la récupération de l'email utilisateur de GitHub",
      es: 'Error al obtener el correo electrónico del usuario de GitHub',
      ru: 'Ошибка получения email пользователя GitHub',
      ja: 'GitHubユーザーのメールアドレスの取得に失敗しました',
      ko: 'GitHub 사용자 이메일 가져오기 실패',
      zh: '从 GitHub 获取用户电子邮件失败',
      de: 'GitHub-Benutzer-E-Mail konnte nicht abgerufen werden',
      ar: 'فشل جلب بريد المستخدم الإلكتروني من GitHub',
      it: 'Recupero email utente da GitHub fallito',
      pt: 'Falha ao buscar e-mail do usuário no GitHub',
      hi: 'GitHub से उपयोगकर्ता ईमेल प्राप्त करने में विफल',
      tr: 'GitHub kullanıcı e-postası alınamadı',
      pl: 'Nie udało się pobrać adresu e-mail użytkownika z GitHub',
      id: 'Gagal Mengambil Email Pengguna GitHub',
      vi: 'Lấy email người dùng từ GitHub thất bại',
      uk: 'Помилка отримання email користувача GitHub',
    },
    message: {
      en: 'Failed to fetch user email from GitHub.',
      'en-GB': 'Failed to fetch user email from GitHub.',
      fr: "Échec de la récupération de l'email utilisateur de GitHub.",
      es: 'Error al obtener el correo electrónico del usuario de GitHub.',
      ru: 'Не удалось получить email пользователя из GitHub.',
      ja: 'GitHubからユーザーのメールアドレスを取得できませんでした。',
      ko: 'GitHub에서 사용자 이메일을 가져오지 못했습니다.',
      zh: '从 GitHub 获取用户电子邮件失败。',
      de: 'Benutzer-E-Mail konnte nicht von GitHub abgerufen werden.',
      ar: 'فشل في جلب بريد المستخدم الإلكتروني من GitHub.',
      it: 'Impossibile recuperare l’email dell’utente da GitHub.',
      pt: 'Falha ao buscar e-mail do usuário no GitHub.',
      hi: 'GitHub से उपयोगकर्ता ईमेल प्राप्त करने में विफल।',
      tr: 'GitHub’dan kullanıcı e-postası alınamadı.',
      pl: 'Nie udało się pobrać adresu e-mail użytkownika z GitHub.',
      id: 'Gagal mengambil email pengguna dari GitHub.',
      vi: 'Không thể lấy email người dùng từ GitHub.',
      uk: 'Не вдалося отримати email користувача з GitHub.',
    },
    statusCode: HttpStatusCodes.INTERNAL_SERVER_ERROR_500,
  },
  GITHUB_CODE_MISSING: {
    title: {
      en: 'GitHub Code Missing',
      'en-GB': 'GitHub Code Missing',
      fr: 'Code GitHub manquant',
      es: 'Código GitHub no encontrado',
      ru: 'Код GitHub отсутствует',
      ja: 'GitHubコードが見つかりません',
      ko: 'GitHub 코드가 누락되었습니다',
      zh: 'GitHub 代码丢失',
      de: 'GitHub-Code fehlt',
      ar: 'رمز GitHub مفقود',
      it: 'Codice GitHub mancante',
      pt: 'Código GitHub ausente',
      hi: 'GitHub कोड अनुपलब्ध है',
      tr: 'GitHub kodu eksik',
      pl: 'Brak kodu GitHub',
      id: 'Kode GitHub Hilang',
      vi: 'Thiếu mã GitHub',
      uk: 'Код GitHub відсутній',
    },
    message: {
      en: 'The GitHub code is missing.',
      'en-GB': 'The GitHub code is missing.',
      fr: 'Le code GitHub est manquant.',
      es: 'El código GitHub no se ha encontrado.',
      ru: 'Код GitHub отсутствует.',
      ja: 'GitHubコードが見つかりませんでした。',
      ko: 'GitHub 코드가 누락되었습니다.',
      zh: 'GitHub 代码丢失。',
      de: 'Der GitHub-Code fehlt.',
      ar: 'رمز GitHub مفقود.',
      it: 'Il codice GitHub è mancante.',
      pt: 'O código GitHub está ausente.',
      hi: 'GitHub कोड अनुपलब्ध है।',
      tr: 'GitHub kodu eksik.',
      pl: 'Brak kodu GitHub.',
      id: 'Kode GitHub hilang.',
      vi: 'Mã GitHub bị thiếu.',
      uk: 'Код GitHub відсутній.',
    },
    statusCode: HttpStatusCodes.BAD_REQUEST_400,
  },
  GITHUB_TOKEN_MISSING: {
    title: {
      en: 'GitHub Token Missing',
      'en-GB': 'GitHub Token Missing',
      fr: 'Jeton GitHub manquant',
      es: 'Token GitHub no encontrado',
      ru: 'Токен GitHub отсутствует',
      ja: 'GitHubトークンが見つかりません',
      ko: 'GitHub 토큰이 누락되었습니다',
      zh: 'GitHub 令牌丢失',
      de: 'GitHub-Token fehlt',
      ar: 'رمز GitHub (Token) مفقود',
      it: 'Token GitHub mancante',
      pt: 'Token GitHub ausente',
      hi: 'GitHub टोकन अनुपलब्ध है',
      tr: 'GitHub belirteci eksik',
      pl: 'Brak tokena GitHub',
      id: 'Token GitHub Hilang',
      vi: 'Thiếu mã thông báo GitHub',
      uk: 'Токен GitHub відсутній',
    },
    message: {
      en: 'The GitHub token is missing.',
      'en-GB': 'The GitHub token is missing.',
      fr: 'Le jeton GitHub est manquant.',
      es: 'El token GitHub no se ha encontrado.',
      ru: 'Токен GitHub отсутствует.',
      ja: 'GitHubトークンが見つかりませんでした。',
      ko: 'GitHub 토큰이 누락되었습니다.',
      zh: 'GitHub 令牌丢失。',
      de: 'Der GitHub-Token fehlt.',
      ar: 'رمز GitHub (Token) مفقود.',
      it: 'Il token GitHub è mancante.',
      pt: 'O token GitHub está ausente.',
      hi: 'GitHub टोकन अनुपलब्ध है।',
      tr: 'GitHub belirteci eksik.',
      pl: 'Brak tokena GitHub.',
      id: 'Token GitHub hilang.',
      vi: 'Mã thông báo GitHub bị thiếu.',
      uk: 'Токен GitHub відсутній.',
    },
    statusCode: HttpStatusCodes.BAD_REQUEST_400,
  },
  GITHUB_CHECK_CONFIG_MISSING_PARAMS: {
    title: {
      en: 'GitHub Check Config Missing Params',
      'en-GB': 'GitHub Check Config Missing Params',
      fr: 'Paramètres de configuration GitHub Check manquants',
      es: 'Parámetros de configuración de GitHub Check no encontrados',
      ru: 'Отсутствуют параметры конфигурации проверки GitHub',
      ja: 'GitHubチェック構成のパラメータが見つかりません',
      ko: 'GitHub 확인 구성 매개변수가 누락되었습니다',
      zh: 'GitHub 检查配置缺少参数',
      de: 'GitHub Check Config Fehlende Parameter',
      ar: 'معلمات تكوين فحص GitHub مفقودة',
      it: 'Parametri configurazione GitHub Check mancanti',
      pt: 'Parâmetros de configuração do GitHub Check ausentes',
      hi: 'GitHub चेक कॉन्फ़िग पैरामीटर अनुपलब्ध हैं',
      tr: 'GitHub kontrol yapılandırması eksik parametreler',
      pl: 'Brak parametrów konfiguracji sprawdzania GitHub',
      id: 'Parameter Konfigurasi Pemeriksaan GitHub Hilang',
      vi: 'Thiếu tham số cấu hình kiểm tra GitHub',
      uk: 'Відсутні параметри конфігурації перевірки GitHub',
    },
    message: {
      en: 'The GitHub check config is missing params.',
      'en-GB': 'The GitHub check config is missing params.',
      fr: 'Les paramètres de configuration GitHub Check sont manquants.',
      es: 'Faltan parámetros en la configuración de GitHub Check.',
      ru: 'В конфигурации проверки GitHub отсутствуют параметры.',
      ja: 'GitHubチェック構成にパラメータがありません。',
      ko: 'GitHub 확인 구성에 매개변수가 누락되었습니다.',
      zh: 'GitHub 检查配置缺少参数。',
      de: 'In der GitHub-Check-Konfiguration fehlen Parameter.',
      ar: 'تكوين فحص GitHub يفتقد إلى المعلمات.',
      it: 'La configurazione di controllo GitHub manca di parametri.',
      pt: 'A configuração de verificação do GitHub está sem parâmetros.',
      hi: 'GitHub चेक कॉन्फ़िग में पैरामीटर अनुपलब्ध हैं।',
      tr: 'GitHub kontrol yapılandırmasında parametreler eksik.',
      pl: 'W konfiguracji sprawdzania GitHub brakuje parametrów.',
      id: 'Konfigurasi pemeriksaan GitHub kekurangan parameter.',
      vi: 'Cấu hình kiểm tra GitHub bị thiếu tham số.',
      uk: 'У конфігурації перевірки GitHub відсутні параметри.',
    },
    statusCode: HttpStatusCodes.BAD_REQUEST_400,
  },
  GITHUB_REDIRECT_URI_MISSING: {
    title: {
      en: 'GitHub Redirect URI Missing',
      'en-GB': 'GitHub Redirect URI Missing',
      fr: 'URI de redirection GitHub manquante',
      es: 'URI de redirección de GitHub no encontrada',
      ru: 'Отсутствует URI перенаправления GitHub',
      ja: 'GitHubリダイレクトURIが見つかりません',
      ko: 'GitHub 리디렉션 URI가 누락되었습니다',
      zh: 'GitHub 重定向 URI 丢失',
      de: 'GitHub-Redirect-URI fehlt',
      ar: 'عنوان URI لإعادة توجيه GitHub مفقود',
      it: 'URI di reindirizzamento GitHub mancante',
      pt: 'URI de redirecionamento do GitHub ausente',
      hi: 'GitHub रीडायरेक्ट URI अनुपलब्ध है',
      tr: 'GitHub yönlendirme URI’si eksik',
      pl: 'Brak identyfikatora URI przekierowania GitHub',
      id: 'URI Pengalihan GitHub Hilang',
      vi: 'Thiếu URI chuyển hướng GitHub',
      uk: 'Відсутній URI перенаправлення GitHub',
    },
    message: {
      en: 'The GitHub redirect URI is missing.',
      'en-GB': 'The GitHub redirect URI is missing.',
      fr: 'L’URI de redirection GitHub est manquante.',
      es: 'Falta la URI de redirección de GitHub.',
      ru: 'URI перенаправления GitHub отсутствует.',
      ja: 'GitHubリダイレクトURIが見つかりませんでした。',
      ko: 'GitHub 리디렉션 URI가 누락되었습니다.',
      zh: 'GitHub 重定向 URI 丢失。',
      de: 'Die GitHub-Redirect-URI fehlt.',
      ar: 'عنوان URI لإعادة توجيه GitHub مفقود.',
      it: 'L’URI di reindirizzamento GitHub è mancante.',
      pt: 'A URI de redirecionamento do GitHub está ausente.',
      hi: 'GitHub रीडायरेक्ट URI अनुपलब्ध है।',
      tr: 'GitHub yönlendirme URI’si eksik.',
      pl: 'Brakuje identyfikatora URI przekierowania GitHub.',
      id: 'URI pengalihan GitHub hilang.',
      vi: 'URI chuyển hướng GitHub bị thiếu.',
      uk: 'URI перенаправлення GitHub відсутній.',
    },
    statusCode: HttpStatusCodes.BAD_REQUEST_400,
  },
  GITHUB_GET_CONFIG_FILE_MISSING_PARAMS: {
    title: {
      en: 'GitHub Get Config File Missing Params',
      'en-GB': 'GitHub Get Config File Missing Params',
      fr: 'Paramètres GitHub Get Config File manquants',
      es: 'Parámetros de GitHub Get Config File no encontrados',
      ru: 'Отсутствуют параметры получения файла конфигурации GitHub',
      ja: 'GitHub構成ファイル取得のパラメータが見つかりません',
      ko: 'GitHub 구성 파일 가져오기 매개변수가 누락되었습니다',
      zh: 'GitHub 获取配置文件缺少参数',
      de: 'GitHub Get Config File Fehlende Parameter',
      ar: 'معلمات ملف الحصول على تكوين GitHub مفقودة',
      it: 'Parametri GitHub Get Config File mancanti',
      pt: 'Parâmetros do arquivo de configuração do GitHub ausentes',
      hi: 'GitHub कॉन्फ़िग फ़ाइल प्राप्त करने के पैरामीटर अनुपलब्ध हैं',
      tr: 'GitHub yapılandırma dosyası alma eksik parametreler',
      pl: 'Brak parametrów pobierania pliku konfiguracji GitHub',
      id: 'Parameter Ambil File Konfigurasi GitHub Hilang',
      vi: 'Thiếu tham số lấy tệp cấu hình GitHub',
      uk: 'Відсутні параметри отримання файлу конфігурації GitHub',
    },
    message: {
      en: 'The GitHub get config file is missing params.',
      'en-GB': 'The GitHub get config file is missing params.',
      fr: 'Les paramètres pour obtenir le fichier de configuration GitHub sont manquants.',
      es: 'Faltan parámetros para obtener el archivo de configuración de GitHub.',
      ru: 'В запросе на получение файла конфигурации GitHub отсутствуют параметры.',
      ja: 'GitHub構成ファイルの取得にパラメータがありません。',
      ko: 'GitHub 구성 파일을 가져오는 데 매개변수가 누락되었습니다.',
      zh: 'GitHub 获取配置文件缺少参数。',
      de: 'In der GitHub-Konfigurationsdatei fehlen Parameter.',
      ar: 'ملف الحصول على تكوين GitHub يفتقد إلى المعلمات.',
      it: 'La richiesta del file di configurazione GitHub manca di parametri.',
      pt: 'O arquivo de configuração do GitHub está sem parâmetros.',
      hi: 'GitHub कॉन्फ़िग फ़ाइल प्राप्त करने में पैरामीटर अनुपलब्ध हैं।',
      tr: 'GitHub yapılandırma dosyası alma işleminde parametreler eksik.',
      pl: 'W pobieraniu pliku konfiguracji GitHub brakuje parametrów.',
      id: 'Ambil file konfigurasi GitHub kekurangan parameter.',
      vi: 'Lấy tệp cấu hình GitHub bị thiếu tham số.',
      uk: 'У запиті на отримання файлу конфігурації GitHub відсутні параметри.',
    },
    statusCode: HttpStatusCodes.BAD_REQUEST_400,
  },
  GITHUB_CONFIG_FILE_NOT_FOUND: {
    title: {
      en: 'GitHub Config File Not Found',
      'en-GB': 'GitHub Config File Not Found',
      fr: 'Fichier de configuration GitHub non trouvé',
      es: 'Archivo de configuración de GitHub no encontrado',
      ru: 'Файл конфигурации GitHub не найден',
      ja: 'GitHub構成ファイルが見つかりません',
      ko: 'GitHub 구성 파일을 찾을 수 없습니다',
      zh: '未找到 GitHub 配置文件',
      de: 'GitHub-Konfigurationsdatei nicht gefunden',
      ar: 'ملف تكوين GitHub غير موجود',
      it: 'File di configurazione GitHub non trovato',
      pt: 'Arquivo de configuração do GitHub não encontrado',
      hi: 'GitHub कॉन्फ़िग फ़ाइल नहीं मिली',
      tr: 'GitHub yapılandırma dosyası bulunamadı',
      pl: 'Nie znaleziono pliku konfiguracji GitHub',
      id: 'File Konfigurasi GitHub Tidak Ditemukan',
      vi: 'Không tìm thấy tệp cấu hình GitHub',
      uk: 'Файл конфігурації GitHub не знайдено',
    },
    message: {
      en: 'The GitHub config file was not found.',
      'en-GB': 'The GitHub config file was not found.',
      fr: "Le fichier de configuration GitHub n'a pas été trouvé.",
      es: 'El archivo de configuración de GitHub no se ha encontrado.',
      ru: 'Файл конфигурации GitHub не был найден.',
      ja: 'GitHub構成ファイルが見つかりませんでした。',
      ko: 'GitHub 구성 파일을 찾을 수 없습니다.',
      zh: '未找到 GitHub 配置文件。',
      de: 'Die GitHub-Konfigurationsdatei wurde nicht gefunden.',
      ar: 'لم يتم العثور على ملف تكوين GitHub.',
      it: 'Il file di configurazione GitHub non è stato trovato.',
      pt: 'O arquivo de configuração do GitHub não foi encontrado.',
      hi: 'GitHub कॉन्फ़िग फ़ाइल नहीं मिली।',
      tr: 'GitHub yapılandırma dosyası bulunamadı.',
      pl: 'Plik konfiguracji GitHub nie został znaleziony.',
      id: 'File konfigurasi GitHub tidak ditemukan.',
      vi: 'Tệp cấu hình GitHub không được tìm thấy.',
      uk: 'Файл конфігурації GitHub не було знайдено.',
    },
    statusCode: HttpStatusCodes.NOT_FOUND_404,
  },
  BITBUCKET_REDIRECT_URI_MISSING: {
    title: {
      en: 'Bitbucket Redirect URI Missing',
      'en-GB': 'Bitbucket Redirect URI Missing',
      fr: 'URI de redirection Bitbucket manquante',
      es: 'URI de redirección de Bitbucket no encontrada',
      ru: 'Отсутствует URI перенаправления Bitbucket',
      ja: 'BitbucketリダイレクトURIが見つかりません',
      ko: 'Bitbucket 리디렉션 URI가 누락되었습니다',
      zh: 'Bitbucket 重定向 URI 丢失',
      de: 'Bitbucket-Redirect-URI fehlt',
      ar: 'عنوان URI لإعادة توجيه Bitbucket مفقود',
      it: 'URI di reindirizzamento Bitbucket mancante',
      pt: 'URI de redirecionamento do Bitbucket ausente',
      hi: 'Bitbucket रीडायरेक्ट URI अनुपलब्ध है',
      tr: 'Bitbucket yönlendirme URI’si eksik',
      pl: 'Brak identyfikatora URI przekierowania Bitbucket',
      id: 'URI Pengalihan Bitbucket Hilang',
      vi: 'Thiếu URI chuyển hướng Bitbucket',
      uk: 'Відсутній URI перенаправлення Bitbucket',
    },
    message: {
      en: 'The Bitbucket redirect URI is missing.',
      'en-GB': 'The Bitbucket redirect URI is missing.',
      fr: 'L’URI de redirection Bitbucket est manquante.',
      es: 'Falta la URI de redirección de Bitbucket.',
      ru: 'URI перенаправления Bitbucket отсутствует.',
      ja: 'BitbucketリダイレクトURIが見つかりませんでした。',
      ko: 'Bitbucket 리디렉션 URI가 누락되었습니다.',
      zh: 'Bitbucket 重定向 URI 丢失。',
      de: 'Die Bitbucket-Redirect-URI fehlt.',
      ar: 'عنوان URI لإعادة توجيه Bitbucket مفقود.',
      it: 'L’URI di reindirizzamento Bitbucket è mancante.',
      pt: 'A URI de redirecionamento do Bitbucket está ausente.',
      hi: 'Bitbucket रीडायरेक्ट URI अनुपलब्ध है।',
      tr: 'Bitbucket yönlendirme URI’si eksik.',
      pl: 'Brakuje identyfikatora URI przekierowania Bitbucket.',
      id: 'URI pengalihan Bitbucket hilang.',
      vi: 'URI chuyển hướng Bitbucket bị thiếu.',
      uk: 'URI перенаправлення Bitbucket відсутній.',
    },
    statusCode: HttpStatusCodes.BAD_REQUEST_400,
  },
  BITBUCKET_CODE_MISSING: {
    title: {
      en: 'Bitbucket Code Missing',
      'en-GB': 'Bitbucket Code Missing',
      fr: 'Code Bitbucket manquant',
      es: 'Código Bitbucket no encontrado',
      ru: 'Код Bitbucket отсутствует',
      ja: 'Bitbucketコードが見つかりません',
      ko: 'Bitbucket 코드가 누락되었습니다',
      zh: 'Bitbucket 代码丢失',
      de: 'Bitbucket-Code fehlt',
      ar: 'رمز Bitbucket مفقود',
      it: 'Codice Bitbucket mancante',
      pt: 'Código Bitbucket ausente',
      hi: 'Bitbucket कोड अनुपलब्ध है',
      tr: 'Bitbucket kodu eksik',
      pl: 'Brak kodu Bitbucket',
      id: 'Kode Bitbucket Hilang',
      vi: 'Thiếu mã Bitbucket',
      uk: 'Код Bitbucket відсутній',
    },
    message: {
      en: 'The Bitbucket code is missing.',
      'en-GB': 'The Bitbucket code is missing.',
      fr: 'Le code Bitbucket est manquant.',
      es: 'El código Bitbucket no se ha encontrado.',
      ru: 'Код Bitbucket отсутствует.',
      ja: 'Bitbucketコードが見つかりませんでした。',
      ko: 'Bitbucket 코드가 누락되었습니다.',
      zh: 'Bitbucket 代码丢失。',
      de: 'Der Bitbucket-Code fehlt.',
      ar: 'رمز Bitbucket مفقود.',
      it: 'Il codice Bitbucket è mancante.',
      pt: 'O código Bitbucket está ausente.',
      hi: 'Bitbucket कोड अनुपलब्ध है।',
      tr: 'Bitbucket kodu eksik.',
      pl: 'Brak kodu Bitbucket.',
      id: 'Kode Bitbucket hilang.',
      vi: 'Mã Bitbucket bị thiếu.',
      uk: 'Код Bitbucket відсутній.',
    },
    statusCode: HttpStatusCodes.BAD_REQUEST_400,
  },
  BITBUCKET_TOKEN_MISSING: {
    title: {
      en: 'Bitbucket Token Missing',
      'en-GB': 'Bitbucket Token Missing',
      fr: 'Jeton Bitbucket manquant',
      es: 'Token Bitbucket no encontrado',
      ru: 'Токен Bitbucket отсутствует',
      ja: 'Bitbucketトークンが見つかりません',
      ko: 'Bitbucket 토큰이 누락되었습니다',
      zh: 'Bitbucket 令牌丢失',
      de: 'Bitbucket-Token fehlt',
      ar: 'رمز Bitbucket (Token) مفقود',
      it: 'Token Bitbucket mancante',
      pt: 'Token Bitbucket ausente',
      hi: 'Bitbucket टोकन अनुपलब्ध है',
      tr: 'Bitbucket belirteci eksik',
      pl: 'Brak tokena Bitbucket',
      id: 'Token Bitbucket Hilang',
      vi: 'Thiếu mã thông báo Bitbucket',
      uk: 'Токен Bitbucket відсутній',
    },
    message: {
      en: 'The Bitbucket token is missing.',
      'en-GB': 'The Bitbucket token is missing.',
      fr: 'Le jeton Bitbucket est manquant.',
      es: 'El token Bitbucket no se ha encontrado.',
      ru: 'Токен Bitbucket отсутствует.',
      ja: 'Bitbucketトークンが見つかりませんでした।',
      ko: 'Bitbucket 토큰이 누락되었습니다.',
      zh: 'Bitbucket 令牌丢失。',
      de: 'Der Bitbucket-Token fehlt.',
      ar: 'رمز Bitbucket (Token) مفقود.',
      it: 'Il token Bitbucket è mancante.',
      pt: 'O token Bitbucket está ausente.',
      hi: 'Bitbucket टोकन अनुपलब्ध है।',
      tr: 'Bitbucket belirteci eksik.',
      pl: 'Brak tokena Bitbucket.',
      id: 'Token Bitbucket hilang.',
      vi: 'Mã thông báo Bitbucket bị thiếu.',
      uk: 'Токен Bitbucket відсутній.',
    },
    statusCode: HttpStatusCodes.BAD_REQUEST_400,
  },
  BITBUCKET_CHECK_CONFIG_MISSING_PARAMS: {
    title: {
      en: 'Bitbucket Check Config Missing Params',
      'en-GB': 'Bitbucket Check Config Missing Params',
      fr: 'Paramètres de configuration Bitbucket Check manquants',
      es: 'Parámetros de configuración de Bitbucket Check no encontrados',
      ru: 'Отсутствуют параметры конфигурации проверки Bitbucket',
      ja: 'Bitbucketチェック構成のパラメータが見つかりません',
      ko: 'Bitbucket 확인 구성 매개변수가 누락되었습니다',
      zh: 'Bitbucket 检查配置缺少参数',
      de: 'Bitbucket Check Config Fehlende Parameter',
      ar: 'معلمات تكوين فحص Bitbucket مفقودة',
      it: 'Parametri configurazione Bitbucket Check mancanti',
      pt: 'Parâmetros de configuração do Bitbucket Check ausentes',
      hi: 'Bitbucket चेक कॉन्फ़िग पैरामीटर अनुपलब्ध हैं',
      tr: 'Bitbucket kontrol yapılandırması eksik parametreler',
      pl: 'Brak parametrów konfiguracji sprawdzania Bitbucket',
      id: 'Parameter Konfigurasi Pemeriksaan Bitbucket Hilang',
      vi: 'Thiếu tham số cấu hình kiểm tra Bitbucket',
      uk: 'Відсутні параметри конфігурації перевірки Bitbucket',
    },
    message: {
      en: 'The Bitbucket check config is missing params.',
      'en-GB': 'The Bitbucket check config is missing params.',
      fr: 'Les paramètres de configuration Bitbucket Check sont manquants.',
      es: 'Faltan parámetros en la configuración de Bitbucket Check.',
      ru: 'В конфигурации проверки Bitbucket отсутствуют параметры.',
      ja: 'Bitbucketチェック構成にパラメータがありません。',
      ko: 'Bitbucket 확인 구성에 매개변수가 누락되었습니다.',
      zh: 'Bitbucket 检查配置缺少参数。',
      de: 'In der Bitbucket-Check-Konfiguration fehlen Parameter.',
      ar: 'تكوين فحص Bitbucket يفتقد إلى المعلمات.',
      it: 'La configurazione di controllo Bitbucket manca di parametri.',
      pt: 'A configuração de verificação do Bitbucket está sem parâmetros.',
      hi: 'Bitbucket चेक कॉन्फ़िग में पैरामीटर अनुपलब्ध हैं।',
      tr: 'Bitbucket kontrol yapılandırmasında parametreler eksik.',
      pl: 'W konfiguracji sprawdzania Bitbucket brakuje parametrów.',
      id: 'Konfigurasi pemeriksaan Bitbucket kekurangan parameter.',
      vi: 'Cấu hình kiểm tra Bitbucket bị thiếu tham số.',
      uk: 'У конфігурації перевірки Bitbucket відсутні параметри.',
    },
    statusCode: HttpStatusCodes.BAD_REQUEST_400,
  },
  BITBUCKET_GET_CONFIG_FILE_MISSING_PARAMS: {
    title: {
      en: 'Bitbucket Get Config File Missing Params',
      'en-GB': 'Bitbucket Get Config File Missing Params',
      fr: 'Paramètres Bitbucket Get Config File manquants',
      es: 'Parámetros de Bitbucket Get Config File no encontrados',
      ru: 'Отсутствуют параметры получения файла конфигурации Bitbucket',
      ja: 'Bitbucket構成ファイル取得のパラメータが見つかりません',
      ko: 'Bitbucket 구성 파일 가져오기 매개변수가 누락되었습니다',
      zh: 'Bitbucket 获取配置文件缺少参数',
      de: 'Bitbucket Get Config File Fehlende Parameter',
      ar: 'معلمات ملف الحصول على تكوين Bitbucket مفقودة',
      it: 'Parametri Bitbucket Get Config File mancanti',
      pt: 'Parâmetros do arquivo de configuração do Bitbucket ausentes',
      hi: 'Bitbucket कॉन्फ़िग फ़ाइल प्राप्त करने के पैरामीटर अनुपलब्ध हैं',
      tr: 'Bitbucket yapılandırma dosyası alma eksik parametreler',
      pl: 'Brak parametrów pobierania pliku konfiguracji Bitbucket',
      id: 'Parameter Ambil File Konfigurasi Bitbucket Hilang',
      vi: 'Thiếu tham số lấy tệp cấu hình Bitbucket',
      uk: 'Відсутні параметри отримання файлу конфігурації Bitbucket',
    },
    message: {
      en: 'The Bitbucket get config file is missing params.',
      'en-GB': 'The Bitbucket get config file is missing params.',
      fr: 'Les paramètres pour obtenir le fichier de configuration Bitbucket sont manquants.',
      es: 'Faltan parámetros para obtener el archivo de configuración de Bitbucket.',
      ru: 'В запросе на получение файла конфигурации Bitbucket отсутствуют параметры.',
      ja: 'Bitbucket構成ファイルの取得にパラメータがありません。',
      ko: 'Bitbucket 구성 파일을 가져오는 데 매개변수가 누락되었습니다.',
      zh: 'Bitbucket 获取配置文件缺少参数。',
      de: 'In der Bitbucket-Konfigurationsdatei fehlen Parameter.',
      ar: 'ملف الحصول على تكوين Bitbucket يفتقد إلى المعلمات.',
      it: 'La richiesta del file di configurazione Bitbucket manca di parametri.',
      pt: 'O arquivo de configuração do Bitbucket está sem parâmetros.',
      hi: 'Bitbucket कॉन्फ़िग फ़ाइल प्राप्त करने में पैरामीटर अनुपलब्ध हैं।',
      tr: 'Bitbucket yapılandırma dosyası alma işleminde parametreler eksik.',
      pl: 'W pobieraniu pliku konfiguracji Bitbucket brakuje parametrów.',
      id: 'Ambil file konfigurasi Bitbucket kekurangan parameter.',
      vi: 'Lấy tệp cấu hình Bitbucket bị thiếu tham số.',
      uk: 'У запиті на отримання файлу конфігурації Bitbucket відсутні параметри.',
    },
    statusCode: HttpStatusCodes.BAD_REQUEST_400,
  },
  BITBUCKET_CONFIG_FILE_NOT_FOUND: {
    title: {
      en: 'Bitbucket Config File Not Found',
      'en-GB': 'Bitbucket Config File Not Found',
      fr: 'Fichier de configuration Bitbucket non trouvé',
      es: 'Archivo de configuración de Bitbucket no encontrado',
      ru: 'Файл конфигурации Bitbucket не найден',
      ja: 'Bitbucket構成ファイルが見つかりません',
      ko: 'Bitbucket 구성 파일을 찾을 수 없습니다',
      zh: '未找到 Bitbucket 配置文件',
      de: 'Bitbucket-Konfigurationsdatei nicht gefunden',
      ar: 'ملف تكوين Bitbucket غير موجود',
      it: 'File di configurazione Bitbucket non trovato',
      pt: 'Arquivo de configuração do Bitbucket não encontrado',
      hi: 'Bitbucket कॉन्फ़िग फ़ाइल नहीं मिली',
      tr: 'Bitbucket yapılandırma dosyası bulunamadı',
      pl: 'Nie znaleziono pliku konfiguracji Bitbucket',
      id: 'File Konfigurasi Bitbucket Tidak Ditemukan',
      vi: 'Không tìm thấy tệp cấu hình Bitbucket',
      uk: 'Файл конфігурації Bitbucket не знайдено',
    },
    message: {
      en: 'The Bitbucket config file was not found.',
      'en-GB': 'The Bitbucket config file was not found.',
      fr: "Le fichier de configuration Bitbucket n'a pas été trouvé.",
      es: 'El archivo de configuración de Bitbucket no se ha encontrado.',
      ru: 'Файл конфигурации Bitbucket не был найден.',
      ja: 'Bitbucket構成ファイルが見つかりませんでした。',
      ko: 'Bitbucket 구성 파일을 찾을 수 없습니다.',
      zh: '未找到 Bitbucket 配置文件。',
      de: 'Die Bitbucket-Konfigurationsdatei wurde nicht gefunden.',
      ar: 'لم يتم العثور على ملف تكوين Bitbucket.',
      it: 'Il file di configurazione Bitbucket non è stato trovato.',
      pt: 'O arquivo de configuração do Bitbucket não foi encontrado.',
      hi: 'Bitbucket कॉन्फ़िग फ़ाइल नहीं मिली।',
      tr: 'Bitbucket yapılandırma dosyası bulunamadı.',
      pl: 'Plik konfiguracji Bitbucket nie został znaleziony.',
      id: 'File konfigurasi Bitbucket tidak ditemukan.',
      vi: 'Tệp cấu hình Bitbucket không được tìm thấy.',
      uk: 'Файл конфігурації Bitbucket не було знайдено.',
    },
    statusCode: HttpStatusCodes.NOT_FOUND_404,
  },
  GITLAB_REDIRECT_URI_MISSING: {
    title: {
      en: 'GitLab Redirect URI Missing',
      'en-GB': 'GitLab Redirect URI Missing',
      fr: 'URI de redirection GitLab manquante',
      es: 'URI de redirección de GitLab no encontrada',
      ru: 'Отсутствует URI перенаправления GitLab',
      ja: 'GitLabリダイレクトURIが見つかりません',
      ko: 'GitLab 리디렉션 URI가 누락되었습니다',
      zh: 'GitLab 重定向 URI 丢失',
      de: 'GitLab-Redirect-URI fehlt',
      ar: 'عنوان URI لإعادة توجيه GitLab مفقود',
      it: 'URI di reindirizzamento GitLab mancante',
      pt: 'URI de redirecionamento do GitLab ausente',
      hi: 'GitLab रीडायरेक्ट URI अनुपलब्ध है',
      tr: 'GitLab yönlendirme URI’si eksik',
      pl: 'Brak identyfikatora URI przekierowania GitLab',
      id: 'URI Pengalihan GitLab Hilang',
      vi: 'Thiếu URI chuyển hướng GitLab',
      uk: 'Відсутній URI перенаправлення GitLab',
    },
    message: {
      en: 'The GitLab redirect URI is missing.',
      'en-GB': 'The GitLab redirect URI is missing.',
      fr: 'L’URI de redirection GitLab est manquante.',
      es: 'Falta la URI de redirección de GitLab.',
      ru: 'URI перенаправления GitLab отсутствует.',
      ja: 'GitLabリダイレクトURIが見つかりませんでした。',
      ko: 'GitLab 리디렉션 URI가 누락되었습니다.',
      zh: 'GitLab 重定向 URI 丢失。',
      de: 'Die GitLab-Redirect-URI fehlt.',
      ar: 'عنوان URI لإعادة توجيه GitLab مفقود.',
      it: 'L’URI di reindirizzamento GitLab è mancante.',
      pt: 'A URI de redirecionamento do GitLab está ausente.',
      hi: 'GitLab रीडायरेक्ट URI अनुपलब्ध है।',
      tr: 'GitLab yönlendirme URI’si eksik.',
      pl: 'Brakuje identyfikatora URI przekierowania GitLab.',
      id: 'URI pengalihan GitLab hilang.',
      vi: 'URI chuyển hướng GitLab bị thiếu.',
      uk: 'URI перенаправлення GitLab відсутній.',
    },
    statusCode: HttpStatusCodes.BAD_REQUEST_400,
  },
  GITLAB_CODE_MISSING: {
    title: {
      en: 'GitLab Code Missing',
      'en-GB': 'GitLab Code Missing',
      fr: 'Code GitLab manquant',
      es: 'Código GitLab no encontrado',
      ru: 'Код GitLab отсутствует',
      ja: 'GitLabコードが見つかりません',
      ko: 'GitLab 코드가 누락되었습니다',
      zh: 'GitLab 代码丢失',
      de: 'GitLab-Code fehlt',
      ar: 'رمز GitLab مفقود',
      it: 'Codice GitLab mancante',
      pt: 'Código GitLab ausente',
      hi: 'GitLab कोड अनुपलब्ध है',
      tr: 'GitLab kodu eksik',
      pl: 'Brak kodu GitLab',
      id: 'Kode GitLab Hilang',
      vi: 'Thiếu mã GitLab',
      uk: 'Код GitLab відсутній',
    },
    message: {
      en: 'The GitLab code is missing.',
      'en-GB': 'The GitLab code is missing.',
      fr: 'Le code GitLab est manquant.',
      es: 'El código GitLab no se ha encontrado.',
      ru: 'Код GitLab отсутствует.',
      ja: 'GitLabコードが見つかりませんでした。',
      ko: 'GitLab 코드가 누락되었습니다.',
      zh: 'GitLab 代码丢失。',
      de: 'Der GitLab-Code fehlt.',
      ar: 'رمز GitLab مفقود.',
      it: 'Il codice GitLab è mancante.',
      pt: 'O código GitLab está ausente.',
      hi: 'GitLab कोड अनुपलब्ध है।',
      tr: 'GitLab kodu eksik.',
      pl: 'Brak kodu GitLab.',
      id: 'Kode GitLab hilang.',
      vi: 'Mã GitLab bị thiếu.',
      uk: 'Код GitLab відсутній.',
    },
    statusCode: HttpStatusCodes.BAD_REQUEST_400,
  },
  GITLAB_TOKEN_MISSING: {
    title: {
      en: 'GitLab Token Missing',
      'en-GB': 'GitLab Token Missing',
      fr: 'Jeton GitLab manquant',
      es: 'Token GitLab no encontrado',
      ru: 'Токен GitLab отсутствует',
      ja: 'GitLabトークンが見つかりません',
      ko: 'GitLab 토큰이 누락되었습니다',
      zh: 'GitLab 令牌丢失',
      de: 'GitLab-Token fehlt',
      ar: 'رمز GitLab (Token) مفقود',
      it: 'Token GitLab mancante',
      pt: 'Token GitLab ausente',
      hi: 'GitLab टोकन अनुपलब्ध है',
      tr: 'GitLab belirteci eksik',
      pl: 'Brak tokena GitLab',
      id: 'Token GitLab Hilang',
      vi: 'Thiếu mã thông báo GitLab',
      uk: 'Токен GitLab відсутній',
    },
    message: {
      en: 'The GitLab token is missing.',
      'en-GB': 'The GitLab token is missing.',
      fr: 'Le jeton GitLab est manquant.',
      es: 'El token GitLab no se ha encontrado.',
      ru: 'Токен GitLab отсутствует.',
      ja: 'GitLabトークンが見つかりませんでした।',
      ko: 'GitLab 토큰이 누락되었습니다.',
      zh: 'GitLab 令牌丢失。',
      de: 'Der GitLab-Token fehlt.',
      ar: 'رمز GitLab (Token) مفقود.',
      it: 'Il token GitLab è mancante.',
      pt: 'O token GitLab está ausente.',
      hi: 'GitLab टोकन अनुपलब्ध है।',
      tr: 'GitLab belirteci eksik.',
      pl: 'Brak tokena GitLab.',
      id: 'Token GitLab hilang.',
      vi: 'Mã thông báo GitLab bị thiếu.',
      uk: 'Токен GitLab відсутній.',
    },
    statusCode: HttpStatusCodes.BAD_REQUEST_400,
  },
  GITLAB_CHECK_CONFIG_MISSING_PARAMS: {
    title: {
      en: 'GitLab Check Config Missing Params',
      'en-GB': 'GitLab Check Config Missing Params',
      fr: 'Paramètres de configuration GitLab Check manquants',
      es: 'Parámetros de configuración de GitLab Check no encontrados',
      ru: 'Отсутствуют параметры конфигурации проверки GitLab',
      ja: 'GitLabチェック構成のパラメータが見つかりません',
      ko: 'GitLab 확인 구성 매개변수가 누락되었습니다',
      zh: 'GitLab 检查配置缺少参数',
      de: 'GitLab Check Config Fehlende Parameter',
      ar: 'معلمات تكوين فحص GitLab مفقودة',
      it: 'Parametri configurazione GitLab Check mancanti',
      pt: 'Parâmetros de configuração do GitLab Check ausentes',
      hi: 'GitLab चेक कॉन्फ़िग पैरामीटर अनुपलब्ध हैं',
      tr: 'GitLab kontrol yapılandırması eksik parametreler',
      pl: 'Brak parametrów konfiguracji sprawdzania GitLab',
      id: 'Parameter Konfigurasi Pemeriksaan GitLab Hilang',
      vi: 'Thiếu tham số cấu hình kiểm tra GitLab',
      uk: 'Відсутні параметри конфігурації перевірки GitLab',
    },
    message: {
      en: 'The GitLab check config is missing params.',
      'en-GB': 'The GitLab check config is missing params.',
      fr: 'Les paramètres de configuration GitLab Check sont manquants.',
      es: 'Faltan parámetros en la configuración de GitLab Check.',
      ru: 'В конфигурации проверки GitLab отсутствуют параметры.',
      ja: 'GitLabチェック構成にパラメータがありません。',
      ko: 'GitLab 확인 구성에 매개변수가 누락되었습니다.',
      zh: 'GitLab 检查配置缺少参数。',
      de: 'In der GitLab-Check-Konfiguration fehlen Parameter.',
      ar: 'تكوين فحص GitLab يفتقد إلى المعلمات.',
      it: 'La configurazione di controllo GitLab manca di parametri.',
      pt: 'A configuração de verificação do GitLab está sem parâmetros.',
      hi: 'GitLab चेक कॉन्फ़िग में पैरामीटर अनुपलब्ध हैं।',
      tr: 'GitLab kontrol yapılandırmasında parametreler eksik.',
      pl: 'W konfiguracji sprawdzania GitLab brakuje parametrów.',
      id: 'Konfigurasi pemeriksaan GitLab kekurangan parameter.',
      vi: 'Cấu hình kiểm tra GitLab bị thiếu tham số.',
      uk: 'У конфігурації перевірки GitLab відсутні параметри.',
    },
    statusCode: HttpStatusCodes.BAD_REQUEST_400,
  },
  GITLAB_GET_CONFIG_FILE_MISSING_PARAMS: {
    title: {
      en: 'GitLab Get Config File Missing Params',
      'en-GB': 'GitLab Get Config File Missing Params',
      fr: 'Paramètres GitLab Get Config File manquants',
      es: 'Parámetros de GitLab Get Config File no encontrados',
      ru: 'Отсутствуют параметры получения файла конфигурации GitLab',
      ja: 'GitLab構成ファイル取得のパラメータが見つかりません',
      ko: 'GitLab 구성 파일 가져오기 매개변수가 누락되었습니다',
      zh: 'GitLab 获取配置文件缺少参数',
      de: 'GitLab Get Config File Fehlende Parameter',
      ar: 'معلمات ملف الحصول على تكوين GitLab مفقودة',
      it: 'Parametri GitLab Get Config File mancanti',
      pt: 'Parâmetros do arquivo de configuração do GitLab ausentes',
      hi: 'GitLab कॉन्फ़िग फ़ाइल प्राप्त करने के पैरामीटर अनुपलब्ध हैं',
      tr: 'GitLab yapılandırma dosyası alma eksik parametreler',
      pl: 'Brak parametrów pobierania pliku konfiguracji GitLab',
      id: 'Parameter Ambil File Konfigurasi GitLab Hilang',
      vi: 'Thiếu tham số lấy tệp cấu hình GitLab',
      uk: 'Відсутні параметри отримання файлу конфігурації GitLab',
    },
    message: {
      en: 'The GitLab get config file is missing params.',
      'en-GB': 'The GitLab get config file is missing params.',
      fr: 'Les paramètres pour obtenir le fichier de configuration GitLab sont manquants.',
      es: 'Faltan parámetros para obtener el archivo de configuración de GitLab.',
      ru: 'В запросе на получение файла конфигурации GitLab отсутствуют параметры.',
      ja: 'GitLab構成ファイルの取得にパラメータがありません।',
      ko: 'GitLab 구성 파일을 가져오는 데 매개변수가 누락되었습니다.',
      zh: 'GitLab 获取配置文件缺少参数。',
      de: 'In der GitLab-Konfigurationsdatei fehlen Parameter.',
      ar: 'ملف الحصول على تكوين GitLab يفتقد إلى المعلمات.',
      it: 'La richiesta del file di configurazione GitLab manca di parametri.',
      pt: 'O arquivo de configuração do GitLab está sem parâmetros.',
      hi: 'GitLab कॉन्फ़िग फ़ाइल प्राप्त करने में पैरामीटर अनुपलब्ध हैं।',
      tr: 'GitLab yapılandırma dosyası alma işleminde parametreler eksik.',
      pl: 'W pobieraniu pliku konfiguracji GitLab brakuje parametrów.',
      id: 'Ambil file konfigurasi GitLab kekurangan parameter.',
      vi: 'Lấy tệp cấu hình GitLab bị thiếu tham số.',
      uk: 'У запиті на отримання файлу конфігурації GitLab відсутні параметри.',
    },
    statusCode: HttpStatusCodes.BAD_REQUEST_400,
  },
  GITLAB_CONFIG_FILE_NOT_FOUND: {
    title: {
      en: 'GitLab Config File Not Found',
      'en-GB': 'GitLab Config File Not Found',
      fr: 'Fichier de configuration GitLab non trouvé',
      es: 'Archivo de configuración de GitLab no encontrado',
      ru: 'Файл конфигурации GitLab не найден',
      ja: 'GitLab構成ファイルが見つかりません',
      ko: 'GitLab 구성 파일을 찾을 수 없습니다',
      zh: '未找到 GitLab 配置文件',
      de: 'GitLab-Konfigurationsdatei nicht gefunden',
      ar: 'ملف تكوين GitLab غير موجود',
      it: 'File di configurazione GitLab non trovato',
      pt: 'Arquivo de configuração do GitLab não encontrado',
      hi: 'GitLab कॉन्फ़िग फ़ाइल नहीं मिली',
      tr: 'GitLab yapılandırma dosyası bulunamadı',
      pl: 'Nie znaleziono pliku konfiguracji GitLab',
      id: 'File Konfigurasi GitLab Tidak Ditemukan',
      vi: 'Không tìm thấy tệp cấu hình GitLab',
      uk: 'Файл конфігурації GitLab не знайдено',
    },
    message: {
      en: 'The GitLab config file was not found.',
      'en-GB': 'The GitLab config file was not found.',
      fr: "Le fichier de configuration GitLab n'a pas été trouvé.",
      es: 'El archivo de configuración de GitLab no se ha encontrado.',
      ru: 'Файл конфигурации GitLab не был найден.',
      ja: 'GitLab構成ファイルが見つかりませんでした।',
      ko: 'GitLab 구성 파일을 찾을 수 없습니다.',
      zh: '未找到 GitLab 配置文件।',
      de: 'Die GitLab-Konfigurationsdatei wurde nicht gefunden.',
      ar: 'لم يتم العثور على ملف تكوين GitLab.',
      it: 'Il file di configurazione GitLab non è stato trovato.',
      pt: 'O arquivo de configuração do GitLab não foi encontrado.',
      hi: 'GitLab कॉन्फ़िग फ़ाइल नहीं मिली।',
      tr: 'GitLab yapılandırma dosyası bulunamadı.',
      pl: 'Plik konfiguracji GitLab nie został znaleziony.',
      id: 'File konfigurasi GitLab tidak ditemukan.',
      vi: 'Tệp cấu hình GitLab không được tìm thấy.',
      uk: 'Файл конфігурації GitLab не було знайдено.',
    },
    statusCode: HttpStatusCodes.NOT_FOUND_404,
  },
} satisfies Record<string, ErrorCode>;
