import { HttpStatusCodes } from '@utils/httpStatusCodes';
import type { ErrorCode } from './errorCodes.types';

/**
 * Website scan error codes.
 */
export const scanErrors = {
  SCAN_URL_NOT_PUBLIC: {
    title: {
      en: 'Invalid URL',
      'en-GB': 'Invalid URL',
      fr: 'URL invalide',
      es: 'URL no válida',
      ru: 'Недопустимый URL',
      ja: '無効な URL',
      ko: '잘못된 URL',
      zh: '无效的 URL',
      de: 'Ungültige URL',
      ar: 'عنوان URL غير صالح',
      it: 'URL non valido',
      pt: 'URL inválida',
      hi: 'अमान्य URL',
      tr: 'Geçersiz URL',
      pl: 'Nieprawidłowy adres URL',
      id: 'URL tidak valid',
      vi: 'URL không hợp lệ',
      uk: 'Недійсна URL-адреса',
    },
    message: {
      en: 'Only public http(s) URLs can be scanned.',
      'en-GB': 'Only public http(s) URLs can be scanned.',
      fr: 'Seules les URL http(s) publiques peuvent être scannées.',
      es: 'Solo se pueden escanear URL http(s) públicas.',
      ru: 'Сканировать можно только публичные http(s) URL.',
      ja: 'スキャンできるのは公開された http(s) URL のみです。',
      ko: '공개 http(s) URL만 스캔할 수 있습니다.',
      zh: '只能扫描公开的 http(s) URL。',
      de: 'Nur öffentliche http(s)-URLs können gescannt werden.',
      ar: 'يمكن فحص عناوين http(s) العامة فقط.',
      it: 'È possibile scansionare solo URL http(s) pubblici.',
      pt: 'Apenas URLs http(s) públicas podem ser verificadas.',
      hi: 'केवल सार्वजनिक http(s) URL स्कैन किए जा सकते हैं।',
      tr: 'Yalnızca herkese açık http(s) URL’leri taranabilir.',
      pl: 'Można skanować tylko publiczne adresy URL http(s).',
      id: 'Hanya URL http(s) publik yang dapat dipindai.',
      vi: 'Chỉ có thể quét các URL http(s) công khai.',
      uk: 'Сканувати можна лише публічні http(s) URL-адреси.',
    },
    statusCode: HttpStatusCodes.BAD_REQUEST_400,
  },
  SCANNED_HOST_NOT_FOUND: {
    title: {
      en: 'Host Not Found',
      'en-GB': 'Host Not Found',
      fr: 'Hôte introuvable',
      es: 'Host no encontrado',
      ru: 'Хост не найден',
      ja: 'ホストが見つかりません',
      ko: '호스트를 찾을 수 없습니다',
      zh: '未找到主机',
      de: 'Host nicht gefunden',
      ar: 'المضيف غير موجود',
      it: 'Host non trovato',
      pt: 'Host não encontrado',
      hi: 'होस्ट नहीं मिला',
      tr: 'Ana makine bulunamadı',
      pl: 'Nie znaleziono hosta',
      id: 'Host Tidak Ditemukan',
      vi: 'Không tìm thấy máy chủ',
      uk: 'Хост не знайдено',
    },
    message: {
      en: 'This host has never been scanned.',
      'en-GB': 'This host has never been scanned.',
      fr: "Cet hôte n'a jamais été scanné.",
      es: 'Este host nunca ha sido escaneado.',
      ru: 'Этот хост ещё ни разу не сканировался.',
      ja: 'このホストはまだスキャンされていません。',
      ko: '이 호스트는 스캔된 적이 없습니다.',
      zh: '该主机从未被扫描过。',
      de: 'Dieser Host wurde noch nie gescannt.',
      ar: 'لم يتم فحص هذا المضيف من قبل.',
      it: 'Questo host non è mai stato scansionato.',
      pt: 'Este host nunca foi verificado.',
      hi: 'इस होस्ट को कभी स्कैन नहीं किया गया।',
      tr: 'Bu ana makine hiç taranmadı.',
      pl: 'Ten host nigdy nie był skanowany.',
      id: 'Host ini belum pernah dipindai.',
      vi: 'Máy chủ này chưa từng được quét.',
      uk: 'Цей хост ще жодного разу не сканувався.',
    },
    statusCode: HttpStatusCodes.NOT_FOUND_404,
  },
} satisfies Record<string, ErrorCode>;
