import { HttpStatusCodes } from '@utils/httpStatusCodes';
import type { ErrorCode } from './errorCodes.types';

/**
 * Showcase-related error codes.
 */
export const showcaseErrors = {
  SHOWCASE_PROJECT_NOT_FOUND: {
    title: {
      en: 'Showcase Project Not Found',
      'en-GB': 'Showcase Project Not Found',
      fr: 'Projet vitrine non trouvé',
      es: 'Proyecto de vitrina no encontrado',
      ru: 'Проект витрины не найден',
      ja: 'ショーケースプロジェクトが見つかりません',
      ko: '쇼케이스 프로젝트를 찾을 수 없습니다',
      zh: '未找到展示项目',
      de: 'Showcase-Projekt nicht gefunden',
      ar: 'مشروع الواجهة غير موجود',
      it: 'Progetto showcase non trovato',
      pt: 'Projeto de vitrine não encontrado',
      hi: 'शोकेस प्रोजेक्ट नहीं मिला',
      tr: 'Vitrin projesi bulunamadı',
      pl: 'Nie znaleziono projektu showcase',
      id: 'Proyek Showcase Tidak Ditemukan',
      vi: 'Không tìm thấy dự án trưng bày',
      uk: 'Проект вітрини не знайдено',
    },
    message: {
      en: 'The showcase project was not found.',
      'en-GB': 'The showcase project was not found.',
      fr: "Le projet vitrine n'a pas été trouvé.",
      es: 'El proyecto de vitrina no se ha encontrado.',
      ru: 'Проект витрины не был найден.',
      ja: 'ショーケースプロジェクトが見つかりませんでした。',
      ko: '쇼케이스 프로젝트를 찾을 수 없습니다.',
      zh: '未找到展示项目。',
      de: 'Das Showcase-Projekt wurde nicht gefunden.',
      ar: 'لم يتم العثور على مشروع الواجهة.',
      it: 'Il progetto showcase non è stato trovato.',
      pt: 'O projeto de vitrine não foi encontrado.',
      hi: 'शोकेस प्रोजेक्ट नहीं मिला।',
      tr: 'Vitrin projesi bulunamadı.',
      pl: 'Projekt showcase nie został znaleziony.',
      id: 'Proyek showcase tidak ditemukan.',
      vi: 'Dự án trưng bày không được tìm thấy.',
      uk: 'Проект вітрини не було знайдено.',
    },
    statusCode: HttpStatusCodes.NOT_FOUND_404,
  },
  SHOWCASE_PROJECT_URL_ALREADY_EXISTS: {
    title: {
      en: 'Showcase Project Already Exists',
      'en-GB': 'Showcase Project Already Exists',
      fr: 'Le projet vitrine existe déjà',
      es: 'El proyecto de vitrina ya existe',
      ru: 'Проект витрины уже существует',
      ja: 'ショーケースプロジェクトは既に存在します',
      ko: '쇼케이스 프로젝트가 이미 존재합니다',
      zh: '展示项目已存在',
      de: 'Showcase-Projekt existiert bereits',
      ar: 'مشروع الواجهة موجود بالفعل',
      it: 'Il progetto showcase esiste già',
      pt: 'O projeto de vitrine já existe',
      hi: 'शोकेस प्रोजेक्ट पहले से मौजूद है',
      tr: 'Vitrin projesi zaten mevcut',
      pl: 'Projekt showcase już istnieje',
      id: 'Proyek Showcase Sudah Ada',
      vi: 'Dự án trưng bày đã tồn tại',
      uk: 'Проект вітрини вже існує',
    },
    message: {
      en: 'A project with this URL has already been submitted.',
      'en-GB': 'A project with this URL has already been submitted.',
      fr: 'Un projet avec cette URL a déjà été soumis.',
      es: 'Ya se ha enviado un proyecto con esta URL.',
      ru: 'Проект с таким URL уже был отправлен.',
      ja: 'このURLのプロジェクトは既に送信されています。',
      ko: '이 URL의 프로젝트가 이미 제출되었습니다.',
      zh: '已提交具有此 URL 的项目。',
      de: 'Ein Projekt mit dieser URL wurde bereits eingereicht.',
      ar: 'تم تقديم مشروع بهذا العنوان بالفعل.',
      it: 'Un progetto con questo URL è già stato inviato.',
      pt: 'Um projeto com esta URL já foi enviado.',
      hi: 'इस URL वाला प्रोजेक्ट पहले ही सबमिट किया जा चुका है।',
      tr: 'Bu URL’ye sahip bir proje zaten gönderildi.',
      pl: 'Projekt o tym adresie URL został już przesłany.',
      id: 'Proyek dengan URL ini sudah dikirimkan.',
      vi: 'Một dự án với URL này đã được gửi.',
      uk: 'Проект із такою URL-адресою вже був надісланий.',
    },
    statusCode: HttpStatusCodes.CONFLICT_409,
  },
  SHOWCASE_PROJECT_NOT_INTLAYER: {
    title: {
      en: 'Not an Intlayer Application',
      'en-GB': 'Not an Intlayer Application',
      fr: 'Pas une application Intlayer',
      es: 'No es una aplicación Intlayer',
      ru: 'Не является приложением Intlayer',
      ja: 'Intlayerアプリケーションではありません',
      ko: 'Intlayer 애플리케이션이 아닙니다',
      zh: '不是 Intlayer 应用程序',
      de: 'Keine Intlayer-Anwendung',
      ar: 'ليست تطبيق Intlayer',
      it: 'Non è un’applicazione Intlayer',
      pt: 'Não é uma aplicação Intlayer',
      hi: 'Intlayer एप्लिकेशन नहीं है',
      tr: 'Bir Intlayer uygulaması değil',
      pl: 'To nie jest aplikacja Intlayer',
      id: 'Bukan Aplikasi Intlayer',
      vi: 'Không phải là ứng dụng Intlayer',
      uk: 'Не є додатком Intlayer',
    },
    message: {
      en: 'The URL does not seem to contain a valid Intlayer application. Ensure Intlayer is installed and deployed.',
      'en-GB':
        'The URL does not seem to contain a valid Intlayer application. Ensure Intlayer is installed and deployed.',
      fr: "L'URL ne semble pas contenir une application Intlayer valide. Assurez-vous qu'Intlayer est installé et déployé.",
      es: 'La URL no parece contener una aplicación Intlayer válida. Asegúrese de que Intlayer esté instalado y desplegado.',
      ru: 'Похоже, что URL-адрес не содержит допустимого приложения Intlayer. Убедитесь, что Intlayer установлен и развернут.',
      ja: 'URLに有効なIntlayerアプリケーションが含まれていないようです。Intlayerがインストールされ、デプロイされていることを確認してください。',
      ko: 'URL에 유효한 Intlayer 애플리케이션이 포함되어 있지 않은 것 같습니다. Intlayer가 설치되고 배포되었는지 확인하십시오.',
      zh: '该 URL 似乎不包含有效的 Intlayer 应用程序。确保已安装并部署 Intlayer。',
      de: 'Die URL scheint keine gültige Intlayer-Anwendung zu enthalten. Stellen Sie sicher, dass Intlayer installiert und bereitgestellt ist.',
      ar: 'يبدو أن عنوان URL لا يحتوي على تطبيق Intlayer صالح. تأكد من تثبيت ونشر Intlayer.',
      it: 'L’URL non sembra contenere un’applicazione Intlayer valida. Assicurati che Intlayer sia installato e distribuito.',
      pt: 'A URL não parece conter uma aplicação Intlayer válida. Certifique-se de que o Intlayer está instalado e implantado.',
      hi: 'URL में मान्य Intlayer एप्लिकेशन नहीं लग रहा है। सुनिश्चित करें कि Intlayer स्थापित और तैनात है।',
      tr: 'URL geçerli bir Intlayer uygulaması içermiyor gibi görünüyor. Intlayer’ın kurulu ve dağıtılmış olduğundan emin olun.',
      pl: 'Adres URL nie wydaje się zawierać prawidłowej aplikacji Intlayer. Upewnij się, że Intlayer jest zainstalowany i wdrożony.',
      id: 'URL tersebut sepertinya tidak berisi aplikasi Intlayer yang valid. Pastikan Intlayer sudah terinstal dan diterapkan.',
      vi: 'URL dường như không chứa ứng dụng Intlayer hợp lệ. Đảm bảo Intlayer đã được cài đặt và triển khai.',
      uk: 'Схоже, що URL-адреса не містить дійсного додатка Intlayer. Переконайтеся, що Intlayer встановлено та розгорнуто.',
    },
    statusCode: HttpStatusCodes.BAD_REQUEST_400,
  },
} satisfies Record<string, ErrorCode>;
