import { HttpStatusCodes } from '@utils/httpStatusCodes';
import type { ErrorCode } from './errorCodes.types';

/**
 * User-related error codes.
 */
export const userErrors = {
  USER_NOT_DEFINED: {
    title: {
      en: 'User not defined',
      'en-GB': 'User not defined',
      fr: 'Utilisateur non défini',
      es: 'Usuario no definido',
      ru: 'Пользователь не определен',
      ja: 'ユーザーが定義されていません',
      ko: '사용자가 정의되지 않았습니다',
      zh: '用户未定义',
      de: 'Benutzer nicht definiert',
      ar: 'المستخدم غير محدد',
      it: 'Utente non definito',
      pt: 'Usuário não definido',
      hi: 'उपयोगकर्ता परिभाषित नहीं है',
      tr: 'Kullanıcı tanımlanmamış',
      pl: 'Użytkownik nie został zdefiniowany',
      id: 'Pengguna tidak ditentukan',
      vi: 'Người dùng chưa được định nghĩa',
      uk: 'Користувач не визначений',
    },
    message: {
      en: 'User is required, but not defined.',
      'en-GB': 'User is required, but not defined.',
      fr: 'Utilisateur requis, mais non défini.',
      es: 'Usuario es requerido, pero no está definido.',
      ru: 'Пользователь обязателен, но не определен.',
      ja: 'ユーザーは必須ですが、定義されていません。',
      ko: '사용자가 필요하지만 정의되지 않았습니다.',
      zh: '用户是必需的，但未定义。',
      de: 'Benutzer ist erforderlich, aber nicht definiert.',
      ar: 'المستخدم مطلوب، لكنه غير محدد.',
      it: 'L’utente è richiesto, ma non definito.',
      pt: 'O usuário é obrigatório, mas não está definido.',
      hi: 'उपयोगकर्ता आवश्यक है, लेकिन परिभाषित नहीं है।',
      tr: 'Kullanıcı gerekli ancak tanımlanmamış.',
      pl: 'Użytkownik jest wymagany, ale nie został zdefiniowany.',
      id: 'Pengguna diperlukan, tetapi tidak ditentukan.',
      vi: 'Người dùng là bắt buộc nhưng chưa được định nghĩa.',
      uk: 'Користувач обов’язковий, але не визначений.',
    },
    statusCode: HttpStatusCodes.BAD_REQUEST_400,
  },
  USER_NOT_FOUND: {
    title: {
      en: 'User not found',
      'en-GB': 'User not found',
      fr: 'Utilisateur non trouvé',
      es: 'Usuario no encontrado',
      ru: 'Пользователь не найден',
      ja: 'ユーザーが見つかりません',
      ko: '사용자를 찾을 수 없습니다',
      zh: '未找到用户',
      de: 'Benutzer nicht gefunden',
      ar: 'المستخدم غير موجود',
      it: 'Utente non trovato',
      pt: 'Usuário não encontrado',
      hi: 'उपयोगकर्ता नहीं मिला',
      tr: 'Kullanıcı bulunamadı',
      pl: 'Nie znaleziono użytkownika',
      id: 'Pengguna tidak ditemukan',
      vi: 'Không tìm thấy người dùng',
      uk: 'Користувач не знайдений',
    },
    message: {
      en: 'The user is probably not authenticated. Please try again.',
      'en-GB': 'The user is probably not authenticated. Please try again.',
      fr: "L'utilisateur n'est probablement pas authentifié. Veuillez réessayer.",
      es: 'El usuario probablemente no está autenticado. Por favor, inténtelo de nuevo.',
      ru: 'Пользователь, вероятно, не аутентифицирован. Пожалуйста, попробуйте снова.',
      ja: 'ユーザーが認証されていない可能性があります。もう一度お試しください。',
      ko: '사용자가 인증되지 않았을 수 있습니다. 다시 시도하십시오.',
      zh: '用户可能未通过身份验证。请重试。',
      de: 'Der Benutzer ist wahrscheinlich nicht authentifiziert. Bitte versuchen Sie es erneut.',
      ar: 'المستخدم على الأرجح غير مصادق عليه. يرجى المحاولة مرة أخرى.',
      it: 'L’utente probabilmente non è autenticato. Riprova.',
      pt: 'O usuário provavelmente não está autenticado. Por favor, tente novamente.',
      hi: 'उपयोगकर्ता शायद प्रमाणित नहीं है। कृपया पुनः प्रयास करें।',
      tr: 'Kullanıcı muhtemelen kimlik doğrulaması yapmamış. Lütfen tekrar deneyin.',
      pl: 'Użytkownik prawdopodobnie nie jest uwierzytelniony. Proszę spróbować ponownie.',
      id: 'Pengguna mungkin tidak terautentikasi. Harap coba lagi.',
      vi: 'Người dùng có thể chưa được xác thực. Vui lòng thử lại.',
      uk: 'Користувач, ймовірно, не автентифікований. Будь ласка, спробуйте ще раз.',
    },
    statusCode: HttpStatusCodes.FORBIDDEN_403,
  },
  USER_DATA_NOT_FOUND: {
    title: {
      en: 'User Data Not Found',
      'en-GB': 'User Data Not Found',
      fr: 'Données utilisateur non trouvées',
      es: 'Datos de usuario no encontrados',
      ru: 'Данные пользователя не найдены',
      ja: 'ユーザーデータが見つかりません',
      ko: '사용자 데이터를 찾을 수 없습니다',
      zh: '未找到用户数据',
      de: 'Benutzerdaten nicht gefunden',
      ar: 'بيانات المستخدم غير موجودة',
      it: 'Dati utente non trovati',
      pt: 'Dados do usuário não encontrados',
      hi: 'उपयोगकर्ता डेटा नहीं मिला',
      tr: 'Kullanıcı verisi bulunamadı',
      pl: 'Nie znaleziono danych użytkownika',
      id: 'Data Pengguna Tidak Ditemukan',
      vi: 'Không tìm thấy dữ liệu người dùng',
      uk: 'Дані користувача не знайдені',
    },
    message: {
      en: 'The user data was not found.',
      'en-GB': 'The user data was not found.',
      fr: "Les données utilisateur n'ont pas été trouvées.",
      es: 'Los datos del usuario no se han encontrado.',
      ru: 'Данные пользователя не были найдены.',
      ja: 'ユーザーデータが見つかりませんでした。',
      ko: '사용자 데이터를 찾을 수 없습니다.',
      zh: '未找到用户数据。',
      de: 'Die Benutzerdaten wurden nicht gefunden.',
      ar: 'لم يتم العثور على بيانات المستخدم.',
      it: 'I dati dell’utente non sono stati trovati.',
      pt: 'Os dados do usuário não foram encontrados.',
      hi: 'उपयोगकर्ता डेटा नहीं मिला।',
      tr: 'Kullanıcı verileri bulunamadı.',
      pl: 'Dane użytkownika nie zostały znalezione.',
      id: 'Data pengguna tidak ditemukan.',
      vi: 'Dữ liệu người dùng không được tìm thấy.',
      uk: 'Дані користувача не були знайдені.',
    },
    statusCode: HttpStatusCodes.NOT_FOUND_404,
  },
  USER_ALREADY_LOGGED_IN: {
    title: {
      en: 'User Already Logged In',
      'en-GB': 'User Already Logged In',
      fr: 'Utilisateur déjà connecté',
      es: 'Usuario ya conectado',
      ru: 'Пользователь уже вошел в систему',
      ja: 'ユーザーはすでにログインしています',
      ko: '사용자가 이미 로그인되어 있습니다',
      zh: '用户已登录',
      de: 'Benutzer bereits angemeldet',
      ar: 'المستخدم مسجل الدخول بالفعل',
      it: 'Utente già autenticato',
      pt: 'Usuário já logado',
      hi: 'उपयोगकर्ता पहले से ही लॉग इन है',
      tr: 'Kullanıcı zaten giriş yapmış',
      pl: 'Użytkownik jest już zalogowany',
      id: 'Pengguna Sudah Login',
      vi: 'Người dùng đã đăng nhập',
      uk: 'Користувач вже увійшов у систему',
    },
    message: {
      en: 'The user is already logged in.',
      'en-GB': 'The user is already logged in.',
      fr: "L'utilisateur est déjà connecté.",
      es: 'El usuario ya está conectado.',
      ru: 'Пользователь уже вошел в систему.',
      ja: 'ユーザーはすでにログインしています。',
      ko: '사용자가 이미 로그인되어 있습니다.',
      zh: '用户已登录。',
      de: 'Der Benutzer ist bereits angemeldet.',
      ar: 'المستخدم مسجل الدخول بالفعل.',
      it: 'L’utente è già autenticato.',
      pt: 'O usuário já está logado.',
      hi: 'उपयोगकर्ता पहले से ही लॉग इन है।',
      tr: 'Kullanıcı zaten giriş yapmış.',
      pl: 'Użytkownik jest już zalogowany.',
      id: 'Pengguna sudah login.',
      vi: 'Người dùng đã đăng nhập.',
      uk: 'Користувач вже увійшов у систему.',
    },
    statusCode: HttpStatusCodes.BAD_REQUEST_400,
  },
  USER_ID_MISMATCH: {
    title: {
      en: 'User ID Mismatch',
      'en-GB': 'User ID Mismatch',
      fr: 'Identifiant utilisateur ne correspond pas',
      es: 'Identificador de usuario no coincide',
      ru: 'Несоответствие ID пользователя',
      ja: 'ユーザーIDの不一致',
      ko: '사용자 ID 불일치',
      zh: '用户 ID 不匹配',
      de: 'Benutzer-ID-Fehlübereinstimmung',
      ar: 'عدم تطابق معرف المستخدم',
      it: 'Mancata corrispondenza dell’ID utente',
      pt: 'Incompatibilidade de ID de usuário',
      hi: 'उपयोगकर्ता आईडी बेमेल',
      tr: 'Kullanıcı ID uyuşmazlığı',
      pl: 'Niezgodność identyfikatora użytkownika',
      id: 'Ketidakcocokan ID Pengguna',
      vi: 'Mã định danh người dùng không khớp',
      uk: 'Невідповідність ID користувача',
    },
    message: {
      en: 'The provided user ID does not match the expected value. Please verify and try again.',
      'en-GB':
        'The provided user ID does not match the expected value. Please verify and try again.',
      fr: "L'identifiant utilisateur fourni ne correspond pas à la valeur attendue. Veuillez vérifier et réessayer.",
      es: 'El identificador de usuario proporcionado no coincide con el valor esperado. Verifique e intente nuevamente.',
      ru: 'Предоставленный ID пользователя не соответствует ожидаемому значению. Пожалуйста, проверьте и попробуйте еще раз.',
      ja: '提供されたユーザーIDが期待される値と一致しません。確認して再試行してください。',
      ko: '제공된 사용자 ID가 예상 값과 일치하지 않습니다. 확인 후 다시 시도하십시오.',
      zh: '提供的用户 ID 与预期值不匹配。请验证并重试。',
      de: 'Die angegebene Benutzer-ID stimmt nicht mit dem erwarteten Wert überein. Bitte überprüfen Sie sie und versuchen Sie es erneut.',
      ar: 'معرف المستخدم المقدم لا يتطابق مع القيمة المتوقعة. يرجى التحقق والمحاولة مرة أخرى.',
      it: 'L’ID utente fornito non corrisponde al valore previsto. Verificare e riprovare.',
      pt: 'O ID de usuário fornecido não coincide com o valor esperado. Verifique e tente novamente.',
      hi: 'प्रदान किया गया उपयोगकर्ता आईडी अपेक्षित मूल्य से मेल नहीं खाता है। कृपया सत्यापित करें और पुनः प्रयास करें।',
      tr: 'Sağlanan kullanıcı ID beklenen değerle eşleşmiyor. Lütfen doğrulayın ve tekrar deneyin.',
      pl: 'Podany identyfikator użytkownika nie zgadza się z oczekiwaną wartością. Proszę zweryfikować i spróbować ponownie.',
      id: 'ID pengguna yang diberikan tidak cocok dengan nilai yang diharapkan. Harap verifikasi dan coba lagi.',
      vi: 'Mã định danh người dùng được cung cấp không khớp với giá trị mong đợi. Vui lòng kiểm tra và thử lại.',
      uk: 'Наданий ID користувача не відповідає очікуваному значенню. Будь ласка, перевірте та спробуйте ще раз.',
    },
    statusCode: HttpStatusCodes.BAD_REQUEST_400,
  },
  USER_INVALID_FIELDS: {
    title: {
      en: 'User Invalid Fields',
      'en-GB': 'User Invalid Fields',
      fr: "Champs d'utilisateur invalides",
      es: 'Campos de usuario no válidos',
      ru: 'Недопустимые поля пользователя',
      ja: 'ユーザーの無効なフィールド',
      ko: '사용자 유효하지 않은 필드',
      zh: '用户无效字段',
      de: 'Ungültige Benutzerfelder',
      ar: 'حقول مستخدم غير صالحة',
      it: 'Campi utente non validi',
      pt: 'Campos de usuário inválidos',
      hi: 'उपयोगकर्ता के अमान्य फ़ील्ड',
      tr: 'Geçersiz kullanıcı alanları',
      pl: 'Nieprawidłowe pola użytkownika',
      id: 'Bidang Pengguna Tidak Valid',
      vi: 'Trường người dùng không hợp lệ',
      uk: 'Неприпустимі поля користувача',
    },
    message: {
      en: 'The provided user fields are invalid.',
      'en-GB': 'The provided user fields are invalid.',
      fr: "Les champs fournis pour l'utilisateur sont invalides.",
      es: 'Los campos proporcionados para el usuario no son válidos.',
      ru: 'Предоставленные поля пользователя недопустимы.',
      ja: '提供されたユーザーフィールドが無効です。',
      ko: '제공된 사용자 필드가 유효하지 않습니다.',
      zh: '提供的用户字段无效。',
      de: 'Die angegebenen Benutzerfelder sind ungültig.',
      ar: 'حقول المستخدم المقدمة غير صالحة.',
      it: 'I campi utente forniti non sono validi.',
      pt: 'Os campos de usuário fornecidos هستند inválidos.',
      hi: 'प्रदान किए गए उपयोगकर्ता फ़ील्ड अमान्य हैं।',
      tr: 'Sağlanan kullanıcı alanları geçersiz.',
      pl: 'Podane pola użytkownika są nieprawidłowe.',
      id: 'Bidang pengguna yang diberikan tidak valid.',
      vi: 'Các trường người dùng được cung cấp không hợp lệ.',
      uk: 'Надані поля користувача неприпустимі.',
    },
    statusCode: HttpStatusCodes.BAD_REQUEST_400,
  },
  USER_CREATION_FAILED: {
    title: {
      en: 'User Creation Failed',
      'en-GB': 'User Creation Failed',
      fr: "Échec de la création de l'utilisateur",
      es: 'Error al crear el usuario',
      ru: 'Ошибка создания пользователя',
      ja: 'ユーザーの作成に失敗しました',
      ko: '사용자 생성 실패',
      zh: '用户创建失败',
      de: 'Benutzererstellung fehlgeschlagen',
      ar: 'فشل إنشاء المستخدم',
      it: 'Creazione utente fallita',
      pt: 'Falha na criação do usuário',
      hi: 'उपयोगकर्ता निर्माण विफल रहा',
      tr: 'Kullanıcı oluşturma başarısız',
      pl: 'Tworzenie użytkownika nie powiodło się',
      id: 'Pembuatan Pengguna Gagal',
      vi: 'Tạo người dùng thất bại',
      uk: 'Помилка створення користувача',
    },
    message: {
      en: 'Failed to create the specified user.',
      'en-GB': 'Failed to create the specified user.',
      fr: "La création de l'utilisateur a échoué.",
      es: 'No se pudo crear el usuario especificado.',
      ru: 'Не удалось создать указанного пользователя.',
      ja: '指定されたユーザーの作成に失敗しました。',
      ko: '지정된 사용자를 생성하지 못했습니다.',
      zh: '无法创建指定的用户。',
      de: 'Der angegebene Benutzer konnte nicht erstellt werden.',
      ar: 'فشل في إنشاء المستخدم المحدد.',
      it: 'Impossibile creare l’utente specificato.',
      pt: 'Falha ao criar o usuário especificado.',
      hi: 'निर्दिष्ट उपयोगकर्ता बनाने में विफल।',
      tr: 'Belirtilen kullanıcı oluşturulamadı.',
      pl: 'Nie udało się utworzyć określonego użytkownika.',
      id: 'Gagal membuat pengguna yang ditentukan.',
      vi: 'Không thể tạo người dùng đã chỉ định.',
      uk: 'Не вдалося створити вказаного користувача.',
    },
    statusCode: HttpStatusCodes.INTERNAL_SERVER_ERROR_500,
  },
  USER_SESSION_EXPIRED: {
    title: {
      en: 'User Session Expired',
      'en-GB': 'User Session Expired',
      fr: 'Session utilisateur expirée',
      es: 'Sesión de usuario caducada',
      ru: 'Сессия пользователя истекла',
      ja: 'ユーザーセッションの期限が切れました',
      ko: '사용자 세션이 만료되었습니다',
      zh: '用户会话已过期',
      de: 'Benutzersitzung abgelaufen',
      ar: 'انتهت صلاحية جلسة المستخدم',
      it: 'Sessione utente scaduta',
      pt: 'Sessão de usuário expirada',
      hi: 'उपयोगकर्ता सत्र समाप्त हो गया है',
      tr: 'Kullanıcı oturumu sona erdi',
      pl: 'Sesja użytkownika wygasła',
      id: 'Sesi Pengguna Kedaluwarsa',
      vi: 'Phiên người dùng đã hết hạn',
      uk: 'Сесія користувача закінчилася',
    },
    message: {
      en: 'The user session has expired.',
      'en-GB': 'The user session has expired.',
      fr: "La session de l'utilisateur a expiré.",
      es: 'La sesión de usuario ha caducado.',
      ru: 'Сессия пользователя истекла.',
      ja: 'ユーザーセッションの期限が切れました。',
      ko: '사용자 세션이 만료되었습니다.',
      zh: '用户会话已过期。',
      de: 'Die Benutzersitzung ist abgelaufen.',
      ar: 'انتهت صلاحية جلسة المستخدم.',
      it: 'La sessione utente è scaduta.',
      pt: 'A sessão de usuário expirou.',
      hi: 'उपयोगकर्ता सत्र समाप्त हो गया है।',
      tr: 'Kullanıcı oturumu sona erdi.',
      pl: 'Sesja użytkownika wygasła.',
      id: 'Sesi pengguna telah kedaluwarsa.',
      vi: 'Phiên người dùng đã hết hạn.',
      uk: 'Сесія користувача закінчилася.',
    },
    statusCode: HttpStatusCodes.UNAUTHORIZED_401,
  },
  USER_UPDATE_FAILED: {
    title: {
      en: 'User Update Failed',
      'en-GB': 'User Update Failed',
      fr: "Échec de la mise à jour de l'utilisateur",
      es: 'Error al actualizar el usuario',
      ru: 'Ошибка обновления пользователя',
      ja: 'ユーザーの更新に失敗しました',
      ko: '사용자 정보 업데이트 실패',
      zh: '用户更新失败',
      de: 'Benutzeraktualisierung fehlgeschlagen',
      ar: 'فشل تحديث المستخدم',
      it: 'Aggiornamento utente fallito',
      pt: 'Falha na atualização do usuário',
      hi: 'उपयोगकर्ता अपडेट विफल रहा',
      tr: 'Kullanıcı güncelleme başarısız',
      pl: 'Aktualizacja użytkownika nie powiodła się',
      id: 'Pembaruan Pengguna Gagal',
      vi: 'Cập nhật người dùng thất bại',
      uk: 'Помилка оновлення користувача',
    },
    message: {
      en: 'Failed to update the specified user.',
      'en-GB': 'Failed to update the specified user.',
      fr: "La mise à jour de l'utilisateur a échoué.",
      es: 'No se pudo actualizar el usuario especificado.',
      ru: 'Не удалось обновить указанного пользователя.',
      ja: '指定されたユーザーの更新に失敗しました。',
      ko: '지정된 사용자 정보를 업데이트하지 못했습니다.',
      zh: '无法更新指定的用户。',
      de: 'Der angegebene Benutzer konnte nicht aktualisiert werden.',
      ar: 'فشل في تحديث المستخدم المحدد.',
      it: 'Impossibile aggiornare l’utente specificato.',
      pt: 'Falha ao atualizar o usuário especificado.',
      hi: 'निर्दिष्ट उपयोगकर्ता को अपडेट करने में विफल।',
      tr: 'Belirtilen kullanıcı güncellenemedi.',
      pl: 'Nie udało się zaktualizować określonego użytkownika.',
      id: 'Gagal memperbarui pengguna yang ditentukan.',
      vi: 'Không thể cập nhật người dùng đã chỉ định.',
      uk: 'Не вдалося оновити вказаного користувача.',
    },
    statusCode: HttpStatusCodes.INTERNAL_SERVER_ERROR_500,
  },
  USER_UPDATED_USER_NOT_FOUND: {
    title: {
      en: 'User Updated User Not Found',
      'en-GB': 'User Updated User Not Found',
      fr: 'Utilisateur mis à jour non trouvé',
      es: 'Usuario actualizado no encontrado',
      ru: 'Обновленный пользователь не найден',
      ja: '更新されたユーザーが見つかりません',
      ko: '업데이트된 사용자를 찾을 수 없습니다',
      zh: '未找到更新的用户',
      de: 'Aktualisierter Benutzer nicht gefunden',
      ar: 'المستخدم المحدث غير موجود',
      it: 'Utente aggiornato non trovato',
      pt: 'Usuário atualizado não encontrado',
      hi: 'अपडेट किया गया उपयोगकर्ता नहीं मिला',
      tr: 'Güncellenen kullanıcı bulunamadı',
      pl: 'Nie znaleziono zaktualizowanego użytkownika',
      id: 'Pengguna yang Diperbarui Tidak Ditemukan',
      vi: 'Không tìm thấy người dùng đã cập nhật',
      uk: 'Оновлений користувач не знайдений',
    },
    message: {
      en: 'The updated user was not found.',
      'en-GB': 'The updated user was not found.',
      fr: "L'utilisateur mis à jour n'a pas été trouvé.",
      es: 'El usuario actualizado no se ha encontrado.',
      ru: 'Обновленный пользователь не был найден.',
      ja: '更新されたユーザーが見つかりませんでした。',
      ko: '업데이트된 사용자를 찾을 수 없습니다.',
      zh: '未找到更新的用户。',
      de: 'Der aktualisierte Benutzer wurde nicht gefunden.',
      ar: 'لم يتم العثور على المستخدم المحدث.',
      it: 'L’utente aggiornato non è stato trovato.',
      pt: 'O usuário atualizado não foi encontrado.',
      hi: 'अपडेट किया गया उपयोगकर्ता नहीं मिला।',
      tr: 'Güncellenen kullanıcı bulunamadı.',
      pl: 'Zaktualizowany użytkownik nie został znaleziony.',
      id: 'Pengguna yang diperbarui tidak ditemukan.',
      vi: 'Người dùng đã cập nhật không được tìm thấy.',
      uk: 'Оновлений користувач не був знайдений.',
    },
    statusCode: HttpStatusCodes.NOT_FOUND_404,
  },
  USER_COUNT_FAILED: {
    title: {
      en: 'User Count Failed',
      'en-GB': 'User Count Failed',
      fr: 'Échec du comptage des utilisateurs',
      es: 'Error al contar los usuarios',
      ru: 'Ошибка подсчета пользователей',
      ja: 'ユーザー数のカウントに失敗しました',
      ko: '사용자 수 계산 실패',
      zh: '用户计数失败',
      de: 'Benutzerzählung fehlgeschlagen',
      ar: 'فشل عد المستخدمين',
      it: 'Conteggio utenti fallito',
      pt: 'Falha na contagem de usuários',
      hi: 'उपयोगकर्ता गणना विफल रही',
      tr: 'Kullanıcı sayımı başarısız',
      pl: 'Liczenie użytkowników nie powiodło się',
      id: 'Penghitungan Pengguna Gagal',
      vi: 'Đếm người dùng thất bại',
      uk: 'Помилка підрахунку користувачів',
    },
    message: {
      en: 'Failed to count users.',
      'en-GB': 'Failed to count users.',
      fr: 'Le comptage des utilisateurs a échoué.',
      es: 'No se pudo contar los usuarios.',
      ru: 'Не удалось подсчитать пользователей.',
      ja: 'ユーザーのカウントに失敗しました。',
      ko: '사용자 수를 계산하지 못했습니다.',
      zh: '无法计算用户数。',
      de: 'Die Anzahl der Benutzer konnte nicht ermittelt werden.',
      ar: 'فشل في عد المستخدمين.',
      it: 'Impossibile contare gli utenti.',
      pt: 'Falha ao contar os usuários.',
      hi: 'उपयोगकर्ताओं की गणना करने में विफल।',
      tr: 'Kullanıcılar sayılamadı.',
      pl: 'Nie udało się policzyć użytkowników.',
      id: 'Gagal menghitung pengguna.',
      vi: 'Không thể đếm người dùng.',
      uk: 'Не вдалося підрахувати користувачів.',
    },
    statusCode: HttpStatusCodes.INTERNAL_SERVER_ERROR_500,
  },
  USER_PROVIDER_NOT_FOUND: {
    title: {
      en: 'User Provider Not Found',
      'en-GB': 'User Provider Not Found',
      fr: "Fournisseur d'utilisateur non trouvé",
      es: 'Proveedor de usuario no encontrado',
      ru: 'Провайдер пользователя не найден',
      ja: 'ユーザープロバイダーが見つかりません',
      ko: '사용자 제공자를 찾을 수 없습니다',
      zh: '未找到用户提供者',
      de: 'Benutzeranbieter nicht gefunden',
      ar: 'موفر المستخدم غير موجود',
      it: 'Provider utente non trovato',
      pt: 'Provedor de usuário não encontrado',
      hi: 'उपयोगकर्ता प्रदाता नहीं मिला',
      tr: 'Kullanıcı sağlayıcı bulunamadı',
      pl: 'Nie znaleziono dostawcy użytkownika',
      id: 'Penyedia Pengguna Tidak Ditemukan',
      vi: 'Không tìm thấy nhà cung cấp người dùng',
      uk: 'Провайдер користувача не знайдений',
    },
    message: {
      en: 'The user provider was not found.',
      'en-GB': 'The user provider was not found.',
      fr: "Le fournisseur d'utilisateur n'a pas été trouvé.",
      es: 'El proveedor de usuario no se ha encontrado.',
      ru: 'Провайдер пользователя не был найден.',
      ja: 'ユーザープロバイダーが見つかりませんでした。',
      ko: '사용자 제공자를 찾을 수 없습니다.',
      zh: '未找到用户提供者。',
      de: 'Der Benutzeranbieter wurde nicht gefunden.',
      ar: 'لم يتم العثور على موفر المستخدم.',
      it: 'Il provider dell’utente non è stato trovato.',
      pt: 'O provedor de usuário não foi encontrado.',
      hi: 'उपयोगकर्ता प्रदाता नहीं मिला।',
      tr: 'Kullanıcı sağlayıcı bulunamadı.',
      pl: 'Dostawca użytkownika nie został znaleziony.',
      id: 'Penyedia pengguna tidak ditemukan.',
      vi: 'Nhà cung cấp người dùng không được tìm thấy.',
      uk: 'Провайдер користувача не був знайдений.',
    },
    statusCode: HttpStatusCodes.NOT_FOUND_404,
  },
  USER_PROVIDER_ALREADY_EXISTS: {
    title: {
      en: 'User Provider Already Exists',
      'en-GB': 'User Provider Already Exists',
      fr: "Le fournisseur d'utilisateur existe déjà",
      es: 'El proveedor de usuario ya existe',
      ru: 'Провайдер пользователя уже существует',
      ja: 'ユーザープロバイダーはすでに存在します',
      ko: '사용자 제공자가 이미 존재합니다',
      zh: '用户提供者 selection 已存在',
      de: 'Benutzeranbieter existiert bereits',
      ar: 'موفر المستخدم موجود بالفعل',
      it: 'Il provider dell’utente esiste già',
      pt: 'O provedor de usuário já existe',
      hi: 'उपयोगकर्ता प्रदाता पहले से मौजूद है',
      tr: 'Kullanıcı sağlayıcı zaten mevcut',
      pl: 'Dostawca użytkownika już istnieje',
      id: 'Penyedia Pengguna Sudah Ada',
      vi: 'Nhà cung cấp người dùng đã tồn tại',
      uk: 'Провайдер користувача вже існує',
    },
    message: {
      en: 'The user provider already exists.',
      'en-GB': 'The user provider already exists.',
      fr: "Le fournisseur d'utilisateur existe déjà.",
      es: 'El proveedor de usuario ya existe.',
      ru: 'Провайдер пользователя уже существует.',
      ja: 'ユーザープロバイダーはすでに存在しています。',
      ko: '사용자 제공자가 이미 존재합니다.',
      zh: '该用户提供者已存在。',
      de: 'Der Benutzeranbieter existiert bereits.',
      ar: 'موفر المستخدم موجود بالفعل.',
      it: 'Il provider dell’utente esiste già.',
      pt: 'O provedor de usuário já existe.',
      hi: 'उपयोगकर्ता प्रदाता पहले से मौजूद है।',
      tr: 'Kullanıcı sağlayıcı zaten mevcut.',
      pl: 'Dostawca użytkownika już istnieje.',
      id: 'Penyedia pengguna sudah ada.',
      vi: 'Nhà cung cấp người dùng đã tồn tại.',
      uk: 'Провайдер користувача вже існує.',
    },
    statusCode: HttpStatusCodes.CONFLICT_409,
  },
  USER_PROVIDER_EMAIL_ALREADY_VALIDATED: {
    title: {
      en: 'User provider email already validated',
      'en-GB': 'User provider email already validated',
      fr: "Email du fournisseur d'utilisateur déjà validé",
      es: 'Correo electrónico del proveedor de usuario ya validado',
      ru: 'Email провайдера пользователя уже подтвержден',
      ja: 'ユーザープロバイダーのメールはすでに検証済みです',
      ko: '사용자 제공자 이메일이 이미 확인되었습니다',
      zh: '用户提供者电子邮件已验证',
      de: 'E-Mail des Benutzeranbieters bereits validiert',
      ar: 'تم التحقق من البريد الإلكتروني لموفر المستخدم بالفعل',
      it: 'Email del provider utente già convalidata',
      pt: 'E-mail do provedor de usuário já validado',
      hi: 'उपयोगकर्ता प्रदाता ईमेल पहले से ही सत्यापित है',
      tr: 'Kullanıcı sağlayıcı e-postası zaten doğrulanmış',
      pl: 'Adres e-mail dostawcy użytkownika został już zweryfikowany',
      id: 'Email penyedia pengguna sudah divalidasi',
      vi: 'Email nhà cung cấp người dùng đã được xác thực',
      uk: 'Email провайдера користувача вже підтверджено',
    },
    message: {
      en: 'The user provider email is already validated.',
      'en-GB': 'The user provider email is already validated.',
      fr: "L'email du fournisseur d'utilisateur est déjà validé.",
      es: 'El correo electrónico del proveedor de usuario ya está validado.',
      ru: 'Электронная почта провайдера пользователя уже подтверждена.',
      ja: 'ユーザープロバイダーのメールはすでに検証済みです。',
      ko: '사용자 제공자 이메일이 이미 확인되었습니다.',
      zh: '用户提供者电子邮件已验证。',
      de: 'Die E-Mail-Adresse des Benutzeranbieters ist bereits validiert.',
      ar: 'تم التحقق من البريد الإلكتروني لموفر المستخدم بالفعل.',
      it: 'L’email del provider utente è già stata convalidata.',
      pt: 'O e-mail do provedor de usuário já está validado.',
      hi: 'उपयोगकर्ता प्रदाता ईमेल पहले से ही सत्यापित है।',
      tr: 'Kullanıcı sağlayıcı e-postası zaten doğrulanmış.',
      pl: 'Adres e-mail dostawcy użytkownika jest już zweryfikowany.',
      id: 'Email penyedia pengguna sudah divalidasi.',
      vi: 'Email nhà cung cấp người dùng đã được xác thực.',
      uk: 'Електронна пошта провайдера користувача вже підтверджена.',
    },
    statusCode: HttpStatusCodes.CONFLICT_409,
  },
  USER_PREVIOUS_PASSWORD_NOT_PROVIDED: {
    title: {
      en: 'User previous password not provided',
      fr: "Mot de passe précédent de l'utilisateur non fourni",
      es: 'Contraseña anterior de usuario no proporcionada',
    },
    message: {
      en: 'The user previous password was not provided.',
      fr: "Le mot de passe précédent de l'utilisateur n'a pas été fourni.",
      es: 'La contraseña anterior de usuario no fue proporcionada.',
    },
    statusCode: HttpStatusCodes.BAD_REQUEST_400,
  },
  USER_PASSWORD_NOT_DEFINED: {
    title: {
      en: 'User password not defined',
      fr: "Mot de passe de l'utilisateur non défini",
      es: 'Contraseña de usuario no definida',
    },
    message: {
      en: 'The user password was not defined.',
      fr: "Le mot de passe de l'utilisateur n'a pas été défini.",
      es: 'La contraseña de usuario no se ha definido.',
    },
    statusCode: HttpStatusCodes.BAD_REQUEST_400,
  },
  USER_PROVIDER_SECRET_NOT_DEFINED: {
    title: {
      en: 'User Provider Secret Not Defined',
      'en-GB': 'User Provider Secret Not Defined',
      fr: "Secret du fournisseur d'utilisateur non défini",
      es: 'Secreto del proveedor de usuario no definido',
      ru: 'Секрет провайдера пользователя не определен',
      ja: 'ユーザープロバイダーのシークレットが定義されていません',
      ko: '사용자 제공자 비밀이 정의되지 않았습니다',
      zh: '未定义用户提供者密钥',
      de: 'Geheimnis des Benutzeranbieters nicht definiert',
      ar: 'سر موفر المستخدم غير محدد',
      it: 'Segreto del provider utente non definito',
      pt: 'Segredo do provedor de usuário não definido',
      hi: 'उपयोगकर्ता प्रदाता गुप्त परिभाषित नहीं है',
      tr: 'Kullanıcı sağlayıcı gizli anahtarı tanımlanmamış',
      pl: 'Klucz dostawcy użytkownika nie został zdefiniowany',
      id: 'Rahasia Penyedia Pengguna Tidak Ditentukan',
      vi: 'Bí mật nhà cung cấp người dùng chưa được định nghĩa',
      uk: 'Секрет провайдера користувача не визначений',
    },
    message: {
      en: 'The user provider secret was not defined.',
      'en-GB': 'The user provider secret was not provided.',
      fr: "Le secret du fournisseur d'utilisateur n'a pas été défini.",
      es: 'El secreto del proveedor de usuario no se ha definido.',
      ru: 'Секрет провайдера пользователя не был определен.',
      ja: 'ユーザープロバイダーのシークレットが定義されていませんでした。',
      ko: '사용자 제공자 비밀이 정의되지 않았습니다.',
      zh: '未定义用户提供者密钥。',
      de: 'Das Geheimnis des Benutzeranbieters wurde nicht definiert.',
      ar: 'لم يتم تحديد سر موفر المستخدم.',
      it: 'Il segreto del provider dell’utente non è stato definito.',
      pt: 'O segredo do provedor de usuário não foi definido.',
      hi: 'उपयोगकर्ता प्रदाता गुप्त परिभाषित नहीं था।',
      tr: 'Kullanıcı sağlayıcı gizli anahtarı tanımlanmamış.',
      pl: 'Klucz dostawcy użytkownika nie został zdefiniowany.',
      id: 'Rahasia penyedia pengguna tidak ditentukan.',
      vi: 'Bí mật nhà cung cấp người dùng chưa được định nghĩa.',
      uk: 'Секрет провайдера користувача не був визначений.',
    },
    statusCode: HttpStatusCodes.BAD_REQUEST_400,
  },
  USER_PROVIDER_SECRET_NOT_VALID: {
    title: {
      en: 'User Provider Secret Not Valid',
      'en-GB': 'User Provider Secret Not Valid',
      fr: "Secret du fournisseur d'utilisateur non valide",
      es: 'Secreto del proveedor de usuario no válido',
      ru: 'Секрет провайдера пользователя недействителен',
      ja: 'ユーザープロバイダーのシークレットが無効です',
      ko: '사용자 제공자 비밀이 유효하지 않습니다',
      zh: '用户提供者密钥无效',
      de: 'Geheimnis des Benutzeranbieters ungültig',
      ar: 'سر موفر المستخدم غير صالح',
      it: 'Segreto del provider utente non valido',
      pt: 'Segredo do provedor de usuário inválido',
      hi: 'उपयोगकर्ता प्रदाता गुप्त मान्य नहीं है',
      tr: 'Kullanıcı sağlayıcı gizli anahtarı geçerli değil',
      pl: 'Klucz dostawcy użytkownika jest nieprawidłowy',
      id: 'Rahasia Penyedia Pengguna Tidak Valid',
      vi: 'Bí mật nhà cung cấp người dùng không hợp lệ',
      uk: 'Секрет провайдера користувача недійсний',
    },
    message: {
      en: 'The user provider secret was not valid.',
      'en-GB': 'The user provider secret was not valid.',
      fr: "Le secret du fournisseur d'utilisateur n'a pas été valide.",
      es: 'El secreto del proveedor de usuario no es válido.',
      ru: 'Секрет провайдера пользователя недействителен.',
      ja: 'ユーザープロバイダーのシークレットが有効ではありませんでした。',
      ko: '사용자 제공자 비밀이 유효하지 않습니다.',
      zh: '用户提供者密钥无效。',
      de: 'Das Geheimnis des Benutzeranbieters war nicht gültig.',
      ar: 'سر موفر المستخدم لم يكن صالحاً.',
      it: 'Il segreto del provider dell’utente non è valido.',
      pt: 'O segredo do provedor de usuário não era válido.',
      hi: 'उपयोगकर्ता प्रदाता गुप्त मान्य नहीं था।',
      tr: 'Kullanıcı sağlayıcı gizli anahtarı geçerli değildi.',
      pl: 'Klucz dostawcy użytkownika był nieprawidłowy.',
      id: 'Rahasia penyedia pengguna tidak valid.',
      vi: 'Bí mật nhà cung cấp người dùng không hợp lệ.',
      uk: 'Секрет провайдера користувача не був дійсним.',
    },
    statusCode: HttpStatusCodes.NOT_FOUND_404,
  },
  USER_ORGANIZATION_MEMBER_MISSING: {
    title: {
      en: 'User Not Organization Member',
      'en-GB': 'User Not Organization Member',
      fr: "Utilisateur non membre de l'organisation",
      es: 'Usuario no miembro de la organización',
      ru: 'Пользователь не является членом организации',
      ja: 'ユーザーは組織のメンバーではありません',
      ko: '사용자가 조직 구성원이 아닙니다',
      zh: '用户不是组织成员',
      de: 'Benutzer kein Organisationsmitglied',
      ar: 'المستخدم ليس عضواً في المنظمة',
      it: 'Utente non membro dell’organizzazione',
      pt: 'Usuário não é membro da organização',
      hi: 'उपयोगकर्ता संगठन का सदस्य नहीं है',
      tr: 'Kullanıcı organizasyon üyesi değil',
      pl: 'Użytkownik nie jest członkiem organizacji',
      id: 'Pengguna Bukan Anggota Organisasi',
      vi: 'Người dùng không phải là thành viên tổ chức',
      uk: 'Користувач не є членом організації',
    },
    message: {
      en: 'The user is not a member of the organization.',
      'en-GB': 'The user is not a member of the organization.',
      fr: "L'utilisateur n'est pas membre de l'organisation.",
      es: 'El usuario no es miembro de la organización.',
      ru: 'Пользователь не является членом организации.',
      ja: 'ユーザーは組織のメンバーではありません。',
      ko: '사용자가 조직의 구성원이 아닙니다.',
      zh: '用户不是该组织的成员。',
      de: 'Der Benutzer ist kein Mitglied der Organisation.',
      ar: 'المستخدم ليس عضواً في المنظمة.',
      it: 'L’utente non è un membro dell’organizzazione.',
      pt: 'O usuário não é um membro da organização.',
      hi: 'उपयोगकर्ता संगठन का सदस्य नहीं है।',
      tr: 'Kullanıcı organizasyonun bir üyesi değil.',
      pl: 'Użytkownik nie jest członkiem organizacji.',
      id: 'Pengguna bukan anggota organisasi.',
      vi: 'Người dùng không phải là thành viên của tổ chức.',
      uk: 'Користувач не є членом організації.',
    },
    statusCode: HttpStatusCodes.FORBIDDEN_403,
  },
  USER_ORGANIZATION_ADMIN_MISSING: {
    title: {
      en: 'User Not Organization Admin',
      'en-GB': 'User Not Organization Admin',
      fr: "Utilisateur non administrateur de l'organisation",
      es: 'Usuario no administrador de la organización',
      ru: 'Пользователь не является администратором организации',
      ja: 'ユーザーは組織の管理者ではありません',
      ko: '사용자가 조직 관리자가 아닙니다',
      zh: '用户不是组织管理员',
      de: 'Benutzer kein Organisationsadministrator',
      ar: 'المستخدم ليس مسؤولاً في المنظمة',
      it: 'Utente non amministratore dell’organizzazione',
      pt: 'Usuário não é administrador da organização',
      hi: 'उपयोगकर्ता संगठन प्रशासक नहीं है',
      tr: 'Kullanıcı organizasyon yöneticisi değil',
      pl: 'Użytkownik nie jest administratorem organizacji',
      id: 'Pengguna Bukan Admin Organisasi',
      vi: 'Người dùng không phải là quản trị viên tổ chức',
      uk: 'Користувач не є адміністратором організації',
    },
    message: {
      en: 'The user is not an admin of the organization.',
      'en-GB': 'The user is not an admin of the organization.',
      fr: "L'utilisateur n'est pas administrateur de l'organisation.",
      es: 'El usuario no es administrador de la organización.',
      ru: 'Пользователь не является администратором организации.',
      ja: 'ユーザーは組織の管理者ではありません。',
      ko: '사용자가 조직의 관리자가 아닙니다.',
      zh: '用户不是该组织的管理员。',
      de: 'Der Benutzer ist kein Administrator der Organisation.',
      ar: 'المستخدم ليس مسؤولاً في المنظمة.',
      it: 'L’utente non è un amministratore dell’organizzazione.',
      pt: 'O usuário não é um administrador da organização.',
      hi: 'उपयोगकर्ता संगठन का प्रशासक नहीं है।',
      tr: 'Kullanıcı organizasyonun bir yöneticisi değil.',
      pl: 'Użytkownik nie jest administratorem organizacji.',
      id: 'Pengguna bukan admin organisasi.',
      vi: 'Người dùng không phải là quản trị viên của tổ chức.',
      uk: 'Користувач не є адміністратором організації.',
    },
    statusCode: HttpStatusCodes.FORBIDDEN_403,
  },
  USER_NOT_AUTHENTICATED: {
    title: {
      en: 'User not authenticated',
      'en-GB': 'User not authenticated',
      fr: 'Utilisateur non authentifié',
      es: 'Usuario no autenticado',
      ru: 'Пользователь не аутентифицирован',
      ja: 'ユーザーが認証されていません',
      ko: '사용자가 인증되지 않았습니다',
      zh: '用户未认证',
      de: 'Benutzer nicht authentifiziert',
      ar: 'المستخدم غير مصادق عليه',
      it: 'Utente non autenticato',
      pt: 'Usuário não autenticado',
      hi: 'उपयोगकर्ता प्रमाणित नहीं है',
      tr: 'Kullanıcı kimliği doğrulanmadı',
      pl: 'Użytkownik nie jest uwierzytelniony',
      id: 'Pengguna tidak terautentikasi',
      vi: 'Người dùng chưa được xác thực',
      uk: 'Користувач не автентифікований',
    },
    message: {
      en: 'The user is not authenticated.',
      'en-GB': 'The user is not authenticated.',
      fr: "L'utilisateur n'est pas authentifié.",
      es: 'El usuario no está autenticado.',
      ru: 'Пользователь не аутентифицирован.',
      ja: 'ユーザーが認証されていません。',
      ko: '사용자가 인증되지 않았습니다.',
      zh: '用户未通过身份验证。',
      de: 'Der Benutzer ist nicht authentifiziert.',
      ar: 'المستخدم غير مصادق عليه.',
      it: 'L’utente non è autenticato.',
      pt: 'O usuário não está autenticado.',
      hi: 'उपयोगकर्ता प्रमाणित नहीं है।',
      tr: 'Kullanıcı kimliği doğrulanmadı.',
      pl: 'Użytkownik nie jest uwierzytelniony.',
      id: 'Pengguna tidak terautentikasi.',
      vi: 'Người dùng chưa được xác thực.',
      uk: 'Користувач не автентифікований.',
    },
    statusCode: HttpStatusCodes.UNAUTHORIZED_401,
  },
  USER_ALREADY_EXISTS: {
    title: {
      en: 'User Already Exists',
      'en-GB': 'User Already Exists',
      fr: 'Utilisateur existe déjà',
      es: 'El usuario ya existe',
      ru: 'Пользователь уже существует',
      ja: 'ユーザーはすでに存在します',
      ko: '사용자가 이미 존재합니다',
      zh: '用户已存在',
      de: 'Benutzer existiert bereits',
      ar: 'المستخدم موجود بالفعل',
      it: 'L’utente esiste già',
      pt: 'O usuário já existe',
      hi: 'उपयोगकर्ता पहले से मौजूद है',
      tr: 'Kullanıcı zaten mevcut',
      pl: 'Użytkownik już istnieje',
      id: 'Pengguna Sudah Ada',
      vi: 'Người dùng đã tồn tại',
      uk: 'Користувач вже існує',
    },
    message: {
      en: 'A user with this email already exists in our system.',
      'en-GB': 'A user with this email already exists in our system.',
      fr: 'Un utilisateur avec cet email existe déjà dans notre système.',
      es: 'Un usuario con este correo electrónico ya existe en nuestro sistema.',
      ru: 'Пользователь с таким email уже существует в нашей системе.',
      ja: 'このメールアドレスを持つユーザーはすでにシステムに存在します。',
      ko: '이 이메일을 사용하는 사용자가 이미 시스템에 존재합니다.',
      zh: '系统中已存在使用此电子邮件的用户。',
      de: 'Ein Benutzer mit dieser E-Mail existiert bereits in unserem System.',
      ar: 'يوجد مستخدم بهذا البريد الإلكتروني موجود بالفعل في نظامنا.',
      it: 'Un utente con questa email esiste già nel nostro sistema.',
      pt: 'Um usuário com este e-mail já existe em nosso sistema.',
      hi: 'इस ईमेल वाला उपयोगकर्ता हमारे सिस्टम में पहले से मौजूद है।',
      tr: 'Bu e-postaya sahip bir kullanıcı sistemimizde zaten mevcut.',
      pl: 'Użytkownik z tym adresem e-mail już istnieje w naszym systemie.',
      id: 'Pengguna dengan email ini sudah ada di sistem kami.',
      vi: 'Người dùng có email này đã tồn tại trong hệ thống của chúng tôi.',
      uk: 'Користувач з таким email вже існує в нашій системі.',
    },
    statusCode: HttpStatusCodes.CONFLICT_409,
  },
} satisfies Record<string, ErrorCode>;
