import { type Dictionary, t } from 'intlayer';

const discussionsAdminPageContent = {
  key: 'discussion-admin-detail',
  content: {
    title: t({
      en: 'Discussions Management',
      fr: 'Gestion des discussions',
      es: 'Gestión de discusiones',
      'en-GB': 'Discussions Management',
      de: 'Diskussionsverwaltung',
      ja: 'ディスカッション管理',
      ko: '토론 관리',
      zh: '讨论管理',
      it: 'Gestione discussioni',
      pt: 'Gestão de discussões',
      hi: 'चर्चा प्रबंधन',
      ar: 'إدارة المناقشات',
      ru: 'Управление обсуждениями',
      tr: 'Tartışma yönetimi',
    }),

    tableHeaders: {
      id: 'ID',
      userName: t({
        en: 'User',
        fr: 'Utilisateur',
        es: 'Usuario',
        'en-GB': 'User',
        de: 'Benutzer',
        ja: 'ユーザー',
        ko: '사용자',
        zh: '用户',
        it: 'Utente',
        pt: 'Usuário',
        hi: 'उपयोगकर्ता',
        ar: 'المستخدم',
        ru: 'Пользователь',
        tr: 'Kullanıcı',
      }),
      numberOfMessages: t({
        en: 'Messages',
        fr: 'Messages',
        es: 'Mensajes',
        'en-GB': 'Messages',
        de: 'Nachrichten',
        ja: 'メッセージ',
        ko: '메시지',
        zh: '消息',
        it: 'Messaggi',
        pt: 'Mensagens',
        hi: 'संदेश',
        ar: 'الرسائل',
        ru: 'Сообщения',
        tr: 'Mesajlar',
      }),
      createdAt: t({
        en: 'Created At',
        fr: 'Créé le',
        es: 'Creado en',
        'en-GB': 'Created At',
        de: 'Erstellt am',
        ja: '作成日',
        ko: '생성일',
        zh: '创建时间',
        it: 'Creato il',
        pt: 'Criado em',
        hi: 'बनाया गया',
        ar: 'تم الإنشاء في',
        ru: 'Создано',
        tr: 'Oluşturulma',
      }),
      updatedAt: t({
        en: 'Updated At',
        fr: 'Mis à jour le',
        es: 'Actualizado en',
        'en-GB': 'Updated At',
        de: 'Aktualisiert am',
        ja: '更新日',
        ko: '업데이트일',
        zh: '更新时间',
        it: 'Aggiornato il',
        pt: 'Atualizado em',
        hi: 'अपडेट किया गया',
        ar: 'تم التحديث في',
        ru: 'Обновлено',
        tr: 'Güncellendi',
      }),
    },
    noData: t({
      en: 'N/A',
      fr: 'N/A',
      es: 'N/A',
      'en-GB': 'N/A',
      de: 'N/A',
      ja: 'なし',
      ko: '없음',
      zh: '无',
      it: 'N/A',
      pt: 'N/A',
      hi: 'N/A',
      ar: 'غير متوفر',
      ru: 'Н/Д',
      tr: 'Yok',
    }),
    errorMessages: {
      loadingError: t({
        en: 'Error loading discussions',
        fr: 'Erreur lors du chargement des discussions',
        es: 'Error al cargar discusiones',
        'en-GB': 'Error loading discussions',
        de: 'Fehler beim Laden der Diskussionen',
        ja: 'ディスカッションの読み込みエラー',
        ko: '토론 로딩 오류',
        zh: '加载讨论时出错',
        it: 'Errore nel caricamento delle discussioni',
        pt: 'Erro ao carregar discussões',
        hi: 'चर्चाओं को लोड करने में त्रुटि',
        ar: 'خطأ في تحميل المناقشات',
        ru: 'Ошибка загрузки обсуждений',
        tr: 'Tartışmalar yüklenirken hata oluştu',
      }),
    },
    searchPlaceholder: t({
      en: 'Search discussions...',
      fr: 'Rechercher des discussions...',
      es: 'Buscar discusiones...',
      'en-GB': 'Search discussions...',
      de: 'Diskussionen suchen...',
      ja: 'ディスカッションを検索...',
      ko: '토론 검색...',
      zh: '搜索讨论...',
      it: 'Cerca discussioni...',
      pt: 'Buscar discussões...',
      hi: 'चर्चाओं की खोज करें...',
      ar: 'ابحث عن المناقشات...',
      ru: 'Поиск обсуждений...',
      tr: 'Tartışmaları ara...',
    }),
    noDiscussionFound: t({
      en: 'Discussion not found',
      fr: 'Discussion non trouvée',
      es: 'Discusión no encontrada',
      'en-GB': 'Discussion not found',
      de: 'Diskussion nicht gefunden',
      ja: 'ディスカッションが見つかりません',
      ko: '토론을 찾을 수 없습니다',
      zh: '找不到讨论',
      it: 'Discussione non trovata',
      pt: 'Discussão não encontrada',
      hi: 'चर्चा नहीं खोजी गई',
      ar: 'المناقشة غير موجودة',
      ru: 'Обсуждение не найдено',
      tr: 'Tartışma bulunamadı',
    }),
    modalTitle: t({
      en: 'Discussion Details - ID: {{id}}',
      fr: 'Détails de la discussion - ID: {{id}}',
      es: 'Detalles de la discusión - ID: {{id}}',
      'en-GB': 'Discussion Details - ID: {{id}}',
      de: 'Diskussion Details - ID: {{id}}',
      ja: 'ディスカッションの詳細 - ID: {{id}}',
      ko: '토론 세부 정보 - ID: {{id}}',
      zh: '讨论详细信息 - ID: {{id}}',
      it: 'Dettagli discussione - ID: {{id}}',
      pt: 'Detalhes da discussão - ID: {{id}}',
      hi: 'चर्चा की विवरण - ID: {{id}}',
      ar: 'تفاصيل المناقشة - ID: {{id}}',
      ru: 'Подробности обсуждения - ID: {{id}}',
      tr: 'Tartışma ayrıntıları - ID: {{id}}',
    }),
  },
} satisfies Dictionary;

export default discussionsAdminPageContent;
