import { type Dictionary, t } from 'intlayer';

const affiliateOnboardingContent = {
  key: 'affiliate-onboarding',
  content: {
    failedToLoadOnboardingPlease: t({
      en: 'Failed to load onboarding. Please try again.',
      ru: 'Не удалось загрузить онбординг. Пожалуйста, попробуйте еще раз.',
      ja: 'オンボーディングの読み込みに失敗しました。もう一度お試しください。',
      fr: "Échec du chargement de l'intégration. Veuillez réessayer.",
      ko: '온보딩을 로드하지 못했습니다. 다시 시도해 주세요.',
      zh: '加载入职培训失败。请重试。',
      es: 'Error al cargar la integración. Por favor, inténtelo de nuevo.',
      de: 'Fehler beim Laden des Onboardings. Bitte versuchen Sie es erneut.',
      ar: 'فشل تحميل الإعداد. يرجى المحاولة مرة أخرى.',
      it: "Impossibile caricare l'onboarding. Riprova.",
      'en-GB': 'Failed to load onboarding. Please try again.',
      pt: 'Falha ao carregar a integração. Por favor, tente novamente.',
      hi: 'ऑनबोर्डिंग लोड करने में विफल। कृपया पुनः प्रयास करें।',
      tr: 'Katılım yüklenemedi. Lütfen tekrar deneyin.',
      pl: 'Nie udało się załadować onboardingu. Spróbuj ponownie.',
      id: 'Gagal memuat orientasi. Silakan coba lagi.',
      vi: 'Không thể tải hướng dẫn. Vui lòng thử lại.',
      uk: 'Не вдалося завантажити онбординг. Будь ласка, спробуйте ще раз.',
    }),

    completeYourPayoutSetup: t({
      en: 'Complete your payout setup',
      ru: 'Завершите настройку выплат',
      ja: '支払い設定を完了する',
      fr: 'Terminez la configuration de vos paiements',
      ko: '지급 설정 완료',
      zh: '完成您的付款设置',
      es: 'Complete la configuración de sus pagos',
      de: 'Schließen Sie Ihre Auszahlungseinrichtung ab',
      ar: 'أكمل إعداد المدفوعات الخاص بك',
      it: 'Completa la configurazione dei pagamenti',
      'en-GB': 'Complete your payout setup',
      pt: 'Conclua a configuração do seu pagamento',
      hi: 'अपना भुगतान सेटअप पूरा करें',
      tr: 'Ödeme kurulumunuzu tamamlayın',
      pl: 'Dokończ konfigurację wypłat',
      id: 'Selesaikan pengaturan pembayaran Anda',
      vi: 'Hoàn tất thiết lập thanh toán của bạn',
      uk: 'Завершіть налаштування виплат',
    }),

    install: t({
      en: 'Install',
      ru: 'Установить',
      ja: 'インストール',
      fr: 'Installer',
      ko: '설치',
      zh: '安装',
      es: 'Instalar',
      de: 'Installieren',
      ar: 'تثبيت',
      it: 'Installa',
      'en-GB': 'Install',
      pt: 'Instalar',
      hi: 'इंस्टॉल करें',
      tr: 'Yükle',
      pl: 'Zainstaluj',
      id: 'Instal',
      vi: 'Cài đặt',
      uk: 'Встановити',
    }),

    toEnableTheEmbeddedOnboarding: t({
      en: 'to enable the embedded onboarding form directly on this page, or',
      ru: 'чтобы включить встроенную форму онбординга прямо на этой странице, или',
      ja: 'このページに埋め込みオンボーディングフォームを直接有効にするには、または',
      fr: "pour activer le formulaire d'intégration intégré directement sur cette page, ou",
      ko: '이 페이지에 포함된 온보딩 양식을 직접 활성화하려면, 또는',
      zh: '以直接在此页面上启用嵌入式入职表单，或者',
      es: 'para habilitar el formulario de integración incrustado directamente en esta página, o',
      de: 'um das eingebettete Onboarding-Formular direkt auf dieser Seite zu aktivieren, oder',
      ar: 'لتمكين نموذج الإعداد المضمن مباشرة في هذه الصفحة، أو',
      it: 'per abilitare il modulo di onboarding incorporato direttamente in questa pagina, o',
      'en-GB':
        'to enable the embedded onboarding form directly on this page, or',
      pt: 'para ativar o formulário de integração incorporado diretamente nesta página, ou',
      hi: 'इस पृष्ठ पर सीधे एम्बेडेड ऑनबोर्डिंग फॉर्म को सक्षम करने के लिए, या',
      tr: 'bu sayfada doğrudan gömülü katılım formunu etkinleştirmek için veya',
      pl: 'aby włączyć osadzony formularz onboardingu bezpośrednio na tej stronie, lub',
      id: 'untuk mengaktifkan formulir orientasi tersemat langsung di halaman ini, atau',
      vi: 'để bật biểu mẫu hướng dẫn được nhúng trực tiếp trên trang này, hoặc',
      uk: 'щоб увімкнути вбудовану форму онбордингу безпосередньо на цій сторінці, або',
    }),

    completeOnboardingOnStripe: t({
      en: 'complete onboarding on Stripe',
      ru: 'завершить онбординг в Stripe',
      ja: 'Stripeでのオンボーディングを完了する',
      fr: "terminer l'intégration sur Stripe",
      ko: 'Stripe에서 온보딩 완료',
      zh: '在Stripe上完成入职',
      es: 'completar la integración en Stripe',
      de: 'Onboarding auf Stripe abschließen',
      ar: 'إكمال الإعداد على Stripe',
      it: "completa l'onboarding su Stripe",
      'en-GB': 'complete onboarding on Stripe',
      pt: 'concluir a integração no Stripe',
      hi: 'Stripe पर ऑनबोर्डिंग पूरा करें',
      tr: 'Stripe üzerinde katılımı tamamla',
      pl: 'zakończ onboarding na Stripe',
      id: 'selesaikan orientasi di Stripe',
      vi: 'hoàn tất hướng dẫn trên Stripe',
      uk: 'завершити онбординг у Stripe',
    }),

    onceCompletedReturnHereAnd: t({
      en: 'Once completed, return here and refresh the page.',
      ru: 'После завершения вернитесь сюда и обновите страницу.',
      ja: '完了したら、ここに戻ってページを更新してください。',
      fr: 'Une fois terminé, revenez ici et actualisez la page.',
      ko: '완료되면 여기로 돌아와서 페이지를 새로 고치십시오.',
      zh: '完成后，请返回此处并刷新页面。',
      es: 'Una vez completado, regrese aquí y actualice la página.',
      de: 'Sobald abgeschlossen, kehren Sie hierher zurück und aktualisieren Sie die Seite.',
      ar: 'بمجرد الانتهاء، عد إلى هنا وقم بتحديث الصفحة.',
      it: 'Una volta completato, torna qui e aggiorna la pagina.',
      'en-GB': 'Once completed, return here and refresh the page.',
      pt: 'Depois de concluído, retorne aqui e atualize a página.',
      hi: 'एक बार पूरा हो जाने पर, यहां वापस आएं और पृष्ठ को रीफ्रेश करें।',
      tr: 'Tamamlandığında buraya dönün ve sayfayı yenileyin.',
      pl: 'Po zakończeniu, wróć tutaj i odśwież stronę.',
      id: 'Setelah selesai, kembali ke sini dan segarkan halaman.',
      vi: 'Khi hoàn tất, hãy quay lại đây và làm mới trang.',
      uk: 'Після завершення поверніться сюди та оновіть сторінку.',
    }),
  },
} satisfies Dictionary;

export default affiliateOnboardingContent;
