import { type Dictionary, t } from 'intlayer';

const sendInvitationFormContent = {
  key: 'send-invitation-form',
  content: {
    failedToSendInvitationPlease: t({
      en: 'Failed to send invitation. Please try again.',
      ru: 'Не удалось отправить приглашение. Пожалуйста, попробуйте еще раз.',
      ja: '招待状の送信に失敗しました。もう一度お試しください。',
      fr: "Échec de l'envoi de l'invitation. Veuillez réessayer.",
      ko: '초대장을 보내지 못했습니다. 다시 시도해 주세요.',
      zh: '发送邀请失败。请重试。',
      es: 'Error al enviar la invitación. Por favor, inténtelo de nuevo.',
      de: 'Fehler beim Senden der Einladung. Bitte versuchen Sie es erneut.',
      ar: 'فشل في إرسال الدعوة. يرجى المحاولة مرة أخرى.',
      it: "Impossibile inviare l'invito. Riprova.",
      'en-GB': 'Failed to send invitation. Please try again.',
      pt: 'Falha ao enviar o convite. Por favor, tente novamente.',
      hi: 'निमंत्रण भेजने में विफल। कृपया पुनः प्रयास करें।',
      tr: 'Davetiye gönderilemedi. Lütfen tekrar deneyin.',
      pl: 'Nie udało się wysłać zaproszenia. Spróbuj ponownie.',
      id: 'Gagal mengirim undangan. Silakan coba lagi.',
      vi: 'Không thể gửi lời mời. Vui lòng thử lại.',
      uk: 'Не вдалося надіслати запрошення. Будь ласка, спробуйте ще раз.',
    }),

    emailAddress: t({
      en: 'Email address',
      ru: 'Адрес электронной почты',
      ja: 'メールアドレス',
      fr: 'Adresse e-mail',
      ko: '이메일 주소',
      zh: '电子邮件地址',
      es: 'Dirección de correo electrónico',
      de: 'E-Mail-Adresse',
      ar: 'عنوان البريد الإلكتروني',
      it: 'Indirizzo email',
      'en-GB': 'Email address',
      pt: 'Endereço de e-mail',
      hi: 'ईमेल पता',
      tr: 'E-posta adresi',
      pl: 'Adres e-mail',
      id: 'Alamat email',
      vi: 'Địa chỉ email',
      uk: 'Адреса електронної пошти',
    }),

    commissionRate: t({
      en: 'Commission rate (%)',
      ru: 'Ставка комиссии (%)',
      ja: 'コミッション率 (%)',
      fr: 'Taux de commission (%)',
      ko: '수수료율 (%)',
      zh: '佣金率 (%)',
      es: 'Tasa de comisión (%)',
      de: 'Provisionssatz (%)',
      ar: 'معدل العمولة (%)',
      it: 'Tasso di commissione (%)',
      'en-GB': 'Commission rate (%)',
      pt: 'Taxa de comissão (%)',
      hi: 'कमीशन दर (%)',
      tr: 'Komisyon oranı (%)',
      pl: 'Stawka prowizji (%)',
      id: 'Tingkat komisi (%)',
      vi: 'Tỷ lệ hoa hồng (%)',
      uk: 'Ставка комісії (%)',
    }),

    sending: t({
      en: 'Sending…',
      ru: 'Отправка…',
      ja: '送信中…',
      fr: 'Envoi en cours…',
      ko: '전송 중…',
      zh: '发送中…',
      es: 'Enviando…',
      de: 'Senden…',
      ar: 'جاري الإرسال…',
      it: 'Invio…',
      'en-GB': 'Sending…',
      pt: 'Enviando…',
      hi: 'भेजा जा रहा है…',
      tr: 'Gönderiliyor…',
      pl: 'Wysyłanie…',
      id: 'Mengirim…',
      vi: 'Đang gửi…',
      uk: 'Відправлення…',
    }),

    sendInvitation: t({
      en: 'Send Invitation',
      ru: 'Отправить приглашение',
      ja: '招待状を送信',
      fr: "Envoyer l'invitation",
      ko: '초대장 보내기',
      zh: '发送邀请',
      es: 'Enviar invitación',
      de: 'Einladung senden',
      ar: 'إرسال دعوة',
      it: 'Invia invito',
      'en-GB': 'Send Invitation',
      pt: 'Enviar convite',
      hi: 'निमंत्रण भेजें',
      tr: 'Davetiye Gönder',
      pl: 'Wyślij zaproszenie',
      id: 'Kirim Undangan',
      vi: 'Gửi lời mời',
      uk: 'Надіслати запрошення',
    }),

    sendInvitationLabel: t({
      en: 'Send invitation to join the affiliate program',
      ru: 'Отправить приглашение присоединиться к партнерской программе',
      ja: 'アフィリエイトプログラムへの参加招待を送信する',
      fr: "Envoyer une invitation à rejoindre le programme d'affiliation",
      ko: '제휴 프로그램 가입 초대장 보내기',
      zh: '发送加入联盟计划的邀请',
      es: 'Enviar invitación para unirse al programa de afiliados',
      de: 'Einladung zur Teilnahme am Affiliate-Programm senden',
      ar: 'إرسال دعوة للانضمام إلى برنامج الشركاء التابعين',
      it: 'Invia invito a unirsi al programma di affiliazione',
      'en-GB': 'Send invitation to join the affiliate program',
      pt: 'Enviar convite para participar do programa de afiliados',
      hi: 'सहबद्ध कार्यक्रम में शामिल होने के लिए निमंत्रण भेजें',
      tr: 'Ortaklık programına katılma daveti gönder',
      pl: 'Wyślij zaproszenie do dołączenia do programu partnerskiego',
      id: 'Kirim undangan untuk bergabung dengan program afiliasi',
      vi: 'Gửi lời mời tham gia chương trình tiếp thị liên kết',
      uk: 'Надіслати запрошення приєднатися до партнерської програми',
    }),

    partnerEmailPlaceholder: 'partner@example.com',
  },
} satisfies Dictionary;

export default sendInvitationFormContent;
