import { t, type Dictionary } from 'intlayer';

const organizationMembersFormContent = {
  key: 'organization-members-form',

  content: {
    title: t({
      en: 'Members',
      es: 'Miembros',
      fr: 'Membres',
      de: 'Mitglieder',
      ja: 'メンバー',
      ko: '회원',
      zh: '会员',
      it: 'Membri',
      pt: 'Membros',
      hi: 'सदस्य',
      ar: 'أعضاء',
      ru: 'Участники',
      'en-GB': 'Members',
    }),
    description: t({
      en: 'Manage the members that have access and can edit your organization.',
      es: 'Administra los miembros que tienen acceso y pueden editar tu organización.',
      fr: 'Gérez les membres qui ont accès et peuvent modifier votre organisation.',
      de: 'Verwalten Sie die Mitglieder, die Zugriff haben und Ihre Organisation bearbeiten können.',
      ja: '組織にアクセスし、編集できるメンバーを管理します。',
      ko: '조직에 접근하고 편집할 수 있는 구성원을 관리합니다.',
      zh: '管理有权访问和可以编辑您的组织的成员。',
      it: 'Gestisci i membri che hanno accesso e possono modificare la tua organizzazione.',
      pt: 'Gerencie os membros que têm acesso e podem editar sua organização.',
      hi: 'उन सदस्यों का प्रबंधन करें जिनके पास आपकी संगठन में पहुँच है और संपादित कर सकते हैं।',
      ar: 'إدارة الأعضاء الذين لديهم حق الوصول ويمكنهم تعديل مؤسستك.',
      ru: 'Управляйте членами, которые имеют доступ и могут редактировать вашу организацию.',
      'en-GB':
        'Manage the members that have access and can edit your organization.',
    }),
    deleteMemberButton: {
      label: t({
        en: 'Delete',
        es: 'Eliminar',
        fr: 'Supprimer',
        de: 'Löschen',
        ja: '削除',
        ko: '삭제',
        zh: '删除',
        it: 'Elimina',
        pt: 'Excluir',
        hi: 'हटाएं',
        ar: 'حذف',
        ru: 'Удалить',
        'en-GB': 'Delete',
      }),
    },
    noMembers: t({
      en: 'No members',
      es: 'Sin miembros',
      fr: 'Aucun membre',
      de: 'Keine Mitglieder',
      ja: 'メンバーはいません',
      ko: '회원이 없습니다',
      zh: '没有成员',
      it: 'Nessun membro',
      pt: 'Sem membros',
      hi: 'कोई सदस्य नहीं',
      ar: 'لا يوجد أعضاء',
      ru: 'Нет участников',
      'en-GB': 'No members',
    }),

    newMemberEmailInput: {
      label: t({
        en: 'Add a member',
        es: 'Agregar miembro',
        fr: 'Ajouter un membre',
        de: 'Mitglied hinzufügen',
        ja: 'メンバーを追加',
        ko: '회원 추가',
        zh: '添加成员',
        it: 'Aggiungi un membro',
        pt: 'Adicionar um membro',
        hi: 'एक सदस्य जोड़ें',
        ar: 'إضافة عضو',
        ru: 'Добавить участника',
        'en-GB': 'Add a member',
      }),
      placeholder: t({
        en: 'Enter an email address',
        es: 'Ingrese una dirección de correo electrónico',
        fr: 'Entrez une adresse e-mail',
        de: 'Geben Sie eine E-Mail-Adresse ein',
        ja: 'メールアドレスを入力',
        ko: '이메일 주소 입력',
        zh: '输入电子邮件地址',
        it: 'Inserisci un indirizzo email',
        pt: 'Digite um endereço de e-mail',
        hi: 'एक ईमेल पता दर्ज करें',
        ar: 'أدخل عنوان البريد الإلكتروني',
        ru: 'Введите адрес электронной почты',
        'en-GB': 'Enter an email address',
      }),

      description: t({
        en: 'Add members to your organization by entering their email addresses.',
        es: 'Agrega miembros a tu organización ingresando sus direcciones de correo electrónico.',
        fr: 'Ajoutez des membres à votre organisation en saisissant leurs adresses e-mail.',
        de: 'Fügen Sie Mitglieder zu Ihrer Organisation hinzu, indem Sie ihre E-Mail-Adressen eingeben.',
        ja: 'メールアドレスを入力して組織にメンバーを追加します。',
        ko: '이메일 주소를 입력하여 조직에 구성원을 추가합니다.',
        zh: '通过输入电子邮件地址向您的组织添加成员。',
        it: 'Aggiungi membri alla tua organizzazione inserendo i loro indirizzi email.',
        pt: 'Adicione membros à sua organização inserindo seus endereços de e-mail.',
        hi: 'ईमेल पते दर्ज कर अपने संगठन में सदस्य जोड़ें।',
        ar: 'أضف أعضاء إلى منظمتك عن طريق إدخال عناوين بريدهم الإلكتروني.',
        ru: 'Добавьте членов в вашу организацию, введя их адреса электронной почты.',
        'en-GB':
          'Add members to your organization by entering their email addresses.',
      }),
    },

    newMemberSubmitButton: {
      label: t({
        en: 'Add member',
        es: 'Agregar miembro',
        fr: 'Ajouter le membre',
        de: 'Mitglied hinzufügen',
        ja: 'メンバーを追加',
        ko: '회원 추가',
        zh: '添加成员',
        it: 'Aggiungi membro',
        pt: 'Adicionar membro',
        hi: 'सदस्य जोड़ें',
        ar: 'إضافة عضو',
        ru: 'Добавить участника',
        'en-GB': 'Add member',
      }),
      text: t({
        en: 'Add',
        es: 'Agregar',
        fr: 'Ajouter',
        de: 'Hinzufügen',
        ja: '追加',
        ko: '추가',
        zh: '添加',
        it: 'Aggiungi',
        pt: 'Adicionar',
        hi: 'जोड़ें',
        ar: 'إضافة',
        ru: 'Добавить',
        'en-GB': 'Add',
      }),
      placeholder: t({
        en: 'Add member',
        es: 'Agregar miembro',
        fr: 'Ajouter le membre',
        de: 'Mitglied hinzufügen',
        ja: 'メンバーを追加',
        ko: '회원 추가',
        zh: '添加成员',
        it: 'Aggiungi membro',
        pt: 'Adicionar membro',
        hi: 'सदस्य जोड़ें',
        ar: 'إضافة عضو',
        ru: 'Добавить участника',
        'en-GB': 'Add member',
      }),
    },

    adminsSelect: {
      label: t({
        en: 'Select admins',
        es: 'Seleccionar administradores',
        fr: 'Sélectionner des administrateurs',
        de: 'Administratoren auswählen',
        ja: '管理者を選択',
        ko: '관리자 선택',
        zh: '选择管理员',
        it: 'Seleziona amministratori',
        pt: 'Selecionar administradores',
        hi: 'व्यवस्थापकों का चयन करें',
        ar: 'حدد المشرفين',
        ru: 'Выберите администраторов',
        'en-GB': 'Select admins',
      }),
      placeholder: t({
        en: 'Select admins',
        es: 'Seleccionar administradores',
        fr: 'Sélectionner des administrateurs',
        de: 'Administratoren auswählen',
        ja: '管理者を選択',
        ko: '관리자 선택',
        zh: '选择管理员',
        it: 'Seleziona amministratori',
        pt: 'Selecionar administradores',
        hi: 'व्यवस्थापकों का चयन करें',
        ar: 'حدد المشرفين',
        ru: 'Выберите администраторов',
        'en-GB': 'Select admins',
      }),
      description: t({
        en: 'Admins can edit members and organization settings.',
        es: 'Los administradores pueden editar miembros y configuraciones del organización.',
        fr: 'Les admins peuvent modifier les membres et les paramètres du organisation.',
        de: 'Administratoren können Mitglieder und Organisationseinstellungen bearbeiten.',
        ja: '管理者はメンバーと組織の設定を編集できます。',
        ko: '관리자는 구성원 및 조직 설정을 편집할 수 있습니다.',
        zh: '管理员可以编辑成员和组织设置。',
        it: "Gli amministratori possono modificare i membri e le impostazioni dell'organizzazione.",
        pt: 'Os administradores podem editar membros e configurações da organização.',
        hi: 'व्यवस्थापक सदस्यों और संगठन सेटिंग्स को संपादित कर सकते हैं।',
        ar: 'يمكن للمسؤولين تعديل الأعضاء وإعدادات المؤسسة.',
        ru: 'Администраторы могут редактировать участников и настройки организации.',
        'en-GB': 'Admins can edit members and organization settings.',
      }),
    },
    addMembersButton: {
      text: t({
        en: 'Update Members',
        es: 'Actualizar Miembros',
        fr: 'Mettre à jour des Membres',
        de: 'Mitglieder aktualisieren',
        ja: 'メンバーを更新',
        ko: '구성원 업데이트',
        zh: '更新成员',
        it: 'Aggiorna membri',
        pt: 'Atualizar membros',
        hi: 'सदस्य अपडेट करें',
        ar: 'تحديث الأعضاء',
        ru: 'Обновить участников',
        'en-GB': 'Update Members',
      }),
      label: t({
        en: 'Update Members',
        es: 'Actualizar Miembros',
        fr: 'Mettre à jour des Membres',
        de: 'Mitglieder aktualisieren',
        ja: 'メンバーを更新',
        ko: '구성원 업데이트',
        zh: '更新成员',
        it: 'Aggiorna membri',
        pt: 'Atualizar membros',
        hi: 'सदस्य अपडेट करें',
        ar: 'تحديث الأعضاء',
        ru: 'Обновить участников',
        'en-GB': 'Update Members',
      }),
    },
  },
} satisfies Dictionary;

export default organizationMembersFormContent;
