import { t, type Dictionary } from 'intlayer';

const projectMembersFormContent = {
  key: 'project-members-form',

  content: {
    title: t({
      en: 'Members',
      es: 'Miembros',
      fr: 'Membres',
      'en-GB': 'Members',
      de: 'Mitglieder',
      ja: 'メンバー',
      ko: '회원',
      zh: '成员',
      it: 'Membri',
      pt: 'Membros',
      hi: 'सदस्य',
      ar: 'الأعضاء',
      ru: 'Члены',
      tr: 'Üyeler',
    }),
    description: t({
      en: 'Manage the members that have access and can edit your project.',
      es: 'Administra los miembros que tienen acceso y pueden editar tu proyecto.',
      fr: 'Gérez les membres qui ont accès et peuvent modifier votre projet.',
      'en-GB': 'Manage the members that have access and can edit your project.',
      de: 'Verwalten Sie die Mitglieder, die Zugriff haben und Ihr Projekt bearbeiten können.',
      ja: 'プロジェクトにアクセスし、編集できるメンバーを管理します。',
      ko: '프로젝트에 접근할 수 있고 편집할 수 있는 구성원을 관리합니다.',
      zh: '管理可以访问和编辑项目的成员。',
      it: 'Gestisci i membri che hanno accesso e possono modificare il tuo progetto.',
      pt: 'Gerencie os membros que têm acesso e podem editar seu projeto.',
      hi: 'उन सदस्यों को प्रबंधित करें जिनके पास पहुंच है और जो आपके प्रोजेक्ट को संपादित कर सकते हैं।',
      ar: 'إدارة الأعضاء الذين يمكنهم الوصول إلى المشروع وتحريره.',
      ru: 'Управляйте членами, которые имеют доступ и могут редактировать ваш проект.',
      tr: 'Projeye erişimi olan ve düzenleyebilen üyeleri yönetin.',
    }),

    noMembers: t({
      en: 'No members',
      es: 'Sin miembros',
      fr: 'Aucun membre',
      'en-GB': 'No members',
      de: 'Keine Mitglieder',
      ja: 'メンバーがいません',
      ko: '회원이 없습니다',
      zh: '没有成员',
      it: 'Nessun membro',
      pt: 'Sem membros',
      hi: 'कोई सदस्य नहीं',
      ar: 'لا يوجد أعضاء',
      ru: 'Нет членов',
      tr: 'Üye yok',
    }),

    membersSelect: {
      label: t({
        en: 'Select members',
        es: 'Seleccionar miembros',
        fr: 'Sélectionner des membres',
        'en-GB': 'Select members',
        de: 'Mitglieder auswählen',
        ja: 'メンバーを選択',
        ko: '구성원 선택',
        zh: '选择成员',
        it: 'Seleziona membri',
        pt: 'Selecionar membros',
        hi: 'सदस्य चुनें',
        ar: 'اختر الأعضاء',
        ru: 'Выберите членов',
        tr: 'Üyeleri seçin',
      }),
      placeholder: t({
        en: 'Select members',
        es: 'Seleccionar miembros',
        fr: 'Sélectionner des membres',
        'en-GB': 'Select members',
        de: 'Mitglieder auswählen',
        ja: 'メンバーを選択',
        ko: '구성원 선택',
        zh: '选择成员',
        it: 'Seleziona membri',
        pt: 'Selecionar membros',
        hi: 'सदस्य चुनें',
        ar: 'اختر الأعضاء',
        ru: 'Выберите членов',
        tr: 'Üyeleri seçin',
      }),
      description: t({
        en: 'Members can view the project.',
        es: 'Los miembros pueden ver el proyecto.',
        fr: 'Les membres peuvent voir le projet.',
        'en-GB': 'Members can view the project.',
        de: 'Mitglieder können das Projekt einsehen.',
        ja: 'メンバーはプロジェクトを表示できます。',
        ko: '회원은 프로젝트를 볼 수 있습니다.',
        zh: '成员可以查看项目。',
        it: 'I membri possono visualizzare il progetto.',
        pt: 'Os membros podem visualizar o projeto.',
        hi: 'सदस्य प्रोजेक्ट देख सकते हैं।',
        ar: 'يمكن للأعضاء عرض المشروع.',
        ru: 'Члены могут просматривать проект.',
        tr: 'Üyeler projeyi görüntüleyebilir.',
      }),
    },
    adminsSelect: {
      label: t({
        en: 'Select admins',
        es: 'Seleccionar administradores',
        fr: 'Sélectionner des administrateurs',
        'en-GB': 'Select admins',
        de: 'Administratoren auswählen',
        ja: '管理者を選択',
        ko: '관리자 선택',
        zh: '选择管理员',
        it: 'Seleziona amministratori',
        pt: 'Selecionar administradores',
        hi: 'व्यवस्थापक चुनें',
        ar: 'اختر المديرين',
        ru: 'Выберите администраторов',
        tr: 'Yöneticileri seçin',
      }),
      placeholder: t({
        en: 'Select admins',
        es: 'Seleccionar administradores',
        fr: 'Sélectionner des administrateurs',
        'en-GB': 'Select admins',
        de: 'Administratoren auswählen',
        ja: '管理者を選択',
        ko: '관리자 선택',
        zh: '选择管理员',
        it: 'Seleziona amministratori',
        pt: 'Selecionar administradores',
        hi: 'व्यवस्थापक चुनें',
        ar: 'اختر المديرين',
        ru: 'Выберите администраторов',
        tr: 'Yöneticileri seçin',
      }),
      description: t({
        en: 'Admins can edit members and project settings.',
        es: 'Los administradores pueden editar miembros y configuraciones del proyecto.',
        fr: 'Les admins peuvent modifier les membres et les paramètres du projet.',
        'en-GB': 'Admins can edit members and project settings.',
        de: 'Administratoren können Mitglieder und Projekteinstellungen bearbeiten.',
        ja: '管理者はメンバーとプロジェクト設定を編集できます。',
        ko: '관리자는 구성원 및 프로젝트 설정을 수정할 수 있습니다.',
        zh: '管理员可以编辑成员和项目设置。',
        it: 'Gli amministratori possono modificare i membri e le impostazioni del progetto.',
        pt: 'Os administradores podem editar membros e configurações do projeto.',
        hi: 'व्यवस्थापक सदस्यों और प्रोजेक्ट सेटिंग्स को संपादित कर सकते हैं।',
        ar: 'يمكن للمديرين تعديل الأعضاء وإعدادات المشروع.',
        ru: 'Администраторы могут редактировать участников и настройки проекта.',
        tr: 'Yöneticiler üyeleri ve proje ayarlarını düzenleyebilir.',
      }),
    },
    addMembersButton: {
      text: t({
        en: 'Update Members',
        es: 'Actualizar Miembros',
        fr: 'Mettre à jour des Membres',
        'en-GB': 'Update Members',
        de: 'Mitglieder aktualisieren',
        ja: 'メンバーを更新',
        ko: '구성원 업데이트',
        zh: '更新成员',
        it: 'Aggiorna membri',
        pt: 'Atualizar membros',
        hi: 'सदस्यों को अपडेट करें',
        ar: 'تحديث الأعضاء',
        ru: 'Обновить членов',
        tr: 'Üyeleri güncelle',
      }),
      label: t({
        en: 'Update Members',
        es: 'Actualizar Miembros',
        fr: 'Mettre à jour des Membres',
        'en-GB': 'Update Members',
        de: 'Mitglieder aktualisieren',
        ja: 'メンバーを更新',
        ko: '구성원 업데이트',
        zh: '更新成员',
        it: 'Aggiorna membri',
        pt: 'Atualizar membros',
        hi: 'सदस्यों को अपडेट करें',
        ar: 'تحديث الأعضاء',
        ru: 'Обновить членов',
        tr: 'Üyeleri güncelle',
      }),
    },
    schema: {
      requiredErrorMember: t({
        en: 'Please add at least one member to the project',
        fr: 'Veuillez ajouter au moins un membre au projet',
        es: 'Por favor, agregue al menos un miembro al proyecto',
        'en-GB': 'Please add at least one member to the project',
        de: 'Bitte fügen Sie mindestens ein Mitglied zum Projekt hinzu',
        ja: 'プロジェクトに少なくとも1人のメンバーを追加してください',
        ko: '프로젝트에 최소한 한 명의 회원을 추가하세요',
        zh: '请至少添加一名成员到项目中',
        it: 'Si prega di aggiungere almeno un membro al progetto',
        pt: 'Por favor, adicione pelo menos um membro ao projeto',
        hi: 'कृपया परियोजना में कम से कम एक सदस्य जोड़ें',
        ar: 'الرجاء إضافة عضو واحد على الأقل إلى المشروع',
        ru: 'Пожалуйста, добавьте хотя бы одного участника в проект',
        tr: 'Lütfen projeye en az bir üye ekleyin',
      }),

      requiredErrorAdmin: t({
        en: 'Please add at least one admin to the project',
        fr: 'Veuillez ajouter au moins un administrateur au projet',
        es: 'Por favor, agregue al menos un administrador al proyecto',
        'en-GB': 'Please add at least one admin to the project',
        de: 'Bitte fügen Sie mindestens einen Administrator zum Projekt hinzu',
        ja: 'プロジェクトに少なくとも1人の管理者を追加してください',
        ko: '프로젝트에 최소 한 명의 관리자를 추가하세요',
        zh: '请至少添加一名管理员到项目中',
        it: 'Si prega di aggiungere almeno un amministratore al progetto',
        pt: 'Por favor, adicione pelo menos um administrador ao projeto',
        hi: 'कृपया परियोजना में कम से कम एक व्यवस्थापक जोड़ें',
        ar: 'الرجاء إضافة مدير واحد على الأقل إلى المشروع',
        ru: 'Пожалуйста, добавьте хотя бы одного администратора в проект',
        tr: 'Lütfen projeye en az bir yönetici ekleyin',
      }),
    },
  },
} satisfies Dictionary;

export default projectMembersFormContent;
