/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as Char123LocaleChar125AboutRouteImport } from './routes/{-$locale}/about';
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index';

const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/{-$locale}/',
    path: '/{-$locale}/',
    getParentRoute: () => rootRouteImport,
  } as any);
const Char123LocaleChar125AboutRoute =
  Char123LocaleChar125AboutRouteImport.update({
    id: '/{-$locale}/about',
    path: '/{-$locale}/about',
    getParentRoute: () => rootRouteImport,
  } as any);

export interface FileRoutesByFullPath {
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute;
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute;
}
export interface FileRoutesByTo {
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute;
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute;
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/{-$locale}/about' | '/{-$locale}/';
  fileRoutesByTo: FileRoutesByTo;
  to: '/{-$locale}/about' | '/{-$locale}';
  id: '__root__' | '/{-$locale}/about' | '/{-$locale}/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  Char123LocaleChar125AboutRoute: typeof Char123LocaleChar125AboutRoute;
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute;
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/{-$locale}/': {
      id: '/{-$locale}/';
      path: '/{-$locale}';
      fullPath: '/{-$locale}/';
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/{-$locale}/about': {
      id: '/{-$locale}/about';
      path: '/{-$locale}/about';
      fullPath: '/{-$locale}/about';
      preLoaderRoute: typeof Char123LocaleChar125AboutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125AboutRoute: Char123LocaleChar125AboutRoute,
  Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { createStart } from '@tanstack/solid-start';
import type { getRouter } from './router.tsx';

declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
