import { t, type Dictionary } from 'intlayer';

const accessKeyFormContent = {
  key: 'access-key-form',

  content: {
    title: t({
      en: 'Access keys',
      fr: "Clés d'accès",
      es: 'Claves de acceso',
      'en-GB': 'Access keys',
      de: 'Zugriffsschlüssel',
      ja: 'アクセスキー',
      ko: '액세스 키',
      zh: '访问密钥',
      it: 'Chiavi di accesso',
      pt: 'Chaves de acesso',
      hi: 'पहुँच कुंजी',
      ar: 'مفاتيح الوصول',
      ru: 'Ключи доступа',
    }),
    description: t({
      en: 'Access keys are used to authenticate your project.',
      fr: "Les clés d'accès sont utilisées pour authentifier votre projet.",
      es: 'Las claves de acceso se utilizan para autenticar su proyecto.',
      'en-GB': 'Access keys are used to authenticate your project.',
      de: 'Zugriffsschlüssel werden verwendet, um Ihr Projekt zu authentifizieren.',
      ja: 'アクセスキーは、プロジェクトを認証するために使用されます。',
      ko: '액세스 키는 프로젝트를 인증하는 데 사용됩니다.',
      zh: '访问密钥用于认证您的项目。',
      it: 'Le chiavi di accesso vengono utilizzate per autenticare il tuo progetto.',
      pt: 'As chaves de acesso são usadas para autenticar o seu projeto.',
      hi: 'पहुँच कुंजी आपके परियोजना को प्रमाणित करने के लिए उपयोग किया जाता है।',
      ar: 'مفاتيح الوصول تستخدم للمصادقة على مشروعك.',
      ru: 'Ключи доступа используются для аутентификации вашего проекта.',
    }),
    noAccessKeys: t({
      en: 'No access keys',
      fr: "Aucune clé d'accès",
      es: 'Sin claves de acceso',
      'en-GB': 'No access keys',
      de: 'Keine Zugriffsschlüssel',
      ja: 'アクセスキーがありません',
      ko: '액세스 키가 없습니다',
      zh: '没有访问密钥',
      it: 'Nessuna chiave di accesso',
      pt: 'Sem chaves de acesso',
      hi: 'कोई पहुँच कुंजी नहीं',
      ar: 'لا توجد مفاتيح الوصول',
      ru: 'Нет ключей доступа',
    }),
    createAccessKey: {
      text: t({
        en: 'Create access key',
        fr: "Créer une clé d'accès",
        es: 'Crear una clave de acceso',
        'en-GB': 'Create access key',
        de: 'Zugriffsschlüssel erstellen',
        ja: 'アクセスキーを作成',
        ko: '액세스 키 만들기',
        zh: '创建访问密钥',
        it: 'Crea chiave di accesso',
        pt: 'Criar chave de acesso',
        hi: 'पहुँच कुंजी बनाएं',
        ar: 'إنشاء مفتاح الوصول',
        ru: 'Создать ключ доступа',
      }),
      label: t({
        en: 'Click to create access key',
        fr: "Cliquez pour créer une clé d'accès",
        es: 'Haga clic para crear una clave de acceso',
        'en-GB': 'Click to create access key',
        de: 'Klicken Sie, um ein Zugriffsschlüssel zu erstellen',
        ja: 'アクセスキーを作成するにはクリックしてください',
        ko: '액세스 키를 만들려면 클릭하세요',
        zh: '点击创建访问密钥',
        it: 'Clicca per creare una chiave di accesso',
        pt: 'Clique para criar uma chave de acesso',
        hi: 'पहुँच कुंजी बनाने के लिए क्लिक करें',
        ar: 'انقر لإنشاء مفتاح الوصول',
        ru: 'Нажмите, чтобы создать ключ доступа',
      }),
    },
    rights: {
      title: t({
        en: 'Rights',
        fr: 'Droits',
        es: 'Derechos',
        'en-GB': 'Rights',
        de: 'Rechte',
        ja: '権限',
        ko: '권한',
        zh: '权限',
        it: 'Diritti',
        pt: 'Direitos',
        hi: 'अधिकार',
        ar: 'الحقوق',
        ru: 'Права',
      }),
      read: t({
        en: 'Read ',
        fr: 'Lecture ',
        es: 'Lectura ',
        'en-GB': 'Read ',
        de: 'Lesen ',
        ja: '読み取り ',
        ko: '읽기 ',
        zh: '读取 ',
        it: 'Lettura ',
        pt: 'Leitura ',
        hi: 'पढ़ने ',
        ar: 'قراءة ',
        ru: 'Чтение ',
      }),
      write: t({
        en: 'Write ',
        fr: 'Écriture ',
        es: 'Escritura ',
        'en-GB': 'Write ',
        de: 'Schreiben ',
        ja: '書き込み ',
        ko: '쓰기 ',
        zh: '写入 ',
        it: 'Scrittura ',
        pt: 'Escrita ',
        hi: 'लिखने ',
        ar: 'كتابة ',
        ru: 'Запись ',
      }),
      admin: 'Admin',
      organization: t({
        en: 'Organization: ',
        fr: 'Organisation : ',
        es: 'Organización: ',
        'en-GB': 'Organization: ',
        de: 'Organisation: ',
        ja: '組織: ',
        ko: '조직: ',
        zh: '组织: ',
        it: 'Organizzazione: ',
        pt: 'Organização: ',
        hi: 'संगठन: ',
        ar: 'المنظمة: ',
        ru: 'Организация: ',
      }),
      project: t({
        en: 'Project: ',
        fr: 'Projet : ',
        es: 'Proyecto: ',
        'en-GB': 'Project: ',
        de: 'Projekt: ',
        ja: 'プロジェクト: ',
        ko: '프로젝트: ',
        zh: '项目: ',
        it: 'Progetto: ',
        pt: 'Projeto: ',
        hi: 'परियोजना: ',
        ar: 'المشروع: ',
        ru: 'Проект: ',
      }),
      dictionary: t({
        en: 'Dictionary: ',
        fr: 'Dictionnaire : ',
        es: 'Diccionario: ',
        'en-GB': 'Dictionary: ',
        de: 'Wörterbuch: ',
        ja: '辞書: ',
        ko: '사전: ',
        zh: '字典: ',
        it: 'Dizionario: ',
        pt: 'Dicionário: ',
        hi: 'शब्दकोश: ',
        ar: 'قاموس: ',
        ru: 'Словарь: ',
      }),
    },
    labels: {
      clientId: t({
        en: 'clientId:',
        fr: 'clientId :',
        es: 'clientId:',
        'en-GB': 'clientId:',
        de: 'clientId:',
        ja: 'clientId:',
        ko: 'clientId:',
        zh: 'clientId:',
        it: 'clientId:',
        pt: 'clientId:',
        hi: 'clientId:',
        ar: 'clientId:',
        ru: 'clientId:',
      }),
      clientSecret: t({
        en: 'clientSecret:',
        fr: 'clientSecret :',
        es: 'clientSecret:',
        'en-GB': 'clientSecret:',
        de: 'clientSecret:',
        ja: 'clientSecret:',
        ko: 'clientSecret:',
        zh: 'clientSecret:',
        it: 'clientSecret:',
        pt: 'clientSecret:',
        hi: 'clientSecret:',
        ar: 'clientSecret:',
        ru: 'clientSecret:',
      }),
      addedOn: t({
        en: 'Added on:',
        fr: 'Ajouté le :',
        es: 'Añadido el:',
        'en-GB': 'Added on:',
        de: 'Hinzugefügt am:',
        ja: '追加日時:',
        ko: '추가된 시간:',
        zh: '添加于:',
        it: 'Aggiunto il:',
        pt: 'Adicionado em:',
        hi: 'जोड़ा था:',
        ar: 'أضيف في:',
        ru: 'Добавлено:',
      }),
      expireOn: t({
        en: 'Expire on:',
        fr: 'Expire le :',
        es: 'Expira el:',
        'en-GB': 'Expire on:',
        de: 'Ablaufdatum:',
        ja: '有効期限:',
        ko: '만료 시간:',
        zh: '过期日期:',
        it: 'Scade il:',
        pt: 'Expira em:',
        hi: 'समाप्ति के दिन:',
        ar: 'تنتهي في:',
        ru: 'Истекает:',
      }),
      deleteButtonText: t({
        en: 'Delete',
        fr: 'Supprimer',
        es: 'Eliminar',
        'en-GB': 'Delete',
        de: 'Löschen',
        ja: '削除',
        ko: '삭제',
        zh: '删除',
        it: 'Elimina',
        pt: 'Excluir',
        hi: 'हटाएं',
        ar: 'حذف',
        ru: 'Удалить',
      }),
      deleteButtonLabel: t({
        en: 'Delete the access key',
        fr: "Supprimer la clé d'accès",
        es: 'Eliminar la clave de acceso',
        'en-GB': 'Delete the access key',
        de: 'Löschen Sie den Zugriffsschlüssel',
        ja: 'アクセスキーを削除',
        ko: '액세스 키를 삭제하십시오',
        zh: '删除访问密钥',
        it: 'Elimina la chiave di accesso',
        pt: 'Excluir a chave de acesso',
        hi: 'पहुँच कुंजी हटाएं',
        ar: 'حذف مفتاح الوصول',
        ru: 'Удалите ключ доступа',
      }),
      refreshButtonText: t({
        en: 'Refresh',
        fr: 'Actualiser',
        es: 'Actualizar',
        'en-GB': 'Refresh',
        de: 'Aktualisieren',
        ja: '更新',
        ko: '새로 고침',
        zh: '刷新',
        it: 'Aggiorna',
        pt: 'Atualizar',
        hi: 'ताज़ा करें',
        ar: 'تحديث',
        ru: 'Обновить',
      }),
      refreshButtonLabel: t({
        en: 'Refresh the access key secret key',
        fr: "Actualiser la clé secrète de la clé d'accès",
        es: 'Actualizar la clave secreta de la clave de acceso',
        'en-GB': 'Refresh the access key secret key',
        de: 'Aktualisieren Sie den Zugriffsschlüssel-Geheimschlüssel',
        ja: 'アクセスキーの秘密鍵を更新します',
        ko: '액세스 키 비밀 키를 새로 고침하십시오',
        zh: '刷新访问密钥秘密钥',
        it: 'Aggiorna la chiave segreta della chiave di accesso',
        pt: 'Atualizar a chave secreta da chave de acesso',
        hi: 'पहुँच कुंजी की गुप्त कुंजी को ताज़ा करें',
        ar: 'تحديث المفتاح السري لمفتاح الوصول',
        ru: 'Обновите секретный ключ ключа доступа',
      }),
    },
    modal: {
      deleteTitle: t({
        en: 'Are you sure you want to delete this access key?',
        fr: "Êtes-vous sûr de vouloir supprimer cette clé d'accès ?",
        es: '¿Está seguro de que desea eliminar esta clave de acceso?',
        'en-GB': 'Are you sure you want to delete this access key?',
        de: 'Sind Sie sicher, dass Sie diesen Zugriffsschlüssel löschen möchten?',
        ja: 'このアクセスキーを削除してもよろしいですか？',
        ko: '이 액세스 키를 삭제하시겠습니까?',
        zh: '您确定要删除此访问密钥吗？',
        it: 'Sei sicuro di voler eliminare questa chiave di accesso?',
        pt: 'Tem certeza de que deseja excluir esta chave de acesso?',
        hi: 'क्या आप इस पहुँच कुंजी को हटाना चाहते हैं?',
        ar: 'هل أنت متأكد من أنك تريد حذف هذا المفتاح الوصولي؟',
        ru: 'Вы уверены, что хотите удалить этот ключ доступа?',
      }),
      updateTitle: t({
        en: 'Are you sure you want to update this access key?',
        fr: "Êtes-vous sûr de vouloir mettre à jour cette clé d'accès ?",
        es: '¿Está seguro de que desea actualizar esta clave de acceso?',
        'en-GB': 'Are you sure you want to update this access key?',
        de: 'Sind Sie sicher, dass Sie diesen Zugriffsschlüssel aktualisieren möchten?',
        ja: 'このアクセスキーを更新してもよろしいですか？',
        ko: '이 액세스 키를 업데이트하시겠습니까?',
        zh: '您确定要更新此访问密钥吗？',
        it: 'Sei sicuro di voler aggiornare questa chiave di accesso?',
        pt: 'Tem certeza de que deseja atualizar esta chave de acesso?',
        hi: 'क्या आप इस पहुँच कुंजी को अद्यतन करना चाहते हैं?',
        ar: 'هل أنت متأكد من أنك تريد تحديث هذا المفتاح الوصولي؟',
        ru: 'Вы уверены, что хотите обновить этот ключ доступа?',
      }),
      deleteMessage: t({
        en: 'This action CANNOT be undone. This will permanently delete the access key and if you’d like to use it in the future, you will need to create it again.',
        fr: "Cette action est IRRÉVERSIBLE. Cela supprimera définitivement la clé d'accès et si vous souhaitez l'utiliser à l'avenir, vous devrez la créer à nouveau.",
        es: 'Esta acción NO SE PUEDE deshacer. Esto eliminará permanentemente la clave de acceso y si desea usarla en el futuro, deberá crearla nuevamente.',
        'en-GB':
          'This action CANNOT be undone. This will permanently delete the access key and if you’d like to use it in the future, you will need to create it again.',
        de: 'Diese Aktion KANN NICHT rückgängig gemacht werden. Dies wird den Zugriffsschlüssel dauerhaft löschen und wenn Sie ihn in der Zukunft verwenden möchten, müssen Sie ihn erneut erstellen.',
        ja: 'この操作は取り消すことができません。これにより、アクセスキーが永久に削除され、将来使用する場合は再度作成する必要があります。',
        ko: '이 작업은 취소할 수 없습니다. 액세스 키가 영구적으로 삭제되며, 향후 사용하려면 다시 생성해야 합니다.',
        zh: '此操作无法撤消。这将永久删除访问密钥，如果您将来想使用它，您将需要重新创建它。',
        it: 'Questa azione NON PUÒ essere annullata. Questo eliminerà definitivamente la chiave di accesso e se desideri utilizzarla in futuro, dovrai crearla nuovamente.',
        pt: 'Esta ação NÃO PODE ser desfeita. Isso excluirá permanentemente a chave de acesso e, se desejar usá-la no futuro, precisará criá-la novamente.',
        hi: 'यह क्रिया पूर्ववत नहीं की जा सकती। यह पहुँच कुंजी को स्थायी रूप से हटा देगा और यदि आप इसे भविष्य में उपयोग करना चाहते हैं तो आपको इसे फिर से बनाना होगा।',
        ar: 'لا يمكن التراجع عن هذا الإجراء. سيتم حذف مفتاح الوصول نهائيًا، وإذا كنت ترغب في استخدامه في المستقبل، فستحتاج إلى إنشائه مرة أخرى.',
        ru: 'Это действие НЕ МОЖЕТ быть отменено. Ключ доступа будет удален навсегда, и если вы захотите использовать его в будущем, вам придется создать его заново.',
      }),
      updateMessage: t({
        en: 'This action will generate a new client secret. The old secret will no longer be valid. Please make sure to update your configurations accordingly.',
        fr: "Cette action générera un nouveau secret client. L'ancien secret ne sera plus valide. Veuillez vous assurer de mettre à jour vos configurations en conséquence.",
        es: 'Esta acción generará un nuevo secreto de cliente. El secreto anterior ya no será válido. Asegúrese de actualizar sus configuraciones en consecuencia.',
        'en-GB':
          'This action will generate a new client secret. The old secret will no longer be valid. Please make sure to update your configurations accordingly.',
        de: 'Diese Aktion wird einen neuen Client-Secret generieren. Das alte Secret ist nicht mehr gültig. Bitte aktualisieren Sie Ihre Konfigurationen entsprechend.',
        ja: 'この操作により、新しいクライアントシークレットが生成されます。以前のシークレットは無効になります。構成を適切に更新してください。',
        ko: '이 작업은 새 클라이언트 비밀 키를 생성합니다. 이전 비밀 키는 더 이상 유효하지 않습니다. 구성 업데이트를 확인하세요.',
        zh: '此操作将生成一个新的客户端密钥。旧密钥将不再有效。请确保更新配置。',
        it: 'Questa azione genererà un nuovo client secret. Il vecchio secret non sarà più valido. Assicurati di aggiornare le configurazioni di conseguenza.',
        pt: 'Esta ação gerará um novo segredo de cliente. O segredo antigo não será mais válido. Certifique-se de atualizar suas configurações adequadamente.',
        hi: 'यह क्रिया एक नया क्लाइंट सीक्रेट उत्पन्न करेगी। पुराना सीक्रेट अब मान्य नहीं होगा। कृपया अपनी कॉन्फ़िगरेशन को तदनुसार अपडेट करना सुनिश्चित करें।',
        ar: 'سيؤدي هذا الإجراء إلى إنشاء مفتاح سري جديد. المفتاح القديم لن يكون صالحًا بعد الآن. يرجى التأكد من تحديث تكويناتك وفقًا لذلك.',
        ru: 'Это действие создаст новый клиентский секрет. Старый секрет больше не будет действительным. Обязательно обновите свои настройки соответственно.',
      }),
      deleteButtonLabel: t({
        en: 'Delete the access key',
        'en-GB': 'Delete the access key',
        fr: "Supprimer la clé d'accès",
        es: 'Eliminar la clave de acceso',
        de: 'Den Zugriffsschlüssel löschen',
        ja: 'アクセスキーを削除する',
        ko: '액세스 키 삭제',
        zh: '删除访问密钥',
        it: 'Elimina la chiave di accesso',
        pt: 'Excluir a chave de acesso',
        hi: 'पहुँच कुंजी को हटाएं',
        ar: 'احذف مفتاح الوصول',
        ru: 'Удалить ключ доступа',
      }),
      updateButtonLabel: t({
        en: 'Update the access key',
        'en-GB': 'Update the access key',
        fr: "Mettre à jour la clé d'accès",
        es: 'Actualizar la clave de acceso',
        de: 'Den Zugriffsschlüssel aktualisieren',
        ja: 'アクセスキーを更新する',
        ko: '액세스 키 업데이트',
        zh: '更新访问密钥',
        it: 'Aggiorna la chiave di accesso',
        pt: 'Atualizar a chave de acesso',
        hi: 'पहुँच कुंजी को अपडेट करें',
        ar: 'قم بتحديث مفتاح الوصول',
        ru: 'Обновить ключ доступа',
      }),
      deleteConfirmText: t({
        en: 'I understand, delete the access key',
        'en-GB': 'I understand, delete the access key',
        fr: "Je comprends, supprimez la clé d'accès",
        es: 'Entiendo, eliminar la clave de acceso',
        de: 'Ich verstehe, löschen Sie den Zugriffsschlüssel',
        ja: '理解しました、アクセスキーを削除してください',
        ko: '이해했습니다, 액세스 키를 삭제하세요',
        zh: '我明白了，删除访问密钥',
        it: 'Ho capito, elimina la chiave di accesso',
        pt: 'Entendi, exclua a chave de acesso',
        hi: 'मैं समझ गया, पहुँच कुंजी को हटाएं',
        ar: 'فهمت، احذف مفتاح الوصول',
        ru: 'Я понимаю, удалите ключ доступа',
      }),
      updateConfirmText: t({
        en: 'I understand, update the access key',
        'en-GB': 'I understand, update the access key',
        fr: "Je comprends, mettez à jour la clé d'accès",
        es: 'Entiendo, actualizar la clave de acceso',
        de: 'Ich verstehe, aktualisieren Sie den Zugriffsschlüssel',
        ja: '理解しました、アクセスキーを更新してください',
        ko: '이해했습니다, 액세스 키를 업데이트하세요',
        zh: '我明白了，更新访问密钥',
        it: 'Ho capito, aggiorna la chiave di accesso',
        pt: 'Entendi, atualize a chave de acesso',
        hi: 'मैं समझ गया, पहुँच कुंजी को अपडेट करें',
        ar: 'فهمت، قم بتحديث مفتاح الوصول',
        ru: 'Я понимаю, обновите ключ доступа',
      }),
    },

    tuto: [
      t({
        en: '1 - Create an access key',
        'en-GB': '1 - Create an access key',
        fr: "1 - Créez une clé d'accès",
        es: '1 - Cree una clave de acceso',
        de: '1 - Erstellen Sie einen Zugriffsschlüssel',
        ja: '1 - アクセスキーを作成する',
        ko: '1 - 액세스 키 생성',
        zh: '1 - 创建访问密钥',
        it: '1 - Crea una chiave di accesso',
        pt: '1 - Crie uma chave de acesso',
        hi: '1 - एक पहुँच कुंजी बनाएँ',
        ar: '1 - أنشئ مفتاح وصول',
        ru: '1 - Создайте ключ доступа',
      }),
      t({
        en: '2 - Copy the access key into your intlayer config file',
        'en-GB': '2 - Copy the access key into your intlayer config file',
        fr: "2 - Copiez la clé d'accès dans votre fichier de configuration intlayer",
        es: '2 - Copie la clave de acceso en su archivo de configuración intlayer',
        de: '2 - Kopieren Sie den Zugriffsschlüssel in Ihre Intlayer-Konfigurationsdatei',
        ja: '2 - アクセスキーをIntlayer設定ファイルにコピーする',
        ko: '2 - 액세스 키를 Intlayer 구성 파일에 복사합니다',
        zh: '2 - 将访问密钥复制到Intlayer配置文件中',
        it: '2 - Copia la chiave di accesso nel file di configurazione di Intlayer',
        pt: '2 - Copie a chave de acesso para o arquivo de configuração do Intlayer',
        hi: '2 - पहुँच कुंजी को अपने इंटलेयर कॉन्फ़िग फ़ाइल में कॉपी करें',
        ar: '2 - انسخ مفتاح الوصول إلى ملف التكوين Intlayer الخاص بك',
        ru: '2 - Скопируйте ключ доступа в файл конфигурации Intlayer',
      }),
    ],

    warningMessage: t({
      en: 'Access keys are personal and should not be shared with others. Be careful to store these access keys securely, such as environment variables.',
      'en-GB':
        'Access keys are personal and should not be shared with others. Be careful to store these access keys securely, such as environment variables.',
      fr: "Les clés d'accès sont personnelles et ne doivent pas être partagées avec d'autres personnes. Attention à stocker ces clés d'accès en sécurité, comme en tant que variables d'environnement.",
      es: 'Las claves de acceso son personales y no deben compartirse con otras personas. Tenga cuidado para almacenar estas claves de acceso de forma segura, como variables de entorno.',
      de: 'Zugriffsschlüssel sind persönlich und sollten nicht mit anderen geteilt werden. Speichern Sie diese Zugriffsschlüssel sicher, z. B. als Umgebungsvariablen.',
      ja: 'アクセスキーは個人的なものであり、他人と共有すべきではありません。環境変数としてなど、安全に保存してください。',
      ko: '액세스 키는 개인적인 것이며 다른 사람과 공유해서는 안 됩니다. 환경 변수로 저장하는 등 안전하게 보관하세요.',
      zh: '访问密钥是个人的，不应与他人共享。请小心将这些访问密钥安全存储，例如环境变量。',
      it: 'Le chiavi di accesso sono personali e non devono essere condivise con altri. Assicurati di conservarle in modo sicuro, ad esempio come variabili di ambiente.',
      pt: 'As chaves de acesso são pessoais e não devem ser compartilhadas com outras pessoas. Certifique-se de armazenar essas chaves de acesso de forma segura, como variáveis de ambiente.',
      hi: 'पहुँच कुंजियाँ व्यक्तिगत होती हैं और इन्हें दूसरों के साथ साझा नहीं किया जाना चाहिए। इन्हें सुरक्षित रूप से संग्रहीत करने का ध्यान रखें, जैसे कि पर्यावरणीय चरों के रूप में।',
      ar: 'مفاتيح الوصول شخصية ولا ينبغي مشاركتها مع الآخرين. تأكد من تخزين هذه المفاتيح بشكل آمن، مثل المتغيرات البيئية.',
      ru: 'Ключи доступа являются личными и не должны передаваться другим лицам. Обеспечьте их безопасное хранение, например, в виде переменных окружения.',
    }),
  },
} satisfies Dictionary;

export default accessKeyFormContent;
