import { type Dictionary, t } from 'intlayer';

const editorProfileContent = {
  key: 'editor-profile',
  content: {
    login: {
      label: t({
        en: 'Log in to the Intlayer CMS (runs intlayer login)',
        fr: 'Se connecter au CMS Intlayer (exécute intlayer login)',
        es: 'Iniciar sesión en el CMS de Intlayer (ejecuta intlayer login)',
        de: 'Beim Intlayer-CMS anmelden (führt intlayer login aus)',
        it: 'Accedi al CMS Intlayer (esegue intlayer login)',
        pt: 'Entrar no CMS Intlayer (executa intlayer login)',
        ru: 'Войти в CMS Intlayer (запускает intlayer login)',
        ja: 'Intlayer CMS にログイン（intlayer login を実行）',
        ko: 'Intlayer CMS에 로그인 (intlayer login 실행)',
        zh: '登录 Intlayer CMS（运行 intlayer login）',
        'en-GB': 'Log in to the Intlayer CMS (runs intlayer login)',
        ar: 'تسجيل الدخول إلى Intlayer CMS (يشغّل intlayer login)',
        hi: 'Intlayer CMS में लॉग इन करें (intlayer login चलाता है)',
      }),
      title: t({
        en: 'Login',
        fr: 'Connexion',
        es: 'Iniciar sesión',
        de: 'Anmelden',
        it: 'Accedi',
        pt: 'Entrar',
        ru: 'Войти',
        ja: 'ログイン',
        ko: '로그인',
        zh: '登录',
        'en-GB': 'Login',
        ar: 'تسجيل الدخول',
        hi: 'लॉग इन',
      }),
      pending: t({
        en: 'Waiting for the browser…',
        fr: 'En attente du navigateur…',
        es: 'Esperando al navegador…',
        de: 'Warten auf den Browser…',
        it: 'In attesa del browser…',
        pt: 'Aguardando o navegador…',
        ru: 'Ожидание браузера…',
        ja: 'ブラウザを待っています…',
        ko: '브라우저를 기다리는 중…',
        zh: '正在等待浏览器…',
        'en-GB': 'Waiting for the browser…',
        ar: 'في انتظار المتصفح…',
        hi: 'ब्राउज़र की प्रतीक्षा…',
      }),
    },
    logout: {
      label: t({
        en: 'Log out of the intlayer login session',
        fr: 'Se déconnecter de la session intlayer login',
        es: 'Cerrar la sesión de intlayer login',
        de: 'Von der intlayer login-Sitzung abmelden',
        it: 'Esci dalla sessione intlayer login',
        pt: 'Sair da sessão do intlayer login',
        ru: 'Выйти из сеанса intlayer login',
        ja: 'intlayer login セッションからログアウト',
        ko: 'intlayer login 세션에서 로그아웃',
        zh: '退出 intlayer login 会话',
        'en-GB': 'Log out of the intlayer login session',
        ar: 'تسجيل الخروج من جلسة intlayer login',
        hi: 'intlayer login सत्र से लॉग आउट करें',
      }),
      title: t({
        en: 'Logout',
        fr: 'Déconnexion',
        es: 'Cerrar sesión',
        de: 'Abmelden',
        it: 'Esci',
        pt: 'Sair',
        ru: 'Выйти',
        ja: 'ログアウト',
        ko: '로그아웃',
        zh: '退出登录',
        'en-GB': 'Logout',
        ar: 'تسجيل الخروج',
        hi: 'लॉग आउट',
      }),
    },
    profileLabel: t({
      en: 'Open the profile menu',
      fr: 'Ouvrir le menu du profil',
      es: 'Abrir el menú del perfil',
      de: 'Profilmenü öffnen',
      it: 'Apri il menu del profilo',
      pt: 'Abrir o menu do perfil',
      ru: 'Открыть меню профиля',
      ja: 'プロフィールメニューを開く',
      ko: '프로필 메뉴 열기',
      zh: '打开个人资料菜单',
      'en-GB': 'Open the profile menu',
      ar: 'فتح قائمة الملف الشخصي',
      hi: 'प्रोफ़ाइल मेनू खोलें',
    }),
    sessionAuth: t({
      en: 'Signed in with intlayer login',
      fr: 'Connecté avec intlayer login',
      es: 'Sesión iniciada con intlayer login',
      de: 'Mit intlayer login angemeldet',
      it: 'Accesso effettuato con intlayer login',
      pt: 'Conectado com intlayer login',
      ru: 'Вход выполнен через intlayer login',
      ja: 'intlayer login でサインイン中',
      ko: 'intlayer login으로 로그인됨',
      zh: '已通过 intlayer login 登录',
      'en-GB': 'Signed in with intlayer login',
      ar: 'تم تسجيل الدخول باستخدام intlayer login',
      hi: 'intlayer login से साइन इन किया गया',
    }),
    accessKeyAuth: t({
      en: 'Signed in with an access key',
      fr: "Connecté avec une clé d'accès",
      es: 'Sesión iniciada con una clave de acceso',
      de: 'Mit einem Zugriffsschlüssel angemeldet',
      it: 'Accesso effettuato con una chiave di accesso',
      pt: 'Conectado com uma chave de acesso',
      ru: 'Вход выполнен с ключом доступа',
      ja: 'アクセスキーでサインイン中',
      ko: '액세스 키로 로그인됨',
      zh: '已通过访问密钥登录',
      'en-GB': 'Signed in with an access key',
      ar: 'تم تسجيل الدخول باستخدام مفتاح وصول',
      hi: 'एक्सेस की से साइन इन किया गया',
    }),
    project: t({
      en: 'Project',
      fr: 'Projet',
      es: 'Proyecto',
      de: 'Projekt',
      it: 'Progetto',
      pt: 'Projeto',
      ru: 'Проект',
      ja: 'プロジェクト',
      ko: '프로젝트',
      zh: '项目',
      'en-GB': 'Project',
      ar: 'المشروع',
      hi: 'प्रोजेक्ट',
    }),
  },
} satisfies Dictionary;

export default editorProfileContent;
