import { type Dictionary, t } from 'intlayer';

const profileFormContent = {
  key: 'profile-form',
  content: {
    title: t({
      en: 'Profile details',
      'en-GB': 'Profile details',
      fr: 'Détails du profil',
      es: 'Detalles del perfil',
      de: 'Profil-details',
      ja: 'プロフィール詳細',
      ko: '프로필 세부정보',
      zh: '个人资料详细信息',
      it: 'Dettagli del profilo',
      pt: 'Detalhes do perfil',
      hi: 'प्रोफ़ाइल विवरण',
      ar: 'تفاصيل الملف الشخصي',
      ru: 'Детали профиля',
      tr: 'Profil detayları',
      pl: 'Szczegóły profilu',
      id: 'Detail profil',
      vi: 'Chi tiết hồ sơ',
      uk: 'Деталі профілю',
    }),

    nameInput: {
      label: t({
        en: 'Name',
        'en-GB': 'Name',
        fr: 'Nom',
        es: 'Nombre',
        de: 'Name',
        ja: '名前',
        ko: '이름',
        zh: '名字',
        it: 'Nome',
        pt: 'Nome',
        hi: 'नाम',
        ar: 'الاسم',
        ru: 'Имя',
        tr: 'İsim',
        pl: 'Imię',
        id: 'Nama',
        vi: 'Tên',
        uk: "Ім'я",
      }),
      placeholder: t({
        en: 'Enter your name',
        'en-GB': 'Enter your name',
        fr: 'Entrez votre nom',
        es: 'Ingrese su nombre',
        de: 'Geben Sie Ihren Namen ein',
        ja: 'あなたの名前を入力してください',
        ko: '이름을 입력하세요',
        zh: '输入您的名字',
        it: 'Inserisci il tuo nome',
        pt: 'Insira seu nome',
        hi: 'अपना नाम दर्ज करें',
        ar: 'أدخل اسمك',
        ru: 'Введите ваше имя',
        tr: 'Adınızı girin',
        pl: 'Wpisz swoje imię',
        id: 'Masukkan nama Anda',
        vi: 'Nhập tên của bạn',
        uk: "Введіть своє ім'я",
      }),
    },

    editButton: {
      text: t({
        en: 'Edit profile',
        'en-GB': 'Edit profile',
        fr: 'Modifier le profil',
        es: 'Editar el perfil',
        de: 'Profil bearbeiten',
        ja: 'プロフィールを編集',
        ko: '프로필 편집',
        zh: '编辑个人资料',
        it: 'Modifica il profilo',
        pt: 'Editar perfil',
        hi: 'प्रोफ़ाइल संपादित करें',
        ar: 'تحرير الملف الشخصي',
        ru: 'Редактировать профиль',
        tr: 'Profili düzenle',
        pl: 'Edytuj profil',
        id: 'Sunting profil',
        vi: 'Chỉnh sửa hồ sơ',
        uk: 'Редагувати профіль',
      }),
      ariaLabel: t({
        en: 'Click to edit',
        'en-GB': 'Click to edit',
        fr: 'Cliquez pour modifier',
        es: 'Haga clic para editar',
        de: 'Klicken Sie zum Bearbeiten',
        ja: '編集するにはクリック',
        ko: '수정하려면 클릭',
        zh: '点击编辑',
        it: 'Clicca per modificare',
        pt: 'Clique para editar',
        hi: 'संपादित करने के लिए क्लिक करें',
        ar: 'انقر للتعديل',
        ru: 'Нажмите для редактирования',
        tr: 'Düzenlemek için tıklayın',
        pl: 'Kliknij, aby edytować',
        id: 'Klik untuk mengedit',
        vi: 'Nhấn để chỉnh sửa',
        uk: 'Натисніть, щоб редагувати',
      }),
    },

    changePasswordTitle: t({
      en: 'Change password',
      'en-GB': 'Change password',
      fr: 'Changer le mot de passe',
      es: 'Cambiar la contraseña',
      de: 'Passwort ändern',
      ja: 'パスワードを変更',
      ko: '비밀번호 변경',
      zh: '更改密码',
      it: 'Cambia password',
      pt: 'Alterar senha',
      hi: 'पासवर्ड बदलें',
      ar: 'تغيير كلمة المرور',
      ru: 'Изменить пароль',
      tr: 'Şifreyi değiştir',
      pl: 'Zmień hasło',
      id: 'Ubah kata sandi',
      vi: 'Đổi mật khẩu',
      uk: 'Змінити пароль',
    }),

    twoFactorTitle: t({
      en: 'Two-Factor Authentication',
      'en-GB': 'Two-Factor Authentication',
      fr: 'Authentification à deux facteurs',
      es: 'Autenticación de dos factores',
      de: 'Zwei-Faktor-Authentifizierung',
      ja: '二要素認証',
      ko: '2단계 인증',
      zh: '双因素认证',
      it: 'Autenticazione a due fattori',
      pt: 'Autenticação de dois fatores',
      hi: 'दो-कारक प्रमाणीकरण',
      ar: 'المصادقة الثنائية',
      ru: 'Двухфакторная аутентификация',
      tr: 'İki Faktörlü Kimlik Doğrulama',
      pl: 'Uwierzytelnianie dwuskładnikowe',
      id: 'Autentikasi Dua Faktor',
      vi: 'Xác thực hai yếu tố',
      uk: 'Двофакторна автентифікація',
    }),

    passkeyTitle: t({
      en: 'Passkeys',
      'en-GB': 'Passkeys',
      fr: "Clés d'accès",
      es: 'Claves de acceso',
      de: 'Passkeys',
      ja: 'パスキー',
      ko: '패스키',
      zh: '通行密钥',
      it: 'Passkey',
      pt: 'Chaves de acesso',
      hi: 'पासकी',
      ar: 'مفاتيح المرور',
      ru: 'Ключи доступа',
      tr: 'Parolasız Giriş',
      pl: 'Klucze dostępu',
      id: 'Kunci Sandi',
      vi: 'Khóa truy cập',
      uk: 'Ключі доступу',
    }),

    connectedAccountsTitle: t({
      en: 'Connected Accounts',
      'en-GB': 'Connected Accounts',
      fr: 'Comptes connectés',
      es: 'Cuentas conectadas',
      de: 'Verbundene Konten',
      ja: '連携アカウント',
      ko: '연결된 계정',
      zh: '已连接账户',
      it: 'Account collegati',
      pt: 'Contas conectadas',
      hi: 'जुड़े खाते',
      ar: 'الحسابات المرتبطة',
      ru: 'Связанные аккаунты',
      tr: 'Bağlı Hesaplar',
      pl: 'Połączone konta',
      id: 'Akun Terhubung',
      vi: 'Tài khoản đã kết nối',
      uk: "Пов'язані акаунти",
    }),

    connectButton: t({
      en: 'Connect',
      'en-GB': 'Connect',
      fr: 'Connecter',
      es: 'Conectar',
      de: 'Verbinden',
      ja: '接続',
      ko: '연결',
      zh: '连接',
      it: 'Connetti',
      pt: 'Conectar',
      hi: 'जोड़ें',
      ar: 'ربط',
      ru: 'Подключить',
      tr: 'Bağlan',
      pl: 'Połącz',
      id: 'Hubungkan',
      vi: 'Kết nối',
      uk: "Під'єднати",
    }),

    disconnectButton: t({
      en: 'Disconnect',
      'en-GB': 'Disconnect',
      fr: 'Déconnecter',
      es: 'Desconectar',
      de: 'Trennen',
      ja: '切断',
      ko: '연결 해제',
      zh: '断开连接',
      it: 'Disconnetti',
      pt: 'Desconectar',
      hi: 'अलग करें',
      ar: 'فصل',
      ru: 'Отключить',
      tr: 'Bağlantıyı Kes',
      pl: 'Rozłącz',
      id: 'Putuskan',
      vi: 'Ngắt kết nối',
      uk: "Від'єднати",
    }),

    providers: {
      google: {
        description: t({
          en: 'Connect for authentication',
          'en-GB': 'Connect for authentication',
          fr: "Connecter pour l'authentification",
          es: 'Conectar para autenticación',
          de: 'Für Authentifizierung verbinden',
          ja: '認証のために接続',
          ko: '인증을 위해 연결',
          zh: '连接以进行身份验证',
          it: "Connetti per l'autenticazione",
          pt: 'Conectar para autenticação',
          hi: 'प्रमाणीकरण के लिए जोड़ें',
          ar: 'ربط للمصادقة',
          ru: 'Подключить для аутентификации',
          tr: 'Kimlik doğrulama için bağlan',
          pl: 'Połącz do uwierzytelniania',
          id: 'Hubungkan untuk autentikasi',
          vi: 'Kết nối để xác thực',
          uk: "Під'єднати для автентифікації",
        }),
      },
      github: {
        description: t({
          en: 'Connect for repositories',
          'en-GB': 'Connect for repositories',
          fr: 'Connecter pour les dépôts',
          es: 'Conectar para repositorios',
          de: 'Für Repositories verbinden',
          ja: 'リポジトリのために接続',
          ko: '리포지토리를 위해 연결',
          zh: '连接以访问存储库',
          it: 'Connetti per i repository',
          pt: 'Conectar para repositórios',
          hi: 'रिपोजिटरी के लिए जोड़ें',
          ar: 'ربط للمستودعات',
          ru: 'Подключить для репозиториев',
          tr: 'Depolar için bağlan',
          pl: 'Połącz dla repozytoriów',
          id: 'Hubungkan untuk repositori',
          vi: 'Kết nối cho kho lưu trữ',
          uk: "Під'єднати для репозиторіїв",
        }),
      },
      gitlab: {
        description: t({
          en: 'Connect for CI/CD',
          'en-GB': 'Connect for CI/CD',
          fr: 'Connecter pour CI/CD',
          es: 'Conectar para CI/CD',
          de: 'Für CI/CD verbinden',
          ja: 'CI/CDのために接続',
          ko: 'CI/CD를 위해 연결',
          zh: '连接以进行 CI/CD',
          it: 'Connetti per CI/CD',
          pt: 'Conectar para CI/CD',
          hi: 'CI/CD के लिए जोड़ें',
          ar: 'ربط لـ CI/CD',
          ru: 'Подключить для CI/CD',
          tr: 'CI/CD için bağlan',
          pl: 'Połącz dla CI/CD',
          id: 'Hubungkan untuk CI/CD',
          vi: 'Kết nối cho CI/CD',
          uk: "Під'єднати для CI/CD",
        }),
      },
      atlassian: {
        description: t({
          en: 'Connect for Jira & Confluence',
          'en-GB': 'Connect for Jira & Confluence',
          fr: 'Connecter pour Jira & Confluence',
          es: 'Conectar para Jira & Confluence',
          de: 'Für Jira & Confluence verbinden',
          ja: 'Jira & Confluenceのために接続',
          ko: 'Jira & Confluence를 위해 연결',
          zh: '连接以使用 Jira 和 Confluence',
          it: 'Connetti per Jira & Confluence',
          pt: 'Conectar para Jira & Confluence',
          hi: 'Jira & Confluence के लिए जोड़ें',
          ar: 'ربط لـ Jira & Confluence',
          ru: 'Подключить для Jira & Confluence',
          tr: 'Jira & Confluence için bağlan',
          pl: 'Połącz dla Jira & Confluence',
          id: 'Hubungkan untuk Jira & Confluence',
          vi: 'Kết nối cho Jira & Confluence',
          uk: "Під'єднати для Jira & Confluence",
        }),
      },
      linkedin: {
        description: t({
          en: 'Connect for professional network',
          'en-GB': 'Connect for professional network',
          fr: 'Connecter pour le réseau professionnel',
          es: 'Conectar para red profesional',
          de: 'Für professionelles Netzwerk verbinden',
          ja: 'プロフェッショナルネットワークのために接続',
          ko: '전문 네트워크를 위해 연결',
          zh: '连接以访问职业网络',
          it: 'Connetti per la rete professionale',
          pt: 'Conectar para rede profissional',
          hi: 'पेशेवर नेटवर्क के लिए जोड़ें',
          ar: 'ربط للشبكة المهنية',
          ru: 'Подключить для профессиональной сети',
          tr: 'Profesyonel ağ için bağlan',
          pl: 'Połącz dla sieci zawodowej',
          id: 'Hubungkan untuk jaringan profesional',
          vi: 'Kết nối cho mạng chuyên nghiệp',
          uk: "Під'єднати для професійної мережі",
        }),
      },
      microsoft: {
        description: t({
          en: 'Connect for Microsoft services',
          'en-GB': 'Connect for Microsoft services',
          fr: 'Connecter pour les services Microsoft',
          es: 'Conectar para servicios de Microsoft',
          de: 'Für Microsoft-Dienste verbinden',
          ja: 'Microsoftサービスのために接続',
          ko: 'Microsoft 서비스를 위해 연결',
          zh: '连接以使用 Microsoft 服务',
          it: 'Connetti per i servizi Microsoft',
          pt: 'Conectar para serviços Microsoft',
          hi: 'Microsoft सेवाओं के लिए जोड़ें',
          ar: 'ربط لخدمات Microsoft',
          ru: 'Подключить для сервисов Microsoft',
          tr: 'Microsoft hizmetleri için bağlan',
          pl: 'Połącz dla usług Microsoft',
          id: 'Hubungkan untuk layanan Microsoft',
          vi: 'Kết nối cho dịch vụ Microsoft',
          uk: "Під'єднати для сервісів Microsoft",
        }),
      },
    },

    changeAvatar: t({
      en: 'Change avatar',
      'en-GB': 'Change avatar',
      fr: "Changer l'avatar",
      es: 'Cambiar avatar',
      de: 'Avatar ändern',
      ja: 'アバターを変更',
      ko: '아바타 변경',
      zh: '更改头像',
      it: 'Cambia avatar',
      pt: 'Mudar avatar',
      hi: 'अवतार बदलें',
      ar: 'تغيير الصورة الرمزية',
      ru: 'Изменить аватар',
      tr: 'Avatar değiştir',
      pl: 'Zmień awatar',
      id: 'Ubah avatar',
      vi: 'Thay đổi ảnh đại diện',
      uk: 'Змінити аватар',
    }),
  },
  title: 'Profile form',
  description:
    'Content dictionary for the profile form component, including labels, placeholders, and accessibility attributes used for editing user profile details.',
  tags: ['form', 'user profile', 'dashboard'],
} satisfies Dictionary;

export default profileFormContent;
