import {
  App_Home_Path,
  Website_Contributors,
  Website_Doc,
  Website_PrivacyPolicy,
  Website_TermsOfService,
} from '@intlayer/design-system/routes';
import { type Dictionary, t } from 'intlayer';

const dashboardNavbarContent = {
  key: 'dashboard-navbar-content',
  content: {
    footerLinks: [
      {
        href: App_Home_Path,
        label: t({
          en: 'Go to home page',
          'en-GB': 'Go to home page',
          fr: 'Aller sur la page d’accueil',
          es: 'Ir a la página de inicio',
          de: 'Zur Startseite gehen',
          ja: 'ホームページに行く',
          ko: '홈페이지로 이동',
          zh: '转到主页',
          it: 'Vai alla pagina principale',
          pt: 'Ir para a página inicial',
          hi: 'मुख्य पृष्ठ पर जाएं',
          ar: 'اذهب إلى الصفحة الرئيسية',
          ru: 'Перейти на главную страницу',
          tr: 'Ana sayfaya git',
          pl: 'Przejdź na stronę główną',
          id: 'Buka beranda',
          vi: 'Đi tới trang chủ',
          uk: 'Перейти на головну сторінку',
        }),
        text: t({
          en: 'Home',
          'en-GB': 'Home',
          fr: 'Accueil',
          es: 'Inicio',
          de: 'Startseite',
          ja: 'ホーム',
          ko: '홈',
          zh: '主页',
          it: 'Home',
          pt: 'Início',
          hi: 'घर',
          ar: 'الرئيسية',
          ru: 'Главная',
          tr: 'Ana Sayfa',
          pl: 'Strona główna',
          id: 'Beranda',
          vi: 'Trang chủ',
          uk: 'Головна',
        }),
      },
      {
        href: Website_Doc,
        label: t({
          en: 'Go to the documentation page',
          'en-GB': 'Go to the documentation page',
          fr: 'Aller sur la page de documentation',
          es: 'Ir a la página de documentación',
          de: 'Zur Dokumentationsseite gehen',
          ja: 'ドキュメンテーションページに行く',
          ko: '문서 페이지로 이동',
          zh: '转到文档页面',
          it: 'Vai alla pagina della documentazione',
          pt: 'Ir para a página de documentação',
          hi: 'डॉक्यूमेंटेशन पृष्ठ पर जाएं',
          ar: 'اذهب إلى صفحة الوثائق',
          ru: 'Перейти на страницу документации',
          tr: 'Belgeler sayfasına git',
          pl: 'Przejdź do strony dokumentacji',
          id: 'Buka dokumentasi',
          vi: 'Đi tới trang tài liệu',
          uk: 'Перейти на сторінку документації',
        }),
        text: t({
          en: 'Documentation',
          'en-GB': 'Documentation',
          fr: 'Documentation',
          es: 'Documentación',
          de: 'Dokumentation',
          ja: '文書',
          ko: '문서',
          zh: '文档',
          it: 'Documentazione',
          pt: 'Documentação',
          hi: 'दस्तावेज़',
          ar: 'التوثيق',
          ru: 'Документация',
          tr: 'Dokümantasyon',
          pl: 'Dokumentacja',
          id: 'Dokumentasi',
          vi: 'Tài liệu',
          uk: 'Документація',
        }),
      },
      {
        href: Website_PrivacyPolicy,
        label: t({
          en: 'Go to the privacy notice page',
          'en-GB': 'Go to the privacy notice page',
          fr: 'Aller sur la page de mention de confidentialité',
          es: 'Ir a la página de aviso de privacidad',
          de: 'Zur Datenschutzerklärung gehen',
          ja: 'プライバシー通知ページに行く',
          ko: '개인정보 보호 페이지로 이동',
          zh: '转到隐私通知页面',
          it: "Vai alla pagina dell'informativa sulla privacy",
          pt: 'Ir para a página de aviso de privacidade',
          hi: 'गोपनीयता सूचना पृष्ठ पर जाएं',
          ar: 'اذهب إلى صفحة إشعار الخصوصية',
          ru: 'Перейти на страницу уведомления о конфиденциальности',
          tr: 'Gizlilik bildirim sayfasına git',
          pl: 'Przejdź do strony polityki prywatności',
          id: 'Buka halaman pemberitahuan privasi',
          vi: 'Đi tới trang thông báo quyền riêng tư',
          uk: 'Перейти на сторінку повідомлення про конфіденційність',
        }),
        text: t({
          en: 'Privacy Notice',
          'en-GB': 'Privacy Notice',
          fr: 'Mention de confidentialité',
          es: 'Aviso de privacidad',
          de: 'Datenschutzerklärung',
          ja: 'プライバシー通知',
          ko: '개인정보 보호',
          zh: '隐私通知',
          it: 'Informativa sulla privacy',
          pt: 'Aviso de privacidade',
          hi: 'गोपनीयता सूचना',
          ar: 'إشعار الخصوصية',
          ru: 'Уведомление о конфиденциальности',
          tr: 'Gizlilik Bildirimi',
          pl: 'Polityka prywatności',
          id: 'Pemberitahuan Privasi',
          vi: 'Thông báo quyền riêng tư',
          uk: 'Повідомлення про конфіденційність',
        }),
      },
      {
        href: Website_TermsOfService,
        label: t({
          en: 'Go to the terms of service page',
          'en-GB': 'Go to the terms of service page',
          fr: 'Aller sur la page des conditions d’utilisation',
          es: 'Ir a la página de términos de servicio',
          de: 'Zur Seite mit den Nutzungsbedingungen gehen',
          ja: '利用規約ページに行く',
          ko: '서비스 약관 페이지로 이동',
          zh: '转到服务条款页面',
          it: 'Vai alla pagina dei termini di servizio',
          pt: 'Ir para a página de termos de serviço',
          hi: 'सेवा की शर्तें पृष्ठ पर जाएं',
          ar: 'اذهب إلى صفحة شروط الخدمة',
          ru: 'Перейти на страницу условий обслуживания',
          tr: 'Hizmet şartları sayfasına git',
          pl: 'Przejdź do strony regulaminu',
          id: 'Buka halaman ketentuan layanan',
          vi: 'Đi tới trang điều khoản dịch vụ',
          uk: 'Перейти на сторінку умов надання послуг',
        }),
        text: t({
          en: 'Terms of Service',
          'en-GB': 'Terms of Service',
          fr: 'Conditions d’utilisation',
          es: 'Términos de servicio',
          de: 'Nutzungsbedingungen',
          ja: 'サービス利用規約',
          ko: '서비스 약관',
          zh: '服务条款',
          it: 'Termini di servizio',
          pt: 'Termos de Serviço',
          hi: 'सेवा की शर्तें',
          ar: 'شروط الخدمة',
          ru: 'Условия обслуживания',
          tr: 'Hizmet Şartları',
          pl: 'Regulamin',
          id: 'Ketentuan Layanan',
          vi: 'Điều khoản dịch vụ',
          uk: 'Умови надання послуг',
        }),
      },
      {
        href: Website_Contributors,
        label: t({
          en: 'Go to contributors page',
          'en-GB': 'Go to contributors page',
          fr: 'Aller sur la page des contributeurs',
          es: 'Ir a la página de colaboradores',
          de: 'Zur Mitwirkenden-Seite gehen',
          ja: '貢献者ページに行く',
          ko: '기여자 페이지로 이동',
          zh: '转到贡献者页面',
          it: 'Vai alla pagina dei contributori',
          pt: 'Ir para a página de colaboradores',
          hi: 'योगदानकर्ता पृष्ठ पर जाएं',
          ar: 'اذهب إلى صفحة المساهمين',
          ru: 'Перейти на страницу участников',
          tr: 'Katkıda bulunanlar sayfasına git',
          pl: 'Przejdź do strony współtwórców',
          id: 'Buka halaman kontributor',
          vi: 'Đi tới trang cộng tác viên',
          uk: 'Перейти на сторінку авторів',
        }),
        text: t({
          en: 'Contributors',
          'en-GB': 'Contributors',
          fr: 'Contributeurs',
          es: 'Colaboradores',
          de: 'Mitwirkende',
          ja: '貢献者',
          ko: '기여자',
          zh: '贡献者',
          it: 'Contributori',
          pt: 'Colaboradores',
          hi: 'योगदानकर्ता',
          ar: 'المساهمون',
          ru: 'Участники',
          tr: 'Katkıda Bulunanlar',
          pl: 'Współtwórcy',
          id: 'Kontributor',
          vi: 'Cộng tác viên',
          uk: 'Автори',
        }),
      },
    ],
  },
  title: 'Dashboard navbar content',
  description:
    'Defines the navigation structure for the Intlayer dashboard, including top navigation links to editor, content, tags, projects, organization, profile, and admin pages, along with footer links to external sections like home, documentation, privacy notice, and terms of service.',
  tags: ['dashboard', 'navigation', 'navbar'],
} satisfies Dictionary;

export default dashboardNavbarContent;
