import { type Dictionary, t } from 'intlayer';

const dashboardNavbar1Content = {
  key: 'dashboard-navbar1',
  content: {
    bannerAriaLabel: t({
      en: 'Dashboard header',
      'en-GB': 'Dashboard header',
      fr: 'En-tête du tableau de bord',
      es: 'Encabezado del panel',
      de: 'Dashboard-Kopfzeile',
      ja: 'ダッシュボードヘッダー',
      ko: '대시보드 헤더',
      zh: '仪表板标题',
      it: 'Intestazione del dashboard',
      pt: 'Cabeçalho do painel',
      hi: 'डैशबोर्ड हेडर',
      ar: 'رأس لوحة القيادة',
      ru: 'Заголовок панели',
      tr: 'Panel başlığı',
      pl: 'Nagłówek panelu',
      id: 'Header dasbor',
      vi: 'Tiêu đề bảng điều khiển',
      uk: 'Заголовок панелі',
    }),

    mobileNavAriaLabel: t({
      en: 'Mobile dashboard navigation',
      'en-GB': 'Mobile dashboard navigation',
      fr: 'Navigation mobile du tableau de bord',
      es: 'Navegación móvil del panel',
      de: 'Mobile Dashboard-Navigation',
      ja: 'モバイルダッシュボードナビゲーション',
      ko: '모바일 대시보드 탐색',
      zh: '移动仪表板导航',
      it: 'Navigazione mobile del dashboard',
      pt: 'Navegação móvel do painel',
      hi: 'मोबाइल डैशबोर्ड नेविगेशन',
      ar: 'تنقل لوحة القيادة المتنقلة',
      ru: 'Мобильная навигация панели',
      tr: 'Mobil panel navigasyonu',
      pl: 'Mobilna nawigacja panelu',
      id: 'Navigasi dasbor seluler',
      vi: 'Điều hướng bảng điều khiển di động',
      uk: 'Мобільна навігація панелі',
    }),

    dashboard: t({
      en: 'Dashboard',
      fr: 'Tableau de bord',
      es: 'Tablero',
      'en-GB': 'Dashboard',
      de: 'Dashboard',
      ja: 'ダッシュボード',
      ko: '대시보드',
      zh: '仪表板',
      it: 'Dashboard',
      pt: 'Painel',
      hi: 'डैशबोर्ड',
      ar: 'لوحة القيادة',
      ru: 'Панель управления',
      tr: 'Panel',
      pl: 'Panel',
      id: 'Panel Instrumen',
      vi: 'Bảng điều khiển',
      uk: 'Панель приладів',
    }),

    organizationAndProject: t({
      en: 'Organization and project',
      fr: 'Organisation et projet',
      es: 'Organización y proyecto',
      'en-GB': 'Organization and project',
      de: 'Organisation und Projekt',
      ja: '組織とプロジェクト',
      ko: '조직 및 프로젝트',
      zh: '组织和项目',
      it: 'Organizzazione e progetto',
      pt: 'Organização e projeto',
      hi: 'संगठन और परियोजना',
      ar: 'المنظمة والمشروع',
      ru: 'Организация и проект',
      tr: 'Organizasyon ve proje',
      pl: 'Organizacja i projekt',
      id: 'Organisasi dan proyek',
      vi: 'Tổ chức và dự án',
      uk: 'Організація та проєкт',
    }),

    enter: t({
      en: 'Enter',
      'en-GB': 'Enter',
      fr: 'Accéder',
      es: 'Acceder',
      de: 'Betreten',
      ja: '移動',
      ko: '이동',
      zh: '进入',
      it: 'Accedi',
      pt: 'Entrar',
      hi: 'प्रवेश करें',
      ar: 'دخول',
      ru: 'Войти',
      tr: 'Giriş',
      pl: 'Wejdź',
      id: 'Masuk',
      vi: 'Vào',
      uk: 'Увійти',
    }),
  },
  title: 'Dashboard Navbar 1',
  description:
    'Content for the dashboard navbar, including the dashboard link and organization/project labels.',
  tags: ['dashboard', 'navbar', 'navigation'],
} satisfies Dictionary;

export default dashboardNavbar1Content;
