import { type Dictionary, t } from 'intlayer';

const adminSidebarContent = {
  key: 'admin-sidebar',
  content: {
    collapseButton: {
      label: t({
        en: 'Collapse sidebar',
        fr: 'Réduire la barre latérale',
        es: 'Colapsar barra lateral',
        'en-GB': 'Collapse sidebar',
        de: 'Seitenleiste zuklappen',
        ja: 'サイドバーを折りたたむ',
        ko: '사이드바 접기',
        zh: '折叠侧边栏',
        it: 'Comprimi barra laterale',
        pt: 'Recolher barra lateral',
        hi: 'साइडबार संकुचित करें',
        ar: 'اطوي الشريط الجانبي',
        ru: 'Свернуть боковую панель',
        tr: 'Kenar çubuğunu daralt',
        pl: 'Zwiń pasek boczny',
        id: 'Sembunyikan sidebar',
        vi: 'Thu gọn thanh bên',
      }),
    },

    navigation: {
      dashboard: {
        label: t({
          en: 'Go to dashboard',
          fr: 'Aller au tableau de bord',
          es: 'Ir al tablero',
          'en-GB': 'Go to dashboard',
          de: 'Zum Dashboard gehen',
          ja: 'ダッシュボードに移動',
          ko: '대시보드로 이동',
          zh: '转到仪表板',
          it: 'Vai alla dashboard',
          pt: 'Ir para o painel',
          hi: 'डैशबोर्ड पर जाएं',
          ar: 'اذهب إلى لوحة القيادة',
          ru: 'Перейти на прибортную панель',
          tr: 'Dashboarde git',
          pl: 'Przejdź do pulpitu',
          id: 'Buka dashboard',
          vi: 'Đi tới bảng điều khiển',
        }),
        title: t({
          en: 'Dashboard',
          fr: 'Tableau de bord',
          es: 'Tablero',
          'en-GB': 'Dashboard',
          de: 'Armaturenbrett',
          ja: 'ダッシュボード',
          ko: '대시보드',
          zh: '仪表板',
          it: 'Dashboard',
          pt: 'Painel',
          hi: 'डैशबोर्ड',
          ar: 'لوحة القيادة',
          ru: 'Приборная панель',
          tr: 'Dashboard',
          pl: 'Pulpit',
          id: 'Dashboard',
          vi: 'Bảng điều khiển',
        }),
      },
      management: {
        label: t({
          en: 'Management section',
          fr: 'Section de gestion',
          es: 'Sección de gestión',
          'en-GB': 'Management section',
          de: 'Verwaltungsbereich',
          ja: '管理セクション',
          ko: '관리 섹션',
          zh: '管理部分',
          it: 'Sezione di gestione',
          pt: 'Seção de gerenciamento',
          hi: 'प्रबंधन अनुभाग',
          ar: 'قسم الإدارة',
          ru: 'Раздел управления',
          tr: 'Yönetim bölümü',
          pl: 'Sekcja zarządzania',
          id: 'Bagian manajemen',
          vi: 'Mục quản lý',
        }),
        title: t({
          en: 'Management',
          fr: 'Gestion',
          es: 'Gestión',
          'en-GB': 'Management',
          de: 'Verwaltung',
          ja: '管理',
          ko: '관리',
          zh: '管理',
          it: 'Gestione',
          pt: 'Gerenciamento',
          hi: 'प्रबंधन',
          ar: 'الإدارة',
          ru: 'Управление',
          tr: 'Yönetim',
          pl: 'Zarządzanie',
          id: 'Manajemen',
          vi: 'Quản lý',
        }),
        organizations: {
          label: t({
            en: 'Manage organizations',
            fr: 'Gérer les organisations',
            es: 'Gestionar organizaciones',
            'en-GB': 'Manage organizations',
            de: 'Organisationen verwalten',
            ja: '組織を管理',
            ko: '조직 관리',
            zh: '管理组织',
            it: 'Gestisci organizzazioni',
            pt: 'Gerenciar organizações',
            hi: 'संगठनों का प्रबंधन',
            ar: 'إدارة المنظمات',
            ru: 'Управление организациями',
            tr: 'Organizasyonları yönet',
            pl: 'Zarządzaj organizacjami',
            id: 'Kelola organisasi',
            vi: 'Quản lý tổ chức',
          }),
          title: t({
            en: 'Organizations',
            fr: 'Organisations',
            es: 'Organizaciones',
            'en-GB': 'Organisations',
            de: 'Organisationen',
            ja: '組織',
            ko: '조직',
            zh: '组织',
            it: 'Organizzazioni',
            pt: 'Organizações',
            hi: 'संगठन',
            ar: 'المنظمات',
            ru: 'Организации',
            tr: 'Organizasyonlar',
            pl: 'Organizacje',
            id: 'Organisasi',
            vi: 'Tổ chức',
          }),
        },
        projects: {
          label: t({
            en: 'Manage projects',
            fr: 'Gérer les projets',
            es: 'Gestionar proyectos',
            'en-GB': 'Manage projects',
            de: 'Projekte verwalten',
            ja: 'プロジェクトを管理',
            ko: '프로젝트 관리',
            zh: '管理项目',
            it: 'Gestisci progetti',
            pt: 'Gerenciar projetos',
            hi: 'परियोजनाओं का प्रबंधन',
            ar: 'إدارة المشاريع',
            ru: 'Управление проектами',
            tr: 'Projeleri yönet',
            pl: 'Zarządzaj projektami',
            id: 'Kelola proyek',
            vi: 'Quản lý dự án',
          }),
          title: t({
            en: 'Projects',
            fr: 'Projets',
            es: 'Proyectos',
            'en-GB': 'Projects',
            de: 'Projekte',
            ja: 'プロジェクト',
            ko: '프로젝트',
            zh: '项目',
            it: 'Progetti',
            pt: 'Projetos',
            hi: 'परियोजनाएं',
            ar: 'المشاريع',
            ru: 'Проекты',
            tr: 'Projeler',
            pl: 'Projekty',
            id: 'Proyek',
            vi: 'Dự án',
          }),
        },
        users: {
          label: t({
            en: 'Manage users',
            fr: 'Gérer les utilisateurs',
            es: 'Gestionar usuarios',
            'en-GB': 'Manage users',
            de: 'Benutzer verwalten',
            ja: 'ユーザーを管理',
            ko: '사용자 관리',
            zh: '管理用户',
            it: 'Gestisci utenti',
            pt: 'Gerenciar usuários',
            hi: 'उपयोगकर्ताओं का प्रबंधन',
            ar: 'إدارة المستخدمين',
            ru: 'Управление пользователями',
            tr: 'Kullanıcıları yönet',
            pl: 'Zarządzaj użytkownikami',
            id: 'Kelola pengguna',
            vi: 'Quản lý người dùng',
          }),
          title: t({
            en: 'Users',
            fr: 'Utilisateurs',
            es: 'Usuarios',
            'en-GB': 'Users',
            de: 'Benutzer',
            ja: 'ユーザー',
            ko: '사용자',
            zh: '用户',
            it: 'Utenti',
            pt: 'Usuários',
            hi: 'उपयोगकर्ता',
            ar: 'المستخدمون',
            ru: 'Пользователи',
            tr: 'Kullanıcılar',
            pl: 'Użytkownicy',
            id: 'Pengguna',
            vi: 'Người dùng',
          }),
        },
        discussions: {
          label: t({
            en: 'Manage discussions',
            fr: 'Gérer les discussions',
            es: 'Gestionar discusiones',
            'en-GB': 'Manage discussions',
            de: 'Diskussionen verwalten',
            ja: 'ディスカッションを管理',
            ko: '토론 관리',
            zh: '管理讨论',
            it: 'Gestisci discussioni',
            pt: 'Gerenciar discussões',
            hi: 'चर्चा प्रबंधन',
            ar: 'إدارة المناقشات',
            ru: 'Управление обсуждениями',
            tr: 'Tartışma yönetimi',
            pl: 'Zarządzaj dyskusjami',
            id: 'Kelola diskusi',
            vi: 'Quản lý thảo luận',
          }),
          title: t({
            en: 'Discussions',
            fr: 'Discussions',
            es: 'Discusiones',
            'en-GB': 'Discussions',
            de: 'Diskussionen',
            ja: 'ディスカッション',
            ko: '토론',
            zh: '讨论',
            it: 'Discussioni',
            pt: 'Discussões',
            hi: 'चर्चा',
            ar: 'المناقشات',
            ru: 'Обсуждения',
            tr: 'Tartışmalar',
            pl: 'Dyskusje',
            id: 'Diskusi',
            vi: 'Thảo luận',
          }),
        },
      },
    },
  },
  title: 'Admin sidebar navigation',
  description:
    'Content declaration for the admin sidebar navigation, includes labels and titles for dashboard access and management sections such as organizations, projects, users, and discussions.',
  tags: ['admin panel', 'sidebar navigation', 'dashboard'],
} satisfies Dictionary;

export default adminSidebarContent;
