import { GithubRoutes, PagesRoutes } from '@/Routes';
import { DocData } from '@components/DocPage/types';
import { Dictionary, t } from 'intlayer';

const docContent = {
  key: 'doc-t-express-intlayer-metadata',
  content: {
    docName: 'package__express-intlayer__t',
    url: PagesRoutes['Doc_Packages_express-intlayer_t'],
    githubUrl: GithubRoutes['Packages_express-intlayer_t'],
    createdAt: '2024-12-02',
    updatedAt: '2024-12-02',
    title: t({
      en: 't Function Documentation | express-intlayer',
      fr: 'Documentation de la fonction t | express-intlayer',
      es: 'Documentación de la función t | express-intlayer',
      de: 'Dokumentation der t-Funktion | express-intlayer',
      ja: 't関数のドキュメント | express-intlayer',
      ko: 't 함수 문서 | express-intlayer',
      zh: 't函数文档 | express-intlayer',
      it: 'Documentazione della funzione t | express-intlayer',
      pt: 'Documentação da função t | express-intlayer',
      hi: 't फ़ंक्शन दस्तावेज़ | express-intlayer',
      ar: 'توثيق دالة t | express-intlayer',
      ru: 'Документация функции t | express-intlayer',
      'en-GB': 't Function Documentation | express-intlayer',
    }),

    description: t({
      en: 'See how to use the t function for express-intlayer package',
      fr: 'Découvrez comment utiliser la fonction t pour le package express-intlayer',
      es: 'Descubre cómo usar la función t para el paquete express-intlayer',
      de: 'Erfahren Sie, wie Sie die t-Funktion für das express-intlayer-Paket verwenden',
      ja: 'express-intlayerパッケージのt関数の使い方を見てみましょう',
      ko: 'express-intlayer 패키지에 대해 t 함수를 사용하는 방법을 확인하십시오',
      zh: '请查看如何使用 express-intlayer 包的 t 函数',
      it: 'Scopri come utilizzare la funzione t per il pacchetto express-intlayer',
      pt: 'Veja como usar a função t para o pacote express-intlayer',
      hi: 'express-intlayer पैकेज के लिए t फ़ंक्शन का उपयोग कैसे करें देखें',
      ar: 'انظر كيف يمكنك استخدام دالة t لحزمة express-intlayer',
      ru: 'Смотрите, как использовать функцию t для пакета express-intlayer',
      'en-GB': 'See how to use the t function for express-intlayer package',
    }),
    keywords: t({
      en: [
        't',
        'translation',
        'Intlayer',
        'Internationalization',
        'Documentation',
        'Express',
        'JavaScript',
        'React',
      ],
      fr: [
        't',
        'traduction',
        'Intlayer',
        'Internationalisation',
        'Documentation',
        'Express',
        'JavaScript',
        'React',
      ],
      es: [
        't',
        'traducción',
        'Intlayer',
        'Internacionalización',
        'Documentación',
        'Express',
        'JavaScript',
        'React',
      ],
      de: [
        't',
        'Übersetzung',
        'Intlayer',
        'Internationalisierung',
        'Dokumentation',
        'Express',
        'JavaScript',
        'React',
      ],
      ja: [
        't',
        '翻訳',
        'Intlayer',
        '国際化',
        'ドキュメンテーション',
        'エクスプレス',
        'JavaScript',
        'リアクト',
      ],
      ko: [
        't',
        '번역',
        'Intlayer',
        '국제화',
        '문서',
        '익스프레스',
        'JavaScript',
        'React',
      ],
      zh: [
        't',
        '翻译',
        'Intlayer',
        '国际化',
        '文档',
        'Express',
        'JavaScript',
        'React',
      ],
      it: [
        't',
        'traduzione',
        'Intlayer',
        'Internazionalizzazione',
        'Documentazione',
        'Express',
        'JavaScript',
        'React',
      ],
      pt: [
        't',
        'tradução',
        'Intlayer',
        'Internacionalização',
        'Documentação',
        'Express',
        'JavaScript',
        'React',
      ],
      hi: [
        't',
        'अनुवाद',
        'Intlayer',
        'अंतर्राष्ट्रीयकरण',
        'दस्तावेज़ीकरण',
        'एक्सप्रेस',
        'जावास्क्रिप्ट',
        'रिएक्ट',
      ],
      ar: [
        't',
        'ترجمة',
        'Intlayer',
        'التدويل',
        'التوثيق',
        'Express',
        'JavaScript',
        'React',
      ],
      ru: [
        't',
        'перевод',
        'Intlayer',
        'Интернационализация',
        'Документация',
        'Express',
        'JavaScript',
        'React',
      ],
      'en-GB': [
        't',
        'translation',
        'Intlayer',
        'Internationalization',
        'Documentation',
        'Express',
        'JavaScript',
        'React',
      ],
    }),
  },
} satisfies Dictionary<DocData>;

export default docContent;
