import { file, insert, t } from 'intlayer';

const buildSettingsContent = {
  key: 'build-settings',
  content: {
    title: 'Webhooks',
    gitProviderSection: {
      title: insert(
        t({
          ar: 'متصل بـ{{provider}}',
          de: 'Verbunden mit {{provider}}',
          en: 'Connected to {{provider}}',
          'en-GB': 'Connected to {{provider}}',
          es: 'Conectado a {{provider}}',
          fr: 'Connecté à {{provider}}',
          hi: 'इससे जुड़ा हुआ {{provider}}',
          id: 'Terhubung ke {{provider}}',
          it: 'Collegato a {{provider}}',
          ja: '接続先 {{provider}}',
          ko: '연결됨 {{provider}}',
          pl: 'Połączono z {{provider}}',
          pt: 'Conectado a {{provider}}',
          ru: 'Подключено к {{provider}}',
          tr: 'Şuna bağlandı {{provider}}',
          uk: 'Підключено до {{provider}}',
          vi: 'Đã kết nối với {{provider}}',
          zh: '已连接到 {{provider}}',
        })
      ),
      noProvider: t({
        en: 'No Git Provider',
        'en-GB': 'No Git Provider',
        fr: 'Aucun fournisseur Git',
        es: 'Sin proveedor Git',
        ru: 'Нет Git-провайдера',
        ja: 'Gitプロバイダーなし',
        ko: 'Git 공급자 없음',
        zh: '无 Git 提供商',
        de: 'Kein Git-Anbieter',
        ar: 'لا يوجد مزود Git',
        it: 'Nessun provider Git',
        pt: 'Nenhum provedor Git',
        hi: 'कोई Git प्रदाता नहीं',
        tr: 'Git Sağlayıcısı Yok',
        pl: 'Brak dostawcy Git',
        id: 'Tidak Ada Penyedia Git',
        vi: 'Không có nhà cung cấp Git',
        uk: 'Немає провайдера Git',
      }),
      description: t({
        en: 'Automatically trigger a pipeline when dictionary content changes.',
        'en-GB':
          'Automatically trigger a pipeline when dictionary content changes.',
        fr: 'Déclencher automatiquement un pipeline lorsque le contenu du dictionnaire change.',
        es: 'Activar automáticamente un pipeline cuando cambia el contenido del diccionario.',
        ru: 'Автоматически запускать пайплайн при изменении содержимого словаря.',
        ja: '辞書コンテンツが変更されたときにパイプラインを自動的にトリガーします。',
        ko: '사전 콘텐츠가 변경될 때 파이프라인을 자동으로 트리거합니다.',
        zh: '当词典内容更改时自动触发流水线。',
        de: 'Automatisch eine Pipeline auslösen, wenn sich der Wörterbuchinhalt ändert.',
        ar: 'قم بتشغيل خط الأنابيب تلقائيًا عند تغيير محتوى القاموس.',
        it: 'Attiva automaticamente una pipeline quando il contenuto del dizionario cambia.',
        pt: 'Acionar automaticamente um pipeline quando o conteúdo do dicionário mudar.',
        hi: 'शब्दकोश सामग्री बदलने पर स्वचालित रूप से पाइपलाइन ट्रिगर करें।',
        tr: 'Sözlük içeriği değiştiğinde otomatik olarak bir işlem hattını tetikle.',
        pl: 'Automatycznie uruchom potok, gdy zmieni się zawartość słownika.',
        id: 'Secara otomatis memicu pipeline saat konten kamus berubah.',
        vi: 'Tự động kích hoạt quy trình khi nội dung từ điển thay đổi.',
        uk: 'Автоматично запускати pipeline, коли змінюється вміст словника.',
      }),
      configureCIButton: {
        text: t({
          en: 'Configure CI',
          'en-GB': 'Configure CI',
          fr: 'Configurer CI',
          es: 'Configurar CI',
          ru: 'Настроить CI',
          ja: 'CIを設定',
          ko: 'CI 구성',
          zh: '配置 CI',
          de: 'CI konfigurieren',
          ar: 'تكوين CI',
          it: 'Configura CI',
          pt: 'Configurar CI',
          hi: 'CI कॉन्फ़िगर करें',
          tr: 'CI Yapılandır',
          pl: 'Skonfiguruj CI',
          id: 'Konfigurasi CI',
          vi: 'Cấu hình CI',
          uk: 'Налаштувати CI',
        }),
        ariaLabel: t({
          en: 'Check CI Configuration',
          'en-GB': 'Check CI Configuration',
          fr: 'Vérifier la configuration CI',
          es: 'Verificar configuración CI',
          ru: 'Проверить конфигурацию CI',
          ja: 'CI設定を確認',
          ko: 'CI 구성 확인',
          zh: '检查 CI 配置',
          de: 'CI-Konfiguration überprüfen',
          ar: 'التحقق من تكوين CI',
          it: 'Verifica configurazione CI',
          pt: 'Verificar configuração CI',
          hi: 'CI कॉन्फ़िगरेशन जांचें',
          tr: 'CI Yapılandırmasını Kontrol Et',
          pl: 'Sprawdź konfigurację CI',
          id: 'Periksa Konfigurasi CI',
          vi: 'Kiểm tra cấu hình CI',
          uk: 'Перевірити конфігурацію CI',
        }),
      },
    },
    webhooksSection: {
      title: t({
        en: 'Additional Webhooks',
        'en-GB': 'Additional Webhooks',
        fr: 'Webhooks supplémentaires',
        es: 'Webhooks adicionales',
        ru: 'Дополнительные вебхуки',
        ja: '追加のWebhook',
        ko: '추가 웹훅',
        zh: '其他 Webhook',
        de: 'Zusätzliche Webhooks',
        ar: 'Webhooks إضافية',
        it: 'Webhook aggiuntivi',
        pt: 'Webhooks adicionais',
        hi: 'अतिरिक्त वेबहुक',
        tr: "Ek Webhook'lar",
        pl: 'Dodatkowe webhooki',
        id: 'Webhook Tambahan',
        vi: 'Webhook bổ sung',
        uk: 'Додаткові вебхуки',
      }),
      description: t({
        en: 'Add webhooks for external services like Vercel, Netlify, or custom CI/CD pipelines.',
        'en-GB':
          'Add webhooks for external services like Vercel, Netlify, or custom CI/CD pipelines.',
        fr: 'Ajoutez des webhooks pour des services externes comme Vercel, Netlify ou des pipelines CI/CD personnalisés.',
        es: 'Agregue webhooks para servicios externos como Vercel, Netlify o pipelines CI/CD personalizados.',
        ru: 'Добавьте вебхуки для внешних сервисов, таких как Vercel, Netlify или пользовательские CI/CD пайплайны.',
        ja: 'Vercel、Netlify、またはカスタムCI/CDパイプラインなどの外部サービス用のWebhookを追加します。',
        ko: 'Vercel, Netlify 또는 사용자 지정 CI/CD 파이프라인과 같은 외부 서비스에 대한 웹훅을 추가합니다.',
        zh: '为 Vercel、Netlify 或自定义 CI/CD 流水线等外部服务添加 Webhook。',
        de: 'Fügen Sie Webhooks für externe Dienste wie Vercel, Netlify oder benutzerdefinierte CI/CD-Pipelines hinzu.',
        ar: 'أضف webhooks للخدمات الخارجية مثل Vercel أو Netlify أو خطوط أنابيب CI/CD المخصصة.',
        it: 'Aggiungi webhook per servizi esterni come Vercel, Netlify o pipeline CI/CD personalizzate.',
        pt: 'Adicione webhooks para serviços externos como Vercel, Netlify ou pipelines CI/CD personalizados.',
        hi: 'Vercel, Netlify, या कस्टम CI/CD पाइपलाइनों जैसी बाहरी सेवाओं के लिए वेबहुक जोड़ें।',
        tr: 'Vercel, Netlify veya özel CI/CD işlem hatları gibi harici hizmetler için webhook ekleyin.',
        pl: 'Dodaj webhooki dla usług zewnętrznych, takich jak Vercel, Netlify lub niestandardowe potoki CI/CD.',
        id: 'Tambahkan webhook untuk layanan eksternal seperti Vercel, Netlify, atau pipeline CI/CD kustom.',
        vi: 'Thêm webhook cho các dịch vụ bên ngoài như Vercel, Netlify hoặc các quy trình CI/CD tùy chỉnh.',
        uk: 'Додайте вебхуки для зовнішніх сервісів, таких як Vercel, Netlify, або для власних CI/CD-процесів.',
      }),
      noWebhooks: t({
        en: 'No webhooks configured',
        'en-GB': 'No webhooks configured',
        fr: 'Aucun webhook configuré',
        es: 'No hay webhooks configurados',
        ru: 'Вебхуки не настроены',
        ja: 'Webhookが構成されていません',
        ko: '구성된 웹훅 없음',
        zh: '未配置 Webhook',
        de: 'Keine Webhooks konfiguriert',
        ar: 'لم يتم تكوين أي webhooks',
        it: 'Nessun webhook configurato',
        pt: 'Nenhum webhook configurado',
        hi: 'कोई वेबहुक कॉन्फ़िगर नहीं है',
        tr: 'Yapılandırılmış webhook yok',
        pl: 'Brak skonfigurowanych webhooków',
        id: 'Tidak ada webhook yang dikonfigurasi',
        vi: 'Không có webhook nào được định cấu hình',
        uk: 'Немає налаштованих вебхуків',
      }),
      namePlaceholder: t({
        en: 'Name (e.g. Vercel)',
        'en-GB': 'Name (e.g. Vercel)',
        fr: 'Nom (ex. Vercel)',
        es: 'Nombre (ej. Vercel)',
        ru: 'Имя (например, Vercel)',
        ja: '名前 (例: Vercel)',
        ko: '이름 (예: Vercel)',
        zh: '名称 (例如 Vercel)',
        de: 'Name (z. B. Vercel)',
        ar: 'الاسم (مثل Vercel)',
        it: 'Nome (es. Vercel)',
        pt: 'Nome (ex: Vercel)',
        hi: 'नाम (जैसे Vercel)',
        tr: 'İsim (ör. Vercel)',
        pl: 'Nazwa (np. Vercel)',
        id: 'Nama (mis. Vercel)',
        vi: 'Tên (ví dụ: Vercel)',
        uk: 'Назва (наприклад, Vercel)',
      }),
      urlPlaceholder: t({
        en: 'https://api.vercel.com/...',
        'en-GB': 'https://api.vercel.com/...',
        fr: 'https://api.vercel.com/...',
        es: 'https://api.vercel.com/...',
        ru: 'https://api.vercel.com/...',
        ja: 'https://api.vercel.com/...',
        ko: 'https://api.vercel.com/...',
        zh: 'https://api.vercel.com/...',
        de: 'https://api.vercel.com/...',
        ar: 'https://api.vercel.com/...',
        it: 'https://api.vercel.com/...',
        pt: 'https://api.vercel.com/...',
        hi: 'https://api.vercel.com/...',
        tr: 'https://api.vercel.com/...',
        pl: 'https://api.vercel.com/...',
        id: 'https://api.vercel.com/...',
        vi: 'https://api.vercel.com/...',
        uk: 'https://api.vercel.com/...',
      }),
      secretPlaceholder: t({
        en: 'Optional: Webhook secret for verification',
        'en-GB': 'Optional: Webhook secret for verification',
        fr: 'Optionnel : Secret du webhook pour vérification',
        es: 'Opcional: Secreto del webhook para verificación',
        ru: 'Необязательно: Секрет вебхука для проверки',
        ja: 'オプション: 検証用のWebhookシークレット',
        ko: '선택 사항: 확인을 위한 웹훅 비밀',
        zh: '可选：用于验证的 Webhook 密钥',
        de: 'Optional: Webhook-Geheimnis zur Überprüfung',
        ar: 'اختياري: سر Webhook للتحقق',
        it: 'Opzionale: Segreto webhook per la verifica',
        pt: 'Opcional: Segredo do webhook para verificação',
        hi: 'वैकल्पिक: सत्यापन के लिए वेबहुक गुप्त',
        tr: 'İsteğe bağlı: Doğrulama için webhook sırrı',
        pl: 'Opcjonalnie: Sekret webhooka do weryfikacji',
        id: 'Opsional: Rahasia webhook untuk verifikasi',
        vi: 'Tùy chọn: Bí mật webhook để xác minh',
        uk: "Необов'язково: секрет вебхука для перевірки",
      }),
      addButton: {
        text: t({
          en: 'Add Webhook',
          'en-GB': 'Add Webhook',
          fr: 'Ajouter un webhook',
          es: 'Agregar webhook',
          ru: 'Добавить вебхук',
          ja: 'Webhookを追加',
          ko: '웹훅 추가',
          zh: '添加 Webhook',
          de: 'Webhook hinzufügen',
          ar: 'إضافة Webhook',
          it: 'Aggiungi webhook',
          pt: 'Adicionar webhook',
          hi: 'वेबहुक जोड़ें',
          tr: 'Webhook Ekle',
          pl: 'Dodaj webhook',
          id: 'Tambah Webhook',
          vi: 'Thêm Webhook',
          uk: 'Додати вебхук',
        }),
        ariaLabel: t({
          en: 'Add a new webhook',
          'en-GB': 'Add a new webhook',
          fr: 'Ajouter un nouveau webhook',
          es: 'Agregar un nuevo webhook',
          ru: 'Добавить новый вебхук',
          ja: '新しいWebhookを追加',
          ko: '새 웹훅 추가',
          zh: '添加新 Webhook',
          de: 'Einen neuen Webhook hinzufügen',
          ar: 'إضافة webhook جديد',
          it: 'Aggiungi un nuovo webhook',
          pt: 'Adicionar um novo webhook',
          hi: 'नया वेबहुक जोड़ें',
          tr: 'Yeni bir webhook ekle',
          pl: 'Dodaj nowy webhook',
          id: 'Tambahkan webhook baru',
          vi: 'Thêm webhook mới',
          uk: 'Додати новий вебхук',
        }),
      },
      deleteButton: {
        text: t({
          en: 'Delete',
          'en-GB': 'Delete',
          fr: 'Supprimer',
          es: 'Eliminar',
          ru: 'Удалить',
          ja: '削除',
          ko: '삭제',
          zh: '删除',
          de: 'Löschen',
          ar: 'حذف',
          it: 'Elimina',
          pt: 'Excluir',
          hi: 'हटाएं',
          tr: 'Sil',
          pl: 'Usuń',
          id: 'Hapus',
          vi: 'Xóa',
          uk: 'Видалити',
        }),
        ariaLabel: t({
          en: 'Delete webhook',
          'en-GB': 'Delete webhook',
          fr: 'Supprimer le webhook',
          es: 'Eliminar webhook',
          ru: 'Удалить вебхук',
          ja: 'Webhookを削除',
          ko: '웹훅 삭제',
          zh: '删除 Webhook',
          de: 'Webhook löschen',
          ar: 'حذف Webhook',
          it: 'Elimina webhook',
          pt: 'Excluir webhook',
          hi: 'वेबहुक हटाएं',
          tr: "Webhook'u sil",
          pl: 'Usuń webhook',
          id: 'Hapus webhook',
          vi: 'Xóa webhook',
          uk: 'Видалити вебхук',
        }),
      },
      validationErrors: {
        nameRequired: t({
          en: 'Name is required',
          'en-GB': 'Name is required',
          fr: 'Le nom est requis',
          es: 'El nombre es obligatorio',
          ru: 'Имя обязательно',
          ja: '名前は必須です',
          ko: '이름은 필수입니다',
          zh: '名称为必填项',
          de: 'Name ist erforderlich',
          ar: 'الاسم مطلوب',
          it: 'Il nome è obbligatorio',
          pt: 'O nome é obrigatório',
          hi: 'नाम आवश्यक है',
          tr: 'İsim gereklidir',
          pl: 'Nazwa jest wymagana',
          id: 'Nama wajib diisi',
          vi: 'Tên là bắt buộc',
          uk: "Назва є обов'язковою",
        }),
        invalidUrl: t({
          en: 'Invalid URL',
          'en-GB': 'Invalid URL',
          fr: 'URL invalide',
          es: 'URL inválida',
          ru: 'Неверный URL',
          ja: '無効なURL',
          ko: '잘못된 URL',
          zh: '无效的 URL',
          de: 'Ungültige URL',
          ar: 'عنوان URL غير صالح',
          it: 'URL non valida',
          pt: 'URL inválida',
          hi: 'अमान्य URL',
          tr: 'Geçersiz URL',
          pl: 'Nieprawidłowy URL',
          id: 'URL tidak valid',
          vi: 'URL không hợp lệ',
          uk: 'Невірний URL',
        }),
      },
      modal: {
        titleAdd: t({
          en: 'Create a new webhook',
          'en-GB': 'Create a new webhook',
          fr: 'Créer un nouveau webhook',
          es: 'Crear un nuevo webhook',
          ru: 'Создать новый вебхук',
          ja: '新しいWebhookを作成',
          ko: '새 웹훅 만들기',
          zh: '创建新 Webhook',
          de: 'Neuen Webhook erstellen',
          ar: 'إنشاء webhook جديد',
          it: 'Crea un nuovo webhook',
          pt: 'Criar um novo webhook',
          hi: 'नया वेबहुक बनाएं',
          tr: 'Yeni bir webhook oluştur',
          pl: 'Utwórz nowy webhook',
          id: 'Buat webhook baru',
          vi: 'Tạo webhook mới',
          uk: 'Створити новий вебхук',
        }),
        titleEdit: t({
          en: 'Edit webhook',
          'en-GB': 'Edit webhook',
          fr: 'Modifier le webhook',
          es: 'Editar webhook',
          ru: 'Редактировать вебхук',
          ja: 'Webhookを編集',
          ko: '웹훅 편집',
          zh: '编辑 Webhook',
          de: 'Webhook bearbeiten',
          ar: 'تعديل Webhook',
          it: 'Modifica webhook',
          pt: 'Editar webhook',
          hi: 'वेबहुक संपादित करें',
          tr: "Webhook'u düzenle",
          pl: 'Edytuj webhook',
          id: 'Edit webhook',
          vi: 'Chỉnh sửa webhook',
          uk: 'Редагувати вебхук',
        }),
        nameLabel: t({
          en: 'Name',
          'en-GB': 'Name',
          fr: 'Nom',
          es: 'Nombre',
          ru: 'Имя',
          ja: '名前',
          ko: '이름',
          zh: '名称',
          de: 'Name',
          ar: 'الاسم',
          it: 'Nome',
          pt: 'Nome',
          hi: 'नाम',
          tr: 'İsim',
          pl: 'Nazwa',
          id: 'Nama',
          vi: 'Tên',
          uk: 'Назва',
        }),
        nameDescription: t({
          en: 'Identifying label for this webhook (e.g. Production Build)',
          'en-GB': 'Identifying label for this webhook (e.g. Production Build)',
          fr: "Étiquette d'identification pour ce webhook (ex. Build de production)",
          es: 'Etiqueta de identificación para este webhook (ej. Build de producción)',
          ru: 'Идентификационная метка для этого вебхука (например, Production Build)',
          ja: 'このWebhookの識別ラベル（例：本番ビルド）',
          ko: '이 웹훅의 식별 레이블 (예: 프로덕션 빌드)',
          zh: '此 Webhook 的标识标签（例如：生产构建）',
          de: 'Identifikationsbezeichnung für diesen Webhook (z. B. Production Build)',
          ar: 'تسمية تعريفية لهذا webhook (مثل Build الإنتاج)',
          it: 'Etichetta identificativa per questo webhook (es. Build di produzione)',
          pt: 'Rótulo de identificação para este webhook (ex. Build de produção)',
          hi: 'इस वेबहुक के लिए पहचान लेबल (जैसे प्रोडक्शन बिल्ड)',
          tr: 'Bu webhook için tanımlayıcı etiket (örn. Production Build)',
          pl: 'Etykieta identyfikacyjna dla tego webhooka (np. Build produkcyjny)',
          id: 'Label identifikasi untuk webhook ini (mis. Production Build)',
          vi: 'Nhãn nhận dạng cho webhook này (ví dụ: Production Build)',
          uk: 'Ідентифікатор для цього вебхука (наприклад, Production Build)',
        }),
        urlLabel: t({
          en: 'URL',
          'en-GB': 'URL',
          fr: 'URL',
          es: 'URL',
          ru: 'URL',
          ja: 'URL',
          ko: 'URL',
          zh: 'URL',
          de: 'URL',
          ar: 'URL',
          it: 'URL',
          pt: 'URL',
          hi: 'URL',
          tr: 'URL',
          pl: 'URL',
          id: 'URL',
          vi: 'URL',
          uk: 'URL',
        }),
        urlDescription: t({
          en: 'The POST URL that should receive the event payload.',
          'en-GB': 'The POST URL that should receive the event payload.',
          fr: "L'URL POST qui doit recevoir la charge utile de l'événement.",
          es: 'La URL POST que debe recibir la carga útil del evento.',
          ru: 'URL POST, который должен получать полезную нагрузку события.',
          ja: 'イベントペイロードを受信するPOST URL。',
          ko: '이벤트 페이로드를 받을 POST URL입니다.',
          zh: '应接收事件负载的 POST URL。',
          de: 'Die POST-URL, die die Ereignisnutzlast empfangen soll.',
          ar: 'عنوان URL POST الذي يجب أن يستقبل حمولة الحدث.',
          it: "L'URL POST che dovrebbe ricevere il payload dell'evento.",
          pt: 'A URL POST que deve receber o payload do evento.',
          hi: 'POST URL जो इवेंट पेलोड प्राप्त करना चाहिए।',
          tr: 'Olay yükünü alması gereken POST URL.',
          pl: 'URL POST, który powinien otrzymać ładunek zdarzenia.',
          id: 'URL POST yang harus menerima payload acara.',
          vi: 'URL POST sẽ nhận tải trọng sự kiện.',
          uk: 'POST-URL, який повинен отримувати дані події.',
        }),
        secretLabel: t({
          en: 'Secret',
          'en-GB': 'Secret',
          fr: 'Secret',
          es: 'Secreto',
          ru: 'Секрет',
          ja: 'シークレット',
          ko: '비밀',
          zh: '密钥',
          de: 'Geheimnis',
          ar: 'سر',
          it: 'Segreto',
          pt: 'Segredo',
          hi: 'गुप्त',
          tr: 'Gizli',
          pl: 'Sekret',
          id: 'Rahasia',
          vi: 'Bí mật',
          uk: 'Секрет',
        }),
        secretDescription: t({
          en: 'Optional: Token used to sign the request for security verification.',
          'en-GB':
            'Optional: Token used to sign the request for security verification.',
          fr: 'Optionnel : Jeton utilisé pour signer la demande pour vérification de sécurité.',
          es: 'Opcional: Token utilizado para firmar la solicitud para verificación de seguridad.',
          ru: 'Необязательно: Токен, используемый для подписи запроса для проверки безопасности.',
          ja: 'オプション: セキュリティ検証のためにリクエストに署名するために使用されるトークン。',
          ko: '선택 사항: 보안 확인을 위해 요청에 서명하는 데 사용되는 토큰.',
          zh: '可选：用于对请求进行签名以进行安全验证的令牌。',
          de: 'Optional: Token, der zum Signieren der Anfrage für die Sicherheitsüberprüfung verwendet wird.',
          ar: 'اختياري: رمز مميز يُستخدم لتوقيع الطلب للتحقق من الأمان.',
          it: 'Opzionale: Token utilizzato per firmare la richiesta per la verifica della sicurezza.',
          pt: 'Opcional: Token usado para assinar a solicitação para verificação de segurança.',
          hi: 'वैकल्पिक: सुरक्षा सत्यापन के लिए अनुरोध पर हस्ताक्षर करने के लिए उपयोग किया जाने वाला टोकन।',
          tr: 'İsteğe bağlı: Güvenlik doğrulaması için isteği imzalamak için kullanılan token.',
          pl: 'Opcjonalnie: Token używany do podpisywania żądania w celu weryfikacji bezpieczeństwa.',
          id: 'Opsional: Token yang digunakan untuk menandatangani permintaan untuk verifikasi keamanan.',
          vi: 'Tùy chọn: Token được sử dụng để ký yêu cầu để xác minh bảo mật.',
          uk: "Необов'язково: токен, який використовується для підпису запиту для перевірки безпеки.",
        }),
        cancel: t({
          en: 'Cancel',
          'en-GB': 'Cancel',
          fr: 'Annuler',
          es: 'Cancelar',
          ru: 'Отмена',
          ja: 'キャンセル',
          ko: '취소',
          zh: '取消',
          de: 'Abbrechen',
          ar: 'إلغاء',
          it: 'Annulla',
          pt: 'Cancelar',
          hi: 'रद्द करें',
          tr: 'İptal',
          pl: 'Anuluj',
          id: 'Batal',
          vi: 'Hủy',
          uk: 'Скасувати',
        }),
        confirm: t({
          en: 'Confirm',
          'en-GB': 'Confirm',
          fr: 'Confirmer',
          es: 'Confirmar',
          ru: 'Подтвердить',
          ja: '確認',
          ko: '확인',
          zh: '确认',
          de: 'Bestätigen',
          ar: 'تأكيد',
          it: 'Conferma',
          pt: 'Confirmar',
          hi: 'पुष्टि करें',
          tr: 'Onayla',
          pl: 'Potwierdź',
          id: 'Konfirmasi',
          vi: 'Xác nhận',
          uk: 'Підтвердити',
        }),
      },
      list: {
        edit: t({
          en: 'Edit',
          'en-GB': 'Edit',
          fr: 'Modifier',
          es: 'Editar',
          ru: 'Редактировать',
          ja: '編集',
          ko: '편집',
          zh: '编辑',
          de: 'Bearbeiten',
          ar: 'تعديل',
          it: 'Modifica',
          pt: 'Editar',
          hi: 'संपादित करें',
          tr: 'Düzenle',
          pl: 'Edytuj',
          id: 'Edit',
          vi: 'Chỉnh sửa',
          uk: 'Редагувати',
        }),
        delete: t({
          en: 'Delete',
          'en-GB': 'Delete',
          fr: 'Supprimer',
          es: 'Eliminar',
          ru: 'Удалить',
          ja: '削除',
          ko: '삭제',
          zh: '删除',
          de: 'Löschen',
          ar: 'حذف',
          it: 'Elimina',
          pt: 'Excluir',
          hi: 'हटाएं',
          tr: 'Sil',
          pl: 'Usuń',
          id: 'Hapus',
          vi: 'Xóa',
          uk: 'Видалити',
        }),
        enabled: t({
          en: 'Enabled',
          'en-GB': 'Enabled',
          fr: 'Activé',
          es: 'Habilitado',
          ru: 'Включено',
          ja: '有効',
          ko: '활성화됨',
          zh: '已启用',
          de: 'Aktiviert',
          ar: 'مفعّل',
          it: 'Abilitato',
          pt: 'Habilitado',
          hi: 'सक्षम',
          tr: 'Etkin',
          pl: 'Włączone',
          id: 'Diaktifkan',
          vi: 'Đã bật',
          uk: 'Увімкнено',
        }),
        disabled: t({
          en: 'Disabled',
          'en-GB': 'Disabled',
          fr: 'Désactivé',
          es: 'Deshabilitado',
          ru: 'Отключено',
          ja: '無効',
          ko: '비활성화됨',
          zh: '已禁用',
          de: 'Deaktiviert',
          ar: 'معطّل',
          it: 'Disabilitato',
          pt: 'Desabilitado',
          hi: 'अक्षम',
          tr: 'Devre dışı',
          pl: 'Wyłączone',
          id: 'Dinonaktifkan',
          vi: 'Đã tắt',
          uk: 'Вимкнено',
        }),
      },
    },
    saveButton: {
      text: t({
        en: 'Save Configuration',
        'en-GB': 'Save Configuration',
        fr: 'Enregistrer la configuration',
        es: 'Guardar configuración',
        ru: 'Сохранить конфигурацию',
        ja: '設定を保存',
        ko: '구성 저장',
        zh: '保存配置',
        de: 'Konfiguration speichern',
        ar: 'حفظ التكوين',
        it: 'Salva configurazione',
        pt: 'Salvar configuração',
        hi: 'कॉन्फ़िगरेशन सहेजें',
        tr: 'Yapılandırmayı Kaydet',
        pl: 'Zapisz konfigurację',
        id: 'Simpan Konfigurasi',
        vi: 'Lưu cấu hình',
        uk: 'Зберегти конфігурацію',
      }),
      ariaLabel: t({
        en: 'Save build settings',
        'en-GB': 'Save build settings',
        fr: 'Enregistrer les paramètres de build',
        es: 'Guardar configuración de build',
        ru: 'Сохранить настройки сборки',
        ja: 'ビルド設定を保存',
        ko: '빌드 설정 저장',
        zh: '保存构建设置',
        de: 'Build-Einstellungen speichern',
        ar: 'حفظ إعدادات البناء',
        it: 'Salva impostazioni di build',
        pt: 'Salvar configurações de build',
        hi: 'बिल्ड सेटिंग्स सहेजें',
        tr: 'Derleme ayarlarını kaydet',
        pl: 'Zapisz ustawienia kompilacji',
        id: 'Simpan pengaturan build',
        vi: 'Lưu cài đặt build',
        uk: 'Зберегти налаштування збірки',
      }),
    },
    testTriggerButton: {
      text: t({
        en: 'Test Trigger Now',
        'en-GB': 'Test Trigger Now',
        fr: 'Tester le déclenchement maintenant',
        es: 'Probar activación ahora',
        ru: 'Протестировать запуск сейчас',
        ja: '今すぐトリガーをテスト',
        ko: '지금 트리거 테스트',
        zh: '立即测试触发',
        de: 'Auslöser jetzt testen',
        ar: 'اختبار المشغل الآن',
        it: 'Testa attivazione ora',
        pt: 'Testar acionamento agora',
        hi: 'ट्रिगर का परीक्षण अभी करें',
        tr: 'Tetikleyiciyi Şimdi Test Et',
        pl: 'Przetestuj wyzwalacz teraz',
        id: 'Uji Pemicu Sekarang',
        vi: 'Kiểm tra kích hoạt ngay',
        uk: 'Протестувати тригер зараз',
      }),
      ariaLabel: t({
        en: 'Test trigger CI build',
        'en-GB': 'Test trigger CI build',
        fr: 'Tester le déclenchement du build CI',
        es: 'Probar activación de build CI',
        ru: 'Протестировать запуск CI сборки',
        ja: 'CIビルドトリガーをテスト',
        ko: 'CI 빌드 트리거 테스트',
        zh: '测试触发 CI 构建',
        de: 'CI-Build-Auslöser testen',
        ar: 'اختبار مشغل بناء CI',
        it: 'Testa attivazione build CI',
        pt: 'Testar acionamento de build CI',
        hi: 'CI बिल्ड ट्रिगर का परीक्षण करें',
        tr: 'CI derleme tetikleyicisini test et',
        pl: 'Przetestuj wyzwalacz kompilacji CI',
        id: 'Uji pemicu build CI',
        vi: 'Kiểm tra kích hoạt build CI',
        uk: 'Протестувати тригер CI-збірки',
      }),
    },
    ciModal: {
      titleExisting: t({
        en: 'CI Configuration Detected',
        'en-GB': 'CI Configuration Detected',
        fr: 'Configuration CI détectée',
        es: 'Configuración CI detectada',
        ru: 'Конфигурация CI обнаружена',
        ja: 'CI設定が検出されました',
        ko: 'CI 구성이 감지되었습니다',
        zh: '检测到 CI 配置',
        de: 'CI-Konfiguration erkannt',
        ar: 'تم اكتشاف تكوين CI',
        it: 'Configurazione CI rilevata',
        pt: 'Configuração CI detectada',
        hi: 'CI कॉन्फ़िगरेशन का पता चला',
        tr: 'CI Yapılandırması Algılandı',
        pl: 'Wykryto konfigurację CI',
        id: 'Konfigurasi CI Terdeteksi',
        vi: 'Đã phát hiện cấu hình CI',
        uk: 'Знайдено конфігурацію CI',
      }),
      titleMissing: t({
        en: 'CI Configuration Missing',
        'en-GB': 'CI Configuration Missing',
        fr: 'Configuration CI manquante',
        es: 'Configuración CI faltante',
        ru: 'Конфигурация CI отсутствует',
        ja: 'CI設定が不足しています',
        ko: 'CI 구성이 누락되었습니다',
        zh: '缺少 CI 配置',
        de: 'CI-Konfiguration fehlt',
        ar: 'تكوين CI مفقود',
        it: 'Configurazione CI mancante',
        pt: 'Configuração CI ausente',
        hi: 'CI कॉन्फ़िगरेशन गायब है',
        tr: 'CI Yapılandırması Eksik',
        pl: 'Brak konfiguracji CI',
        id: 'Konfigurasi CI Hilang',
        vi: 'Thiếu cấu hình CI',
        uk: 'Немає конфігурації CI',
      }),
      descriptionExisting: t({
        en: 'Your repository already has a CI workflow configured. You can view the configuration below.',
        'en-GB':
          'Your repository already has a CI workflow configured. You can view the configuration below.',
        fr: 'Votre dépôt a déjà un workflow CI configuré. Vous pouvez voir la configuration ci-dessous.',
        es: 'Su repositorio ya tiene un flujo de trabajo CI configurado. Puede ver la configuración a continuación.',
        ru: 'В вашем репозитории уже настроен CI workflow. Вы можете просмотреть конфигурацию ниже.',
        ja: 'リポジトリには既にCIワークフローが設定されています。以下で設定を確認できます。',
        ko: '저장소에 이미 CI 워크플로우가 구성되어 있습니다. 아래에서 구성을 볼 수 있습니다.',
        zh: '您的存储库已配置 CI 工作流。您可以在下面查看配置。',
        de: 'Ihr Repository hat bereits einen CI-Workflow konfiguriert. Sie können die Konfiguration unten anzeigen.',
        ar: 'يحتوي مستودعك بالفعل على سير عمل CI مُكوّن. يمكنك عرض التكوين أدناه.',
        it: 'Il tuo repository ha già un workflow CI configurato. Puoi visualizzare la configurazione di seguito.',
        pt: 'Seu repositório já tem um fluxo de trabalho CI configurado. Você pode ver a configuração abaixo.',
        hi: 'आपके रिपॉजिटरी में पहले से ही एक CI वर्कफ़्लो कॉन्फ़िगर किया गया है। आप नीचे कॉन्फ़िगरेशन देख सकते हैं।',
        tr: 'Deponuzda zaten bir CI iş akışı yapılandırılmış. Yapılandırmayı aşağıda görüntüleyebilirsiniz.',
        pl: 'Twoje repozytorium ma już skonfigurowany przepływ pracy CI. Możesz zobaczyć konfigurację poniżej.',
        id: 'Repositori Anda sudah memiliki alur kerja CI yang dikonfigurasi. Anda dapat melihat konfigurasi di bawah ini.',
        vi: 'Kho lưu trữ của bạn đã có quy trình CI được cấu hình. Bạn có thể xem cấu hình bên dưới.',
        uk: 'У вашому репозиторії вже налаштовано CI-воркфлоу. Ви можете переглянути конфігурацію нижче.',
      }),
      descriptionMissing: t({
        en: 'Your repository does not have a CI workflow configured. Add the configuration below to enable automatic builds when dictionary content changes.',
        'en-GB':
          'Your repository does not have a CI workflow configured. Add the configuration below to enable automatic builds when dictionary content changes.',
        fr: "Votre dépôt n'a pas de workflow CI configuré. Ajoutez la configuration ci-dessous pour activer les builds automatiques lorsque le contenu du dictionnaire change.",
        es: 'Su repositorio no tiene un flujo de trabajo CI configurado. Agregue la configuración a continuación para habilitar las compilaciones automáticas cuando cambie el contenido del diccionario.',
        ru: 'В вашем репозитории не настроен CI workflow. Добавьте конфигурацию ниже, чтобы включить автоматические сборки при изменении содержимого словаря.',
        ja: 'リポジトリにCIワークフローが設定されていません。以下の設定を追加して、辞書コンテンツが変更されたときに自動ビルドを有効にします。',
        ko: '저장소에 CI 워크플로우가 구성되어 있지 않습니다. 아래 구성을 추가하여 사전 콘텐츠가 변경될 때 자동 빌드를 활성화하세요.',
        zh: '您的存储库未配置 CI 工作流。添加下面的配置以在字典内容更改时启用自动构建。',
        de: 'Ihr Repository hat keinen CI-Workflow konfiguriert. Fügen Sie die Konfiguration unten hinzu, um automatische Builds zu aktivieren, wenn sich der Wörterbuchinhalt ändert.',
        ar: 'لا يحتوي مستودعك على سير عمل CI مُكوّن. أضف التكوين أدناه لتمكين البناء التلقائي عند تغيير محتوى القاموس.',
        it: 'Il tuo repository non ha un workflow CI configurato. Aggiungi la configurazione di seguito per abilitare le build automatiche quando il contenuto del dizionario cambia.',
        pt: 'Seu repositório não tem um fluxo de trabalho CI configurado. Adicione a configuração abaixo para habilitar compilações automáticas quando o conteúdo do dicionário mudar.',
        hi: 'आपके रिपॉजिटरी में CI वर्कफ़्लो कॉन्फ़िगर नहीं है। शब्दकोश सामग्री बदलने पर स्वचालित बिल्ड सक्षम करने के लिए नीचे कॉन्फ़िगरेशन जोड़ें।',
        tr: 'Deponuzda bir CI iş akışı yapılandırılmamış. Sözlük içeriği değiştiğinde otomatik derlemeleri etkinleştirmek için aşağıdaki yapılandırmayı ekleyin.',
        pl: 'Twoje repozytorium nie ma skonfigurowanego przepływu pracy CI. Dodaj konfigurację poniżej, aby włączyć automatyczne kompilacje po zmianie zawartości słownika.',
        id: 'Repositori Anda tidak memiliki alur kerja CI yang dikonfigurasi. Tambahkan konfigurasi di bawah ini untuk mengaktifkan build otomatis saat konten kamus berubah.',
        vi: 'Kho lưu trữ của bạn chưa có quy trình CI được cấu hình. Thêm cấu hình bên dưới để bật bản dựng tự động khi nội dung từ điển thay đổi.',
        uk: 'У вашому репозиторії немає налаштованого CI-воркфлоу. Додайте конфігурацію нижче, щоб увімкнути автоматичні збірки при зміні вмісту словника.',
      }),
      buttons: {
        copy: t({
          en: 'Copy',
          'en-GB': 'Copy',
          fr: 'Copier',
          es: 'Copiar',
          ru: 'Копировать',
          ja: 'コピー',
          ko: '복사',
          zh: '复制',
          de: 'Kopieren',
          ar: 'نسخ',
          it: 'Copia',
          pt: 'Copiar',
          hi: 'कॉपी करें',
          tr: 'Kopyala',
          pl: 'Kopiuj',
          id: 'Salin',
          vi: 'Sao chép',
          uk: 'Копіювати',
        }),
        push: t({
          en: 'Push to Repository',
          'en-GB': 'Push to Repository',
          fr: 'Pousser vers le dépôt',
          es: 'Enviar al repositorio',
          ru: 'Отправить в репозиторий',
          ja: 'リポジトリにプッシュ',
          ko: '저장소에 푸시',
          zh: '推送到存储库',
          de: 'Zum Repository pushen',
          ar: 'دفع إلى المستودع',
          it: 'Invia al repository',
          pt: 'Enviar para o repositório',
          hi: 'रिपॉजिटरी में पुश करें',
          tr: 'Depoya Gönder',
          pl: 'Wypchnij do repozytorium',
          id: 'Kirim ke Repositori',
          vi: 'Đẩy vào kho lưu trữ',
          uk: 'Запушити в репозиторій',
        }),
      },
      messages: {
        copied: t({
          en: 'Configuration copied to clipboard',
          'en-GB': 'Configuration copied to clipboard',
          fr: 'Configuration copiée dans le presse-papiers',
          es: 'Configuración copiada al portapapeles',
          ru: 'Конфигурация скопирована в буфер обмена',
          ja: '設定がクリップボードにコピーされました',
          ko: '구성이 클립보드에 복사되었습니다',
          zh: '配置已复制到剪贴板',
          de: 'Konfiguration in Zwischenablage kopiert',
          ar: 'تم نسخ التكوين إلى الحافظة',
          it: 'Configurazione copiata negli appunti',
          pt: 'Configuração copiada para a área de transferência',
          hi: 'कॉन्फ़िगरेशन क्लिपबोर्ड पर कॉपी किया गया',
          tr: 'Yapılandırma panoya kopyalandı',
          pl: 'Konfiguracja skopiowana do schowka',
          id: 'Konfigurasi disalin ke clipboard',
          vi: 'Đã sao chép cấu hình vào clipboard',
          uk: 'Конфігурацію скопійовано в буфер обміну',
        }),
      },
      viewFileLink: t({
        en: 'View file in repository',
        'en-GB': 'View file in repository',
        fr: 'Voir le fichier dans le dépôt',
        es: 'Ver archivo en el repositorio',
        ru: 'Просмотреть файл в репозитории',
        ja: 'リポジトリでファイルを表示',
        ko: '저장소에서 파일 보기',
        zh: '在存储库中查看文件',
        de: 'Datei im Repository anzeigen',
        ar: 'عرض الملف في المستودع',
        it: 'Visualizza file nel repository',
        pt: 'Ver arquivo no repositório',
        hi: 'रिपॉजिटरी में फ़ाइल देखें',
        tr: 'Depoda dosyayı görüntüle',
        pl: 'Zobacz plik w repozytorium',
        id: 'Lihat file di repositori',
        vi: 'Xem tệp trong kho lưu trữ',
        uk: 'Переглянути файл у репозиторії',
      }),
      copyButtonLabel: t({
        en: 'Copy configuration',
        'en-GB': 'Copy configuration',
        fr: 'Copier la configuration',
        es: 'Copiar configuración',
        ru: 'Копировать конфигурацию',
        ja: '設定をコピー',
        ko: '구성 복사',
        zh: '复制配置',
        de: 'Konfiguration kopieren',
        ar: 'نسخ التكوين',
        it: 'Copia configurazione',
        pt: 'Copiar configuração',
        hi: 'कॉन्फ़िगरेशन कॉपी करें',
        tr: 'Yapılandırmayı kopyala',
        pl: 'Kopiuj konfigurację',
        id: 'Salin konfigurasi',
        vi: 'Sao chép cấu hình',
        uk: 'Копіювати конфігурацію',
      }),
      pushButtonLabel: t({
        en: 'Push to repository',
        'en-GB': 'Push to repository',
        fr: 'Pousser vers le dépôt',
        es: 'Enviar al repositorio',
        ru: 'Отправить в репозиторий',
        ja: 'リポジトリにプッシュ',
        ko: '저장소에 푸시',
        zh: '推送到存储库',
        de: 'Zum Repository pushen',
        ar: 'دفع إلى المستودع',
        it: 'Invia al repository',
        pt: 'Enviar para o repositório',
        hi: 'रिपॉजिटरी में पुश करें',
        tr: 'Depoya gönder',
        pl: 'Wypchnij do repozytorium',
        id: 'Kirim ke repositori',
        vi: 'Đẩy vào kho lưu trữ',
        uk: 'Запушити в репозиторій',
      }),
      manualInstallMessage: t({
        en: 'Manual installation required. Copy the configuration above and add it to your repository.',
        'en-GB':
          'Manual installation required. Copy the configuration above and add it to your repository.',
        fr: 'Installation manuelle requise. Copiez la configuration ci-dessus et ajoutez-la à votre dépôt.',
        es: 'Instalación manual requerida. Copie la configuración anterior y agréguela a su repositorio.',
        ru: 'Требуется ручная установка. Скопируйте конфигурацию выше и добавьте её в ваш репозиторий.',
        ja: '手動インストールが必要です。上記の設定をコピーして、リポジトリに追加してください。',
        ko: '수동 설치가 필요합니다. 위의 구성을 복사하여 저장소에 추가하세요.',
        zh: '需要手动安装。复制上面的配置并将其添加到您的存储库。',
        de: 'Manuelle Installation erforderlich. Kopieren Sie die obige Konfiguration und fügen Sie sie zu Ihrem Repository hinzu.',
        ar: 'التثبيت اليدوي مطلوب. انسخ التكوين أعلاه وأضفه إلى مستودعك.',
        it: 'Installazione manuale richiesta. Copia la configurazione sopra e aggiungila al tuo repository.',
        pt: 'Instalação manual necessária. Copie a configuração acima e adicione-a ao seu repositório.',
        hi: 'मैन्युअल इंस्टॉलेशन आवश्यक है। ऊपर दी गई कॉन्फ़िगरेशन को कॉपी करें और इसे अपने रिपॉजिटरी में जोड़ें।',
        tr: 'Manuel kurulum gerekli. Yukarıdaki yapılandırmayı kopyalayın ve deponuza ekleyin.',
        pl: 'Wymagana instalacja ręczna. Skopiuj powyższą konfigurację i dodaj ją do swojego repozytorium.',
        id: 'Instalasi manual diperlukan. Salin konfigurasi di atas dan tambahkan ke repositori Anda.',
        vi: 'Cần cài đặt thủ công. Sao chép cấu hình ở trên và thêm vào kho lưu trữ của bạn.',
        uk: 'Потрібна ручна установка. Скопіюйте конфігурацію вище та додайте її до свого репозиторію.',
      }),
      failedToLoad: t({
        en: 'Failed to load configuration',
        'en-GB': 'Failed to load configuration',
        fr: 'Échec du chargement de la configuration',
        es: 'Error al cargar la configuración',
        ru: 'Не удалось загрузить конфигурацию',
        ja: '設定の読み込みに失敗しました',
        ko: '구성 로드 실패',
        zh: '加载配置失败',
        de: 'Konfiguration konnte nicht geladen werden',
        ar: 'فشل تحميل التكوين',
        it: 'Impossibile caricare la configurazione',
        pt: 'Falha ao carregar configuração',
        hi: 'कॉन्फ़िगरेशन लोड करने में विफल',
        tr: 'Yapılandırma yüklenemedi',
        pl: 'Nie udało się załadować konfiguracji',
        id: 'Gagal memuat konfigurasi',
        vi: 'Không thể tải cấu hình',
        uk: 'Не вдалося завантажити конфігурацію',
      }),
    },
    ciTemplates: {
      github: file('./CI_GITHUB_TEMPLATE.yaml'),
      gitlab: file('./CI_GITLAB_TEMPLATE.yaml'),
      bitbucket: file('./CI_BITBUCKET_TEMPLATE.yaml'),
    },
  },
  title: 'Build settings',
  description:
    'Configuration for project build settings: manage connected git provider, add and edit webhooks, test triggers, save build configuration, and view CI configuration. Includes CI templates for GitHub, GitLab, and Bitbucket and modals for creating/editing webhooks and CI setup.',
  tags: ['build settings', 'webhooks', 'ci', 'deployments', 'integrations'],
};

export default buildSettingsContent;
