import {
  type BlogKey,
  getBlogMetadata as getBlogMetadataCore,
} from '@intlayer/docs';
import { type Dictionary, localeRecord, t } from 'intlayer';

const getBlogMetadata = (blog: BlogKey) =>
  t(
    localeRecord(async ({ locale }) => await getBlogMetadataCore(blog, locale))
  );

const blogDataContent: Dictionary = {
  key: 'blog-data',
  fill: false,
  content: {
    'what-is-internationalization': {
      title: t({
        en: 'What is Internationalization (i18n)?',
        'en-GB': 'What is Internationalization (i18n)?',
        fr: "Qu'est-ce que l'internationalisation (i18n) ?",
        es: '¿Qué es la internacionalización (i18n)?',
        de: 'Was ist Internationalisierung (i18n)?',
        ja: '国際化とは？',
        ko: '국제화란?',
        zh: '什么是国际化？',
        it: "Cos'è l'internazionalizzazione (i18n)?",
        pt: 'O que é internacionalização (i18n)?',
        hi: 'अंतर्राष्ट्रीयकरण (i18n) क्या है?',
        ar: 'ما هو التدويل (i18n)?',
        ru: 'Что такое интернационализация (i18n)?',
        tr: 'Uluslararasılaştırma (i18n) nedir?',
        pl: 'Co to jest internacjonalizacja (i18n)?',
        id: 'Apa itu internasionalisasi (i18n)?',
        vi: 'Internationalization (i18n) là gì?',
        uk: 'Що таке міжнароднізація (i18n)?',
      }),
      default: getBlogMetadata('./blog/en/what_is_internationalization.md'),
    },
    'SEO-and-i18n': {
      title: t({
        en: 'SEO and i18n',
        'en-GB': 'SEO and i18n',
        fr: 'SEO et i18n',
        es: 'SEO y i18n',
        de: 'SEO und i18n',
        ja: 'SEOと国際化',
        ko: 'SEO와 국제화',
        zh: 'SEO和国际化',
        it: 'SEO e i18n',
        pt: 'SEO e i18n',
        hi: 'SEO और अंतर्राष्ट्रीयकरण',
        ar: 'SEO و التدويل',
        ru: 'SEO и Интернационализация',
        tr: 'SEO ve i18n',
        pl: 'SEO dan i18n',
        id: 'SEO dan i18n',
        vi: 'SEO và i18n',
        uk: 'SEO та i18n',
      }),
      default: getBlogMetadata('./blog/en/internationalization_and_SEO.md'),
    },
    guide: {
      title: t({
        en: 'Guide',
        'en-GB': 'Guide',
        fr: 'Guide',
        es: 'Guía',
        de: 'Leitfaden',
        ja: 'ガイド',
        ko: '가이드',
        zh: '指南',
        it: 'Guida',
        pt: 'Guia',
        hi: 'मार्गदर्शिका',
        ar: 'دليل',
        ru: 'Руководство',
        tr: 'Rehber',
        pl: 'Przewodnik',
        id: 'Panduan',
        vi: 'Hướng dẫn',
        uk: 'Гід',
      }),
      subSections: {
        'i18n-using-next-i18next': {
          title: t({
            en: 'i18n using next-i18next',
            'en-GB': 'i18n using next-i18next',
            fr: 'i18n avec next-i18next',
            es: 'i18n usando next-i18next',
            de: 'i18n mit next-i18next',
            ja: 'next-i18nextによるi18n',
            ko: 'next-i18next로 i18n',
            zh: '使用next-i18next的i18n',
            it: 'i18n con next-i18next',
            pt: 'i18n com next-i18next',
            hi: 'next-i18next के साथ i18n',
            ar: 'i18n باستخدام next-i18next',
            ru: 'i18n с помощью next-i18next',
            tr: 'next-i18next ile i18n',
            pl: 'i18n przy użyciu next-i18next',
            id: 'i18n dengan next-i18next',
            vi: 'i18n với next-i18next',
            uk: 'i18n з використанням next-i18next',
          }),
          default: getBlogMetadata('./blog/en/i18n_using_next-i18next.md'),
        },
        'i18n-using-with-next-intl': {
          title: t({
            en: 'i18n using next-intl',
            'en-GB': 'i18n using next-intl',
            fr: 'i18n avec next-intl',
            es: 'i18n usando next-intl',
            de: 'i18n mit next-intl',
            ja: 'next-intlによるi18n',
            ko: 'next-intl로 i18n',
            zh: '使用next-intl的i18n',
            it: 'i18n con next-intl',
            pt: 'i18n com next-intl',
            hi: 'next-intl के साथ i18n',
            ar: 'i18n باستخدام next-intl',
            ru: 'i18n с помощью next-intl',
            tr: 'next-intl ile i18n',
            pl: 'i18n przy użyciu next-intl',
            id: 'i18n dengan next-intl',
            vi: 'i18n với next-intl',
            uk: 'i18n з використанням next-intl',
          }),
          default: getBlogMetadata('./blog/en/i18n_using_next-intl.md'),
        },
      },
    },
    'wrapping-your-current-i18n-solution-with-intlayer': {
      title: t({
        en: 'Use Intlayer on your solution',
        'en-GB': 'Use Intlayer on your solution',
        fr: 'Utilisez Intlayer sur votre solution',
        es: 'Utiliza Intlayer en tu solución',
        de: 'Verwenden Sie Intlayer in Ihrer Lösung',
        ja: 'Intlayerをあなたのソリューションで使う',
        ko: 'Intlayer를 당신의 솔루션에 사용하세요',
        zh: '在你的方案中使用Intlayer',
        it: 'Usa Intlayer sulla tua soluzione',
        pt: 'Use Intlayer na sua solução',
        hi: 'अपनी समाधान में Intlayer का उपयोग करें',
        ar: 'استخدم Intlayer على الحل الخاص بك',
        ru: 'Используйте Intlayer в вашем решении',
        tr: 'Çözümünüzde Intlayer kullanın',
        pl: 'Użyj Intlayer w swoim rozwiązaniu',
        id: 'Gunakan Intlayer di solusi Anda',
        vi: 'Sử dụng Intlayer trên giải pháp của bạn',
        uk: 'Використовуйте Intlayer на своєму рішенні',
      }),
      subSections: {
        'intlayer-with-next-i18next': {
          title: t({
            en: 'Automate next-i18next',
            'en-GB': 'Automate next-i18next',
            fr: 'Automatiser next-i18next',
            es: 'Automatizar next-i18next',
            de: 'Automatisieren next-i18next',
            ja: 'next-i18nextを自動化',
            ko: 'next-i18next 자동화',
            zh: '自动化 next-i18next',
            it: 'Automatizza next-i18next',
            pt: 'Automatizar next-i18next',
            hi: 'next-i18next को स्वचालित करें',
            ar: 'أتمتة next-i18next',
            ru: 'Автоматизировать next-i18next',
            tr: 'next-i18next otomatikleştir',
            pl: 'Automatyzacja next-i18next',
            id: 'Automatisasi next-i18next',
            vi: 'Tự động hóa next-i18next',
            uk: 'Автоматизація next-i18next',
          }),
          default: getBlogMetadata('./blog/en/intlayer_with_next-i18next.md'),
        },
        'intlayer-with-react-i18next': {
          title: t({
            en: 'Automate react-i18next',
            'en-GB': 'Automate react-i18next',
            fr: 'Automatiser react-i18next',
            es: 'Automatizar react-i18next',
            de: 'Automatisieren react-i18next',
            ja: 'react-i18nextを自動化',
            ko: 'react-i18next 자동화',
            zh: '自动化 react-i18next',
            it: 'Automatizza react-i18next',
            pt: 'Automatizar react-i18next',
            hi: 'react-i18next को स्वचालित करें',
            ar: 'أتمتة react-i18next',
            ru: 'Автоматизировать react-i18next',
            tr: 'react-i18next otomatikleştir',
            pl: 'Automatyzacja react-i18next',
            id: 'Automatisasi react-i18next',
            vi: 'Tự động hóa react-i18next',
            uk: 'Автоматизація react-i18next',
          }),
          default: getBlogMetadata('./blog/en/intlayer_with_react-i18next.md'),
        },
        'intlayer-with-next-intl': {
          title: t({
            en: 'Automate next-intl',
            'en-GB': 'Automate next-intl',
            fr: 'Automatiser next-intl',
            es: 'Automatizar next-intl',
            de: 'Automatisieren next-intl',
            ja: 'next-intlを自動化',
            ko: 'next-intl 자동화',
            zh: '自动化 next-intl',
            it: 'Automatizza next-intl',
            pt: 'Automatizar next-intl',
            hi: 'next-intl को स्वचालित करें',
            ar: 'أتمتة next-intl',
            uk: 'Автоматизація next-intl',
            ru: 'Автоматизировать next-intl',
            tr: 'next-intl otomatikleştir',
            pl: 'Automatyzacja next-intl',
            id: 'Automatisasi next-intl',
            vi: 'Tự động hóa next-intl',
          }),
          default: getBlogMetadata('./blog/en/intlayer_with_next-intl.md'),
        },
        'intlayer-with-react-intl': {
          title: t({
            en: 'Automate react-intl',
            'en-GB': 'Automate react-intl',
            fr: 'Automatiser react-intl',
            es: 'Automatizar react-intl',
            de: 'Automatisieren react-intl',
            ja: 'react-intlを自動化',
            ko: 'react-intl 자동화',
            zh: '自动化 react-intl',
            it: 'Automatizza react-intl',
            pt: 'Automatizar react-intl',
            hi: 'react-intl को स्वचालित करें',
            ar: 'أتمتة react-intl',
            uk: 'Автоматизація react-intl',
            ru: 'Автоматизировать react-intl',
            tr: 'react-intl otomatikleştir',
            pl: 'Automatyzacja react-intl',
            id: 'Automatisasi react-intl',
            vi: 'Tự động hóa react-intl',
          }),
          default: getBlogMetadata('./blog/en/intlayer_with_react-intl.md'),
        },
        'intlayer-with-vue-i18n': {
          title: t({
            en: 'Automate vue-i18n',
            'en-GB': 'Automate vue-i18n',
            fr: 'Automatiser vue-i18n',
            es: 'Automatizar vue-i18n',
            de: 'Automatisieren vue-i18n',
            ja: 'vue-i18nを自動化',
            ko: 'vue-i18n 자동화',
            zh: '自动化 vue-i18n',
            it: 'Automatizza vue-i18n',
            pt: 'Automatizar vue-i18n',
            hi: 'vue-i18n को स्वचालित करें',
            ar: 'أتمتة vue-i18n',
            uk: 'Автоматизація vue-i18n',
            ru: 'Автоматизировать vue-i18n',
            tr: 'vue-i18n otomatikleştir',
            pl: 'Automatyzacja vue-i18n',
            id: 'Automatisasi vue-i18n',
            vi: 'Tự động hóa vue-i18n',
          }),
          default: getBlogMetadata('./blog/en/intlayer_with_vue-i18n.md'),
        },
        'intlayer-with-i18next': {
          title: t({
            en: 'Automate i18next',
            'en-GB': 'Automate i18next',
            fr: 'Automatiser i18next',
            es: 'Automatizar i18next',
            de: 'Automatisieren i18next',
            ja: 'i18nextを自動化',
            ko: 'i18next 자동화',
            zh: '自动化 i18next',
            it: 'Automatizza i18next',
            pt: 'Automatizar i18next',
            hi: 'i18next को स्वचालित करें',
            ar: 'أتمتة i18next',
            uk: 'Автоматизація i18next',
            ru: 'Автоматизировать i18next',
            tr: 'i18next otomatikleştir',
            pl: 'Automatyzacja i18next',
            id: 'Automatisasi i18next',
            vi: 'Tự động hóa i18next',
          }),
          default: getBlogMetadata('./blog/en/intlayer_with_i18next.md'),
        },
      },
    },
    comparisons: {
      title: t({
        en: 'Comparisons',
        'en-GB': 'Comparisons',
        fr: 'Comparaisons',
        es: 'Comparaciones',
        de: 'Vergleiche',
        ja: '比較',
        ko: '비교',
        zh: '比较',
        it: 'Comparazioni',
        pt: 'Comparações',
        hi: 'तुलना',
        ar: 'مقارنات',
        uk: 'Порівняння',
        ru: 'Сравнения',
        tr: 'Karşılaştırmalar',
        pl: 'Porównania',
        id: 'Perbandingan',
        vi: 'So sánh',
      }),
      subSections: {
        'next-i18next-vs-next-intl-vs-intlayer': {
          title: 'next-i18next vs next-intl vs Intlayer',
          default: getBlogMetadata(
            './blog/en/next-i18next_vs_next-intl_vs_intlayer.md'
          ),
        },
        'react-i18next-vs-react-intl-vs-intlayer': {
          title: 'react-i18next vs react-intl vs Intlayer',
          default: getBlogMetadata(
            './blog/en/react-i18next_vs_react-intl_vs_intlayer.md'
          ),
        },
        'is-next-intl-outdated': {
          title: t({
            en: 'Is next-intl outdated?',
            'en-GB': 'Is next-intl outdated?',
            fr: 'next-intl est-il dépassé ?',
            es: '¿Está next-intl obsoleto?',
            de: 'Ist next-intl veraltet?',
            ja: 'next-intl は時代遅れ？',
            ko: 'next-intl은 구식인가요?',
            zh: 'next-intl 过时了吗？',
            it: 'next-intl è obsoleto?',
            pt: 'O next-intl está desatualizado?',
            hi: 'क्या next-intl पुराना हो चुका है?',
            ar: 'هل أصبح next-intl قديمًا؟',
            ru: 'Устарел ли next-intl?',
            tr: 'next-intl güncelliğini yitirdi mi?',
            pl: 'Czy next-intl jest przestarzały?',
            id: 'Apakah next-intl sudah usang?',
            vi: 'next-intl đã lỗi thời chưa?',
            uk: 'Чи застарів next-intl?',
          }),
          default: getBlogMetadata('./blog/en/is_next-intl_outdated.md'),
        },
        'is-i18next-outdated': {
          title: t({
            en: 'Is i18next outdated?',
            'en-GB': 'Is i18next outdated?',
            fr: 'i18next est-il dépassé ?',
            es: '¿Está i18next obsoleto?',
            de: 'Ist i18next veraltet?',
            ja: 'i18next は時代遅れ？',
            ko: 'i18next는 구식인가요?',
            zh: 'i18next 过时了吗？',
            it: 'i18next è obsoleto?',
            pt: 'O i18next está desatualizado?',
            hi: 'क्या i18next पुराना हो चुका है?',
            ar: 'هل أصبح i18next قديمًا؟',
            ru: 'Устарел ли i18next?',
            tr: 'i18next güncelliğini yitirdi mi?',
            pl: 'Czy i18next jest przestarzały?',
            id: 'Apakah i18next sudah usang?',
            vi: 'i18next đã lỗi thời chưa?',
            uk: 'Чи застарів i18next?',
          }),
          default: getBlogMetadata('./blog/en/is_i18next_outdated.md'),
        },
        'is-vue-i18n-outdated': {
          title: t({
            en: 'Is vue-i18n outdated?',
            'en-GB': 'Is vue-i18n outdated?',
            fr: 'vue-i18n est-il dépassé ?',
            es: '¿Está vue-i18n obsoleto?',
            de: 'Ist vue-i18n veraltet?',
            ja: 'vue-i18n は時代遅れ？',
            ko: 'vue-i18n은 구식인가요?',
            zh: 'vue-i18n 过时了吗？',
            it: 'vue-i18n è obsoleto?',
            pt: 'O vue-i18n está desatualizado?',
            hi: 'क्या vue-i18n पुराना हो चुका है?',
            ar: 'هل أصبح vue-i18n قديمًا؟',
            ru: 'Устарел ли vue-i18n?',
            tr: 'vue-i18n güncelliğini yitirdi mi?',
            pl: 'Czy vue-i18n jest przestarzały?',
            id: 'Apakah vue-i18n sudah usang?',
            vi: 'vue-i18n đã lỗi thời chưa?',
            uk: 'Чи застарів vue-i18n?',
          }),
          default: getBlogMetadata('./blog/en/is_vue-i18n_outdated.md'),
        },
        'vue-i18n-vs-intlayer': {
          title: 'vue-i18n vs Intlayer',
          default: getBlogMetadata('./blog/en/vue-i18n_vs_intlayer.md'),
        },
      },
    },

    'i18n-technologies': {
      title: t({
        en: 'i18n Technologies',
        'en-GB': 'i18n Technologies',
        fr: 'Technologies i18n',
        es: 'Tecnologías i18n',
        de: 'i18n-Technologien',
        ja: 'i18n テクノロジー',
        ko: 'i18n 기술',
        zh: 'i18n 技术',
        it: 'Tecnologie i18n',
        pt: 'Tecnologias i18n',
        hi: 'i18n तकनीकें',
        ar: 'تقنيات i18n',
        ru: 'Технологии i18n',
        tr: 'i18n Teknolojileri',
        pl: 'Technologie i18n',
        id: 'Teknologi i18n',
        vi: 'Công nghệ i18n',
        uk: 'Технології i18n',
      }),
      subSections: {
        frameworks: {
          title: t({
            en: 'Frameworks',
            'en-GB': 'Frameworks',
            fr: 'Frameworks',
            es: 'Frameworks',
            de: 'Frameworks',
            ja: 'フレームワーク',
            ko: '프레임워크',
            zh: '框架',
            it: 'Framework',
            pt: 'Frameworks',
            hi: 'फ्रेमवर्क',
            ar: 'أطر العمل',
            ru: 'Фреймворки',
            tr: 'Frameworkler',
            pl: 'Frameworki',
            id: 'Framework',
            vi: 'Framework',
            uk: 'Фреймворки',
          }),
          subSections: {
            nextjs: {
              title: 'Next.js',
              default: getBlogMetadata(
                './blog/en/list_i18n_technologies/frameworks/nextjs.md'
              ),
            },
            react: {
              title: 'React',
              default: getBlogMetadata(
                './blog/en/list_i18n_technologies/frameworks/react.md'
              ),
            },
            'react-router': {
              title: 'React Router',
              default: getBlogMetadata(
                './blog/en/list_i18n_technologies/frameworks/react-router.md'
              ),
            },
            'tanstack-start': {
              title: 'TanStack Start',
              default: getBlogMetadata(
                './blog/en/list_i18n_technologies/frameworks/tanstack-start.md'
              ),
            },
            'react-native': {
              title: 'React Native',
              default: getBlogMetadata(
                './blog/en/list_i18n_technologies/frameworks/react-native.md'
              ),
            },
            vue: {
              title: 'Vue',
              default: getBlogMetadata(
                './blog/en/list_i18n_technologies/frameworks/vue.md'
              ),
            },
            nuxt: {
              title: 'Nuxt',
              default: getBlogMetadata(
                './blog/en/list_i18n_technologies/frameworks/nuxt.md'
              ),
            },
            svelte: {
              title: 'Svelte',
              default: getBlogMetadata(
                './blog/en/list_i18n_technologies/frameworks/svelte.md'
              ),
            },
            sveltekit: {
              title: 'SvelteKit',
              default: getBlogMetadata(
                './blog/en/list_i18n_technologies/frameworks/sveltekit.md'
              ),
            },
            angular: {
              title: 'Angular',
              default: getBlogMetadata(
                './blog/en/list_i18n_technologies/frameworks/angular.md'
              ),
            },
            solid: {
              title: 'Solid',
              default: getBlogMetadata(
                './blog/en/list_i18n_technologies/frameworks/solid.md'
              ),
            },
            astro: {
              title: 'Astro',
              default: getBlogMetadata(
                './blog/en/list_i18n_technologies/frameworks/astro.md'
              ),
            },
          },
        },
        'build-tools': {
          title: t({
            en: 'Build tools',
            'en-GB': 'Build tools',
            fr: 'Outils de build',
            es: 'Herramientas de build',
            de: 'Build-Tools',
            ja: 'ビルドツール',
            ko: '빌드 도구',
            zh: '构建工具',
            it: 'Strumenti di build',
            pt: 'Ferramentas de build',
            hi: 'बिल्ड टूल्स',
            ar: 'أدوات البناء',
            ru: 'Инструменты сборки',
            tr: 'Build araçları',
            pl: 'Narzędzia build',
            id: 'Build tools',
            vi: 'Công cụ build',
            uk: 'Інструменти збірки',
          }),
          subSections: {
            vite: {
              title: 'Vite',
              default: getBlogMetadata(
                './blog/en/list_i18n_technologies/build-tools/vite.md'
              ),
            },
          },
        },
      },
    },

    concepts: {
      title: t({
        en: 'Concepts',
        'en-GB': 'Concepts',
        fr: 'Concepts',
        es: 'Conceptos',
        de: 'Konzepte',
        ja: 'コンセプト',
        ko: '개념',
        zh: '概念',
        it: 'Concetti',
        pt: 'Conceitos',
        hi: 'अवधारणाएं',
        ar: 'المفاهيم',
        ru: 'Концепции',
        tr: 'Kavramlar',
        pl: 'Koncepcje',
        id: 'Konsep',
        vi: 'Khái niệm',
        uk: 'Концепції',
      }),
      subSections: {
        'i18n-meaning': {
          title: t({
            en: 'What does i18n mean?',
            'en-GB': 'What does i18n mean?',
            fr: 'Que signifie i18n ?',
            es: '¿Qué significa i18n?',
            de: 'Was bedeutet i18n?',
            ja: 'i18n とは何か？',
            ko: 'i18n은 무엇을 의미하나요?',
            zh: 'i18n 是什么意思？',
            it: 'Cosa significa i18n?',
            pt: 'O que significa i18n?',
            hi: 'i18n का क्या अर्थ है?',
            ar: 'ماذا يعني i18n؟',
            ru: 'Что означает i18n?',
            tr: 'i18n ne anlama gelir?',
            pl: 'Co oznacza i18n?',
            id: 'Apa arti i18n?',
            vi: 'i18n nghĩa là gì?',
            uk: 'Що означає i18n?',
          }),
          default: getBlogMetadata('./blog/en/i18n_meaning.md'),
        },
        'icu-message-format': {
          title: 'ICU Message Format',
          default: getBlogMetadata('./blog/en/icu_message_format.md'),
        },
        'date-time-number-formatting-locales': {
          title: t({
            en: 'Formatting dates and numbers',
            'en-GB': 'Formatting dates and numbers',
            fr: 'Formater dates et nombres',
            es: 'Formatear fechas y números',
            de: 'Datums- und Zahlenformatierung',
            ja: '日付と数値のフォーマット',
            ko: '날짜와 숫자 포맷팅',
            zh: '日期与数字格式化',
            it: 'Formattare date e numeri',
            pt: 'Formatar datas e números',
            hi: 'दिनांक और संख्या स्वरूपण',
            ar: 'تنسيق التواريخ والأرقام',
            ru: 'Форматирование дат и чисел',
            tr: 'Tarih ve sayı biçimlendirme',
            pl: 'Formatowanie dat i liczb',
            id: 'Memformat tanggal dan angka',
            vi: 'Định dạng ngày và số',
            uk: 'Форматування дат і чисел',
          }),
          default: getBlogMetadata(
            './blog/en/date_time_number_formatting_locales.md'
          ),
        },
        'per-component-vs-centralized-i18n': {
          title: t({
            en: 'Per-component vs centralized i18n',
            'en-GB': 'Per-component vs centralised i18n',
            fr: 'i18n par composant vs centralisée',
            es: 'i18n por componente vs centralizada',
            de: 'i18n pro Komponente vs. zentralisiert',
            ja: 'コンポーネント単位 vs 集中管理の i18n',
            ko: '컴포넌트별 vs 중앙집중식 i18n',
            zh: '按组件 vs 集中式 i18n',
            it: 'i18n per componente vs centralizzata',
            pt: 'i18n por componente vs centralizada',
            hi: 'प्रति-कंपोनेंट बनाम केंद्रीकृत i18n',
            ar: 'i18n لكل مكوّن مقابل المركزية',
            ru: 'i18n по компонентам против централизованной',
            tr: 'Bileşen bazlı vs merkezi i18n',
            pl: 'i18n per komponent vs scentralizowana',
            id: 'i18n per komponen vs terpusat',
            vi: 'i18n theo component vs tập trung',
            uk: 'i18n покомпонентно проти централізованої',
          }),
          default: getBlogMetadata(
            './blog/en/per-component_vs_centralized_i18n.md'
          ),
        },
        'compiler-vs-declarative-i18n': {
          title: t({
            en: 'Compiler vs declarative i18n',
            'en-GB': 'Compiler vs declarative i18n',
            fr: 'i18n par compilateur vs déclarative',
            es: 'i18n con compilador vs declarativa',
            de: 'Compiler- vs. deklarative i18n',
            ja: 'コンパイラ型 vs 宣言型 i18n',
            ko: '컴파일러 vs 선언형 i18n',
            zh: '编译器式 vs 声明式 i18n',
            it: 'i18n con compilatore vs dichiarativa',
            pt: 'i18n com compilador vs declarativa',
            hi: 'कंपाइलर बनाम घोषणात्मक i18n',
            ar: 'i18n بالمترجم مقابل التصريحية',
            ru: 'Компиляторная против декларативной i18n',
            tr: 'Derleyici vs bildirimsel i18n',
            pl: 'i18n kompilatorowa vs deklaratywna',
            id: 'i18n compiler vs deklaratif',
            vi: 'i18n dùng compiler vs khai báo',
            uk: 'Компіляторна проти декларативної i18n',
          }),
          default: getBlogMetadata('./blog/en/compiler_vs_declarative_i18n.md'),
        },
      },
    },

    quality: {
      title: t({
        en: 'Quality and automation',
        'en-GB': 'Quality and automation',
        fr: 'Qualité et automatisation',
        es: 'Calidad y automatización',
        de: 'Qualität und Automatisierung',
        ja: '品質と自動化',
        ko: '품질과 자동화',
        zh: '质量与自动化',
        it: 'Qualità e automazione',
        pt: 'Qualidade e automação',
        hi: 'गुणवत्ता और स्वचालन',
        ar: 'الجودة والأتمتة',
        ru: 'Качество и автоматизация',
        tr: 'Kalite ve otomasyon',
        pl: 'Jakość i automatyzacja',
        id: 'Kualitas dan otomatisasi',
        vi: 'Chất lượng và tự động hóa',
        uk: 'Якість та автоматизація',
      }),
      subSections: {
        'detecting-missing-translations': {
          title: t({
            en: 'Finding missing translations',
            'en-GB': 'Finding missing translations',
            fr: 'Trouver les traductions manquantes',
            es: 'Encontrar traducciones faltantes',
            de: 'Fehlende Übersetzungen finden',
            ja: '未翻訳の検出',
            ko: '누락된 번역 찾기',
            zh: '查找缺失的翻译',
            it: 'Trovare le traduzioni mancanti',
            pt: 'Encontrar traduções ausentes',
            hi: 'अनुपलब्ध अनुवाद खोजना',
            ar: 'العثور على الترجمات الناقصة',
            ru: 'Поиск недостающих переводов',
            tr: 'Eksik çevirileri bulma',
            pl: 'Znajdowanie brakujących tłumaczeń',
            id: 'Menemukan terjemahan yang hilang',
            vi: 'Tìm bản dịch còn thiếu',
            uk: 'Пошук відсутніх перекладів',
          }),
          default: getBlogMetadata(
            './blog/en/detecting_missing_translations.md'
          ),
        },
        'i18n-testing-strategies': {
          title: t({
            en: 'Testing translations',
            'en-GB': 'Testing translations',
            fr: 'Tester les traductions',
            es: 'Probar las traducciones',
            de: 'Übersetzungen testen',
            ja: '翻訳のテスト',
            ko: '번역 테스트',
            zh: '测试翻译',
            it: 'Testare le traduzioni',
            pt: 'Testar traduções',
            hi: 'अनुवाद का परीक्षण',
            ar: 'اختبار الترجمات',
            ru: 'Тестирование переводов',
            tr: 'Çevirileri test etme',
            pl: 'Testowanie tłumaczeń',
            id: 'Menguji terjemahan',
            vi: 'Kiểm thử bản dịch',
            uk: 'Тестування перекладів',
          }),
          default: getBlogMetadata('./blog/en/i18n_testing_strategies.md'),
        },
        'i18n-in-ci-cd-pipelines': {
          title: t({
            en: 'i18n in CI/CD pipelines',
            'en-GB': 'i18n in CI/CD pipelines',
            fr: 'i18n dans les pipelines CI/CD',
            es: 'i18n en pipelines CI/CD',
            de: 'i18n in CI/CD-Pipelines',
            ja: 'CI/CD パイプラインでの i18n',
            ko: 'CI/CD 파이프라인의 i18n',
            zh: 'CI/CD 流水线中的 i18n',
            it: 'i18n nelle pipeline CI/CD',
            pt: 'i18n em pipelines CI/CD',
            hi: 'CI/CD पाइपलाइन में i18n',
            ar: 'i18n في خطوط CI/CD',
            ru: 'i18n в CI/CD-пайплайнах',
            tr: 'CI/CD süreçlerinde i18n',
            pl: 'i18n w pipeline CI/CD',
            id: 'i18n dalam pipeline CI/CD',
            vi: 'i18n trong pipeline CI/CD',
            uk: 'i18n у CI/CD-пайплайнах',
          }),
          default: getBlogMetadata('./blog/en/i18n_in_ci_cd_pipelines.md'),
        },
      },
    },

    seo: {
      title: 'SEO',
      subSections: {
        'hreflang-guide-multilingual-seo': {
          title: t({
            en: 'hreflang guide for multilingual SEO',
            'en-GB': 'hreflang guide for multilingual SEO',
            fr: 'Guide hreflang pour le SEO multilingue',
            es: 'Guía de hreflang para SEO multilingüe',
            de: 'hreflang-Leitfaden für mehrsprachiges SEO',
            ja: '多言語 SEO のための hreflang ガイド',
            ko: '다국어 SEO를 위한 hreflang 가이드',
            zh: '多语言 SEO 的 hreflang 指南',
            it: 'Guida hreflang per la SEO multilingue',
            pt: 'Guia hreflang para SEO multilíngue',
            hi: 'बहुभाषी SEO के लिए hreflang गाइड',
            ar: 'دليل hreflang لتحسين محركات البحث متعدد اللغات',
            ru: 'Руководство по hreflang для многоязычного SEO',
            tr: 'Çok dilli SEO için hreflang rehberi',
            pl: 'Przewodnik hreflang dla wielojęzycznego SEO',
            id: 'Panduan hreflang untuk SEO multibahasa',
            vi: 'Hướng dẫn hreflang cho SEO đa ngôn ngữ',
            uk: 'Посібник із hreflang для багатомовного SEO',
          }),
          default: getBlogMetadata(
            './blog/en/hreflang_guide_multilingual_seo.md'
          ),
        },
        'blog-seo-i18n-nextjs': {
          title: t({
            en: 'Multilingual SEO in Next.js',
            'en-GB': 'Multilingual SEO in Next.js',
            fr: 'SEO multilingue avec Next.js',
            es: 'SEO multilingüe en Next.js',
            de: 'Mehrsprachiges SEO in Next.js',
            ja: 'Next.js の多言語 SEO',
            ko: 'Next.js의 다국어 SEO',
            zh: 'Next.js 多语言 SEO',
            it: 'SEO multilingue in Next.js',
            pt: 'SEO multilíngue no Next.js',
            hi: 'Next.js में बहुभाषी SEO',
            ar: 'تحسين محركات البحث متعدد اللغات في Next.js',
            ru: 'Многоязычное SEO в Next.js',
            tr: 'Next.js ile çok dilli SEO',
            pl: 'Wielojęzyczne SEO w Next.js',
            id: 'SEO multibahasa di Next.js',
            vi: 'SEO đa ngôn ngữ trong Next.js',
            uk: 'Багатомовне SEO у Next.js',
          }),
          default: getBlogMetadata(
            './blog/en/nextjs-multilingual-seo-comparison.md'
          ),
        },
      },
    },

    'l10n-platform-alternative': {
      title: t({
        en: 'Localization platform alternatives',
        'en-GB': 'Localisation platform alternatives',
        fr: 'Alternatives aux plateformes de localisation',
        es: 'Alternativas a plataformas de localización',
        de: 'Alternativen zu Lokalisierungsplattformen',
        ja: 'ローカリゼーションプラットフォームの代替',
        ko: '현지화 플랫폼 대안',
        zh: '本地化平台替代方案',
        it: 'Alternative alle piattaforme di localizzazione',
        pt: 'Alternativas a plataformas de localização',
        hi: 'लोकलाइज़ेशन प्लेटफ़ॉर्म विकल्प',
        ar: 'بدائل منصات التوطين',
        ru: 'Альтернативы платформам локализации',
        tr: 'Yerelleştirme platformu alternatifleri',
        pl: 'Alternatywy dla platform lokalizacyjnych',
        id: 'Alternatif platform lokalisasi',
        vi: 'Giải pháp thay thế nền tảng bản địa hóa',
        uk: 'Альтернативи платформам локалізації',
      }),
      subSections: {
        crowdin: {
          title: 'Crowdin',
          default: getBlogMetadata(
            './blog/en/l10n_platform_alternative/crowdin.md'
          ),
        },
        lokalise: {
          title: 'Lokalise',
          default: getBlogMetadata(
            './blog/en/l10n_platform_alternative/Lokalise.md'
          ),
        },
        phrase: {
          title: 'Phrase',
          default: getBlogMetadata(
            './blog/en/l10n_platform_alternative/phrase.md'
          ),
        },
      },
    },

    'rag-powered-documentation-assistant': {
      title: t({
        en: 'RAG-powered documentation assistant',
        'en-GB': 'RAG-powered documentation assistant',
        fr: 'Assistant de documentation basé sur le RAG',
        es: 'Asistente de documentación basado en RAG',
        de: 'RAG-gestützter Dokumentationsassistent',
        ja: 'RAG を活用したドキュメントアシスタント',
        ko: 'RAG 기반 문서 어시스턴트',
        zh: '基于 RAG 的文档助手',
        it: 'Assistente alla documentazione basato su RAG',
        pt: 'Assistente de documentação com RAG',
        hi: 'RAG-आधारित दस्तावेज़ सहायक',
        ar: 'مساعد توثيق يعتمد على RAG',
        ru: 'Ассистент документации на базе RAG',
        tr: 'RAG tabanlı dokümantasyon asistanı',
        pl: 'Asystent dokumentacji oparty na RAG',
        id: 'Asisten dokumentasi berbasis RAG',
        vi: 'Trợ lý tài liệu dùng RAG',
        uk: 'Асистент документації на основі RAG',
      }),
      default: getBlogMetadata(
        './blog/en/rag_powered_documentation_assistant.md'
      ),
    },
  },
} satisfies Dictionary;

export default blogDataContent;
