import { type Dictionary, insert, t } from 'intlayer';

const scansAdminPageContent = {
  key: 'scans-admin-page',
  content: {
    categories: {
      all: t({
        en: 'All',
        'en-GB': 'All',
        fr: 'Tout',
        es: 'Todo',
        de: 'Alle',
        ja: 'すべて',
        ko: '전체',
        zh: '全部',
        it: 'Tutto',
        pt: 'Tudo',
        hi: 'सभी',
        ar: 'الكل',
        ru: 'Все',
        tr: 'Tümü',
        pl: 'Wszystko',
        id: 'Semua',
        vi: 'Tất cả',
        uk: 'Усі',
      }),
      'i18n-library': t({
        en: 'i18n libraries',
        'en-GB': 'i18n libraries',
        fr: 'Bibliothèques i18n',
        es: 'Bibliotecas i18n',
        de: 'i18n-Bibliotheken',
        ja: 'i18n ライブラリ',
        ko: 'i18n 라이브러리',
        zh: 'i18n 库',
        it: 'Librerie i18n',
        pt: 'Bibliotecas i18n',
        hi: 'i18n लाइब्रेरी',
        ar: 'مكتبات i18n',
        ru: 'Библиотеки i18n',
        tr: 'i18n kütüphaneleri',
        pl: 'Biblioteki i18n',
        id: 'Pustaka i18n',
        vi: 'Thư viện i18n',
        uk: 'Бібліотеки i18n',
      }),
      tms: t({
        en: 'TMS',
        'en-GB': 'TMS',
        fr: 'TMS',
        es: 'TMS',
        de: 'TMS',
        ja: 'TMS',
        ko: 'TMS',
        zh: 'TMS',
        it: 'TMS',
        pt: 'TMS',
        hi: 'TMS',
        ar: 'TMS',
        ru: 'TMS',
        tr: 'TMS',
        pl: 'TMS',
        id: 'TMS',
        vi: 'TMS',
        uk: 'TMS',
      }),
      'translation-proxy': t({
        en: 'Translation proxies',
        'en-GB': 'Translation proxies',
        fr: 'Proxys de traduction',
        es: 'Proxies de traducción',
        de: 'Übersetzungs-Proxys',
        ja: '翻訳プロキシ',
        ko: '번역 프록시',
        zh: '翻译代理',
        it: 'Proxy di traduzione',
        pt: 'Proxies de tradução',
        hi: 'अनुवाद प्रॉक्सी',
        ar: 'وكلاء الترجمة',
        ru: 'Прокси перевода',
        tr: 'Çeviri proxy’leri',
        pl: 'Proxy tłumaczeń',
        id: 'Proksi terjemahan',
        vi: 'Proxy dịch thuật',
        uk: 'Проксі перекладу',
      }),
      framework: t({
        en: 'Frameworks',
        'en-GB': 'Frameworks',
        fr: 'Frameworks',
        es: 'Frameworks',
        de: 'Frameworks',
        ja: 'フレームワーク',
        ko: '프레임워크',
        zh: '框架',
        it: 'Framework',
        pt: 'Frameworks',
        hi: 'फ़्रेमवर्क',
        ar: 'أطر العمل',
        ru: 'Фреймворки',
        tr: 'Çatılar',
        pl: 'Frameworki',
        id: 'Framework',
        vi: 'Framework',
        uk: 'Фреймворки',
      }),
      cms: t({
        en: 'CMS',
        'en-GB': 'CMS',
        fr: 'CMS',
        es: 'CMS',
        de: 'CMS',
        ja: 'CMS',
        ko: 'CMS',
        zh: 'CMS',
        it: 'CMS',
        pt: 'CMS',
        hi: 'CMS',
        ar: 'CMS',
        ru: 'CMS',
        tr: 'CMS',
        pl: 'CMS',
        id: 'CMS',
        vi: 'CMS',
        uk: 'CMS',
      }),
    },
    usageTitle: t({
      en: 'Technology usage',
      'en-GB': 'Technology usage',
      fr: 'Utilisation des technologies',
      es: 'Uso de tecnologías',
      de: 'Technologienutzung',
      ja: '技術の利用状況',
      ko: '기술 사용 현황',
      zh: '技术使用情况',
      it: 'Utilizzo delle tecnologie',
      pt: 'Uso de tecnologias',
      hi: 'तकनीक का उपयोग',
      ar: 'استخدام التقنيات',
      ru: 'Использование технологий',
      tr: 'Teknoloji kullanımı',
      pl: 'Wykorzystanie technologii',
      id: 'Penggunaan teknologi',
      vi: 'Mức sử dụng công nghệ',
      uk: 'Використання технологій',
    }),
    usageDescription: t({
      en: 'Based on the latest scan of each website (scanner, recursive audits and Chrome extension).',
      'en-GB':
        'Based on the latest scan of each website (scanner, recursive audits and Chrome extension).',
      fr: 'Basé sur le dernier scan de chaque site (scanner, audits récursifs et extension Chrome).',
      es: 'Basado en el último escaneo de cada sitio (escáner, auditorías recursivas y extensión de Chrome).',
      de: 'Basierend auf dem letzten Scan jeder Website (Scanner, rekursive Audits und Chrome-Erweiterung).',
      ja: '各サイトの最新スキャンに基づきます（スキャナー、再帰監査、Chrome 拡張機能）。',
      ko: '각 사이트의 최신 스캔 기준입니다 (스캐너, 재귀 감사, Chrome 확장 프로그램).',
      zh: '基于每个网站的最新扫描（扫描器、递归审计和 Chrome 扩展）。',
      it: 'Basato sull’ultima scansione di ogni sito (scanner, audit ricorsivi ed estensione Chrome).',
      pt: 'Com base na última verificação de cada site (scanner, auditorias recursivas e extensão do Chrome).',
      hi: 'हर वेबसाइट के नवीनतम स्कैन पर आधारित (स्कैनर, रिकर्सिव ऑडिट और Chrome एक्सटेंशन)।',
      ar: 'استنادًا إلى أحدث فحص لكل موقع (الماسح، والتدقيقات المتكررة، وإضافة Chrome).',
      ru: 'По последнему сканированию каждого сайта (сканер, рекурсивные аудиты и расширение Chrome).',
      tr: 'Her sitenin son taramasına göre (tarayıcı, özyinelemeli denetimler ve Chrome uzantısı).',
      pl: 'Na podstawie ostatniego skanu każdej witryny (skaner, audyty rekurencyjne i rozszerzenie Chrome).',
      id: 'Berdasarkan pemindaian terbaru setiap situs (pemindai, audit rekursif, dan ekstensi Chrome).',
      vi: 'Dựa trên lần quét gần nhất của mỗi trang (trình quét, kiểm tra đệ quy và tiện ích Chrome).',
      uk: 'На основі останнього сканування кожного сайту (сканер, рекурсивні аудити та розширення Chrome).',
    }),
    hostCount: insert(
      t({
        en: '{{count}} websites',
        'en-GB': '{{count}} websites',
        fr: '{{count}} sites',
        es: '{{count}} sitios',
        de: '{{count}} Websites',
        ja: '{{count}} サイト',
        ko: '사이트 {{count}}개',
        zh: '{{count}} 个网站',
        it: '{{count}} siti',
        pt: '{{count}} sites',
        hi: '{{count}} वेबसाइटें',
        ar: '{{count}} مواقع',
        ru: 'Сайтов: {{count}}',
        tr: '{{count}} site',
        pl: 'Witryny: {{count}}',
        id: '{{count}} situs',
        vi: '{{count}} trang web',
        uk: 'Сайтів: {{count}}',
      })
    ),
    hostsTitle: t({
      en: 'Scanned websites',
      'en-GB': 'Scanned websites',
      fr: 'Sites scannés',
      es: 'Sitios escaneados',
      de: 'Gescannte Websites',
      ja: 'スキャン済みサイト',
      ko: '스캔된 사이트',
      zh: '已扫描的网站',
      it: 'Siti scansionati',
      pt: 'Sites verificados',
      hi: 'स्कैन की गई वेबसाइटें',
      ar: 'المواقع المفحوصة',
      ru: 'Просканированные сайты',
      tr: 'Taranan siteler',
      pl: 'Przeskanowane witryny',
      id: 'Situs yang dipindai',
      vi: 'Trang web đã quét',
      uk: 'Проскановані сайти',
    }),
    clearTechnologyFilter: t({
      en: 'Clear technology filter',
      'en-GB': 'Clear technology filter',
      fr: 'Retirer le filtre de technologie',
      es: 'Quitar el filtro de tecnología',
      de: 'Technologiefilter entfernen',
      ja: '技術フィルターを解除',
      ko: '기술 필터 지우기',
      zh: '清除技术筛选',
      it: 'Rimuovi il filtro tecnologia',
      pt: 'Limpar filtro de tecnologia',
      hi: 'तकनीक फ़िल्टर हटाएँ',
      ar: 'إزالة عامل تصفية التقنية',
      ru: 'Сбросить фильтр технологии',
      tr: 'Teknoloji filtresini temizle',
      pl: 'Wyczyść filtr technologii',
      id: 'Hapus filter teknologi',
      vi: 'Xóa bộ lọc công nghệ',
      uk: 'Скинути фільтр технології',
    }),
    searchPlaceholder: t({
      en: 'Search a host…',
      'en-GB': 'Search a host…',
      fr: 'Rechercher un hôte…',
      es: 'Buscar un host…',
      de: 'Host suchen…',
      ja: 'ホストを検索…',
      ko: '호스트 검색…',
      zh: '搜索主机…',
      it: 'Cerca un host…',
      pt: 'Pesquisar um host…',
      hi: 'होस्ट खोजें…',
      ar: 'ابحث عن مضيف…',
      ru: 'Поиск хоста…',
      tr: 'Ana makine ara…',
      pl: 'Szukaj hosta…',
      id: 'Cari host…',
      vi: 'Tìm máy chủ…',
      uk: 'Пошук хоста…',
    }),
    tableHeaders: {
      host: t({
        en: 'Host',
        'en-GB': 'Host',
        fr: 'Hôte',
        es: 'Host',
        de: 'Host',
        ja: 'ホスト',
        ko: '호스트',
        zh: '主机',
        it: 'Host',
        pt: 'Host',
        hi: 'होस्ट',
        ar: 'المضيف',
        ru: 'Хост',
        tr: 'Ana makine',
        pl: 'Host',
        id: 'Host',
        vi: 'Máy chủ',
        uk: 'Хост',
      }),
      scanCount: t({
        en: 'Scans',
        'en-GB': 'Scans',
        fr: 'Scans',
        es: 'Escaneos',
        de: 'Scans',
        ja: 'スキャン数',
        ko: '스캔 수',
        zh: '扫描次数',
        it: 'Scansioni',
        pt: 'Verificações',
        hi: 'स्कैन',
        ar: 'عمليات الفحص',
        ru: 'Сканирования',
        tr: 'Taramalar',
        pl: 'Skany',
        id: 'Pemindaian',
        vi: 'Lượt quét',
        uk: 'Сканування',
      }),
      technologies: t({
        en: 'Stack',
        'en-GB': 'Stack',
        fr: 'Stack',
        es: 'Stack',
        de: 'Stack',
        ja: 'スタック',
        ko: '스택',
        zh: '技术栈',
        it: 'Stack',
        pt: 'Stack',
        hi: 'स्टैक',
        ar: 'المكدس التقني',
        ru: 'Стек',
        tr: 'Yığın',
        pl: 'Stos',
        id: 'Stack',
        vi: 'Ngăn xếp',
        uk: 'Стек',
      }),
      routing: t({
        en: 'Routing',
        'en-GB': 'Routing',
        fr: 'Routage',
        es: 'Enrutamiento',
        de: 'Routing',
        ja: 'ルーティング',
        ko: '라우팅',
        zh: '路由',
        it: 'Routing',
        pt: 'Roteamento',
        hi: 'रूटिंग',
        ar: 'التوجيه',
        ru: 'Маршрутизация',
        tr: 'Yönlendirme',
        pl: 'Routing',
        id: 'Perutean',
        vi: 'Định tuyến',
        uk: 'Маршрутизація',
      }),
      locales: t({
        en: 'Locales',
        'en-GB': 'Locales',
        fr: 'Langues',
        es: 'Idiomas',
        de: 'Sprachen',
        ja: 'ロケール',
        ko: '로케일',
        zh: '语言区域',
        it: 'Lingue',
        pt: 'Idiomas',
        hi: 'लोकेल',
        ar: 'اللغات',
        ru: 'Локали',
        tr: 'Diller',
        pl: 'Języki',
        id: 'Lokal',
        vi: 'Ngôn ngữ',
        uk: 'Локалі',
      }),
      score: t({
        en: 'Score',
        'en-GB': 'Score',
        fr: 'Score',
        es: 'Puntuación',
        de: 'Punktzahl',
        ja: 'スコア',
        ko: '점수',
        zh: '得分',
        it: 'Punteggio',
        pt: 'Pontuação',
        hi: 'स्कोर',
        ar: 'النتيجة',
        ru: 'Оценка',
        tr: 'Puan',
        pl: 'Wynik',
        id: 'Skor',
        vi: 'Điểm',
        uk: 'Оцінка',
      }),
      scannedAt: t({
        en: 'Scanned',
        'en-GB': 'Scanned',
        fr: 'Scanné le',
        es: 'Escaneado',
        de: 'Gescannt',
        ja: 'スキャン日',
        ko: '스캔 일시',
        zh: '扫描时间',
        it: 'Scansionato',
        pt: 'Verificado',
        hi: 'स्कैन किया गया',
        ar: 'تاريخ الفحص',
        ru: 'Сканирование',
        tr: 'Tarandı',
        pl: 'Zeskanowano',
        id: 'Dipindai',
        vi: 'Đã quét',
        uk: 'Сканування',
      }),
    },
    modalTitle: insert(
      t({
        en: 'Scans of {{host}}',
        'en-GB': 'Scans of {{host}}',
        fr: 'Scans de {{host}}',
        es: 'Escaneos de {{host}}',
        de: 'Scans von {{host}}',
        ja: '{{host}} のスキャン',
        ko: '{{host}} 스캔 기록',
        zh: '{{host}} 的扫描记录',
        it: 'Scansioni di {{host}}',
        pt: 'Verificações de {{host}}',
        hi: '{{host}} के स्कैन',
        ar: 'عمليات فحص {{host}}',
        ru: 'Сканирования {{host}}',
        tr: '{{host}} taramaları',
        pl: 'Skany {{host}}',
        id: 'Pemindaian {{host}}',
        vi: 'Các lượt quét của {{host}}',
        uk: 'Сканування {{host}}',
      })
    ),
    scanHeaders: {
      page: t({
        en: 'Page',
        'en-GB': 'Page',
        fr: 'Page',
        es: 'Página',
        de: 'Seite',
        ja: 'ページ',
        ko: '페이지',
        zh: '页面',
        it: 'Pagina',
        pt: 'Página',
        hi: 'पेज',
        ar: 'الصفحة',
        ru: 'Страница',
        tr: 'Sayfa',
        pl: 'Strona',
        id: 'Halaman',
        vi: 'Trang',
        uk: 'Сторінка',
      }),
      source: t({
        en: 'Source',
        'en-GB': 'Source',
        fr: 'Source',
        es: 'Origen',
        de: 'Quelle',
        ja: 'ソース',
        ko: '출처',
        zh: '来源',
        it: 'Origine',
        pt: 'Origem',
        hi: 'स्रोत',
        ar: 'المصدر',
        ru: 'Источник',
        tr: 'Kaynak',
        pl: 'Źródło',
        id: 'Sumber',
        vi: 'Nguồn',
        uk: 'Джерело',
      }),
      score: t({
        en: 'Score',
        'en-GB': 'Score',
        fr: 'Score',
        es: 'Puntuación',
        de: 'Punktzahl',
        ja: 'スコア',
        ko: '점수',
        zh: '得分',
        it: 'Punteggio',
        pt: 'Pontuação',
        hi: 'स्कोर',
        ar: 'النتيجة',
        ru: 'Оценка',
        tr: 'Puan',
        pl: 'Wynik',
        id: 'Skor',
        vi: 'Điểm',
        uk: 'Оцінка',
      }),
      stack: t({
        en: 'Stack',
        'en-GB': 'Stack',
        fr: 'Stack',
        es: 'Stack',
        de: 'Stack',
        ja: 'スタック',
        ko: '스택',
        zh: '技术栈',
        it: 'Stack',
        pt: 'Stack',
        hi: 'स्टैक',
        ar: 'المكدس التقني',
        ru: 'Стек',
        tr: 'Yığın',
        pl: 'Stos',
        id: 'Stack',
        vi: 'Ngăn xếp',
        uk: 'Стек',
      }),
      scannedAt: t({
        en: 'Scanned',
        'en-GB': 'Scanned',
        fr: 'Scanné le',
        es: 'Escaneado',
        de: 'Gescannt',
        ja: 'スキャン日',
        ko: '스캔 일시',
        zh: '扫描时间',
        it: 'Scansionato',
        pt: 'Verificado',
        hi: 'स्कैन किया गया',
        ar: 'تاريخ الفحص',
        ru: 'Сканирование',
        tr: 'Tarandı',
        pl: 'Zeskanowano',
        id: 'Dipindai',
        vi: 'Đã quét',
        uk: 'Сканування',
      }),
    },
    sources: {
      scan: t({
        en: 'Scanner',
        'en-GB': 'Scanner',
        fr: 'Scanner',
        es: 'Escáner',
        de: 'Scanner',
        ja: 'スキャナー',
        ko: '스캐너',
        zh: '扫描器',
        it: 'Scanner',
        pt: 'Scanner',
        hi: 'स्कैनर',
        ar: 'الماسح',
        ru: 'Сканер',
        tr: 'Tarayıcı',
        pl: 'Skaner',
        id: 'Pemindai',
        vi: 'Trình quét',
        uk: 'Сканер',
      }),
      recursive: t({
        en: 'Recursive audit',
        'en-GB': 'Recursive audit',
        fr: 'Audit récursif',
        es: 'Auditoría recursiva',
        de: 'Rekursives Audit',
        ja: '再帰監査',
        ko: '재귀 감사',
        zh: '递归审计',
        it: 'Audit ricorsivo',
        pt: 'Auditoria recursiva',
        hi: 'रिकर्सिव ऑडिट',
        ar: 'تدقيق متكرر',
        ru: 'Рекурсивный аудит',
        tr: 'Özyinelemeli denetim',
        pl: 'Audyt rekurencyjny',
        id: 'Audit rekursif',
        vi: 'Kiểm tra đệ quy',
        uk: 'Рекурсивний аудит',
      }),
      extension: t({
        en: 'Chrome extension',
        'en-GB': 'Chrome extension',
        fr: 'Extension Chrome',
        es: 'Extensión de Chrome',
        de: 'Chrome-Erweiterung',
        ja: 'Chrome 拡張機能',
        ko: 'Chrome 확장 프로그램',
        zh: 'Chrome 扩展',
        it: 'Estensione Chrome',
        pt: 'Extensão do Chrome',
        hi: 'Chrome एक्सटेंशन',
        ar: 'إضافة Chrome',
        ru: 'Расширение Chrome',
        tr: 'Chrome uzantısı',
        pl: 'Rozszerzenie Chrome',
        id: 'Ekstensi Chrome',
        vi: 'Tiện ích Chrome',
        uk: 'Розширення Chrome',
      }),
      background: t({
        en: 'Automatic audit',
        'en-GB': 'Automatic audit',
        fr: 'Audit automatique',
        es: 'Auditoría automática',
        de: 'Automatisches Audit',
        ja: '自動監査',
        ko: '자동 감사',
        zh: '自动审计',
        it: 'Audit automatico',
        pt: 'Auditoria automática',
        hi: 'स्वचालित ऑडिट',
        ar: 'تدقيق تلقائي',
        ru: 'Автоматический аудит',
        tr: 'Otomatik denetim',
        pl: 'Audyt automatyczny',
        id: 'Audit otomatis',
        vi: 'Kiểm tra tự động',
        uk: 'Автоматичний аудит',
      }),
    },
    noData: t({
      en: 'No scan recorded yet',
      'en-GB': 'No scan recorded yet',
      fr: 'Aucun scan enregistré pour le moment',
      es: 'Aún no hay escaneos registrados',
      de: 'Noch keine Scans gespeichert',
      ja: 'まだスキャンは記録されていません',
      ko: '아직 기록된 스캔이 없습니다',
      zh: '尚无扫描记录',
      it: 'Nessuna scansione registrata',
      pt: 'Nenhuma verificação registrada ainda',
      hi: 'अभी तक कोई स्कैन दर्ज नहीं है',
      ar: 'لا توجد عمليات فحص مسجلة بعد',
      ru: 'Сканирований пока нет',
      tr: 'Henüz kayıtlı tarama yok',
      pl: 'Brak zapisanych skanów',
      id: 'Belum ada pemindaian tercatat',
      vi: 'Chưa có lần quét nào',
      uk: 'Сканувань ще немає',
    }),
    loadingError: t({
      en: 'Failed to load the scans',
      'en-GB': 'Failed to load the scans',
      fr: 'Échec du chargement des scans',
      es: 'Error al cargar los escaneos',
      de: 'Scans konnten nicht geladen werden',
      ja: 'スキャンを読み込めませんでした',
      ko: '스캔을 불러오지 못했습니다',
      zh: '无法加载扫描记录',
      it: 'Impossibile caricare le scansioni',
      pt: 'Falha ao carregar as verificações',
      hi: 'स्कैन लोड नहीं हो सके',
      ar: 'تعذر تحميل عمليات الفحص',
      ru: 'Не удалось загрузить сканирования',
      tr: 'Taramalar yüklenemedi',
      pl: 'Nie udało się wczytać skanów',
      id: 'Gagal memuat pemindaian',
      vi: 'Không thể tải các lần quét',
      uk: 'Не вдалося завантажити сканування',
    }),
  },
  title: 'Scans admin page',
  description:
    'Admin view of the scanned websites, stored per host: which i18n library, TMS, translation proxy and framework each host uses, and its scan history.',
  tags: ['admin panel', 'scanner', 'technology usage'],
} satisfies Dictionary;

export default scansAdminPageContent;
