import type { MessageTemplate } from '../types';

export const ICU_TEMPLATES: MessageTemplate[] = [
  // ==================== BASIC ====================
  {
    id: 'icu-simple-variable',
    title: 'Simple Variable',
    description: 'Insert a single dynamic value into the translated message.',
    category: 'basic',
    dialect: 'icu',
    tags: ['greeting', 'name', 'basic'],
    template: 'Hello, {name}!',
    defaultVariables: { name: 'Alex' },
    defaultLocale: 'en',
  },
  {
    id: 'icu-multiple-variables',
    title: 'Multiple Variables',
    description: 'Insert multiple values in one message string.',
    category: 'basic',
    dialect: 'icu',
    tags: ['greeting', 'name', 'time'],
    template: 'Good {timeOfDay}, {firstName} {lastName}!',
    defaultVariables: {
      timeOfDay: 'morning',
      firstName: 'Sarah',
      lastName: 'Connor',
    },
    defaultLocale: 'en',
  },
  {
    id: 'icu-greeting-time',
    title: 'Greeting with Time',
    description: 'Dynamic greeting based on context and timestamp.',
    category: 'basic',
    dialect: 'icu',
    tags: ['greeting', 'time'],
    template: 'Welcome back {name}, you logged in at {loginTime}.',
    defaultVariables: { name: 'Aymeric', loginTime: '09:42 AM' },
    defaultLocale: 'en',
  },
  {
    id: 'icu-escape-braces',
    title: 'Escape Braces',
    description:
      'Show literal curly braces in output by quoting with single quotes.',
    category: 'basic',
    dialect: 'icu',
    tags: ['escape', 'code'],
    template:
      "To define a variable in JavaScript, use '{' const x = {val} '}'.",
    defaultVariables: { val: 42 },
    defaultLocale: 'en',
  },
  {
    id: 'icu-escape-single-quote',
    title: 'Escape Single Quote',
    description: 'Show literal single quotes by doubling them up.',
    category: 'basic',
    dialect: 'icu',
    tags: ['escape'],
    template: "Don''t hesitate to contact our customer support team.",
    defaultVariables: {},
    defaultLocale: 'en',
  },
  {
    id: 'icu-code-reference',
    title: 'Code Reference',
    description: 'Variable with code context and technical terms.',
    category: 'basic',
    dialect: 'icu',
    tags: ['code', 'technical'],
    template: 'Function `{functionName}()` failed with error code {errorCode}.',
    defaultVariables: { functionName: 'fetchUser', errorCode: 404 },
    defaultLocale: 'en',
  },
  {
    id: 'icu-variable-reuse',
    title: 'Variable Reuse',
    description: 'Same variable used multiple times throughout the message.',
    category: 'basic',
    dialect: 'icu',
    tags: ['variable', 'reuse'],
    template: '{name} sent you a message. Reply to {name} now.',
    defaultVariables: { name: 'Elena' },
    defaultLocale: 'en',
  },
  {
    id: 'icu-literal-hash',
    title: 'Literal Hash in Plural',
    description:
      "Use ''#'' inside plural to display a literal # symbol instead of count.",
    category: 'basic',
    dialect: 'icu',
    tags: ['hash', 'escape', 'plural'],
    template:
      "{count, plural, one {Issue ''#''{issueId}} other {Issues ''#''{issueId} and others}}",
    defaultVariables: { count: 1, issueId: 1042 },
    defaultLocale: 'en',
  },

  // ==================== PLURALIZATION ====================
  {
    id: 'icu-simple-plural',
    title: 'Simple Plural',
    description: 'Basic singular and plural forms for counting items.',
    category: 'pluralization',
    dialect: 'icu',
    tags: ['count', 'items', 'plural'],
    template: '{count, plural, one {# item} other {# items}}',
    defaultVariables: { count: 3 },
    defaultLocale: 'en',
  },
  {
    id: 'icu-messages-count',
    title: 'Messages Count',
    description: 'Unread messages notification with zero match.',
    category: 'pluralization',
    dialect: 'icu',
    tags: ['messages', 'notification'],
    template:
      '{count, plural, =0 {No unread messages} one {You have # unread message} other {You have # unread messages}}',
    defaultVariables: { count: 5 },
    defaultLocale: 'en',
  },
  {
    id: 'icu-files-selected',
    title: 'Files Selected',
    description: 'File selection counter in file upload component.',
    category: 'pluralization',
    dialect: 'icu',
    tags: ['files', 'selection'],
    template:
      '{count, plural, =0 {No files selected} one {# file selected ({size} MB)} other {# files selected ({size} MB)}}',
    defaultVariables: { count: 2, size: 14.5 },
    defaultLocale: 'en',
  },
  {
    id: 'icu-people-count',
    title: 'People Count',
    description: 'Number of people or attendees attending an event.',
    category: 'pluralization',
    dialect: 'icu',
    tags: ['social', 'likes'],
    template:
      '{count, plural, =0 {Nobody joined yet} one {# person joined} other {# people joined}}',
    defaultVariables: { count: 12 },
    defaultLocale: 'en',
  },
  {
    id: 'icu-plural-with-offset',
    title: 'Plural with Offset',
    description: '"You and X others" pattern using offset parameter.',
    category: 'pluralization',
    dialect: 'icu',
    tags: ['social', 'likes', 'offset'],
    template:
      '{count, plural, offset:1 =0 {Nobody liked this} =1 {You liked this} one {You and # other person liked this} other {You and # other people liked this}}',
    defaultVariables: { count: 4 },
    defaultLocale: 'en',
  },
  {
    id: 'icu-comments-with-offset',
    title: 'Comments with Offset',
    description: '"You and X others commented" pattern with offset:1.',
    category: 'pluralization',
    dialect: 'icu',
    tags: ['social', 'comments', 'offset'],
    template:
      '{count, plural, offset:1 =0 {No comments} =1 {You commented} one {You and # other user commented} other {You and # other users commented}}',
    defaultVariables: { count: 8 },
    defaultLocale: 'en',
  },
  {
    id: 'icu-days-remaining',
    title: 'Days Remaining',
    description: 'Trial or subscription days countdown display.',
    category: 'pluralization',
    dialect: 'icu',
    tags: ['subscription', 'trial'],
    template:
      '{days, plural, =0 {Your trial ends today!} one {Only # day remaining} other {# days remaining in your trial}}',
    defaultVariables: { days: 3 },
    defaultLocale: 'en',
  },
  {
    id: 'icu-duration',
    title: 'Duration',
    description: 'Time duration counter for media or download remaining time.',
    category: 'pluralization',
    dialect: 'icu',
    tags: ['time', 'duration'],
    template:
      '{minutes, plural, =0 {Less than a minute} one {# minute left} other {# minutes left}}',
    defaultVariables: { minutes: 15 },
    defaultLocale: 'en',
  },
  {
    id: 'icu-arabic-plural',
    title: 'Arabic Plural Structure',
    description:
      'The 6 required CLDR plural forms for Arabic: zero, one, two, few, many, other.',
    category: 'pluralization',
    dialect: 'icu',
    tags: ['arabic', 'cldr', 'multilingual'],
    template:
      '{count, plural, zero {لا توجد رسائل} one {رسالة واحدة} two {رسالتان} few {# رسائل} many {# رسالة} other {# رسالة}}',
    defaultVariables: { count: 3 },
    defaultLocale: 'ar',
  },
  {
    id: 'icu-exact-matches',
    title: 'Exact Value Matches',
    description:
      'Special distinct messages for exact numeric values (=0, =1, =100).',
    category: 'pluralization',
    dialect: 'icu',
    tags: ['gamification', 'achievements'],
    template:
      '{score, plural, =0 {No points yet, start playing!} =100 {Perfect score of 100!} one {# point} other {# points}}',
    defaultVariables: { score: 100 },
    defaultLocale: 'en',
  },
  {
    id: 'icu-difference-change',
    title: 'Difference / Change',
    description: 'Show positive or negative analytics metrics delta.',
    category: 'pluralization',
    dialect: 'icu',
    tags: ['analytics', 'change'],
    template:
      '{diff, plural, =0 {No change compared to last week} one {+# new user} other {+# new users}}',
    defaultVariables: { diff: 14 },
    defaultLocale: 'en',
  },
  {
    id: 'icu-russian-slavic-plural',
    title: 'Russian / Slavic Plural',
    description:
      'The 4 CLDR forms for Slavic languages (one, few, many, other): 1=one, 2-4=few, 5-20=many.',
    category: 'pluralization',
    dialect: 'icu',
    tags: ['russian', 'slavic', 'cldr'],
    template:
      '{count, plural, one {# день} few {# дня} many {# дней} other {# дня}}',
    defaultVariables: { count: 4 },
    defaultLocale: 'ru',
  },
  {
    id: 'icu-polish-plural',
    title: 'Polish Plural',
    description: 'Polish CLDR plural rules covering one, few, and many forms.',
    category: 'pluralization',
    dialect: 'icu',
    tags: ['polish', 'slavic', 'cldr'],
    template:
      '{count, plural, one {# plik} few {# pliki} many {# plików} other {# pliku}}',
    defaultVariables: { count: 22 },
    defaultLocale: 'pl',
  },
  {
    id: 'icu-two-plurals',
    title: 'Two Pluralized Nouns',
    description:
      'Two independent plurals in one sentence — each noun changes form separately.',
    category: 'pluralization',
    dialect: 'icu',
    tags: ['multiple', 'dual', 'complex'],
    template:
      'Found {files, plural, one {# file} other {# files}} across {folders, plural, one {# folder} other {# folders}}.',
    defaultVariables: { files: 12, folders: 3 },
    defaultLocale: 'en',
  },
  {
    id: 'icu-plural-formatted-number',
    title: 'Plural with Formatted Number',
    description:
      'Plural branches combined with localized currency or percentage.',
    category: 'pluralization',
    dialect: 'icu',
    tags: ['number', 'currency'],
    template:
      '{count, plural, one {You saved {amount, number, ::currency/USD} on # purchase} other {You saved {amount, number, ::currency/USD} across # purchases}}',
    defaultVariables: { count: 5, amount: 49.99 },
    defaultLocale: 'en',
  },
  {
    id: 'icu-compact-number-in-plural',
    title: 'Compact Number in Plural',
    description: 'Compact formatted large count inside plural string.',
    category: 'pluralization',
    dialect: 'icu',
    tags: ['compact', 'social', 'views'],
    template: '{views, plural, one {# view} other {# views}} this month',
    defaultVariables: { views: 2400 },
    defaultLocale: 'en',
  },

  // ==================== SELECT ====================
  {
    id: 'icu-gender-switch',
    title: 'Gender Discriminant',
    description:
      'Select appropriate pronouns and verbs based on subject gender.',
    category: 'select',
    dialect: 'icu',
    tags: ['gender', 'pronouns'],
    template:
      '{gender, select, male {He liked your post.} female {She liked your post.} other {They liked your post.}}',
    defaultVariables: { gender: 'female' },
    defaultLocale: 'en',
  },
  {
    id: 'icu-account-role',
    title: 'Account Role',
    description: 'Display permissions message based on access level.',
    category: 'select',
    dialect: 'icu',
    tags: ['roles', 'permissions', 'auth'],
    template:
      '{role, select, admin {Administrator access granted.} editor {Editor access: you can modify content.} other {Viewer access: read only.}}',
    defaultVariables: { role: 'editor' },
    defaultLocale: 'en',
  },
  {
    id: 'icu-payment-status',
    title: 'Payment Status',
    description: 'Transactional state notification for checkout flows.',
    category: 'select',
    dialect: 'icu',
    tags: ['ecommerce', 'billing', 'status'],
    template:
      '{status, select, paid {Payment succeeded! Your invoice is ready.} pending {Payment is pending confirmation.} failed {Payment failed. Please retry.} other {Status unknown.}}',
    defaultVariables: { status: 'paid' },
    defaultLocale: 'en',
  },
  {
    id: 'icu-delivery-status',
    title: 'Delivery Status',
    description: 'Shipment and delivery tracking update message.',
    category: 'select',
    dialect: 'icu',
    tags: ['tracking', 'logistics', 'shipping'],
    template:
      'Your package is currently {status, select, dispatched {on its way to your destination} delivered {delivered and waiting at your doorstep} transit {in transit between sorting hubs} other {being prepared for shipment}}.',
    defaultVariables: { status: 'transit' },
    defaultLocale: 'en',
  },
  {
    id: 'icu-file-type',
    title: 'File Type Warning',
    description: 'Contextual file processing feedback.',
    category: 'select',
    dialect: 'icu',
    tags: ['upload', 'media'],
    template:
      '{fileType, select, image {Processing preview image...} video {Transcoding video stream...} pdf {Extracting document pages...} other {Processing file...}}',
    defaultVariables: { fileType: 'pdf' },
    defaultLocale: 'en',
  },

  // ==================== ORDINAL ====================
  {
    id: 'icu-ranking-position',
    title: 'Ranking Position',
    description: 'Leaderboard or competition ranking with ordinal suffix.',
    category: 'ordinal',
    dialect: 'icu',
    tags: ['ranking', 'competition', 'ordinal'],
    template:
      'You placed {rank, selectordinal, one {#st} two {#nd} few {#rd} other {#th}} in the tournament!',
    defaultVariables: { rank: 1 },
    defaultLocale: 'en',
  },
  {
    id: 'icu-floor-number',
    title: 'Floor Number',
    description: 'Building floor navigation indicator.',
    category: 'ordinal',
    dialect: 'icu',
    tags: ['navigation', 'building', 'ordinal'],
    template:
      'The meeting room is on the {floor, selectordinal, =0 {ground floor} one {#st floor} two {#nd floor} few {#rd floor} other {#th floor}}.',
    defaultVariables: { floor: 3 },
    defaultLocale: 'en',
  },
  {
    id: 'icu-attempt-number',
    title: 'Attempt Number',
    description: 'Login or quiz attempt counter.',
    category: 'ordinal',
    dialect: 'icu',
    tags: ['security', 'attempts', 'auth'],
    template:
      'This is your {attempt, selectordinal, one {#st} two {#nd} few {#rd} other {#th}} attempt. Maximum allowed: 5.',
    defaultVariables: { attempt: 2 },
    defaultLocale: 'en',
  },
  {
    id: 'icu-anniversary',
    title: 'Anniversary',
    description: 'Anniversary or milestone celebration ordinal message.',
    category: 'ordinal',
    dialect: 'icu',
    tags: ['celebration', 'milestone'],
    template:
      'Happy {year, selectordinal, one {#st} two {#nd} few {#rd} other {#th}} work anniversary, {name}!',
    defaultVariables: { year: 5, name: 'David' },
    defaultLocale: 'en',
  },
  {
    id: 'icu-step-number',
    title: 'Step Number',
    description: 'Multi-step process or wizard indicator.',
    category: 'ordinal',
    dialect: 'icu',
    tags: ['progress', 'wizard'],
    template:
      'Step {step, selectordinal, one {#st step: Configuration} two {#nd step: Review} few {#rd step: Payment} other {#th step: Confirmation}}',
    defaultVariables: { step: 1 },
    defaultLocale: 'en',
  },
  {
    id: 'icu-week-of-month',
    title: 'Week of Month',
    description: 'Calendar week indicator within current month.',
    category: 'ordinal',
    dialect: 'icu',
    tags: ['calendar', 'date'],
    template:
      'Report for the {week, selectordinal, one {#st} two {#nd} few {#rd} other {#th}} week of {month}.',
    defaultVariables: { week: 2, month: 'October' },
    defaultLocale: 'en',
  },

  // ==================== NESTED ====================
  {
    id: 'icu-nested-select-plural',
    title: 'Select inside Plural',
    description:
      'Combine demographic or gender selection within plural counts.',
    category: 'nested',
    dialect: 'icu',
    tags: ['nested', 'complex'],
    template:
      '{count, plural, =0 {No invitations sent.} one {{gender, select, female {She was} male {He was} other {They were}} invited.} other {# people were invited.}}',
    defaultVariables: { count: 1, gender: 'female' },
    defaultLocale: 'en',
  },
  {
    id: 'icu-nested-plural-select',
    title: 'Plural inside Select',
    description: 'Role-based branching containing plural item counters.',
    category: 'nested',
    dialect: 'icu',
    tags: ['nested', 'roles', 'plural'],
    template:
      '{role, select, author {You published {count, plural, one {# article} other {# articles}}.} editor {You reviewed {count, plural, one {# submission} other {# submissions}}.} other {You viewed {count, plural, one {# post} other {# posts}}.}}',
    defaultVariables: { role: 'author', count: 7 },
    defaultLocale: 'en',
  },

  // ==================== NUMBERS ====================
  {
    id: 'icu-basic-number',
    title: 'Basic Number',
    description: 'Locale-formatted number with thousand separators.',
    category: 'numbers',
    dialect: 'icu',
    tags: ['format', 'locale', 'number'],
    template: 'Total downloads: {downloads, number}',
    defaultVariables: { downloads: 1489200 },
    defaultLocale: 'en',
  },
  {
    id: 'icu-decimal-places',
    title: 'Decimal Places',
    description: 'Fixed decimal precision rating display.',
    category: 'numbers',
    dialect: 'icu',
    tags: ['decimal', 'rating'],
    template:
      'Average customer rating: {rating, number} out of 5.0 stars ({reviews} reviews).',
    defaultVariables: { rating: 4.85, reviews: 310 },
    defaultLocale: 'en',
  },
  {
    id: 'icu-percentage',
    title: 'Percentage',
    description: 'Format fractional values as localized percentages.',
    category: 'numbers',
    dialect: 'icu',
    tags: ['percent', 'progress'],
    template: 'Battery charge level: {pct, number, percent}',
    defaultVariables: { pct: 0.84 },
    defaultLocale: 'en',
  },
  {
    id: 'icu-currency-usd',
    title: 'Currency (USD)',
    description: 'Format prices in US Dollars with symbol.',
    category: 'numbers',
    dialect: 'icu',
    tags: ['currency', 'usd', 'ecommerce'],
    template: 'Subtotal: {price, number, currency}',
    defaultVariables: { price: 29.99 },
    defaultLocale: 'en',
  },
  {
    id: 'icu-currency-eur',
    title: 'Currency (EUR)',
    description: 'Euro formatting with localized decimal placement.',
    category: 'numbers',
    dialect: 'icu',
    tags: ['currency', 'eur'],
    template: 'Prix TTC: {price, number, currency}',
    defaultVariables: { price: 45.5 },
    defaultLocale: 'fr',
  },

  // ==================== DATES & TIME ====================
  {
    id: 'icu-date-short',
    title: 'Short Date',
    description: 'Localized numeric date representation.',
    category: 'dates',
    dialect: 'icu',
    tags: ['date', 'short'],
    template: 'Invoice date: {issuedAt, date, short}',
    defaultVariables: { issuedAt: '2026-09-04' },
    defaultLocale: 'en',
  },
  {
    id: 'icu-date-long',
    title: 'Long Date',
    description: 'Full month name and year formatted to locale.',
    category: 'dates',
    dialect: 'icu',
    tags: ['date', 'long'],
    template: 'Conference scheduled for {eventDate, date, long}.',
    defaultVariables: { eventDate: '2026-11-15' },
    defaultLocale: 'en',
  },
  {
    id: 'icu-time-short',
    title: 'Short Time',
    description: 'Hour and minute time display.',
    category: 'dates',
    dialect: 'icu',
    tags: ['time', 'short'],
    template: 'Your flight departs at {departureTime, time, short}.',
    defaultVariables: { departureTime: '14:30:00' },
    defaultLocale: 'en',
  },

  // ==================== RICH TEXT ====================
  {
    id: 'icu-rich-text-links',
    title: 'Links & Strong Text',
    description: 'Embedded HTML elements with interpolated arguments.',
    category: 'rich-text',
    dialect: 'icu',
    tags: ['html', 'links', 'bold'],
    template:
      'Please agree to our <a href="{termsUrl}">Terms of Service</a> and <strong>Privacy Policy</strong>.',
    defaultVariables: { termsUrl: '/terms' },
    defaultLocale: 'en',
  },
  {
    id: 'icu-rich-text-badge',
    title: 'Badge & Component Tags',
    description: 'Wrap dynamic variables inside UI component markup.',
    category: 'rich-text',
    dialect: 'icu',
    tags: ['markup', 'components'],
    template:
      'Status: <span class="badge badge-success">{status}</span> ({updatedAgo} ago)',
    defaultVariables: { status: 'Active', updatedAgo: '2m' },
    defaultLocale: 'en',
  },

  // ==================== REAL WORLD ====================
  {
    id: 'icu-ecommerce-checkout',
    title: 'Checkout Summary',
    description: 'Complete e-commerce shopping bag statement.',
    category: 'real-world',
    dialect: 'icu',
    tags: ['checkout', 'cart', 'order'],
    template:
      '{count, plural, =0 {Your cart is empty.} one {You have 1 item in your cart for {total, number, currency}.} other {You have # items in your cart for {total, number, currency}.}}',
    defaultVariables: { count: 3, total: 89.5 },
    defaultLocale: 'en',
  },
  {
    id: 'icu-login-security',
    title: 'Security Alert',
    description:
      'Failed login security notification with device and IP context.',
    category: 'real-world',
    dialect: 'icu',
    tags: ['security', 'auth', 'alert'],
    template:
      'We detected {attempts, plural, one {a suspicious login attempt} other {# suspicious login attempts}} from {device} located in {location}.',
    defaultVariables: {
      attempts: 3,
      device: 'Chrome on macOS',
      location: 'Paris, France',
    },
    defaultLocale: 'en',
  },
  {
    id: 'icu-storage-quota',
    title: 'Storage Quota Warning',
    description: 'Cloud storage percentage and remaining capacity alert.',
    category: 'real-world',
    dialect: 'icu',
    tags: ['storage', 'cloud', 'quota'],
    template:
      'You have used {usedPct, number, percent} of your {totalStorage} GB quota ({remainingGb} GB remaining).',
    defaultVariables: { usedPct: 0.92, totalStorage: 100, remainingGb: 8 },
    defaultLocale: 'en',
  },
];
