import { t, type Dictionary } from 'intlayer';
import { type Metadata } from 'next';

const docContent = {
  key: 'doc-intlayer-with-create-react-app-metadata',
  content: {
    title: t({
      en: 'Translate your Create React App (CRA) website (i18n)',
      'en-GB': 'Translate your Create React App (CRA) website (i18n)',
      fr: 'Traduire votre site web Create React App (CRA) (i18n)',
      es: 'Traduce su sitio web Create React App (CRA) (i18n)',
      de: 'Übersetzen Sie Ihre Create React App (CRA)-Website (i18n)',
      ja: 'Create React App (CRA)のウェブサイトを翻訳する (i18n)',
      ko: 'Create React App (CRA)의 웹사이트를 번역하십시오 (i18n)',
      zh: '翻译你的Create React App (CRA)网站 (i18n)',
      it: 'Traduci il tuo sito web Create React App (CRA) (i18n)',
      pt: 'Traduza o seu site Create React App (CRA) (i18n)',
      hi: 'Create React App (CRA) के वेबसाइट को अनुवाद करें (i18n)',
      ar: 'ترجم موقعك الإلكتروني Create React App (CRA) (i18n)',
      ru: 'Переведите свой сайт Create React App (CRA) (i18n)',
    }),
    description: t({
      en: 'Discover how to make your Create React App (CRA) website multilingual. Follow the documentation to internationalize (i18n) and translate it.',
      'en-GB':
        'Discover how to make your Create React App (CRA) website multilingual. Follow the documentation to internationalize (i18n) and translate it.',
      ar: 'اكتشف كيفية جعل موقع Create React App (CRA) الخاص بك متعدد اللغات. اتبع الوثائق لتدويله (i18n) وترجمته.',
      de: 'Entdecken Sie, wie Sie Ihre Create React App (CRA)-Website mehrsprachig gestalten können. Befolgen Sie die Dokumentation, um sie zu internationalisieren (i18n) und zu übersetzen.',
      es: 'Descubre cómo hacer que tu sitio web de Create React App (CRA) sea multilingüe. Sigue la documentación para internacionalizar (i18n) y traducirlo.',
      fr: 'Découvrez comment rendre votre site Create React App (CRA) multilingue. Suivez la documentation pour l’internationaliser (i18n) et le traduire.',
      hi: 'जानें कि कैसे अपनी Create React App (CRA) वेबसाइट को बहुभाषी बनाया जाए। इसे अंतर्राष्ट्रीय बनाने (i18n) और अनुवाद करने के लिए दस्तावेज़ का पालन करें।',
      it: 'Scopri come rendere il tuo sito Create React App (CRA) multilingue. Segui la documentazione per internazionalizzare (i18n) e tradurlo.',
      ja: 'Create React App (CRA) を使用したウェブサイトを多言語化する方法を見つけましょう。国際化（i18n）して翻訳するためにドキュメントに従ってください。',
      ko: 'Create React App (CRA) 웹사이트를 다국어로 만드는 방법을 알아보세요. 국제화(i18n)하고 번역하려면 문서를 따르세요.',
      pt: 'Descubra como tornar seu site Create React App (CRA) multilíngue. Siga a documentação para internacionalizar (i18n) e traduzi-lo.',
      ru: 'Узнайте, как сделать ваш сайт Create React App (CRA) многоязычным. Следуйте документации для интернационализации (i18n) и перевода.',
      zh: '了解如何使您的 Create React App (CRA) 网站实现多语言。请遵循文档进行国际化（i18n）和翻译。',
    }),

    keywords: t({
      en: [
        'Internationalization',
        'Documentation',
        'Intlayer',
        'Create React App',
        'CRA',
        'JavaScript',
        'React',
      ],
      'en-GB': [
        'Internationalization',
        'Documentation',
        'Intlayer',
        'Create React App',
        'CRA',
        'JavaScript',
        'React',
      ],
      fr: [
        'Internationalisation',
        'Documentation',
        'Intlayer',
        'Create React App',
        'CRA',
        'JavaScript',
        'React',
      ],
      es: [
        'Internacionalización',
        'Documentación',
        'Intlayer',
        'Create React App',
        'CRA',
        'JavaScript',
        'React',
      ],
      de: [
        'Internationalisierung',
        'Dokumentation',
        'Intlayer',
        'Create React App',
        'CRA',
        'JavaScript',
        'React',
      ],
      ja: [
        '国際化',
        '文書',
        'Intlayer',
        'Create React App',
        'CRA',
        'JavaScript',
        'React',
      ],
      ko: [
        '국제화',
        '문서',
        'Intlayer',
        'Create React App',
        'CRA',
        'JavaScript',
        'React',
      ],
      zh: [
        '国际化',
        '文档',
        'Intlayer',
        'Create React App',
        'CRA',
        'JavaScript',
        'React',
      ],
      it: [
        'Internazionalizzazione',
        'Documentazione',
        'Intlayer',
        'Create React App',
        'CRA',
        'JavaScript',
        'React',
      ],
      pt: [
        'Internacionalização',
        'Documentação',
        'Intlayer',
        'Create React App',
        'CRA',
        'JavaScript',
        'React',
      ],
      hi: [
        'अंतर्राष्ट्रीयकरण',
        'डॉक्यूमेंटेशन',
        'Intlayer',
        'Create React App',
        'CRA',
        'जावास्क्रिप्ट',
        'React',
      ],
      ar: [
        'التدويل',
        'توثيق',
        'Intlayer',
        'Create React App',
        'CRA',
        'جافا سكريبت',
        'React',
      ],
      ru: [
        'Интернационализация',
        'Документация',
        'Intlayer',
        'Create React App',
        'CRA',
        'JavaScript',
        'React',
      ],
    }),
  },
} satisfies Dictionary<Metadata>;

export default docContent;
