import { t, type DeclarationContent } from 'intlayer';
import { Metadata } from 'next';

const docContent = {
  key: 'doc-intlayer-with-express-metadata',
  content: {
    title: t({
      en: 'Translate your Express backend',
      fr: 'Traduire votre Express backend',
      es: 'Traduce su Express backend',
      'en-GB': 'Translate your Express backend',
      de: 'Übersetzen Sie Ihren Express-Backend',
      ja: 'Expressのバックエンドを翻訳する',
      ko: 'Express 백엔드를 번역하십시오',
      zh: '翻译你的Express后端',
      it: 'Traduci il tuo backend Express',
      pt: 'Traduza o seu backend Express',
      hi: 'Express का बैकएंड को अनुवाद करें',
      ar: 'ترجم موقعك الإلكتروني Express',
      ru: 'Переведите свой Express бэкэнд',
    }),

    description: t({
      en: 'Discover how to make your vite backend multilingual. Follow the documentation to internationalize (i18n) and translate it.',
      'en-GB':
        'Discover how to make your vite backend multilingual. Follow the documentation to internationalize (i18n) and translate it.',
      ar: 'اكتشف كيفية جعل الواجهة الخلفية لـ vite متعددة اللغات. اتبع الوثائق لتدويل (i18n) وترجمتها.',
      de: 'Entdecken Sie, wie Sie Ihre vite-Backend mehrsprachig gestalten können. Befolgen Sie die Dokumentation, um sie zu internationalisieren (i18n) und zu übersetzen.',
      es: 'Descubre cómo hacer que tu backend de vite sea multilingüe. Sigue la documentación para internacionalizar (i18n) y traducirlo.',
      fr: 'Découvrez comment rendre votre backend vite multilingue. Suivez la documentation pour l’internationaliser (i18n) et le traduire.',
      hi: 'जानें कि कैसे अपनी vite बैकएंड को बहुभाषी बनाया जाए। इसे अंतर्राष्ट्रीय बनाने (i18n) और अनुवाद करने के लिए दस्तावेज़ का पालन करें।',
      it: 'Scopri come rendere il tuo backend vite multilingue. Segui la documentazione per internazionalizzare (i18n) e tradurlo.',
      ja: 'viteバックエンドを多言語化する方法を見つけましょう。国際化（i18n）して翻訳するためにドキュメントに従ってください。',
      ko: 'vite 백엔드를 다국어로 만드는 방법을 알아보세요. 국제화(i18n)하고 번역하려면 문서를 따르세요.',
      pt: 'Descubra como tornar seu backend vite multilíngue. Siga a documentação para internacionalizar (i18n) e traduzi-lo.',
      ru: 'Узнайте, как сделать ваш backend vite многоязычным. Следуйте документации для интернационализации (i18n) и перевода.',
      zh: '了解如何使您的 vite 后端实现多语言。请遵循文档进行国际化（i18n）和翻译。',
    }),
    keywords: t({
      en: [
        'Internationalization',
        'Documentation',
        'Intlayer',
        'Express',
        'JavaScript',
        'Backend',
      ],
      'en-GB': [
        'Internationalization',
        'Documentation',
        'Intlayer',
        'Express',
        'JavaScript',
        'Backend',
      ],
      fr: [
        'Internationalisation',
        'Documentation',
        'Intlayer',
        'Express',
        'JavaScript',
        'Backend',
      ],
      es: [
        'Internacionalización',
        'Documentación',
        'Intlayer',
        'Express',
        'JavaScript',
        'Backend',
      ],
      de: [
        'Internationalisierung',
        'Dokumentation',
        'Intlayer',
        'Express',
        'JavaScript',
        'Backend',
      ],
      ja: [
        '国際化',
        'ドキュメンテーション',
        'Intlayer',
        'Express',
        'JavaScript',
        'バックエンド',
      ],
      ko: ['국제화', '문서', 'Intlayer', 'Express', 'JavaScript', '백엔드'],
      zh: ['国际化', '文档', 'Intlayer', 'Express', 'JavaScript', '后端'],
      it: [
        'Internazionalizzazione',
        'Documentazione',
        'Intlayer',
        'Express',
        'JavaScript',
        'Backend',
      ],
      pt: [
        'Internacionalização',
        'Documentação',
        'Intlayer',
        'Express',
        'JavaScript',
        'Backend',
      ],
      hi: [
        'आंतरराष्ट्रीयकरण',
        'दस्तावेज़ीकरण',
        'Intlayer',
        'Express',
        'JavaScript',
        'बैकएंड',
      ],
      ar: ['دولية', 'توثيق', 'Intlayer', 'Express', 'JavaScript', 'الخلفية'],
      ru: [
        'Интернационализация',
        'Документация',
        'Intlayer',
        'Express',
        'JavaScript',
        'Бэкэнд',
      ],
    }),
  },
} satisfies DeclarationContent<Metadata>;

export default docContent;
