import { t, type DeclarationContent } from 'intlayer';
import { Metadata } from 'next';

const docContent = {
  key: 'doc-intlayer-with-express-metadata',
  content: {
    title: t({
      en: 'Intlayer with Express',
      'en-GB': 'Intlayer with Express',
      fr: 'Intlayer avec Express',
      es: 'Intlayer con Express',
      de: 'Intlayer mit Express',
      ja: 'ExpressとのIntlayer',
      ko: 'Express와 함께하는 Intlayer',
      zh: '与Express一起使用Intlayer',
      it: 'Intlayer con Express',
      pt: 'Intlayer com Express',
      hi: 'Express के साथ Intlayer',
      ar: 'Intlayer مع Express',
      ru: 'Intlayer с Express',
    }),

    description: t({
      en: 'Learn how to integrate Intlayer with Express to enable multilingual capabilities in your backend. This guide will show you how to configure your server to handle multiple languages, enhancing accessibility and user experience.',
      'en-GB':
        'Learn how to integrate Intlayer with Express to enable multilingual capabilities in your backend. This guide will show you how to configure your server to handle multiple languages, enhancing accessibility and user experience.',
      fr: "Apprenez à intégrer Intlayer avec Express pour activer les capacités multilingues dans votre backend. Ce guide vous montrera comment configurer votre serveur pour gérer plusieurs langues, améliorant l'accessibilité et l'expérience utilisateur.",
      es: 'Aprenda a integrar Intlayer con Express para habilitar capacidades multilingües en su backend. Esta guía le mostrará cómo configurar su servidor para manejar múltiples idiomas, mejorando la accesibilidad y la experiencia del usuario.',
      de: 'Erfahren Sie, wie Sie Intlayer mit Express integrieren, um mehrsprachige Funktionen in Ihrem Backend zu aktivieren. Diese Anleitung zeigt Ihnen, wie Sie Ihren Server konfigurieren, um mehrere Sprachen zu unterstützen, was die Barrierefreiheit und Benutzererfahrung verbessert.',
      ja: 'バックエンドで多言語機能を有効にするために、IntlayerをExpressに統合する方法を学びましょう。このガイドでは、複数の言語を処理するためのサーバーの設定方法を示し、アクセシビリティとユーザーエクスペリエンスを向上させます。',
      ko: 'Express와 함께 Intlayer를 통합하여 백엔드에서 다국어 기능을 활성화하는 방법을 알아보세요. 이 가이드는 여러 언어를 처리하는 서버 구성을 보여주어 접근성과 사용자 경험을 향상시킵니다.',
      zh: '了解如何将Intlayer与Express集成，以在后端启用多语言功能。本指南将向您展示如何配置服务器以处理多种语言，从而增强可访问性和用户体验。',
      it: 'Scopri come integrare Intlayer con Express per abilitare le capacità multilingue nel tuo backend. Questa guida ti mostrerà come configurare il tuo server per gestire più lingue, migliorando accessibilità ed esperienza utente.',
      pt: 'Aprenda a integrar o Intlayer com o Express para habilitar recursos multilíngues no seu backend. Este guia mostrará como configurar seu servidor para lidar com vários idiomas, melhorando a acessibilidade e a experiência do usuário.',
      hi: 'Express के साथ Intlayer को एकीकृत करने के लिए जानें ताकि आपके बैकएंड में बहुभाषी क्षमताएं सक्षम हो सकें। यह गाइड आपको दिखाएगा कि कई भाषाओं को संभालने के लिए अपने सर्वर को कैसे कॉन्फ़िगर करें, जिससे पहुंच और उपयोगकर्ता अनुभव को बेहतर बनाया जा सके।',
      ar: 'تعلم كيفية دمج Intlayer مع Express لتمكين القدرات متعددة اللغات في الواجهة الخلفية الخاصة بك. ستظهر لك هذه الإرشادات كيفية تكوين خادمك للتعامل مع لغات متعددة، مما يعزز من الوصول وتجربة المستخدم.',
      ru: 'Узнайте, как интегрировать Intlayer с Express, чтобы включить многоязычные возможности в вашем бэкенде. Этот справочник покажет вам, как настроить ваш сервер для поддержки нескольких языков, улучшая доступность и взаимодействие с пользователем.',
    }),
    keywords: t({
      en: [
        'Internationalization',
        'Documentation',
        'Intlayer',
        'Express',
        'JavaScript',
        'Backend',
      ],
      'en-GB': [
        'Internationalization',
        'Documentation',
        'Intlayer',
        'Express',
        'JavaScript',
        'Backend',
      ],
      fr: [
        'Internationalisation',
        'Documentation',
        'Intlayer',
        'Express',
        'JavaScript',
        'Backend',
      ],
      es: [
        'Internacionalización',
        'Documentación',
        'Intlayer',
        'Express',
        'JavaScript',
        'Backend',
      ],
      de: [
        'Internationalisierung',
        'Dokumentation',
        'Intlayer',
        'Express',
        'JavaScript',
        'Backend',
      ],
      ja: [
        '国際化',
        'ドキュメンテーション',
        'Intlayer',
        'Express',
        'JavaScript',
        'バックエンド',
      ],
      ko: ['국제화', '문서', 'Intlayer', 'Express', 'JavaScript', '백엔드'],
      zh: ['国际化', '文档', 'Intlayer', 'Express', 'JavaScript', '后端'],
      it: [
        'Internazionalizzazione',
        'Documentazione',
        'Intlayer',
        'Express',
        'JavaScript',
        'Backend',
      ],
      pt: [
        'Internacionalização',
        'Documentação',
        'Intlayer',
        'Express',
        'JavaScript',
        'Backend',
      ],
      hi: [
        'आंतरराष्ट्रीयकरण',
        'दस्तावेज़ीकरण',
        'Intlayer',
        'Express',
        'JavaScript',
        'बैकएंड',
      ],
      ar: ['دولية', 'توثيق', 'Intlayer', 'Express', 'JavaScript', 'الخلفية'],
      ru: [
        'Интернационализация',
        'Документация',
        'Intlayer',
        'Express',
        'JavaScript',
        'Бэкэнд',
      ],
    }),
  },
} satisfies DeclarationContent<Metadata>;

export default docContent;
