import { t, type Dictionary } from 'intlayer';
import { type Metadata } from 'next';

const docContent = {
  key: 'doc-intlayer-with-lynx-and-react-metadata',
  content: {
    title: t({
      en: 'Translate your Lynx and React mobile app (i18n)',
      fr: 'Traduit ton application mobile Lynx et React (i18n)',
      es: 'Traduce su aplicación móvil Lynx y React (i18n)',
      'en-GB': 'Translate your Lynx and React mobile app (i18n)',
      de: 'Übersetzen Sie Ihre Lynx- und React-Mobile-App (i18n)',
      ja: 'LynxとReactのモバイルアプリを翻訳する (i18n)',
      ko: 'Lynx와 React의 모바일 앱을 번역하십시오 (i18n)',
      zh: '翻译你的Lynx和React移动应用 (i18n)',
      it: 'Traduci il tuo app mobile Lynx e React (i18n)',
      pt: 'Traduza o seu aplicativo móvel Lynx e React (i18n)',
      hi: 'Lynx और React के मोबाइल ऐप को अनुवाद करें (i18n)',
      ar: 'ترجم تطبيق الجوال Lynx و React (i18n)',
      ru: 'Переведите свой мобильный приложение Lynx и React (i18n)',
    }),

    description: t({
      en: 'Discover how to make your Lynx and React mobile app multilingual. Follow the documentation to internationalize (i18n) and translate it.',
      fr: 'Découvrez comment rendre votre application mobile Lynx et React multilingue. Suivez la documentation pour l’internationaliser (i18n) et le traduire.',
      es: 'Descubre cómo hacer que tu aplicación móvil Lynx y React sea multilingüe. Sigue la documentación para internacionalizar (i18n) y traducirlo.',
      'en-GB':
        'Discover how to make your Lynx and React mobile app multilingual. Follow the documentation to internationalize (i18n) and translate it.',
      de: 'Entdecken Sie, wie Sie Ihre mit Lynx und React unter Verwendung des Page Router erstellte Website mehrsprachig gestalten können. Befolgen Sie die Dokumentation, um sie zu internationalisieren (i18n) und zu übersetzen.',
      ja: 'LynxとReactを使用してPage Routerを利用したウェブサイトを多言語化する方法を見つけましょう。国際化（i18n）して翻訳するためにドキュメントに従ってください。',
      ko: 'Lynx와 React를 사용하여 Page Router 웹사이트를 다국어로 만드는 방법을 알아보세요. 국제화(i18n)하고 번역하려면 문서를 따르세요.',
      zh: '了解如何使您的使用 Lynx 和 React 的 Page Router 网站实现多语言。请遵循文档进行国际化（i18n）和翻译。',
      it: 'Scopri come rendere il tuo sito web che utilizza Lynx e React multilingue. Segui la documentazione per internazionalizzare (i18n) e tradurlo.',
      pt: 'Descubra como tornar seu site que utiliza Lynx e React com Page Router multilíngue. Siga a documentação para internacionalizar (i18n) e traduzi-lo.',
      ru: 'Узнайте, как сделать ваш сайт, использующий Lynx и React, многоязычным. Следуйте документации для интернационализации (i18n) и перевода.',
      ar: 'اكتشف كيفية جعل موقعك الذي يستخدم Lynx و React مع Page Router متعدد اللغات. اتبع الوثائق لتدويله (i18n) وترجمته.',
      hi: '​लिनक्स और रिएक्ट मोबाइल ऐप को बहुभाषी बनाने के लिए जानें। इसे अंतर्राष्ट्रीयकृत (i18n) और अनुवादित करने के लिए दस्तावेज़ का पालन करें।​',
    }),
    keywords: t({
      en: [
        'Internationalization',
        'Documentation',
        'Intlayer',
        'Vite',
        'React',
        'Lynx',
        'JavaScript',
      ],
      fr: [
        'Internationalisation',
        'Documentation',
        'Intlayer',
        'Vite',
        'React',
        'Lynx',
        'JavaScript',
      ],
      es: [
        'Internacionalización',
        'Documentación',
        'Intlayer',
        'Vite',
        'React',
        'Lynx',
        'JavaScript',
      ],
      de: [
        'Internationalisierung',
        'Dokumentation',
        'Intlayer',
        'Vite',
        'React',
        'Lynx',
        'JavaScript',
      ],
      ja: [
        '国際化',
        'ドキュメンテーション',
        'Intlayer',
        'Vite',
        'React',
        'Lynx',
        'JavaScript',
      ],
      ko: ['국제화', '문서', 'Intlayer', 'Vite', 'React', 'Lynx', 'JavaScript'],
      zh: ['国际化', '文档', 'Intlayer', 'Vite', 'React', 'Lynx', 'JavaScript'],
      it: [
        'Internazionalizzazione',
        'Documentazione',
        'Intlayer',
        'Vite',
        'React',
        'Lynx',
        'JavaScript',
      ],
      pt: [
        'Internacionalização',
        'Documentação',
        'Intlayer',
        'Vite',
        'React',
        'Lynx',
        'JavaScript',
      ],
      hi: [
        'अंतर्राष्ट्रीयकरण',
        'दस्तावेज़ीकरण',
        'Intlayer',
        'Vite',
        'React',
        'Lynx',
        'JavaScript',
      ],
      ar: [
        'التدويل',
        'ت Documentation',
        'Intlayer',
        'Vite',
        'React',
        'Lynx',
        'JavaScript',
      ],
      ru: [
        ' интернационализация',
        'Документация',
        'Intlayer',
        'Vite',
        'React',
        'Lynx',
        'JavaScript',
      ],
      'en-GB': [
        'Internationalization',
        'Documentation',
        'Intlayer',
        'Vite',
        'React',
        'Lynx',
        'JavaScript',
      ],
    }),
  },
} satisfies Dictionary<Metadata>;

export default docContent;
