import { t, type Dictionary } from 'intlayer';
import { type Metadata } from 'next';

const docContent = {
  key: 'doc-intlayer-with-nextjs-15-metadata',
  content: {
    title: t({
      en: 'Translate your Next.js 15 website',
      fr: 'Traduire votre site web Next.js 15',
      es: 'Traduce su sitio web Next.js 15',
      'en-GB': 'Translate your Next.js 15 website',
      de: 'Übersetzen Sie Ihre Next.js 15-Website',
      ja: 'Next.js 15のウェブサイトを翻訳する',
      ko: 'Next.js 15의 웹사이트를 번역하십시오',
      zh: '翻译你的Next.js 15网站',
      it: 'Traduci il tuo sito web Next.js 15',
      pt: 'Traduza o seu site Next.js 15',
      hi: 'Next.js 15 के वेबसाइट को अनुवाद करें',
      ar: 'ترجم موقعك الإلكتروني Next.js 15',
      ru: 'Переведите свой сайт Next.js 15',
    }),

    description: t({
      en: 'Discover how to make your Next.js 15 website multilingual. Follow the documentation to internationalize (i18n) and translate it.',
      'en-GB':
        'Discover how to make your Next.js 15 website multilingual. Follow the documentation to internationalize (i18n) and translate it.',
      ar: 'اكتشف كيفية جعل موقع Next.js 15 الخاص بك متعدد اللغات. اتبع الوثائق لتدويل (i18n) وترجمته.',
      de: 'Entdecken Sie, wie Sie Ihre Next.js 15-Website mehrsprachig gestalten. Befolgen Sie die Dokumentation, um sie zu internationalisieren (i18n) und zu übersetzen.',
      es: 'Descubre cómo hacer que tu sitio web de Next.js 15 sea multilingüe. Sigue la documentación para internacionalizar (i18n) y traducirlo.',
      fr: 'Découvrez comment rendre votre site Next.js 15 multilingue. Suivez la documentation pour l’internationaliser (i18n) et le traduire.',
      hi: 'जानें कि कैसे अपनी Next.js 15 वेबसाइट को बहुभाषी बनाया जाए। इसे अंतर्राष्ट्रीय बनाने (i18n) और अनुवाद करने के लिए दस्तावेज़ का पालन करें।',
      it: 'Scopri come rendere il tuo sito Next.js 15 multilingue. Segui la documentazione per internazionalizzare (i18n) e tradurlo.',
      ja: 'Next.js 15のウェブサイトを多言語化する方法を見つけましょう。国際化（i18n）して翻訳するためにドキュメントに従ってください。',
      ko: 'Next.js 15 웹사이트를 다국어로 만드는 방법을 알아보세요. 국제화(i18n)하고 번역하려면 문서를 따르세요.',
      pt: 'Descubra como tornar seu site Next.js 15 multilíngue. Siga a documentação para internacionalizar (i18n) e traduzi-lo.',
      ru: 'Узнайте, как сделать ваш сайт на Next.js 15 многоязычным. Следуйте документации для интернационализации (i18n) и перевода.',
      zh: '了解如何使您的 Next.js 15 网站实现多语言。请遵循文档进行国际化（i18n）和翻译。',
    }),

    keywords: t({
      en: [
        'Internationalization',
        'Documentation',
        'Intlayer',
        'Next.js 15',
        'JavaScript',
        'React',
      ],
      fr: [
        'Internationalisation',
        'Documentation',
        'Intlayer',
        'Next.js 15',
        'JavaScript',
        'React',
      ],
      es: [
        'Internacionalización',
        'Documentación',
        'Intlayer',
        'Next.js 15',
        'JavaScript',
        'React',
      ],
      'en-GB': [
        'Internationalization',
        'Documentation',
        'Intlayer',
        'Next.js 15',
        'JavaScript',
        'React',
      ],
      de: [
        'Internationalisierung',
        'Dokumentation',
        'Intlayer',
        'Next.js 15',
        'JavaScript',
        'React',
      ],
      ja: [
        '国際化',
        'ドキュメント',
        'Intlayer',
        'Next.js 15',
        'JavaScript',
        'React',
      ],
      ko: ['국제화', '문서', 'Intlayer', 'Next.js 15', 'JavaScript', 'React'],
      zh: ['国际化', '文档', 'Intlayer', 'Next.js 15', 'JavaScript', 'React'],
      it: [
        'Internazionalizzazione',
        'Documentazione',
        'Intlayer',
        'Next.js 15',
        'JavaScript',
        'React',
      ],
      pt: [
        'Internacionalização',
        'Documentação',
        'Intlayer',
        'Next.js 15',
        'JavaScript',
        'React',
      ],
      hi: [
        'अंतर्राष्ट्रीयकरण',
        'दस्तावेज़',
        'Intlayer',
        'Next.js 15',
        'JavaScript',
        'React',
      ],
      ar: ['التدويل', 'توثيق', 'Intlayer', 'Next.js 15', 'JavaScript', 'React'],
      ru: [
        'Интернационализация',
        'Документация',
        'Intlayer',
        'Next.js 15',
        'JavaScript',
        'React',
      ],
    }),
  },
} satisfies Dictionary<Metadata>;

export default docContent;
