import { t, type DeclarationContent } from 'intlayer';
import { Metadata } from 'next';

const docContent = {
  key: 'doc-intlayer-with-nextjs-14-metadata',
  content: {
    title: t({
      en: 'Intlayer with Next.js 14 and App Router',
      fr: 'Intlayer avec Next.js 14 et App Router',
      es: 'Intlayer con Next.js 14 y App Router',
      'en-GB': 'Intlayer with Next.js 14 and App Router',
      de: 'Intlayer mit Next.js 14 und App Router',
      ja: 'Next.js 14とApp Routerを使用したIntlayer',
      ko: 'Next.js 14 및 App Router와 함께하는 Intlayer',
      zh: '与 Next.js 14 和 App Router 一起使用的 Intlayer',
      it: 'Intlayer con Next.js 14 e App Router',
      pt: 'Intlayer com Next.js 14 e App Router',
      hi: 'Next.js 14 और App Router के साथ Intlayer',
      ar: 'Intlayer مع Next.js 14 و App Router',
      ru: 'Intlayer с Next.js 14 и App Router',
    }),

    description: t({
      en: 'Discover how to set up Intlayer with Next.js 14 to make your website multilingual. Follow the steps in this online documentation to set up your project in a few minutes.',
      fr: 'Découvrez comment configurer Intlayer avec Next.js 14 pour rendre votre site web multilingue. Suivez les étapes de cette documentation en ligne pour mettre en place votre projet en quelques minutes.',
      es: 'Descubra cómo configurar Intlayer con Next.js 14 para hacer que su sitio web sea multilingüe. Siga los pasos de esta documentación en línea para configurar su proyecto en unos minutos.',
      'en-GB':
        'Discover how to set up Intlayer with Next.js 14 to make your website multilingual. Follow the steps in this online documentation to set up your project in a few minutes.',
      de: 'Erfahren Sie, wie Sie Intlayer mit Next.js 14 einrichten, um Ihre Website mehrsprachig zu gestalten. Befolgen Sie die Schritte in dieser Online-Dokumentation, um Ihr Projekt in nur wenigen Minuten einzurichten.',
      ja: 'Next.js 14でIntlayerを設定して、ウェブサイトを多言語化する方法を見つけましょう。このオンラインドキュメントの手順に従って、数分でプロジェクトを設定できます。',
      ko: 'Next.js 14와 함께 Intlayer를 설정하여 웹사이트를 다국어화하는 방법을 알아보세요. 이 온라인 문서의 단계를 따라 몇 분 만에 프로젝트를 설정하세요.',
      zh: '了解如何使用 Next.js 14 设置 Intlayer，使您的网站支持多语言。按照本在线文档中的步骤，几分钟内即可设置您的项目。',
      it: 'Scopri come configurare Intlayer con Next.js 14 per rendere il tuo sito web multilingue. Segui i passaggi in questa documentazione online per impostare il tuo progetto in pochi minuti.',
      pt: 'Descubra como configurar Intlayer com Next.js 14 para tornar seu site multilíngue. Siga as etapas nesta documentação online para configurar seu projeto em poucos minutos.',
      hi: 'Next.js 14 के साथ Intlayer को सेटअप करने के लिए जानें जिससे आपका वेबसाइट बहुभाषी हो सके। इस ऑनलाइन दस्तावेज़ में दिए गए चरणों का पालन करें और अपने प्रोजेक्ट को कुछ ही मिनटों में सेट करें।',
      ar: 'اكتشف كيف يمكنك إعداد Intlayer مع Next.js 14 لجعل موقعك متعدد اللغات. اتبع الخطوات في هذه الوثيقة عبر الإنترنت لإعداد مشروعك في بضع دقائق.',
      ru: 'Узнайте, как настроить Intlayer с Next.js 14, чтобы ваш веб-сайт был многоязычным. Следуйте инструкциям в этой онлайн-документации, чтобы настроить проект за несколько минут.',
    }),
    keywords: t({
      en: [
        'Internationalization',
        'Documentation',
        'Intlayer',
        'Next.js 14',
        'JavaScript',
        'React',
      ],
      fr: [
        'Internationalisation',
        'Documentation',
        'Intlayer',
        'Next.js 14',
        'JavaScript',
        'React',
      ],
      es: [
        'Internacionalización',
        'Documentación',
        'Intlayer',
        'Next.js 14',
        'JavaScript',
        'React',
      ],
      'en-GB': [
        'Internationalization',
        'Documentation',
        'Intlayer',
        'Next.js 14',
        'JavaScript',
        'React',
      ],
      de: [
        'Internationalisierung',
        'Dokumentation',
        'Intlayer',
        'Next.js 14',
        'JavaScript',
        'React',
      ],
      ja: [
        '国際化',
        'ドキュメンテーション',
        'Intlayer',
        'Next.js 14',
        'JavaScript',
        'React',
      ],
      ko: ['국제화', '문서화', 'Intlayer', 'Next.js 14', 'JavaScript', 'React'],
      zh: ['国际化', '文档', 'Intlayer', 'Next.js 14', 'JavaScript', 'React'],
      it: [
        'Internazionalizzazione',
        'Documentazione',
        'Intlayer',
        'Next.js 14',
        'JavaScript',
        'React',
      ],
      pt: [
        'Internacionalização',
        'Documentação',
        'Intlayer',
        'Next.js 14',
        'JavaScript',
        'React',
      ],
      hi: [
        'अंतर्राष्ट्रीयकरण',
        'शक्ति',
        'Intlayer',
        'Next.js 14',
        'जावास्क्रिप्ट',
        'React',
      ],
      ar: [
        'التدوين الدولي',
        'الوثائق',
        'Intlayer',
        'Next.js 14',
        'جافا سكريبت',
        'React',
      ],
      ru: [
        'Интернационализация',
        'Документация',
        'Intlayer',
        'Next.js 14',
        'JavaScript',
        'React',
      ],
    }),
  },
} satisfies DeclarationContent<Metadata>;

export default docContent;
