import { t, type DeclarationContent } from 'intlayer';
import { type Metadata } from 'next';

const docContent = {
  key: 'doc-intlayer-with-nextjs-14-metadata',
  content: {
    title: t({
      en: 'Translate your Next.js 14 and App Router website',
      fr: 'Traduire votre site web Next.js 14 et App Router',
      es: 'Traduce su sitio web Next.js 14 y App Router',
      'en-GB': 'Translate your Next.js 14 and App Router website',
      de: 'Übersetzen Sie Ihre Next.js 14 und App Router-Website',
      ja: 'Next.js 14とApp Routerのウェブサイトを翻訳する',
      ko: 'Next.js 14와 App Router의 웹사이트를 번역하십시오',
      zh: '翻译你的Next.js 14和App Router网站',
      it: 'Traduci il tuo sito web Next.js 14 e App Router',
      pt: 'Traduza o seu site Next.js 14 e App Router',
      hi: 'Next.js 14 और App Router के वेबसाइट को अनुवाद करें',
      ar: 'ترجم موقعك الإلكتروني Next.js 14 و App Router',
      ru: 'Переведите свой сайт Next.js 14 и App Router',
    }),

    description: t({
      en: 'Discover how to make your Next.js 14 App Router website multilingual. Follow the documentation to internationalize (i18n) and translate it.',
      'en-GB':
        'Discover how to make your Next.js 14 App Router website multilingual. Follow the documentation to internationalize (i18n) and translate it.',
      ar: 'اكتشف كيفية جعل موقع Next.js 14 App Router الخاص بك متعدد اللغات. اتبع الوثائق لتدويل (i18n) وترجمته.',
      de: 'Entdecken Sie, wie Sie Ihre Next.js 14 App Router-Website mehrsprachig gestalten. Befolgen Sie die Dokumentation, um sie zu internationalisieren (i18n) und zu übersetzen.',
      es: 'Descubre cómo hacer que tu sitio web de Next.js 14 App Router sea multilingüe. Sigue la documentación para internacionalizar (i18n) y traducirlo.',
      fr: 'Découvrez comment rendre votre site Next.js 14 App Router multilingue. Suivez la documentation pour l’internationaliser (i18n) et le traduire.',
      hi: 'जानें कि कैसे अपनी Next.js 14 App Router वेबसाइट को बहुभाषी बनाया जाए। इसे अंतर्राष्ट्रीय बनाने (i18n) और अनुवाद करने के लिए दस्तावेज़ का पालन करें।',
      it: 'Scopri come rendere il tuo sito Next.js 14 App Router multilingue. Segui la documentazione per internazionalizzare (i18n) e tradurlo.',
      ja: 'Next.js 14 App Routerのウェブサイトを多言語化する方法を見つけましょう。国際化（i18n）して翻訳するためにドキュメントに従ってください。',
      ko: 'Next.js 14 App Router 웹사이트를 다국어로 만드는 방법을 알아보세요. 국제화(i18n)하고 번역하려면 문서를 따르세요.',
      pt: 'Descubra como tornar seu site Next.js 14 App Router multilíngue. Siga a documentação para internacionalizar (i18n) e traduzi-lo.',
      ru: 'Узнайте, как сделать ваш сайт на Next.js 14 App Router многоязычным. Следуйте документации для интернационализации (i18n) и перевода.',
      zh: '了解如何使您的 Next.js 14 App Router 网站实现多语言。请遵循文档进行国际化（i18n）和翻译。',
    }),
    keywords: t({
      en: [
        'Internationalization',
        'Documentation',
        'Intlayer',
        'Next.js 14',
        'JavaScript',
        'React',
      ],
      fr: [
        'Internationalisation',
        'Documentation',
        'Intlayer',
        'Next.js 14',
        'JavaScript',
        'React',
      ],
      es: [
        'Internacionalización',
        'Documentación',
        'Intlayer',
        'Next.js 14',
        'JavaScript',
        'React',
      ],
      'en-GB': [
        'Internationalization',
        'Documentation',
        'Intlayer',
        'Next.js 14',
        'JavaScript',
        'React',
      ],
      de: [
        'Internationalisierung',
        'Dokumentation',
        'Intlayer',
        'Next.js 14',
        'JavaScript',
        'React',
      ],
      ja: [
        '国際化',
        'ドキュメンテーション',
        'Intlayer',
        'Next.js 14',
        'JavaScript',
        'React',
      ],
      ko: ['국제화', '문서화', 'Intlayer', 'Next.js 14', 'JavaScript', 'React'],
      zh: ['国际化', '文档', 'Intlayer', 'Next.js 14', 'JavaScript', 'React'],
      it: [
        'Internazionalizzazione',
        'Documentazione',
        'Intlayer',
        'Next.js 14',
        'JavaScript',
        'React',
      ],
      pt: [
        'Internacionalização',
        'Documentação',
        'Intlayer',
        'Next.js 14',
        'JavaScript',
        'React',
      ],
      hi: [
        'अंतर्राष्ट्रीयकरण',
        'शक्ति',
        'Intlayer',
        'Next.js 14',
        'जावास्क्रिप्ट',
        'React',
      ],
      ar: [
        'التدوين الدولي',
        'الوثائق',
        'Intlayer',
        'Next.js 14',
        'جافا سكريبت',
        'React',
      ],
      ru: [
        'Интернационализация',
        'Документация',
        'Intlayer',
        'Next.js 14',
        'JavaScript',
        'React',
      ],
    }),
  },
} satisfies DeclarationContent<Metadata>;

export default docContent;
