import { t, type DeclarationContent } from 'intlayer';
import { type Metadata } from 'next';

const docContent = {
  key: 'doc-intlayer-with-nextjs-page-router-metadata',
  content: {
    title: t({
      en: 'Translate your Next.js and Page Router website',
      fr: 'Traduire votre site web Next.js et Page Router',
      es: 'Traduce su sitio web Next.js y Page Router',
      'en-GB': 'Translate your Next.js and Page Router website',
      de: 'Übersetzen Sie Ihre Next.js und Page Router-Website',
      ja: 'Next.jsとPage Routerのウェブサイトを翻訳する',
      ko: 'Next.js와 페이지 라우터의 웹사이트를 번역하십시오',
      zh: '翻译你的Next.js和Page Router网站',
      it: 'Traduci il tuo sito web Next.js e Page Router',
      pt: 'Traduza o seu site Next.js e Page Router',
      hi: 'Next.js और पृष्ठ राउटर के वेबसाइट को अनुवाद करें',
      ar: 'ترجم موقعك الإلكتروني Next.js و Page Router',
      ru: 'Переведите свой сайт Next.js и Page Router',
    }),

    description: t({
      en: 'Discover how to make your Next.js using Page Router website multilingual. Follow the documentation to internationalize (i18n) and translate it.',
      'en-GB':
        'Discover how to make your Next.js using Page Router website multilingual. Follow the documentation to internationalize (i18n) and translate it.',
      ar: 'اكتشف كيفية جعل موقع Next.js باستخدام Page Router الخاص بك متعدد اللغات. اتبع الوثائق لتدويل (i18n) وترجمته.',
      de: 'Entdecken Sie, wie Sie Ihre Next.js-Website mit Page Router mehrsprachig gestalten können. Befolgen Sie die Dokumentation, um sie zu internationalisieren (i18n) und zu übersetzen.',
      es: 'Descubre cómo hacer que tu sitio web de Next.js usando Page Router sea multilingüe. Sigue la documentación para internacionalizar (i18n) y traducirlo.',
      fr: 'Découvrez comment rendre votre site Next.js utilisant Page Router multilingue. Suivez la documentation pour l’internationaliser (i18n) et le traduire.',
      hi: 'जानें कि कैसे अपनी Page Router का उपयोग करते हुए Next.js वेबसाइट को बहुभाषी बनाया जाए। इसे अंतर्राष्ट्रीय बनाने (i18n) और अनुवाद करने के लिए दस्तावेज़ का पालन करें।',
      it: 'Scopri come rendere il tuo sito Next.js che utilizza Page Router multilingue. Segui la documentazione per internazionalizzare (i18n) e tradurlo.',
      ja: 'Page Routerを使用したNext.jsのウェブサイトを多言語化する方法を見つけましょう。国際化（i18n）して翻訳するためにドキュメントに従ってください。',
      ko: 'Page Router를 사용하는 Next.js 웹사이트를 다국어로 만드는 방법을 알아보세요. 국제화(i18n)하고 번역하려면 문서를 따르세요.',
      pt: 'Descubra como tornar seu site Next.js usando Page Router multilíngue. Siga a documentação para internacionalizar (i18n) e traduzi-lo.',
      ru: 'Узнайте, как сделать ваш сайт на Next.js с использованием Page Router многоязычным. Следуйте документации для интернационализации (i18n) и перевода.',
      zh: '了解如何使您的使用Page Router的Next.js网站实现多语言。请遵循文档进行国际化（i18n）和翻译。',
    }),
    keywords: t({
      en: [
        'Internationalization',
        'Documentation',
        'Intlayer',
        'Page Router',
        'Next.js',
        'JavaScript',
        'React',
      ],
      'en-GB': [
        'Internationalization',
        'Documentation',
        'Intlayer',
        'Page Router',
        'Next.js',
        'JavaScript',
        'React',
      ],
      fr: [
        'Internationalisation',
        'Documentation',
        'Page Router',
        'Intlayer',
        'Next.js',
        'JavaScript',
        'React',
      ],
      es: [
        'Internationalization',
        'Documentación',
        'Page Router',
        'Intlayer',
        'Next.js',
        'JavaScript',
        'React',
      ],
      de: [
        'Internationalisierung',
        'Dokumentation',
        'Page Router',
        'Intlayer',
        'Next.js',
        'JavaScript',
        'React',
      ],
      it: [
        'Internazionalizzazione',
        'Documentazione',
        'Page Router',
        'Intlayer',
        'Next.js',
        'JavaScript',
        'React',
      ],
      ja: [
        '国際化',
        'ドキュメンテーション',
        'Intlayer',
        'ページルーター',
        'Next.js',
        'JavaScript',
        'React',
      ],
      ko: [
        '국제화',
        '문서',
        'Intlayer',
        '페이지 라우터',
        'Next.js',
        'JavaScript',
        'React',
      ],
      zh: [
        '国际化',
        '文档',
        'Intlayer',
        '页面路由',
        'Next.js',
        'JavaScript',
        '反应',
      ],
      pt: [
        'Internacionalização',
        'Documentação',
        'Intlayer',
        'Page Router',
        'Next.js',
        'JavaScript',
        'React',
      ],
      hi: [
        'अंतर्राष्ट्रीयकरण',
        'दस्तावेज़ीकरण',
        'Intlayer',
        'पृष्ठ राउटर',
        'Next.js',
        'जावास्क्रिप्ट',
        'React',
      ],
      ar: [
        'التدوين الدولي',
        'الوثائق',
        'Intlayer',
        'جهاز التوجيه للصفحة',
        'Next.js',
        'جافا سكريبت',
        'رد فعل',
      ],
      ru: [
        'Международализация',
        'Документация',
        'Intlayer',
        'Маршрутизатор страниц',
        'Next.js',
        'JavaScript',
        'React',
      ],
    }),
  },
} satisfies DeclarationContent<Metadata>;

export default docContent;
