import { GithubRoutes, PagesRoutes } from '@/Routes';
import { DocData } from '@components/DocPage/types';
import { Dictionary, t } from 'intlayer';

const docContent = {
  key: 'doc-intlayer-with-vite-solid-metadata',
  content: {
    docName: 'intlayer_with_vite_solid',
    url: PagesRoutes.Doc_Environment_ViteAndSolid,
    githubUrl: GithubRoutes.IntlayerWithViteSolid,
    createdAt: '2025-04-18',
    updatedAt: '2025-04-18',
    title: t({
      en: 'Translate your Vite and Solid website (i18n)',
      fr: 'Traduire votre site web Vite et Solid (i18n)',
      es: 'Traduce su sitio web Vite y Solid (i18n)',
      'en-GB': 'Translate your Vite and Solid website (i18n)',
      de: 'Übersetzen Sie Ihre Vite und Solid-Website (i18n)',
      ja: 'ViteとSolidのウェブサイトを翻訳する (i18n)',
      ko: 'Vite와 Solid의 웹사이트를 번역하십시오 (i18n)',
      zh: '翻译你的Vite和Solid网站 (i18n)',
      it: 'Traduci il tuo sito web Vite e Solid (i18n)',
      pt: 'Traduza o seu site Vite e Solid (i18n)',
      hi: 'Vite और Solid के वेबसाइट को अनुवाद करें (i18n)',
      ar: 'ترجم موقعك الإلكتروني Vite و Solid (i18n)',
      ru: 'Переведите свой сайт Vite и Solid (i18n)',
    }),

    description: t({
      en: 'Discover how to make your Vite and Solid website multilingual. Follow the documentation to internationalize (i18n) and translate it.',
      'en-GB':
        'Discover how to make your Vite and Solid website multilingual. Follow the documentation to internationalise (i18n) and translate it.',
      ar: 'اكتشف كيفية جعل موقعك الإلكتروني باستخدام Vite وSolid متعدد اللغات. اتبع الوثائق لتدويله (i18n) وترجمته.',
      de: 'Erfahren Sie, wie Sie Ihre mit Vite und Solid erstellte Website mehrsprachig gestalten können. Folgen Sie der Dokumentation zur Internationalisierung (i18n) und Übersetzung.',
      es: 'Descubre cómo hacer que tu sitio web con Vite y Solid sea multilingüe. Sigue la documentación para internacionalizarlo (i18n) y traducirlo.',
      fr: 'Découvrez comment rendre votre site web avec Vite et Solid multilingue. Suivez la documentation pour l’internationaliser (i18n) et le traduire.',
      hi: 'जानें कि Vite और Solid का उपयोग करके अपनी वेबसाइट को बहुभाषी कैसे बनाएं। इसे अंतर्राष्ट्रीय (i18n) और अनुवादित करने के लिए प्रलेखन का पालन करें।',
      it: 'Scopri come rendere multilingue il tuo sito web con Vite e Solid. Segui la documentazione per internazionalizzarlo (i18n) e tradurlo.',
      ja: 'ViteとSolidを使ったウェブサイトを多言語対応にする方法を学びましょう。国際化（i18n）と翻訳のためにドキュメントに従ってください。',
      ko: 'Vite와 Solid를 사용한 웹사이트를 다국어로 만드는 방법을 알아보세요. 국제화(i18n) 및 번역을 위해 문서를 참조하세요.',
      pt: 'Descubra como tornar seu site com Vite e Solid multilíngue. Siga a documentação para internacionalizá-lo (i18n) e traduzi-lo.',
      ru: 'Узнайте, как сделать ваш сайт на Vite и Solid многоязычным. Следуйте документации для интернационализации (i18n) и перевода.',
      zh: '了解如何使您使用 Vite 和 Solid 构建的网站实现多语言支持。请参阅文档以进行国际化（i18n）和翻译。',
    }),
    keywords: t({
      en: [
        'Internationalization',
        'Documentation',
        'Intlayer',
        'Vite',
        'Solid',
        'JavaScript',
      ],
      fr: [
        'Internationalisation',
        'Documentation',
        'Intlayer',
        'Vite',
        'Solid',
        'JavaScript',
      ],
      es: [
        'Internacionalización',
        'Documentación',
        'Intlayer',
        'Vite',
        'Solid',
        'JavaScript',
      ],
      de: [
        'Internationalisierung',
        'Dokumentation',
        'Intlayer',
        'Vite',
        'Solid',
        'JavaScript',
      ],
      ja: [
        '国際化',
        'ドキュメンテーション',
        'Intlayer',
        'Vite',
        'Solid',
        'JavaScript',
      ],
      ko: ['국제화', '문서', 'Intlayer', 'Vite', 'Solid', 'JavaScript'],
      zh: ['国际化', '文档', 'Intlayer', 'Vite', 'Solid', 'JavaScript'],
      it: [
        'Internazionalizzazione',
        'Documentazione',
        'Intlayer',
        'Vite',
        'Solid',
        'JavaScript',
      ],
      pt: [
        'Internacionalização',
        'Documentação',
        'Intlayer',
        'Vite',
        'Solid',
        'JavaScript',
      ],
      hi: [
        'अंतर्राष्ट्रीयकरण',
        'दस्तावेज़ीकरण',
        'Intlayer',
        'Vite',
        'Solid',
        'JavaScript',
      ],
      ar: [
        'التدويل',
        'ت Documentation',
        'Intlayer',
        'Vite',
        'Solid',
        'JavaScript',
      ],
      ru: [
        ' интернационализация',
        'Документация',
        'Intlayer',
        'Vite',
        'Solid',
        'JavaScript',
      ],
      'en-GB': [
        'Internationalization',
        'Documentation',
        'Intlayer',
        'Vite',
        'Solid',
        'JavaScript',
      ],
    }),
  },
} satisfies Dictionary<DocData>;

export default docContent;
