import { t } from 'intlayer';

const content = {
  key: 'sign-up-form',
  content: {
    emailInput: {
      label: t({
        en: 'Email address',
        'en-GB': 'Email address',
        fr: 'Adresse e-mail',
        es: 'Dirección de correo electrónico',
        de: 'E-Mail-Adresse',
        ja: 'メールアドレス',
        ko: '이메일 주소',
        zh: '电子邮件地址',
        it: 'Indirizzo email',
        pt: 'Endereço de e-mail',
        hi: 'ई-मेल पता',
        ar: 'عنوان البريد الإلكتروني',
        ru: 'Адрес электронной почты',
        tr: 'E-posta adresi',
        pl: 'Adres e-mail',
        id: 'Alamat email',
        vi: 'Địa chỉ email',
      }),
      placeholder: t({
        en: 'Enter e-mail address',
        'en-GB': 'Enter e-mail address',
        fr: 'Entrez votre adresse e-mail',
        es: 'Ingrese su dirección de correo electrónico',
        de: 'E-Mail-Adresse eingeben',
        ja: 'メールアドレスを入力してください',
        ko: '이메일 주소를 입력하세요',
        zh: '请输入电子邮件地址',
        it: "Inserisci l'indirizzo email",
        pt: 'Insira o endereço de e-mail',
        hi: 'ई-मेल पता दर्ज करें',
        ar: 'أدخل عنوان البريد الإلكتروني',
        ru: 'Введите адрес электронной почты',
        tr: 'E-posta adresinizi girin',
        pl: 'Wprowadź adres e-mail',
        id: 'Masukkan alamat e-mail',
        vi: 'Nhập địa chỉ e-mail',
      }),
    },
    passwordInput: {
      label: t({
        en: 'Password',
        'en-GB': 'Password',
        fr: 'Mot de passe',
        es: 'Contraseña',
        de: 'Passwort',
        ja: 'パスワード',
        ko: '비밀번호',
        zh: '密码',
        it: 'Password',
        pt: 'Senha',
        hi: 'पासवर्ड',
        ar: 'كلمة المرور',
        ru: 'Пароль',
        tr: 'Parola',
        pl: 'Hasło',
        id: 'Kata sandi',
        vi: 'Mật khẩu',
      }),
      placeholder: t({
        en: 'Enter password',
        'en-GB': 'Enter password',
        fr: 'Entrez votre mot de passe',
        es: 'Ingrese su contraseña',
        de: 'Passwort eingeben',
        ja: 'パスワードを入力してください',
        ko: '비밀번호를 입력하세요',
        zh: '请输入密码',
        it: 'Inserisci la password',
        pt: 'Insira a senha',
        hi: 'पासवर्ड डालें',
        ar: 'أدخل كلمة المرور',
        ru: 'Введите пароль',
        tr: 'Parolanızı girin',
        pl: 'Wprowadź hasło',
        id: 'Masukkan kata sandi',
        vi: 'Nhập mật khẩu',
      }),
    },
    passwordConfirmationInput: {
      label: t({
        en: 'Password Confirmation',
        'en-GB': 'Password Confirmation',
        fr: 'Confirmation du mot de passe',
        es: 'Confirmación de contraseña',
        de: 'Passwortbestätigung',
        ja: 'パスワードの確認',
        ko: '비밀번호 확인',
        zh: '确认密码',
        it: 'Conferma password',
        pt: 'Confirmação de senha',
        hi: 'पासवर्ड की पुष्टि',
        ar: 'تأكيد كلمة المرور',
        ru: 'Подтверждение пароля',
        tr: 'Parola Onayı',
        pl: 'Potwierdzenie hasła',
        id: 'Konfirmasi kata sandi',
        vi: 'Xác nhận mật khẩu',
      }),
      placeholder: t({
        en: 'Enter password again',
        'en-GB': 'Enter password again',
        fr: 'Entrez votre mot de passe à nouveau',
        es: 'Ingrese su contraseña nuevamente',
        de: 'Passwort erneut eingeben',
        ja: 'パスワードを再度入力してください',
        ko: '비밀번호를 다시 입력하세요',
        zh: '请再次输入密码',
        it: 'Reinserisci la password',
        pt: 'Digite a senha novamente',
        hi: 'पासवर्ड पुनः दर्ज करें',
        ar: 'أعد إدخال كلمة المرور',
        ru: 'Введите пароль еще раз',
        tr: 'Parolayı tekrar girin',
        pl: 'Wprowadź hasło ponownie',
        id: 'Masukkan kata sandi lagi',
        vi: 'Nhập lại mật khẩu',
      }),
    },
    termsAndConditionsCheckbox: {
      description: t({
        en: 'I agree to the terms and conditions',
        'en-GB': 'I agree to the terms and conditions',
        fr: "J'accepte les conditions d'utilisation",
        es: 'Acepto los términos y condiciones',
        de: 'Ich stimme den Nutzungsbedingungen zu',
        ja: '利用規約に同意する',
        ko: '이용 약관에 동의합니다',
        zh: '同意使用条款',
        it: 'Accetto i termini e le condizioni',
        pt: 'Concordo com os termos e condições',
        hi: 'शर्तें और शर्तें सहमत होते हैं',
        ar: 'أوافق على الشروط والأحكام',
        ru: 'Соглашаюсь с условиями и положениями',
        tr: 'Şartlar ve koşulları kabul ediyorum',
        pl: 'Zgadzam się z warunkami i regulaminem',
        id: 'Saya setuju dengan syarat dan ketentuan',
        vi: 'Tôi đồng ý với các điều khoản và điều kiện',
      }),
    },

    signUpButton: {
      text: t({
        en: 'Create account',
        'en-GB': 'Create account',
        fr: 'Créer un compte',
        es: 'Crear una cuenta',
        de: 'Konto erstellen',
        ja: 'アカウントを作成',
        ko: '계정 만들기',
        zh: '创建账户',
        it: 'Crea account',
        pt: 'Criar conta',
        hi: 'खाता बनाएं',
        ar: 'إنشاء حساب',
        ru: 'Создать аккаунт',
        tr: 'Hesap oluştur',
        pl: 'Utwórz konto',
        id: 'Buat akun',
        vi: 'Tạo tài khoản',
      }),
      ariaLabel: t({
        en: 'Submit form to create account',
        'en-GB': 'Submit form to create account',
        fr: 'Soumettre le formulaire pour créer un compte',
        es: 'Enviar formulario para crear cuenta',
        de: 'Formular absenden, um ein Konto zu erstellen',
        ja: 'アカウントを作成するためにフォームを送信する',
        ko: '계정을 만들기 위해 양식을 제출하세요',
        zh: '提交表单以创建账户',
        it: 'Invia il modulo per creare un account',
        pt: 'Envie o formulário para criar uma conta',
        hi: 'खाता बनाने के लिए फॉर्म जमा करें',
        ar: 'إرسال النموذج لإنشاء حساب',
        ru: 'Отправить форму для создания аккаунта',
        tr: 'Hesap oluşturmak için formu gönderin',
        pl: 'Wyślij formularz, aby utworzyć konto',
        id: 'Kirim formulir untuk membuat akun',
        vi: 'Gửi biểu mẫu để tạo tài khoản',
      }),
    },
    loginLink: {
      message: t({
        en: 'You already have an account?',
        'en-GB': 'You already have an account?',
        fr: 'Vous avez déjà un compte ?',
        es: '¿Ya tienes una cuenta?',
        de: 'Sie haben bereits ein Konto?',
        ja: 'すでにアカウントをお持ちですか？',
        ko: '이미 계정이 있습니까?',
        zh: '您已经有一个账户了吗？',
        it: 'Hai già un account?',
        pt: 'Você já tem uma conta?',
        hi: 'क्या आपके पास पहले से ही एक खाता है?',
        ar: 'هل لديك حساب بالفعل؟',
        ru: 'У вас уже есть аккаунт?',
        tr: 'Zaten bir hesabınız var mı?',
        pl: 'Masz już konto?',
        id: 'Sudah punya akun?',
        vi: 'Bạn đã có tài khoản?',
      }),
      text: t({
        en: 'Log in',
        'en-GB': 'Log in',
        fr: 'Se connecter',
        es: 'Iniciar sesión',
        de: 'Einloggen',
        ja: 'ログイン',
        ko: '로그인',
        zh: '登录',
        it: 'Accedi',
        pt: 'Entrar',
        hi: 'लॉग इन करें',
        ar: 'تسجيل الدخول',
        ru: 'Войти',
        tr: 'Giriş yap',
        pl: 'Zaloguj się',
        id: 'Masuk',
        vi: 'Đăng nhập',
      }),
      ariaLabel: t({
        en: 'Click to go to login page',
        'en-GB': 'Click to go to login page',
        fr: 'Cliquez pour aller à la page de connexion',
        es: 'Haz clic para ir a la página de inicio de sesión',
        de: 'Klicken Sie, um zur Anmeldeseite zu gelangen',
        ja: 'ログインページに移動するにはクリックしてください',
        ko: '로그인 페이지로 이동하려면 클릭하세요',
        zh: '点击进入登录页面',
        it: 'Clicca per andare alla pagina di login',
        pt: 'Clique para ir para a página de login',
        hi: 'लॉगिन पृष्ठ पर जाने के लिए क्लिक करें',
        ar: 'انقر للذهاب إلى صفحة تسجيل الدخول',
        ru: 'Нажмите, чтобы перейти на страницу входа',
        tr: 'Giriş sayfasına gitmek için tıklayın',
        pl: 'Kliknij, aby przejść do strony logowania',
        id: 'Klik untuk menuju halaman masuk',
        vi: 'Nhấn để đến trang đăng nhập',
      }),
    },
  },
  title: 'Sign-up form',
  description:
    'Content declaration for the user sign-up form, including input labels, placeholders, checkbox agreement, and navigation to login. Designed to support multilingual authentication interfaces.',
  tags: ['form', 'authentication', 'sign-up'],
};

export default content;
