import { type Dictionary, t } from 'intlayer';

export const confirmationStepContent = {
  key: 'confirmation-step',
  content: {
    confirmation: {
      title: t({
        en: 'Confirmation',
        'en-GB': 'Confirmation',
        fr: 'Confirmation',
        es: 'Confirmación',
        de: 'Bestätigung',
        ja: '確認',
        ko: '확인',
        zh: '确认',
        it: 'Conferma',
        pt: 'Confirmação',
        hi: 'निष्कर्ष',
        ar: 'تأكيد',
        ru: 'Подтверждение',
        tr: 'Onay',
        pl: 'Potwierdzenie',
        id: 'Konfirmasi',
        vi: 'Xác nhận',
        uk: 'Підтвердження',
      }),
      hiText: t({
        en: 'Hi {name}!',
        'en-GB': 'Hi {name}!',
        fr: 'Bonjour {name}!',
        es: 'Hola {name}!',
        de: 'Hallo {name}!',
        ja: 'こんにちは {name}!',
        ko: '안녕하세요 {name}!',
        zh: '嗨 {name}!',
        it: 'Ciao {name}!',
        pt: 'Olá {name}!',
        hi: 'नमस्ते {name}!',
        ar: 'مرحبا {name}!',
        ru: 'Привет {name}!',
        tr: 'Merhaba {name}!',
        pl: 'Cześć {name}!',
        id: 'Hai {name}!',
        vi: 'Chào {name}!',
        uk: 'Привіт, {name}!',
      }),
      description: t({
        en: 'You are now ready to start using Intlayer.',
        'en-GB': 'You are now ready to start using Intlayer.',
        fr: 'Vous êtes maintenant prêt à utiliser Intlayer.',
        es: 'Ahora estás listo para comenzar a usar Intlayer.',
        de: 'Sie sind jetzt bereit, Intlayer zu verwenden.',
        ja: 'あなたは今、Intlayerを使用する準備ができています。',
        ko: '이제 Intlayer를 사용할 준비가 되었습니다.',
        zh: '您现在已准备好使用Intlayer。',
        it: 'Ora sei pronto per iniziare a usare Intlayer.',
        pt: 'Você está agora pronto para começar a usar o Intlayer.',
        hi: 'आप अब Intlayer का उपयोग करने के लिए तैयार हैं।',
        ar: 'أنت الآن جاهز لبدء استخدام Intlayer.',
        ru: 'Теперь вы готовы начать использовать Intlayer.',
        tr: 'Artık Intlayer kullanmaya hazırsınız.',
        pl: 'Teraz możesz zacząć korzystać z Intlayer.',
        id: 'Anda sekarang siap untuk mulai menggunakan Intlayer.',
        vi: 'Bạn đã sẵn sàng bắt đầu sử dụng Intlayer.',
        uk: 'Тепер ви готові почати користуватися Intlayer.',
      }),
    },
    goToDashboardButton: {
      label: t({
        en: 'Go to dashboard',
        'en-GB': 'Go to dashboard',
        fr: 'Aller au tableau de bord',
        es: 'Ir al tablero de mando',
        de: 'Zum Dashboard gehen',
        ja: 'ダッシュボードに行く',
        ko: '대시보드로 가기',
        zh: '前往仪表板',
        it: 'Vai alla dashboard',
        pt: 'Ir para o painel',
        hi: 'डैशबोर्ड पर जाएं',
        ar: 'اذهب إلى لوحة التحكم',
        ru: 'Перейти к приборной панели',
        tr: 'Kontrol paneline git',
        pl: 'Przejdź do pulpitu',
        id: 'Buka dashboard',
        vi: 'Đi đến dashboard',
        uk: 'Перейти до панелі керування',
      }),
      text: t({
        en: 'Go to dashboard',
        'en-GB': 'Go to dashboard',
        fr: 'Aller au tableau de bord',
        es: 'Ir al tablero de mando',
        de: 'Zum Dashboard gehen',
        ja: 'ダッシュボードに行く',
        ko: '대시보드로 가기',
        zh: '前往仪表板',
        it: 'Vai alla dashboard',
        pt: 'Ir para o painel',
        hi: 'डैशबोर्ड पर जाएं',
        ar: 'اذهب إلى لوحة التحكم',
        ru: 'Перейти к приборной панели',
        tr: 'Kontrol paneline git',
        pl: 'Przejdź do pulpitu',
        id: 'Buka dashboard',
        vi: 'Đi đến dashboard',
        uk: 'Перейти до панелі керування',
      }),
    },
  },
  title: 'Confirmation step content',
  description:
    'Content declarations for the confirmation step of the onboarding process, including user greeting and navigation to the dashboard.',
  tags: ['onboarding', 'confirmation step', 'dashboard navigation'],
} satisfies Dictionary;

export default confirmationStepContent;
