import { type Dictionary, t } from 'intlayer';

const demoContent = {
  key: 'compiler-section',
  content: {
    title: t({
      en: 'Intlayer Compiler',
      fr: 'Compilateur Intlayer',
      es: 'Compilador Intlayer',
      'en-GB': 'Intlayer Compiler',
      de: 'Intlayer Compiler',
      ja: 'インテレイヤーコンパイラ',
      ko: '인트레이어 컴파일러',
      zh: 'Intlayer 编译器',
      it: 'Compilatore Intlayer',
      pt: 'Compilador Intlayer',
      hi: 'इंटलेयर कंपाइलर',
      ar: 'مترجم Intlayer',
      ru: 'Компилятор Intlayer',
      tr: 'Intlayer Derleyici',
      pl: 'Kompilator Intlayer',
      id: 'Kompiler Intlayer',
      vi: 'Trình biên dịch Intlayer',
    }),
    paragraph: t({
      en: 'The Intlayer Compiler extract automatically the content from the components and generate the dictionary files.',
      fr: 'Le Compilateur Intlayer extrait automatiquement le contenu des composants et génère les fichiers de dictionnaire.',
      es: 'El Compilador Intlayer extrae automáticamente el contenido de los componentes y genera los archivos de diccionario.',
      'en-GB':
        'The Intlayer Compiler extract automatically the content from the components and generate the dictionary files.',
      de: 'Der Intlayer Compiler extrahiert automatisch den Inhalt aus den Komponenten und generiert die Wörterbuchdateien.',
      ja: 'Intlayerコンパイラは、コンポーネントからコンテンツを自動的に抽出し、辞書ファイルを生成します。',
      ko: 'Intlayer 컴파일러는 컴포넌트에서 콘텐츠를 자동으로 추출하여 사전 파일을 생성합니다.',
      zh: 'Intlayer编译器自动提取组件中的内容并生成字典文件。',
      it: 'Il Compilatore Intlayer estrae automaticamente il contenuto dai componenti e genera i file del dizionario.',
      pt: 'O Compilador Intlayer extrai automaticamente o conteúdo dos componentes e gera os arquivos de dicionário.',
      hi: 'Intlayer Compiler स्वचालित रूप से कंपोनेंट्स की सामग्री को निकालता है और शब्दकोश फ़ाइलें तैयार करता है।',
      ar: 'يقوم مترجم Intlayer باستخراج المحتوى من المكونات تلقائيًا وإنشاء ملفات القاموس.',
      ru: 'Компилятор Intlayer автоматически извлекает содержимое из компонентов и генерирует файлы словаря.',
      tr: 'Intlayer Derleyicisi, bileşenlerden içeriği otomatik olarak çıkarır ve sözlük dosyalarını oluşturur.',
      pl: 'Kompilator Intlayer automatycznie wyodrębnia zawartość z komponentów i generuje pliki słownika.',
      id: 'Intlayer Compiler secara otomatis mengekstrak konten dari komponen dan menghasilkan file kamus.',
      vi: 'Trình biên dịch Intlayer tự động trích xuất nội dung từ các thành phần và tạo các tệp từ điển.',
    }),
    selectPlaceholder: t({
      en: 'Choose locale...',
      fr: 'Choisir la locale...',
      es: 'Elegir la locale...',
      'en-GB': 'Choose locale...',
      de: 'Sprache auswählen...',
      ja: '言語を選択...',
      ko: '언어 선택...',
      zh: '选择语言...',
      it: 'Seleziona la lingua...',
      pt: 'Selecionar idioma...',
      hi: 'भाषा चुनें...',
      ar: 'اختر اللغة...',
      ru: 'Выберите язык...',
      tr: 'Dil seçin...',
      pl: 'Wybierz język...',
      id: 'Pilih bahasa...',
      vi: 'Chọn ngôn ngữ...',
    }),
  },
} as const satisfies Dictionary;

export default demoContent;
