import { type Dictionary, t } from 'intlayer';

const docHeaderContent = {
  key: 'doc-header',
  content: {
    authorLabel: t({
      ar: 'المؤلف',
      de: 'Autor',
      en: 'Author',
      'en-GB': 'Author',
      es: 'Autor',
      fr: 'Auteur',
      hi: 'Author',
      it: 'Autore',
      ja: '著者',
      ko: '작가',
      pt: 'Autor',
      ru: 'Автор',
      tr: 'Yazar',
      zh: '作者',
    }),
    creationLabel: t({
      ar: 'إنشاء',
      de: 'Erstellung',
      en: 'Creation',
      'en-GB': 'Creation',
      es: 'Creación',
      fr: 'Création',
      hi: 'Creation',
      it: 'Creazione',
      ja: '作成',
      ko: '생성',
      pt: 'Criação',
      ru: 'Создание',
      tr: 'Oluşturma',
      zh: 'Creation',
    }),
    lastUpdateLabel: t({
      ar: 'آخر تحديث',
      de: 'Letzte Aktualisierung',
      en: 'Last update',
      'en-GB': 'Last update',
      es: 'Última actualización',
      fr: 'Dernière mise à jour',
      hi: 'Last update',
      it: 'Ultimo aggiornamento',
      ja: '最終更新',
      ko: '마지막 업데이트',
      pt: 'Última atualização',
      ru: 'Последнее обновление',
      tr: 'Son güncelleme',
      zh: 'Last update',
    }),
  },
} satisfies Dictionary;

export default docHeaderContent;
