import { type Dictionary, insert, t } from 'intlayer';

const paginationContent = {
  key: 'pagination',
  content: {
    numberItemsSelector: t({
      en: 'Items per page',
      fr: 'Eléments par page',
      es: 'Items por página',
      'en-GB': 'Items per page',
      de: 'Items pro Seite',
      ja: 'ページあたりのアイテム数',
      ko: '페이지당 아이템 수',
      zh: '每页项目数',
      it: 'Elementi per pagina',
      pt: 'Itens por página',
      hi: 'पृष्ठ पर आइटम्स',
      ar: 'عدد العناصر لكل صفحة',
      ru: 'Элементов на странице',
      tr: 'Sayfa başına öğe',
      pl: 'Elementów na stronę',
      id: 'Item per halaman',
      vi: 'Số mục trên mỗi trang',
    }),
    showingResults: insert(
      t({
        ar: 'عرض {{start}} إلى {{end}} من {{total}} نتائج',
        de: 'Zeigt {{start}} bis {{end}} von {{total}} Ergebnissen',
        en: 'Showing {{start}} to {{end}} of {{total}} results',
        'en-GB': 'Showing {{start}} to {{end}} of {{total}} results',
        es: 'Mostrando {{start}} a {{end}} de {{total}} resultados',
        fr: 'Afficher {{start}} à {{end}} de {{total}} résultats',
        hi: '{{start}} से {{end}} तक के {{total}} परिणाम दिखा रहे हैं',
        id: 'Menampilkan {{start}} hingga {{end}} dari {{total}} hasil',
        it: 'Mostrando {{start}} a {{end}} di {{total}} risultati',
        ja: '{{start}} から {{end}} までの {{total}} 件の結果を表示',
        ko: '{{start}} 에서 {{end}} 까지의 {{total}} 개 결과 표시',
        pl: 'Wyświetlane {{start}} do {{end}} z {{total}} wyników',
        pt: 'Mostrando {{start}} a {{end}} de {{total}} resultados',
        ru: 'Показано {{start}}-{{end}} из {{total}} результатов',
        tr: '{{start}} から {{end}} までの {{total}} 件の結果を表示',
        vi: 'Hiển thị {{start}} đến {{end}} trong tổng số {{total}} kết quả',
        zh: '显示第 {{start}} 到 {{end}} 项，共 {{total}} 个结果',
      })
    ),
    selectPageSize: t({
      en: 'Select page size',
      fr: 'Sélectionner la taille de la page',
      es: 'Seleccionar tamaño de página',
      'en-GB': 'Select page size',
      de: 'Seitegröße auswählen',
      ja: 'ページサイズを選択',
      ko: '페이지 크기 선택',
      zh: '选择页面大小',
      it: 'Seleziona una dimensione di pagina',
      pt: 'Selecionar um tamanho de página',
      hi: 'पृष्ठ आकार चुनें',
      ar: 'اختر حجم الصفحة',
      ru: 'Выберите размер страницы',
      tr: 'Sayfa boyutunu seç',
      pl: 'Wybierz liczbę elementów na stronę',
      id: 'Pilih jumlah item per halaman',
      vi: 'Chọn số mục trên mỗi trang',
    }),
    goToNextPage: t({
      en: 'Go to next page',
      fr: 'Aller à la page suivante',
      es: 'Ir a la página siguiente',
      'en-GB': 'Go to next page',
      de: 'Zur nächsten Seite',
      ja: '次のページに移動',
      ko: '다음 페이지로 이동',
      zh: '转到下一页',
      it: 'Vai alla pagina successiva',
      pt: 'Ir para a página seguinte',
      hi: 'अगली पृष्ठ पर जाएं',
      ar: 'اذهب إلى الصفحة التالية',
      ru: 'Перейти к следующей странице',
      tr: 'Sonraki sayfaya git',
      pl: 'Przejdź do następnej strony',
      id: 'Pergi ke halaman berikutnya',
      vi: 'Chuyển sang trang tiếp theo',
    }),
    goToPreviousPage: t({
      en: 'Go to previous page',
      fr: 'Aller à la page précédente',
      es: 'Ir a la página anterior',
      'en-GB': 'Go to previous page',
      de: 'Zur vorherigen Seite',
      ja: '前のページに移動',
      ko: '이전 페이지로 이동',
      zh: '转到上一页',
      it: 'Vai alla pagina precedente',
      pt: 'Ir para a página anterior',
      hi: 'पिछली पृष्ठ पर जाएं',
      ar: 'اذهب إلى الصفحة السابقة',
      ru: 'Перейти к предыдущей странице',
      tr: 'Önceki sayfaya git',
      pl: 'Przejdź do poprzedniej strony',
      id: 'Pergi ke halaman sebelumnya',
      vi: 'Chuyển sang trang trước',
    }),
  },
  title: 'Pagination',
  description:
    'Content strings used for the pagination component, including labels for navigating pages and selecting items per page.',
  tags: ['pagination', 'component'],
} satisfies Dictionary;

export default paginationContent;
