import { type Dictionary, t } from 'intlayer';

const errorComponentContent = {
  key: 'error-component',
  content: {
    somethingWentWrong: t({
      en: 'Something went wrong',
      'en-GB': 'Something went wrong',
      fr: "Quelque chose s'est mal passé",
      es: 'Algo salió mal',
      de: 'Etwas ist schief gelaufen',
      ja: '問題が発生しました',
      ko: '문제가 발생했습니다',
      zh: '出错了',
      it: 'Qualcosa è andato storto',
      pt: 'Algo deu errado',
      hi: 'कुछ गलत हो गया',
      ar: 'حدث خطأ ما',
      ru: 'Что-то пошло не так',
      tr: 'Bir şeyler yanlış gitti',
      pl: 'Coś poszło nie tak',
      id: 'Ada yang salah',
      uk: 'Щось пішло не так',
      vi: 'Đã xảy ra lỗi',
    }),
    unexpectedError: t({
      en: 'An unexpected error occurred.',
      'en-GB': 'An unexpected error occurred.',
      fr: "Une erreur inattendue s'est produite.",
      es: 'Ocurrió un error inesperado.',
      de: 'Ein unerwarteter Fehler ist aufgetreten.',
      ja: '予期しないエラーが発生しました。',
      ko: '예기치 않은 오류가 발생했습니다.',
      zh: '发生了意外错误。',
      it: 'Si è verificato un errore imprevisto.',
      pt: 'Ocorreu um erro inesperado.',
      hi: 'एक अप्रत्याशित त्रुटि हुई।',
      ar: 'حدث خطأ غير متوقع.',
      ru: 'Произошла непредвиденная ошибка.',
      tr: 'Beklenmedik bir hata oluştu.',
      pl: 'Wystąpił nieoczekiwany błąd.',
      id: 'Terjadi kesalahan yang tidak terduga.',
      uk: 'Сталася неочікувана помилка.',
      vi: 'Đã xảy ra lỗi không mong muốn.',
    }),
    tryAgain: t({
      en: 'Try again',
      'en-GB': 'Try again',
      fr: 'Réessayer',
      es: 'Intentar de nuevo',
      de: 'Erneut versuchen',
      ja: '再試行',
      ko: '다시 시도',
      zh: '重试',
      it: 'Riprova',
      pt: 'Tentar novamente',
      hi: 'फिर से प्रयास करें',
      ar: 'حاول مرة أخرى',
      ru: 'Попробовать снова',
      tr: 'Tekrar dene',
      pl: 'Spróbuj ponownie',
      id: 'Coba lagi',
      uk: 'Спробувати ще раз',
      vi: 'Thử lại',
    }),
    backToHome: t({
      en: 'Back to home',
      'en-GB': 'Back to home',
      fr: "Retour à l'accueil",
      es: 'Volver al inicio',
      de: 'Zurück zur Startseite',
      ja: 'ホームに戻る',
      ko: '홈으로 돌아가기',
      zh: '返回首页',
      it: 'Torna alla home',
      pt: 'Voltar ao início',
      hi: 'घर वापस जाएं',
      ar: 'العودة إلى الرئيسية',
      ru: 'Вернуться на главную',
      tr: 'Ana sayfaya dön',
      pl: 'Wróć do strony głównej',
      id: 'Kembali ke beranda',
      uk: 'Повернутися на головну',
      vi: 'Quay về trang chủ',
    }),
  },
} satisfies Dictionary;

export default errorComponentContent;
