import { type Dictionary, t } from 'intlayer';

const analyzerFormContent = {
  key: 'analyzer-form',
  content: {
    input: {
      placeholder: t({
        en: 'https://yourwebsite.com',
        ru: 'https://вашсайт.рф',
        ja: 'https://あなたのサイト.jp',
        fr: 'https://votresite.com',
        ko: 'https://당사이트.kr',
        zh: 'https://你的網站.cn',
        es: 'https://tusitio.com',
        de: 'https://ihrewebsite.de',
        ar: 'https://موقعك.مصر',
        it: 'https://iltuosito.it',
        'en-GB': 'https://yourwebsite.co.uk',
        pt: 'https://seusite.com.br',
        hi: 'https://aapkiwebsite.in',
        tr: 'https://siteniz.com',
        pl: 'https://twojastrona.pl',
        id: 'https://websiteanda.id',
        vi: 'https://trangwebcuaban.vn',
      }),
      label: t({
        en: 'Website URL',
        ru: 'URL сайта',
        ja: 'ウェブサイトのURL',
        fr: 'URL du site web',
        ko: '웹사이트 URL',
        zh: '网站URL',
        es: 'URL del sitio web',
        de: 'Website-URL',
        ar: 'رابط الموقع',
        it: 'URL del sito web',
        'en-GB': 'Website URL',
        pt: 'URL do site',
        hi: 'वेबसाइट URL',
        tr: "Web sitesi URL'si",
        pl: 'Adres URL strony',
        id: 'URL situs web',
        vi: 'URL trang web',
      }),
    },
    button: {
      label: t({
        en: 'Analyze',
        ru: 'Анализировать',
        ja: '分析する',
        fr: 'Analyser',
        ko: '분석하기',
        zh: '分析',
        es: 'Analizar',
        de: 'Analysieren',
        ar: 'حلل',
        it: 'Analizza',
        'en-GB': 'Analyse',
        pt: 'Analisar',
        hi: 'विश्लेषण करें',
        tr: 'Analiz Et',
        pl: 'Analizuj',
        id: 'Analisis',
        vi: 'Phân tích',
      }),
      analyze: t({
        en: 'Analyze',
        ru: 'Анализировать',
        ja: '分析する',
        fr: 'Analyser',
        ko: '분석하기',
        zh: '分析',
        es: 'Analizar',
        de: 'Analysieren',
        ar: 'حلل',
        it: 'Analizza',
        'en-GB': 'Analyse',
        pt: 'Analisar',
        hi: 'विश्लेषण करें',
        tr: 'Analiz Et',
        pl: 'Analizuj',
        id: 'Analisis',
        vi: 'Phân tích',
      }),
      analyzing: t({
        en: 'Analyzing...',
        ru: 'Анализ...',
        ja: '分析中...',
        fr: 'Analyse en cours...',
        ko: '분석 중...',
        zh: '正在分析...',
        es: 'Analizando...',
        de: 'Analysiere...',
        ar: 'جاري التحليل...',
        it: 'Analisi in corso...',
        'en-GB': 'Analysing...',
        pt: 'Analisando...',
        hi: 'विश्लेषण हो रहा है...',
        tr: 'Analiz ediliyor...',
        pl: 'Analizuję...',
        id: 'Sedang menganalisis...',
        vi: 'Đang phân tích...',
      }),
    },
    invalidUrlError: t({
      en: 'Please enter a valid URL',
      ru: 'Пожалуйста, введите корректный URL',
      ja: '有効なURLを入力してください',
      fr: 'Veuillez saisir une URL valide',
      ko: '유효한 URL을 입력해 주세요',
      zh: '请输入有效的URL',
      es: 'Por favor, ingrese una URL válida',
      de: 'Bitte geben Sie eine gültige URL ein',
      ar: 'يرجى إدخال رابط صالح',
      it: 'Per favore, inserisci un URL valido',
      'en-GB': 'Please enter a valid URL',
      pt: 'Por favor, insira uma URL válida',
      hi: 'कृपया एक मान्य URL दर्ज करें',
      tr: 'Lütfen geçerli bir URL girin',
      pl: 'Proszę podać poprawny adres URL',
      id: 'Silakan masukkan URL yang valid',
      vi: 'Vui lòng nhập một URL hợp lệ',
    }),
  },
  title: 'Analyzer form texts',
  description: 'Localized labels and placeholders for the analyzer form',
  tags: ['form', 'analyze', 'url'],
} satisfies Dictionary;

export default analyzerFormContent;
