import { type Dictionary, t } from 'intlayer';

const contentDeliveryContent = {
  key: 'cms-landing-content-delivery',
  title: 'CMS landing page — Content delivery',
  description:
    "Content declarations for the CMS landing page's content delivery section, including delivery modes and descriptions for static, dynamic, and live-sync options.",
  content: {
    deliveryTitle: t({
      en: 'Deliver content your way',
      'en-GB': 'Deliver content your way',
      fr: 'Livrez le contenu à votre façon',
      es: 'Entrega el contenido a tu manera',
      de: 'Inhalte nach Ihren Wünschen bereitstellen',
      ru: 'Доставляйте контент по-своему',
      ja: 'あなたの方法でコンテンツを配信',
      ko: '원하는 방식으로 콘텐츠 제공',
      zh: '以您的方式交付内容',
      ar: 'قم بتسليم المحتوى بطريقتك',
      it: 'Consegna i contenuti a modo tuo',
      pt: 'Entregue o conteúdo do seu jeito',
      hi: 'अपने तरीके से सामग्री वितरित करें',
      tr: 'İçeriği kendi yolunuzla teslim edin',
      pl: 'Dostarczaj treść po swojemu',
      id: 'Kirim konten dengan cara Anda',
      vi: 'Giao nội dung theo cách của bạn',
      uk: 'Доставляйте контент у зручний для вас спосіб',
    }),
    deliveryDescription: t({
      en: 'Choose the delivery mode that fits your architecture, or mix them.',
      'en-GB':
        'Choose the delivery mode that fits your architecture, or mix them.',
      fr: 'Choisissez le mode de livraison qui correspond à votre architecture, ou mélangez-les.',
      es: 'Elige el modo de entrega que se adapte a tu arquitectura, o mézclalos.',
      de: 'Wählen Sie den Bereitstellungsmodus, der zu Ihrer Architektur passt, oder kombinieren Sie sie.',
      ru: 'Выберите режим доставки, который подходит вашей архитектуре, или смешайте их.',
      ja: 'あなたのアーキテクチャに適合する配信モードを選択するか、それらを混在させます。',
      ko: '아키텍처에 맞는 배송 모드를 선택하거나 혼합하세요.',
      zh: '选择适合您架构的交付模式，或混合使用。',
      ar: 'اختر وضع التسليم الذي يناسب بنيتك، أو اخلطها.',
      it: 'Scegli la modalità di consegna che si adatta alla tua architettura, o combinale.',
      pt: 'Escolha o modo de entrega que se adapta à sua arquitetura, ou misture-os.',
      hi: 'अपनी आर्किटेक्चर के अनुरूप डिलीवरी मोड चुनें, या उन्हें मिलाएं।',
      tr: 'Mimarinize uyan teslimat modunu seçin veya bunları karıştırın.',
      pl: 'Wybierz tryb dostarczania, który pasuje do Twojej architektury, lub je zmieszaj.',
      id: 'Pilih mode pengiriman yang sesuai dengan arsitektur Anda, atau campurkan.',
      vi: 'Chọn chế độ giao hàng phù hợp với kiến trúc của bạn, hoặc kết hợp chúng.',
      uk: 'Виберіть режим доставки, що підходить вашій архітектурі, або комбінуйте їх.',
    }),
    deliveryModes: [
      {
        id: 'static',
        icon: 'archive',
        title: t({
          en: 'Bundled (Static)',
          'en-GB': 'Bundled (Static)',
          fr: 'Empaqueté (Statique)',
          es: 'Empaquetado (Estático)',
          de: 'Gebündelt (Statisch)',
          ru: 'Встроенный (Статический)',
          ja: 'バンドル (静的)',
          ko: '번들 (정적)',
          zh: '捆绑 (静态)',
          ar: 'مجمعة (ثابت)',
          it: 'Integrato (Statico)',
          pt: 'Empacotado (Estático)',
          hi: 'बंडल (स्थिर)',
          tr: 'Paketlenmiş (Statik)',
          pl: 'Wbudowany (Statyczny)',
          id: 'Dibundel (Statis)',
          vi: 'Đóng gói (Tĩnh)',
          uk: 'Упакована (статична)',
        }),
        description: t({
          en: 'Import content directly into your application bundle. High speed and zero latency, perfect for design systems.',
          'en-GB':
            'Import content directly into your application bundle. High speed and zero latency, perfect for design systems.',
          fr: 'Importez le contenu directement dans votre bundle. Grande vitesse et latence nulle, parfait pour les design systems.',
          es: 'Importa contenido directamente en el bundle. Alta velocidad y latencia cero, perfecto para sistemas de diseño.',
          de: 'Inhalt direkt in das App-Bundle importieren. Hohe Geschwindigkeit, keine Latenz, perfekt für Design-Systeme.',
          ru: 'Импортируйте контент прямо в сборку. Высокая скорость, нулевая задержка, идеально для дизайн-систем.',
          ja: 'コンテンツをアプリのバンドルに直接インポート。高速で低遅延、デザインシステムに最適です。',
          ko: '애플리케이션 번들로 콘텐츠를 직접 가져옵니다. 고속 및 제로 레이턴시, 디자인 시스템에 완벽합니다.',
          zh: '直接将内容导入应用程序包中。高速且零延迟，非常适合设计系统。',
          ar: 'استيراد المحتوى مباشرة إلى حزمة التطبيق الخاصة بك. سرعة عالية وزمن انتقال صفر، مثالي لأنظمة التصميم.',
          it: "Importa il contenuto direttamente nel bundle dell'app. Alta velocità e latenza zero, perfetto per i design system.",
          pt: 'Importe conteúdo diretamente para o bundle da aplicação. Alta velocidade e latência zero, perfeito para design systems.',
          hi: 'सामग्री को सीधे अपने एप्लिकेशन बंडल में आयात करें। उच्च गति और शून्य विलंबता, डिज़ाइन सिस्टम के लिए एकदम सही।',
          tr: 'İçeriği doğrudan uygulama paketinize aktarın. Yüksek hız ve sıfır gecikme, tasarım sistemleri için mükemmel.',
          pl: 'Importuj treść bezpośrednio do paczki aplikacji. Wysoka prędkość i zerowe opóźnienie, idealne dla systemów designu.',
          id: 'Impor konten langsung ke dalam bundel aplikasi Anda. Kecepatan tinggi dan latensi nol, sempurna untuk sistem desain.',
          vi: 'Nhập nội dung trực tiếp vào gói ứng dụng của bạn. Tốc độ cao và độ trễ bằng không, hoàn hảo cho các hệ thống thiết kế.',
          uk: 'Імпортуйте контент безпосередньо в бандл вашого застосунку. Висока швидкість і нульова затримка, ідеально підходить для систем дизайну.',
        }),
        badge: t({
          en: 'Maximum Speed',
          'en-GB': 'Maximum Speed',
          fr: 'Vitesse maximale',
          es: 'Velocidad máxima',
          de: 'Maximale Geschwindigkeit',
          ru: 'Максимальная скорость',
          ja: '最高速度',
          ko: '최고 속도',
          zh: '最高速度',
          ar: 'السرعة القصوى',
          it: 'Massima velocità',
          pt: 'Velocidade Máxima',
          hi: 'अधिकतम गति',
          tr: 'Maksimum Hız',
          pl: 'Maksymalna prędkość',
          id: 'Kecepatan Maksimum',
          vi: 'Tốc độ tối đa',
          uk: 'Максимальна швидкість',
        }),
      },
      {
        id: 'dynamic',
        icon: 'code',
        title: t({
          en: 'Lazy Loaded (Dynamic)',
          'en-GB': 'Lazy Loaded (Dynamic)',
          fr: 'Chargement Différé (Dynamique)',
          es: 'Carga Diferida (Dinámico)',
          de: 'Lazy Loaded (Dynamisch)',
          ru: 'Ленивая загрузка (Динамический)',
          ja: '遅延読み込み (動的)',
          ko: '지연 로드 (동적)',
          zh: '懒加载 (动态)',
          ar: 'تحميل كسول (ديناميكي)',
          it: 'Caricamento Pigro (Dinamico)',
          pt: 'Carregamento Preguiçoso (Dinâmico)',
          hi: 'लेजी लोडेड (गतिशील)',
          tr: 'Tembel Yükleme (Dinamik)',
          pl: 'Leniwe ładowanie (Dynamiczny)',
          id: 'Lazy Loaded (Dinamis)',
          vi: 'Tải chậm (Động)',
          uk: 'Завантаження за потреби (динамічне)',
        }),
        description: t({
          en: 'Fetch only the necessary content via asynchronous imports. Reduces initial bundle size at the cost of a network request.',
          'en-GB':
            'Fetch only the necessary content via asynchronous imports. Reduces initial bundle size at the cost of a network request.',
          fr: "Ne récupérez que le contenu nécessaire via des imports asynchrones. Réduit la taille initiale du bundle au prix d'une requête réseau.",
          es: 'Obtén solo el contenido necesario vía imports asíncronos. Reduce el tamaño inicial del bundle a costa de una petición de red.',
          de: 'Nur notwendige Inhalte asynchron laden. Reduziert die anfängliche Bundle-Größe auf Kosten einer Netzwerkabfrage.',
          ru: 'Загружайте только необходимое через асинхронные импорты. Уменьшает размер сборки ценой сетевого запроса.',
          ja: '非同期インポートで必要なコンテンツのみを取得。ネットワークリクエストが必要ですが、初期バンドルサイズを削減します。',
          ko: '비동기 가져오기를 통해 필요한 콘텐츠만 가져옵니다. 네트워크 요청 비용으로 초기 번들 크기를 줄입니다.',
          zh: '通过异步导入仅获取必要的内容。以网络请求为代价减少初始包大小。',
          ar: 'احصل فقط على المحتوى الضروري عبر الاستيراد غير المتزامن. يقلل من حجم الحزمة الأولي بتكلفة طلب شبكة.',
          it: 'Recupera solo il contenuto necessario tramite import asincroni. Riduce la dimensione iniziale del bundle al costo di una richiesta di rete.',
          pt: 'Busque apenas o conteúdo necessário via imports assíncronos. Reduz o tamanho inicial do bundle ao custo de uma requisição de rede.',
          hi: 'अतुल्यकालिक आयात के माध्यम से केवल आवश्यक सामग्री प्राप्त करें। नेटवर्क अनुरोध की कीमत पर प्रारंभिक बंडल आकार को कम करता है।',
          tr: 'Sadece gerekli içeriği asenkron içe aktarmalarla alın. Bir ağ isteği pahasına başlangıç paket boyutunu azaltır.',
          pl: 'Pobieraj tylko niezbędną treść poprzez asynchroniczne importy. Zmniejsza początkowy rozmiar paczki kosztem zapytania sieciowego.',
          id: 'Ambil hanya konten yang diperlukan melalui impor asinkron. Mengurangi ukuran bundel awal dengan biaya permintaan jaringan.',
          vi: 'Chỉ lấy nội dung cần thiết thông qua nhập không đồng bộ. Giảm kích thước gói ban đầu với chi phí là một yêu cầu mạng.',
          uk: 'Підвантажуйте лише необхідний контент через асинхронні імпорти. Зменшує початковий розмір бандлу за рахунок мережевого запиту.',
        }),
        badge: t({
          en: 'Optimized Bundle',
          'en-GB': 'Optimized Bundle',
          fr: 'Bundle optimisé',
          es: 'Bundle optimizado',
          de: 'Optimiertes Bundle',
          ru: 'Оптимизированная сборка',
          ja: '最適化されたバンドル',
          ko: '최적화된 번들',
          zh: '优化的包',
          ar: 'حزمة محسنة',
          it: 'Bundle ottimizzato',
          pt: 'Bundle Otimizado',
          hi: 'अनुकूलित बंडल',
          tr: 'Optimize Edilmiş Paket',
          pl: 'Zoptymalizowana paczka',
          id: 'Bundel Teroptimasi',
          vi: 'Gói được tối ưu hóa',
          uk: 'Оптимізований бандл',
        }),
      },
      {
        id: 'live-sync',
        icon: 'server',
        title: t({
          en: 'Live Sync',
          'en-GB': 'Live Sync',
          fr: 'Sync en Direct',
          es: 'Sincronización en Vivo',
          de: 'Live-Sync',
          ru: 'Живая синхронизация',
          ja: 'ライブ同期',
          ko: '라이브 동기화',
          zh: '实时同步',
          ar: 'مزامنة مباشرة',
          it: 'Sincronizzazione Live',
          pt: 'Sincronização ao Vivo',
          hi: 'लाइव सिंक',
          tr: 'Canlı Senkronizasyon',
          pl: 'Synchronizacja na żywo',
          id: 'Sinkronisasi Langsung',
          vi: 'Đồng bộ trực tiếp',
          uk: 'Жива синхронізація',
        }),
        description: t({
          en: 'Fetch content via a local proxy acting as a CDN. Apply content updates in production instantly without rebuilding.',
          'en-GB':
            'Fetch content via a local proxy acting as a CDN. Apply content updates in production instantly without rebuilding.',
          fr: 'Récupérez le contenu via un proxy local agissant comme un CDN. Appliquez les mises à jour en production instantanément sans reconstruire.',
          es: 'Obtén contenido vía un proxy local que actúa como CDN. Aplica actualizaciones en producción al instante sin reconstruir.',
          de: 'Inhalte über lokalen Proxy (als CDN) abrufen. Updates sofort in Produktion anwenden, ohne Rebuild.',
          ru: 'Получайте контент через локальный прокси (как CDN). Мгновенно применяйте обновления в продакшене без пересборки.',
          ja: 'CDNとして機能するローカルプロキシ経由でコンテンツを取得。再構築なしで本番環境に更新を即座に適用します。',
          ko: 'CDN 역할을 하는 로컬 프록시를 통해 콘텐츠를 가져옵니다. 재빌드 없이 프로덕션에 콘텐츠 업데이트를 즉시 적용합니다.',
          zh: '通过充当CDN的本地代理获取内容。无需重建即可在生产环境中立即应用内容更新。',
          ar: 'جلب المحتوى عبر وكيل محلي يعمل كـ CDN. تطبيق تحديثات المحتوى في الإنتاج فورًا دون إعادة البناء.',
          it: 'Recupera il contenuto tramite un proxy locale che funge da CDN. Applica gli aggiornamenti in produzione istantaneamente senza ricompilare.',
          pt: 'Busque conteúdo via proxy local atuando como CDN. Aplique atualizações em produção instantaneamente sem reconstruir.',
          hi: 'CDN के रूप में कार्य करने वाले स्थानीय प्रॉक्सी के माध्यम से सामग्री प्राप्त करें। पुनर्निर्माण के बिना उत्पादन में सामग्री अपडेट तुरंत लागू करें।',
          tr: 'CDN gibi davranan yerel bir proxy aracılığıyla içerik alın. Yeniden derlemeden üretimde içerik güncellemelerini anında uygulayın.',
          pl: 'Pobieraj treść przez lokalne proxy działające jako CDN. Wdrażaj aktualizacje na produkcji natychmiast bez przebudowy.',
          id: 'Ambil konten melalui proksi lokal yang bertindak sebagai CDN. Terapkan pembaruan konten di produksi secara instan tanpa membangun ulang.',
          vi: 'Lấy nội dung qua proxy cục bộ hoạt động như CDN. Áp dụng cập nhật nội dung trong sản xuất ngay lập tức mà không cần xây dựng lại.',
          uk: 'Отримуйте контент через локальний проксі, що працює як CDN. Застосовуйте оновлення контенту в продуктивному середовищі миттєво, без перескладання.',
        }),
        badge: t({
          en: 'No Rebuild',
          'en-GB': 'No Rebuild',
          fr: 'Pas de reconstruction',
          es: 'Sin reconstrucción',
          de: 'Kein Rebuild',
          ru: 'Без пересборки',
          ja: '再構築不要',
          ko: '재빌드 없음',
          zh: '无需重建',
          ar: 'لا إعادة بناء',
          it: 'Nessuna ricompilazione',
          pt: 'Sem Reconstrução',
          hi: 'कोई पुनर्निर्माण नहीं',
          tr: 'Yeniden Derleme Yok',
          pl: 'Bez przebudowy',
          id: 'Tanpa Bangun Ulang',
          vi: 'Không cần xây dựng lại',
          uk: 'Без перескладання',
        }),
      },
    ],
  },
  tags: ['cms', 'landing page', 'content delivery', 'page section'],
} satisfies Dictionary;

export default contentDeliveryContent;
