import { type Dictionary, t } from 'intlayer';

const integrationContent = {
  key: 'cms-landing-integration',
  title: 'CMS Landing Integration',
  description:
    "Content declarations for the CMS landing page's integration section, including the integration title, description, and call-to-action.",
  content: {
    integrationTitle: t({
      en: 'Seamlessly connected to Intlayer i18n',
      'en-GB': 'Seamlessly connected to Intlayer i18n',
      fr: 'Connecté de manière transparente à Intlayer i18n',
      es: 'Conectado perfectamente con Intlayer i18n',
      de: 'Nahtlos verbunden mit Intlayer i18n',
      ru: 'Бесшовно подключено к Intlayer i18n',
      ja: 'Intlayer i18nにシームレスに接続',
      ko: 'Intlayer i18n에 원활하게 연결',
      zh: '与 Intlayer i18n 无缝连接',
      ar: 'متصل بسلاسة مع Intlayer i18n',
      it: 'Connesso perfettamente a Intlayer i18n',
      pt: 'Conectado perfeitamente ao Intlayer i18n',
      hi: 'Intlayer i18n से निर्बाध रूप से जुड़ा हुआ',
      tr: 'Intlayer i18n ile sorunsuz bağlantı',
      pl: 'Bezproblemowo połączony z Intlayer i18n',
      id: 'Terhubung mulus dengan Intlayer i18n',
      vi: 'Kết nối liền mạch với Intlayer i18n',
      uk: 'Безшовна інтеграція з Intlayer i18n',
    }),
    integrationDescription: t({
      en: 'Already using the Intlayer i18n library? Your dictionaries, routing, and type-safe hooks work exactly the same with the CMS, zero migration, zero friction.',
      'en-GB':
        'Already using the Intlayer i18n library? Your dictionaries, routing, and type-safe hooks work exactly the same with the CMS, zero migration, zero friction.',
      fr: 'Vous utilisez déjà la bibliothèque Intlayer i18n ? Vos dictionnaires, routing et hooks type-safe fonctionnent exactement de la même manière avec le CMS, zéro migration, zéro friction.',
      es: '¿Ya usas la biblioteca Intlayer i18n? Tus diccionarios, enrutamiento y hooks type-safe funcionan exactamente igual con el CMS, cero migración, cero fricción.',
      de: 'Nutzen Sie bereits die Intlayer i18n Library? Ihre Dictionaries, Routing und type-safe Hooks funktionieren mit dem CMS genauso, keine Migration, keine Reibung.',
      ru: 'Уже используете библиотеку Intlayer i18n? Ваши словари, маршрутизация и типобезопасные хуки работают точно так же с CMS, нулевая миграция, нулевое трение.',
      ja: 'すでにIntlayer i18nライブラリを使用していますか？辞書、ルーティング、タイプセーフなフックはCMSでもまったく同じように機能し、移行も摩擦もゼロです。',
      ko: '이미 Intlayer i18n 라이브러리를 사용하고 계신가요? 사전, 라우팅 및 타입 안전 훅이 CMS에서도 정확히 동일하게 작동하며, 마이그레이션과 마찰이 없습니다.',
      zh: '已经在使用 Intlayer i18n 库了吗？您的字典、路由和类型安全钩子在 CMS 中完全一样工作，零迁移，零摩擦。',
      ar: 'هل تستخدم بالفعل مكتبة Intlayer i18n؟ تعمل القواميس والتوجيه وخطافات الأمان النوعية بنفس الطريقة تماماً مع CMS، صفر هجرة، صفر احتكاك.',
      it: 'Stai già usando la libreria Intlayer i18n? I tuoi dizionari, il routing e gli hook type-safe funzionano esattamente allo stesso modo con il CMS, zero migrazione, zero attrito.',
      pt: 'Já está usando a biblioteca Intlayer i18n? Seus dicionários, roteamento e hooks type-safe funcionam exatamente da mesma forma com o CMS, zero migração, zero fricção.',
      hi: 'पहले से Intlayer i18n लाइब्रेरी का उपयोग कर रहे हैं? आपके शब्दकोश, रूटिंग और टाइप-सेफ हुक CMS के साथ बिल्कुल वैसे ही काम करते हैं, शून्य माइग्रेशन, शून्य घर्षण।',
      tr: 'Zaten Intlayer i18n kütüphanesini kullanıyor musunuz? Sözlükleriniz, yönlendirme ve tip güvenli kancalar CMS ile tam olarak aynı şekilde çalışır, sıfır geçiş, sıfır sürtünme.',
      pl: 'Już używasz biblioteki Intlayer i18n? Twoje słowniki, routing i type-safe hooki działają dokładnie tak samo z CMS, zero migracji, zero tarcia.',
      id: 'Sudah menggunakan library Intlayer i18n? Kamus, routing, dan hook type-safe Anda bekerja persis sama dengan CMS, nol migrasi, nol gesekan.',
      vi: 'Đã sử dụng thư viện Intlayer i18n? Từ điển, định tuyến và hook type-safe của bạn hoạt động chính xác như vậy với CMS, không cần di chuyển, không ma sát.',
      uk: 'Вже використовуєте бібліотеку Intlayer i18n? Ваші словники, маршрутизація та типобезпечні хуки працюють так само з CMS — без міграцій та зайвих складнощів.',
    }),
    integrationCta: t({
      en: 'Explore the i18n library',
      'en-GB': 'Explore the i18n library',
      fr: 'Explorer la bibliothèque i18n',
      es: 'Explorar la biblioteca i18n',
      de: 'Die i18n Library erkunden',
      ru: 'Изучить библиотеку i18n',
      ja: 'i18nライブラリを探索',
      ko: 'i18n 라이브러리 탐색',
      zh: '探索 i18n 库',
      ar: 'استكشف مكتبة i18n',
      it: 'Esplora la libreria i18n',
      pt: 'Explorar a biblioteca i18n',
      hi: 'i18n लाइब्रेरी का अन्वेषण करें',
      tr: 'i18n kütüphanesini keşfet',
      pl: 'Poznaj bibliotekę i18n',
      id: 'Jelajahi library i18n',
      vi: 'Khám phá thư viện i18n',
      uk: 'Переглянути бібліотеку i18n',
    }),
  },
  tags: ['cms', 'landing page', 'integration', 'i18n'],
} satisfies Dictionary;

export default integrationContent;
