import { type Dictionary, t } from 'intlayer';

export const externalsLoginButtonsContent = {
  key: 'externals-login-buttons',
  content: {
    span: t({
      ar: 'أو',
      de: 'oder',
      en: 'or',
      'en-GB': 'or',
      es: 'o',
      fr: 'ou',
      hi: 'या',
      it: 'o',
      ja: 'または',
      ko: '또는',
      pt: 'ou',
      ru: 'или',
      tr: 'veya',
      zh: '或',
    }),
    github: {
      label: t({
        en: 'Sign in with GitHub',
        fr: 'Se connecter avec GitHub',
        es: 'Iniciar sesión con GitHub',
        de: 'Mit GitHub anmelden',
        ja: 'GitHubでサインイン',
        ko: 'GitHub로 로그인',
        zh: '使用GitHub登录',
        it: 'Accedi con GitHub',
        pt: 'Entrar com o GitHub',
        hi: 'GitHub के साथ साइनइन करें',
        ar: 'تسجيل الدخول باستخدام GitHub',
        ru: 'Войти с GitHub',
        'en-GB': 'Sign in with GitHub',
        tr: 'GitHub ile giriş yap',
      }),
      ariaLabel: t({
        en: 'Sign in with GitHub',
        fr: 'Se connecter avec GitHub',
        es: 'Iniciar sesión con GitHub',
        de: 'Mit GitHub anmelden',
        ja: 'GitHubでサインイン',
        ko: 'GitHub로 로그인',
        zh: '使用GitHub登录',
        it: 'Accedi con GitHub',
        pt: 'Entrar com o GitHub',
        hi: 'GitHub के साथ साइनइन करें',
        ar: 'تسجيل الدخول باستخدام GitHub',
        ru: 'Войти с GitHub',
        'en-GB': 'Sign in with GitHub',
        tr: 'GitHub ile giriş yap',
      }),
    },
    google: {
      label: t({
        en: 'Sign in with Google',
        fr: 'Se connecter avec Google',
        es: 'Iniciar sesión con Google',
        de: 'Mit Google anmelden',
        ja: 'Googleでサインイン',
        ko: 'Google로 로그인',
        zh: '使用Google登录',
        it: 'Accedi con Google',
        pt: 'Entrar com o Google',
        hi: 'Google के साथ साइनइन करें',
        ar: 'تسجيل الدخول باستخدام Google',
        ru: 'Войти с Google',
        'en-GB': 'Sign in with Google',
        tr: 'Google ile giriş yap',
      }),
      ariaLabel: t({
        en: 'Sign in with Google',
        fr: 'Se connecter avec Google',
        es: 'Iniciar sesión con Google',
        de: 'Mit Google anmelden',
        ja: 'Googleでサインイン',
        ko: 'Google로 로그인',
        zh: '使用Google登录',
        it: 'Accedi con Google',
        pt: 'Entrar com o Google',
        hi: 'Google के साथ साइनइन करें',
        ar: 'تسجيل الدخول باستخدام Google',
        ru: 'Войти с Google',
        'en-GB': 'Sign in with Google',
        tr: 'Google ile giriş yap',
      }),
    },
  },
} satisfies Dictionary;

export default externalsLoginButtonsContent;
