import { type Dictionary, insert, t } from 'intlayer';

const accountSwitcherContent = {
  key: 'account-switcher',
  content: {
    accountSwitcherAriaLabel: t({
      en: 'Account switcher',
      fr: 'Sélecteur de compte',
      es: 'Selector de cuenta',
      ru: 'Переключатель аккаунтов',
      ja: 'アカウント切り替え',
      ko: '계정 전환기',
      zh: '帐户切换器',
      de: 'Konto-Umschalter',
      ar: 'مبدل الحسابات',
      it: 'Selettore account',
      'en-GB': 'Account switcher',
      pt: 'Seletor de conta',
      hi: 'खाता स्विचर',
      tr: 'Hesap değiştirici',
      pl: 'Przełącznik kont',
      id: 'Pengalih akun',
      vi: 'Trình chuyển đổi tài khoản',
      uk: 'Перемикач облікових записів',
    }),
    activeAccountAriaLabel: t({
      en: 'Active account',
      fr: 'Compte actif',
      es: 'Cuenta activa',
      ru: 'Активный аккаунт',
      ja: 'アクティブなアカウント',
      ko: '활성 계정',
      zh: '活跃帐户',
      de: 'Aktives Konto',
      ar: 'الحساب النشط',
      it: 'Account attivo',
      'en-GB': 'Active account',
      pt: 'Conta ativa',
      hi: 'सक्रिय खाता',
      tr: 'Aktif hesap',
      pl: 'Aktywne konto',
      id: 'Akun aktif',
      vi: 'Tài khoản hoạt động',
      uk: 'Активний обліковий запис',
    }),
    switchingAccountAriaLabel: t({
      en: 'Switching account…',
      fr: 'Changement de compte…',
      es: 'Cambiando de cuenta…',
      ru: 'Смена аккаунта…',
      ja: 'アカウントを切り替えています…',
      ko: '계정 전환 중…',
      zh: '正在切换帐户…',
      de: 'Konto wird gewechselt…',
      ar: 'جاري تبديل الحساب…',
      it: 'Cambio account…',
      'en-GB': 'Switching account…',
      pt: 'Trocando de conta…',
      hi: 'खाता बदल रहा है…',
      tr: 'Hesap değiştiriliyor…',
      pl: 'Przełączanie konta…',
      id: 'Mengalihkan akun…',
      vi: 'Đang chuyển đổi tài khoản…',
      uk: 'Зміна облікового запису…',
    }),
    addAccountTitle: t({
      en: 'Add another account',
      fr: 'Ajouter un autre compte',
      es: 'Añadir otra cuenta',
      ru: 'Добавить другой аккаунт',
      ja: '別のアカウントを追加',
      ko: '다른 계정 추가',
      zh: '添加另一个帐户',
      de: 'Weiteres Konto hinzufügen',
      ar: 'إضافة حساب آخر',
      it: 'Aggiungi un altro account',
      'en-GB': 'Add another account',
      pt: 'Adicionar outra conta',
      hi: 'एक और खाता जोड़ें',
      tr: 'Başka bir hesap ekle',
      pl: 'Dodaj inne konto',
      id: 'Tambahkan akun lain',
      vi: 'Thêm tài khoản khác',
      uk: 'Додати інший обліковий запис',
    }),
    switchToAriaLabel: insert(
      t({
        en: 'Switch to {{name}}',
        fr: 'Passer à {{name}}',
        es: 'Cambiar a {{name}}',
        ru: 'Переключиться на {{name}}',
        ja: '{{name}} に切り替える',
        ko: '{{name}}(으)로 전환',
        zh: '切换到 {{name}}',
        de: 'Zu {{name}} wechseln',
        ar: 'التبديل إلى {{name}}',
        it: 'Passa a {{name}}',
        'en-GB': 'Switch to {{name}}',
        pt: 'Mudar para {{name}}',
        hi: '{{name}} पर स्विच करें',
        tr: "{{name}}'a geç",
        pl: 'Przełącz na {{name}}',
        id: 'Beralih ke {{name}}',
        vi: 'Chuyển sang {{name}}',
        uk: 'Переключитись на {{name}}',
      })
    ),
    signOutAriaLabel: insert(
      t({
        en: 'Sign out {{name}}',
        fr: 'Déconnecter {{name}}',
        es: 'Cerrar sesión de {{name}}',
        ru: 'Выйти из {{name}}',
        ja: '{{name}} からサインアウト',
        ko: '{{name}} 로그아웃',
        zh: '登出 {{name}}',
        de: '{{name}} abmelden',
        ar: 'تسجيل خروج {{name}}',
        it: 'Disconnetti {{name}}',
        'en-GB': 'Sign out {{name}}',
        pt: 'Sair de {{name}}',
        hi: '{{name}} से साइन आउट करें',
        tr: '{{name}} oturumunu kapat',
        pl: 'Wyloguj {{name}}',
        id: 'Keluar dari {{name}}',
        vi: 'Đăng xuất {{name}}',
        uk: 'Вийти з {{name}}',
      })
    ),
  },
  title: 'Account switcher',
  description:
    'Content declaration for the account switcher component, providing aria-labels and button text for switching accounts.',
  tags: ['account', 'switcher', 'user'],
} satisfies Dictionary;

export default accountSwitcherContent;
