import { type Dictionary, t } from 'intlayer';

const magicLinkButtonContent = {
  key: 'magic-link-button',
  content: {
    text: t({
      en: 'Send Magic Link',
      fr: 'Envoyer un lien magique',
      es: 'Enviar enlace mágico',
      de: 'Magic Link senden',
      ja: 'マジックリンクを送信',
      ko: '매직 링크 보내기',
      zh: '发送魔法链接',
      it: 'Invia link magico',
      pt: 'Enviar link mágico',
      hi: 'मैजिक लिंक भेजें',
      ar: 'إرسال رابط سحري',
      ru: 'Отправить волшебную ссылку',
      'en-GB': 'Send Magic Link',
      tr: 'Sihirli Bağlantı Gönder',
      pl: 'Wyślij Magiczny Link',
      id: 'Kirim Tautan Ajaib',
      vi: 'Gửi liên kết ma thuật',
      uk: 'Надіслати магічне посилання',
    }),
    ariaLabel: t({
      en: 'Sign in with magic link',
      fr: 'Se connecter avec un lien magique',
      es: 'Iniciar sesión con enlace mágico',
      de: 'Mit Magic Link anmelden',
      ja: 'マジックリンクでログイン',
      ko: '매직 링크로 로그인',
      zh: '用魔法链接登录',
      it: 'Accedi con link magico',
      pt: 'Entrar com link mágico',
      hi: 'मैजिक लिंक से साइनइन करें',
      ar: 'تسجيل الدخول باستخدام الرابط السحري',
      ru: 'Войти по волшебной ссылке',
      'en-GB': 'Sign in with magic link',
      tr: 'Sihirli Bağlantı ile giriş yap',
      pl: 'Zaloguj się przy użyciu Magic Link',
      id: 'Masuk dengan Tautan Ajaib',
      vi: 'Đăng nhập bằng liên kết ma thuật',
      uk: 'Увійти за допомогою магічного посилання',
    }),
    successMessage: t({
      en: 'Magic link sent! Check your email.',
      fr: 'Lien magique envoyé ! Vérifiez votre email.',
      es: '¡Enlace mágico enviado! Revisa tu correo.',
      de: 'Magic Link gesendet! Prüfe deine E-Mails.',
      ja: 'マジックリンクが送信されました！メールを確認してください。',
      ko: '매직 링크가 전송되었습니다! 이메일을 확인하세요.',
      zh: '魔法链接已发送！请检查您的邮箱。',
      it: 'Link magico inviato! Controlla la tua email.',
      pt: 'Link mágico enviado! Verifique seu e-mail.',
      hi: 'मैजिक लिंक भेज दिया गया है! अपनी ईमेल जांचें।',
      ar: 'تم إرسال الرابط السحري! تحقق من بريدك الإلكتروني.',
      ru: 'Волшебная ссылка отправлена! Проверьте свою почту.',
      'en-GB': 'Magic link sent! Check your email.',
      tr: 'Sihirli bağlantı gönderildi! E-postanı kontrol et.',
      pl: 'Magiczny link został wysłany! Sprawdź swoją pocztę.',
      id: 'Tautan ajaib telah dikirim! Periksa email Anda.',
      vi: 'Liên kết ma thuật đã được gửi! Kiểm tra email của bạn.',
      uk: 'Магічне посилання надіслано! Перевірте свою електронну пошту.',
    }),
    errorMessage: t({
      en: 'Failed to send magic link',
      fr: "Échec de l'envoi du lien magique",
      es: 'Error al enviar el enlace mágico',
      de: 'Fehler beim Senden des Magic Links',
      ja: 'マジックリンクの送信に失敗しました',
      ko: '매직 링크 전송에 실패했습니다',
      zh: '发送魔法链接失败',
      it: 'Invio del link magico non riuscito',
      pt: 'Falha ao enviar o link mágico',
      hi: 'मैजिक लिंक भेजने में विफल',
      ar: 'فشل في إرسال الرابط السحري',
      ru: 'Не удалось отправить волшебную ссылку',
      'en-GB': 'Failed to send magic link',
      tr: 'Sihirli bağlantı gönderilemedi',
      pl: 'Nie udało się wysłać magicznego linku',
      id: 'Gagal mengirim tautan ajaib',
      vi: 'Không thể gửi liên kết ma thuật',
      uk: 'Не вдалося надіслати магічне посилання',
    }),
    modal: {
      title: t({
        en: 'Sign in with Magic Link',
        fr: 'Se connecter avec un lien magique',
        es: 'Iniciar sesión con enlace mágico',
        de: 'Mit Magic Link anmelden',
        ja: 'マジックリンクでログイン',
        ko: '매직 링크로 로그인',
        zh: '用魔法链接登录',
        it: 'Accedi con link magico',
        pt: 'Entrar com link mágico',
        hi: 'मैजिक लिंक से साइनइन करें',
        ar: 'تسجيل الدخول باستخدام الرابط السحري',
        ru: 'Войти по волшебной ссылке',
        'en-GB': 'Sign in with Magic Link',
        tr: 'Sihirli Bağlantı ile giriş yap',
        pl: 'Zaloguj się przy użyciu Magic Link',
        id: 'Masuk dengan Tautan Ajaib',
        vi: 'Đăng nhập bằng liên kết ma thuật',
        uk: 'Увійти за допомогою магічного посилання',
      }),
      description: t({
        en: "Enter your email address and we'll send you a magic link to sign in instantly.",
        fr: 'Entrez votre adresse e-mail et nous vous enverrons un lien magique pour vous connecter instantanément.',
        es: 'Ingrese su dirección de correo electrónico y le enviaremos un enlace mágico para iniciar sesión al instante.',
        de: 'Geben Sie Ihre E-Mail-Adresse ein und wir senden Ihnen einen Magic Link, mit dem Sie sich sofort anmelden können.',
        ja: 'メールアドレスを入力すると、すぐにサインインできるマジックリンクをお送りします。',
        ko: '이메일 주소를 입력하시면 즉시 로그인할 수 있는 매직 링크를 보내드립니다.',
        zh: '输入您的电子邮件地址，我们将向您发送一个魔法链接以便即时登录。',
        it: 'Inserisci il tuo indirizzo email e ti invieremo un link magico per accedere istantaneamente.',
        pt: 'Digite seu endereço de e-mail e enviaremos um link mágico para você fazer login instantaneamente.',
        hi: 'अपना ईमेल पता दर्ज करें और हम आपको तुरंत साइन इन करने के लिए एक मैजिक लिंक भेजेंगे।',
        ar: 'أدخل عنوان بريدك الإلكتروني وسنرسل لك رابطًا سحريًا لتسجيل الدخول على الفور.',
        ru: 'Введите свой адрес электронной почты, и мы отправим вам волшебную ссылку для мгновенного входа.',
        'en-GB':
          "Enter your email address and we'll send you a magic link to sign in instantly.",
        tr: 'E-posta adresinizi girin, size anında giriş yapmanız için sihirli bir bağlantı gönderelim.',
        pl: 'Wprowadź swój adres e-mail, a my wyślemy Ci magiczny link do natychmiastowego zalogowania.',
        id: 'Masukkan alamat email Anda dan kami akan mengirimkan tautan ajaib untuk masuk secara instan.',
        vi: 'Nhập địa chỉ email của bạn và chúng tôi sẽ gửi cho bạn liên kết ma thuật để đăng nhập ngay lập tức.',
        uk: 'Введіть свою електронну адресу, і ми надішлемо вам магічне посилання для миттєвого входу.',
      }),
      emailPlaceholder: t({
        en: 'Enter your email',
        fr: 'Entrez votre e-mail',
        es: 'Ingrese su correo electrónico',
        de: 'Geben Sie Ihre E-Mail ein',
        ja: 'メールアドレスを入力',
        ko: '이메일을 입력하세요',
        zh: '输入您的电子邮件',
        it: 'Inserisci la tua email',
        pt: 'Digite seu e-mail',
        hi: 'अपना ईमेल दर्ज करें',
        ar: 'أدخل بريدك الإلكتروني',
        ru: 'Введите ваш адрес электронной почты',
        'en-GB': 'Enter your email',
        tr: 'E-postanızı girin',
        pl: 'Wprowadź swój e-mail',
        id: 'Masukkan email Anda',
        vi: 'Nhập email của bạn',
        uk: 'Введіть електронну адресу',
      }),
      cancelButton: t({
        en: 'Cancel',
        fr: 'Annuler',
        es: 'Cancelar',
        de: 'Abbrechen',
        ja: 'キャンセル',
        ko: '취소',
        zh: '取消',
        it: 'Annulla',
        pt: 'Cancelar',
        hi: 'रद्द करें',
        ar: 'إلغاء',
        ru: 'Отмена',
        'en-GB': 'Cancel',
        tr: 'İptal',
        pl: 'Anuluj',
        id: 'Batal',
        vi: 'Hủy',
        uk: 'Скасувати',
      }),
      sendButton: t({
        en: 'Send Magic Link',
        fr: 'Envoyer le lien magique',
        es: 'Enviar enlace mágico',
        de: 'Magic Link senden',
        ja: 'マジックリンクを送信',
        ko: '매직 링크 보내기',
        zh: '发送魔法链接',
        it: 'Invia link magico',
        pt: 'Enviar link mágico',
        hi: 'मैजिक लिंक भेजें',
        ar: 'إرسال رابط سحري',
        ru: 'Отправить волшебную ссылку',
        'en-GB': 'Send Magic Link',
        tr: 'Sihirli Bağlantı Gönder',
        pl: 'Wyślij Magiczny Link',
        id: 'Kirim Tautan Ajaib',
        vi: 'Gửi liên kết ma thuật',
        uk: 'Надіслати магічне посилання',
      }),
    },
  },
  title: 'Magic link button',
  description:
    'Content for the Magic Link sign-in button and its modal: button text, ARIA label, success and error messages, modal title and description, email placeholder and action buttons.',
  tags: ['auth', 'button', 'component', 'modal', 'localization'],
} satisfies Dictionary;

export default magicLinkButtonContent;
