import { type Dictionary, t } from 'intlayer';

const autoFillSettingsContent = {
  key: 'auto-fill-settings',
  content: {
    title: t({
      en: 'Auto-fill',
      'en-GB': 'Auto-fill',
      fr: 'Remplissage automatique',
      es: 'Auto-completar',
      de: 'Automatisches Ausfüllen',
      ja: '自動補完',
      ko: '자동 채우기',
      zh: '自动填充',
      it: 'Compilazione automatica',
      pt: 'Preenchimento automático',
      hi: 'स्वतः भरें',
      ar: 'الملء التلقائي',
      ru: 'Автозаполнение',
      tr: 'Otomatik Doldurma',
      pl: 'Auto-uzupełnianie',
      id: 'Isi Otomatis',
      vi: 'Tự động điền',
      uk: 'Автозаповнення',
    }),
    autoFillOnPushToggle: {
      label: t({
        en: 'Auto-fill on push',
        'en-GB': 'Auto-fill on push',
        fr: 'Remplissage automatique à la mise à jour',
        es: 'Auto-completar al publicar',
        de: 'Automatisch beim Push ausfüllen',
        ja: 'プッシュ時に自動補完',
        ko: '푸시 시 자동 채우기',
        zh: '推送时自动填充',
        it: 'Compilazione automatica al push',
        pt: 'Preenchimento automático ao publicar',
        hi: 'पुश पर स्वतः भरें',
        ar: 'الملء التلقائي عند الدفع',
        ru: 'Автозаполнение при push',
        tr: 'Push işleminde otomatik doldur',
        pl: 'Auto-uzupełnianie przy push',
        id: 'Isi otomatis saat push',
        vi: 'Tự động điền khi push',
        uk: 'Автозаповнення при push',
      }),
      description: t({
        en: 'Automatically fill missing translations when dictionaries are pushed to the CMS.',
        'en-GB':
          'Automatically fill missing translations when dictionaries are pushed to the CMS.',
        fr: 'Remplir automatiquement les traductions manquantes lors de la mise à jour des dictionnaires dans le CMS.',
        es: 'Completar automáticamente las traducciones faltantes cuando se publican diccionarios en el CMS.',
        de: 'Fehlende Übersetzungen automatisch ausfüllen, wenn Wörterbücher an das CMS gepusht werden.',
        ja: '辞書がCMSにプッシュされたときに不足している翻訳を自動的に補完します。',
        ko: '사전이 CMS에 푸시될 때 누락된 번역을 자동으로 채웁니다.',
        zh: '当词典被推送到 CMS 时，自动填充缺失的翻译。',
        it: 'Compila automaticamente le traduzioni mancanti quando i dizionari vengono inviati al CMS.',
        pt: 'Preencher automaticamente as traduções ausentes quando os dicionários são publicados no CMS.',
        hi: 'जब शब्दकोश CMS में पुश किए जाते हैं तो लापता अनुवाद स्वचालित रूप से भरें।',
        ar: 'ملء الترجمات المفقودة تلقائيًا عند دفع القواميس إلى نظام إدارة المحتوى.',
        ru: 'Автоматически заполнять недостающие переводы при push словарей в CMS.',
        tr: "Sözlükler CMS'e push edildiğinde eksik çevirileri otomatik olarak doldur.",
        pl: 'Automatycznie uzupełniaj brakujące tłumaczenia przy publikowaniu słowników do CMS.',
        id: 'Isi terjemahan yang hilang secara otomatis saat kamus dipush ke CMS.',
        vi: 'Tự động điền các bản dịch còn thiếu khi từ điển được push lên CMS.',
        uk: 'Автоматично заповнювати відсутні переклади при push словників до CMS.',
      }),
    },
    saveButton: {
      text: t({
        en: 'Save',
        'en-GB': 'Save',
        fr: 'Enregistrer',
        es: 'Guardar',
        de: 'Speichern',
        ja: '保存',
        ko: '저장',
        zh: '保存',
        it: 'Salva',
        pt: 'Salvar',
        hi: 'सहेजें',
        ar: 'حفظ',
        ru: 'Сохранить',
        tr: 'Kaydet',
        pl: 'Zapisz',
        id: 'Simpan',
        vi: 'Lưu',
        uk: 'Зберегти',
      }),
      ariaLabel: t({
        en: 'Save auto-fill settings',
        'en-GB': 'Save auto-fill settings',
        fr: 'Enregistrer les paramètres de remplissage automatique',
        es: 'Guardar ajustes de auto-completar',
        de: 'Einstellungen für automatisches Ausfüllen speichern',
        ja: '自動補完設定を保存',
        ko: '자동 채우기 설정 저장',
        zh: '保存自动填充设置',
        it: 'Salva impostazioni di compilazione automatica',
        pt: 'Salvar configurações de preenchimento automático',
        hi: 'स्वतः भरें सेटिंग्स सहेजें',
        ar: 'حفظ إعدادات الملء التلقائي',
        ru: 'Сохранить настройки автозаполнения',
        tr: 'Otomatik doldurma ayarlarını kaydet',
        pl: 'Zapisz ustawienia auto-uzupełniania',
        id: 'Simpan pengaturan isi otomatis',
        vi: 'Lưu cài đặt tự động điền',
        uk: 'Зберегти налаштування автозаповнення',
      }),
    },
  },
} satisfies Dictionary;

export default autoFillSettingsContent;
