import { type Dictionary, t } from 'intlayer';

const autoFillSettingsContent = {
  key: 'auto-fill-settings',
  content: {
    title: t({
      en: 'Auto-fill',
      'en-GB': 'Auto-fill',
      fr: 'Remplissage automatique',
      es: 'Auto-completar',
      de: 'Automatisches Ausfüllen',
      ja: '自動補完',
      ko: '자동 채우기',
      zh: '自动填充',
      it: 'Compilazione automatica',
      pt: 'Preenchimento automático',
      hi: 'स्वतः भरें',
      ar: 'الملء التلقائي',
      ru: 'Автозаполнение',
      tr: 'Otomatik Doldurma',
      pl: 'Auto-uzupełnianie',
      id: 'Isi Otomatis',
      vi: 'Tự động điền',
      uk: 'Автозаповнення',
    }),
    autoFillOnPushToggle: {
      label: t({
        en: 'Auto-fill on push',
        'en-GB': 'Auto-fill on push',
        fr: 'Remplissage automatique à la mise à jour',
        es: 'Auto-completar al publicar',
        de: 'Automatisch beim Push ausfüllen',
        ja: 'プッシュ時に自動補完',
        ko: '푸시 시 자동 채우기',
        zh: '推送时自动填充',
        it: 'Compilazione automatica al push',
        pt: 'Preenchimento automático ao publicar',
        hi: 'पुश पर स्वतः भरें',
        ar: 'الملء التلقائي عند الدفع',
        ru: 'Автозаполнение при push',
        tr: 'Push işleminde otomatik doldur',
        pl: 'Auto-uzupełnianie przy push',
        id: 'Isi otomatis saat push',
        vi: 'Tự động điền khi push',
        uk: 'Автозаповнення при push',
      }),
      description: t({
        en: 'Automatically fill missing translations when dictionaries are updated. Will work on Git update as well as CMS content push.',
        'en-GB':
          'Automatically fill missing translations when dictionaries are updated. Will work on Git update as well as CMS content push.',
        fr: "Remplir automatiquement les traductions manquantes lors de la mise à jour des dictionnaires. Fonctionnera aussi bien avec Git update qu'avec CMS content push.",
        es: 'Completar automáticamente las traducciones faltantes cuando se actualizan los diccionarios. Funciona tanto con Git update como con CMS content push.',
        de: 'Fehlende Übersetzungen automatisch ausfüllen, wenn Wörterbücher aktualisiert werden. Funktioniert sowohl bei Git update als auch bei CMS content push.',
        ja: '辞書が更新されたときに不足している翻訳を自動的に補完します。Gitの更新およびCMSコンテンツのプッシュでも機能します。',
        ko: '사전이 업데이트될 때 누락된 번역을 자동으로 채웁니다. Git 업데이트 및 CMS 콘텐츠 푸시에서도 작동합니다.',
        zh: '当词典更新时，自动填充缺失的翻译。适用于 Git 更新和 CMS 内容推送。',
        it: 'Compila automaticamente le traduzioni mancanti quando i dizionari vengono aggiornati. Funzionerà sia con l’aggiornamento di Git che con l’invio dei contenuti CMS.',
        pt: 'Preencher automaticamente as traduções ausentes quando os dicionários são atualizados. Funcionará tanto na atualização do Git quanto no envio de conteúdo CMS.',
        hi: 'जब शब्दकोश अपडेट किए जाते हैं तो लापता अनुवाद स्वचालित रूप से भरें। यह गिट अपडेट के साथ-साथ CMS कंटेंट पुश पर भी काम करेगा।',
        ar: 'ملء الترجمات المفقودة تلقائيًا عند تحديث القواميس. سيعمل عند تحديث Git بالإضافة إلى دفع محتوى CMS.',
        ru: 'Автоматически заполнять недостающие переводы при обновлении словарей. Будет работать как при обновлении Git, так и при CMS push контента.',
        tr: 'Sözlükler güncellendiğinde eksik çevirileri otomatik olarak doldur. Hem Git güncellemesinde hem de CMS içerik push işleminde çalışacaktır.',
        pl: 'Automatycznie uzupełniaj brakujące tłumaczenia przy aktualizacji słowników. Będzie działać zarówno przy aktualizacji Git, jak i przy wysyłaniu treści CMS.',
        id: 'Isi terjemahan yang hilang secara otomatis saat kamus diperbarui. Akan berfungsi pada pembaruan Git serta pengiriman konten CMS.',
        vi: 'Tự động điền các bản dịch còn thiếu khi từ điển được cập nhật. Sẽ hoạt động trên bản cập nhật Git cũng như CMS push nội dung.',
        uk: 'Автоматично заповнювати відсутні переклади при оновленні словників. Працюватиме як при оновленні Git, так і при CMS push контенту.',
      }),
    },
    saveButton: {
      text: t({
        en: 'Save',
        'en-GB': 'Save',
        fr: 'Enregistrer',
        es: 'Guardar',
        de: 'Speichern',
        ja: '保存',
        ko: '저장',
        zh: '保存',
        it: 'Salva',
        pt: 'Salvar',
        hi: 'सहेजें',
        ar: 'حفظ',
        ru: 'Сохранить',
        tr: 'Kaydet',
        pl: 'Zapisz',
        id: 'Simpan',
        vi: 'Lưu',
        uk: 'Зберегти',
      }),
      ariaLabel: t({
        en: 'Save auto-fill settings',
        'en-GB': 'Save auto-fill settings',
        fr: 'Enregistrer les paramètres de remplissage automatique',
        es: 'Guardar ajustes de auto-completar',
        de: 'Einstellungen für automatisches Ausfüllen speichern',
        ja: '自動補完設定を保存',
        ko: '자동 채우기 설정 저장',
        zh: '保存自动填充设置',
        it: 'Salva impostazioni di compilazione automatica',
        pt: 'Salvar configurações de preenchimento automático',
        hi: 'स्वतः भरें सेटिंग्स सहेजें',
        ar: 'حفظ إعدادات الملء التلقائي',
        ru: 'Сохранить настройки автозаполнения',
        tr: 'Otomatik doldurma ayarlarını kaydet',
        pl: 'Zapisz ustawienia auto-uzupełniania',
        id: 'Simpan pengaturan isi otomatis',
        vi: 'Lưu cài đặt tự động điền',
        uk: 'Зберегти налаштування автозаповнення',
      }),
    },
  },
} satisfies Dictionary;

export default autoFillSettingsContent;
