import { type Dictionary, t } from 'intlayer';

const userDeleteActionContent = {
  key: 'user-delete-action',
  content: {
    errorMessages: {
      loadingError: t({
        en: 'Error loading user details',
        fr: "Erreur lors du chargement des détails de l'utilisateur",
        es: 'Error al cargar los detalles del usuario',
        'en-GB': 'Error loading user details',
        de: 'Fehler beim Laden der Benutzerdetails',
        ja: 'ユーザー詳細の読み込みエラー',
        ko: '사용자 세부정보 로딩 오류',
        zh: '加载用户详情时出错',
        it: 'Errore nel caricamento dei dettagli utente',
        pt: 'Erro ao carregar detalhes do usuário',
        hi: 'उपयोगकर्ता विवरण लोड करने में त्रुटि',
        ar: 'خطأ في تحميل تفاصيل المستخدم',
        ru: 'Ошибка загрузки деталей пользователя',
        tr: 'Kullanıcı detayları yüklenirken hata',
      }),
      deleteError: t({
        en: 'Error deleting user',
        fr: "Erreur lors de la suppression de l'utilisateur",
        es: 'Error al eliminar el usuario',
        'en-GB': 'Error deleting user',
        de: 'Fehler beim Löschen des Benutzers',
        ja: 'ユーザー削除エラー',
        ko: '사용자 삭제 오류',
        zh: '删除用户时出错',
        it: "Errore nell'eliminazione dell'utente",
        pt: 'Erro ao excluir usuário',
        hi: 'उपयोगकर्ता हटाने में त्रुटि',
        ar: 'خطأ في حذف المستخدم',
        ru: 'Ошибка удаления пользователя',
        tr: 'Kullanıcı silinirken hata',
      }),
    },
    successMessages: {
      userDeleted: t({
        en: 'User deleted successfully',
        fr: 'Utilisateur supprimé avec succès',
        es: 'Usuario eliminado con éxito',
        'en-GB': 'User deleted successfully',
        de: 'Benutzer erfolgreich gelöscht',
        ja: 'ユーザーが正常に削除されました',
        ko: '사용자가 성공적으로 삭제되었습니다',
        zh: '用户已成功删除',
        it: 'Utente eliminato con successo',
        pt: 'Usuário excluído com sucesso',
        hi: 'उपयोगकर्ता सफलतापूर्वक हटाया गया',
        ar: 'تم حذف المستخدم بنجاح',
        ru: 'Пользователь успешно удален',
        tr: 'Kullanıcı başarıyla silindi',
      }),
      userUpdated: t({
        en: 'User updated successfully',
        fr: 'Utilisateur mis à jour avec succès',
        es: 'Usuario actualizado con éxito',
        'en-GB': 'User updated successfully',
        de: 'Benutzer erfolgreich aktualisiert',
        ja: 'ユーザーが正常に更新されました',
        ko: '사용자가 성공적으로 업데이트되었습니다',
        zh: '用户已成功更新',
        it: 'Utente aggiornato con successo',
        pt: 'Usuário atualizado com sucesso',
        hi: 'उपयोगकर्ता सफलतापूर्वक अपडेट किया गया',
        ar: 'تم تحديث المستخدم بنجاح',
        ru: 'Пользователь успешно обновлен',
        tr: 'Kullanıcı başarıyla güncellendi',
      }),
    },
    deleteSection: {
      title: t({
        en: 'Danger Zone',
        fr: 'Zone dangereuse',
        es: 'Zona peligrosa',
        'en-GB': 'Danger Zone',
        de: 'Gefahrenzone',
        ja: '危険ゾーン',
        ko: '위험 구역',
        zh: '危险区域',
        it: 'Zona pericolosa',
        pt: 'Zona de perigo',
        hi: 'खतरनाक क्षेत्र',
        ar: 'منطقة الخطر',
        ru: 'Опасная зона',
        tr: 'Tehlikeli Bölge',
      }),
      description: t({
        en: 'Once you delete this user, there is no going back. Please be certain.',
        fr: "Une fois que vous supprimez cet utilisateur, il n'y a pas de retour en arrière. Soyez certain.",
        es: 'Una vez que elimine este usuario, no hay vuelta atrás. Por favor, esté seguro.',
        'en-GB':
          'Once you delete this user, there is no going back. Please be certain.',
        de: 'Sobald Sie diesen Benutzer löschen, gibt es kein Zurück. Bitte seien Sie sicher.',
        ja: 'このユーザーを削除すると、元に戻すことはできません。ご注意ください。',
        ko: '이 사용자를 삭제하면 되돌릴 수 없습니다. 확실히 하십시오.',
        zh: '删除此用户后，将无法恢复。请确认。',
        it: 'Una volta eliminato questo utente, non si può tornare indietro. Si prega di essere certi.',
        pt: 'Depois de excluir este usuário, não há como voltar atrás. Por favor, tenha certeza.',
        hi: 'एक बार जब आप इस उपयोगकर्ता को हटा देते हैं, तो वापस नहीं लौटा जा सकता। कृपया निश्चित रहें।',
        ar: 'بمجرد حذف هذا المستخدم، لا يمكن التراجع. يرجى التأكد.',
        ru: 'После удаления этого пользователя пути назад нет. Пожалуйста, убедитесь.',
        tr: 'Bu kullanıcıyı sildiğinizde geri dönüş olmaz. Lütfen emin olun.',
      }),
      button: t({
        en: 'Delete User',
        fr: "Supprimer l'utilisateur",
        es: 'Eliminar usuario',
        'en-GB': 'Delete User',
        de: 'Benutzer löschen',
        ja: 'ユーザーを削除',
        ko: '사용자 삭제',
        zh: '删除用户',
        it: 'Elimina utente',
        pt: 'Excluir usuário',
        hi: 'उपयोगकर्ता हटाएं',
        ar: 'حذف المستخدم',
        ru: 'Удалить пользователя',
        tr: 'Kullanıcıyı Sil',
      }),
      modalTitle: t({
        en: 'Delete User',
        fr: "Supprimer l'utilisateur",
        es: 'Eliminar usuario',
        'en-GB': 'Delete User',
        de: 'Benutzer löschen',
        ja: 'ユーザーを削除',
        ko: '사용자 삭제',
        zh: '删除用户',
        it: 'Elimina utente',
        pt: 'Excluir usuário',
        hi: 'उपयोगकर्ता हटाएं',
        ar: 'حذف المستخدم',
        ru: 'Удалить пользователя',
        tr: 'Kullanıcıyı Sil',
      }),
      modalWarning: t({
        en: 'Warning: This action cannot be undone!',
        fr: 'Attention : Cette action ne peut pas être annulée !',
        es: '¡Advertencia: Esta acción no se puede deshacer!',
        'en-GB': 'Warning: This action cannot be undone!',
        de: 'Warnung: Diese Aktion kann nicht rückgängig gemacht werden!',
        ja: '警告：この操作は元に戻せません！',
        ko: '경고: 이 작업은 취소할 수 없습니다!',
        zh: '警告：此操作无法撤消！',
        it: 'Attenzione: questa azione non può essere annullata!',
        pt: 'Aviso: Esta ação não pode ser desfeita!',
        hi: 'चेतावनी: यह क्रिया पूर्ववत नहीं की जा सकती!',
        ar: 'تحذير: لا يمكن التراجع عن هذا الإجراء!',
        ru: 'Внимание: это действие нельзя отменить!',
        tr: 'Uyarı: Bu işlem geri alınamaz!',
      }),
      modalDescription: t({
        en: 'This will permanently delete the user account and all associated data. This action is irreversible.',
        fr: 'Cela supprimera définitivement le compte utilisateur et toutes les données associées. Cette action est irréversible.',
        es: 'Esto eliminará permanentemente la cuenta de usuario y todos los datos asociados. Esta acción es irreversible.',
        'en-GB':
          'This will permanently delete the user account and all associated data. This action is irreversible.',
        de: 'Dies wird das Benutzerkonto und alle zugehörigen Daten dauerhaft löschen. Diese Aktion ist irreversibel.',
        ja: 'これにより、ユーザーアカウントと関連するすべてのデータが完全に削除されます。この操作は元に戻せません。',
        ko: '사용자 계정 및 관련된 모든 데이터가 영구적으로 삭제됩니다. 이 작업은 되돌릴 수 없습니다.',
        zh: '这将永久删除用户帐户和所有关联数据。此操作不可逆。',
        it: "Questo eliminerà definitivamente l'account utente e tutti i dati associati. Questa azione è irreversibile.",
        pt: 'Isso excluirá permanentemente a conta do usuário e todos os dados associados. Esta ação é irreversível.',
        hi: 'यह उपयोगकर्ता खाते और सभी संबंधित डेटा को स्थायी रूप से हटा देगा। यह क्रिया अपरिवर्तनीय है।',
        ar: 'سيؤدي هذا إلى حذف حساب المستخدم وجميع البيانات المرتبطة به بشكل دائم. هذا الإجراء لا رجعة فيه.',
        ru: 'Это навсегда удалит учетную запись пользователя и все связанные данные. Это действие необратимо.',
        tr: 'Bu, kullanıcı hesabını ve ilişkili tüm verileri kalıcı olarak silecektir. Bu işlem geri alınamaz.',
      }),
      userToDelete: t({
        en: 'User to be deleted:',
        fr: 'Utilisateur à supprimer :',
        es: 'Usuario a eliminar:',
        'en-GB': 'User to be deleted:',
        de: 'Zu löschender Benutzer:',
        ja: '削除するユーザー：',
        ko: '삭제할 사용자:',
        zh: '要删除的用户：',
        it: 'Utente da eliminare:',
        pt: 'Usuário a ser excluído:',
        hi: 'हटाए जाने वाला उपयोगकर्ता:',
        ar: 'المستخدم المراد حذفه:',
        ru: 'Пользователь для удаления:',
        tr: 'Silinecek kullanıcı:',
      }),
      cancelButton: t({
        en: 'Cancel',
        fr: 'Annuler',
        es: 'Cancelar',
        'en-GB': 'Cancel',
        de: 'Abbrechen',
        ja: 'キャンセル',
        ko: '취소',
        zh: '取消',
        it: 'Annulla',
        pt: 'Cancelar',
        hi: 'रद्द करें',
        ar: 'إلغاء',
        ru: 'Отмена',
        tr: 'İptal',
      }),
      confirmButton: t({
        en: 'Delete Permanently',
        fr: 'Supprimer définitivement',
        es: 'Eliminar permanentemente',
        'en-GB': 'Delete Permanently',
        de: 'Dauerhaft löschen',
        ja: '完全に削除',
        ko: '영구 삭제',
        zh: '永久删除',
        it: 'Elimina definitivamente',
        pt: 'Excluir permanentemente',
        hi: 'स्थायी रूप से हटाएं',
        ar: 'حذف نهائيًا',
        ru: 'Удалить навсегда',
        tr: 'Kalıcı olarak sil',
      }),
    },
  },
} satisfies Dictionary;

export default userDeleteActionContent;
