import { GithubRoutes, PagesRoutes } from '@/Routes';
import { DocData } from '@components/DocPage/types';
import { Dictionary, t } from 'intlayer';

const docContent = {
  key: 'doc-vue-intlayer-metadata',
  content: {
    docName: 'package__vue-intlayer',
    url: PagesRoutes['Doc_Packages_vue-intlayer'],
    githubUrl: GithubRoutes['Packages_vue-intlayer'],
    createdAt: '2025-04-18',
    updatedAt: '2025-04-18',
    title: t({
      en: 'Package Documentation | vue-intlayer',
      'en-GB': 'Package Documentation | vue-intlayer',
      fr: 'Documentation du package | vue-intlayer',
      es: 'Documentación del paquete | vue-intlayer',
      de: 'Paketdokumentation | vue-intlayer',
      ja: 'パッケージドキュメント | vue-intlayer',
      ko: '패키지 문서 | vue-intlayer',
      zh: '包文档 | vue-intlayer',
      it: 'Documentazione del pacchetto | vue-intlayer',
      pt: 'Documentação do pacote | vue-intlayer',
      hi: 'पैकेज के डॉक्यूमेंटेशन | vue-intlayer',
      ar: 'وثائق حزمة | vue-intlayer',
      ru: 'Документация пакета | vue-intlayer',
    }),

    description: t({
      en: 'See how to use the vue-intlayer package',
      'en-GB': 'See how to use the vue-intlayer package',
      fr: 'Découvrez comment utiliser le package vue-intlayer',
      es: 'Descubre cómo usar el paquete vue-intlayer',
      de: 'Erfahren Sie, wie Sie das vue-intlayer-Paket verwenden',
      ja: 'vue-intlayerパッケージの使用方法を確認してください',
      ko: 'vue-intlayer 패키지 사용 방법을 확인하세요',
      zh: '查看如何使用 vue-intlayer 软件包',
      it: 'Scopri come utilizzare il pacchetto vue-intlayer',
      pt: 'Veja como usar o pacote vue-intlayer',
      hi: 'vue-intlayer पैकेज का उपयोग कैसे करें',
      ar: 'انظر كيف تستخدم حزمة vue-intlayer',
      ru: 'Узнайте, как использовать пакет vue-intlayer',
    }),

    keywords: t({
      en: [
        'Intlayer',
        'vue-intlayer',
        'Internationalization',
        'Documentation',
        'JavaScript',
        'Vue',
      ],
      'en-GB': [
        'Intlayer',
        'vue-intlayer',
        'Internationalization',
        'Documentation',
        'JavaScript',
        'Vue',
      ],
      fr: [
        'Intlayer',
        'vue-intlayer',
        'Internationalisation',
        'Documentation',
        'JavaScript',
        'Vue',
      ],
      es: [
        'Intlayer',
        'vue-intlayer',
        'Internacionalización',
        'Documentación',
        'JavaScript',
        'Vue',
      ],
      de: [
        'Intlayer',
        'vue-intlayer',
        'Internationalisierung',
        'Dokumentation',
        'JavaScript',
        'Vue',
      ],
      ja: [
        'Intlayer',
        'vue-intlayer',
        '国際化',
        'ドキュメント',
        'JavaScript',
        'Vue',
      ],
      ko: ['Intlayer', 'vue-intlayer', '국제화', '문서', 'JavaScript', 'Vue'],
      zh: ['Intlayer', 'vue-intlayer', '国际化', '文档', 'JavaScript', 'Vue'],
      it: [
        'Intlayer',
        'vue-intlayer',
        'internazionalizzazione',
        'documentazione',
        'JavaScript',
        'Vue',
      ],
      pt: [
        'Intlayer',
        'vue-intlayer',
        'internacionalização',
        'documentação',
        'JavaScript',
        'Vue',
      ],
      hi: [
        'Intlayer',
        'vue-intlayer',
        'अंतर्राष्ट्रीयकरण',
        'प्रलेखन',
        'JavaScript',
        'Vue',
      ],
      ar: [
        'Intlayer',
        'vue-intlayer',
        'الدولية',
        'المستندات',
        'JavaScript',
        'Vue',
      ],
      ru: [
        'Intlayer',
        'vue-intlayer',
        'интернационализация',
        'документация',
        'JavaScript',
        'Vue',
      ],
    }),
  },
} satisfies Dictionary<DocData>;

export default docContent;
