import { type Dictionary, t } from 'intlayer';

export default {
  key: 'step-layout',
  content: {
    nextStepButton: {
      label: t({
        en: 'Next',
        'en-GB': 'Next',
        fr: 'Suivant',
        es: 'Siguiente',
        de: 'Nächste',
        ja: '次',
        ko: '다음',
        zh: '下一个',
        it: 'Prossimo',
        pt: 'Próximo',
        hi: 'अगला',
        ar: 'التالي',
        ru: 'Далее',
        tr: 'Sonraki',
        pl: 'Dalej',
        id: 'Berikutnya',
        vi: 'Tiếp theo',
      }),
      text: t({
        en: 'Next',
        'en-GB': 'Next',
        fr: 'Suivant',
        es: 'Siguiente',
        de: 'Nächste',
        ja: '次',
        ko: '다음',
        zh: '下一个',
        it: 'Prossimo',
        pt: 'Próximo',
        hi: 'अगला',
        ar: 'التالي',
        ru: 'Далее',
        tr: 'Sonraki',
        pl: 'Dalej',
        id: 'Berikutnya',
        vi: 'Tiếp theo',
      }),
    },
    previousStepButton: {
      label: t({
        en: 'Previous',
        'en-GB': 'Previous',
        fr: 'Précédent',
        es: 'Anterior',
        de: 'Vorherige',
        ja: '前',
        ko: '이전',
        zh: '上一个',
        it: 'Precedente',
        pt: 'Anterior',
        hi: 'पिछला',
        ar: 'السابق',
        ru: 'Предыдущий',
        tr: 'Önceki',
        pl: 'Wstecz',
        id: 'Sebelumnya',
        vi: 'Quay lại',
      }),
      text: t({
        en: 'Previous',
        'en-GB': 'Previous',
        fr: 'Précédent',
        es: 'Anterior',
        de: 'Vorherige',
        ja: '前',
        ko: '이전',
        zh: '上一个',
        it: 'Precedente',
        pt: 'Anterior',
        hi: 'पिछला',
        ar: 'السابق',
        ru: 'Предыдущий',
        tr: 'Önceki',
        pl: 'Wstecz',
        id: 'Sebelumnya',
        vi: 'Quay lại',
      }),
    },
    skipButton: {
      label: t({
        en: 'Skip',
        'en-GB': 'Skip',
        fr: 'Passer',
        es: 'Saltar',
        de: 'Überspringen',
        ja: 'スキップ',
        ko: '건너뛰기',
        zh: '跳过',
        it: 'Salta',
        pt: 'Pular',
        hi: 'छोड़ें',
        ar: 'تجاوز',
        ru: 'Пропустить',
        tr: 'Atla',
        pl: 'Pomiń',
        id: 'Lewati',
        vi: 'Bỏ qua',
      }),
      text: t({
        en: 'Skip',
        'en-GB': 'Skip',
        fr: 'Passer',
        es: 'Saltar',
        de: 'Überspringen',
        ja: 'スキップ',
        ko: '건너뛰기',
        zh: '跳过',
        it: 'Salta',
        pt: 'Pular',
        hi: 'छोड़ें',
        ar: 'تجاوز',
        ru: 'Пропустить',
        tr: 'Atla',
        pl: 'Pomiń',
        id: 'Lewati',
        vi: 'Bỏ qua',
      }),
    },
  },
  title: 'Onboarding step layout',
  description:
    'Content declaration managing step navigation buttons such as Next, Previous, and Skip within the onboarding page layout.',
  tags: ['onboarding', 'navigation', 'buttons'],
} satisfies Dictionary;
