import { type DeclarationContent, t } from 'intlayer';

const cliLoginFlowContent = {
  key: 'cli-login-flow',
  content: {
    loginTitle: t({
      en: 'Login to CLI',
      'en-GB': 'Login to CLI',
      es: 'Iniciar sesión en CLI',
      fr: 'Connexion au CLI',
      ru: 'Вход в CLI',
      ja: 'CLI にログイン',
      ko: 'CLI에 로그인',
      zh: '登录到 CLI',
      de: 'Anmeldung am CLI',
      ar: 'تسجيل الدخول إلى CLI',
      it: 'Accedi al CLI',
      pt: 'Entrar no CLI',
      hi: 'CLI में लॉगिन करें',
      tr: "CLI'ye Giriş Yap",
      pl: 'Zaloguj się do CLI',
      id: 'Masuk ke CLI',
      vi: 'Đăng nhập vào CLI',
      uk: 'Увійти в CLI',
    }),
    selectOrganization: t({
      en: 'Select Organization',
      'en-GB': 'Select Organisation',
      es: 'Seleccionar organización',
      fr: 'Sélectionner une organisation',
      ru: 'Выберите организацию',
      ja: '組織を選択',
      ko: '조직 선택',
      zh: '选择组织',
      de: 'Organisation auswählen',
      ar: 'اختر المؤسسة',
      it: 'Seleziona organizzazione',
      pt: 'Selecionar organização',
      hi: 'संगठन चुनें',
      tr: 'Organizasyon Seç',
      pl: 'Wybierz organizację',
      id: 'Pilih Organisasi',
      vi: 'Chọn tổ chức',
      uk: 'Оберіть організацію',
    }),
    selectProject: t({
      en: 'Select Project',
      'en-GB': 'Select Project',
      es: 'Seleccionar proyecto',
      fr: 'Sélectionner un projet',
      ru: 'Выберите проект',
      ja: 'プロジェクトを選択',
      ko: '프로젝트 선택',
      zh: '选择项目',
      de: 'Projekt auswählen',
      ar: 'اختر المشروع',
      it: 'Seleziona progetto',
      pt: 'Selecionar projeto',
      hi: 'परियोजना चुनें',
      tr: 'Proje Seç',
      pl: 'Wybierz projekt',
      id: 'Pilih Proyek',
      vi: 'Chọn dự án',
      uk: 'Оберіть проєкт',
    }),
    selectAccessKey: t({
      en: 'Select Access Key',
      'en-GB': 'Select Access Key',
      es: 'Seleccionar clave de acceso',
      fr: "Sélectionner une clé d'accès",
      ru: 'Выберите ключ доступа',
      ja: 'アクセスキーを選択',
      ko: '액세스 키 선택',
      zh: '选择访问密钥',
      de: 'Zugriffsschlüssel auswählen',
      ar: 'اختر مفتاح الوصول',
      it: "Seleziona chiave d'accesso",
      pt: 'Selecionar chave de acesso',
      hi: 'एक्सेस कुंजी चुनें',
      tr: 'Erişim Anahtarını Seç',
      pl: 'Wybierz klucz dostępu',
      id: 'Pilih Kunci Akses',
      vi: 'Chọn khóa truy cập',
      uk: 'Оберіть ключ доступу',
    }),
  },
  title: 'CLI Login Flow',
  description:
    'Content declaration for the CLI login flow used by the Auth/CliLogin component. Provides labels and selections for logging in, choosing organization, project, and access key.',
  tags: ['cli', 'authentication', 'login', 'auth-flow'],
} satisfies DeclarationContent;

export default cliLoginFlowContent;
