import { t, type Dictionary } from 'intlayer';

const youtubeVideoMessageContent = {
  key: 'youtube-video-message',
  content: {
    title: t({
      en: 'Watch the video tutorial',
      fr: 'Regarder le tutoriel vidéo',
      ar: 'شاهد الفيديو التعليمي',
      de: 'Video-Tutorial ansehen',
      es: 'Ver el video tutorial',
      hi: 'वीडियो ट्यूटोरियल देखें',
      ru: 'Посмотреть видео урок',
      'en-GB': 'Watch the video tutorial',
      it: 'Guarda il video tutorial',
      ja: 'ビデオチュートリアルを見る',
      ko: '비디오 튜토리얼 보기',
      pt: 'Assistir ao vídeo tutorial',
      zh: '观看视频教程',
    }),
    description: t({
      en: 'This page has a video tutorial available.',
      fr: "Cette page dispose d'un tutoriel vidéo.",
      es: 'Esta página tiene un video tutorial disponible.',
      hi: 'इस पृष्ठ के लिए एक वीडियो ट्यूटोरियल उपलब्ध है।',
      ru: 'Для этой страницы доступен видео урок.',
      de: 'Für diese Seite ist ein Video-Tutorial verfügbar.',
      pt: 'Esta página tem um vídeo tutorial disponível.',
      ja: 'このページにはビデオチュートリアルがあります。',
      ko: '이 페이지에는 비디오 튜토리얼이 제공됩니다.',
      zh: '此页面有视频教程。',
      ar: 'هذه الصفحة لديها فيديو تعليمي متاح.',
      'en-GB': 'This page has a video tutorial available.',
      it: 'Questa pagina ha un video tutorial disponibile.',
    }),
    link: {
      content: t({
        en: 'Watch the video tutorial on YouTube',
        fr: 'Regarder le tutoriel vidéo sur YouTube',
        es: 'Ver el video tutorial en YouTube',
        hi: 'YouTube पर वीडियो ट्यूटोरियल देखें',
        ru: 'Посмотреть видео урок на YouTube',
        de: 'Video-Tutorial auf YouTube ansehen',
        ja: 'YouTubeでビデオチュートリアルを見る',
        ko: 'YouTube에서 비디오 튜토리얼 보기',
        zh: '在 YouTube 上观看视频教程',
        ar: 'شاهد الفيديو التعليمي على YouTube',
        pt: 'Assistir ao vídeo tutorial no YouTube',
        'en-GB': 'Watch the video tutorial on YouTube',
        it: 'Guarda il video tutorial su YouTube',
      }),
      label: t({
        en: 'Click to watch the video tutorial',
        fr: 'Cliquez pour regarder le tutoriel vidéo',
        es: 'Haga clic para ver el video tutorial',
        hi: 'वीडियो ट्यूटोरियल देखने के लिए क्लिक करें',
        ru: 'Нажмите, чтобы посмотреть видео урок',
        de: 'Klicken Sie hier, um das Video-Tutorial anzusehen',
        ja: 'ビデオチュートリアルを見るにはクリックしてください',
        ko: '비디오 튜토리얼을 보려면 클릭하십시오',
        zh: '点击观看视频教程',
        ar: 'انقر لمشاهدة الفيديو التعليمي',
        pt: 'Clique para assistir ao vídeo tutorial',
        'en-GB': 'Click to watch the video tutorial',
        it: 'Fai clic per guardare il video tutorial',
      }),
    },
  },
} satisfies Dictionary;

export default youtubeVideoMessageContent;
