import { type Dictionary, t } from 'intlayer';

const showcaseSuggestionContent = {
  key: 'showcase-suggestion',
  content: {
    title: t({
      en: 'Built with Intlayer',
      'en-GB': 'Built with Intlayer',
      fr: 'Construit avec Intlayer',
      es: 'Creado con Intlayer',
      de: 'Mit Intlayer erstellt',
      ja: 'Intlayer で構築',
      ko: 'Intlayer로 제작됨',
      zh: '使用 Intlayer 构建',
      it: 'Realizzato con Intlayer',
      pt: 'Feito com Intlayer',
      hi: 'Intlayer से बनाया गया',
      ar: 'مبني باستخدام Intlayer',
      ru: 'Создано на Intlayer',
      tr: 'Intlayer ile geliştirildi',
      pl: 'Zbudowane z Intlayer',
      id: 'Dibuat dengan Intlayer',
      vi: 'Được xây dựng với Intlayer',
      uk: 'Створено на Intlayer',
    }),
    description: t({
      en: 'This site uses Intlayer. Is it yours? Add it to the Intlayer showcase.',
      'en-GB':
        'This site uses Intlayer. Is it yours? Add it to the Intlayer showcase.',
      fr: 'Ce site utilise Intlayer. C’est le vôtre ? Ajoutez-le au showcase Intlayer.',
      es: 'Este sitio usa Intlayer. ¿Es tuyo? Añádelo al showcase de Intlayer.',
      de: 'Diese Website nutzt Intlayer. Ist es deine? Füge sie zum Intlayer-Showcase hinzu.',
      ja: 'このサイトは Intlayer を使用しています。あなたのサイトですか？Intlayer ショーケースに追加しましょう。',
      ko: '이 사이트는 Intlayer를 사용합니다. 당신의 사이트인가요? Intlayer 쇼케이스에 추가하세요.',
      zh: '该网站使用了 Intlayer。是你的网站吗？将它添加到 Intlayer 展示页。',
      it: 'Questo sito usa Intlayer. È tuo? Aggiungilo allo showcase di Intlayer.',
      pt: 'Este site usa Intlayer. É seu? Adicione-o ao showcase do Intlayer.',
      hi: 'यह साइट Intlayer का उपयोग करती है। क्या यह आपकी है? इसे Intlayer शोकेस में जोड़ें।',
      ar: 'يستخدم هذا الموقع Intlayer. هل هو موقعك؟ أضفه إلى معرض Intlayer.',
      ru: 'Этот сайт использует Intlayer. Он ваш? Добавьте его в витрину Intlayer.',
      tr: 'Bu site Intlayer kullanıyor. Sizin mi? Intlayer vitrinine ekleyin.',
      pl: 'Ta strona korzysta z Intlayer. To Twoja? Dodaj ją do galerii Intlayer.',
      id: 'Situs ini menggunakan Intlayer. Milik Anda? Tambahkan ke showcase Intlayer.',
      vi: 'Trang web này dùng Intlayer. Là của bạn? Hãy thêm vào showcase của Intlayer.',
      uk: 'Цей сайт використовує Intlayer. Він ваш? Додайте його до вітрини Intlayer.',
    }),
    submitButton: t({
      en: 'Submit to the showcase',
      'en-GB': 'Submit to the showcase',
      fr: 'Soumettre au showcase',
      es: 'Enviar al showcase',
      de: 'Zum Showcase einreichen',
      ja: 'ショーケースに投稿',
      ko: '쇼케이스에 제출',
      zh: '提交到展示页',
      it: 'Invia allo showcase',
      pt: 'Enviar para o showcase',
      hi: 'शोकेस में सबमिट करें',
      ar: 'إرسال إلى المعرض',
      ru: 'Отправить в витрину',
      tr: 'Vitrine gönder',
      pl: 'Zgłoś do galerii',
      id: 'Kirim ke showcase',
      vi: 'Gửi lên showcase',
      uk: 'Надіслати до вітрини',
    }),
  },
  title: 'Showcase suggestion',
  description:
    'Popup card inviting the user to submit a site built with Intlayer to the Intlayer showcase.',
  tags: ['chrome-extension', 'popup', 'showcase'],
} satisfies Dictionary;

export default showcaseSuggestionContent;
