import { type Dictionary, t } from 'intlayer';

const markdownSectionContent = {
  key: 'autocompletion-section',
  title: 'Autocompletion section',
  content: {
    input: t({
      ar: 'عزيز العملاء،\n\nأنا أريد كتابة لك ',
      de: 'Sehr geehrte Kundin,\n\nIch schreibe Ihnen ',
      en: 'Dear customer,\n\nI am writing to you ',
      'en-GB': 'Dear customer,\n\nI am writing to you ',
      es: 'Estimado cliente,\n\nEstoy escribiendo a usted ',
      fr: 'Cher client,\n\nJe vous écris ',
      hi: 'धन्यवाद, मैंने आपको ',
      it: 'Caro cliente,\n\nSto scrivendo a te ',
      ja: 'お客様さん、\n\nこんにちは。私はあなたに書きます ',
      ko: '사용자님,\n\n안녕하세요. 나는 당신에게 ',
      pt: 'Caro cliente,\n\nEstou escrevendo para você ',
      ru: 'Дорогой клиент,\n\nЯ напишу вам ',
      tr: 'Değerli müşteri,\n\nSize yazıyorum ',
      zh: '您好，我是写给您的 ',
      pl: 'Szanowny Kliencie,\n\nPiszę do Państwa ',
      id: 'Pelanggan yang terhormat,\n\nSaya menulis kepada Anda ',
      vi: 'Kính gửi Quý khách,\n\nTôi viết thư này ',
      uk: 'Шановний(-а) клієнте,\n\nПишу вам ',
    }),
    suggestion: t({
      ar: 'لتأكيد طلبك',
      de: 'um Bestellung zu bestätigen',
      en: 'to confirm your order',
      'en-GB': 'to confirm your order',
      es: 'para confirmar su pedido',
      fr: 'pour confirmer votre commande',
      hi: 'आपके आदेश की पुष्टि करने के लिए',
      it: 'per confermare il tuo ordine',
      ja: 'お客様の注文を確認する',
      ko: '당신의 주문을 확인하려면',
      pt: 'para confirmar o seu pedido',
      ru: 'для подтверждения вашего заказа',
      tr: 'siparişinizi onaylamak için',
      zh: '确认您的订单',
      pl: 'aby potwierdzić Państwa zamówienie',
      id: 'untuk mengonfirmasi pesanan Anda',
      vi: 'để xác nhận đơn hàng của Quý khách',
      uk: 'щоб підтвердити ваше замовлення',
    }),
    ariaLabel: t({
      ar: 'محرر الإكمال التلقائي',
      de: 'Autovervollständigungs-Editor',
      en: 'Autocompletion editor',
      'en-GB': 'Autocompletion editor',
      es: 'Editor de autocompletado',
      fr: 'Éditeur de complétion automatique',
      hi: 'स्वचालित पूर्णिति एडिटर',
      it: 'Editor di autocompletamento',
      ja: '自動補完エディター',
      ko: '자동 완성 편집기',
      pt: 'Editor de autocompletar',
      ru: 'Редактор автозавершения',
      tr: 'Otomatik Tamamlama düzenleyicisi',
      zh: '自动补全编辑器',
      pl: 'Edytor autouzupełniania',
      id: 'Editor autocompletion',
      vi: 'Trình soạn thảo tự hoàn thành',
      uk: 'Редактор автозаповнення',
    }),
  },
  description:
    'Content declaration for the Autocompletion section of the landing page. Includes UI strings for an editor experience such as input prompts and autocomplete suggestions.',
  tags: ['landing page', 'UI component', 'autocompletion'],
} satisfies Dictionary;

export default markdownSectionContent;
