import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'change-password-form',
  content: {
    openButton: {
      text: t({
        en: 'Change password',
        'en-GB': 'Change password',
        fr: 'Changer le mot de passe',
        es: 'Cambiar la contraseña',
        de: 'Passwort ändern',
        ja: 'パスワードを変更',
        ko: '비밀번호 변경',
        zh: '更改密码',
        it: 'Cambia password',
        pt: 'Alterar senha',
        hi: 'पासवर्ड बदलें',
        ar: 'تغيير كلمة المرور',
        ru: 'Изменить пароль',
        tr: 'Şifreyi değiştir',
        pl: 'Zmień hasło',
        id: 'Ubah kata sandi',
        vi: 'Đổi mật khẩu',
        uk: 'Змінити пароль',
      }),
      ariaLabel: t({
        en: 'Click to change your password',
        'en-GB': 'Click to change your password',
        fr: 'Cliquez pour changer votre mot de passe',
        es: 'Haz clic para cambiar tu contraseña',
        de: 'Klicken Sie, um Ihr Passwort zu ändern',
        ja: 'パスワードを変更するにはクリック',
        ko: '비밀번호를 변경하려면 클릭하세요',
        zh: '点击更改您的密码',
        it: 'Clicca per cambiare la tua password',
        pt: 'Clique para alterar sua senha',
        hi: 'पासवर्ड बदलने के लिए क्लिक करें',
        ar: 'انقر لتغيير كلمة المرور',
        ru: 'Нажмите, чтобы изменить пароль',
        tr: 'Şifrenizi değiştirmek için tıklayın',
        pl: 'Kliknij, aby zmienić hasło',
        id: 'Klik untuk mengubah kata sandi',
        vi: 'Nhấp để đổi mật khẩu',
        uk: 'Натисніть, щоб змінити пароль',
      }),
    },
    goToLoginButton: {
      text: t({
        hi: 'होम पेज पर जाएँ',
        pt: 'Ir para a página inicial',
        it: 'Vai alla home page',
        ar: 'اذهب إلى الصفحة الرئيسية',
        zh: '前往主页',
        ko: '홈페이지로 이동',
        ja: 'トップページへ',
        ru: 'Перейти на главную страницу',
        en: 'Go to home page',
        fr: "Retourner à l'accueil",
        es: 'Ir a la página de inicio',
        de: 'Gehen Sie zur Startseite',
        'en-GB': 'Go to home page',
        tr: 'Ana sayfaya git',
        pl: 'Przejdź na stronę główną',
        id: 'Ke beranda',
        vi: 'Về trang chủ',
        uk: 'Перейти на головну сторінку',
      }),
      ariaLabel: t({
        hi: 'होम पेज पर जाने के लिए क्लिक करें',
        pt: 'Clique para ir para a home page',
        it: 'Clicca per andare alla home page',
        ar: 'انقر للذهاب إلى الصفحة الرئيسية',
        zh: '点击进入主页',
        ko: '홈페이지로 가는 방법을 클릭하세요',
        ja: 'ホームページに行くにはクリックしてください',
        ru: 'Нажмите, чтобы перейти на главную страницу',
        en: 'Click to go to home page',
        fr: "Cliquez pour aller à la page d'accueil",
        es: 'Haz clic para ir a la página de inicio',
        de: 'Klicken Sie, um zur Startseite zu gehen',
        'en-GB': 'Click to go to home page',
        tr: 'Ana sayfaya gitmek için tıklayın',
        pl: 'Kliknij, aby przejść na stronę główną',
        id: 'Klik untuk pergi ke beranda',
        vi: 'Nhấp để về trang chủ',
        uk: 'Натисніть, щоб перейти на головну сторінку',
      }),
    },
  },
  title: 'Change password form',
  description:
    'Content for the change password form component, including button text and accessibility label to navigate back to the home page.',
  tags: ['auth form', 'change password'],
} satisfies Dictionary;

export default content;
