import { type Dictionary, t } from 'intlayer';
import { PagesRoutes } from '@/Routes';

const docNavTitlesContent = {
  key: 'common-questions',
  content: {
    title: t({
      fr: 'Questions fréquentes',
      en: 'Frequently asked questions',
      es: 'Preguntas frecuentes',
      'en-GB': 'Frequently asked questions',
      de: 'Häufig gestellte Fragen',
      ja: 'よくある質問',
      ko: '자주 묻는 질문',
      zh: '常见问题',
      it: 'Domande frequenti',
      pt: 'Perguntas frequentes',
      hi: 'अधिकतर पूछे जाने वाले प्रश्न',
      ar: 'الأسئلة الشائعة',
      ru: 'Часто задаваемые вопросы',
      tr: 'Sıkça Sorulan Sorular',
    }),

    content: [
      {
        question: t({
          en: 'What is internationalization (i18n)?',
          fr: 'Qu’est-ce que l’internationalisation (i18n) ?',
          es: '¿Qué es la internacionalización (i18n)?',
          'en-GB': 'What is internationalization (i18n)?',
          de: 'Was ist Internationalisierung (i18n)?',
          ja: '国際化（i18n）とは何ですか？',
          ko: '국제화(i18n)란 무엇입니까?',
          zh: '什么是国际化（i18n）？',
          it: 'Cos’è l’internazionalizzazione (i18n)?',
          pt: 'O que é internacionalização (i18n)?',
          hi: 'अंतर्राष्ट्रीयकरण (i18n) क्या है?',
          ar: 'ما هو التدويل (i18n)؟',
          ru: 'Что такое интернационализация (i18n)?',
          tr: 'Uluslararasılaştırma (i18n) nedir?',
        }),
        answer: t({
          en: 'Internationalization (i18n) is the process of designing and developing applications like Next.js, react, or express to support multiple languages easily. It enables you to create multilingual websites by simplifying the translation process. Tools like TypeScript make it easier to implement i18n, allowing for efficient and easy adaptation of your application to different languages and regions.',
          fr: "L'internationalisation (i18n) est le processus de conception et de développement d'applications comme Next.js, react ou express pour prendre en charge facilement plusieurs langues. Elle vous permet de créer des sites web multilingues en simplifiant le processus de traduction. Des outils comme TypeScript facilitent la mise en œuvre de l'i18n, permettant une adaptation efficace et facile de votre application à différentes langues et régions.",
          es: 'La internacionalización (i18n) es el proceso de diseñar y desarrollar aplicaciones como Next.js, react o express para admitir fácilmente múltiples idiomas. Te permite crear sitios web multilingües simplificando el proceso de traducción. Herramientas como TypeScript facilitan la implementación de i18n, permitiendo una adaptación eficiente y fácil de tu aplicación a diferentes idiomas y regiones.',
          'en-GB':
            'Internationalization (i18n) is the process of designing and developing applications like Next.js, react, or express to support multiple languages easily. It enables you to create multilingual websites by simplifying the translation process. Tools like TypeScript make it easier to implement i18n, allowing for efficient and easy adaptation of your application to different languages and regions.',
          de: 'Die Internationalisierung (i18n) ist der Prozess der Gestaltung und Entwicklung von Anwendungen wie Next.js, React oder Express, um mehrere Sprachen einfach zu unterstützen. Es ermöglicht Ihnen die Erstellung mehrsprachiger Websites, indem der Übersetzungsprozess vereinfacht wird. Tools wie TypeScript erleichtern die Implementierung von i18n und ermöglichen eine effiziente und einfache Anpassung Ihrer Anwendung an verschiedene Sprachen und Regionen.',
          ja: '国際化（i18n）とは、Next.js、react、またはexpressなどのアプリケーションを設計し、開発して、複数の言語に簡単に対応するプロセスです。翻訳プロセスを簡素化することで、多言語ウェブサイトを作成することができます。TypeScriptのようなツールを使用すると、i18nの実装が容易になり、アプリケーションをさまざまな言語や地域に効率的かつ簡単に適応させることができます。',
          ko: '국제화(i18n)는 Next.js, React 또는 Express와 같은 응용 프로그램을 설계하고 개발하여 여러 언어를 쉽게 지원하는 과정입니다. 이는 번역 프로세스를 단순화하여 다국어 웹사이트를 생성할 수 있도록 합니다. TypeScript와 같은 도구는 i18n을 구현하기 쉽게 하여 애플리케이션을 다양한 언어와 지역에 효율적이고 쉽게 적응할 수 있도록 합니다.',
          zh: '国际化（i18n）是设计和开发像 Next.js、react 或 express 等应用程序以轻松支持多语言的过程。这使得您能够通过简化翻译过程来创建多语种网站。像 TypeScript 这样的工具使得实现 i18n 更加容易，并允许您的应用程序高效且轻松地适应不同的语言和地区。',
          it: 'L’internazionalizzazione (i18n) è il processo di progettazione e sviluppo di applicazioni come Next.js, React o Express per supportare facilmente più lingue. Ti consente di creare siti web multilingue semplificando il processo di traduzione. Strumenti come TypeScript rendono più facile implementare l’i18n, consentendo un’adattamento efficiente e semplice della tua applicazione a diverse lingue e regioni.',
          pt: 'A internacionalização (i18n) é o processo de projetar e desenvolver aplicativos como Next.js, react ou express para suportar facilmente vários idiomas. Isso permite que você crie sites multilíngues simplificando o processo de tradução. Ferramentas como TypeScript tornam mais fácil implementar a i18n, permitindo uma adaptação eficiente e fácil do seu aplicativo a diferentes idiomas e regiões.',
          hi: 'अंतर्राष्ट्रीयकरण (i18n) वह प्रक्रिया है जिसमें Next.js, react, या express जैसी आवेदन को आसानी से कई भाषाओं का समर्थन करने के लिए डिजाइन और विकसित किया जाता है। यह आपको अनुवाद प्रक्रिया को सरल बनाकर बहुभाषी वेबसाइट बनाने की अनुमति देता है। TypeScript जैसे उपकरण i18n का कार्यान्वयन करने को आसान बनाते हैं, जिससे आपके अनुप्रयोग को विभिन्न भाषाओं और क्षेत्रों के अनुकूल बनाना कुशल और आसान हो जाता है।',
          ar: 'التدويل (i18n) هو عملية تصميم وتطوير التطبيقات مثل Next.js وReact أو Express لدعم لغات متعددة بسهولة. يتيح لك إنشاء مواقع ويب متعددة اللغات من خلال تبسيط عملية الترجمة. تجعل الأدوات مثل TypeScript من السهل تنفيذ i18n، مما يسمح بتكيف كفء وسهل لتطبيقك مع لغات ومناطق مختلفة.',
          ru: 'Интернационализация (i18n) - это процесс проектирования и разработки приложений, таких как Next.js, React или Express, для удобной поддержки нескольких языков. Она позволяет создавать многоязычные веб-сайты, упрощая процесс перевода. Инструменты, такие как TypeScript, облегчают реализацию i18n, позволяя эффективно и легко адаптировать ваше приложение к различным языкам и регионам.',
          tr: 'Uluslararasılaştırma (i18n), Next.js, React veya Express gibi uygulamaların birden çok dili kolayca destekleyecek şekilde tasarlanması ve geliştirilmesi sürecidir. Çeviri sürecini basitleştirerek çok dilli web siteleri oluşturmanızı sağlar. TypeScript gibi araçlar, i18n uygulamasını kolaylaştırır ve uygulamanızın farklı dillere ve bölgelere verimli ve kolay bir şekilde uyum sağlamasına olanak tanır.',
        }),
        callToAction: {
          label: t({
            en: 'Read more about i18n',
            fr: 'En savoir plus sur l’internationalisation',
            es: 'Leer más sobre la internacionalización',
            'en-GB': 'Read more about i18n',
            de: 'Erfahren Sie mehr über i18n',
            ja: 'i18nについてもっと読む',
            ko: 'i18n에 대해 더 읽어보세요',
            zh: '了解更多关于i18n的信息',
            it: 'Scopri di più sull’internazionalizzazione',
            pt: 'Saiba mais sobre i18n',
            hi: 'अंतर्राष्ट्रीयकरण के बारे में अधिक पढ़ें',
            ar: 'اقرأ المزيد عن التدويل',
            ru: 'Узнайте больше о i18n',
            tr: 'i18n hakkında daha fazla bilgi edinin',
          }),
          alt: t({
            fr: "Cliquez ici pour en savoir plus sur l'internationalisation",
            en: 'Click here to read more about i18n',
            es: 'Haga clic aquí para leer más sobre la internacionalización',
            'en-GB': 'Click here to read more about i18n',
            de: 'Klicken Sie hier, um mehr über i18n zu erfahren',
            ja: 'i18nについての詳細を読むにはここをクリックしてください',
            ko: 'i18n에 대한 자세한 내용을 보려면 여기를 클릭하세요',
            zh: '点击这里了解有关i18n的更多信息',
            it: 'Clicca qui per leggere di più sull’internazionalizzazione',
            pt: 'Clique aqui para saber mais sobre i18n',
            hi: 'अंतर्राष्ट्रीयकरण के बारे में अधिक जानने के लिए यहां क्लिक करें',
            ar: 'انقر هنا لقراءة المزيد عن التدويل',
            ru: 'Нажмите здесь, чтобы узнать больше о i18n',
            tr: 'i18n hakkında daha fazla bilgi edinmek için tıklayın',
          }),
          url: PagesRoutes.Blog_What_is_i18n,
        },
      },
      {
        question: t({
          en: 'What is Intlayer?',
          fr: 'Qu’est-ce que Intlayer ?',
          es: '¿Qué es Intlayer?',
          'en-GB': 'What is Intlayer?',
          de: 'Was ist Intlayer?',
          ja: 'Intlayerとは何ですか？',
          ko: 'Intlayer란 무엇입니까?',
          zh: 'Intlayer是什么？',
          it: 'Che cos’è Intlayer?',
          pt: 'O que é Intlayer?',
          hi: 'Intlayer क्या है?',
          ar: 'ما هو Intlayer؟',
          ru: 'Что такое Intlayer?',
          tr: 'Intlayer nedir?',
        }),
        answer: t({
          en: 'Intlayer is a package that allows you to manage your multilingual website. It provides a set of tools and utilities that make it easy to set up your website for multilingual content and localization.',
          fr: 'Intlayer est un package qui vous permet de gérer votre site web multilingue. Il fournit un ensemble d’outils et d’utilitaires qui facilitent la mise en place de votre site web pour le contenu multilingue et la localisation.',
          es: 'Intlayer es un paquete que te permite gestionar tu sitio web multilingüe. Proporciona un conjunto de herramientas y utilidades que facilitan la configuración de tu sitio web para el contenido multilingüe y la localización.',
          'en-GB':
            'Intlayer is a package that allows you to manage your multilingual website. It provides a set of tools and utilities that make it easy to set up your website for multilingual content and localization.',
          de: 'Intlayer ist ein Paket, das es Ihnen ermöglicht, Ihre mehrsprachige Website zu verwalten. Es bietet eine Reihe von Werkzeugen und Dienstprogrammen, die das Einrichten Ihrer Website für mehrsprachige Inhalte und Lokalisierung erleichtern.',
          ja: 'Intlayerは、あなたの多言語ウェブサイトを管理するためのパッケージです。多言語コンテンツおよびローカリゼーションのためにウェブサイトを簡単に設定するためのツールとユーティリティのセットを提供します。',
          ko: 'Intlayer는 다국어 웹사이트를 관리할 수 있도록 하는 패키지입니다. 다국어 콘텐츠와 현지화를 위한 웹사이트 설정을 쉽게 할 수 있도록 도와주는 도구 및 유틸리티 세트를 제공합니다.',
          zh: 'Intlayer是一个允许您管理多语言网站的包。它提供了一系列工具和实用程序，使您可以轻松地为多语言内容和本地化设置您的网站。',
          it: 'Intlayer è un pacchetto che ti consente di gestire il tuo sito web multilingue. Fornisce un insieme di strumenti e utility che facilitano la configurazione del tuo sito web per contenuti multilingue e localizzazione.',
          pt: 'Intlayer é um pacote que permite gerenciar seu site multilíngue. Ele fornece um conjunto de ferramentas e utilitários que facilitam a configuração de seu site para conteúdo multilíngue e localização.',
          hi: 'Intlayer एक पैकेज है जो आपको अपनी बहुभाषी वेबसाइट को प्रबंधित करने की अनुमति देता है। यह बहुभाषी सामग्री और स्थानीयकरण के लिए आपकी वेबसाइट को सेटअप करना आसान बनाने के लिए टूल और उपयोगिताओं का एक सेट प्रदान करता है。',
          ar: 'Intlayer هو حزمة تسمح لك بإدارة موقع الويب متعدد اللغات الخاص بك. يوفر مجموعة من الأدوات والمرافق التي تجعل من السهل إعداد موقع الويب الخاص بك لمحتوى متعدد اللغات والتعريب.',
          ru: 'Intlayer - это пакет, который позволяет вам управлять вашим многоязычным веб-сайтом. Он предоставляет набор инструментов и утилит, которые облегчают настройку вашего веб-сайта для многоязычного контента и локализации.',
          tr: 'Intlayer, çok dilli web sitenizi yönetmenizi sağlayan bir pakettir. Çok dilli içerik ve yerelleştirme için web sitenizi kolayca kurmanızı sağlayan bir dizi araç ve yardımcı program sunar.',
        }),
        callToAction: {
          label: t({
            en: 'Read more about Intlayer',
            fr: 'En savoir plus sur Intlayer',
            es: 'Leer más sobre Intlayer',
            'en-GB': 'Read more about Intlayer',
            de: 'Erfahren Sie mehr über Intlayer',
            ja: 'Intlayerについてもっと読む',
            ko: 'Intlayer에 대해 더 읽어보세요',
            zh: '了解更多关于Intlayer的信息',
            it: 'Scopri di più su Intlayer',
            pt: 'Saiba mais sobre o Intlayer',
            hi: 'Intlayer के बारे में अधिक पढ़ें',
            ar: 'اقرأ المزيد عن Intlayer',
            ru: 'Узнайте больше о Intlayer',
            tr: 'Intlayer hakkında daha fazla bilgi edinin',
          }),
          alt: t({
            fr: "Cliquez ici pour en savoir plus sur l'utilisation d'Intlayer",
            en: 'Click here to read more about Intlayer usage',
            es: 'Haga clic aquí para leer más sobre el uso de Intlayer',
            'en-GB': 'Click here to read more about Intlayer usage',
            de: 'Klicken Sie hier, um mehr über die Verwendung von Intlayer zu erfahren',
            ja: 'Intlayerの使用についての詳細を読むにはここをクリックしてください',
            ko: 'Intlayer 사용에 대한 더 많은 정보를 보려면 여기를 클릭하세요',
            zh: '点击这里了解有关Intlayer使用的更多信息',
            it: 'Clicca qui per leggere di più su come usare Intlayer',
            pt: 'Clique aqui para saber mais sobre o uso do Intlayer',
            hi: 'Intlayer के उपयोग के बारे में अधिक पढ़ने के लिए यहां क्लिक करें',
            ar: 'انقر هنا لقراءة المزيد عن استخدام Intlayer',
            ru: 'Нажмите здесь, чтобы узнать больше о использовании Intlayer',
            tr: 'Intlayer kullanımı hakkında daha fazla bilgi edinmek için tıklayın',
          }),
          url: PagesRoutes.Doc,
        },
      },
      {
        question: t({
          en: 'What are the main features of Intlayer?',
          fr: 'Quelles sont les principales fonctionnalités d’Intlayer ?',
          es: '¿Cuáles son las principales características de Intlayer?',
          'en-GB': 'What are the main features of Intlayer?',
          de: 'Was sind die Hauptmerkmale von Intlayer?',
          ja: 'Intlayerの主な機能は何ですか？',
          ko: 'Intlayer의 주요 기능은 무엇입니까?',
          zh: 'Intlayer的主要特性是什么？',
          it: 'Quali sono le principali funzionalità di Intlayer?',
          pt: 'Quais são os principais recursos do Intlayer?',
          hi: 'Intlayer की मुख्य विशेषताएँ क्या हैं?',
          ar: 'ما هي المميزات الرئيسية لـ Intlayer؟',
          ru: 'Каковы основные функции Intlayer?',
          tr: 'Intlayer’ın temel özellikleri nelerdir?',
        }),
        answer: t({
          en: 'Intlayer simplifies configuration management and enables internationalization for various types of JavaScript applications, including server components. It allows content declaration directly alongside components, improving codebase maintainability. Additionally, Intlayer leverages TypeScript to prevent missing declarations. Finally, Intlayer offers a visual editor, enabling non-developers to edit website content, translate automatically using AI, and optimize the application’s SEO.',
          fr: 'Intlayer simplifie la gestion des configurations et permet l’internationalisation de plusieurs types d’applications JavaScript, y compris les server components. Il permet de déclarer le contenu au même niveau que les composants, ce qui améliore la maintenabilité de la base de code. De plus, Intlayer utilise TypeScript pour prévenir les déclarations manquantes. Enfin, Intlayer offre un éditeur visuel, permettant aux non-développeurs de modifier le contenu du site web, de traduire automatiquement grâce à l’IA et d’optimiser le SEO de l’application.',
          es: 'Intlayer simplifica la gestión de configuraciones y habilita la internacionalización para varios tipos de aplicaciones JavaScript, incluidos los server components. Permite declarar el contenido directamente junto a los componentes, mejorando el mantenimiento del código. Además, Intlayer utiliza TypeScript para evitar declaraciones faltantes. Finalmente, Intlayer ofrece un editor visual que permite a los no desarrolladores editar el contenido del sitio web, traducir automáticamente con IA y optimizar el SEO de la aplicación.',
          'en-GB':
            'Intlayer simplifies configuration management and enables internationalization for various types of JavaScript applications, including server components. It allows content declaration directly alongside components, improving codebase maintainability. Additionally, Intlayer leverages TypeScript to prevent missing declarations. Finally, Intlayer offers a visual editor, enabling non-developers to edit website content, translate automatically using AI, and optimize the application’s SEO.',
          de: 'Intlayer vereinfacht das Konfigurationsmanagement und ermöglicht die Internationalisierung für verschiedene Arten von JavaScript-Anwendungen, einschließlich Serverkomponenten. Es ermöglicht die Deklaration von Inhalten direkt neben den Komponenten, was die Wartbarkeit des Codes verbessert. Darüber hinaus nutzt Intlayer TypeScript, um das Fehlen von Deklarationen zu verhindern. Schließlich bietet Intlayer einen visuellen Editor, der es Nicht-Entwicklern ermöglicht, den Inhalt der Website zu bearbeiten, automatisch mit KI zu übersetzen und die SEO der Anwendung zu optimieren.',
          ja: 'Intlayerは構成管理を簡素化し、サーバーコンポーネントを含むさまざまなタイプのJavaScriptアプリケーションの国際化を可能にします。コンポーネントと同じ場所でコンテンツの宣言を行うことができ、コードベースの保守性が向上します。さらに、IntlayerはTypeScriptを活用して宣言の欠落を防ぎます。最後に、Intlayerはビジュアルエディターを提供し、非開発者がWebサイトのコンテンツを編集し、AIを使用して自動翻訳し、アプリケーションのSEOを最適化できるようにします。',
          ko: 'Intlayer는 구성 관리를 간소화하고 서버 구성 요소를 포함한 다양한 유형의 JavaScript 애플리케이션에 대한 국제화를 가능하게 합니다. 구성 요소와 나란히 콘텐츠 선언을 허용하여 코드베이스의 유지관리를 개선합니다. 또한 Intlayer는 TypeScript를 활용하여 누락된 선언을 방지합니다. 마지막으로 Intlayer는 비개발자가 웹사이트 콘텐츠를 편집하고 AI를 사용하여 자동으로 번역하며 애플리케이션의 SEO를 최적화할 수 있게 하는 비주얼 편집기를 제공합니다.',
          zh: 'Intlayer简化了配置管理，并使各种类型的JavaScript应用程序（包括服务器组件）能够实现国际化。它允许内容在组件旁边直接声明，从而改善代码库的可维护性。此外，Intlayer利用TypeScript防止缺失声明。最后，Intlayer提供了一个可视化编辑器，使非开发人员能够编辑网站内容，使用AI自动翻译并优化应用程序的SEO。',
          it: 'Intlayer semplifica la gestione delle configurazioni e abilita l’internazionalizzazione per vari tipi di applicazioni JavaScript, inclusi i componenti server. Consente la dichiarazione del contenuto direttamente accanto ai componenti, migliorando la manutenzione del codice. Inoltre, Intlayer sfrutta TypeScript per prevenire le dichiarazioni mancanti. Infine, Intlayer offre un editor visivo, che consente a chi non è sviluppatore di modificare i contenuti del sito web, tradurre automaticamente utilizzando l’intelligenza artificiale e ottimizzare il SEO dell’applicazione.',
          pt: 'O Intlayer simplifica a gestão da configuração e habilita a internacionalização para vários tipos de aplicações JavaScript, incluindo componentes de servidor. Permite a declaração do conteúdo diretamente ao lado dos componentes, melhorando a manutenibilidade da base de código. Além disso, o Intlayer utiliza o TypeScript para evitar declarações ausentes. Finalmente, o Intlayer oferece um editor visual, permitindo que não desenvolvedores editem o conteúdo do site, traduzam automaticamente usando IA e otimizem o SEO da aplicação.',
          hi: 'Intlayer कॉन्फ़िगरेशन प्रबंधन को सरल बनाता है और विभिन्न प्रकार के JavaScript अनुप्रयोगों, जिसमें सर्वर घटक शामिल हैं, के लिए अंतर्राष्ट्रीयकरण सक्षम करता है। यह घटकों के साथ सीधे सामग्री की घोषणा की अनुमति देता है, जिससे कोडबेस की रखरखाव क्षमता में सुधार होता है। इसके अलावा, Intlayer को अनुप्रयोग की घोषणा समाप्त होने से रोकने के लिए TypeScript का लाभ उठाता है। अंततः, Intlayer एक दृश्य संपादक प्रदान करता है, जो गैर-डेवलपर्स को वेबसाइट की सामग्री को संपादित करने, AI का उपयोग करके स्वचालित रूप से अनुवाद करने और एप्लिकेशन के SEO को अनुकूलित करने में सक्षम बनाता है।',
          ar: 'تسهل Intlayer إدارة التكوين وتتيح التدويل لمجموعة متنوعة من أنواع تطبيقات JavaScript، بما في ذلك المكونات الخادم. يسمح بإعلان المحتوى مباشرة بجانب المكونات، مما يحسن من قابلية صيانة قاعدة التعليمات البرمجية. بالإضافة إلى ذلك، تستفيد Intlayer من TypeScript لمنع فقدان التصريحات. أخيرًا، تقدم Intlayer محررًا مرئيًا، مما يتيح لغير المطورين تحرير محتوى الموقع، والترجمة تلقائيًا باستخدام الذكاء الاصطناعي، وتحسين تحسين محركات البحث للتطبيق.',
          ru: 'Intlayer упрощает управление конфигурацией и позволяет интернационализировать различные типы JavaScript-приложений, включая серверные компоненты. Он позволяет объявлять содержимое непосредственно рядом с компонентами, улучшая поддерживаемость кодовой базы. Кроме того, Intlayer использует TypeScript, чтобы предотвратить отсутствие деклараций. Наконец, Intlayer предлагает визуальный редактор, позволяя недевелоперам редактировать содержимое сайта, автоматически переводить с помощью ИИ и оптимизировать SEO приложения.',
          tr: "Intlayer, yapılandırma yönetimini basitleştirir ve sunucu bileşenleri de dahil olmak üzere çeşitli türde JavaScript uygulamaları için uluslararasılaştırmayı etkinleştirir. İçerik beyanını bileşenlerin yanında doğrudan yapmanıza olanak tanır ve kod tabanının sürdürülebilirliğini artırır. Ayrıca, Intlayer, eksik beyanları önlemek için TypeScript'ten yararlanır. Son olarak, Intlayer, geliştirici olmayanların web sitesi içeriğini düzenlemesine, AI kullanarak otomatik olarak çeviri yapmasına ve uygulamanın SEO'sunu optimize etmesine olanak tanıyan görsel bir editör sunar.",
        }),
        callToAction: {
          label: t({
            en: "Read more about Intlayer's features",
            fr: "En savoir plus sur les fonctionnalités d'Intlayer",
            es: 'Leer más sobre las características de Intlayer',
            'en-GB': "Read more about Intlayer's features",
            de: 'Erfahren Sie mehr über die Funktionen von Intlayer',
            ja: 'Intlayerの機能についてもっと読む',
            ko: 'Intlayer의 기능에 대해 더 읽어보세요',
            zh: '了解更多关于Intlayer功能的信息',
            it: 'Scopri di più sulle funzionalità di Intlayer',
            pt: 'Saiba mais sobre os recursos do Intlayer',
            hi: 'Intlayer की विशेषताओं के बारे में अधिक पढ़ें',
            ar: 'اقرأ المزيد عن مميزات Intlayer',
            ru: 'Узнайте больше о функциях Intlayer',
            tr: 'Intlayer’ın özellikleri hakkında daha fazla bilgi edinin',
          }),
          alt: t({
            fr: "Cliquez ici pour en savoir plus sur les fonctionnalités d'Intlayer",
            en: 'Click here to read more about Intlayer features',
            es: 'Haga clic aquí para leer más sobre las características de Intlayer',
            'en-GB': 'Click here to read more about Intlayer features',
            de: 'Klicken Sie hier, um mehr über die Funktionen von Intlayer zu erfahren',
            ja: 'Intlayerの機能についての詳細を読むにはここをクリックしてください',
            ko: 'Intlayer 기능에 대한 더 많은 정보를 보려면 여기를 클릭하세요',
            zh: '点击这里了解有关Intlayer功能的更多信息',
            it: 'Clicca qui per leggere di più sulle funzionalità di Intlayer',
            pt: 'Clique aqui para saber mais sobre os recursos do Intlayer',
            hi: 'Intlayer की विशेषताओं के बारे में अधिक जानने के लिए यहां क्लिक करें',
            ar: 'انقر هنا لقراءة المزيد عن ميزات Intlayer',
            ru: 'Нажмите здесь, чтобы узнать больше о функциях Intlayer',
            tr: 'Intlayer özellikleri hakkında daha fazla bilgi edinmek için tıklayın',
          }),
          url: PagesRoutes.Doc_Why,
        },
      },
      {
        question: t({
          en: 'How does Intlayer integrate with Next.js?',
          fr: 'Comment Intlayer s’intègre-t-il avec Next.js ?',
          es: '¿Cómo se integra Intlayer con Next.js?',
          'en-GB': 'How does Intlayer integrate with Next.js?',
          de: 'Wie integriert sich Intlayer in Next.js?',
          ja: 'IntlayerはNext.jsとどのように統合されますか？',
          ko: 'Intlayer는 Next.js와 어떻게 통합됩니까?',
          zh: 'Intlayer如何与Next.js集成？',
          it: 'Come si integra Intlayer con Next.js?',
          pt: 'Como o Intlayer se integra ao Next.js?',
          hi: 'Intlayer कैसे Next.js के साथ एकीकृत होता है?',
          ar: 'كيف يتكامل Intlayer مع Next.js؟',
          ru: 'Как Intlayer интегрируется с Next.js?',
          tr: 'Intlayer, Next.js ile nasıl entegre olur?',
        }),
        answer: t({
          en: 'Intlayer integrates with Next.js to enable server-side rendering and static site generation, making multilingual content delivery more efficient.',
          fr: 'Intlayer s’intègre avec Next.js pour permettre le rendu côté serveur et la génération de sites statiques, rendant la diffusion de contenu multilingue plus efficace.',
          es: 'Intlayer se integra con Next.js para habilitar el renderizado del lado del servidor y la generación de sitios estáticos, haciendo más eficiente la entrega de contenido multilingüe.',
          'en-GB':
            'Intlayer integrates with Next.js to enable server-side rendering and static site generation, making multilingual content delivery more efficient.',
          de: 'Intlayer integriert sich in Next.js, um serverseitiges Rendering und die Erstellung statischer Seiten zu ermöglichen, was die Bereitstellung mehrsprachiger Inhalte effizienter macht.',
          ja: 'Intlayerは、サーバーサイドレンダリングと静的サイト生成を可能にするためにNext.jsと統合されており、マルチリンガルコンテンツの配信をより効率的にします。',
          ko: 'Intlayer는 서버 사이드 렌더링 및 정적 사이트 생성을 가능하게 하여 다국어 콘텐츠 제공을 보다 효율적으로 통합합니다.',
          zh: 'Intlayer与Next.js集成以启用服务器端渲染和静态站点生成，从而使多语言内容交付更有效。',
          it: 'Intlayer si integra con Next.js per abilitare il rendering lato server e la generazione di siti statici, rendendo la consegna dei contenuti multilingue più efficiente.',
          pt: 'O Intlayer se integra ao Next.js para permitir o renderização do lado do servidor e a geração de sites estáticos, tornando a entrega de conteúdo multilíngue mais eficiente.',
          hi: 'Intlayer Next.js के साथ सर्वर-साइड रेंडरिंग और स्थिर साइट जनरेट करने के लिए एकीकृत होता है, जिससे बहुभाषी सामग्री वितरण अधिक प्रभावी तरीके से हो सके।',
          ar: 'يتكامل Intlayer مع Next.js لتمكين عملية التجسيد من جانب الخادم وإنشاء المواقع الثابتة، مما يجعل تسليم المحتوى متعدد اللغات أكثر كفاءة.',
          ru: 'Intlayer интегрируется с Next.js, чтобы обеспечить рендеринг на стороне сервера и генерацию статических сайтов, делая доставку многоязычного контента более эффективной.',
          tr: 'Intlayer, Next.js ile entegre olarak sunucu tarafı render ve statik site oluşturmayı etkinleştirir, çok dilli içerik teslimatını daha verimli hale getirir.',
        }),
        callToAction: {
          label: t({
            en: 'Read more about Next.js integration',
            fr: 'En savoir plus sur l’intégration de Next.js',
            es: 'Leer más sobre la integración de Next.js',
            'en-GB': 'Read more about Next.js integration',
            de: 'Erfahren Sie mehr über die Integration von Next.js',
            ja: 'Next.jsの統合についてもっと読む',
            ko: 'Next.js 통합에 대해 더 읽어보세요',
            zh: '了解更多关于Next.js集成的信息',
            it: 'Scopri di più sull’integrazione con Next.js',
            pt: 'Saiba mais sobre a integração com o Next.js',
            hi: 'Next.js के साथ एकीकरण के बारे में अधिक पढ़ें',
            ar: 'اقرأ المزيد عن تكامل Intlayer مع Next.js',
            ru: 'Узнайте больше об интеграции с Next.js',
            tr: 'Next.js entegrasyonu hakkında daha fazla bilgi edinin',
          }),
          alt: t({
            fr: "Cliquez ici pour en savoir plus sur l'intégration d'Intlayer avec Next.js",
            en: 'Click here to read more about Intlayer integration with Next.js',
            es: 'Haga clic aquí para leer más sobre la integración de Intlayer con Next.js',
            'en-GB':
              'Click here to read more about Intlayer integration with Next.js',
            de: 'Klicken Sie hier, um mehr über die Integration von Intlayer in Next.js zu erfahren',
            ja: 'IntlayerのNext.jsとの統合についてさらに読むにはここをクリックしてください',
            ko: 'Intlayer의 Next.js 통합에 대한 자세한 내용을 보려면 여기를 클릭하세요',
            zh: '点击这里了解有关Intlayer与Next.js集成的更多信息',
            it: 'Clicca qui per leggere di più sull’integrazione di Intlayer con Next.js',
            pt: 'Clique aqui para saber mais sobre a integração do Intlayer com o Next.js',
            hi: 'Next.js के साथ Intlayer की एकीकरण के बारे में अधिक पढ़ने के लिए यहां क्लिक करें',
            ar: 'انقر هنا لقراءة المزيد عن تكامل Intlayer مع Next.js',
            ru: 'Нажмите здесь, чтобы узнать больше об интеграции с Next.js',
            tr: "Intlayer'ın Next.js ile entegrasyonu hakkında daha fazla bilgi edinmek için tıklayın",
          }),
          url: PagesRoutes.Doc_Environment_NextJS_15,
        },
      },
      {
        question: t({
          en: 'Is there a visual editor in Intlayer?',
          fr: 'Existe-t-il un éditeur visuel dans Intlayer ?',
          es: '¿Hay un editor visual en Intlayer?',
          'en-GB': 'Is there a visual editor in Intlayer?',
          de: 'Gibt es einen visuellen Editor in Intlayer?',
          ja: 'Intlayerにはビジュアルエディターはありますか？',
          ko: 'Intlayer에 비주얼 편집기가 있습니까?',
          zh: 'Intlayer中有可视化编辑器吗？',
          it: 'Esiste un editor visivo in Intlayer?',
          pt: 'Existe um editor visual no Intlayer?',
          hi: 'क्या Intlayer में एक दृश्य संपादक है?',
          ar: 'هل هناك محرر مرئي في Intlayer؟',
          ru: 'Есть ли визуальный редактор в Intlayer?',
          tr: "Intlayer'da görsel bir editör var mı?",
        }),
        answer: t({
          en: 'Yes, Intlayer provides an optional visual editor for managing content easily without diving into code.',
          fr: 'Oui, Intlayer propose un éditeur visuel optionnel pour gérer le contenu facilement sans plonger dans le code.',
          es: 'Sí, Intlayer proporciona un editor visual opcional para gestionar contenido fácilmente sin necesidad de entrar en el código.',
          'en-GB':
            'Yes, Intlayer provides an optional visual editor for managing content easily without diving into code.',
          de: 'Ja, Intlayer bietet einen optionalen visuellen Editor, um Inhalte einfach zu verwalten, ohne in den Code eintauchen zu müssen.',
          ja: 'はい、Intlayerには、コードを掘り下げずにコンテンツを簡単に管理するためのオプションのビジュアルエディターがあります。',
          ko: '예, Intlayer는 코드에 다이빙하지 않고 콘텐츠를 쉽게 관리할 수 있는 선택적 비주얼 편집기를 제공합니다.',
          zh: '是的，Intlayer提供了一个可选的可视化编辑器，可轻松管理内容，而无需深入代码。',
          it: 'Sì, Intlayer offre un editor visivo opzionale per gestire i contenuti facilmente senza dover entrare nel codice.',
          pt: 'Sim, o Intlayer oferece um editor visual opcional para gerenciar conteúdo facilmente sem mergulhar no código.',
          hi: 'जी हां, Intlayer एक वैकल्पिक दृश्य संपादक प्रदान करता है जिससे बिना कोड में जाकर सामग्री को आसानी से प्रबंधित किया जा सकता है।',
          ar: 'نعم، يقدم Intlayer محررًا مرئيًا اختياريًا لإدارة المحتوى بسهولة دون الحاجة إلى التعمق في الكود.',
          ru: 'Да, Intlayer предоставляет необязательный визуальный редактор для легкого управления содержимым, не углубляясь в код.',
          tr: 'Evet, Intlayer, koda dalmadan içeriği kolayca yönetmek için isteğe bağlı bir görsel editör sağlar.',
        }),
        callToAction: {
          label: t({
            en: 'Read more about the visual editor',
            fr: 'En savoir plus sur l’éditeur visuel',
            es: 'Leer más sobre el editor visual',
            'en-GB': 'Read more about the visual editor',
            de: 'Erfahren Sie mehr über den visuellen Editor',
            ja: 'ビジュアルエディターについてもっと読む',
            ko: '비주얼 편집기에 대해 더 읽어보세요',
            zh: '了解更多关于可视化编辑器的信息',
            it: 'Scopri di più sull’editor visivo',
            pt: 'Saiba mais sobre o editor visual',
            hi: 'दृश्य संपादक के बारे में अधिक पढ़ें',
            ar: 'اقرأ المزيد عن المحرر المرئي',
            ru: 'Узнайте больше о визуальном редакторе',
            tr: 'Görsel editör hakkında daha fazla bilgi edinin',
          }),
          alt: t({
            fr: "Cliquez ici pour en savoir plus sur l'éditeur visuel d'Intlayer",
            en: 'Click here to read more about Intlayer visual editor',
            es: 'Haga clic aquí para leer más sobre el editor visual de Intlayer',
            'en-GB': 'Click here to read more about Intlayer visual editor',
            de: 'Klicken Sie hier, um mehr über den visuellen Editor von Intlayer zu erfahren',
            ja: 'Intlayerのビジュアルエディターについての詳細を読むにはここをクリックしてください',
            ko: 'Intlayer 비주얼 편집기에 대한 자세한 내용을 보려면 여기를 클릭하세요',
            zh: '点击这里了解有关Intlayer可视化编辑器的更多信息',
            it: 'Clicca qui per leggere di più sull’editor visivo di Intlayer',
            pt: 'Clique aqui para saber mais sobre o editor visual do Intlayer',
            hi: 'Intlayer दृश्य संपादक के बारे में अधिक जानकारी के लिए यहां क्लिक करें',
            ar: 'انقر هنا لقراءة المزيد عن محرر Intlayer المرئي',
            ru: 'Нажмите здесь, чтобы узнать больше о визуальном редакторе Intlayer',
            tr: 'Intlayer görsel editör hakkında daha fazla bilgi edinmek için tıklayın',
          }),
          url: PagesRoutes.Doc_IntlayerVisualEditor,
        },
      },
      {
        question: t({
          en: 'How can I contribute to Intlayer?',
          fr: 'Comment puis-je contribuer à Intlayer ?',
          es: '¿Cómo puedo contribuir a Intlayer?',
          'en-GB': 'How can I contribute to Intlayer?',
          de: 'Wie kann ich zu Intlayer beitragen?',
          ja: 'Intlayerにどう貢献できますか？',
          ko: 'Intlayer에 어떻게 기여할 수 있습니까?',
          zh: '我如何为Intlayer做出贡献？',
          it: 'Come posso contribuire a Intlayer?',
          pt: 'Como posso contribuir para o Intlayer?',
          hi: 'मैं Intlayer में कैसे योगदान कर सकता हूँ?',
          ar: 'كيف يمكنني المساهمة في Intlayer؟',
          ru: 'Как я могу сделать вклад в Intlayer?',
          tr: "Intlayer'a nasıl katkıda bulunabilirim?",
        }),
        answer: t({
          en: 'You can contribute by submitting pull requests or reporting issues on the GitHub repository.',
          fr: 'Vous pouvez contribuer en soumettant des pull requests ou en signalant des problèmes sur le dépôt GitHub.',
          es: 'Puedes contribuir enviando pull requests o reportando problemas en el repositorio de GitHub.',
          'en-GB':
            'You can contribute by submitting pull requests or reporting issues on the GitHub repository.',
          de: 'Sie können beitragen, indem Sie Pull-Requests einreichen oder Probleme im GitHub-Repository melden.',
          ja: 'プルリクエストを送信するか、GitHubリポジトリで問題を報告することで貢献できます。',
          ko: 'Pull requests를 제출하거나 GitHub 리포지토리에서 문제를 보고함으로써 기여할 수 있습니다.',
          zh: '您可以通过提交拉取请求或在GitHub存储库中报告问题来贡献。',
          it: 'Puoi contribuire inviando pull request o segnalando problemi nel repository di GitHub.',
          pt: 'Você pode contribuir enviando pull requests ou relatando problemas no repositório do GitHub.',
          hi: 'आप पुल अनुरोध सबमिट करके या GitHub भंडार पर मुद्दों की रिपोर्ट करके योगदान कर सकते हैं।',
          ar: 'يمكنك المساهمة من خلال تقديم طلبات سحب أو الإبلاغ عن مشكلات على مستودع GitHub.',
          ru: 'Вы можете внести свой вклад, отправив запросы на извлечение или сообщив об ошибках в репозитории GitHub.',
          tr: 'GitHub deposunda çekme istekleri göndererek veya sorunları bildirerek katkıda bulunabilirsiniz.',
        }),
        callToAction: {
          label: t({
            en: 'Read more about how to contribute',
            fr: 'En savoir plus sur la façon de contribuer',
            es: 'Leer más sobre cómo contribuir',
            'en-GB': 'Read more about how to contribute',
            de: 'Erfahren Sie mehr darüber, wie Sie beitragen können',
            ja: '貢献する方法についてもっと読む',
            ko: '기여하는 방법에 대해 더 읽어보세요',
            zh: '了解更多关于如何贡献的信息',
            it: 'Scopri di più su come contribuire',
            pt: 'Saiba mais sobre como contribuir',
            hi: 'योगदान करने के तरीके के बारे में अधिक पढ़ें',
            ar: 'اقرأ المزيد عن كيفية المساهمة',
            ru: 'Узнайте больше о том, как внести свой вклад',
            tr: 'Katkıda bulunma hakkında daha fazla bilgi edinin',
          }),
          alt: t({
            fr: 'Cliquez ici pour en savoir plus sur la façon de contribuer à Intlayer',
            en: 'Click here to read more about how to contribute to Intlayer',
            es: 'Haga clic aquí para leer más sobre cómo contribuir a Intlayer',
            'en-GB':
              'Click here to read more about how to contribute to Intlayer',
            de: 'Klicken Sie hier, um mehr darüber zu erfahren, wie Sie zu Intlayer beitragen können',
            ja: 'Intlayerに貢献する方法についての詳細を読むにはここをクリックしてください',
            ko: 'Intlayer에 기여하는 방법에 대한 자세한 내용을 보려면 여기를 클릭하세요',
            zh: '点击这里了解有关如何为Intlayer做贡献的更多信息',
            it: 'Clicca qui per leggere di più su come contribuire a Intlayer',
            pt: 'Clique aqui para saber mais sobre como contribuir para o Intlayer',
            hi: 'Intlayer में योगदान करने के तरीके के बारे में अधिक जानकारी के लिए यहां क्लिक करें',
            ar: 'انقر هنا لقراءة المزيد عن كيفية المساهمة في Intlayer',
            ru: 'Нажмите здесь, чтобы узнать больше о том, как внести свой вклад в Intlayer',
            tr: "Intlayer'a nasıl katkıda bulunulacağı hakkında daha fazla bilgi edinmek için tıklayın",
          }),
          url: 'https://github.com/aymericzip/intlayer/blob/main/CONTRIBUTING.md',
        },
      },
      {
        question: t({
          en: 'What is the cost of using Intlayer?',
          fr: 'Quel est le coût de l’utilisation d’Intlayer ?',
          es: '¿Cuál es el costo de usar Intlayer?',
          'en-GB': 'What is the cost of using Intlayer?',
          de: 'Was kostet die Nutzung von Intlayer?',
          ja: 'Intlayerを使用するのにかかる費用はいくらですか？',
          ko: 'Intlayer를 사용하는 비용은 얼마입니까?',
          zh: '使用Intlayer的费用是多少？',
          it: 'Qual è il costo di utilizzo di Intlayer?',
          pt: 'Qual é o custo de usar o Intlayer?',
          hi: 'Intlayer का उपयोग करने की लागत क्या है?',
          ar: 'ما هي تكلفة استخدام Intlayer؟',
          ru: 'Какова стоимость использования Intlayer?',
          tr: "Intlayer'ı kullanmanın maliyeti nedir?",
        }),
        answer: t({
          en: 'Intlayer integrates a selection of free NPM packages along with a visual editor. Additionally, it offers a CMS for externalizing content. This CMS is free to use but includes additional features for Premium and Enterprise plan members.',
          fr: 'Intlayer intègre une sélection de packages NPM gratuits ainsi qu’un éditeur visuel. De plus, il propose un CMS pour externaliser le contenu. Ce CMS est gratuit, mais inclut des fonctionnalités supplémentaires pour les membres des plans Premium et Enterprise.',
          es: 'Intlayer integra una selección de paquetes NPM gratuitos junto con un editor visual. Además, ofrece un CMS para externalizar contenido. Este CMS es gratuito, pero incluye características adicionales para los miembros de los planes Premium y Enterprise.',
          'en-GB':
            'Intlayer integrates a selection of free NPM packages along with a visual editor. Additionally, it offers a CMS for externalizing content. This CMS is free to use but includes additional features for Premium and Enterprise plan members.',
          de: 'Intlayer integriert eine Auswahl kostenloser NPM-Pakete sowie einen visuellen Editor. Zusätzlich bietet es ein CMS zur Externalisierung von Inhalten. Dieses CMS ist kostenlos, enthält jedoch zusätzliche Funktionen für Mitglieder der Premium- und Enterprise-Pläne.',
          ja: 'Intlayerは、無料のNPMパッケージのセレクションとビジュアルエディタを統合しています。さらに、コンテンツを外部化するためのCMSを提供します。このCMSは無料で使用できますが、PremiumおよびEnterpriseプランのメンバーには追加機能が含まれています。',
          ko: 'Intlayer는 무료 NPM 패키지와 시각적 편집기를 통합합니다. 또한, 콘텐츠 외부화를 위한 CMS를 제공합니다. 이 CMS는 무료로 사용할 수 있지만, 프리미엄 및 엔터프라이즈 플랜 멤버를 위한 추가 기능이 포함되어 있습니다.',
          zh: 'Intlayer集成了一系列免费的NPM软件包以及一个可视化编辑器。此外，它还提供了一个CMS来外部化内容。此CMS可免费使用，但对于Premium和Enterprise计划的用户，包含额外功能。',
          it: 'Intlayer integra una selezione di pacchetti NPM gratuiti insieme a un editor visivo. Inoltre, offre un CMS per l’esternalizzazione dei contenuti. Questo CMS è gratuito, ma include funzionalità aggiuntive per i membri dei piani Premium ed Enterprise.',
          pt: 'O Intlayer integra uma seleção de pacotes NPM gratuitos juntamente com um editor visual. Além disso, oferece um CMS para externalizar conteúdo. Este CMS é gratuito, mas inclui recursos adicionais para membros dos planos Premium e Enterprise.',
          hi: 'Intlayer एक चयनित नि:शुल्क NPM पैकेज और एक विज़ुअल एडिटर को एकीकृत करता है। इसके अलावा, यह सामग्री को बाहरीकरण करने के लिए एक CMS प्रदान करता है। यह CMS निःशुल्क उपयोग के लिए उपलब्ध है, लेकिन Premium और Enterprise योजना के सदस्यों के लिए अतिरिक्त सुविधाएँ शामिल हैं।',
          ar: 'يُدمج Intlayer مجموعة مختارة من حزم NPM المجانية جنبًا إلى جنب مع محرر مرئي. بالإضافة إلى ذلك، يقدم نظام CMS لخارجية المحتوى. هذا النظام مجاني للاستخدام ولكنه يتضمن ميزات إضافية لأعضاء خطط Premium و Enterprise.',
          ru: 'Intlayer интегрирует подборку бесплатных пакетов NPM вместе с визуальным редактором. Кроме того, он предлагает CMS для внешнего управления контентом. Этот CMS бесплатен в использовании, но включает дополнительные функции для участников планов Premium и Enterprise.',
          tr: 'Intlayer, görsel bir editörle birlikte ücretsiz NPM paketlerinden oluşan bir seçkiyi entegre eder. Ayrıca, içeriği dışa aktarmak için bir CMS sunar. Bu CMS ücretsizdir, ancak Premium ve Enterprise plan üyeleri için ek özellikler içerir.',
        }),
        callToAction: {
          label: t({
            en: 'Read more about Intlayer plans',
            fr: 'En savoir plus sur les plans d’Intlayer',
            es: 'Leer más sobre los planes de Intlayer',
            'en-GB': 'Read more about Intlayer plans',
            de: 'Erfahren Sie mehr über die Pläne von Intlayer',
            ja: 'Intlayerのプランについてもっと読む',
            ko: 'Intlayer 계획에 대해 더 읽어보세요',
            zh: '了解更多有关Intlayer计划的信息',
            it: 'Scopri di più sui piani di Intlayer',
            pt: 'Saiba mais sobre os planos do Intlayer',
            hi: 'Intlayer की योजनाओं के बारे में अधिक पढ़ें',
            ar: 'اقرأ المزيد عن خطط Intlayer',
            ru: 'Узнайте больше о планах Intlayer',
            tr: 'Intlayer planları hakkında daha fazla bilgi edinin',
          }),
          alt: t({
            fr: "Cliquez ici pour en savoir plus sur les plans d'Intlayer",
            en: 'Click here to read more about Intlayer plans',
            es: 'Haga clic aquí para leer más sobre los planes de Intlayer',
            'en-GB': 'Click here to read more about Intlayer plans',
            de: 'Klicken Sie hier, um mehr über die Pläne von Intlayer zu erfahren',
            ja: 'Intlayerのプランについてもっと読むにはここをクリックしてください',
            ko: 'Intlayer 계획에 대한 더 많은 정보를 보려면 여기를 클릭하세요',
            zh: '点击这里了解有关Intlayer计划的更多信息',
            it: 'Clicca qui per leggere di più sui piani di Intlayer',
            pt: 'Clique aqui para saber mais sobre os planos do Intlayer',
            hi: 'Intlayer की योजनाओं के बारे में अधिक पढ़ने के लिए यहां क्लिक करें',
            ar: 'انقر هنا لقراءة المزيد عن خطط Intlayer',
            ru: 'Нажмите здесь, чтобы узнать больше о планах Intlayer',
            tr: 'Intlayer planları hakkında daha fazla bilgi edinmek için tıklayın',
          }),
          url: PagesRoutes.Pricing,
        },
      },
      {
        question: t({
          en: 'Which platforms does Intlayer support?',
          fr: 'Quelles plateformes sont prises en charge par Intlayer ?',
          es: '¿Qué plataformas son compatibles con Intlayer?',
          'en-GB': 'Which platforms does Intlayer support?',
          de: 'Welche Plattformen werden von Intlayer unterstützt?',
          ja: 'Intlayerはどのプラットフォームをサポートしていますか？',
          ko: 'Intlayer는 어떤 플랫폼을 지원합니까?',
          zh: 'Intlayer支持哪些平台？',
          it: 'Quali piattaforme supporta Intlayer?',
          pt: 'Quais plataformas o Intlayer suporta?',
          hi: 'Intlayer किन प्लेटफार्मों का समर्थन करता है?',
          ar: 'ما هي المنصات التي يدعمها Intlayer؟',
          ru: 'Какие платформы поддерживает Intlayer?',
          tr: 'Intlayer hangi platformları destekliyor?',
        }),
        answer: t({
          en: 'Intlayer is available for React (including Create React App), Vite with React, Next.js, and Express. This ensures a seamless integration with modern JavaScript frameworks and server-side environments.',
          fr: 'Intlayer est disponible pour React (y compris Create React App), Vite avec React, Next.js et Express. Cela garantit une intégration fluide avec les frameworks JavaScript modernes et les environnements côté serveur.',
          es: 'Intlayer está disponible para React (incluido Create React App), Vite con React, Next.js y Express. Esto garantiza una integración fluida con marcos de JavaScript modernos y entornos del lado del servidor.',
          'en-GB':
            'Intlayer is available for React (including Create React App), Vite with React, Next.js, and Express. This ensures a seamless integration with modern JavaScript frameworks and server-side environments.',
          de: 'Intlayer ist verfügbar für React (einschließlich Create React App), Vite mit React, Next.js und Express. Dies gewährleistet eine nahtlose Integration mit modernen JavaScript-Frameworks und serverseitigen Umgebungen.',
          ja: 'Intlayerは、React（Create React Appを含む）、Reactを使用したVite、Next.js、およびExpressで利用できます。これにより、最新のJavaScriptフレームワークやサーバーサイド環境とのシームレスな統合が保証されます。',
          ko: 'Intlayer는 React(React 앱 생성 포함), Vite를 사용하는 React, Next.js 및 Express에서 사용할 수 있습니다. 이를 통해 최신 JavaScript 프레임워크 및 서버 측 환경과의 원활한 통합을 보장합니다.',
          zh: 'Intlayer适用于React（包括Create React App）、Vite与React、Next.js和Express。这确保了与现代JavaScript框架和服务器端环境的无缝集成。',
          it: 'Intlayer è disponibile per React (compreso Create React App), Vite con React, Next.js e Express. Questo garantisce un’integrazione fluida con i moderni framework JavaScript e gli ambienti server-side.',
          pt: 'O Intlayer está disponível para React (incluindo Create React App), Vite com React, Next.js e Express. Isso garante uma integração perfeita com os modernos frameworks JavaScript e ambientes do lado do servidor.',
          hi: 'Intlayer React (Create React App सहित), Vite के साथ React, Next.js, और Express के लिए उपलब्ध है। यह आधुनिक JavaScript ढांचे और सर्वर-साइड वातावरण के साथ एक सहज एकीकरण सुनिश्चित करता है।',
          ar: 'يتوفر Intlayer لـ React (بما في ذلك Create React App) و Vite مع React و Next.js و Express. يضمن ذلك تكاملاً سلساً مع إطار العمل الحديث JavaScript والبيئات من جانب الخادم.',
          ru: 'Intlayer доступен для React (включая Create React App), Vite с React, Next.js и Express. Это обеспечивает бесшовную интеграцию с современными JavaScript-фреймворками и серверными средами.',
          tr: 'Intlayer, React (Create React App dahil), Vite with React, Next.js ve Express için kullanılabilir. Bu, modern JavaScript çerçeveleri ve sunucu tarafı ortamlarla sorunsuz entegrasyon sağlar.',
        }),
        callToAction: {
          label: t({
            en: 'Read more about the platforms supported',
            fr: 'En savoir plus sur les plateformes prises en charge',
            es: 'Leer más sobre las plataformas compatibles',
            'en-GB': 'Read more about the platforms supported',
            de: 'Erfahren Sie mehr über die unterstützten Plattformen',
            ja: 'サポートされているプラットフォームについてもっと読む',
            ko: '지원되는 플랫폼에 대해 더 읽어보세요',
            zh: '了解更多关于所支持的平台的信息',
            it: 'Scopri di più sulle piattaforme supportate',
            pt: 'Saiba mais sobre as plataformas suportadas',
            hi: 'समर्थित प्लेटफार्मों के बारे में अधिक पढ़ें',
            ar: 'اقرأ المزيد عن المنصات المدعومة',
            ru: 'Узнайте больше о поддерживаемых платформах',
            tr: 'Desteklenen platformlar hakkında daha fazla bilgi edinin',
          }),
          alt: t({
            fr: 'Cliquez ici pour en savoir plus sur les plateformes prises en charge par Intlayer',
            en: 'Click here to read more about the platforms supported by Intlayer',
            es: 'Haga clic aquí para leer más sobre las plataformas compatibles con Intlayer',
            'en-GB':
              'Click here to read more about the platforms supported by Intlayer',
            de: 'Klicken Sie hier, um mehr über die unterstützten Plattformen von Intlayer zu erfahren',
            ja: 'Intlayerがサポートするプラットフォームについて詳しく知るには、ここをクリックしてください',
            ko: 'Intlayer에서 지원하는 플랫폼에 대한 자세한 내용을 보려면 여기를 클릭하세요',
            zh: '点击这里了解有关Intlayer支持的平台的更多信息',
            it: 'Clicca qui per leggere di più sulle piattaforme supportate da Intlayer',
            pt: 'Clique aqui para saber mais sobre as plataformas suportadas pelo Intlayer',
            hi: 'Intlayer द्वारा समर्थित प्लेटफार्मों के बारे में अधिक जानने के लिए यहां क्लिक करें',
            ar: 'انقر هنا لقراءة المزيد عن المنصات المدعومة من Intlayer',
            ru: 'Нажмите здесь, чтобы узнать больше о поддерживаемых платформах Intlayer',
            tr: 'Intlayer tarafından desteklenen platformlar hakkında daha fazla bilgi edinmek için tıklayın',
          }),
          url: `${PagesRoutes.Doc}#platforms-supported`,
        },
      },
    ],
  },
} satisfies Dictionary;

export default docNavTitlesContent;
