import { type Dictionary, t } from 'intlayer';

const docPageLayoutContent = {
  key: 'doc-page-layout',
  content: {
    documentationNavigation: t({
      en: 'Documentation navigation',
      fr: 'Navigation de la documentation',
      es: 'Navegación de la documentación',
      ru: 'Навигация по документации',
      ja: 'ドキュメントのナビゲーション',
      ko: '문서 탐색',
      zh: '文档导航',
      de: 'Dokumentationsnavigation',
      ar: 'التنقل في المستندات',
      it: 'Navigazione della documentazione',
      'en-GB': 'Documentation navigation',
      pt: 'Navegação da documentação',
      hi: 'दस्तावेज़ीकरण नेвиगेशन',
      tr: 'Dokümantasyon navigasyonu',
      pl: 'Nawigacja po dokumentacji',
      id: 'Navigasi dokumentasi',
      vi: 'Điều hướng tài liệu',
      uk: 'Навігація по документації',
    }),
    documentationContent: t({
      en: 'Documentation content',
      fr: 'Contenu de la documentation',
      es: 'Contenido de la documentación',
      ru: 'Содержимое документации',
      ja: 'ドキュメントのコンテンツ',
      ko: '문서 내용',
      zh: '文档内容',
      de: 'Dokumentationsinhalt',
      ar: 'محتوى المستندات',
      it: 'Contenuto della documentazione',
      'en-GB': 'Documentation content',
      pt: 'Conteúdo da documentação',
      hi: 'दस्ताвеज़ीकरण सामग्री',
      tr: 'Dokümantasyon içeriği',
      pl: 'Treść dokumentacji',
      id: 'Konten dokumentasi',
      vi: 'Nội dung tài liệu',
      uk: 'Вміст документації',
    }),
    onThisPage: t({
      en: 'On this page',
      fr: 'Sur cette page',
      es: 'En esta página',
      ru: 'На этой странице',
      ja: 'このページ内',
      ko: '이 페이지에서',
      zh: '在此页面上',
      de: 'Auf dieser Seite',
      ar: 'في هذه الصفحة',
      it: 'Su questa pagina',
      'en-GB': 'On this page',
      pt: 'Nesta página',
      hi: 'इस पृष्ठ पर',
      tr: 'Bu sayfada',
      pl: 'Na tej stronie',
      id: 'Di halaman ini',
      vi: 'Trên trang này',
      uk: 'На цій сторінці',
    }),
  },
} satisfies Dictionary;

export default docPageLayoutContent;
