import { type Dictionary, t } from 'intlayer';

const ssoButtonContent = {
  key: 'sso-button',
  content: {
    text: 'SSO',
    ariaLabel: t({
      en: 'Sign in with Single Sign-On',
      'en-GB': 'Sign in with Single Sign-On',
      fr: "Se connecter avec l'authentification unique",
      es: 'Iniciar sesión con inicio de sesión único',
      de: 'Mit Single Sign-On anmelden',
      ja: 'シングルサインオンでログイン',
      ko: 'Single Sign-On으로 로그인',
      zh: '使用单点登录登录',
      it: 'Accedi con Single Sign-On',
      pt: 'Entrar com Single Sign-On',
      hi: 'सिंगल साइन-ऑन के साथ साइन इन करें',
      ar: 'تسجيل الدخول باستخدام تسجيل الدخول الموحد',
      ru: 'Войти через единый вход',
      tr: 'Tek Oturum Açma ile giriş yap',
      pl: 'Zaloguj się przy użyciu Single Sign-On',
      nl: 'Inloggen met Single Sign-On',
      id: 'Masuk dengan Single Sign-On',
      vi: 'Đăng nhập bằng Single Sign-On',
      uk: 'Увійти через єдиний вхід (SSO)',
    }),
    modalTitle: t({
      en: 'Sign in with SSO',
      'en-GB': 'Sign in with SSO',
      fr: 'Se connecter avec SSO',
      es: 'Iniciar sesión con SSO',
      de: 'Mit SSO anmelden',
      ja: 'SSOでログイン',
      ko: 'SSO로 로그인',
      zh: '使用 SSO 登录',
      it: 'Accedi con SSO',
      pt: 'Entrar com SSO',
      hi: 'SSO के साथ साइन इन करें',
      ar: 'تسجيل الدخول باستخدام SSO',
      ru: 'Войти через SSO',
      tr: 'SSO ile giriş yap',
      pl: 'Zaloguj się przez SSO',
      nl: 'Inloggen met SSO',
      id: 'Masuk dengan SSO',
      vi: 'Đăng nhập bằng SSO',
      uk: 'Увійти через SSO',
    }),
    domainInputLabel: t({
      en: 'Enter your organization domain',
      'en-GB': 'Enter your organisation domain',
      fr: 'Entrez le domaine de votre organisation',
      es: 'Ingrese el dominio de su organización',
      de: 'Geben Sie Ihre Organisationsdomäne ein',
      ja: '組織ドメインを入力してください',
      ko: '조직 도메인을 입력하세요',
      zh: '输入您的组织域名',
      it: 'Inserisci il dominio della tua organizzazione',
      pt: 'Digite o domínio da sua organização',
      hi: 'अपना संगठन डोमेन दर्ज करें',
      ar: 'أدخل نطاق مؤسستك',
      ru: 'Введите домен вашей организации',
      tr: 'Kuruluş alan adınızı girin',
      pl: 'Wprowadź domenę swojej organizacji',
      nl: 'Voer uw organisatiedomein in',
      id: 'Masukkan domain organisasi Anda',
      vi: 'Nhập tên miền tổ chức của bạn',
      uk: 'Введіть домен вашої організації',
    }),
    domainInputPlaceholder: 'example.com',
    cancelButton: t({
      en: 'Cancel',
      'en-GB': 'Cancel',
      fr: 'Annuler',
      es: 'Cancelar',
      de: 'Abbrechen',
      ja: 'キャンセル',
      ko: '취소',
      zh: '取消',
      it: 'Annulla',
      pt: 'Cancelar',
      hi: 'रद्द करें',
      ar: 'إلغاء',
      ru: 'Отмена',
      tr: 'İptal',
      pl: 'Anuluj',
      nl: 'Annuleren',
      id: 'Batal',
      vi: 'Hủy',
      uk: 'Скасувати',
    }),
    submitButton: t({
      en: 'Continue',
      'en-GB': 'Continue',
      fr: 'Continuer',
      es: 'Continuar',
      de: 'Weiter',
      ja: '続ける',
      ko: '계속',
      zh: '继续',
      it: 'Continua',
      pt: 'Continuar',
      hi: 'जारी रखें',
      ar: 'متابعة',
      ru: 'Продолжить',
      tr: 'Devam et',
      pl: 'Kontynuuj',
      nl: 'Doorgaan',
      id: 'Lanjutkan',
      vi: 'Tiếp tục',
      uk: 'Продовжити',
    }),
    fetchingConfig: t({
      en: 'Looking up SSO configuration...',
      'en-GB': 'Looking up SSO configuration...',
      fr: 'Recherche de la configuration SSO...',
      es: 'Buscando configuración SSO...',
      de: 'SSO-Konfiguration wird gesucht...',
      ja: 'SSO設定を検索中...',
      ko: 'SSO 구성 조회 중...',
      zh: '正在查找 SSO 配置...',
      it: 'Ricerca configurazione SSO...',
      pt: 'Procurando configuração SSO...',
      hi: 'SSO कॉन्फ़िगरेशन खोज रहा है...',
      ar: 'جارٍ البحث عن تكوين SSO...',
      ru: 'Поиск конфигурации SSO...',
      tr: 'SSO yapılandırması aranıyor...',
      pl: 'Wyszukiwanie konfiguracji SSO...',
      nl: 'SSO-configuratie opzoeken...',
      id: 'Mencari konfigurasi SSO...',
      vi: 'Đang tìm kiếm cấu hình SSO...',
      uk: 'Перевіряється конфігурація SSO...',
    }),
    noSSOConfigured: t({
      en: 'No SSO configured for this domain',
      'en-GB': 'No SSO configured for this domain',
      fr: 'Aucun SSO configuré pour ce domaine',
      es: 'No hay SSO configurado para este dominio',
      de: 'Für diese Domain ist kein SSO konfiguriert',
      ja: 'このドメインにはSSOが設定されていません',
      ko: '이 도메인에 대해 구성된 SSO가 없습니다',
      zh: '此域未配置 SSO',
      it: 'Nessun SSO configurato per questo dominio',
      pt: 'Nenhum SSO configurado para este domínio',
      hi: 'इस डोमेन के लिए कोई SSO कॉन्फ़िगर नहीं है',
      ar: 'لم يتم تكوين SSO لهذا النطاق',
      ru: 'SSO не настроен для этого домена',
      tr: 'Bu alan adı için SSO yapılandırılmamış',
      pl: 'Brak skonfigurowanego SSO dla tej domeny',
      nl: 'Geen SSO geconfigureerd voor dit domein',
      id: 'Tidak ada SSO yang dikonfigurasi untuk domain ini',
      vi: 'Chưa cấu hình SSO cho tên miền này',
      uk: 'SSO не налаштовано для цього домену',
    }),
  },
  title: 'SSO Button',
  description:
    'Text content for the SSO (Single Sign-On) button used for organization-based authentication.',
  tags: ['auth', 'sso', 'login'],
} satisfies Dictionary;

export default ssoButtonContent;
