import {
  AffiliateActivatedEmailAR,
  AffiliateActivatedEmailDE,
  AffiliateActivatedEmailEN,
  AffiliateActivatedEmailEN_GB,
  AffiliateActivatedEmailES,
  AffiliateActivatedEmailFR,
  AffiliateActivatedEmailHI,
  AffiliateActivatedEmailID,
  AffiliateActivatedEmailIT,
  AffiliateActivatedEmailJA,
  AffiliateActivatedEmailKO,
  AffiliateActivatedEmailPL,
  AffiliateActivatedEmailPT,
  AffiliateActivatedEmailRU,
  AffiliateActivatedEmailTR,
  AffiliateActivatedEmailUK,
  AffiliateActivatedEmailVI,
  AffiliateActivatedEmailZH,
} from '@emails/AffiliateActivatedEmail';
import {
  AffiliateConversionEmailAR,
  AffiliateConversionEmailDE,
  AffiliateConversionEmailEN,
  AffiliateConversionEmailEN_GB,
  AffiliateConversionEmailES,
  AffiliateConversionEmailFR,
  AffiliateConversionEmailHI,
  AffiliateConversionEmailID,
  AffiliateConversionEmailIT,
  AffiliateConversionEmailJA,
  AffiliateConversionEmailKO,
  AffiliateConversionEmailPL,
  AffiliateConversionEmailPT,
  AffiliateConversionEmailRU,
  AffiliateConversionEmailTR,
  AffiliateConversionEmailUK,
  AffiliateConversionEmailVI,
  AffiliateConversionEmailZH,
} from '@emails/AffiliateConversionEmail';
import {
  AffiliateInvitationEmailAR,
  AffiliateInvitationEmailDE,
  AffiliateInvitationEmailEN,
  AffiliateInvitationEmailEN_GB,
  AffiliateInvitationEmailES,
  AffiliateInvitationEmailFR,
  AffiliateInvitationEmailHI,
  AffiliateInvitationEmailID,
  AffiliateInvitationEmailIT,
  AffiliateInvitationEmailJA,
  AffiliateInvitationEmailKO,
  AffiliateInvitationEmailPL,
  AffiliateInvitationEmailPT,
  AffiliateInvitationEmailRU,
  AffiliateInvitationEmailTR,
  AffiliateInvitationEmailUK,
  AffiliateInvitationEmailVI,
  AffiliateInvitationEmailZH,
} from '@emails/AffiliateInvitationEmail';
import {
  AffiliateWelcomeEmailAR,
  AffiliateWelcomeEmailDE,
  AffiliateWelcomeEmailEN,
  AffiliateWelcomeEmailEN_GB,
  AffiliateWelcomeEmailES,
  AffiliateWelcomeEmailFR,
  AffiliateWelcomeEmailHI,
  AffiliateWelcomeEmailID,
  AffiliateWelcomeEmailIT,
  AffiliateWelcomeEmailJA,
  AffiliateWelcomeEmailKO,
  AffiliateWelcomeEmailPL,
  AffiliateWelcomeEmailPT,
  AffiliateWelcomeEmailRU,
  AffiliateWelcomeEmailTR,
  AffiliateWelcomeEmailUK,
  AffiliateWelcomeEmailVI,
  AffiliateWelcomeEmailZH,
} from '@emails/AffiliateWelcomeEmail';
import {
  InviteUserEmailAR,
  InviteUserEmailDE,
  InviteUserEmailEN,
  InviteUserEmailEN_GB,
  InviteUserEmailES,
  InviteUserEmailFR,
  InviteUserEmailHI,
  InviteUserEmailID,
  InviteUserEmailIT,
  InviteUserEmailJA,
  InviteUserEmailKO,
  InviteUserEmailPL,
  InviteUserEmailPT,
  InviteUserEmailRU,
  InviteUserEmailTR,
  InviteUserEmailUK,
  InviteUserEmailVI,
  InviteUserEmailZH,
} from '@emails/InviteUserEmail';
import {
  MagicLinkEmailAR,
  MagicLinkEmailDE,
  MagicLinkEmailEN,
  MagicLinkEmailEN_GB,
  MagicLinkEmailES,
  MagicLinkEmailFR,
  MagicLinkEmailHI,
  MagicLinkEmailID,
  MagicLinkEmailIT,
  MagicLinkEmailJA,
  MagicLinkEmailKO,
  MagicLinkEmailPL,
  MagicLinkEmailPT,
  MagicLinkEmailRU,
  MagicLinkEmailTR,
  MagicLinkEmailUK,
  MagicLinkEmailVI,
  MagicLinkEmailZH,
} from '@emails/MagicLinkEmail';
import {
  MissionRequestedClientEmailAR,
  MissionRequestedClientEmailDE,
  MissionRequestedClientEmailEN,
  MissionRequestedClientEmailEN_GB,
  MissionRequestedClientEmailES,
  MissionRequestedClientEmailFR,
  MissionRequestedClientEmailHI,
  MissionRequestedClientEmailID,
  MissionRequestedClientEmailIT,
  MissionRequestedClientEmailJA,
  MissionRequestedClientEmailKO,
  MissionRequestedClientEmailPL,
  MissionRequestedClientEmailPT,
  MissionRequestedClientEmailRU,
  MissionRequestedClientEmailTR,
  MissionRequestedClientEmailUK,
  MissionRequestedClientEmailVI,
  MissionRequestedClientEmailZH,
} from '@emails/MissionRequestedClientEmail';
import {
  MissionRequestedReviewerEmailAR,
  MissionRequestedReviewerEmailDE,
  MissionRequestedReviewerEmailEN,
  MissionRequestedReviewerEmailEN_GB,
  MissionRequestedReviewerEmailES,
  MissionRequestedReviewerEmailFR,
  MissionRequestedReviewerEmailHI,
  MissionRequestedReviewerEmailID,
  MissionRequestedReviewerEmailIT,
  MissionRequestedReviewerEmailJA,
  MissionRequestedReviewerEmailKO,
  MissionRequestedReviewerEmailPL,
  MissionRequestedReviewerEmailPT,
  MissionRequestedReviewerEmailRU,
  MissionRequestedReviewerEmailTR,
  MissionRequestedReviewerEmailUK,
  MissionRequestedReviewerEmailVI,
  MissionRequestedReviewerEmailZH,
} from '@emails/MissionRequestedReviewerEmail';
import {
  OAuthTokenCreatedEmailAR,
  OAuthTokenCreatedEmailDE,
  OAuthTokenCreatedEmailEN,
  OAuthTokenCreatedEmailEN_GB,
  OAuthTokenCreatedEmailES,
  OAuthTokenCreatedEmailFR,
  OAuthTokenCreatedEmailHI,
  OAuthTokenCreatedEmailID,
  OAuthTokenCreatedEmailIT,
  OAuthTokenCreatedEmailJA,
  OAuthTokenCreatedEmailKO,
  OAuthTokenCreatedEmailPL,
  OAuthTokenCreatedEmailPT,
  OAuthTokenCreatedEmailRU,
  OAuthTokenCreatedEmailTR,
  OAuthTokenCreatedEmailUK,
  OAuthTokenCreatedEmailVI,
  OAuthTokenCreatedEmailZH,
} from '@emails/OAuthTokenCreatedEmail';
import {
  PasswordChangeConfirmationEmailAR,
  PasswordChangeConfirmationEmailDE,
  PasswordChangeConfirmationEmailEN,
  PasswordChangeConfirmationEmailEN_GB,
  PasswordChangeConfirmationEmailES,
  PasswordChangeConfirmationEmailFR,
  PasswordChangeConfirmationEmailHI,
  PasswordChangeConfirmationEmailID,
  PasswordChangeConfirmationEmailIT,
  PasswordChangeConfirmationEmailJA,
  PasswordChangeConfirmationEmailKO,
  PasswordChangeConfirmationEmailPL,
  PasswordChangeConfirmationEmailPT,
  PasswordChangeConfirmationEmailRU,
  PasswordChangeConfirmationEmailTR,
  PasswordChangeConfirmationEmailUK,
  PasswordChangeConfirmationEmailVI,
  PasswordChangeConfirmationEmailZH,
} from '@emails/PasswordChangeConfirmation';
import {
  ResetPasswordEmailAR,
  ResetPasswordEmailDE,
  ResetPasswordEmailEN,
  ResetPasswordEmailEN_GB,
  ResetPasswordEmailES,
  ResetPasswordEmailFR,
  ResetPasswordEmailHI,
  ResetPasswordEmailID,
  ResetPasswordEmailIT,
  ResetPasswordEmailJA,
  ResetPasswordEmailKO,
  ResetPasswordEmailPL,
  ResetPasswordEmailPT,
  ResetPasswordEmailRU,
  ResetPasswordEmailTR,
  ResetPasswordEmailUK,
  ResetPasswordEmailVI,
  ResetPasswordEmailZH,
} from '@emails/ResetUserPassword';
import {
  ReviewerApplicationEmailAR,
  ReviewerApplicationEmailDE,
  ReviewerApplicationEmailEN,
  ReviewerApplicationEmailEN_GB,
  ReviewerApplicationEmailES,
  ReviewerApplicationEmailFR,
  ReviewerApplicationEmailHI,
  ReviewerApplicationEmailID,
  ReviewerApplicationEmailIT,
  ReviewerApplicationEmailJA,
  ReviewerApplicationEmailKO,
  ReviewerApplicationEmailPL,
  ReviewerApplicationEmailPT,
  ReviewerApplicationEmailRU,
  ReviewerApplicationEmailTR,
  ReviewerApplicationEmailUK,
  ReviewerApplicationEmailVI,
  ReviewerApplicationEmailZH,
} from '@emails/ReviewerApplicationEmail';
import {
  ReviewerApprovedEmailAR,
  ReviewerApprovedEmailDE,
  ReviewerApprovedEmailEN,
  ReviewerApprovedEmailEN_GB,
  ReviewerApprovedEmailES,
  ReviewerApprovedEmailFR,
  ReviewerApprovedEmailHI,
  ReviewerApprovedEmailID,
  ReviewerApprovedEmailIT,
  ReviewerApprovedEmailJA,
  ReviewerApprovedEmailKO,
  ReviewerApprovedEmailPL,
  ReviewerApprovedEmailPT,
  ReviewerApprovedEmailRU,
  ReviewerApprovedEmailTR,
  ReviewerApprovedEmailUK,
  ReviewerApprovedEmailVI,
  ReviewerApprovedEmailZH,
} from '@emails/ReviewerApprovedEmail';
import { ReviewerContactEmailEN } from '@emails/ReviewerContactEmail';
import {
  SubscriptionPaymentCancellationAR,
  SubscriptionPaymentCancellationDE,
  SubscriptionPaymentCancellationEN,
  SubscriptionPaymentCancellationEN_GB,
  SubscriptionPaymentCancellationES,
  SubscriptionPaymentCancellationFR,
  SubscriptionPaymentCancellationHI,
  SubscriptionPaymentCancellationID,
  SubscriptionPaymentCancellationIT,
  SubscriptionPaymentCancellationJA,
  SubscriptionPaymentCancellationKO,
  SubscriptionPaymentCancellationPL,
  SubscriptionPaymentCancellationPT,
  SubscriptionPaymentCancellationRU,
  SubscriptionPaymentCancellationTR,
  SubscriptionPaymentCancellationUK,
  SubscriptionPaymentCancellationVI,
  SubscriptionPaymentCancellationZH,
} from '@emails/SubscriptionPaymentCancellation';
import {
  SubscriptionPaymentErrorAR,
  SubscriptionPaymentErrorDE,
  SubscriptionPaymentErrorEN,
  SubscriptionPaymentErrorEN_GB,
  SubscriptionPaymentErrorES,
  SubscriptionPaymentErrorFR,
  SubscriptionPaymentErrorHI,
  SubscriptionPaymentErrorID,
  SubscriptionPaymentErrorIT,
  SubscriptionPaymentErrorJA,
  SubscriptionPaymentErrorKO,
  SubscriptionPaymentErrorPL,
  SubscriptionPaymentErrorPT,
  SubscriptionPaymentErrorRU,
  SubscriptionPaymentErrorTR,
  SubscriptionPaymentErrorUK,
  SubscriptionPaymentErrorVI,
  SubscriptionPaymentErrorZH,
} from '@emails/SubscriptionPaymentError';
import {
  SubscriptionPaymentSuccessAR,
  SubscriptionPaymentSuccessDE,
  SubscriptionPaymentSuccessEN,
  SubscriptionPaymentSuccessEN_GB,
  SubscriptionPaymentSuccessES,
  SubscriptionPaymentSuccessFR,
  SubscriptionPaymentSuccessHI,
  SubscriptionPaymentSuccessID,
  SubscriptionPaymentSuccessIT,
  SubscriptionPaymentSuccessJA,
  SubscriptionPaymentSuccessKO,
  SubscriptionPaymentSuccessPL,
  SubscriptionPaymentSuccessPT,
  SubscriptionPaymentSuccessRU,
  SubscriptionPaymentSuccessTR,
  SubscriptionPaymentSuccessUK,
  SubscriptionPaymentSuccessVI,
  SubscriptionPaymentSuccessZH,
} from '@emails/SubscriptionPaymentSuccess';
import {
  ValidateUserEmailAR,
  ValidateUserEmailDE,
  ValidateUserEmailEN,
  ValidateUserEmailEN_GB,
  ValidateUserEmailES,
  ValidateUserEmailFR,
  ValidateUserEmailHI,
  ValidateUserEmailID,
  ValidateUserEmailIT,
  ValidateUserEmailJA,
  ValidateUserEmailKO,
  ValidateUserEmailPL,
  ValidateUserEmailPT,
  ValidateUserEmailRU,
  ValidateUserEmailTR,
  ValidateUserEmailUK,
  ValidateUserEmailVI,
  ValidateUserEmailZH,
} from '@emails/ValidateUserEmail';
import {
  WelcomeEmailAR,
  WelcomeEmailDE,
  WelcomeEmailEN,
  WelcomeEmailEN_GB,
  WelcomeEmailES,
  WelcomeEmailFR,
  WelcomeEmailHI,
  WelcomeEmailID,
  WelcomeEmailIT,
  WelcomeEmailJA,
  WelcomeEmailKO,
  WelcomeEmailPL,
  WelcomeEmailPT,
  WelcomeEmailRU,
  WelcomeEmailTR,
  WelcomeEmailUK,
  WelcomeEmailVI,
  WelcomeEmailZH,
} from '@emails/Welcome';
import type { Locale } from '@intlayer/types/allLocales';
import { logger } from '@logger';
import { t } from 'fastify-intlayer';
import type { ComponentProps, JSX } from 'react';
import { Resend } from 'resend';

type EmailComponentsType = (...props: any) => JSX.Element;
type EmailComponents = {
  [key: string]: {
    template: EmailComponentsType;
    subject: string;
  };
};

const getEmailComponents = (locale?: Locale) =>
  ({
    affiliateInvitation: {
      template: t(
        {
          en: AffiliateInvitationEmailEN,
          fr: AffiliateInvitationEmailFR,
          es: AffiliateInvitationEmailES,
          ru: AffiliateInvitationEmailRU,
          ja: AffiliateInvitationEmailJA,
          ko: AffiliateInvitationEmailKO,
          zh: AffiliateInvitationEmailZH,
          de: AffiliateInvitationEmailDE,
          ar: AffiliateInvitationEmailAR,
          it: AffiliateInvitationEmailIT,
          'en-GB': AffiliateInvitationEmailEN_GB,
          pt: AffiliateInvitationEmailPT,
          hi: AffiliateInvitationEmailHI,
          tr: AffiliateInvitationEmailTR,
          pl: AffiliateInvitationEmailPL,
          id: AffiliateInvitationEmailID,
          vi: AffiliateInvitationEmailVI,
          uk: AffiliateInvitationEmailUK,
        },
        locale
      ),
      subject: "You've been invited to the Intlayer Affiliate Program",
    },
    affiliateWelcome: {
      template: t(
        {
          en: AffiliateWelcomeEmailEN,
          fr: AffiliateWelcomeEmailFR,
          es: AffiliateWelcomeEmailES,
          ru: AffiliateWelcomeEmailRU,
          ja: AffiliateWelcomeEmailJA,
          ko: AffiliateWelcomeEmailKO,
          zh: AffiliateWelcomeEmailZH,
          de: AffiliateWelcomeEmailDE,
          ar: AffiliateWelcomeEmailAR,
          it: AffiliateWelcomeEmailIT,
          'en-GB': AffiliateWelcomeEmailEN_GB,
          pt: AffiliateWelcomeEmailPT,
          hi: AffiliateWelcomeEmailHI,
          tr: AffiliateWelcomeEmailTR,
          pl: AffiliateWelcomeEmailPL,
          id: AffiliateWelcomeEmailID,
          vi: AffiliateWelcomeEmailVI,
          uk: AffiliateWelcomeEmailUK,
        },
        locale
      ),
      subject:
        'Welcome to the Intlayer Affiliate Program — complete your setup',
    },
    affiliateConversion: {
      template: t(
        {
          en: AffiliateConversionEmailEN,
          fr: AffiliateConversionEmailFR,
          es: AffiliateConversionEmailES,
          ru: AffiliateConversionEmailRU,
          ja: AffiliateConversionEmailJA,
          ko: AffiliateConversionEmailKO,
          zh: AffiliateConversionEmailZH,
          de: AffiliateConversionEmailDE,
          ar: AffiliateConversionEmailAR,
          it: AffiliateConversionEmailIT,
          'en-GB': AffiliateConversionEmailEN_GB,
          pt: AffiliateConversionEmailPT,
          hi: AffiliateConversionEmailHI,
          tr: AffiliateConversionEmailTR,
          pl: AffiliateConversionEmailPL,
          id: AffiliateConversionEmailID,
          vi: AffiliateConversionEmailVI,
          uk: AffiliateConversionEmailUK,
        },
        locale
      ),
      subject: 'New referral conversion — you earned a commission!',
    },
    affiliateActivated: {
      template: t(
        {
          en: AffiliateActivatedEmailEN,
          fr: AffiliateActivatedEmailFR,
          es: AffiliateActivatedEmailES,
          ru: AffiliateActivatedEmailRU,
          ja: AffiliateActivatedEmailJA,
          ko: AffiliateActivatedEmailKO,
          zh: AffiliateActivatedEmailZH,
          de: AffiliateActivatedEmailDE,
          ar: AffiliateActivatedEmailAR,
          it: AffiliateActivatedEmailIT,
          'en-GB': AffiliateActivatedEmailEN_GB,
          pt: AffiliateActivatedEmailPT,
          hi: AffiliateActivatedEmailHI,
          tr: AffiliateActivatedEmailTR,
          pl: AffiliateActivatedEmailPL,
          id: AffiliateActivatedEmailID,
          vi: AffiliateActivatedEmailVI,
          uk: AffiliateActivatedEmailUK,
        },
        locale
      ),
      subject: 'Your Intlayer affiliate account is now active!',
    },
    invite: {
      template: t(
        {
          en: InviteUserEmailEN,
          fr: InviteUserEmailFR,
          es: InviteUserEmailES,
          ru: InviteUserEmailRU,
          ja: InviteUserEmailJA,
          ko: InviteUserEmailKO,
          zh: InviteUserEmailZH,
          de: InviteUserEmailDE,
          ar: InviteUserEmailAR,
          it: InviteUserEmailIT,
          'en-GB': InviteUserEmailEN_GB,
          pt: InviteUserEmailPT,
          hi: InviteUserEmailHI,
          tr: InviteUserEmailTR,
          pl: InviteUserEmailPL,
          id: InviteUserEmailID,
          vi: InviteUserEmailVI,
          uk: InviteUserEmailUK,
        },
        locale
      ),
      subject: t(
        {
          en: 'You have been invited to join Intlayer',
          fr: 'Vous êtes invité à rejoindre Intlayer',
          es: 'Has sido invitado a unirte a Intlayer',
          ru: 'Вы были приглашены присоединиться к Intlayer',
          ja: 'Intlayerへの招待が届きました',
          ko: 'Intlayer에 초대되었습니다',
          zh: '您已受邀加入 Intlayer',
          de: 'Sie wurden eingeladen, Intlayer beizutreten',
          ar: 'لقد تم دعوتك للانضمام إلى Intlayer',
          it: 'Sei stato invitato a unirti a Intlayer',
          'en-GB': 'You have been invited to join Intlayer',
          pt: 'Você foi convidado a se juntar ao Intlayer',
          hi: 'आपको Intlayer में शामिल होने के लिए आमंत्रित किया गया है',
          tr: "Intlayer'a katılmanız için davet edildiniz",
          pl: 'Zostałeś zaproszony do dołączenia do Intlayer',
          id: 'Anda telah diundang untuk bergabung dengan Intlayer',
          vi: 'Bạn đã được mời tham gia Intlayer',
          uk: 'Вас запросили приєднатися до Intlayer',
        },
        locale
      ),
    },
    validate: {
      template: t(
        {
          en: ValidateUserEmailEN,
          fr: ValidateUserEmailFR,
          es: ValidateUserEmailES,
          ru: ValidateUserEmailRU,
          ja: ValidateUserEmailJA,
          ko: ValidateUserEmailKO,
          zh: ValidateUserEmailZH,
          de: ValidateUserEmailDE,
          ar: ValidateUserEmailAR,
          it: ValidateUserEmailIT,
          'en-GB': ValidateUserEmailEN_GB,
          pt: ValidateUserEmailPT,
          hi: ValidateUserEmailHI,
          tr: ValidateUserEmailTR,
          pl: ValidateUserEmailPL,
          id: ValidateUserEmailID,
          vi: ValidateUserEmailVI,
          uk: ValidateUserEmailUK,
        },
        locale
      ),
      subject: t(
        {
          en: 'Validate your email for Intlayer',
          fr: 'Validez votre email pour Intlayer',
          es: 'Valida tu correo electrónico para Intlayer',
          ru: 'Подтвердите свой адрес электронной почты для Intlayer',
          ja: 'Intlayerのメールアドレスを認証してください',
          ko: 'Intlayer 이메일 주소를 인증해 주세요',
          zh: '验证您的 Intlayer 电子邮件',
          de: 'Bestätigen Sie Ihre E-Mail für Intlayer',
          ar: 'تأكيد بريدك الإلكتروني لـ Intlayer',
          it: 'Conferma la tua email per Intlayer',
          'en-GB': 'Validate your email for Intlayer',
          pt: 'Valide seu e-mail para Intlayer',
          hi: 'Intlayer के लिए अपना ईमेल सत्यापित करें',
          tr: 'Intlayer için e-postanızı doğrulayın',
          pl: 'Zweryfikuj swój e-mail dla Intlayer',
          id: 'Validasi email Anda per Intlayer',
          vi: 'Xác thực email của bạn cho Intlayer',
          uk: 'Підтвердьте свою електронну пошту для Intlayer',
        },
        locale
      ),
    },
    resetPassword: {
      template: t(
        {
          en: ResetPasswordEmailEN,
          fr: ResetPasswordEmailFR,
          es: ResetPasswordEmailES,
          ru: ResetPasswordEmailRU,
          ja: ResetPasswordEmailJA,
          ko: ResetPasswordEmailKO,
          zh: ResetPasswordEmailZH,
          de: ResetPasswordEmailDE,
          ar: ResetPasswordEmailAR,
          it: ResetPasswordEmailIT,
          'en-GB': ResetPasswordEmailEN_GB,
          pt: ResetPasswordEmailPT,
          hi: ResetPasswordEmailHI,
          tr: ResetPasswordEmailTR,
          pl: ResetPasswordEmailPL,
          id: ResetPasswordEmailID,
          vi: ResetPasswordEmailVI,
          uk: ResetPasswordEmailUK,
        },
        locale
      ),
      subject: t(
        {
          en: 'Reset your password for Intlayer',
          fr: 'Réinitialisez votre mot de passe pour Intlayer',
          es: 'Restablece tu contraseña para Intlayer',
          ru: 'Сброс пароля для Intlayer',
          ja: 'Intlayerのパスワードをリセットしてください',
          ko: 'Intlayer 비밀번호를 재설정해 주세요',
          zh: '重置您的 Intlayer 密码',
          de: 'Setzen Sie Ihr Passwort für Intlayer zurück',
          ar: 'إعادة تعيين كلمة المرور لـ Intlayer',
          it: 'Reimposta la tua password per Intlayer',
          'en-GB': 'Reset your password for Intlayer',
          pt: 'Redefina sua senha para Intlayer',
          hi: 'Intlayer के लिए अपना पासवर्ड रीसेट करें',
          tr: 'Intlayer için şifrenizi sıfırlayın',
          pl: 'Zresetuj swoje hasło do Intlayer',
          id: 'Reset kata sandi Anda untuk Intlayer',
          vi: 'Đặt lại mật khẩu của bạn cho Intlayer',
          uk: 'Скидання пароля для Intlayer',
        },
        locale
      ),
    },
    welcome: {
      template: t(
        {
          en: WelcomeEmailEN,
          fr: WelcomeEmailFR,
          es: WelcomeEmailES,
          ru: WelcomeEmailRU,
          ja: WelcomeEmailJA,
          ko: WelcomeEmailKO,
          zh: WelcomeEmailZH,
          de: WelcomeEmailDE,
          ar: WelcomeEmailAR,
          it: WelcomeEmailIT,
          'en-GB': WelcomeEmailEN_GB,
          pt: WelcomeEmailPT,
          hi: WelcomeEmailHI,
          tr: WelcomeEmailTR,
          pl: WelcomeEmailPL,
          id: WelcomeEmailID,
          vi: WelcomeEmailVI,
          uk: WelcomeEmailUK,
        },
        locale
      ),
      subject: t(
        {
          en: 'Welcome to Intlayer!',
          fr: 'Bienvenue chez Intlayer!',
          es: '¡Bienvenido a Intlayer!',
          ru: 'Добро пожаловать в Intlayer!',
          ja: 'Intlayerへようこそ！',
          ko: 'Intlayer에 오신 것을 환영합니다!',
          zh: '欢迎来到 Intlayer！',
          de: 'Willkommen bei Intlayer!',
          ar: 'مرحباً بك في Intlayer!',
          it: 'Benvenuto in Intlayer!',
          'en-GB': 'Welcome to Intlayer!',
          pt: 'Bem-vindo ao Intlayer!',
          hi: 'Intlayer में आपका स्वागत है!',
          tr: "Intlayer'a hoş geldiniz!",
          pl: 'Witaj w Intlayer!',
          id: 'Selamat datang di Intlayer!',
          vi: 'Chào mừng bạn đến với Intlayer!',
          uk: 'Ласкаво просимо до Intlayer!',
        },
        locale
      ),
    },
    magicLink: {
      template: t(
        {
          en: MagicLinkEmailEN,
          fr: MagicLinkEmailFR,
          es: MagicLinkEmailES,
          ru: MagicLinkEmailRU,
          ja: MagicLinkEmailJA,
          ko: MagicLinkEmailKO,
          zh: MagicLinkEmailZH,
          de: MagicLinkEmailDE,
          ar: MagicLinkEmailAR,
          it: MagicLinkEmailIT,
          'en-GB': MagicLinkEmailEN_GB,
          pt: MagicLinkEmailPT,
          hi: MagicLinkEmailHI,
          tr: MagicLinkEmailTR,
          pl: MagicLinkEmailPL,
          id: MagicLinkEmailID,
          vi: MagicLinkEmailVI,
          uk: MagicLinkEmailUK,
        },
        locale
      ),
      subject: t(
        {
          en: 'Sign in to Intlayer',
          fr: 'Connectez-vous à Intlayer',
          es: 'Inicia sesión en Intlayer',
          ru: 'Войти в Intlayer',
          ja: 'Intlayerにサインイン',
          ko: 'Intlayer에 로그인하기',
          zh: '登录到 Intlayer',
          de: 'Bei Intlayer anmelden',
          ar: 'تسجيل الدخول إلى Intlayer',
          it: 'Accedi a Intlayer',
          'en-GB': 'Sign in to Intlayer',
          pt: 'Entrar no Intlayer',
          hi: 'Intlayer में साइन इन करें',
          tr: "Intlayer'a giriş yapın",
          pl: 'Zaloguj się do Intlayer',
          id: 'Masuk ke Intlayer',
          vi: 'Đăng nhập vào Intlayer',
          uk: 'Увійти в Intlayer',
        },
        locale
      ),
    },
    passwordChangeConfirmation: {
      template: t(
        {
          en: PasswordChangeConfirmationEmailEN,
          fr: PasswordChangeConfirmationEmailFR,
          es: PasswordChangeConfirmationEmailES,
          ru: PasswordChangeConfirmationEmailRU,
          ja: PasswordChangeConfirmationEmailJA,
          ko: PasswordChangeConfirmationEmailKO,
          zh: PasswordChangeConfirmationEmailZH,
          de: PasswordChangeConfirmationEmailDE,
          ar: PasswordChangeConfirmationEmailAR,
          it: PasswordChangeConfirmationEmailIT,
          'en-GB': PasswordChangeConfirmationEmailEN_GB,
          pt: PasswordChangeConfirmationEmailPT,
          hi: PasswordChangeConfirmationEmailHI,
          tr: PasswordChangeConfirmationEmailTR,
          pl: PasswordChangeConfirmationEmailPL,
          id: PasswordChangeConfirmationEmailID,
          vi: PasswordChangeConfirmationEmailVI,
          uk: PasswordChangeConfirmationEmailUK,
        },
        locale
      ),
      subject: t(
        {
          en: 'Your Intlayer password has been changed',
          fr: 'Votre mot de passe Intlayer a été modifié',
          es: 'Tu contraseña de Intlayer ha sido cambiada',
          ru: 'Ваш пароль Intlayer был изменен',
          ja: 'Intlayerのパスワードが変更されました',
          ko: 'Intlayer 비밀번호가 변경되었습니다',
          zh: '您的 Intlayer 密码已更改',
          de: 'Ihr Intlayer-Passwort wurde geändert',
          ar: 'تم تغيير كلمة مرور Intlayer الخاصة بك',
          it: 'La tua password Intlayer è stata modificata',
          'en-GB': 'Your Intlayer password has been changed',
          pt: 'Sua senha do Intlayer foi alterada',
          hi: 'आपका Intlayer पासवर्ड बदल दिया गया है',
          tr: 'Intlayer şifreniz değiştirildi',
          pl: 'Twoje hasło do Intlayer zostało zmienione',
          id: 'Kata sandi Intlayer Anda telah diubah',
          vi: 'Mật khẩu Intlayer của bạn đã được thay đổi',
          uk: 'Ваш пароль Intlayer було змінено',
        },
        locale
      ),
    },
    subscriptionPaymentSuccess: {
      template: t(
        {
          en: SubscriptionPaymentSuccessEN,
          fr: SubscriptionPaymentSuccessFR,
          es: SubscriptionPaymentSuccessES,
          ru: SubscriptionPaymentSuccessRU,
          ja: SubscriptionPaymentSuccessJA,
          ko: SubscriptionPaymentSuccessKO,
          zh: SubscriptionPaymentSuccessZH,
          de: SubscriptionPaymentSuccessDE,
          ar: SubscriptionPaymentSuccessAR,
          it: SubscriptionPaymentSuccessIT,
          'en-GB': SubscriptionPaymentSuccessEN_GB,
          pt: SubscriptionPaymentSuccessPT,
          hi: SubscriptionPaymentSuccessHI,
          tr: SubscriptionPaymentSuccessTR,
          pl: SubscriptionPaymentSuccessPL,
          id: SubscriptionPaymentSuccessID,
          vi: SubscriptionPaymentSuccessVI,
          uk: SubscriptionPaymentSuccessUK,
        },
        locale
      ),
      subject: t(
        {
          en: 'Your payment for Intlayer subscription is confirmed',
          fr: "Votre paiement pour l'abonnement Intlayer est confirmé",
          es: 'Tu pago por la suscripción de Intlayer ha sido confirmado',
          ru: 'Ваш платеж за подписку Intlayer подтвержден',
          ja: 'Intlayerサブスクリプションの支払いが確認されました',
          ko: 'Intlayer 구독 결제가 완료되었습니다',
          zh: '您的 Intlayer 订阅付款已确认',
          de: 'Ihre Zahlung für das Intlayer-Abonnement wurde bestätigt',
          ar: 'تم تأكيد دفعك لاشتراك Intlayer',
          it: "Il tuo pagamento per l'abbonamento Intlayer è confermato",
          'en-GB': 'Your payment for Intlayer subscription is confirmed',
          pt: 'Seu pagamento para a assinatura Intlayer está confirmado',
          hi: 'Intlayer सदस्यता के लिए आपका भुगतान पुष्ट हो गया है',
          tr: 'Intlayer aboneliği için ödemeniz onaylandı',
          pl: 'Twoja płatność za subskrypcję Intlayer została potwierdzona',
          id: 'Pembayaran Anda untuk langganan Intlayer telah dikonfirmasi',
          vi: 'Thanh toán cho gói thuê bao Intlayer của bạn đã được xác nhận',
          uk: 'Ваш платіж за підписку Intlayer підтверджено',
        },
        locale
      ),
    },
    subscriptionPaymentCancellation: {
      template: t(
        {
          en: SubscriptionPaymentCancellationEN,
          fr: SubscriptionPaymentCancellationFR,
          es: SubscriptionPaymentCancellationES,
          ru: SubscriptionPaymentCancellationRU,
          ja: SubscriptionPaymentCancellationJA,
          ko: SubscriptionPaymentCancellationKO,
          zh: SubscriptionPaymentCancellationZH,
          de: SubscriptionPaymentCancellationDE,
          ar: SubscriptionPaymentCancellationAR,
          it: SubscriptionPaymentCancellationIT,
          'en-GB': SubscriptionPaymentCancellationEN_GB,
          pt: SubscriptionPaymentCancellationPT,
          hi: SubscriptionPaymentCancellationHI,
          tr: SubscriptionPaymentCancellationTR,
          pl: SubscriptionPaymentCancellationPL,
          id: SubscriptionPaymentCancellationID,
          vi: SubscriptionPaymentCancellationVI,
          uk: SubscriptionPaymentCancellationUK,
        },
        locale
      ),
      subject: t(
        {
          en: 'Your Intlayer subscription has been canceled',
          fr: 'Votre abonnement Intlayer a été annulé',
          es: 'Tu suscripción de Intlayer ha sido cancelada',
          ru: 'Ваша подписка Intlayer была отменена',
          ja: 'Intlayerサブスクリプションがキャンセルされました',
          ko: 'Intlayer 구독이 취소되었습니다',
          zh: '您的 Intlayer 订阅已取消',
          de: 'Ihr Intlayer-Abonnement wurde gekündigt',
          ar: 'تم إلغاء اشتراك Intlayer الخاص بك',
          it: 'Il tuo abbonamento Intlayer è stato annullato',
          'en-GB': 'Your Intlayer subscription has been cancelled',
          pt: 'Sua assinatura do Intlayer foi cancelada',
          hi: 'आपकी Intlayer सदस्यता रद्द कर दी गई है',
          tr: 'Intlayer aboneliğiniz iptal edildi',
          pl: 'Twoja subskrypcja Intlayer została anulowana',
          id: 'Langganan Intlayer Anda telah dibatalkan',
          vi: 'Gói thuê bao Intlayer của bạn đã bị hủy',
          uk: 'Вашу підписку Intlayer скасовано',
        },
        locale
      ),
    },
    subscriptionPaymentError: {
      template: t(
        {
          en: SubscriptionPaymentErrorEN,
          fr: SubscriptionPaymentErrorFR,
          es: SubscriptionPaymentErrorES,
          ru: SubscriptionPaymentErrorRU,
          ja: SubscriptionPaymentErrorJA,
          ko: SubscriptionPaymentErrorKO,
          zh: SubscriptionPaymentErrorZH,
          de: SubscriptionPaymentErrorDE,
          ar: SubscriptionPaymentErrorAR,
          it: SubscriptionPaymentErrorIT,
          'en-GB': SubscriptionPaymentErrorEN_GB,
          pt: SubscriptionPaymentErrorPT,
          hi: SubscriptionPaymentErrorHI,
          tr: SubscriptionPaymentErrorTR,
          pl: SubscriptionPaymentErrorPL,
          id: SubscriptionPaymentErrorID,
          vi: SubscriptionPaymentErrorVI,
          uk: SubscriptionPaymentErrorUK,
        },
        locale
      ),
      subject: t(
        {
          en: 'There was an issue with your Intlayer subscription payment',
          fr: "Un problème est survenu avec votre paiement pour l'abonnement Intlayer",
          es: 'Hubo un problema con el pago de tu suscripción de Intlayer',
          ru: 'Возникла проблема с оплатой подписки Intlayer',
          ja: 'Intlayerサブスクリプションの支払いに問題が発生しました',
          ko: 'Intlayer 구독 결제 중 문제가 발생했습니다',
          zh: '您的 Intlayer 订阅付款出现问题',
          de: 'Es gab ein Problem mit Ihrer Intlayer-Abonnementzahlung',
          ar: 'كانت هناك مشكلة في دفع اشتراك Intlayer الخاص بك',
          it: "C'è stato un problema con il pagamento dell'abbonamento Intlayer",
          'en-GB': 'There was an issue with your Intlayer subscription payment',
          pt: 'Houve um problema com o pagamento da sua assinatura Intlayer',
          hi: 'आपकी Intlayer सदस्यता के भुगतान में कोई समस्या थी',
          tr: 'Intlayer abonelik ödemenizde bir sorun oluştu',
          pl: 'Wystąpił problem z płatnością za subskrypcję Intlayer',
          id: 'Terjadi masalah dengan pembayaran langganan Intlayer Anda',
          vi: 'Đã xảy ra vấn đề với việc thanh toán gói thuê bao Intlayer của bạn',
          uk: 'Виникла проблема з оплатою підписки Intlayer',
        },
        locale
      ),
    },
    oAuthTokenCreated: {
      template: t(
        {
          en: OAuthTokenCreatedEmailEN,
          fr: OAuthTokenCreatedEmailFR,
          es: OAuthTokenCreatedEmailES,
          ru: OAuthTokenCreatedEmailRU,
          ja: OAuthTokenCreatedEmailJA,
          ko: OAuthTokenCreatedEmailKO,
          zh: OAuthTokenCreatedEmailZH,
          de: OAuthTokenCreatedEmailDE,
          ar: OAuthTokenCreatedEmailAR,
          it: OAuthTokenCreatedEmailIT,
          'en-GB': OAuthTokenCreatedEmailEN_GB,
          pt: OAuthTokenCreatedEmailPT,
          hi: OAuthTokenCreatedEmailHI,
          tr: OAuthTokenCreatedEmailTR,
          pl: OAuthTokenCreatedEmailPL,
          id: OAuthTokenCreatedEmailID,
          vi: OAuthTokenCreatedEmailVI,
          uk: OAuthTokenCreatedEmailUK,
        },
        locale
      ),
      subject: t(
        {
          en: 'A third-party OAuth application has been added to your Intlayer account',
          fr: 'Une application OAuth tierce a été ajoutée à votre compte Intlayer',
          es: 'Una aplicación OAuth de terceros ha sido añadida a tu cuenta de Intlayer',
          ru: 'Стороннее приложение OAuth было добавлено в ваш аккаунт Intlayer',
          ja: 'サードパーティのOAuthアプリケーションがIntlayerアカウントに追加されました',
          ko: '제3자 OAuth 애플리케이션이 Intlayer 계정에 추가되었습니다',
          zh: '一个第三方 OAuth 应用程序已添加到您的 Intlayer 帐户',
          de: 'Eine OAuth-Anwendung eines Drittanbieters wurde Ihrem Intlayer-Konto hinzugefügt',
          ar: 'تمت إضافة تطبيق OAuth لجهة خارجية إلى حساب Intlayer الخاص بك',
          it: "Un'applicazione OAuth di terze parti è stata aggiunta al tuo account Intlayer",
          'en-GB':
            'A third-party OAuth application has been added to your Intlayer account',
          pt: 'Um aplicativo OAuth de terceiros foi adicionado à sua conta do Intlayer',
          hi: 'आपके Intlayer खाते में एक तृतीय-पक्ष OAuth एप्लिकेशन जोड़ा गया है',
          tr: 'Intlayer hesabınıza üçüncü taraf bir OAuth uygulaması eklendi',
          pl: 'Do Twojego konta Intlayer dodano aplikację OAuth innej firmy',
          id: 'Aplikasi OAuth pihak ketiga telah ditambahkan ke akun Intlayer Anda',
          vi: 'Một ứng dụng OAuth của bên thứ ba đã được thêm vào tài khoản Intlayer của bạn',
          uk: 'До вашого облікового запису Intlayer додано сторонній додаток OAuth',
        },
        locale
      ),
    },
    missionRequestedClient: {
      template: t(
        {
          en: MissionRequestedClientEmailEN,
          fr: MissionRequestedClientEmailFR,
          es: MissionRequestedClientEmailES,
          ru: MissionRequestedClientEmailRU,
          ja: MissionRequestedClientEmailJA,
          ko: MissionRequestedClientEmailKO,
          zh: MissionRequestedClientEmailZH,
          de: MissionRequestedClientEmailDE,
          ar: MissionRequestedClientEmailAR,
          it: MissionRequestedClientEmailIT,
          'en-GB': MissionRequestedClientEmailEN_GB,
          pt: MissionRequestedClientEmailPT,
          hi: MissionRequestedClientEmailHI,
          tr: MissionRequestedClientEmailTR,
          pl: MissionRequestedClientEmailPL,
          id: MissionRequestedClientEmailID,
          vi: MissionRequestedClientEmailVI,
          uk: MissionRequestedClientEmailUK,
        },
        locale
      ),
      subject: t(
        {
          en: 'Your request has been sent — Intlayer',
          fr: 'Votre demande a été envoyée — Intlayer',
          es: 'Tu solicitud ha sido enviada — Intlayer',
          ru: 'Ваш запрос отправлен — Intlayer',
          ja: 'リクエストが送信されました — Intlayer',
          ko: '요청이 전송되었습니다 — Intlayer',
          zh: '您的请求已发送 — Intlayer',
          de: 'Ihre Anfrage wurde gesendet — Intlayer',
          ar: 'تم إرسال طلبك — Intlayer',
          it: 'La tua richiesta è stata inviata — Intlayer',
          'en-GB': 'Your request has been sent — Intlayer',
          pt: 'Sua solicitação foi enviada — Intlayer',
          hi: 'आपका अनुरोध भेज दिया गया — Intlayer',
          tr: 'İsteğiniz gönderildi — Intlayer',
          pl: 'Twoje zgłoszenie zostało wysłane — Intlayer',
          id: 'Permintaan Anda telah dikirim — Intlayer',
          vi: 'Yêu cầu của bạn đã được gửi — Intlayer',
          uk: 'Ваш запит надіслано — Intlayer',
        },
        locale
      ),
    },
    missionRequestedReviewer: {
      template: t(
        {
          en: MissionRequestedReviewerEmailEN,
          fr: MissionRequestedReviewerEmailFR,
          es: MissionRequestedReviewerEmailES,
          ru: MissionRequestedReviewerEmailRU,
          ja: MissionRequestedReviewerEmailJA,
          ko: MissionRequestedReviewerEmailKO,
          zh: MissionRequestedReviewerEmailZH,
          de: MissionRequestedReviewerEmailDE,
          ar: MissionRequestedReviewerEmailAR,
          it: MissionRequestedReviewerEmailIT,
          'en-GB': MissionRequestedReviewerEmailEN_GB,
          pt: MissionRequestedReviewerEmailPT,
          hi: MissionRequestedReviewerEmailHI,
          tr: MissionRequestedReviewerEmailTR,
          pl: MissionRequestedReviewerEmailPL,
          id: MissionRequestedReviewerEmailID,
          vi: MissionRequestedReviewerEmailVI,
          uk: MissionRequestedReviewerEmailUK,
        },
        locale
      ),
      subject: t(
        {
          en: 'You have a new translation request — Intlayer',
          fr: 'Vous avez une nouvelle demande de traduction — Intlayer',
          es: 'Tienes una nueva solicitud de traducción — Intlayer',
          ru: 'У вас новый запрос на перевод — Intlayer',
          ja: '新しい翻訳リクエストがあります — Intlayer',
          ko: '새 번역 요청이 있습니다 — Intlayer',
          zh: '您有一个新的翻译请求 — Intlayer',
          de: 'Sie haben eine neue Übersetzungsanfrage — Intlayer',
          ar: 'لديك طلب ترجمة جديد — Intlayer',
          it: 'Hai una nuova richiesta di traduzione — Intlayer',
          'en-GB': 'You have a new translation request — Intlayer',
          pt: 'Você tem uma nova solicitação de tradução — Intlayer',
          hi: 'आपके पास एक नया अनुवाद अनुरोध है — Intlayer',
          tr: 'Yeni bir çeviri talebiniz var — Intlayer',
          pl: 'Masz nowe zlecenie tłumaczenia — Intlayer',
          id: 'Anda memiliki permintaan terjemahan baru — Intlayer',
          vi: 'Bạn có một yêu cầu dịch thuật mới — Intlayer',
          uk: 'У вас новий запит на переклад — Intlayer',
        },
        locale
      ),
    },
    reviewerApplication: {
      template: t(
        {
          en: ReviewerApplicationEmailEN,
          fr: ReviewerApplicationEmailFR,
          es: ReviewerApplicationEmailES,
          ru: ReviewerApplicationEmailRU,
          ja: ReviewerApplicationEmailJA,
          ko: ReviewerApplicationEmailKO,
          zh: ReviewerApplicationEmailZH,
          de: ReviewerApplicationEmailDE,
          ar: ReviewerApplicationEmailAR,
          it: ReviewerApplicationEmailIT,
          'en-GB': ReviewerApplicationEmailEN_GB,
          pt: ReviewerApplicationEmailPT,
          hi: ReviewerApplicationEmailHI,
          tr: ReviewerApplicationEmailTR,
          pl: ReviewerApplicationEmailPL,
          id: ReviewerApplicationEmailID,
          vi: ReviewerApplicationEmailVI,
          uk: ReviewerApplicationEmailUK,
        },
        locale
      ),
      subject: 'New reviewer application on Intlayer',
    },
    reviewerApproved: {
      template: t(
        {
          en: ReviewerApprovedEmailEN,
          fr: ReviewerApprovedEmailFR,
          es: ReviewerApprovedEmailES,
          ru: ReviewerApprovedEmailRU,
          ja: ReviewerApprovedEmailJA,
          ko: ReviewerApprovedEmailKO,
          zh: ReviewerApprovedEmailZH,
          de: ReviewerApprovedEmailDE,
          ar: ReviewerApprovedEmailAR,
          it: ReviewerApprovedEmailIT,
          'en-GB': ReviewerApprovedEmailEN_GB,
          pt: ReviewerApprovedEmailPT,
          hi: ReviewerApprovedEmailHI,
          tr: ReviewerApprovedEmailTR,
          pl: ReviewerApprovedEmailPL,
          id: ReviewerApprovedEmailID,
          vi: ReviewerApprovedEmailVI,
          uk: ReviewerApprovedEmailUK,
        },
        locale
      ),
      subject: t(
        {
          en: 'Your Intlayer reviewer profile has been approved!',
          fr: 'Votre profil traducteur Intlayer a été approuvé !',
          es: '¡Tu perfil de traductor en Intlayer ha sido aprobado!',
          ru: 'Ваш профиль переводчика на Intlayer одобрен!',
          ja: 'Intlayerの翻訳者プロフィールが承認されました！',
          ko: 'Intlayer 번역가 프로필이 승인되었습니다!',
          zh: '您的 Intlayer 译者档案已获批准！',
          de: 'Ihr Intlayer Übersetzer-Profil wurde genehmigt!',
          ar: 'تمت الموافقة على ملف المترجم الخاص بك في Intlayer!',
          it: 'Il tuo profilo traduttore su Intlayer è stato approvato!',
          'en-GB': 'Your Intlayer reviewer profile has been approved!',
          pt: 'Seu perfil de tradutor no Intlayer foi aprovado!',
          hi: 'Intlayer पर आपकी अनुवादक प्रोफ़ाइल को अनुमोदित कर दिया गया है!',
          tr: 'Intlayer çevirmen profiliniz onaylandı!',
          pl: 'Twój profil tłumacza w Intlayer został zatwierdzony!',
          id: 'Profil penerjemah Intlayer Anda telah disetujui!',
          vi: 'Hồ sơ dịch giả Intlayer của bạn đã được phê duyệt!',
          uk: 'Ваш профіль перекладача на Intlayer схвалено!',
        },
        locale
      ),
    },
    reviewerContactInquiry: {
      template: ReviewerContactEmailEN,
      subject: 'New message from a client — Intlayer',
    },
  }) satisfies EmailComponents;

type EmailType = keyof ReturnType<typeof getEmailComponents>;

export type SendEmailProps<T extends EmailType> = {
  type: T;
  to: string;
  subject?: string;
  locale?: Locale;
} & ComponentProps<ReturnType<typeof getEmailComponents>[T]['template']>;

export const sendEmail = async <T extends EmailType>({
  type,
  to,
  subject,
  locale,
  ...props
}: SendEmailProps<T>) => {
  const resend = new Resend(process.env.RESEND_API_KEY);

  const emailComponents = getEmailComponents(locale);

  const { template, subject: baseSubject } = emailComponents[type];

  type EmailComponentType = (typeof emailComponents)[T]['template'];

  const EmailComponent: EmailComponentType = template;

  const react = <EmailComponent {...(props as any)} />;

  await resend.emails
    .send({
      from: 'Intlayer <no-reply@intlayer.org>',
      to,
      subject: subject ?? baseSubject,
      react,
    })
    .catch((err) => logger.error(err));

  logger.info(`Email sent ${type} to ${to}`);
};
