import { type Dictionary, t } from 'intlayer';

const tagFormContent = {
  key: 'tag-form',
  content: {
    noAdminMessage: t({
      en: 'You are not an admin of this tag. Contact your administrator if you want to edit the tag.',
      'en-GB':
        'You are not an admin of this tag. Contact your administrator if you want to edit the tag.',
      es: 'No eres un administrador de este tag. Contacta a tu administrador si deseas editar el tag.',
      fr: "Vous n'êtes pas un administrateur de ce tag. Contactez votre administrateur si vous souhaitez modifier le tag.",
      de: 'Sie sind kein Administrator dieses Tags. Wenden Sie sich an Ihren Administrator, wenn Sie den Tag bearbeiten möchten.',
      ja: 'このタグの管理者ではありません。タグを編集したい場合は管理者に連絡してください。',
      ko: '이 태그의 관리자가 아닙니다. 태그를 편집하려면 관리자에게 문의하십시오.',
      zh: '您不是此标签的管理员。如果要编辑标签，请联系管理员。',
      it: 'Non sei un amministratore di questo tag. Contatta il tuo amministratore se desideri modificare il tag.',
      pt: 'Você não é um administrador desta tag. Entre em contato com seu administrador se desejar editar a tag.',
      hi: 'आप इस टैग के व्यवस्थापक नहीं हैं। टैग संपादित करना चाहते हैं तो अपने प्रशासक से संपर्क करें।',
      ar: 'أنت لست مسؤولًا عن هذا الوسم. اتصل بمسؤولك إذا كنت ترغب في تحرير الوسم.',
      ru: 'Вы не являетесь администратором этого тега. Свяжитесь с вашим администратором, если хотите отредактировать тег.',
      tr: 'Bu tagın yöneticisi değilsiniz. Tagı düzenlemek istiyorsanız yöneticinizle iletişime geçin.',
      pl: 'Nie jesteś administratorem tego tagu. Skontaktuj się z administratorem, jeśli chcesz go edytować.',
      id: 'Anda bukan admin tag ini. Hubungi administrator jika ingin mengedit tag ini.',
      vi: 'Bạn không phải là admin của tag này. Liên hệ admin của bạn nếu bạn muốn chỉnh sửa tag.',
    }),

    keyInput: {
      label: t({
        en: 'Key',
        'en-GB': 'Key',
        fr: 'Clé',
        es: 'Clave',
        de: 'Schlüssel',
        ja: 'キー',
        ko: '키',
        zh: '密钥',
        it: 'Chiave',
        pt: 'Chave',
        hi: 'की',
        ar: 'مفتاح',
        ru: 'Ключ',
        tr: 'Anahtar',
        pl: 'Klucz',
        id: 'Key',
        vi: 'Key',
      }),
      description: t({
        en: 'Identify your tag with a unique key',
        'en-GB': 'Identify your tag with a unique key',
        fr: 'Identifier votre tag avec une clé unique',
        es: 'Identifique su tag con una clave única',
        de: 'Identifizieren Sie Ihren Tag mit einer eindeutigen Schlüssel',
        ja: 'タグを一意のキーで識別します',
        ko: '태그를 고유한 키로 식별합니다',
        zh: '通过一个独特的密钥来识别您的标签',
        it: 'Identifica il tuo tag con una chiave unica',
        pt: 'Identifique seu tag com uma chave única',
        hi: 'अपने टैग को एक अद्वितीय कुंजी के साथ पहचान करें',
        ar: 'تحديد الوسم الخاص بك باستخدام مفتاح فريد',
        ru: 'Укажите уникальный ключ для вашего тега',
        tr: 'Tagınızı benzersiz bir anahtarla tanımlayın',
        pl: 'Zidentyfikuj swój tag za pomocą unikalnego klucza',
        id: 'Identifikasi tag Anda dengan key yang unik',
        vi: 'Xác định tag của bạn bằng một key duy nhất',
      }),
      placeholder: t({
        en: 'Enter the key of your tag',
        'en-GB': 'Enter the key of your tag',
        fr: 'Entrez la clé de votre tag',
        es: 'Ingrese la clave de su tag',
        de: 'Geben Sie den Schlüssel Ihres Tags ein',
        ja: 'タグのキーを入力してください',
        ko: '태그의 키를 입력하십시오',
        zh: '输入标签的密钥',
        it: 'Inserisci la chiave del tag',
        pt: 'Insira a chave do seu tag',
        hi: 'टैग का कुंजी दर्ज करें',
        ar: 'أدخل مفتاح الوسم',
        ru: 'Введите ключ вашего тега',
        tr: "Tag'ınızın anahtarını girin",
        pl: 'Wprowadź klucz tagu',
        id: 'Masukkan key tag Anda',
        vi: 'Nhập key cho tag của bạn',
      }),
    },

    nameInput: {
      label: t({
        en: 'Name',
        'en-GB': 'Name',
        fr: 'Nom',
        es: 'Nombre',
        de: 'Name',
        ja: '名前',
        ko: '이름',
        zh: '名称',
        it: 'Nome',
        pt: 'Nome',
        hi: 'नाम',
        ar: 'الاسم',
        ru: 'Название',
        tr: 'İsim',
        pl: 'Nazwa',
        id: 'Nama',
        vi: 'Name',
      }),
      description: t({
        en: 'Title of your tag to help you identify it',
        'en-GB': 'Title of your tag to help you identify it',
        fr: 'Titre de votre tag pour vous aider à l’identifier',
        es: 'Título de su tag para ayudarlo a identificarse',
        de: 'Titel Ihres Tags, um es zu identifizieren',
        ja: 'タグのタイトルです。これがあなたのタグを識別するのに役立ちます',
        ko: '태그의 제목입니다. 이것은 태그를 식별하는데 도움이 됩니다',
        zh: '标签的标题，以便您能够识别它',
        it: 'Titolo del tuo tag per aiutarti a identificarlo',
        pt: 'Título do seu tag para ajudá-lo a identificá-lo',
        hi: 'अपने टैग का शीर्षक जो आपको इसे पहचान करने में मदद करता है',
        ar: 'عنوان الوسم الخاص بك لمساعدتك في تحديده',
        ru: 'Название вашего тега, чтобы вам помочь в его идентификации',
        tr: 'Tagınızın başlığı, onu tanımlamanıza yardımcı olur',
        pl: 'Nazwa tagu, która pomoże Ci go zidentyfikować',
        id: 'Judul tag Anda untuk membantu mengidentifikasinya',
        vi: 'Tên của tag giúp bạn nhận diện nó',
      }),
      placeholder: t({
        en: 'Enter the name of the tag',
        'en-GB': 'Enter the name of the tag',
        fr: 'Entrez le nom du tag',
        es: 'Ingrese el nombre del tag',
        de: 'Geben Sie den Namen des Tags ein',
        ja: 'タグの名前を入力してください',
        ko: '태그 이름을 입력하세요',
        zh: '输入标签名称',
        it: 'Inserisci il nome del tag',
        pt: 'Insira o nome da tag',
        hi: 'टैग का नाम दर्ज करें',
        ar: 'أدخل اسم الوسم',
        ru: 'Введите название тега',
        tr: 'Tagın adını girin',
        pl: 'Wprowadź nazwę tagu',
        id: 'Masukkan nama tag',
        vi: 'Nhập tên của tag',
      }),
    },

    descriptionInput: {
      label: t({
        en: 'Description',
        'en-GB': 'Description',
        fr: 'Description',
        es: 'Descripción',
        de: 'Beschreibung',
        ja: '説明',
        ko: '설명',
        zh: '描述',
        it: 'Descrizione',
        pt: 'Descrição',
        hi: 'वर्णन',
        ar: 'وصف',
        ru: 'Описание',
        tr: 'Açıklama',
        pl: 'Opis',
        id: 'Deskripsi',
        vi: 'Description',
      }),
      description: t({
        en: 'Description of your tag to help you udnerstand its purpose. This will also be used to search for your tag',
        'en-GB':
          'Description of your tag to help you udnerstand its purpose. This will also be used to search for your tag',
        fr: 'Description de votre tag pour vous aider à comprendre son objectif. Cela sera également utilisé pour rechercher votre tag',
        es: 'Descripción de su tag para ayudarlo a entender su propósito. También se utilizará para buscar su tag',
        de: 'Beschreibung Ihres Tags, um Ihnen zu helfen, seine Bedeutung zu verstehen. Dies wird auch verwendet, um Ihren Tag zu suchen',
        ja: 'タグの説明です。これはタグの目的を理解するのに役立ちます。また、タグを検索するためにも使用されます',
        ko: '태그의 설명입니다. 이것은 태그의 목적을 이해하는데 도움이 됩니다. 또한 태그를 찾는데 사용됩니다',
        zh: '标签的描述，以便您能够理解它的目的。这也将用于搜索您的标签',
        it: 'Descrizione del tuo tag per aiutarti a capire il suo scopo. Questo verrà anche utilizzato per cercare il tuo tag',
        pt: 'Descrição do seu tag para ajudá-lo a entender seu propósito. Isso também será usado para pesquisar seu tag',
        hi: 'अपने टैग का वर्णन करने में मदद करता है इसे अपने टैग के लिए उपयोग किया जाएगा',
        ar: 'وصف الوسم الخاص بك لمساعدتك في فهم الغرض منه. سيتم استخدام هذا أيضًا للبحث عن وسمك',
        ru: 'Описание вашего тега, чтобы помочь вам понять его назначение. Это также будет использоваться для поиска вашего тега',
        tr: 'Tagınızın amacını anlamanıza yardımcı olacak tag açıklaması. Bu, tagınızı aramak için de kullanılacaktır',
        pl: 'Opis tagu, który pomoże Ci zrozumieć jego przeznaczenie. Będzie on również używany do wyszukiwania tagu',
        id: 'Deskripsi tag Anda untuk membantu memahami tujuannya. Ini juga akan digunakan untuk mencari tag Anda',
        vi: 'Mô tả tag của bạn để giúp bạn hiểu mục đích của nó. Mục này cũng sẽ được dùng để tìm kiếm tag của bạn',
      }),

      placeholder: t({
        en: 'Enter the description of your tag',
        'en-GB': 'Enter the description of your tag',
        fr: 'Entrez la description de votre tag',
        es: 'Ingrese la descripción de su tag',
        de: 'Geben Sie die Beschreibung Ihres Tags ein',
        ja: 'タグの説明を入力してください',
        ko: '태그의 설명을 입력하십시오',
        zh: '输入标签的描述',
        it: 'Inserisci la descrizione del tag',
        pt: 'Insira a descrição do seu tag',
        hi: 'टैग का वर्णन दर्ज करें',
        ar: 'أدخل وصف الوسم',
        ru: 'Введите описание вашего тега',
        tr: "Tag'ınızın açıklamasını girin",
        pl: 'Wprowadź opis tagu',
        id: 'Masukkan deskripsi tag Anda',
        vi: 'Nhập mô tả cho tag của bạn',
      }),
    },

    instructionsInput: {
      label: t({
        en: 'Instructions',
        'en-GB': 'Instructions',
        fr: 'Instructions',
        es: 'Instrucciones',
        de: 'Anweisungen',
        ja: '指示',
        ko: '지침',
        zh: '指示',
        it: 'Istruzioni',
        pt: 'Instruções',
        hi: 'निर्देश',
        ar: 'تعليمات',
        ru: 'Инструкции',
        tr: 'Talimatlar',
        pl: 'Instrukcje',
        id: 'Instruksi',
        vi: 'Instructions',
      }),
      description: t({
        en: 'Instructions are provided to AI to better understand your tag, and what rules to apply to a dictionary containing your tag',
        'en-GB':
          'Instructions are provided to AI to better understand your tag, and what rules to apply to a dictionary containing your tag',
        fr: 'Les instructions sont fournies à l’IA pour mieux comprendre votre tag et les règles à appliquer à un dictionnaire contenant votre tag',
        es: 'Las instrucciones se proporcionan a la IA para entender mejor su tag y las reglas a aplicar a un diccionario que contenga su tag',
        de: 'Anweisungen werden an AI bereitgestellt, um Ihren Tag besser zu verstehen und anzuwenden, welche Regeln für ein Wörterbuch mit Ihrem Tag gelten',
        ja: 'AIにタグの理解を改善するために提供された指示です。タグを含む辞書に適用するためのルールも提供されます',
        ko: '지침은 AI에게 태그를 더 잘 이해하고 태그를 포함하는 사전에 적용할 규칙을 제공합니다',
        zh: '指示是为了更好地理解您的标签，以及应用于包含您的标签的字典的规则',
        it: 'Le istruzioni vengono fornite all’IA per comprendere meglio il tuo tag e le regole da applicare a un dizionario contenente il tuo tag',
        pt: 'As instruções são fornecidas à IA para entender melhor seu tag e as regras a serem aplicadas a um dicionário contendo seu tag',
        hi: 'निर्देश एआई को आपके टैग को बेहतर समझने और आपके टैग को समाहित शब्दकोश पर लागू करने के नियमों को लागू करने के लिए प्रदान किए जाते हैं',
        ar: 'توصيات تقدمها للذكاء الذكي لتفهم مزيد من الوسم والقواعد التي ينطبق على قاموس يحتوي على الوسم',
        ru: 'Инструкции предоставляются ИИ для лучшего понимания вашего тега и правил, которые нужно применить к словарю, содержащему ваш тег',
        tr: "Talimatlar, AI'ya tagınızı ve tagınızı içeren bir sözlüğe uygulanacak kuralları daha iyi anlaması için sağlanır",
        pl: 'Instrukcje przekazywane są do AI, aby lepiej zrozumiało tag i zasady, które należy stosować w słowniku zawierającym ten tag',
        id: 'Instruksi diberikan kepada AI untuk lebih memahami tag Anda dan aturan yang harus diterapkan pada kamus yang berisi tag ini',
        vi: 'Các hướng dẫn được cung cấp cho AI để hiểu rõ hơn về tag của bạn và những quy tắc áp dụng cho một dictionary chứa tag này',
      }),
      placeholder: t({
        en: 'Enter the instructions of your tag',
        'en-GB': 'Enter the instructions of your tag',
        fr: 'Entrez les instructions de votre tag',
        es: 'Ingrese las instrucciones de su tag',
        de: 'Geben Sie die Anweisungen Ihres Tags ein',
        ja: 'タグの指示を入力してください',
        ko: '태그의 지침을 입력하십시오',
        zh: '输入标签的指示',
        it: 'Inserisci le istruzioni del tag',
        pt: 'Insira as instruções do seu tag',
        hi: 'टैग का निर्देश दर्ज करें',
        ar: 'أدخل تعليمات الوسم',
        ru: 'Введите инструкции вашего тега',
        tr: "Tag'ınızın talimatlarını girin",
        pl: 'Wprowadź instrukcje dla tagu',
        id: 'Masukkan instruksi tag Anda',
        vi: 'Nhập hướng dẫn cho tag của bạn',
      }),
    },

    createTagTitle: t({
      en: 'No tag',
      'en-GB': 'No tag',
      fr: 'Aucun tag',
      es: 'Sin tag',
      de: 'Kein Tag',
      ja: 'タグなし',
      ko: '태그 없음',
      zh: '没有标签',
      it: 'Nessun tag',
      pt: 'Sem tag',
      hi: 'कोई टैग नहीं',
      ar: 'لا توجد وسم',
      ru: 'Нет тега',
      tr: 'Tag yok',
      pl: 'Brak tagu',
      id: 'Belum ada tag',
      vi: 'Chưa có tag',
    }),

    createTagDescription: t({
      en: 'Create your first tag to indicate how AI can structure your content',
      'en-GB':
        'Create your first tag to indicate how AI can structure your content',
      fr: 'Créez votre premier tag pour indiquer comment l’IA peut structurer votre contenu',
      es: 'Cree su primer tag para indicar cómo la IA puede estructurar su contenido',
      de: 'Erstellen Sie Ihr erstes Tag, um anzugeben, wie die KI Ihren Inhalt strukturieren kann',
      ja: 'AIがコンテンツを構成する方法を示すために、最初のタグを作成してください',
      ko: 'AI가 콘텐츠를 구성하는 방법을 나타내는 첫 번째 태그를 만들어주세요',
      zh: '创建您的第一个标签，以指示 AI 如何构建您的内容',
      it: 'Crea il tuo primo tag per indicare come l’IA può strutturare il tuo contenuto',
      pt: 'Crie seu primeiro tag para indicar como a IA pode estruturar seu conteúdo',
      hi: 'AI को अपने सामग्री को संरचित करने के लिए अपने पहला टैग बनाने के लिए बनाएं',
      ar: 'أنشئ مشروعك الأول للبدء في استخدام Intlayer',
      ru: 'Создайте свой первый тег, чтобы показать, как ИИ может структурировать ваш контент',
      tr: "İçeriğinizi AI'nın nasıl yapılandırabileceğini göstermek için ilk tagınızı oluşturun",
      pl: 'Utwórz pierwszy tag, aby określić, jak AI może strukturyzować Twoje treści',
      id: 'Buat tag pertama Anda untuk menunjukkan bagaimana AI dapat mengatur konten Anda',
      vi: 'Tạo tag đầu tiên để chỉ cách AI có thể cấu trúc nội dung của bạn',
    }),

    createTagButton: {
      text: t({
        en: 'Create tag',
        'en-GB': 'Create tag',
        fr: 'Créer un tag',
        es: 'Crear un tag',
        de: 'Tag erstellen',
        ja: 'タグを作成',
        ko: '태그 만들기',
        zh: '创建标签',
        it: 'Crea tag',
        pt: 'Criar tag',
        hi: 'टैग बनाएं',
        ar: 'إنشاء وسم',
        ru: 'Создать тег',
        tr: 'Tag oluştur',
        pl: 'Utwórz tag',
        id: 'Buat tag',
        vi: 'Tạo tag',
      }),
      ariaLabel: t({
        en: 'Click to create tag',
        'en-GB': 'Click to create tag',
        fr: 'Cliquez pour créer un tag',
        es: 'Haga clic para crear un tag',
        de: 'Klicken Sie, um ein Tag zu erstellen',
        ja: 'タグを作成するにはクリックしてください',
        ko: '태그를 만들려면 클릭하세요',
        zh: '点击创建标签',
        it: 'Clicca per creare il tag',
        pt: 'Clique para criar o tag',
        hi: 'टैग बनाने के लिए क्लिक करें',
        ar: 'انقر لإنشاء وسم',
        ru: 'Нажмите, чтобы создать тег',
        tr: 'Tag oluşturmak için tıklayın',
        pl: 'Kliknij, aby utworzyć tag',
        id: 'Klik untuk membuat tag',
        vi: 'Nhấp để tạo tag',
      }),
    },

    editButton: {
      text: t({
        en: 'Edit tag',
        'en-GB': 'Edit tag',
        fr: 'Modifier le tag',
        es: 'Editar tag',
        de: 'Tag bearbeiten',
        ja: 'タグを編集',
        ko: '태그 편집',
        zh: '编辑标签',
        it: 'Modifica tag',
        pt: 'Editar tag',
        hi: 'टैग संपादित करें',
        ar: 'تعديل الوسم',
        ru: 'Редактировать тег',
        tr: 'Tagı düzenle',
        pl: 'Edytuj tag',
        id: 'Edit tag',
        vi: 'Chỉnh sửa tag',
      }),
      ariaLabel: t({
        en: 'Click to edit',
        'en-GB': 'Click to edit',
        fr: 'Cliquez pour modifier',
        es: 'Haga clic para editar',
        de: 'Klicken Sie zum Bearbeiten',
        ja: '編集するにはクリックしてください',
        ko: '편집하려면 클릭하세요',
        zh: '点击进行编辑',
        it: 'Clicca per modificare',
        pt: 'Clique para editar',
        hi: 'संपादित करने के लिए क्लिक करें',
        ar: 'انقر للتعديل',
        ru: 'Нажмите, чтобы редактировать',
        tr: 'Düzenlemek için tıklayın',
        pl: 'Kliknij, aby edytować',
        id: 'Klik untuk mengedit tag',
        vi: 'Nhấp để chỉnh sửa',
      }),
    },
    deleteButton: {
      text: t({
        en: 'Delete tag',
        'en-GB': 'Delete tag',
        fr: 'Supprimer le tag',
        es: 'Eliminar etiqueta',
        de: 'Tag löschen',
        ja: 'タグを削除',
        ko: '태그 삭제',
        zh: '删除标签',
        it: 'Elimina tag',
        pt: 'Excluir tag',
        hi: 'टैग हटाएं',
        ar: 'حذف الوسم',
        ru: 'Удалить тег',
        tr: 'Tagı sil',
        pl: 'Usuń tag',
        id: 'Hapus tag',
        vi: 'Xóa tag',
      }),
      ariaLabel: t({
        en: 'Click to delete tag',
        'en-GB': 'Click to delete tag',
        fr: 'Cliquez pour supprimer le tag',
        es: 'Haga clic para eliminar la etiqueta',
        de: 'Klicken Sie, um das Tag zu löschen',
        ja: 'タグを削除するにはクリックしてください',
        ko: '태그를 삭제하려면 클릭하세요',
        zh: '点击删除标签',
        it: 'Clicca per eliminare il tag',
        pt: 'Clique para excluir o tag',
        hi: 'टैग हटाने के लिए क्लिक करें',
        ar: 'انقر لحذف الوسم',
        ru: 'Нажмите, чтобы удалить тег',
        tr: 'Tagı silmek için tıklayın',
        pl: 'Kliknij, aby usunąć tag',
        id: 'Klik untuk menghapus tag',
        vi: 'Nhấp để xóa tag',
      }),
    },
    auditButton: {
      label: t({
        en: 'Audit',
        fr: 'Auditer',
        es: 'Auditar',
        'en-GB': 'Audit',
        de: 'Prüfen',
        ja: '監査',
        ko: '감사',
        zh: '审核',
        it: 'Controllare',
        pt: 'Auditar',
        hi: 'ऑडिट',
        ar: 'التدقيق',
        ru: 'Отслеживание',
        tr: 'Denetim',
        pl: 'Audyt',
        id: 'Audit',
        vi: 'Audit',
      }),
    },
  },
  title: 'Tag form',
  description:
    'Content declaration for the tag form component. Includes field labels, placeholders, and button texts used to create, edit, and manage tags within the dashboard.',
  tags: ['tag', 'form', 'dashboard'],
} satisfies Dictionary;

export default tagFormContent;
