import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'tag-form-schema',
  content: {
    requiredErrorKey: t({
      en: 'Please enter a key for your tag',
      'en-GB': 'Please enter a key for your tag',
      fr: 'Veuillez saisir une clé pour votre tag',
      es: 'Por favor, ingrese una clave para su tag',
      de: 'Bitte geben Sie einen Schlüssel für Ihr Tag ein',
      ja: 'タグのキーを入力してください',
      ko: '태그의 키를 입력하십시오',
      zh: '请为您的标签输入密钥',
      it: 'Si prega di inserire una chiave per il tag',
      pt: 'Por favor, insira uma chave para o seu tag',
      hi: 'कृपया अपने टैग का कुंजी दर्ज करें',
      ar: 'يرجى إدخال مفتاح لوسمك',
      ru: 'Пожалуйста, введите ключ для вашего тега',
      tr: 'Lütfen etiketiniz için bir anahtar girin',
      pl: 'Proszę podać klucz tagu.',
      id: 'Silakan masukkan key untuk tag Anda',
      vi: 'Vui lòng nhập key cho tag của bạn',
    }),

    invalidTypeErrorKey: t({
      en: 'Please enter a valid tag for your tag',
      'en-GB': 'Please enter a valid tag for your tag',
      fr: 'Veuillez saisir un tag valide pour votre tag',
      es: 'Por favor, ingrese un tag válido para su tag',
      de: 'Bitte geben Sie einen gültigen Tag für Ihr Tag ein',
      ja: 'タグの有効なタグを入力してください',
      ko: '태그의 유효한 태그를 입력하십시오',
      zh: '请输入标签的有效标签',
      it: 'Si prega di inserire un tag valido per il tag',
      pt: 'Por favor, insira um tag válido para o seu tag',
      hi: 'कृपया अपने टैग का एक वैध टैग दर्ज करें',
      ar: 'يرجى إدخال علامة تعريف صالحة لوسمك',
      ru: 'Пожалуйста, введите допустимый тег для вашего тега',
      tr: 'Lütfen etiketiniz için geçerli bir etiket girin',
      pl: 'Proszę podać prawidłowy klucz tagu.',
      id: 'Silakan masukkan key yang valid untuk tag Anda',
      vi: 'Vui lòng nhập một tag hợp lệ cho tag của bạn',
    }),

    requiredErrorName: t({
      en: 'Please enter a key for your tag',
      'en-GB': 'Please enter a key for your tag',
      fr: 'Veuillez saisir une clé pour votre tag',
      es: 'Por favor, ingrese una clave para su tag',
      de: 'Bitte geben Sie einen Schlüssel für Ihr Tag ein',
      ja: 'タグのキーを入力してください',
      ko: '태그의 키를 입력하십시오',
      zh: '请为您的标签输入密钥',
      it: 'Si prega di inserire una chiave per il tag',
      pt: 'Por favor, insira uma chave para o seu tag',
      hi: 'कृपया अपने टैग का कुंजी दर्ज करें',
      ar: 'يرجى إدخال مفتاح لوسمك',
      ru: 'Пожалуйста, введите ключ для вашего тега',
      tr: 'Lütfen etiketiniz için bir anahtar girin',
      pl: 'Proszę podać klucz tagu.',
      id: 'Silakan masukkan key untuk tag Anda',
      vi: 'Vui lòng nhập key cho tag của bạn',
    }),

    invalidTypeErrorName: t({
      en: 'Please enter a valid tag for your tag',
      'en-GB': 'Please enter a valid tag for your tag',
      fr: 'Veuillez saisir un tag valide pour votre tag',
      es: 'Por favor, ingrese un tag válido para su tag',
      de: 'Bitte geben Sie einen gültigen Tag für Ihr Tag ein',
      ja: 'タグの有効なタグを入力してください',
      ko: '태그의 유효한 태그를 입력하십시오',
      zh: '请输入标签的有效标签',
      it: 'Si prega di inserire un tag valido per il tag',
      pt: 'Por favor, insira um tag válido para o seu tag',
      hi: 'कृपया अपने टैग का एक वैध टैग दर्ज करें',
      ar: 'يرجى إدخال علامة تعريف صالحة لوسمك',
      ru: 'Пожалуйста, введите допустимый тег для вашего тега',
      tr: 'Lütfen etiketiniz için geçerli bir etiket girin',
      pl: 'Proszę podać prawidłowy klucz tagu.',
      id: 'Silakan masukkan key yang valid untuk tag Anda',
      vi: 'Vui lòng nhập một tag hợp lệ cho tag của bạn',
    }),

    invalidTypeErrorDescription: t({
      en: 'Please enter a valid description for your tag',
      'en-GB': 'Please enter a valid description for your tag',
      fr: 'Veuillez saisir une description valide pour votre tag',
      es: 'Por favor, ingrese una descripción válida para su tag',
      de: 'Bitte geben Sie eine gültige Beschreibung für Ihr Tag ein',
      ja: 'タグの説明を入力してください',
      ko: '태그의 설명을 입력하십시오',
      zh: '请输入标签的有效描述',
      it: 'Si prega di inserire una descrizione valida per il tag',
      pt: 'Por favor, insira uma descrição válida para o seu tag',
      hi: 'कृपया अपने टैग का एक वैध वर्णन दर्ज करें',
      ar: 'يرجى إدخال وصف صالح لوسمك',
      ru: 'Пожалуйста, введите допустимое описание для вашего тега',
      tr: 'Lütfen etiketiniz için geçerli bir açıklama girin',
      pl: 'Proszę podać prawidłowy opis tagu.',
      id: 'Silakan masukkan deskripsi yang valid untuk tag Anda',
      vi: 'Vui lòng nhập một description hợp lệ cho tag của bạn',
    }),

    requiredErrorDescription: t({
      en: 'Please enter a description for your tag',
      'en-GB': 'Please enter a description for your tag',
      fr: 'Veuillez saisir une description pour votre tag',
      es: 'Por favor, ingrese una descripción para su etiqueta',
      de: 'Bitte geben Sie eine Beschreibung für Ihr Tag ein',
      ja: 'タグの説明を入力してください',
      ko: '태그의 설명을 입력하십시오',
      zh: '请输入标签的有效描述',
      it: 'Si prega di inserire una descrizione valida per il tag',
      pt: 'Por favor, insira uma descrição válida para o seu tag',
      hi: 'कृपया अपने टैग का एक वैध वर्णन दर्ज करें',
      ar: 'يرجى إدخال وصف صالح لوسمك',
      ru: 'Пожалуйста, введите допустимое описание для вашего тега',
      tr: 'Lütfen etiketiniz için bir açıklama girin',
      pl: 'Proszę podać opis tagu.',
      id: 'Silakan masukkan deskripsi untuk tag Anda',
      vi: 'Vui lòng nhập description cho tag của bạn',
    }),

    requiredErrorInstructions: t({
      en: 'Please enter instructions for your tag',
      'en-GB': 'Please enter instructions for your tag',
      fr: 'Veuillez saisir des instructions pour votre tag',
      es: 'Por favor, ingrese instrucciones para su etiqueta',
      de: 'Bitte geben Sie Anweisungen für Ihr Tag ein',
      ja: 'タグの指示を入力してください',
      ko: '태그의 지침을 입력하십시오',
      zh: '请输入标签的有效描述',
      it: 'Si prega di inserire istruzioni valida per il tag',
      pt: 'Por favor, insira instruções válidas para o seu tag',
      hi: 'कृपया अपने टैग का एक वैध वर्णन दर्ज करें',
      ar: 'يرجى إدخال وصف صالح لوسمك',
      ru: 'Пожалуйста, введите допустимое описание для вашего тега',
      tr: 'Lütfen etiketiniz için talimatlar girin',
      pl: 'Proszę podać instrukcje dla tagu.',
      id: 'Silakan masukkan instruksi untuk tag Anda',
      vi: 'Vui lòng nhập instructions cho tag của bạn',
    }),

    invalidTypeErrorInstructions: t({
      en: 'Please enter a valid instructions for your tag',
      'en-GB': 'Please enter a valid instructions for your tag',
      fr: 'Veuillez saisir des instructions valides pour votre tag',
      es: 'Por favor, ingrese instrucciones válidas para su etiqueta',
      de: 'Bitte geben Sie eine gültige Anweisungen für Ihr Tag ein',
      ja: 'タグの指示を入力してください',
      ko: '태그의 지침을 입력하십시오',
      zh: '请输入标签的有效描述',
      it: 'Si prega di inserire istruzioni valida per il tag',
      pt: 'Por favor, insira instruções válidas para o seu tag',
      hi: 'कृपया अपने टैग का एक वैध वर्णन दर्ज करें',
      ar: 'يرجى إدخال وصف صالح لوسمك',
      ru: 'Пожалуйста, введите допустимое описание для вашего тега',
      tr: 'Lütfen etiketiniz için geçerli talimatlar girin',
      pl: 'Proszę podać prawidłowe instrukcje dla tagu.',
      id: 'Silakan masukkan instruksi yang valid untuk tag Anda',
      vi: 'Vui lòng nhập instructions hợp lệ cho tag của bạn',
    }),
  },
  title: 'Tag form schema',
  description:
    'Validation messages and schema configuration used in the dashboard tag form. Ensures correct input for key, description, and instructions fields when creating or editing a tag.',
  tags: ['form validation', 'tag management', 'dashboard'],
} satisfies Dictionary;

export default content;
