/**
 * Returns the dynamic dictionaries generated by Intlayer (per-locale lazy
 * loaders).
 *
 * `@intlayer/dictionaries-entry/dynamic` is meant to be aliased by the bundler
 * configuration to the generated `.intlayer/main/dynamic_dictionaries` entry.
 * Outside a bundler (Node) this stub reads the entry itself.
 */

import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { build, system } from '@intlayer/config/built';
import { configESMxCJSRequire } from '@intlayer/config/utils';
import type { IntlayerConfig } from '@intlayer/types/config';
import type { Dictionary } from '@intlayer/types/dictionary';
import type {
  DictionaryKeys,
  StrictModeLocaleMap,
} from '@intlayer/types/module_augmentation';

export type DynamicDictionaries = Record<
  DictionaryKeys,
  StrictModeLocaleMap<() => Promise<Dictionary>>
>;

type GetDynamicDictionaries = (
  configuration?: Pick<IntlayerConfig, 'system' | 'build'>
) => DynamicDictionaries;

export const getDynamicDictionaries: GetDynamicDictionaries = (
  configuration: Pick<IntlayerConfig, 'system' | 'build'> = { system, build }
) => {
  const { system, build } = configuration;

  // Always use cjs for dictionaries entry as it uses require
  const dictionariesPath = join(system.mainDir, `dynamic_dictionaries.cjs`);
  let dictionaries: DynamicDictionaries = {};

  if (existsSync(dictionariesPath)) {
    dictionaries = (build.require ?? configESMxCJSRequire)(dictionariesPath);
  }

  return dictionaries;
};
