/**
 * Returns the fetch dictionaries generated by Intlayer (per-locale JSON files
 * fetched at runtime).
 *
 * `@intlayer/dictionaries-entry/fetch` is meant to be aliased by the bundler
 * configuration to the generated `.intlayer/main/fetch_dictionaries` entry.
 * Outside a bundler (Node) this stub reads the JSON files itself.
 */

import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { basename, extname, join } from 'node:path';
import { system } from '@intlayer/config/built';
import type { IntlayerConfig } from '@intlayer/types/config';
import type { Dictionary } from '@intlayer/types/dictionary';
import type {
  DictionaryKeys,
  StrictModeLocaleMap,
} from '@intlayer/types/module_augmentation';

export type FetchDictionaries = Record<
  DictionaryKeys,
  StrictModeLocaleMap<Dictionary>
>;

type GetFetchDictionaries = (
  configuration?: Pick<IntlayerConfig, 'system'>
) => FetchDictionaries;

export const getFetchDictionaries: GetFetchDictionaries = (
  configuration: Pick<IntlayerConfig, 'system'> = { system }
) => {
  const { system } = configuration;
  const { fetchDictionariesDir } = system;

  const dictionaries: Record<string, StrictModeLocaleMap<Dictionary>> = {};

  if (existsSync(fetchDictionariesDir)) {
    // Read JSON files directly to avoid require.cache memory leak
    const files = readdirSync(fetchDictionariesDir).filter((file) =>
      file.endsWith('.json')
    );

    for (const file of files) {
      const key = basename(file, extname(file));
      const content = readFileSync(join(fetchDictionariesDir, file), 'utf-8');
      dictionaries[key] = JSON.parse(content);
    }
  }

  return dictionaries as FetchDictionaries;
};
