/**
 * Returns the merged dictionaries generated by Intlayer.
 *
 * `@intlayer/dictionaries-entry` is meant to be aliased by the
 * bundler configuration (webpack, Vite, Turbopack, esbuild, Metro, …) to the
 * generated `.intlayer/main/dictionaries` entry, so the app hot reloads on any
 * dictionary change. Outside a bundler (Node) this stub reads the entry itself.
 */

import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { build, system } from '@intlayer/config/built';
import { configESMxCJSRequire } from '@intlayer/config/utils';
import type { IntlayerConfig } from '@intlayer/types/config';
import type { DictionaryRegistry } from '@intlayer/types/module_augmentation';

type GetDictionaries = (
  configuration?: Pick<IntlayerConfig, 'system' | 'build'>
) => DictionaryRegistry;

export const getDictionaries: GetDictionaries = (
  configuration: Pick<IntlayerConfig, 'system' | 'build'> = { system, build }
) => {
  const { system, build } = configuration;

  // Always use cjs for dictionaries entry as it uses require
  const dictionariesPath = join(system.mainDir, `dictionaries.cjs`);

  let dictionaries = {};
  if (existsSync(dictionariesPath)) {
    dictionaries = (build.require ?? configESMxCJSRequire)(dictionariesPath);
  }

  return (dictionaries ?? {}) as DictionaryRegistry;
};
