/**
 * Returns the unmerged dictionaries generated by Intlayer (one array of
 * declarations per key, before merging).
 *
 * `@intlayer/dictionaries-entry/unmerged` is meant to be aliased by the bundler
 * configuration to the generated `.intlayer/main/unmerged_dictionaries` entry.
 * Outside a bundler (Node) this stub reads the JSON files itself.
 */

import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { basename, extname, join } from 'node:path';
import { build, system } from '@intlayer/config/built';
import type { IntlayerConfig } from '@intlayer/types/config';
import type { Dictionary } from '@intlayer/types/dictionary';
import type { DictionaryKeys } from '@intlayer/types/module_augmentation';

export type UnmergedDictionaries = Record<DictionaryKeys, Dictionary[]>;

type GetUnmergedDictionaries = (
  configuration?: Pick<IntlayerConfig, 'system' | 'build'>
) => UnmergedDictionaries;

export const getUnmergedDictionaries: GetUnmergedDictionaries = (
  configuration: Pick<IntlayerConfig, 'system' | 'build'> = { system, build }
) => {
  const { system } = configuration;
  const { unmergedDictionariesDir } = system;

  const dictionaries: Record<string, Dictionary[]> = {};

  if (existsSync(unmergedDictionariesDir)) {
    // Read JSON files directly to avoid require.cache memory leak
    const files = readdirSync(unmergedDictionariesDir).filter((file) =>
      file.endsWith('.json')
    );

    for (const file of files) {
      const key = basename(file, extname(file));
      const content = readFileSync(
        join(unmergedDictionariesDir, file),
        'utf-8'
      );
      dictionaries[key] = JSON.parse(content);
    }
  }

  return dictionaries as UnmergedDictionaries;
};
