import { type Dictionary, t } from 'intlayer';

const dashboardLocalizationScannerContent = {
  key: 'dashboard-localization-scanner',
  content: {
    noApplicationUrl: t({
      en: 'No application URL is configured for this project. Set it in the project settings to enable scanning.',
      'en-GB':
        'No application URL is configured for this project. Set it in the project settings to enable scanning.',
      fr: "Aucune URL d'application n'est configurée pour ce projet. Définissez-la dans les paramètres du projet pour activer le scan.",
      es: 'No hay URL de aplicación configurada para este proyecto. Configúrala en los ajustes del proyecto para activar el escáner.',
      de: 'Für dieses Projekt ist keine Anwendungs-URL konfiguriert. Legen Sie sie in den Projekteinstellungen fest, um das Scannen zu aktivieren.',
      ja: 'このプロジェクトにはアプリケーションURLが設定されていません。スキャンを有効にするには、プロジェクト設定で設定してください。',
      ko: '이 프로젝트에 애플리케이션 URL이 구성되어 있지 않습니다. 스캔을 활성화하려면 프로젝트 설정에서 설정하세요.',
      zh: '此项目未配置应用程序 URL。请在项目设置中设置它以启用扫描。',
      it: "Nessun URL dell'applicazione configurato per questo progetto. Impostalo nelle impostazioni del progetto per abilitare la scansione.",
      pt: 'Nenhuma URL de aplicação configurada para este projeto. Defina-a nas configurações do projeto para ativar a varredura.',
      hi: 'इस प्रोजेक्ट के लिए कोई एप्लिकेशन URL कॉन्फ़िगर नहीं है। स्कैनिंग सक्षम करने के लिए इसे प्रोजेक्ट सेटिंग में सेट करें।',
      ar: 'لم يتم تكوين عنوان URL للتطبيق لهذا المشروع. قم بتعيينه في إعدادات المشروع لتمكين الفحص.',
      ru: 'Для этого проекта не настроен URL приложения. Установите его в настройках проекта, чтобы включить сканирование.',
      tr: "Bu proje için uygulama URL'si yapılandırılmamış. Taramayı etkinleştirmek için proje ayarlarında ayarlayın.",
      pl: 'Dla tego projektu nie skonfigurowano adresu URL aplikacji. Ustaw go w ustawieniach projektu, aby włączyć skanowanie.',
      id: 'Tidak ada URL aplikasi yang dikonfigurasi untuk proyek ini. Atur di pengaturan proyek untuk mengaktifkan pemindaian.',
      vi: 'Không có URL ứng dụng nào được cấu hình cho dự án này. Đặt nó trong cài đặt dự án để bật quét.',
      uk: 'Для цього проєкту не налаштовано URL додатка. Встановіть його в налаштуваннях проєкту, щоб увімкнути сканування.',
    }),
    goToProjectSettings: t({
      en: 'Go to project settings',
      'en-GB': 'Go to project settings',
      fr: 'Aller aux paramètres du projet',
      es: 'Ir a la configuración del proyecto',
      de: 'Zu den Projekteinstellungen gehen',
      ja: 'プロジェクト設定に移動',
      ko: '프로젝트 설정으로 이동',
      zh: '前往项目设置',
      it: 'Vai alle impostazioni del progetto',
      pt: 'Ir para as configurações do projeto',
      hi: 'प्रोजेक्ट सेटिंग पर जाएं',
      ar: 'الذهاب إلى إعدادات المشروع',
      ru: 'Перейти к настройкам проекта',
      tr: 'Proje ayarlarına git',
      pl: 'Przejdź do ustawień projektu',
      id: 'Buka pengaturan proyek',
      vi: 'Đi tới cài đặt dự án',
      uk: 'Перейти до налаштувань проєкту',
    }),
    searchAriaLabel: t({
      en: 'Search URLs',
      'en-GB': 'Search URLs',
      fr: 'Rechercher des URLs',
      es: 'Buscar URLs',
      de: 'URLs suchen',
      ja: 'URLを検索',
      ko: 'URL 검색',
      zh: '搜索 URL',
      it: 'Cerca URL',
      pt: 'Pesquisar URLs',
      hi: 'URL खोजें',
      ar: 'البحث عن عناوين URL',
      ru: 'Поиск URL',
      tr: "URL'leri ara",
      pl: 'Szukaj URL',
      id: 'Cari URL',
      vi: 'Tìm kiếm URL',
      uk: 'Пошук URL',
    }),
    searchPlaceholder: t({
      en: 'Filter pages…',
      'en-GB': 'Filter pages…',
      fr: 'Filtrer les pages…',
      es: 'Filtrar páginas…',
      de: 'Seiten filtern…',
      ja: 'ページをフィルター…',
      ko: '페이지 필터링…',
      zh: '筛选页面…',
      it: 'Filtra pagine…',
      pt: 'Filtrar páginas…',
      hi: 'पेज फ़िल्टर करें…',
      ar: 'تصفية الصفحات…',
      ru: 'Фильтровать страницы…',
      tr: 'Sayfaları filtrele…',
      pl: 'Filtruj strony…',
      id: 'Filter halaman…',
      vi: 'Lọc trang…',
      uk: 'Фільтрувати сторінки…',
    }),
    loadingUrls: t({
      en: 'Discovering pages from sitemap…',
      'en-GB': 'Discovering pages from sitemap…',
      fr: 'Découverte des pages depuis le sitemap…',
      es: 'Descubriendo páginas desde el sitemap…',
      de: 'Seiten aus Sitemap werden ermittelt…',
      ja: 'サイトマップからページを検出中…',
      ko: '사이트맵에서 페이지 검색 중…',
      zh: '正在从站点地图中发现页面…',
      it: 'Ricerca delle pagine dalla sitemap…',
      pt: 'Descobrindo páginas do sitemap…',
      hi: 'साइटमैप से पेज खोजे जा रहे हैं…',
      ar: 'جارٍ اكتشاف الصفحات من خريطة الموقع…',
      ru: 'Поиск страниц из карты сайта…',
      tr: 'Site haritasından sayfalar keşfediliyor…',
      pl: 'Odkrywanie stron z mapy witryny…',
      id: 'Menemukan halaman dari sitemap…',
      vi: 'Đang tìm trang từ sitemap…',
      uk: 'Пошук сторінок із карти сайту…',
    }),
    noUrls: t({
      en: 'No pages found.',
      'en-GB': 'No pages found.',
      fr: 'Aucune page trouvée.',
      es: 'No se encontraron páginas.',
      de: 'Keine Seiten gefunden.',
      ja: 'ページが見つかりません。',
      ko: '페이지를 찾을 수 없습니다.',
      zh: '未找到页面。',
      it: 'Nessuna pagina trovata.',
      pt: 'Nenhuma página encontrada.',
      hi: 'कोई पेज नहीं मिला।',
      ar: 'لم يتم العثور على صفحات.',
      ru: 'Страницы не найдены.',
      tr: 'Sayfa bulunamadı.',
      pl: 'Nie znaleziono stron.',
      id: 'Tidak ada halaman ditemukan.',
      vi: 'Không tìm thấy trang nào.',
      uk: 'Сторінок не знайдено.',
    }),
    refreshLabel: t({
      en: 'Refresh',
      'en-GB': 'Refresh',
      fr: 'Actualiser',
      es: 'Actualizar',
      de: 'Aktualisieren',
      ja: '更新',
      ko: '새로고침',
      zh: '刷新',
      it: 'Aggiorna',
      pt: 'Atualizar',
      hi: 'रिफ्रेश करें',
      ar: 'تحديث',
      ru: 'Обновить',
      tr: 'Yenile',
      pl: 'Odśwież',
      id: 'Muat ulang',
      vi: 'Làm mới',
      uk: 'Оновити',
    }),
    selectUrlPrompt: t({
      en: 'Select a page from the list to scan it.',
      'en-GB': 'Select a page from the list to scan it.',
      fr: 'Sélectionnez une page dans la liste pour la scanner.',
      es: 'Selecciona una página de la lista para escanearla.',
      de: 'Wählen Sie eine Seite aus der Liste aus, um sie zu scannen.',
      ja: 'リストからページを選択してスキャンします。',
      ko: '목록에서 페이지를 선택하여 스캔하세요.',
      zh: '从列表中选择一个页面进行扫描。',
      it: "Seleziona una pagina dall'elenco per scansionarla.",
      pt: 'Selecione uma página da lista para escaneá-la.',
      hi: 'स्कैन करने के लिए सूची से एक पेज चुनें।',
      ar: 'حدد صفحة من القائمة لفحصها.',
      ru: 'Выберите страницу из списка для сканирования.',
      tr: 'Taramak için listeden bir sayfa seçin.',
      pl: 'Wybierz stronę z listy, aby ją zeskanować.',
      id: 'Pilih halaman dari daftar untuk memindainya.',
      vi: 'Chọn một trang từ danh sách để quét.',
      uk: 'Виберіть сторінку зі списку для сканування.',
    }),
  },
  title: 'Dashboard localization scanner',
  description:
    'UI strings for the dashboard-embedded localization scanner panel.',
  tags: ['scanner', 'dashboard', 'i18n'],
} satisfies Dictionary;

export default dashboardLocalizationScannerContent;
