import { type Dictionary, t } from 'intlayer';

const addPasskeyModalContent = {
  key: 'add-passkey-modal',
  content: {
    modalTitle: t({
      en: 'Add New Passkey',
      fr: 'Ajouter une nouvelle clé',
      es: 'Agregar nueva llave',
      mi: 'Tāpiri Kīuru Hōu',
      de: 'Neuen Passkey hinzufügen',
      it: 'Aggiungi nuova passkey',
      pt: 'Adicionar nova chave de acesso',
      zh: '添加新的通行密钥',
      ja: '新しいパスキーを追加',
      ko: '새 패스키 추가',
      ru: 'Добавить новый пропуск-ключ',
      nl: 'Nieuwe passkey toevoegen',
      tr: 'Yeni Geçiş Anahtarı Ekle',
      pl: 'Dodaj nowy klucz dostępu',
      hi: 'नई पासकी जोड़ें',
      ar: 'أضف مفتاح مرور جديد',
      'en-GB': 'Add New Passkey',
      id: 'Tambahkan Passkey Baru',
      vi: 'Thêm Passkey mới',
    }),
    modalDescription: t({
      en: 'Create a new passkey for secure, passwordless authentication.',
      fr: 'Créez une nouvelle clé de sécurité pour une authentification sécurisée sans mot de passe.',
      es: 'Cree una nueva llave de acceso para una autenticación segura sin contraseña.',
      mi: 'Hangaia he kīuru hōu mō te takiuru haumaru, kāore e hiahiatia he kupuhipa.',
      de: 'Erstellen Sie einen neuen Passkey für eine sichere, passwortlose Authentifizierung.',
      it: "Crea una nuova passkey per un'autenticazione sicura e senza password.",
      pt: 'Crie uma nova chave de acesso para autenticação segura sem senha.',
      zh: '创建新的通行密钥，实现安全、无密码的身份验证。',
      ja: '安全でパスワード不要の認証のために新しいパスキーを作成します。',
      ko: '안전하고 비밀번호 없는 인증을 위해 새 패스키를 만드세요.',
      ru: 'Создайте новый пропуск-ключ для безопасной, входа без пароля.',
      nl: 'Maak een nieuwe passkey voor veilige, wachtwoordloze authenticatie.',
      tr: 'Güvenli, şifresiz kimlik doğrulama için yeni bir geçiş anahtarı oluşturun.',
      pl: 'Utwórz nowy klucz dostępu do bezpiecznej, bezhasłowej autoryzacji.',
      hi: 'सुरक्षित, पासवर्डरहित प्रमाणीकरण के लिए नई पासकी बनाएं।',
      ar: 'أنشئ مفتاح مرور جديد لمصادقة آمنة وخالية من كلمات المرور.',
      'en-GB': 'Create a new passkey for secure, passwordless authentication.',
      id: 'Buat passkey baru untuk autentikasi aman tanpa kata sandi.',
      vi: 'Tạo passkey mới cho xác thực an toàn không cần mật khẩu.',
    }),
    nameInput: {
      label: t({
        en: 'Name',
        fr: 'Nom',
        es: 'Nombre',
        mi: 'Ingoa',
        de: 'Name',
        it: 'Nome',
        pt: 'Nome',
        zh: '名称',
        ja: '名前',
        ko: '이름',
        ru: 'Имя',
        nl: 'Naam',
        tr: 'Ad',
        pl: 'Nazwa',
        hi: 'नाम',
        ar: 'الاسم',
        'en-GB': 'Name',
        id: 'Nama',
        vi: 'Tên',
      }),
      placeholder: t({
        en: 'Enter passkey name',
        fr: 'Entrez le nom de la clé',
        es: 'Ingrese el nombre de la llave',
        mi: 'Tāuruhia te ingoa o te kīuru',
        de: 'Passkey-Namen eingeben',
        it: 'Inserisci il nome della passkey',
        pt: 'Digite o nome da chave de acesso',
        zh: '输入通行密钥名称',
        ja: 'パスキー名を入力',
        ko: '패스키 이름 입력',
        ru: 'Введите имя пропуск-ключа',
        nl: 'Voer passkey-naam in',
        tr: 'Geçiş anahtarı adını girin',
        pl: 'Wprowadź nazwę klucza dostępu',
        hi: 'पासकी का नाम दर्ज करें',
        ar: 'أدخل اسم مفتاح المرور',
        'en-GB': 'Enter passkey name',
        id: 'Masukkan nama passkey',
        vi: 'Nhập tên passkey',
      }),
    },
    submitButton: {
      text: t({
        en: 'Add Passkey',
        fr: 'Ajouter',
        es: 'Agregar',
        mi: 'Tāpiri Kīuru',
        de: 'Hinzufügen',
        it: 'Aggiungi',
        pt: 'Adicionar',
        zh: '添加',
        ja: '追加',
        ko: '추가',
        ru: 'Добавить',
        nl: 'Toevoegen',
        tr: 'Ekle',
        pl: 'Dodaj',
        hi: 'जोड़ें',
        ar: 'إضافة',
        'en-GB': 'Add Passkey',
        id: 'Tambahkan',
        vi: 'Thêm',
      }),
      ariaLabel: t({
        en: 'Add new passkey',
        fr: 'Ajouter une nouvelle clé',
        es: 'Agregar nueva llave',
        mi: 'Täpiri kīuru hōu',
        de: 'Neuen Passkey hinzufügen',
        it: 'Aggiungi nuova passkey',
        pt: 'Adicionar nova chave de acesso',
        zh: '添加新的通行密钥',
        ja: '新しいパスキーを追加',
        ko: '새 패스키 추가',
        ru: 'Добавить новый пропуск-ключ',
        nl: 'Nieuwe passkey toevoegen',
        tr: 'Yeni geçiş anahtarı ekle',
        pl: 'Dodaj nowy klucz dostępu',
        hi: 'नई पासकी जोड़ें',
        ar: 'أضف مفتاح مرور جديد',
        'en-GB': 'Add New Passkey',
        id: 'Tambahkan Passkey Baru',
        vi: 'Thêm Passkey mới',
      }),
    },
    cancelButton: {
      text: t({
        en: 'Cancel',
        fr: 'Annuler',
        es: 'Cancelar',
        mi: 'Whakakore',
        de: 'Abbrechen',
        it: 'Annulla',
        pt: 'Cancelar',
        zh: '取消',
        ja: 'キャンセル',
        ko: '취소',
        ru: 'Отмена',
        nl: 'Annuleren',
        tr: 'İptal',
        pl: 'Anuluj',
        hi: 'रद्द करें',
        ar: 'إلغاء',
        'en-GB': 'Cancel',
        id: 'Batal',
        vi: 'Hủy',
      }),
      ariaLabel: t({
        en: 'Cancel adding passkey',
        fr: "Annuler l'ajout de la clé",
        es: 'Cancelar agregar llave',
        mi: 'Whakakore i te tāpiri kīuru',
        de: 'Hinzufügen des Passkeys abbrechen',
        it: 'Annulla aggiunta passkey',
        pt: 'Cancelar adição de chave de acesso',
        zh: '取消添加通行密钥',
        ja: 'パスキー追加をキャンセル',
        ko: '패스키 추가 취소',
        ru: 'Отменить добавление пропуск-ключа',
        nl: 'Toevoegen van passkey annuleren',
        tr: 'Geçiş anahtarı eklemeyi iptal et',
        pl: 'Anuluj dodawanie klucza dostępu',
        hi: 'पासकी जोड़ना रद्द करें',
        ar: 'إلغاء إضافة مفتاح المرور',
        'en-GB': 'Cancel adding passkey',
        id: 'Batal menambah passkey',
        vi: 'Hủy thêm passkey',
      }),
    },
  },
} satisfies Dictionary;

export default addPasskeyModalContent;
