import { type Dictionary, t } from 'intlayer';

const repositoryComparisonContent = {
  key: 'repository-comparison',
  content: {
    commits: t({
      en: 'commits',
      'en-GB': 'commits',
      fr: 'commits',
      es: 'commits',
      de: 'Commits',
      it: 'commit',
      pt: 'commits',
      ru: 'коммитов',
      ja: 'コミット',
      ko: '커밋',
      zh: '次提交',
      ar: 'التزامات',
      hi: 'कमिट',
      tr: 'commit',
      pl: 'commitów',
      id: 'commit',
      vi: 'commit',
      uk: 'комітів',
    }),
    downloads: t({
      en: 'downloads',
      'en-GB': 'downloads',
      fr: 'téléchargements',
      es: 'descargas',
      de: 'Downloads',
      it: 'download',
      pt: 'downloads',
      ru: 'загрузок',
      ja: 'ダウンロード',
      ko: '다운로드',
      zh: '次下载',
      ar: 'تنزيلات',
      hi: 'डाउनलोड',
      tr: 'indirme',
      pl: 'pobrań',
      id: 'unduhan',
      vi: 'lượt tải',
      uk: 'завантажень',
    }),
    unavailable: t({
      en: 'Unavailable',
      'en-GB': 'Unavailable',
      fr: 'Indisponible',
      es: 'No disponible',
      de: 'Nicht verfügbar',
      it: 'Non disponibile',
      pt: 'Indisponível',
      ru: 'Недоступно',
      ja: '取得できません',
      ko: '사용할 수 없음',
      zh: '不可用',
      ar: 'غير متاح',
      hi: 'उपलब्ध नहीं',
      tr: 'Kullanılamıyor',
      pl: 'Niedostępne',
      id: 'Tidak tersedia',
      vi: 'Không khả dụng',
      uk: 'Недоступно',
    }),
    commitsSource: t({
      en: 'Commits on the default branch, source: GitHub API.',
      'en-GB': 'Commits on the default branch, source: GitHub API.',
      fr: 'Commits sur la branche par défaut, source : API GitHub.',
      es: 'Commits en la rama por defecto, fuente: API de GitHub.',
      de: 'Commits auf dem Standard-Branch, Quelle: GitHub API.',
      it: 'Commit sul branch predefinito, fonte: API GitHub.',
      pt: 'Commits no branch padrão, fonte: API do GitHub.',
      ru: 'Коммиты в основной ветке, источник: GitHub API.',
      ja: 'デフォルトブランチのコミット数、出典: GitHub API。',
      ko: '기본 브랜치의 커밋 수, 출처: GitHub API.',
      zh: '默认分支上的提交数，来源：GitHub API。',
      ar: 'الالتزامات على الفرع الافتراضي، المصدر: GitHub API.',
      hi: 'डिफ़ॉल्ट ब्रांच पर कमिट, स्रोत: GitHub API।',
      tr: 'Varsayılan daldaki commit sayısı, kaynak: GitHub API.',
      pl: 'Commity na domyślnej gałęzi, źródło: GitHub API.',
      id: 'Commit pada branch default, sumber: GitHub API.',
      vi: 'Số commit trên nhánh mặc định, nguồn: GitHub API.',
      uk: 'Коміти в основній гілці, джерело: GitHub API.',
    }),
    downloadsSource: t({
      en: 'Source: npm registry downloads API.',
      'en-GB': 'Source: npm registry downloads API.',
      fr: 'Source : API de téléchargements du registre npm.',
      es: 'Fuente: API de descargas del registro npm.',
      de: 'Quelle: Download-API der npm-Registry.',
      it: 'Fonte: API dei download del registro npm.',
      pt: 'Fonte: API de downloads do registro npm.',
      ru: 'Источник: API загрузок реестра npm.',
      ja: '出典: npm レジストリのダウンロード API。',
      ko: '출처: npm 레지스트리 다운로드 API.',
      zh: '来源：npm 注册表下载 API。',
      ar: 'المصدر: واجهة تنزيلات سجل npm.',
      hi: 'स्रोत: npm रजिस्ट्री डाउनलोड API।',
      tr: 'Kaynak: npm kayıt defteri indirme API’si.',
      pl: 'Źródło: API pobrań rejestru npm.',
      id: 'Sumber: API unduhan registri npm.',
      vi: 'Nguồn: API lượt tải của npm registry.',
      uk: 'Джерело: API завантажень реєстру npm.',
    }),
    periods: {
      'last-week': t({
        en: 'Last week',
        'en-GB': 'Last week',
        fr: 'Dernière semaine',
        es: 'Última semana',
        de: 'Letzte Woche',
        it: 'Ultima settimana',
        pt: 'Última semana',
        ru: 'Неделя',
        ja: '過去1週間',
        ko: '지난 1주',
        zh: '最近一周',
        ar: 'آخر أسبوع',
        hi: 'पिछला सप्ताह',
        tr: 'Son hafta',
        pl: 'Ostatni tydzień',
        id: 'Minggu terakhir',
        vi: 'Tuần qua',
        uk: 'Тиждень',
      }),
      'last-month': t({
        en: 'Last month',
        'en-GB': 'Last month',
        fr: 'Dernier mois',
        es: 'Último mes',
        de: 'Letzter Monat',
        it: 'Ultimo mese',
        pt: 'Último mês',
        ru: 'Месяц',
        ja: '過去1か月',
        ko: '지난 1개월',
        zh: '最近一个月',
        ar: 'آخر شهر',
        hi: 'पिछला महीना',
        tr: 'Son ay',
        pl: 'Ostatni miesiąc',
        id: 'Bulan terakhir',
        vi: 'Tháng qua',
        uk: 'Місяць',
      }),
      'last-6-months': t({
        en: 'Last 6 months',
        'en-GB': 'Last 6 months',
        fr: '6 derniers mois',
        es: 'Últimos 6 meses',
        de: 'Letzte 6 Monate',
        it: 'Ultimi 6 mesi',
        pt: 'Últimos 6 meses',
        ru: '6 месяцев',
        ja: '過去6か月',
        ko: '지난 6개월',
        zh: '最近 6 个月',
        ar: 'آخر 6 أشهر',
        hi: 'पिछले 6 महीने',
        tr: 'Son 6 ay',
        pl: 'Ostatnie 6 miesięcy',
        id: '6 bulan terakhir',
        vi: '6 tháng qua',
        uk: '6 місяців',
      }),
      'last-year': t({
        en: 'Last year',
        'en-GB': 'Last year',
        fr: 'Dernière année',
        es: 'Último año',
        de: 'Letztes Jahr',
        it: 'Ultimo anno',
        pt: 'Último ano',
        ru: 'Год',
        ja: '過去1年',
        ko: '지난 1년',
        zh: '最近一年',
        ar: 'آخر سنة',
        hi: 'पिछला वर्ष',
        tr: 'Son yıl',
        pl: 'Ostatni rok',
        id: 'Tahun terakhir',
        vi: 'Năm qua',
        uk: 'Рік',
      }),
    },
  },
} satisfies Dictionary;

export default repositoryComparisonContent;
