import { type Dictionary, t } from 'intlayer';

const repositoryComparisonContent = {
  key: 'repository-comparison',
  content: {
    commits: t({
      en: 'commits',
      'en-GB': 'commits',
      fr: 'commits',
      es: 'commits',
      de: 'Commits',
      it: 'commit',
      pt: 'commits',
      ru: 'коммитов',
      ja: 'コミット',
      ko: '커밋',
      zh: '次提交',
      ar: 'التزامات',
      hi: 'कमिट',
      tr: 'commit',
      pl: 'commitów',
      id: 'commit',
      vi: 'commit',
      uk: 'комітів',
    }),
    downloads: t({
      en: 'downloads',
      'en-GB': 'downloads',
      fr: 'téléchargements',
      es: 'descargas',
      de: 'Downloads',
      it: 'download',
      pt: 'downloads',
      ru: 'загрузок',
      ja: 'ダウンロード',
      ko: '다운로드',
      zh: '次下载',
      ar: 'تنزيلات',
      hi: 'डाउनलोड',
      tr: 'indirme',
      pl: 'pobrań',
      id: 'unduhan',
      vi: 'lượt tải',
      uk: 'завантажень',
    }),
    unavailable: t({
      en: 'Unavailable',
      'en-GB': 'Unavailable',
      fr: 'Indisponible',
      es: 'No disponible',
      de: 'Nicht verfügbar',
      it: 'Non disponibile',
      pt: 'Indisponível',
      ru: 'Недоступно',
      ja: '取得できません',
      ko: '사용할 수 없음',
      zh: '不可用',
      ar: 'غير متاح',
      hi: 'उपलब्ध नहीं',
      tr: 'Kullanılamıyor',
      pl: 'Niedostępne',
      id: 'Tidak tersedia',
      vi: 'Không khả dụng',
      uk: 'Недоступно',
    }),
    commitsSource: t({
      en: 'Commits on the default branch, source: GitHub API.',
      'en-GB': 'Commits on the default branch, source: GitHub API.',
      fr: 'Commits sur la branche par défaut, source : API GitHub.',
      es: 'Commits en la rama por defecto, fuente: API de GitHub.',
      de: 'Commits auf dem Standard-Branch, Quelle: GitHub API.',
      it: 'Commit sul branch predefinito, fonte: API GitHub.',
      pt: 'Commits no branch padrão, fonte: API do GitHub.',
      ru: 'Коммиты в основной ветке, источник: GitHub API.',
      ja: 'デフォルトブランチのコミット数、出典: GitHub API。',
      ko: '기본 브랜치의 커밋 수, 출처: GitHub API.',
      zh: '默认分支上的提交数，来源：GitHub API。',
      ar: 'الالتزامات على الفرع الافتراضي، المصدر: GitHub API.',
      hi: 'डिफ़ॉल्ट ब्रांच पर कमिट, स्रोत: GitHub API।',
      tr: 'Varsayılan daldaki commit sayısı, kaynak: GitHub API.',
      pl: 'Commity na domyślnej gałęzi, źródło: GitHub API.',
      id: 'Commit pada branch default, sumber: GitHub API.',
      vi: 'Số commit trên nhánh mặc định, nguồn: GitHub API.',
      uk: 'Коміти в основній гілці, джерело: GitHub API.',
    }),
    downloadsSource: t({
      en: 'Source: npm registry downloads API.',
      'en-GB': 'Source: npm registry downloads API.',
      fr: 'Source : API de téléchargements du registre npm.',
      es: 'Fuente: API de descargas del registro npm.',
      de: 'Quelle: Download-API der npm-Registry.',
      it: 'Fonte: API dei download del registro npm.',
      pt: 'Fonte: API de downloads do registro npm.',
      ru: 'Источник: API загрузок реестра npm.',
      ja: '出典: npm レジストリのダウンロード API。',
      ko: '출처: npm 레지스트리 다운로드 API.',
      zh: '来源：npm 注册表下载 API。',
      ar: 'المصدر: واجهة تنزيلات سجل npm.',
      hi: 'स्रोत: npm रजिस्ट्री डाउनलोड API।',
      tr: 'Kaynak: npm kayıt defteri indirme API’si.',
      pl: 'Źródło: API pobrań rejestru npm.',
      id: 'Sumber: API unduhan registri npm.',
      vi: 'Nguồn: API lượt tải của npm registry.',
      uk: 'Джерело: API завантажень реєстру npm.',
    }),
    commitsDatasetName: t({
      en: 'GitHub commits of i18n libraries',
      'en-GB': 'GitHub commits of i18n libraries',
      fr: 'Commits GitHub des bibliothèques i18n',
      es: 'Commits de GitHub de las bibliotecas i18n',
      de: 'GitHub-Commits von i18n-Bibliotheken',
      it: 'Commit GitHub delle librerie i18n',
      pt: 'Commits no GitHub das bibliotecas i18n',
      ru: 'Коммиты GitHub библиотек i18n',
      ja: 'i18n ライブラリの GitHub コミット数',
      ko: 'i18n 라이브러리의 GitHub 커밋 수',
      zh: 'i18n 库的 GitHub 提交数',
      ar: 'التزامات GitHub لمكتبات i18n',
      hi: 'i18n लाइब्रेरी के GitHub कमिट',
      tr: 'i18n kütüphanelerinin GitHub commit sayıları',
      pl: 'Commity GitHub bibliotek i18n',
      id: 'Commit GitHub pustaka i18n',
      vi: 'Số commit GitHub của các thư viện i18n',
      uk: 'Коміти GitHub бібліотек i18n',
    }),
    commitsDatasetDescription: t({
      en: 'Number of commits on the default branch of each compared GitHub repository, collected from the GitHub API. Repositories:',
      'en-GB':
        'Number of commits on the default branch of each compared GitHub repository, collected from the GitHub API. Repositories:',
      fr: 'Nombre de commits sur la branche par défaut de chaque dépôt GitHub comparé, collecté via l’API GitHub. Dépôts :',
      es: 'Número de commits en la rama por defecto de cada repositorio de GitHub comparado, obtenido de la API de GitHub. Repositorios:',
      de: 'Anzahl der Commits auf dem Standard-Branch jedes verglichenen GitHub-Repositorys, erhoben über die GitHub API. Repositorys:',
      it: 'Numero di commit sul branch predefinito di ogni repository GitHub confrontato, raccolto tramite l’API GitHub. Repository:',
      pt: 'Número de commits no branch padrão de cada repositório do GitHub comparado, coletado pela API do GitHub. Repositórios:',
      ru: 'Количество коммитов в основной ветке каждого сравниваемого репозитория GitHub, полученное через GitHub API. Репозитории:',
      ja: '比較対象の各 GitHub リポジトリのデフォルトブランチにあるコミット数。GitHub API から取得しています。リポジトリ：',
      ko: '비교 대상 GitHub 저장소별 기본 브랜치의 커밋 수로, GitHub API에서 수집했습니다. 저장소:',
      zh: '每个参与比较的 GitHub 仓库默认分支上的提交数量，数据通过 GitHub API 收集。仓库：',
      ar: 'عدد الالتزامات على الفرع الافتراضي لكل مستودع GitHub تمت مقارنته، مجمّعة عبر GitHub API. المستودعات:',
      hi: 'तुलना किए गए प्रत्येक GitHub रिपॉज़िटरी की डिफ़ॉल्ट ब्रांच पर कमिट की संख्या, GitHub API से एकत्रित। रिपॉज़िटरी:',
      tr: 'Karşılaştırılan her GitHub deposunun varsayılan dalındaki commit sayısı, GitHub API üzerinden toplanmıştır. Depolar:',
      pl: 'Liczba commitów na domyślnej gałęzi każdego porównywanego repozytorium GitHub, pobrana z GitHub API. Repozytoria:',
      id: 'Jumlah commit pada branch default setiap repositori GitHub yang dibandingkan, dikumpulkan dari GitHub API. Repositori:',
      vi: 'Số commit trên nhánh mặc định của từng kho GitHub được so sánh, thu thập từ GitHub API. Các kho:',
      uk: 'Кількість комітів в основній гілці кожного порівнюваного репозиторію GitHub, отримана через GitHub API. Репозиторії:',
    }),
    downloadsDatasetName: t({
      en: 'npm downloads of i18n libraries',
      'en-GB': 'npm downloads of i18n libraries',
      fr: 'Téléchargements npm des bibliothèques i18n',
      es: 'Descargas de npm de las bibliotecas i18n',
      de: 'npm-Downloads von i18n-Bibliotheken',
      it: 'Download npm delle librerie i18n',
      pt: 'Downloads no npm das bibliotecas i18n',
      ru: 'Загрузки npm библиотек i18n',
      ja: 'i18n ライブラリの npm ダウンロード数',
      ko: 'i18n 라이브러리의 npm 다운로드 수',
      zh: 'i18n 库的 npm 下载量',
      ar: 'تنزيلات npm لمكتبات i18n',
      hi: 'i18n लाइब्रेरी के npm डाउनलोड',
      tr: 'i18n kütüphanelerinin npm indirme sayıları',
      pl: 'Pobrania npm bibliotek i18n',
      id: 'Unduhan npm pustaka i18n',
      vi: 'Lượt tải npm của các thư viện i18n',
      uk: 'Завантаження npm бібліотек i18n',
    }),
    downloadsDatasetDescription: t({
      en: 'Total downloads of each compared package over the selected period, summed from the daily counts of the npm registry downloads API. Packages:',
      'en-GB':
        'Total downloads of each compared package over the selected period, summed from the daily counts of the npm registry downloads API. Packages:',
      fr: 'Téléchargements totaux de chaque paquet comparé sur la période choisie, additionnés à partir des chiffres quotidiens de l’API de téléchargements du registre npm. Paquets :',
      es: 'Descargas totales de cada paquete comparado en el periodo seleccionado, sumadas a partir de los recuentos diarios de la API de descargas del registro npm. Paquetes:',
      de: 'Gesamtdownloads jedes verglichenen Pakets im gewählten Zeitraum, summiert aus den täglichen Werten der Download-API der npm-Registry. Pakete:',
      it: 'Download totali di ogni pacchetto confrontato nel periodo selezionato, sommati dai conteggi giornalieri dell’API dei download del registro npm. Pacchetti:',
      pt: 'Downloads totais de cada pacote comparado no período selecionado, somados a partir das contagens diárias da API de downloads do registro npm. Pacotes:',
      ru: 'Общее число загрузок каждого сравниваемого пакета за выбранный период, суммированное по ежедневным данным API загрузок реестра npm. Пакеты:',
      ja: '選択した期間における比較対象の各パッケージの合計ダウンロード数。npm レジストリのダウンロード API の日次データを合算しています。パッケージ：',
      ko: '선택한 기간 동안 비교 대상 패키지별 총 다운로드 수로, npm 레지스트리 다운로드 API의 일별 수치를 합산했습니다. 패키지:',
      zh: '所选时间段内每个参与比较的包的总下载量，由 npm 注册表下载 API 的每日数据累加得出。包：',
      ar: 'إجمالي تنزيلات كل حزمة تمت مقارنتها خلال الفترة المحددة، محسوبًا من الأعداد اليومية لواجهة تنزيلات سجل npm. الحزم:',
      hi: 'चुनी गई अवधि में तुलना किए गए प्रत्येक पैकेज के कुल डाउनलोड, npm रजिस्ट्री डाउनलोड API की दैनिक गिनती से जोड़े गए। पैकेज:',
      tr: 'Seçilen dönemde karşılaştırılan her paketin toplam indirme sayısı, npm kayıt defteri indirme API’sinin günlük değerlerinden toplanmıştır. Paketler:',
      pl: 'Łączna liczba pobrań każdego porównywanego pakietu w wybranym okresie, zsumowana z dziennych danych API pobrań rejestru npm. Pakiety:',
      id: 'Total unduhan setiap paket yang dibandingkan selama periode terpilih, dijumlahkan dari hitungan harian API unduhan registri npm. Paket:',
      vi: 'Tổng lượt tải của từng gói được so sánh trong khoảng thời gian đã chọn, cộng dồn từ số liệu hằng ngày của API lượt tải npm registry. Các gói:',
      uk: 'Загальна кількість завантажень кожного порівнюваного пакета за вибраний період, підсумована з щоденних даних API завантажень реєстру npm. Пакети:',
    }),
    periods: {
      'last-week': t({
        en: 'Last week',
        'en-GB': 'Last week',
        fr: 'Dernière semaine',
        es: 'Última semana',
        de: 'Letzte Woche',
        it: 'Ultima settimana',
        pt: 'Última semana',
        ru: 'Неделя',
        ja: '過去1週間',
        ko: '지난 1주',
        zh: '最近一周',
        ar: 'آخر أسبوع',
        hi: 'पिछला सप्ताह',
        tr: 'Son hafta',
        pl: 'Ostatni tydzień',
        id: 'Minggu terakhir',
        vi: 'Tuần qua',
        uk: 'Тиждень',
      }),
      'last-month': t({
        en: 'Last month',
        'en-GB': 'Last month',
        fr: 'Dernier mois',
        es: 'Último mes',
        de: 'Letzter Monat',
        it: 'Ultimo mese',
        pt: 'Último mês',
        ru: 'Месяц',
        ja: '過去1か月',
        ko: '지난 1개월',
        zh: '最近一个月',
        ar: 'آخر شهر',
        hi: 'पिछला महीना',
        tr: 'Son ay',
        pl: 'Ostatni miesiąc',
        id: 'Bulan terakhir',
        vi: 'Tháng qua',
        uk: 'Місяць',
      }),
      'last-6-months': t({
        en: 'Last 6 months',
        'en-GB': 'Last 6 months',
        fr: '6 derniers mois',
        es: 'Últimos 6 meses',
        de: 'Letzte 6 Monate',
        it: 'Ultimi 6 mesi',
        pt: 'Últimos 6 meses',
        ru: '6 месяцев',
        ja: '過去6か月',
        ko: '지난 6개월',
        zh: '最近 6 个月',
        ar: 'آخر 6 أشهر',
        hi: 'पिछले 6 महीने',
        tr: 'Son 6 ay',
        pl: 'Ostatnie 6 miesięcy',
        id: '6 bulan terakhir',
        vi: '6 tháng qua',
        uk: '6 місяців',
      }),
      'last-year': t({
        en: 'Last year',
        'en-GB': 'Last year',
        fr: 'Dernière année',
        es: 'Último año',
        de: 'Letztes Jahr',
        it: 'Ultimo anno',
        pt: 'Último ano',
        ru: 'Год',
        ja: '過去1年',
        ko: '지난 1년',
        zh: '最近一年',
        ar: 'آخر سنة',
        hi: 'पिछला वर्ष',
        tr: 'Son yıl',
        pl: 'Ostatni rok',
        id: 'Tahun terakhir',
        vi: 'Năm qua',
        uk: 'Рік',
      }),
    },
  },
} satisfies Dictionary;

export default repositoryComparisonContent;
