import { GithubRoutes, PagesRoutes } from '@/Routes';
import { Dictionary, t } from 'intlayer';
import { DocData } from '../types';

const docContent = {
  key: 'doc-mcp-server-metadata',
  content: {
    docName: 'mcp_server',
    url: PagesRoutes.MCP_Server,
    githubUrl: GithubRoutes['MCP_Server'],
    createdAt: '2025-06-07',
    updatedAt: '2025-06-07',
    title: t({
      en: 'MCP Server Documentation',
      'en-GB': 'MCP Server Documentation',
      fr: 'Documentation du serveur MCP',
      es: 'Documentación del servidor MCP',
      de: 'MCP-Server-Dokumentation',
      ja: 'MCPサーバーのドキュメント',
      ko: 'MCP 서버 문서',
      zh: 'MCP服务器文档',
      it: 'Documentazione del server MCP',
      pt: 'Documentação do servidor MCP',
      hi: 'MCP सर्वर दस्तावेज़ीकरण',
      ar: 'توثيق خادم MCP',
      ru: 'Документация сервера MCP',
    }),
    description: t({
      en: 'Explore the features and setup of the MCP Server to optimize your server management and operations.',
      'en-GB':
        'Explore the features and setup of the MCP Server to optimize your server management and operations.',
      fr: 'Découvrez les fonctionnalités et la configuration du serveur MCP pour optimiser la gestion et les opérations de votre serveur.',
      es: 'Explore las características y la configuración del servidor MCP para optimizar la gestión y las operaciones de su servidor.',
      de: 'Erkunden Sie die Funktionen und die Einrichtung des MCP-Servers, um Ihre Serververwaltung und -operationen zu optimieren.',
      ja: 'MCPサーバーの機能とセットアップを探索して、サーバー管理と運用を最適化します。',
      ko: 'MCP 서버의 기능과 설정을 탐색하여 서버 관리 및 운영을 최적화하세요.',
      zh: '探索MCP服务器的功能和设置，以优化您的服务器管理和操作。',
      it: 'Esplora le funzionalità e la configurazione del server MCP per ottimizzare la gestione e le operazioni del tuo server.',
      pt: 'Explore os recursos e a configuração do servidor MCP para otimizar o gerenciamento e as operações do seu servidor.',
      hi: 'MCP सर्वर की विशेषताओं और सेटअप का अन्वेषण करें ताकि आपके सर्वर प्रबंधन और संचालन को अनुकूलित किया जा सके।',
      ar: 'استكشف ميزات وإعدادات خادم MCP لتحسين إدارة الخادم وعملياته.',
      ru: 'Изучите функции и настройку сервера MCP, чтобы оптимизировать управление сервером и его операции.',
    }),
    keywords: t({
      en: [
        'MCP Server',
        'Server Management',
        'Optimization',
        'Intlayer',
        'Documentation',
        'Setup',
        'Features',
      ],
      'en-GB': [
        'MCP Server',
        'Server Management',
        'Optimization',
        'Intlayer',
        'Documentation',
        'Setup',
        'Features',
      ],
      fr: [
        'Serveur MCP',
        'Gestion de serveur',
        'Optimisation',
        'Intlayer',
        'Documentation',
        'Configuration',
        'Fonctionnalités',
      ],
      es: [
        'Servidor MCP',
        'Gestión de servidores',
        'Optimización',
        'Intlayer',
        'Documentación',
        'Configuración',
        'Características',
      ],
      de: [
        'MCP-Server',
        'Serververwaltung',
        'Optimierung',
        'Intlayer',
        'Dokumentation',
        'Einrichtung',
        'Funktionen',
      ],
      ja: [
        'MCPサーバー',
        'サーバー管理',
        '最適化',
        'Intlayer',
        'ドキュメント',
        'セットアップ',
        '機能',
      ],
      ko: [
        'MCP 서버',
        '서버 관리',
        '최적화',
        'Intlayer',
        '문서',
        '설정',
        '기능',
      ],
      zh: [
        'MCP服务器',
        '服务器管理',
        '优化',
        'Intlayer',
        '文档',
        '设置',
        '功能',
      ],
      it: [
        'Server MCP',
        'Gestione del server',
        'Ottimizzazione',
        'Intlayer',
        'Documentazione',
        'Configurazione',
        'Funzionalità',
      ],
      pt: [
        'Servidor MCP',
        'Gerenciamento de servidor',
        'Otimização',
        'Intlayer',
        'Documentação',
        'Configuração',
        'Recursos',
      ],
      hi: [
        'MCP सर्वर',
        'सर्वर प्रबंधन',
        'अनुकूलन',
        'Intlayer',
        'दस्तावेज़ीकरण',
        'सेटअप',
        'विशेषताएं',
      ],
      ar: [
        'خادم MCP',
        'إدارة الخادم',
        'تحسين',
        'Intlayer',
        'توثيق',
        'إعداد',
        'ميزات',
      ],
      ru: [
        'Сервер MCP',
        'Управление сервером',
        'Оптимизация',
        'Intlayer',
        'Документация',
        'Настройка',
        'Функции',
      ],
    }),
  },
} satisfies Dictionary<DocData>;

export default docContent;
