declare module '@intlayer/docs' {
  enum DocsKeysEnum {
    introduction,
    how_works_intlayer,
    configuration,
    interest_of_intlayer,
    intlayer_cli,
    intlayer_visual_editor,
    intlayer_CMS,
    intlayer_with_create_react_app,
    intlayer_with_i18next,
    intlayer_with_nextjs_15,
    intlayer_with_nextjs_14,
    intlayer_with_nextjs_page_router,
    intlayer_with_vite_react,
    dictionary__translation,
    dictionary__enumeration,
    dictionary__function_fetching,
    dictionary__get_started,
    dictionary__content_extention_customization,
    terms_of_service,
    privacy_notice,
    'package__intlayer',
    'package__intlayer__getConfiguration',
    'package__intlayer__getDictionary',
    'package__intlayer__getLocaleLang',
    'package__intlayer__getLocaleName',
    'package__intlayer__getLocalizedUrl',
    'package__intlayer__getMultilingualUrls',
    'package__intlayer__getPathWithoutLocale',
    'package__intlayer__getTranslationContent',
    'package__intlayer__getEnumerationContent',
    'package__intlayer__removeLocaleFromUrl',
    'package__express-intlayer',
    'package__express-intlayer__t',
    'package__next-intlayer',
    'package__next-intlayer__t',
    'package__next-intlayer__useDictionary',
    'package__next-intlayer__useIntlayer',
    'package__next-intlayer__useIntlayerAsync',
    'package__next-intlayer__useLocale',
    'package__react-intlayer',
    'package__react-intlayer__t',
    'package__react-intlayer__useDictionary',
    'package__react-intlayer__useIntlayer',
    'package__react-intlayer__useIntlayerAsync',
    'package__react-intlayer__useLocale',
    'package__vite-intlayer',
    'package__react-scripts-intlayer',
    'package__intlayer-editor',
    'package__@intlayer_api',
    'package__@intlayer_chokidar',
    'package__@intlayer_cli',
    'package__@intlayer_config',
    'package__@intlayer_core',
    'package__@intlayer_design-system',
    'package__@intlayer_dictionary-entry',
    'package__@intlayer_webpack',
    'package__@intlayer_editor',
    'package__@intlayer_editor-react',
  }

  export type DocsKeys = keyof typeof DocsKeysEnum;

  export function getDocs(lang?: string): Docs;
  export function getDoc<T extends DocsKeys>(
    docName: T,
    lang?: string
  ): Docs[T];

  export type Docs = Record<DocsKeys, string>;
}
