import { t, type Dictionary } from 'intlayer';
import { type Metadata } from 'next';

const docContent = {
  key: 'doc-lynx-intlayer-metadata',
  content: {
    title: t({
      en: 'Package Documentation | lynx-intlayer',
      'en-GB': 'Package Documentation | lynx-intlayer',
      fr: 'Documentation du package | lynx-intlayer',
      es: 'Documentación del paquete | lynx-intlayer',
      de: 'Paketdokumentation | lynx-intlayer',
      ja: 'パッケージドキュメント | lynx-intlayer',
      ko: '패키지 문서 | lynx-intlayer',
      zh: '包文档 | lynx-intlayer',
      it: 'Documentazione del pacchetto | lynx-intlayer',
      pt: 'Documentação do pacote | lynx-intlayer',
      hi: 'पैकेज के डॉक्यूमेंटेशन | lynx-intlayer',
      ar: 'وثائق حزمة | lynx-intlayer',
      ru: 'Документация пакета | lynx-intlayer',
    }),

    description: t({
      en: 'See how to use the lynx-intlayer package',
      'en-GB': 'See how to use the lynx-intlayer package',
      fr: 'Découvrez comment utiliser le package lynx-intlayer',
      es: 'Descubre cómo usar el paquete lynx-intlayer',
      de: 'Erfahren Sie, wie Sie das lynx-intlayer-Paket verwenden',
      ja: 'lynx-intlayerパッケージの使用方法を確認してください',
      ko: 'lynx-intlayer 패키지 사용 방법을 확인하세요',
      zh: '查看如何使用 lynx-intlayer 软件包',
      it: 'Scopri come utilizzare il pacchetto lynx-intlayer',
      pt: 'Veja como usar o pacote lynx-intlayer',
      hi: 'lynx-intlayer पैकेज का उपयोग कैसे करें',
      ar: 'انظر كيف تستخدم حزمة lynx-intlayer',
      ru: 'Узнайте, как использовать пакет lynx-intlayer',
    }),

    keywords: t({
      en: [
        'Intlayer',
        'lynx-intlayer',
        'Internationalization',
        'Documentation',
        'Next.js',
        'JavaScript',
        'React',
      ],
      'en-GB': [
        'Intlayer',
        'lynx-intlayer',
        'Internationalization',
        'Documentation',
        'Next.js',
        'JavaScript',
        'React',
      ],
      fr: [
        'Intlayer',
        'lynx-intlayer',
        'Internationalisation',
        'Documentation',
        'Next.js',
        'JavaScript',
        'React',
      ],
      es: [
        'Intlayer',
        'lynx-intlayer',
        'Internacionalización',
        'Documentación',
        'Next.js',
        'JavaScript',
        'React',
      ],
      de: [
        'Intlayer',
        'lynx-intlayer',
        'Internationalisierung',
        'Dokumentation',
        'Next.js',
        'JavaScript',
        'React',
      ],
      ja: [
        'Intlayer',
        'lynx-intlayer',
        '国際化',
        'ドキュメント',
        'Next.js',
        'JavaScript',
        'React',
      ],
      ko: [
        'Intlayer',
        'lynx-intlayer',
        '국제화',
        '문서',
        'Next.js',
        'JavaScript',
        'React',
      ],
      zh: [
        'Intlayer',
        'lynx-intlayer',
        '国际化',
        '文档',
        'Next.js',
        'JavaScript',
        'React',
      ],
      it: [
        'Intlayer',
        'lynx-intlayer',
        'internazionalizzazione',
        'documentazione',
        'Next.js',
        'JavaScript',
        'React',
      ],
      pt: [
        'Intlayer',
        'lynx-intlayer',
        'internacionalização',
        'documentação',
        'Next.js',
        'JavaScript',
        'React',
      ],
      hi: [
        'Intlayer',
        'lynx-intlayer',
        'अंतर्राष्ट्रीयकरण',
        'प्रलेखन',
        'Next.js',
        'JavaScript',
        'React',
      ],
      ar: [
        'Intlayer',
        'lynx-intlayer',
        'الدولية',
        'المستندات',
        'Next.js',
        'JavaScript',
        'React',
      ],
      ru: [
        'Intlayer',
        'lynx-intlayer',
        'интернационализация',
        'документация',
        'Next.js',
        'JavaScript',
        'React',
      ],
    }),
  },
} satisfies Dictionary<Metadata>;

export default docContent;
