import { type Dictionary, insert, t } from 'intlayer';

const repositoryLinkContent = {
  key: 'repository-link',
  content: {
    title: t({
      en: 'Repository Connection',
      fr: 'Connexion au dépôt',
      es: 'Conexión al repositorio',
      ru: 'Подключение репозитория',
      ja: 'リポジトリ接続',
      ko: '저장소 연결',
      zh: '仓库连接',
      de: 'Repository-Verbindung',
      ar: 'اتصال المستودع',
      it: 'Connessione al repository',
      'en-GB': 'Repository Connection',
      pt: 'Conexão do repositório',
      hi: 'रिपॉजिटरी कनेक्शन',
      tr: 'Depo Bağlantısı',
      pl: 'Połączenie z repozytorium',
      id: 'Koneksi Repositori',
      vi: 'Kết nối kho lưu trữ',
      uk: 'Підключення репозиторію',
    }),

    selectProvider: t({
      en: 'Select a repository provider',
      fr: 'Sélectionnez un fournisseur de dépôt',
      es: 'Seleccione un proveedor de repositorio',
      ru: 'Выберите провайдера репозитория',
      ja: 'リポジトリプロバイダーを選択',
      ko: '저장소 제공업체 선택',
      zh: '选择仓库提供商',
      de: 'Repository-Anbieter auswählen',
      ar: 'اختر مزود المستودع',
      it: 'Seleziona un provider di repository',
      'en-GB': 'Select a repository provider',
      pt: 'Selecione um provedor de repositório',
      hi: 'रिपॉजिटरी प्रदाता चुनें',
      tr: 'Bir depo sağlayıcısı seçin',
      pl: 'Wybierz dostawcę repozytorium',
      id: 'Pilih penyedia repositori',
      vi: 'Chọn nhà cung cấp kho lưu trữ',
      uk: 'Виберіть постачальника репозиторію',
    }),

    connectTitle: insert(
      t({
        ar: '{{provider}} ربط',
        de: '{{provider}} verbinden',
        en: 'Connect {{provider}}',
        'en-GB': 'Connect {{provider}}',
        es: 'Conectar {{provider}}',
        fr: 'Connecter {{provider}}',
        hi: '{{provider}} कनेक्ट करें',
        id: 'Hubungkan {{provider}}',
        it: 'Connetti {{provider}}',
        ja: '{{provider}} に接続',
        ko: '{{provider}} 연결',
        pl: 'Połącz {{provider}}',
        pt: 'Conectar {{provider}}',
        ru: 'Подключить {{provider}}',
        tr: '{{provider}} Bağlayın',
        uk: 'Підключити {{provider}}',
        vi: 'Kết nối {{provider}}',
        zh: '连接 {{provider}}',
      })
    ),

    connectDescription: t({
      en: 'Link your account to browse and import repositories.',
      fr: 'Liez votre compte pour parcourir et importer des dépôts.',
      es: 'Vincula tu cuenta para explorar e importar repositorios.',
      ru: 'Свяжите свой аккаунт для просмотра и импорта репозиториев.',
      ja: 'アカウントをリンクしてリポジトリを閲覧・インポートできます。',
      ko: '계정을 연결하여 저장소를 탐색하고 가져오세요.',
      zh: '链接您的账户以浏览和导入仓库。',
      de: 'Verknüpfen Sie Ihr Konto, um Repositories zu durchsuchen und zu importieren.',
      ar: 'اربط حسابك لتصفح واستيراد المستودعات.',
      it: 'Collega il tuo account per sfogliare e importare repository.',
      'en-GB': 'Link your account to browse and import repositories.',
      pt: 'Vincule sua conta para navegar e importar repositórios.',
      hi: 'रिपॉजिटरी ब्राउज़ और इम्पोर्ट करने के लिए अपना खाता लिंक करें।',
      tr: 'Depoları görmek ve içe aktarmak için hesabınızı bağlayın.',
      pl: 'Połącz swoje konto, aby przeglądać i importować repozytoria.',
      id: 'Tautkan akun Anda untuk menelusuri dan mengimpor repositori.',
      vi: 'Liên kết tài khoản của bạn để duyệt và nhập kho lưu trữ.',
      uk: 'Пов’яжіть свій обліковий запис, щоб переглядати та імортувати репозиторії.',
    }),

    selectRepository: t({
      en: 'Select a repository to connect',
      fr: 'Sélectionnez un dépôt à connecter',
      es: 'Seleccione un repositorio para conectar',
      ru: 'Выберите репозиторий для подключения',
      ja: '接続するリポジトリを選択',
      ko: '연결할 저장소 선택',
      zh: '选择要连接的仓库',
      de: 'Repository zum Verbinden auswählen',
      ar: 'اختر مستودعاً للاتصال',
      it: 'Seleziona un repository da connettere',
      'en-GB': 'Select a repository to connect',
      pt: 'Selecione um repositório para conectar',
      hi: 'कनेक्ट करने के लिए एक रिपॉजिटरी चुनें',
      tr: 'Bağlanacak bir depo seçin',
      pl: 'Wybierz repozytorium do połączenia',
      id: 'Pilih repositori untuk dihubungkan',
      vi: 'Chọn kho lưu trữ để kết nối',
      uk: 'Виберіть репозиторій для підключення',
    }),

    gitlab: {
      instanceUrl: t({
        en: 'GitLab Instance URL',
        fr: "URL de l'instance GitLab",
        es: 'URL de la instancia de GitLab',
        ru: 'URL экземпляра GitLab',
        ja: 'GitLabインスタンスURL',
        ko: 'GitLab 인스턴스 URL',
        zh: 'GitLab实例URL',
        de: 'GitLab-Instanz-URL',
        ar: 'رابط نسخة GitLab',
        it: 'URL istanza GitLab',
        'en-GB': 'GitLab Instance URL',
        pt: 'URL da instância GitLab',
        hi: 'GitLab इंस्टेंस URL',
        tr: 'GitLab Örnek URL',
        pl: 'URL instancji GitLab',
        id: 'URL Instansi GitLab',
        vi: 'URL phiên bản GitLab',
        uk: 'URL-адреса інстансу GitLab',
      }),
      instanceUrlHint: t({
        en: '(leave empty for gitlab.com)',
        fr: '(laissez vide pour gitlab.com)',
        es: '(dejar vacío para gitlab.com)',
        ru: '(оставьте пустым для gitlab.com)',
        ja: '(gitlab.comの場合は空欄のまま)',
        ko: '(gitlab.com의 경우 비워두세요)',
        zh: '(gitlab.com请留空)',
        de: '(leer lassen für gitlab.com)',
        ar: '(اتركه فارغاً لـ gitlab.com)',
        it: '(lascia vuoto per gitlab.com)',
        'en-GB': '(leave empty for gitlab.com)',
        pt: '(deixe vazio para gitlab.com)',
        hi: '(gitlab.com के लिए खाली छोड़ें)',
        tr: '(gitlab.com için boş bırakın)',
        pl: '(zostaw puste dla gitlab.com)',
        id: '(kosongkan untuk gitlab.com)',
        vi: '(để trống cho gitlab.com)',
        uk: '(залиште пустим для gitlab.com)',
      }),
    },

    status: {
      connectedTo: t({
        en: 'Connected to',
        fr: 'Connecté à',
        es: 'Conectado a',
        ru: 'Подключено к',
        ja: '接続先',
        ko: '연결됨',
        zh: '已连接到',
        de: 'Verbunden mit',
        ar: 'متصل بـ',
        it: 'Connesso a',
        'en-GB': 'Connected to',
        pt: 'Conectado a',
        hi: 'से जुड़ा',
        tr: 'Bağlı',
        pl: 'Połączono z',
        id: 'Terhubung ke',
        vi: 'Đã kết nối với',
        uk: 'Підключено до',
      }),
      configNotFound: t({
        en: 'Configuration Not Found',
        fr: 'Configuration non trouvée',
        es: 'Configuración no encontrada',
        ru: 'Конфигурация не найдена',
        ja: '設定が見つかりません',
        ko: '구성을 찾을 수 없습니다',
        zh: '未找到配置',
        de: 'Konfiguration nicht gefunden',
        ar: 'لم يتم العثور على التكوين',
        it: 'Configurazione non trovata',
        'en-GB': 'Configuration Not Found',
        pt: 'Configuração não encontrada',
        hi: 'कॉन्फ़िगरेशन नहीं मिला',
        tr: 'Yapılandırma Bulunamadı',
        pl: 'Nie znaleziono konfiguracji',
        id: 'Konfigurasi Tidak Ditemukan',
        vi: 'Không tìm thấy cấu hình',
        uk: 'Конфігурація не знайдена',
      }),
    },

    authentication: {
      failed: t({
        en: 'Authentication Failed',
        fr: "Échec de l'authentification",
        es: 'Error de autenticación',
        ru: 'Ошибка аутентификации',
        ja: '認証に失敗しました',
        ko: '인증 실패',
        zh: '认证失败',
        de: 'Authentifizierung fehlgeschlagen',
        ar: 'فشل المصادقة',
        it: 'Autenticazione fallita',
        'en-GB': 'Authentication Failed',
        pt: 'Falha na autenticação',
        hi: 'प्रमाणीकरण विफल',
        tr: 'Kimlik Doğrulama Başarısız',
        pl: 'Uwierzytelnianie nie powiodło się',
        id: 'Autentikasi Gagal',
        vi: 'Xác thực thất bại',
        uk: 'Не вдалося автентифікуватися',
      }),
    },

    actions: {
      connect: t({
        en: 'Connect',
        fr: 'Connecter',
        es: 'Conectar',
        ru: 'Подключить',
        ja: '接続',
        ko: '연결',
        zh: '连接',
        de: 'Verbinden',
        ar: 'اتصال',
        it: 'Connetti',
        'en-GB': 'Connect',
        pt: 'Conectar',
        hi: 'कनेक्ट करें',
        tr: 'Bağlan',
        pl: 'Połącz',
        id: 'Hubungkan',
        vi: 'Kết nối',
        uk: 'Підключити',
      }),
      connectWithProvider: insert(
        t({
          ar: '{{provider}} ربط',
          de: '{{provider}} verbinden',
          en: 'Connect {{provider}}',
          'en-GB': 'Connect {{provider}}',
          es: 'Conectar {{provider}}',
          fr: 'Connecter {{provider}}',
          hi: '{{provider}} कनेक्ट करें',
          id: 'Hubungkan {{provider}}',
          it: 'Connetti {{provider}}',
          ja: '{{provider}} に接続',
          ko: '{{provider}} 연결',
          pl: 'Połącz {{provider}}',
          pt: 'Conectar {{provider}}',
          ru: 'Подключить {{provider}}',
          tr: '{{provider}} Bağlayın',
          uk: 'Підключити {{provider}}',
          vi: 'Kết nối {{provider}}',
          zh: '连接 {{provider}}',
        })
      ),
      disconnect: t({
        en: 'Disconnect',
        fr: 'Déconnecter',
        es: 'Desconectar',
        ru: 'Отключить',
        ja: '切断',
        ko: '연결 해제',
        zh: '断开连接',
        de: 'Trennen',
        ar: 'قطع الاتصال',
        it: 'Disconnetti',
        'en-GB': 'Disconnect',
        pt: 'Desconectar',
        hi: 'डिस्कनेक्ट करें',
        tr: 'Bağlantıyı Kes',
        pl: 'Rozłącz',
        id: 'Putuskan',
        vi: 'Ngắt kết nối',
        uk: 'Відключити',
      }),
      browseRepos: t({
        en: 'Browse Repositories',
        fr: 'Parcourir les dépôts',
        es: 'Explorar repositorios',
        ru: 'Просмотреть репозитории',
        ja: 'リポジトリを参照',
        ko: '저장소 탐색',
        zh: '浏览仓库',
        de: 'Repositories durchsuchen',
        ar: 'تصفح المستودعات',
        it: 'Sfoglia repository',
        'en-GB': 'Browse Repositories',
        pt: 'Navegar repositórios',
        hi: 'रिपॉजिटरी ब्राउज़ करें',
        tr: 'Depoları Gözat',
        pl: 'Przeglądaj repozytoria',
        id: 'Telusuri Repositori',
        vi: 'Duyệt kho lưu trữ',
        uk: 'Переглянути репозиторії',
      }),
      import: t({
        en: 'Import',
        fr: 'Importer',
        es: 'Importar',
        ru: 'Импорт',
        ja: 'インポート',
        ko: '가져오기',
        zh: '导入',
        de: 'Importieren',
        ar: 'استيراد',
        it: 'Importa',
        'en-GB': 'Import',
        pt: 'Importar',
        hi: 'आयात करें',
        tr: 'İçe Aktar',
        pl: 'Importuj',
        id: 'Impor',
        vi: 'Nhập',
        uk: 'Імпортувати',
      }),
      loadConfig: t({
        en: 'View Config',
        fr: 'Voir la config',
        es: 'Ver configuración',
        ru: 'Просмотреть конфигурацию',
        ja: '設定を表示',
        ko: '설정 보기',
        zh: '查看配置',
        de: 'Konfiguration anzeigen',
        ar: 'عرض التكوين',
        it: 'Visualizza configurazione',
        'en-GB': 'View Config',
        pt: 'Ver configuração',
        hi: 'कॉन्फ़िग देखें',
        tr: 'Yapılandırmayı Görüntüle',
        pl: 'Zobacz konfigurację',
        id: 'Lihat Konfigurasi',
        vi: 'Xem cấu hình',
        uk: 'Переглянути конфігурацію',
      }),
      cancel: t({
        en: 'Cancel',
        fr: 'Annuler',
        es: 'Cancelar',
        ru: 'Отмена',
        ja: 'キャンセル',
        ko: '취소',
        zh: '取消',
        de: 'Abbrechen',
        ar: 'إلغاء',
        it: 'Annulla',
        'en-GB': 'Cancel',
        pt: 'Cancelar',
        hi: 'रद्द करें',
        tr: 'İptal',
        pl: 'Anuluj',
        id: 'Batal',
        vi: 'Hủy',
        uk: 'Скасувати',
      }),
      useThisFile: t({
        en: 'Use This File',
        fr: 'Utiliser ce fichier',
        es: 'Usar este archivo',
        ru: 'Использовать этот файл',
        ja: 'このファイルを使用',
        ko: '이 파일 사용',
        zh: '使用此文件',
        de: 'Diese Datei verwenden',
        ar: 'استخدم هذا الملف',
        it: 'Usa questo file',
        'en-GB': 'Use This File',
        pt: 'Usar este arquivo',
        hi: 'इस फ़ाइल का उपयोग करें',
        tr: 'Bu Dosyayı Kullan',
        pl: 'Użyj tego pliku',
        id: 'Gunakan File Ini',
        vi: 'Sử dụng tệp này',
        uk: 'Використати цей файл',
      }),
    },

    modal: {
      selectRepository: t({
        en: 'Select Repository',
        fr: 'Sélectionner un dépôt',
        es: 'Seleccionar repositorio',
        ru: 'Выбрать репозиторий',
        ja: 'リポジトリを選択',
        ko: '저장소 선택',
        zh: '选择仓库',
        de: 'Repository auswählen',
        ar: 'اختر المستودع',
        it: 'Seleziona repository',
        'en-GB': 'Select Repository',
        pt: 'Selecionar repositório',
        hi: 'रिपॉजिटरी चुनें',
        tr: 'Depo Seç',
        pl: 'Wybierz repozytorium',
        id: 'Pilih Repositori',
        vi: 'Chọn kho lưu trữ',
        uk: 'Виберіть репозиторій',
      }),
      selectRepositoryWithProvider: insert(
        t({
          ar: 'اختر مستودع {{provider}}',
          de: '{{provider}} Repository auswählen',
          en: 'Select {{provider}} Repository',
          'en-GB': 'Select {{provider}} Repository',
          es: 'Seleccionar repositorio {{provider}}',
          fr: 'Sélectionner un dépôt {{provider}}',
          hi: '{{provider}} रिपॉजिटरी चुनें',
          id: 'Pilih Repositori {{provider}}',
          it: 'Seleziona repository {{provider}}',
          ja: '{{provider}} リポジトリを選択',
          ko: '{{provider}} 저장소 선택',
          pl: 'Wybierz repozytorium {{provider}}',
          pt: 'Selecionar repositório {{provider}}',
          ru: 'Выбрать репозиторий {{provider}}',
          tr: '{{provider}} Depo Seç',
          uk: 'Виберіть репозиторій {{provider}}',
          vi: 'Chọn kho lưu trữ {{provider}}',
          zh: '选择 {{provider}} 仓库',
        })
      ),
      selectConfigTitle: t({
        en: 'Select Configuration File',
        fr: 'Sélectionner le fichier de configuration',
        es: 'Seleccionar archivo de configuración',
        ru: 'Выберите файл конфигурации',
        ja: '設定ファイルを選択',
        ko: '구성 파일 선택',
        zh: '选择配置文件',
        de: 'Konfigurationsdatei auswählen',
        ar: 'اختر ملف التكوين',
        it: 'Seleziona file di configurazione',
        'en-GB': 'Select Configuration File',
        pt: 'Selecionar arquivo de configuração',
        hi: 'कॉन्फ़िगरेशन फ़ाइल चुनें',
        tr: 'Yapılandırma Dosyası Seç',
        pl: 'Wybierz plik konfiguracyjny',
        id: 'Pilih File Konfigurasi',
        vi: 'Chọn tệp cấu hình',
        uk: 'Виберіть файл конфігурації',
      }),
      selectConfigDescription: t({
        en: 'Multiple configuration files found in',
        fr: 'Plusieurs fichiers de configuration trouvés dans',
        es: 'Se encontraron múltiples archivos de configuración en',
        ru: 'Найдено несколько файлов конфигурации в',
        ja: '複数の設定ファイルが見つかりました：',
        ko: '여러 구성 파일이 발견됨:',
        zh: '在以下位置找到多个配置文件：',
        de: 'Mehrere Konfigurationsdateien gefunden in',
        ar: 'تم العثور على عدة ملفات تكوين في',
        it: 'Trovati più file di configurazione in',
        'en-GB': 'Multiple configuration files found in',
        pt: 'Vários arquivos de configuração encontrados em',
        hi: 'में कई कॉन्फ़िगरेशन फ़ाइलें मिलीं',
        tr: 'Birden fazla yapılandırma dosyası bulundu:',
        pl: 'Znaleziono wiele plików konfiguracyjnych w',
        id: 'Beberapa file konfigurasi ditemukan di',
        vi: 'Tìm thấy nhiều tệp cấu hình trong',
        uk: 'Знайдено кілька файлів конфігурації в',
      }),
      selectConfigDescriptionEnd: t({
        en: '. Select the one to use.',
        fr: '. Sélectionnez celui à utiliser.',
        es: '. Seleccione el que desea usar.',
        ru: '. Выберите нужный.',
        ja: '使用するものを選択してください。',
        ko: '. 사용할 것을 선택하세요.',
        zh: '。请选择要使用的文件。',
        de: '. Wählen Sie die gewünschte aus.',
        ar: '. اختر الملف المطلوب.',
        it: '. Seleziona quello da usare.',
        'en-GB': '. Select the one to use.',
        pt: '. Selecione o que deseja usar.',
        hi: '. उपयोग करने के लिए चुनें।',
        tr: '. Kullanılacak olanı seçin.',
        pl: '. Wybierz ten, którego chcesz użyć.',
        id: '. Pilih yang akan digunakan.',
        vi: '. Chọn tệp để sử dụng.',
        uk: '. Оберіть той, який потрібно використовувати.',
      }),
      confirmTitle: t({
        en: 'Confirm Import',
        fr: "Confirmer l'importation",
        es: 'Confirmar importación',
        ru: 'Подтвердить импорт',
        ja: 'インポートを確認',
        ko: '가져오기 확인',
        zh: '确认导入',
        de: 'Import bestätigen',
        ar: 'تأكيد الاستيراد',
        it: "Conferma l'importazione",
        'en-GB': 'Confirm Import',
        pt: 'Confirmar importação',
        hi: 'आयात की पुष्टि करें',
        tr: 'İçe Aktarmayı Onayla',
        pl: 'Potwierdź import',
        id: 'Konfirmasi Impor',
        vi: 'Xác nhận nhập',
        uk: 'Підтвердити імпорт',
      }),
      viewConfigTitle: t({
        en: 'View Configuration',
        fr: 'Voir la configuration',
        es: 'Ver configuración',
        ru: 'Просмотр конфигурации',
        ja: '設定を表示',
        ko: '구성 보기',
        zh: '查看配置',
        de: 'Konfiguration anzeigen',
        ar: 'عرض التكوين',
        it: 'Visualizza configurazione',
        'en-GB': 'View Configuration',
        pt: 'Ver configuração',
        hi: 'कॉन्फ़िगरेशन देखें',
        tr: 'Yapılandırmayı Görüntüle',
        pl: 'Zobacz konfigurację',
        id: 'Lihat Konfigurasi',
        vi: 'Xem cấu hình',
        uk: 'Переглянути конфігурацію',
      }),
      failedToLoad: t({
        en: 'Failed to load configuration',
        fr: 'Échec du chargement de la configuration',
        es: 'Error al cargar la configuración',
        ru: 'Не удалось загрузить конфигурацию',
        ja: '設定の読み込みに失敗しました',
        ko: '구성 로드 실패',
        zh: '加载配置失败',
        de: 'Konfiguration konnte nicht geladen werden',
        ar: 'فشل تحميل التكوين',
        it: 'Impossibile caricare la configurazione',
        'en-GB': 'Failed to load configuration',
        pt: 'Falha ao carregar configuração',
        hi: 'कॉन्फ़िगरेशन लोड करने में विफल',
        tr: 'Yapılandırma yüklenemedi',
        pl: 'Nie udało się załadować konfiguracji',
        id: 'Gagal memuat konfigurasi',
        vi: 'Không thể tải cấu hình',
        uk: 'Не вдалося завантажити конфігурацію',
      }),
      back: t({
        en: 'Back',
        fr: 'Retour',
        es: 'Volver',
        ru: 'Назад',
        ja: '戻る',
        ko: '뒤로',
        zh: '返回',
        de: 'Zurück',
        ar: 'رجوع',
        it: 'Indietro',
        'en-GB': 'Back',
        pt: 'Voltar',
        hi: 'वापस',
        tr: 'Geri',
        pl: 'Wstecz',
        id: 'Kembali',
        vi: 'Quay lại',
        uk: 'Назад',
      }),
      close: t({
        en: 'Close',
        fr: 'Fermer',
        es: 'Cerrar',
        ru: 'Закрыть',
        ja: '閉じる',
        ko: '닫기',
        zh: '关闭',
        de: 'Schließen',
        ar: 'إغلاق',
        it: 'Chiudi',
        'en-GB': 'Close',
        pt: 'Fechar',
        hi: 'बंद करें',
        tr: 'Kapat',
        pl: 'Zamknij',
        id: 'Tutup',
        vi: 'Đóng',
        uk: 'Закрити',
      }),
    },

    providers: {
      github: {
        name: t({
          en: 'GitHub',
          fr: 'GitHub',
          es: 'GitHub',
          ru: 'GitHub',
          ja: 'GitHub',
          ko: 'GitHub',
          zh: 'GitHub',
          de: 'GitHub',
          ar: 'GitHub',
          it: 'GitHub',
          'en-GB': 'GitHub',
          pt: 'GitHub',
          hi: 'GitHub',
          tr: 'GitHub',
          pl: 'GitHub',
          id: 'GitHub',
          vi: 'GitHub',
          uk: 'GitHub',
        }),
        description: t({
          en: 'Connect with GitHub repositories',
          fr: 'Connecter avec les dépôts GitHub',
          es: 'Conectar con repositorios de GitHub',
          ru: 'Подключение к репозиториям GitHub',
          ja: 'GitHubリポジトリに接続',
          ko: 'GitHub 저장소에 연결',
          zh: '连接GitHub仓库',
          de: 'Mit GitHub-Repositories verbinden',
          ar: 'الاتصال بمستودعات GitHub',
          it: 'Connetti con repository GitHub',
          'en-GB': 'Connect with GitHub repositories',
          pt: 'Conectar com repositórios GitHub',
          hi: 'GitHub रिपॉजिटरी से कनेक्ट करें',
          tr: 'GitHub depolarına bağlan',
          pl: 'Połącz z repozytoriami GitHub',
          id: 'Hubungkan dengan repositori GitHub',
          vi: 'Kết nối với kho lưu trữ GitHub',
          uk: 'Підключіться до репозиторіїв GitHub',
        }),
      },
      gitlab: {
        name: t({
          en: 'GitLab',
          fr: 'GitLab',
          es: 'GitLab',
          ru: 'GitLab',
          ja: 'GitLab',
          ko: 'GitLab',
          zh: 'GitLab',
          de: 'GitLab',
          ar: 'GitLab',
          it: 'GitLab',
          'en-GB': 'GitLab',
          pt: 'GitLab',
          hi: 'GitLab',
          tr: 'GitLab',
          pl: 'GitLab',
          id: 'GitLab',
          vi: 'GitLab',
          uk: 'GitLab',
        }),
        description: t({
          en: 'Connect with GitLab projects (supports self-hosted)',
          fr: 'Connecter avec les projets GitLab (supporte les instances auto-hébergées)',
          es: 'Conectar con proyectos de GitLab (soporta instancias auto-alojadas)',
          ru: 'Подключение к проектам GitLab (поддержка самостоятельного хостинга)',
          ja: 'GitLabプロジェクトに接続（セルフホスト対応）',
          ko: 'GitLab 프로젝트에 연결 (자체 호스팅 지원)',
          zh: '连接GitLab项目（支持自托管）',
          de: 'Mit GitLab-Projekten verbinden (unterstützt Self-Hosted)',
          ar: 'الاتصال بمشاريع GitLab (يدعم الاستضافة الذاتية)',
          it: 'Connetti con progetti GitLab (supporta self-hosted)',
          'en-GB': 'Connect with GitLab projects (supports self-hosted)',
          pt: 'Conectar com projetos GitLab (suporta auto-hospedado)',
          hi: 'GitLab प्रोजेक्ट से कनेक्ट करें (सेल्फ-होस्टेड समर्थित)',
          tr: 'GitLab projelerine bağlan (kendi sunucusu desteklenir)',
          pl: 'Połącz z projektami GitLab (obsługuje self-hosted)',
          id: 'Hubungkan dengan proyek GitLab (mendukung self-hosted)',
          vi: 'Kết nối với dự án GitLab (hỗ trợ tự lưu trữ)',
          uk: 'Підключіться до проєктів GitLab (підтримує самохостинг)',
        }),
      },
      bitbucket: {
        name: t({
          en: 'Bitbucket',
          fr: 'Bitbucket',
          es: 'Bitbucket',
          ru: 'Bitbucket',
          ja: 'Bitbucket',
          ko: 'Bitbucket',
          zh: 'Bitbucket',
          de: 'Bitbucket',
          ar: 'Bitbucket',
          it: 'Bitbucket',
          'en-GB': 'Bitbucket',
          pt: 'Bitbucket',
          hi: 'Bitbucket',
          tr: 'Bitbucket',
          pl: 'Bitbucket',
          id: 'Bitbucket',
          vi: 'Bitbucket',
          uk: 'Bitbucket',
        }),
        description: t({
          en: 'Connect with Bitbucket repositories',
          fr: 'Connecter avec les dépôts Bitbucket',
          es: 'Conectar con repositorios de Bitbucket',
          ru: 'Подключение к репозиториям Bitbucket',
          ja: 'Bitbucketリポジトリに接続',
          ko: 'Bitbucket 저장소에 연결',
          zh: '连接Bitbucket仓库',
          de: 'Mit Bitbucket-Repositories verbinden',
          ar: 'الاتصال بمستودعات Bitbucket',
          it: 'Connetti con repository Bitbucket',
          'en-GB': 'Connect with Bitbucket repositories',
          pt: 'Conectar com repositórios Bitbucket',
          hi: 'Bitbucket रिपॉजिटरी से कनेक्ट करें',
          tr: 'Bitbucket depolarına bağlan',
          pl: 'Połącz z repozytoriami Bitbucket',
          id: 'Hubungkan dengan repositori Bitbucket',
          vi: 'Kết nối với kho lưu trữ Bitbucket',
          uk: 'Підключіться до репозиторіїв Bitbucket',
        }),
      },
    },
  },
  title: 'Repository link',
  description:
    'UI strings for connecting a source-code repository to a project, including provider selection, authentication, browsing and importing repositories, provider-specific settings, and related modal dialogs.',
  tags: ['repository', 'integration', 'providers', 'import'],
} satisfies Dictionary;

export default repositoryLinkContent;
