import { type Dictionary, insert, t } from 'intlayer';

const submitProjectFormContent = {
  key: 'submit-project-form',
  content: {
    title: t({
      en: 'Submit Your Project',
      'en-GB': 'Submit Your Project',
      fr: 'Soumettez votre projet',
      es: 'Envía tu proyecto',
      de: 'Reichen Sie Ihr Projekt ein',
      ja: 'プロジェクトを提出する',
      ko: '프로젝트 제출',
      zh: '提交您的项目',
      it: 'Invia il tuo progetto',
      pt: 'Envie seu projet',
      hi: 'अपना प्रोजेक्ट सबमिट करें',
      ar: 'أرسل مشروعك',
      ru: 'Отправьте свой проект',
      tr: 'Projenizi Gönderin',
      pl: 'Prześlij swój projekt',
      id: 'Kirimkan Proyek Anda',
      uk: 'Надішліть свій проект',
      vi: 'Gửi dự án của bạn',
    }),
    description: t({
      en: "Share what you've built. Your submission will be scanned before being submitted on the showcase list.",
      'en-GB':
        "Share what you've built. Your submission will be scanned before being submitted on the showcase list.",
      fr: "Partagez ce que vous avez construit. Votre soumission sera scannée avant d'être soumise à la liste de la vitrine.",
      es: 'Comparte lo que has construido. Tu envío será escaneado antes de ser enviado a la lista del escaparate.',
      de: 'Teilen Sie, was Sie gebaut haben. Ihre Einreichung wird gescannt, bevor sie in die Schaufenster-Liste aufgenommen wird.',
      ja: '構築したものを共有してください。提出物はショーケースリストに登録される前にスキャンされます。',
      ko: '빌드한 것을 공유하세요. 제출물은 쇼케이스 목록에 제출되기 전에 스캔됩니다.',
      zh: '分享您构建的内容。您的提交将在提交到展示列表之前经过扫描。',
      it: "Condividi ciò che hai costruito. La tua sottomissione verrà scansionata prima di essere inviata all'elenco della vetrina.",
      pt: 'Compartilhe o que você construiu. Seu envio será verificado antes de ser enviado para a lista da vitrine.',
      hi: 'जो आपने बनाया है उसे साझा करें। आपके सबमिशन को शोकेस सूची में जमा करने से पहले स्कैन किया जाएगा।',
      ar: 'شارك ما بنيته. سيتم فحص إرسالك قبل تقديمه في قائمة العرض.',
      ru: 'Поделитесь тем, что вы создали. Ваша заявка будет отсканирована перед отправкой в список витрины.',
      tr: 'Neler oluşturduğunuzu paylaşın. Gönderiniz, vitrin listesine eklenmeden önce taranacaktır.',
      pl: 'Podziel się tym, co zbudowałeś. Twoje zgłoszenie zostanie przeskanowane przed dodaniem do listy projektów.',
      id: 'Bagikan apa yang telah Anda buat. Kiriman Anda akan dipindai sebelum dimasukkan ke dalam daftar showcase.',
      uk: 'Поділіться тим, що ви створили. Ваша заявка буде перевірена перед додаванням до списку вітрини.',
      vi: 'Chia sẻ những gì bạn đã xây dựng. Bản gửi của bạn sẽ được quét trước khi đưa vào danh sách trưng bày.',
    }),
    projectNameInput: {
      label: t({
        en: 'Project Name',
        'en-GB': 'Project Name',
        fr: 'Nom du projet',
        es: 'Nombre del proyecto',
        de: 'Projektname',
        ja: 'プロジェクト名',
        ko: '프로젝트 이름',
        zh: '项目名称',
        it: 'Nome del progetto',
        pt: 'Nome do projeto',
        hi: 'प्रोजेक्ट का नाम',
        ar: 'اسم المشروع',
        ru: 'Название проекта',
        tr: 'Proje Adı',
        pl: 'Nazwa projektu',
        id: 'Nama Proyek',
        uk: 'Назва проекту',
        vi: 'Tên dự án',
      }),
      placeholder: t({
        en: 'My Awesome App',
        'en-GB': 'My Awesome App',
        fr: 'Ma Super App',
        es: 'Mi aplicación increíble',
        de: 'Meine tolle App',
        ja: '私の素晴らしいアプリ',
        ko: '내 멋진 앱',
        zh: '我的超棒应用',
        it: 'La mia fantastica app',
        pt: 'Meu aplicativo incrível',
        hi: 'मेरा अद्भुत ऐप',
        ar: 'تطبيقي الرائع',
        ru: 'Мое потрясающее приложение',
        tr: 'Harika Uygulamam',
        pl: 'Moja świetna aplikacja',
        id: 'Aplikasi Keren Saya',
        uk: 'Мій чудовий додаток',
        vi: 'Ứng dụng tuyệt vời của tôi',
      }),
    },
    projectUrlInput: {
      label: t({
        en: 'Project URL',
        'en-GB': 'Project URL',
        fr: 'URL du projet',
        es: 'URL del proyecto',
        de: 'Projekt-URL',
        ja: 'プロジェクトのURL',
        ko: '프로젝트 URL',
        zh: '项目URL',
        it: 'URL del progetto',
        pt: 'URL do projeto',
        hi: 'प्रोजेक्ट URL',
        ar: 'رابط المشروع',
        ru: 'URL проекта',
        tr: "Proje URL'si",
        pl: 'URL projektu',
        id: 'URL Proyek',
        uk: 'URL проекту',
        vi: 'URL dự án',
      }),
      placeholder: t({
        en: 'https://your-project.com',
        'en-GB': 'https://your-project.com',
        fr: 'https://votre-projet.com',
        es: 'https://tu-proyecto.com',
        de: 'https://ihr-projekt.de',
        ja: 'https://your-project.com',
        ko: 'https://your-project.com',
        zh: 'https://your-project.com',
        it: 'https://tuo-progetto.it',
        pt: 'https://seu-projeto.com',
        hi: 'https://your-project.com',
        ar: 'https://your-project.com',
        ru: 'https://vash-proekt.ru',
        tr: 'https://projeniz.com',
        pl: 'https://twoj-projekt.pl',
        id: 'https://proyek-anda.com',
        uk: 'https://vash-proekt.com',
        vi: 'https://du-an-cua-ban.com',
      }),
    },
    githubUrlInput: {
      label: t({
        en: 'GitHub URL',
        'en-GB': 'GitHub URL',
        fr: 'URL GitHub',
        es: 'URL de GitHub',
        de: 'GitHub-URL',
        ja: 'GitHubのURL',
        ko: 'GitHub URL',
        zh: 'GitHub URL',
        it: 'URL di GitHub',
        pt: 'URL do GitHub',
        hi: 'GitHub URL',
        ar: 'رابط GitHub',
        ru: 'GitHub URL',
        tr: "GitHub URL'si",
        pl: 'URL GitHub',
        id: 'URL GitHub',
        uk: 'GitHub URL',
        vi: 'URL GitHub',
      }),
      placeholder: t({
        en: 'https://github.com/your-username/your-repo',
        'en-GB': 'https://github.com/your-username/your-repo',
        fr: 'https://github.com/votre-nom/votre-depot',
        es: 'https://github.com/tu-usuario/tu-repo',
        de: 'https://github.com/ihr-benutzer/ihr-repo',
        ja: 'https://github.com/your-username/your-repo',
        ko: 'https://github.com/your-username/your-repo',
        zh: 'https://github.com/your-username/your-repo',
        it: 'https://github.com/tuo-utente/tuo-repo',
        pt: 'https://github.com/seu-usuario/seu-repo',
        hi: 'https://github.com/your-username/your-repo',
        ar: 'https://github.com/your-username/your-repo',
        ru: 'https://github.com/vash-polzovatel/vash-repo',
        tr: 'https://github.com/kullanici-adiniz/deponuz',
        pl: 'https://github.com/twoja-nazwa/twoje-repo',
        id: 'https://github.com/username-anda/repo-anda',
        uk: 'https://github.com/vash-login/vash-repo',
        vi: 'https://github.com/ten-dang-nhap/kho-cua-ban',
      }),
    },
    taglineInput: {
      label: t({
        en: 'Tagline',
        'en-GB': 'Tagline',
        fr: 'Slogan',
        es: 'Eslogan',
        de: 'Slogan',
        ja: 'キャッチフレーズ',
        ko: '태그라인',
        zh: '标语',
        it: 'Slogan',
        pt: 'Slogan',
        hi: 'टैगलाइन',
        ar: 'الشعار',
        ru: 'Слоган',
        tr: 'Slogan',
        pl: 'Slogan',
        id: 'Tagline',
        uk: 'Слоган',
        vi: 'Slogan',
      }),
      placeholder: t({
        en: 'A brief description of your project',
        'en-GB': 'A brief description of your project',
        fr: 'Une brève description de votre projet',
        es: 'Una breve descripción de tu proyecto',
        de: 'Eine kurze Beschreibung Ihres Projekts',
        ja: 'プロジェクトの簡単な説明',
        ko: '프로젝트에 대한 간단한 설명',
        zh: '对您的项目的简短描述',
        it: 'Una breve descrizione del tuo progetto',
        pt: 'Uma breve descrizione do seu projeto',
        hi: 'आपके प्रोजेक्ट का एक संक्षिप्त विवरण',
        ar: 'وصف موجز لمشروعك',
        ru: 'Краткое описание вашего проекта',
        tr: 'Projenizin kısa bir açıklaması',
        pl: 'Krótki opis Twojego projektu',
        id: 'Deskripsi singkat proyek Anda',
        uk: 'Короткий опис вашого проекту',
        vi: 'Mô tả ngắn gọn về dự án của bạn',
      }),
      charactersInfo: insert(
        t({
          en: '{{count}}/500 characters',
          'en-GB': '{{count}}/500 characters',
          fr: '{{count}}/500 caractères',
          es: '{{count}}/500 caracteres',
          de: '{{count}}/500 Zeichen',
          ja: '{{count}}/500文字',
          ko: '{{count}}/500자',
          zh: '{{count}}/500 个字符',
          it: '{{count}}/500 caratteri',
          pt: '{{count}}/500 caracteres',
          hi: '{{count}}/500 वर्ण',
          ar: '{{count}}/500 حرف',
          ru: '{{count}}/500 символов',
          tr: '{{count}}/500 karakter',
          pl: '{{count}}/500 znaków',
          id: '{{count}}/500 karakter',
          uk: '{{count}}/500 символів',
          vi: '{{count}}/500 ký tự',
        })
      ),
    },
    descriptionInput: {
      label: t({
        en: 'Description',
        'en-GB': 'Description',
        fr: 'Description',
        es: 'Descripción',
        de: 'Beschreibung',
        ja: '説明',
        ko: '설명',
        zh: '描述',
        it: 'Descrizione',
        pt: 'Descrição',
        hi: 'विवरण',
        ar: 'الوصف',
        ru: 'Описание',
        tr: 'Açıklama',
        pl: 'Opis',
        id: 'Deskripsi',
        uk: 'Опис',
        vi: 'Mô tả',
      }),
      placeholder: t({
        en: 'Tell us more about your project...',
        'en-GB': 'Tell us more about your project...',
        fr: 'Dites-nous en plus sur votre projet...',
        es: 'Cuéntanos más sobre tu proyecto...',
        de: 'Erzählen Sie uns mehr über Ihr Projekt...',
        ja: 'プロジェクトについてもっと教えてください...',
        ko: '프로젝트에 대해 더 알려주세요...',
        zh: '告诉我们更多关于您的项目...',
        it: 'Raccontaci di più sul tuo progetto...',
        pt: 'Conte-nos mais sobre seu projeto...',
        hi: 'हमें अपने प्रोजेक्ट के बारे में और बताएं...',
        ar: 'أخبرنا المزيد عن مشروعค...',
        ru: 'Расскажите нам больше о вашем проекте...',
        tr: 'Projeniz hakkında bize daha fazla bilgi verin...',
        pl: 'Opowiedz nam więcej o swoim projekcie...',
        id: 'Beri tahu kami lebih banyak tentang proyek Anda...',
        uk: 'Розкажіть нам більше про свій проект...',
        vi: 'Hãy cho chúng tôi biết thêm về dự án của bạn...',
      }),
    },
    useCasesInput: {
      label: t({
        en: 'Use Cases',
        'en-GB': 'Use Cases',
        fr: "Cas d'utilisation",
        es: 'Casos de uso',
        de: 'Anwendungsfälle',
        ja: 'ユースケース',
        ko: '사용 사례',
        zh: '使用案例',
        it: "Casi d'uso",
        pt: 'Casos de uso',
        hi: 'उपयोग के मामले',
        ar: 'حالات الاستخدام',
        ru: 'Сценарии использования',
        tr: 'Kullanım Durumları',
        pl: 'Przypadki użycia',
        id: 'Kasus Penggunaan',
        uk: 'Сценарії використання',
        vi: 'Trường hợp sử dụng',
      }),
      placeholder: t({
        en: 'Select use cases...',
        'en-GB': 'Select use cases...',
        fr: "Sélectionnez des cas d'utilisation...",
        es: 'Seleccione casos de uso...',
        de: 'Anwendungsfälle auswählen...',
        ja: 'ユースケースを選択...',
        ko: '사용 사례 선택...',
        zh: '选择使用案例...',
        it: "Seleziona casi d'uso...",
        pt: 'Selecione casos de uso...',
        hi: 'उपयोग के मामले चुनें...',
        ar: 'حدد حالات الاستخدام...',
        ru: 'Выберите сценарии использования...',
        tr: 'Kullanım durumlarını seçin...',
        pl: 'Wybierz przypadki użycia...',
        id: 'Pilih kasus penggunaan...',
        uk: 'Виберіть сценарії використання...',
        vi: 'Chọn trường hợp sử dụng...',
      }),
      description: t({
        en: 'Optional: Help others discover your project by category',
        'en-GB': 'Optional: Help others discover your project by category',
        fr: 'Optionnel : Aidez les autres à découvrir votre projet par catégorie',
        es: 'Opcional: Ayuda a otros a descubrir tu proyecto por categoría',
        de: 'Optional: Helfen Sie anderen, Ihr Projekt nach Kategorie zu entdecken',
        ja: 'オプション：カテゴリ別にプロジェクトを見つけてもらいやすくします',
        ko: '선택 사항: 다른 사람들이 카테고리별로 프로젝트를 발견할 수 있도록 도와주세요',
        zh: '可选：帮助他人按类别发现您的项目',
        it: 'Opzionale: aiuta gli altri a scoprire il tuo progetto per categoria',
        pt: 'Opcional: ajude outras pessoas a descobrir seu projeto por categoria',
        hi: 'वैकल्पिक: श्रेणी के अनुसार दूसरों को आपका प्रोजेक्ट खोजने में मदद करें',
        ar: 'اختياري: ساعد الآخرين على اكتشاف مشروعك حسب الفئة',
        ru: 'Необязательно: помогите другим найти ваш проект по категории',
        tr: 'İsteğe bağlı: Başkalarının projenizi kategoriye göre keşfetmesine yardımcı olun',
        pl: 'Opcjonalnie: Pomóż innym odkryć Twój projekt według kategorii',
        id: 'Opsional: Bantu orang lain menemukan proyek Anda berdasarkan kategori',
        uk: "Необов'язково: допоможіть іншим знайти ваш проект за категорією",
        vi: 'Tùy chọn: Giúp người khác khám phá dự án của bạn theo danh mục',
      }),
    },
    submitButton: {
      label: t({
        en: 'Submit for Review',
        'en-GB': 'Submit for Review',
        fr: 'Soumettre pour révision',
        es: 'Enviar para revisión',
        de: 'Zur Überprüfung einreichen',
        ja: 'レビューのために提出する',
        ko: '검토를 위해 제출',
        zh: '提交审核',
        it: 'Invia per revisione',
        pt: 'Enviar para revisão',
        hi: 'समीक्षा के लिए सबमिट करें',
        ar: 'إرسال للمراجعة',
        ru: 'Отправить на проверку',
        tr: 'İnceleme İçin Gönder',
        pl: 'Wyślij do recenzji',
        id: 'Kirim untuk Ditinjau',
        uk: 'Надіслати на перевірку',
        vi: 'Gửi để xem xét',
      }),
    },
    modal: {
      title: t({
        en: 'Processing Submission',
        'en-GB': 'Processing Submission',
        fr: 'Traitement de la soumission',
        es: 'Procesando el envío',
        de: 'Einreichung wird bearbeitet',
        ja: '提出を処理しています',
        ko: '제출 처리 중',
        zh: '正在处理提交',
        it: 'Elaborazione della sottomissione',
        pt: 'Processando envio',
        hi: 'सबमिशन प्रोसेस हो रहा है',
        ar: 'جاري معالجة التقديم',
        ru: 'Обработка отправки',
        tr: 'Gönderim İşleniyor',
        pl: 'Przetwarzanie zgłoszenia',
        id: 'Memproses Kiriman',
        uk: 'Обробка заявки',
        vi: 'Đang xử lý bản gửi',
      }),
      successTitle: t({
        en: 'Success!',
        'en-GB': 'Success!',
        fr: 'Succès !',
        es: '¡Éxito!',
        de: 'Erfolg!',
        ja: '成功！',
        ko: '성공!',
        zh: '成功！',
        it: 'Successo!',
        pt: 'Sucesso!',
        hi: 'सफलता!',
        ar: 'نجاح!',
        ru: 'Успех!',
        tr: 'Başarılı!',
        pl: 'Sukces!',
        id: 'Berhasil!',
        uk: 'Успіх!',
        vi: 'Thành công!',
      }),
      successMessage: t({
        en: 'Your project has been successfully submitted and verified.',
        'en-GB': 'Your project has been successfully submitted and verified.',
        fr: 'Votre projet a été soumis et vérifié avec succès.',
        es: 'Su proyecto ha sido enviado y verificado con éxito.',
        de: 'Ihr Projekt wurde erfolgreich eingereicht und überprüft.',
        ja: 'プロジェクトは正常に送信され、確認されました。',
        ko: '프로젝트가 성공적으로 제출되고 확인되었습니다.',
        zh: '您的项目已成功提交并验证。',
        it: 'Il tuo progetto è stato inviato e verificato con successo.',
        pt: 'Seu projeto foi enviado e verificado com successo.',
        hi: 'आपका प्रोजेक्ट सफलतापूर्वक सबमिट और सत्यापित हो गया है।',
        ar: 'تم تقديم مشروعك والتحقق منه بنجاح.',
        ru: 'Ваш проект был успешно отправлен и проверен.',
        tr: 'Projeniz başarıyla gönderildi ve doğrulandı.',
        pl: 'Twój projekt został pomyślnie przesłany i zweryfikowany.',
        id: 'Proyek Anda telah berhasil dikirim dan diverifikasi.',
        uk: 'Ваш проект був успішно надісланий та перевірений.',
        vi: 'Dự án của bạn đã được gửi và xác minh thành công.',
      }),
      errorTitle: t({
        en: 'Submission Failed',
        'en-GB': 'Submission Failed',
        fr: 'Échec de la soumission',
        es: 'El envío falló',
        de: 'Einreichung fehlgeschlagen',
        ja: '提出に失敗しました',
        ko: '제출 실패',
        zh: '提交失败',
        it: 'Invio fallito',
        pt: 'Falha no envio',
        hi: 'सबमिशन विफल रहा',
        ar: 'فشل التقديم',
        ru: 'Ошибка отправки',
        tr: 'Gönderim Başarısız',
        pl: 'Przesyłanie nie powiodło się',
        id: 'Kiriman Gagal',
        uk: 'Помилка відправлення',
        vi: 'Gửi thất bại',
      }),
      closeButton: t({
        en: 'Close',
        'en-GB': 'Close',
        fr: 'Fermer',
        es: 'Cerrar',
        de: 'Schließen',
        ja: '閉じる',
        ko: '닫기',
        zh: '关闭',
        it: 'Chiudi',
        pt: 'Fechar',
        hi: 'बंद करें',
        ar: 'إغلاق',
        ru: 'Закрыть',
        tr: 'Kapat',
        pl: 'Zamknij',
        id: 'Tutup',
        uk: 'Закрити',
        vi: 'Đóng',
      }),
      goToDashboardButton: t({
        en: 'Go to Dashboard',
        'en-GB': 'Go to Dashboard',
        fr: 'Aller au tableau de bord',
        es: 'Ir al panel',
        de: 'Zum Dashboard gehen',
        ja: 'ダッシュボードに行く',
        ko: '대시보드로 이동',
        zh: '去仪表板',
        it: 'Vai alla dashboard',
        pt: 'Ir para o painel',
        hi: 'डैशबोर्ड पर जाएं',
        ar: 'الذهاب إلى لوحة القيادة',
        ru: 'Перейти к панели управления',
        tr: 'Panele Git',
        pl: 'Przejdź do panelu',
        id: 'Buka Dashboard',
        uk: 'Перейти до панелі керування',
        vi: 'Đi đến bảng điều khiển',
      }),
      steps: {
        verifyBundle: t({
          en: 'Verifying Intlayer usage on website...',
          'en-GB': 'Verifying Intlayer usage on website...',
          fr: "Vérification de l'utilisation d'Intlayer sur le site web...",
          es: 'Verificando el uso de Intlayer en el sitio web...',
          de: 'Überprüfung der Intlayer-Nutzung auf der Website...',
          ja: 'ウェブサイトでのIntlayerの使用を確認しています...',
          ko: '웹사이트에서 Intlayer 사용 확인 중...',
          zh: '正在验证网站上的 Intlayer 使用情况...',
          it: "Verifica dell'uso di Intlayer sul sito web...",
          pt: 'Verificando o uso do Intlayer no site...',
          hi: 'वेबसाइट पर Intlayer उपयोग की पुष्टि की जा रही है...',
          ar: 'جاري التحقق من استخدام Intlayer على الموقع الإلكتروني...',
          ru: 'Проверка использования Intlayer на сайте...',
          tr: 'Web sitesinde Intlayer kullanımı doğrulanıyor...',
          pl: 'Weryfikacja użycia Intlayer na stronie...',
          id: 'Memverifikasi penggunaan Intlayer di situs web...',
          uk: 'Перевірка використання Intlayer на сайті...',
          vi: 'Đang xác minh việc sử dụng Intlayer trên trang web...',
        }),
        verifyGithub: t({
          en: 'Checking GitHub repository...',
          'en-GB': 'Checking GitHub repository...',
          fr: 'Vérification du dépôt GitHub...',
          es: 'Comprobando el repositorio de GitHub...',
          de: 'GitHub-Repository wird überprüft...',
          ja: 'GitHubリポジトリを確認しています...',
          ko: 'GitHub 저장소 확인 중...',
          zh: '正在检查 GitHub 存储库...',
          it: 'Controllo del repository GitHub...',
          pt: 'Verificando repositório do GitHub...',
          hi: 'GitHub रिपॉजिटरी की जाँच की जा रही है...',
          ar: 'جاري فحص مستودع GitHub...',
          ru: 'Проверка репозитория GitHub...',
          tr: 'GitHub deposu kontrol ediliyor...',
          pl: 'Sprawdzanie repozytorium GitHub...',
          id: 'Memeriksa repositori GitHub...',
          uk: 'Перевірка репозиторію GitHub...',
          vi: 'Đang kiểm tra kho lưu trữ GitHub...',
        }),
        screenshotAndSave: t({
          en: 'Generating screenshot and saving...',
          'en-GB': 'Generating screenshot and saving...',
          fr: "Génération de la capture d'écran et sauvegarde...",
          es: 'Generando captura de pantalla y guardando...',
          de: 'Screenshot wird erstellt und gespeichert...',
          ja: 'スクリーンショットを生成して保存しています...',
          ko: '스크린샷 생성 및 저장 중...',
          zh: '正在生成屏幕截图并保存...',
          it: 'Generazione dello screenshot e salvataggio...',
          pt: 'Gerando captura de tela e salvando...',
          hi: 'स्क्रीनशॉट जेनरेट और सेव किया जा रहा है...',
          ar: 'جاري إنشاء لقطة شاشة وحفظها...',
          ru: 'Генерация скриншота и сохранение...',
          tr: 'Ekran görüntüsü oluşturuluyor ve kaydediliyor...',
          pl: 'Generowanie zrzutu ekranu i zapisywanie...',
          id: 'Membuat tangkapan layar dan menyimpan...',
          uk: 'Створення знімка екрана та збереження...',
          vi: 'Đang tạo ảnh chụp màn hình và lưu...',
        }),
      },
    },
    backToShowcase: t({
      en: 'Back to Showcase Gallery',
      'en-GB': 'Back to Showcase Gallery',
      fr: 'Retour à la galerie Showcase',
      es: 'Volver a la galería de Showcase',
      de: 'Zurück zur Showcase-Galerie',
      ja: 'ショーケースギャラリーに戻る',
      ko: '쇼케이스 갤러리로 돌아가기',
      zh: '回到展示图库',
      it: 'Torna alla galleria Showcase',
      pt: 'Voltar para a Galeria Showcase',
      hi: 'शोकेस गैलरी पर वापस जाएं',
      ar: 'العودة إلى معرض المواقع',
      uk: 'Назад до вітрини',
      ru: 'Назад в галерею',
      tr: 'Vitrin Galerisine Dön',
      pl: 'Powrót do galerii projektów',
      id: 'Kembali ke Galeri Showcase',
      vi: 'Quay lại Showcase',
    }),
  },
} satisfies Dictionary;

export default submitProjectFormContent;
