import { type Dictionary, t } from 'intlayer';

const useSubmitProjectFormSchemaContent = {
  key: 'submit-project-form-schema',
  content: {
    projectNameRequired: t({
      en: 'Project Name is required',
      'en-GB': 'Project Name is required',
      fr: 'Le nom du projet est requis',
      es: 'El nombre del proyecto es obligatoire',
      de: 'Projektname ist erforderlich',
      ja: 'プロジェクト名は必須です',
      ko: '프로젝트 이름은 필수입니다',
      zh: '项目名称是必填项',
      it: 'Il nome del progetto è obbligatorio',
      pt: 'O nome do projet est obligatoire',
      hi: 'प्रोजेक्ट का नाम आवश्यक है',
      ar: 'اسم المشروع مطلوب',
      ru: 'Название проекта обязательно',
      tr: 'Proje Adı zorunludur',
      pl: 'Nazwa projektu jest wymagana',
      id: 'Nama Proyek wajib diisi',
      uk: "Назва проекту обов'язкова",
      vi: 'Tên dự án là bắt buộc',
    }),
    urlInvalid: t({
      en: 'Must be a valid URL',
      'en-GB': 'Must be a valid URL',
      fr: 'Doit être une URL valide',
      es: 'Debe ser una URL válida',
      de: 'Muss eine gültige URL sein',
      ja: '有効なURLである必要があります',
      ko: '유효한 URL이어야 합니다',
      zh: '必须是有效的URL',
      it: 'Deve essere un URL valido',
      pt: 'Deve ser um URL válido',
      hi: 'एक मान्य URL होना चाहिए',
      ar: 'يجب أن يكون رابطًا صالحًا',
      ru: 'Должен быть действительным URL-адресом',
      tr: 'Geçerli bir URL olmalıdır',
      pl: 'Musi być prawidłowym adresem URL',
      id: 'Harus berupa URL yang valid',
      uk: 'Має бути дійсною URL-адресою',
      vi: 'Phải là một URL hợp lệ',
    }),
    projectUrlRequired: t({
      en: 'Project URL is required',
      'en-GB': 'Project URL is required',
      fr: "L'URL du projet est requise",
      es: 'La URL del proyecto est obligatoria',
      de: 'Projekt-URL ist erforderlich',
      ja: 'プロジェクトのURLは必須です',
      ko: '프로젝트 URL은 필수입니다',
      zh: '项目URL est 必填项',
      it: "L'URL del progetto è obbligatorio",
      pt: 'A URL do projeto é obrigatória',
      hi: 'प्रोजेक्ट URL आवश्यक है',
      ar: 'رابط المشروع مطلوب',
      ru: 'URL проекта обязателен',
      tr: "Proje URL'si zorunludur",
      pl: 'URL projektu jest wymagany',
      id: 'URL Proyek wajib diisi',
      uk: "URL проекту обов'язковий",
      vi: 'URL dự án là bắt buộc',
    }),
    taglineRequired: t({
      en: 'Tagline is required',
      'en-GB': 'Tagline is required',
      fr: 'Le slogan est requis',
      es: 'El eslogan es obligatorio',
      de: 'Slogan ist erforderlich',
      ja: 'キャッチフレーズは必須です',
      ko: '태그라인은 필수입니다',
      zh: '标语 est 必填项',
      it: 'Lo slogan è obbligatorio',
      pt: 'O slogan é obligatorio',
      hi: 'टैगलाइन आवश्यक है',
      ar: 'الشعار مطلوب',
      ru: 'Слоган обязателен',
      tr: 'Slogan zorunludur',
      pl: 'Slogan jest wymagany',
      id: 'Tagline wajib diisi',
      uk: "Слоган обов'язковий",
      vi: 'Slogan là bắt buộc',
    }),
    descriptionRequired: t({
      en: 'Description is required',
      'en-GB': 'Description is required',
      fr: 'La description est requise',
      es: 'La descripción es obligatoria',
      de: 'Beschreibung ist erforderlich',
      ja: '説明は必須です',
      ko: '설명이 필요합니다',
      zh: '描述是必须的',
      it: 'La descrizione è obbligatoria',
      pt: 'A descripción è obrigatória',
      hi: 'विवरण आवश्यक है',
      ar: 'الوصف مطلوب',
      ru: 'Описание обязательно',
      tr: 'Açıklama zorunludur',
      pl: 'Opis jest wymagany',
      id: 'Deskripsi wajib diisi',
      uk: "Опис обов'язковий",
      vi: 'Mô tả là bắt buộc',
    }),
    maxUseCases: t({
      en: 'Max 3 use cases allowed',
      'en-GB': 'Max 3 use cases allowed',
      fr: 'Maximum 3 cas d’utilisation autorisés',
      es: 'Máximo 3 casos de uso permitidos',
      de: 'Maximal 3 Anwendungsfälle erlaubt',
      ja: '最大3つのユースケースが許可されています',
      ko: '최대 3개의 유스케이스가 허용됩니다',
      zh: '最多允许3个用例',
      it: 'Massimo 3 casi d’uso consentiti',
      pt: 'Máximo 3 casos de uso permitidos',
      hi: 'अधिकतम 3 उपयोग के मामलों की अनुमति है',
      ar: 'يسمح بحد أقصى 3 حالات استخدام',
      ru: 'Разрешено не более 3 вариантов использования',
      tr: 'En fazla 3 kullanım durumuna izin verilir',
      pl: 'Dozwolone maksymalnie 3 przypadki użycia',
      id: 'Maksimum 3 kasus penggunaan diizinkan',
      uk: 'Дозволено максимум 3 варіанти використання',
      vi: 'Tối đa 3 trường hợp sử dụng được phép',
    }),
  },
} satisfies Dictionary;

export default useSubmitProjectFormSchemaContent;
