import { type DeclarationContent, t } from 'intlayer';

export const resetPasswordContent = {
  key: 'reset-password',
  content: {
    emailInput: {
      label: t({
        en: 'Email address',
        fr: 'Adresse e-mail',
        es: 'Dirección de correo electrónico',
        'en-GB': 'Email address',
        de: 'E-Mail-Adresse',
        ja: '電子メールアドレス',
        ko: '이메일 주소',
        zh: '电子邮件地址',
        it: 'Indirizzo email',
        pt: 'Endereço de e-mail',
        hi: 'ईमेल पता',
        ar: 'عنوان البريد الإلكتروني',
        ru: 'Адрес электронной почты',
      }),
      placeholder: t({
        en: 'Enter e-mail address',
        fr: 'Entrez votre adresse e-mail',
        es: 'Ingrese su dirección de correo electrónico',
        'en-GB': 'Enter e-mail address',
        de: 'Geben Sie die E-Mail-Adresse ein',
        ja: 'メールアドレスを入力してください',
        ko: '이메일 주소를 입력하세요',
        zh: '输入电子邮件地址',
        it: "Inserisci l'indirizzo email",
        pt: 'Insira o endereço de e-mail',
        hi: 'ईमेल पता दर्ज करें',
        ar: 'أدخل عنوان البريد الإلكتروني',
        ru: 'Введите адрес электронной почты',
      }),
    },
    sendRecoveryEmailButton: {
      text: t({
        en: 'Send recovery email',
        fr: 'Envoyer un e-mail de récupération',
        es: 'Enviar correo de recuperación',
        'en-GB': 'Send recovery email',
        de: 'Wiederherstellungs-E-Mail senden',
        ja: '回復メールを送信',
        ko: '복구 이메일 전송',
        zh: '发送恢复电子邮件',
        it: 'Invia email di recupero',
        pt: 'Enviar e-mail de recuperação',
        hi: 'पुनर्प्राप्ति ईमेल भेजें',
        ar: 'إرسال بريد إلكتروني لاستعادة كلمة المرور',
        ru: 'Отправить письмо для восстановления',
      }),
      ariaLabel: t({
        en: 'Click to send recovery email',
        fr: 'Cliquez pour envoyer un e-mail de récupération',
        es: 'Haz clic para enviar correo de recuperación',
        'en-GB': 'Click to send recovery email',
        de: 'Klicken Sie, um die Wiederherstellungs-E-Mail zu senden',
        ja: '回復メールを送信するにはクリックしてください',
        ko: '복구 이메일을 보내려면 클릭하세요',
        zh: '点击发送恢复电子邮件',
        it: "Clicca per inviare l'email di recupero",
        pt: 'Clique para enviar o e-mail de recuperação',
        hi: 'पुनर्प्राप्ति ईमेल भेजने के लिए क्लिक करें',
        ar: 'انقر لإرسال بريد إلكتروني لاستعادة كلمة المرور',
        ru: 'Щелкните, чтобы отправить электронное письмо для восстановления',
      }),
    },
    resendRecoveryEmailButton: {
      text: t({
        en: 'Resend recovery email',
        fr: 'Renvoyer l’e-mail de récupération',
        es: 'Reenviar correo de recuperación',
        'en-GB': 'Resend recovery email',
        de: 'Wiederherstellungs-E-Mail erneut senden',
        ja: '回復メールを再送信',
        ko: '복구 이메일 재전송',
        zh: '重新发送恢复电子邮件',
        it: "Invia di nuovo l'email di recupero",
        pt: 'Reenviar e-mail de recuperação',
        hi: 'पुनर्प्राप्ति ईमेल पुनः भेजें',
        ar: 'إعادة إرسال البريد الإلكتروني لاستعادة كلمة المرور',
        ru: 'Повторно отправить письмо для восстановления',
      }),
    },
    resendInText: t({
      en: 'Resend in',
      fr: 'Renvoyer dans',
      es: 'Reenviar en',
      'en-GB': 'Resend in',
      de: 'Erneut senden in',
      ja: '再送信まで',
      ko: '다시 전송하기까지',
      zh: '重新发送',
      it: 'Reinvia in',
      pt: 'Reenviar em',
      hi: 'फिर से भेजें',
      ar: 'إعادة الإرسال في',
      ru: 'Повторно отправить через',
    }),
    backToLoginButton: {
      text: t({
        en: 'Back to login',
        fr: 'Retour à la connexion',
        es: 'Volver al inicio de sesión',
        'en-GB': 'Back to login',
        de: 'Zurück zur Anmeldung',
        ja: 'ログインに戻る',
        ko: '로그인으로 돌아가기',
        zh: '返回登录',
        it: 'Torna al login',
        pt: 'Voltar ao login',
        hi: 'लॉगइन पर वापस जाएं',
        ar: 'العودة إلى تسجيل الدخول',
        ru: 'Вернуться к входу',
      }),
    },
  },
} satisfies DeclarationContent;
