import { type Dictionary, insert, t } from 'intlayer';

const electronUpdaterContent = {
  key: 'electron-updater',
  content: {
    updateAvailableVersion: insert(
      t({
        en: 'Update available — v{{version}}',
        fr: 'Mise à jour disponible — v{{version}}',
        ru: 'Доступно обновление — v{{version}}',
        ja: 'アップデートが利用可能です — v{{version}}',
        ko: '업데이트 가능 — v{{version}}',
        zh: '可用更新 — v{{version}}',
        es: 'Actualización disponible — v{{version}}',
        de: 'Update verfügbar — v{{version}}',
        ar: 'التحديث متاح — v{{version}}',
        it: 'Aggiornamento disponibile — v{{version}}',
        'en-GB': 'Update available — v{{version}}',
        pt: 'Atualização disponível — v{{version}}',
        hi: 'अपडेट उपलब्ध — v{{version}}',
        tr: 'Güncelleme mevcut — v{{version}}',
        pl: 'Dostępna aktualizacja — v{{version}}',
        id: 'Pembaruan tersedia — v{{version}}',
        vi: 'Có bản cập nhật — v{{version}}',
        uk: 'Доступне оновлення — v{{version}}',
      })
    ),

    aNewVersionOfIntlayer: t({
      en: 'A new version of Intlayer is ready to download.',
      fr: 'Une nouvelle version de Intlayer est prête à être téléchargée.',
      ru: 'Новая версия Intlayer готова к загрузке.',
      ja: 'Intlayerの新しいバージョンがダウンロード可能です。',
      ko: 'Intlayer의 새 버전을 다운로드할 준비가 되었습니다.',
      zh: 'Intlayer 的新版本已准备好下载状态。',
      es: 'Una nueva versión de Intlayer está lista para descargar.',
      de: 'Eine neue Version von Intlayer ist zum Download bereit.',
      ar: 'نسخة جديدة من Intlayer جاهزة للتنزيل.',
      it: 'Una nuova versione di Intlayer è pronta per il download.',
      'en-GB': 'A new version of Intlayer is ready to download.',
      pt: 'Uma nova versão do Intlayer está pronta para baixar.',
      hi: 'Intlayer का एक नया संस्करण डाउनलोड के लिए तैयार है।',
      tr: "Intlayer'ın yeni bir sürümü indirilmeye hazır.",
      pl: 'Nowa wersja Intlayer jest gotowa do pobrania.',
      id: 'Versi baru Intlayer siap diunduh.',
      vi: 'Một phiên bản mới của Intlayer đã sẵn sàng để tải về.',
      uk: 'Нова версія Intlayer готова до завантаження.',
    }),

    downloadUpdate: t({
      en: 'Download update',
      fr: 'Télécharger la mise à jour',
      ru: 'Загрузить обновление',
      ja: 'アップデートをダウンロード',
      ko: '업데이트 다운로드',
      zh: '下载更新',
      es: 'Descargar actualización',
      de: 'Update herunterladen',
      ar: 'تنزيل التحديث',
      it: 'Scarica aggiornamento',
      'en-GB': 'Download update',
      pt: 'Baixar atualização',
      hi: 'अपडेट डाउनलोड करें',
      tr: 'Güncellemeyi indir',
      pl: 'Pobierz aktualizację',
      id: 'Unduh pembaruan',
      vi: 'Tải bản cập nhật',
      uk: 'Завантажити оновлення',
    }),

    download: t({
      en: 'Download',
      fr: 'Télécharger',
      ru: 'Загрузить',
      ja: 'ダウンロード',
      ko: '다운로드',
      zh: '下载',
      es: 'Descargar',
      de: 'Download',
      ar: 'تنزيل',
      it: 'Scarica',
      'en-GB': 'Download',
      pt: 'Baixar',
      hi: 'डाउनलोड',
      tr: 'İndir',
      pl: 'Pobierz',
      id: 'Unduh',
      vi: 'Tải về',
      uk: 'Завантажити',
    }),

    dismiss: t({
      en: 'Dismiss',
      fr: 'Ignorer',
      ru: 'Отклонить',
      ja: '閉じる',
      ko: '무시',
      zh: '忽略',
      es: 'Descartar',
      de: 'Verwerfen',
      ar: 'تجاهل',
      it: 'Ignora',
      'en-GB': 'Dismiss',
      pt: 'Descartar',
      hi: 'खारिज करें',
      tr: 'Kapat',
      pl: 'Odrzuć',
      id: 'Abaikan',
      vi: 'Bỏ qua',
      uk: 'Відхилити',
    }),

    later: t({
      en: 'Later',
      fr: 'Plus tard',
      ru: 'Позже',
      ja: '後で',
      ko: '나중에',
      zh: '稍后',
      es: 'Más tarde',
      de: 'Später',
      ar: 'لاحقاً',
      it: 'Più tardi',
      'en-GB': 'Later',
      pt: 'Depois',
      hi: 'बाद में',
      tr: 'Sonra',
      pl: 'Później',
      id: 'Nanti',
      vi: 'Sau',
      uk: 'Пізніше',
    }),

    downloadingPercent: insert(
      t({
        en: 'Downloading… {{percent}}%',
        fr: 'Téléchargement… {{percent}}%',
        ru: 'Загрузка… {{percent}}%',
        ja: 'ダウンロード中… {{percent}}%',
        ko: '다운로드 중… {{percent}}%',
        zh: '正在下载… {{percent}}%',
        es: 'Descargando… {{percent}}%',
        de: 'Wird heruntergeladen… {{percent}}%',
        ar: 'جارٍ التنزيل… {{percent}}%',
        it: 'Download in corso… {{percent}}%',
        'en-GB': 'Downloading… {{percent}}%',
        pt: 'Baixando… {{percent}}%',
        hi: 'डाउनलोड हो रहा है… {{percent}}%',
        tr: 'İndiriliyor… {{percent}}%',
        pl: 'Pobieranie… {{percent}}%',
        id: 'Mengunduh… {{percent}}%',
        vi: 'Đang tải… {{percent}}%',
        uk: 'Завантаження… {{percent}}%',
      })
    ),

    updateReadyToInstall: t({
      en: 'Update ready to install',
      fr: 'Mise à jour prête à être installée',
      ru: 'Обновление готово к установке',
      ja: 'アップデートのインストール準備が完了しました',
      ko: '업데이트를 설치할 준비가 되었습니다',
      zh: '更新已准备好安装',
      es: 'Actualización lista para instalar',
      de: 'Update bereit zur Installation',
      ar: 'التحديث جاهز للتثبيت',
      it: "Aggiornamento pronto per l'installazione",
      'en-GB': 'Update ready to install',
      pt: 'Atualização pronta para instalar',
      hi: 'अपडेट इंस्टॉल करने के लिए तैयार है',
      tr: 'Güncelleme yüklemeye hazır',
      pl: 'Aktualizacja gotowa do instalacji',
      id: 'Pembaruan siap dipasang',
      vi: 'Bản cập nhật đã sẵn sàng để cài đặt',
      uk: 'Оновлення готове до інсталяції',
    }),

    restartIntlayerToApplyThe: t({
      en: 'Restart Intlayer to apply the update.',
      fr: 'Redémarrer Intlayer pour appliquer la mise à jour.',
      ru: 'Перезапустите Intlayer, чтобы применить обновление.',
      ja: 'アップデートを適用するにはIntlayerを再起動してください。',
      ko: '업데이트를 적용하려면 Intlayer를 재시작하세요.',
      zh: '重新启动 Intlayer 以应用更新。',
      es: 'Reinicie Intlayer para aplicar la actualización.',
      de: 'Starten Sie Intlayer neu, um das Update anzuwenden.',
      ar: 'أعد تشغيل Intlayer لتطبيق التحديث.',
      it: "Riavvia Intlayer per applicare l'aggiornamento.",
      'en-GB': 'Restart Intlayer to apply the update.',
      pt: 'Reinicie o Intlayer para aplicar a atualização.',
      hi: 'अपडेट लागू करने के लिए Intlayer को पुनरarंभ करें।',
      tr: "Güncellemeyi uygulamak için Intlayer'ı yeniden başlatın.",
      pl: 'Uruchom ponownie Intlayer, aby zastosować aktualizację.',
      id: 'Mulai ulang Intlayer untuk menerapkan pembaruan.',
      vi: 'Khởi động lại Intlayer để áp dụng bản cập nhật.',
      uk: 'Перезапустіть Intlayer, щоб застосувати оновлення.',
    }),

    restartAndInstall: t({
      en: 'Restart and install',
      fr: 'Redémarrer et installer',
      ru: 'Перезапустить и установить',
      ja: '再起動してインストール',
      ko: '재시작 및 설치',
      zh: '重启并安装',
      es: 'Reiniciar e instalar',
      de: 'Neu starten und installieren',
      ar: 'إعادة التشغيل والتثبيت',
      it: 'Riavvia e installa',
      'en-GB': 'Restart and install',
      pt: 'Reiniciar e instalar',
      hi: 'पुनरारंभ करें और इंस्टॉल करें',
      tr: 'Yeniden başlat ve yükle',
      pl: 'Uruchom ponownie i zainstaluj',
      id: 'Mulai ulang dan pasang',
      vi: 'Khởi động lại và cài đặt',
      uk: 'Перезапустити та інсталювати',
    }),

    restartInstall: t({
      en: 'Restart & install',
      fr: 'Redémarrer & installer',
      ru: 'Перезапуск и установка',
      ja: '再起動＆インストール',
      ko: '재시작 & 설치',
      zh: '重启 & 安装',
      es: 'Reiniciar e instalar',
      de: 'Neu starten & installieren',
      ar: 'إعادة التشغيل والتثبيت',
      it: 'Riavvia & installa',
      'en-GB': 'Restart & install',
      pt: 'Reiniciar & instalar',
      hi: 'पुनरारंभ और इंस्टॉल करें',
      tr: 'Yeniden başlat & yükle',
      pl: 'Restart i instalacja',
      id: 'Mulai ulang & pasang',
      vi: 'Khởi động lại & cài đặt',
      uk: 'Перезапуск та інсталяція',
    }),

    updateErrorMessage: insert(
      t({
        en: 'Update error: {{message}}',
        fr: 'Erreur de mise à jour : {{message}}',
        ru: 'Ошибка обновления: {{message}}',
        ja: 'アップデートエラー: {{message}}',
        ko: '업데이트 오류: {{message}}',
        zh: '更新错误: {{message}}',
        es: 'Error de actualización: {{message}}',
        de: 'Update-Fehler: {{message}}',
        ar: 'خطأ في التحديث: {{message}}',
        it: 'Errore di aggiornamento: {{message}}',
        'en-GB': 'Update error: {{message}}',
        pt: 'Erro de atualização: {{message}}',
        hi: 'अपडेट त्रुटि: {{message}}',
        tr: 'Güncelleme hatası: {{message}}',
        pl: 'Błąd aktualizacji: {{message}}',
        id: 'Kesalahan pembaruan: {{message}}',
        vi: 'Lỗi cập nhật: {{message}}',
        uk: 'Помилка оновлення: {{message}}',
      })
    ),
  },
} satisfies Dictionary;

export default electronUpdaterContent;
