import { type Dictionary, insert, t } from 'intlayer';

const dictionaryFormContent = {
  key: 'dictionary-list',
  content: {
    searchPlaceholder: t({
      ar: 'قاموس 검색',
      de: 'Wörterbuch suchen',
      en: 'Search for a dictionary',
      'en-GB': 'Search for a dictionary',
      es: 'Buscar un diccionario',
      fr: 'Rechercher un dictionnaire',
      hi: 'शब्दकोश खोजें',
      it: 'Cerca un dizionario',
      ja: '辞書を検索',
      ko: '사전 검색',
      pt: 'Pesquisar um dicionário',
      ru: 'Найти словарь',
      tr: 'Sözlük arama',
      zh: '搜索字典',
      pl: 'Wyszukaj słownik',
      id: 'Cari kamus',
      vi: 'Tìm kiếm từ điển',
    }),

    selectDictionaryButton: {
      label: t({
        en: 'Click to select a dictionary',
        fr: 'Cliquez pour sélectionner un dictionnaire',
        es: 'Haga clic para seleccionar un diccionario',
        'en-GB': 'Click to select a dictionary',
        de: 'Klicken Sie, um ein Wörterbuch auszuwählen',
        ja: '辞書を選択するにはクリックしてください',
        ko: '사전을 선택하려면 클릭하세요',
        zh: '单击以选择字典',
        it: 'Clicca per selezionare un dizionario',
        pt: 'Clique para selecionar um dicionário',
        hi: 'शब्दकोश का चयन करने के लिए क्लिक करें',
        ar: 'اضغط لتحديد قاموس',
        ru: 'Нажмите, чтобы выбрать словарь',
        tr: 'Bir sözlük seçmek için tıklayın',
        pl: 'Kliknij, aby wybrać słownik',
        id: 'Klik untuk memilih kamus',
        vi: 'Nhấp để chọn một từ điển',
      }),
    },

    noDictionaries: t({
      en: 'No dictionaries found',
      fr: 'Aucun dictionnaire trouvé',
      es: 'No se encontraron diccionarios',
      'en-GB': 'No dictionaries found',
      de: 'Keine Wörterbücher gefunden',
      ja: '辞書が見つかりませんでした',
      ko: '사전을 찾을 수 없습니다',
      zh: '未找到字典',
      it: 'Nessun dizionario trovato',
      pt: 'Nenhum dicionário encontrado',
      hi: 'कोई शब्दकोश नहीं मिला',
      ar: 'لم يتم العثور على قواميس',
      ru: 'Словари не найдены',
      tr: 'Sözlük bulunamadı',
      pl: 'Nie znaleziono słowników',
      id: 'Tidak ada kamus yang ditemukan',
      vi: 'Không tìm thấy từ điển',
    }),

    saveAllButton: {
      label: t({
        en: 'Save all dictionaries',
        fr: 'Enregistrer tous les dictionnaires',
        es: 'Guardar todos los diccionarios',
        'en-GB': 'Save all dictionaries',
        de: 'Alle Wörterbücher speichern',
        ar: 'حفظ جميع القواميس',
        hi: 'सभी शब्दकोश सहेजें',
        it: 'Salva tutti i dizionari',
        ja: 'すべての辞書を保存',
        ko: '모든 사전 저장',
        pt: 'Salvar todos os dicionários',
        ru: 'Сохранить все словари',
        tr: 'Tüm sözlükleri kaydet',
        zh: '保存所有字典',
        pl: 'Zapisz wszystkie słowniki',
        id: 'Simpan semua kamus',
        vi: 'Lưu tất cả từ điển',
      }),
      text: insert(
        t({
          en: 'Save all ({{count}})',
          fr: 'Tout enregistrer ({{count}})',
          es: 'Guardar todo ({{count}})',
          'en-GB': 'Save all ({{count}})',
          de: 'Alle speichern ({{count}})',
          ar: 'حفظ الكل ({{count}})',
          hi: 'सभी सहेजें ({{count}})',
          it: 'Salva tutto ({{count}})',
          ja: 'すべて保存 ({{count}})',
          ko: '모두 저장 ({{count}})',
          pt: 'Salvar tudo ({{count}})',
          ru: 'Сохранить все ({{count}})',
          tr: 'Tümünü kaydet ({{count}})',
          zh: '保存全部 ({{count}})',
          pl: 'Zapisz wszystko ({{count}})',
          id: 'Simpan semua ({{count}})',
          vi: 'Lưu tất cả ({{count}})',
        })
      ),
    },
    restoreAllButton: {
      label: t({
        en: 'Restore all dictionaries',
        fr: 'Restaurer tous les dictionnaires',
        es: 'Restaurar todos los diccionarios',
        'en-GB': 'Restore all dictionaries',
        de: 'Alle Wörterbücher wiederherstellen',
        ar: 'استعادة جميع القواميس',
        hi: 'सभी शब्दकोश पुनर्स्थापित करें',
        it: 'Ripristina tutti i dizionari',
        ja: 'すべての辞書を復元',
        ko: '모든 사전 복원',
        pt: 'Restaurar todos os dicionários',
        ru: 'Восстановить все словари',
        tr: 'Tüm sözlükleri geri yükle',
        zh: '恢复所有字典',
        pl: 'Przywróć wszystkie słowniki',
        id: 'Pulihkan semua kamus',
        vi: 'Khôi phục tất cả từ điển',
      }),
      text: t({
        en: 'Restore all',
        fr: 'Tout restaurer',
        es: 'Restaurar todo',
        'en-GB': 'Restore all',
        de: 'Alle wiederherstellen',
        ar: 'استعادة الكل',
        hi: 'सभी पुनर्स्थापित करें',
        it: 'Ripristina tutto',
        ja: 'すべて復元',
        ko: '모두 복원',
        pt: 'Restaurar tudo',
        ru: 'Восстановить все',
        tr: 'Tümünü geri yükle',
        zh: '恢复全部',
        pl: 'Przywróć wszystko',
        id: 'Pulihkan semua',
        vi: 'Khôi phục tất cả',
      }),
    },
    saveDictionaryButton: {
      label: t({
        en: 'Save dictionary',
        fr: 'Enregistrer le dictionnaire',
        es: 'Guardar diccionario',
        'en-GB': 'Save dictionary',
        de: 'Wörterbuch speichern',
        ar: 'حفظ القاموس',
        hi: 'शब्दकोश सहेजें',
        it: 'Salva dizionario',
        ja: '辞書を保存',
        ko: '사전 저장',
        pt: 'Salvar dicionário',
        ru: 'Сохранить словарь',
        tr: 'Sözlüğü kaydet',
        zh: '保存字典',
        pl: 'Zapisz słownik',
        id: 'Simpan kamus',
        vi: 'Lưu từ điển',
      }),
    },
    restoreDictionaryButton: {
      label: t({
        en: 'Restore dictionary',
        fr: 'Restaurer le dictionnaire',
        es: 'Restaurar diccionario',
        'en-GB': 'Restore dictionary',
        de: 'Wörterbuch wiederherstellen',
        ar: 'استعادة القاموس',
        hi: 'शब्दकोश पुनर्स्थापित करें',
        it: 'Ripristina dizionario',
        ja: '辞書を復元',
        ko: '사전 복원',
        pt: 'Restaurar dicionário',
        ru: 'Восстановить словарь',
        tr: 'Sözlüğü geri yükle',
        zh: '恢复字典',
        pl: 'Przywróć słownik',
        id: 'Pulihkan kamus',
        vi: 'Khôi phục từ điển',
      }),
    },
    modifiedCount: insert(
      t({
        en: '{{count}} Modified',
        fr: '{{count}} Modifié',
        es: '{{count}} Modificado',
        'en-GB': '{{count}} Modified',
        de: '{{count}} Geändert',
        ar: '{{count}} معدل',
        hi: '{{count}} संशोधित',
        it: '{{count}} Modificato',
        ja: '{{count}} 変更済み',
        ko: '{{count}} 수정됨',
        pt: '{{count}} Modificado',
        ru: '{{count}} Изменено',
        tr: '{{count}} Değiştirildi',
        zh: '{{count}} 已修改',
        pl: '{{count}} Zmodyfikowano',
        id: '{{count}} Dimodifikasi',
        vi: '{{count}} Đã sửa đổi',
      })
    ),
  },
  title: 'Dictionary list dashboard',
  description:
    'UI content for the dashboard section listing available dictionaries. Includes search placeholder and dictionary selection button.',
  tags: ['dashboard', 'dictionary'],
} satisfies Dictionary;

export default dictionaryFormContent;
