import { type Dictionary, md, t } from 'intlayer';

const aiAbTestingSectionContent = {
  key: 'ai-ab-testing-section',
  content: {
    betaTag: t({
      ar: 'اختبار AB',
      de: 'AB-Testing',
      en: 'AB testing',
      'en-GB': 'AB testing',
      es: 'AB testing',
      fr: 'AB testing',
      hi: 'AB testing',
      it: 'AB testing',
      ja: 'ABテスト',
      ko: 'AB 테스트',
      pt: 'AB testing',
      ru: 'AB тестирование',
      tr: 'AB testing',
      zh: 'AB测试',
      pl: 'AB testing',
      id: 'AB testing',
      vi: 'Kiểm thử AB',
      uk: 'A/B-тестування',
    }),
    title: t({
      ar: 'ملعبك لتجارب المنتجات.',
      de: 'Ihr Spielplatz für Produktexperimente.',
      en: 'Your Playground for Product Experiments.',
      'en-GB': 'Your Playground for Product Experiments.',
      es: 'Tu campo de juego para experimentos de producto.',
      fr: 'Votre terrain de jeu pour les expérimentations produit.',
      hi: 'उत्पाद प्रयोगों के लिए आपका खेल का मैदान।',
      it: 'Il tuo parco giochi per esperimenti di prodotto.',
      ja: 'プロダクト実験のためのプレイグラウンド。',
      ko: '제품 실험을 위한 플레이그라운드.',
      pt: 'Seu playground para experimentos de produto.',
      ru: 'Ваша площадка для экспериментов с продуктом.',
      tr: 'Ürün Deneyleri için Playground.',
      zh: '您的产品实验演练场。',
      pl: 'Twoje pole do eksperymentów produktowych.',
      id: 'Area Eksperimen Produk Anda.',
      vi: 'Sân chơi để thử nghiệm sản phẩm của bạn.',
      uk: 'Ваш майданчик для продуктових експериментів.',
    }),
    description: md(
      t({
        ar: 'كن أول من يستكشف نسخة تجريبية جديدة من **A/B Testing** المدعوم بالذكاء الاصطناعي من Intlayer، والمصممة لتعزيز قابلية الاكتشاف وتوجيه قرارات المنتج الأكثر ذكاءً. اختبر أي شيء في الوقت الفعلي، من النسخ والتصميم إلى الميزات الكاملة، ودع البيانات تظهر لك ما يعمل حقًا.',
        de: 'Seien Sie die Ersten, die Intlayers neue KI-gestützte A/B-Testing-Beta erkunden, die entwickelt wurde, um die Auffindbarkeit zu steigern und intelligentere Produktentscheidungen zu leiten. Testen Sie alles in Echtzeit, von Texten und Design bis hin zu ganzen Features, und lassen Sie die Daten zeigen, was wirklich funktioniert.',
        en: "Be the first to explore Intlayer's new **AI-driven A/B Testing** beta, built to boost discoverability and guide smarter product decisions. Test anything in real time, from copy and design to entire features, and let the data show you what truly works.",
        'en-GB':
          "Be the first to explore Intlayer's new **AI-driven A/B Testing** beta, built to boost discoverability and guide smarter product decisions. Test anything in real time, from copy and design to entire features, and let the data show you what truly works.",
        es: 'Sé el primero en explorar la nueva beta de **A/B Testing impulsado por IA** de Intlayer, diseñada para impulsar la descubribilidad y guiar decisiones de producto más inteligentes. Prueba cualquier cosa en tiempo real, desde copy y diseño hasta funciones completas, y deja que los datos te muestren lo que realmente funciona.',
        fr: "Soyez les premiers à explorer la nouvelle version bêta d'**A/B Testing piloté par IA** d'Intlayer, conçue pour améliorer la découvrabilité et guider des décisions produit plus intelligentes. Testez tout en temps réel, du contenu et du design aux fonctionnalités complètes, et laissez les données vous montrer ce qui fonctionne vraiment.",
        hi: 'Intlayer के नए **AI-संचालित A/B टेस्टिंग** बीटा का पता लगाने वाले पहले व्यक्ति बनें, जो खोज योग्यता बढ़ाने और स्मार्ट उत्पाद निर्णयों का मार्गदर्शन करने के लिए बनाया गया है। कॉपी और डिज़ाइन से लेकर पूरे फीचर्स तक, रियल टाइम में कुछ भी टेस्ट करें, और डेटा को दिखाने दें कि वास्तव में क्या काम करता है।',
        id: 'Jadilah yang pertama menjelajahi beta baru Intlayer untuk **AI-driven A/B Testing**, yang dibuat untuk meningkatkan discoverability dan membantu pengambilan keputusan produk yang lebih cerdas. Uji apa saja secara real time, mulai dari teks dan desain hingga fitur lengkap, dan biarkan data menunjukkan apa yang benar-benar berhasil.',
        it: "Sii il primo a esplorare la nuova beta di A/B Testing guidato dall'IA di Intlayer, costruita per aumentare la scopribilità e guidare decisioni di prodotto più intelligenti. Testa qualsiasi cosa in tempo reale, dai copy e design alle funzionalità complete, e lascia che i dati ti mostrino cosa funziona davvero.",
        ja: 'Intlayerの新しい**AI搭載A/Bテストベータ**を最初に体験してください。発見可能性を高め、よりスマートな製品決定を導くために構築されました。コピーやデザインから機能全体まで、リアルタイムで何でもテストし、データに本当に効果的なものを示してもらいましょう。',
        ko: 'Intlayer의 새로운 **AI 기반 A/B 테스트 베타**를 가장 먼저 탐험해보세요. 발견 가능성을 높이고 더 스마트한 제품 결정을 안내하도록 구축되었습니다. 카피와 디자인부터 전체 기능까지 실시간으로 무엇이든 테스트하고, 데이터가 진정으로 작동하는 것을 보여주도록 하세요.',
        pl: 'Bądź pierwszym, który wypróbuje nową wersję beta **AI-driven A/B Testing** od Intlayera — stworzoną, aby zwiększyć odkrywalność i wspierać mądrzejsze decyzje produktowe. Testuj wszystko w czasie rzeczywistym: od treści i projektu po całe funkcje, i pozwól danym pokazać, co naprawdę działa.',
        pt: 'Seja o primeiro a explorar a nova beta de A/B Testing orientado por IA da Intlayer, construída para aumentar a descoberta e orientar decisões de produto mais inteligentes. Teste qualquer coisa em tempo real, desde copy e design até recursos completos, e deixe os dados mostrarem o que realmente funciona.',
        ru: 'Станьте первыми, кто исследует новую бета-версию **A/B-тестирования на базе ИИ** от Intlayer, созданную для повышения обнаруживаемости и направления более умных решений по продукту. Тестируйте что угодно в реальном времени, от текстов и дизайна до целых функций, и позвольте данным показать вам, что действительно работает.',
        tr: "Intlayer'ın yeni **Yapay Zeka destekli A/B Testi** beta sürümünü keşfeden ilk kişi olun. Keşfedilebilirliği artırmak ve daha akıllı ürün kararlarına rehberlik etmek için tasarlandı. Kopya ve tasarımdan tüm özelliklere kadar her şeyi gerçek zamanlı olarak test edin ve verilerin gerçekten neyin işe yaradığını göstermesine izin verin.",
        uk: 'Станьте першими, хто дослідить нову бета-версію Intlayer — **A/B-тестування на базі ШІ**, створену, щоб підвищити видимість і допомогти приймати розумніші продуктові рішення. Тестуйте будь-що в реальному часі — від текстів і дизайну до цілих функцій — і дозвольте даним показати, що справді працює.',
        vi: 'Hãy là người đầu tiên khám phá bản Beta mới của Intlayer: **AI-driven A/B Testing**, được xây dựng để tăng khả năng hiển thị và định hướng những quyết định sản phẩm thông minh hơn. Thử nghiệm mọi thứ theo thời gian thực, từ nội dung (copy) và thiết kế đến toàn bộ tính năng, và để dữ liệu cho bạn thấy điều gì thực sự hiệu quả.',
        zh: '成为第一批探索 Intlayer 新 **AI 驱动 A/B 测试**测试版的用户，该版本旨在提升可发现性并指导更明智的产品决策。从文案和设计到整个功能，实时测试任何内容，让数据告诉您什么真正有效。',
      })
    ),
    ctaButton: {
      label: t({
        en: 'Learn more about the *AI A/B Testing feature (opens in new tab)',
        'en-GB':
          'Learn more about the *AI A/B Testing feature (opens in new tab)',
        fr: "En savoir plus sur la fonctionnalité A/B Testing IA (s'ouvre dans un nouvel onglet)",
        es: 'Conoce más sobre la función de A/B Testing con IA (se abre en nueva pestaña)',
        de: 'Erfahren Sie mehr über die KI A/B-Testing-Funktion (öffnet in neuem Tab)',
        ja: '*AI A/Bテスト機能について詳しく学ぶ（新しいタブで開きます）',
        ko: '*AI A/B 테스트 기능에 대해 자세히 알아보기 (새 탭에서 열림)',
        zh: '了解更多 *AI A/B 测试功能（在新标签页中打开）',
        it: 'Scopri di più sulla funzione *AI A/B Testing (si apre in una nuova scheda)',
        pt: 'Saiba mais sobre o recurso de A/B Testing com IA (abre em nova aba)',
        hi: '*AI A/B टेस्टिंग फीचर के बारे में और जानें (नए टैब में खुलता है)',
        ar: 'تعرف على المزيد حول ميزة اختبار A/B بالذكاء الاصطناعي (يفتح في علامة تبويب جديدة)',
        ru: 'Узнайте больше о функции *AI A/B Testing (открывается в новой вкладке)',
        tr: '*Yapay Zeka A/B Testi özelliği hakkında daha fazla bilgi edinin (yeni sekmede açılır)',
        pl: 'Dowiedz się więcej o funkcji *AI A/B Testing (otworzy się w nowej karcie)',
        id: 'Pelajari lebih lanjut tentang fitur AI A/B Testing (buka di tab baru)',
        vi: 'Tìm hiểu thêm về tính năng *AI A/B Testing* (mở trong tab mới)',
        uk: 'Дізнатися більше про *функцію A/B-тестування на базі ШІ (відкривається в новій вкладці)',
      }),
      text: t({
        en: 'See A/B test',
        'en-GB': 'See A/B test',
        fr: 'Voir test A/B',
        es: 'Ver prueba A/B',
        de: 'A/B-Test ansehen',
        ja: 'A/Bテストを見る',
        ko: 'A/B 테스트 보기',
        zh: '查看 A/B 测试',
        it: 'Vedi test A/B',
        pt: 'Ver teste A/B',
        hi: 'A/B टेस्ट देखें',
        ar: 'شاهد اختبار A/B',
        ru: 'Смотреть A/B тест',
        tr: 'A/B Testi gör',
        pl: 'Zobacz test A/B',
        id: 'Lihat uji A/B',
        vi: 'Xem thử nghiệm A/B',
        uk: 'Переглянути A/B-тест',
      }),
    },
  },
  title: 'AI A/B Testing section',
  description:
    'Content declaration for the AI-driven A/B Testing section on the landing page. Highlights beta availability, feature presentation, and CTA for further exploration. Aimed at encouraging user experimentation and data-driven product optimization.',
  tags: ['landing page', 'feature section', 'AI A/B testing'],
} satisfies Dictionary;

export default aiAbTestingSectionContent;
