import { t, type DeclarationContent } from 'intlayer';

const chatFormSectionContent = {
  key: 'chat-form-section',
  content: {
    textArea: {
      label: t({
        en: 'Ask your question to our AI-Powered Smart Documentation',
        'en-GB': 'Ask your question to our AI-Powered Smart Documentation',
        fr: 'Posez votre question à notre documentation intelligente',
        es: 'Pregúntale a nuestra documentación inteligente',
        de: 'Stellen Sie Ihre Frage zu unserer intelligenten Dokumentation',
        ja: '私たちのAIドキュメントに問い合わせる',
        ko: '우리의 AI 스마트 문서에 문의하세요',
        zh: '请向我们的AI智能文档发出问题',
        it: 'Fai una domanda alla nostra documentazione intelligente',
        pt: 'Faça uma pergunta para nossa documentação inteligente',
        hi: 'हमारे एआई-पॉयटेड स्मार्ट दस्तावेज़ के लिए अपनी प्रश्न करें',
        ar: 'طرح سؤالك لدردشة الوثائق الخاصة بنا AI',
        ru: 'Спросите нашу умную документацию',
      }),
      placeholder: t({
        en: 'Ask me anything...',
        'en-GB': 'Ask me anything...',
        fr: 'Posez-moi quelque chose...',
        es: 'Pregúntame algo...',
        de: 'Stellen Sie mir irgendwas...',
        ja: '私たちに何か質問してください...',
        ko: '무엇을 물어보세요...',
        zh: '问我任何事情...',
        it: 'Fai qualcosa...',
        pt: 'Faça algo...',
        hi: 'कुछ प्रश्न करें...',
        ar: 'طرح شيئا...',
        ru: 'Спросите меня что-нибудь...',
      }),
    },
    sendQuestionButton: {
      text: t({
        en: 'Send',
        'en-GB': 'Send',
        fr: 'Envoyer',
        es: 'Enviar',
        de: 'Senden',
        ja: '送信',
        ko: '보내기',
        zh: '发送',
        it: 'Invia',
        pt: 'Enviar',
        hi: 'भेजें',
        ar: 'إرسال',
        ru: 'Отправить',
      }),
      label: t({
        en: 'Click to send question',
        'en-GB': 'Click to send question',
        fr: 'Cliquez pour envoyer la question',
        es: 'Haga clic para enviar la pregunta',
        de: 'Klicken Sie, um die Frage zu senden',
        ja: '質問を送信するにはクリックしてください',
        ko: '질문을 보내려면 클릭하세요',
        zh: '点击发送问题',
        it: 'Clicca per inviare la domanda',
        pt: 'Clique para enviar a pergunta',
        hi: 'प्रश्न भेजने के लिए क्लिक करें',
        ar: 'انقر لإرسال السؤال',
        ru: 'Нажмите, чтобы отправить вопрос',
      }),
    },
    clearButton: {
      label: t({
        en: 'Click to clear',
        'en-GB': 'Click to clear',
        fr: 'Cliquez pour effacer',
        es: 'Haga clic para borrar',
        de: 'Klicken Sie, um zu löschen',
        ja: 'クリアするにはクリックしてください',
        ko: '지우려면 클릭하세요',
        zh: '点击清除',
        it: 'Clicca per cancellare',
        pt: 'Clique para limpar',
        hi: 'साफ़ करने के लिए क्लिक करें',
        ar: 'انقر لمسح',
        ru: 'Нажмите, чтобы очистить',
      }),
      text: t({
        en: 'Clear',
        'en-GB': 'Clear',
        fr: 'Effacer',
        es: 'Borrar',
        de: 'Löschen',
        ja: 'クリア',
        ko: '지우기',
        zh: '清除',
        it: 'Cancella',
        pt: 'Limpar',
        hi: 'साफ़ करें',
        ar: 'مسح',
        ru: 'Очистить',
      }),
    },
  },
} satisfies DeclarationContent;

export default chatFormSectionContent;
