import { type Dictionary, t } from 'intlayer';

const chatFormSectionContent = {
  key: 'chat',
  content: {
    firstMessageContent: {
      role: 'system',
      content: t({
        en: "Hey! Ask me anything and I'll try to answer it.",
        'en-GB': "Hey! Ask me anything and I'll try to answer it.",
        fr: 'Hey! Posez-moi quelque chose et je vais répondre.',
        es: '¡Hola! Pregúntame algo y te ayudaré.',
        de: 'Hallo! Stell mir irgendwas und ich werde es beantworten.',
        ja: 'こんにちは！お好きなものを聞いてください。',
        ko: '안녕하세요! 무엇을 물어보세요.',
        zh: '你好！问我任何事情，我会尽力回答。',
        it: 'Ciao! Fai qualcosa e ti aiuterò.',
        pt: 'Olá! Faça uma pergunta e eu responderei.',
        hi: 'नमस्ते! कुछ प्रश्न करें और मुझे उत्तर देंगे।',
        ar: 'مرحبا! اسمح لي بسؤال وسأقوم بالإجابة.',
        ru: 'Привет! Спросите меня что-нибудь и я помогу тебе.',
        tr: 'Hey! Bana bir şey sor ve cevaplamaya çalışayım.',
        pl: 'Cześć! Zapytaj mnie o cokolwiek, a postaram się odpowiedzieć.',
        id: 'Hai! Tanyakan apa saja dan saya akan mencoba menjawabnya.',
        vi: 'Chào! Hỏi tôi bất cứ điều gì và tôi sẽ cố gắng trả lời.',
        uk: 'Привіт! Запитай мене про що завгодно, і я спробую відповісти.',
      }),
    },
    rateLimitExceededMessage: t({
      ar: 'عدد الطلبات محدود للمستخدمين غير المصرح لهم. يرجى المحاولة مرة أخرى لاحقًا، أو تسجيل الدخول لزيادة الحد وفتح المزيد من المودلات.',
      de: 'Die Anzahl der Anfragen ist für nicht authentifizierte Benutzer begrenzt. Bitte versuchen Sie es später erneut, oder melden Sie sich an, um Ihre Begrenzung zu erhöhen und bessere Modelle zu entsperren.',
      en: 'The number of requests is limited for unauthenticated users. Please try again later, or sign in to increase your limit and unlock better models.',
      'en-GB':
        'The number of requests is limited for unauthenticated users. Please try again later, or sign in to increase your limit and unlock better models.',
      es: 'El número de solicitudes está limitado para usuarios no autenticados. Por favor, inténtelo de nuevo más tarde, o inicie sesión para aumentar su límite y desbloquear mejores modelos.',
      fr: 'Le nombre de requêtes est limité pour les utilisateurs non authentifiés. Veuillez réessayer plus tard, ou connectez-vous pour augmenter votre limite et débloquer de meilleurs modèles.',
      hi: 'अनुमोदित उपयोगकर्ताओं के लिए अनुरोधों की संख्या सीमित है। कृपया बाद में पुनः प्रयास करें, या लॉग इन करके सीमा बढ़ाएं और बेहतर मॉडल खोलें।',
      it: 'Il numero di richieste è limitato per gli utenti non autenticati. Per favore, riprova più tardi, o accedi per aumentare il limite e sbloccare modelli migliori.',
      ja: '非認証ユーザーのリクエスト数は制限されています。後でもう一度お試しください、またはログインして制限を増やしてください。',
      ko: '인증되지 않은 사용자의 요청 수는 제한되어 있습니다. 나중에 다시 시도하거나 로그인하여 제한을 늘리세요.',
      pt: 'O número de solicitações é limitado para usuários não autenticados. Por favor, tente novamente mais tarde, ou faça login para aumentar seu limite e desbloquear modelos melhores.',
      ru: 'Количество запросов ограничено для неавторизованных пользователей. Пожалуйста, попробуйте снова позже, или войдите для увеличения лимита и открытия лучших моделей.',
      tr: 'Kimliği doğrulanmamış kullanıcılar için istek sayısı sınırlıdır. Lütfen daha sonra tekrar deneyin veya sınırınızı artırmak ve daha iyi modelleri açmak için giriş yapın.',
      zh: '未认证用户的请求数有限。请稍后再试，或登录以增加您的限制。',
      pl: 'Liczba żądań jest ograniczona dla niezalogowanych użytkowników. Spróbuj ponownie później lub zaloguj się, aby zwiększyć limit i uzyskać dostęp do lepszych modeli.',
      id: 'Jumlah permintaan dibatasi untuk pengguna yang belum diautentikasi. Silakan coba lagi nanti, atau masuk untuk meningkatkan batas Anda dan membuka akses ke models yang lebih baik.',
      vi: 'Số lượng yêu cầu bị giới hạn đối với người dùng chưa xác thực. Vui lòng thử lại sau, hoặc đăng nhập để tăng giới hạn của bạn và mở khóa các mô hình tốt hơn.',
      uk: 'Кількість запитів обмежена для неавторизованих користувачів. Спробуйте пізніше або увійдіть у систему, щоб збільшити ліміт і отримати доступ до кращих моделей.',
    }),
    signInButton: {
      text: t({
        en: 'Sign in',
        'en-GB': 'Sign in',
        fr: 'Se connecter',
        es: 'Iniciar sesión',
        de: 'Anmelden',
        ja: 'ログイン',
        ko: '로그인',
        zh: '登录',
        it: 'Accedi',
        pt: 'Fazer login',
        hi: 'लॉग इन',
        ar: 'تسجيل الدخول',
        ru: 'Войти',
        tr: 'Giriş yap',
        pl: 'Zaloguj się',
        id: 'Masuk',
        vi: 'Đăng nhập',
        uk: 'Увійти',
      }),
      label: t({
        en: 'Go to login page',
        'en-GB': 'Go to login page',
        fr: 'Aller à la page de connexion',
        es: 'Ir a la página de inicio de sesión',
        de: 'Zur Anmeldeseite gehen',
        ja: 'ログインページに移動',
        ko: '로그인 페이지로 이동',
        zh: '前往登录页面',
        it: 'Vai alla pagina di login',
        pt: 'Ir para a página de login',
        hi: 'लॉग इन पेज पर जाएं',
        ar: 'الذهاب إلى صفحة التسجيل',
        ru: 'Перейти на страницу входа',
        tr: 'Giriş sayfasına git',
        pl: 'Przejdź do strony logowania',
        id: 'Pergi ke halaman login',
        vi: 'Đi tới trang đăng nhập',
        uk: 'Перейти на сторінку входу',
      }),
    },
    disclaimerNote: t({
      en: 'Discussions are anonymous and regularly reviewed to address common issues. Feel free to share feature ideas, feedback on the documentation, or anything related to Intlayer — we use this input to shape our roadmap and improve the product.',
      'en-GB':
        'Discussions are anonymous and regularly reviewed to address common issues. Feel free to share feature ideas, feedback on the documentation, or anything related to Intlayer — we use this input to shape our roadmap and improve the product.',
      fr: "Les discussions sont anonymes et régulièrement analysées pour traiter les problèmes fréquents. N'hésitez pas à partager vos idées de fonctionnalités, vos retours sur la documentation ou tout ce qui concerne Intlayer — nous utilisons ces retours pour construire notre roadmap et améliorer le produit.",
      es: 'Las conversaciones son anónimas y se revisan regularmente para abordar problemas comunes. No dudes en compartir ideas de funcionalidades, comentarios sobre la documentación o cualquier cosa relacionada con Intlayer — usamos esta información para definir nuestra hoja de ruta y mejorar el producto.',
      de: 'Diskussionen sind anonym und werden regelmäßig überprüft, um häufige Probleme zu behandeln. Teilen Sie gerne Feature-Ideen, Feedback zur Dokumentation oder alles rund um Intlayer — wir nutzen diese Eingaben, um unsere Roadmap zu gestalten und das Produkt zu verbessern.',
      ja: 'ディスカッションは匿名で、よくある問題に対処するために定期的に確認されます。機能のアイデア、ドキュメントへのフィードバック、Intlayerに関することなど、お気軽にお聞かせください — このフィードバックをロードマップの作成と製品の改善に活用しています。',
      ko: '토론은 익명이며 일반적인 문제를 해결하기 위해 정기적으로 검토됩니다. 기능 아이디어, 문서에 대한 피드백 또는 Intlayer와 관련된 모든 것을 자유롭게 공유하세요 — 이 의견을 로드맵 구성과 제품 개선에 활용합니다.',
      zh: '讨论是匿名的，并会定期审查以解决常见问题。欢迎分享功能想法、对文档的反馈或任何与 Intlayer 相关的内容 — 我们会利用这些意见来制定路线图并改进产品。',
      it: 'Le discussioni sono anonime e vengono regolarmente esaminate per affrontare problemi comuni. Sentiti libero di condividere idee per nuove funzionalità, feedback sulla documentazione o qualsiasi cosa relativa a Intlayer — utilizziamo questi input per definire la nostra roadmap e migliorare il prodotto.',
      pt: 'As discussões são anônimas e regularmente revisadas para resolver problemas comuns. Sinta-se à vontade para compartilhar ideias de funcionalidades, feedback sobre a documentação ou qualquer coisa relacionada ao Intlayer — usamos essas informações para moldar nosso roadmap e melhorar o produto.',
      hi: 'चर्चाएं गुमनाम हैं और सामान्य मुद्दों को संबोधित करने के लिए नियमित रूप से समीक्षा की जाती हैं। फीचर आइडिया, डॉक्यूमेंटेशन पर फीडबैक, या Intlayer से संबंधित कुछ भी साझा करने में संकोच न करें — हम इस इनपुट का उपयोग अपने रोडमैप को आकार देने और उत्पाद को बेहतर बनाने के लिए करते हैं।',
      ar: 'المناقشات مجهولة الهوية ويتم مراجعتها بانتظام لمعالجة المشكلات الشائعة. لا تتردد في مشاركة أفكار الميزات أو التعليقات على الوثائق أو أي شيء يتعلق بـ Intlayer — نستخدم هذه المدخلات لتشكيل خارطة الطريق وتحسين المنتج.',
      ru: 'Обсуждения анонимны и регулярно просматриваются для решения распространённых проблем. Не стесняйтесь делиться идеями функций, отзывами о документации или чем-либо, связанным с Intlayer — мы используем эту информацию для формирования нашей дорожной карты и улучшения продукта.',
      tr: 'Tartışmalar anonimdir ve yaygın sorunları ele almak için düzenli olarak incelenir. Özellik fikirleri, belgeleme hakkında geri bildirimler veya Intlayer ile ilgili herhangi bir şeyi paylaşmaktan çekinmeyin — bu girdileri yol haritamızı şekillendirmek ve ürünü geliştirmek için kullanıyoruz.',
      pl: 'Dyskusje są anonimowe i regularnie przeglądane w celu rozwiązania typowych problemów. Podziel się pomysłami na funkcje, opinią o dokumentacji lub czymkolwiek związanym z Intlayer — wykorzystujemy te informacje do kształtowania naszej mapy drogowej i ulepszania produktu.',
      id: 'Diskusi bersifat anonim dan ditinjau secara berkala untuk mengatasi masalah umum. Jangan ragu untuk berbagi ide fitur, masukan tentang dokumentasi, atau apa pun yang terkait dengan Intlayer — kami menggunakan masukan ini untuk membentuk peta jalan dan meningkatkan produk.',
      vi: 'Các cuộc thảo luận là ẩn danh và được xem xét thường xuyên để giải quyết các vấn đề phổ biến. Hãy thoải mái chia sẻ ý tưởng tính năng, phản hồi về tài liệu hoặc bất cứ điều gì liên quan đến Intlayer — chúng tôi sử dụng thông tin này để định hình lộ trình và cải thiện sản phẩm.',
      uk: 'Обговорення анонімні та регулярно переглядаються для вирішення поширених проблем. Не соромтеся ділитися ідеями функцій, відгуками про документацію або будь-чим, що стосується Intlayer — ми використовуємо цю інформацію для формування нашої дорожньої карти та покращення продукту.',
    }),
  },
  title: 'Chatbot component content',
  description:
    'Content declarations for the chatbot component, including system message, rate limit warning, and sign-in button labels used in the interactive assistant.',
  tags: ['chatbot', 'component content'],
} satisfies Dictionary;

export default chatFormSectionContent;
