import { type DeclarationContent, t } from 'intlayer';

const definePasswordStepContent = {
  key: 'define-password-step',
  content: {
    title: t({
      en: 'Define a password',
      'en-GB': 'Define a password',
      fr: 'Définissez un mot de passe',
      es: 'Defina una contraseña',
      de: 'Ein Passwort definieren',
      ja: 'パスワードを定義する',
      ko: '비밀번호 정의',
      zh: '定义密码',
      it: 'Definisci una password',
      pt: 'Defina uma senha',
      hi: 'एक पासवर्ड निर्दिष्ट करें',
      ar: 'حدد كلمة مرور',
      ru: 'Установить пароль',
    }),
    currentPasswordInput: {
      label: t({
        en: 'Current password',
        'en-GB': 'Current password',
        fr: 'Mot de passe actuel',
        es: 'Contraseña actual',
        de: 'Aktuelles Passwort',
        ja: '現在のパスワード',
        ko: '현재 비밀번호',
        zh: '当前密码',
        it: 'Password attuale',
        pt: 'Senha atual',
        hi: 'वर्तमान पासवर्ड',
        ar: 'كلمة المرور الحالية',
        ru: 'Текущий пароль',
      }),
      placeholder: t({
        en: 'Enter current password',
        'en-GB': 'Enter current password',
        fr: 'Entrez votre mot de passe actuel',
        es: 'Ingresa tu contraseña actual',
        de: 'Aktuelles Passwort eingeben',
        ja: '現在のパスワードを入力',
        ko: '현재 비밀번호를 입력',
        zh: '输入当前密码',
        it: 'Inserisci la password attuale',
        pt: 'Digite a senha atual',
        hi: 'वर्तमान पासवर्ड दर्ज करें',
        ar: 'أدخل كلمة المرور الحالية',
        ru: 'Введите текущий пароль',
      }),
    },
    newPasswordInput: {
      label: t({
        en: 'Password',
        'en-GB': 'Password',
        fr: 'Mot de passe',
        es: 'Contraseña',
        de: 'Passwort',
        ja: 'パスワード',
        ko: '비밀번호',
        zh: '密码',
        it: 'Password',
        pt: 'Senha',
        hi: 'पासवर्ड',
        ar: 'كلمة المرور',
        ru: 'Пароль',
      }),
      placeholder: t({
        en: 'Enter password',
        'en-GB': 'Enter password',
        fr: 'Entrez un mot de passe',
        es: 'Ingresa una contraseña',
        de: 'Passwort eingeben',
        ja: 'パスワードを入力',
        ko: '비밀번호를 입력',
        zh: '输入密码',
        it: 'Inserisci la password',
        pt: 'Digite a senha',
        hi: 'पासवर्ड दर्ज करें',
        ar: 'أدخل كلمة المرور',
        ru: 'Введите пароль',
      }),
    },
    confirmPasswordInput: {
      label: t({
        en: 'Confirm password',
        'en-GB': 'Confirm password',
        fr: 'Confirmez le mot de passe',
        es: 'Confirma tu contraseña',
        de: 'Passwort bestätigen',
        ja: 'パスワードを確認',
        ko: '비밀번호 확인',
        zh: '确认密码',
        it: 'Conferma password',
        pt: 'Confirme a senha',
        hi: 'पासवर्ड की पुष्टि करें',
        ar: 'تأكيد كلمة المرور',
        ru: 'Подтвердите пароль',
      }),
      placeholder: t({
        en: 'Confirm password',
        'en-GB': 'Confirm password',
        fr: 'Confirmez votre mot de passe',
        es: 'Confirma tu contraseña',
        de: 'Passwort bestätigen',
        ja: 'パスワードを確認',
        ko: '비밀번호를 확인',
        zh: '确认密码',
        it: 'Conferma password',
        pt: 'Confirme a senha',
        hi: 'पासवर्ड की पुष्टि करें',
        ar: 'تأكيد كلمة المرور',
        ru: 'Подтвердите пароль',
      }),
    },
  },
} satisfies DeclarationContent;

export default definePasswordStepContent;
