import { type Dictionary, t } from 'intlayer';

const definePasswordStepContent = {
  key: 'define-password-step',
  content: {
    title: t({
      ar: 'حدد كلمة مرور',
      de: 'Ein Passwort definieren',
      en: 'Define a password',
      'en-GB': 'Define a password',
      es: 'Defina una contraseña',
      fr: 'Définissez un mot de passe',
      hi: 'एक पासवर्ड निर्दिष्ट करें',
      it: 'Definisci una password',
      ja: 'パスワードを定義する',
      ko: '비밀번호 정의',
      pt: 'Defina uma senha',
      ru: 'Установить пароль',
      tr: 'Bir şifre belirleyin',
      zh: '定义密码',
      pl: 'Zdefiniuj hasło',
    }),

    newPasswordInput: {
      label: t({
        en: 'Password',
        'en-GB': 'Password',
        fr: 'Mot de passe',
        es: 'Contraseña',
        de: 'Passwort',
        ja: 'パスワード',
        ko: '비밀번호',
        zh: '密码',
        it: 'Password',
        pt: 'Senha',
        hi: 'पासवर्ड',
        ar: 'كلمة المرور',
        ru: 'Пароль',
        tr: 'Parola',
        pl: 'Hasło',
      }),
      placeholder: t({
        en: 'Enter password',
        'en-GB': 'Enter password',
        fr: 'Entrez un mot de passe',
        es: 'Ingresa una contraseña',
        de: 'Passwort eingeben',
        ja: 'パスワードを入力',
        ko: '비밀번호를 입력',
        zh: '输入密码',
        it: 'Inserisci la password',
        pt: 'Digite a senha',
        hi: 'पासवर्ड दर्ज करें',
        ar: 'أدخل كلمة المرور',
        ru: 'Введите пароль',
        tr: 'Parolayı girin',
        pl: 'Wprowadź hasło',
      }),
    },
    confirmPasswordInput: {
      label: t({
        en: 'Confirm password',
        'en-GB': 'Confirm password',
        fr: 'Confirmez le mot de passe',
        es: 'Confirma tu contraseña',
        de: 'Passwort bestätigen',
        ja: 'パスワードを確認',
        ko: '비밀번호 확인',
        zh: '确认密码',
        it: 'Conferma password',
        pt: 'Confirme a senha',
        hi: 'पासवर्ड की पुष्टि करें',
        ar: 'تأكيد كلمة المرور',
        ru: 'Подтвердите пароль',
        tr: 'Parolayı onayla',
        pl: 'Potwierdź hasło',
      }),
      placeholder: t({
        en: 'Confirm password',
        'en-GB': 'Confirm password',
        fr: 'Confirmez votre mot de passe',
        es: 'Confirma tu contraseña',
        de: 'Passwort bestätigen',
        ja: 'パスワードを確認',
        ko: '비밀번호를 확인',
        zh: '确认密码',
        it: 'Conferma password',
        pt: 'Confirme a senha',
        hi: 'पासवर्ड की पुष्टि करें',
        ar: 'تأكيد كلمة المرور',
        ru: 'Подтвердите пароль',
        tr: 'Parolayı onayla',
        pl: 'Potwierdź hasło',
      }),
    },
  },
  title: 'Define password step',
  description:
    'Content declaration for the step where users define and confirm their password during onboarding. Includes labels and placeholders for new and confirmation password inputs.',
  tags: ['onboarding', 'authentication', 'form step'],
} satisfies Dictionary;

export default definePasswordStepContent;
